### PR TITLE
[adc] Use new library with ESP-IDF v5

### LINKED ISSUE #2988: Allow ADC2 on ESP32 when Wifi is configured
**Describe the problem you have/What new integration you would like**

When allow_other_uses is set to true, configuring ADC2 should be allowed even if Wifi is configured

**Please describe your use case for this integration and alternatives you've tried:**

When the ESP32 is booting there's still chance to get the ADC reading before Wifi is started.
For example, on_boot with priority >250.0 will occur before Wifi initialized.

**Additional context**

I have project that will boot the every 10 minutes and enter sleeping mode after processing. I can read the ADC value on boot and send the value after wifi is connected.
Currently I can achieve it by using lambda template with analogRead but it does not be calibrated. It will be helpful if the ADC sensor can be supported directly.

### LINKED ISSUE #6389: Deprecated ADC Functions
### The problem

When compiling an ESPHome project that uses the ADC component on an ESP32C6 board with the ESP-IDF framework, multiple warnings and errors are generated due to deprecated functions. ESPHome's ADC component still references outdated ADC driver functions, which were deprecated and replaced by new ones in the latest ESP-IDF versions.

### Which version of ESPHome has the issue?

2024.10.2

### What type of installation are you using?

Home Assistant Add-on

### Which version of Home Assistant has the issue?

_No response_

### What platform are you using?

ESP32-IDF

### Board

ESP32C6 

### Component causing the issue

_No response_

### Example YAML snippet

```yaml
esp32:
  board: esp32-c6-devkitc-1
  variant: esp32c6
  framework:
    type: esp-idf
    version: "5.3.1"
    platform_version: 6.8.1


sensor: 
  - platform: adc
    pin: GPIO2
    name: "Water Level"
    update_interval: 1s
    unit_of_measurement: "%"

output:
  - platform: ledc
    id: pwm_output
    pin: GPIO18
    frequency: 200000 Hz
```

### Anything in the logs that might be useful for us?

```txt
In file included from src/esphome/components/adc/adc_sensor.h:10,
                 from src/esphome/components/adc/adc_sensor.cpp:1:
/data/cache/platformio/packages/framework-espidf/components/esp_adc/deprecated/include/esp_adc_cal.h:17:2: warning: #warning "legacy adc calibration driver is deprecated, please migrate to use esp_adc/adc_cali.h and esp_adc/adc_cali_scheme.h" [-Wcpp]
   17 | #warning "legacy adc calibration driver is deprecated, please migrate to use esp_adc/adc_cali.h and esp_adc/adc_cali_scheme.h"
      |  ^~~~~~~
In file included from src/esphome/components/adc/adc_sensor.h:11:
/data/cache/platformio/packages/framework-espidf/components/driver/deprecated/driver/adc.h:19:2: warning: #warning "legacy adc driver is deprecated, please migrate to use esp_adc/adc_oneshot.h and esp_adc/adc_continuous.h for oneshot mode and continuous mode drivers respectively" [-Wcpp]
   19 | #warning "legacy adc driver is deprecated, please migrate to use esp_adc/adc_oneshot.h and esp_adc/adc_continuous.h for oneshot mode and continuous mode drivers respectively"
      |  ^~~~~~~
src/esphome/components/adc/adc_sensor.h:41:21: error: 'adc2_channel_t' has not been declared
   41 |   void set_channel2(adc2_channel_t channel) {
      |                     ^~~~~~~~~~~~~~
src/esphome/components/adc/adc_sensor.h:80:3: error: 'adc2_channel_t' does not name a type; did you mean 'adc_channel_t'?
   80 |   adc2_channel_t channel2_{ADC2_CHANNEL_MAX};
      |   ^~~~~~~~~~~~~~
      |   adc_channel_t
src/esphome/components/adc/adc_sensor.h:83:3: error: 'esp_adc_cal_characteristics_t' does not name a type
   83 |   esp_adc_cal_characteristics_t cal_characteristics_[SOC_ADC_ATTEN_NUM] = {};
      |   ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~
src/esphome/components/adc/adc_sensor.h: In member function 'void esphome::adc::ADCSensor::set_channel1(adc1_channel_t)':
src/esphome/components/adc/adc_sensor.h:39:11: error: 'class esphome::adc::ADCSensor' has no member named 'channel2_'; did you mean 'channel1_'?
   39 |     this->channel2_ = ADC2_CHANNEL_MAX;
      |           ^~~~~~~~~
      |           channel1_
src/esphome/components/adc/adc_sensor.h:39:23: error: 'ADC2_CHANNEL_MAX' was not declared in this scope; did you mean 'ADC1_CHANNEL_MAX'?
   39 |     this->channel2_ = ADC2_CHANNEL_MAX;
      |                       ^~~~~~~~~~~~~~~~
      |                       ADC1_CHANNEL_MAX
src/esphome/components/adc/adc_sensor.h: In member function 'void esphome::adc::ADCSensor::set_channel2(int)':
src/esphome/components/adc/adc_sensor.h:42:11: error: 'class esphome::adc::ADCSensor' has no member named 'channel2_'; did you mean 'channel1_'?
   42 |     this->channel2_ = channel;
      |           ^~~~~~~~~
      |           channel1_
src/esphome/components/adc/adc_sensor.cpp: In member function 'virtual void esphome::adc::ADCSensor::setup()':
src/esphome/components/adc/adc_sensor.cpp:58:20: error: 'class esphome::adc::ADCSensor' has no member named 'channel2_'; did you mean 'channel1_'?
   58 |   } else if (this->channel2_ != ADC2_CHANNEL_MAX) {
      |                    ^~~~~~~~~
      |                    channel1_
src/esphome/components/adc/adc_sensor.cpp:58:33: error: 'ADC2_CHANNEL_MAX' was not declared in this scope; did you mean 'ADC1_CHANNEL_MAX'?
   58 |   } else if (this->channel2_ != ADC2_CHANNEL_MAX) {
      |                                 ^~~~~~~~~~~~~~~~
      |                                 ADC1_CHANNEL_MAX
src/esphome/components/adc/adc_sensor.cpp:60:39: error: 'class esphome::adc::ADCSensor' has no member named 'channel2_'; did you mean 'channel1_'?
   60 |       adc2_config_channel_atten(this->channel2_, this->attenuation_);
      |                                       ^~~~~~~~~
      |                                       channel1_
src/esphome/components/adc/adc_sensor.cpp:60:7: error: 'adc2_config_channel_atten' was not declared in this scope; did you mean 'adc1_config_channel_atten'?
   60 |       adc2_config_channel_atten(this->channel2_, this->attenuation_);
      |       ^~~~~~~~~~~~~~~~~~~~~~~~~
      |       adc1_config_channel_atten
src/esphome/components/adc/adc_sensor.cpp:69:54: error: 'class esphome::adc::ADCSensor' has no member named 'cal_characteristics_'
   69 |                                               &this->cal_characteristics_[i]);
      |                                                      ^~~~~~~~~~~~~~~~~~~~
src/esphome/components/adc/adc_sensor.cpp:67:22: error: 'esp_adc_cal_characterize' was not declared in this scope
   67 |     auto cal_value = esp_adc_cal_characterize(adc_unit, (adc_atten_t) i, ADC_WIDTH_MAX_SOC_BITS,
      |                      ^~~~~~~~~~~~~~~~~~~~~~~~
src/esphome/components/adc/adc_sensor.cpp:71:12: error: 'ESP_ADC_CAL_VAL_EFUSE_VREF' was not declared in this scope
   71 |       case ESP_ADC_CAL_VAL_EFUSE_VREF:
      |            ^~~~~~~~~~~~~~~~~~~~~~~~~~
src/esphome/components/adc/adc_sensor.cpp:74:12: error: 'ESP_ADC_CAL_VAL_EFUSE_TP' was not declared in this scope
   74 |       case ESP_ADC_CAL_VAL_EFUSE_TP:
      |            ^~~~~~~~~~~~~~~~~~~~~~~~
src/esphome/components/adc/adc_sensor.cpp:77:12: error: 'ESP_ADC_CAL_VAL_DEFAULT_VREF' was not declared in this scope
   77 |       case ESP_ADC_CAL_VAL_DEFAULT_VREF:
      |            ^~~~~~~~~~~~~~~~~~~~~~~~~~~~
src/esphome/components/adc/adc_sensor.cpp: In member function 'virtual float esphome::adc::ADCSensor::sample()':
src/esphome/components/adc/adc_sensor.cpp:184:24: error: 'class esphome::adc::ADCSensor' has no member named 'channel2_'; did you mean 'channel1_'?
  184 |       } else if (this->channel2_ != ADC2_CHANNEL_MAX) {
      |                        ^~~~~~~~~
      |                        channel1_
src/esphome/components/adc/adc_sensor.cpp:184:37: error: 'ADC2_CHANNEL_MAX' was not declared in this scope; did you mean 'ADC1_CHANNEL_MAX'?
  184 |       } else if (this->channel2_ != ADC2_CHANNEL_MAX) {
      |                                     ^~~~~~~~~~~~~~~~
      |                                     ADC1_CHANNEL_MAX
src/esphome/components/adc/adc_sensor.cpp:185:28: error: 'class esphome::adc::ADCSensor' has no member named 'channel2_'; did you mean 'channel1_'?
  185 |         adc2_get_raw(this->channel2_, ADC_WIDTH_MAX_SOC_BITS, &raw);
      |                            ^~~~~~~~~
      |                            channel1_
src/esphome/components/adc/adc_sensor.cpp:185:9: error: 'adc2_get_raw' was not declared in this scope; did you mean 'adc1_get_raw'?
  185 |         adc2_get_raw(this->channel2_, ADC_WIDTH_MAX_SOC_BITS, &raw);
      |         ^~~~~~~~~~~~
      |         adc1_get_raw
src/esphome/components/adc/adc_sensor.cpp:196:58: error: 'class esphome::adc::ADCSensor' has no member named 'cal_characteristics_'
  196 |     uint32_t mv = esp_adc_cal_raw_to_voltage(sum, &this->cal_characteristics_[(int32_t) this->attenuation_]);
      |                                                          ^~~~~~~~~~~~~~~~~~~~
src/esphome/components/adc/adc_sensor.cpp:196:19: error: 'esp_adc_cal_raw_to_voltage' was not declared in this scope
  196 |     uint32_t mv = esp_adc_cal_raw_to_voltage(sum, &this->cal_characteristics_[(int32_t) this->attenuation_]);
      |                   ^~~~~~~~~~~~~~~~~~~~~~~~~~
src/esphome/components/adc/adc_sensor.cpp:217:20: error: 'class esphome::adc::ADCSensor' has no member named 'channel2_'; did you mean 'channel1_'?
  217 |   } else if (this->channel2_ != ADC2_CHANNEL_MAX) {
      |                    ^~~~~~~~~
      |                    channel1_
src/esphome/components/adc/adc_sensor.cpp:217:33: error: 'ADC2_CHANNEL_MAX' was not declared in this scope; did you mean 'ADC1_CHANNEL_MAX'?
  217 |   } else if (this->channel2_ != ADC2_CHANNEL_MAX) {
      |                                 ^~~~~~~~~~~~~~~~
      |                                 ADC1_CHANNEL_MAX
src/esphome/components/adc/adc_sensor.cpp:218:37: error: 'class esphome::adc::ADCSensor' has no member named 'channel2_'; did you mean 'channel1_'?
  218 |     adc2_config_channel_atten(this->channel2_, ADC_ATTEN_DB_12_COMPAT);
      |                                     ^~~~~~~~~
      |                                     channel1_
src/esphome/components/adc/adc_sensor.cpp:218:5: error: 'adc2_config_channel_atten' was not declared in this scope; did you mean 'adc1_config_channel_atten'?
  218 |     adc2_config_channel_atten(this->channel2_, ADC_ATTEN_DB_12_COMPAT);
      |     ^~~~~~~~~~~~~~~~~~~~~~~~~
      |     adc1_config_channel_atten
src/esphome/components/adc/adc_sensor.cpp:219:24: error: 'class esphome::adc::ADCSensor' has no member named 'channel2_'; did you mean 'channel1_'?
  219 |     adc2_get_raw(this->channel2_, ADC_WIDTH_MAX_SOC_BITS, &raw12);
      |                        ^~~~~~~~~
      |                        channel1_
src/esphome/components/adc/adc_sensor.cpp:219:5: error: 'adc2_get_raw' was not declared in this scope; did you mean 'adc1_get_raw'?
  219 |     adc2_get_raw(this->channel2_, ADC_WIDTH_MAX_SOC_BITS, &raw12);
      |     ^~~~~~~~~~~~
      |     adc1_get_raw
src/esphome/components/adc/adc_sensor.cpp:221:39: error: 'class esphome::adc::ADCSensor' has no member named 'channel2_'; did you mean 'channel1_'?
  221 |       adc2_config_channel_atten(this->channel2_, ADC_ATTEN_DB_6);
      |                                       ^~~~~~~~~
      |                                       channel1_
src/esphome/components/adc/adc_sensor.cpp:222:26: error: 'class esphome::adc::ADCSensor' has no member named 'channel2_'; did you mean 'channel1_'?
  222 |       adc2_get_raw(this->channel2_, ADC_WIDTH_MAX_SOC_BITS, &raw6);
      |                          ^~~~~~~~~
      |                          channel1_
src/esphome/components/adc/adc_sensor.cpp:224:41: error: 'class esphome::adc::ADCSensor' has no member named 'channel2_'; did you mean 'channel1_'?
  224 |         adc2_config_channel_atten(this->channel2_, ADC_ATTEN_DB_2_5);
      |                                         ^~~~~~~~~
      |                                         channel1_
src/esphome/components/adc/adc_sensor.cpp:225:28: error: 'class esphome::adc::ADCSensor' has no member named 'channel2_'; did you mean 'channel1_'?
  225 |         adc2_get_raw(this->channel2_, ADC_WIDTH_MAX_SOC_BITS, &raw2);
      |                            ^~~~~~~~~
      |                            channel1_
src/esphome/components/adc/adc_sensor.cpp:227:43: error: 'class esphome::adc::ADCSensor' has no member named 'channel2_'; did you mean 'channel1_'?
  227 |           adc2_config_channel_atten(this->channel2_, ADC_ATTEN_DB_0);
      |                                           ^~~~~~~~~
      |                                           channel1_
src/esphome/components/adc/adc_sensor.cpp:228:30: error: 'class esphome::adc::ADCSensor' has no member named 'channel2_'; did you mean 'channel1_'?
  228 |           adc2_get_raw(this->channel2_, ADC_WIDTH_MAX_SOC_BITS, &raw0);
      |                              ^~~~~~~~~
      |                              channel1_
src/esphome/components/adc/adc_sensor.cpp:238:60: error: 'class esphome::adc::ADCSensor' has no member named 'cal_characteristics_'
  238 |   uint32_t mv12 = esp_adc_cal_raw_to_voltage(raw12, &this->cal_characteristics_[(int32_t) ADC_ATTEN_DB_12_COMPAT]);
      |                                                            ^~~~~~~~~~~~~~~~~~~~
src/esphome/components/adc/adc_sensor.cpp:238:19: error: 'esp_adc_cal_raw_to_voltage' was not declared in this scope
  238 |   uint32_t mv12 = esp_adc_cal_raw_to_voltage(raw12, &this->cal_characteristics_[(int32_t) ADC_ATTEN_DB_12_COMPAT]);
      |                   ^~~~~~~~~~~~~~~~~~~~~~~~~~
src/esphome/components/adc/adc_sensor.cpp:239:58: error: 'class esphome::adc::ADCSensor' has no member named 'cal_characteristics_'
  239 |   uint32_t mv6 = esp_adc_cal_raw_to_voltage(raw6, &this->cal_characteristics_[(int32_t) ADC_ATTEN_DB_6]);
      |                                                          ^~~~~~~~~~~~~~~~~~~~
src/esphome/components/adc/adc_sensor.cpp:240:58: error: 'class esphome::adc::ADCSensor' has no member named 'cal_characteristics_'
  240 |   uint32_t mv2 = esp_adc_cal_raw_to_voltage(raw2, &this->cal_characteristics_[(int32_t) ADC_ATTEN_DB_2_5]);
      |                                                          ^~~~~~~~~~~~~~~~~~~~
src/esphome/components/adc/adc_sensor.cpp:241:58: error: 'class esphome::adc::ADCSensor' has no member named 'cal_characteristics_'
  241 |   uint32_t mv0 = esp_adc_cal_raw_to_voltage(raw0, &this->cal_characteristics_[(int32_t) ADC_ATTEN_DB_0]);
      |                                                          ^~~~~~~~~~~~~~~~~~~~
*** [.pioenvs/c6-pwm/src/esphome/components/adc/adc_sensor.cpp.o] Error 1
========================= [FAILED] Took 103.58 seconds =========================
```

### Additional information

_No response_

### LINKED ISSUE #6455: #warning "legacy adc calibration driver is deprecated
### The problem

Compiling .pioenvs/p-ku-ble-shellyproxy/src/esphome/components/api/api_connection.cpp.o
In file included from src/esphome/components/adc/adc_sensor.h:10,
                 from src/esphome/components/adc/adc_sensor.cpp:1:
/data/cache/platformio/packages/framework-espidf/components/esp_adc/deprecated/include/esp_adc_cal.h:17:2: warning: #warning "legacy adc calibration driver is deprecated, please migrate to use esp_adc/adc_cali.h and esp_adc/adc_cali_scheme.h" [-Wcpp]
   17 | #warning "legacy adc calibration driver is deprecated, please migrate to use esp_adc/adc_cali.h and esp_adc/adc_cali_scheme.h"
      |  ^~~~~~~
In file included from src/esphome/components/adc/adc_sensor.h:11:
/data/cache/platformio/packages/framework-espidf/components/driver/deprecated/driver/adc.h:19:2: warning: #warning "legacy adc driver is deprecated, please migrate to use esp_adc/adc_oneshot.h and esp_adc/adc_continuous.h for oneshot mode and continuous mode drivers respectively" [-Wcpp]
   19 | #warning "legacy adc driver is deprecated, please migrate to use esp_adc/adc_oneshot.h and esp_adc/adc_continuous.h for oneshot mode and continuous mode drivers respectively"
      |  ^~~~~~~
      
Compiling .pioenvs/p-bdo-ble-shellyproxy/src/main.cpp.o
In file included from src/esphome/components/adc/adc_sensor.h:10,
                 from src/esphome.h:3,
                 from src/main.cpp:3:
/data/cache/platformio/packages/framework-espidf/components/esp_adc/deprecated/include/esp_adc_cal.h:17:2: warning: #warning "legacy adc calibration driver is deprecated, please migrate to use esp_adc/adc_cali.h and esp_adc/adc_cali_scheme.h" [-Wcpp]
   17 | #warning "legacy adc calibration driver is deprecated, please migrate to use esp_adc/adc_cali.h and esp_adc/adc_cali_scheme.h"
      |  ^~~~~~~
In file included from src/esphome/components/adc/adc_sensor.h:11:
/data/cache/platformio/packages/framework-espidf/components/driver/deprecated/driver/adc.h:19:2: warning: #warning "legacy adc driver is deprecated, please migrate to use esp_adc/adc_oneshot.h and esp_adc/adc_continuous.h for oneshot mode and continuous mode drivers respectively" [-Wcpp]
   19 | #warning "legacy adc driver is deprecated, please migrate to use esp_adc/adc_oneshot.h and esp_adc/adc_continuous.h for oneshot mode and continuous mode drivers respectively"
      |  ^~~~~~~

### Which version of ESPHome has the issue?

2024.11.0 and older

### What type of installation are you using?

Home Assistant Add-on

### Which version of Home Assistant has the issue?

2024.11.2

### What platform are you using?

ESP32-IDF

### Board

ESP32-C3

### Component causing the issue

adc / platformio/espressif32@6.9.0 and 6.7.0 framework-espidf @ 3.50301.0 and 3.50202.0 

### Example YAML snippet

```yaml
sensor:
  - platform: ntc
    sensor: temp_resistance_reading
    name: "Temperature"
    unit_of_measurement: "°C"
    accuracy_decimals: 1
    device_class: temperature
    state_class: measurement
    icon: "mdi:thermometer"
    calibration:
      b_constant: 3350
      reference_resistance: 10kOhm
      reference_temperature: 298.15K

  - platform: resistance
    id: temp_resistance_reading
    sensor: temp_analog_reading
    configuration: DOWNSTREAM
    resistor: 10kOhm
    
  - platform: adc
    id: temp_analog_reading
    pin: GPIO3
    attenuation: 12db
```

### Anything in the logs that might be useful for us?

_No response_

### Additional information

_No response_

### PR DESCRIPTION
**Pull request by edwardtfn**
# What does this implement/fix?

This adds compatibility to ESP-IDF v5 to the ADC component, preventing the warning message related to the deprecated libraries.
This is a continuation of PR#7940 which was splitting the files per platform, so if this one is merged, that other pr becomes obsolete. Or #7940 could be merged first to make this one smaller. 😉 

**ATTENTION**: This is exactly the same as #7942. I've duplicated as that PR got lots of non-related things when getting updates from DEV.

## Types of changes

- [ ] Bugfix (non-breaking change which fixes an issue)
- [X] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [X] Code quality improvements to existing code or addition of tests
- [ ] Other

**Related issue or feature (if applicable):**

- possibly fixes esphome/issues#6389
- fixes esphome/issues#6455
- closes esphome/feature-requests#2988

**Pull request in [esphome-docs](https://github.com/esphome/esphome-docs) with documentation (if applicable):** esphome/esphome-docs#4502

## Test Environment

- [X] ESP32
- [X] ESP32 IDF v4.4.8
- [X] ESP32 IDF v5.1.5
- [X] ESP32 IDF v5.3.1
- [X] ESP8266
- [ ] RP2040
- [ ] BK72xx
- [ ] RTL87xx

## Checklist:
  - [X] The code change is tested and works locally.
  - [ ] Tests have been added to verify that the new code works (under `tests/` folder).

If user exposed functionality or configuration variables are added/changed:
  - [ ] Documentation added/updated in [esphome-docs](https://github.com/esphome/esphome-docs).

### CODE REVIEW

File: esphome/components/adc/adc_sensor.h [hunk 1]
```diff
@@ -3,17 +3,70 @@
...
 #include <esp_adc_cal.h>
 #include "driver/adc.h"
+#endif  // ESP_IDF_VERSION >= ESP_IDF_VERSION_VAL(5, 0, 0)
 #endif  // USE_ESP32
 
 namespace esphome {
 namespace adc {
 
 #ifdef USE_ESP32
+#if ESP_IDF_VERSION >= ESP_IDF_VERSION_VAL(5, 0, 0)
```
Comment (jesserockz) [inline esphome/components/adc/adc_sensor.h]: All of these checks can be dropped now that the default idf version will be above 5.0.0

**Review by jesserockz — CHANGES_REQUESTED** [review]

File: esphome/components/adc/adc_sensor.h (hunk 1 above)
Comment (edwardtfn) [reply esphome/components/adc/adc_sensor.h]: Should we drop idf v4 support from all components now?

- https://github.com/esphome/developers.esphome.io/discussions/42#discussioncomment-13536135

Comment (jesserockz) [reply esphome/components/adc/adc_sensor.h]: All are fine in their own PRs.

**Comment by jesserockz** [comment]
I was reading today that the oneshot driver also allows for using adc2 with wifi running

> ADC2 is also used by Wi-Fi. [adc_oneshot_read()](https://docs.espressif.com/projects/esp-idf/en/v5.3.3/esp32s3/api-reference/peripherals/adc_oneshot.html#_CPPv416adc_oneshot_read25adc_oneshot_unit_handle_t13adc_channel_tPi) has provided protection between the Wi-Fi driver and ADC oneshot mode driver.

https://docs.espressif.com/projects/esp-idf/en/v5.3.3/esp32s3/api-reference/peripherals/adc_oneshot.html#hardware-limitations

**Comment by WebDesignerlol** [comment]
i believe this is still failing for ESP32C6:

see [issue#6389](https://github.com/esphome/issues/issues/6389) for a fix, it would be great if you could implement their code here for the ESP32C6. The final working solution was 


, its still failing with this PR on the ESP32C6. here are my logs for the ESP32C6 from XAIO Seeed Studios that relate to the adc from this PR (default adc had similar issues):
```
Processing testproject (board: esp32-c6-devkitm-1; framework: espidf; platform: https://github.com/pioarduino/platform-espressif32/releases/download/53.03.13/platform-espressif32.zip)
--------------------------------------------------------------------------------
HARDWARE: ESP32C6 160MHz, 320KB RAM, 4MB Flash
 - framework-espidf @ 3.50302.0 (5.3.2) 
 - tool-cmake @ 3.30.2 
 - tool-esptoolpy @ 4.8.6 
 - tool-mklittlefs @ 3.2.0 
 - tool-ninja @ 1.10.2 
 - tool-riscv32-esp-elf-gdb @ 14.2.0+20240403 
 - tool-xtensa-esp-elf-gdb @ 14.2.0+20240403 
 - toolchain-esp32ulp @ 2.35.0-20220830 
 - toolchain-riscv32-esp @ 13.2.0+20240530
Reading CMake configuration...
Dependency Graph
|-- noise-c @ 0.1.6
Compiling .pioenvs/testproject/src/esphome/components/adc/adc_sensor_common.cpp.o
Compiling .pioenvs/testproject/src/esphome/components/adc/adc_sensor_esp32.cpp.o
....
In file included from src/esphome/components/adc/adc_sensor.h:9,
                 from src/esphome/components/adc/adc_sensor_common.cpp:1:
/data/cache/platformio/packages/framework-espidf/components/esp_adc/deprecated/include/esp_adc_cal.h:17:2: warning: #warning "legacy adc calibration driver is deprecated, please migrate to use esp_adc/adc_cali.h and esp_adc/adc_cali_scheme.h" [-Wcpp]
   17 | #warning "legacy adc calibration driver is deprecated, please migrate to use esp_adc/adc_cali.h and esp_adc/adc_cali_scheme.h"
      |  ^~~~~~~
In file included from src/esphome/components/adc/adc_sensor.h:10:
/data/cache/platformio/packages/framework-espidf/components/driver/deprecated/driver/adc.h:19:2: warning: #warning "legacy adc driver is deprecated, please migrate to use esp_adc/adc_oneshot.h and esp_adc/adc_continuous.h for oneshot mode and continuous mode drivers respectively" [-Wcpp]
   19 | #warning "legacy adc driver is deprecated, please migrate to use esp_adc/adc_oneshot.h and esp_adc/adc_continuous.h for oneshot mode and continuous mode drivers respectively"
      |  ^~~~~~~
In file included from src/esphome/components/adc/adc_sensor.h:9,
                 from src/esphome/components/adc/adc_sensor_esp32.cpp:3:
/data/cache/platformio/packages/framework-espidf/components/esp_adc/deprecated/include/esp_adc_cal.h:17:2: warning: #warning "legacy adc calibration driver is deprecated, please migrate to use esp_adc/adc_cali.h and esp_adc/adc_cali_scheme.h" [-Wcpp]
   17 | #warning "legacy adc calibration driver is deprecated, please migrate to use esp_adc/adc_cali.h and esp_adc/adc_cali_scheme.h"
      |  ^~~~~~~
In file included from src/esphome/components/adc/adc_sensor.h:10:
/data/cache/platformio/packages/framework-espidf/components/driver/deprecated/driver/adc.h:19:2: warning: #warning "legacy adc driver is deprecated, please migrate to use esp_adc/adc_oneshot.h and esp_adc/adc_continuous.h for oneshot mode and continuous mode drivers respectively" [-Wcpp]
   19 | #warning "legacy adc driver is deprecated, please migrate to use esp_adc/adc_oneshot.h and esp_adc/adc_continuous.h for oneshot mode and continuous mode drivers respectively"
      |  ^~~~~~~
Compiling .pioenvs/testproject/src/esphome/components/captive_portal/captive_portal.cpp.o
...
Compiling .pioenvs/testproject/src/esphome/components/esp32/core.cpp.o
src/esphome/components/adc/adc_sensor.h:55:21: error: 'adc2_channel_t' has not been declared
   55 |   void set_channel2(adc2_channel_t channel) {
      |                     ^~~~~~~~~~~~~~
src/esphome/components/adc/adc_sensor.h:96:3: error: 'adc2_channel_t' does not name a type; did you mean 'adc_channel_t'?
   96 |   adc2_channel_t channel2_{ADC2_CHANNEL_MAX};
      |   ^~~~~~~~~~~~~~
      |   adc_channel_t
src/esphome/components/adc/adc_sensor.h:99:3: error: 'esp_adc_cal_characteristics_t' does not name a type
   99 |   esp_adc_cal_characteristics_t cal_characteristics_[SOC_ADC_ATTEN_NUM] = {};
      |   ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~
src/esphome/components/adc/adc_sensor.h: In member function 'void esphome::adc::ADCSensor::set_channel1(adc1_channel_t)':
src/esphome/components/adc/adc_sensor.h:53:11: error: 'class esphome::adc::ADCSensor' has no member named 'channel2_'; did you mean 'channel1_'?
   53 |     this->channel2_ = ADC2_CHANNEL_MAX;
      |           ^~~~~~~~~
      |           channel1_
src/esphome/components/adc/adc_sensor.h:53:23: error: 'ADC2_CHANNEL_MAX' was not declared in this scope; did you mean 'ADC1_CHANNEL_MAX'?
   53 |     this->channel2_ = ADC2_CHANNEL_MAX;
      |                       ^~~~~~~~~~~~~~~~
      |                       ADC1_CHANNEL_MAX
src/esphome/components/adc/adc_sensor.h: In member function 'void esphome::adc::ADCSensor::set_channel2(int)':
src/esphome/components/adc/adc_sensor.h:56:11: error: 'class esphome::adc::ADCSensor' has no member named 'channel2_'; did you mean 'channel1_'?
   56 |     this->channel2_ = channel;
      |           ^~~~~~~~~
      |           channel1_
src/esphome/components/adc/adc_sensor_esp32.cpp: In member function 'virtual void esphome::adc::ADCSensor::setup()':
src/esphome/components/adc/adc_sensor_esp32.cpp:32:20: error: 'class esphome::adc::ADCSensor' has no member named 'channel2_'; did you mean 'channel1_'?
   32 |   } else if (this->channel2_ != ADC2_CHANNEL_MAX) {
      |                    ^~~~~~~~~
      |                    channel1_
src/esphome/components/adc/adc_sensor_esp32.cpp:32:33: error: 'ADC2_CHANNEL_MAX' was not declared in this scope; did you mean 'ADC1_CHANNEL_MAX'?
   32 |   } else if (this->channel2_ != ADC2_CHANNEL_MAX) {
      |                                 ^~~~~~~~~~~~~~~~
      |                                 ADC1_CHANNEL_MAX
src/esphome/components/adc/adc_sensor_esp32.cpp:34:39: error: 'class esphome::adc::ADCSensor' has no member named 'channel2_'; did you mean 'channel1_'?
   34 |       adc2_config_channel_atten(this->channel2_, this->attenuation_);
      |                                       ^~~~~~~~~
      |                                       channel1_
src/esphome/components/adc/adc_sensor.h:55:21: error: 'adc2_channel_t' has not been declared
   55 |   void set_channel2(adc2_channel_t channel) {
      |                     ^~~~~~~~~~~~~~
src/esphome/components/adc/adc_sensor.h:96:3: error: 'adc2_channel_t' does not name a type; did you mean 'adc_channel_t'?
   96 |   adc2_channel_t channel2_{ADC2_CHANNEL_MAX};
      |   ^~~~~~~~~~~~~~
      |   adc_channel_t
src/esphome/components/adc/adc_sensor_esp32.cpp:34:7: error: 'adc2_config_channel_atten' was not declared in this scope; did you mean 'adc1_config_channel_atten'?
   34 |       adc2_config_channel_atten(this->channel2_, this->attenuation_);
      |       ^~~~~~~~~~~~~~~~~~~~~~~~~
      |       adc1_config_channel_atten
src/esphome/components/adc/adc_sensor_esp32.cpp:42:54: error: 'class esphome::adc::ADCSensor' has no member named 'cal_characteristics_'
   42 |                                               &this->cal_characteristics_[i]);
      |                                                      ^~~~~~~~~~~~~~~~~~~~
src/esphome/components/adc/adc_sensor.h:99:3: error: 'esp_adc_cal_characteristics_t' does not name a type
   99 |   esp_adc_cal_characteristics_t cal_characteristics_[SOC_ADC_ATTEN_NUM] = {};
      |   ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~
src/esphome/components/adc/adc_sensor.h: In member function 'void esphome::adc::ADCSensor::set_channel1(adc1_channel_t)':
src/esphome/components/adc/adc_sensor.h:53:11: error: 'class esphome::adc::ADCSensor' has no member named 'channel2_'; did you mean 'channel1_'?
   53 |     this->channel2_ = ADC2_CHANNEL_MAX;
      |           ^~~~~~~~~
      |           channel1_
src/esphome/components/adc/adc_sensor.h:53:23: error: 'ADC2_CHANNEL_MAX' was not declared in this scope; did you mean 'ADC1_CHANNEL_MAX'?
   53 |     this->channel2_ = ADC2_CHANNEL_MAX;
      |                       ^~~~~~~~~~~~~~~~
      |                       ADC1_CHANNEL_MAX
src/esphome/components/adc/adc_sensor.h: In member function 'void esphome::adc::ADCSensor::set_channel2(int)':
src/esphome/components/adc/adc_sensor.h:56:11: error: 'class esphome::adc::ADCSensor' has no member named 'channel2_'; did you mean 'channel1_'?
   56 |     this->channel2_ = channel;
      |           ^~~~~~~~~
      |           channel1_
src/esphome/components/adc/adc_sensor_esp32.cpp:40:22: error: 'esp_adc_cal_characterize' was not declared in this scope
   40 |     auto cal_value = esp_adc_cal_characterize(adc_unit, (adc_atten_t) i, ADC_WIDTH_MAX_SOC_BITS,
      |                      ^~~~~~~~~~~~~~~~~~~~~~~~
src/esphome/components/adc/adc_sensor_esp32.cpp:44:12: error: 'ESP_ADC_CAL_VAL_EFUSE_VREF' was not declared in this scope
   44 |       case ESP_ADC_CAL_VAL_EFUSE_VREF:
      |            ^~~~~~~~~~~~~~~~~~~~~~~~~~
src/esphome/components/adc/adc_sensor_esp32.cpp:47:12: error: 'ESP_ADC_CAL_VAL_EFUSE_TP' was not declared in this scope
   47 |       case ESP_ADC_CAL_VAL_EFUSE_TP:
      |            ^~~~~~~~~~~~~~~~~~~~~~~~
src/esphome/components/adc/adc_sensor_esp32.cpp:50:12: error: 'ESP_ADC_CAL_VAL_DEFAULT_VREF' was not declared in this scope
   50 |       case ESP_ADC_CAL_VAL_DEFAULT_VREF:
      |            ^~~~~~~~~~~~~~~~~~~~~~~~~~~~
src/esphome/components/adc/adc_sensor_esp32.cpp: In member function 'virtual float esphome::adc::ADCSensor::sample()':
src/esphome/components/adc/adc_sensor_esp32.cpp:95:24: error: 'class esphome::adc::ADCSensor' has no member named 'channel2_'; did you mean 'channel1_'?
   95 |       } else if (this->channel2_ != ADC2_CHANNEL_MAX) {
      |                        ^~~~~~~~~
      |                        channel1_
src/esphome/components/adc/adc_sensor_esp32.cpp:95:37: error: 'ADC2_CHANNEL_MAX' was not declared in this scope; did you mean 'ADC1_CHANNEL_MAX'?
   95 |       } else if (this->channel2_ != ADC2_CHANNEL_MAX) {
      |                                     ^~~~~~~~~~~~~~~~
      |                                     ADC1_CHANNEL_MAX
src/esphome/components/adc/adc_sensor_esp32.cpp:96:28: error: 'class esphome::adc::ADCSensor' has no member named 'channel2_'; did you mean 'channel1_'?
   96 |         adc2_get_raw(this->channel2_, ADC_WIDTH_MAX_SOC_BITS, &raw);
      |                            ^~~~~~~~~
      |                            channel1_
src/esphome/components/adc/adc_sensor_esp32.cpp:96:9: error: 'adc2_get_raw' was not declared in this scope; did you mean 'adc1_get_raw'?
   96 |         adc2_get_raw(this->channel2_, ADC_WIDTH_MAX_SOC_BITS, &raw);
      |         ^~~~~~~~~~~~
      |         adc1_get_raw
src/esphome/components/adc/adc_sensor_esp32.cpp:108:61: error: 'class esphome::adc::ADCSensor' has no member named 'cal_characteristics_'
  108 |         esp_adc_cal_raw_to_voltage(aggr.aggregate(), &this->cal_characteristics_[(int32_t) this->attenuation_]);
      |                                                             ^~~~~~~~~~~~~~~~~~~~
src/esphome/components/adc/adc_sensor_esp32.cpp:108:9: error: 'esp_adc_cal_raw_to_voltage' was not declared in this scope
  108 |         esp_adc_cal_raw_to_voltage(aggr.aggregate(), &this->cal_characteristics_[(int32_t) this->attenuation_]);
      |         ^~~~~~~~~~~~~~~~~~~~~~~~~~
src/esphome/components/adc/adc_sensor_esp32.cpp:129:20: error: 'class esphome::adc::ADCSensor' has no member named 'channel2_'; did you mean 'channel1_'?
  129 |   } else if (this->channel2_ != ADC2_CHANNEL_MAX) {
      |                    ^~~~~~~~~
      |                    channel1_
src/esphome/components/adc/adc_sensor_esp32.cpp:129:33: error: 'ADC2_CHANNEL_MAX' was not declared in this scope; did you mean 'ADC1_CHANNEL_MAX'?
  129 |   } else if (this->channel2_ != ADC2_CHANNEL_MAX) {
      |                                 ^~~~~~~~~~~~~~~~
      |                                 ADC1_CHANNEL_MAX
src/esphome/components/adc/adc_sensor_esp32.cpp:130:37: error: 'class esphome::adc::ADCSensor' has no member named 'channel2_'; did you mean 'channel1_'?
  130 |     adc2_config_channel_atten(this->channel2_, ADC_ATTEN_DB_12_COMPAT);
      |                                     ^~~~~~~~~
      |                                     channel1_
src/esphome/components/adc/adc_sensor_esp32.cpp:130:5: error: 'adc2_config_channel_atten' was not declared in this scope; did you mean 'adc1_config_channel_atten'?
  130 |     adc2_config_channel_atten(this->channel2_, ADC_ATTEN_DB_12_COMPAT);
      |     ^~~~~~~~~~~~~~~~~~~~~~~~~
      |     adc1_config_channel_atten
src/esphome/components/adc/adc_sensor_esp32.cpp:131:24: error: 'class esphome::adc::ADCSensor' has no member named 'channel2_'; did you mean 'channel1_'?
  131 |     adc2_get_raw(this->channel2_, ADC_WIDTH_MAX_SOC_BITS, &raw12);
      |                        ^~~~~~~~~
      |                        channel1_
src/esphome/components/adc/adc_sensor_esp32.cpp:131:5: error: 'adc2_get_raw' was not declared in this scope; did you mean 'adc1_get_raw'?
  131 |     adc2_get_raw(this->channel2_, ADC_WIDTH_MAX_SOC_BITS, &raw12);
      |     ^~~~~~~~~~~~
      |     adc1_get_raw
src/esphome/components/adc/adc_sensor_esp32.cpp:133:39: error: 'class esphome::adc::ADCSensor' has no member named 'channel2_'; did you mean 'channel1_'?
  133 |       adc2_config_channel_atten(this->channel2_, ADC_ATTEN_DB_6);
      |                                       ^~~~~~~~~
      |                                       channel1_
src/esphome/components/adc/adc_sensor_esp32.cpp:134:26: error: 'class esphome::adc::ADCSensor' has no member named 'channel2_'; did you mean 'channel1_'?
  134 |       adc2_get_raw(this->channel2_, ADC_WIDTH_MAX_SOC_BITS, &raw6);
      |                          ^~~~~~~~~
      |                          channel1_
src/esphome/components/adc/adc_sensor_esp32.cpp:136:41: error: 'class esphome::adc::ADCSensor' has no member named 'channel2_'; did you mean 'channel1_'?
  136 |         adc2_config_channel_atten(this->channel2_, ADC_ATTEN_DB_2_5);
      |                                         ^~~~~~~~~
      |                                         channel1_
src/esphome/components/adc/adc_sensor_esp32.cpp:137:28: error: 'class esphome::adc::ADCSensor' has no member named 'channel2_'; did you mean 'channel1_'?
  137 |         adc2_get_raw(this->channel2_, ADC_WIDTH_MAX_SOC_BITS, &raw2);
      |                            ^~~~~~~~~
      |                            channel1_
src/esphome/components/adc/adc_sensor_esp32.cpp:139:43: error: 'class esphome::adc::ADCSensor' has no member named 'channel2_'; did you mean 'channel1_'?
  139 |           adc2_config_channel_atten(this->channel2_, ADC_ATTEN_DB_0);
      |                                           ^~~~~~~~~
      |                                           channel1_
src/esphome/components/adc/adc_sensor_esp32.cpp:140:30: error: 'class esphome::adc::ADCSensor' has no member named 'channel2_'; did you mean 'channel1_'?
  140 |           adc2_get_raw(this->channel2_, ADC_WIDTH_MAX_SOC_BITS, &raw0);
      |                              ^~~~~~~~~
      |                              channel1_
src/esphome/components/adc/adc_sensor_esp32.cpp:150:60: error: 'class esphome::adc::ADCSensor' has no member named 'cal_characteristics_'
  150 |   uint32_t mv12 = esp_adc_cal_raw_to_voltage(raw12, &this->cal_characteristics_[(int32_t) ADC_ATTEN_DB_12_COMPAT]);
      |                                                            ^~~~~~~~~~~~~~~~~~~~
src/esphome/components/adc/adc_sensor_esp32.cpp:150:19: error: 'esp_adc_cal_raw_to_voltage' was not declared in this scope
  150 |   uint32_t mv12 = esp_adc_cal_raw_to_voltage(raw12, &this->cal_characteristics_[(int32_t) ADC_ATTEN_DB_12_COMPAT]);
      |                   ^~~~~~~~~~~~~~~~~~~~~~~~~~
src/esphome/components/adc/adc_sensor_esp32.cpp:151:58: error: 'class esphome::adc::ADCSensor' has no member named 'cal_characteristics_'
  151 |   uint32_t mv6 = esp_adc_cal_raw_to_voltage(raw6, &this->cal_characteristics_[(int32_t) ADC_ATTEN_DB_6]);
      |                                                          ^~~~~~~~~~~~~~~~~~~~
src/esphome/components/adc/adc_sensor_esp32.cpp:152:58: error: 'class esphome::adc::ADCSensor' has no member named 'cal_characteristics_'
  152 |   uint32_t mv2 = esp_adc_cal_raw_to_voltage(raw2, &this->cal_characteristics_[(int32_t) ADC_ATTEN_DB_2_5]);
      |                                                          ^~~~~~~~~~~~~~~~~~~~
src/esphome/components/adc/adc_sensor_esp32.cpp:153:58: error: 'class esphome::adc::ADCSensor' has no member named 'cal_characteristics_'
  153 |   uint32_t mv0 = esp_adc_cal_raw_to_voltage(raw0, &this->cal_characteristics_[(int32_t) ADC_ATTEN_DB_0]);
      |                                                          ^~~~~~~~~~~~~~~~~~~~
*** [.pioenvs/testproject/src/esphome/components/adc/adc_sensor_common.cpp.o] Error 1
*** [.pioenvs/testproject/src/esphome/components/adc/adc_sensor_esp32.cpp.o] Error 1
========================= [FAILED] Took 14.38 seconds =========================
```

I had tried this PR with the following addition to my yaml, which caused the log above (so the below fails):
```
external_components:
  - source:
      type: git
      url: https://github.com/esphome/esphome
      ref: pr9021
    refresh: 30s
    components:
      - adc
```
what worked was [PhracturedBlue's changes](https://github.com/PhracturedBlue/c6_adc/tree/665cc257fd0607c270da762a80e3baa6a788926b), so it would be awesome if someone could merge/test those better but i can vouch for my specific ESP32c6 Seeed Studios variant, and [another commentator can also](https://github.com/esphome/issues/issues/5363#issuecomment-2798417075):

```
external_components:
  - source: github://PhracturedBlue/c6_adc
    refresh: 0s   # uncomment to force refresh of repo
...
  - platform: c6_adc
    pin: GPIO2
    name: "Analog Sensor"
    update_interval: 5s
```

File: esphome/components/adc/adc_sensor.h (hunk 1 above)
Comment (edwardtfn) [reply esphome/components/adc/adc_sensor.h]: Done!

**Comment by jesserockz** [comment]
@edwardtfn I hope you don't mind. I pushed some cleanups to remove some of the duplicated code and hopefully made it a bit cleaner.

Also removed the final validation as ESPHome will not support any IDF4 based versions from 2025.7.0 anyway and also the adc2/wifi check is not needed with the one-shot driver.

Let me know if I broke something, but I did a simple test on an esp32s3 and will do some more tomorrow.

**Comment by edwardtfn** [comment]
> @edwardtfn I hope you don't mind. I pushed some cleanups to remove some of the duplicated code and hopefully made it a bit cleaner.

I don't mind at all!!  😉 
Thanks a lot for that.

> Also removed the final validation as ESPHome will not support any IDF4 based versions from 2025.7.0 anyway and also the adc2/wifi check is not needed with the one-shot driver.

👍 

> Let me know if I broke something, but I did a simple test on an esp32s3 and will do some more tomorrow.

I'm also pending some tests since my last changes (removing idf v4 code) and look at that thing about ESP32C6 (https://github.com/esphome/esphome/pull/9021#issuecomment-3001954588).

Have to find some time to test it more. 😞

**Comment by jesserockz** [comment]
I'll give a c6 a go today too

**Comment by jesserockz** [comment]
I didn't get around to actually testing on a c6 today, but it compiles fine for one

**Review by jesserockz — APPROVED** [review]

**Comment by edwardtfn** [comment]
Should I change this back to "Ready for review"?

**Comment by oxynatOr** [comment]
i can confirm it runs on C3, C5 and C6, you want it tested on C61? 

i also test it in 7 of my Shelly Gen3 plugs. no issues at all!

**Comment by kaschperle8324** [comment]
How can i test it. How to get the new files compiled?

**Comment by oxynatOr** [comment]
@edwardtfn  
my bad, i use the PR inside your esphome repo (i merged it into my esp).
/e: ref: adc-new-library-espidf-5  is what i use for a couple of month now. 

With the #PR9021 i will get an error on dev and stable:

ImportError: cannot import name 'filter_source_files_from_platform' from 'esphome.config_helpers' (/esphome/esphome/config_helpers.py) 


@kaschperle8324  take a look here: https://github.com/Blackymas/NSPanel_HA_Blueprint/issues/2626 

```
external_components:
  - source: github://pr#9021
    components:
      - adc
    refresh: 30s
```

**Comment by markusg1234** [comment]
How can i test it. How to get the new files compiled?

I use this with ESPHome Builder (dev)

``` 
esphome:
  name: moisture-sensor-1
  friendly_name: Moisture sensor 1

esp32:
  board: esp32-c6-devkitm-1
  framework:
    type: esp-idf
    version: "5.3.1"
   
external_components:
   - source: github://pr#9021
     components: adc

**Comment by edwardtfn** [comment]
Have you tried this with ESPHome 2025.7.0bx?

**Comment by markusg1234** [comment]
Just tested with ESPHome 2025.7.0b2.  It compiled, I uploaded to the C6 and it is working. 
Note: I have only tested in on GPIO0.

**Comment by oxynatOr** [comment]
> Have you tried this with ESPHome 2025.7.0bx?

upgraded to 2025.8 and its compiling for C3, can you allow C5 too? 
```
  This ESP32 variant (ESP32C5) is not supported.
```

**Comment by jesserockz** [comment]
@oxynatOr As this PR is done and ready to go and only waiting until the release is out, we (or you) can add the c5 in a new PR after this one.

**Comment by edwardtfn** [comment]
> can you allow C5 too?
> 
> ```
>   This ESP32 variant (ESP32C5) is not supported.
> ```

As mentioned, it's better to have this in another PR, so let's use PR #9486 for this.
I don't have any C5 device, so I would appreciate if you can run tests and report your results on that PR.
