### PR TITLE
Fix RP2040 Neopixel flickering issue

### LINKED ISSUE #6083: LED Strip flickers randomly with light effects
### The problem

WS212B_Flicker

https://github.com/user-attachments/assets/5b75c7c8-2423-495d-81ae-bcc3b3bf1d44

When using a Neopixel WS2812B strip with Raspberry pi pico w running Esphome, the led strip flickers intermittently. I'm not sure what's the root cause of the issue. I tried using a different frequency (8MHz) but it didn't work either.

Is this a common issue? I also tried with a different strip and faced same issue. I used another pico w running micropython and verified that the strip works fine with it so not sure what's wrong with using via esphome.

### Which version of ESPHome has the issue?

2024.7.1

### What type of installation are you using?

Home Assistant Add-on

### Which version of Home Assistant has the issue?

2024.7.3

### What platform are you using?

RP2040

### Board

pico w

### Component causing the issue

rp2040_pio_led_strip

### Example YAML snippet

```yaml
light:
  - platform: rp2040_pio_led_strip
    name: "Neopixel Strip"
    id: led_strip
    pin: GPIO21
    num_leds: 60
    pio: 0
    rgb_order: GRB
    chipset: WS2812B
    effects:
      - pulse:
      - pulse:
          name: "Fast Pulse"
          transition_length: 0.5s
          update_interval: 0.5s
          min_brightness: 0%
          max_brightness: 100%
      # Use default parameters:
      - random:
      # Customize parameters
      - random:
          name: "My Slow Random Effect"
          transition_length: 30s
          update_interval: 30s
      - random:
          name: "My Fast Random Effect"
          transition_length: 4s
          update_interval: 5s
      - strobe:
      - strobe:
          name: Strobe Effect With Custom Values
          colors:
            - state: true
              brightness: 100%
              red: 100%
              green: 90%
              blue: 0%
              duration: 500ms
            - state: false
              duration: 250ms
            - state: true
              brightness: 100%
              red: 0%
              green: 100%
              blue: 0%
              duration: 500ms
      - addressable_rainbow:
      - addressable_rainbow:
          name: Rainbow Effect With Custom Values
          speed: 10
          width: 50
```

### Anything in the logs that might be useful for us?

```txt
There's no error message in the logs.
```

### Additional information

_No response_

### PR DESCRIPTION
**Pull request by deCodeIt**
# What does this implement/fix?

Fixes Raspberry Pi Pico W ( RP2040 ) flickering issue for the following cases:
- Any addressable effect used to cause random flickering along with random color leds in between.
- Flickering during normal color change transitions

The dma writes were missing interrupt handling causing writes to fire faster than the previous writes used to complete ending up with flickering and random colors. This patch adds interrupt handling for dma writes.

Tested the patch with 2 Neopixel Strips.
Flickering Fixed

## Types of changes

- [x] Bugfix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] Other

**Related issue or feature (if applicable):** fixes [esphome/issues#6083](https://github.com/esphome/issues/issues/6083)

**Pull request in [esphome-docs](https://github.com/esphome/esphome-docs) with documentation (if applicable):** esphome/esphome-docs#<esphome-docs PR number goes here>

## Test Environment

- [ ] ESP32
- [ ] ESP32 IDF
- [ ] ESP8266
- [x] RP2040
- [ ] BK72xx
- [ ] RTL87xx

## Example entry for `config.yaml`:

```yaml
light:
  - platform: rp2040_pio_led_strip
    name: led_strip
    id: led_strip
    pin: GPIO18
    num_leds: 10
    pio: 0
    rgb_order: GRB
    chipset: WS2812B
    effects:
      - addressable_rainbow:

```

## Checklist:
  - [x] The code change is tested and works locally.
  - [x] Tests have been added to verify that the new code works (under `tests/` folder).

If user exposed functionality or configuration variables are added/changed:
  - [ ] Documentation added/updated in [esphome-docs](https://github.com/esphome/esphome-docs).

### CODE REVIEW

**Comment by deCodeIt** [comment]
Tagging @jesserockz

File: esphome/components/rp2040_pio_led_strip/led_strip.cpp [hunk 1]
```diff
@@ -93,6 +108,9 @@ void RP2040PIOLEDStripLightOutput::setup() {
     return;
   }
 
+  // Mark the DMA channel as active
+  dma_chan_active_[this->dma_chan_] = true;
```
Comment (jesserockz) [inline esphome/components/rp2040_pio_led_strip/led_strip.cpp]: Can we add some class prefixes here just to make it clearer what is being accessed?
(I know the other static variables are not marked like this, if you want to update them, that would be helpful too, but that would not be a requirement for this PR.)
```suggestion
  RP2040PIOLEDStripLightOutput::dma_chan_active_[this->dma_chan_] = true;
```

**Review by jesserockz — CHANGES_REQUESTED** [review]

**Comment by deCodeIt** [comment]
Addressed review changes by using class name to differentiate static class variables.

**Review by jesserockz — APPROVED** [review]
