### PR TITLE
[ultrasonic] Fix ISR edge detection with debounce and trigger filtering

### LINKED ISSUE #13861: Ultrasonic sensor "pulse end before pulse start" error on ESP32 after ESPHome 2025.1.x update
## The problem

After updating ESPHome from 2024.12.x to 2025.1.4, all my ultrasonic distance sensors (HC-SR04) stopped working correctly on ESP32. The sensors were working perfectly until mid-January 2025.

The error message is:
```
[W][ultrasonic.sensor:088]: 'Distanza Cassetto 1' - pulse end before pulse start, does the echo pin need to be inverted?
```

When measurements fail, the timeout values show integer overflow:
```
[D][ultrasonic.sensor:072]: 'Distanza Cassetto 2' - Measurement pulse timed out after 4294964007us
```

## Environment

- **ESPHome version with bug**: 2025.1.4
- **Last working version**: 2024.12.2
- **Installation type**: Home Assistant Add-on
- **ESP32 board**: ESP32-WROOM (generic esp32dev)
- **Sensor type**: HC-SR04 ultrasonic distance sensors (3 sensors)
- **Framework tested**: Both Arduino and ESP-IDF (both fail)

## Hardware setup

- 3x HC-SR04 ultrasonic sensors
- GPIO pins used:
  - Sensor 1: Trigger GPIO16, Echo GPIO17
  - Sensor 2: Trigger GPIO25, Echo GPIO26
  - Sensor 3: Trigger GPIO32, Echo GPIO33

## Configuration
```yaml
esp32:
  board: esp32dev
  variant: esp32
  framework:
    type: arduino

interval:
  - interval: 6s
    then:
      - component.update: distanza_cassetto_1
      - delay: 2s
      - component.update: distanza_cassetto_2
      - delay: 2s
      - component.update: distanza_cassetto_3

sensor:
  - platform: ultrasonic
    name: "Distance Sensor 1"
    id: distanza_cassetto_1
    trigger_pin: GPIO16
    echo_pin: GPIO17
    update_interval: never
    timeout: 3m
    pulse_time: 10us
    unit_of_measurement: "cm"
    filters:
      - multiply: 100
      - sliding_window_moving_average:
          window_size: 7
          send_every: 2
  # ... same for other 2 sensors
```

## Logs

With ESPHome 2025.1.4:
```
[11:38:50.859][W][ultrasonic.sensor:088]: 'Distanza Cassetto 3' - pulse end before pulse start, does the echo pin need to be inverted?
[11:38:51.421][W][ultrasonic.sensor:088]: 'Distanza Cassetto 1' - pulse end before pulse start, does the echo pin need to be inverted?
[11:38:51.632][W][ultrasonic.sensor:088]: 'Distanza Cassetto 2' - pulse end before pulse start, does the echo pin need to be inverted?
[11:38:52.859][W][ultrasonic.sensor:088]: 'Distanza Cassetto 3' - pulse end before pulse start, does the echo pin need to be inverted?
[11:38:52.865][D][sensor:129]: 'Distanza Cassetto 3' >> nan cm
[11:38:53.421][W][ultrasonic.sensor:088]: 'Distanza Cassetto 1' - pulse end before pulse start, does the echo pin need to be inverted?
[11:38:53.423][D][sensor:129]: 'Distanza Cassetto 1' >> nan cm
[11:38:53.633][W][ultrasonic.sensor:088]: 'Distanza Cassetto 2' - pulse end before pulse start, does the echo pin need to be inverted?
[11:38:53.636][D][sensor:129]: 'Distanza Cassetto 2' >> nan cm
[12:57:03.395][D][ultrasonic.sensor:072]: 'Distanza Cassetto 1' - Measurement pulse timed out after 4294963035us
[12:57:05.390][D][ultrasonic.sensor:072]: 'Distanza Cassetto 2' - Measurement pulse timed out after 4294964008us
```

## What I've tried

- ✅ Using `interval` with `component.update` to sequence sensor readings (2s delay between sensors)
- ✅ Switching from ESP-IDF to Arduino framework
- ✅ Increasing timeout values
- ✅ Setting explicit `pulse_time: 10us`
- ✅ Testing with `inverted: true` on echo pins (causes incorrect readings)
- ✅ Testing with only one sensor (still fails)
- ❌ None of these fixes work with ESPHome 2025.1.x

## Workaround

Downgrading to ESPHome 2024.12.2 fixes the issue completely. Compiling with Docker using the old version works perfectly:
```bash
docker run --rm -v ${PWD}:/config -it ghcr.io/esphome/esphome:2024.12.2 compile lavanderia-sensori.yaml
```

## Additional context

This appears to be a regression introduced between ESPHome 2024.12.x and 2025.1.x specifically affecting ultrasonic sensors on ESP32. The same hardware and configuration that worked flawlessly for months now fails completely after the update.

The integer overflow in timeout values (4294964007us ≈ 2^32) suggests a possible timing/interrupt handling issue in the ultrasonic sensor component.

### Which version of ESPHome has the issue?

2026.1.4

### What type of installation are you using?

Home Assistant Add-on

### What platform are you using?

ESP32

### Component causing the issue

ultrasonic

### YAML Config

```yaml
esphome:
  name: "lavanderia-sensori"
  friendly_name: lavanderia-sensori
  min_version: 2025.11.0
  name_add_mac_suffix: false

esp32:
  variant: esp32
  framework:
    type: esp-idf

# Enable logging
logger:

# Enable Home Assistant API
api:

# Allow Over-The-Air updates
ota:
- platform: esphome

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password

globals:
  - id: distanza_vuoto
    type: float
    restore_value: no
    initial_value: '75.0'

  - id: distanza_pieno
    type: float
    restore_value: no
    initial_value: '20.0'

interval:
  - interval: 6s
    then:
      - component.update: distanza_cassetto_1
      - delay: 2s
      - component.update: distanza_cassetto_2
      - delay: 2s
      - component.update: distanza_cassetto_3

sensor:
  - platform: ultrasonic
    name: "Distanza Cassetto 1"
    id: distanza_cassetto_1
    trigger_pin: GPIO16
    echo_pin: GPIO17
    update_interval: never  # Importante!
    timeout: 3m  # Aggiungi timeout più lungo
    pulse_time: 10us  # Aggiungi pulse time esplicito
    unit_of_measurement: "cm"
    filters:
      - multiply: 100
      - sliding_window_moving_average:
          window_size: 7
          send_every: 2

  - platform: ultrasonic
    name: "Distanza Cassetto 2"
    id: distanza_cassetto_2
    trigger_pin: GPIO25
    echo_pin: GPIO26
    update_interval: never  # Importante!
    timeout: 3m
    pulse_time: 10us
    unit_of_measurement: "cm"
    filters:
      - multiply: 100
      - sliding_window_moving_average:
          window_size: 7
          send_every: 2

  - platform: ultrasonic
    name: "Distanza Cassetto 3"
    id: distanza_cassetto_3
    trigger_pin: GPIO32
    echo_pin: GPIO33
    update_interval: never  # Importante!
    timeout: 3m
    pulse_time: 10us
    unit_of_measurement: "cm"
    filters:
      - multiply: 100
      - sliding_window_moving_average:
          window_size: 7
          send_every: 2

# --- SENSORI PERCENTUALE DI RIEMPIMENTO ---

  - platform: template
    name: "Riempimento Cassetto 1"
    unit_of_measurement: "%"
    accuracy_decimals: 0
    lambda: |-
      if (isnan(id(distanza_cassetto_1).state)) {
        return {};
      }
      float d = id(distanza_cassetto_1).state;
      float perc = (id(distanza_vuoto) - d)
                   / (id(distanza_vuoto) - id(distanza_pieno)) * 100.0;
      return clamp(perc, 0.0f, 100.0f);
    update_interval: 4s  # Più lungo per dare tempo al moving average
    filters:
      - sliding_window_moving_average:
          window_size: 3
          send_every: 1
      - or:
          - throttle: 10s
          - delta: 5.0

  - platform: template
    name: "Riempimento Cassetto 2"
    unit_of_measurement: "%"
    accuracy_decimals: 0
    lambda: |-
      if (isnan(id(distanza_cassetto_2).state)) {
        return {};
      }
      float d = id(distanza_cassetto_2).state;
      float perc = (id(distanza_vuoto) - d)
                   / (id(distanza_vuoto) - id(distanza_pieno)) * 100.0;
      return clamp(perc, 0.0f, 100.0f);
    update_interval: 4s  # Più lungo per dare tempo al moving average
    filters:
      - sliding_window_moving_average:
          window_size: 3
          send_every: 1
      - or:
          - throttle: 10s
          - delta: 5.0

  - platform: template
    name: "Riempimento Cassetto 3"
    unit_of_measurement: "%"
    accuracy_decimals: 0
    lambda: |-
      if (isnan(id(distanza_cassetto_3).state)) {
        return {};
      }
      float d = id(distanza_cassetto_3).state;
      float perc = (id(distanza_vuoto) - d)
                   / (id(distanza_vuoto) - id(distanza_pieno)) * 100.0;
      return clamp(perc, 0.0f, 100.0f);
    update_interval: 4s  # Più lungo per dare tempo al moving average
    filters:
      - sliding_window_moving_average:
          window_size: 3
          send_every: 1
      - or:
          - throttle: 10s
          - delta: 5.0
```

### Anything in the logs that might be useful for us?

```txt
[11:38:50.859][W][ultrasonic.sensor:088]: 'Distanza Cassetto 3' - pulse end before pulse start, does the echo pin need to be inverted?
[11:38:51.421][W][ultrasonic.sensor:088]: 'Distanza Cassetto 1' - pulse end before pulse start, does the echo pin need to be inverted?
[11:38:51.632][W][ultrasonic.sensor:088]: 'Distanza Cassetto 2' - pulse end before pulse start, does the echo pin need to be inverted?
[11:38:52.859][W][ultrasonic.sensor:088]: 'Distanza Cassetto 3' - pulse end before pulse start, does the echo pin need to be inverted?
[11:38:52.865][D][sensor:129]: 'Distanza Cassetto 3' >> nan cm
[11:38:53.421][W][ultrasonic.sensor:088]: 'Distanza Cassetto 1' - pulse end before pulse start, does the echo pin need to be inverted?
[11:38:53.423][D][sensor:129]: 'Distanza Cassetto 1' >> nan cm
[11:38:53.633][W][ultrasonic.sensor:088]: 'Distanza Cassetto 2' - pulse end before pulse start, does the echo pin need to be inverted?
[11:38:53.636][D][sensor:129]: 'Distanza Cassetto 2' >> nan cm
[12:57:03.395][D][ultrasonic.sensor:072]: 'Distanza Cassetto 1' - Measurement pulse timed out after 4294963035us
[12:57:05.390][D][ultrasonic.sensor:072]: 'Distanza Cassetto 2' - Measurement pulse timed out after 4294964008us
```

### Additional information

_No response_

### PR DESCRIPTION
**Pull request by swoboda1337**
# What does this implement/fix?

Fixes unreliable ultrasonic sensor readings caused by two issues in the ISR:

1. **Trigger bleed-through**: Some HC-SR04 clones echo the trigger pulse on the echo pin, causing the ISR to capture a false start edge. Added a 100us start delay filter after trigger to ignore these.

2. **Pin bounce on edges**: The `digital_read()` approach from #13738 can read the wrong pin level if the ISR fires during an edge transition bounce. Reverted to the debounce-based approach where timing determines which edge is start vs end — no pin level read needed.

The ISR now:
- Ignores all edges within 100us of trigger end (filters bleed-through)
- Uses 50us debounce: edges within 50us of echo_start re-stamp it (filters bounce)
- First valid edge after debounce = echo start
- Second valid edge = echo end

Also removes unused `echo_pin_isr` and `wait_start_us` from the store.

fixes https://github.com/esphome/esphome/issues/13861

## Types of changes

- [x] Bugfix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] Developer breaking change (an API change that could break external components)
- [ ] Undocumented C++ API change
- [ ] Code quality improvements to existing code or addition of tests
- [ ] Other

**Related issue or feature (if applicable):**

- Partial revert of #13738

**Pull request in [esphome-docs](https://github.com/esphome/esphome-docs) with documentation (if applicable):**

- N/A

## Test Environment

- [x] ESP32
- [x] ESP32 IDF
- [ ] ESP8266
- [ ] RP2040/RP2350
- [ ] BK72xx
- [ ] RTL87xx
- [ ] LN882x
- [ ] nRF52840

## Example entry for config.yaml:

No config changes required.

## Checklist:
  - [x] The code change is tested and works locally.
  - [x] Tests have been added to verify that the new code works (under tests/ folder).

### CODE REVIEW

File: esphome/components/ultrasonic/ultrasonic_sensor.cpp [hunk 1]
```diff
@@ -6,11 +6,17 @@ namespace esphome::ultrasonic {
...
+static constexpr uint32_t START_DELAY_US = 100;      // Ignore edges within 100us of trigger (filters bleed-through)
 static constexpr uint32_t START_TIMEOUT_US = 40000;  // Maximum time to wait for echo pulse to start
 
 void IRAM_ATTR UltrasonicSensorStore::gpio_intr(UltrasonicSensorStore *arg) {
   uint32_t now = micros();
-  if (arg->echo_pin_isr.digital_read()) {
+  // Ignore edges too soon after trigger pulse
+  if ((now - arg->measurement_start_us) <= START_DELAY_US) {
+    return;
+  }
```
Comment (bdraco) [inline esphome/components/ultrasonic/ultrasonic_sensor.cpp:18]: copilot had a  `comments suppressed due to low confidence (1) ` that might be a real issue

`echo_start_us` is accepted even if `echo_end` is true

should this return early if `arg->echo_end` is true?

Comment (bdraco) [reply esphome/components/ultrasonic/ultrasonic_sensor.cpp:18]: nah I think it can't actually happen because `send_trigger_pulse_` holds the lock the whole time.

Comment (bdraco) [reply esphome/components/ultrasonic/ultrasonic_sensor.cpp:18]: but it could fire after that.. probably safer to add the check.

Comment (swoboda1337) [reply esphome/components/ultrasonic/ultrasonic_sensor.cpp:18]: done

**Review by bdraco — APPROVED** [review]

**Comment by swoboda1337** [comment]
Thanks
