### PR TITLE
[sps30] Add idle mode functionality

### LINKED ISSUE #2133: SPS30 Particulate Matter Sensor - implement idle mode
**Describe the problem you have/What new integration you would like**

I was able to successfully implement SPS30 Particulate Matter Sensor. 
https://esphome.io/components/sensor/sps30.html
First point - the wiring diagram is incorrect. There is switched SEL and GND pin [(see page 4)](https://eu.mouser.com/datasheet/2/682/seri_s_a0010891602_1-2291035.pdf). But since both must be connected to GND, it didn't cause issues so far.

The problem is:
Measurement works fine. However I observed that fan inside is constantly spinning - I can feel vibrations inside sensor. I configured update_interval to 300s.
According to documentation, fan should spin only during the measurement. In idle mode fan has to be turned off.
https://sensirion.com/media/documents/188A2C3C/6166F165/Sensirion_Particulate_Matter_AppNotes_SPS30_Low_Power_Operation_D1.pdf

So it looks like sensor is constantly in measurement mode. This will definitively raise power consumption.  I am not sure but this may also reduce the sensor lifetime that is currently rated on 8-10 years with non-constant measurement mode.

According to documentation is obvious that is good when fan is spinning some time (around 15-30s) before measurement is taken.

As a solution, would be good to be able define also time how long must fan run before measurement is taken (or multiple averaged measurements are taken). If update interval is 300s and measurement interval is 30s, then it will be in measurement mode 30s and rest 270s will be in idle mode with reduced consumption.

**Please describe your use case for this integration and alternatives you've tried:**

**Additional context**

### PR DESCRIPTION
**Pull request by c0mputerguru**
Supersedes #6828 

# What does this implement/fix?

Adds functionality to put SPS30 sensor into idle mode.  This can be done manually as an action or in a idle/wake/warm-up/read/idle loop by specifying the `idle_interval` configuration parameter.

This is useful as the SPS30 sensor when running in continuous mode always has its fan on.  To improve energy usage as well as prolong the life of the sensor, it can be put into idle mode where measurements are no longer taken.

When measurement is started again, the [documentation](https://sensirion.com/media/documents/188A2C3C/6166F165/Sensirion_Particulate_Matter_AppNotes_SPS30_Low_Power_Operation_D1.pdf) states that there is a warm up period of up to 30 seconds.

Note that this warm-up period is applied whether or not the idle_interval is specified.  This is the only change in behavior compared to status quo, but any readings taken prior to sensor warm-up were not necessarily accurate, so this change may remove some inaccurate readings, so I don't consider this a breaking change.

Inspiration for this change:
https://community.home-assistant.io/t/ignoring-sensor-values-during-warm-up-after-periodic-wake-up/245401/9
https://github.com/tiimsvk/SPS30-idle-mode

## Types of changes

- [ ] Bugfix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] Other

**Related issue or feature (if applicable):** fixes https://github.com/esphome/feature-requests/issues/2133

**Pull request in [esphome-docs](https://github.com/esphome/esphome-docs) with documentation (if applicable):** esphome/esphome-docs#5713

## Test Environment

- [x] ESP32
- [ ] ESP32 IDF
- [ ] ESP8266
- [ ] RP2040
- [ ] BK72xx
- [ ] RTL87xx

## Example entry for `config.yaml`:

```yaml
# Example config.yaml
sensor:
  - platform: sps30
    id: particulate
    update_interval: 1s
    idle_interval: 5min
    pm_1_0:
      name: "PM <1µm Weight concentration"
      id: "PM_1_0"
    pm_2_5:
      name: "PM <2.5µm Weight concentration"
      id: "PM_2_5"
    pm_4_0:
      name: "PM <4µm Weight concentration"
      id: "PM_4_0"
    pm_10_0:
      name: "PM <10µm Weight concentration"
      id: "PM_10_0"
    pmc_0_5:
      name: "PM <0.5µm Number concentration"
      id: "PMC_0_5"
    pmc_1_0:
      name: "PM <1µm Number concentration"
      id: "PMC_1_0"
    pmc_2_5:
      name: "PM <2.5µm Number concentration"
      id: "PMC_2_5"
    pmc_4_0:
      name: "PM <4µm Number concentration"
      id: "PMC_4_0"
    pmc_10_0:
      name: "PM <10µm Number concentration"
      id: "PMC_10_0"
    pm_size:
      name: "Typical Particle size"
      id: "pm_size"
```

## Checklist:
  - [x] The code change is tested and works locally.
  - [ ] Tests have been added to verify that the new code works (under `tests/` folder).

If user exposed functionality or configuration variables are added/changed:
  - [x] Documentation added/updated in [esphome-docs](https://github.com/esphome/esphome-docs).

### CODE REVIEW

**Comment by bdraco** [comment]
Compile coverage is missing.

Please add `idle_interval: 5min` to common.yaml

File: esphome/components/sps30/sps30.cpp [hunk 1]
```diff
@@ -132,6 +135,29 @@ void SPS30Component::update() {
...
+  switch (this->next_state_) {
+    case WAKE:
+      this->start_measurement();
+      return;
+    case IDLE:
+    // Idle happens at the end of reading, so go through another read.
+    case READ:
+      if (this->idle_interval_.has_value()) {
+        this->next_state_ = IDLE;
+      }
```
Comment (bdraco) [inline esphome/components/sps30/sps30.cpp]: This logic is a bit confusing. If its IDLE it falls though to read and sets IDLE?

Comment (bdraco) [reply esphome/components/sps30/sps30.cpp]: Shouldn't it just break ?

File: esphome/components/sps30/sps30.cpp [hunk 2]
```diff
@@ -219,6 +252,25 @@ bool SPS30Component::start_continuous_measurement_() {
...
+bool SPS30Component::stop_measurement() {
+  if (!write_command(SPS30_CMD_STOP_MEASUREMENTS)) {
+    ESP_LOGE(TAG, "Error stopping measurements");
+  } else {
+    ESP_LOGD(TAG, "Stopped measurements");
+    // Exit the state machine if measurement is stopped.
+    this->next_state_ms_ = 0;
+    this->next_state_ = NONE;
+  }
   return true;
```
Comment (bdraco) [inline esphome/components/sps30/sps30.cpp:278]: This is confusing as this always returns true when it fails and is never checked

File: esphome/components/sps30/sps30.h [hunk 3]
```diff
@@ -23,17 +23,23 @@ class SPS30Component : public PollingComponent, public sensirion_common::Sensiri
 
   void set_pm_size_sensor(sensor::Sensor *pm_size) { pm_size_sensor_ = pm_size; }
   void set_auto_cleaning_interval(uint32_t auto_cleaning_interval) { fan_interval_ = auto_cleaning_interval; }
+  void set_idle_interval(uint32_t idle_interval) { idle_interval_ = idle_interval; }
   void setup() override;
   void update() override;
   void dump_config() override;
```
Comment (bdraco) [inline esphome/components/sps30/sps30.h:29]: Please update dump_config with something like
```
  if (this->idle_interval_.has_value()) {
    ESP_LOGCONFIG(TAG, "  Idle Interval: %us", this->idle_interval_.value() / 1000);
  }
```

File: esphome/components/sps30/sps30.cpp [hunk 4]
```diff
@@ -132,6 +135,29 @@ void SPS30Component::update() {
...
+
+  switch (this->next_state_) {
+    case WAKE:
+      this->start_measurement();
+      return;
+    case IDLE:
+    // Idle happens at the end of reading, so go through another read.
+    case READ:
+      if (this->idle_interval_.has_value()) {
+        this->next_state_ = IDLE;
```
Comment (bdraco) [inline esphome/components/sps30/sps30.cpp]: should we set next_state_ms_ here as well?

File: esphome/components/sps30/sps30.h [hunk 5]
```diff
@@ -23,17 +23,23 @@ class SPS30Component : public PollingComponent, public sensirion_common::Sensiri
...
+  bool start_measurement();
 
  protected:
   bool setup_complete_{false};
   uint16_t raw_firmware_version_;
   char serial_number_[17] = {0};  /// Terminating NULL character
   uint8_t skipped_data_read_cycles_ = 0;
+  uint32_t next_state_ms_ = 0;
+
+  enum NextState { IDLE, WAKE, READ, NONE } next_state_{NONE};
```
Comment (bdraco) [inline esphome/components/sps30/sps30.h]: should be uint8_t like ErrorCode

File: esphome/components/sps30/sps30.cpp (hunk 1 above)
Comment (c0mputerguru) [reply esphome/components/sps30/sps30.cpp]: Honestly, it's been way more than a year that I looked at this code, so I'm a little hazy on the details, but agree that it is confusing.

I think my initial implementation had the call to `stop_measurement` in the `IDLE` case statement, but the problem with that was after a read, it had to wait a whole `update_interval` (default 60s) to actually stop the fan.  So I moved that logic to the end of the `READ` so it would happen right away after a reading was taken.

From what I can tell, that `IDLE` case should only execute when a `READ` update doesn't actually get a reading or if the `update_interval` is shorter than how long it takes to actually perform the read.  I think in both cases, the semantic logic should be that if the next state is `IDLE` it should do the same thing as if the next state is `READ`.

Having it break is the same today, but if that ever changes, I think the right logic is for it to fall through to `READ`.  I've updated the comment to hopefully clarify a bit better.

File: esphome/components/sps30/sps30.cpp (hunk 2 above)
Comment (c0mputerguru) [reply esphome/components/sps30/sps30.cpp:278]: Added the failure return case; must have been a miss on my part as I can't think of a reason I would have done that.

File: esphome/components/sps30/sps30.h (hunk 3 above)
Comment (c0mputerguru) [reply esphome/components/sps30/sps30.h:29]: Done.

File: esphome/components/sps30/sps30.cpp (hunk 4 above)
Comment (c0mputerguru) [reply esphome/components/sps30/sps30.cpp]: See my comment above about why IDLE execution was moved to the end of a successful read.  Since this pass is a read pass, we shouldn't have the state machine sleep any longer in case a read fails, but to retry the read on the next update.

File: esphome/components/sps30/sps30.h (hunk 5 above)
Comment (c0mputerguru) [reply esphome/components/sps30/sps30.h]: Done.

**Review by bdraco — DISMISSED** [review]

**Comment by bdraco** [comment]
@martgras Any comments before merging?

**Comment by SeveranExp** [comment]
Omg you guys made my Christmas night sooner than expected 🤣 lovely! I got two sps30 to try out now too!

**Comment by swoboda1337** [comment]
> @martgras Any comments before merging?

That gh account seems inactive.

File: esphome/components/sps30/sps30.cpp [hunk 6]
```diff
@@ -132,6 +138,30 @@ void SPS30Component::update() {
     }
     return;
   }
+
+  // If its not time to take an action, do nothing.
+  if (millis() < this->next_state_ms_) {
+    ESP_LOGD(TAG, "Sensor waiting for %ums before transitioning to state %d.", (this->next_state_ms_ - millis()),
+             this->next_state_);
+    return;
+  }
```
Comment (swoboda1337) [inline esphome/components/sps30/sps30.cpp]: It doesn't look like `next_state_ms_` is not set anywhere when `idle_interval_` has no value. Seems to be set in setup but then never again. Unless I am missing something  this will block measurements when its not supposed to.

**Review by swoboda1337 — CHANGES_REQUESTED** [review]

File: esphome/components/sps30/sps30.cpp [hunk 7]
```diff
@@ -132,6 +138,30 @@ void SPS30Component::update() {
     }
     return;
   }
+
+  // If its not time to take an action, do nothing.
+  if (millis() < this->next_state_ms_) {
```
Comment (swoboda1337) [inline esphome/components/sps30/sps30.cpp]:
```suggestion
  if ((int32_t) (this->next_state_ms_ - millis()) > 0) {
```

If `next_state_ms_` rolls over to say 0, this will not block like it is supposed to. Need to do a subtract here. Rolling counters can never be compared without a subtraction to account for the rollover.

**Review by swoboda1337 — CHANGES_REQUESTED** [review]

File: esphome/components/sps30/sps30.cpp (hunk 6 above)
Comment (bdraco) [reply esphome/components/sps30/sps30.cpp]: The code could be made more clear, but I think it does work as intended besides the rollover issue.

https://github.com/esphome/esphome/pull/12255/files#diff-54fcf22b0c42372ec6638c3e79ae967bcf459e616be77b99416302c077c47ba4R67 should always set it at setup time

So `millis()` >= `next_state_ms_` will always be true after the first read

Comment (swoboda1337) [reply esphome/components/sps30/sps30.cpp]: Until `millis()` rolls over and is < `next_state_ms_`

Comment (bdraco) [reply esphome/components/sps30/sps30.cpp]: But yes this case has the rollover problem as well

Comment (swoboda1337) [reply esphome/components/sps30/sps30.cpp]: Unless `next_state_ms_` is 0 there it will be blocked when it shouldnt be

Comment (bdraco) [reply esphome/components/sps30/sps30.cpp]: Would be cleaner to skip the timer check when not in idle mode

Comment (c0mputerguru) [reply esphome/components/sps30/sps30.cpp]: The timer check is still used when not in idle mode to do the initial warmup.  That isn't done in the current implementation, but is still technically necessary based on the sensors specs.

Comment (c0mputerguru) [reply esphome/components/sps30/sps30.cpp]: Good catch on the rollover issue; I hadn't even considered that.

Let me think about the best way to handle it, but given that millis() and the next_state_ms_ should rollover at the same time, the only case where it will block when it is not supposed to is when it rolls over when the idle mode is not active and it's within the rolled over warm-up period.  So once every 50ish days it may wait an extra update_interval if it updates within 30s of the rollover.

File: esphome/components/sps30/sps30.cpp [hunk 8]
```diff
@@ -211,6 +241,13 @@ void SPS30Component::update() {
 
     this->status_clear_warning();
     this->skipped_data_read_cycles_ = 0;
+
+    // Idle if we got a reading and our next state is to idle
+    if (this->next_state_ == IDLE && millis() >= this->next_state_ms_) {
```
Comment (c0mputerguru) [inline esphome/components/sps30/sps30.cpp]: (note to self) This also needs to be updated to handle rollover.

File: esphome/components/sps30/sps30.cpp (hunk 6 above)
Comment (swoboda1337) [reply esphome/components/sps30/sps30.cpp]: Yep its not often but still a bug :)

Can just set a timeout in setup

Comment (c0mputerguru) [reply esphome/components/sps30/sps30.cpp]: Yeah, didn't mean to say we should keep the bug, just why I hadn't come across it in the year+ of having this code running.

Not sure what you mean by setting a timeout in setup; can you elaborate a bit more?

Comment (c0mputerguru) [reply esphome/components/sps30/sps30.cpp]: Also, even if idle mode isn't enabled, using the start/stop actions would still require the warm-up.

Comment (swoboda1337) [reply esphome/components/sps30/sps30.cpp]: Right. Can add a flag to indicate its waiting I guess

File: esphome/components/sps30/sps30.cpp [hunk 9]
```diff
@@ -211,6 +241,13 @@ void SPS30Component::update() {
 
     this->status_clear_warning();
     this->skipped_data_read_cycles_ = 0;
+
+    // Idle if we got a reading and our next state is to idle
+    if (this->next_state_ == IDLE && ((int32_t) (this->next_state_ms_ - millis()) <= 0)) {
```
Comment (swoboda1337) [inline esphome/components/sps30/sps30.cpp]: Is the millis check needed here. Should have already been checked above.

File: esphome/components/sps30/sps30.cpp (hunk 6 above)
Comment (c0mputerguru) [reply esphome/components/sps30/sps30.cpp]: I think it's probably cleaner to just keep updating the `next_state_ms_` even in the case that idle mode is not enabled rather than introduce yet another state variable.

File: esphome/components/sps30/sps30.cpp (hunk 9 above)
Comment (c0mputerguru) [reply esphome/components/sps30/sps30.cpp]: Good point, removed.

File: esphome/components/sps30/sps30.cpp (hunk 6 above)
Comment (c0mputerguru) [reply esphome/components/sps30/sps30.cpp]: I did a bit of simplification by removing IDLE as an explicit state in the state machine and keeping next_state_ms_ updated with every read.

File: esphome/components/sps30/sps30.cpp [hunk 10]
```diff
@@ -132,6 +138,25 @@ void SPS30Component::update() {
     }
     return;
   }
+
+  // If its not time to take an action, do nothing.
+  if ((int32_t) (this->next_state_ms_ - millis()) > 0) {
+    ESP_LOGD(TAG, "Sensor waiting for %ums before transitioning to state %d.", (this->next_state_ms_ - millis()),
```
Comment (swoboda1337) [inline esphome/components/sps30/sps30.cpp]: This could show a negative number or 0 if millis changes between the if an the print. Could cache millis at the start of the function or use App.get_loop_component_start_time();

Comment (c0mputerguru) [reply esphome/components/sps30/sps30.cpp]: Cached.

File: esphome/components/sps30/sps30.cpp [hunk 11]
```diff
@@ -132,6 +138,26 @@ void SPS30Component::update() {
...
+             this->next_state_);
+    return;
+  }
+
+  switch (this->next_state_) {
+    case WAKE:
+      this->start_measurement();
+      return;
+    case NONE:
+      return;
```
Comment (swoboda1337) [inline esphome/components/sps30/sps30.cpp:155]: Not updating `next_state_ms_` in the case of NONE, maybe can call `stop_poller/start_poller`? It might print confusing prints in this case.

**Review by swoboda1337 — CHANGES_REQUESTED** [review]

**Review by swoboda1337 — APPROVED** [review]

File: esphome/components/sps30/sps30.cpp [hunk 12]
```diff
@@ -132,6 +138,26 @@ void SPS30Component::update() {
...
```
Comment (bdraco) [inline esphome/components/sps30/sps30.cpp:155]: Much nicer 👍

**Review by bdraco — APPROVED** [review]
Thanks @c0mputerguru @swoboda1337 

Definitely a lot better from when I last looked 👍

**Comment by swoboda1337** [comment]
Thanks

**Comment by bruvv** [comment]
And thanks also from me as an end user!
