### PR TITLE
[esp32] Bump IDF version to 5.5.1 and Arduino version to 3.3.2

### LINKED ISSUE #60: Move to IDF 5.5
Main issues:
- The pioarduino 55 platform required .platformio to be cleaned when moving from 54 or after libretiny. Issue as been root caused and fixed in https://github.com/pioarduino/platform-espressif32.git#develop waiting for a release: https://discord.com/channels/1263397951829708871/1263406018235203686/1420089393997287586
- Arduino 3.3 based on 5.5 uses NimBLE which we don't support, need to use Arduino as a component. This is done.
- Arduino 3.3.1 has a compile issue, fixed after issue filed, waiting for a patch release. 

PR is ready just waiting for the above releases.

### LINKED ISSUE #10978: esp_idf_size: error: unrecognized arguments: --ng
### The problem

Linking .pioenvs/gdo/firmware.elf
usage: esp_idf_size [-h] [--format {table,text,tree,csv,json2,raw,dot}]
                    [--archives] [--archive-dependencies] [--dep-symbols]
                    [--dep-reverse] [--archive-details ARCHIVE_NAME] [--files]
                    [--diff MAP_FILE] [--no-abbrev] [--unify] [--show-unused]
                    [--show-unchanged] [--use-flash-size] [--lto] [-d]
                    [-o OUTPUT_FILE] [-s COLUMN] [-F PATTERN] [--sort-diff]
                    [--sort-reverse] [-q] [--no-color] [--force-terminal]
                    [--doc]
                    MAP_FILE
esp_idf_size: error: unrecognized arguments: --ng
Warning: esp-idf-size exited with code 2

### Which version of ESPHome has the issue?

2025.9.3

### What type of installation are you using?

Home Assistant Add-on

### What platform are you using?

ESP32

### Component causing the issue

_No response_

### YAML Config

```yaml
During building all my devices, including bt_proxy:

Linking .pioenvs/gdo/firmware.elf
usage: esp_idf_size [-h] [--format {table,text,tree,csv,json2,raw,dot}]
                    [--archives] [--archive-dependencies] [--dep-symbols]
                    [--dep-reverse] [--archive-details ARCHIVE_NAME] [--files]
                    [--diff MAP_FILE] [--no-abbrev] [--unify] [--show-unused]
                    [--show-unchanged] [--use-flash-size] [--lto] [-d]
                    [-o OUTPUT_FILE] [-s COLUMN] [-F PATTERN] [--sort-diff]
                    [--sort-reverse] [-q] [--no-color] [--force-terminal]
                    [--doc]
                    MAP_FILE
esp_idf_size: error: unrecognized arguments: --ng
Warning: esp-idf-size exited with code 2
```

### Anything in the logs that might be useful for us?

```txt

```

### Additional information

_No response_

### PR DESCRIPTION
**Pull request by swoboda1337**
# What does this implement/fix?

Merge https://github.com/esphome/esphome/pull/11170 first

ESP-IDF Release v5.5.1: https://github.com/espressif/esp-idf/releases/tag/v5.5.1
Arduino Release v3.3.1 based on ESP-IDF v5.5.1: https://github.com/espressif/arduino-esp32/releases/tag/3.3.2
Platform: https://github.com/pioarduino/platform-espressif32/releases/tag/55.03.31-1

To use:
```
  framework:
    type: esp-idf
    version: 5.5.1
    platform_version: 55.03.31-1
```
or:
```
  framework:
    type: arduino
    version: 3.3.2
    platform_version: 55.03.31-1
```

## Types of changes

- [ ] Bugfix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] Code quality improvements to existing code or addition of tests
- [x] Other

**Related issue or feature (if applicable):**

- resolves https://github.com/esphome/backlog/issues/60
- fixes https://github.com/esphome/esphome/issues/10978

**Pull request in [esphome-docs](https://github.com/esphome/esphome-docs) with documentation (if applicable):**

- esphome/esphome-docs#<esphome-docs PR number goes here>

## Test Environment

- [ ] ESP32
- [x] ESP32 IDF
- [ ] ESP8266
- [ ] RP2040
- [ ] BK72xx
- [ ] RTL87xx
- [ ] nRF52840

## Example entry for `config.yaml`:

```yaml
# Example config.yaml

```

## Checklist:
  - [x] The code change is tested and works locally.
  - [ ] Tests have been added to verify that the new code works (under `tests/` folder).

If user exposed functionality or configuration variables are added/changed:
  - [ ] Documentation added/updated in [esphome-docs](https://github.com/esphome/esphome-docs).

### CODE REVIEW

File: esphome/components/espnow/espnow_packet.h [hunk 1]
```diff
@@ -49,7 +49,7 @@ class ESPNowPacket {
 #if ESP_IDF_VERSION >= ESP_IDF_VERSION_VAL(5, 5, 0)
   // Constructor for sent data
   ESPNowPacket(const esp_now_send_info_t *info, esp_now_send_status_t status) {
-    this->init_sent_data(info->src_addr, status);
+    this->init_sent_data_(info->src_addr, status);
```
Comment (swoboda1337) [inline esphome/components/espnow/espnow_packet.h:52]: FYI @nielsnl68

**Comment by swoboda1337** [comment]
Hosted component seems like it needs to be bumped, p4 builds fail

**Comment by bdraco** [comment]
+3100 K RAM free on Arduino
+3300 K RAM free on pure IDF

**Comment by swoboda1337** [comment]
Arduino has a bug causing compile issues: https://github.com/espressif/arduino-esp32/issues/11857
Seems platform 55.03.31 still has issues and cant find python sometimes.

**Comment by swoboda1337** [comment]
https://github.com/pioarduino/platform-espressif32/blob/55.03.31/builder/penv_setup.py#L92
https://github.com/pioarduino/platform-espressif32/blob/55.03.31/builder/penv_setup.py#L427

It seems that if ~/.platformio/penv exists pioarduino won't try to create its python venv however that path almost always exists as it contains ~/.platformio/penv/.espidf-5.4.2 and ~/.platformio/penv/.libretiny etc etc

Will try to get pioarduino to put its venv here: ~/.platformio/penv/.pioarduino instead of the root folder.

**Comment by swoboda1337** [comment]
Fix will be added to pioarduino: https://discord.com/channels/1263397951829708871/1263406018235203686/1420078439607570583

**Comment by bdraco** [comment]
Once we have this we can Disable [CONFIG_LIBC_LOCKS_PLACE_IN_IRAM](https://docs.espressif.com/projects/esp-idf/en/stable/esp32/api-reference/kconfig-reference.html#config-libc-locks-place-in-iram) and save another ~1KB of RAM (probably as esp32 advanced option defaulting to disabled.. as I doubt this is being used)

**Comment by swoboda1337** [comment]
Waiting for Arduino to make a patch release to fix the compile issue. Pioarduino will then release with it's fix. They said this should happen soon.

**Comment by edurenye** [comment]
Please, since you are already on it, can you bump the platform to 55.03.32 (https://github.com/pioarduino/platform-espressif32/releases/tag/55.03.32) to fix this other issue: https://github.com/esphome/esphome/issues/10978 ?

Thank you!

**Review by bdraco — DISMISSED** [review]

**Comment by bdraco** [comment]
Missed mipi_rgb single case. fixed in https://github.com/esphome/esphome/pull/11185

File: esphome/components/esp32/__init__.py [hunk 2]
```diff
@@ -363,7 +363,7 @@ def _is_framework_url(source: str) -> str:
 # The platform-espressif32 version
 #  - https://github.com/pioarduino/platform-espressif32/releases
 PLATFORM_VERSION_LOOKUP = {
-    "recommended": cv.Version(54, 3, 21, "2"),
+    "recommended": cv.Version(55, 3, 31, "1"),
```
Comment (jesserockz) [inline esphome/components/esp32/__init__.py:366]: Wouldnt this go to 55.3.32 to match 3.3.2?

Comment (swoboda1337) [reply esphome/components/esp32/__init__.py:366]: Arduino 55.3.32 used some random point in IDF master, its not based on IDF 5.5.1 see https://github.com/pioarduino/esp-idf/releases/tag/v5.5.1.250929

Unfortunately IDF bumped the compiler versions in master which makes 55.3.32 incompatible with the official IDF 5.5.1. It would be a pain to use 5.5.1.250929 as the IDF version. We also cant use Arduino 3.3.1 as it has compile errors on S3 which I can't work around. 

Makes the most sense to compile Arduino 3.3.2 with the real IDF 5.5.1 on 55.3.31-1

Comment (swoboda1337) [reply esphome/components/esp32/__init__.py:366]: If you try to compile 5.5.1 with 55.3.32 you get:
```
  Tool doesn't match supported version from list ['esp-14.2.0_20241119']:
  /home/jon/.platformio/packages/toolchain-xtensa-esp-elf/bin/xtensa-esp32-elf-gcc

  Please try to run 'idf.py fullclean' to solve it.
  ```

**Review by bdraco — APPROVED** [review]

**Comment by bdraco** [comment]
Let's do it. Hopefully we don't get too many regressions.

**Comment by bdraco** [comment]
also marked https://github.com/esphome/esphome/pull/10930 ready now
