### PR TITLE
[pulse_meter] Fix early edge detection

### LINKED ISSUE #10605: Pulse_meter with filter_mode_ == FILTER_PULSE leads to wrong pulse detection
### The problem

The problem and a potential solution is explained in this thread:

[Forum post](https://community.home-assistant.io/t/pulse-meter-seems-to-be-buggy/927035/14)

### Which version of ESPHome has the issue?

2025.8.3

### What type of installation are you using?

Docker

### What platform are you using?

ESP8266

### Component causing the issue

pulse_meter

### YAML Config

```yaml
esphome:
  name: stromzaehler
  friendly_name: Stromzähler

esp8266:
  board: d1_mini

# Enable logging
logger:
  level: VERBOSE

ota:
  - platform: esphome
    password: "4271de215c26d9a935fd0b0387717b6f"

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password

  # Enable fallback hotspot (captive portal) in case wifi connection fails
  ap:
    ssid: "Stromzahler Fallback Hotspot"
    password: "BB2pv48pNdCZ"

captive_portal:

substitutions:
  pulses_per_kWh: 96.0

# Configuration entry
sensor:
  # Used for testing and validation purposes
  #- platform: adc
  #  pin: GPIO17
  #  name: "Electricity Meter Analog Voltage Signal"
  #  update_interval: 100ms

  # Used for Energy Monitoring
  - platform: pulse_meter
    name: 'Electricity Power Usage'
    id: sensor_pulse_meter
    #unit_of_measurement: 'kW'
    device_class: power
    state_class: measurement
    internal_filter: 1s
    internal_filter_mode: PULSE
    accuracy_decimals: 3
    pin: D5
    #filters:
    #  - multiply: !lambda return 60.0 / ${pulses_per_kWh};

    total:
      name: "Electricity Energy Usage"
      #unit_of_measurement: 'kWh'
      accuracy_decimals: 1 
    #  filters:
    #    - multiply: !lambda return 1.0 / ${pulses_per_kWh};
    
    #on_raw_value: 
    #  then:
    #    - lambda: |-
    #        ESP_LOGD("custom", "Raw_value: %.5f >> Period of %.1f s", x, 60 / x );
    #        id(sensor_pulse_meter).set_filter_us((60.0f * 1000000.0f) / x / 5.0f);
    #      # Set the internal filter to 1/10 of the pulse period

# Enable Home Assistant API
api:
  encryption:
    key: "5Qj5gYvGeF22aWOrEXsf4eavx09TJ+ELhXzjuszCSe0="

  # Setting the total pulse count
  actions:
    - action: set_total
      variables:
        new_total: int
      then:
        - pulse_meter.set_total_pulses:
            id: sensor_pulse_meter
            value: !lambda 'return new_total;'
```

### Anything in the logs that might be useful for us?

```txt
[13:28:22][V][pulse_meter:099]: New pulse, delta: 4294963626 µs, count: 1, width: 4294963712.00000 µs
[13:28:22][V][sensor:051]: 'Electricity Power Usage': Received new state 0.013970
[13:28:22][D][sensor:103]: 'Electricity Power Usage': Sending state 0.01397 pulses/min with 3 decimals of accuracy
[13:31:15][V][pulse_meter:099]: New pulse, delta: 9222 µs, count: 1, width: 9222.00000 µs
[13:31:15][V][sensor:051]: 'Electricity Power Usage': Received new state 6506.180664
[13:31:15][D][sensor:103]: 'Electricity Power Usage': Sending state 6506.18066 pulses/min with 3 decimals of accuracy
```

### Additional information

_No response_

### LINKED ISSUE #12319: Getting random "inf" states from a pulse_meter sensor, time accounting issues?
### The problem

This appears to be the issue described here:  https://github.com/esphome/issues/issues/6683,  However I'm in a position to do a little more debugging.

I'm working through the [Power Meter](https://www.esphome.io/cookbook/power_meter/) cookbook recipe and am observing issues where the returned value is `inf`.

After reading esphome/issues#6683 I extended the debug logging with a simple patch [here](https://github.com/esphome/esphome/compare/dev...whitty:emerald_ble:bugfix/pulse_meter_inf) which will be apparent in the log snippets.  Looking through the code I was fairly suspicious of the Peek/Repay sequencing hence the logging changes, however its unclear if they are directly or only indirectly involved.

Working backward from sending `inf` we see a pulse of width `0` (hence `inf`).  

Backtracking we see in the same processing `loop()` we have a "Peeked" edge that sets the last detected edge to the last rising edge, then when we compare that to the processed edge its the same.  Now I'm not sure I understand the intended logic behind the Peeked and Repaid edge, however my best guess is one of:

1. the edge-detect for the peeking may only apply in `EDGE` filter mode, but I'm using `PULSE`.
2. the peeking should perhaps also be gated by `this->get_->last_rising_edge_us_ > this->last_processed_edge_us_` to ensure whatever logic we are in is not re-dispatching the same edge.  Since I don't understand the intended entry logic for Peeking I'm not sure about this.

```
[20:30:09.988][V][pulse_meter:105]: New pulse, delta: 2080380 µs, count: 1, width: 2080380.00000 µs, last-detected=821691387µs, @821707055
[20:30:10.683][D][sensor:133]: 'Total Pulses': Sending state 225.62500 Wh with 4 decimals of accuracy
[20:30:12.064][V][pulse_meter:077]: Peeked Edge, detected: 821691387 µs, rising: 823785824µs, delt: 2091µs, count: 0 @823787915
[20:30:12.069][V][pulse_meter:105]: New pulse, delta: 2094437 µs, count: 1, width: 2094437.00000 µs, last-detected=823785824µs, @823787915
[20:30:12.116][V][pulse_meter:069]: Repay Edge, @823800952 µs, count: 1
[20:30:14.188][V][pulse_meter:105]: New pulse, delta: 2116055 µs, count: 1, width: 2116055.00000 µs, last-detected=825901879µs, @825914130
[20:30:16.311][V][pulse_meter:105]: New pulse, delta: 2108308 µs, count: 1, width: 2108308.00000 µs, last-detected=828010187µs, @828026761
[20:30:16.311][V][pulse_meter:077]: Peeked Edge, detected: 823785824 µs, rising: 828010187µs, delt: 21858µs, count: 0 @828032045
[20:30:16.313][V][pulse_meter:105]: New pulse, delta: 0 µs, count: 1, width: 0.00000 µs, last-detected=828010187µs, @828032045
[20:30:18.460][V][pulse_meter:069]: Repay Edge, @830144935 µs, count: 1
[20:30:18.995][D][sensor:133]: 'Pulse Meter': Sending state inf W with 1 decimals of accuracy
```

I'm suspicious this only happens when scheduling delay elsewhere runs `loop()` back-to-back - though I can't prove that.

Larger context - there's likely some clock/dispatch variation on the `loop` dispatch due to other tasks - `bluetooth_proxy`/`ble_tracker` doing scanning for Bermuda with a significant active scan time. 

### Which version of ESPHome has the issue?

2025.11.4

### What type of installation are you using?

Home Assistant Add-on

### What platform are you using?

ESP32

### Component causing the issue

pulse_meter

### YAML Config

```yaml
esphome:
  name: atoms3lite
  friendly_name: AtomS3Lite

  on_boot:
    priority: 600
    then:
      - logger.set_level: DEBUG
      - logger.set_level:
          level: VERBOSE
          tag: pulse_meter

# Enable logging
logger:
  level: VERBOSE

# Enable Home Assistant API
api:
  encryption:
    key:

ota:
  - platform: esphome
    password:

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password


light:
  #G35=RGB WS2812C-2020
  - platform: esp32_rmt_led_strip
    rgb_order: GRB
    pin: 35
    num_leds: 4
    # rmt_symbols can add up to 196 between these channels
    rmt_symbols: 48
    chipset: ws2812
    id: led
    name: "Led"

sensor:
  - platform: pulse_meter
    pin: GPIO1
    name: "Pulse Meter"
    id: sensor_pulse_meter
    unit_of_measurement: 'W'
    device_class: power
    state_class: measurement
    accuracy_decimals: 1
    internal_filter: 1ms
    internal_filter_mode: PULSE
    filters:
      - throttle_average: 10s
        - filter_out:
          - NaN
      - multiply: 18.75 # 60s (pulse_meter is /min) / 3200 (imp/unit - imp/KWh)  - * 1000 -> W (h)

    total:
      name: "Total Pulses"
      unit_of_measurement: "Wh"
      state_class: total_increasing
      accuracy_decimals: 4
      filters:
        - multiply: 0.3125 #  1/3200.0
        - throttle_average: 10s
        - filter_out:
          - NaN

#G41=Button
binary_sensor:
  - platform: gpio
    name: Button
    pin:
      number: GPIO41
      inverted: true
      mode:
        input: true
        pullup: true
    filters:
      - delayed_off: 10ms
    on_press:
      then:
        - logger.log: Button Pressed

esp32_ble_tracker:
  scan_parameters:
    active: True # Whether to send scan-request packets to devices to gather more info (like devicename)
    interval: 320ms # Bermuda suggested 211ms # default 320ms
    window:   300ms # Bermuda suggested 120ms # default 30ms

esp32_ble:
  max_connections: 5

bluetooth_proxy:
  active: True

time:
  - platform: homeassistant
    id: homeassistant_time
```

### Anything in the logs that might be useful for us?

```txt
Here is an excerpt from the log showing two such incidents in close succession.  In the cases recorded here the `inf` send _immediately_ followed a pulse accounted with `delta: 0 µs`, however because of `throttle_average` and variations in power usage these `delta: 0 µs` may appear anywhere in the sequence of `New pulse`s in between the `sensor:133` reports.


[20:29:48.988][D][sensor:133]: 'Pulse Meter': Sending state 546.25256 W with 1 decimals of accuracy
[20:29:49.227][V][pulse_meter:105]: New pulse, delta: 2065101 µs, count: 1, width: 2065101.00000 µs, last-detected=800938607µs, @800952975
[20:29:50.662][D][sensor:133]: 'Total Pulses': Sending state 222.18750 Wh with 4 decimals of accuracy
[20:29:51.342][V][pulse_meter:077]: Peeked Edge, detected: 800938607 µs, rising: 803019520µs, delt: 8426µs, count: 0 @803027946
[20:29:51.342][V][pulse_meter:105]: New pulse, delta: 2080913 µs, count: 1, width: 2080913.00000 µs, last-detected=803019520µs, @803027946
[20:29:51.342][V][pulse_meter:069]: Repay Edge, @803037615 µs, count: 1
[20:29:53.406][V][pulse_meter:077]: Peeked Edge, detected: 803019520 µs, rising: 805110951µs, delt: 8139µs, count: 0 @805119090
[20:29:53.406][V][pulse_meter:105]: New pulse, delta: 2091431 µs, count: 1, width: 2091431.00000 µs, last-detected=805110951µs, @805119090
[20:29:53.406][V][pulse_meter:069]: Repay Edge, @805129993 µs, count: 1
[20:29:55.481][V][pulse_meter:077]: Peeked Edge, detected: 805110951 µs, rising: 807204858µs, delt: 1888µs, count: 0 @807206746
[20:29:55.539][V][pulse_meter:105]: New pulse, delta: 2093907 µs, count: 1, width: 2093907.00000 µs, last-detected=807204858µs, @807206746
[20:29:55.539][V][pulse_meter:069]: Repay Edge, @807218555 µs, count: 1
[20:29:57.585][V][pulse_meter:105]: New pulse, delta: 2087515 µs, count: 1, width: 2087515.00000 µs, last-detected=809292373µs, @809309948
[20:29:57.600][V][pulse_meter:077]: Peeked Edge, detected: 807204858 µs, rising: 809292373µs, delt: 23791µs, count: 0 @809316164
[20:29:57.601][V][pulse_meter:105]: New pulse, delta: 0 µs, count: 1, width: 0.00000 µs, last-detected=809292373µs, @809316164
[20:29:59.017][D][sensor:133]: 'Pulse Meter': Sending state inf W with 1 decimals of accuracy

[20:29:59.646][V][pulse_meter:077]: Peeked Edge, detected: 809292373 µs, rising: 811358505µs, delt: 2380µs, count: 0 @811360885
[20:29:59.647][V][pulse_meter:105]: New pulse, delta: 2066132 µs, count: 1, width: 2066132.00000 µs, last-detected=811358505µs, @811360885
[20:29:59.670][V][pulse_meter:069]: Repay Edge, @811386988 µs, count: 1
[20:30:00.674][D][sensor:133]: 'Total Pulses': Sending state 223.90625 Wh with 4 decimals of accuracy
[20:30:01.728][V][pulse_meter:077]: Peeked Edge, detected: 811358505 µs, rising: 813439426µs, delt: 6298µs, count: 0 @813445724
[20:30:01.743][V][pulse_meter:105]: New pulse, delta: 2080921 µs, count: 1, width: 2080921.00000 µs, last-detected=813439426µs, @813445724
[20:30:01.751][V][pulse_meter:069]: Repay Edge, @813459103 µs, count: 1
[20:30:03.827][V][pulse_meter:077]: Peeked Edge, detected: 813439426 µs, rising: 815512448µs, delt: 9651µs, count: 0 @815522099
[20:30:03.827][V][pulse_meter:105]: New pulse, delta: 2073022 µs, count: 1, width: 2073022.00000 µs, last-detected=815512448µs, @815522099
[20:30:03.827][V][pulse_meter:069]: Repay Edge, @815532693 µs, count: 1
[20:30:05.874][V][pulse_meter:105]: New pulse, delta: 2041958 µs, count: 1, width: 2041958.00000 µs, last-detected=817554406µs, @817569068
[20:30:07.920][V][pulse_meter:077]: Peeked Edge, detected: 817554406 µs, rising: 819611007µs, delt: 5000µs, count: 0 @819616007
[20:30:07.921][V][pulse_meter:105]: New pulse, delta: 2056601 µs, count: 1, width: 2056601.00000 µs, last-detected=819611007µs, @819616007
[20:30:07.921][V][pulse_meter:069]: Repay Edge, @819625197 µs, count: 1
[20:30:08.981][D][sensor:133]: 'Pulse Meter': Sending state 545.15369 W with 1 decimals of accuracy

[20:30:09.988][V][pulse_meter:105]: New pulse, delta: 2080380 µs, count: 1, width: 2080380.00000 µs, last-detected=821691387µs, @821707055
[20:30:10.683][D][sensor:133]: 'Total Pulses': Sending state 225.62500 Wh with 4 decimals of accuracy
[20:30:12.064][V][pulse_meter:077]: Peeked Edge, detected: 821691387 µs, rising: 823785824µs, delt: 2091µs, count: 0 @823787915
[20:30:12.069][V][pulse_meter:105]: New pulse, delta: 2094437 µs, count: 1, width: 2094437.00000 µs, last-detected=823785824µs, @823787915
[20:30:12.116][V][pulse_meter:069]: Repay Edge, @823800952 µs, count: 1
[20:30:14.188][V][pulse_meter:105]: New pulse, delta: 2116055 µs, count: 1, width: 2116055.00000 µs, last-detected=825901879µs, @825914130
[20:30:16.311][V][pulse_meter:105]: New pulse, delta: 2108308 µs, count: 1, width: 2108308.00000 µs, last-detected=828010187µs, @828026761
[20:30:16.311][V][pulse_meter:077]: Peeked Edge, detected: 823785824 µs, rising: 828010187µs, delt: 21858µs, count: 0 @828032045
[20:30:16.313][V][pulse_meter:105]: New pulse, delta: 0 µs, count: 1, width: 0.00000 µs, last-detected=828010187µs, @828032045
[20:30:18.460][V][pulse_meter:069]: Repay Edge, @830144935 µs, count: 1
[20:30:18.995][D][sensor:133]: 'Pulse Meter': Sending state inf W with 1 decimals of accuracy
```

### Additional information

_No response_

### PR DESCRIPTION
**Pull request by LucasCZE**
# What does this implement/fix?

This is an alternative to PR https://github.com/esphome/esphome/pull/10619. The changes in this PR fixes exactly the same issue, but I think in a more appropriate way. The change is smaller, there is no new condition, there is no new property. The idea for this solution came up in the discussion under the original PR.

The changes fixes an issue related to the pulse meter component, expecting in the main `loop()` the latest state from ISR, but in fact swapping sometimes the latest state with an older one. This lead to false early edge detection, when `filter_mode_` is set to `FILTER_PULSE`, as described in this thread: [Pulse_meter seems to be buggy](https://community.home-assistant.io/t/pulse-meter-seems-to-be-buggy/927035/14)

This bugfix changes swapping of `set_` and `get_` in every `loop()` to copying `set_` to `get_` and resetting `count_` in `set_`, ensuring `loop()` to always have the latest state from ISR.

I've been testing the changes in this PR for a week now and everything is working great. Previously I was getting a few false pulses every week.

## Types of changes

- [x] Bugfix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] Developer breaking change (an API change that could break external components)
- [x] Code quality improvements to existing code or addition of tests
- [ ] Other

**Related issue or feature (if applicable):**

- fixes https://github.com/esphome/esphome/issues/10605
- fixes https://github.com/esphome/esphome/issues/12319

**Pull request in [esphome-docs](https://github.com/esphome/esphome-docs) with documentation (if applicable):**

- esphome/esphome-docs#<esphome-docs PR number goes here>

## Test Environment

- [x] ESP32
- [x] ESP32 IDF
- [ ] ESP8266
- [ ] RP2040
- [ ] BK72xx
- [ ] RTL87xx
- [ ] nRF52840

## Example entry for `config.yaml`:

```yaml
sensor:
  # ----- Utility Meter - Gas -----
  - platform: pulse_meter
    id: gas_volume_flow_rate_sensor
    name: "Gas - Volume Flow Rate"
    unit_of_measurement: "m³/h"
    device_class: volume_flow_rate
    state_class: measurement
    icon: "mdi:fire"
    accuracy_decimals: 2
    filters:
      - multiply: 0.6
    pin:
      number: GPIO22
      inverted: true
      mode: INPUT
    internal_filter_mode: PULSE
    internal_filter: 1300ms
    timeout: 2min
    total:
      id: gas_total_consumption_sensor
      name: "Gas - Total Consumption"
      unit_of_measurement: "m³"
      device_class: gas
      state_class: total_increasing
      icon: "mdi:meter-gas-outline"
      accuracy_decimals: 2
      filters:
        - multiply: 0.01

  # ----- Utility Meter - Water -----
  - platform: pulse_meter
    id: water_volume_flow_rate_sensor
    name: "Water - Volume Flow Rate"
    unit_of_measurement: "L/min"
    device_class: volume_flow_rate
    state_class: measurement
    icon: "mdi:water"
    accuracy_decimals: 1
    pin:
      number: GPIO13
      inverted: true
      mode: INPUT
    internal_filter_mode: PULSE
    internal_filter: 450ms
    timeout: 2min
    total:
      id: water_total_consumption_sensor
      name: "Water - Total Consumption"
      unit_of_measurement: "L"
      device_class: water
      state_class: total_increasing
      icon: "mdi:gauge"
      accuracy_decimals: 0
```

## Checklist:
  - [x] The code change is tested and works locally.
  - [ ] Tests have been added to verify that the new code works (under `tests/` folder).

If user exposed functionality or configuration variables are added/changed:
  - [ ] Documentation added/updated in [esphome-docs](https://github.com/esphome/esphome-docs).

### CODE REVIEW

File: esphome/components/pulse_meter/pulse_meter_sensor.cpp [hunk 1]
```diff
@@ -58,8 +55,9 @@ void PulseMeterSensor::loop() {
     }
     this->last_pin_val_ = current;
 
-    // Swap out set and get to get the latest state from the ISR
-    std::swap(this->set_, this->get_);
+    // Get the latest state from the ISR and reset the count in the ISR
+    std::memcpy((void *) this->get_, (void *) this->set_, sizeof(State));
```
Comment (TrentHouliston) [inline esphome/components/pulse_meter/pulse_meter_sensor.cpp]: No need for the memcpy here, it's probably clearer to just use assignment
```suggestion
    *this->get_ = *this->set_;
```

**Review by TrentHouliston — CHANGES_REQUESTED** [review]
Looks good,

Just two minor things to make it clearer for future people working on this

File: esphome/components/pulse_meter/pulse_meter_sensor.h
Comment (TrentHouliston) [inline esphome/components/pulse_meter/pulse_meter_sensor.h]: Since we're not doing the swap trick anymore and are just moving data in an interrupt lock, change these to ordinary variables rather than pointers.

```suggestion
State set_{};
State get_{};
```

File: esphome/components/pulse_meter/pulse_meter_sensor.cpp (hunk 1 above)
Comment (LucasCZE) [reply esphome/components/pulse_meter/pulse_meter_sensor.cpp]: I completely agree with you and it was my first choice, but it is not possible becase these are volatile. The cast to void in memcpy is needed for the same reason.

File: esphome/components/pulse_meter/pulse_meter_sensor.h
Comment (LucasCZE) [reply esphome/components/pulse_meter/pulse_meter_sensor.h]: Do you mean also remove the volatile keyword? I thought about this but I wasn't sure.

Comment (TrentHouliston) [reply esphome/components/pulse_meter/pulse_meter_sensor.h]: Yeah you can also remove the volatile keyword, that's important for cases when the variable may be changed in an ISR after being read in main while you're still using it. In this case the interrupt lock protects us from that so it's not needed

File: esphome/components/pulse_meter/pulse_meter_sensor.cpp (hunk 1 above)
Comment (TrentHouliston) [reply esphome/components/pulse_meter/pulse_meter_sensor.cpp]: Making them non volatile members rather than pointers is for the best then. The variables themselves aren't volatile anyway just the pointers to them

Comment (LucasCZE) [reply esphome/components/pulse_meter/pulse_meter_sensor.cpp]: But because the pointers are volatile and we always use pointers to access the members, the compiler considers the members to be volatile as well. At least that is my understanding. But I want to believe the interrupt lock will be enough.

File: esphome/components/pulse_meter/pulse_meter_sensor.h
Comment (LucasCZE) [reply esphome/components/pulse_meter/pulse_meter_sensor.h]: I wasn't sure if without volatile we could rely on the fact that the assignment and resetting of the count would actually happen in the interrupt lock. So I will hope that is the case and will remove the pointers and the volatile keywords. Thanks for your feedback!

Comment (LucasCZE) [reply esphome/components/pulse_meter/pulse_meter_sensor.h]: I have incorporated the changes you suggested. Please take a look and let me know what you think.

**Comment by LucasCZE** [comment]
I've been testing the latest changes, including the incorporated suggestions from @TrentHouliston, in my environment for two days now. Everything works great.

Also, @whitty verified that changes in this PR fixes bug #12319 as well.

**Review by TrentHouliston — APPROVED** [review]
LGTM!

**Review by stevebaxter — APPROVED** [review]
Very nice!

**Comment by avbentem** [comment]
This PR **works great** for me. Thanks a lot for this, @LucasCZE and all!

Tested for about 24 hours, about 6.5k pulses, ranging from 1.5 pulse/minute to 22 pulses/minute.

<details>
<summary> Background</summary>

I deployed a device yesterday and immediately ran into random ghost pulses reported, say, 2&nbsp;ms before or after an actual pulse. This was far below the value I set for `internal_filter`. And `total` seemed to be reporting the ghost pulse in the very same loop cycle that also reported another value.

I already knew about https://github.com/esphome/issues/issues/4807 and #10605, so before deployment I ran some `interval` that generated random pulses on a GPIO output, wired to the Pulse Meter input. But I guess those dummy pulses were always generated during the loop, which is _probably_ why I did not run into the issue. Until connecting to an actual pulse sensor, which also generates pulses at other times.
</details>

**Comment by wolfbrelan** [comment]
I have been testing this for two weeks, 40.000 pulses (bursts at constant ~10 pulses/min), zero drifting so far.

Finally, pulse_meter is usable for me now.

THANK YOU @LucasCZE and @lefevrer

**Comment by boarder876** [comment]
After using PR #10619 for over a month without any pulse lost or added compared to my gas meter, ESPHome is now showing compilation errors and I'm not able to update the esp8266.
Then I saw that this PR was released and updated the external component to PR 12360 two days ago. This night I noticed a way too short pulse, which should be filtered out. Also the ESP is showing additional two pulses compared to the gas meter.

According to the measured value, the pulse time was roughly 0.135ms. Filter is set to 400ms.

It seems the filter of PR10619 was more robust. I will keep an eye on it the next days...how ofter this will occur.

**Comment by boarder876** [comment]
Unfortunately, same happened this night :(
Screenshot_2025-12-22-08-16-13-741_io homeassistant companion android
Usually 25kw should be a maximum value.

**Comment by LucasCZE** [comment]
@boarder876 I don't know why this fix would work worse than the previous one. The only thing I can think of is that removing `volatile` was not a good idea. But it's possible I'm missing something.

Could you try the first version of this fix (before incorporating the suggestions in this PR), which still had `volatile` preserved, in your environment? I created a new `pulse_meter-fix_early_edge_detection-with_volatile` tag to make it easy to try.

```
external_components:
  - source: github://LucasCZE/esphome@pulse_meter-fix_early_edge_detection-with_volatile
    components: [pulse_meter]
    refresh: 1h
```

[It contains these changes.](https://github.com/esphome/esphome/compare/dev...LucasCZE:esphome:pulse_meter-fix_early_edge_detection-with_volatile)

**Comment by boarder876** [comment]
I've followed your instructions immediatly, but a few minutes ago I already noticed another peak value with a pulse time of ~0,1ms which was counted.

This is my config:
```
external_components:
  - source: github://LucasCZE/esphome@pulse_meter-fix_early_edge_detection-with_volatile
    components: [pulse_meter]
    refresh: 1h
esphome:
  name: gaszaehler
  friendly_name: Gaszähler
esp8266:
  board: nodemcuv2

#....additional configs not shown.

sensor:
  # 1. Der Gaszähler (Pulse Meter)
  - platform: pulse_meter
    id: pulse_meter_gas
    pin: 
      number: GPIO13 
      mode:
        input: true
        pullup: true 
    
    # Momentanverbrauch Sensor
    unit_of_measurement: 'kW'
    name: 'momentan'
    internal_filter: 400ms
    internal_filter_mode: pulse
    accuracy_decimals: 2
    timeout: 2min
    filters:
      - lambda: return x*60*11.525*0.9301/100; # Formel für kW
    
    # Der Zählerstand (Total)
    total:
      name: "total"
      unit_of_measurement: "m³"
      device_class: gas
      state_class: total_increasing 
      accuracy_decimals: 2
      filters:
        - multiply: 0.01 # Internen Zählerstand (x) in m³ umrechnen
```

**Comment by LucasCZE** [comment]
@boarder876 I have no idea why the fix in this PR works for me and a few other people and not for you. Removing `volatile` is apparently not a problem. Could you try the original fix again? So that we can be sure that the problem is really in the changes in this PR and not in something else.

I have created a new branch for you that is up-to-date (so it will compile with the latest ESPHome without errors) and contains the fix from the original PR.

```
external_components:
  - source: github://LucasCZE/esphome@pulse_meter-fix_early_edge_detection-lefevrer
    components: [pulse_meter]
    refresh: 1h
```

[You can inspect the changes here.](https://github.com/esphome/esphome/compare/dev...LucasCZE:esphome:pulse_meter-fix_early_edge_detection-lefevrer)

**Comment by avbentem** [comment]
In case it helps: I don't actually know how clean or noisy the pulses were in my earlier successful testing of this PR. In other words: **maybe** the pulses in my test case were very clean, hence maybe nothing needed any filtering at all? So, **maybe** in my test case `internal_filter: 50ms` was never actually needed/used? 🤔

(Pulses generated by an infrared [TCRT5000 Line Tracking Sensor Module](https://einstronic.com/product/infrared-line-tracking-sensor-module/) on a water meter.)

**Comment by LucasCZE** [comment]
I think I see your point. But I haven't changed my sensors and the changes in this PR resolve the issue in my environment. And the bug was causing exactly the same spikes as in the graph that boarder876 attached. We'll see what boarder876 comes up with.

BTW, I use [a reed switch](https://www.tme.eu/cz/details/mk04-1a66b-1000w/jazyckove-kontakty/meder/) to measure gas and [an inductive proximity sensor](https://www.aliexpress.com/item/32826218456.html) to measure water. Both sensors suffered from the exact same issue, although the reed switch must be causing much more noise.

**Comment by Qhilm** [comment]
I use a reed sensor on a gas meter with an az-delivery-devkit-v4 board. I have around 25k pulses a week at the moment.

Over the last 3 weeks I am missing a single pulse so far, so I would say, this works remarkably well for me.

**Comment by avbentem** [comment]
> But I haven't changed my sensors and the changes in this PR resolve the issue in my environment. And the bug was causing exactly the same spikes as in the graph that boarder876 attached. We'll see what boarder876 comes up with.

Ah, you were not seeing ghost pulses? If you did: I'm not sure if boarder876 is seeing ghost pulses, or non-filtered actual pulses. I think that in my case your PR saved me from seeing pulses that were not real at all. 🙏

**Not** a problem for me, but just wondering if my earlier successful field test may not have used/needed the `internal_filter` value at all:

Meanwhile I tested with an ESP8266 to generate pulses, wired to an ESP32 with this very PR. And it seems **filtering is working fine for me**. (Any pulses shorter than my `internal_filter: 50ms` are nicely discarded. The pulses I used are still quite long though, 29 to 70 ms.)

Counting of _valid_ pulses surely is missing some, but that could **very well** be due to the quality of my test setup. Or maybe the timing between the ESP8266 and ESP32 is a bit off? I was playing with pulses less close to the 50 ms filter value. But now the ESP8266 seems broken (also adding to my doubts about the quality of my setup), which is a good moment to call it a day.

<details>
<summary>ESPHome pulse generator config used</summary>

```yaml
# Pulse generator to test https://github.com/esphome/esphome/pull/12360
esphome:
  name: esphome-web-db4fef
  friendly_name: ESPHome Web db4fef yellow
  min_version: 2025.11.0
  name_add_mac_suffix: false

esp8266:
  board: esp01_1m

logger:

api:

ota:
- platform: esphome

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password

output:
  - platform: gpio
    # On an Adafruit Huzzah ESP8266, GPIO0 is also the built-in LED and button;
    # see https://learn.adafruit.com/adafruit-huzzah-esp8266-breakout/overview
    pin: GPIO0
    id: dummy_pulse
    inverted: true

script:
  # A single-mode script, ensuring `interval` will not run parallel instances
  - id: trigger_pulse
    mode: single
    then:
      - lambda: !lambda |-

          static int64_t skipped = 0;
          static int64_t invalid = 0;
          static int64_t valid = 0;

          // Skip 9 out of 10
          if (random() % 10 > 0) {
            skipped++;
            return;
          }
          
          // A valid pulse 1 out of 5
          bool create_valid = random() % 5 == 0;

          int pulse_ms;
          if (create_valid) {
            valid++;
            // Pulse Meter is configured with `internal_filter_mode: PULSE`
            // along with `internal_filter: 50ms` (defaults to 0.013ms)
            pulse_ms = 50 + random() % 20;
          }
          else {
            invalid++;
            pulse_ms = 49 - random() % 20;
          }

          id(dummy_pulse).turn_on();
          delay(pulse_ms);
          id(dummy_pulse).turn_off();

          // `interval` may trigger the next run almost immediately, so ensure
          // a falling edge
          delay(1);

          ESP_LOGI("pulse",
            "Pulse: length=%dms; valid=%lld; invalid=%lld; skipped=%lld",
            pulse_ms, valid, invalid, skipped
          );

interval:
  - interval: 20ms
    startup_delay: 5s
    then:
      - script.execute: trigger_pulse
          
```
</details>

**Comment by boarder876** [comment]
I kept the previous configuration "with_volatile" up to this morning, because I just saw one peak value 2h after updating, but everything was fine yesterday. But in the night again another peak value.
I've updated this morning to the latest configuration with "...lefevrer" at the end. Let's see. It is the same fix as in PR 10619…?

About my configuration:
NodeMCU V3.4 (ESP8266), powered via USB
Gas meter is a BK-G4 Model with the magnet on the 0,001 m3 digit.
I use a reed switch which is connected between GPIO13 and GND. Also I enabled the internal pullups to have a stable high input while the circuit is open.

The gas meter is just supplying the central gas heater (could run between 5-24 kW). 1m³ are roughly 10kWh here in my region. 

Because the magnet on the meter is mounted in the 0,001 digit, the smallest value I can measure is 0,01m³.
The gas heater is way to oversized for my home, therefore it's most time running at 5-6kw. One rotation is then 60sec, while the circuit with the reed is closed (low signal) for approximately 8seconds.

I'm not sure how to differ in between reed bouncing or ghost pulses. 
I tried to understand the topic with ghost pulses a while ago, but it was not really clear to me.

I really appreciate your support! Have a wonderful Christmas 🎄

**Comment by Qhilm** [comment]
@boarder876, I would recommend connecting an additional GPIO to the same reed sensor and use `binary_sensor` to graph the pulses themselves. That's what I did in the past to troubleshoot missing or ghost pulses.

For what it's worth, I also use `mode: INPUT_PULLUP` (both for `pulse_meter` and for `binary_sensor`).

I have even added a LED to be able to see the pulses in real time when standing in front of the gasmeter.

```yaml
output:
  - platform: gpio
    pin: 
      number: GPIO25
      # inverted: True
    id: color1

light:
  - platform: binary
    name: "light 1"
    output: color1
    id: light_1

binary_sensor:
  - platform: gpio
    name: "binary_reed"
    id: "binary_reed"
    pin:
      number: GPIO26
      inverted: true
      mode: INPUT_PULLUP
    icon: 'mdi:fire'
    # device_class: gas
    filters:
      - delayed_on_off:
          time_on: 200ms
          time_off: 200ms
    on_press:
      then:
        - light.turn_on: light_1
    on_release:
      then:
        - light.turn_off: light_1
```

**Comment by boarder876** [comment]
Thanks for your suggestion. I already made the same for the setup and positioning of the reed. Because it's not allowed anymore to use the same GPIO for different purposes...I connected the reed with a second GPIO and used a binary sensor to trigger the onboard LED (without delay). I haven't seen any flickering but I think the bouncing of the reed is too fast for that. Unfortunately I just have a multimeter here, not a oscilloscope.
Because with PR 10619 everything went well, in the meantime I commented the binary sensor out and just use a 50ms led signal with on_value: inside the Pulse Meter sensor.

**Comment by LucasCZE** [comment]
@avbentem:

> Ah, you were not seeing ghost pulses?

I know that a reed sensor produces a lot of noise. But at the same time, I'm sure the problem was with the ghost pulses in my environment. So I'm pretty sure that in my environment I don't have a problem with either the filter or the ghost pulses with the changes in this PR.

> Meanwhile I tested with an ESP8266 to generate pulses, wired to an ESP32 with this very PR. And it seems **filtering is working fine for me**. (Any pulses shorter than my `internal_filter: 50ms` are nicely discarded. The pulses I used are still quite long though, 29 to 70 ms.)

It's great that you've put so much effort into solving this problem. Thank you very much.

> Counting of _valid_ pulses surely is missing some, but that could **very well** be due to the quality of my test setup. Or maybe the timing between the ESP8266 and ESP32 is a bit off? I was playing with pulses less close to the 50 ms filter value. But now the ESP8266 seems broken (also adding to my doubts about the quality of my setup), which is a good moment to call it a day.

I see one problem in your configuration that will definitely cause some pulses not to be counted by the pulse meter, even though the generator does count them.

> ```
> id(dummy_pulse).turn_on();
> delay(pulse_ms);
> id(dummy_pulse).turn_off();
> 
> // `interval` may trigger the next run almost immediately, so ensure a falling edge
> delay(1);
> ```

The pulse meter's filter in the `PULSE` mode filters out both short high levels and short low levels. Your configuration often generates a low level that is too short to be counted. I think a better working configuration could look something like this:

```
id(dummy_pulse).turn_on();
delay(pulse_ms);
id(dummy_pulse).turn_off();
delay(pulse_ms);
```

@boarder876:

> I've updated this morning to the latest configuration with "...lefevrer" at the end. Let's see. It is the same fix as in PR 10619…?

Yes, it's the same fix as in PR 10619. lefevrer is the author of that PR, hence the lefevrer suffix.

> About my configuration...

I have a very similar configuration. I even have the exact same gas meter and a gas boiler with almost the same power and it's also oversized for my house. The biggest difference I see is that I use an ESP32 and you use an ESP8266.

> I'm not sure how to differ in between reed bouncing or ghost pulses.

Yes, I think it's quite a problem to distinguish these 2 things and I think we can't be sure without an oscilloscope.

> I really appreciate your support! Have a wonderful Christmas 🎄

Thank you very much and I wish you a Merry Christmas too!

> I connected the reed with a second GPIO and used a binary sensor to trigger the onboard LED (without delay). I haven't seen any flickering but I think the bouncing of the reed is too fast for that. Unfortunately I just have a multimeter here, not a oscilloscope.

I agree with everything you wrote.

@Qhilm:

> I would recommend connecting an additional GPIO to the same reed sensor and use `binary_sensor` to graph the pulses themselves. That's what I did in the past to troubleshoot missing or ghost pulses.

I think this might provide some information. Since boarder876 has his filter set to 400ms, this should probably work reliably for the pulses that should be counted. As for the noise caused by a reed sensor, I think `binary_sensor` will not detect it. But that's just my guess.

**Comment by boarder876** [comment]
Just for clarification the statistic diagram of the maximum values for the last 35 days. Before that I've used esphome@2023.7.1 for more than a year without issues. That was one of the last releases before major changes on the code was made and sometimes unfiltered values passed the sensor.
If it's now the same code, i would wonder If i see any higher values again. like in the period of 19. November to 19. December. Let's wait for the results. 

image

**Comment by avbentem** [comment]
> The pulse meter's filter in the `PULSE` mode filters out both short high levels and short low levels.

Wow, thanks, I never realized that! Always great to think I'm helping someone, and in fact it's the other way around. ❤️ I'll go over the documentation during the holidays, to see if I just missed it, or if it makes sense to add your explanation there.

Also, I doubt it helps anyone, but I left the pulse generator with that extra `delay` running for 3 hours: 100% success.

(7,453 valid pulses generated, nicely handled. And 29,417 too short, nicely filtered out. If anyone wants me to test with a different config, let me know. Aside, I also added `reboot_timeout: 0s` to both `api` and `wifi`, to suppress things like "No clients; rebooting".)

<details>
<summary>ESPHome pulse generator config used</summary>

```yaml
# Pulse generator to test https://github.com/esphome/esphome/pull/12360
esphome:
  name: esphome-web-db4fef
  friendly_name: ESPHome Web db4fef yellow
  min_version: 2025.11.0
  name_add_mac_suffix: false

esp8266:
  board: esp01_1m

logger:

api:
  # Suppress "No clients; rebooting"
  reboot_timeout: 0s

ota:
- platform: esphome

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password
  # Never reboot when WiFi is failing
  reboot_timeout: 0s

output:
  - platform: gpio
    # On an Adafruit Huzzah ESP8266, GPIO0 is also the built-in LED and button;
    # see https://learn.adafruit.com/adafruit-huzzah-esp8266-breakout/overview
    pin: GPIO0
    id: dummy_pulse
    inverted: true

script:
  # A single-mode script, ensuring `interval` will not run parallel instances
  - id: trigger_pulse
    mode: single
    then:
      - lambda: !lambda |-

          static int64_t skipped = 0;
          static int64_t invalid = 0;
          static int64_t valid = 0;

          // Skip 9 out of 10
          if (random() % 10 > 0) {
            skipped++;
            return;
          }
          
          // A valid pulse 1 out of 5; always a valid first pulse so we can quickly
          // check the wiring is correct
          // bool create_valid = (valid == 0) || (random() % 5 == 0);
          bool create_valid = (valid == 0) || (random() % 5 == 0);

          int pulse_ms;
          if (create_valid) {
            valid++;
            // Pulse Meter is configured with `internal_filter_mode: PULSE`
            // along with `internal_filter: 50ms` (defaults to 0.013ms)
            pulse_ms = 50 + random() % 20;
          }
          else {
            invalid++;
            pulse_ms = 49 - random() % 20;
          }

          auto start_ms = millis();
          id(dummy_pulse).turn_on();
          delay(pulse_ms);
          id(dummy_pulse).turn_off();
          auto end_ms = millis();

          // As per https://github.com/esphome/esphome/pull/12360#issuecomment-3689411051
          delay(pulse_ms);

          uint32_t pulse_real_ms = end_ms - start_ms;
          ESP_LOGI("pulse",
            "Pulse: length=%dms; actual=%zums; valid=%lld; invalid=%lld; skipped=%lld",
            pulse_ms, pulse_real_ms, valid, invalid, skipped
          );

interval:
  - interval: 20ms
    startup_delay: 10s
    then:
      - script.execute: trigger_pulse
```
</details>

**Comment by LucasCZE** [comment]
I think this information is missing in the documentation. But it works like this. And I think it makes sense. Here is the related source code.

```
  ...

  // Filter length has passed since the last interrupt
  const bool length = now - state.last_intr_ >= sensor->filter_us_;
  if (length && state.latched_ && !sensor->last_pin_val_) {  // Long enough low edge
    state.latched_ = false;
  } else if (length && !state.latched_ && sensor->last_pin_val_) {  // Long enough high edge
    state.latched_ = true;
    set.last_detected_edge_us_ = state.last_intr_;
    set.count_++;
  }

  ...
```

**Comment by boarder876** [comment]
Lefevrer Version works now worryless for a week.
Edit: almost 4 weeks without any issues

**Comment by LucasCZE** [comment]
@boarder876 Thank you for sharing your findings.

From my perspective, it looks like there are 2 bugs in `pulse_meter`.
1. The first bug exists since version 2023.8.0. This bug has never occurred in my environment and no one has yet figured out what the issue is. This PR does not fix this bug. The PR https://github.com/esphome/esphome/pull/10619 fixes this bug, even though it seems like it's just a lucky coincidence.
2. The second bug described in this PR and the other PR as well exists since version 2024.5.0. The root cause of this bug was discovered by @lefevrer and is fixed in both PRs.

I'm not sure what to do next. The changes in version 2023.8.0 were extensive, the first bug could be basically anywhere. It might be best to close this PR and wait for the PR https://github.com/esphome/esphome/pull/10619 to be completed? That should fix both bugs.

**Comment by boarder876** [comment]
Do you see any disadvantages or problems with the PR #10619? I haven't seen any comments about problems in this PR, even if nobody understand the idea behind this fix.
I'm not sure if it make sense to wait for PR #10619, because lefevrer last reaction was in September :/

**Comment by Qhilm** [comment]
@LucasCZE I don't think we should wait for #10619, as @lefevrer has been mentioned multiple times and hasn't shown any activity in months. If/when this person comes back, fixing the first issue (which luckily never impacted me either) is always an option – or maybe someone else finally figures out what actually fixed the issue 1. We should decouple both issues and most of all, not wait for #10619 in my view.

**Comment by LucasCZE** [comment]
Okay. In that case, I'm leaving this PR open. I don't think I can do anything more now. If someone figures out the cause of the first bug, we can move on (maybe in another PR). Until then, we have a fix for at least the second bug, which seems to be enough for most people.

(It is possible that the first bug only exists on ESP8266. @boarder876 uses ESP8266 and is struggling with the first bug. Me, @Qhilm, @avbentem and @whitty use ESP32 and we are not affected by the first bug.)

**Comment by boarder876** [comment]
I'd actually thought about that too. Lefevrer also had the bug with the ESP8266. Unfortunately, I don't currently have an ESP32 at home that I could use for comparison.

Edit: I've found a ESP32-C6 mini board at home, which is now installed in parallel at the same reed contact as the esp8266. Both firmwares are now running with the same configuration and the normal PR #12360 fix. Let's see if both devices behave the same or differently.

**Comment by boarder876** [comment]
I have no idea, what is going on. 
After my last comment two weeks ago, I've set up a new ESP32C6 in addition to the ESP8266 and wired them in parallel to see if they behave differently.
I powered both devices with the same power supply and connected the reed switch in parallel to a each a GPIO pin on both devices.

I cleaned Build files and used the following configuration:

```
external_components:
- source: github://pr#12360
  components: [pulse_meter]
  refresh: 1h
```

For the first week, both ESPs ran identically: no spikes, the same total value at the end, which matched the gas meter reading.
I was surprised that there were no more errors when combined with the ESP32. Therefore, I removed the ESP32 and ran only the ESP8266. During the second week, no spikes occurred again, and the total value matched the consumption exactly.

The same configuration was running around Christmas, which regularly caused at least one error per day. I can't explain why it's now running without problems for a week...

**Comment by whitty** [comment]
> Do you see any disadvantages or problems with the PR #10619? I haven't seen any comments about problems in this PR, even if nobody understand the idea behind this fix. I'm not sure if it make sense to wait for PR #10619, because lefevrer last reaction was in September :/

My preference is for this PR - especially if you can confirm its now working for you on ESP8266

With my reviewer hat on [this change](https://github.com/esphome/esphome/pull/12360/changes#diff-2421f768261b150494a9645d18fee16f9463486eb5c1f849b9f8f7ab8c96e283L61-R59) 

```
-    // Swap out set and get to get the latest state from the ISR
-    std::swap(this->set_, this->get_);
+    // Get the latest state from the ISR and reset the count in the ISR
+    this->get_ = this->set_;
+    this->set_.count_ = 0;
```

Seems more robust, clear in intention and not at risk of being broken by changes in the lines above (its reliance on the external clearing `count_`.  That core is essentially the same as the original fix as far as I can tell, with the rest of this PR includes cleanups that seem preferable because they simplify and remove the code smell around the `volatile` pointers.

The `peeked_edge_` gate in this PR seems prudent because it makes the logic there more obviously correct (it probably does fix an obscure condition, though I can't prove I've needed it).

**Comment by marshn** [comment]
This PR seems to have resolved a problem that I have been having with an 8266 monitoring a gas meter. With a pulse rate of up to 4 pulses/minute I was seeing a spurious pulse of a few microseconds most days, despite using:
```
    internal_filter_mode: pulse
    internal_filter: 50ms
```
The software had been running for three years with no spurious pulses until I upgraded to a 2025 version in November last year. Upgraded again recently to 2026.1 and the problem persisted.

Now running 2026.1 with this PR for three days, and no spurious pulses so far.

File: esphome/components/pulse_meter/pulse_meter_sensor.h [hunk 2]
```diff
@@ -46,17 +46,17 @@ class PulseMeterSensor : public sensor::Sensor, public Component {
...
   struct State {
     uint32_t last_detected_edge_us_ = 0;
     uint32_t last_rising_edge_us_ = 0;
     uint32_t count_ = 0;
   };
-  State state_[2];
-  volatile State *set_ = state_;
-  volatile State *get_ = state_ + 1;
+  State set_{};
+  State get_{};
```
Comment (swoboda1337) [inline esphome/components/pulse_meter/pulse_meter_sensor.h]: - Should remove get_ as a member variable, can just put it on the stack inside loop, don't need to retain it. 
- Should rename set_ to something else and it should be volatile.

**Review by swoboda1337 — CHANGES_REQUESTED** [review]

File: esphome/components/pulse_meter/pulse_meter_sensor.h (hunk 2 above)
Comment (swoboda1337) [reply esphome/components/pulse_meter/pulse_meter_sensor.h]: Looks good otherwise

Comment (LucasCZE) [reply esphome/components/pulse_meter/pulse_meter_sensor.h]: Thanks for the feedback. Done.

`state = this->state_;` is no longer possible because `this->state_` is volatile now. `memcpy()` is used instead now.

`std::memcpy((void *) &state, (void *) &this->state_, sizeof(State));`

I'm already using the changes in my environment. Everything is working so far.

File: esphome/components/pulse_meter/pulse_meter_sensor.cpp [hunk 3]
```diff
@@ -58,31 +57,33 @@ void PulseMeterSensor::loop() {
     }
     this->last_pin_val_ = current;
 
-    // Swap out set and get to get the latest state from the ISR
-    std::swap(this->set_, this->get_);
+    // Get the latest state from the ISR and reset the count in the ISR
+    std::memcpy((void *) &state, (void *) &this->state_, sizeof(State));
```
Comment (swoboda1337) [inline esphome/components/pulse_meter/pulse_meter_sensor.cpp]:
```suggestion
    state.last_detected_edge_us_ = this->state_.last_detected_edge_us_;
    state.last_rising_edge_us_ = this->state_.last_rising_edge_us_;
    state.count_ = this->state_.count_;
```

**Review by swoboda1337 — APPROVED** [review]

File: esphome/components/pulse_meter/pulse_meter_sensor.cpp (hunk 3 above)
Comment (swoboda1337) [reply esphome/components/pulse_meter/pulse_meter_sensor.cpp]: Casting away volatile is technically undefined behavior so just copy all fields manually

**Comment by swoboda1337** [comment]
Thanks
