### PR TITLE
Sleep mode fix for BP5758D driver

### LINKED ISSUE #4920: BP5758D creeping on when turned off (possibly a sleep mode issue)
### The problem

A recent flash of LibreTiny to some bulbs running BK7231N/BP5758D chipsets has resulted in bulbs which turn fully off but, after being turned off, slowly creep back up to about 10% brightness. This is the same behavior I reported exactly a year ago (by sheer coincidence) when the same bulbs ran OpenBeken ([OpenBK issue linked here](https://github.com/openshwprojects/OpenBK7231T_App/issues/221)) with what is likely the same cause, which is to say improperly entering sleep mode. 

In OpenBK the fix for this bug is in [PR#242](https://github.com/openshwprojects/OpenBK7231T_App/pull/242); I haven't had a chance to do a head-to-head comparison of code but it seems likely that there is analogous code in esphome/components/bp5758d/bp5758d.cpp that needs a similar fix.

### Which version of ESPHome has the issue?

2023.9.1

### What type of installation are you using?

Home Assistant Add-on

### Which version of Home Assistant has the issue?

2023.9.3

### What platform are you using?

ESP8266

### Board

cb2l (bk72xx platform; not an option above)

### Component causing the issue

bp5758d

### Example YAML snippet

```yaml
bk72xx:
  board: cb2l

api:

ota:
  password: !secret ota_password

bp5758d:
  data_pin: P8
  clock_pin: P7
 
output:
  - platform: bp5758d
    id: bp5758d_red
    channel: 3
    current: 20
  - platform: bp5758d
    id: bp5758d_green
    channel: 2
    current: 20
  - platform: bp5758d
    id: bp5758d_blue
    channel: 1
    current: 20
  - platform: bp5758d
    id: bp5758d_cw
    channel: 5
    current: 30
  - platform: bp5758d
    id: bp5758d_ww
    channel: 4
    current: 30

light:
  - platform: rgbww
    name: Light
    red: bp5758d_red
    green: bp5758d_green
    blue: bp5758d_blue
    cold_white: bp5758d_cw
    warm_white: bp5758d_ww
    cold_white_color_temperature: 6500 K
    warm_white_color_temperature: 2700 K
    color_interlock: true
```

### Anything in the logs that might be useful for us?

_No response_

### Additional information

_No response_

### PR DESCRIPTION
**Pull request by dwildstr**
# What does this implement/fix?

This is an implementation of a detail in the BP5758D specification which requires that all channels be set to zero before entering sleep mode. Failure to do so can cause the lights to slowly creep back up to being dim rather than off after the lights have been turned off. This same issue was explored in detail in openshwprojects/OpenBK7231T_App#221 and fixed in openshwprojects/OpenBK7231T_App#242. This code is based closely on that PR.

## Types of changes

- [X] Bugfix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] Other

**Related issue or feature (if applicable):** fixes esphome/issues#4920

**Pull request in [esphome-docs](https://github.com/esphome/esphome-docs) with documentation (if applicable):** esphome/esphome-docs#<esphome-docs PR number goes here>

## Test Environment

- [ ] ESP32
- [ ] ESP32 IDF
- [ ] ESP8266
- [ ] RP2040
- [X] BK7231N

## Checklist:
  - [X] The code change is tested and works locally.
  - [ ] Tests have been added to verify that the new code works (under `tests/` folder).

If user exposed functionality or configuration variables are added/changed:
  - [ ] Documentation added/updated in [esphome-docs](https://github.com/esphome/esphome-docs).

### CODE REVIEW

File: esphome/components/bp5758d/bp5758d.cpp [hunk 1]
```diff
@@ -39,7 +39,12 @@ void BP5758D::loop() {
...
-    // Off / Sleep
+    // First turn all channels off
+    data[0] = BP5758D_MODEL_ID + BP5758D_ADDR_START_3CH;
+    for (int i = 1; i < 16; i++)
+      data[i] = 0;
+    this->write_buffer_(data, 17);
+    // Then sleep
     data[0] = BP5758D_MODEL_ID + BP5758D_ADDR_STANDBY;
     for (int i = 1; i < 16; i++)
       data[i] = 0;
```
Comment (jesserockz) [inline esphome/components/bp5758d/bp5758d.cpp]: No need to loop and fill the buffer twice.
```suggestion
    for (int i = 1; i < 16; i++)
      data[i] = 0;

    // First turn all channels off
    data[0] = BP5758D_MODEL_ID + BP5758D_ADDR_START_3CH;
    this->write_buffer_(data, 17);
    // Then sleep
    data[0] = BP5758D_MODEL_ID + BP5758D_ADDR_STANDBY;
```

**Review by jesserockz — CHANGES_REQUESTED** [review]

**Review by jesserockz — APPROVED** [review]
