### PR TITLE
[http_request] Add esp-idf and rp2040 support

### LINKED ISSUE #3426: http_request feature is incompatible with esp-idf
### The problem

Esphome config fails to compile as soon as http_request component appears in config.

```
ubuntu$ esphome run esp32c3.yml 
INFO Reading configuration esp32c3.yml...
Failed config

http_request: [source esp32c3.yml:46]
  
  This feature is incompatible with esp-idf.
  useragent: esphome/weightscale
  timeout: 5s
```

PS: I'm new to Esphome. Let me know if anything else is needed for debugging. Thanks!

### Which version of ESPHome has the issue?

Version: 2022.6.2

### What type of installation are you using?

pip

### Which version of Home Assistant has the issue?

_No response_

### What platform are you using?

ESP32

### Board

esp32-c3-devkitm-1

### Component causing the issue

http_request

### Example YAML snippet

```yaml
esphome:
  name: esp32c3
  platformio_options:
    board_build.variant: esp32c3
    board_build.flash_mode: dio

esp32:
  board: esp32-c3-devkitm-1
  framework:
    type: esp-idf

http_request:
  useragent: esphome/weightscale
  timeout: 5s
```

### Anything in the logs that might be useful for us?

```txt
ubuntu$ esphome run esp32c3.yml 
INFO Reading configuration esp32c3.yml...
Failed config

http_request: [source esp32c3.yml:46]
  
  This feature is incompatible with esp-idf.
  useragent: esphome/weightscale
  timeout: 5s
```

### Additional information

_No response_

### PR DESCRIPTION
**Pull request by jesserockz**
# What does this implement/fix?

This is a major rewrite of the `http_request` component using the methods that were added in #5586 and brings the base http_request component to `esp-idf` and `rp2040`.

This PR simplifies the ota platform for http_request by pulling all of the platform specific http code out to the top level component and making it a dependency.

This also simplifies the configuration, putting all of the common variables on the top level `http_request` component.

This is a breaking change for the `ota` platform, but since it has not been released yet, this is fine.

This is also a breaking change for the top level `http_request` component because it moves `verify_ssl` to the top level out of the action, and removes the `HttpComponent::get_string()` public method, and instead, you can set `capture_response: true` on the `http_request.*` actions which will place the response data in the `body` variable as a `std::string`.

The `status_code` and `content_length` of the response can be found in the `response` object that is given to lambdas in `on_response`.

## Types of changes

- [ ] Bugfix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [x] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] Other

**Related issue or feature (if applicable):** fixes https://github.com/esphome/issues/issues/3426

**Pull request in [esphome-docs](https://github.com/esphome/esphome-docs) with documentation (if applicable):** esphome/esphome-docs#3919

## Test Environment

- [x] ESP32
- [x] ESP32 IDF
- [x] ESP8266

## Example entry for `config.yaml`:

```yaml
# Example config.yaml

```

## Checklist:
  - [x] The code change is tested and works locally.
  - [ ] Tests have been added to verify that the new code works (under `tests/` folder).

If user exposed functionality or configuration variables are added/changed:
  - [x] Documentation added/updated in [esphome-docs](https://github.com/esphome/esphome-docs).

### CODE REVIEW

File: esphome/components/http_request/http_request_idf.cpp [hunk 1]
```diff
@@ -0,0 +1,137 @@
...
+  }
+
+  esp_http_client_config_t config = {};
+
+  config.url = this->url_.c_str();
+  config.method = method;
+  config.timeout_ms = this->timeout_;
+  config.disable_auto_redirect = !this->follow_redirects_;
+  config.max_redirection_count = this->redirect_limit_;
+  config.user_data = (void *) &buffer;
```
Comment (dcousens) [inline esphome/components/http_request/http_request_idf.cpp:89]:
```suggestion
  config.user_data = (void *) buffer.data();
```

Comment (jesserockz) [reply esphome/components/http_request/http_request_idf.cpp:89]: :facepalm: Thanks

**Comment by dcousens** [comment]
Sorry @jesserockz,  I think I was wrong on that comment and tried to remove it before I distracted you; ~nonetheless the lifetime of that `std::vector` seems... sketchy.~

~You `std::move` it; so `user_data` will only be OK as long as the `HttpResponse` lifetime.~

**Comment by jesserockz** [comment]
Yeah I realised that too, modifying the buffer underneath is also not great from what I read.
By the time it is moved, the handler will be completed and will not access it anymore.

**Comment by nagyrobi** [comment]
@jesserockz thank you for this.
Can you please also consider implementing a trigger for timeout? Like https://github.com/esphome/feature-requests/issues/1652

**Comment by jesserockz** [comment]
@nagyrobi  Can do that in a further PR as not to bloat this too much with more changes.

File: esphome/components/http_request/http_request_idf.cpp [hunk 2]
```diff
@@ -0,0 +1,139 @@
...
```
Comment (dcousens) [inline esphome/components/http_request/http_request_idf.cpp:91]:
```suggestion
  config.user_data = nullptr;
```

Actually, reading this again.

`&buffer` is the address of `buffer` on the stack.
It has nothing to do with the underlying memory allocated,  for that you want `.data()`.

However, `buffer` never actually allocates;  you never use it.
Explosions all the way down.

I recommend you leave this as `nullptr`.
You could probably use `evt->data` directly in `http_event_handler`, depending on it's lifetime.
No `std::vector` required.

File: esphome/components/http_request/http_request_idf.cpp [hunk 3]
```diff
@@ -0,0 +1,139 @@
...
+
+  for (const auto &header : this->headers_) {
+    esp_http_client_set_header(client, header.name, header.value);
+  }
+
+  if (!this->body_.empty()) {
+    esp_http_client_set_post_field(client, this->body_.c_str(), this->body_.length());
+  }
+
+  esp_err_t err = esp_http_client_perform(client);
```
Comment (dcousens) [inline esphome/components/http_request/http_request_idf.cpp]: Ignore my (deleted/striked) comments,  I didn't see this previously.
[Reading the documentation](https://github.com/espressif/esp-idf/blob/7c7fbb1fd0762fe20cce2ea6d870101b64af04ed/docs/en/api-reference/protocols/esp_http_client.rst#overview), I think your lifetimes will be OK.

Sorry for any confusion.

**Comment by KingBoomie** [comment]
On esp8266 with the config below HTTPS requests fail. (HTTP does succeed)

<details >
<summary>Show config</summary>

```yaml

esphome:
  name: bath-heater-1

esp8266:
  board: nodemcuv2

external_components:
  - source: github://pr#3256
    components: [http_request]

http_request:
      
time:
  - platform: sntp
    id: sntp_time
    on_time:
      - seconds: /5
        then:
          - http_request.get: 
              url: "https://reqbin.com/echo/get/json"
              capture_response: true
              verify_ssl: false
              on_response:
                then:
                  - lambda: |-
                      std::string str(response.data.begin(), response.data.end());
                      ESP_LOGI("custom", "str: %s", str.c_str());
```

</details>

**Comment by jesserockz** [comment]
@KingBoomie Any more info on what or how it fails?

**Comment by KingBoomie** [comment]
Either i'm really confused about parts of the esphome ecosystem, or something weird is up. Your PR probably didn't break anything, since https doesn't work on released esphome on esp8266 too and since esp-idf only exists for esp32. 

My issue should probably not for this PR, but if you want to take a look

Enabling logging (with    -DDEBUG_ESP_HTTP_CLIENT     -DDEBUG_ESP_PORT=Serial     -DDEBUG_ESP_SSL) , I get this output

```
[I][custom:036]: str:
m[W][http_request:081]: HTTP Request failed; URL: https://reqbin.com/echo/get/json; Error: connection lost
[HTTP-Client][end] tcp is closed
[HTTP-Client][begin] url: https://reqbin.com/echo/get/json
[HTTP-Client][begin] host: reqbin.com port: 443 url: /echo/get/json
[HTTP-Client][sendRequest] type: 'GET' redirCount: 0
BSSL:_connectSSL: start connection
BSSL:CERT: 30 82 03 be 30 82 03 44 a0 03 02 01 02 02 12 03 30 16 e5 2c 74 7c 7c e7 09 f9 c4 c3 fe 6d b0 47 e9 30 0a 06 08 2a 86 48 ce 3d 04 03 03 30 32 31 0b 30 09 06 03 55 04 06 13 02 55 53 31 16 30 14 06 03 55 04 0a 13 0d 4c 65 74 27 73 20 45 6e 63 72 79 70 74 31 0b 30 09 06 03 55 04 03 13 02 45 31 30 1e 17 0d 32 32 31 31 30 32 31 39 30 36 33 35 5a 17 0d 32 33 30 31 33 31 31 39 30 36 33 34 5a 30 17 31 15 30 13 06 03 55 04 03 0c 0c 2a 2e 72 65 71 62 69 6e 2e 63 6f 6d 30 59 30 13 06 07 2a 86 48 ce 3d 02 01 06 08 2a 86 48 ce 3d 03 01 07 03 42 00 04 aa 51 5f fe 8d b8 c4 d8 d0 d4 4e c8 c7 bf 0e f9 fd 15 b2 19 75 85 05 3f 1c 32 2e 6f eb 06 82 5f 5a f4 d4 4b 3f 16 4c 14 ac f1 14 b8 da 20 98 88 b9 66 a9 e3 e9 23 71 4c 68 9f 88 36 1a 08 d4 40 a3 82 02 53 30 82 02 4f 30 0e 06
BSSL:CERT: 03 55 1d 0f 01 01 ff 04 04 03 02 07 80 30 1d 06 03 55 1d 25 04 16 30 14 06 08 2b 06 01 05 05 07 03 01 06 08 2b 06 01 05 05 07 03 02 30 0c 06 03 55 1d 13 01 01 ff 04 02 30 00 30 1d 06 03 55 1d 0e 04 16 04 14 ed c8 12 8f 9e c8 d7 4b 53 5a 07 d4 72 94 73 6e f9 7d ed af 30 1f 06 03 55 1d 23 04 18 30 16 80 14 5a f3 ed 2b fc 36 c2 37 79 b9 52 30 ea 54 6f cf 55 cb 2e ac 30 55 06 08 2b 06 01 05 05 07 01 01 04 49 30 47 30 21 06 08 2b 06 01 05 05 07 30 01 86 15 68 74 74 70 3a 2f 2f 65 31 2e 6f 2e 6c 65 6e 63 72 2e 6f 72 67 30 22 06 08 2b 06 01 05 05 07 30 02 86 16 68 74 74 70 3a 2f 2f 65 31 2e 69 2e 6c 65 6e 63 72 2e 6f 72 67 2f 30 23 06 03 55 1d 11 04 1c 30 1a 82 0c 2a 2e 72 65 71 62 69 6e 2e 63 6f 6d 82 0a 72 65 71 62 69 6e 2e 63 6f 6d 30 4c 06 03 55 1d 20 04 45 30
BSSL:CERT: 43 30 08 06 06 67 81 0c 01 02 01 30 37 06 0b 2b 06 01 04 01 82 df 13 01 01 01 30 28 30 26 06 08 2b 06 01 05 05 07 02 01 16 1a 68 74 74 70 3a 2f 2f 63 70 73 2e 6c 65 74 73 65 6e 63 72 79 70 74 2e 6f 72 67 30 82 01 04 06 0a 2b 06 01 04 01 d6 79 02 04 02 04 81 f5 04 81 f2 00 f0 00 75 00 7a 32 8c 54 d8 b7 2d b6 20 ea 38 e0 52 1e e9 84 16 70 32 13 85 4d 3b d2 2b c1 3a 57 a3 52 eb 52 00 00 01 84 39 f3 e4 00 00 00 04 03 00 46 30 44 02 20 0b 91 75 d9 7e 08 ca d8 13 9c fe 44 87 95 8e a4 81 2b cf 5e aa 5e 12 0d 45 6f 8d 2d e1 ef b3 c1 02 20 6d 9d cc 81 c1 02 0b 67 c4 d1 22 5e 95 61 5c 1a c4 f5 0d e3 b4 1d ca 6b 42 3c cd 85 2c d9 99 95 00 77 00 b7 3e fb 24 df 9c 4d ba 75 f2 39 c5 ba 58 f4 6c 5d fc 42 cf 7a 9f 35 c4 9e 1d 09 81 25 ed b4 99 00 00 01 84 39 f3 e3 f8 00 00
BSSL:CERT: 04 03 00 48 30 46 02 21 00 a6 e6 63 a4 14 89 2a f3 6d bd ba 2f 39 05 ff e3 c8 9f 1f c3 b0 94 f2 a6 e9 95 26 cd 17 e0 1e db 02 21 00 9b 27 67 d9 0d c6 51 18 0c c9 0c bb f6 ff 45 e0 f2 c3 a9 2b bc e8 d3 93 49 ca e1 ff 41 8c f0 15 30 0a 06 08 2a 86 48 ce 3d 04 03 03 03 68 00 30 65 02 30 37 c9 59 d0 f4 48 2b ee f5 33 8a 34 32 0f 30 be 64 e0 58 57 a3 a7 6d d4 9a fc 9a 4a 54 f5 34 61 23 b1 10 59 0e d9 42 38 ae e4 21 15 c5 ca b5 15 02 31 00 83 8b 2a 96 22 73 63 bd 8e 4d fb 6c 98 9a 5e 68 0b 9a a2 30 e2 53 ad c7 52 eb 12 ab 53 66 8a 9a 64 82 87 42 7a 11 42 56 84 42 99 83 88 67 51 3c
BSSL:Connected!
[HTTP-Client] connected to reqbin.com:443
[HTTP-Client] sending request header
-----
GET /echo/get/json HTTP/1.1
Host: reqbin.com
User-Agent: esphome/device
Accept-Encoding: identity;q=1,chunked;q=0.1,*;q=0
Connection: keep-alive
Content-Length: 0

-----
[HTTP-Client][returnError] error(-5): connection lost
[HTTP-Client][end] tcp is closed
```

while with http, we get a nice 301 response
```
[HTTP-Client][begin] url: http://reqbin.com/echo/get/json
[HTTP-Client][begin] host: reqbin.com port: 80 url: /echo/get/json
[HTTP-Client][sendRequest] type: 'GET' redirCount: 0
[HTTP-Client] connected to reqbin.com:80
[HTTP-Client] sending request header
-----
GET /echo/get/json HTTP/1.1
Host: reqbin.com
User-Agent: esphome/device
Accept-Encoding: identity;q=1,chunked;q=0.1,*;q=0
Connection: keep-alive
Content-Length: 0

-----
'HTTP-Client][handleHeaderResponse] RX: 'HTTP/1.1 301 Moved Permanently
'HTTP-Client][handleHeaderResponse] RX: 'Date: Fri, 18 Nov 2022 15:18:35 GMT
'HTTP-Client][handleHeaderResponse] RX: 'Transfer-Encoding: chunked
'HTTP-Client][handleHeaderResponse] RX: 'Connection: keep-alive
'HTTP-Client][handleHeaderResponse] RX: 'Cache-Control: max-age=3600
'HTTP-Client][handleHeaderResponse] RX: 'Expires: Fri, 18 Nov 2022 16:18:35 GMT
'HTTP-Client][handleHeaderResponse] RX: 'Location: https://reqbin.com/echo/get/json
[HTTP-Client][handleHeaderResponse] RX: 'Report-To: {"endpoints":[{"url":"https:\/\/a.nel.cloudflare.com\/report\/v3?s=ektCyif24vZaUP0VYW8OIed4%2Fm%2BWz2R4wWIn3Av2%2BNUhpo6DcWIEpmsUdvK%2B81wweyoIqAebj4i3Fi3UrY07q0liBYMrmOn01%2F6dIgWXyERwSp7d7ritHscHv%2Fs%3D"}],"group":"cf-nel",'max_age":604800}
'HTTP-Client][handleHeaderResponse] RX: 'NEL: {"success_fraction":0,"report_to":"cf-nel","max_age":604800}
'HTTP-Client][handleHeaderResponse] RX: 'Vary: Accept-Encoding
'HTTP-Client][handleHeaderResponse] RX: 'expect-ct: max-age=86400, enforce
'HTTP-Client][handleHeaderResponse] RX: 'referrer-policy: same-origin
'HTTP-Client][handleHeaderResponse] RX: 'x-content-type-options: nosniff
'HTTP-Client][handleHeaderResponse] RX: 'x-frame-options: SAMEORIGIN
'HTTP-Client][handleHeaderResponse] RX: 'x-xss-protection: 1; mode=block
'HTTP-Client][handleHeaderResponse] RX: 'Server: cloudflare
'HTTP-Client][handleHeaderResponse] RX: 'CF-RAY: 76c1adf69ed68fec-FRA
'HTTP-Client][handleHeaderResponse] RX: '
[HTTP-Client][handleHeaderResponse] code: 301
[HTTP-Client][handleHeaderResponse] Transfer-Encoding: chunked
[HTTP-Client][sendRequest] following redirect (the same method): 'https://reqbin.com/echo/get/json' redirCount: 1
[HTTP-Client][setURL] new URL not the same protocol, expected 'http', URL: 'https://reqbin.com/echo/get/json'
[HTTP-Client][sendRequest] failed setting URL for redirection
[HTTP-Client] read chunk len: 0
[HTTP-Client][end] still data in buffer (2), clean up.
[HTTP-Client][end] tcp keep open for reuse
[I][custom:036]: str:
33m[W][http_request:088]: HTTP Request failed; URL: http://reqbin.com/echo/get/json; Code: 3010m
```

I kinda gave up on doing my project through esphome after that, and went back to a regular plaftormio project. From playing around over there, I found that some parts of ESP8266HTTPClient act weirdly (buggily) and in order to do https GET requests, where I actually get to read the response, I had to do manual chunking with `HTTPClient.begin(client, url)`. (Mostly [this](https://github.com/esp8266/Arduino/blob/master/libraries/ESP8266HTTPClient/examples/StreamHttpsClient/StreamHttpsClient.ino) example. So the bug I encountered is most likely somewhere in the esp arduino framework http/s  implementation.

**Comment by jcam** [comment]
I attempted to use this component for sending energy data to my energy monitoring system.
That component expects an HTTP GET with a very long query string. When attempting to send, I get the below error.
Should this request buffer be configurable? espressif points to an integer that could be set:
https://github.com/espressif/esp-idf/issues/9164


[10:54:11][D][esp-idf:000]: E (11089) HTTP_CLIENT: Out of buffer

[10:54:11][E][http_request.idf:019]: HTTP_EVENT_ERROR
[10:54:11][E][http_request.idf:112]: HTTP Request failed: ESP_FAIL

The request looks like this:
http://192.168.1.8/index.php/ecmEngine/greeneye?SN=01000010&SC=5956977&V=1149&c1=356108415191,0,27.62&c2=474374184783,0,1.16&c3=267233220038,0,0.02&c4=258836305667,0,.84&c5=465639463448,0,0&c6=219586310554,0,0.04&c7=1641234,0,0&c8=2432143,0,0&c9=1578123495,0,3.88&c10=1296949,0,0&c11=63518439,0,.10&c12=743931336,0,0&c13=2666185110,0,14.50&c14=336662841,0,.56&c15=82205955,0,0&c16=218101154,0,0&c17=4270608,0,0&c18=590448354,0,2.72&c19=2335935,0,0&c20=120208829,0,.16&c21=130404319,0,0.08&c22=2086382,0,0&c23=4543725523,0,1.36&c24=1142327047,0,2.58&c25=51285,0,0&c26=38984,65281,0&c27=51884,1,0&c28=37785,0,0&c29=51094,0,0&c30=44409,0,0&c31=69278,0,0&c32=38438,0,0&c33=0,0,445.44&c34=0,0,18.64&c35=0,0,154.26&c36=0,0,499.20&c37=0,0,655.50&c38=0,0,573.32&c39=0,0,302.08&c40=0,0,655.44&c41=0,0,17.20&c42=0,0,970.24&c43=0,0,655.36&c44=0,0,118.27&c45=0,0,34.70&c46=0,0,690.04&c47=0,0,509.44&c48=0,0,655.48&PL=1,0,0,0&T=21.0,27.0,27.0,,,,,&Resp=

**Comment by jesserockz** [comment]
Thanks for the feedback @jcam I will be taking another look at this PR early next year.

Note to self: `buffer_size_tx`

**Comment by jcam** [comment]
I forgot to respond here, I increased the transmit buffer size and the above request was able to complete successfully!
I just hardcoded it to a higher value, not what we would likely do in a normal situation, but it was good enough for a POC:
https://github.com/esphome/esphome/compare/jesserockz-2022-103...jcam:esphome:idf_http_request
(note there is both a buffer_size_tx and also a buffer_size for the response in the config that are both configurable)

Unfortunately the amount of time the ESP takes making that http request causes it to miss poll intervals from the I2C bus (I am using this component: https://github.com/emporia-vue-local/esphome) resulting in errors like "Detected 2 missing reading(s), data may not be accurate", so I disabled the http requests for now.
Not sure if there's any simple way to manage which processing core the http request fires on, but I may look back at that after the holidays.

**Comment by kpfleming** [comment]
With `capture_response: true`, with or without an `on_response` trigger, I'm getting crashes when the memory allocator fails.

Config snippet:
```yaml
external_components:
  - source: github://pr#3256
    components: [ http_request ]

http_request:
  id: pvs_data
  useragent: esphome/pvs
  timeout: 60s
  rx_buffer_size: 60000

time:
  - id: homeassistant_time
    platform: homeassistant
    timezone: EST5EDT,M3.2.0,M11.1.0
    on_time:
      - seconds: 45
        minutes: '*'
        then:
          - http_request.get:
              url: http://pvs.km6g.us/cgi-bin/dl_cgi?Command=DeviceList
              capture_response: true
```

Stack trace:
```
[15:28:41][D][sensor:094]: 'Heap Free': Sending state 263612.00000 B with 0 decimals of accuracy
[15:28:41][D][sensor:094]: 'Heap Max Block': Sending state 110592.00000 B with 0 decimals of accuracy
[15:28:42][D][sensor:094]: 'esp32-dev-1 WiFi Signal': Sending state -59.00000 dBm with 0 decimals of accuracy
[15:28:55]
[15:28:55]abort() was called at PC 0x40147b3a on core 1
[15:28:55]
[15:28:55]
[15:28:55]Backtrace: 0x400823ce:0x3ffbe670 0x40088bb9:0x3ffbe690 0x4008eb4e:0x3ffbe6b0 0x40147b3a:0x3ffbe720 0x40145fc3:0x3ffbe740 0x40145f2a:0x3ffbe760 0x400d7636:0x3ffbe780 0x400d76f5:0x3ffbe7b0 0x401591f6:0x3ffbe7d0 0x400e268d:0x3ffbe7f0 0x400f8427:0x3ffbe820 0x400e2859:0x3ffbe870 0x400e38fe:0x3ffbe890 0x400d74c0:0x3ffbe8b0 0x400df911:0x3ffbe980 0x401590cf:0x3ffbe9f0 0x40158b95:0x3ffbea10 0x400d94e5:0x3ffbea30 0x40158e1d:0x3ffbeaa0 0x40158f09:0x3ffbeac0 0x400dc838:0x3ffbeae0 0x400dea52:0x3ffbeb10 0x400d6bc6:0x3ffbeb30
WARNING Found stack trace! Trying to decode it
WARNING Decoded 0x400823ce: panic_abort at /home/kpfleming/.platformio/packages/framework-espidf/components/esp_system/panic.c:408
WARNING Decoded 0x40088bb9: esp_system_abort at /home/kpfleming/.platformio/packages/framework-espidf/components/esp_system/esp_system.c:137
WARNING Decoded 0x4008eb4e: abort at /home/kpfleming/.platformio/packages/framework-espidf/components/newlib/abort.c:46
WARNING Decoded 0x40147b3a: __wrap__Unwind_RaiseException
WARNING Decoded 0x40145fc3: __cxa_throw at /builds/idf/crosstool-NG/.build/xtensa-esp32-elf/src/gcc/libstdc++-v3/libsupc++/eh_throw.cc:90
WARNING Decoded 0x40145f2a: operator new(unsigned int) at /builds/idf/crosstool-NG/.build/xtensa-esp32-elf/src/gcc/libstdc++-v3/libsupc++/new_op.cc:54
WARNING Decoded 0x400d7636: __gnu_cxx::new_allocator<char>::allocate(unsigned int, void const*) at /home/kpfleming/.platformio/packages/toolchain-xtensa-esp32@8.4.0+2021r2-patch5/xtensa-esp32-elf/include/c++/8.4.0/ext/new_allocator.h:111
 (inlined by) std::allocator_traits<std::allocator<char> >::allocate(std::allocator<char>&, unsigned int) at /home/kpfleming/.platformio/packages/toolchain-xtensa-esp32@8.4.0+2021r2-patch5/xtensa-esp32-elf/include/c++/8.4.0/bits/alloc_traits.h:436
 (inlined by) std::_Vector_base<char, std::allocator<char> >::_M_allocate(unsigned int) at /home/kpfleming/.platformio/packages/toolchain-xtensa-esp32@8.4.0+2021r2-patch5/xtensa-esp32-elf/include/c++/8.4.0/bits/stl_vector.h:296
 (inlined by) void std::vector<char, std::allocator<char> >::_M_range_insert<char*>(__gnu_cxx::__normal_iterator<char*, std::vector<char, std::allocator<char> > >, char*, char*, std::forward_iterator_tag) at /home/kpfleming/.platformio/packages/toolchain-xtensa-esp32@8.4.0+2021r2-patch5/xtensa-esp32-elf/include/c++/8.4.0/bits/vector.tcc:720
WARNING Decoded 0x400d76f5: void std::vector<char, std::allocator<char> >::_M_insert_dispatch<char*>(__gnu_cxx::__normal_iterator<char*, std::vector<char, std::allocator<char> > >, char*, char*, std::__false_type) at /home/kpfleming/.platformio/packages/toolchain-xtensa-esp32@8.4.0+2021r2-patch5/xtensa-esp32-elf/include/c++/8.4.0/bits/stl_vector.h:1549
 (inlined by) __gnu_cxx::__normal_iterator<char*, std::vector<char, std::allocator<char> > > std::vector<char, std::allocator<char> >::insert<char*, void>(__gnu_cxx::__normal_iterator<char const*, std::vector<char, std::allocator<char> > >, char*, char*) at /home/kpfleming/.platformio/packages/toolchain-xtensa-esp32@8.4.0+2021r2-patch5/xtensa-esp32-elf/include/c++/8.4.0/bits/stl_vector.h:1270
 (inlined by) esphome::http_request::http_event_handler(esp_http_client_event*) at /home/kpfleming/git-personal/esphome/.esphome/build/esp32-dev-1/src/esphome/components/http_request/http_request_idf.cpp:41
 (inlined by) esphome::http_request::http_event_handler(esp_http_client_event*) at /home/kpfleming/git-personal/esphome/.esphome/build/esp32-dev-1/src/esphome/components/http_request/http_request_idf.cpp:15
WARNING Decoded 0x401591f6: http_dispatch_event at /home/kpfleming/.platformio/packages/framework-espidf/components/esp_http_client/esp_http_client.c:179
WARNING Decoded 0x400e268d: http_on_body at /home/kpfleming/.platformio/packages/framework-espidf/components/esp_http_client/esp_http_client.c:293
WARNING Decoded 0x400f8427: http_parser_execute at /home/kpfleming/.platformio/packages/framework-espidf/components/nghttp/port/http_parser.c:1935 (discriminator 5)
WARNING Decoded 0x400e2859: esp_http_client_get_data at /home/kpfleming/.platformio/packages/framework-espidf/components/esp_http_client/esp_http_client.c:1007
 (inlined by) esp_http_client_get_data at /home/kpfleming/.platformio/packages/framework-espidf/components/esp_http_client/esp_http_client.c:991
WARNING Decoded 0x400e38fe: esp_http_client_perform at /home/kpfleming/.platformio/packages/framework-espidf/components/esp_http_client/esp_http_client.c:1184
WARNING Decoded 0x400d74c0: esphome::http_request::HttpRequestIDF::send() at /home/kpfleming/git-personal/esphome/.esphome/build/esp32-dev-1/src/esphome/components/http_request/http_request_idf.cpp:111
WARNING Decoded 0x400df911: esphome::http_request::HttpRequestSendAction<>::play() at /home/kpfleming/git-personal/esphome/.esphome/build/esp32-dev-1/src/esphome/components/http_request/http_request.h:118
WARNING Decoded 0x401590cf: esphome::Action<>::play_complex() at /home/kpfleming/git-personal/esphome/.esphome/build/esp32-dev-1/src/esphome/core/automation.h:125
WARNING Decoded 0x40158b95: esphome::ActionList<>::play() at /home/kpfleming/git-personal/esphome/.esphome/build/esp32-dev-1/src/esphome/core/automation.h:203
 (inlined by) esphome::Automation<>::trigger() at /home/kpfleming/git-personal/esphome/.esphome/build/esp32-dev-1/src/esphome/core/automation.h:241
 (inlined by) esphome::Trigger<>::trigger() at /home/kpfleming/git-personal/esphome/.esphome/build/esp32-dev-1/src/esphome/core/automation.h:98
WARNING Decoded 0x400d94e5: esphome::time::CronTrigger::loop() at /home/kpfleming/git-personal/esphome/.esphome/build/esp32-dev-1/src/esphome/components/time/automation.cpp:62
WARNING Decoded 0x40158e1d: esphome::Component::call_loop() at /home/kpfleming/git-personal/esphome/.esphome/build/esp32-dev-1/src/esphome/core/component.cpp:76
WARNING Decoded 0x40158f09: esphome::Component::call() at /home/kpfleming/git-personal/esphome/.esphome/build/esp32-dev-1/src/esphome/core/component.cpp:98
WARNING Decoded 0x400dc838: esphome::Application::loop() at /home/kpfleming/git-personal/esphome/.esphome/build/esp32-dev-1/src/esphome/core/application.cpp:74 (discriminator 2)
WARNING Decoded 0x400dea52: loop() at /home/kpfleming/git-personal/esphome/.esphome/build/esp32-dev-1/src/main.cpp:376
WARNING Decoded 0x400d6bc6: esphome::loop_task(void*) at /home/kpfleming/git-personal/esphome/.esphome/build/esp32-dev-1/src/esphome/components/esp32/core.cpp:65 (discriminator 1)
```

The HTTP response is just under 32,000 bytes, and I can supply examples of the content if that might be useful but it seems unlikely.

Sometimes the second or third request will crash, other times it will be the eighth or ninth, but the system never really gets beyond that point without crashing.

**Comment by jesserockz** [comment]
@kpfleming I have added a line to reserve the response data size as it seemed to be crashing on reallocating the vector when it was trying to add more data. THis may or may not fix the issue. But tbh `http_request` was never made to download 32kb of data :wink:

**Comment by kpfleming** [comment]
That's the not the least of the things I'm making it do which it wasn't intended to do.. but does very well :-)

That commit appears to have solved the problem, it's been running for 10 minutes now (10 HTTP request cycles) with no crashes. If you wanted to optimize a bit you could wait to call `reserve` until you've got the Content-Length and then only reserve that amount, but for normal users that isn't going to matter.

**Comment by jesserockz** [comment]
Yeah good point on the content length. I will do that next time I check out the branch.

**Comment by nagyrobi** [comment]
Some webservers omit Content-Length so a default value is recommended to be set just to be sure...

**Comment by jesserockz** [comment]
Those webservers are not supported :stuck_out_tongue_closed_eyes:

**Comment by kpfleming** [comment]
I'm now building my second external component which relies on `http_request`, and in this one I need to be able to easily determine what the status code in the response was. The `HTTPResponse` structure in this PR looks very nice, it would be very easy to get what I need this way (rather than having to instantiate a fake `Trigger`). Do you need more testers to move this PR forward?

**Comment by nagyrobi** [comment]
More testers, more use cases described and results posted increase priority.

**Comment by kpfleming** [comment]
I can say that I'm quite happy using this as part of https://github.com/kpfleming/esphome-sunpower; it's running all day long, pulling JSON data from a monitoring system once per minute (and the data is nearly 32KB, which is far beyond what `http_request` was designed for, but it works anyway).

File: esphome/components/http_request/http_request_idf.cpp [hunk 4]
```diff
@@ -0,0 +1,145 @@
...
+      ESP_LOGV(TAG, "HTTP_EVENT_ON_HEADER, key=%s, value=%s", evt->header_key, evt->header_value);
+      break;
+    case HTTP_EVENT_ON_DATA:
+      ESP_LOGV(TAG, "HTTP_EVENT_ON_DATA, len=%d", evt->data_len);
+      /*
+       *  Check for chunked encoding is added as the URL for chunked encoding used in this example returns binary data.
+       *  However, event handler can also be used in case chunked encoding is used.
+       */
+      if (!esp_http_client_is_chunked_response(evt->client)) {
+        if (global_http_request->get_capture_response()) {
```
Comment (kpfleming) [inline esphome/components/http_request/http_request_idf.cpp]: This is going to be a trap for some users, I suspect. The Python code in `__init__.py` allows multiple instances of `http_request` to be created, with their usual IDs (and those can be used in the Actions), but the code here can only handle events for one of them (which will probably be the last one instantiated during setup).

If desired, I can investigate whether it would be possible to feed something through the ESP-IDF stack to have a way to connect these events to the proper component instance.

Comment (kpfleming) [reply esphome/components/http_request/http_request_idf.cpp]: A somewhat ugly, but workable, solution may be to set `global_http_request` in the `send` function, instead of in the constructor. This way it will be set at the moment a synchronous request is being initiated, and that's when it matters.

Comment (jesserockz) [reply esphome/components/http_request/http_request_idf.cpp]: http_request can only have a single instance in config, it cannot be a list.

For multiple to be allowed in yaml, `MULTI_CONF = True` is required which this does not have

Comment (kpfleming) [reply esphome/components/http_request/http_request_idf.cpp]: Ahh, sorry for the distraction. I'm not used to components being limited to a single instance.

**Comment by ghost58400** [comment]
Hello, with the last version of ESPHome and the added support of LibreTiny, this pull request breaks compatibility of the http component for LibreTiny devices, here is the error message :
Failed config

http_request: [source /config/esphome/XXXXXXXX.yaml:18]
  
  Internal Error: require_framework_version does not support this platform configuration
                  platform: bk72xx
                  framework: arduino
  
              Please report this issue on GitHub -> https://github.com/esphome/issues/issues/new?template=bug_report.yml.

**Comment by ghost58400** [comment]
> Hello, with the last version of ESPHome and the added support of LibreTiny, this pull request breaks compatibility of the http component for LibreTiny devices, here is the error message : Failed config
> 
> http_request: [source /config/esphome/XXXXXXXX.yaml:18]
> 
> Internal Error: require_framework_version does not support this platform configuration platform: bk72xx framework: arduino
> 
> ```
>           Please report this issue on GitHub -> https://github.com/esphome/issues/issues/new?template=bug_report.yml.
> ```

Hello, I think that I am wrong, the http_request component seems not supported on the LibreTiny platform for the moment, and this PR is not involved in the problem, I will open a dedicated issue.

**Comment by SamP20** [comment]
I haven't been able to investigate the cause of this issue yet, however after 7 requests (all having a 404 response) I end up with the following error each time I try and make further requests:
```
[20:24:54][D][esp-idf:000]: E (80242) esp-tls: Failed to create socket (family 2 socktype 1 protocol 0)

[20:24:54][D][esp-idf:000]: E (80245) TRANSPORT_BASE: Failed to open a new connection: 32770

[20:24:54][D][esp-idf:000]: E (80248) HTTP_CLIENT: Connection failed, sock < 0

[20:24:54][E][http_request.idf:019]: HTTP_EVENT_ERROR
[20:24:54][E][http_request.idf:117]: HTTP Request failed: ESP_ERR_HTTP_CONNECT; Duration: 19 ms
```

The  part of the config sending the request is here:
```
...
    then:
      - http_request.get:
          url: "http://..."
          headers:
            Content-Type: application/json
          verify_ssl: false
          on_response:
            then:
              - logger.log:
                  format: 'Response status: %d, Duration: %u ms'
                  args:
                    - status_code
                    - duration_ms
```

Let me know if there's anything I can do to help investigate this further.

**Comment by digaus** [comment]
Using it to send push notification to smartphone when doorbell rings.

Works nicely so far but will do more testing

**Comment by kpfleming** [comment]
I have this running on >20 nodes, sending requests every minute (to InfluxDB), along with a few other uses. It has been completely reliable :)

**Comment by snoopsbne** [comment]
I am using this to poll a Fronius inverter and am seeing something similar to SamP20. It works perfectly until there is an issue with the endpoint.

```
[18:10:58][I][esp-idf:000]: E (21730) esp-tls: [sock=58] delayed connect error: Connection reset by peer

[18:10:58][I][esp-idf:000]: E (21733) TRANSPORT_BASE: Failed to open a new connection: 32772

[18:10:58][I][esp-idf:000]: E (21735) HTTP_CLIENT: Connection failed, sock < 0

[18:10:58][E][http_request.idf:019]: HTTP_EVENT_ERROR
[18:10:58][E][http_request.idf:117]: HTTP Request failed: ESP_ERR_HTTP_CONNECT; Duration: 13 ms
```

Which also causes my board to reboot.. I also have this in my yaml: (Using an "real/not a clone" ESP32-POE-ISO dev board so POE powered and wifi is not used)
```
api:
  reboot_timeout: 0s
```

When the endpoint is "stable" - I've had this run for days without issue and I am polling every 3 seconds.

```
esp32:
  board: esp32-poe-iso
  framework:
    type: esp-idf

external_components:
  - source: github://pr#3256
    components: [ http_request ]

 - interval: 3s
    then:
      - if:
          condition:
            - lambda: 'return id(operational_mode) != 10;'
          then:
            - http_request.get:
                url: "http://xxxxxx/solar_api/v1/GetPowerFlowRealtimeData.fcgi"
                capture_response: true
                on_response:
                 then:
                    - lambda: |-
```

File: esphome/components/http_request/http_request_idf.cpp [hunk 5]
```diff
@@ -0,0 +1,145 @@
...
+
+  const auto status_code = esp_http_client_get_status_code(client);
+  response.status_code = status_code;
+  response.content_length = esp_http_client_get_content_length(client);
+  response.duration_ms = duration;
+
+  if (status_code < 200 || status_code >= 300) {
+    ESP_LOGE(TAG, "HTTP Request failed; URL: %s; Code: %d; Duration: %u ms", this->url_.c_str(), status_code, duration);
+    this->status_set_warning();
+    return response;
```
Comment (SamP20) [inline esphome/components/http_request/http_request_idf.cpp]: This branch is missing `esp_http_client_cleanup`. This is probably the cause of the socket exhaustion issue that myself and @snoopsbne have seen.

File: esphome/components/http_request/http_request_idf.cpp (hunk 4 above)
Comment (danielBreitlauch) [reply esphome/components/http_request/http_request_idf.cpp]: You could get rid of the global variable by adding and setting the capture_response bool in the HttpResponse when initializing the esp-idf request.

**Comment by Bascht74** [comment]
As I need this as well: 

Is there a way to use the code from this pull reqest in my yaml?
Maybe somebody can point me in the right direction...

@jesserockz Could you please look into the suggestion from @SamP20 ? 
Maybe this pull request from 2022 could be completed then and another component would be fit for esp-idf...

File: esphome/components/http_request/http_request_idf.cpp (hunk 5 above)
Comment (jesserockz) [reply esphome/components/http_request/http_request_idf.cpp]: I have moved the line up higher to cleanup

File: esphome/components/http_request/http_request_idf.cpp (hunk 4 above)
Comment (jesserockz) [reply esphome/components/http_request/http_request_idf.cpp]: Thanks @danielBreitlauch, not sure why I didn't think of that.

**Comment by jesserockz** [comment]
@Bascht74 see the yaml above by `@snoopsbne` that has this pr included as an `external_component`

**Comment by oarcher** [comment]
If the URL is behind a proxy (specifically the Nginx Proxy Manager HA add-on), the query takes longer and the watchdog is often triggered.

I've encountered this issue for `ota_http`  at https://github.com/esphome/esphome/pull/5586#issuecomment-2018631742, and I've reproduced with this PR. Inserting `App.feed_wdt()` in the code was not enough, I had to  explicitly increase the watchdog:

https://github.com/oarcher/esphome/blob/8ddd5e393ab1d7bb804eb9c83de2d9cdf81b5601/esphome/components/ota_http/ota_http_arduino.cpp#L38-L49

**Comment by kpfleming** [comment]
I have a similar situation, but was able to work around it using YAML configuration:
```yaml
esp32:
  framework:
    sdkconfig_options:
      CONFIG_ESP_TASK_WDT_TIMEOUT_S: "15"

```

**Comment by Hiekkaharju** [comment]
I'm trying to use this for the very basic sharing of data directly between ESPHome nodes, obviously on esp-idf platform for other reasons.
And working with json is really not my homeground...
All examples and documentation I find, like https://esphome.io/cookbook/http_request_sensor.html, use get_string() in parsing the response to an esphome sensor.
But this PR removes get_string() and corresponding result can be in response.data
Took me a good while to figure out any way to get actual data out from that in lambda. I did not figure out any cast etc to make response.data work when replacing the get_string thingy with it in something like the samples. Finally found an example using deserialize in lambda and got that working. So in case someone is doing similar with as limited knowledge as I, here is a lambda that can be used with this PR when otherwise using the cookbook sample. I'm rather sure there is also some better way.

- lambda: |-
    StaticJsonDocument<256> doc;
    DeserializationError error = deserializeJson(doc, response.data);
    if (error) {
       ESP_LOGI("parse error", "deserializeJson failed %s",error.c_str());
    } else {
       id(template_sensor_id).publish_state(doc["value"]);
    }

File: esphome/components/http_request/http_request_arduino.cpp [hunk 6]
```diff
@@ -0,0 +1,151 @@
...
+
+  // returned needed headers must be collected before the requests
+  container->client_.collectHeaders(header_keys, HEADER_COUNT);
+
+  container->status_code = container->client_.sendRequest(method.c_str(), body.c_str());
+  if (container->status_code < 0) {
+    ESP_LOGW(TAG, "HTTP Request failed; URL: %s; Error: %s", url.c_str(),
+             HTTPClient::errorToString(container->status_code).c_str());
+    this->status_momentary_error("failed", 1000);
+    container->end();
```
Comment (kbx81) [inline esphome/components/http_request/http_request_arduino.cpp:107]: This one

File: esphome/components/http_request/ota/ota_http_request.cpp [hunk 7]
```diff
@@ -256,28 +226,33 @@ bool OtaHttpRequestComponent::http_get_md5_() {
 
   ESP_LOGVV(TAG, "url_with_auth: %s", url_with_auth.c_str());
   ESP_LOGI(TAG, "Connecting to: %s", this->md5_url_.c_str());
-  this->http_init(url_with_auth);
-  if (!this->check_status()) {
-    this->http_end();
+  auto container = this->parent_->get(url_with_auth);
+  if (container == nullptr) {
+    ESP_LOGE(TAG, "Failed to connect to MD5 URL");
+    container->end();
```
Comment (kbx81) [inline esphome/components/http_request/ota/ota_http_request.cpp]: Two

**Review by kbx81 — CHANGES_REQUESTED** [review]
For OTA, I found we are calling `container->end()` twice which causes a crash if there is a connection failure -- ~~but I'm not sure which makes more sense to remove.~~ 😅

File: esphome/components/http_request/ota/ota_http_request.cpp (hunk 7 above)
Comment (kbx81) [reply esphome/components/http_request/ota/ota_http_request.cpp]: Yeahhhh...best to remove this one 😅
```suggestion
```

File: esphome/components/http_request/ota/ota_http_request.cpp [hunk 8]
```diff
@@ -256,28 +226,32 @@ bool OtaHttpRequestComponent::http_get_md5_() {
...
-  this->http_end();
+  int read_len = 0;
+  while (container->get_bytes_read() < MD5_SIZE) {
+    read_len = container->read((uint8_t *) this->md5_expected_.data(), MD5_SIZE);
+    App.feed_wdt();
+    yield();
+  }
+  container->end();
 
+  ESP_LOGD(TAG, "Read len: %u, MD5 expected: %u", read_len, MD5_SIZE);
```
Comment (kbx81) [inline esphome/components/http_request/ota/ota_http_request.cpp]: This could probably be verbose
```suggestion
  ESP_LOGV(TAG, "Read len: %u, MD5 expected: %u", read_len, MD5_SIZE);
```

File: esphome/components/http_request/http_request.cpp [hunk 9]
```diff
@@ -16,129 +13,10 @@ void HttpRequestComponent::dump_config() {
   ESP_LOGCONFIG(TAG, "  User-Agent: %s", this->useragent_);
   ESP_LOGCONFIG(TAG, "  Follow Redirects: %d", this->follow_redirects_);
```
Comment (kbx81) [inline esphome/components/http_request/http_request.cpp]:
```suggestion
  ESP_LOGCONFIG(TAG, "  Follow redirects: %s", YESNO(this->follow_redirects_));
```

**Review by kbx81 — APPROVED** [review]
