### PR TITLE
[micro_wake_word] Pin esp-nn version

### LINKED ISSUE #7242: micro_wake_word: v2 models fail to allocate tensor arena on ESP32-S3 N16R8 with PSRAM
### The problem

When using `micro_wake_word` with any v2 model (e.g. the default `okay_nabu` which now resolves to the v2 model), the streaming model fails to allocate its tensor arena on the first inference attempt.

The v1 equivalent of the same wake word (`github://esphome/micro-wake-word-models/models/okay_nabu.json@main`) works correctly on the exact same hardware with the exact same config otherwise.

### Error

```
[D][micro_wake_word:262]: Inference task has started, attempting to allocate memory for buffers
[D][micro_wake_word:267]: Inference task is running
[D][micro_wake_word:378]: State changed from STARTING to DETECTING_WAKE_WORD
Failed to resize buffer. Requested: 19440, available 11876, missing: 7564
[E][micro_wake_word:061][mww]: Failed to allocate tensors for the streaming model
[E][micro_wake_word:252]: Encountered an error while performing an inference
[D][micro_wake_word:274]: Inference task is stopping, deallocating buffers
[D][micro_wake_word:279]: Inference task is finished, freeing task resources
[D][micro_wake_word:378]: State changed from DETECTING_WAKE_WORD to STOPPED
```

Same symptom with `hey_jarvis` v2 (Requested: 17840, available: 10876).

The v2 `okay_nabu.json` declares `tensor_arena_size: 26080` but the allocator only ends up with ~11KB available for resize, suggesting the arena size is either not being honoured or something else is consuming ~15KB of it before the model runs.

### Which version of ESPHome has the issue?

2026.2.4

### What type of installation are you using?

pip

### What platform are you using?

ESP32-S3

### Board

ESP32-S3-DevKitC-1 N16R8 (16MB flash, 8MB octal PSRAM)

### Component causing the issue

micro_wake_word

### Example YAML snippet

```yaml
esp32:
  board: esp32-s3-devkitc-1
  flash_size: 16MB
  framework:
    type: esp-idf
    sdkconfig_options:
      CONFIG_SPIRAM_USE_MALLOC: y
      CONFIG_SPIRAM_MALLOC_ALWAYSINTERNAL: "8192"
      CONFIG_SPIRAM_TRY_ALLOCATE_WIFI_LWIP: y

psram:
  mode: octal
  speed: 80MHz

i2s_audio:
  - id: i2s_in
    i2s_lrclk_pin: GPIO11
    i2s_bclk_pin: GPIO10

microphone:
  - platform: i2s_audio
    id: ext_mic
    i2s_audio_id: i2s_in
    adc_type: external
    i2s_din_pin: GPIO12
    pdm: false
    bits_per_sample: 32bit
    channel: left

# FAILS — default `okay_nabu` resolves to v2 model
micro_wake_word:
  id: mww
  models:
    - model: okay_nabu
      probability_cutoff: 0.5

# WORKS — explicitly forcing v1 model path
# micro_wake_word:
#   id: mww
#   models:
#     - model: github://esphome/micro-wake-word-models/models/okay_nabu.json@main
#       probability_cutoff: 0.5
```

### Anything in the logs that might be useful for us?

Mic hardware is confirmed working — verified with an `on_data` lambda that logs peak amplitude. Peak responds cleanly to sound (baseline ~8-16 in silence, jumps to 800-2000 when speaking), so the I2S wiring and mic config are fine. The failure is purely in the wake word model's tensor allocation.

PSRAM is enabled (`psram:` + octal + 80MHz) and `CONFIG_SPIRAM_USE_MALLOC` is set in sdkconfig, so large allocations should go to PSRAM. The small `available` number in the error suggests TFLite's internal allocator is not allocating from PSRAM for this arena, or the v2 model's declared `tensor_arena_size` isn't being used as the initial pool size.

### Impact

This is a regression for anyone following the ESPHome `micro_wake_word` docs verbatim, because the default model names (`okay_nabu`, `hey_jarvis`, etc.) now resolve to v2 models in the `esphome/micro-wake-word-models` repo. Users on the "recommended" hardware (ESP32-S3 with PSRAM) will hit this on first boot with a working mic.

Workaround: explicitly pin the model URL to the v1 path:
```yaml
model: github://esphome/micro-wake-word-models/models/okay_nabu.json@main
```

### LINKED ISSUE #15603: micro_wake_word: V2 models fail tensor allocation on ESP32-S3 Box3,
### The problem

micro_wake_word: V2 models fail tensor allocation on ESP32-S3 Box3, while V1 okay_nabu works on same config

as also seen recently here:  https://github.com/esphome/issues/issues/7242

Hardware:
- ESP32-S3 Box3 (`esp32s3box`)
- 16MB flash, PSRAM enabled

Observations:
- V2 wake word models fail at runtime with:
  Failed to resize buffer...
  Failed to allocate tensors for the streaming model
- Explicit V1 okay_nabu works on the same Box3 build and can wake successfully
- External Kahrendt okay_nabu JSON fails
- Custom V2 micro wake words fail.

What works:
- `model: github://esphome/micro-wake-word-models/models/okay_nabu.json@main`
-  old compiled binaries with V2/custom models

### Which version of ESPHome has the issue?

 2026.2.4, 2026.3.1, 2026.3.3,

### What type of installation are you using?

Home Assistant Add-on

### What platform are you using?

ESP32

### Component causing the issue

micro_wake_word

### YAML Config

```yaml
substitutions:
  name: box3-mww-minimal
  friendly_name: Box3 MWW Minimal

esphome:
  name: ${name}
  friendly_name: ${friendly_name}
  min_version: 2025.5.0
  name_add_mac_suffix: true
  on_boot:
    priority: 600
    then:
      - delay: 10s
      - micro_wake_word.start

esp32:
  board: esp32s3box
  flash_size: 16MB
  cpu_frequency: 240MHz
  framework:
    type: esp-idf
    sdkconfig_options:
      CONFIG_ESP32S3_DEFAULT_CPU_FREQ_240: "y"
      CONFIG_ESP32S3_DATA_CACHE_64KB: "y"
      CONFIG_ESP32S3_DATA_CACHE_LINE_64B: "y"

psram:
  mode: octal
  speed: 80MHz

logger:
  hardware_uart: USB_SERIAL_JTAG
  level: DEBUG

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password

api:

i2c:
  - id: i2c_adc_dac
    scl: GPIO18
    sda: GPIO8

i2s_audio:
  - id: i2s_audio_bus
    i2s_lrclk_pin:
      number: GPIO45
      ignore_strapping_warning: true
    i2s_bclk_pin: GPIO17
    i2s_mclk_pin: GPIO2

audio_adc:
  - platform: es7210
    i2c_id: i2c_adc_dac
    id: es7210_adc
    bits_per_sample: 16bit
    sample_rate: 16000

audio_dac:
  - platform: es8311
    i2c_id: i2c_adc_dac
    id: es8311_dac
    bits_per_sample: 16bit
    sample_rate: 48000

microphone:
  - platform: i2s_audio
    id: box_mic
    sample_rate: 16000
    i2s_din_pin: GPIO16
    bits_per_sample: 16bit
    adc_type: external

micro_wake_word:
  models:
#    - model: https://github.com/kahrendt/microWakeWord/releases/download/okay_nabu_20241226.3/okay_nabu.json
 #     id: okay_nabu
    - model: github://esphome/micro-wake-word-models/models/okay_nabu.json@main
      id: okay_nabu_github
  #  - model: /config/esphome/microwakeword/Rosita.json
   #   id: Rosita
  on_wake_word_detected:
    - logger.log: "Wake word detected"
```

### Anything in the logs that might be useful for us?

```txt
#### okay nabu v2 ####

[11:11:56.254][D][micro_wake_word:360]: Starting wake word detection
[11:11:56.255][D][micro_wake_word:378]: State changed from STOPPED to STARTING
[11:11:56.271][D][micro_wake_word:262]: Inference task has started, attempting to allocate memory for buffers
[11:11:56.272][D][micro_wake_word:267]: Inference task is running
[11:11:56.272][D][micro_wake_word:378]: State changed from STARTING to DETECTING_WAKE_WORD
[11:11:56.273][D][ring_buffer:034][mww]: Created ring buffer with size 3840
[11:11:56.296]Failed to resize buffer. Requested: 33488, available 20472, missing: 13016
[11:11:56.298][E][micro_wake_word:252]: Encountered an error while performing an inference
[11:11:56.298][D][micro_wake_word:274]: Inference task is stopping, deallocating buffers
[11:11:56.300][E][micro_wake_word:061][mww]: Failed to allocate tensors for the streaming model
[11:11:56.306][D][micro_wake_word:279]: Inference task is finished, freeing task resources
[11:11:56.307][D][micro_wake_word:378]: State changed from DETECTING_WAKE_WORD to STOPPED


#### custom (Rosita) ####


[11:30:49.764][D][micro_wake_word:360]: Starting wake word detection
[11:30:49.765][D][micro_wake_word:378]: State changed from STOPPED to STARTING
[11:30:49.781][D][micro_wake_word:262]: Inference task has started, attempting to allocate memory for buffers
[11:30:49.782][D][micro_wake_word:267]: Inference task is running
[11:30:49.783][D][micro_wake_word:378]: State changed from STARTING to DETECTING_WAKE_WORD
[11:30:49.784][D][ring_buffer:034][mww]: Created ring buffer with size 3840
[11:30:49.804]Failed to resize buffer. Requested: 19712, available 13764, missing: 5948
[11:30:49.806][E][micro_wake_word:252]: Encountered an error while performing an inference
[11:30:49.807][D][micro_wake_word:274]: Inference task is stopping, deallocating buffers
[11:30:49.808][E][micro_wake_word:061][mww]: Failed to allocate tensors for the streaming model
[11:30:49.817][D][micro_wake_word:279]: Inference task is finished, freeing task resources
[11:30:49.818][D][micro_wake_word:378]: State changed from DETECTING_WAKE_WORD to STOPPED


#### Okay Nabu v1 #####


[11:33:30.643][W][component:429]: wifi cleared Warning flag
[11:33:36.556][D][micro_wake_word:360]: Starting wake word detection
[11:33:36.558][D][micro_wake_word:378]: State changed from STOPPED to STARTING
[11:33:36.573][D][micro_wake_word:262]: Inference task has started, attempting to allocate memory for buffers
[11:33:36.574][D][micro_wake_word:267]: Inference task is running
[11:33:36.575][D][micro_wake_word:378]: State changed from STARTING to DETECTING_WAKE_WORD
[11:33:36.576][D][ring_buffer:034][mww]: Created ring buffer with size 3840
```

### Additional information

_No response_

### PR DESCRIPTION
**Pull request by kahrendt**
# What does this implement/fix?

The esp-nn library ([Espressif Registry](https://components.espressif.com/components/espressif/esp-nn/versions/1.2.1/readme)) recently had a new version released. The esp-tflite-micro library micro_wake_word uses always pulls latest esp-nn version, so it was silently bumped. This new esp-nn version requires a larger tensor arena on an ESP32-S3, causing micro_wake_word to fail to start with recently built firmwares.

This PR pins esp-nn to 1.2.1 for future stability. Additionally, when a model is first loaded, mWW now probes to determine the best tensor arena size. It will first try the manifest's size. If it fails, it then doubles it and tries again (solving the too small arena size on an S3). Once its finds a working size, it uses the TFLite helper ``arena_used_bytes()`` (plus a 16 byte margin and then rounded to 16 bytes, following guidance from upstream TFLite Micro for handling potentially different memory alignments in future allocations) to get a lower bound of a working arena size. This value works on an ESP32-S3, but it is too small on an ESP32. So, the probe will keep trying until it finds a value that actually works by using the mid-point between the current lower bound and the known working upper bound (rounded to a 16 byte alignment). Once it finds a working value it adds a 16 byte safety margin in case a future allocation is aligned differently.

While this is an annoying extra complication, we do have some benefits: The new esp-nn version gives faster inference on an ESP32-S3 (7% faster on a VPE with 1 active wake word + VAD). On an ESP32, it now uses less memory than before (the manifest arena size was always measured on an S3 since it required more memory compared to an ESP32).

## Types of changes

- [x] Bugfix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected) — [policy](https://developers.esphome.io/contributing/code/#what-constitutes-a-c-breaking-change)
- [ ] Developer breaking change (an API change that could break external components) — [policy](https://developers.esphome.io/contributing/code/#what-is-considered-public-c-api)
- [ ] Undocumented C++ API change (removal or change of undocumented public methods that lambda users may depend on) — [policy](https://developers.esphome.io/contributing/code/#c-user-expectations)
- [ ] Code quality improvements to existing code or addition of tests
- [ ] Other

**Related issue or feature (if applicable):**

- fixes #15603
- fixes https://github.com/esphome/issues/issues/7242

**Pull request in [esphome-docs](https://github.com/esphome/esphome-docs) with documentation (if applicable):** not applicable

## Test Environment

- [ ] ESP32
- [x] ESP32 IDF
- [ ] ESP8266
- [ ] RP2040/RP2350
- [ ] BK72xx
- [ ] RTL87xx
- [ ] LN882x
- [ ] nRF52840

## Example entry for `config.yaml`:

```yaml
# Example config.yaml

micro_wake_word:
  id: mww
  microphone:
    microphone: i2s_mics
    channels: 1
    gain_factor: 4
  stop_after_detection: false
  models:
    - model: https://github.com/kahrendt/microWakeWord/releases/download/okay_nabu_20241226.3/okay_nabu.json
      id: okay_nabu
    - model: hey_jarvis
      id: hey_jarvis
    - model: hey_mycroft
      id: hey_mycroft
    - model: https://github.com/kahrendt/microWakeWord/releases/download/stop/stop.json
      id: stop
      internal: true
  vad:

```

## Checklist:
  - [x] The code change is tested and works locally.
  - [ ] Tests have been added to verify that the new code works (under `tests/` folder).

If user exposed functionality or configuration variables are added/changed:
  - [ ] Documentation added/updated in [esphome-docs](https://github.com/esphome/esphome-docs).

### CODE REVIEW

File: esphome/components/micro_wake_word/streaming_model.cpp [hunk 1]
```diff
@@ -94,6 +106,68 @@ bool StreamingModel::load_model_() {
   return true;
 }
 
+size_t StreamingModel::probe_arena_size_() {
+  RAMAllocator<uint8_t> arena_allocator;
+
+  // Try with the manifest size first, then escalate to 2x if it fails. Different platforms and different versions of
+  // the esp-nn library require different amounts of memory, so the manifest size may not always be correct, and probing
+  // allows us to find the actual required size for the current build and platform.
+  size_t attempt_sizes[] = {this->tensor_arena_size_, this->tensor_arena_size_ * 2};
```
Comment (bdraco) [inline esphome/components/micro_wake_word/streaming_model.cpp]: how big is this? is 2x going to be a problem?  Should it be more granular?

File: esphome/components/micro_wake_word/streaming_model.cpp [hunk 2]
```diff
@@ -94,6 +106,68 @@ bool StreamingModel::load_model_() {
...
+        upper = lower + 16;  // Pad by 16 bytes to be safe for future allocations
+        break;
+      }
+
+      // Try the midpoint between current attempt and full size
+      lower = ((lower + upper) / 2 + 15) & ~15;
+    }
+
+    arena_allocator.deallocate(probe_arena, attempt_size);
+    return upper;
```
[the remark this answers is not in the document]
Comment (kahrendt) [reply esphome/components/micro_wake_word/streaming_model.cpp:167]: I've aligned the original attempt sizes to 16 bytes.

File: esphome/components/micro_wake_word/streaming_model.cpp (hunk 1 above)
Comment (kahrendt) [reply esphome/components/micro_wake_word/streaming_model.cpp]: The largest manifest value is 37kB for an "OKay Nabu" model. The new esp-nn version requires ~50100 kilobytes for that same model. It depends on the original model architecture, so I don't know a really safe value to try, but I did add a 1.5x test case in between to make it more granule. It does try to allocate in PSRAM first, so it should generally be safe.

**Review by bdraco — APPROVED** [review]

**Comment by kahrendt** [comment]
Thanks!

**Comment by JohnMcLear** [comment]
If s3 is underpowered for an optimal experience would it also make sense to update the docs to recommend a different minimum hardware requirements for tf?

**Comment by kahrendt** [comment]
> If s3 is underpowered for an optimal experience would it also make sense to update the docs to recommend a different minimum hardware requirements for tf?

I don't understand what you mean exactly. The ESP32-S3 handles the mWW models easily. This PR was just addressing a change in the upstream Espressif libraries that actually sped up inference at the cost of using more memory. This PR just makes sure that we allocate enough memory to run inference on both the S3 and plain ESP32 (and other platforms as well, but I haven't tested them explicitly).

**Comment by Pepasek11** [comment]
After applying this fix, wake word detection started working again. However, I also had to lower the VAD probability cutoff to 10% to prevent it from blocking detections. Before the esp-nn update, the default VAD cutoff worked fine.

Is the VAD model affected by the same tensor arena allocation issue? It seems like it loads without error but produces incorrect probabilities, causing it to block all wake word detections even when speech is clearly present. Does anyone have a same issue?
