### PR TITLE
Change HDC1080 init instruction failure from error to warning

### LINKED ISSUE #2700: HDC1080 fails with latest ESPhome version
### The problem

I updated my script to change a temperature offset value. Compiling updated to latest version of ESPHome.
Now, the HDC1080 SPI temperature sensor is no longer working (it was working fine with 2021.8.2.

During log init, error "[E][hdc1080:032]: Communication with HDC1080 failed!" is shown. No temperature sensor updates then occur.

What's changed between these versions that's broken this?

Note that my SPI setup is unconventional (this is on a hacked device; I didn't get to choose which pins to use!):

i2c:
  sda: 2
  scl: 14
  scan: false

### Which version of ESPHome has the issue?

2021.11.2

### What type of installation are you using?

Home Assistant Add-on

### Which version of Home Assistant has the issue?

2021.10.3

### What platform are you using?

ESP8266

### Board

_No response_

### Component causing the issue

HDC1080

### Example YAML snippet

```yaml
esphome:
  name: guestroomaircon
  platform: ESP8266
  board: esp_wroom_02

# Enable logging
logger:

# Enable Home Assistant API
api:

ota:
  password: **SECRET**

wifi:
  networks:
  - ssid: **SECRET**
    password: **SECRET**
    hidden: true
  domain: ".localdomain"
  fast_connect: true

  # Enable fallback hotspot (captive portal) in case wifi connection fails
  #ap:
  #  ssid: "Livingroomaircon"
  #  password: "RCsEPnkL5xjM"

#captive_portal:

web_server:
  port: 80
  
status_led:
  pin:
    number: 12
    inverted: false
    
i2c:
  sda: 2
  scl: 14
  scan: false
  
sensor:
  - platform: hdc1080
    temperature:
      name: "Guest Room Temperature"
      id: tempsensor
      filters:
        - offset: -3.4
        - sliding_window_moving_average:
            window_size: 5
            send_every: 1
    humidity:
      name: "Guest Room Humidity"
      id: humiditysensor
      filters:
        - lambda: |-
            float rh = x;
            float t1 = id(tempsensor).raw_state;
            float t2 = id(tempsensor).state;
            rh *= exp((17.67 * t1) / (t1 + 243.5));
            rh *= (273.15 + t2);
            rh /= exp((17.67 * t2) / (t2 + 243.5));
            rh /= (273.15 + t1);
            return rh;
        - sliding_window_moving_average:
            window_size: 5
            send_every: 1
    update_interval: 60s

binary_sensor:
  - platform: gpio
    pin:
      number: 13
      inverted: true
      mode: INPUT_PULLUP
    id: resetbutton
    internal: true

remote_transmitter:
  pin: 15
  carrier_duty_percent: 50%

climate:
  - platform: daikin       # adjust to match your AC unit!
    name: "Guest Room Air Conditioner"
    sensor: tempsensor
    receiver_id: receiver1
    
remote_receiver:
  - id: receiver1
    pin:
      number: 4
      inverted: true
      #mode: INPUT_PULLUP
    tolerance: 55%
    #dump: all
  - id: receiver2
    pin:
      number: 5
      inverted: true
      #mode: INPUT_PULLUP
    tolerance: 55%
    #dump: all
```

### Anything in the logs that might be useful for us?

```txt
INFO Successfully connected to guestroomaircon.localdomain
[17:37:02][I][app:099]: ESPHome version 2021.10.3 compiled on Nov 11 2021, 17:36:24
[17:37:02][C][status_led:019]: Status LED:
[17:37:02][C][status_led:020]:   Pin: GPIO12
[17:37:02][C][wifi:490]: WiFi:
[17:37:02][C][wifi:352]:   Local MAC: 2C:F4:32:12:12:6F
[17:37:02][C][wifi:353]:   SSID: [redacted]
[17:37:02][C][wifi:354]:   IP Address: 192.168.1.20
[17:37:02][C][wifi:356]:   BSSID: [redacted]
[17:37:02][C][wifi:357]:   Hostname: 'guestroomaircon'
[17:37:02][C][wifi:359]:   Signal strength: -55 dB ▂▄▆█
[17:37:02][C][wifi:363]:   Channel: 11
[17:37:02][C][wifi:364]:   Subnet: 255.255.255.0
[17:37:02][C][wifi:365]:   Gateway: 192.168.1.1
[17:37:02][C][wifi:366]:   DNS1: 192.168.1.1
[17:37:02][C][wifi:367]:   DNS2: 0.0.0.0
[17:37:02][C][i2c.arduino:032]: I2C Bus:
[17:37:02][C][i2c.arduino:033]:   SDA Pin: GPIO2
[17:37:02][C][i2c.arduino:034]:   SCL Pin: GPIO14
[17:37:02][C][i2c.arduino:035]:   Frequency: 50000 Hz
[17:37:02][C][i2c.arduino:038]:   Recovery: bus successfully recovered
[17:37:02][C][gpio.binary_sensor:015]: GPIO Binary Sensor 'resetbutton'
[17:37:02][C][gpio.binary_sensor:016]:   Pin: GPIO13
[17:37:02][C][logger:233]: Logger:
[17:37:02][C][logger:234]:   Level: DEBUG
[17:37:02][C][logger:235]:   Log Baud Rate: 115200
[17:37:02][C][logger:236]:   Hardware UART: UART0
[17:37:02][C][hdc1080:029]: HDC1080:
[17:37:02][C][hdc1080:030]:   Address: 0x40
[17:37:02][E][hdc1080:032]: Communication with HDC1080 failed!
[17:37:02][C][hdc1080:034]:   Update Interval: 60.0s
[17:37:02][C][hdc1080:035]:   Temperature 'Guest Room Temperature'
[17:37:02][C][hdc1080:035]:     Device Class: 'temperature'
[17:37:02][C][hdc1080:035]:     State Class: 'measurement'
[17:37:02][C][hdc1080:035]:     Unit of Measurement: '°C'
[17:37:02][C][hdc1080:035]:     Accuracy Decimals: 1
[17:37:02][C][hdc1080:036]:   Humidity 'Guest Room Humidity'
[17:37:02][C][hdc1080:036]:     Device Class: 'humidity'
[17:37:02][C][hdc1080:036]:     State Class: 'measurement'
[17:37:02][C][hdc1080:036]:     Unit of Measurement: '%'
[17:37:02][C][hdc1080:036]:     Accuracy Decimals: 0
[17:37:02][C][remote_transmitter:018]: Remote Transmitter...
[17:37:02][C][remote_transmitter:019]:   Carrier Duty: 50%
[17:37:02][C][remote_transmitter:020]:   Pin: GPIO15
[17:37:02][C][climate_ir:072]: IR Climate 'Guest Room Air Conditioner'
[17:37:02][C][climate_ir:073]:   Min. Temperature: 10.0°C
[17:37:02][C][climate_ir:074]:   Max. Temperature: 30.0°C
[17:37:02][C][climate_ir:075]:   Supports HEAT: YES
[17:37:02][C][climate_ir:076]:   Supports COOL: YES
[17:37:02][C][remote_receiver.esp8266:060]: Remote Receiver:
[17:37:02][C][remote_receiver.esp8266:061]:   Pin: GPIO4
[17:37:02][C][remote_receiver.esp8266:066]:   Buffer Size: 1000
[17:37:02][C][remote_receiver.esp8266:067]:   Tolerance: 55%
[17:37:02][C][remote_receiver.esp8266:068]:   Filter out pulses shorter than: 50 us
[17:37:02][C][remote_receiver.esp8266:069]:   Signal is done after 10000 us of no changes
[17:37:02][C][remote_receiver.esp8266:060]: Remote Receiver:
[17:37:02][C][remote_receiver.esp8266:061]:   Pin: GPIO5
[17:37:02][C][remote_receiver.esp8266:066]:   Buffer Size: 1000
[17:37:02][C][remote_receiver.esp8266:067]:   Tolerance: 55%
[17:37:02][C][remote_receiver.esp8266:068]:   Filter out pulses shorter than: 50 us
[17:37:02][C][remote_receiver.esp8266:069]:   Signal is done after 10000 us of no changes
[17:37:02][C][web_server:160]: Web Server:
[17:37:02][C][web_server:161]:   Address: guestroomaircon.localdomain:80
[17:37:02][C][ota:082]: Over-The-Air Updates:
[17:37:02][C][ota:083]:   Address: guestroomaircon.localdomain:8266
[17:37:02][C][ota:086]:   Using Password.
[17:37:02][C][api:134]: API Server:
[17:37:02][C][api:135]:   Address: guestroomaircon.localdomain:6053
[17:37:02][C][api:139]:   Using noise encryption: NO
```

### Additional information

_No response_

### PR DESCRIPTION
**Pull request by grob6000**
# What does this implement/fix? 

HDC1080 init instruction fails (typical, all devices I've used), resulting in sensor not operating, due to a bug introduced in underlying i2c code somewhere (see issue report for more detail). This fix is a bit 'quick and dirty' but I think improves resilience - as the current hardcoded device config instruction mirrors the device's powerup defaults, it has no effect in practice. Failure of init instruction should not be terminal (device works fine if ignored).  This PR removes setting the device in error state when config instruction fails, and logs a warning instead. My testing shows the device works fine as is (even if the return state of this message was not ERROR_OK). Message is still attempted.

In the case the config init instruction (currently hardcoded) is changed in future, will need to review impact of failure (i.e. revert to entering error state on failure iff the device doesn't function as expected without the config message).

Noted that at some point, someone needs to fix the underlying bug (somethat's making this device fail - haven't been able to track it down myself as all my devices are currently wall mounted!

Quick description and explanation of changes

## Types of changes

- [X] Bugfix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] Other

**Related issue or feature (if applicable):** fixes https://github.com/esphome/issues/issues/2700

**Pull request in [esphome-docs](https://github.com/esphome/esphome-docs) with documentation (if applicable):**
None - no change to user funtionality.

## Test Environment

- [ ] ESP32
- [ ] ESP32 IDF
- [X] ESP8266

## Example entry for `config.yaml`:

Note the filters are designed to correct RH for temperature offset. Feel free to steal.
```yaml
sensor:
  - platform: hdc1080
    temperature:
      name: "Living Room Temperature"
      id: tempsensor
      filters:
        - offset: -2.9
        - sliding_window_moving_average:
            window_size: 5
            send_every: 1
    humidity:
      name: "Living Room Humidity"
      id: humiditysensor
      filters:
        - lambda: |-
            float rh = x;
            float t1 = id(tempsensor).raw_state;
            float t2 = id(tempsensor).state;
            rh *= exp((17.67 * t1) / (t1 + 243.5));
            rh *= (273.15 + t2);
            rh /= exp((17.67 * t2) / (t2 + 243.5));
            rh /= (273.15 + t1);
            return rh;
        - sliding_window_moving_average:
            window_size: 5
            send_every: 1
    update_interval: 60s

```

## Checklist:
  - [X] The code change is tested and works locally.
  - [ ] Tests have been added to verify that the new code works (under `tests/` folder).
  Note - existing tests should suffice.
  
If user exposed functionality or configuration variables are added/changed:
  - [ ] Documentation added/updated in [esphome-docs](https://github.com/esphome/esphome-docs).
None added.

### CODE REVIEW

**Review by schinckel — APPROVED** [review]

File: esphome/components/hdc1080/hdc1080.cpp [hunk 1]
```diff
@@ -21,7 +21,9 @@ void HDC1080Component::setup() {
   };
 
   if (!this->write_bytes(HDC1080_CMD_CONFIGURATION, data, 2)) {
-    this->mark_failed();
+    // as instruction is same as powerup defaults (for now), interpret as warning if this fails
+    ESP_LOGW(TAG, "HDC1080 initial config instruction error");
+    //this->mark_failed();
```
Comment (oxan) [inline esphome/components/hdc1080/hdc1080.cpp]: Let's make it an actual warning then:
```suggestion
    this->status_set_warning();
```
(Also, in general we don't like commented-out code, just remove it; if it's ever necessary there's always git).

**Comment by grob6000** [comment]
Thanks @oxan, accepted your changes. Tested on my device and works a charm.

**Review by oxan — APPROVED** [review]

**Review by jesserockz — APPROVED** [review]
