### PR TITLE
Nexa 433MHz RF protocol

### LINKED ISSUE #934: Nexa / Proove / Anslut 433mhz remote protocol (8?) not working
**Operating environment/Installation (Hass.io/Docker/pip/etc.):**

Hass.io (Home Assistant 0.103.0, HassOS 2.12, ESPHome 1.14.3) on raspberry pi 3

**ESP (ESP32/ESP8266, Board/Sonoff):**

Sonoff RF bridge
```
  platform: ESP8266
  board: esp01_1m
```
**Affected component:**

https://esphome.io/components/remote_receiver.html
https://esphome.io/components/remote_transmitter.html

**Description of problem:**
The remote receiver and transmitter seems to not work for these protocols/devices: Nexa, Proove, Anslut
The receiver kindof works but gives strange data. Protocol 8 has the correct timings for the bits in this protocol. But he data part on the physical link is coded so that every logical bit is sent as two physical bits, where the second one is the inverse of the first one.
```
'0' => '01'
'1' => '10'
```
Example: For the logical datastream 0111, is sent over the air as 01101010.

>For more details about these protocols see https://tech.jolowe.se/home-automation-rf-protocols/ and http://tech.jolowe.se/home-automation-rf-protocol-update/

So the received data is a sync bit followed by 64 physical bits (representing 32 logical bits) followed by a pause bit.
In the debug view from my esphome receiver I get the same code/data 5 times every time a button is pressed. The remote control sends the code 6 times so this is a bit odd. Also the code/data it shows me is not what I would expect:
```
[22:24:22][D][remote.rc_switch:243]: Received RCSwitch Raw: protocol=8 data='1101010101011010011010100101010111010101010110100110101001010101'
[22:24:22][D][remote.rc_switch:243]: Received RCSwitch Raw: protocol=8 data='1101010101011010011010100101010111010101010110100110101001010101'
[22:24:22][D][remote.rc_switch:243]: Received RCSwitch Raw: protocol=8 data='1101010101011010011010100101010111010101010110100110101001010101'
[22:24:22][D][remote.rc_switch:243]: Received RCSwitch Raw: protocol=8 data='1101010101011010011010100101010111010101010110100110101001010101'
[22:24:22][D][remote.rc_switch:243]: Received RCSwitch Raw: protocol=8 data='1101010101011010011010100101010111010101010110100110101001010101'
```

The data is 64 bits long so my first thought was that this must be the physical bits. But they can never start with 11. The I noticed that it is the same 32 bit pattern repeated twice. So I thought it seems to print the logical bits twice for some reason? But looking at the actual signal sent on the a scope connected to the actual transmitter gives this data:
```
Data from scope (S=Sync bit, P=Pause bit):
S 1010010110100101100101100101011001010101010110100110101001010101 P

Logical bits:
S 1 1 0 0 1 1 0 0 1 0 0 1 0 0 0 1 0 0 0 0 0 0 1 1 0 1 1 1 0 0 0 0  P
11001100100100010000001101110000 
```
Which is not the same as what ESPHome prints out. So it seems it is receiving something but not the correct data.

Sending a code is however not working. I assumed that it was printing the correct data twice and copied the 32 bit code and sent it to the transmitter but did not get a response from the receiver it was set to control. Looking at the 433Mhz spectrum with a RTL-SDR i noticed that the code esphome sends is much shorter that what the original physical remote control is sending. My guess after trying to read the source code for the remote transmitter (https://github.com/esphome/esphome/tree/adf2a463fd60c818aeeeee520f1cf7ac19095da8/esphome/components/remote_transmitter) is that is does not send each bit as two bits when using protocol 8? Also I could not find any reference to the pause bit that is sent after the code?
I tried adding wait times, repeats and custom protocol to my esphome yaml but nothing works.

For code that seems to send the data correct see: https://github.com/tirithen/Arduino-ProoveSignal

**Problem-relevant YAML-configuration entries:**
```yaml
remote_receiver:
  pin: 4
  dump: rc_switch
  tolerance: 50
  filter: 4us
  idle: 4ms
  
remote_transmitter:
  pin: 5
  carrier_duty_percent: 100%

switch:
  - platform: template
    name: anslut_2072266
    turn_on_action:
      - remote_transmitter.transmit_rc_switch_raw:
          # 1101010101011010011010100101010111010101010110100110101001010101
          code: '11010101010110100110101001010101'
          #protocol: 8
          repeat: 
            times: 6
            wait_time: 10250us
          protocol:
            pulse_length: 250
            sync: [1, 10]
            zero: [1, 5]
            one: [1, 1]
            inverted: false
```

**Logs (if applicable):**

```
[22:24:22][D][remote.rc_switch:243]: Received RCSwitch Raw: protocol=8 data='1101010101011010011010100101010111010101010110100110101001010101'
[22:24:22][D][remote.rc_switch:243]: Received RCSwitch Raw: protocol=8 data='1101010101011010011010100101010111010101010110100110101001010101'
[22:24:22][D][remote.rc_switch:243]: Received RCSwitch Raw: protocol=8 data='1101010101011010011010100101010111010101010110100110101001010101'
[22:24:22][D][remote.rc_switch:243]: Received RCSwitch Raw: protocol=8 data='1101010101011010011010100101010111010101010110100110101001010101'
[22:24:22][D][remote.rc_switch:243]: Received RCSwitch Raw: protocol=8 data='1101010101011010011010100101010111010101010110100110101001010101'

```

**Additional information and things you've tried:**

I started out with a wemos d1 mini with 433mhz RX and TX modules attached and tried to get things working on that but since I could not get it working I thought I had some hardware problem with the transmitter and ordered a Sonoff RF bridge to rule that out.

Scope image of the data used in my text above as seen on the output pin on the physical remote control (not the ESPHome):
Code send 6 times
Zoom in on one code

### PR DESCRIPTION
**Pull request by GruffyPuffy**
# What does this implement/fix? 

Support for Nexa (433MHz) devices using remote receiver/transmitter by implementing a new Nexa codec.

## Types of changes

- [ ] Bugfix (non-breaking change which fixes an issue)
- [X] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] Other

**Related issue or feature (if applicable):** fixes https://github.com/esphome/issues/issues/934

**Pull request in [esphome-docs](https://github.com/esphome/esphome-docs) with documentation (if applicable):** esphome/esphome-docs#1313

## Test Environment

- [ ] ESP32
- [X] ESP8266

## Example entry for `config.yaml`:

```yaml
esphome:
   name: nexa_bridge
   platform: ESP8266
   board: esp01_1m

wifi:
   ssid: "YOUR SSID"
   password: "YOUR PASSWD"

# Enable logging
logger:

web_server:
  port: 80

# Enable Home Assistant API
api:
  password: ""

ota:
  password: ""

remote_receiver:
   pin:
     number: 4
   dump:
   - nexa
   filter: 50us
   idle: 4ms

remote_transmitter:
  pin: 5
  carrier_duty_percent: 100%

binary_sensor:
  - platform: remote_receiver
    name: "Nexa Remote 2 Open"
    internal: yes
    nexa:
      device: 0x4C1C12
      state: 1
      group: 0
      channel: 1
      level: 0
    on_press:
      - binary_sensor.template.publish:
          id: NexaRemote2
          state: ON
  - platform: remote_receiver
    name: "Nexa Remote 2 Closed"
    internal: yes
    nexa:
      device: 0x4C1C12
      state: 0
      group: 0
      channel: 1
      level: 0
    on_press:
      - binary_sensor.template.publish:
          id: NexaRemote2
          state: OFF
  - platform: template
    name: "NexaRemote2 State"
    device_class: window
    id: NexaRemote2

output:
  - platform: template
    id: tilda_slinga_output
    type: binary

    write_action:
      - if:
          condition:
            light.is_on: tilda_slinga_light
          then:
            remote_transmitter.transmit_nexa:
              device: 0x38DDB4A
              state: 1
              group: 0
              channel: 15
              level: 0
              repeat: 5
          else:
            remote_transmitter.transmit_nexa:
              device: 0x38DDB4A
              state: 0
              group: 0
              channel: 15
              level: 0
              repeat: 5

  - platform: template
    id: vardagsrum_dimable_slinga_output
    type: float

    write_action:
      - if:
          condition:
            lambda: return (state > 0);
          then:
            remote_transmitter.transmit_nexa:
              device: 0x19A5470
              state: 2
              group: 0
              channel: 0
              level: !lambda return state*15;
              repeat: 5
          else:
            remote_transmitter.transmit_nexa:
              device: 0x19A5470
              state: 0
              group: 0
              channel: 0
              level: 0
              repeat: 5


light:
  - platform: binary
    name: "Tilda Slinga"
    id: tilda_slinga_light
    output: tilda_slinga_output

  - platform: monochromatic
    name: "Vardagsrum Slinga"
    id: vardagsrum_dimable_slinga_light
    output: vardagsrum_dimable_slinga_output
```

## Checklist:
  - [X] The code change is tested and works locally.
  - [ ] Tests have been added to verify that the new code works (under `tests/` folder).
  
If user exposed functionality or configuration variables are added/changed:
  - [X] Documentation added/updated in [esphome-docs](https://github.com/esphome/esphome-docs).

### CODE REVIEW

**Comment by wt4711** [comment]
@GruffyPuffy, just tried your modified receiver (dump and sensor platform) on a Sonoff RFR3 (data output from the radio chip wired to GPIO4). It works fine with Nexa WT-2 (two button battery wall switch) and a Nexa MRYT-1805 (battery wall dimmer)!

Some on/off events from the wall switch are missed, but this happens only when I click the buttons a very short time, and I believe the sender is to blame in those cases.

Great and much needed work! I hope this will be included in the distribution soon. I'm not familiar with the development of ESPhome, but are willing to help with more tests.

**Comment by GruffyPuffy** [comment]
> @GruffyPuffy, just tried your modified receiver (dump and sensor platform) on a Sonoff RFR3 (data output from the radio chip wired to GPIO4). It works fine with Nexa WT-2 (two button battery wall switch) and a Nexa MRYT-1805 (battery wall dimmer)!
> 
> Some on/off events from the wall switch are missed, but this happens only when I click the buttons a very short time, and I believe the sender is to blame in those cases.
> 
> Great and much needed work! I hope this will be included in the distribution soon. I'm not familiar with the development of ESPhome, but are willing to help with more tests.

@wt4711 
Thanx for testing! 
I have two of the Sonoff RF-bridge and they behave a little different. There are lots of spikes in RX on one of them and that one is a little worse...however it usually works. I do think that what must be improved is the filtering in the IRQ. Hopefully I get some time for this. If you like, you can play with the RX timings in the source and see if you find better values etc.

File: esphome/components/remote_base/nexa_protocol.cpp [hunk 1]
```diff
@@ -0,0 +1,327 @@
...
+static const uint32_t TX_HEADER_LOW_US = TX_HEADER_HIGH_US * 10;
+static const uint32_t TX_BIT_HIGH_US = 250;
+static const uint32_t TX_BIT_ONE_LOW_US = TX_BIT_HIGH_US * 5;
+static const uint32_t TX_BIT_ZERO_LOW_US = TX_BIT_HIGH_US * 1;
+
+void NexaProtocol::one(RemoteTransmitData *dst) const {
+  // '1' => '10'
+  dst->item(TX_BIT_HIGH_US, TX_BIT_ONE_LOW_US);
+  dst->item(TX_BIT_HIGH_US, TX_BIT_ZERO_LOW_US);
+  // ESP_LOGD(TAG, "1 ");
```
Comment (jesserockz) [inline esphome/components/remote_base/nexa_protocol.cpp]: Please don't add commented code. You can add this (and all the rest) as `ESP_LOGVV` so its activated with the log level.

File: esphome/components/remote_base/nexa_protocol.cpp [hunk 2]
```diff
@@ -0,0 +1,327 @@
...
+
+  // Send finishing Zero
+  // this->zero(dst);
+  dst->item(TX_BIT_HIGH_US, TX_BIT_ZERO_LOW_US);
+
+  // Send the PAUSE
+  // dst->mark(BIT_HIGH_US);
+  // dst->space(TX_BIT_HIGH_US*50);
+
+  ESP_LOGD(TAG, "ENCODE NEXA: Done");
```
Comment (jesserockz) [inline esphome/components/remote_base/nexa_protocol.cpp]: This should not really be any higher than VERBOSE
```suggestion
  ESP_LOGV(TAG, "ENCODE NEXA: Done");
```

**Review by jesserockz — CHANGES_REQUESTED** [review]
There is a lot of commented code here. Can you either remove it or make it functional? The logs can be made VV or V, but other stuff should be removed please.

File: esphome/components/remote_base/nexa_protocol.cpp [hunk 3]
```diff
@@ -0,0 +1,327 @@
...
+        this->zero(dst);
+    }
+  }
+
+  // Send finishing Zero
+  // this->zero(dst);
+  dst->item(TX_BIT_HIGH_US, TX_BIT_ZERO_LOW_US);
+
+  // Send the PAUSE
+  // dst->mark(BIT_HIGH_US);
```
Comment (Swiftwork) [inline esphome/components/remote_base/nexa_protocol.cpp]: Why did you choose to send a final ZERO bit instead of a PAUSE bit? I would imagine that if a user configures the "repeat" value they would need to specify the time of at least `TX_HEADER_HIGH_US * 40 - TX_BIT_ZERO_LOW_US` instead of 0.

File: esphome/components/remote_base/nexa_protocol.cpp (hunk 2 above)
Comment (GruffyPuffy) [reply esphome/components/remote_base/nexa_protocol.cpp]: Will do! I used a lot during dev, but it is not needed anymore.

File: esphome/components/remote_base/nexa_protocol.cpp (hunk 3 above)
Comment (GruffyPuffy) [reply esphome/components/remote_base/nexa_protocol.cpp]: The specifications I saw, and my testing, as well as when I captured Nexa devices on my oscilloscope showed  that it should end with a zero. I tested various stuff and forgot to remove non-used code. Will clean up the code. The pause (i.e. silence) is controlled by the calling layer above this.

Comment (Swiftwork) [reply esphome/components/remote_base/nexa_protocol.cpp]: Ah I see, I think I have been referring to the old Nexa protocol. You can disregard this :)

**Comment by Swiftwork** [comment]
I have added this PR to my esphome using external components and can verify that it works for both my Nexa devices and my Telldus which uses the same protocol. Well done!

**Comment by wt4711** [comment]
I have been running this since July (the receiver), and it has been working flawlessly! Would be really nice to have this included in the distribution. I'm sure it would be useful for a lot of people who might just give up using Nexa RF devices otherwise.

File: esphome/components/remote_base/__init__.py [hunk 4]
```diff
@@ -1137,7 +1190,7 @@ async def panasonic_action(var, config, args):
         ),
     }
 )
-
+
```
Comment (jesserockz) [inline esphome/components/remote_base/__init__.py]:
```suggestion

```

File: esphome/components/remote_base/__init__.py [hunk 5]
```diff
@@ -1138,7 +1191,6 @@ async def panasonic_action(var, config, args):
     }
 )
```
Comment (jesserockz) [inline esphome/components/remote_base/__init__.py:1193]:
```suggestion
    }
)


```

Comment (jesserockz) [inline esphome/components/remote_base/__init__.py]:
```suggestion
    }
)


```

File: esphome/components/remote_base/nexa_protocol.cpp [hunk 6]
```diff
@@ -0,0 +1,236 @@
...
+        (src.expect_pulse_with_gap(BIT_HIGH_US, BIT_ZERO_LOW_US))) {
+      // '1' => '10'
+      out.level |= 0x01;
+    } else if (src.expect_pulse_with_gap(BIT_HIGH_US, BIT_ZERO_LOW_US) &&
+               (src.expect_pulse_with_gap(BIT_HIGH_US, BIT_ONE_LOW_US))) {
+      // '0' => '01'
+      out.level |= 0x00;
+    } else {
+      // This should not happen...failed command
+      // return {};
```
Comment (jesserockz) [inline esphome/components/remote_base/nexa_protocol.cpp]:
```suggestion
```

**Review by jesserockz — APPROVED** [review]
