### PR TITLE
[uart] Improve error handling and validate buffer size

### LINKED ISSUE #11559: Reading data from RDM6300 failed
### The problem

After updating Esphome to >=2025.10.0, I have a problem with the RDM6300 component. Reading of RFID tags does not work and the log shows:

[08:53:16.538][E][component:154]: uart is marked FAILED: unspecified
[08:53:16.543][D][esp-idf:000]: E (517556) uart: uart_get_buffered_data_len(1661): uart driver error
[08:53:16.548][D][esp-idf:000]: E (517560) uart: uart_get_buffered_data_len(1661): uart driver error
[08:44:45.871][E][uart:015]: Reading from UART timed out at byte 2148391796!
[08:44:45.882][W][rdm6300:018]: Reading data from RDM6300 failed!
[08:44:45.898][D][esp-idf:000]: E (6912) uart: uart_get_buffered_data_len(1661): uart driver error
[08:44:45.903][D][esp-idf:000]: E (6915) uart: uart_get_buffered_data_len(1661): uart driver error
[08:44:45.903][D][esp-idf:000]: E (6918) uart: uart_get_buffered_data_len(1661): uart driver error
[08:44:45.907][D][esp-idf:000]: E (6925) uart: uart_get_buffered_data_len(1661): uart driver error

### Which version of ESPHome has the issue?

2025.10.0

### What type of installation are you using?

Home Assistant Add-on

### What platform are you using?

ESP32

### Component causing the issue

rdm6300, uart

### YAML Config

```yaml
esphome:
  name: door-opener-controller-mirror
  friendly_name: Door Opener Controller Mirror

esp32:
  board: esp32dev
  framework:
    type: esp-idf

# Enable logging
logger:

# Enable Home Assistant API
api:
  encryption:
    key: "S32L0GuBqOx2o8iSYC7K/t6tMXPnuSVdEK5CJwq+Nus="


ota:
  platform: esphome
  password: "aab80ba821f3c4b8a1e49a83c4317044"

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password
  fast_connect: True
  # Enable fallback hotspot (captive portal) in case wifi connection fails
  ap:
    ssid: "Door-Opener-Controller-Mirror"
    password: ""
captive_portal:

# ethernet setup, Only one of ethernet or wifi can be active at the same time
# ethernet:
#   type: LAN8720
#   mdc_pin: GPIO23
#   mdio_pin: GPIO18
#   clk:
#     pin: GPIO0
#     mode: CLK_EXT_IN
#   phy_addr: 1
#   power_pin: GPIO16


# UART setup used by rdm6300 RFID reader
uart:
  id: rdm_uart
  rx_buffer_size: 14
  rx_pin:
    number: GPIO35
    mode:
      input: true
  baud_rate: 9600
  data_bits: 8
  parity: NONE
  stop_bits: 1  


# Support for rdm6300 RFID reader
rdm6300:
  uart_id: rdm_uart
  on_tag:
    then:
      - logger.log: "on_tag"
```

### Anything in the logs that might be useful for us?

```txt
[08:53:16.538][E][component:154]:   uart is marked FAILED: unspecified
[08:53:16.543][D][esp-idf:000]: E (517556) uart: uart_get_buffered_data_len(1661): uart driver error
[08:53:16.548][D][esp-idf:000]: E (517560) uart: uart_get_buffered_data_len(1661): uart driver error
[08:44:45.871][E][uart:015]: Reading from UART timed out at byte 2148391796!
[08:44:45.882][W][rdm6300:018]: Reading data from RDM6300 failed!
[08:44:45.898][D][esp-idf:000]: E (6912) uart: uart_get_buffered_data_len(1661): uart driver error
[08:44:45.903][D][esp-idf:000]: E (6915) uart: uart_get_buffered_data_len(1661): uart driver error
[08:44:45.903][D][esp-idf:000]: E (6918) uart: uart_get_buffered_data_len(1661): uart driver error
[08:44:45.907][D][esp-idf:000]: E (6925) uart: uart_get_buffered_data_len(1661): uart driver error
[08:44:45.913][D][esp-idf:000]: E (6928) uart: uart_get_buffered_data_len(1661): uart driver error
[08:44:45.922][D][esp-idf:000]: E (6934) uart: uart_get_buffered_data_len(1661): uart driver error
[08:44:45.933][D][esp-idf:000]: E (6944) uart: uart_get_buffered_data_len(1661): uart driver error
[08:44:45.948][D][esp-idf:000]: E (6954) uart: uart_get_buffered_data_len(1661): uart driver error
[08:44:45.949][D][esp-idf:000]: E (6964) uart: uart_get_buffered_data_len(1661): uart driver error
[08:44:45.953][D][esp-idf:000]: E (6966) uart: uart_get_buffered_data_len(1661): uart driver error
[08:44:45.963][D][esp-idf:000]: E (6974) uart: uart_get_buffered_data_len(1661): uart driver error
[08:44:45.974][D][esp-idf:000]: E (6985) uart: uart_get_buffered_data_len(1661): uart driver error
[08:44:45.985][D][esp-idf:000]: E (6995) uart: uart_get_buffered_data_len(1661): uart driver error
[08:44:45.996][D][esp-idf:000]: E (7005) uart: uart_get_buffered_data_len(1661): uart driver error
[08:44:46.000][D][esp-idf:000]: E (7016) uart: uart_get_buffered_data_len(1661): uart driver error
[08:44:46.016][D][esp-idf:000]: E (7019) uart: uart_get_buffered_data_len(1661): uart driver error
[08:44:46.017][E][uart:015]: Reading from UART timed out at byte 2148391796!
[08:44:46.025][W][rdm6300:018]: Reading data from RDM6300 failed!
```

### Additional information

_No response_

### PR DESCRIPTION
**Pull request by swoboda1337**
# What does this implement/fix?

  Improved error handling in ESP32 UART component implementation.

  Changes Made

  1. Added RX Buffer Size Validation
    - Added check to ensure rx_buffer_size_ meets minimum hardware FIFO length
    - Automatically adjusts buffer size with warning if configured too small
    - Prevents potential ESP-IDF driver errors during initialization
  2. Added Error Checking to write_array()
    - Added error checking for uart_write_bytes() return value
    - Previously ignored the return value and couldn't detect write failures
    - Now logs error and marks component as failed when write operation fails
  3. Fixed Variable Initialization in available()
    - Changed size_t available; to size_t available = 0;
    - Prevents undefined behavior if uart_get_buffered_data_len() fails
  4. Added Error Checking to available()
    - Added error checking for uart_get_buffered_data_len() return value
    - Previously ignored the return value and couldn't detect buffer query failures
    - Now logs error and marks component as failed when operation fails
  5. Fixed read_array() Return Value
    - Added read_len variable to track actual bytes read from uart_read_bytes()
    - Now returns false if read operation doesn't return expected number of bytes
    - Previously always returned true even on partial/failed reads
  6. Integrated validation into CONFIG_SCHEMA:
    - Added validate_rx_buffer_size() function
    - Added validate_rx_buffer_size to the validation chain

## Types of changes

- [x] Bugfix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] Code quality improvements to existing code or addition of tests
- [ ] Other

**Related issue or feature (if applicable):**

- fixes https://github.com/esphome/esphome/issues/11559

**Pull request in [esphome-docs](https://github.com/esphome/esphome-docs) with documentation (if applicable):**

- esphome/esphome-docs#<esphome-docs PR number goes here>

## Test Environment

- [ ] ESP32
- [x] ESP32 IDF
- [ ] ESP8266
- [ ] RP2040
- [ ] BK72xx
- [ ] RTL87xx
- [ ] nRF52840

## Example entry for `config.yaml`:

```yaml
# Example config.yaml

```

## Checklist:
  - [x] The code change is tested and works locally.
  - [ ] Tests have been added to verify that the new code works (under `tests/` folder).

If user exposed functionality or configuration variables are added/changed:
  - [ ] Documentation added/updated in [esphome-docs](https://github.com/esphome/esphome-docs).

### CODE REVIEW

File: esphome/components/uart/uart_component_esp_idf.cpp [hunk 1]
```diff
@@ -91,6 +91,16 @@ void IDFUARTComponent::setup() {
...
 
+#if (SOC_UART_LP_NUM >= 1)
+  size_t fifo_len = ((this->uart_num_ < SOC_UART_HP_NUM) ? SOC_UART_FIFO_LEN : SOC_LP_UART_FIFO_LEN);
+#else
+  size_t fifo_len = SOC_UART_FIFO_LEN;
+#endif
+  if (this->rx_buffer_size_ <= fifo_len) {
+    ESP_LOGW(TAG, "rx_buffer_size is too small, must be greater than %zu", fifo_len);
+    this->rx_buffer_size_ = fifo_len * 2;
+  }
```
Comment (bdraco) [inline esphome/components/uart/uart_component_esp_idf.cpp:102]: Since these are known values and unlikely to change (we could add static asserts as well), we could add warnings at python codegen time as well as they are far less likely to see it here

File: esphome/components/uart/uart_component_esp_idf.cpp [hunk 2]
```diff
@@ -237,8 +247,12 @@ void IDFUARTComponent::set_rx_timeout(size_t rx_timeout) {
 
 void IDFUARTComponent::write_array(const uint8_t *data, size_t len) {
   xSemaphoreTake(this->lock_, portMAX_DELAY);
-  uart_write_bytes(this->uart_num_, data, len);
+  int32_t write_len = uart_write_bytes(this->uart_num_, data, len);
   xSemaphoreGive(this->lock_);
+  if (write_len != (int32_t) len) {
+    ESP_LOGW(TAG, "uart_write_bytes failed: %d != %zu", write_len, len);
+    mark_failed();
```
Comment (bdraco) [inline esphome/components/uart/uart_component_esp_idf.cpp]:
```suggestion
    this->mark_failed();
```

nit: ESPHome style

Comment (swoboda1337) [reply esphome/components/uart/uart_component_esp_idf.cpp]: Copy and paste / ai. From else where in this file. Thanks

File: esphome/components/uart/uart_component_esp_idf.cpp (hunk 1 above)
Comment (swoboda1337) [reply esphome/components/uart/uart_component_esp_idf.cpp:102]: Values can be different for each esp32 variant. They are also different between HP and LP power uarts. Its not easy to do this during config time. There is also a bunch of logic involving the logger uart as well above this.

Comment (swoboda1337) [reply esphome/components/uart/uart_component_esp_idf.cpp:102]: We could just assume 256 for all esp32 uarts but LP ones are like 16

Comment (bdraco) [reply esphome/components/uart/uart_component_esp_idf.cpp:102]: I asked claude to add it, and claude suggested something like 
```diff
diff --git a/esphome/components/uart/__init__.py b/esphome/components/uart/__init__.py
index cbc11d0db..1ff23e1e9 100644
--- a/esphome/components/uart/__init__.py
+++ b/esphome/components/uart/__init__.py
@@ -130,6 +130,57 @@ def validate_host_config(config):
     return config
 
 
+def validate_rx_buffer_size(config):
+    """Validate RX buffer size meets ESP-IDF UART driver requirements.
+
+    The ESP-IDF UART driver requires rx_buffer_size > UART_HW_FIFO_LEN.
+    - Regular UART: 128 bytes FIFO
+    - LP UART (on C5, C6, P4): 16 bytes FIFO
+    """
+    if not CORE.is_esp32:
+        return config
+
+    rx_buffer_size = config.get(CONF_RX_BUFFER_SIZE, 256)
+
+    # Import here to avoid circular dependency
+    from esphome.components import esp32
+    from esphome.components.esp32.const import (
+        VARIANT_ESP32C5,
+        VARIANT_ESP32C6,
+        VARIANT_ESP32P4,
+    )
+
+    # Determine FIFO length based on variant
+    # Chips with LP UART support have 16-byte FIFO for LP UART, 128-byte for regular UART
+    # For simplicity, we validate against the regular UART FIFO size since we don't know
+    # which UART number will be assigned yet (that happens in C++ setup)
+    variant = esp32.get_esp32_variant()
+
+    if variant in (VARIANT_ESP32C5, VARIANT_ESP32C6, VARIANT_ESP32P4):
+        # These chips have LP UART, but we validate against regular UART FIFO (128 bytes)
+        # because LP UART is typically auto-assigned and users won't know which they'll get.
+        # The C++ code will handle the actual validation and auto-correction if needed.
+        min_buffer_size = 129  # > 128 bytes (regular UART FIFO)
+        fifo_size = 128
+    else:
+        # All other ESP32 variants have 128-byte FIFO
+        min_buffer_size = 129  # > 128 bytes
+        fifo_size = 128
+
+    if rx_buffer_size <= fifo_size:
+        _LOGGER.warning(
+            "UART rx_buffer_size (%d bytes) is too small and must be greater than "
+            "the hardware FIFO size (%d bytes). Consider using at least %d bytes. "
+            "The buffer size will be automatically adjusted at runtime, but you should "
+            "update your configuration to avoid this warning.",
+            rx_buffer_size,
+            fifo_size,
+            fifo_size * 2,
+        )
+
+    return config
+
+
```

but probably with less magic numbers and python constants

Comment (swoboda1337) [reply esphome/components/uart/uart_component_esp_idf.cpp:102]: I guess we can just warn if its <= 128, if they are using a LP they can just ignore it.

**Review by bdraco — DISMISSED** [review]

**Review by bdraco — APPROVED** [review]

**Comment by swoboda1337** [comment]
Thank!
