### PR TITLE
Fix SSD1306 post-setup brightness control

### LINKED ISSUE #1235: SSD1306 OLED Display brightness doesn't work?
**Operating environment/Installation (Hass.io/Docker/pip/etc.):**

github, `dev` brunch

**ESP (ESP32/ESP8266, Board/Sonoff):**

wemos d1 mini

**Affected component:**

https://next.esphome.io/components/display/ssd1306.html

**Description of problem:**
I'm trying to control brightness for the display, it doesn't change. Tried two displays, just with different screen size.
Neither brightness from display configuration nor my template switch don't work.
Tried to call `setup()` in template switch, no changes.
Overall I would like to switch off display to reduce power consumption, if there is another way todo it?

**Problem-relevant YAML-configuration entries:**
```yaml
esphome:
  name: test_unit
  platform: ESP8266
  board: nodemcuv2

i2c:

font:
  - file: 'Arial.ttf'
    id: font1
    size: 14

display:
  - platform: ssd1306_i2c
    model: "SSD1306 128x32"
    brightness: 10%
    id: screen
    lambda: |-
      it.print(0, 0, id(font1), "Hello World!");

switch:
  - platform: template
    name: "Backlights"
    assumed_state: true
    optimistic: true
    turn_on_action:
      then:
        - lambda: |-
            id(screen).set_brightness(1);
            id(screen).fill(COLOR_ON);
    turn_off_action:
      then:
        - lambda: |-
            id(screen).set_brightness(0);
            id(screen).fill(COLOR_OFF);
```

**Logs (if applicable):**

```
PASTE DEBUG LOG HERE

```

**Additional information and things you've tried:**
Testing this on latest `dev` branch

### PR DESCRIPTION
**Pull request by kbx81**
## Description:

Quick patch to fix post-setup brightness control on this display.

**Related issue (if applicable):** fixes https://github.com/esphome/issues/issues/1235

**Pull request in [esphome-docs](https://github.com/esphome/esphome-docs) with documentation (if applicable):** No doc update necessary

## Checklist:
  - [x] The code change is tested and works locally.
  - [x] Tests have been added to verify that the new code works (under `tests/` folder).

If user exposed functionality or configuration variables are added/changed:
  - [x] Documentation added/updated in [esphome-docs](https://github.com/esphome/esphome-docs).

### CODE REVIEW

**Comment by freekode** [comment]
Thank you, just checked, brightness is working well.

File: esphome/components/ssd1306_base/ssd1306_base.cpp [hunk 1]
```diff
@@ -140,6 +127,18 @@ void SSD1306::update() {
   this->do_update_();
   this->display();
 }
+void SSD1306::set_brightness(float brightness) {
```
Comment (freekode) [inline esphome/components/ssd1306_base/ssd1306_base.cpp:130]: Propose also add methods
```c
void SSD1306::turn_on() {
    this->command(SSD1306_COMMAND_DISPLAY_ON);
}
void SSD1306::turn_off() {
    this->command(SSD1306_COMMAND_DISPLAY_OFF);
}
```

Comment (kbx81) [reply esphome/components/ssd1306_base/ssd1306_base.cpp:130]: Yeah, I was thinking about doing that, too. Might as well... 😄

Comment (kbx81) [reply esphome/components/ssd1306_base/ssd1306_base.cpp:131]: @freekode just pushed an update -- let me know if it works for you.

Comment (freekode) [reply esphome/components/ssd1306_base/ssd1306_base.cpp:131]: All good

**Review by freekode — APPROVED** [review]

**Review by glmnet — COMMENTED** [review]
as always, just checking nothing gets broken

File: esphome/components/ssd1306_base/ssd1306_base.cpp [hunk 2]
```diff
@@ -69,27 +73,6 @@ void SSD1306::setup() {
...
-      break;
-    case SSD1306_MODEL_96_16:
-    case SH1106_MODEL_96_16:
-      if (this->external_vcc_)
-        this->command(0x10);
-      else
-        this->command(0xAF);
-      break;
-  }
-
```
[the remark this answers is not in the document]
Comment (kbx81) [reply esphome/components/ssd1306_base/ssd1306_base.cpp:92]: For closure, I bought a couple of the SSH1106 displays (https://www.amazon.com/dp/B07X2ZSNLM/ref=cm_sw_em_r_mt_dp_cyIkFb1BWHK53) and tested, just to be sure -- this works as expected! 🙂 (I also _love_ their shade of blue.)

[the remark this answers is not in the document]
Comment (kbx81) [reply esphome/components/ssd1306_base/ssd1306_base.cpp:92]: (Unrelated: I wrote the first comment a couple weeks ago but just realized I had to push "Submit Review" down below. Yay. 😂)

**Review by glmnet — APPROVED** [review]

**Comment by htvekov** [comment]
Cherry-picked indeed and much anticipated bug fix 😉😁

We'll done @kbx81  👍

I've tested with my i2c ssd1306- and ssd1309 displays and everything works perfectly.

Some quick notes from me about this bug fix:

1. Don't you believe it's neccesary to update docs, so users will be aware of the possibility to use lambda commands to turn on/off display completely and use dynamic brightness calls ?

2. Fiddled a bit getting brightness to work, until I realized it was float (0 to 1) that should be used and not integer (0-100)

3. SSD1309 2,42" (blue circuitboard version)  setup as i2c display works perfectly with ssd1306 libraries in general and with ssd1306 128x64 settings in ESPHome. Only difference I've experienced is that setting brightness to zero doesn't turn off display completely as it does with the SSD1306. Tested with display setup as sh1106 as well without any notisable difference. Thought commands might be different.

Thank you very much for this 😎👍

Ciao !

**Comment by kbx81** [comment]
@htvekov Happy to hear it's working well for you! 😄

Component functions aren't documented in the mainstream documentation. There is a link at the bottom of those pages to the [API Reference](https://next.esphome.io/api/ssd1306__base_8h.html)...although I see we need to get better at using doxygen... 😏

**Comment by htvekov** [comment]
Noted, Keith 👍

Wasn't even aware of the API references at bottom for each component 😉
