### PR TITLE
[ld2410/ld2450] Replace header sync with buffer size increase for frame resync

### LINKED ISSUE #14131: LD2450 regression in 2026.2.0 – "Max command length exceeded; ignoring" prevents initialization
### The problem

After upgrading to ESPHome 2026.2.0, my LD2450 radar devices no longer initialize and continuously log:

[W][ld2450:777]: Max command length exceeded; ignoring

The warning repeats every few hundred milliseconds during startup and the radar never enters reporting mode (no presence or target updates).

Rolling back to ESPHome 2026.1.0 restores full functionality with the same YAML and hardware.

This appears to be a regression introduced in 2026.2.0 related to stricter frame length validation in the LD2450 component.

### Which version of ESPHome has the issue?

2026.2.0

### What type of installation are you using?

Home Assistant Add-on

### Which version of Home Assistant has the issue?

(Home Assistant version here)

### What platform are you using?

ESP32 (esp32dev board)
Framework: esp-idf (recommended)

### Board

esp32dev

### Component causing the issue

ld2450

### Example YAML snippet

```yaml
uart:
  id: uart_ld2450
  tx_pin: GPIO01
  rx_pin: GPIO03
  baud_rate: 115200
  rx_buffer_size: 2048

ld2450:
  id: garage_radar
  uart_id: uart_ld2450


### Which version of ESPHome has the issue?

2026.2.0

### What type of installation are you using?

Home Assistant Add-on

### What platform are you using?

ESP32

### Component causing the issue

LD2450 Human Presence device

### YAML Config

```yaml
# ────────────────────────────────────────────────────
# LD2450 Human Presence Radar – Room Occupancy Detection
# Version: 2.1
# Date: 2026-02-19
#
# CHANGELOG
# v2.1
#   • Lowered UART baud to 115200 (ESP-IDF stability fix)
#   • Removed on_boot presence_timeout push (caused init race)
#   • Added api + wifi reboot_timeout protection
#   • Added LD2450 setup_priority for clean startup ordering
#   • Simplified occupancy lambda
#   • Added optional radar watchdog restart
# ────────────────────────────────────────────────────

substitutions:
  name: "occupancy-garage"
  friendly_name: "occupancy-garage"
  uart_tx_pin: "GPIO01"
  uart_rx_pin: "GPIO03"
  uart_baud_rate: "115200"   # v2.1 STABILITY FIX
  ha_entity_suffix: "garage"

esphome:
  name: ${name}
  friendly_name: ${friendly_name}
  min_version: "2026.1.0"

esp32:
  board: esp32dev
  framework:
    type: esp-idf
    version: recommended

logger:
  level: INFO
  logs:
    ld2450: WARN

api:
  encryption:
    key: !secret api_key
  reboot_timeout: 0s   # v2.1 Prevent API-triggered reboots

#ota:
#  - platform: esphome

ota:
  - platform: esphome
    password: !secret ota_password


wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password
  reboot_timeout: 0s   # v2.1 Prevent WiFi drop reboot loops
  ap:
    ssid: "${friendly_name} Hotspot"
    password: !secret ap_password

captive_portal:

web_server:
  port: 80

# ────────────────────────────────────────────────────
# UART
# ────────────────────────────────────────────────────
uart:
  id: uart_ld2450
  tx_pin: ${uart_tx_pin}
  rx_pin: ${uart_rx_pin}
  baud_rate: ${uart_baud_rate}
  rx_buffer_size: 2048

# ────────────────────────────────────────────────────
# LD2450 Component
# ────────────────────────────────────────────────────
ld2450:
  id: ${ha_entity_suffix}_radar
  uart_id: uart_ld2450
  setup_priority: -10   # v2.1 ensure UART is ready first

# ────────────────────────────────────────────────────
# Binary Sensors
# ────────────────────────────────────────────────────
binary_sensor:

  - platform: ld2450
    ld2450_id: ${ha_entity_suffix}_radar

    has_target:
      id: radar_has_target
      internal: true

    has_moving_target:
      id: radar_moving
      internal: true

    has_still_target:
      id: radar_still
      internal: true

  - platform: template
    name: "Occupied"
    id: occupied
    lambda: |-
      return id(radar_has_target).state;
    filters:
      - delayed_on: 1s
      - delayed_off: 20s

# ────────────────────────────────────────────────────
# Sensors
# ────────────────────────────────────────────────────
sensor:

  - platform: ld2450
    ld2450_id: ${ha_entity_suffix}_radar

    moving_target_count:
      id: moving_target_count
      accuracy_decimals: 0

    still_target_count:
      id: still_target_count
      accuracy_decimals: 0

# ────────────────────────────────────────────────────
# Watchdog (Optional but Recommended)
# Restarts radar module if no target updates occur
# for 5 minutes
# ────────────────────────────────────────────────────
interval:
  - interval: 5min
    then:
      - if:
          condition:
            lambda: |-
              return !id(radar_has_target).has_state();
          then:
            - logger.log: "LD2450 appears offline – restarting module"
            - button.press: radar_restart

button:
  - platform: ld2450
    ld2450_id: ${ha_entity_suffix}_radar
    restart:
      id: radar_restart
      name: "Radar Restart"
```

### Anything in the logs that might be useful for us?

```txt
[15:13:41.327][I][app:215]: ESPHome version 2026.2.0 compiled on 2026-02-19 13:57:35 -0800
[15:13:41.369][I][app:222]: ESP32 Chip: ESP32 rev1.0, 2 core(s)
[15:13:41.370][W][ld2450:777]: Max command length exceeded; ignoring
[15:13:41.628][W][ld2450:777]: Max command length exceeded; ignoring
[15:13:41.991][W][ld2450:777]: Max command length exceeded; ignoring
(repeats continuously)
```

### Additional information

This was working until I installed the latest updates

### PR DESCRIPTION
**Pull request by swoboda1337**
# What does this implement/fix?

Reverts the frame header synchronization added in #14135 and #14136 in favor of a simpler fix: increasing `MAX_LINE_LENGTH` so that the existing footer-based resynchronization can recover after losing sync.

Both components already check for frame footers at every byte position, which naturally resyncs the parser after losing sync (e.g. module restart or UART noise). The problem was that the buffers were sized exactly to fit the largest frame, so a desynced parser's footer could land at the overflow boundary and get discarded, causing infinite "Max command length exceeded" log spam. Increasing the buffer by 4 bytes (footer size) ensures the footer always lands inside the buffer.

- ld2450: 41 → 45 (zone query response = 40 bytes + 1 null + 4 footer)
- ld2410: 46 → 50 (engineering data frame = 45 bytes + 1 null + 4 footer)

## Types of changes

- [x] Bugfix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] Developer breaking change (an API change that could break external components)
- [ ] Code quality improvements to existing code or addition of tests
- [ ] Other

**Related issue or feature (if applicable):**

- fixes https://github.com/esphome/esphome/issues/14131

**Pull request in [esphome-docs](https://github.com/esphome/esphome-docs) with documentation (if applicable):**

- N/A

## Test Environment

- [ ] ESP32
- [x] ESP32 IDF
- [x] ESP8266
- [x] RP2040
- [ ] BK72xx
- [ ] RTL87xx
- [ ] LN882x
- [ ] nRF52840

## Example entry for `config.yaml`:

```yaml
# No config changes required - this is an internal buffer size fix
```

## Checklist:
  - [x] The code change is tested and works locally.
  - [x] Tests have been added to verify that the new code works (under `tests/` folder).

If user exposed functionality or configuration variables are added/changed:
  - [ ] Documentation added/updated in [esphome-docs](https://github.com/esphome/esphome-docs).

### CODE REVIEW

File: esphome/components/ld2410/ld2410.cpp [hunk 1]
```diff
@@ -601,28 +601,11 @@ void LD2410Component::readline_(int readch) {
...
-    if (this->buffer_pos_ == 0 && byte != DATA_FRAME_HEADER[0] && byte != CMD_FRAME_HEADER[0]) {
-      return;
-    }
-  }
-
   if (this->buffer_pos_ < MAX_LINE_LENGTH - 1) {
     this->buffer_data_[this->buffer_pos_++] = readch;
     this->buffer_data_[this->buffer_pos_] = 0;
   } else {
+    // We should never get here, but just in case...
```
Comment (bdraco) [inline esphome/components/ld2410/ld2410.cpp:608]: But isn't this the expected recover method now... shouldn't the we say buffer likely overflowed?

File: esphome/components/ld2450/ld2450.cpp [hunk 2]
```diff
@@ -769,28 +769,11 @@ void LD2450Component::readline_(int readch) {
...
-    if (this->buffer_pos_ == 0 && byte != DATA_FRAME_HEADER[0] && byte != CMD_FRAME_HEADER[0]) {
-      return;
-    }
-  }
-
   if (this->buffer_pos_ < MAX_LINE_LENGTH - 1) {
     this->buffer_data_[this->buffer_pos_++] = readch;
     this->buffer_data_[this->buffer_pos_] = 0;
   } else {
+    // We should never get here, but just in case...
```
Comment (bdraco) [inline esphome/components/ld2450/ld2450.cpp:776]: But isn't this the expected recover method now... shouldn't the we say buffer likely overflowed?

File: esphome/components/ld2410/ld2410.cpp (hunk 1 above)
Comment (swoboda1337) [reply esphome/components/ld2410/ld2410.cpp:608]: No we should hit the footer before we overflow

Comment (swoboda1337) [reply esphome/components/ld2410/ld2410.cpp:608]: The problem was the footer could straddle the end of the buffer. With the footer inside it should never happen

**Review by bdraco — APPROVED** [review]
