### PR TITLE
Fix the LiberTiny bug with UART pin setup

### LINKED ISSUE #11513: uart issues since 10.3 / 11.0-dev
### The problem

My tongou TOQ2CB2L tuya (cb3s+mcu) circuit breakers cannot initialize the mcu anymore since esphome 2025.10.3

I have tried various pin configs (explicitly setting/not-setting pullup, mode, etc)

### Which version of ESPHome has the issue?

2025.10.3

### What type of installation are you using?

Home Assistant Add-on

### What platform are you using?

BK72XX

### Component causing the issue

uart

### YAML Config

```yaml
esphome:
  name: breaker-grid
  friendly_name: breaker-grid
packages:
  defaults: !include includes/defaults.yaml
bk72xx:
  board: cb3s
  framework:
    options:
      LT_SERIAL_BUFFER_SIZE: 512
logger:
  baud_rate: 0
uart:
  rx_pin: 10
  tx_pin: 11
  baud_rate: 115200
  rx_buffer_size: 512
interval:
  - interval: 10s  # Adjust to 10-60s based on needs; too frequent might overload the MCU
    then:
      - lambda: id(tuyamcu).set_raw_datapoint_value(0x08, {});
tuya:
  #status_pin: 14
  id: tuyamcu
  on_datapoint_update:
    - sensor_datapoint: 6
      datapoint_type: raw
      then:
        - lambda: |-
            if (x.size() != 8) return;
            uint16_t volt_raw = (x[0] << 8) | x[1];
            id(phase_a_voltage).publish_state(volt_raw / 10.0f);
            uint32_t curr_raw = (x[2] << 16) | (x[3] << 8) | x[4];
            id(phase_a_current).publish_state(curr_raw / 1000.0f);
            uint32_t pow_raw = (x[5] << 16) | (x[6] << 8) | x[7];
            id(phase_a_power).publish_state(pow_raw);
    - sensor_datapoint: 7
      datapoint_type: raw
      then:
        - lambda: |-
            if (x.size() != 8) return;
            uint16_t volt_raw = (x[0] << 8) | x[1];
            id(phase_b_voltage).publish_state(volt_raw / 10.0f);
            uint32_t curr_raw = (x[2] << 16) | (x[3] << 8) | x[4];
            id(phase_b_current).publish_state(curr_raw / 1000.0f);
            uint32_t pow_raw = (x[5] << 16) | (x[6] << 8) | x[7];
            id(phase_b_power).publish_state(pow_raw);
    - sensor_datapoint: 8
      datapoint_type: raw
      then:
        - lambda: |-
            if (x.size() != 8) return;
            uint16_t volt_raw = (x[0] << 8) | x[1];
            id(phase_c_voltage).publish_state(volt_raw / 10.0f);
            uint32_t curr_raw = (x[2] << 16) | (x[3] << 8) | x[4];
            id(phase_c_current).publish_state(curr_raw / 1000.0f);
            uint32_t pow_raw = (x[5] << 16) | (x[6] << 8) | x[7];
            id(phase_c_power).publish_state(pow_raw);

sensor:
  - platform: internal_temperature
    name: "Internal Temperature"
  - platform: template
    name: "Phase A Voltage"
    id: phase_a_voltage
    unit_of_measurement: V
    accuracy_decimals: 1
    device_class: voltage
    state_class: measurement
  - platform: template
    name: "Phase A Current"
    id: phase_a_current
    unit_of_measurement: A
    accuracy_decimals: 3
    device_class: current
    state_class: measurement
  - platform: template
    name: "Phase A Power"
    id: phase_a_power
    unit_of_measurement: W
    accuracy_decimals: 0
    device_class: power
    state_class: measurement
  - platform: template
    name: "Phase B Voltage"
    id: phase_b_voltage
    unit_of_measurement: V
    accuracy_decimals: 1
    device_class: voltage
    state_class: measurement
  - platform: template
    name: "Phase B Current"
    id: phase_b_current
    unit_of_measurement: A
    accuracy_decimals: 3
    device_class: current
    state_class: measurement
  - platform: template
    name: "Phase B Power"
    id: phase_b_power
    unit_of_measurement: W
    accuracy_decimals: 0
    device_class: power
    state_class: measurement
  - platform: template
    name: "Phase C Voltage"
    id: phase_c_voltage
    unit_of_measurement: V
    accuracy_decimals: 1
    device_class: voltage
    state_class: measurement
  - platform: template
    name: "Phase C Current"
    id: phase_c_current
    unit_of_measurement: A
    accuracy_decimals: 3
    device_class: current
    state_class: measurement
  - platform: template
    name: "Phase C Power"
    id: phase_c_power
    unit_of_measurement: W
    accuracy_decimals: 0
    device_class: power
    state_class: measurement
  - platform: tuya
    name: "Total Power"
    sensor_datapoint: 139
    unit_of_measurement: W
    accuracy_decimals: 0
    device_class: power
    state_class: measurement
  - platform: tuya
    name: "Total Forward Energy"
    sensor_datapoint: 1
    unit_of_measurement: kWh
    accuracy_decimals: 3
    device_class: energy
    state_class: total_increasing
    filters:
      - multiply: 0.01
  - platform: tuya
    name: "Phase A Energy"
    sensor_datapoint: 125
    unit_of_measurement: kWh
    accuracy_decimals: 3
    device_class: energy
    state_class: total_increasing
    filters:
      - multiply: 0.01
  - platform: tuya
    name: "Phase B Energy"
    sensor_datapoint: 126
    unit_of_measurement: kWh
    accuracy_decimals: 3
    device_class: energy
    state_class: total_increasing
    filters:
      - multiply: 0.01
  - platform: tuya
    name: "Phase C Energy"
    sensor_datapoint: 127
    unit_of_measurement: kWh
    accuracy_decimals: 3
    device_class: energy
    state_class: total_increasing
    filters:
      - multiply: 0.01
  - platform: tuya
    name: "Phase A Temperature"
    sensor_datapoint: 131
    unit_of_measurement: °C
    accuracy_decimals: 1
    device_class: temperature
    state_class: measurement
    filters:
      - multiply: 0.1
  - platform: tuya
    name: "Phase B Temperature"
    sensor_datapoint: 132
    unit_of_measurement: °C
    accuracy_decimals: 1
    device_class: temperature
    state_class: measurement
    filters:
      - multiply: 0.1
  - platform: tuya
    name: "Phase C Temperature"
    sensor_datapoint: 133
    unit_of_measurement: °C
    accuracy_decimals: 1
    device_class: temperature
    state_class: measurement
    filters:
      - multiply: 0.1
  - platform: tuya
    name: "Neutral Temperature"
    sensor_datapoint: 134
    unit_of_measurement: °C
    accuracy_decimals: 1
    device_class: temperature
    state_class: measurement
    filters:
      - multiply: 0.1
  - platform: tuya
    name: "LC"
    sensor_datapoint: 15
    unit_of_measurement: mA
    accuracy_decimals: 0
    state_class: measurement

switch:
  - platform: tuya
    name: "Breaker Switch"
    switch_datapoint: 16
  - platform: tuya
    name: "Auto Reclose after UV/OV"
    switch_datapoint: 112
  - platform: tuya
    name: "Restore Default Settings"
    switch_datapoint: 113

number:
  - platform: tuya
    name: "OC Threshold"
    number_datapoint: 114
    min_value: 1
    max_value: 100
    step: 1
    unit_of_measurement: A
    mode: box
  - platform: tuya
    name: "OV Threshold"
    number_datapoint: 115
    min_value: 200
    max_value: 300
    step: 1
    unit_of_measurement: V
    mode: box
  - platform: tuya
    name: "UV Threshold"
    number_datapoint: 116
    min_value: 100
    max_value: 200
    step: 1
    unit_of_measurement: V
    mode: box
  - platform: tuya
    name: "LC Threshold"
    number_datapoint: 117
    min_value: 0
    max_value: 100
    step: 1
    unit_of_measurement: mA
    mode: box
  - platform: tuya
    name: "OT Threshold"
    number_datapoint: 118
    min_value: 30
    max_value: 100
    step: 0.1
    mode: box
    multiply: 10
    unit_of_measurement: °C
  - platform: tuya
    name: "OP Threshold"
    number_datapoint: 119
    min_value: 0
    max_value: 20
    step: 0.1
    multiply: 1000
    unit_of_measurement: kW
    mode: box
select:
  - platform: tuya
    enum_datapoint: 102
    name: OV Behaviour
    options:
      0: Do Nothing
      1: Warning Alarm
      2: Trip Breaker
  - platform: tuya
    enum_datapoint: 103
    name: UV Behaviour
    options:
      0: Do Nothing
      1: Warning Alarm
      2: Trip Breaker
  - platform: tuya
    enum_datapoint: 104
    name: OC Behaviour
    options:
      0: Do Nothing
      1: Warning Alarm
      2: Trip Breaker
  - platform: tuya
    enum_datapoint: 105
    name: OP Behaviour
    options:
      0: Do Nothing
      1: Warning Alarm
      2: Trip Breaker
  - platform: tuya
    enum_datapoint: 107
    name: OT Behaviour
    options:
      0: Do Nothing
      1: Warning Alarm
      2: Trip Breaker
  - platform: tuya
    enum_datapoint: 108
    name: LC Behaviour
    options:
      0: Do Nothing
      1: Warning Alarm
      2: Trip Breaker
text_sensor:
  - platform: tuya
    name: "Online State"
    sensor_datapoint: 109
    filters:
      - map:
        - 0 -> Offline
        - 1 -> Online
  - platform: tuya
    name: "Event"
    sensor_datapoint: 110
    filters:
      - map:
        - 0 -> Normal
        - 1 -> Over Current Trip
        - 2 -> Over Power Trip
        - 3 -> High Temp Trip
        - 4 -> Over Voltage Trip
        - 5 -> Under Voltage Trip
        - 6 -> Over Current Alarm
        - 7 -> Over Power Alarm
        - 8 -> High Temp Alarm
        - 9 -> Over Voltage Alarm
        - 10 -> Under Voltage Alarm
        - 11 -> Remote ON
        - 12 -> Remote OFF
        - 13 -> Manual ON
        - 14 -> Manual OFF
        - 15 -> Leakage Trip
        - 16 -> Leakage Alarm
        - 17 -> Restore Default
        - 18 -> Automatic Closing
        - 19 -> Electricity Shortage
        - 20 -> Electricity Shortage Alarm
        - 21 -> Timing switch ON
        - 22 -> Timing switch OFF
```

### Anything in the logs that might be useful for us?

```txt
[11:00:39.933][C][logger:261]: Logger:
[11:00:39.933][C][logger:261]:   Max Level: DEBUG
[11:00:39.933][C][logger:261]:   Initial Level: DEBUG
[11:00:39.940][C][logger:267]:   Log Baud Rate: 0
[11:00:39.940][C][logger:267]:   Hardware UART: DEFAULT
[11:00:39.951][C][uart.lt:106]: UART Bus:
[11:00:39.953][C][uart.lt:107]:   Type: hardware
[11:00:39.957][C][uart.lt:109]:   Port number: 1
[11:00:39.959][C][uart.lt:111]:   TX Pin: 11
[11:00:39.963][C][uart.lt:112]:   RX Pin: 10
[11:00:39.966][C][uart.lt:114]:   RX Buffer Size: 512
[11:00:39.968][C][uart.lt:116]:   Baud Rate: 115200 baud
[11:00:39.968][C][uart.lt:116]:   Data Bits: 8
[11:00:39.968][C][uart.lt:116]:   Parity: NONE
[11:00:39.968][C][uart.lt:116]:   Stop bits: 1
[11:00:39.991][C][template.sensor:015]: Template Sensor 'Phase A Voltage'
[11:00:39.991][C][template.sensor:015]:   State Class: 'measurement'
[11:00:39.991][C][template.sensor:015]:   Unit of Measurement: 'V'
[11:00:39.991][C][template.sensor:015]:   Accuracy Decimals: 1
[11:00:39.994][C][template.sensor:025]:   Device Class: 'voltage'
[11:00:39.997][C][template.sensor:362]:   Update Interval: 60.0s
[11:00:40.004][C][template.sensor:015]: Template Sensor 'Phase A Current'
[11:00:40.004][C][template.sensor:015]:   State Class: 'measurement'
[11:00:40.004][C][template.sensor:015]:   Unit of Measurement: 'A'
[11:00:40.004][C][template.sensor:015]:   Accuracy Decimals: 3
[11:00:40.007][C][template.sensor:025]:   Device Class: 'current'
[11:00:40.013][C][template.sensor:362]:   Update Interval: 60.0s
[11:00:40.020][C][template.sensor:015]: Template Sensor 'Phase A Power'
[11:00:40.020][C][template.sensor:015]:   State Class: 'measurement'
[11:00:40.020][C][template.sensor:015]:   Unit of Measurement: 'W'
[11:00:40.020][C][template.sensor:015]:   Accuracy Decimals: 0
[11:00:40.024][C][template.sensor:025]:   Device Class: 'power'
[11:00:40.027][C][template.sensor:362]:   Update Interval: 60.0s
[11:00:40.035][C][template.sensor:015]: Template Sensor 'Phase B Voltage'
[11:00:40.035][C][template.sensor:015]:   State Class: 'measurement'
[11:00:40.035][C][template.sensor:015]:   Unit of Measurement: 'V'
[11:00:40.035][C][template.sensor:015]:   Accuracy Decimals: 1
[11:00:40.036][C][template.sensor:025]:   Device Class: 'voltage'
[11:00:40.043][C][template.sensor:362]:   Update Interval: 60.0s
[11:00:40.050][C][template.sensor:015]: Template Sensor 'Phase B Current'
[11:00:40.050][C][template.sensor:015]:   State Class: 'measurement'
[11:00:40.050][C][template.sensor:015]:   Unit of Measurement: 'A'
[11:00:40.050][C][template.sensor:015]:   Accuracy Decimals: 3
[11:00:40.053][C][template.sensor:025]:   Device Class: 'current'
[11:00:40.053][C][template.sensor:362]:   Update Interval: 60.0s
[11:00:40.062][C][template.sensor:015]: Template Sensor 'Phase B Power'
[11:00:40.062][C][template.sensor:015]:   State Class: 'measurement'
[11:00:40.062][C][template.sensor:015]:   Unit of Measurement: 'W'
[11:00:40.062][C][template.sensor:015]:   Accuracy Decimals: 0
[11:00:40.064][C][template.sensor:025]:   Device Class: 'power'
[11:00:40.067][C][template.sensor:362]:   Update Interval: 60.0s
[11:00:40.078][C][template.sensor:015]: Template Sensor 'Phase C Voltage'
[11:00:40.078][C][template.sensor:015]:   State Class: 'measurement'
[11:00:40.078][C][template.sensor:015]:   Unit of Measurement: 'V'
[11:00:40.078][C][template.sensor:015]:   Accuracy Decimals: 1
[11:00:40.078][C][template.sensor:025]:   Device Class: 'voltage'
[11:00:40.078][C][template.sensor:362]:   Update Interval: 60.0s
[11:00:40.089][C][template.sensor:015]: Template Sensor 'Phase C Current'
[11:00:40.089][C][template.sensor:015]:   State Class: 'measurement'
[11:00:40.089][C][template.sensor:015]:   Unit of Measurement: 'A'
[11:00:40.089][C][template.sensor:015]:   Accuracy Decimals: 3
[11:00:40.091][C][template.sensor:025]:   Device Class: 'current'
[11:00:40.095][C][template.sensor:362]:   Update Interval: 60.0s
[11:00:40.102][C][template.sensor:015]: Template Sensor 'Phase C Power'
[11:00:40.102][C][template.sensor:015]:   State Class: 'measurement'
[11:00:40.102][C][template.sensor:015]:   Unit of Measurement: 'W'
[11:00:40.102][C][template.sensor:015]:   Accuracy Decimals: 0
[11:00:40.105][C][template.sensor:025]:   Device Class: 'power'
[11:00:40.107][C][template.sensor:362]:   Update Interval: 60.0s
[11:00:40.116][C][homeassistant.time:010]: Home Assistant Time:
[11:00:40.116][C][homeassistant.time:010]:   Timezone: 'CET-1CEST,M3.5.0,M10.5.0/3'
[11:00:40.128][C][restart.button:015]: Restart Button 'Microcontroller Reboot'
[11:00:40.130][C][restart.button:018]:   Icon: 'mdi:restart'
[11:00:40.154][C][internal_temperature:015]: Internal Temperature Sensor 'Internal Temperature'
[11:00:40.154][C][internal_temperature:015]:   State Class: 'measurement'
[11:00:40.154][C][internal_temperature:015]:   Unit of Measurement: '°C'
[11:00:40.154][C][internal_temperature:015]:   Accuracy Decimals: 1
[11:00:40.157][C][internal_temperature:025]:   Device Class: 'temperature'
[11:00:40.164][C][tuya.sensor:015]: Tuya Sensor 'Total Power'
[11:00:40.164][C][tuya.sensor:015]:   State Class: 'measurement'
[11:00:40.164][C][tuya.sensor:015]:   Unit of Measurement: 'W'
[11:00:40.164][C][tuya.sensor:015]:   Accuracy Decimals: 0
[11:00:40.166][C][tuya.sensor:025]:   Device Class: 'power'
[11:00:40.168][C][tuya.sensor:030]:   Sensor has datapoint ID 139
[11:00:40.179][C][tuya.sensor:015]: Tuya Sensor 'Total Forward Energy'
[11:00:40.179][C][tuya.sensor:015]:   State Class: 'total_increasing'
[11:00:40.179][C][tuya.sensor:015]:   Unit of Measurement: 'kWh'
[11:00:40.179][C][tuya.sensor:015]:   Accuracy Decimals: 3
[11:00:40.182][C][tuya.sensor:025]:   Device Class: 'energy'
[11:00:40.206][C][tuya.sensor:030]:   Sensor has datapoint ID 1
[11:00:40.206][C][tuya.sensor:015]: Tuya Sensor 'Phase A Energy'
[11:00:40.206][C][tuya.sensor:015]:   State Class: 'total_increasing'
[11:00:40.206][C][tuya.sensor:015]:   Unit of Measurement: 'kWh'
[11:00:40.206][C][tuya.sensor:015]:   Accuracy Decimals: 3
[11:00:40.206][C][tuya.sensor:025]:   Device Class: 'energy'
[11:00:40.206][C][tuya.sensor:030]:   Sensor has datapoint ID 125
[11:00:40.206][C][tuya.sensor:015]: Tuya Sensor 'Phase B Energy'
[11:00:40.206][C][tuya.sensor:015]:   State Class: 'total_increasing'
[11:00:40.206][C][tuya.sensor:015]:   Unit of Measurement: 'kWh'
[11:00:40.206][C][tuya.sensor:015]:   Accuracy Decimals: 3
[11:00:40.207][C][tuya.sensor:025]:   Device Class: 'energy'
[11:00:40.208][C][tuya.sensor:030]:   Sensor has datapoint ID 126
[11:00:40.214][C][tuya.sensor:015]: Tuya Sensor 'Phase C Energy'
[11:00:40.214][C][tuya.sensor:015]:   State Class: 'total_increasing'
[11:00:40.214][C][tuya.sensor:015]:   Unit of Measurement: 'kWh'
[11:00:40.214][C][tuya.sensor:015]:   Accuracy Decimals: 3
[11:00:40.218][C][tuya.sensor:025]:   Device Class: 'energy'
[11:00:40.220][C][tuya.sensor:030]:   Sensor has datapoint ID 127
[11:00:40.229][C][tuya.sensor:015]: Tuya Sensor 'Phase A Temperature'
[11:00:40.229][C][tuya.sensor:015]:   State Class: 'measurement'
[11:00:40.229][C][tuya.sensor:015]:   Unit of Measurement: '°C'
[11:00:40.229][C][tuya.sensor:015]:   Accuracy Decimals: 1
[11:00:40.231][C][tuya.sensor:025]:   Device Class: 'temperature'
[11:00:40.237][C][tuya.sensor:030]:   Sensor has datapoint ID 131
[11:00:40.248][C][tuya.sensor:015]: Tuya Sensor 'Phase B Temperature'
[11:00:40.248][C][tuya.sensor:015]:   State Class: 'measurement'
[11:00:40.248][C][tuya.sensor:015]:   Unit of Measurement: '°C'
[11:00:40.248][C][tuya.sensor:015]:   Accuracy Decimals: 1
[11:00:40.248][C][tuya.sensor:025]:   Device Class: 'temperature'
[11:00:40.255][C][tuya.sensor:030]:   Sensor has datapoint ID 132
[11:00:40.263][C][tuya.sensor:015]: Tuya Sensor 'Phase C Temperature'
[11:00:40.263][C][tuya.sensor:015]:   State Class: 'measurement'
[11:00:40.263][C][tuya.sensor:015]:   Unit of Measurement: '°C'
[11:00:40.263][C][tuya.sensor:015]:   Accuracy Decimals: 1
[11:00:40.265][C][tuya.sensor:025]:   Device Class: 'temperature'
[11:00:40.267][C][tuya.sensor:030]:   Sensor has datapoint ID 133
[11:00:40.279][C][tuya.sensor:015]: Tuya Sensor 'Neutral Temperature'
[11:00:40.279][C][tuya.sensor:015]:   State Class: 'measurement'
[11:00:40.279][C][tuya.sensor:015]:   Unit of Measurement: '°C'
[11:00:40.279][C][tuya.sensor:015]:   Accuracy Decimals: 1
[11:00:40.279][C][tuya.sensor:025]:   Device Class: 'temperature'
[11:00:40.279][C][tuya.sensor:030]:   Sensor has datapoint ID 134
[11:00:40.286][C][tuya.sensor:015]: Tuya Sensor 'LC'
[11:00:40.286][C][tuya.sensor:015]:   State Class: 'measurement'
[11:00:40.286][C][tuya.sensor:015]:   Unit of Measurement: 'mA'
[11:00:40.286][C][tuya.sensor:015]:   Accuracy Decimals: 0
[11:00:40.289][C][tuya.sensor:030]:   Sensor has datapoint ID 15
[11:00:40.307][C][tuya.switch:087]: Tuya Switch 'Breaker Switch'
[11:00:40.307][C][tuya.switch:087]:   Restore Mode: always OFF
[11:00:40.307][C][tuya.switch:024]:   Switch has datapoint ID 16
[11:00:40.310][C][tuya.switch:087]: Tuya Switch 'Auto Reclose after UV/OV'
[11:00:40.310][C][tuya.switch:087]:   Restore Mode: always OFF
[11:00:40.313][C][tuya.switch:024]:   Switch has datapoint ID 112
[11:00:40.322][C][tuya.switch:087]: Tuya Switch 'Restore Default Settings'
[11:00:40.322][C][tuya.switch:087]:   Restore Mode: always OFF
[11:00:40.324][C][tuya.switch:024]:   Switch has datapoint ID 113
[11:00:40.332][C][tuya.number:015]: Tuya Number 'OC Threshold'
[11:00:40.334][C][tuya.number:022]:   Unit of Measurement: 'A'
[11:00:40.336][C][tuya.number:080]:   Number has datapoint ID 114
[11:00:40.338][C][tuya.number:084]:   Datapoint type is unknown
[11:00:40.343][C][tuya.number:091]:   Restore Value: NO
[11:00:40.350][C][tuya.number:015]: Tuya Number 'OV Threshold'
[11:00:40.352][C][tuya.number:022]:   Unit of Measurement: 'V'
[11:00:40.356][C][tuya.number:080]:   Number has datapoint ID 115
[11:00:40.359][C][tuya.number:084]:   Datapoint type is unknown
[11:00:40.362][C][tuya.number:091]:   Restore Value: NO
[11:00:40.371][C][tuya.number:015]: Tuya Number 'UV Threshold'
[11:00:40.373][C][tuya.number:022]:   Unit of Measurement: 'V'
[11:00:40.375][C][tuya.number:080]:   Number has datapoint ID 116
[11:00:40.376][C][tuya.number:084]:   Datapoint type is unknown
[11:00:40.378][C][tuya.number:091]:   Restore Value: NO
[11:00:40.386][C][tuya.number:015]: Tuya Number 'LC Threshold'
[11:00:40.390][C][tuya.number:022]:   Unit of Measurement: 'mA'
[11:00:40.392][C][tuya.number:080]:   Number has datapoint ID 117
[11:00:40.394][C][tuya.number:084]:   Datapoint type is unknown
[11:00:40.397][C][tuya.number:091]:   Restore Value: NO
[11:00:40.404][C][tuya.number:015]: Tuya Number 'OT Threshold'
[11:00:40.406][C][tuya.number:022]:   Unit of Measurement: '°C'
[11:00:40.408][C][tuya.number:080]:   Number has datapoint ID 118
[11:00:40.411][C][tuya.number:084]:   Datapoint type is unknown
[11:00:40.415][C][tuya.number:091]:   Restore Value: NO
[11:00:40.420][C][tuya.number:015]: Tuya Number 'OP Threshold'
[11:00:40.422][C][tuya.number:022]:   Unit of Measurement: 'kW'
[11:00:40.426][C][tuya.number:080]:   Number has datapoint ID 119
[11:00:40.428][C][tuya.number:084]:   Datapoint type is unknown
[11:00:40.431][C][tuya.number:091]:   Restore Value: NO
[11:00:40.438][C][tuya.select:046]: Tuya Select 'OV Behaviour'
[11:00:40.442][C][tuya.select:047]:   Select has datapoint ID 102
[11:00:40.442][C][tuya.select:047]:   Data type: enum
[11:00:40.442][C][tuya.select:047]:   Options are:
[11:00:40.442][C][tuya.select:054]:     0: Do Nothing
[11:00:40.443][C][tuya.select:054]:     1: Warning Alarm
[11:00:40.452][C][tuya.select:054]:     2: Trip Breaker
[11:00:40.457][C][tuya.select:046]: Tuya Select 'UV Behaviour'
[11:00:40.459][C][tuya.select:047]:   Select has datapoint ID 103
[11:00:40.459][C][tuya.select:047]:   Data type: enum
[11:00:40.459][C][tuya.select:047]:   Options are:
[11:00:40.461][C][tuya.select:054]:     0: Do Nothing
[11:00:40.463][C][tuya.select:054]:     1: Warning Alarm
[11:00:40.465][C][tuya.select:054]:     2: Trip Breaker
[11:00:40.470][C][tuya.select:046]: Tuya Select 'OC Behaviour'
[11:00:40.473][C][tuya.select:047]:   Select has datapoint ID 104
[11:00:40.473][C][tuya.select:047]:   Data type: enum
[11:00:40.473][C][tuya.select:047]:   Options are:
[11:00:40.475][C][tuya.select:054]:     0: Do Nothing
[11:00:40.477][C][tuya.select:054]:     1: Warning Alarm
[11:00:40.479][C][tuya.select:054]:     2: Trip Breaker
[11:00:40.488][C][tuya.select:046]: Tuya Select 'OP Behaviour'
[11:00:40.491][C][tuya.select:047]:   Select has datapoint ID 105
[11:00:40.491][C][tuya.select:047]:   Data type: enum
[11:00:40.491][C][tuya.select:047]:   Options are:
[11:00:40.495][C][tuya.select:054]:     0: Do Nothing
[11:00:40.497][C][tuya.select:054]:     1: Warning Alarm
[11:00:40.501][C][tuya.select:054]:     2: Trip Breaker
[11:00:40.508][C][tuya.select:046]: Tuya Select 'OT Behaviour'
[11:00:40.512][C][tuya.select:047]:   Select has datapoint ID 107
[11:00:40.512][C][tuya.select:047]:   Data type: enum
[11:00:40.512][C][tuya.select:047]:   Options are:
[11:00:40.514][C][tuya.select:054]:     0: Do Nothing
[11:00:40.518][C][tuya.select:054]:     1: Warning Alarm
[11:00:40.520][C][tuya.select:054]:     2: Trip Breaker
[11:00:40.528][C][tuya.select:046]: Tuya Select 'LC Behaviour'
[11:00:40.531][C][tuya.select:047]:   Select has datapoint ID 108
[11:00:40.531][C][tuya.select:047]:   Data type: enum
[11:00:40.531][C][tuya.select:047]:   Options are:
[11:00:40.532][C][tuya.select:054]:     0: Do Nothing
[11:00:40.536][C][tuya.select:054]:     1: Warning Alarm
[11:00:40.540][C][tuya.select:054]:     2: Trip Breaker
[11:00:40.546][C][tuya.text_sensor:036]: Tuya Text Sensor:
[11:00:40.555][C][tuya.text_sensor:037]:   Text Sensor has datapoint ID 109
[11:00:40.561][C][tuya.text_sensor:036]: Tuya Text Sensor:
[11:00:40.565][C][tuya.text_sensor:037]:   Text Sensor has datapoint ID 110
[11:00:40.570][C][esphome.ota:093]: Over-The-Air updates:
[11:00:40.570][C][esphome.ota:093]:   Address: breaker-grid.local:8892
[11:00:40.570][C][esphome.ota:093]:   Version: 2
[11:00:40.572][C][esphome.ota:100]:   Password configured
[11:00:40.586][C][safe_mode:018]: Safe Mode:
[11:00:40.586][C][safe_mode:018]:   Successful after: 60s
[11:00:40.586][C][safe_mode:018]:   Invoke after: 10 attempts
[11:00:40.586][C][safe_mode:018]:   Duration: 300s
[11:00:40.593][C][api:222]: Server:
[11:00:40.593][C][api:222]:   Address: breaker-grid.local:6053
[11:00:40.593][C][api:222]:   Listen backlog: 4
[11:00:40.593][C][api:222]:   Max connections: 8
[11:00:40.594][C][api:234]:   Noise encryption: NO
[11:00:40.606][C][mdns:179]: mDNS:
[11:00:40.606][C][mdns:179]:   Hostname: breaker-grid
[11:00:40.614][C][lt.component:013]: LibreTiny:
[11:00:40.614][C][lt.component:013]:   Version: v1.9.1+sha.284b510 on cb3s, compiled at Oct 24 2025 09:16:18, GCC 10.3.1 (-O1)
[11:00:40.614][C][lt.component:013]:   Loglevel: 3
[11:00:40.628][C][tuya:041]: Tuya:
[11:00:40.630][C][tuya:044]:   Initialization failed. Current init_state: 0
[11:00:40.633][C][tuya:049]:   If no further output is received, confirm that this is a supported Tuya device.
[11:00:47.017][D][tuya:678]: Setting datapoint 8 to 
[11:00:47.021][W][tuya:681]: Setting unknown datapoint 8
[11:00:48.560][E][tuya:489]: Initialization failed at init_state 0
[11:00:50.724][D][sensor:131]: 'Internal Temperature': Sending state 32.88000 °C with 1 decimals of accuracy
[11:00:50.914][E][tuya:489]: Initialization failed at init_state 0
[11:00:57.017][D][tuya:678]: Setting datapoint 8 to 
[11:00:57.022][W][tuya:681]: Setting unknown datapoint 8
[11:00:58.561][E][tuya:489]: Initialization failed at init_state 0
```

### Additional information

I also tried the open uart fixes PR, latest 2025.11.0 dev, and as mentioned, all sensible pin configs.

### PR DESCRIPTION
**Pull request by asergunov**
# What does this implement/fix?

Problem: once pin->setup() is called pin becomes a GPIO pin. But Hardware UART can't use GPIO pins. It needs pin to be in special UART mode.

So we don't call pin setup initializing the Hardware UART for LiberTiny platform

- If not pin flags set:
  - if hardware UART is using: no pin initialization
  - if software UART is usgin: calling pin->setup()
- If any pin flag set:
  - if hardware UART is using:
    - if we have software UART supported: using software UART with info message
    - if we don't have software UART supported: no pin initialization with Warning message
  - if software UART is usging: calling pin->setup()

## Types of changes

- [x] Bugfix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] Code quality improvements to existing code or addition of tests
- [ ] Other

**Related issue or feature (if applicable):**

- fixes https://github.com/esphome/esphome/issues/11513

## Test Environment

- [ ] ESP32
- [ ] ESP32 IDF
- [ ] ESP8266
- [ ] RP2040
- [x] BK72xx
- [ ] RTL87xx
- [ ] nRF52840

## Example entry for `config.yaml`:

```yaml
# Example config.yaml

```

## Checklist:
  - [x] The code change is tested and works locally.
  - [ ] Tests have been added to verify that the new code works (under `tests/` folder).

If user exposed functionality or configuration variables are added/changed:
  - [ ] Documentation added/updated in [esphome-docs](https://github.com/esphome/esphome-docs).

### CODE REVIEW

**Comment by tbrasser** [comment]
Tried but getting:

```
src/esphome/components/uart/uart_component_libretiny.cpp: 
In lambda function: 
src/esphome/components/uart/uart_component_libretiny.cpp:54:45: 
error: expected '{' before 'bool' 
54 | auto shouldFallbackToSoftwareSerial = [&] bool { 
   |                                       ^~~~ 
src/esphome/components/uart/uart_component_libretiny.cpp: 
In member function 
'virtual void esphome::uart::LibreTinyUARTComponent::setup()': 
src/esphome/components/uart/uart_component_libretiny.cpp:54:45: 
error: expected ',' or ';' before 'bool' 
src/esphome/components/uart/uart_component_libretiny.cpp:85:43: 
error: could not convert 'shouldFallbackToSoftwareSerial.esphome::uart::LibreTinyUARTComponent::setup()::<lambda()>()' from 'void' to 'bool' 
85 | !shouldFallbackToSoftwareSerial()) { 
   | ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^~
   | 
   | 
   | void 
src/esphome/components/uart/uart_component_libretiny.cpp:85:43: 
error: in argument to unary ! 
src/esphome/components/uart/uart_component_libretiny.cpp:92:43: 
error: could not convert 'shouldFallbackToSoftwareSerial.esphome::uart::LibreTinyUARTComponent::setup()::<lambda()>()' from 'void' to 'bool' 
92 | !shouldFallbackToSoftwareSerial()) { 
   | ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^~
   | 
   | 
   | void 
src/esphome/components/uart/uart_component_libretiny.cpp:92:43: 
error: in argument to unary ! 
Compiling .pioenvs/breaker-grid/src/esphome/core/entity_base.cpp.o 
Compiling .pioenvs/breaker-grid/src/esphome/core/helpers.cpp.o
```

**Comment by ssieb** [comment]
Don't fallback to software serial.  If flags are set on the hardware uart, then throw a validation error.  If someone needs to set pin modes, they can use other pins with the software serial.  Software serial is terrible and shouldn't be inflicted on someone without their knowledge.

**Comment by asergunov** [comment]
@tbrasser Sorry my bad. Doing Go more than C++. I've fixed the build errors. Could you give it a test?

**Comment by asergunov** [comment]
@ssieb It's hard to make validation error because it decides between Hardware and Software Serial in the C++ code by compilation flags. Also it decides by pin numbers which are also macro definitions in C++. So we have no idea from Python code what it will choose. But I can see it's really easy to mess up already and fall to Software serial already just giving it wrong pin numbers or swap them.

**Comment by tbrasser** [comment]
> @tbrasser Sorry my bad. Doing Go more than C++. I've fixed the build errors. Could you give it a test?


Works! Nice!

**Comment by asergunov** [comment]
> > @tbrasser Sorry my bad. Doing Go more than C++. I've fixed the build errors. Could you give it a test?
> 
> 
> Works! Nice!
> 

Awesome! Could you also try if you set RX pull up? Will it use Software Serial? Will rx pin will actually pulled up or setting will be overridden by Software uart itself?

**Comment by tbrasser** [comment]
Still same hardware serial working behavior with:

```yaml
uart:
  rx_pin:
    number: 10
    mode:
      input: true
      pullup: true
  tx_pin: 11
  baud_rate: 115200
  rx_buffer_size: 512
```

**Comment by asergunov** [comment]
@tbrasser this could mean you don't have Software serial. In this case it should print `Pin flags are set but not supported for hardware serial. Ignoring` warning in log.

**Comment by tbrasser** [comment]
It's a cb3s, not sure about these beken chips.
The tuya mcu is always connected to TX1 and RX1

Nothing in wifi logs, would have to open device and solder to TX2 to read serial logs

**Comment by asergunov** [comment]
> It's a cb3s, not sure about these beken chips.
> The tuya mcu is always connected to TX1 and RX1
> 
> Nothing in wifi logs, would have to open device and solder to TX2 to read serial logs

It's in setup. Before WiFi initialised. I think I can make it print something in dumpConfig.

File: esphome/components/uart/uart_component_libretiny.cpp [hunk 1]
```diff
@@ -46,40 +46,58 @@ uint16_t LibreTinyUARTComponent::get_config() {
...
-  if (this->tx_pin_ && this->rx_pin_ != this->tx_pin_) {
-    this->tx_pin_->setup();
-  }
-
   int8_t tx_pin = tx_pin_ == nullptr ? -1 : tx_pin_->get_pin();
   int8_t rx_pin = rx_pin_ == nullptr ? -1 : rx_pin_->get_pin();
   bool tx_inverted = tx_pin_ != nullptr && tx_pin_->is_inverted();
   bool rx_inverted = rx_pin_ != nullptr && rx_pin_->is_inverted();
 
+  auto shouldFallbackToSoftwareSerial = [&]() -> bool {
```
Comment (jesserockz) [inline esphome/components/uart/uart_component_libretiny.cpp:54]: This should not be a function called multiple times. It should be a simple boolean value that is set once

**Review by jesserockz — CHANGES_REQUESTED** [review]

File: esphome/components/uart/uart_component_libretiny.cpp (hunk 1 above)
Comment (asergunov) [reply esphome/components/uart/uart_component_libretiny.cpp:54]: This way it's called only if all other checks in `if` conditions passed. So user will have log messages only fallback actually happened or failed because there is no software uart available

**Comment by samuelolteanu** [comment]
Tried the pr and seems to be fine.

**Comment by justlikeef** [comment]
Resolved the issue for me, also.

**Review by jesserockz — APPROVED** [review]
