### PR TITLE
[sprinkler] Squash a few bugs + minor optimization

### LINKED ISSUE #4648: Sprinkler starts valves when Standby switch is on.
### The problem

Sprinkler controller is configured with Standby switch. When Standby switch is on, and one of actions, like `sprinkler.next_valve, sprinkler.previous_valve` (others are not tested), are called - sprinkler starts valves. 

From one side,  according to documentation sprinkler should not start any valves in Standby mode, from other side - easy workaround exists - check if sprinkler in standby mode before triggering any actions. 

### Which version of ESPHome has the issue?

2023.6.2

### What type of installation are you using?

Home Assistant Add-on

### Which version of Home Assistant has the issue?

2023.6.3

### What platform are you using?

ESP32

### Board

esp32 devkit v4

### Component causing the issue

sprinkler

### Example YAML snippet

```yaml
sprinkler:
  - id: sp_ctrlr
    main_switch:
      name: Sprinklers
      id: sp_main_switch
    standby_switch: 
      name: SP StandBy
      id: sp_standby_sw
...

  - platform: nextion
    id: nxt_sp_btnForward
    page_id: ${sp_home_page_id}
    component_id: ${sp_btn_next_id}
    component_name: ${sp_home_page_id}.${sp_btn_next_objname}
    on_press:
      then:
        - sprinkler.next_valve: sp_ctrlr
```

### Anything in the logs that might be useful for us?

_No response_

### Additional information

_No response_

### LINKED ISSUE #5740: Sprinkler Controller, running a cycle leads to panic and automatic reboot
### The problem

ESP32 crashes and reboots when running a cycle. I ran the same YAML on an ESP8266 based board and gets the same crash/reboot while running an irrigation cycle.

```
[18:46:56]Guru Meditation Error: Core  1 panic'ed (LoadProhibited). Exception was unhandled.
[18:46:56]
[18:46:56]Core  1 register dump:
[18:46:56]PC      : 0x400e2f44  PS      : 0x00060530  A0      : 0x80205d00  A1      : 0x3ffcd9e0  
[18:46:56]A2      : 0x3ffbc8fc  A3      : 0x00000000  A4      : 0x3ffbca98  A5      : 0x000035c0  
[18:46:56]A6      : 0x3ffcd9c4  A7      : 0x00000000  A8      : 0x800e2f36  A9      : 0x3ffcd9c0  
[18:46:56]A10     : 0x3ffbca68  A11     : 0x00000000  A12     : 0x00002710  A13     : 0x00060f23  
[18:46:56]A14     : 0x00060f20  A15     : 0x00000001  SAR     : 0x0000000a  EXCCAUSE: 0x0000001c  
[18:46:56]EXCVADDR: 0x00000028  LBEG    : 0x40084605  LEND    : 0x4008460d  LCOUNT  : 0x00000027  
[18:46:56]
[18:46:56]
[18:46:56]Backtrace:0x400e2f41:0x3ffcd9e00x40205cfd:0x3ffcda00 0x40205d61:0x3ffcda20 0x400ea350:0x3ffcda40 0x400ec942:0x3ffcda70 0x400f9115:0x3ffcda90 
[18:46:56]
[18:46:56]
[18:46:56]
[18:46:56]
[18:46:56]ELF file SHA256: 0000000000000000
[18:46:56]
[18:46:56]Rebooting...
[18:46:56]ets Jun  8 2016 00:22:57
[18:46:56]
[18:46:56]rst:0xc (SW_CPU_RESET),boot:0x12 (SPI_FAST_FLASH_BOOT)
[18:46:56]configsip: 0, SPIWP:0xee
[18:46:56]clk_drv:0x00,q_drv:0x00,d_drv:0x00,cs0_drv:0x00,hd_drv:0x00,wp_drv:0x00
[18:46:56]mode:DIO, clock div:2
[18:46:56]load:0x3fff0030,len:1184
[18:46:56]load:0x40078000,len:13132
[18:46:56]load:0x40080400,len:3036
[18:46:56]entry 0x400805e4
```

### Which version of ESPHome has the issue?

2024.4.1

### What type of installation are you using?

Home Assistant Add-on

### Which version of Home Assistant has the issue?

2024.4.4

### What platform are you using?

ESP32

### Board

LILYGO T-Relay ESP32 (4ch with ESP32-WROOM-B)

### Component causing the issue

Sprinkler Controller

### Example YAML snippet

```yaml
sprinkler:
  - id: lawn_sprinkler_ctrlr
    main_switch: "Start Irrigation Cycle"
    auto_advance_switch: "Irrigation Auto Advance"
    reverse_switch: "Irrigation Reverse"
    multiplier_number: "Irrigation Multiplier"
    repeat_number: "Irrigation Repeat"
    valve_overlap: 5s
    valves:
      - valve_switch: "Flowers Front"
        enable_switch:
          id: enable_switch_valve2
          name: "Enable irrigation for Flowers Front"
          restore_mode: RESTORE_DEFAULT_ON
        run_duration: 10s
        valve_switch_id: irrigation_valve_sw2

      - valve_switch: "Trees"
        enable_switch:
          id: enable_switch_valve3
          name: "Enable irrigation for Trees"
          restore_mode: RESTORE_DEFAULT_ON
        run_duration: 10s
        valve_switch_id: irrigation_valve_sw3

      - valve_switch: "Flowers Back"
        enable_switch:
          id: enable_switch_valve4
          name: "Enable irrigation for Flowers Back"
          restore_mode: RESTORE_DEFAULT_ON
        run_duration: 10s
        valve_switch_id: irrigation_valve_sw4

      # Relay/Valve #1 for Lawn
      - valve_switch: "Lawn"
        enable_switch:
          id: enable_switch_valve1
          name: "Enable irrigation for Lawn"
          restore_mode: RESTORE_DEFAULT_OFF
        run_duration: 10s
        valve_switch_id: irrigation_valve_sw1

button:
  - platform: restart
    id: irrigation_controller_restart_button
    name: "Irrigation Controller Restart Button"

switch:
  - platform: gpio
    pin: 21
    # Garden Irrigation - Valve 1
    id: irrigation_valve_sw1

  - platform: gpio
    pin: 19
    #Garden Irrigation - Valve 2
    id: irrigation_valve_sw2

  - platform: gpio
    pin: 18
    #Garden Irrigation - Valve 3
    id: irrigation_valve_sw3

  - platform: gpio
    pin: 5
    #Garden Irrigation - Valve 4
    id: irrigation_valve_sw4
```

### Anything in the logs that might be useful for us?

```txt
[18:46:41][D][switch:012]: 'Start Irrigation Cycle' Turning ON.
[18:46:41][VV][sprinkler:1488]: fsm_transition_ called; state is IDLE
[18:46:41][VV][scheduler:032]: set_timeout(name='Start Irrigation Cyclesm', timeout=5000)
[18:46:41][VV][sprinkler:1651]: Timer 0 started for 5 sec
[18:46:41][D][sprinkler:1427]: CYCLE is starting valve 0 for 10 seconds, cycle 1 of 1
[18:46:41][D][switch:012]: 'irrigation_valve_sw2' Turning ON.
[18:46:41][D][switch:055]: 'irrigation_valve_sw2': Sending state ON
[18:46:41][VV][sprinkler:1531]: fsm_transition_ complete; new state is ACTIVE
[18:46:41][D][switch:055]: 'Start Irrigation Cycle': Sending state ON
[18:46:41][V][json:038]: Attempting to allocate 512 bytes for JSON serialization
[18:46:41][V][json:058]: Size after shrink 80 bytes
[18:46:41][VV][api.service:156]: send_switch_state_response: SwitchStateResponse {
  key: 2268764749
  state: YES
}
[18:46:41][W][component:237]: Component web_server took a long time for an operation (80 ms).
[18:46:41][W][component:238]: Components should block for at most 30 ms.
[18:46:41][D][switch:055]: 'Flowers Front': Sending state ON
[18:46:41][V][json:038]: Attempting to allocate 512 bytes for JSON serialization
[18:46:41][V][json:058]: Size after shrink 72 bytes
[18:46:41][VV][api.service:156]: send_switch_state_response: SwitchStateResponse {
  key: 3963119055
  state: YES
}
[18:46:42][VV][scheduler:226]: Running interval '' with interval=10000 last_execution=16357 (now=26358)
[18:46:46][VV][scheduler:226]: Running timeout 'Start Irrigation Cyclesm' with interval=5000 last_execution=25734 (now=30740)
[18:46:46][VV][sprinkler:1682]: State machine timer expired
[18:46:46][VV][sprinkler:1488]: fsm_transition_ called; state is ACTIVE
[18:46:46][D][sprinkler:1296]: Marking valve 0 complete
[18:46:46][VV][scheduler:032]: set_timeout(name='Start Irrigation Cyclesm', timeout=5000)
[18:46:46][VV][sprinkler:1651]: Timer 0 started for 5 sec
[18:46:46][D][sprinkler:1427]: CYCLE is starting valve 1 for 10 seconds, cycle 1 of 1
[18:46:46][D][switch:012]: 'irrigation_valve_sw3' Turning ON.
[18:46:46][D][switch:055]: 'irrigation_valve_sw3': Sending state ON
[18:46:46][VV][sprinkler:1531]: fsm_transition_ complete; new state is ACTIVE
[18:46:46][W][component:237]: Component sprinkler took a long time for an operation (63 ms).
[18:46:46][W][component:238]: Components should block for at most 30 ms.
[18:46:46][D][switch:055]: 'Trees': Sending state ON
[18:46:46][V][json:038]: Attempting to allocate 512 bytes for JSON serialization
[18:46:46][E][json:043]: Could not allocate memory for JSON document! Requested 512 bytes, largest free heap block: 1396 bytes
[18:46:46][VV][api.service:156]: send_switch_state_response: SwitchStateResponse {
  key: 3882419280
  state: YES
}
[18:46:48][VV][scheduler:226]: Running interval '' with interval=60000 last_execution=4294939677 (now=32382)
[18:46:51][VV][scheduler:226]: Running timeout 'Start Irrigation Cyclesm' with interval=5000 last_execution=30763 (now=35765)
[18:46:51][VV][sprinkler:1682]: State machine timer expired
[18:46:51][VV][sprinkler:1488]: fsm_transition_ called; state is ACTIVE
[18:46:51][D][sprinkler:1296]: Marking valve 1 complete
[18:46:51][VV][scheduler:032]: set_timeout(name='Start Irrigation Cyclesm', timeout=5000)
[18:46:51][VV][sprinkler:1651]: Timer 0 started for 5 sec
[18:46:51][VV][sprinkler:1531]: fsm_transition_ complete; new state is ACTIVE
[18:46:51][D][switch:016]: 'irrigation_valve_sw2' Turning OFF.
[18:46:51][D][switch:055]: 'irrigation_valve_sw2': Sending state OFF
[18:46:51][D][switch:055]: 'Flowers Front': Sending state OFF
[18:46:51][V][json:038]: Attempting to allocate 512 bytes for JSON serialization
[18:46:51][V][json:058]: Size after shrink 72 bytes
[18:46:51][VV][api.service:156]: send_switch_state_response: SwitchStateResponse {
  key: 3963119055
  state: NO
}
[18:46:52][VV][scheduler:226]: Running interval '' with interval=10000 last_execution=26357 (now=36358)
[18:46:56][VV][scheduler:226]: Running timeout 'Start Irrigation Cyclesm' with interval=5000 last_execution=35784 (now=40784)
[18:46:56][VV][sprinkler:1682]: State machine timer expired
[18:46:56][VV][sprinkler:1488]: fsm_transition_ called; state is ACTIVE
[18:46:56][D][sprinkler:1296]: Marking valve 2 complete
[18:46:56][VV][scheduler:032]: set_timeout(name='Start Irrigation Cyclesm', timeout=5000)
[18:46:56][VV][sprinkler:1651]: Timer 0 started for 5 sec
[18:46:56][D][sprinkler:1427]: CYCLE is starting valve 3 for 10 seconds, cycle 1 of 1
[18:46:56][D][switch:012]: 'irrigation_valve_sw1' Turning ON.
[18:46:56][D][switch:055]: 'irrigation_valve_sw1': Sending state ON
[18:46:56][VV][sprinkler:1531]: fsm_transition_ complete; new state is ACTIVE
[18:46:56][W][component:237]: Component sprinkler took a long time for an operation (62 ms).
[18:46:56][W][component:238]: Components should block for at most 30 ms.
[18:46:56][D][switch:055]: 'Lawn': Sending state ON
[18:46:56][V][json:038]: Attempting to allocate 512 bytes for JSON serialization
[18:46:56][V][json:058]: Size after shrink 60 bytes
[18:46:56][VV][api.service:156]: send_switch_state_response: SwitchStateResponse {
  key: 557079219
  state: YES
}
[18:46:56][D][switch:016]: 'irrigation_valve_sw3' Turning OFF.
[18:46:56][D][switch:055]: 'irrigation_valve_sw3': Sending state OFF
[18:46:56]Guru Meditation Error: Core  1 panic'ed (LoadProhibited). Exception was unhandled.
[18:46:56]
[18:46:56]Core  1 register dump:
[18:46:56]PC      : 0x400e2f44  PS      : 0x00060530  A0      : 0x80205d00  A1      : 0x3ffcd9e0  
[18:46:56]A2      : 0x3ffbc8fc  A3      : 0x00000000  A4      : 0x3ffbca98  A5      : 0x000035c0  
[18:46:56]A6      : 0x3ffcd9c4  A7      : 0x00000000  A8      : 0x800e2f36  A9      : 0x3ffcd9c0  
[18:46:56]A10     : 0x3ffbca68  A11     : 0x00000000  A12     : 0x00002710  A13     : 0x00060f23  
[18:46:56]A14     : 0x00060f20  A15     : 0x00000001  SAR     : 0x0000000a  EXCCAUSE: 0x0000001c  
[18:46:56]EXCVADDR: 0x00000028  LBEG    : 0x40084605  LEND    : 0x4008460d  LCOUNT  : 0x00000027  
[18:46:56]
[18:46:56]
[18:46:56]Backtrace:0x400e2f41:0x3ffcd9e00x40205cfd:0x3ffcda00 0x40205d61:0x3ffcda20 0x400ea350:0x3ffcda40 0x400ec942:0x3ffcda70 0x400f9115:0x3ffcda90 
[18:46:56]
[18:46:56]
[18:46:56]
[18:46:56]
[18:46:56]ELF file SHA256: 0000000000000000
[18:46:56]
[18:46:56]Rebooting...
[18:46:56]ets Jun  8 2016 00:22:57
[18:46:56]
[18:46:56]rst:0xc (SW_CPU_RESET),boot:0x12 (SPI_FAST_FLASH_BOOT)
[18:46:56]configsip: 0, SPIWP:0xee
[18:46:56]clk_drv:0x00,q_drv:0x00,d_drv:0x00,cs0_drv:0x00,hd_drv:0x00,wp_drv:0x00
[18:46:56]mode:DIO, clock div:2
[18:46:56]load:0x3fff0030,len:1184
[18:46:56]load:0x40078000,len:13132
[18:46:56]load:0x40080400,len:3036
[18:46:56]entry 0x400805e4
```

### Additional information

_No response_

### LINKED ISSUE #6148: Guru Meditation Error when using sprinkler controller with valves without pump_switch_id.
### The problem

Hi.
When I have a mix of valves with and  without  pump_switch_id, esp32 crash when switching zones.
Error: EXCVADDR: 0x00000010 indicate null pointer to structure.

```
    sprinkler:
      - id: mysprinklerctrl
        valve_open_delay: 1s
        next_prev_ignore_disabled: true
        pump_switch_off_during_valve_open_delay: false
      ...
      - valve_switch_id: valve_switch_12
        pump_switch_id: pump_switch
        ...
      - valve_switch_id: valve_over_pressure
        # pump_switch_id: pump_switch
```
Enabling valve_over_pressure zone after valve_switch_12 cause:

```
Guru Meditation Error: Core  1 panic'ed (LoadProhibited). Exception was unhandled.
Core  1 register dump:
PC      : 0x400dfda5  PS      : 0x00060930  A0      : 0x800dfe2c  A1      : 0x3ffb2610  
A2      : 0x3ffb457c  A3      : 0x3ffcab7c  A4      : 0x00000000  A5      : 0x00000001  
A6      : 0x3ffb4718  A7      : 0x00000010  A8      : 0x800dfda5  A9      : 0x3ffb25f0  
A10     : 0x00000000  A11     : 0x00000000  A12     : 0x3f418213  A13     : 0x3ffb8ab0  
A14     : 0x00000003  A15     : 0x00060023  SAR     : 0x00000020  EXCCAUSE: 0x0000001c  
EXCVADDR: 0x00000010  LBEG    : 0x40089c90  LEND    : 0x40089ca6  LCOUNT  : 0xffffffff  

Backtrace:0x400dfda2:0x3ffb26100x400dfe29:0x3ffb2630 0x400dfe65:0x3ffb2650 
0x400dfe81:0x3ffb2670 0x400dfea9:0x3ffb2690 0x400e0864:0x3ffb26b0 0x400e0de5:0x3ffb2720
0x400e0fa9:0x3ffb2740 0x40186fc1:0x3ffb2760 0x400ece5b:0x3ffb2780 0x400ea7e9:0x3ffb27d0
0x400edb76:0x3ffb2800 0x40100665:0x3ffb2820
```

My usecase is to have a special zone enabled only when over pressure event happen to drain it out, so when enabled pump should be off and valve open for short time.

Regards.

### Which version of ESPHome has the issue?

2024.6.1 Aug 13 2024, 07:34:55

### What type of installation are you using?

Docker

### Which version of Home Assistant has the issue?

_No response_

### What platform are you using?

ESP32

### Board

esp32dev

### Component causing the issue

_No response_

### Example YAML snippet

_No response_

### Anything in the logs that might be useful for us?

_No response_

### Additional information

_No response_

### LINKED ISSUE #6306: In member function 'bool esphome::sprinkler::Sprinkler::is_a_valid_valve(size_t)'
### The problem

Compiling .pioenvs/irrigation-control/src/esphome/components/switch/switch.o
src/esphome/components/sprinkler/sprinkler.cpp: In member function 'bool esphome::sprinkler::Sprinkler::is_a_valid_valve(size_t)':
src/esphome/components/sprinkler/sprinkler.cpp:1030:25: warning: comparison of unsigned expression >= 0 is always true [-Wtype-limits]
   return ((valve_number >= 0) && (valve_number < this->number_of_valves()));

### Which version of ESPHome has the issue?

2024-09-02

### What type of installation are you using?

Home Assistant Add-on

### Which version of Home Assistant has the issue?

_No response_

### What platform are you using?

ESP32

### Board

_No response_

### Component causing the issue

_No response_

### Example YAML snippet

```yaml
probably this 

return ((valve_number >= 0) && (valve_number < this->number_of_valves()));


should be replaced with

return (valve_number < this->number_of_valves());
```

### Anything in the logs that might be useful for us?

_No response_

### Additional information

_No response_

### LINKED ISSUE #6685: Sprinkler Controller Queue Failure
### The problem

This is probably a very edge case, but through testing for a sprinkler, I found a bug that seems to lock the controller. If the `valve_open_delay` is greater than the time the valve is to be opened, the controller gets stuck in an on position. This was only found against `valve_open_delay` but may affect other `*_delay` as well. "Test Error 1" button will reproduce the error.

The `start_full_cycle()` is unaffected by this issue. "Test Error 2" is for the `start_full_cycle()`. If you run this after "Test Error 1" a reboot may be required as the valves may still be in the queue.

### Which version of ESPHome has the issue?

2024.12.2

### What type of installation are you using?

pip

### Which version of Home Assistant has the issue?

I have 2025.1.2 installed, but should not be applicable

### What platform are you using?

ESP32-IDF

### Board

T-Relay 5V 8 Channel Relay

### Component causing the issue

sprinkler

### YAML Config

```yaml
esphome:
  name: error-sprinkler
  name_add_mac_suffix: True

logger:

api:

ota:
  - platform: esphome
    password: !secret esphome_ota_password

esp32:
  board: esp32dev
  framework:
    type: esp-idf

web_server:
  port: 80

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password

captive_portal:

sprinkler:
  - id: sprinkler_ctrlr
    main_switch: "Sprinklers"
    auto_advance_switch: "Auto Advance Enable"
    valve_open_delay: 5s # <- comment out this line and it works.
    valves:
      - valve_switch_id: lawn_sprinkler_valve_sw1
        valve_switch: "Zone 1"
        enable_switch: "Enable Zone 1"
        run_duration: 600s

      - valve_switch_id: lawn_sprinkler_valve_sw2
        valve_switch: "Zone 2"
        enable_switch: "Enable Zone 2"
        run_duration: 600s

switch:
  - platform: gpio
    id: lawn_sprinkler_valve_sw1
    pin: GPIO33
  - platform: gpio
    id: lawn_sprinkler_valve_sw2
    pin: GPIO32

button:
  - platform: template
    name: Test Error
    on_press:
      - lambda: |-
          id(sprinkler_ctrlr).queue_valve(0, 5);
          id(sprinkler_ctrlr).queue_valve(1, 15);

          id(sprinkler_ctrlr).start_from_queue();

  - platform: template
    name: Test Error 2
    on_press:
      - lambda: |-
          id(sprinkler_ctrlr).set_valve_run_duration(0, 5);
          id(sprinkler_ctrlr).set_valve_run_duration(1, 15);

          id(sprinkler_ctrlr).start_full_cycle();
```

### Anything in the logs that might be useful for us?

```txt
[21:41:53][D][button:010]: 'Test Error' Pressed.
[21:41:53][D][sprinkler:879]: Valve 0 placed into queue with run duration of 5 seconds
[21:41:53][D][sprinkler:879]: Valve 1 placed into queue with run duration of 15 seconds
[21:41:53][D][sprinkler:1425]: QUEUE is starting valve 0 for 5 seconds, cycle 1 of 1
[21:41:53][D][switch:012]: 'lawn_sprinkler_valve_sw1' Turning ON.
[21:41:53][D][switch:055]: 'lawn_sprinkler_valve_sw1': Sending state ON
[21:41:53][D][switch:055]: 'Sprinklers': Sending state ON
[21:41:53][D][switch:055]: 'Zone 1': Sending state ON
[21:41:53][D][sensor:093]: 'Neptune Sprinkler Uptime': Sending state 53.86500 s with 0 decimals of accuracy
[21:41:58][D][switch:016]: 'lawn_sprinkler_valve_sw1' Turning OFF.
[21:41:58][D][switch:055]: 'lawn_sprinkler_valve_sw1': Sending state OFF
[21:41:58][D][switch:055]: 'Zone 1': Sending state OFF


Though Zone 1 turns off, but Zone 2 never turns on and the main switch "Sprinklers" is still on.

However this does not happen when running start_full_cycle(). A reboot will be required before running "Test Error 2" as the valves from "Test Error 1" are still in queue.
[21:47:26][D][button:010]: 'Test Error 2' Pressed.
[21:47:26][D][sprinkler:1425]: CYCLE is starting valve 0 for 10 seconds, cycle 1 of 1
[21:47:26][D][switch:012]: 'lawn_sprinkler_valve_sw1' Turning ON.
[21:47:26][D][switch:055]: 'lawn_sprinkler_valve_sw1': Sending state ON
[21:47:26][D][switch:055]: 'Sprinklers': Sending state ON
[21:47:26][D][switch:055]: 'Zone 1': Sending state ON
[21:47:31][D][sprinkler:1296]: Marking valve 0 complete
[21:47:36][D][switch:016]: 'lawn_sprinkler_valve_sw1' Turning OFF.
[21:47:36][D][switch:055]: 'lawn_sprinkler_valve_sw1': Sending state OFF
[21:47:36][D][switch:055]: 'Zone 1': Sending state OFF
[21:47:41][D][sprinkler:1425]: CYCLE is starting valve 1 for 15 seconds, cycle 1 of 1
[21:47:41][D][switch:012]: 'lawn_sprinkler_valve_sw2' Turning ON.
[21:47:41][D][switch:055]: 'lawn_sprinkler_valve_sw2': Sending state ON
[21:47:41][D][switch:055]: 'Zone 2': Sending state ON
[21:47:50][D][sensor:093]: 'Neptune Sprinkler WiFi Strength': Sending state -62.00000 dBm with 0 decimals of accuracy
[21:47:51][D][sprinkler:1296]: Marking valve 1 complete
[21:47:53][D][sensor:093]: 'Neptune Sprinkler Uptime': Sending state 413.86700 s with 0 decimals of accuracy
[21:47:56][D][switch:016]: 'lawn_sprinkler_valve_sw2' Turning OFF.
[21:47:56][D][switch:055]: 'lawn_sprinkler_valve_sw2': Sending state OFF
[21:47:56][D][switch:055]: 'Zone 2': Sending state OFF
[21:47:57][D][sprinkler:1449]: All valves stopped, including pumps
[21:47:57][D][switch:055]: 'Sprinklers': Sending state OFF
```

### Additional information

_No response_

### LINKED ISSUE #6872: Sprinkler Controller causes panic when running through automatic advance
### The problem

Been trying to build a sprinkler controller using a KinCony E16S, which is an ESP32 relay board.

When I set each output as regular switches, I can turn them on and off freely, all on, all off, without issues.

But if I try to run the sprinkler auto advance program, it fails and panics on the third "valve". I've tried enabling many different orders, changing the pin outputs around, it's consistently on the third one.

### Which version of ESPHome has the issue?

2025.2.2

### What type of installation are you using?

Home Assistant Add-on

### Which version of Home Assistant has the issue?

2025.3.3

### What platform are you using?

ESP32-IDF

### Board

KinCony KC868-E16S-V1.4 with ESP32-WROOM-32E

### Component causing the issue

Sprinkler

### YAML Config

```yaml
substitutions:
  name: "irrigation-controller-3243cc"
  friendly_name: Irrigation Controller

esphome:
  name: ${name}
  friendly_name: ${friendly_name}
  min_version: 2024.6.0
  name_add_mac_suffix: false
  project:
    name: esphome.web
    version: dev
  on_boot:
    then:
      - button.press: buzzer_beep

esp32:
  board: esp32dev
  framework:
    type: esp-idf

# Enable logging
logger:
  level: DEBUG

# Enable Home Assistant API
api:

# Allow Over-The-Air updates
ota:
  - platform: esphome

# Allow provisioning Wi-Fi via serial
improv_serial:

wifi:
  networks:
    - ssid: !secret wifi_ssid
      password: !secret wifi_password
      bssid: <redacted>

i2c:
  sda: 16
  scl: 15
  scan: true
  id: bus_a

# MARK: IO multiplexer config
pcf8574:
  - id: "hub_out_1" # for output channel 1-8
    address: 0x21

  - id: "hub_out_2" # for output channel 9-16
    address: 0x25

  - id: "hub_in_1" # for input channel 1-8
    address: 0x22

  - id: "hub_in_2" # for input channel 9-16
    address: 0x24

output:
  - platform: gpio
    id: "buzzer"
    pin: GPIO2

button:
  - platform: output
    id: "buzzer_beep"
    output: buzzer
    duration: 100ms

# MARK: Individual Outputs
switch:
  - platform: gpio
    id: "e16s_output1"
    pin:
      pcf8574: hub_out_1
      number: 0
      mode: OUTPUT
      inverted: true

  - platform: gpio
    id: "e16s_output2"
    pin:
      pcf8574: hub_out_1
      number: 1
      mode: OUTPUT
      inverted: true

  - platform: gpio
    id: "e16s_output3"
    pin:
      pcf8574: hub_out_1
      number: 2
      mode: OUTPUT
      inverted: true

  - platform: gpio
    id: "e16s_output4"
    pin:
      pcf8574: hub_out_1
      number: 3
      mode: OUTPUT
      inverted: true

  - platform: gpio
    id: "e16s_output5"
    pin:
      pcf8574: hub_out_1
      number: 4
      mode: OUTPUT
      inverted: true

  - platform: gpio
    id: "e16s_output6"
    pin:
      pcf8574: hub_out_1
      number: 5
      mode: OUTPUT
      inverted: true

  - platform: gpio
    id: "e16s_output7"
    pin:
      pcf8574: hub_out_1
      number: 6
      mode: OUTPUT
      inverted: true

  - platform: gpio
    id: "e16s_output8"
    pin:
      pcf8574: hub_out_1
      number: 7
      mode: OUTPUT
      inverted: true

  - platform: gpio
    id: "e16s_output9"
    pin:
      pcf8574: hub_out_2
      number: 0
      mode: OUTPUT
      inverted: true

  - platform: gpio
    id: "e16s_output10"
    pin:
      pcf8574: hub_out_2
      number: 1
      mode: OUTPUT
      inverted: true

  - platform: gpio
    id: "e16s_output11"
    pin:
      pcf8574: hub_out_2
      number: 2
      mode: OUTPUT
      inverted: true

  - platform: gpio
    id: "e16s_output12"
    pin:
      pcf8574: hub_out_2
      number: 3
      mode: OUTPUT
      inverted: true

  - platform: gpio
    id: "e16s_output13"
    pin:
      pcf8574: hub_out_2
      number: 4
      mode: OUTPUT
      inverted: true

  - platform: gpio
    id: "e16s_output14"
    pin:
      pcf8574: hub_out_2
      number: 5
      mode: OUTPUT
      inverted: true

  - platform: gpio
    id: "e16s_output15"
    pin:
      pcf8574: hub_out_2
      number: 6
      mode: OUTPUT
      inverted: true

  - platform: gpio
    id: "e16s_output16"
    pin:
      pcf8574: hub_out_2
      number: 7
      mode: OUTPUT
      inverted: true

  # MARK: Helper Switches
  - platform: template
    id: "master_with_pump"
    optimistic: true
    turn_on_action:
      then:
        - switch.turn_on: e16s_output1
        - delay: 1s
        - switch.turn_on: e16s_output2
    turn_off_action:
      then:
        - switch.turn_off: e16s_output2
        - delay: 1s
        - switch.turn_off: e16s_output1

# MARK: Individual Inputs
binary_sensor:
  - platform: gpio
    name: "e16s_input1"
    pin:
      pcf8574: hub_in_1
      number: 0
      mode: INPUT
      inverted: true

  - platform: gpio
    name: "e16s_input2"
    pin:
      pcf8574: hub_in_1
      number: 1
      mode: INPUT
      inverted: true

  - platform: gpio
    name: "e16s_input3"
    pin:
      pcf8574: hub_in_1
      number: 2
      mode: INPUT
      inverted: true

  - platform: gpio
    name: "e16s_input4"
    pin:
      pcf8574: hub_in_1
      number: 3
      mode: INPUT
      inverted: true

  - platform: gpio
    name: "e16s_input5"
    pin:
      pcf8574: hub_in_1
      number: 4
      mode: INPUT
      inverted: true

  - platform: gpio
    name: "e16s_input6"
    pin:
      pcf8574: hub_in_1
      number: 5
      mode: INPUT
      inverted: true

  - platform: gpio
    name: "e16s_input7"
    pin:
      pcf8574: hub_in_1
      number: 6
      mode: INPUT
      inverted: true

  - platform: gpio
    name: "e16s_input8"
    pin:
      pcf8574: hub_in_1
      number: 7
      mode: INPUT
      inverted: true

  - platform: gpio
    name: "e16s_input9"
    pin:
      pcf8574: hub_in_2
      number: 0
      mode: INPUT
      inverted: true

  - platform: gpio
    name: "e16s_input10"
    pin:
      pcf8574: hub_in_2
      number: 1
      mode: INPUT
      inverted: true

  - platform: gpio
    name: "e16s_input11"
    pin:
      pcf8574: hub_in_2
      number: 2
      mode: INPUT
      inverted: true

  - platform: gpio
    name: "e16s_input12"
    pin:
      pcf8574: hub_in_2
      number: 3
      mode: INPUT
      inverted: true

  - platform: gpio
    name: "e16s_input13"
    pin:
      pcf8574: hub_in_2
      number: 4
      mode: INPUT
      inverted: true

  - platform: gpio
    name: "e16s_input14"
    pin:
      pcf8574: hub_in_2
      number: 5
      mode: INPUT
      inverted: true

  - platform: gpio
    name: "e16s_input15"
    pin:
      pcf8574: hub_in_2
      number: 6
      mode: INPUT
      inverted: true

  - platform: gpio
    name: "e16s_input16"
    pin:
      pcf8574: hub_in_2
      number: 7
      mode: INPUT
      inverted: true

# MARK: Sprinkler Setup
sprinkler:
  - id: main_sprinkler
    main_switch:
      name: Sprinklers
    auto_advance_switch: Sprinklers Auto Advance
    queue_enable_switch: Sprinklers Queue Enable
    reverse_switch: Sprinklers Reverse
    standby_switch: Sprinklers Standby
    multiplier_number:
      id: main_sprinkler_multiplier
      name: "Sprinkler Multiplier"
    repeat_number:
      id: main_sprinkler_repeat
      name: "Sprinkler Repeat"
    valve_overlap: 1s
    pump_start_pump_delay: 2s
    pump_stop_valve_delay: 2s
    valves:
      - valve_switch: Front & Curb
        enable_switch: Front & Curb Enable
        pump_switch_id: master_with_pump
        run_duration: 5s
        valve_switch_id: e16s_output3
      - valve_switch: Front Yard
        enable_switch: Front Yard Enable
        pump_switch_id: master_with_pump
        run_duration: 5s
        valve_switch_id: e16s_output4
      - valve_switch: Patio
        enable_switch: Patio Enable
        pump_switch_id: master_with_pump
        run_duration: 5s
        valve_switch_id: e16s_output6
      - valve_switch: North Side
        enable_switch: North Side Enable
        pump_switch_id: master_with_pump
        run_duration: 5s
        valve_switch_id: e16s_output7
      - valve_switch: Near Backyard
        enable_switch: Near Backyard Enable
        pump_switch_id: master_with_pump
        run_duration: 5s
        valve_switch_id: e16s_output9
      - valve_switch: Middle Backyard
        enable_switch: Middle Backyard Enable
        pump_switch_id: master_with_pump
        run_duration: 5s
        valve_switch_id: e16s_output10
      - valve_switch: South Side
        enable_switch: South Side Enable
        pump_switch_id: master_with_pump
        run_duration: 5s
        valve_switch_id: e16s_output11
      - valve_switch: Mid-far Backyard
        enable_switch: Mid-far Backyard Enable
        pump_switch_id: master_with_pump
        run_duration: 5s
        valve_switch_id: e16s_output12
      - valve_switch: Far & South Backyard
        enable_switch: Far & South Backyard Enable
        pump_switch_id: master_with_pump
        run_duration: 5s
        valve_switch_id: e16s_output13
      - valve_switch: Farthest Backyard
        enable_switch: Farthest BackyardEnable
        pump_switch_id: master_with_pump
        run_duration: 5s
        valve_switch_id: e16s_output14
```

### Anything in the logs that might be useful for us?

```txt
[D][switch:012]: 'Sprinklers' Turning ON.
[D][sprinkler:1427]: CYCLE is starting valve 0 for 5 seconds, cycle 1 of 1
[D][switch:012]: 'e16s_output3' Turning ON.
[D][switch:055]: 'e16s_output3': Sending state ON
[D][switch:055]: 'Sprinklers': Sending state ON
[D][switch:012]: 'master_with_pump' Turning ON.
[D][switch:012]: 'e16s_output1' Turning ON.
[D][switch:055]: 'e16s_output1': Sending state ON
[D][switch:055]: 'master_with_pump': Sending state ON
[D][switch:055]: 'Front & Curb': Sending state ON
[D][switch:012]: 'e16s_output2' Turning ON.
[D][switch:055]: 'e16s_output2': Sending state ON
[D][sprinkler:1298]: Marking valve 0 complete
[D][sprinkler:1427]: CYCLE is starting valve 1 for 5 seconds, cycle 1 of 1
[D][switch:012]: 'e16s_output4' Turning ON.
[D][switch:055]: 'e16s_output4': Sending state ON
[D][switch:055]: 'Front Yard': Sending state ON
[D][switch:016]: 'e16s_output3' Turning OFF.
[D][switch:055]: 'e16s_output3': Sending state OFF
[D][switch:055]: 'Front & Curb': Sending state OFF
[D][esp32.preferences:114]: Saving 2 preferences to flash...
[D][esp32.preferences:142]: Saving 2 preferences to flash: 1 cached, 1 written, 0 failed
[D][sprinkler:1298]: Marking valve 1 complete
[D][switch:016]: 'master_with_pump' Turning OFF.
[D][switch:016]: 'e16s_output2' Turning OFF.
[D][switch:055]: 'e16s_output2': Sending state OFF
[D][switch:055]: 'master_with_pump': Sending state OFF
[D][switch:055]: 'Front Yard': Sending state OFF
[D][sprinkler:1298]: Marking valve 2 complete
[D][sprinkler:1427]: CYCLE is starting valve 3 for 5 seconds, cycle 1 of 1
[D][switch:012]: 'e16s_output7' Turning ON.
[D][switch:055]: 'e16s_output7': Sending state ON
[D][switch:016]: 'e16s_output1' Turning OFF.
[D][switch:055]: 'e16s_output1': Sending state OFF
Guru Meditation Error: Core  0 panic'ed (LoadProhibited). Exception was unhandled.
[13:42:21]
[13:42:21]Core  0 register dump:
[13:42:21]PC      : 0x400dd006  PS      : 0x00060830  A0      : 0x80158050  A1      : 0x3ffbf960  
[13:42:21]A2      : 0x3ffc0d38  A3      : 0x00000000  A4      : 0x3ffc0ec8  A5      : 0x0000af40  
[13:42:21]A6      : 0xb33fffff  A7      : 0xb33fffff  A8      : 0x800dd039  A9      : 0x3ffbf940  
[13:42:21]A10     : 0x3ffc0e98  A11     : 0x00019bbc  A12     : 0x00000000  A13     : 0x00060c23  
[13:42:21]A14     : 0xb33fffff  A15     : 0xb33fffff  SAR     : 0x0000000a  EXCCAUSE: 0x0000001c  
[13:42:21]EXCVADDR: 0x00000028  LBEG    : 0x40082f5d  LEND    : 0x40082f65  LCOUNT  : 0x00000027  
[13:42:21]
[13:42:21]
[13:42:21]Backtrace: 0x400dd003:0x3ffbf960 0x4015804d:0x3ffbf980 0x401580b7:0x3ffbf9a0 0x400e2457:0x3ffbf9c0 0x400e4a5e:0x3ffbf9f0 0x400d7fa2:0x3ffbfa10
[13:42:21]
[13:42:21]
[13:42:21]
[13:42:21]
[13:42:21]ELF file SHA256: d9ba86196112b4ff
[13:42:21]
[13:42:21]Rebooting...
[13:42:21]ets Jul 29 2019 12:21:46
[13:42:21]
[13:42:21]rst:0xc (SW_CPU_RESET),boot:0x13 (SPI_FAST_FLASH_BOOT)
[13:42:21]configsip: 0, SPIWP:0xee
[13:42:21]clk_drv:0x00,q_drv:0x00,d_drv:0x00,cs0_drv:0x00,hd_drv:0x00,wp_drv:0x00
[13:42:21]mode:DIO, clock div:2
[13:42:21]load:0x3fff0030,len:7112
[13:42:21]load:0x40078000,len:15624
[13:42:21]load:0x40080400,len:4
[13:42:21]load:0x40080404,len:3876
[13:42:21]entry 0x4008064c
```

### Additional information

_No response_

### PR DESCRIPTION
**Pull request by kbx81**
# What does this implement/fix?

Fixes multiple crashes and memory issues in the sprinkler component, plus minor performance optimizations.

### 1. Null Pointer Dereference with Mixed Valve/Pump Configuration
**Fixes [#6148](https://github.com/esphome/issues/issues/6148)**

When checking if a pump is in use during valve open delay, the code called `valve_pump_switch()` without checking for nullptr, causing LoadProhibited exceptions when mixing valves with and without pumps.

- Added null check in `pump_in_use()` before dereferencing pump pointers ([sprinkler.cpp:1065-1070](esphome/components/sprinkler/sprinkler.cpp#L1065-L1070))
- Added defensive null checks in valve pump comparison logic ([sprinkler.cpp:1585-1587](esphome/components/sprinkler/sprinkler.cpp#L1585-L1587))

### 2. Race Condition During Rapid Valve Switching
**Fixes [#6872](https://github.com/esphome/issues/issues/6872), [#5740](https://github.com/esphome/issues/issues/5740)**

The code checked `has_request()` but didn't verify that `valve_operator()` was non-null before calling `state()`. During rapid valve transitions (web UI or auto-advance), a request could exist without an assigned operator.

- Added `has_valve_operator()` check in `active_valve()` ([sprinkler.cpp:1012-1014](esphome/components/sprinkler/sprinkler.cpp#L1012-L1014))
- Added `has_valve_operator()` check in `loop()` ([sprinkler.cpp:414-416](esphome/components/sprinkler/sprinkler.cpp#L414-L416))

### 3. Timer Underflow with Short Run Durations
**Fixes [#6685](https://github.com/esphome/issues/issues/6685)**

When `valve_open_delay` >= `run_duration`, the subtraction operation caused unsigned integer underflow, resulting in a timer value of millions of seconds that effectively hung the controller.

Fixed in three FSM transition locations:
- STARTING state handler ([sprinkler.cpp:1510-1514](esphome/components/sprinkler/sprinkler.cpp#L1510-L1514))
- `fsm_transition_from_shutdown_()` ([sprinkler.cpp:1554-1558](esphome/components/sprinkler/sprinkler.cpp#L1554-L1558))
- `fsm_transition_from_valve_run_()` ([sprinkler.cpp:1595-1599](esphome/components/sprinkler/sprinkler.cpp#L1595-L1599))

Now checks if `run_duration > switching_delay` before subtraction to prevent underflow.

### String Return Type Optimization

Changed `req_as_str_()` and `state_as_str_()` to return `const char*` instead of `std::string` ([sprinkler.h:494,497](esphome/components/sprinkler/sprinkler.h#L494), [sprinkler.cpp:1623-1659](esphome/components/sprinkler/sprinkler.cpp#L1623-L1659))

**Benefits:**
- Eliminates string allocation overhead during logging
- Reduces code size by ~100-200 bytes
- Zero runtime allocation for debug strings

## Compatibility

All fixes are backward compatible with no breaking changes:
- No API changes
- No configuration changes required
- Only adds defensive safety checks

## Types of changes

- [x] Bugfix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] Developer breaking change (an API change that could break external components)
- [x] Code quality improvements to existing code or addition of tests
- [ ] Other

**Related issue or feature (if applicable):**

- fixes https://github.com/esphome/issues/issues/6148
- fixes https://github.com/esphome/issues/issues/6872
- fixes https://github.com/esphome/issues/issues/5740
- fixes https://github.com/esphome/issues/issues/6685
- fixes https://github.com/esphome/issues/issues/6306
- fixes https://github.com/esphome/issues/issues/4648

**Pull request in [esphome-docs](https://github.com/esphome/esphome-docs) with documentation (if applicable):**

- esphome/esphome-docs#<esphome-docs PR number goes here>

## Test Environment

- [ ] ESP32
- [x] ESP32 IDF
- [ ] ESP8266
- [ ] RP2040
- [ ] BK72xx
- [ ] RTL87xx
- [ ] nRF52840

## Example entry for `config.yaml`:

```yaml
# Example config.yaml

```

## Checklist:
  - [x] The code change is tested and works locally.
  - [ ] Tests have been added to verify that the new code works (under `tests/` folder).

If user exposed functionality or configuration variables are added/changed:
  - [ ] Documentation added/updated in [esphome-docs](https://github.com/esphome/esphome-docs).

### CODE REVIEW

File: esphome/components/sprinkler/sprinkler.cpp [hunk 1]
```diff
@@ -808,11 +808,11 @@ bool Sprinkler::standby() {
 
 void Sprinkler::start_from_queue() {
   if (this->standby()) {
-    ESP_LOGD(TAG, "start_from_queue called but standby is enabled; no action taken");
+    this->log_standby_warning_("start_from_queue");
```
Comment (bdraco) [inline esphome/components/sprinkler/sprinkler.cpp]: If you make `log_standby_warning_` accept `LogString` instead the RAM usage won't go up

Comment (bdraco) [reply esphome/components/sprinkler/sprinkler.cpp]: https://github.com/bdraco/esphome/commit/47c929fb6a9ae53b1e6c23e4e54d64f96becb50d

Comment (kbx81) [reply esphome/components/sprinkler/sprinkler.cpp]: Nice, thanks! 🙏🏻

Comment (bdraco) [reply esphome/components/sprinkler/sprinkler.cpp]: One more place `state_as_str_` could return LogString as well. That should get rid of the remaining 32 bytes

Comment (bdraco) [reply esphome/components/sprinkler/sprinkler.cpp]: ex https://github.com/esphome/esphome/blob/e89fe9b9456430dd6ef1c517fc9ee43be897fcc2/esphome/components/sensor/sensor.cpp#L39

Comment (kbx81) [reply esphome/components/sprinkler/sprinkler.cpp]: Got it 🙏🏻😄

**Review by bdraco — APPROVED** [review]

**Comment by kbx81** [comment]
Thanks again @bdraco 🍻
