### PR TITLE
[tormatic] Fix UART stream desync on ESP32

### LINKED ISSUE #15335: tormatic Uart - payload issue
### The problem

since ESPhome 2026.3.x issue with tormatic cover

<pre><code>
[13:47:53.121][D][cover:071]: 'Garage Auto' - Setting
[13:47:53.127][D][cover:079]:   Position: 100%
[13:47:53.128][I][tormatic.cover:205]: Fully opening gate
[13:47:53.128][I][tormatic.cover:316]: Sending gate command Opened
[13:47:53.327][E][tormatic.cover:297]: Reading remaining 196867 payload bytes of unknown type 0x0
[13:47:53.628][E][tormatic.cover:297]: Reading remaining 67070 payload bytes of unknown type 0x0
[13:47:53.935][E][tormatic.cover:297]: Reading remaining 67326 payload bytes of unknown type 0x0
[13:47:54.242][E][tormatic.cover:297]: Reading remaining 67582 payload bytes of unknown type 0x0
....
</code></pre>

### Which version of ESPHome has the issue?

2026.3.1

### What type of installation are you using?

Home Assistant Add-on

### What platform are you using?

ESP32

### Component causing the issue

tormatic or cover

### YAML Config

```yaml
esphome:
  name: garageauto
  friendly_name: UG Garage Auto

esp32:
  board: esp32-c6-devkitc-1
  framework:
    type: esp-idf

uart:
  - id: uart_1
    tx_pin: GPIO02
    rx_pin: GPIO03
    baud_rate: 9600

cover:
  - platform: tormatic
    device_class: garage
    name: Garage Auto
    uart_id: uart_1
```

### Anything in the logs that might be useful for us?

```txt

```

### Additional information

_No response_

### PR DESCRIPTION
**Pull request by swoboda1337**
# What does this implement/fix?

Fix UART stream desync in the tormatic cover component that causes cascading parse errors (`Reading remaining 196867 payload bytes of unknown type 0x0`).

Since #14391 enabled wake-on-RX by default for ESP32, the main loop wakes via ISR as soon as the first UART byte arrives. At 9600 baud, the 8-byte message header is read before the payload finishes transmitting. The old `drain_rx_()` was non-blocking (used `available()`/`read_byte()`), so it would exit with 0 bytes drained. The orphan payload bytes then shift all subsequent reads, producing garbage headers that cascade indefinitely.

**Fix:** Add a `pending_hdr_` state so `read_gate_status_()` checks `available()` before reading both the header and the payload. If the payload hasn't arrived yet, the header is saved and processing resumes on the next `loop()` iteration — no messages are dropped and `loop()` never blocks.

Also adds:
- Sanity check on `payload_size()` after reading a header — if it exceeds the largest known message type, the rx buffer is flushed with a 15ms time-based drain (`DRAIN_TIMEOUT_MS`) to guarantee all in-flight bytes at 9600 baud are consumed before resuming. This prevents cascading parse errors from bytes still in transit.
- Early drain-and-return in the STATUS case when `payload_size` doesn't match `sizeof(StatusReply)`, instead of reading a potentially wrong struct.

## Types of changes

- [x] Bugfix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected) — [policy](https://developers.esphome.io/contributing/code/#what-constitutes-a-c-breaking-change)
- [ ] Developer breaking change (an API change that could break external components) — [policy](https://developers.esphome.io/contributing/code/#what-is-considered-public-c-api)
- [ ] Undocumented C++ API change (removal or change of undocumented public methods that lambda users may depend on) — [policy](https://developers.esphome.io/contributing/code/#c-user-expectations)
- [ ] Code quality improvements to existing code or addition of tests
- [ ] Other

**Related issue or feature (if applicable):**

- fixes https://github.com/esphome/esphome/issues/15335

**Pull request in [esphome-docs](https://github.com/esphome/esphome-docs) with documentation (if applicable):**

- N/A

## Test Environment

- [ ] ESP32
- [x] ESP32 IDF
- [ ] ESP8266
- [ ] RP2040/RP2350
- [ ] BK72xx
- [ ] RTL87xx
- [ ] LN882x
- [ ] nRF52840

## Example entry for `config.yaml`:

```yaml
# No config changes needed — existing tormatic configs work as before
uart:
  - id: uart_1
    tx_pin: GPIO02
    rx_pin: GPIO03
    baud_rate: 9600

cover:
  - platform: tormatic
    device_class: garage
    name: Garage Auto
    uart_id: uart_1
```

## Checklist:
  - [x] The code change is tested and works locally.
  - [ ] Tests have been added to verify that the new code works (under `tests/` folder).

If user exposed functionality or configuration variables are added/changed:
  - [ ] Documentation added/updated in [esphome-docs](https://github.com/esphome/esphome-docs).

### CODE REVIEW

**Comment by otih** [comment]
This PR solves the issue. Tested on Tormatic Black 600 with ESP32-c6. Thank you, @swoboda1337

**Comment by ti-mo** [comment]
@swoboda1337 Thanks, but why does this require 10 commits? :) This is going to make understanding the commit log a lot harder than it should be.

Also, in https://github.com/esphome/esphome/issues/15335#issuecomment-4163417309 you mention there's a bug in the UART consumer, but how is/was it supposed to be used, then? Is this PR a band-aid or a proper solution?

**Comment by swoboda1337** [comment]
> @swoboda1337 Thanks, but why does this require 10 commits? :) This is going to make understanding the commit log a lot harder than it should be.
> 
> Also, in [#15335 (comment)](https://github.com/esphome/esphome/issues/15335#issuecomment-4163417309) you mention there's a bug in the UART consumer, but how is/was it supposed to be used, then? Is this PR a band-aid or a proper solution?

Why 10 commits because of AI, it didn't do a great job, I had to fix it. When this gets merged the commits get squashed into one, don't have to worry about the log. 

This is a proper fix, it should be able to resync and waits for the payload bytes.

**Comment by swoboda1337** [comment]
One more tweak to guarantee we recover if we are out of sync.

File: esphome/components/tormatic/tormatic_cover.cpp [hunk 1]
```diff
@@ -344,16 +367,24 @@ template<typename T> optional<T> Tormatic::read_data_() {
...
+      if (!this->read_byte(&data)) {
+        return;
+      }
+    }
+  } else {
+    uint32_t start = millis();
+    while (millis() - start < DRAIN_TIMEOUT_MS) {
+      if (this->available()) {
+        this->read_byte(&data);
+      }
```
Comment (bdraco) [inline esphome/components/tormatic/tormatic_cover.cpp:387]: busy wait isn't great here but probably fine for a patch release. should be refactored long term

**Review by bdraco — APPROVED** [review]

File: esphome/components/tormatic/tormatic_cover.cpp (hunk 1 above)
Comment (swoboda1337) [reply esphome/components/tormatic/tormatic_cover.cpp:387]: It should never happen though.

Comment (swoboda1337) [reply esphome/components/tormatic/tormatic_cover.cpp:387]: This is only if it gets out of sync, its a bit annoying to integrate into the loop

Comment (bdraco) [reply esphome/components/tormatic/tormatic_cover.cpp:387]: its fine for a patch. can be improved later

**Comment by swoboda1337** [comment]
Thanks
