### PR TITLE
[spi] Fix display init failure by marking displays as write-only for half-duplex mode

### LINKED ISSUE #13418: esp32 arduino  with ili9341 no longer logs into the wifi and stays with a white screen, with version 2026.1.0
### The problem

esp32 appears to stop when booting and cannot be accessed via cable. the ili9341 screen remains white. what changes need to be noticed in the yaml?

### Which version of ESPHome has the issue?

2026.1.0

### What type of installation are you using?

Home Assistant Add-on

### What platform are you using?

ESP32

### Component causing the issue

maybe display drivers?

### YAML Config

```yaml
esphome:
  name: touchmod01

esp32:
  board: wemos_d1_mini32
  framework:
    type: arduino

# Enable logging
logger:
  logs:
    component: ERROR
  
# Enable Home Assistant API
api:
  services:
    - service: play_rtttl
      variables:
        song_str: string
      then:
        - rtttl.play:
            rtttl: !lambda 'return song_str;'

ota:
  platform: esphome
  password: !secret ota_password

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password
  min_auth_mode: WPA2
  fast_connect: true

  # Enable fallback hotspot (captive portal) in case wifi connection fails
  ap:
    ssid: !secret wifi_ssid
    password: !secret wifi_password

one_wire:
  - platform: gpio
    pin: GPIO25  

i2c:
  sda: GPIO21
  scl: GPIO22
  
time:
  - platform: homeassistant
    id: homeassistant_time

text_sensor:
  - platform: homeassistant
    id: kilometerstand
    entity_id: sensor.wvwzzzcdzmw350657_odometer
    internal: true

  - platform: homeassistant
    id: reichweite_fuel
    entity_id: sensor.wvwzzzcdzmw350657_combustion_range
    internal: true

  - platform: homeassistant
    id: reichweite_batt
    entity_id: sensor.wvwzzzcdzmw350657_electric_range
    internal: true
    
  - platform: homeassistant
    id: batterie_level
    entity_id: sensor.wvwzzzcdzmw350657_battery_level
    internal: true
    
  - platform: homeassistant
    id: tank_level
    entity_id: sensor.wvwzzzcdzmw350657_fuel_level
    internal: true 

  - platform: homeassistant
    id: ladedauer
    entity_id: sensor.minutes_to_hours
    internal: true 

  - platform: wifi_info
    ip_address:
      name: touchmod_ip_address
      id: touchmod_ip_address

  - platform: homeassistant
    entity_id: sensor.tag_de
    id: tag
    internal: true
    
  - platform: homeassistant
    entity_id: sensor.date_de
    id: wochentag
    internal: true
  
sensor:

  - platform: template
    name: "Helligkeit Display"
    id: "helligkeit_display"
    update_interval: 10s
    accuracy_decimals: 0
    lambda: |-
      return (int(id(back_light_touch).remote_values.get_brightness() * 100));
  
  - platform: bmp085
    temperature:
      name: "BMP180 Temperatur"
      id: bmp180_temperatur
      filters:
      - offset: -1.6
    pressure:
      name: "BMP180 Luftdruck"
      id: bmp180_luftdruck
    update_interval: 60s

  - platform: wifi_signal
    name: "WiFi Signal dB"
    id: wifi_signal_db
    update_interval: 60s
    entity_category: "diagnostic"

  - platform: adc
    pin: GPIO35
    name: "helligkeitswert"
    id: helligkeit
    internal: true
    update_interval: 5s
    attenuation: 12db
    on_value_range:
      - above: 0.1
        then:
        - light.turn_on: 
            id: back_light_touch
            brightness: 100%
      - above: 0.35
        then:
        - light.turn_on: 
            id: back_light_touch
            brightness: 80%
      - above: 1.0
        then:
        - light.turn_on: 
            id: back_light_touch
            brightness: 70%
      - above: 1.5
        then:
        - light.turn_on: 
            id: back_light_touch
            brightness: 50%
      - above: 2.0
        then:
        - light.turn_on: 
            id: back_light_touch
            brightness: 35%
      - below: 2.0
        then:
        - light.turn_on: 
            id: back_light_touch
            brightness: 50%
      - below: 1.5
        then:
        - light.turn_on: 
            id: back_light_touch
            brightness: 70%
      - below: 1.0
        then:
        - light.turn_on: 
            id: back_light_touch
            brightness: 80%
      - below: 0.35
        then:
        - light.turn_on: 
            id: back_light_touch
            brightness: 100%

  - platform: dallas_temp
    address: 0xe63cdbf648199028
    id: temp_touchmod
    name: "Temp Touchmod"
    filters:
      - offset: 0
  
  - platform: homeassistant
    id: aussen_temperatur
    entity_id: sensor.shelly_blu_h_t_6412_temperature
    internal: true
    
  - platform: homeassistant
    id: displayhelligkeit
    entity_id: light.ili9341_touchdisplay_backlight
    internal: true
    
  - platform: homeassistant
    id: carport_temperatur
    entity_id: sensor.carport_temperatur
    internal: true
    
  - platform: homeassistant
    id: batterie_carport
    entity_id: sensor.batterie_carport
    internal: true
    
  - platform: homeassistant
    id: aussen_feuchte
    entity_id: sensor.shelly_blu_h_t_6412_humidity
    internal: true
    
  - platform: homeassistant
    id: keller_temperatur
    entity_id: sensor.temperatur_obi3
    internal: true  
  
  - platform: homeassistant
    id: keller_feuchte
    entity_id: sensor.luftfeuchte_obi3
    internal: true
    
output:
  # buzzer
  - platform: ledc
    pin: GPIO16
    id: rtttl_out
    # component buzzer 
    
    # backlight
  - platform: ledc
    pin:
      number: GPIO15
      ignore_strapping_warning: true
    id: touchbacklight_pwm
    inverted: true

rtttl:
  output: rtttl_out
  on_finished_playback:
    - logger.log: 'Song ended!'
# to play from HA

font:
  - file: 'arial.ttf'
    id: font1
    size: 10

  - file: 'arial.ttf'
    id: font20
    size: 20  

  - file: 'arial.ttf'
    id: font2
    size: 25

  - file: 'arial.ttf'
    id: font23
    size: 23

  - file: 'arial.ttf'
    id: font28
    size: 28

  - file: 'arial.ttf'
    id: font3
    size: 30

  - file: 'arial.ttf'
    id: font32
    size: 32
    
  - file: 'arial.ttf'
    id: font4
    size: 40

  - file: 'arial.ttf'
    id: font5
    size: 50
    
  - file: 'arial.ttf'
    id: font6
    size: 65

  - file: 'arial.ttf'
    id: font9
    size: 90

  - file: 'fonts/materialdesignicons-webfont.ttf' 
    id: water_font
    size: 230
    glyphs: [
      'ﳆ', # mdi-beaker
    ]

image:
    
  - file: "/config/www/icons/Homescreen320x240.png"
    id: logo_gross
    resize: 320x240
    type: RGB
    
  - file: "/config/www/icons/homeassistant_logo_klein_320.png"
    id: logo_streifen
    type: RGB

  - file: "/config/www/icons/pfeil_links.png"
    id: pfeil_links
    resize: 80x26
    type: RGB

  - file: "/config/www/icons/homeassistant_logo.png"
    id: homeassistant_logo
    resize: 40x40
    type: RGB

  - file: "/config/www/icons/pfeil_rechts.png"
    id: pfeil_rechts
    resize: 80x26
    type: RGB

  - file: "/config/www/icons/feuchte.png"
    id: feuchte
    resize: 60x60
    type: RGB  

  - file: "/config/www/icons/aussentemperatur.png"
    id: aussentemperatur
    resize: 60x60
    type: RGB

  - file: "/config/www/icons/garage_blue.png"
    id: carport_temp
    resize: 60x60
    type: RGB
  
  - file: "/config/www/icons/battery.png"
    id: battery
    resize: 60x60
    type: RGB
    
  - file: "/config/www/icons/keller_white.png"
    id: keller_temp
    resize: 40x40
    type: RGB
    
  - file: "/config/www/icons/luftfeuchte.png"
    id: keller_luftfeuchte
    resize: 50x50
    type: RGB
    
  - file: "/config/www/icons/licht_on.png"
    id: licht_an
    resize: 60x35
    type: RGB
    
  - file: "/config/www/icons/licht_aus.png"
    id: licht_aus
    resize: 60x35
    type: RGB
    
  - file: "/config/www/icons/wasserstand_ok.png"
    id: wasserstand_ok
    resize: 45x45
    type: RGB
    
  - file: "/config/www/icons/wasserstand_voll.png"
    id: wasserstand_voll
    resize: 45x45
    type: RGB
    
  - file: "/config/www/icons/waschmaschine.png"
    id: waschmaschine
    resize: 45x45
    type: RGB
    
  - file: "/config/www/icons/steckdose_an.png"
    id: steckdose_an
    resize: 45x45
    type: RGB
    
  - file: "/config/www/icons/steckdose_aus.png"
    id: steckdose_aus
    resize: 45x45
    type: RGB

color:
  - id: my_red
    red: 100%
    green: 0%
    blue: 0%
    
  - id: my_blue
    red: 0%
    green: 0%
    blue: 100%

  - id: my_green
    red: 0%
    green: 100%
    blue: 0%
    
  - id: my_darkgreen
    red: 0%
    green: 40%
    blue: 0%
    
  - id: my_white
    red: 100%
    green: 100%
    blue: 100%
    
  - id: my_black
    red: 0%
    green: 0%
    blue: 0%

  - id: my_grey
    red: 70%
    green: 70%
    blue: 70%

spi:
  clk_pin: GPIO18
  mosi_pin: GPIO23
  miso_pin: GPIO19
  interface: hardware
  
light:
  # backlight for HA
  - platform: monochromatic
    output: touchbacklight_pwm
    name: "ILI9341 Touchdisplay Backlight"
    id: back_light_touch
    restore_mode: RESTORE_AND_ON
    
display:
  - platform: ili9xxx
    model: ili9341
    id: touch_display
    cs_pin: GPIO5
    dc_pin: GPIO4
    color_palette: 8BIT
    invert_colors: false
    reset_pin: GPIO17
    rotation: 90

    pages:
      - id: page1
        
        lambda: |-
          it.fill(my_black);
          it.rectangle( 0, 0, 320, 240, my_green);
          it.line( 0, 182, 200, 182, my_green);

          if (id(aussen_temperatur).has_state()) {
          it.printf(160, 5, id(font9), id(my_grey), TextAlign::TOP_CENTER , "%.1f°C", id(aussen_temperatur).state);
          }

          if (id(aussen_feuchte).has_state()) {
          it.printf(100, 100, id(font6), id(my_grey), TextAlign::TOP_CENTER , "%.0f %%", id(aussen_feuchte).state);
          }
          if (id(wochentag).has_state()) {
          it.print( 100, 192, id(font32), id(my_grey), TextAlign::TOP_CENTER , id(wochentag).state.c_str());
          }
          it.strftime( 260, 130, id(font32), id(my_grey), TextAlign::TOP_CENTER , "%d.%m.", id(homeassistant_time).now());
          it.strftime( 260, 192, id(font32), id(my_grey), TextAlign::TOP_CENTER , "%H:%M", id(homeassistant_time).now());
          it.rectangle( 200, 110, 320, 240, my_green);

          if(id(wasserbehaelter).state) {
          it.print( 50, 210, id(water_font), id(my_red), TextAlign::BASELINE_LEFT , "ﳆ"); 
          }

      - id: page2
      
        lambda: |-
          it.fill(my_black);
          it.image(  0, 7, id(pfeil_links));
          it.image(275, 7, id(pfeil_rechts));
          
          it.print(159, 5, id(font2), id(my_grey), TextAlign::TOP_CENTER , "eigene Messwerte");

          it.print( 5, 40, id(font23), id(my_grey), "BMP-Temperatur");
          if (id(bmp180_temperatur).has_state()) {
          it.printf(315, 40, id(font2), id(my_grey), TextAlign::TOP_RIGHT, "%.1f °C", id(bmp180_temperatur).state);
          }

          it.print( 5, 75, id(font23), id(my_grey), "BMP-Luftdruck");
          if (id(bmp180_luftdruck).has_state()) {
          it.printf(315, 75, id(font2), id(my_grey), TextAlign::TOP_RIGHT, "%.0f hPa", id(bmp180_luftdruck).state);
          }

          it.print( 5, 110, id(font23), id(my_grey), "DS 18b20");
          if (id(temp_touchmod).has_state()) {
          it.printf(315, 110, id(font2), id(my_grey), TextAlign::TOP_RIGHT, "%.1f °C", id(temp_touchmod).state);
          }

          it.print( 5, 145, id(font23), id(my_grey), "ADC Spannung");
          if (id(helligkeit).has_state()) {
          it.printf(315, 145, id(font2), id(my_grey), TextAlign::TOP_RIGHT, "%.2f V", id(helligkeit).state);
          }
          
          it.print( 5, 180, id(font23), id(my_grey), "Helligkeit Display");          
          if (id(helligkeit_display).has_state()) {
          it.printf( 315, 180, id(font23), id(my_grey), TextAlign::TOP_RIGHT, "%.0f %%", id(helligkeit_display).state);
          }
          it.print( 5, 215, id(font23), id(my_grey), "Wifi-Signal");
          if (id(wifi_signal_db).has_state()) {
          it.printf(245, 215, id(font2), id(my_grey), "%.0f db", id(wifi_signal_db).state);
          }
          if(id(wasserbehaelter).state) {
          it.print( 50, 210, id(water_font), id(my_red), TextAlign::BASELINE_LEFT , "ﳆ"); 
          }

      - id: page3
      
        lambda: |-
          it.fill(my_black);
          it.image(  0, 7, id(pfeil_links));
          it.image(275, 7, id(pfeil_rechts));
          if (id(tag).has_state()) {
          it.print( 52, 5, id(font28), id(my_grey), id(tag).state.c_str());
          }
          it.strftime( 102, 5, id(font28), id(my_grey), "%d.%m.", id(homeassistant_time).now());
          it.strftime( 195, 5, id(font28), id(my_grey), "%H:%M", id(homeassistant_time).now());
          it.image(  0,60, id(aussentemperatur));
          it.image(160,60, id(feuchte));
          it.image(  0,120, id(carport_temp));
          it.image(163,120, id(battery));
          it.image(  0,180, id(keller_temp));
          it.image(163,180, id(keller_luftfeuchte));
          
          if (id(aussen_temperatur).has_state()) {
          it.printf(55, 72, id(font2), id(my_grey), "%.1f °C", id(aussen_temperatur).state);
          }
          if (id(carport_temperatur).has_state()) {
          it.printf(55, 129, id(font2), id(my_grey), "%.1f °C", id(carport_temperatur).state);
          }
          if (id(batterie_carport).has_state()) {
          it.printf(230, 129, id(font2), id(my_grey), "%.2f V", id(batterie_carport).state);
          }
          if (id(aussen_feuchte).has_state()) {
          it.printf(230, 72, id(font2), id(my_grey), "%.1f %%", id(aussen_feuchte).state);
          }
          if (id(keller_temperatur).has_state()) {
          it.printf(55, 186, id(font2), id(my_grey), "%.1f °C", id(keller_temperatur).state);
          }
          if (id(keller_feuchte).has_state()) {
          it.printf(230, 186, id(font2), id(my_grey), "%.1f %%", id(keller_feuchte).state);
          }
          if(id(wasserbehaelter).state) {
          it.print( 50, 210, id(water_font), id(my_red), TextAlign::BASELINE_LEFT , "ﳆ"); 
          }
          
      - id: page4
      
        lambda: |-
          it.fill(my_black);
          it.image(  0, 7, id(pfeil_links));
          it.image(275, 7, id(pfeil_rechts));
          if (id(tag).has_state()) {
          it.print( 52, 5, id(font28), id(my_grey), id(tag).state.c_str());
          }
          it.strftime( 102, 5, id(font28), id(my_grey), "%d.%m.", id(homeassistant_time).now());
          it.strftime( 195, 5, id(font28), id(my_grey), "%H:%M", id(homeassistant_time).now());
          it.print(159, 47, id(font2), id(my_grey), TextAlign::TOP_CENTER , "Keller");
          
          it.print( 50, 90, id(font2), id(my_grey), "Vorrat");
          if (id(licht_vorratskeller).state) {
            it.image( 10, 90, id(licht_an));
          } else {
            it.image( 10, 90, id(licht_aus));
          }
          
          it.print( 50, 139, id(font2), id(my_grey), "Wasch");
          if (id(licht_waschkueche).state) {
            it.image( 10, 140, id(licht_an));
          } else {
            it.image( 10, 140, id(licht_aus));
          }
          
          it.print( 210, 90, id(font2), id(my_grey), "Bastel");
          if (id(licht_bastelkeller).state) {
            it.image( 170, 90, id(licht_an));
          } else {
            it.image( 170, 90, id(licht_aus));
          }
          
          it.print( 210, 139, id(font2), id(my_grey), "Heizungs");
          if (id(licht_heizungskeller).state) {
            it.image( 170, 140, id(licht_an));
          } else {
            it.image( 170, 140, id(licht_aus));
          }
          
          it.print( 50, 190, id(font2), id(my_grey), "Wasser");
          if (id(wasserbehaelter).state) {
            it.image( 0, 185, id(wasserstand_voll));
          } else {
            it.image( 0, 185, id(wasserstand_ok));
          }

          it.print( 210, 190, id(font2), id(my_grey), "Maschine");
          it.image( 157, 185, id(waschmaschine));
          
          if(id(wasserbehaelter).state) {
          it.print( 50, 210, id(water_font), id(my_red), TextAlign::BASELINE_LEFT , "ﳆ"); 
          }
          
      - id: page5
      
        lambda: |-
          it.fill(my_black);
          it.image(  0, 7, id(pfeil_links));
          it.image(275, 7, id(pfeil_rechts));
          if (id(tag).has_state()) {
          it.print( 52, 5, id(font28), id(my_grey), id(tag).state.c_str());
          }
          it.strftime( 102, 5, id(font28), id(my_grey), "%d.%m.", id(homeassistant_time).now());
          it.strftime( 195, 5, id(font28), id(my_grey), "%H:%M", id(homeassistant_time).now());
          it.print(159, 47, id(font2), id(my_grey), TextAlign::TOP_CENTER , "Steckdosen");

          
          it.print( 47, 90, id(font23), id(my_grey), "Esp1");
          if (id(esp_steckdose1).state) {
            it.image( 0, 84, id(steckdose_an));
          } else {
            it.image( 0, 84, id(steckdose_aus));
          }
          
          it.print( 47, 139, id(font23), id(my_grey), "Esp4");
          if (id(esp_steckdose4).state) {
            it.image( 0, 134, id(steckdose_an));
          } else {
            it.image( 0, 134, id(steckdose_aus));
          }
          
          it.print( 153, 90, id(font23), id(my_grey), "Esp2");
          if (id(esp_steckdose2).state) {
            it.image( 107, 84, id(steckdose_an));
          } else {
            it.image( 107, 84, id(steckdose_aus));
          }
          
          it.print( 153, 139, id(font23), id(my_grey), "Esp5");
          if (id(esp_steckdose5).state) {
            it.image( 107, 134, id(steckdose_an));
          } else {
            it.image( 107, 134, id(steckdose_aus));
          }
          
          it.print( 47, 190, id(font23), id(my_grey), "Obi1");
          if (id(obi_steckdose).state) {
            it.image( 0, 185, id(steckdose_an));
          } else {
            it.image( 0, 185, id(steckdose_aus));
          }

          it.print( 153, 190, id(font23), id(my_grey), "Obi2");
          if (id(obi_steckdose2).state) {
            it.image( 107, 185, id(steckdose_an));
          } else {
            it.image( 107, 185, id(steckdose_aus));
          }
          
          it.print( 258, 190, id(font23), id(my_grey), "Esp7");
          if (id(esp_steckdose7).state) {
            it.image( 214, 185, id(steckdose_an));
          } else {
            it.image( 214, 185, id(steckdose_aus));
          }

          it.print( 258, 90, id(font23), id(my_grey), "Esp3");
          if (id(esp_steckdose3).state) {
            it.image( 214, 84, id(steckdose_an));
          } else {
            it.image( 214, 84, id(steckdose_aus));
          }

          it.print( 258, 139, id(font23), id(my_grey), "Esp6");
          if (id(esp_steckdose6).state) {
            it.image( 214, 134, id(steckdose_an));
          } else {
            it.image( 214, 134, id(steckdose_aus));
          }
          
          if(id(wasserbehaelter).state) {
          it.print( 50, 210, id(water_font), id(my_red), TextAlign::BASELINE_LEFT , "ﳆ"); 
          }

      - id: page6
      
        lambda: |-
          it.fill(my_black);
          it.image(  0, 7, id(pfeil_links));
          it.image(275, 7, id(pfeil_rechts));
          
          it.print(159, 5, id(font2), id(my_grey), TextAlign::TOP_CENTER , "Auto-Daten");

          it.print( 5, 40, id(font23), id(my_grey), "Kilometerstand");
          it.print( 275, 40, id(font23), id(my_grey), TextAlign::TOP_RIGHT, id(kilometerstand).state.c_str());
          it.print( 315, 40, id(font23), id(my_grey), TextAlign::TOP_RIGHT, "Km");

          it.print( 5, 75, id(font23), id(my_grey), "Reichweite Tank");
          it.print( 275, 75, id(font23), id(my_grey), TextAlign::TOP_RIGHT, id(reichweite_fuel).state.c_str());
          it.print( 315, 75, id(font23), id(my_grey), TextAlign::TOP_RIGHT, "Km");

          it.print( 5, 110, id(font23), id(my_grey), "Tank Level");
          it.print( 275, 110, id(font23), id(my_grey), TextAlign::TOP_RIGHT, id(tank_level).state.c_str());
          it.print( 305, 110, id(font23), id(my_grey), TextAlign::TOP_RIGHT, "%");

          it.print( 5, 145, id(font23), id(my_grey), "Reichweite Batterie");
          it.print( 275, 145, id(font23), id(my_grey), TextAlign::TOP_RIGHT, id(reichweite_batt).state.c_str());
          it.print( 315, 145, id(font23), id(my_grey), TextAlign::TOP_RIGHT, "Km");
          
          it.print( 5, 180, id(font23), id(my_grey), "Batterie Level");
          it.print( 275, 180, id(font23), id(my_grey), TextAlign::TOP_RIGHT, id(batterie_level).state.c_str());
          it.print( 305, 180, id(font23), id(my_grey), TextAlign::TOP_RIGHT, "%");

          it.print( 5, 215, id(font23), id(my_grey), "Ladedauer");
          it.print( 300, 215, id(font23), id(my_grey), TextAlign::TOP_RIGHT, id(ladedauer).state.c_str());

          if(id(wasserbehaelter).state) {
          it.print( 50, 210, id(water_font), id(my_red), TextAlign::BASELINE_LEFT , "ﳆ"); 
          }

      - id: page7

        lambda: |-
          it.image( 0, 0, id(logo_gross));
          if (id(wochentag).has_state()) {
          it.print( 10, 80, id(font3), id(my_grey), id(wochentag).state.c_str());
          }
          it.strftime( 10, 130, id(font3), id(my_grey), "%d.%m.%y", id(homeassistant_time).now());
          it.strftime(10, 5, id(font5), id(my_grey), "%H:%M:%S", id(homeassistant_time).now());
          
          it.printf( 10, 205, id(font2), id(my_grey), "IP:");
          it.print( 42, 205, id(font2), id(my_grey), id(touchmod_ip_address).state.c_str());
          if (id(bmp180_temperatur).has_state()) {
          it.printf(235, 10, id(font2), id(my_grey), "%.1f °C", id(bmp180_temperatur).state);
          }
          if (id(wifi_signal_db).has_state()) {
          it.printf(245, 205, id(font2), id(my_grey), "%.0f db", id(wifi_signal_db).state);
          }
          if(id(wasserbehaelter).state) {
          it.print( 50, 210, id(water_font), id(my_red), TextAlign::BASELINE_LEFT , "ﳆ"); 
          }       

touchscreen:
  platform: xpt2046
  id: xpt2046_touchscreen
  cs_pin: 14
  interrupt_pin: 27
  update_interval: 50ms
  threshold: 800
  calibration:
    x_min: 280
    x_max: 3860
    y_min: 340
    y_max: 3860

binary_sensor:
  - platform: touchscreen
    name: touch_links
    x_min: 0
    x_max: 160
    y_min: 0
    y_max: 240
    on_press:
      - display.page.show_previous: touch_display

  - platform: touchscreen
    name: touch_rechts
    x_min: 161
    x_max: 320
    y_min: 0
    y_max: 240
    on_press:
      - display.page.show_next: touch_display
  
  - platform: homeassistant
    id: wasserbehaelter
    entity_id: binary_sensor.relaise_taster3
    internal: true
    
  - platform: homeassistant
    id: licht_bastelkeller
    entity_id: binary_sensor.licht_bastelkeller
    internal: true
    
  - platform: homeassistant
    id: licht_vorratskeller
    entity_id: binary_sensor.licht_vorratskeller
    internal: true
    
  - platform: homeassistant
    id: licht_heizungskeller
    entity_id: binary_sensor.licht_heizungskeller
    internal: true

  - platform: homeassistant
    id: licht_waschkueche
    entity_id: binary_sensor.licht_waschkueche
    internal: true

  - platform: homeassistant
    id: obi_steckdose
    entity_id: switch.relay
    internal: true

  - platform: homeassistant
    id: obi_steckdose2
    entity_id: switch.relaise2
    internal: true
    
  - platform: homeassistant
    id: esp_steckdose1
    entity_id: switch.esp_steckdose1
    internal: true
    
  - platform: homeassistant
    id: esp_steckdose2
    entity_id: switch.esp_steckdose2
    internal: true
    
  - platform: homeassistant
    id: esp_steckdose3
    entity_id: switch.esp_steckdose3
    internal: true
    
  - platform: homeassistant
    id: esp_steckdose4
    entity_id: switch.esp_steckdose4
    internal: true
    
  - platform: homeassistant
    id: esp_steckdose5
    entity_id: switch.esp_steckdose5
    internal: true

  - platform: homeassistant
    id: esp_steckdose6
    entity_id: switch.feuchter_schalter_2
    internal: true

  - platform: homeassistant
    id: esp_steckdose7
    entity_id: switch.bewaesserung_vorn
    internal: true
```

### Anything in the logs that might be useful for us?

```txt
There are no logs because no connection is possible, not via wifi and not via cable
```

### Additional information

_No response_

### PR DESCRIPTION
**Pull request by bdraco**
# What does this implement/fix?

Fixes SPI display initialization failures when the SPI bus has a MISO pin configured. This became a widespread issue after #12420 unified ESP32 Arduino to use the ESP-IDF SPI driver, but was actually a long-standing issue for ESP-IDF framework users.

## Background

The ESP-IDF SPI driver has a speed limit for full-duplex mode on GPIO matrix pins (ESP32 original only). When a MISO pin is present on the SPI bus, full-duplex mode is used. Most display components (like ili9xxx) default to 40 MHz, which exceeds the ~26.67 MHz limit.

**Timeline:**
- **ESP-IDF framework**: This issue always existed but affected fewer users
- **Arduino framework (pre-#12420)**: Arduino SPI library silently capped speeds to achievable rates, so 40 MHz requests worked
- **Arduino framework (post-#12420)**: Now uses ESP-IDF driver, exposing the same issue to a much larger user base

When the speed limit is exceeded, `spi_bus_add_device()` fails with:
```
E (43) spi_hal: The clock_speed_hz should less than 26666666
```

The device never gets registered, causing all subsequent SPI transactions to fail. Users see a white screen and the device fails to boot.

## Solution

**Mark all SPI display components as write-only**: Displays don't read data over SPI (busy status is read via separate GPIO pins). Setting `write_only=True` enables half-duplex mode (`SPI_DEVICE_HALFDUPLEX`), which has no speed limit.

## Future Work

This PR originally included fallback speed capping in the SPI driver for devices that don't set write-only mode. This was removed as too risky for a patch release since the speed limit calculation is complex (varies by chip variant, pin configuration, and whether GPIO matrix vs IOMUX is used). A future PR should address this to prevent the issue for external components or other SPI devices that may hit this limit.

## Implementation

Added a `write_only` parameter to `register_spi_device()` in the SPI component to centralize the write-only configuration. Display components now pass `write_only=True` when registering:

```python
await spi.register_spi_device(var, config, write_only=True)
```

Updated 20 display components:
- ili9xxx, epaper_spi, waveshare_epaper
- max7219, max7219digit
- mipi_rgb, mipi_spi, qspi_dbi, st7701s
- pcd8544, st7735, st7789v, st7920
- ssd1306_spi, ssd1322_spi, ssd1325_spi, ssd1327_spi, ssd1331_spi, ssd1351_spi
- st7567_spi

## Types of changes

- [x] Bugfix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] Developer breaking change (an API change that could break external components)
- [ ] Code quality improvements to existing code or addition of tests
- [ ] Other

**Related issue or feature (if applicable):**

- fixes https://github.com/esphome/esphome/issues/13418

**Pull request in [esphome-docs](https://github.com/esphome/esphome-docs) with documentation (if applicable):**

- N/A (no user-facing config changes)

## Test Environment

- [x] ESP32
- [x] ESP32 IDF
- [ ] ESP8266
- [ ] RP2040
- [ ] BK72xx
- [ ] RTL87xx
- [ ] LN882x
- [ ] nRF52840

## Example entry for `config.yaml`:

```yaml
# No config changes needed - this fixes existing configs that broke after 2026.1.0
# Example config that was failing:
spi:
  clk_pin: GPIO18
  mosi_pin: GPIO23
  miso_pin: GPIO19  # This caused full-duplex mode, triggering the 26MHz limit
  interface: hardware

display:
  - platform: ili9xxx
    model: ili9341
    cs_pin: GPIO5
    dc_pin: GPIO4
    # data_rate defaults to 40MHz, which now works because display uses half-duplex
```

## Checklist:
  - [x] The code change is tested and works locally.
  - [ ] Tests have been added to verify that the new code works (under `tests/` folder).

If user exposed functionality or configuration variables are added/changed:
  - [x] Documentation added/updated in [esphome-docs](https://github.com/esphome/esphome-docs). (N/A - no user-facing changes)

### CODE REVIEW

File: esphome/components/spi/spi_esp_idf.cpp [hunk 1]
```diff
@@ -184,6 +184,10 @@ class SPIDelegateHw : public SPIDelegate {
   void read_array(uint8_t *ptr, size_t length) override { this->transfer(nullptr, ptr, length); }
 
  protected:
+  // Maximum SPI clock speed for full-duplex mode on GPIO matrix pins
+  // ESP-IDF limit is "less than APB_CLK/3" (26.67MHz), so we use 26MHz to be safe
+  static constexpr uint32_t MAX_FULL_DUPLEX_SPEED = 26000000;
```
Comment (swoboda1337) [inline esphome/components/spi/spi_esp_idf.cpp]:
```
  ┌───────────┬─────────────────┬──────────────────────────┐
  │  Variant  │  APB_CLK_FREQ   │ Max Full-Duplex SPI (÷3) │
  ├───────────┼─────────────────┼──────────────────────────┤
  │ ESP32     │ 80 MHz          │ ~26.67 MHz               │
  ├───────────┼─────────────────┼──────────────────────────┤
  │ ESP32-S2  │ 80 MHz          │ ~26.67 MHz               │
  ├───────────┼─────────────────┼──────────────────────────┤
  │ ESP32-S3  │ 80 MHz          │ ~26.67 MHz               │
  ├───────────┼─────────────────┼──────────────────────────┤
  │ ESP32-C3  │ 80 MHz          │ ~26.67 MHz               │
  ├───────────┼─────────────────┼──────────────────────────┤
  │ ESP32-P4  │ 90 MHz          │ 30 MHz                   │
  ├───────────┼─────────────────┼──────────────────────────┤
  │ ESP32-C5  │ 40 MHz          │ ~13.33 MHz               │
  ├───────────┼─────────────────┼──────────────────────────┤
  │ ESP32-C6  │ 40 MHz          │ ~13.33 MHz               │
  ├───────────┼─────────────────┼──────────────────────────┤
  │ ESP32-C61 │ 40 MHz          │ ~13.33 MHz               │
  ├───────────┼─────────────────┼──────────────────────────┤
  │ ESP32-H2  │ 32 MHz          │ ~10.67 MHz               │
  ├───────────┼─────────────────┼──────────────────────────┤
  │ ESP32-H21 │ 32 MHz          │ ~10.67 MHz               │
  ├───────────┼─────────────────┼──────────────────────────┤
  │ ESP32-H4  │ 40 MHz          │ ~13.33 MHz               │
  ├───────────┼─────────────────┼──────────────────────────┤
  │ ESP32-C2  │ Variable (XTAL) │ Depends on XTAL          │
  └───────────┴─────────────────┴──────────────────────────┘
```

Comment (swoboda1337) [reply esphome/components/spi/spi_esp_idf.cpp]: I think we need find a function or define from IDF here

Comment (bdraco) [reply esphome/components/spi/spi_esp_idf.cpp]: Of course :)

Comment (bdraco) [reply esphome/components/spi/spi_esp_idf.cpp]: 8f157df6fd

File: esphome/components/spi/spi_esp_idf.cpp [hunk 2]
```diff
@@ -184,6 +187,15 @@ class SPIDelegateHw : public SPIDelegate {
   void read_array(uint8_t *ptr, size_t length) override { this->transfer(nullptr, ptr, length); }
 
  protected:
+  // Get maximum SPI clock speed for full-duplex mode on GPIO matrix pins.
+  // ESP-IDF limit is "less than APB_CLK/3". We subtract 1 to ensure we're strictly less than.
+  // This varies by chip: ESP32/S2/S3/C3=26.67MHz, C5/C6=13.33MHz, H2=10.67MHz, etc.
+  static uint32_t get_max_full_duplex_speed_() {
+    uint32_t apb_freq = 0;
+    esp_clk_tree_src_get_freq_hz(SOC_MOD_CLK_APB, ESP_CLK_TREE_SRC_FREQ_PRECISION_EXACT, &apb_freq);
+    return (apb_freq / 3) - 1;
```
Comment (swoboda1337) [inline esphome/components/spi/spi_esp_idf.cpp]: On P4 the limit would be 30mhz probably dont need the - 1, limit would be 29999999

Comment (bdraco) [reply esphome/components/spi/spi_esp_idf.cpp]: 30e06768bd

**Review by swoboda1337 — DISMISSED** [review]
@clydebarrow can you take a look at this one?

**Comment by clydebarrow** [comment]
Basically fine, though I would have done it this way:
```
async def register_spi_device(var, config, write_only=False):
    parent = await cg.get_variable(config[CONF_SPI_ID])
    cg.add(var.set_spi_parent(parent))
    if write_only:
        cg.add(var.set_write_only(True))

```
This keeps the nuts and bolts of spi config in the spi component.

**Review by swoboda1337 — APPROVED** [review]

**Review by clydebarrow — APPROVED** [review]

**Comment by bdraco** [comment]
thanks
