### PR TITLE
fix: non-optional x/y target calculation for ld2450

### LINKED ISSUE #9847: LD2450 still target and still target count broken by recent update
### The problem

I recently updated my presence sensor from 2025.5.0 to 2025.7.3 and noticed the following issues (which I was able to confirm by also updating a second, causing the same behaviour change):

When I enter the room, the moving target count changes from 0 to 1, still target count changes from 0 to -1.
After staying still, _both_ values return to 0.

Effectively, this breaks the still target and presence sensors, as still target count is always reported as <= 0.

I managed to figure out the unterlying Problem by taking a look at the code and commit history:

This commit https://github.com/esphome/esphome/commit/a1291c27303fe7ad287a64b7faf427b9191119cd tried to reduce calculation overhead by using already-calculated x and y positions (variables tx and ty) in this line https://github.com/esphome/esphome/blob/2b5cceda58dd9940ea6172d69351687c0b067e4a/esphome/components/ld2450/ld2450.cpp#L535

These values are, however, only ever calculated here https://github.com/esphome/esphome/blob/2b5cceda58dd9940ea6172d69351687c0b067e4a/esphome/components/ld2450/ld2450.cpp#L481 if the corresponding X and Y sensors for the target are configured.

A fix would be to either always (re)calculate the value at the newly optimized line 535, or always calculate the values tx and ty further above, even if the sensors are not configured (which would at least skip the overhead of calculating twice if both presence and x/y sensors are used)

### Which version of ESPHome has the issue?

2025.7.3

### What type of installation are you using?

Home Assistant Add-on

### What platform are you using?

ESP32

### Component causing the issue

ld2450

### YAML Config

```yaml
esphome:
  name: praesenz-schlafzimmer
  friendly_name: Präsenz Schlafzimmer

esp32:
  board: esp32dev
  framework:
    type: arduino

# Enable logging
logger:

# Enable Home Assistant API
api:
  encryption:
    key: "XXXXXXX"

ota:
  - platform: esphome
    password: "XXXXXX"

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password

  # Enable fallback hotspot (captive portal) in case wifi connection fails
  ap:
    ssid: "Praesenz-Schlafzimmer"
    password: "XXXXXX"

captive_portal:

# sensors
uart:
  - id: ld2450_radar_uart
    tx_pin: GPIO27
    rx_pin: GPIO26
    parity: NONE
    stop_bits: 1
    baud_rate: 256000

ld2450:
  id: ld2450_radar
  uart_id: ld2450_radar_uart
  throttle: 1000ms

switch:
  - platform: ld2450
    ld2450_id: ld2450_radar
    bluetooth:
      name: "Bluetooth"
    multi_target:
      name: "Multi Target Tracking"

button:
  - platform: ld2450
    ld2450_id: ld2450_radar
    factory_reset:
      name: "LD2450 Factory Reset"
    restart:
      name: "LD2450 Restart"

number:
  - platform: ld2450
    ld2450_id: ld2450_radar
    presence_timeout:
      name: "Timeout"

binary_sensor:
  - platform: ld2450
    ld2450_id: ld2450_radar
    has_target:
      name: Presence
    has_moving_target:
      name: Moving Target
    has_still_target:
      name: Still Target

sensor:
  - platform: ld2450
    ld2450_id: ld2450_radar
    target_count:
      name: Presence Target Count
    still_target_count:
      name: Still Target Count
    moving_target_count:
      name: Moving Target Count
```

### Anything in the logs that might be useful for us?

```txt
Entering the room, stying still, leaving the room - current firmware:

[21:46:53][D][sensor:104]: 'Still Target Count': Sending state -1.00000  with 0 decimals of accuracy
[21:46:53][D][sensor:104]: 'Moving Target Count': Sending state 1.00000  with 0 decimals of accuracy
[21:46:53][D][binary_sensor:026]: 'Moving Target': New state is ON
[21:46:54][D][sensor:104]: 'Still Target Count': Sending state 0.00000  with 0 decimals of accuracy
[21:46:54][D][sensor:104]: 'Moving Target Count': Sending state 0.00000  with 0 decimals of accuracy
[21:46:58][D][binary_sensor:026]: 'Moving Target': New state is OFF
[21:47:03][D][sensor:104]: 'Still Target Count': Sending state -1.00000  with 0 decimals of accuracy
[21:47:03][D][sensor:104]: 'Moving Target Count': Sending state 1.00000  with 0 decimals of accuracy
[21:47:03][D][binary_sensor:026]: 'Moving Target': New state is ON
[21:47:04][D][sensor:104]: 'Still Target Count': Sending state -1.00000  with 0 decimals of accuracy
[21:47:05][D][sensor:104]: 'Still Target Count': Sending state -1.00000  with 0 decimals of accuracy
[21:47:06][D][sensor:104]: 'Still Target Count': Sending state -1.00000  with 0 decimals of accuracy
[21:47:07][D][sensor:104]: 'Still Target Count': Sending state 0.00000  with 0 decimals of accuracy
[21:47:07][D][sensor:104]: 'Moving Target Count': Sending state 0.00000  with 0 decimals of accuracy
[21:47:10][D][sensor:104]: 'Still Target Count': Sending state -1.00000  with 0 decimals of accuracy
[21:47:10][D][sensor:104]: 'Moving Target Count': Sending state 1.00000  with 0 decimals of accuracy
[21:47:11][D][sensor:104]: 'Still Target Count': Sending state 0.00000  with 0 decimals of accuracy
[21:47:11][D][sensor:104]: 'Moving Target Count': Sending state 0.00000  with 0 decimals of accuracy
[21:47:13][D][sensor:104]: 'Still Target Count': Sending state -1.00000  with 0 decimals of accuracy
[21:47:13][D][sensor:104]: 'Moving Target Count': Sending state 1.00000  with 0 decimals of accuracy
[21:47:14][D][sensor:104]: 'Still Target Count': Sending state -1.00000  with 0 decimals of accuracy
[21:47:15][D][sensor:104]: 'Still Target Count': Sending state 0.00000  with 0 decimals of accuracy
[21:47:15][D][sensor:104]: 'Moving Target Count': Sending state 0.00000  with 0 decimals of accuracy
[21:47:20][D][binary_sensor:026]: 'Moving Target': New state is OFF





The same actions, previous firmware:

[21:56:09][D][sensor:094]: 'Moving Target Count': Sending state 0.00000  with 0 decimals of accuracy
[21:56:11][D][sensor:094]: 'Presence Target Count': Sending state 0.00000  with 0 decimals of accuracy
[21:56:11][D][sensor:094]: 'Still Target Count': Sending state 0.00000  with 0 decimals of accuracy
[21:56:11][D][sensor:094]: 'Moving Target Count': Sending state 0.00000  with 0 decimals of accuracy
[21:56:12][D][sensor:094]: 'Presence Target Count': Sending state 0.00000  with 0 decimals of accuracy
[21:56:12][D][sensor:094]: 'Still Target Count': Sending state 0.00000  with 0 decimals of accuracy
[21:56:12][D][sensor:094]: 'Moving Target Count': Sending state 0.00000  with 0 decimals of accuracy
[21:56:13][D][sensor:094]: 'Presence Target Count': Sending state 1.00000  with 0 decimals of accuracy
[21:56:13][D][sensor:094]: 'Still Target Count': Sending state 0.00000  with 0 decimals of accuracy
[21:56:13][D][sensor:094]: 'Moving Target Count': Sending state 1.00000  with 0 decimals of accuracy
[21:56:13][D][binary_sensor:036]: 'Presence': Sending state ON
[21:56:13][D][binary_sensor:036]: 'Moving Target': Sending state ON
[21:56:14][D][sensor:094]: 'Presence Target Count': Sending state 1.00000  with 0 decimals of accuracy
[21:56:14][D][sensor:094]: 'Still Target Count': Sending state 0.00000  with 0 decimals of accuracy
[21:56:14][D][sensor:094]: 'Moving Target Count': Sending state 1.00000  with 0 decimals of accuracy
[21:56:15][D][sensor:094]: 'Presence Target Count': Sending state 1.00000  with 0 decimals of accuracy
[21:56:15][D][sensor:094]: 'Still Target Count': Sending state 0.00000  with 0 decimals of accuracy
[21:56:15][D][sensor:094]: 'Moving Target Count': Sending state 1.00000  with 0 decimals of accuracy
[21:56:16][D][sensor:094]: 'Presence Target Count': Sending state 1.00000  with 0 decimals of accuracy
[21:56:16][D][sensor:094]: 'Still Target Count': Sending state 1.00000  with 0 decimals of accuracy
[21:56:16][D][sensor:094]: 'Moving Target Count': Sending state 0.00000  with 0 decimals of accuracy
[21:56:16][D][binary_sensor:036]: 'Still Target': Sending state ON
[21:56:17][D][sensor:094]: 'Presence Target Count': Sending state 1.00000  with 0 decimals of accuracy
[21:56:17][D][sensor:094]: 'Still Target Count': Sending state 1.00000  with 0 decimals of accuracy
[21:56:17][D][sensor:094]: 'Moving Target Count': Sending state 0.00000  with 0 decimals of accuracy
[21:56:18][D][sensor:094]: 'Presence Target Count': Sending state 1.00000  with 0 decimals of accuracy
[21:56:18][D][sensor:094]: 'Still Target Count': Sending state 1.00000  with 0 decimals of accuracy
[21:56:18][D][sensor:094]: 'Moving Target Count': Sending state 0.00000  with 0 decimals of accuracy
[21:56:19][D][sensor:094]: 'Presence Target Count': Sending state 1.00000  with 0 decimals of accuracy
[21:56:19][D][sensor:094]: 'Still Target Count': Sending state 0.00000  with 0 decimals of accuracy
[21:56:19][D][sensor:094]: 'Moving Target Count': Sending state 1.00000  with 0 decimals of accuracy
[21:56:20][D][sensor:094]: 'Presence Target Count': Sending state 1.00000  with 0 decimals of accuracy
[21:56:20][D][sensor:094]: 'Still Target Count': Sending state 0.00000  with 0 decimals of accuracy
[21:56:20][D][sensor:094]: 'Moving Target Count': Sending state 1.00000  with 0 decimals of accuracy
[21:56:21][D][sensor:094]: 'Presence Target Count': Sending state 0.00000  with 0 decimals of accuracy
[21:56:21][D][sensor:094]: 'Still Target Count': Sending state 0.00000  with 0 decimals of accuracy
[21:56:21][D][sensor:094]: 'Moving Target Count': Sending state 0.00000  with 0 decimals of accuracy
[21:56:22][D][sensor:094]: 'Presence Target Count': Sending state 0.00000  with 0 decimals of accuracy
[21:56:22][D][sensor:094]: 'Still Target Count': Sending state 0.00000  with 0 decimals of accuracy
[21:56:22][D][sensor:094]: 'Moving Target Count': Sending state 0.00000  with 0 decimals of accuracy
[21:56:23][D][sensor:094]: 'Presence Target Count': Sending state 0.00000  with 0 decimals of accuracy
[21:56:23][D][sensor:094]: 'Still Target Count': Sending state 0.00000  with 0 decimals of accuracy
[21:56:23][D][sensor:094]: 'Moving Target Count': Sending state 0.00000  with 0 decimals of accuracy
[21:56:23][D][binary_sensor:036]: 'Still Target': Sending state OFF
[21:56:24][D][sensor:094]: 'Presence Target Count': Sending state 0.00000  with 0 decimals of accuracy
[21:56:24][D][sensor:094]: 'Still Target Count': Sending state 0.00000  with 0 decimals of accuracy
[21:56:24][D][sensor:094]: 'Moving Target Count': Sending state 0.00000  with 0 decimals of accuracy
[21:56:25][D][sensor:094]: 'Presence Target Count': Sending state 0.00000  with 0 decimals of accuracy
[21:56:25][D][sensor:094]: 'Still Target Count': Sending state 0.00000  with 0 decimals of accuracy
[21:56:25][D][sensor:094]: 'Moving Target Count': Sending state 0.00000  with 0 decimals of accuracy
[21:56:25][D][binary_sensor:036]: 'Presence': Sending state OFF
[21:56:26][D][binary_sensor:036]: 'Moving Target': Sending state OFF
```

### Additional information

Affected users can add the following workaround to their config to restore correct behaviour:

```yaml
  - platform: ld2450
    ld2450_id: ld2450_radar
    target_count:
      name: Presence Target Count
    still_target_count:
      name: Still Target Count
    moving_target_count:
      name: Moving Target Count
    # still presence bug workaround:
    target_1:
       x:
         name: Target-1 X
       y:
         name: Target-1 Y
    target_2:
       x:
         name: Target-2 X
       y:
         name: Target-2 Y
    target_3:
       x:
         name: Target-3 X
       y:
         name: Target-3 Y
```

### PR DESCRIPTION
**Pull request by Hofferic**
# What does this implement/fix?

As the target X and Y positions are re-used for other sensors, they cannot be treated as optional calculations.
Even if the x/y movement sensors are not configured, the values are now calculated and can be re-used by others to avoid re-calculating the values or using default values (0).

This fixes (at least) the still target, still target count, presence, and target angle sensors when a configuration does not include target x/y sensors for all possible targets.

## Types of changes

- [x ] Bugfix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] Code quality improvements to existing code or addition of tests
- [ ] Other

**Related issue or feature (if applicable):**

- fixes https://github.com/esphome/esphome/issues/9847

**Pull request in [esphome-docs](https://github.com/esphome/esphome-docs) with documentation (if applicable):**

## Test Environment

- [x ] ESP32
- [ ] ESP32 IDF
- [ ] ESP8266
- [ ] RP2040
- [ ] BK72xx
- [ ] RTL87xx
- [ ] nRF52840

## Example entry for `config.yaml`:
see https://github.com/esphome/esphome/issues/9847

## Checklist:
  - [ ] The code change is tested and works locally.
  - [ ] Tests have been added to verify that the new code works (under `tests/` folder).

If user exposed functionality or configuration variables are added/changed:
  - [ ] Documentation added/updated in [esphome-docs](https://github.com/esphome/esphome-docs).

### CODE REVIEW

**Review by bdraco — APPROVED** [review]

**Comment by bdraco** [comment]
Just realized this is untested. Should be ok to merge once testing is done

**Comment by Hofferic** [comment]
Oh sorry. I mentioned that in the issue but perhaps checking the esp32 box was misleading 😅

**Comment by bdraco** [comment]
tested with apollo sensor. All good
Screenshot 2025-07-23 at 11 55 01 AM

File: esphome/components/ld2450/ld2450.cpp [hunk 1]
```diff
@@ -477,21 +477,23 @@ void LD2450Component::handle_periodic_data_() {
     // X
     start = TARGET_X + index * 8;
     is_moving = false;
+    // tx is used for further calculations, so always needs to be populated
+    val = ld2450::decode_coordinate(this->buffer_data_[start], this->buffer_data_[start + 1]);
+    tx = val;
```
Comment (bdraco) [inline esphome/components/ld2450/ld2450.cpp:482]: In a future PR we can drop val and just use tx. But this is fine for a patch / cherry-pick

File: esphome/components/ld2450/ld2450.cpp [hunk 2]
```diff
@@ -477,21 +477,23 @@ void LD2450Component::handle_periodic_data_() {
...
-      tx = val;
       if (this->cached_target_data_[index].x != val) {
         sx->publish_state(val);
         this->cached_target_data_[index].x = val;
       }
     }
     // Y
     start = TARGET_Y + index * 8;
+    // ty is used for further calculations, so always needs to be populated
+    val = ld2450::decode_coordinate(this->buffer_data_[start], this->buffer_data_[start + 1]);
```
Comment (bdraco) [inline esphome/components/ld2450/ld2450.cpp:493]: In a future PR we can drop val and just use ty. But this is fine for a patch / cherry-pick

**Comment by bdraco** [comment]
Thanks @Hofferic

**Comment by Hofferic** [comment]
And thank you for the quick process @bdraco :)
