### PR TITLE
[wifi] Fix WiFi recovery after failed connection attempts

### LINKED ISSUE #12152: WiFi fast_connect fails on Beken chips
### The problem

When using ESPHome on devices with Beken chips, enabling fast_connect: true in the WiFi configuration prevents the device from connecting to the network. The connection attempt fails consistently, while disabling fast_connect allows normal operation.

This issue appears specific to CB2S, CB3S modules. In some cases, the device initially connects successfully, but once the WiFi connection drops(deepsleep or router reboot), it is unable to reconnect.

### Which version of ESPHome has the issue?

2025.11

### What type of installation are you using?

Home Assistant Add-on

### What platform are you using?

BK72XX

### Component causing the issue

wifi

### YAML Config

```yaml
substitutions:
  name: "door-sensor-gas"
  comment: "Door Sensor Gas 48"
  s_ip: 192.168.1.48

esphome:
  name: ${name}
  comment: ${comment}
  on_boot:
    priority: 600
    then:
      - switch.turn_on: batt_dv
      - lambda: |-
          auto now = id(h_time).now();
          if (now.day_of_month != id(last_day)) {
            id(last_day) = now.day_of_month;
            id(gas_pulses_daily) = 0;
          }


bk72xx:
  board: cb3s
  framework:
    version: latest

# Enable logging
logger:
 #baud_rate: 0

debug:
  update_interval: 5s
  
# Enable Home Assistant API
api:
  reboot_timeout: 0s
  on_client_connected: 
    then:
      - component.update: VCC
      - component.update: wifi_signal_db
ota:
  - platform: esphome

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password
  #power_save_mode: HIGH  
  fast_connect: True
  reboot_timeout: 0s
  manual_ip: 
   static_ip: $s_ip
   gateway: 192.168.1.1
   subnet: 255.255.255.0
   dns1: 1.1.1.1
   dns2: 1.0.0.1

  # Enable fallback hotspot in case wifi connection fails
  ap:
    ssid: "${name} Hotspot"

# Make sure logging is not using the serial port

globals:
  - id: gas_pulses_daily
    type: int
    restore_value: yes
    initial_value: '0'
  - id: gas_pulses_total
    type: int
    restore_value: yes
    initial_value: '0'
  - id: last_day
    type: int
    restore_value: yes
    initial_value: '0'

external_components:
  - source: github://Xmister/libretuya-esphome@deep-sleep
    components: [deep_sleep]

time:
  - platform: homeassistant
    id: h_time

binary_sensor:
  - platform: status
    name: "Connection Status"    

  - platform: gpio
    name: "Gas Sensor"
    id: gas_sensor
    device_class: gas
    pin: 
      number: 8
      inverted: true
      mode: INPUT_PULLUP
      allow_other_uses: true
    filters:
      - delayed_on: 100ms
      - delayed_off: 100ms
    on_press:
      then:        
        - lambda: |-
            id(gas_pulses_daily) += 1;
            id(gas_pulses_total) += 1;
        - logger.log: "Gas Detected!"
        - light.turn_on: s_led
        - delay: 0.5s
        - light.turn_off: s_led
        - wait_until: 
            condition: 
              - api.connected:
        - if:
            condition:
              switch.is_on: sleep_switch
            then:
              - logger.log: "Deepsleep is On! Sleep!"
              - script.execute: sleep_start
            else: 
              - logger.log: "Deepsleep is Off!"
    on_release:
      then:
        - logger.log: "Gas Cleared!"

  - platform: gpio
    name: "Reset Button"
    internal: True
    pin: 
      number: 7
      mode: INPUT_PULLUP
      inverted: true
      allow_other_uses: true
    on_click: 
      then:
        - switch.turn_off: sleep_switch
        - light.turn_on: s_led
        - delay: 0.5s
        - light.turn_off: s_led
        - logger.log: "Wakeup!"
    on_double_click:
      then:
        - logger.log: "Sleep!"
        - light.turn_on: s_led
        - delay: 0.5s
        - light.turn_off: s_led
        - switch.turn_on: sleep_switch
        - script.execute: sleep_start
    on_multi_click:
      - timing:
        - ON for at least 5s   
        - OFF for at least 0.5s
        then:          
          - logger.log: "Gas Reset"
          - button.press: gas_reset
    
      - timing:
        - ON for at least 10s   
        - OFF for at least 0.5s
        then:          
          - logger.log: "Restart"
          - button.press: re_start
          

sensor:
  - platform: wifi_signal # Reports the WiFi signal strength/RSSI in dB
    name: "WiFi Signal dB"
    id: wifi_signal_db
    internal: true
    entity_category: "diagnostic"

  - platform: copy # Reports the WiFi signal strength in %
    source_id: wifi_signal_db
    name: "WiFi Signal Percent"
    filters:
      - lambda: return min(max(2 * (x + 100.0), 0.0), 100.0);
    unit_of_measurement: "Signal %"
    entity_category: "diagnostic"
    device_class: ""
    icon: mdi:wifi

  - platform: internal_temperature
    name: 'Internal temperature'  
  - platform: template
    name: "Gas Usage Today"
    id: now_gas
    device_class: gas
    state_class: measurement
    unit_of_measurement: "m³"
    accuracy_decimals: 3
    lambda: |-
      return id(gas_pulses_daily) * 0.01;  

  - platform: template
    name: "Gas Usage Total"
    id: total_gas
    device_class: gas
    state_class: total_increasing
    unit_of_measurement: "m³"
    accuracy_decimals: 3
    lambda: |-
      return id(gas_pulses_total) * 0.01;

  - platform: adc
    name: "Battery Voltage"  
    pin: P23
    id: VCC
    accuracy_decimals: 3
    unit_of_measurement: "V"
    icon: mdi:battery-medium
    update_interval: never
    filters:
      - multiply: 2.4
      - clamp:
          min_value: 0.0
          max_value: 3.2
          #ignore_out_of_range: true
    on_value:
      then:
        - component.update: battery_level

  - platform: template
    name: "Battery Level (%)"
    unit_of_measurement: "%"
    update_interval: never
    id: battery_level
    lambda: |-
      float V = id(VCC).state;
      float percent = ((V - 2.0f) / (3.2f - 2.0f)) * 100.0f;
      return clamp(percent, 0.0f, 100.0f);
    icon: mdi:battery
    on_value:
      - lambda: |-
          if (!isnan(x)) {
          id(batt_dv).turn_off();
          }

switch:
  - platform: gpio    
    id: batt_dv
    pin: 
      number: P14
      mode: OUTPUT
      inverted: true
    name: "Battery check"
    internal: false

  - platform: template
    id: sleep_switch
    name: "Deep Sleep Mode"
    optimistic: True
    restore_mode: RESTORE_DEFAULT_OFF
    turn_on_action:
      then:
    turn_off_action: 
      then:
        - deep_sleep.prevent: d_sleep

text_sensor:
  - platform: version
    name: "Esphome Version"    
  - platform: wifi_info
    ip_address:
     name: Device IP Address
  - platform: debug
    reset_reason: 
      name: Rest Reason

light:
  - platform: status_led
    name: "Status LED"
    internal: True
    id: s_led
    pin: 
      number: P26
      inverted: true

button:    
  - platform: restart
    name: "Restart"
    id: re_start
    entity_category: diagnostic
  - platform: template
    name: "Gas Reset"
    id: gas_reset
    entity_category: config
    on_press: 
      then:
        - globals.set:
            id: gas_pulses_total
            value: '0'
        - globals.set:
            id: gas_pulses_daily
            value: '0'


  - platform: template
    name: "Manual Sleep"
    id: sleep_button
    on_press: 
      then:
        - script.execute: sleep_start

deep_sleep:
  id: d_sleep
  run_duration: 5s
  sleep_duration: 12h
  wakeup_pins:
    - pin:
        number: P7 
        mode: INPUT_PULLUP
        allow_other_uses: true
      wakeup_pin_mode: INVERT_WAKEUP
    - pin:
        number: P8
        mode: INPUT_PULLUP
        allow_other_uses: true
      wakeup_pin_mode: INVERT_WAKEUP 

script:
  - id: sleep_start
    then:
      - deep_sleep.enter: d_sleep
```

### Anything in the logs that might be useful for us?

```txt
The device remains disconnected and does not produce any UART logs during the connection attempt.
```

### Additional information

Thanks to the continuous efforts of the ESPHome team, WiFi connection speed has already improved significantly even without fast_connect. Therefore, not using fast_connect does not cause major usability issues. However, it would be great if this feature could be improved for Beken chips, as it may help users who encounter similar problems and make the experience more consistent across supported platforms.

### PR DESCRIPTION
**Pull request by bdraco**
# What does this implement/fix?

Fixes WiFi connection timeout handling to properly abort in-progress connections and allow the device to recover and eventually connect.

## Problem

When a WiFi connection times out (e.g., wrong password, AP out of range), the WiFi driver may still be busy with the connection attempt. Without explicitly disconnecting, subsequent scan operations fail because the driver is occupied. This causes a cascading failure where the device never recovers to try other networks or start the fallback AP.

This was particularly visible on LibreTiny/Beken platforms with `fast_connect: true`, where connections can take 30-60 seconds when no prior scan has provided channel information.

## Solution

1. **Call `wifi_disconnect_()` on connection timeout** - This frees the WiFi driver so subsequent scans can proceed. On all platforms this calls the native disconnect API:
   - ESP32 IDF: `esp_wifi_disconnect()`
   - ESP8266: `wifi_station_disconnect()` + clears station config
   - LibreTiny: `WiFi.disconnect()`
   - Pico W: `cyw43_wifi_leave()`

2. **Clear `s_sta_connecting` on STA stop (LibreTiny, ESP32 IDF)** - When the WiFi adapter is restarted, the STA_STOP event now clears the connecting flag. Without this, `wifi_sta_connect_status_()` would return CONNECTING even after restart, causing the state machine to wait 61 seconds for a timeout instead of immediately proceeding to scan. ESP8266 doesn't have this event, and Pico W queries hardware directly so neither are affected.

3. **Call `wifi_disconnect_()` when skipping adapter restart** - When captive portal or improv is active, we skip the full adapter restart to avoid disrupting the AP. However, this meant the driver state wasn't cleared, causing a 61-second delay. Now we call `wifi_disconnect_()` to clear the connection state even when skipping the full restart.

4. **Clear `s_sta_connecting` in `wifi_disconnect_()` (LibreTiny only)** - On LibreTiny, `WiFi.disconnect()` triggers events with empty SSID which get filtered out by the spurious event protection. Clearing the flag before calling disconnect ensures the state machine sees IDLE status immediately.

5. **Increase connection timeout from 30s to 46s** - On LibreTiny without `fast_connect`, the first connection attempt can take 40-46 seconds due to internal scanning when no channel/BSSID is provided. Once the driver has located the AP, subsequent connection attempts to the same BSSID are fast (<1s). The timeout is a fallback; actual failures are detected via callbacks. 46s ensures we don't abort connections that are about to succeed.

6. **Extract timeouts as named constants with documentation** - Explains why these values should not be lowered to prevent future regressions.

Changes:
- Add `wifi_disconnect_()` call when connection times out before calling `retry_connect()`
- Add `wifi_disconnect_()` call when skipping adapter restart (captive portal/improv active)
- Clear `s_sta_connecting` flag in STA_STOP event handler (LibreTiny, ESP32 IDF)
- Clear `s_sta_connecting` flag in `wifi_disconnect_()` (LibreTiny only)
- Increase `WIFI_CONNECT_TIMEOUT_MS` from 30000 to 46000
- Extract `WIFI_SCAN_TIMEOUT_MS` (31000) as a named constant
- Add documentation explaining the timeout purpose and cascading failure risk

## Known Limitation

After credentials are submitted via captive portal, the device cannot scan for the best AP because scanning fails when the fallback AP is active. The device will connect to whatever AP the driver finds first, which may have weaker signal than optimal. The device will eventually find a good AP through retry cycles. Users who want faster optimal AP selection can reboot after submitting credentials. This is a pre-existing platform limitation, not introduced by this PR.

## Types of changes

- [x] Bugfix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] Developer breaking change (an API change that could break external components)
- [ ] Code quality improvements to existing code or addition of tests
- [ ] Other

**Related issue or feature (if applicable):**

- fixes https://github.com/esphome/esphome/issues/12152

**Pull request in [esphome-docs](https://github.com/esphome/esphome-docs) with documentation (if applicable):**

- N/A (no user-facing configuration changes)

## Test Environment

- [ ] ESP32
- [x] ESP32 IDF
- [ ] ESP8266
- [ ] RP2040
- [x] BK72xx
- [ ] RTL87xx
- [ ] nRF52840

## Example entry for `config.yaml`:

```yaml
# Tested on CB3S (BK7231N)
wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password
  ap:
    ssid: "device-fallback"

captive_portal:
```

## Checklist:
  - [x] The code change is tested and works locally.
  - [ ] Tests have been added to verify that the new code works (under `tests/` folder).

If user exposed functionality or configuration variables are added/changed:
  - [ ] Documentation added/updated in [esphome-docs](https://github.com/esphome/esphome-docs).

### CODE REVIEW

File: esphome/components/wifi/wifi_component.cpp [hunk 1]
```diff
@@ -1184,7 +1199,7 @@ void WiFiComponent::check_connecting_finished() {
   }
 
   uint32_t now = millis();
-  if (now - this->action_started_ > 30000) {
+  if (now - this->action_started_ > WIFI_CONNECT_TIMEOUT_MS) {
     ESP_LOGW(TAG, "Connection timeout");
```
Comment (bdraco) [inline esphome/components/wifi/wifi_component.cpp]: likely need to force disconnect here in case it gets stuck as it appears it retries forever until stopped when the password is wrong

**Comment by bdraco** [comment]
test matrix

- [x] cb3s fast connect wrong password, recovery
- [x] cb3s fast connect correct password
- [x] cb3s normal connect wrong password, recovery
- [x] cb3s normal connect correct password
- [x] esp8266 wrong password
- [x] esp8266 correct pasword
- [x] esp32 wrong pass
- [x] esp32 correct pass

**Review by swoboda1337 — APPROVED** [review]

**Comment by bdraco** [comment]
thanks

**Comment by plplaaa2** [comment]
Thanks to your efforts, many improvements seem to have been made. It looks like the chronic Wi-Fi issues of the Beken platform have been largely resolved.
