### PR TITLE
[mipi_spi] Fix log_pin() FlashStringHelper compatibility

### LINKED ISSUE #13668: [mipi_spi] Fix dump_summary deprecation warnings
### The problem

**Describe the bug**
The mipi_spi component still uses the deprecated dump_summary() method, causing compilation warnings similar to those fixed in other components (e.g., #13447, #13460-#13463).

**Compilation warnings**
warning: 'virtual std::string esphome::GPIOPin::dump_summary() const' is deprecated: 
Override dump_summary(char*, size_t) instead. Will be removed in 2026.7.0. [-Wdeprecated-declarations]
These warnings appear multiple times during compilation for the CS, Reset, and DC pins in mipi_spi.h around lines 228, 230, and 232.

**Expected behavior**
The component should use the buffer-based dump_summary(char*, size_t) API to eliminate deprecation warnings and avoid heap allocations, consistent with the fixes applied to other components.

**Environment**
ESPHome version: 2026.1.3
ESP32 variant: ESP32-S3
Board: esp32-s3-devkitc-1
Framework: ESP-IDF

**Additional context**
Similar fixes have been applied to other components:

#13447 - fingerprint_grow
#13460 - slow_pwm
#13461 - rpi_dpi_rgb
#13462 - st7701s
#13463 - mipi_rgb

The mipi_spi component appears to have been missed in this cleanup effort.

### Which version of ESPHome has the issue?

2026.1.3

### What type of installation are you using?

Home Assistant Add-on

### What platform are you using?

ESP32

### Component causing the issue

mipi_spi

### YAML Config

```yaml
- platform: mipi_spi
    id: w32_disp
    model: wt32-sc01-plus
    data_rate: 10MHz
    rotation: 90
```

### Anything in the logs that might be useful for us?

```txt
warning: 'virtual std::string esphome::GPIOPin::dump_summary() const' is deprecated: 
Override dump_summary(char*, size_t) instead. Will be removed in 2026.7.0.
```

### Additional information

_No response_

### PR DESCRIPTION
**Pull request by J0k3r2k1**
## What does this implement/fix?

Fixes `dump_config()` compilation failures on ESP8266 caused by `LOG_PIN` macro incompatibility with header-only templated code.

The `LOG_PIN` macro uses `FlashStringHelper` on ESP8266 Arduino, which cannot be used directly in header files with templated classes. This PR moves the logging logic to a non-templated helper function `internal_dump_config()` in the `.cpp` file, where the macro works correctly.

## Types of changes

- [X] Bugfix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] Developer breaking change (an API change that could break external components)
- [ ] Code quality improvements to existing code or addition of tests
- [ ] Other

**Related issue or feature (if applicable):**

n/a

**Pull request in [esphome-docs](https://github.com/esphome/esphome-docs) with documentation (if applicable):**

n/a

## Test Environment

- [ ] ESP32
- [X] ESP32 IDF
- [X] ESP8266
- [ ] RP2040
- [ ] BK72xx
- [ ] RTL87xx
- [ ] LN882x
- [ ] nRF52840

## Example entry for `config.yaml`:

n/a (no config changes)

fixes #13668

## Checklist:
- [X] The code change is tested and works locally.
- [X] Tests have been added to verify that the new code works (under `tests/` folder).

If user exposed functionality or configuration variables are added/changed:
- [ ] Documentation added/updated in [esphome-docs](https://github.com/esphome/esphome-docs).

### CODE REVIEW

File: esphome/components/mipi_spi/mipi_spi.h [hunk 1]
```diff
@@ -224,9 +224,21 @@ class MipiSpi : public display::Display,
...
+    if (this->reset_pin_ != nullptr) {
+      char reset_buf[64];
+      this->reset_pin_->dump_summary(reset_buf, sizeof(reset_buf));
+      esph_log_config(TAG, "  Reset Pin: %s", reset_buf);
+    }
+    if (this->dc_pin_ != nullptr) {
+      char dc_buf[64];
+      this->dc_pin_->dump_summary(dc_buf, sizeof(dc_buf));
+      esph_log_config(TAG, "  DC Pin: %s", dc_buf);
+    }
```
Comment (swoboda1337) [inline esphome/components/mipi_spi/mipi_spi.h]:
```suggestion
    log_pin_with_prefix(TAG, "  CS Pin: ", this->cs_);
    log_pin_with_prefix(TAG, "  Reset Pin: ", this->reset_pin_);
    log_pin_with_prefix(TAG, "  DC Pin: ", this->dc_pin_);
```
Would something like this not be a better idea?

**Review by swoboda1337 — CHANGES_REQUESTED** [review]

File: esphome/components/mipi_spi/mipi_spi.h (hunk 1 above)
Comment (J0k3r2k1) [reply esphome/components/mipi_spi/mipi_spi.h]: The ESP8266 label may have suggested that this was an Arduino‑specific issue, but the real problem is ESPHome’s header restrictions and the **ESP‑IDF** build. Even on ESP32, the code must compile under ESP‑IDF, where log_pin() and F() aren’t available, and header logging is not allowed. So the safer logging approach is required across all platforms.   ... 
And of course, the CI lint bot has zero sense of humor and will reject anything that even smells like forbidden logging in a header. 😉

Comment (swoboda1337) [reply esphome/components/mipi_spi/mipi_spi.h]: What is the error you are trying to fix? Do you have a log?

Comment (swoboda1337) [reply esphome/components/mipi_spi/mipi_spi.h]: Why would log_pin not be available on esp32 idf?

Comment (swoboda1337) [reply esphome/components/mipi_spi/mipi_spi.h]: Ok I see we cant use F in a header on esp8266

Comment (J0k3r2k1) [reply esphome/components/mipi_spi/mipi_spi.h]: `Compiling .pioenvs/smalltv-ultra/src/esphome/components/network/util.cpp.o
In file included from src/esphome/components/mipi_spi/mipi_spi.cpp:1:
src/esphome/components/mipi_spi/mipi_spi.h: In member function 'void esphome::mipi_spi::MipiSpi<BUFFERTYPE, BUFFERPIXEL, IS_BIG_ENDIAN, DISPLAYPIXEL, BUS_TYPE, WIDTH, HEIGHT, OFFSET_WIDTH, OFFSET_HEIGHT>::dump_config()':
src/esphome/components/mipi_spi/mipi_spi.h:227:18: error: cannot convert 'const char*' to 'const __FlashStringHelper*'
  227 |     log_pin(TAG, "  CS Pin: ", this->cs_);
      |                  ^~~~~~~~~~~~
      |                  |
      |                  const char*
In file included from src/esphome/core/hal.h:4,
                 from src/esphome/core/application.h:12,
                 from src/esphome/components/spi/spi.h:2,
                 from src/esphome/components/mipi_spi/mipi_spi.h:5,
                 from src/esphome/components/mipi_spi/mipi_spi.cpp:1:
src/esphome/core/gpio.h:157:58: note:   initializing argument 2 of 'void esphome::log_pin(const char*, const __FlashStringHelper*, esphome::GPIOPin*)'
  157 | void log_pin(const char *tag, const __FlashStringHelper *prefix, GPIOPin *pin);
      |                               ~~~~~~~~~~~~~~~~~~~~~~~~~~~^~~~~~
In file included from src/esphome/components/mipi_spi/mipi_spi.cpp:1:
src/esphome/components/mipi_spi/mipi_spi.h:228:18: error: cannot convert 'const char*' to 'const __FlashStringHelper*'
  228 |     log_pin(TAG, "  Reset Pin: ", this->reset_pin_);
      |                  ^~~~~~~~~~~~~~~
      |                  |
      |                  const char*
In file included from src/esphome/core/hal.h:4,
                 from src/esphome/core/application.h:12,
                 from src/esphome/components/spi/spi.h:2,
                 from src/esphome/components/mipi_spi/mipi_spi.h:5,
                 from src/esphome/components/mipi_spi/mipi_spi.cpp:1:
src/esphome/core/gpio.h:157:58: note:   initializing argument 2 of 'void esphome::log_pin(const char*, const __FlashStringHelper*, esphome::GPIOPin*)'
  157 | void log_pin(const char *tag, const __FlashStringHelper *prefix, GPIOPin *pin);
      |                               ~~~~~~~~~~~~~~~~~~~~~~~~~~~^~~~~~
In file included from src/esphome/components/mipi_spi/mipi_spi.cpp:1:
src/esphome/components/mipi_spi/mipi_spi.h:229:18: error: cannot convert 'const char*' to 'const __FlashStringHelper*'
  229 |     log_pin(TAG, "  DC Pin: ", this->dc_pin_);
      |                  ^~~~~~~~~~~~
      |                  |
      |                  const char*
In file included from src/esphome/core/hal.h:4,
                 from src/esphome/core/application.h:12,
                 from src/esphome/components/spi/spi.h:2,
                 from src/esphome/components/mipi_spi/mipi_spi.h:5,
                 from src/esphome/components/mipi_spi/mipi_spi.cpp:1:
src/esphome/core/gpio.h:157:58: note:   initializing argument 2 of 'void esphome::log_pin(const char*, const __FlashStringHelper*, esphome::GPIOPin*)'
  157 | void log_pin(const char *tag, const __FlashStringHelper *prefix, GPIOPin *pin);
      |                               ~~~~~~~~~~~~~~~~~~~~~~~~~~~^~~~~~
*** [.pioenvs/smalltv-ultra/src/esphome/components/mipi_spi/mipi_spi.cpp.o] Error 1
========================= [FAILED] Took 49.23 seconds =========================
`
my compile error came from calling log_pin() with a normal C‑string. That function expects a __FlashStringHelper*, which only exists in the Arduino environment. Because the component is compiled in ESPHome’s ESP‑IDF build as well, the compiler rejects the call and fails with the “cannot convert ‘const char’ to ‘const __FlashStringHelper’” error.**

I forgot to mention that I’m using the containerized ESPHome dev build (tag 2026.2.0-dev20260129)
hardware used is: 
esp8266:
  board: esp01_1m

Comment (J0k3r2k1) [reply esphome/components/mipi_spi/mipi_spi.h]: > Why would log_pin not be available on esp32 idf?

In ESPHome, log_pin is only available in Arduino builds. It’s declared behind #ifdef USE_ARDUINO and uses __FlashStringHelper, which is part of the Arduino core and not available in the ESP‑IDF build, so log_pin simply doesn’t exist on ESP‑IDF.

Comment (swoboda1337) [reply esphome/components/mipi_spi/mipi_spi.h]: Can you show me where the Arduino ifdef is: https://github.com/esphome/esphome/blob/dev/esphome/core/gpio.h#L156-L160

**Comment by swoboda1337** [comment]
Can you test with that change

File: esphome/components/mipi_spi/mipi_spi.h (hunk 1 above)
Comment (J0k3r2k1) [reply esphome/components/mipi_spi/mipi_spi.h]: The snippet you’re pointing at only switches between ESP8266 and non‑ESP8266 inside the Arduino build. The entire log_pin block is wrapped in #ifdef USE_ARDUINO, so in the ESP‑IDF build the function doesn’t exist at all.

I’m using Arduino on ESP8266 (since thats the only available framework on this old ESPs), but ESPHome still compiles all headers in the ESP‑IDF build as well, which is why the issue appears there.

Comment (swoboda1337) [reply esphome/components/mipi_spi/mipi_spi.h]: Where is the USE_ARDUINO block?

**Comment by J0k3r2k1** [comment]
Your latest change works — the log_pin_with_prefix() version compiles and runs without issues. 😎

**Comment by bdraco** [comment]
Pushed a refactor that moves `dump_config` logic to `internal_dump_config()` in the .cpp file. This allows using the standard `LOG_PIN` macro instead of `log_pin_with_prefix`, so we don't have a bespoke solution that we have to reason about differently.  

The template's `dump_config()` is now a one-liner that passes the values to the helper. Would you please retest? Thanks!

**Review by swoboda1337 — DISMISSED** [review]

**Review by swoboda1337 — DISMISSED** [review]

**Review by clydebarrow — DISMISSED** [review]

**Comment by swoboda1337** [comment]
Should probably add an 8266 test, would have caught the failure

**Comment by J0k3r2k1** [comment]
>  Would you please retest? Thanks!

works fine on the ESP8266 with ST7789V 😎

**Review by bdraco — APPROVED** [review]

**Comment by bdraco** [comment]
Thank you maintainers for looking at this & thanks @J0k3r2k1 for brining it to our attention with a PR.

**Comment by bdraco** [comment]
> Should probably add an 8266 test, would have caught the failure

Added test so we won't miss problems like this again
