### PR TITLE
fix negative temperature for pmsx003

### LINKED ISSUE #3814: Incorrect readout for negative values for PMS5003T
### The problem

When the temperature dips below 0.0 °C the readout inverts and goes to 6553,5 °C. This equals the value 65535 without rounding.

When investigating the [source code](https://github.com/esphome/esphome/blob/d8746266625c5a4c9127577297876e445cffe859/esphome/components/pmsx003/pmsx003.cpp#L198), it can be seen that an unsigned 16-bit integer is used, which is *not* compatible with getting negative values.

So the solution would be reading out the temperature as a signed integer.

### Which version of ESPHome has the issue?

2022.11.1

### What type of installation are you using?

Home Assistant Add-on

### Which version of Home Assistant has the issue?

2022.11.3

### What platform are you using?

ESP32

### Board

az-delivery-devkit-v4

### Component causing the issue

pmsx003

### Example YAML snippet

_No response_

### Anything in the logs that might be useful for us?

_No response_

### Additional information

I have attached an example temperature readout below: 
grafik

This issue has also been previously reported here:  #3013

### PR DESCRIPTION
**Pull request by ssieb**
# What does this implement/fix?

The current component doesn't handle negative temperatures.

## Types of changes

- [X] Bugfix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] Other

**Related issue or feature (if applicable):** fixes https://github.com/esphome/issues/issues/3814

**Pull request in [esphome-docs](https://github.com/esphome/esphome-docs) with documentation (if applicable):** esphome/esphome-docs#<esphome-docs PR number goes here>

## Test Environment

- [ ] ESP32
- [ ] ESP32 IDF
- [ ] ESP8266
- [ ] RP2040
- [ ] BK72xx
- [ ] RTL87xx

## Example entry for `config.yaml`:

```yaml
# Example config.yaml

```

## Checklist:
  - [ ] The code change is tested and works locally.
  - [ ] Tests have been added to verify that the new code works (under `tests/` folder).

If user exposed functionality or configuration variables are added/changed:
  - [ ] Documentation added/updated in [esphome-docs](https://github.com/esphome/esphome-docs).

### CODE REVIEW

File: esphome/components/pmsx003/pmsx003.cpp [hunk 1]
```diff
@@ -195,7 +195,7 @@ void PMSX003Component::send_command_(uint8_t cmd, uint16_t data) {
 void PMSX003Component::parse_data_() {
   switch (this->type_) {
     case PMSX003_TYPE_5003ST: {
-      float temperature = this->get_16_bit_uint_(30) / 10.0f;
+      float temperature = (this->get_16_bit_uint_(30) / 10.0f;
```
Comment (ssieb) [inline esphome/components/pmsx003/pmsx003.cpp]:
```suggestion
      float temperature = (int16_t) this->get_16_bit_uint_(30) / 10.0f;
```

**Review by kbx81 — APPROVED** [review]
