### PR TITLE
[deep_sleep][logger][zephyr][zigbee] add deep sleep support with zigbee wakeup

### LINKED ISSUE #13926: nRF52840 Zigbee End Device idle current stays ~7mA (expected deep-sleep-class current)
Title: nRF52840 Zigbee End Device idle current stays ~7mA (expected deep-sleep-class current)

### The problem
On a Seeed XIAO nRF52840 Sense running ESPHome Zigbee end-device firmware, idle current between measurements is about **7mA**.

This seems much higher than expected for a battery Zigbee end device, where I'd expect sleep current to be in the tens of microamps range between periodic reports.

### Which version of ESPHome has the issue?
ESPHome 2026.1.3

### What type of installation are you using?
CLI

### Which version of Home Assistant has the issue?
N/A

### What platform are you using?
nRF52 (Zephyr)

### Board
Seeed XIAO nRF52840 Sense (`nrf52.board: xiao_ble`)

### Component causing the issue
`zigbee` (end-device behavior / low-power behavior)

### Example YAML snippet
```yaml
substitutions:
  measure_interval: 4h
  logger_baud: "115200"

esphome:
  name: nrf52840-zigbee-tof

nrf52:
  board: xiao_ble

logger:
  baud_rate: ${logger_baud}
  level: INFO

zigbee:
  power_source: BATTERY
  wipe_on_boot: false

preferences:
  flash_write_interval: never

i2c:
  sda: P1.13
  scl: P1.14
  scan: false
  frequency: 100kHz

sensor:
  - platform: vl53l0x
    id: tof
    name: "Distance"
    address: 0x29
    timing_budget: 50ms
    timeout: 100ms
    update_interval: never
    filters:
      - multiply: 1000.0
      - sliding_window_moving_average:
          window_size: 5
          send_every: 5
          send_first_at: 5

  - platform: adc
    id: batt_v_raw
    pin: P0.02
    update_interval: never

  - platform: template
    id: batt_v
    name: "Battery_Voltage"
    update_interval: never
    lambda: |-
      return id(batt_v_raw).state * 2.0;

  - platform: template
    id: batt_pct
    name: "Battery"
    update_interval: never
    lambda: |-
      float v = id(batt_v).state;
      float pct = (v - 2.2f) / (3.0f - 2.2f) * 100.0f;
      if (pct < 0.0f) pct = 0.0f;
      if (pct > 100.0f) pct = 100.0f;
      return pct;

interval:
  - interval: ${measure_interval}
    then:
      - component.update: batt_v_raw
      - component.update: batt_v
      - component.update: batt_pct
      - component.update: tof
      - delay: 250ms
      - component.update: tof
      - delay: 250ms
      - component.update: tof
      - delay: 250ms
      - component.update: tof
      - delay: 250ms
      - component.update: tof
```

### To Reproduce
1. Flash the YAML above to XIAO nRF52840 Sense.
2. Join Zigbee network successfully.
3. Measure supply current in idle period (between 4h measurement intervals).
4. Observe around 7mA continuous draw.

### Expected behavior
A battery Zigbee end device should spend most of time in low-power sleep and draw much less current in idle periods.

### Observed behavior
Device remains around ~7mA idle draw between measurements.

### Logs
The device boots, joins, and reports sensor values as expected; functional behavior is OK, but current draw remains high.

### Additional context
- This is intended for CR2032/CR2450-class battery use.
- Looking for guidance whether low-power Zigbee sleep is currently supported/fully enabled for nRF52 in ESPHome Zigbee and if extra configuration is required.

### PR DESCRIPTION
**Pull request by tomaszduda23**
# What does this implement/fix?

- adds `zephyr_add_kconfig` which allow to set hidden values in zephyr config. It can be used to control CPU idle in the future. Related to https://github.com/esphome/esphome/pull/11672#issuecomment-3536894362
- basic support of deep sleep for nrf52. On nrf52 RTC cannot wake up soc. To support sleep_duration main thread go to sleep. After the sleep CPU continues to execute without reset which is new use case.
- ~~Some components may stop working due to~~
```
  App.run_safe_shutdown_hooks();
  // It's critical to teardown components cleanly for deep sleep to ensure
  // Home Assistant sees a clean disconnect instead of marking the device unavailable
  App.teardown_components(TEARDOWN_TIMEOUT_DEEP_SLEEP_MS);
  App.run_powerdown_hooks();
``` 
- add wakeup to deep_sleep component. zigbee wakes up main thread if anything need to be done.
- if sleep_duration is not set cpu is power off (exception if zigbee is in use). Only way to wakeup for now is just reset
- ~~change power source to battery by default. It seems to work better with z2m.~~
- do not init serial or usb_stack if logger baud_rate is 0
- add zigbee `sleepy` which disable RX during idle
- fix a few compilation warning when logger is missing
- disable optional configuration settings for zigbee for better power usage
- add dummy implementation for mandatory zigbee logging functions
- print `RX on when idle`

## Types of changes

- [ ] Bugfix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] Developer breaking change (an API change that could break external components)
- [ ] Code quality improvements to existing code or addition of tests
- [x] Other

**Related issue or feature (if applicable):**

- fixes https://github.com/esphome/esphome/issues/13926

**Pull request in [esphome-docs](https://github.com/esphome/esphome-docs) with documentation (if applicable):**

- https://github.com/esphome/esphome-docs/pull/6069

## Test Environment

- [ ] ESP32
- [ ] ESP32 IDF
- [ ] ESP8266
- [ ] RP2040
- [ ] BK72xx
- [ ] RTL87xx
- [ ] LN882x
- [x] nRF52840

## Example entry for `config.yaml`:

```yaml
# Example config.yaml

```

## Checklist:
  - [x] The code change is tested and works locally.
  - [x] Tests have been added to verify that the new code works (under `tests/` folder).

If user exposed functionality or configuration variables are added/changed:
  - [x] Documentation added/updated in [esphome-docs](https://github.com/esphome/esphome-docs).

### CODE REVIEW

**Comment by luar123** [comment]
> change power source to battery by default. It seems to work better with z2m.

What is working better in this case?
Are there any side effect on nrf52 when you set the power source to battery in the basic cluster? Asking because with esp32 I saw many reports that you also need to adjust the node descriptor in this case, otherwise there are bugs like devices not reporting or not rejoining after a reboot (might also depend on the coordinator). Maybe we should not assume any default and use undefined instead.

**Comment by tomaszduda23** [comment]
> What is working better in this case?

z2m does not like when device do not respond during interviewing process. It seems work better if it is set to battery.
With `sleepy: true` z2m interviewing works randomly. Sometimes it gets stuck forever.

zha seems to work fine in all cases.

> Are there any side effect on nrf52 when you set the power source to battery in the basic cluster?

I didn't notice anything.

> Asking because with esp32 I saw many reports that you also need to adjust the node descriptor in this case, otherwise there are bugs like devices not reporting or not rejoining after a reboot (might also depend on the coordinator). 

Any reference?

> Maybe we should not assume any default and use undefined instead.

zigbee is too complex for average user to understand. imho default should provide best possible experience.

**Comment by luar123** [comment]
> z2m does not like when device do not respond during interviewing process. It seems work better if it is set to battery. With `sleepy: true` z2m interviewing works randomly. Sometimes it gets stuck forever.

Ok, so it works better only if set to sleepy? That makes sense because most sleepy device are probably battery powered. Could we set the default to battery powered only when sleepy is true?
It could also be that setting sleepy is not enough, because behavior of sleepy devices depends a lot on multiple settings:
- keep alive
- implementation of poll control

Is the node descriptor and node power descriptor set correctly (could be independent from settings in the sdk)?
- power source bit
- rx on when idle bit
- current power mode field
- current power source


> > Asking because with esp32 I saw many reports that you also need to adjust the node descriptor in this case, otherwise there are bugs like devices not reporting or not rejoining after a reboot (might also depend on the coordinator).
> 
> Any reference?

https://github.com/luar123/zigbee_esphome/issues/28
https://github.com/espressif/arduino-esp32/issues/10612

> zigbee is too complex for average user to understand. imho default should provide best possible experience.

Agree, but it should also not show a battery powered device if it is not.

**Comment by tomaszduda23** [comment]
> Ok, so it works better only if set to sleepy?

with `sleepy: true` z2m works randomly. The power source does not matter here.


> Could we set the default to battery powered only when sleepy is true? It could also be that setting sleepy is not enough, because behavior of sleepy devices depends a lot on multiple settings:
> 
> * keep alive
> * implementation of poll control
> 
> Is the node descriptor and node power descriptor set correctly (could be independent from settings in the sdk)?
> 
> * power source bit
> * rx on when idle bit
> * current power mode field
> * current power source
> 

Most of those can be controlled from sdk. But I'm not sure what is the proper configuration from z2m point of view. And I don't feel like to start debugging communication between z2m and nrf52 ^^
If you have any suggestion I could check. It could be also a bug somewhere:
https://github.com/Koenkk/zigbee2mqtt/discussions/30542
https://github.com/LevelHome/sdk-nrf-fork/blob/82f738927cd6d2bbfe172c458f353dc03371c530/doc/nrf/known_issues.rst?plain=1#L771

This is reference implementation https://github.com/nrfconnect/ncs-zigbee-r22/blob/c856addeeb1cb9dcf20e8e142277407372c22d19/samples/light_switch/src/main.c#L834


> Agree, but it should also not show a battery powered device if it is not.

Let me think about it. I added warning first but who reads the warnings. It started giving me the trouble when I added `deep_sleep:` which should not matter tbh. Maybe default could be set to battery when deep sleep is present.

**Comment by tomaszduda23** [comment]
sleepy disable rx on when idle. it seems the same as https://github.com/luar123/zigbee_esphome/blob/1a8a6e428f13605cfcd4080d2640b5d36be18dae/components/zigbee/zigbee.cpp#L417

**Comment by luar123** [comment]
Yes, I think there might be multiple issues involved. Will try to run some tests.

> > Ok, so it works better only if set to sleepy?
> 
> with `sleepy: true` z2m works randomly. The power source does not matter here.

Sorry, I am confused
- with `sleepy: true`: I understand you have interviewing issues. Does power source = battery make any difference?
- with `sleepy: false`: What is the issue here? Does power source = battery make any difference?

**Comment by tomaszduda23** [comment]
> * with `sleepy: true`: I understand you have interviewing issues. Does power source = battery make any difference?

z2m completes interviewing 50% of time. 
power source = battery do not help at all.

> * with `sleepy: false`: What is the issue here? Does power source = battery make any difference?

When I add `deep_sleep:` it sometimes have interviewing issues if power source != battery

**Comment by luar123** [comment]
> > * with `sleepy: true`: I understand you have interviewing issues. Does power source = battery make any difference?
> 
> z2m completes interviewing 50% of time. power source = battery do not help at all.

Will test if this is the same for esp32, could be related to some wrong settings.

> > * with `sleepy: false`: What is the issue here? Does power source = battery make any difference?
> 
> When I add `deep_sleep:` it sometimes have interviewing issues if power source != battery

Can you use deep_sleep + rx_on_when_idle on nrf? For esp this is not possible at all (for light sleep, deepsleep works differently anyway). I would assume that there is some issue with delayed responses here. Could be an issue on esphome side or on z2m side. What is your keep alive setting? Only found https://ncsdoc.z6.web.core.windows.net/zboss/3.9.0.1/group__zb__general__set.html#gafb20d6f762d98096ab34e3c98f772584 but no default value.

Anyway, we could also use different defaults on esp/nrf.

**Comment by tomaszduda23** [comment]
> Can you use deep_sleep + rx_on_when_idle on nrf? 

nrf52840 do not have deep sleep. You can power it off but then everything start from scratch.
It just idle all threads when in "deep_sleep".

> What is your keep alive setting?

I didn't set anything. And there is no API to get current value. Based on logs it seems to be 5 seconds.

> Anyway, we could also use different defaults on esp/nrf.

If esp32 is able to do sleepy device I would like to understand what is missing on nrf52 side to make z2m happy. 


btw is there any tool to dump zigbee traffic in readable form with all flags?

**Comment by tomaszduda23** [comment]
@luar123 do you support Poll Control Cluster Server?

**Comment by luar123** [comment]
> > Can you use deep_sleep + rx_on_when_idle on nrf?
> 
> nrf52840 do not have deep sleep. You can power it off but then everything start from scratch. It just idle all threads when in "deep_sleep".

Then what you are implementing is called light_sleep or auto_lightsleep on esp32, which is unfortunately not supported in esphome (there is #12325). On esp you also can't use  rx_on_when_idle + lightsleep.

> > What is your keep alive setting?
> 
> I didn't set anything. And there is no API to get current value. Based on logs it seems to be 5 seconds.
> do you support Poll Control Cluster Server?

I don't fully understand keep alive and polling, but I think as long as keep alive is below 7.5s the device will receive and respond to commands. I have not looked into poll control.

> > Anyway, we could also use different defaults on esp/nrf.
> 
> If esp32 is able to do sleepy device I would like to understand what is missing on nrf52 side to make z2m happy.

I will look into this but could take some time
 
> btw is there any tool to dump zigbee traffic in readable form with all flags?

You can use a sniffer+wireshark: https://www.zigbee2mqtt.io/advanced/zigbee/04_sniff_zigbee_traffic.html
(never tried)
Or look at debug logs in z2m (for me they are not shown in the frontend), but there not everything in a readable format.

**Comment by swoboda1337** [comment]
Conflicts

File: esphome/components/deep_sleep/deep_sleep_zephyr.cpp [hunk 1]
```diff
@@ -0,0 +1,49 @@
...
+    sys_poweroff();
+#endif
+  }
+  // It might wake up immediately if k_sem_give was called again after wake up
+  int ret = k_sem_take(&this->wakeup_sem_, sleep_duration);
+  if (ret == 0) {
+    ESP_LOGD(TAG, "Woken up by another thread");
+  } else {
+    ESP_LOGD(TAG, "Timeout expired (normal sleep)");
+  }
```
[the remark this answers is not in the document]
Comment (tomaszduda23) [reply esphome/components/deep_sleep/deep_sleep_zephyr.cpp:44]: This is done on purpose. If wake up event happens just before sleep it could be missed. Instead it will go sleep in next sleep loop.

File: esphome/components/deep_sleep/deep_sleep_zephyr.cpp [hunk 2]
```diff
@@ -0,0 +1,49 @@
...
+    // the device can be woken up through one of the following signals:
+    // - The DETECT signal, optionally generated by the GPIO peripheral.
+    // - The ANADETECT signal, optionally generated by the LPCOMP module.
+    // - The SENSE signal, optionally generated by the NFC module to wake-on-field.
+    // - Detecting a valid USB voltage on the VBUS pin (VBUS,DETECT).
+    // - A reset.
+    //
+    // The system is reset when it wakes up from System OFF mode.
+    sys_poweroff();
+#endif
```
[the remark this answers is not in the document]
Comment (tomaszduda23) [reply esphome/components/deep_sleep/deep_sleep_zephyr.cpp:36]: done

File: esphome/components/zephyr/__init__.py [hunk 3]
```diff
@@ -185,8 +188,12 @@ def zephyr_add_cdc_acm(config: ConfigType, id: int) -> None:
     )
 
 
+def zephyr_add_kconfig(kconfig: str) -> None:
+    zephyr_data()[KEY_KCONFIG] += textwrap.dedent(kconfig) + "\n"
+
+
 def zephyr_add_pm_static(section: Section):
-    CORE.data[KEY_ZEPHYR][KEY_PM_STATIC].extend(section)
+    zephyr_data()[KEY_PM_STATIC].extend(section)
```
[the remark this answers is not in the document]
Comment (tomaszduda23) [reply esphome/components/zephyr/__init__.py]: done

File: esphome/components/deep_sleep/deep_sleep_component.cpp [hunk 4]
```diff
@@ -65,6 +76,7 @@ void DeepSleepComponent::begin_sleep(bool manual) {
   App.run_powerdown_hooks();
 
   this->deep_sleep_();
+  this->setup_deep_sleep_();
```
Comment (swoboda1337) [inline esphome/components/deep_sleep/deep_sleep_component.cpp]: Teardown ran right before deep_sleep_(), but on wake only this component is re-setup. Other components (template sensors, climate, etc) wont come back and will silently stop updating after the first wake cycle. Either skip teardown on platforms where deep_sleep_() can return, or re-init everything here. The PR description mentions "Some components may stop working" - thats a pretty big footgun to land without handling

File: esphome/components/zephyr/__init__.py [hunk 5]
```diff
@@ -185,8 +188,12 @@ def zephyr_add_cdc_acm(config: ConfigType, id: int) -> None:
     )
 
 
-def zephyr_add_pm_static(section: Section):
-    CORE.data[KEY_ZEPHYR][KEY_PM_STATIC].extend(section)
+def zephyr_add_kconfig(kconfig: str) -> None:
+    zephyr_data()[KEY_KCONFIG] += textwrap.dedent(kconfig) + "\n"
+
```
Comment (swoboda1337) [inline esphome/components/zephyr/__init__.py:193]: This doesnt seem used?

**Review by swoboda1337 — CHANGES_REQUESTED** [review]

File: esphome/components/zephyr/__init__.py (hunk 5 above)
Comment (tomaszduda23) [reply esphome/components/zephyr/__init__.py:193]: It is needed to set hidden configs. E.g. to change HAS_PM from https://github.com/zephyrproject-rtos/zephyr/blob/3cf7b202780d788976e4bf3e46724e63d23f6bcc/samples/subsys/pm/latency/Kconfig#L13. I ended up not using it but it is valid implementation which was tested.
It took me a while to figure out how to make it work with zephyr. I would like to keep it for future use in the code.

File: esphome/components/deep_sleep/deep_sleep_component.cpp (hunk 4 above)
Comment (tomaszduda23) [reply esphome/components/deep_sleep/deep_sleep_component.cpp]: Let's do not teardown things for now if nrf52 would wake up.
It seems quite big task to make sure that all components are setup in correct way.

Comment (tomaszduda23) [reply esphome/components/deep_sleep/deep_sleep_component.cpp]: this condition is wrong.

File: esphome/components/deep_sleep/deep_sleep_component.cpp [hunk 6]
```diff
@@ -58,13 +69,23 @@ void DeepSleepComponent::begin_sleep(bool manual) {
...
   }
-  App.run_safe_shutdown_hooks();
-  // It's critical to teardown components cleanly for deep sleep to ensure
-  // Home Assistant sees a clean disconnect instead of marking the device unavailable
-  App.teardown_components(TEARDOWN_TIMEOUT_DEEP_SLEEP_MS);
-  App.run_powerdown_hooks();
+
+// nRF52 may return from sleep without reset.
+// Do not teardown things to make sure it still works after.
+#if defined(USE_NRF52) && !defined(USE_ZIGBEE)
```
Comment (swoboda1337) [inline esphome/components/deep_sleep/deep_sleep_component.cpp]:
```suggestion
#if defined(USE_NRF52)
```
Shouldnt it be this?

Comment (tomaszduda23) [reply esphome/components/deep_sleep/deep_sleep_component.cpp]: Yep. I noticed that in mean while. Sorry.

File: esphome/components/deep_sleep/deep_sleep_component.cpp (hunk 4 above)
Comment (tomaszduda23) [reply esphome/components/deep_sleep/deep_sleep_component.cpp]: Now it should be fine.

File: esphome/components/deep_sleep/deep_sleep_component.cpp [hunk 7]
```diff
@@ -58,13 +69,30 @@ void DeepSleepComponent::begin_sleep(bool manual) {
...
+#ifdef USE_NRF52
+  bool poweroff = true;
+  if (this->sleep_duration_.has_value()) {
+    poweroff = false;
+  }
+#ifdef USE_ZIGBEE
+  poweroff = false;
+#endif
+  if (poweroff) {
+#endif
```
Comment (swoboda1337) [inline esphome/components/deep_sleep/deep_sleep_component.cpp]: Maybe add a should_teardown_ helper?

File: esphome/components/deep_sleep/deep_sleep_component.cpp [hunk 8]
```diff
@@ -9,11 +9,22 @@ static const char *const TAG = "deep_sleep";
...
+  k_sem_init(&this->wakeup_sem_, 0, 1);
+#endif
   global_has_deep_sleep = true;
+  this->setup_deep_sleep_();
+  // It can be used from another thread for waking up the device.
+  // It should be called as last item in setup.
+  global_deep_sleep.store(this);
+}
 
+void DeepSleepComponent::setup_deep_sleep_() {
```
Comment (swoboda1337) [inline esphome/components/deep_sleep/deep_sleep_component.cpp]: Maybe rename to schedule_sleep_?

Comment (tomaszduda23) [reply esphome/components/deep_sleep/deep_sleep_component.cpp]: done

File: esphome/components/deep_sleep/deep_sleep_component.cpp (hunk 7 above)
Comment (tomaszduda23) [reply esphome/components/deep_sleep/deep_sleep_component.cpp]: done

**Comment by swoboda1337** [comment]
Conflicts

**Comment by swoboda1337** [comment]
@copilot resolve the merge conflicts in this pull request

**Comment by tomaszduda23** [comment]
I solved it.
Was copilot going to solve it?

**Comment by swoboda1337** [comment]
> I solved it. Was copilot going to solve it?

Doesnt look like it.

File: esphome/components/zigbee/__init__.py [hunk 9]
```diff
@@ -107,6 +108,10 @@ def zigbee_set_core_data(config: ConfigType) -> ConfigType:
                 ),
                 cv.requires_component("nrf52"),
             ),
+            cv.Optional(CONF_SLEEPY, default=False): cv.All(
```
Comment (luar123) [inline esphome/components/zigbee/__init__.py]: you need to use `OnlyWith()` now that esp is merged

Comment (tomaszduda23) [reply esphome/components/zigbee/__init__.py]: thanks

**Comment by swoboda1337** [comment]
Tested and it works fine but I noticed:
```
[22:12:12.569][I][deep_sleep:070]: Sleeping for ldus
```
Do we want to fix 64 bit prints:
```
● Update(esphome/components/logger/__init__.py)
  ⎿  Added 2 lines, removed 2 lines
      472          # esphome implement own fatal error handler which save PC/LR before reset
      473          zephyr_add_prj_conf("RESET_ON_FATAL_ERROR", False)
      474          zephyr_add_prj_conf("THREAD_LOCAL_STORAGE", True)
      475 +        # newlib-nano strips %lld / PRId64 support; use full newlib so 64-bit logs render
      476 +        zephyr_add_prj_conf("NEWLIB_LIBC_NANO", False)
      477          if has_serial_logging:
      478              if config[CONF_HARDWARE_UART] == UART0:
      479                  zephyr_add_overlay("""&uart0 { status = "okay";};""")
      ```

**Comment by swoboda1337** [comment]
There is a real cost though:
```
  ┌───────┬───────────────────┬─────────────────────┬───────────────────────┐
  │       │   Before (nano)   │ After (full newlib) │           Δ           │
  ├───────┼───────────────────┼─────────────────────┼───────────────────────┤
  │ Flash │ 310,076 B (38.0%) │ 331,440 B (40.7%)   │ +21,364 B (+20.9 KiB) │
  ├───────┼───────────────────┼─────────────────────┼───────────────────────┤
  │ RAM   │ 65,241 B (26.2%)  │ 66,937 B (26.9%)    │ +1,696 B (+1.66 KiB)  │
  └───────┴───────────────────┴─────────────────────┴───────────────────────┘
  ```

**Review by swoboda1337 — APPROVED** [review]

**Comment by swoboda1337** [comment]
Thanks

**Comment by tomaszduda23** [comment]
Maybe we could add own implementation for 64-bit prints.

File: esphome/components/deep_sleep/deep_sleep_component.cpp [hunk 10]
```diff
@@ -9,11 +9,22 @@ static const char *const TAG = "deep_sleep";
 // 5 seconds for deep sleep to ensure clean disconnect from Home Assistant
 static const uint32_t TEARDOWN_TIMEOUT_DEEP_SLEEP_MS = 5000;
 
-bool global_has_deep_sleep = false;  // NOLINT(cppcoreguidelines-avoid-non-const-global-variables)
+bool global_has_deep_sleep = false;                   // NOLINT(cppcoreguidelines-avoid-non-const-global-variables)
+std::atomic<DeepSleepComponent *> global_deep_sleep;  // NOLINT(cppcoreguidelines-avoid-non-const-global-variables)
```
Comment (bdraco) [inline esphome/components/deep_sleep/deep_sleep_component.cpp:13]: We support 3 different threading models so `std::atomic` here may break some platforms

`ESPHOME_THREAD_SINGLE`, `ESPHOME_THREAD_MULTI_NO_ATOMICS`, `ESPHOME_THREAD_MULTI_ATOMICS`

Comment (tomaszduda23) [reply esphome/components/deep_sleep/deep_sleep_component.cpp:13]: Addressed in https://github.com/esphome/esphome/pull/16032
