### PR TITLE
Thermostat publish state fix

### LINKED ISSUE #2492: Climate thermostat state is not updated when longer intervals expire
### The problem

Playing with the thermostat component in preparation for making my floor heating smart I found that if I use longer intervals for `min_heating_off_time`, `min_heating_run_time` and `min_idle_time` the status in HA is not updated when the device actually switches to the new state based on the set interval if a change in HA happens within the interval.
The issue occurs if I have an interval for example of 30 seconds for all three options.
Start with a actual temperature of 20° and a set of 18°, the thermostat is off. I switch it to heating and the thermostat changes to 'Idle' as expected. Changing the set-point temperature to 22° after waiting 30 seconds brings it to 'Heating' and the device actually activates the output right away. All good.
But if I change the set-point right after switching heating on before the 30 seconds expire the status stays on 'Idle'. After the time expires the device activates the output but the status in HA does not update, it is still 'Idle' and stays 'Idle' forever.
If I then change the temperature to 18° I get 'Idle', raising the temperature before 30 seconds are over to 23° it still reads 'Idle', the devices activates the output after the 30 seconds expired so.

From what I can tell and see in the DEBUG log from the climate component is that the device only sends an update of its state right after it received a change from HA but not when a timer expires and the action is really done in case of longer intervals that allow the user to send changes while a timeout is still active.

### Which version of ESPHome has the issue?

2021.9.2

### What type of installation are you using?

Home Assistant Add-on

### Which version of Home Assistant has the issue?

2021.9.7

### What platform are you using?

ESP8266

### Board

D1 mini

### Component causing the issue

thermostat

### Example YAML snippet

```yaml
climate:
  - platform: thermostat
    name: test1
    sensor: temperature_test1
    default_target_temperature_low: 18 °C
    min_heating_off_time: 30s
    min_heating_run_time: 30s
    min_idle_time: 30s
    heat_action:
      - output.turn_on: hc1
    idle_action:
      - output.turn_off: hc1
```

### Anything in the logs that might be useful for us?

_No response_

### Additional information

_No response_

### PR DESCRIPTION
**Pull request by kbx81**
# What does this implement/fix?

Quick fix to ensure state is published after a delayed change of climate action.

## Types of changes

- [x] Bugfix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] Other

**Related issue or feature (if applicable):** fixes https://github.com/esphome/issues/issues/2492

**Pull request in [esphome-docs](https://github.com/esphome/esphome-docs) with documentation (if applicable):** Not required

## Test Environment

- [x] ESP32
- [ ] ESP8266

## Checklist:
  - [x] The code change is tested and works locally.
  - [ ] Tests have been added to verify that the new code works (under `tests/` folder).
  
If user exposed functionality or configuration variables are added/changed:
  - [ ] Documentation added/updated in [esphome-docs](https://github.com/esphome/esphome-docs).

### CODE REVIEW

File: esphome/components/thermostat/thermostat_climate.cpp [hunk 1]
```diff
@@ -615,9 +621,11 @@ void ThermostatClimate::switch_to_mode_(climate::ClimateMode mode) {
   this->mode = mode;
   this->prev_mode_ = mode;
   this->prev_mode_trigger_ = trig;
+  if (publish_state)
+    this->publish_state();
 }
 
-void ThermostatClimate::switch_to_swing_mode_(climate::ClimateSwingMode swing_mode) {
+void ThermostatClimate::switch_to_swing_mode_(climate::ClimateSwingMode swing_mode, const bool publish_state) {
```
Comment (OttoWinter) [inline esphome/components/thermostat/thermostat_climate.cpp]:
```suggestion
void ThermostatClimate::switch_to_swing_mode_(climate::ClimateSwingMode swing_mode, bool publish_state) {
```

it's declared as `bool` in the header, so it should match here

**Comment by kbx81** [comment]
Yup, I forgot how to `git`. Nothing to see here, please move along. Sorry for all the tags. 😆

File: esphome/components/thermostat/thermostat_climate.cpp (hunk 1 above)
Comment (kbx81) [reply esphome/components/thermostat/thermostat_climate.cpp]: clang-tidy doesn't like when we put `const` in the header, though. See the failed test.

Comment (kbx81) [reply esphome/components/thermostat/thermostat_climate.cpp]: I could make it not-const, but...it should be `const`...it shouldn't be changed in the method...but I'm not an expert in modern semantics. Is `const` bad these days?

Comment (kbx81) [reply esphome/components/thermostat/thermostat_climate.cpp]: I just removed it...this is a pretty trivial use case, no strong feelings either way. clang-tidy doesn't like `const` in the header, which I get. I know in the function itself it's a copy of the data so `const` is pretty irrelevant in that regard, but it's personal preference to use `const` in cases like this to prevent silly mistakes like `=` vs. `==`. It can also help express intent. I'm cool either way and if you don't like it, I'm most definitely not here to argue. 😄

Comment (OttoWinter) [reply esphome/components/thermostat/thermostat_climate.cpp]: My concern was that this might be undefined/implementation-defined behavior :) but perhaps cpp has rules that const/non-const params resolve to the same symbol (don't know enough about that)
