### PR TITLE
[http_request] Bugfix: run update function in a task

### LINKED ISSUE #241: Voice PE bootloops after power reconnect and wifi is connected (watchdog) (v 24.12.8)
I received two voice pe today. After the first setup the bootloop problems started. When I reflash the boards everything works until I remove the power, then they just bootloop.
Does anyone have the same problem, or has an idea?
```
[18:01:54][I][wifi:617]: WiFi Connected!
[18:01:54][C][wifi:428]:   Local MAC: 20:F8:3B:09:30:F4
[18:01:54][C][wifi:433]:   SSID: 'MyWifi'[redacted]
[18:01:54][C][wifi:436]:   IP Address: 192.168.2.78
[18:01:54][C][wifi:439]:   BSSID: 5C:E9:31:B1:71:F2[redacted]
[18:01:54][C][wifi:441]:   Hostname: 'home-assistant-voice-0930f4'
[18:01:54][C][wifi:443]:   Signal strength: -44 dB ▂▄▆█
[18:01:54][C][wifi:447]:   Channel: 6
[18:01:54][C][wifi:448]:   Subnet: 255.255.255.0
[18:01:54][C][wifi:449]:   Gateway: 192.168.2.1
[18:01:54][C][wifi:450]:   DNS1: 192.168.2.160
[18:01:54][C][wifi:451]:   DNS2: 1.1.1.1
[18:01:54][C][api:026]: Setting up Home Assistant API server...
[18:01:54][C][micro_wake_word:083]: Setting up microWakeWord...
[18:01:54][C][micro_wake_word:109]: Micro Wake Word initialized
[18:01:54][I][app:062]: setup() finished successfully!
[18:01:58][D][esp-idf:000][wifi]: I (20245) wifi:
[18:01:58][D][esp-idf:000][wifi]: <ba-add>idx:1 (ifx:0, 5c:e9:31:b1:71:f2), tid:0, ssn:0, winSize:64
[18:01:58][D][esp-idf:000][wifi]: 
[18:01:58]
[18:01:59]E (21342) task_wdt: Task watchdog got triggered. The following tasks/users did not reset the watchdog in time:
[18:01:59]E (21342) task_wdt:  - loopTask (CPU 0)
[18:01:59]E (21342) task_wdt: Tasks currently running:
[18:01:59]E (21342) task_wdt: CPU 0: IDLE0
[18:01:59]E (21342) task_wdt: CPU 1: IDLE1
[18:01:59]E (21342) task_wdt: Aborting.
[18:01:59]E (21342) task_wdt: Print CPU 0 (current core) backtrace
[18:01:59]
[18:01:59]
[18:01:59]
[18:01:59]
[18:01:59]Backtrace: 0x40383577:0x3fcaffc0 0x420b2d31:0x3fcaffe0 0x4038717b:0x3fcb0000
[18:01:59]
[18:01:59]
[18:01:59]
[18:01:59]
[18:01:59]ELF file SHA256: c77aced757c7321d
[18:01:59]
[18:01:59]Rebooting...
```

### PR DESCRIPTION
**Pull request by kahrendt**
# What does this implement/fix?

If the update function can't open the manifest url due to a bad/blocked internet connection, the device crashes with a watchdog timeout. This PR moves the update function into its own task to avoid the crash. This allows it to yield to the main task, giving the ``esp_http_client`` enough time to return with an error.

## Types of changes

- [x] Bugfix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [x] Code quality improvements to existing code or addition of tests
- [ ] Other

**Related issue or feature (if applicable):**

- fixes esphome/home-assistant-voice-pe/issues/241

**Pull request in [esphome-docs](https://github.com/esphome/esphome-docs) with documentation (if applicable):** not applicable

## Test Environment

- [ ] ESP32
- [x] ESP32 IDF
- [ ] ESP8266
- [ ] RP2040
- [ ] BK72xx
- [ ] RTL87xx

## Example entry for `config.yaml`:

```yaml
# Example config.yaml

ota:
  - platform: http_request
    id: ota_http_request

http_request:

update:
  - platform: http_request
    name: None
    id: update_http_request
    source: https://firmware.esphome.io/home-assistant-voice-pe/home-assistant-voice/manifest.json

```

## Checklist:
  - [x] The code change is tested and works locally.
  - [ ] Tests have been added to verify that the new code works (under `tests/` folder).

If user exposed functionality or configuration variables are added/changed:
  - [ ] Documentation added/updated in [esphome-docs](https://github.com/esphome/esphome-docs).

### CODE REVIEW

**Comment by tjhorner** [comment]
Thought I would flag this potential issue here when using the Arduino framework: https://github.com/espressif/arduino-esp32/issues/8804

I modified an external component of mine to run HTTP requests in a separate task, using this PR as a model. I ran into the issue in the issue linked above. After 16 requests, the requests start failing and the node actually entirely stops responding on the network. The same thing would likely happen with the task here, but be noticed much later due to how infrequently it runs.

**Edit**: Also of note is that this will probably leak memory if not handled very very carefully. FreeRTOS does not free memory used by tasks once they are deleted (as I discovered while trying to implement this myself lol). There is a long thread on the ESPHome Discord where we discussed this problem, if it sounds helpful: https://discord.com/channels/429907082951524364/429907082955718657/1326659408142532749

**Review by kbx81 — DISMISSED** [review]
I've confirmed that this change results in a memory leak, which seems to eat roughly 800 bytes with each HTTP request. I played around a bit to see if I could work out a fix, but no luck -- the discussion on Discord mentioned above might shed some light.

**Comment by kahrendt** [comment]
Thanks for raising the issue @kbx81 and @tjhorner.

Variables declared on the stack get freed just fine when ending a FreeRTOS task. C++ objects on the heap do not. The memory leak here was due to the ``std::string`` never deallocating. I just moved the code using the strings into their ``{}`` brackets, so they will automatically be deallocated when falling out of scope. This fixed the memory leak on my end!

File: esphome/components/http_request/update/http_request_update.cpp [hunk 1]
```diff
@@ -72,47 +72,51 @@ void HttpRequestUpdate::update_task(void *params) {
     read_index += read_bytes;
   }
 
-  std::string response((char *) data, read_index);
-  allocator.deallocate(data, container->content_length);
-
   container->end();
+  container.reset();  // Release ownership of the container's shared_ptr
```
Comment (jesserockz) [inline esphome/components/http_request/update/http_request_update.cpp]: `container->content_length` is used 7 lines below this? Isnt that gonna cause an issue?

Comment (kahrendt) [reply esphome/components/http_request/update/http_request_update.cpp]: I'm surprised it didn't actually cause a problem! I adjusted it. Thanks.

**Review by jesserockz — APPROVED** [review]
