### PR TITLE
Waveshare epaper 7in5 v2alt

### LINKED ISSUE #3119: Waveshare 7.5 inch E-Ink E-Paper Display not working
### The problem

I bought a 7.5 e-ink screen from Waveshare [here](https://www.tinytronics.nl/shop/en/displays/e-ink/waveshare-7.5-inch-e-ink-e-paper-display) and got it to work via an Arduino and on a [Wemos Lolin32](https://www.mischianti.org/wp-content/uploads/2020/11/ESP32-WeMos-LOLIN32-pinout-mischianti.png) but seem completely unable to get it to work on ESPHome...

ESPHome version is v2022.2.6, the ID on the label connect of the screen is `WFT0583CZ61` and hooked it up according to the config from the source provided by Waveshare itself. It does not match 1 to 1 with the image on the site I bought it from, connector seems different.

I've tried different ESP32 boards, bunch of different wiring, all 7.5 inch models... I have no clue what else I can do.

With an Arduino Uno I used
https://github.com/waveshare/e-Paper/tree/master/Arduino/epd7in5_V2

With the Wemos Lolin32 I used 
https://www.waveshare.com/wiki/File:E-Paper_ESP32_Driver_Board_Code.7z

### Which version of ESPHome has the issue?

2022.2.6

### What type of installation are you using?

Docker

### Which version of Home Assistant has the issue?

2022.3.2

### What platform are you using?

ESP32

### Board

_No response_

### Component causing the issue

display/waveshare_epaper

### Example YAML snippet

`DEV_Config.h` lists;
```c
#define EPD_SCK_PIN  13
#define EPD_MOSI_PIN 14
#define EPD_CS_PIN   15
#define EPD_RST_PIN  26
#define EPD_DC_PIN   27
#define EPD_BUSY_PIN 25
```

Using the same pins as on the working Arduino framework code;

```yaml
substitutions:
  device_name: lolin-test
  # online example
  # gpio_spi_clk_pin: GPIO25
  # gpio_spi_mosi_pin: GPIO26
  # gpio_cs_pin: GPIO32
  # gpio_dc_pin: GPIO17
  # gpio_reset_pin: GPIO27
  # gpio_busy_pin: GPIO33
  
  # my attempt
  # gpio_spi_clk_pin: GPIO18
  # gpio_spi_mosi_pin: GPIO23
  # gpio_cs_pin: GPIO5
  # gpio_dc_pin: GPIO22
  # gpio_reset_pin: GPIO21
  # gpio_busy_pin: GPIO4

  # EPD_7IN5_V2 / DEV_Config.h
  gpio_spi_clk_pin: GPIO13
  gpio_spi_mosi_pin: GPIO14
  gpio_cs_pin: GPIO15
  gpio_dc_pin: GPIO27
  gpio_reset_pin: GPIO26
  gpio_busy_pin: GPIO25

  
esphome:
  name: ${device_name}
  name_add_mac_suffix: false

esp32:
  board: lolin32
  framework:
    type: arduino

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password

  # Enable fallback hotspot (captive portal) in case wifi connection fails
  ap:
    ssid: "Lolin-test Fallback Hotspot"
    password: "IFOpMALE9VYQ"

captive_portal:

# Enable logging
logger:
#  baud_rate: 0

# Enable Home Assistant API
api:
  password: "2HQ7Y9YseHMk2uydHBxxxxxxx"

ota:
  password: "2HQ7Y9YseHMk2uydHBxxxxxxx"
  
font:
  - file: 'fonts/OpenSans-Regular.ttf'
    id: font_regular_8
    size: 8
  - file: 'fonts/OpenSans-Regular.ttf'
    id: font_regular_65
    size: 65
    
  - file: 'fonts/OpenSans-Bold.ttf'
    id: font_medium_20
    size: 20

web_server:
  port: 80

time:
  - platform: homeassistant
    timezone: Europe/Amsterdam
    id: current_time
    on_time_sync:
      - component.update: uptime_timestamp

switch:
  - platform: restart
    name: "$device_name Restart"


sensor:
  - platform: uptime
    name: "$device_name Uptime Sec"
    id: uptime_sec
    internal: true

  - platform: wifi_signal
    name: "$device_name WiFi Signal"
    update_interval: 120s

  - platform: template
    id: uptime_timestamp
    name: "$device_name Uptime"
    device_class: "timestamp"
    accuracy_decimals: 0
    update_interval: never
    lambda: |-
      static float timestamp = (
        id(current_time).utcnow().timestamp - id(uptime_sec).state
      );
      return timestamp;

spi:
  clk_pin: $gpio_spi_clk_pin
  mosi_pin: $gpio_spi_mosi_pin
  id: epaper_display

display:
  - platform: waveshare_epaper
    id: epaper
    cs_pin: $gpio_cs_pin
    busy_pin: $gpio_busy_pin
    reset_pin: $gpio_reset_pin
    dc_pin: $gpio_dc_pin
    # model: 7.50in-bV2
    # model: 7.50in-bc
    model: 7.50inV2
    # model: 7.50in
    # full_update_every: 30
    lambda: |-
      ESP_LOGI("display", "Updating...");
      // OUTSIDE
      it.printf(7, 15, id(font_regular_8), TextAlign::BASELINE_LEFT, "Dehors");
      it.line(78, 14, 293, 14);
      
      int time = id(current_time).now().hour * 100 + id(current_time).now().minute;
      // TIME
      it.line(7, 337, 293, 337);
      it.strftime(7, 363, id(font_medium_20), TextAlign::BASELINE_LEFT, "%A", id(current_time).now());
      it.strftime(7, 393, id(font_medium_20), TextAlign::BASELINE_LEFT, "%d %b. %y", id(current_time).now());
      it.strftime(290, 393, id(font_regular_65), TextAlign::BASELINE_RIGHT, "%H:%M", id(current_time).now());
```

### Anything in the logs that might be useful for us?

_No response_

### Additional information

Looking at the c code from esphome specifically the init;

header
```c++
class WaveshareEPaper7P5InV2 : public WaveshareEPaper {
 public:
  void initialize() override;

  void display() override;

  void dump_config() override;

  void deep_sleep() override {
    // COMMAND POWER OFF
    this->command(0x02);
    this->wait_until_idle_();
    // COMMAND DEEP SLEEP
    this->command(0x07);
    this->data(0xA5);  // check byte
  }

 protected:
  int get_width_internal() override;

  int get_height_internal() override;
};
```

```c++
void WaveshareEPaper7P5InV2::initialize() {
  // COMMAND POWER SETTING
  this->command(0x01);
  this->data(0x07);
  this->data(0x07);
  this->data(0x3f);
  this->data(0x3f);
  this->command(0x04);

  delay(100);  // NOLINT
  this->wait_until_idle_();
  // COMMAND PANEL SETTING
  this->command(0x00);
  this->data(0x1F);

  // COMMAND RESOLUTION SETTING
  this->command(0x61);
  this->data(0x03);
  this->data(0x20);
  this->data(0x01);
  this->data(0xE0);
  // COMMAND ...?
  this->command(0x15);
  this->data(0x00);
  // COMMAND VCOM AND DATA INTERVAL SETTING
  this->command(0x50);
  this->data(0x10);
  this->data(0x07);
  // COMMAND TCON SETTING
  this->command(0x60);
  this->data(0x22);
}
```

and I compare that with a working version:

https://github.com/waveshare/e-Paper/blob/master/Arduino/epd7in5_V2/epd7in5_V2.cpp#L96

AND

https://www.waveshare.com/wiki/File:E-Paper_ESP32_Driver_Board_Code.7z

```c++
UBYTE Voltage_Frame_7IN5_V2[]={
	0x6, 0x3F, 0x3F, 0x11, 0x24, 0x7, 0x17,
};

UBYTE EPD_7IN5_V2_Init(void)
{
    EPD_Reset();

    // EPD_SendCommand(0x01);			//POWER SETTING
    // EPD_SendData(0x07);
    // EPD_SendData(0x07);    //VGH=20V,VGL=-20V
    // EPD_SendData(0x3f);		//VDH=15V
    // EPD_SendData(0x3f);		//VDL=-15V

	EPD_SendCommand(0x01);  // power setting
	EPD_SendData(0x17);  // 1-0=11: internal power
	EPD_SendData(*(Voltage_Frame_7IN5_V2+6));  // VGH&VGL
	EPD_SendData(*(Voltage_Frame_7IN5_V2+1));  // VSH
	EPD_SendData(*(Voltage_Frame_7IN5_V2+2));  //  VSL
	EPD_SendData(*(Voltage_Frame_7IN5_V2+3));  //  VSHR
	
	EPD_SendCommand(0x82);  // VCOM DC Setting
	EPD_SendData(*(Voltage_Frame_7IN5_V2+4));  // VCOM

	EPD_SendCommand(0x06);  // Booster Setting
	EPD_SendData(0x27);
	EPD_SendData(0x27);
	EPD_SendData(0x2F);
	EPD_SendData(0x17);

    EPD_SendCommand(0x04); //POWER ON
    DEV_Delay_ms(100);
    EPD_WaitUntilIdle();

    EPD_SendCommand(0X00);			//PANNEL SETTING
    EPD_SendData(0x3F);   //KW-3f   KWR-2F	BWROTP 0f	BWOTP 1f

    EPD_SendCommand(0x61);        	//tres
    EPD_SendData(0x03);		//source 800
    EPD_SendData(0x20);
    EPD_SendData(0x01);		//gate 480
    EPD_SendData(0xE0);

    EPD_SendCommand(0X15);
    EPD_SendData(0x00);

    EPD_SendCommand(0X50);			//VCOM AND DATA INTERVAL SETTING
    EPD_SendData(0x10);
    EPD_SendData(0x00);

    EPD_SendCommand(0X60);			//TCON SETTING
    EPD_SendData(0x22);

    EPD_SendCommand(0x65);  // Resolution setting
    EPD_SendData(0x00);
    EPD_SendData(0x00);//800*480
    EPD_SendData(0x00);
    EPD_SendData(0x00);

	EPD_7IN5_V2_LUT(LUT_VCOM_7IN5_V2, LUT_WW_7IN5_V2, LUT_BW_7IN5_V2, LUT_WB_7IN5_V2, LUT_BB_7IN5_V2);

    return 0;
}
```

### PR DESCRIPTION
**Pull request by patvdleer**
# What does this implement/fix?

Alternative to the current Waveshare epaper `7.50inV2`, with the ID `WFT0583CZ61` on the connector, is added.

## Types of changes

- [ ] Bugfix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] Other

**Related issue or feature (if applicable):** fixes esphome/issues#3119

**Pull request in [esphome-docs](https://github.com/esphome/esphome-docs) with documentation (if applicable):** esphome/esphome-docs#1954

## Test Environment

- [x] ESP32
- [ ] ESP32 IDF
- [ ] ESP8266

## Example entry for `config.yaml`:

```yaml
substitutions:
  device_name: lolin-test
  gpio_spi_clk_pin: GPIO13
  gpio_spi_mosi_pin: GPIO14
  gpio_cs_pin: GPIO15
  gpio_dc_pin: GPIO27
  gpio_reset_pin: GPIO26
  gpio_busy_pin: GPIO25

esphome:
  name: ${device_name}
  name_add_mac_suffix: false

esp32:
  board: lolin32
  framework:
    type: arduino

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password

captive_portal:

# Enable logging
logger:
#  baud_rate: 0

# Enable Home Assistant API
api:
  password: "2HQ7Y9YseHMk2uydHB9Uxxxxxxxxxxxxxx"

ota:
  password: "2HQ7Y9YseHMk2uydHB9Uxxxxxxxxxxxxxx"

spi:
  clk_pin: $gpio_spi_clk_pin
  mosi_pin: $gpio_spi_mosi_pin
  id: epaper_display

font:
  - file: 'fonts/OpenSans-Bold.ttf'
    id: font_medium_65
    size: 65

display:
  - platform: waveshare_epaper
    id: epaper
    cs_pin: $gpio_cs_pin
    busy_pin: $gpio_busy_pin
    reset_pin: $gpio_reset_pin
    dc_pin: $gpio_dc_pin
    # model: 7.50inV2
    model: 7.50inV2alt
    lambda: |-
      ESP_LOGI("display", "Updating...");
      // OUTSIDE
      it.printf(7, 60, id(font_medium_65), TextAlign::BASELINE_LEFT, "This is a test");
      it.line(1, 65, 500, 65);
```

## Checklist:
  - [x] The code change is tested and works locally.
  - [ ] Tests have been added to verify that the new code works (under `tests/` folder).

If user exposed functionality or configuration variables are added/changed:
  - [x] Documentation added/updated in [esphome-docs](https://github.com/esphome/esphome-docs).

### CODE REVIEW

File: esphome/components/waveshare_epaper/waveshare_epaper.h [hunk 1]
```diff
@@ -350,6 +350,25 @@ class WaveshareEPaper7P5InV2 : public WaveshareEPaper {
...
+
+ protected:
+  void reset_() {
+    if (this->reset_pin_ != nullptr) {
+      this->reset_pin_->digital_write(true);
+      delay(200);  // NOLINT
+      this->reset_pin_->digital_write(false);
+      delay(2);  // NOLINT
+      this->reset_pin_->digital_write(true);
+      delay(20);  // NOLINT
```
Comment (jesserockz) [inline esphome/components/waveshare_epaper/waveshare_epaper.h]:
```suggestion
      delay(2);
      this->reset_pin_->digital_write(true);
      delay(20);
```

**Comment by Konstantin-Davidneko** [comment]
@OttoWinter can this be merged into ESPHome? Or you need any additional help?

**Comment by Konstantin-Davidneko** [comment]
Hello. This is pretty important, people who bought Waveshare displays in past couple of months will be unable to use them, if we will not continue to update ESPHome with latest display configurations.

**Review by jesserockz — APPROVED** [review]
