### PR TITLE
Remove floating point ops from the ISR

### LINKED ISSUE #2724: Sensor component ZyAura bootloops ESP32 because of using float variables in ISR
### The problem

Compiling and flashing yaml with ZyAura CO2 sensor component (example from https://esphome.io/components/sensor/zyaura.html) leads to **Guru Meditation Error: Core  1 panic'ed (Coprocessor exception)** and thus boot loops the ESP32.

This is because of float variables being used in the ISR: https://github.com/esphome/esphome/tree/dev/esphome/components/zyaura

From zyaura.h line 43:
```
class ZaSensorStore {
 public:
  float co2 = NAN;
  float temperature = NAN;
  float humidity = NAN;
```
And from zyaura.cpp line 57:
```
void IRAM_ATTR ZaSensorStore::set_data_(ZaMessage *message) {
  switch (message->type) {
    case HUMIDITY:
      this->humidity = (message->value > 10000) ? NAN : (message->value / 100.0f);
      break;

    case TEMPERATURE:
      this->temperature = (message->value > 5970) ? NAN : (message->value / 16.0f - 273.15f);
      break;

    case CO2:
      this->co2 = (message->value > 10000) ? NAN : message->value;
      break;

    default:
      break;
  }
}
```
Temporarily setting these variables to fixed integers solves the boot loop.

This kind of issue is described here as example: https://www.reddit.com/r/esp32/comments/lj2nkx/just_discovered_that_you_cant_use_floats_in_isr/

Thanks @ssieb for helping me.

### Which version of ESPHome has the issue?

2021.9.1

### What type of installation are you using?

pip

### Which version of Home Assistant has the issue?

-

### What platform are you using?

ESP32

### Board

az-delivery-devkit-v4

### Component causing the issue

zyaura

### Example YAML snippet

```yaml
sensor:
  - platform: zyaura
    clock_pin: 22
    data_pin: 21
    co2:
      name: "ZyAura CO2"
    temperature:
      name: "ZyAura Temperature"
```

### Anything in the logs that might be useful for us?

```txt
[11:00:05]Rebooting...
[11:00:05]ets Jun  8 2016 00:22:57
[11:00:05]
[11:00:05]rst:0xc (SW_CPU_RESET),boot:0x13 (SPI_FAST_FLASH_BOOT)
[11:00:05]configsip: 0, SPIWP:0xee
[11:00:05]clk_drv:0x00,q_drv:0x00,d_drv:0x00,cs0_drv:0x00,hd_drv:0x00,wp_drv:0x00
[11:00:05]mode:DIO, clock div:2
[11:00:05]load:0x3fff0018,len:4
[11:00:05]load:0x3fff001c,len:1044
[11:00:05]load:0x40078000,len:10124
[11:00:05]load:0x40080400,len:5828
[11:00:05]entry 0x400806a8
[11:00:05][I][logger:174]: Log initialized
[11:00:05][VV][preferences:038]: LOAD 0: valid=YES, 0=0x00000008 1=0x75320207 (Type=233825507, CRC=0x75320207)
[11:00:05][C][ota:379]: There have been 8 suspected unsuccessful boot attempts.
[11:00:05][VV][preferences:051]: SAVE 0: 0=0x00000009 1=0x4A164723 (Type=233825507, CRC=0x4A164723)
[11:00:05][I][app:029]: Running through setup()...
[11:00:05][V][app:030]: Sorting components by setup priority...
[11:00:05][VV][scheduler:056]: set_interval(name='update', interval=60000, offset=24997)
[11:00:05][C][wifi:037]: Setting up WiFi...
[11:00:05][V][preferences:260]: nvs_get_blob('1'): ESP_ERR_NVS_NOT_FOUND - the key might not be set yet
[11:00:05][V][wifi_esp32:037]: Enabling STA.
[11:00:05][VV][esp-idf:000]: I (88) wifi:
[11:00:05][VV][esp-idf:000]: wifi driver task: 3ffae738, prio:23, stack:3584, core=0
[11:00:05][VV][esp-idf:000]: 
[11:00:05]
[11:00:05][VV][esp-idf:000]: I (399) wifi:
[11:00:05][VV][esp-idf:000]: wifi firmware version: dc30037
[11:00:05][VV][esp-idf:000]: 
[11:00:05]
[11:00:05][VV][esp-idf:000]: I (400) wifi:
[11:00:05][VV][esp-idf:000]: config NVS flash: enabled
[11:00:05][VV][esp-idf:000]: 
[11:00:05]
[11:00:05][VV][esp-idf:000]: I (412) wifi:
[11:00:05][VV][esp-idf:000]: config nano formating: disabled
[11:00:05][VV][esp-idf:000]: 
[11:00:05]
[11:00:05][VV][esp-idf:000]: I (424) wifi:
[11:00:05][VV][esp-idf:000]: Init data frame dynamic rx buffer num: 32
[11:00:05][VV][esp-idf:000]: 
[11:00:05]
[11:00:05][VV][esp-idf:000]: I (437) wifi:
[11:00:05][VV][esp-idf:000]: Init management frame dynamic rx buffer num: 32
[11:00:05][VV][esp-idf:000]: 
[11:00:05]
[11:00:05][VV][esp-idf:000]: I (451) wifi:
[11:00:05][VV][esp-idf:000]: Init management short buffer num: 32
[11:00:05][VV][esp-idf:000]: 
[11:00:05]
[11:00:05][VV][esp-idf:000]: I (463) wifi:
[11:00:05][VV][esp-idf:000]: Init dynamic tx buffer num: 32
[11:00:05][VV][esp-idf:000]: 
[11:00:05]
[11:00:05][VV][esp-idf:000]: I (476) wifi:
[11:00:05][VV][esp-idf:000]: Init static rx buffer size: 1600
[11:00:05][VV][esp-idf:000]: 
[11:00:05]
[11:00:05][VV][esp-idf:000]: I (488) wifi:
[11:00:05][VV][esp-idf:000]: Init static rx buffer num: 16
[11:00:05][VV][esp-idf:000]: 
[11:00:05]
[11:00:05][VV][esp-idf:000]: I (500) wifi:
[11:00:05][VV][esp-idf:000]: Init dynamic rx buffer num: 32
[11:00:05][VV][esp-idf:000]: 
[11:00:05]
[11:00:05][VV][esp-idf:000]: I (604) wifi:
[11:00:05][VV][esp-idf:000]: mode : sta (cc:50:e3:9a:1b:2c)
[11:00:05][VV][esp-idf:000]: 
[11:00:05]
[11:00:05][D][WiFiGeneric.cpp:374] _eventCallback(): Event: 0 - WIFI_READY
[11:00:05][D][WiFiGeneric.cpp:374] _eventCallback(): Event: 2 - STA_START
[11:00:05][V][wifi_esp32:413]: Event: WiFi STA start
[11:00:05][V][wifi_esp32:400]: Event: WiFi ready
[11:00:05][VV][esp-idf:000]: I (637) wifi:
[11:00:05][VV][esp-idf:000]: Set ps type: 1
[11:00:05]
[11:00:05][VV][esp-idf:000]: 
[11:00:05]
[11:00:05][D][wifi:382]: Starting scan...
[11:00:05][VV][scheduler:151]: Running interval 'update' with interval=60000 last_execution=4294882362 (now=372)
[11:00:05][V][sensor:070]: 'ZyAura CO2': Received new state nan
[11:00:05][D][sensor:121]: 'ZyAura CO2': Sending state nan ppm with 0 decimals of accuracy
[11:00:05][W][zyaura:086]: Sensor reported invalid data. Is the update interval too small?
[11:00:05]Guru Meditation Error: Core  1 panic'ed (Coprocessor exception)
[11:00:05]Core 1 register dump:
[11:00:05]PC      : 0x4008103d  PS      : 0x00060031  A0      : 0x800810b1  A1      : 0x3ffbfe40  
WARNING Decoded 0x4008103d: esphome::zyaura::ZaSensorStore::set_data_(esphome::zyaura::ZaMessage*) at /home/user/projects/ZyAura_CO2_Sensor/room1/src/esphome/components/zyaura/zyaura.cpp:60 (discriminator 1)
[11:00:06]A2      : 0x3ffb8c4c  A3      : 0x00000001  A4      : 0x3ffb87b0  A5      : 0x00000000  
[11:00:06]A6      : 0x00000000  A7      : 0x00000000  A8      : 0x00002710  A9      : 0x00000041  
[11:00:06]A10     : 0x7fc00000  A11     : 0x00000000  A12     : 0x00000798  A13     : 0x0000e5c0  
[11:00:06]A14     : 0x00000798  A15     : 0x00000000  SAR     : 0x0000000a  EXCCAUSE: 0x00000004  
[11:00:06]EXCVADDR: 0x00000000  LBEG    : 0x400014fd  LEND    : 0x4000150d  LCOUNT  : 0xffffffe8  
[11:00:06]Core 1 was running in ISR context:
[11:00:06]EPC1    : 0x4008103d  EPC2    : 0x00000000  EPC3    : 0x00000000  EPC4    : 0x40087a60
[11:00:06]
[11:00:06]ELF file SHA256: 0000000000000000
[11:00:06]
[11:00:06]Backtrace: 0x4008103d:0x3ffbfe40 0x400810ae:0x3ffbff20 0x4008134d:0x3ffbff40 0x400872d5:0x3ffbff60 0x4008c71b:0x3ffb1d20 0x4008c716:0x3ffb1d40 0x400de09d:0x3ffb1d60 0x400dff62:0x3ffb1db0 0x400eadda:0x3ffb1fb0 0x40089f02:0x3ffb1fd0
WARNING Found stack trace! Trying to decode it
WARNING Decoded 0x4008103d: esphome::zyaura::ZaSensorStore::set_data_(esphome::zyaura::ZaMessage*) at /home/user/projects/ZyAura_CO2_Sensor/room1/src/esphome/components/zyaura/zyaura.cpp:60 (discriminator 1)
WARNING Decoded 0x400810ae: esphome::zyaura::ZaSensorStore::interrupt(esphome::zyaura::ZaSensorStore*) at /home/user/projects/ZyAura_CO2_Sensor/room1/src/esphome/components/zyaura/zyaura.cpp:53
WARNING Decoded 0x4008134d: __onPinInterrupt at /home/user/.platformio/packages/framework-arduinoespressif32/cores/esp32/esp32-hal-gpio.c:198
WARNING Decoded 0x400872d5: _xt_lowint1 at /home/runner/work/esp32-arduino-lib-builder/esp32-arduino-lib-builder/esp-idf/components/freertos/xtensa_vectors.S:1154
WARNING Decoded 0x4008c71b: vPortYield at /home/runner/work/esp32-arduino-lib-builder/esp32-arduino-lib-builder/esp-idf/components/freertos/portasm.S:525
WARNING Decoded 0x4008c716: vPortYield at /home/runner/work/esp32-arduino-lib-builder/esp32-arduino-lib-builder/esp-idf/components/freertos/portasm.S:523
WARNING Decoded 0x400de09d: esphome::Application::setup() at /home/user/projects/ZyAura_CO2_Sensor/room1/src/esphome/core/application.cpp:55
WARNING Decoded 0x400dff62: setup() at /home/user/projects/ZyAura_CO2_Sensor/room1/src/main.cpp:158
WARNING Decoded 0x400eadda: loopTask(void*) at /home/user/.platformio/packages/framework-arduinoespressif32/cores/esp32/main.cpp:18
WARNING Decoded 0x40089f02: vPortTaskWrapper at /home/runner/work/esp32-arduino-lib-builder/esp32-arduino-lib-builder/esp-idf/components/freertos/port.c:355 (discriminator 1)
[11:00:06]
[11:00:06]Rebooting...
```

### Additional information

_No response_

### PR DESCRIPTION
**Pull request by ssieb**
# What does this implement/fix? 

Fixes the coprocessor exception from [issues#2724](https://github.com/esphome/issues/issues/2724).

## Types of changes

- [X] Bugfix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] Other

**Related issue or feature (if applicable):** fixes [issues#2724](https://github.com/esphome/issues/issues/2724)

**Pull request in [esphome-docs](https://github.com/esphome/esphome-docs) with documentation (if applicable):** 

## Test Environment

- [ ] ESP32
- [ ] ESP32 IDF
- [ ] ESP8266

## Example entry for `config.yaml`:

```yaml
# Example config.yaml

```

## Checklist:
  - [ ] The code change is tested and works locally.
  - [ ] Tests have been added to verify that the new code works (under `tests/` folder).
  
If user exposed functionality or configuration variables are added/changed:
  - [ ] Documentation added/updated in [esphome-docs](https://github.com/esphome/esphome-docs).

### CODE REVIEW

**Review by oxan — APPROVED** [review]

**Comment by nemonada23** [comment]
I tested the fix and it solved the issue. The ESP32 connected to the sensor is now correctly sending CO2 and temperature values to HomeAssistant
unknown

During compiling I got a warning, because a temporarily variable may not be initialized:

```
src/esphome/components/zyaura/zyaura.cpp: In member function 'bool esphome::zyaura::ZyAuraSensor::publishstate(esphome::zyaura::ZaDataType, esphome::sensor::Sensor, uint16_t)':
src/esphome/components/zyaura/zyaura.cpp:98:3: warning: 'value' may be used uninitialized in this function [-Wmaybe-uninitialized]
   if (isnan(value)) {
```

Also I'm not sure if the isnan() check is working as intended right now.
Thanks for the fix @ssieb!

File: esphome/components/zyaura/zyaura.cpp [hunk 1]
```diff
@@ -57,38 +57,46 @@ void IRAM_ATTR ZaSensorStore::interrupt(ZaSensorStore *arg) {
...
+  switch (data_type) {
+    case HUMIDITY:
+      value = (*data_value > 10000) ? NAN : (*data_value / 100.0f);
+      break;
+    case TEMPERATURE:
+      value = (*data_value > 5970) ? NAN : (*data_value / 16.0f - 273.15f);
+      break;
+    case CO2:
+      value = (*data_value > 10000) ? NAN : *data_value;
+      break;
```
Comment (oxan) [inline esphome/components/zyaura/zyaura.cpp:87]: Curious that compile warning didn't show up on CI...
```suggestion
      break;
    default:
      return false;
```

**Review by oxan — COMMENTED** [review]
As far as I can see the `isnan` check should work fine.

File: esphome/components/zyaura/zyaura.cpp (hunk 1 above)
Comment (nemonada23) [reply esphome/components/zyaura/zyaura.cpp:87]: I compiled the new code using `pio run --target upload` from within the project folder after compiling it once with `esphome compile`, because i was not able to compile it as a local external component/the git issue syntax, e.g. `source: github://pr#2751`.

This is my first encounter with ESPHome, so I'm sure that I messed something up during configuring the external component, but somewhere in the docs I read about the possibility to compile it with pio run. Maybe this is doing different things than esphome compile?

Comment (oxan) [reply esphome/components/zyaura/zyaura.cpp:87]: > Maybe this is doing different things than esphome compile?

No, you're doing it right, I get the warning too. CI actually [gets it as well](https://github.com/esphome/esphome/runs/4245943944?check_suite_focus=true#step:11:473), but I think the matcher is broken.

Comment (ssieb) [reply esphome/components/zyaura/zyaura.cpp:87]: It shouldn't need that because all cases are covered.  I'll just initialize the variable...

Comment (oxan) [reply esphome/components/zyaura/zyaura.cpp:87]: > It shouldn't need that because all cases are covered.

The problem is that in C++ enumerations are really just an integer, so an enum variable can have values that aren't part of the enum.

**Review by nemonada23 — APPROVED** [review]

**Review by jesserockz — APPROVED** [review]
