### PR TITLE
fix i2c scanning eror for Arduino

### LINKED ISSUE #2453: i2c scanning not working after  after #2303
### The problem

I2c scan reports all addresses as connected if Arduino framework is used (esp-idf is ok)

expected 
[16:35:29][I][i2c.arduino:034]: Scanning i2c bus for active devices...
[16:35:29][I][i2c.arduino:042]: Found i2c device at address 0x76
[16:35:29][C][logger:235]: Logger:

actually getting:

I][i2c.arduino:034]: Scanning i2c bus for active devices...
[16:41:58][I][i2c.arduino:040]: Found i2c device at address 0x01
[16:41:58][I][i2c.arduino:040]: Found i2c device at address 0x02
...
[16:41:59][I][i2c.arduino:040]: Found i2c device at address 0x74
[16:41:59][I][i2c.arduino:040]: Found i2c device at address 0x75
[16:41:59][I][i2c.arduino:040]: Found i2c device at address 0x76
[16:41:59][I][i2c.arduino:040]: Found i2c device at address 0x77

### Which version of ESPHome has the issue?

current dev branch

### What type of installation are you using?

pip

### Which version of Home Assistant has the issue?

_No response_

### What platform are you using?

ESP32

### Board

_No response_

### Component causing the issue

_No response_

### Example YAML snippet

```yaml
substitutions:
  updates: 60s
  unique_id: bme280

esphome:
  name: ${unique_id}

esp32:
  board: TinyPICO
  framework:
    type: arduino

logger:
  level: VERBOSE
i2c:
  sda: 21
  scl: 22
  scan: True
  id: bus_a

sensor:
  - platform: bme280
    temperature:
      name: "Temperatur (Huette)"
      id: hut_temperature
    humidity:
      name: "Luftfeuchtigkeit (Huette)"
      id: hut_humidity
    update_interval: ${updates}
    address: 0x76
```

### Anything in the logs that might be useful for us?

```txt
I][i2c.arduino:034]: Scanning i2c bus for active devices...
[16:41:58][I][i2c.arduino:040]: Found i2c device at address 0x01
[16:41:58][I][i2c.arduino:040]: Found i2c device at address 0x02
...
[16:41:59][I][i2c.arduino:040]: Found i2c device at address 0x74
[16:41:59][I][i2c.arduino:040]: Found i2c device at address 0x75
[16:41:59][I][i2c.arduino:040]: Found i2c device at address 0x76
[16:41:59][I][i2c.arduino:040]: Found i2c device at address 0x77
```

### Additional information

reverting the code to the previous pattern fixes the issue
 `
wire_->beginTransmission(address);
auto err = wire_->endTransmission(true);
`

### PR DESCRIPTION
**Pull request by martgras**
revert to the old scan implementation.

# What does this implement/fix? 
getting correct i2c scan results

Quick description and explanation of changes

## Types of changes

- [x] Bugfix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] Other

**Related issue or feature (if applicable):** fixes https://github.com/esphome/issues/issues/2453

**Pull request in [esphome-docs](https://github.com/esphome/esphome-docs) with documentation (if applicable):** esphome/esphome-docs#<esphome-docs PR number goes here>

## Test Environment

- [x] ESP32
- [ ] ESP8266

## Example entry for `config.yaml`:

```yaml
substitutions:
  updates: 60s
  unique_id: bme280

esphome:
  name: ${unique_id}

esp32:
  board: TinyPICO
  framework:
    type: arduino

logger:
  level: VERBOSE
i2c:
  sda: 21
  scl: 22
  scan: True
  id: bus_a

sensor:
  - platform: bme280
    temperature:
      name: "Temperatur (Huette)"
      id: hut_temperature
    humidity:
      name: "Luftfeuchtigkeit (Huette)"
      id: hut_humidity
    update_interval: ${updates}
    address: 0x76
```

## Checklist:
  - [x] The code change is tested and works locally.
  - [ ] Tests have been added to verify that the new code works (under `tests/` folder).

### CODE REVIEW

**Review by mmakaay — COMMENTED** [review]
Why revert the code? I think the roll forward option might be to use:

```c++
auto err = writev(address, nullptr, 0);
```
That should work too IMO, and would be closer to the intended target code.

File: esphome/components/i2c/i2c_bus_arduino.cpp [hunk 1]
```diff
@@ -34,7 +34,8 @@ void ArduinoI2CBus::dump_config() {
     ESP_LOGI(TAG, "Scanning i2c bus for active devices...");
     uint8_t found = 0;
     for (uint8_t address = 1; address < 120; address++) {
-      auto err = readv(address, nullptr, 0);
+      wire_->beginTransmission(address);
+      auto err = wire_->endTransmission(true);
 
       if (err == ERROR_OK) {
```
Comment (OttoWinter) [inline esphome/components/i2c/i2c_bus_arduino.cpp:38]: `ERROR_OK` is of type `i2c::ErrorCode`; but `endTransmission` returns type `int` - it may just happen that the i2c error codes match up with what endTransmission returns, but we can't assume that in general.

**Comment by martgras** [comment]
@mmakaay is right  `auto err = writev(address, nullptr, 0);` works as well for me and we don't have to use the underlying wire_ object here.

File: esphome/components/i2c/i2c_bus_arduino.cpp (hunk 1 above)
Comment (martgras) [reply esphome/components/i2c/i2c_bus_arduino.cpp:38]: updated the PR to use writev. 
Is there a reason why the scan ends at address 119 and not 127?

Comment (OttoWinter) [reply esphome/components/i2c/i2c_bus_arduino.cpp:38]: iirc those addresses are reserved for special uses and so can't have i2d devices connected

looks like this explains it: https://electronics.stackexchange.com/a/7553

**Comment by OttoWinter** [comment]
> @mmakaay is right  `auto err = writev(address, nullptr, 0);` works as well for me and we don't have to use the underlying wire_ object here. 
> 
> 

The same applies to the esp_idf implementation, could you also update the _esp_idf.cpp file? Thanks!

File: esphome/components/i2c/i2c_bus_arduino.cpp (hunk 1 above)
Comment (martgras) [reply esphome/components/i2c/i2c_bus_arduino.cpp:38]: ok changed the range to 8 - 119 to exclude the 2 reserved ranges

Comment (martgras) [reply esphome/components/i2c/i2c_bus_arduino.cpp:38]: actually  for esp-idf readv works as well but switching to writev for consistency.

**Comment by martgras** [comment]
BTW: The CI check doesn't seem to pull the correct files https://github.com/esphome/esphome/actions/runs/1261652210 shows files that are not part of this commit

**Comment by oxan** [comment]
> BTW: The CI check doesn't seem to pull the correct files https://github.com/esphome/esphome/actions/runs/1261652210 shows files that are not part of this commit

The CI runs on a simulated merge between dev and your PR, but you unfortunately just hit the moment where I broke CI on dev. I've scheduled a rerun, it should be fine now.

**Review by OttoWinter — APPROVED** [review]
Thanks!
