### PR TITLE
[mipi_spi] Add M5CORE2 model that extends the ILI9341 driver chip

### LINKED ISSUE #12297: Issue with the `mipi_spi` component `transform` key
### The problem

I am facing an issue with the `mipi_spi` `transform` key and M5Core2 device. 
Same issue with M5Core2 V1.1 too.

**Working config**
```yaml
display:
  - platform: mipi_spi
    model: ILI9341
    id: main_display
    cs_pin: GPIO5
    dc_pin: GPIO15
    data_rate: 40MHz
    invert_colors: true
    pixel_mode: 18bit
    dimensions:
      height: 240
      width: 320
    transform: # must be explicitly set until bug is fixed
      swap_xy: false
      mirror_x: false
      mirror_y: false
    show_test_card: true
```

It should be possible to remove the `transform` section, but this is not the case.
If this part is removed, the display is inverted on the x-axis. So there is definitely a problem.

**Not working config**
```yaml
display:
  - platform: mipi_spi
    model: ILI9341
    id: main_display
    cs_pin: GPIO5
    dc_pin: GPIO15
    data_rate: 40MHz
    invert_colors: true
    pixel_mode: 18bit
    dimensions:
      height: 240
      width: 320
    show_test_card: true
```
<details><summary>Device screen picture</summary>
<p>

Image

</p>
</details> 

### Which version of ESPHome has the issue?

2025.11.3

### What type of installation are you using?

Home Assistant Add-on

### What platform are you using?

esp32

### Component causing the issue

_No response_

### YAML Config

```yaml
display:
  - platform: mipi_spi
    model: ILI9341
    id: main_display
    cs_pin: GPIO5
    dc_pin: GPIO15
    data_rate: 40MHz
    invert_colors: true
    pixel_mode: 18bit
    dimensions:
      height: 240
      width: 320
    show_test_card: true
```

### Anything in the logs that might be useful for us?

```txt

```

### Additional information

https://github.com/esphome/esphome/blob/19fa76873070356fda4b277bfee7b3db152e9b49/esphome/components/mipi/__init__.py#L403

### PR DESCRIPTION
**Pull request by lboue**
# What does this implement/fix?

This PR adds support for the M5Stack Core2 display by creating a new M5CORE2 model that extends the existing ILI9341 driver chip definition. The M5Stack Core2 uses an ILI9341 chip but requires different default configuration settings (particularly disabling mirror_x) along with hardware-specific pin assignments and display characteristics.

Key Changes:

- Adds `M5CORE2` model extending `ILI9341` with hardware-specific configuration (320x240 resolution, specific GPIO pins, 18-bit pixel mode, inverted colors)
- Overrides the base ILI9341's `mirror_x=True` default with `mirror_x=False` for correct display orientation on the M5Stack Core2 hardware

## Types of changes

- [ ] Bugfix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] Developer breaking change (an API change that could break external components)
- [ ] Code quality improvements to existing code or addition of tests
- [ ] Other

**Related issue or feature (if applicable):**

- fixes [#12297](https://github.com/esphome/esphome/issues/12297)

**Pull request in [esphome-docs](https://github.com/esphome/esphome-docs) with documentation (if applicable):**

- esphome/esphome-docs#5730

## Test Environment

- [x] ESP32
- [ ] ESP32 IDF
- [ ] ESP8266
- [ ] RP2040
- [ ] BK72xx
- [ ] RTL87xx
- [ ] nRF52840

## Example entry for `config.yaml`:

```yaml
display:
  - platform: mipi_spi
    model: M5CORE2
    show_test_card: true
```

## Checklist:
  - [ ] The code change is tested and works locally.
  - [ ] Tests have been added to verify that the new code works (under `tests/` folder).

If user exposed functionality or configuration variables are added/changed:
  - [x] Documentation added/updated in [esphome-docs](https://github.com/esphome/esphome-docs).

### CODE REVIEW

File: esphome/components/mipi_spi/mipi_spi.h [hunk 1]
```diff
@@ -478,7 +478,7 @@ class MipiSpiBuffer : public MipiSpi<BUFFERTYPE, BUFFERPIXEL, IS_BIG_ENDIAN, DIS
     RAMAllocator<BUFFERTYPE> allocator{};
     this->buffer_ = allocator.allocate(BUFFER_WIDTH * BUFFER_HEIGHT / FRACTION);
     if (this->buffer_ == nullptr) {
-      this->mark_failed(LOG_STR("Buffer allocation failed"));
+      this->mark_failed("Buffer allocation failed");
```
Comment (swoboda1337) [inline esphome/components/mipi_spi/mipi_spi.h]: Why?

Comment (lboue) [reply esphome/components/mipi_spi/mipi_spi.h]: I am getting this error:
```cpp
src/esphome/components/mipi_spi/mipi_spi.h:481:24: error: no matching function for call to 'esphome::mipi_spi::MipiSpiBuffer<short unsigned int, esphome::mipi_spi::PIXEL_MODE_16, true, esphome::mipi_spi::PIXEL_MODE_16, esphome::mipi_spi::BUS_TYPE_SINGLE, 135, 240, 40, 52, esphome::display::DISPLAY_ROTATION_0_DEGREES, 5, 2>::mark_failed(const esphome::LogString*)'
  481 |       this->mark_failed(LOG_STR("Buffer allocation failed"));
      |       ~~~~~~~~~~~~~~~~~^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
In file included from src/esphome/core/application.h:7,
                 from src/esphome/components/api/api_frame_helper.h:13,
                 from src/esphome/components/api/api_connection.h:5,
                 from src/esphome.h:3:
src/esphome/core/component.h:158:16: note: candidate: 'virtual void esphome::Component::mark_failed()'
  158 |   virtual void mark_failed();
      |                ^~~~~~~~~~~
src/esphome/core/component.h:158:16: note:   candidate expects 0 arguments, 1 provided
src/esphome/core/component.h:160:8: note: candidate: 'void esphome::Component::mark_failed(const char*)'
  160 |   void mark_failed(const char *message) {
      |        ^~~~~~~~~~~
src/esphome/core/component.h:160:32: note:   no known conversion for argument 1 from 'const esphome::LogString*' to 'const char*'
  160 |   void mark_failed(const char *message) {
      |                    ~~~~~~~~~~~~^~~~~~~
*** [.pioenvs/m5stick-plus/src/main.cpp.o] Error 1
```

Comment (swoboda1337) [reply esphome/components/mipi_spi/mipi_spi.h]: It is there:
```
  void mark_failed(const LogString *message) {
    this->status_set_error(message);
    this->mark_failed();
  }
```
I suspect you are not building from source but with a version of esphome installed via python. To build from your clone do this then run `esphome` normally:
```
script/setup
source venv/bin/activate
```
Your change here to LOG_STR doesnt make sense and needs to be reverted.

**Review by swoboda1337 — DISMISSED** [review]

File: esphome/components/mipi_spi/mipi_spi.h (hunk 1 above)
Comment (lboue) [reply esphome/components/mipi_spi/mipi_spi.h]: Reverted.
Yes I did the test with 2025.11.3. It was not a good idea.

File: tests/components/mipi_spi/test-m5core2.esp32-idf.yaml [hunk 2]
```diff
@@ -0,0 +1,7 @@
+packages:
+  spi: !include ../../test_build_components/common/spi/esp32-ard.yaml
+
+display:
+  - platform: mipi_spi
+    spi_id: spi_bus
+    model: M5CORE2
```
Comment (clydebarrow) [inline tests/components/mipi_spi/test-m5core2.esp32-idf.yaml]: This file isn't needed - the various models are config tested by the unit tests, and we don't need another compile test.

**Review by clydebarrow — CHANGES_REQUESTED** [review]
Otherwise looks good.

File: tests/components/mipi_spi/test-m5core2.esp32-idf.yaml (hunk 2 above)
Comment (lboue) [reply tests/components/mipi_spi/test-m5core2.esp32-idf.yaml]: Thanks. I removed it.

**Review by clydebarrow — APPROVED** [review]
