### PR TITLE
TCS34725 BugFix and GA factor

### LINKED ISSUE #1740: TCS34725 color temperature algorithm wrong. Better one available.
**Operating environment/Installation (Hass.io/Docker/pip/etc.):**

Latest esphome and HomeAssistant (as of 5th January 2021)

**ESP (ESP32/ESP8266, Board/Sonoff):**

Generic ESP32 but is does not matter
**ESPHome version (latest production, beta, dev branch)**

 1.15.3
**Affected component:**

TCS34725

**Description of problem:**
Function for calculating color temperature for this sensor is now deprecated in Adafruit library as it was found to produce wrong values.
https://github.com/esphome/esphome/blob/3ee6348e41f31b293e2a7d61c8f896b55acba519/esphome/components/tcs34725/tcs34725.cpp#L94

Adafruit lib provides newer function based on manufacturers white paper. It should provide better results.
https://github.com/adafruit/Adafruit_TCS34725/blob/6dc42834bd071aeb94bdddff7e17cb662de20ad2/Adafruit_TCS34725.cpp#L418

Here are some references to mentioned issue:
https://github.com/adafruit/Adafruit_TCS34725/issues/21
https://github.com/letscontrolit/ESPEasy/issues/3453

**Problem-relevant YAML-configuration entries:**
```yaml
PASTE YAML FILE HERE
 - platform: tcs34725
    red_channel:
      name: "Weather Station Red Channel"
    green_channel:
      name: "Weather Station Green Channel"
    blue_channel:
      name: "Weather Station Blue Channel"
    clear_channel:
      name: "Weather Station Clear Channel"
    illuminance:
      name: "Weather Station Illuminance (TCS34725)"
    color_temperature:
      name: "Weather Station Color Temperature"
    gain: 1x
    integration_time: 50ms
    address: 0x29
    update_interval: 10s
```

**Logs (if applicable):**

```
PASTE DEBUG LOG HERE

```

**Additional information and things you've tried:**

Also illuminance values are way off. I have two different sensors next to TCS34725. They are more or less similar but TCS is wrong by orders of magnitude. Also you can see how wrong is temperature. 
image

### PR DESCRIPTION
**Pull request by razorback16**
- Fixed endianness bug on tcs34725 data read
- Fixed supported integration times. **700ms** is not supported so it was removed.
- Fixed lux adjustments based on gain, integration time, and GA factor
- Added glass attenuation factor to allow using this sensor behind
  semi-transparent glass

Got inspired by **Adafruit changes to TCS34725 library**. ESPHome code was out of date and was not representing the right values as the byte order was swapped.

Fixes issue esphome/issues#1740

Documentation is also updated to reflect the Glass Transmissivity factor on another pull request to esphome-docs

## Types of changes

- [X] Bugfix (non-breaking change which fixes an issue)
- [X] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] Other

**Related issue or feature (if applicable):** fixes esphome/issues#1740

**Pull request in [esphome-docs](https://github.com/esphome/esphome-docs) with documentation (if applicable):** esphome/esphome-docs#1506

## Test Environment

- [X] ESP32
- [ ] ESP8266

## Example entry for `config.yaml`:

```yaml
# Example config.yaml
# Example configuration entry
sensor:
  - platform: tcs34725
    red_channel:
      name: "TCS34725 Red Channel"
    green_channel:
      name: "TCS34725 Green Channel"
    blue_channel:
      name: "TCS34725 Blue Channel"
    clear_channel:
      name: "TCS34725 Clear Channel"
    illuminance:
      name: "TCS34725 Illuminance"
    color_temperature:
      name: "TCS34725 Color Temperature"
    gain: 1x
    glass_attenuation_factor: 1.0
    integration_time: 614ms
    address: 0x29
    update_interval: 60s
```

## Checklist:
  - [X] The code change is tested and works locally.
  - [X] Tests have been added to verify that the new code works (under `tests/` folder).
  
If user exposed functionality or configuration variables are added/changed:
  - [X] Documentation added/updated in [esphome-docs](https://github.com/esphome/esphome-docs).

### CODE REVIEW

File: esphome/components/tcs34725/tcs34725.cpp [hunk 1]
```diff
@@ -74,6 +180,12 @@ void TCS34725Component::update() {
     return;
   }
 
+  // Need to convert from little endian to big endian to get proper values
```
Comment (oxan) [inline esphome/components/tcs34725/tcs34725.cpp]: I think this comment is the wrong way around; the ESP's are all little endian, so you only need to swap if the data you read is big endian.

Comment (OttoWinter) [reply esphome/components/tcs34725/tcs34725.cpp]: Agree, and also we shouldn't assume the endianness of the host system (there may be esps with different endianness at some point)

Please have a look at i2c::i2ctohs (behaves like ntohs)

Comment (razorback16) [reply esphome/components/tcs34725/tcs34725.cpp]: Hi Otto,

Thanks for the suggestion, I have updated the code and the comment to use i2c::i2ctohs for the bug fix.

**Review by jesserockz — APPROVED** [review]

**Comment by OttoWinter** [comment]
@jesserockz is this really a breaking change? If the option didn't work before anyway, I wouldn't consider it a breaking change...

**Comment by jesserockz** [comment]
It is if someone has `700ms` in their config

The value sent to the device is the same as 614ms, but it breaks existing configs.

**Comment by razorback16** [comment]
Hi @OttoWinter when will this get merged?

**Review by oxan — APPROVED** [review]

**Comment by oxan** [comment]
Thanks!
