### PR TITLE
Fix climate restore schema changed resulting in invalid restore

### LINKED ISSUE #2235: 1.19.2 to 1.19.4 bang_bang reports gibberish state in HA 2021.7.2 thermostat UI
**Operating environment/Installation (Hass.io/Docker/pip/etc.):**

ESPHome: Docker, 1.19.4
HA: Docker, 2021.7.2

**ESP (ESP32/ESP8266, Board/Sonoff):**

Sonoff TH10

**ESPHome version (latest production, beta, dev branch)**

1.19.4

**Affected component:**

bang_bang

**Description of problem:**
Upgrading from 1.19.2 to 1.19.4 broke the UI text for the HA thermostat component.
1.19.2 work, 1.19.4 broke

**Problem-relevant YAML-configuration entries:**
```yaml
climate:
  - platform: bang_bang
    name: ${device_name}_bangbang
    id: bangbang
    sensor: recirc_temp
    default_target_temperature_low: 30
    default_target_temperature_high: 40
    heat_action:
      - logger.log: "BangBang : Heat Action, Turning Relay On."
      - switch.turn_on: relay
    idle_action:
      - logger.log: "BangBang : Idle Action, Turning Relay Off."
      - switch.turn_off: relay
    visual:
      min_temperature: 20
      max_temperature: 50
      temperature_step: 0.5
```

**Logs (if applicable):**

```
[19:38:14][D][debug:023]: ESPHome version 1.19.4
[19:38:14][D][debug:025]: Free Heap Size: 17872 bytes
[19:38:14][D][debug:053]: Flash Chip: Size=1024kB Speed=40MHz Mode=DOUT
[19:38:14][D][debug:190]: Chip ID: 0x00006BAB
[19:38:14][D][debug:191]: SDK Version: 2.2.2-dev(38a443e)
[19:38:14][D][debug:192]: Core Version: 2_7_4
[19:38:14][D][debug:193]: Boot Version=31 Mode=1
[19:38:14][D][debug:194]: CPU Frequency: 80
[19:38:14][D][debug:195]: Flash Chip ID=0x0014605E
[19:38:14][D][debug:196]: Reset Reason: Software/System restart
[19:38:14][D][debug:197]: Reset Info: Software/System restart
[19:38:20][D][sensor:117]: 'sonoff_th10_hot_recirc_pump_uptime': Sending state 8.79045 minutes with 0 decimals of accuracy
[19:38:21][D][dallas.sensor:153]: 'sonoff_th10_hot_recirc_pump_recirc_temp': Got Temperature=36.6°C
[19:38:21][D][sensor:117]: 'sonoff_th10_hot_recirc_pump_recirc_temp': Sending state 36.83333 °C with 1 decimals of accuracy
[19:38:21][D][climate:369]: 'sonoff_th10_hot_recirc_pump_bangbang' - Sending state:
[19:38:21][D][climate:372]:   Mode: HEAT_COOL
[19:38:21][D][climate:374]:   Action: IDLE
[19:38:21][D][climate:392]:   Current Temperature: 36.83°C
[19:38:21][D][climate:396]:   Target Temperature: Low: -158456325028528675187087900672.00°C High: 0.00°C
[19:38:21][D][dallas.sensor:153]: 'sonoff_th10_hot_recirc_pump_hot_temp': Got Temperature=48.0°C
[19:38:21][D][sensor:117]: 'sonoff_th10_hot_recirc_pump_hot_temp': Sending state 48.10417 °C with 1 decimals of accuracy
[19:38:21][D][dallas.sensor:153]: 'sonoff_th10_hot_recirc_pump_cold_temp': Got Temperature=25.8°C
[19:38:21][D][sensor:117]: 'sonoff_th10_hot_recirc_pump_cold_temp': Sending state 25.72917 °C with 1 decimals of accuracy
[19:38:21][D][dallas.sensor:153]: 'sonoff_th10_hot_recirc_pump_ambient_temp': Got Temperature=31.1°C
[19:38:21][D][sensor:117]: 'sonoff_th10_hot_recirc_pump_ambient_temp': Sending state 31.06250 °C with 1 decimals of accuracy
[19:38:28][D][sensor:117]: 'sonoff_th10_hot_recirc_pump_wifi_signal': Sending state -49.33333 dBm with 0 decimals of accuracy
```
2021-07-12 (2)_LI
2021-07-12 (3)_LI

**Additional information and things you've tried:**
After upgrading from 1.19.2 to 1.19.4 you have to go into the HA UI and drag the low and high temps to get the thermostat to behave correctly.

My money is on the HA API changes that broke backwards compatibility between ESPHome and HA for stored state information.

### PR DESCRIPTION
**Pull request by OttoWinter**
# What does this implement/fix? 

Fixes https://github.com/esphome/issues/issues/2235

## Types of changes

- [x] Bugfix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] Other

**Related issue or feature (if applicable):** fixes <link to issue>

**Pull request in [esphome-docs](https://github.com/esphome/esphome-docs) with documentation (if applicable):** esphome/esphome-docs#<esphome-docs PR number goes here>

## Test Environment

- [ ] ESP32
- [ ] ESP8266

## Example entry for `config.yaml`:

```yaml
# Example config.yaml

```

## Checklist:
  - [ ] The code change is tested and works locally.
  - [ ] Tests have been added to verify that the new code works (under `tests/` folder).
  
If user exposed functionality or configuration variables are added/changed:
  - [ ] Documentation added/updated in [esphome-docs](https://github.com/esphome/esphome-docs).

### CODE REVIEW

File: esphome/components/climate/climate.cpp [hunk 1]
```diff
@@ -313,7 +313,7 @@ void Climate::add_on_state_callback(std::function<void()> &&callback) {
 }
 
 optional<ClimateDeviceRestoreState> Climate::restore_state_() {
-  this->rtc_ = global_preferences.make_preference<ClimateDeviceRestoreState>(this->get_object_id_hash());
+  this->rtc_ = global_preferences.make_preference<ClimateDeviceRestoreState>(this->get_object_id_hash() ^ 0x848EA6ADUL);
```
Comment (agners) [inline esphome/components/climate/climate.cpp]: :monocle_face: what is this? Can use a pre-processor define or static variable to give this a name?

Comment (OttoWinter) [reply esphome/components/climate/climate.cpp]: Changing this parameter to `make_preference` essentially invalidates the existing preference. But yeah I can create a var :)

File: esphome/components/climate/climate.cpp [hunk 2]
```diff
@@ -312,8 +312,11 @@ void Climate::add_on_state_callback(std::function<void()> &&callback) {
   this->state_callback_.add(std::move(callback));
 }
 
+// Random 32bit value; If this changes existing restore preferences are invalided
```
Comment (agners) [inline esphome/components/climate/climate.cpp]:
```suggestion
// Random 32bit value; If this changes existing restore preferences are invalidated
```

**Review by agners — APPROVED** [review]
