### PR TITLE
[esp32_touch] Migrate to new unified touch sensor driver (esp_driver_touch_sens)

### LINKED ISSUE #12323: Run time warning v2025.11.4 for touch sensor
### The problem

For a couple of months I have been noticing a runtime error that I don't think has been reported for touch sensors.  The error I get is below and others on Home Assistant Community are getting the same error.

```txt
In file included from src/esphome/components/esp32_touch/esp32_touch.h:11,
                 from src/esphome/components/esp32_touch/esp32_touch_common.cpp:3:
/data/cache/platformio/packages/framework-espidf/components/driver/touch_sensor/esp32/include/driver/touch_sensor.h:13:2: warning: #warning "This set of Touch APIs has been deprecated, please include 'driver/touch_sens.h' instead. if you want to keep using the old APIs and ignore this warning, you can enable 'Suppress legacy driver deprecated warning' option under 'Touch Configuration' menu in Kconfig" [-Wcpp]
   13 | #warning "This set of Touch APIs has been deprecated, \
      |  ^~~~~~~
Compiling .pioenvs/f
```

The sensor is a water sensor on an ESP32 platform:
```yaml
binary_sensor:
  - platform: esp32_touch
    name: "Water Sensor Pin15"
    pin: 15
    threshold: 100
```

I have not figured a work around anywhere and wanted to bring it to your attention.

### Which version of ESPHome has the issue?

v2025.11.4

### What type of installation are you using?

Home Assistant Add-on

### What platform are you using?

ESP32

### Component causing the issue

Touch Sensor

### YAML Config

```yaml
substitutions:
  esphome_name: aquariumsensor

esphome:
  name: ${esphome_name}

esp32:
  board: esp-wrover-kit
  framework:
    type: esp-idf

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_ssid_password
  
  # Enable fallback hotspot (captive portal) in case wifi connection fails
  ap:
    ssid: "Aquariumsensor Fallback Hotspot"
    password: "46iopd2Oc7eU"

captive_portal:

# Enable logging
logger:
  level: debug

# Enable Home Assistant API
api:
  reboot_timeout: 60min

ota:
  - platform: esphome

time:
  - platform: homeassistant
    id: esptime

remote_transmitter:
  pin: 26
  # Infrared remotes use a 50% carrier signal
  carrier_duty_percent: 50%
  
switch:
#no pin in esp32 from keystudio
  - platform: restart
    name: ${esphome_name}-restart
    id: restart_switch
#buttonsrow1
  - platform: template
    name: "aqled_orange"
    id: aqled_orange
    turn_on_action:
      - remote_transmitter.transmit_raw:
          code: [ 8979, -4441, 589, -538, 586, -519, 560, -1689, 563, -542, 560, -564, 588, -538, 587, -518, 560, -564, 588, -1643, 585, -1664, 587, -519, 559, -1690, 587, -1641, 588, -1644, 584, -1666, 643, -1585, 587, -540, 586, -518, 559, -1691, 643, 
                  -1584, 588, -1643, 585, -540, 587, -1643, 585, -539, 587, -1644, 584, -1664, 646, -461, 558, -564, 588, -540, 643, -1585, 587, -539, 644, -1584, 588]
          carrier_frequency: 38kHz        
  - platform: template
    name: "aqled_cyan"
    id: aqled_cyan
    turn_on_action:
      - remote_transmitter.transmit_raw:
          code: [ 8979, -4440, 589, -537, 644, -463, 584, -1664, 644, -463, 585, -537, 589, -536, 646, -461, 584, -539, 589, -1643, 585, -1662, 646, -461, 585, -1663, 644, -1585, 588, -1644, 585, -1662, 645, -1585, 588, -1643, 585, -539, 589, -1641, 586, 
                  -1662, 646, -1584, 588, -537, 646, -1584, 587, -538, 645, -462, 559, -1688, 646, -461, 584, -539, 587, -538, 646, -1584, 587, -538, 644, -1585, 587]
          carrier_frequency: 38kHz        
  - platform: template
    name: "aqled_purple"
    id: aqled_purple
    turn_on_action:
      - remote_transmitter.transmit_raw:
          code: [ 8978, -4442, 589, -537, 645, -461, 559, -1690, 563, -543, 559, -564, 563, -563, 645, -460, 584, -539, 589, -1642, 586, -1663, 564, -542, 560, -1689, 563, -1666, 589, -1642, 586, -1663, 589, -1640, 589, -1642, 586, -538, 588, -538, 563, 
                  -542, 560, -564, 588, -539, 572, -1655, 589, -537, 645, -461, 559, -1689, 564, -1666, 588, -1642, 586, -1664, 563, -1666, 587, -539, 644, -1584, 589]
          carrier_frequency: 38kHz
  - platform: template
    name: "aqled_power"
    id: aqled_power
    turn_on_action:
      - remote_transmitter.transmit_raw:
          code: [ 8974, -4445, 587, -537, 589, -538, 644, -1584, 588, -538, 646, -459, 563, -560, 589, -536, 644, -463, 559, -1690, 644, -1584, 589, -537, 645, -1584, 588, -1643, 585, -1663, 645, -1584, 589, -1643, 585, -538, 588, -539, 562, -542, 560, -563, 
                  589, -538, 644, -461, 560, -1690, 642, -463, 559, -1689, 644, -1585, 589, -1642, 586, -1664, 562, -1666, 589, -1642, 585, -538, 589, -1643, 585]
          carrier_frequency: 38kHz
#buttonsrow2
  - platform: template
    name: "aqled_white"
    id: aqled_white
    turn_on_action:
      - remote_transmitter.transmit_raw:
          code: [ 9026, -4411, 620, -507, 563, -542, 558, -1691, 564, -541, 558, -566, 563, -563, 563, -542, 558, -566, 618, -1613, 558, -1690, 565, -541, 558, -1691, 564, -1664, 563, -1669, 558, -1689, 565, -1665, 563, -563, 564, -542, 557, -566, 618, 
                  -1613, 558, -1691, 564, -542, 557, -1692, 563, -542, 558, -1691, 564, -1665, 562, -1669, 558, -564, 563, -563, 565, -1665, 617, -508, 563, -1665, 563]
          carrier_frequency: 38kHz        
  - platform: template
    name: "aqled_sun"
    id: aqled_sun
    turn_on_action:
      - remote_transmitter.transmit_raw:
          code: [ 8979, -4441, 589, -538, 642, -463, 559, -1690, 642, -464, 559, -564, 588, -537, 643, -463, 584, -539, 589, -1642, 586, -1663, 643, -463, 561, -1688, 643, -1586, 587, -1644, 585, -1663, 645, -1584, 589, -1642, 586, -537, 590, -537, 642, 
                  -1586, 589, -1642, 586, -537, 589, -1641, 587, -539, 588, -538, 641, -1586, 589, -1643, 585, -537, 589, -537, 671, -1558, 589, -537, 643, -1586, 588]
          carrier_frequency: 38kHz        
  - platform: template
    name: "aqled_blue"
    id: aqled_blue
    turn_on_action:
      - remote_transmitter.transmit_raw:
          code: [ 8979, -4440, 590, -536, 645, -462, 559, -1689, 644, -462, 560, -563, 588, -538, 587, -519, 584, -538, 589, -1643, 585, -1663, 564, -543, 559, -1689, 644, -1585, 589, -1642, 585, -1663, 644, -1586, 588, -1643, 585, -538, 589, -1642, 586, 
                  -537, 589, -538, 644, -461, 560, -1689, 563, -543, 559, -564, 588, -1642, 586, -538, 589, -1642, 585, -1665, 642, -1586, 588, -539, 642, -1586, 587]
          carrier_frequency: 38kHz
  - platform: template
    name: "aqled_play"
    id: aqled_play
    turn_on_action:
      - remote_transmitter.transmit_raw:
          code: [ 8977, -4441, 590, -538, 587, -518, 559, -1690, 565, -540, 559, -564, 588, -537, 589, -517, 560, -564, 587, -1644, 585, -1664, 645, -461, 559, -1691, 586, -1641, 588, -1643, 585, -1664, 587, -1642, 588, -537, 588, -518, 559, -1690, 645, 
                  -460, 560, -565, 587, -539, 586, -1642, 588, -537, 571, -1658, 588, -1642, 585, -539, 588, -1644, 584, -1664, 646, -1583, 588, -538, 645, -1583, 589]
          carrier_frequency: 38kHz
#buttonsrow3
  - platform: template
    name: "aqled_red_up"
    id: aqled_red_up
    turn_on_action:
      - remote_transmitter.transmit_raw:
          code: [ 8976, -4442, 588, -520, 582, -541, 585, -1647, 581, -541, 585, -540, 589, -518, 583, -539, 585, -540, 646, -1584, 586, -1646, 581, -541, 586, -1646, 583, -1664, 647, -1583, 585, -1648, 582, -1664, 647, -461, 582, -540, 585, -1647, 583, 
                  -539, 586, -1646, 583, -541, 585, -1646, 583, -539, 586, -1647, 583, -1664, 646, -461, 583, -1664, 590, -518, 582, -1665, 647, -461, 582, -1665, 564]
          carrier_frequency: 38kHz        
  - platform: template
    name: "aqled_green_up"
    id: aqled_green_up
    turn_on_action:
      - remote_transmitter.transmit_raw:
          code: [ 9052, -4389, 641, -464, 559, -565, 588, -1642, 585, -539, 588, -541, 639, -463, 585, -539, 589, -537, 642, -1586, 588, -1643, 559, -565, 588, -1642, 585, -1666, 642, -1586, 586, -1645, 558, -1691, 643, -1586, 587, -539, 641, -1588, 586, 
                  -540, 641, -1587, 586, -541, 641, -1586, 587, -540, 587, -517, 559, -1691, 642, -463, 558, -1692, 640, -464, 559, -1691, 643, -486, 534, -1694, 666]
          carrier_frequency: 38kHz        
  - platform: template
    name: "aqled_blue_up"
    id: aqled_blue_up
    turn_on_action:
      - remote_transmitter.transmit_raw:
          code: [ 8999, -4441, 646, -478, 512, -593, 566, -1685, 511, -593, 645, -481, 564, -560, 511, -593, 565, -562, 643, -1585, 566, -1685, 511, -592, 643, -1610, 509, -1719, 564, -1665, 645, -1605, 511, -1719, 643, -1586, 645, -481, 642, -483, 510, 
                  -1720, 563, -562, 509, -594, 564, -1687, 510, -593, 565, -562, 642, -1587, 646, -1604, 511, -593, 565, -1685, 511, -1720, 669, -455, 511, -1719, 644]
          carrier_frequency: 38kHz
  - platform: template
    name: "aqled_bright_up"
    id: aqled_bright_up
    turn_on_action:
      - remote_transmitter.transmit_raw:
          code: [ 8975, -4445, 586, -539, 643, -464, 582, -1666, 642, -465, 582, -540, 586, -539, 565, -543, 575, -547, 586, -1646, 583, -1665, 642, -464, 583, -1665, 643, -1587, 586, -1646, 582, -1665, 644, -1586, 584, -541, 643, -464, 557, -565, 585, 
                  -1648, 582, -540, 586, -539, 589, -1640, 586, -539, 644, -1586, 585, -1647, 583, -1664, 644, -464, 582, -1665, 644, -1586, 586, -539, 643, -1586, 588]
          carrier_frequency: 38kHz
#buttonsrow4
  - platform: template
    name: "aqled_red_dn"
    id: aqled_red_dn
    turn_on_action:
      - remote_transmitter.transmit_raw:
          code: [ 9040, -4381, 650, -476, 559, -545, 591, -1660, 558, -546, 591, -534, 593, -532, 559, -546, 590, -535, 592, -1637, 588, -1663, 586, -517, 588, -1663, 587, -1640, 588, -1644, 583, -1666, 587, -1642, 587, -539, 587, -517, 560, -565, 587, -540, 
                  586, -1641, 587, -540, 586, -1641, 588, -538, 587, -1642, 587, -1644, 585, -1664, 587, -1643, 587, -538, 562, -1666, 589, -539, 586, -1641, 589]
          carrier_frequency: 38kHz        
  - platform: template
    name: "aqled_green_dn"
    id: aqled_green_dn
    turn_on_action:
      - remote_transmitter.transmit_raw:
          code: [ 8976, -4444, 587, -538, 565, -542, 583, -1665, 646, -461, 583, -539, 587, -539, 645, -462, 582, -540, 587, -1645, 583, -1664, 590, -517, 584, -1664, 564, -1666, 560, -1671, 584, -1664, 565, -1664, 586, -1646, 584, -539, 586, -539, 646, 
                  -461, 584, -1664, 645, -462, 583, -1664, 564, -543, 583, -540, 586, -1646, 583, -1664, 564, -1665, 587, -539, 646, -1583, 587, -538, 591, -1639, 586]
          carrier_frequency: 38kHz        
  - platform: template
    name: "aqled_blue_dn"
    id: aqled_blue_dn
    turn_on_action:
      - remote_transmitter.transmit_raw:
          code: [ 8979, -4441, 590, -536, 644, -462, 585, -1663, 563, -544, 560, -562, 589, -538, 643, -462, 585, -538, 589, -1642, 586, -1663, 644, -462, 585, -1663, 645, -1585, 587, -1644, 585, -1663, 645, -1584, 587, -1645, 585, -538, 588, -1644, 584, 
                  -1663, 647, -460, 584, -539, 588, -1644, 584, -538, 588, -537, 565, -1665, 586, -539, 646, -461, 558, -1690, 645, -1584, 587, -539, 645, -1583, 587]
          carrier_frequency: 38kHz
  - platform: template
    name: "aqled_bright_dn"
    id: aqled_bright_dn
    turn_on_action:
      - remote_transmitter.transmit_raw:
          code: [ 9056, -4385, 645, -480, 588, -519, 558, -1691, 586, -520, 558, -565, 587, -538, 588, -518, 561, -562, 589, -1642, 585, -1665, 562, -543, 559, -1690, 576, -1652, 589, -1643, 585, -1663, 564, -1666, 588, -537, 563, -543, 584, -1663, 565, 
                  -1665, 589, -537, 563, -543, 585, -1662, 644, -464, 584, -1663, 564, -1666, 588, -538, 562, -544, 559, -1688, 643, -1587, 588, -537, 563, -1666, 589]
          carrier_frequency: 38kHz
#buttonsrow5
  - platform: template
    name: "aqled_m1"
    id: aqled_m1
    turn_on_action:
      - remote_transmitter.transmit_raw:
          code: [ 9039, -4385, 564, -543, 560, -563, 589, -1643, 585, -538, 589, -535, 589, -519, 584, -539, 588, -538, 586, -1643, 588, -1643, 585, -539, 588, -1642, 586, -1664, 564, -1665, 588, -1642, 585, -1665, 587, -519, 559, -564, 588, -1643, 585, 
                  -1665, 643, -1586, 587, -539, 643, -461, 584, -540, 588, -1644, 584, -1661, 590, -543, 534, -565, 589, -539, 641, -1586, 592, -1640, 590, -1659, 4319, -1590, 774, -1032]
          carrier_frequency: 38kHz        
  - platform: template
    name: "aqled_m2"
    id: aqled_m2
    turn_on_action:
      - remote_transmitter.transmit_raw:
          code: [ 8925, -4497, 511, -594, 567, -558, 568, -1661, 567, -559, 566, -559, 510, -594, 567, -558, 568, -557, 511, -1719, 568, -1661, 565, -560, 568, -1662, 645, -1604, 614, -1615, 648, -1584, 616, -1633, 614, -1615, 618, -509, 612, -1616, 560, 
                  -1670, 558, -1692, 615, -490, 557, -567, 561, -566, 615, -488, 558, -1693, 615, -489, 558, -565, 563, -564, 613, -1615, 562, -1670, 558, -1692, 1785, -1590, 774, -1032]
          carrier_frequency: 38kHz        
  - platform: template
    name: "aqled_m3"
    id: aqled_m3
    turn_on_action:
      - remote_transmitter.transmit_raw:
          code: [ 9035, -4388, 669, -437, 563, -562, 586, -1643, 585, -539, 588, -539, 642, -462, 585, -540, 588, -538, 642, -1586, 589, -1641, 587, -537, 592, -1638, 589, -1664, 640, -1586, 592, -1639, 589, -1662, 640, -464, 647, -1603, 559, -1669, 650, 
                  -1582, 647, -1603, 558, -546, 591, -534, 650, -475, 557, -1672, 648, -478, 557, -548, 649, -476, 649, -476, 510, -1719, 649, -1581, 647, -1604, 5029, -1446]
          carrier_frequency: 38kHz
  - platform: template
    name: "aqled_m4"
    id: aqled_m4
    turn_on_action:
      - remote_transmitter.transmit_raw:
          code: [ 8955, -4469, 557, -547, 591, -535, 648, -1581, 647, -479, 673, -452, 510, -594, 567, -559, 565, -560, 510, -1719, 645, -1583, 566, -561, 643, -1586, 565, -1685, 511, -1720, 642, -1586, 644, -1606, 539, -1692, 562, -1666, 564, -1687, 539, 
                  -1691, 640, -1588, 644, -483, 561, -563, 539, -565, 563, -564, 560, -564, 539, -564, 564, -563, 562, -563, 538, -1691, 563, -1666, 565, -1686, 2902, -1446, 1830, -553]
          carrier_frequency: 38kHz
#buttonsrow6
  - platform: template
    name: "aqled_bluemoon"
    id: aqled_bluemoon
    turn_on_action:
      - remote_transmitter.transmit_raw:
          code: [ 8945, -4496, 536, -570, 584, -540, 561, -1669, 586, -539, 587, -538, 535, -571, 559, -565, 587, -537, 535, -1695, 587, -1644, 584, -541, 585, -1645, 585, -1663, 535, -1695, 587, -1643, 587, -1663, 534, -572, 559, -565, 613, -511, 536, 
                  -1695, 586, -1643, 586, -539, 561, -564, 535, -571, 586, -1662, 535, -1695, 587, -1644, 560, -564, 589, -536, 535, -1695, 586, -1644, 614, -1635, 992, -1446, 1830, -553]
          carrier_frequency: 38kHz        
  - platform: template
    name: "aqled_greymoon"
    id: aqled_greymoon
    turn_on_action:
      - remote_transmitter.transmit_raw:
          code: [ 8924, -4496, 536, -571, 558, -565, 561, -1670, 587, -537, 585, -540, 536, -570, 584, -540, 586, -538, 536, -1694, 587, -1644, 585, -539, 560, -1671, 586, -1663, 535, -1695, 585, -1645, 559, -1689, 536, -1694, 561, -565, 535, -572, 583, 
                  -1665, 534, -1695, 586, -539, 535, -571, 586, -538, 586, -539, 535, -1694, 586, -1645, 559, -565, 561, -564, 536, -1693, 586, -1645, 585, -1664, 750, -553, 3974, -325, 117, -650]
          carrier_frequency: 38kHz        
  - platform: template
    name: "aqled_nightcloudy"
    id: aqled_nightcloudy
    turn_on_action:
      - remote_transmitter.transmit_raw:
          code: [ 8923, -4496, 512, -595, 563, -561, 564, -1666, 564, -560, 617, -509, 510, -595, 563, -561, 565, -560, 511, -1718, 565, -1667, 588, -536, 589, -1641, 589, -1660, 511, -1719, 591, -1639, 589, -1660, 533, -573, 578, -1671, 531, -575, 562, 
                   -1687, 532, -1698, 563, -562, 532, -573, 588, -537, 590, -1640, 587, -537, 590, -1640, 589, -536, 589, -535, 514, -1717, 563, -1667, 588, -1660, 2687, -325, 117, -650, 1702, -2071, 600, -7157]
          carrier_frequency: 38kHz
  - platform: template
    name: "aqled_sunrise"
    id: aqled_sunrise
    turn_on_action:
      - remote_transmitter.transmit_raw:
          code: [ 8940, -4498, 512, -591, 559, -569, 559, -1669, 561, -565, 559, -566, 510, -594, 558, -568, 559, -566, 530, -1699, 559, -1670, 558, -567, 560, -1670, 585, -1664, 512, -1718, 586, -1644, 587, -1662, 555, -1675, 587, -1644, 588, -536, 564, 
                  -1667, 588, -1661, 563, -543, 562, -562, 588, -537, 562, -544, 563, -562, 563, -1666, 588, -536, 589, -536, 562, -1668, 565, -1665, 564, -1686, 2043, -2071, 600, -7157, 2935, -213]
          carrier_frequency: 38kHz
#buttonsrow7
  - platform: template
    name: "aqled_partcloud"
    id: aqled_partcloud
    turn_on_action:
      - remote_transmitter.transmit_raw:
          code: [ 9064, -4371, 663, -459, 665, -460, 559, -1671, 665, -459, 559, -550, 661, -461, 664, -461, 583, -524, 663, -1585, 557, -1672, 664, -461, 558, -1671, 585, -1648, 662, -1585, 556, -1674, 585, -1648, 660, -461, 587, -539, 556, -1673, 585, 
                  -541, 556, -1672, 586, -541, 555, -552, 581, -540, 586, -1648, 581, -1666, 555, -552, 581, -1666, 556, -552, 581, -1666, 557, -1672, 585, -1648, 582]
          carrier_frequency: 38kHz        
  - platform: template
    name: "aqled_partcloud2"
    id: aqled_partcloud2
    turn_on_action:
      - remote_transmitter.transmit_raw:
          code: [ 8923, -4497, 512, -593, 648, -478, 646, -1584, 566, -559, 566, -559, 510, -594, 645, -481, 566, -558, 511, -1719, 567, -1663, 566, -559, 646, -1583, 648, -1602, 511, -1719, 646, -1583, 567, -1684, 511, -1719, 644, -481, 510, -1719, 645, 
                  -480, 510, -1720, 646, -480, 509, -594, 647, -479, 646, -478, 511, -1719, 646, -480, 510, -1719, 646, -479, 510, -1720, 647, -1582, 645, -1605, 511]
          carrier_frequency: 38kHz        
  - platform: template
    name: "aqled_cloudy"
    id: aqled_cloudy
    turn_on_action:
      - remote_transmitter.transmit_raw:
          code: [ 9078, -4363, 641, -464, 564, -559, 588, -1644, 584, -540, 587, -540, 641, -462, 584, -540, 587, -540, 638, -1590, 587, -1644, 584, -540, 587, -1643, 584, -1667, 640, -1587, 588, -1644, 583, -1666, 642, -464, 557, -1693, 641, -1587, 586, 
                 -540, 641, -1588, 586, -541, 641, -462, 584, -540, 587, -1644, 584, -540, 587, -540, 667, -1560, 587, -540, 642, -1586, 587, -1644, 584, -1667, 640, -466, 88]
          carrier_frequency: 38kHz
  - platform: template
    name: "aqled_cloudy2"
    id: aqled_cloudy2
    turn_on_action:
      - remote_transmitter.transmit_raw:
          code: [ 8973, -4446, 586, -538, 588, -538, 587, -1641, 589, -538, 643, -462, 559, -565, 587, -538, 587, -519, 559, -1690, 644, -1585, 588, -538, 587, -1641, 588, -1643, 585, -1663, 589, -1642, 588, -1643, 584, -1666, 643, -1585, 587, -1644, 584, 
                  -540, 587, -1645, 583, -539, 588, -539, 586, -518, 584, -539, 589, -538, 644, -462, 558, -1692, 642, -462, 559, -1690, 672, -1557, 587, -1644, 584
                  ]
          carrier_frequency: 38kHz
#buttonsrow8
  - platform: template
    name: "aqled_tstorm"
    id: aqled_tstorm
    turn_on_action:
      - remote_transmitter.transmit_raw:
          code: [ 9034, -4386, 567, -559, 566, -558, 511, -1720, 566, -558, 511, -593, 567, -559, 566, -559, 511, -593, 567, -1684, 510, -1720, 566, -558, 511, -1720, 565, -1663, 567, -1683, 512, -1719, 567, -1662, 566, -560, 565, -560, 510, -594, 567, -559, 
                  565, -1664, 566, -560, 565, -559, 511, -593, 567, -1683, 511, -1720, 590, -1638, 568, -1683, 511, -594, 566, -1684, 510, -1719, 585, -1645, 566]
          carrier_frequency: 38kHz        
  - platform: template
    name: "aqled_tstorm2"
    id: aqled_tstorm2
    turn_on_action:
      - remote_transmitter.transmit_raw:
          code: [ 9037, -4383, 647, -479, 647, -478, 510, -1720, 591, -533, 511, -594, 648, -478, 647, -477, 511, -594, 566, -1684, 510, -1720, 566, -559, 510, -1720, 646, -1583, 566, -1683, 511, -1720, 647, -1582, 567, -1683, 511, -594, 566, -559, 646, 
                  -478, 511, -1720, 646, -478, 511, -594, 567, -559, 647, -477, 511, -1719, 647, -1582, 648, -1603, 510, -594, 567, -1683, 511, -1719, 647, -1582, 567]
          carrier_frequency: 38kHz        
  - platform: template
    name: "aqled_tstormsun"
    id: aqled_tstormsun
    turn_on_action:
      - remote_transmitter.transmit_raw:
          code: [ 8955, -4465, 567, -558, 596, -529, 511, -1719, 597, -529, 509, -595, 595, -531, 596, -528, 511, -594, 566, -1684, 510, -1719, 595, -531, 510, -1719, 568, -1662, 594, -1656, 510, -1720, 597, -1632, 566, -559, 597, -1633, 596, -529, 596, 
                   -529, 511, -1718, 597, -529, 510, -595, 596, -529, 597, -1632, 567, -558, 596, -1634, 566, -1683, 511, -595, 566, -1683, 511, -1719, 568, -1662, 566]
          carrier_frequency: 38kHz
  - platform: template
    name: "aqled_cloudsun"
    id: aqled_cloudsun
    turn_on_action:
      - remote_transmitter.transmit_raw:
          code: [ 9035, -4386, 646, -480, 564, -560, 511, -1720, 563, -561, 510, -593, 646, -482, 562, -563, 509, -593, 565, -1687, 509, -1720, 645, -480, 511, -1719, 644, -1584, 566, -1686, 510, -1719, 644, -1585, 565, -1685, 511, -1718, 645, -481, 511, 
                  -593, 565, -1686, 511, -593, 644, -483, 563, -561, 511, -593, 565, -562, 644, -1584, 645, -1605, 511, -594, 646, -1604, 511, -1719, 644, -1585, 565]
          carrier_frequency: 38kHz

# Example configuration entry
#dallas:
#   - pin: 23
one_wire:
  - platform: gpio
    pin: 23
  
# Example configuration entry
sensor:
  - platform: dallas_temp
    address: 0x3001204D7AD46828
    name: "Aquarium Temp1"
  - platform: dallas_temp
    address: 0x0001204F25649828
    name: "Aquarium Temp2"    
  - platform: uptime
    name: "${esphome_name}_Uptime Sensor"
    update_interval: 60s    
  - platform: wifi_signal
    name: "${esphome_name} WiFi Signal"
    update_interval: 60s
#internal use below
  - platform: homeassistant
    id: a_temp1
    entity_id: sensor.Aquarium_Temp1_2
    internal: true
  - platform: homeassistant
    id: a_temp2
    entity_id: sensor.Aquarium_Temp2_2
    internal: true
  - platform: homeassistant
    id: wifi_sig
    entity_id: sensor.aquariumsensor_wifi_signal
    internal: true
  - platform: homeassistant
    id: o_temp
    entity_id: sensor.temp_off
    internal: true
  - platform: homeassistant
    id: a_tds
    entity_id: sensor.aquarium_tds
    internal: true
####tds PPM docs and old way to measure
# https://github.com/jcallaghan/esphome-config/issues/4
#https://community.home-assistant.io/t/aquarium-water-quality-tds-sensor/420676
#  - platform: adc
#    pin: 34
#    name: "aquarium_tds"
#    update_interval: 60s
#    unit_of_measurement: "ppm"
#    icon: "mdi:water-percent"
#    filters:
#default from keyestudio
#      - lambda: return (133.42*x*x*x - 255.86*x*x + 857.39*x)*0.5;
#my calibration 04-03-21
#      - lambda: return (135*x*x*x - 256*x*x + 1220*x)*0.5;
#compensationCoefficient=1.0+0.02*(temperature-25.0) in °C
#=(1+0.02*((a_temp1-32)*5/9-25))
#celcius=(x°F − 32) × 5/9
#compensationVolatge=averageVoltage/compensationCoefficient;
#      - lambda: return (133.42*(x/(1+0.02*((a_temp1-32)*5/9-25)))*(x/(1+0.02*((a_temp1-32)*5/9-25)))*(x/(1+0.02*((a_temp1-32)*5/9-25))) - 255.86*(x/(1+0.02*((a_temp1-32)*5/9-25)))*(x/(1+0.02*((a_temp1-32)*5/9-25))) + 857.39*(x/(1+0.02*((a_temp1-32)*5/9-25))))*0.5;
#(x/(1+0.02*((a_temp1-32)*5/9-25)))
#      - calibrate_linear:
#          - 0.0 -> 0.0 
#          - 0.87 -> 1353
#    attenuation: 6db
###tds volts raw reading with moving average
  - platform: adc
    pin: 34
    name: "aquarium_tds_volts"
    id: tds01raw
    accuracy_decimals: 4
    update_interval: 10s
    unit_of_measurement: "v"
    icon: "mdi:water-percent"
    filters:
      - sliding_window_moving_average:
          window_size: 6
          send_every: 6  
    attenuation: 6db
### Temperature Compensated Voltage
  - platform: template
    name: "TDS TCV"
    id: temp01_comp_v
    unit_of_measurement: 'v'
    accuracy_decimals: 4
#in °C    
#    lambda: 'return ((id(tds01raw).state) / (1 + (0.02 * ((id(a_temp1).state) - 25.0))));'
#in °F
    lambda: 'return ((id(tds01raw).state) / (1 + (0.02 * (((id(a_temp1).state - 32) * 5 / 9) - 25.0))));'
    update_interval: 30s
    internal: true
### Temperature Compensated TDS
  - platform: template
    name: "aquarium_tds"
    id: "atds"
    update_interval: 30s
    unit_of_measurement: "ppm"
    state_class: "measurement"
    icon: "mdi:water-percent"
    accuracy_decimals: 0    
    lambda: return (133.42*(id(temp01_comp_v).state)*(id(temp01_comp_v).state)*(id(temp01_comp_v).state) - 255.86*(id(temp01_comp_v).state)*(id(temp01_comp_v).state) + 857.39*(id(temp01_comp_v).state))*0.5;

#for display and version sensor
text_sensor:
  - platform: version
    name: "${esphome_name}_ver"

font:
  - file: 'arial.ttf'
    id: font1
    size: 15
  - file: 'BebasNeue-Regular.ttf'
    id: font2
    size: 42
  - file: 'arial.ttf'
    id: font3
    size: 14

image:
#small screen
  - file: mdi:home-city
    type: BINARY
    id: office
    resize: 14x14
  - file: mdi:wifi
    type: BINARY
    id: wifix
    resize: 14x14
  - file: mdi:arrow-up-bold
    type: BINARY
    id: up
    resize: 20x20
  - file: mdi:arrow-down-bold
    type: BINARY
    id: down
    resize: 18x18
  - file: mdi:water-percent
    type: BINARY
    id: waterq
    resize: 14x14
    
output:
  - platform: ledc
    pin: 19
    id: redgpio
  - platform: ledc
    pin: 22
    id: greengpio
  - platform: ledc
    pin: 21
    id: bluegpio

light:
  - platform: rgb
    name: "LED Aquarium"
    red: redgpio
    green: greengpio
    blue: bluegpio

# Example esp32 touch
esp32_touch:
  setup_mode: false

binary_sensor:
  - platform: esp32_touch
    name: "Water Sensor Pin15"
    pin: 15
    threshold: 100

#multi-temperature graph plot
#SSD1306 is 128 width x 64 height
#y_grid is 20 deg/div = 20
graph:
  - id: multi_temperature_graph
    duration: 12h
    x_grid: 1h
    y_grid: 2     
    width: 128
    height: 50
    traces:
      - sensor: a_temp2
        line_type: DASHED
        line_thickness: 2
      - sensor: a_temp1
        line_type: SOLID
        line_thickness: 3
  - id: tds_graph
    duration: 12h
    x_grid: 1h
    y_grid: 10
    width: 128
    height: 50
    traces:
      - sensor: atds
        line_type: SOLID
        line_thickness: 3

# display SSD1306 OLED
i2c:
  #yellow wire=s on display=d0 on board=scl
  sda: 5
  #blue wire=s on display=d4 on board=scl
  scl: 18
  frequency: 400kHz

display:
  - platform: ssd1306_i2c
    model: "SSD1306 128x64"
    id: my_display
    pages:
      - id: page1
        lambda: |-
          it.strftime(0, 0, id(font1), TextAlign::TOP_LEFT, "%m-%d-%y %I:%M %p", id(esptime).now());
          it.image(-2, 15, id(up));
          it.printf(14, 14, id(font2), "%.0f°", id(a_temp1).state);
          it.line(0, 14, 128, 14);
          it.line(64, 14, 64, 100);
          it.image(65, 15, id(down));
          it.printf(80, 14, id(font2), "%.0f°", id(a_temp2).state);
          it.image(0, 52, id(office));
          it.printf(15, 50, id(font1), "%.0f°", id(o_temp).state);
          it.image(72, 52, id(waterq));
          it.printf(87, 50, id(font1), "%.0f", id(a_tds).state);
      - id: page2
        lambda: |-
          it.printf(1, 0, id(font3), "Up:%.0f°", id(a_temp1).state);
          it.printf(81, 0, id(font3), "Dn:%.0f°", id(a_temp2).state);
          it.graph(0, 14, id(multi_temperature_graph));
          it.line(47, 7, 57, 7);
          it.line(67, 7, 71, 7);
          it.line(75, 7, 79, 7);
      - id: page3
        lambda: |-
          it.printf(1, 0, id(font3), "TDS: %.0f", id(atds).state);
          it.graph(0, 14, id(tds_graph));

# For example cycle through pages on a timer
interval:
  - interval: 10s
    then:
      - display.page.show_next: my_display
      - component.update: my_display
```

### Anything in the logs that might be useful for us?

```txt
In file included from src/esphome/components/esp32_touch/esp32_touch.h:11,
                 from src/esphome/components/esp32_touch/esp32_touch_common.cpp:3:
/data/cache/platformio/packages/framework-espidf/components/driver/touch_sensor/esp32/include/driver/touch_sensor.h:13:2: warning: #warning "This set of Touch APIs has been deprecated, please include 'driver/touch_sens.h' instead. if you want to keep using the old APIs and ignore this warning, you can enable 'Suppress legacy driver deprecated warning' option under 'Touch Configuration' menu in Kconfig" [-Wcpp]
   13 | #warning "This set of Touch APIs has been deprecated, \
      |  ^~~~~~~
Compiling .pioenvs/f
```

### Additional information

_No response_

### PR DESCRIPTION
**Pull request by swoboda1337**
# What does this implement/fix?

Migrate the `esp32_touch` component from the deprecated `driver/touch_sensor.h` API to the new unified `driver/touch_sens.h` (`esp_driver_touch_sens`) API introduced in ESP-IDF v5.5.

**Key changes:**
- Eliminates deprecation warnings when building with ESP-IDF v5.5+
- Adds ESP32-P4 touch pad support (new V3 hardware)
- Consolidates three separate implementation files (`esp32_touch_v1.cpp`, `esp32_touch_v2.cpp`, `esp32_touch_common.cpp`) into a single unified `esp32_touch.cpp` using targeted `#ifdef` blocks for the small variant-specific differences
- Updates all enum/type names to new API equivalents (e.g., `TOUCH_LVOLT_0V5` → `TOUCH_VOLT_LIM_L_0V5`)
- Uses unified callback mechanism (`on_active`/`on_inactive`) instead of raw ISR handlers
- Touch pad pins are now mapped to integer channel IDs instead of `TOUCH_PAD_NUMx` enums
- `voltage_attenuation` is now properly supported on ESP32 V1 via the new combined `touch_volt_lim_h_t` enum (which encodes both high voltage reference and attenuation)

The new API uses the same lifecycle across all variants: `touch_sensor_new_controller` → `touch_sensor_new_channel` → `touch_sensor_config_filter` → `touch_sensor_register_callbacks` → `touch_sensor_enable` → `touch_sensor_start_continuous_scanning`.

## Types of changes

- [ ] Bugfix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] Developer breaking change (an API change that could break external components)
- [ ] Code quality improvements to existing code or addition of tests
- [ ] Other

**Related issue or feature (if applicable):**

- fixes https://github.com/esphome/esphome/issues/12323

**Pull request in [esphome-docs](https://github.com/esphome/esphome-docs) with documentation (if applicable):**

- esphome/esphome-docs#6104

## Test Environment

- [x] ESP32
- [x] ESP32 IDF
- [ ] ESP8266
- [ ] RP2040
- [ ] BK72xx
- [ ] RTL87xx
- [ ] LN882x
- [ ] nRF52840

## Example entry for `config.yaml`:

```yaml
# Existing configs work unchanged
esp32_touch:
  setup_mode: false

binary_sensor:
  - platform: esp32_touch
    name: "Touch Pad"
    pin: GPIO4
    threshold: 1000

# ESP32-P4 is now also supported
# (GPIO 2-15 map to touch channels 1-14)
```

## Checklist:
  - [x] The code change is tested and works locally.
  - [x] Tests have been added to verify that the new code works (under `tests/` folder).

If user exposed functionality or configuration variables are added/changed:
  - [x] Documentation added/updated in [esphome-docs](https://github.com/esphome/esphome-docs).

### CODE REVIEW

**Comment by bdraco** [comment]
Do we need to wait for 5.5.3 to test?

I can test when I'm back in Hawaii and the end of next week and I have the hardware setup for v1/v2

**Comment by swoboda1337** [comment]
> Do we need to wait for 5.5.3 to test?
> 
> I can test when I'm back in Hawaii and the end of next week and I have the hardware setup for v1/v2

You only need 5.5.3 if you want to test pins 32 or 33 on the original esp32. Those pins have a hw bug and require the driver to swap. There is a bug in 5.5.2 where it doesnt swap in the enable api but it only affects those two pins on that variant. 

I tested pin 33 with 260206 and it is fixed:
```
esp32:
  variant: esp32
  framework:
    type: esp-idf
    release: "260206"
```

File: esphome/components/esp32_touch/esp32_touch.h
Comment (bdraco) [inline esphome/components/esp32_touch/esp32_touch.h]: nit: could mark as final

File: esphome/components/esp32_touch/esp32_touch.h [hunk 1]
```diff
@@ -4,28 +4,25 @@
...
-// - ESP32-S2/S3 v2: Hardware supports both touch and release interrupts, but release
-//   interrupts are unreliable and sometimes don't fire. We now only use touch interrupts
-//   and detect releases via timeout, similar to v1.
+// CALLBACK BEHAVIOR:
+// - ESP32 v1: on_active/on_inactive fire from a software filter timer (esp_timer context).
+//   The software filter MUST be configured for these callbacks to fire.
+// - ESP32-S2/S3 v2, ESP32-P4 v3: on_active/on_inactive fire from hardware ISR context.
+//   Release detection via on_inactive is used, with timeout as safety fallback.
 
 static const uint32_t SETUP_MODE_LOG_INTERVAL_MS = 250;
```
Comment (bdraco) [inline esphome/components/esp32_touch/esp32_touch.h]:
```suggestion
static constexpr uint32_t SETUP_MODE_LOG_INTERVAL_MS = 250;
```

File: esphome/components/esp32_touch/esp32_touch.cpp [hunk 2]
```diff
@@ -0,0 +1,547 @@
...
+        guard_chan = child->chan_handle_;
+        break;
+      }
+    }
+
+    touch_channel_handle_t shield_chan = nullptr;
+    touch_channel_config_t shield_cfg = {};
+#ifdef USE_ESP32_VARIANT_ESP32P4
+    shield_cfg.active_thresh[0] = 0;
+    err = touch_sensor_new_channel(this->sens_handle_, 14, &shield_cfg, &shield_chan);
```
Comment (bdraco) [inline esphome/components/esp32_touch/esp32_touch.cpp]: nit: hard coded value should be constexpr

File: esphome/components/esp32_touch/esp32_touch.cpp [hunk 3]
```diff
@@ -0,0 +1,547 @@
...
+
+  err = touch_sensor_start_continuous_scanning(this->sens_handle_);
+  if (err != ESP_OK) {
+    ESP_LOGE(TAG, "Failed to start continuous scanning: %s", esp_err_to_name(err));
+    this->mark_failed();
+    return;
+  }
+
+  // Set release timeout as safety fallback
+  this->release_timeout_ms_ = 1500;
```
Comment (bdraco) [inline esphome/components/esp32_touch/esp32_touch.cpp]: nit: 1500 should be constexpr

Comment (bdraco) [inline esphome/components/esp32_touch/esp32_touch.cpp]: Its set to release_timeout_ms_ in the .h as well.  It looks like there is no way this value is ever set to anything else ?

File: esphome/components/esp32_touch/esp32_touch.cpp [hunk 4]
```diff
@@ -0,0 +1,547 @@
...
+  if (!this->create_touch_queue_()) {
+    return;
+  }
+
+  // Create sample config - differs per hardware version
+#ifdef USE_ESP32_VARIANT_ESP32
+  touch_sensor_sample_config_t sample_cfg = TOUCH_SENSOR_V1_DEFAULT_SAMPLE_CONFIG(
+      this->charge_duration_ms_, this->low_voltage_reference_, this->high_voltage_reference_);
+#elif defined(USE_ESP32_VARIANT_ESP32P4)
+  touch_sensor_sample_config_t sample_cfg = TOUCH_SENSOR_V3_DEFAULT_SAMPLE_CONFIG(8, 2, 2);
```
Comment (bdraco) [inline esphome/components/esp32_touch/esp32_touch.cpp:58]: nit: hard coded magic numbers..

File: esphome/components/esp32_touch/esp32_touch.cpp [hunk 5]
```diff
@@ -0,0 +1,547 @@
...
+  if (err != ESP_OK) {
+    ESP_LOGE(TAG, "Failed to enable touch sensor: %s", esp_err_to_name(err));
+    this->cleanup_touch_queue_();
+    this->mark_failed();
+    return;
+  }
+
+  // Do initial oneshot scans to populate baseline values
+  for (int i = 0; i < 3; i++) {
+    touch_sensor_trigger_oneshot_scanning(this->sens_handle_, 2000);
```
Comment (bdraco) [inline esphome/components/esp32_touch/esp32_touch.cpp]: nit: hard coded magic numbers

File: esphome/components/esp32_touch/__init__.py [hunk 6]
```diff
@@ -260,51 +293,74 @@ def validator(value):
...
-    cg.add(
-        touch.set_voltage_attenuation(
-            VOLTAGE_ATTENUATION[config[CONF_VOLTAGE_ATTENUATION]]
+        cg.add(touch.set_charge_duration_ms(charge_duration_ms))
+    else:
+        # V2/V3: charge_times (approximate conversion from duration)
+        # The old API used clock cycles; the new API uses charge_times count.
+        # Default is 500 for V2/V3. Use measurement_duration as a rough scaling factor.
+        charge_times = int(
+            round(config[CONF_MEASUREMENT_DURATION].total_microseconds * 7.99987793)
```
Comment (bdraco) [inline esphome/components/esp32_touch/__init__.py]: magic number looks like its 65535 / 8192

File: esphome/components/esp32_touch/esp32_touch.cpp (hunk 5 above)
Comment (bdraco) [inline esphome/components/esp32_touch/esp32_touch.cpp]: no error check here

File: esphome/components/esp32_touch/esp32_touch.cpp (hunk 3 above)
Comment (bdraco) [reply esphome/components/esp32_touch/esp32_touch.cpp]: this used to be
`uint32_t rtc_freq = rtc_clk_slow_freq_get_hz(); `
`this->release_timeout_ms_ = (this->sleep_cycle_ * 1000 * 3) / rtc_freq;`

Now its hard coded?

Comment (bdraco) [reply esphome/components/esp32_touch/esp32_touch.cpp]: ok so hard code is intentional. We just need to cleanup the dead code

**Comment by bdraco** [comment]
Possible bug with V1

I held GPIO4 and it stil turned off Pad 'Touch Pad GPIO4' (Ch0): 727                                                                                                           


```
  [15:21:10.129][D][esp32_touch:505]: Touch Pad 'Touch Pad GPIO14' (Ch6): 757                                                                                                                           
  [15:21:10.381][D][esp32_touch:505]: Touch Pad 'Touch Pad GPIO4' (Ch0): 728                                                                                                                            
  [15:21:10.384][D][esp32_touch:505]: Touch Pad 'Touch Pad GPIO14' (Ch6): 758                                                                                                                       
  [15:21:10.638][D][esp32_touch:505]: Touch Pad 'Touch Pad GPIO4' (Ch0): 518                                                                                                                        
  [15:21:10.641][D][esp32_touch:505]: Touch Pad 'Touch Pad GPIO14' (Ch6): 757                                                                                                                       
  [15:21:10.644][D][binary_sensor:048]: 'Touch Pad GPIO4' >> ON                                                                                                                                     
  [15:21:10.895][D][esp32_touch:505]: Touch Pad 'Touch Pad GPIO4' (Ch0): 23                                                                                                                         
  [15:21:10.898][D][esp32_touch:505]: Touch Pad 'Touch Pad GPIO14' (Ch6): 757                                                                                                                       
  [15:21:11.147][D][esp32_touch:505]: Touch Pad 'Touch Pad GPIO4' (Ch0): 1                                                                                                                          
  [15:21:11.150][D][esp32_touch:505]: Touch Pad 'Touch Pad GPIO14' (Ch6): 757                                                                                                                       
  [15:21:11.401][D][esp32_touch:505]: Touch Pad 'Touch Pad GPIO4' (Ch0): 2                                                                                                                          
  [15:21:11.404][D][esp32_touch:505]: Touch Pad 'Touch Pad GPIO14' (Ch6): 757                                                                                                                       
  [15:21:11.656][D][esp32_touch:505]: Touch Pad 'Touch Pad GPIO4' (Ch0): 1                                                                                                                          
  [15:21:11.659][D][esp32_touch:505]: Touch Pad 'Touch Pad GPIO14' (Ch6): 758                                                                                                                       
  [15:21:11.913][D][esp32_touch:505]: Touch Pad 'Touch Pad GPIO4' (Ch0): 2                                                                                                                          
  [15:21:11.916][D][esp32_touch:505]: Touch Pad 'Touch Pad GPIO14' (Ch6): 757                                                                                                                       
  [15:21:12.164][D][esp32_touch:505]: Touch Pad 'Touch Pad GPIO4' (Ch0): 3                                                                                                                          
  [15:21:12.167][D][esp32_touch:505]: Touch Pad 'Touch Pad GPIO14' (Ch6): 757                                                                                                                       
  [15:21:12.254][D][binary_sensor:048]: 'Touch Pad GPIO4' >> OFF                                                                                                                                    
  [15:21:12.417][D][esp32_touch:505]: Touch Pad 'Touch Pad GPIO4' (Ch0): 3                                                                                                                          
  [15:21:12.420][D][esp32_touch:505]: Touch Pad 'Touch Pad GPIO14' (Ch6): 757                                                                                                                       
  [15:21:12.669][D][esp32_touch:505]: Touch Pad 'Touch Pad GPIO4' (Ch0): 3                                                                                                                          
  [15:21:12.672][D][esp32_touch:505]: Touch Pad 'Touch Pad GPIO14' (Ch6): 757                                                                                                                       
  [15:21:12.933][D][esp32_touch:505]: Touch Pad 'Touch Pad GPIO4' (Ch0): 3                                                                                                                          
  [15:21:12.937][D][esp32_touch:505]: Touch Pad 'Touch Pad GPIO14' (Ch6): 758                                                                                                                       
  [15:21:13.186][D][esp32_touch:505]: Touch Pad 'Touch Pad GPIO4' (Ch0): 3              
```

**Comment by bdraco** [comment]
v2 has a check .. .maybe we need it for v1 now

**Comment by bdraco** [comment]
confirmed dev is not affected so this is a v1 regression

**Comment by bdraco** [comment]
The old V1 ISR (`touch_isr_handler`) fired periodically while any pad was touched, scanning all pads each cycle and sending events that kept `last_touch_time_` refreshed.

It looks likke the new unified API's `on_active_cb` only fires once on the state transition, so `last_touch_time_` is never refreshed while held. This causes the release timeout to fire after 1.5s even though the pad is clearly still being touched (value 1-3 vs baseline ~728).

Tested on ESP32-POE-ISO with GPIO4: touch detected correctly, but after 1.5s the binary sensor reports OFF while the pad value remains at 1-3 (still held). This does not happen on dev with the old driver.

V2/V3 already has a verification read before releasing. V1 needs the same, with the appropriate inverted comparison (`value < threshold` instead of `value > benchmark + threshold`):

```cpp
if (time_diff > this->release_timeout_ms_) {
#ifdef USE_ESP32_VARIANT_ESP32
        // V1: Verify actual state before declaring release
        uint32_t value = 0;
        touch_channel_read_data(child->chan_handle_, TOUCH_CHAN_DATA_TYPE_SMOOTH, &value);
        child->value_ = value;
        if (value < child->get_threshold()) {
          // Still touched - reset timer
          child->last_touch_time_ = now;
          continue;
        }
#else
        // V2/V3: existing verification...
```

But we need to make sure `touch_channel_read_data` isn't blocking....

**Comment by bdraco** [comment]
TOUCH_CHAN_DATA_TYPE_RAW would be a problem but TOUCH_CHAN_DATA_TYPE_SMOOTH looks safe and non-blocking

**Comment by bdraco** [comment]
ok thats all the v1 testing. Switching to esp32s3 now to test

**Comment by bdraco** [comment]
v2/v3 looks good

## Test Setup

### ESP32 V1 (Olimex ESP32-POE-ISO)

```yaml
esp32:
  board: esp32-poe-iso
  framework:
    type: esp-idf

esp32_touch:
  setup_mode: true
  iir_filter: 10ms

binary_sensor:
  - platform: esp32_touch
    name: Touch Pad GPIO4
    pin: GPIO4
    threshold: 600
  - platform: esp32_touch
    name: Touch Pad GPIO14
    pin: GPIO14
    threshold: 600
```

**Result:** Touch detection works, but holding a pad for >1.5s causes a false release while the pad is still clearly touched (value 1-3 vs baseline ~728). This is because `on_active_cb` only fires once on the state transition, unlike the old ISR which fired periodically while held. The release timeout expires without `last_touch_time_` being refreshed. V2/V3 has a verification read before releasing (`esp32_touch.cpp:377-391`) but V1 is missing it.

### ESP32-S3 V2 (XIAO ESP32S3)

```yaml
esp32:
  board: esp32-s3-devkitc-1
  framework:
    type: esp-idf

esp32_touch:
  measurement_duration: 50us
  denoise_grade: BIT12
  denoise_cap_level: L0
  debounce_count: 1
  filter_mode: IIR_16
  noise_threshold: 0
  jitter_step: 0
  smooth_mode: IIR_2

binary_sensor:
  - platform: esp32_touch
    name: "Touch D3"
    pin: GPIO4
    threshold: 96600
  - platform: esp32_touch
    name: "Touch D4"
    pin: GPIO5
    threshold: 93600
  - platform: esp32_touch
    name: "Touch D5"
    pin: GPIO6
    threshold: 94800
  - platform: esp32_touch
    name: "Touch D9"
    pin: GPIO8
    threshold: 100000
```

**Result:** Works correctly. Touch and release both detected reliably, including sustained holds.

**Review by bdraco — DISMISSED** [review]

**Comment by bdraco** [comment]
retested with esp32 classic and esp32s3

Could not get it to fail with the check removed

**Review by bdraco — APPROVED** [review]

**Comment by bdraco** [comment]
Tried very hard to get it to fail, all working as expected so I merged it
