### PR TITLE
[fix] ESP32-C6: internal temperature reporting

### LINKED ISSUE #5687: Enable ESP32c6 to display chip temperature correctly, it is currently unable to display
### The problem

Enable ESP32c6 to display chip temp

erature correctly, it is currently unable to display

IDF document：https://docs.espressif.com/projects/esp-idf/en/latest/esp32c6/api-reference/peripherals/temp_sensor.html

### Which version of ESPHome has the issue?

2024.3.2

### What type of installation are you using?

Docker

### Which version of Home Assistant has the issue?

_No response_

### What platform are you using?

ESP32-IDF

### Board

ESP32C6

### Component causing the issue

internal_temperature

### Example YAML snippet

```yaml
- platform: internal_temperature
    name: ${node_internal_temperature_name}
    update_interval: 60s
```

### Anything in the logs that might be useful for us?

_No response_

### Additional information

_No response_

### PR DESCRIPTION
**Pull request by rvalitov**
# What does this implement/fix?

ESP32-C6 does not report internal temperature. This PR fixes it.

## Types of changes

- [x] Bugfix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] Other

**Related issue or feature (if applicable):** fixes https://github.com/esphome/issues/issues/5687

**Pull request in [esphome-docs](https://github.com/esphome/esphome-docs) with documentation (if applicable):** esphome/esphome-docs#<esphome-docs PR number goes here>

## Test Environment

- [ ] ESP32
- [x] ESP32 IDF
- [ ] ESP8266
- [ ] RP2040
- [ ] BK72xx
- [ ] RTL87xx

## Example entry for `config.yaml`:

```yaml
# Example config.yaml
esphome:
  name: bt-proxy
  friendly_name: Bluetooth Proxy
  platformio_options:
    board_build.flash_mode: dio 

esp32:
  board: esp32-c6-devkitc-1
  variant: ESP32C6
  flash_size: 8MB
  framework:
    type: esp-idf
    version: 5.3.1
    platform_version: 6.9.0
    sdkconfig_options:
      CONFIG_ESPTOOLPY_FLASHSIZE_8MB: y
      CONFIG_OPENTHREAD_ENABLED: n
      CONFIG_ENABLE_WIFI_STATION: y
      CONFIG_USE_MINIMAL_MDNS: y

wifi:
  ssid: "secret"
  password: "secret"

sensor:
  - platform: internal_temperature
    id: esp_internal_temperature
    name: "Internal Temperature"
```

## Checklist:
  - [x] The code change is tested and works locally.
  - [ ] Tests have been added to verify that the new code works (under `tests/` folder).

If user exposed functionality or configuration variables are added/changed:
  - [ ] Documentation added/updated in [esphome-docs](https://github.com/esphome/esphome-docs).

### CODE REVIEW

File: esphome/components/internal_temperature/internal_temperature.cpp [hunk 1]
```diff
@@ -34,13 +35,18 @@ void InternalTemperatureSensor::update() {
...
   temp_sensor_config_t tsens = TSENS_CONFIG_DEFAULT();
   temp_sensor_set_config(tsens);
   temp_sensor_start();
 #if defined(USE_ESP32_VARIANT_ESP32S3) && (ESP_IDF_VERSION < ESP_IDF_VERSION_VAL(4, 4, 3))
 #error \
     "ESP32-S3 internal temperature sensor requires ESP IDF V4.4.3 or higher. See https://github.com/esphome/issues/issues/4271"
+#endif
+#if defined(USE_ESP32_VARIANT_ESP32C6) && (ESP_IDF_VERSION < ESP_IDF_VERSION_VAL(5, 1, 0))
+#error \
+    "ESP32-C6 requires ESP IDF V5.1.0 or higher. See https://github.com/espressif/esp-idf?tab=readme-ov-file#esp-idf-release-and-soc-compatibility"
```
Comment (jesserockz) [inline esphome/components/internal_temperature/internal_temperature.cpp]: This doesn't belong here and has nothing to do with this sensor. The entire project won't compile if not using a high enough version.
```suggestion
```

**Review by jesserockz — CHANGES_REQUESTED** [review]

File: esphome/components/internal_temperature/internal_temperature.cpp (hunk 1 above)
Comment (rvalitov) [reply esphome/components/internal_temperature/internal_temperature.cpp]: Thank you for the review! I just followed the style and approach in the code for ESP-S3 where there's a check for ESP IDF version. Ok, if you think such check is not required for ESP32-C6, I remove it.

**Review by Mat931 — APPROVED** [review]

**Review by jesserockz — APPROVED** [review]
