### PR TITLE
[nrf52,ssd1306_i2c] fix build error

### LINKED ISSUE #11662: [nrf52] components/display/display.cpp:46:40: error: 'M_PI' was not declared in this scope
### The problem

Hi,

I am getting an error building the display (ssd_1306_i2c) componant for nRF52 platform: 
```
/data/build/xiao-nrf52-i2c/src/esphome/components/display/display.cpp: In member function 'void esphome::display::Display::line_at_angle(int, int, int, int, int, esphome::Color)':
/data/build/xiao-nrf52-i2c/src/esphome/components/display/display.cpp:46:40: error: 'M_PI' was not declared in this scope
   46 |   int x1 = (start_radius * cos(angle * M_PI / 180)) + x;
      |                                        ^~~~
```

It seems to be caused by this:
`It means that M_PI (the constant for π) isn’t defined by default in your environment — this often happens with C++20, Zephyr, or embedded toolchains that use newlib or libc variants that don’t expose math constants unless explicitly requested.`

### Which version of ESPHome has the issue?

2025.11.0-dev

### What type of installation are you using?

Home Assistant Add-on

### What platform are you using?

nrf52

### Component causing the issue

display

### YAML Config

```yaml
esphome:
  name: xiao-nrf52-i2c
  friendly_name: XIAO nRF52 I2C

nrf52:
  board: xiao_ble

logger:
  level: VERY_VERBOSE

external_components:
    # i2c
  - source: github://pr#8150
    components: [i2c]
    refresh: 1h

i2c:
  - sda: P0.04
    scl: P0.05

font:
  # gfonts://family[@weight]
- file: "gfonts://Roboto"
  id: roboto_10
  size: 10

display:
  - platform: ssd1306_i2c
    model: "SSD1306 128x64"
    address: 0x3C
    lambda: |-
      it.print(0, 0, id(roboto_10), "Hello World!");

```

### Anything in the logs that might be useful for us?

```txt
[11/214] Building CXX object CMakeFiles/app.dir/data/build/xiao-nrf52-i2c/src/esphome/components/display/display.cpp.obj
FAILED: CMakeFiles/app.dir/data/build/xiao-nrf52-i2c/src/esphome/components/display/display.cpp.obj 
/data/cache/platformio/packages/toolchain-gccarmnoneeabi/zephyr-sdk-0.17.4/arm-zephyr-eabi/bin/arm-zephyr-eabi-g++ -DKERNEL -DNRF52840_XXAA -D_ANSI_SOURCE -D_FORTIFY_SOURCE=1 -D__LINUX_ERRNO_EXTENSIONS__ -D__PROGRAM_START -D__ZEPHYR__=1 -I/data/build/xiao-nrf52-i2c/zephyr/../src -I/data/cache/platformio/packages/framework-zephyr/zephyr/include -I/data/build/xiao-nrf52-i2c/.pioenvs/xiao-nrf52-i2c/zephyr/include/generated -I/data/cache/platformio/packages/framework-zephyr/zephyr/soc/arm/nordic_nrf/nrf52 -I/data/cache/platformio/packages/framework-zephyr/zephyr/lib/libc/newlib/include -I/data/cache/platformio/packages/framework-zephyr/zephyr/soc/common/nordic_nrf/. -I/data/cache/platformio/packages/framework-zephyr/zephyr/soc/arm/nordic_nrf/common/. -I/data/cache/platformio/packages/framework-zephyr/zephyr/subsys/usb/device -I/data/cache/platformio/packages/framework-zephyr/zephyr/subsys/settings/include -I/data/cache/platformio/packages/framework-zephyr/zephyr/drivers/usb/common/nrf_usbd_common/. -I/data/cache/platformio/packages/framework-zephyr/nrf/include -I/data/cache/platformio/packages/framework-zephyr/nrf/tests/include -I/data/cache/platformio/packages/framework-zephyr/modules/hal/cmsis/CMSIS/Core/Include -I/data/cache/platformio/packages/framework-zephyr/zephyr/modules/cmsis/. -I/data/cache/platformio/packages/framework-zephyr/modules/hal/nordic/nrfx -I/data/cache/platformio/packages/framework-zephyr/modules/hal/nordic/nrfx/drivers/include -I/data/cache/platformio/packages/framework-zephyr/modules/hal/nordic/nrfx/mdk -I/data/cache/platformio/packages/framework-zephyr/zephyr/modules/hal_nordic/nrfx/. -isystem /data/cache/platformio/packages/framework-zephyr/zephyr/lib/libc/common/include -isystem /data/cache/platformio/packages/framework-zephyr/nrfxlib/crypto/nrf_cc310_platform/include -DESPHOME_LOG_LEVEL=ESPHOME_LOG_LEVEL_VERY_VERBOSE -DUSE_NRF52 -DUSE_ZEPHYR -Wno-sign-compare -Wno-unused-but-set-variable -Wno-unused-variable -fno-exceptions -std=gnu++20 -fno-strict-aliasing -Os -fcheck-new -std=c++20 -Wno-register -Wno-volatile -fno-exceptions -fno-rtti -imacros /data/build/xiao-nrf52-i2c/.pioenvs/xiao-nrf52-i2c/zephyr/include/generated/autoconf.h -fno-common -g -gdwarf-4 -fdiagnostics-color=always -mcpu=cortex-m4 -mthumb -mabi=aapcs -mfpu=fpv4-sp-d16 -mfloat-abi=hard -mfp16-format=ieee --sysroot=/data/cache/platformio/packages/toolchain-gccarmnoneeabi/zephyr-sdk-0.17.4/arm-zephyr-eabi/arm-zephyr-eabi -imacros /data/cache/platformio/packages/framework-zephyr/zephyr/include/zephyr/toolchain/zephyr_stdint.h -Wall -Wformat -Wformat-security -Wno-format-zero-length -Wpointer-arith -Wexpansion-to-defined -Wno-unused-but-set-variable -fno-pic -fno-pie -fno-asynchronous-unwind-tables -fno-reorder-functions --param=min-pagesize=0 -fno-defer-pop -fmacro-prefix-map=/data/build/xiao-nrf52-i2c/zephyr=CMAKE_SOURCE_DIR -fmacro-prefix-map=/data/cache/platformio/packages/framework-zephyr/zephyr=ZEPHYR_BASE -fmacro-prefix-map=/data/cache/platformio/packages/framework-zephyr=WEST_TOPDIR -ffunction-sections -fdata-sections -specs=nano.specs -MD -MT CMakeFiles/app.dir/data/build/xiao-nrf52-i2c/src/esphome/components/display/display.cpp.obj -MF CMakeFiles/app.dir/data/build/xiao-nrf52-i2c/src/esphome/components/display/display.cpp.obj.d -o CMakeFiles/app.dir/data/build/xiao-nrf52-i2c/src/esphome/components/display/display.cpp.obj -c /data/build/xiao-nrf52-i2c/src/esphome/components/display/display.cpp
/data/build/xiao-nrf52-i2c/src/esphome/components/display/display.cpp: In member function 'void esphome::display::Display::line_at_angle(int, int, int, int, int, esphome::Color)':
/data/build/xiao-nrf52-i2c/src/esphome/components/display/display.cpp:46:40: error: 'M_PI' was not declared in this scope
   46 |   int x1 = (start_radius * cos(angle * M_PI / 180)) + x;
      |                                        ^~~~
/data/build/xiao-nrf52-i2c/src/esphome/components/display/display.cpp: In member function 'void esphome::display::Display::filled_gauge(int, int, int, int, int, esphome::Color)':
/data/build/xiao-nrf52-i2c/src/esphome/components/display/display.cpp:225:71: error: 'M_PI' was not declared in this scope
  225 |   float tan_a = (progress == 50) ? 65535 : tan(float(draw_progress) * M_PI / 100);  // slope
      |                                                                       ^~~~
[12/214] Building CXX object CMakeFiles/app.dir/data/build/xiao-nrf52-i2c/src/esphome/components/display/rect.cpp.obj
[13/214] Building CXX object CMakeFiles/app.dir/data/build/xiao-nrf52-i2c/src/esphome/components/i2c/i2c.cpp.obj
[14/214] Building CXX object CMakeFiles/app.dir/data/build/xiao-nrf52-i2c/src/esphome/components/font/font.cpp.obj
[15/214] Building CXX object CMakeFiles/app.dir/data/build/xiao-nrf52-i2c/src/esphome/components/display/display_buffer.cpp.obj
[16/214] Building CXX object CMakeFiles/app.dir/data/build/xiao-nrf52-i2c/src/esphome/components/aht10/aht10.cpp.obj
ninja: build stopped: subcommand failed.
*** Error 1
```

### Additional information

[logs_xiao-nrf52-i2c_compile (3).txt](https://github.com/user-attachments/files/23286581/logs_xiao-nrf52-i2c_compile.3.txt)

### PR DESCRIPTION
**Pull request by tomaszduda23**
# What does this implement/fix?

zephyr do not define M_PI

## Types of changes

- [x] Bugfix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] Code quality improvements to existing code or addition of tests
- [ ] Other

**Related issue or feature (if applicable):**

- fixes https://github.com/esphome/esphome/issues/11662

**Pull request in [esphome-docs](https://github.com/esphome/esphome-docs) with documentation (if applicable):**

- esphome/esphome-docs#<esphome-docs PR number goes here>

## Test Environment

- [ ] ESP32
- [ ] ESP32 IDF
- [ ] ESP8266
- [ ] RP2040
- [ ] BK72xx
- [ ] RTL87xx
- [x] nRF52840

## Example entry for `config.yaml`:

```yaml
# Example config.yaml

```

## Checklist:
  - [ ] The code change is tested and works locally.
  - [x] Tests have been added to verify that the new code works (under `tests/` folder).

If user exposed functionality or configuration variables are added/changed:
  - [ ] Documentation added/updated in [esphome-docs](https://github.com/esphome/esphome-docs).

### CODE REVIEW

File: esphome/core/helpers.h [hunk 1]
```diff
@@ -45,6 +45,10 @@
 #define ESPHOME_ALWAYS_INLINE __attribute__((always_inline))
 #define PACKED __attribute__((packed))
 
+#ifdef USE_ZEPHYR
+#define M_PI 3.14159265358979323846
+#endif
```
Comment (bdraco) [inline esphome/core/helpers.h]: maybe this should be in macros.h ?

Comment (tomaszduda23) [reply esphome/core/helpers.h]: done

**Review by bdraco — APPROVED** [review]

**Comment by bdraco** [comment]
Thanks @tomaszduda23
