### PR TITLE
[script] Fix parallel mode scripts with delays cancelling each other

### LINKED ISSUE #10264: Scripts with delay no longer run concurrently in parallel mode from 2025.7.2
### The problem

Calls to ESPHOME script in parrallel mode appear to terminate currently runing script instance(s) . In the example script below the log message "Script Ended" is never actioned in 2025.7.2 but in 2025.7.1 it is successful

Maybe related to the change implemented in 2025.7.2 https://github.com/esphome/esphome/pull/9646 

### Which version of ESPHome has the issue?

2025.7.2

### What type of installation are you using?

Docker

### What platform are you using?

ESP8266

### Component causing the issue

_No response_

### YAML Config

```yaml

esphome:
  name: dev-environment
  friendly_name: Dev-environment

esp8266:
  board: esp01_1m

# Enable logging
logger:

# Enable Home Assistant API
api:
  encryption:
    key: "CW692JTlqWjuCmm/322JyoDxhiMi07YhjqFWCxZ3A7A="

ota:
  - platform: esphome
    password: "3cb67d8a286e245ccc366ec952f8df09"

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password

  # Enable fallback hotspot (captive portal) in case wifi connection fails
  ap:
    ssid: "Dev-Environment Fallback Hotspot"
    password: "4TqZIXqJiNKA"

captive_portal:

#The log message "Script Ended" will not execute in 2025.7.2 onwards
script:
  - id: test_parallel_exec_with_delay
    mode: parallel
    then:
      - lambda: !lambda |-
          ESP_LOGI("SCRIPT","Script Started");
      - delay: 15 sec
      - lambda: !lambda |-
          ESP_LOGI("SCRIPT","Script Ended");

interval:
  - interval: 10 sec
    then:
      - script.execute: test_parallel_exec_with_delay

    
```

### Anything in the logs that might be useful for us?

```txt

```

### Additional information

_No response_

### PR DESCRIPTION
**Pull request by bdraco**
# What does this implement/fix?

This PR fixes an issue where delays in parallel mode scripts were interfering with each other, causing them to terminate early. The problem was introduced when PR #9646 changed `DelayAction` to use named timeouts (from empty string to "delay"). Since actions are singletons shared across all script instances, parallel scripts were cancelling each other's delays when they called `set_timeout()` with the same name.

The fix detects when `DelayAction` is running in parallel mode (by checking `num_running_ > 1`) and uses a special non-cancelling timeout mechanism to allow multiple delays to coexist. This is implemented through a friend class relationship to avoid exposing dangerous functionality in the public API.

## Types of changes

- [x] Bugfix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [x] Code quality improvements to existing code or addition of tests
- [ ] Other

**Related issue or feature (if applicable):**

- fixes #10264

**Pull request in [esphome-docs](https://github.com/esphome/esphome-docs) with documentation (if applicable):**

- N/A (internal implementation detail, no user-facing changes)

## Test Environment

- [ ] ESP32
- [ ] ESP32 IDF
- [ ] ESP8266
- [ ] RP2040
- [ ] BK72xx
- [ ] RTL87xx
- [ ] nRF52840

**Note:** Integration tests were run on the host platform (native). The fix is platform-independent as it only affects the timing/scheduling logic in the core automation system.

## Example entry for `config.yaml`:

```yaml
# Example demonstrating parallel scripts with delays that now work correctly
script:
  - id: my_parallel_script
    mode: parallel
    max_runs: 3  # Recommended to limit concurrent executions
    then:
      - logger.log: "Script instance started"
      - delay: 5s
      - logger.log: "Script instance completed after delay"

# This will now correctly run 3 instances in parallel,
# each with their own 5-second delay
api:
  actions:
    - action: test_parallel
      then:
        - script.execute: my_parallel_script
        - delay: 100ms
        - script.execute: my_parallel_script
        - delay: 100ms
        - script.execute: my_parallel_script
```

## Checklist:
  - [x] The code change is tested and works locally.
  - [x] Tests have been added to verify that the new code works (under `tests/` folder).

If user exposed functionality or configuration variables are added/changed:
  - [ ] Documentation added/updated in [esphome-docs](https://github.com/esphome/esphome-docs).

## Additional Notes

- Added integration tests for both parallel and restart modes to ensure the fix doesn't break existing functionality
- The implementation uses `DelayAction` as a friend class of `Scheduler` to access the internal `set_timer_common_` method with `skip_cancel=true`
- This approach was chosen to avoid exposing a dangerous public API that could lead to scheduler overload if misused
- Users should use `max_runs` on parallel scripts to prevent unbounded delay accumulation

### CODE REVIEW

File: esphome/core/scheduler.cpp [hunk 1]
```diff
@@ -166,6 +173,7 @@ void HOT Scheduler::set_timeout(Component *component, const std::string &name, u
                                 std::function<void()> func) {
   this->set_timer_common_(component, SchedulerItem::TIMEOUT, false, &name, timeout, std::move(func));
 }
+
```
Comment (bdraco) [inline esphome/core/scheduler.cpp]:
```suggestion
```

**Review by jesserockz — APPROVED** [review]
