### PR TITLE
Break the Tuya set_datapoint_value method into separate methods per datapoint type

### LINKED ISSUE #2149: Tuya datapoint is not expected size / unknown datapoint error
**Operating environment/Installation (Hass.io/Docker/pip/etc.):**

Hass.io

**ESP (ESP32/ESP8266, Board/Sonoff):**

```yaml
  platform: ESP8266
  board: esp01_1m
```

**ESPHome version (latest production, beta, dev branch)**

1.19.0

**Affected component:**

https://esphome.io/components/tuya.html
https://esphome.io/components/fan/tuya.html

**Description of problem:**

3rd party Tuya based fan, flashed with ESPHome.

Following available datapoints in log:
```
[19:29:37][C][tuya:026]: Tuya:
[19:29:37][C][tuya:037]:   Datapoint 1: switch (value: ON)
[19:29:37][C][tuya:043]:   Datapoint 2: enum (value: 0)
[19:29:37][C][tuya:043]:   Datapoint 4: enum (value: 0)
[19:29:37][C][tuya:043]:   Datapoint 5: enum (value: 0)
```
With 1.18 I was able to control the fan speed on (the not listed) Datapoint 3. 

Now with 1.19.0 changing fan speed is not possible anymore on Datapoint 3. Changing speed from within HA results in the ESPHome error:
```
[19:33:28][E][tuya:405]: Attempt to set unknown datapoint 3
```

Still can control the fan speed with the remote that comes with the device, but that also gives an ESPHome warning:
```
[19:34:56][W][tuya:235]: Datapoint 3 is not expected size
```

**Problem-relevant YAML-configuration entries:**
```yaml

uart:
  rx_pin: GPIO13
  tx_pin: GPIO15
  baud_rate: 9600

tuya:

fan:
  - platform: tuya
    name: fan01
    switch_datapoint: 1
    speed_datapoint: 3
    oscillation_datapoint: 4
    direction_datapoint: 5
    speed_count: 26
```

**Logs (if applicable):**

```
PASTE DEBUG LOG HERE

```

**Additional information and things you've tried:**

Querying status reporting response:

```
[20:39:41][V][tuya:105]: Received Tuya: CMD=0x07 VERSION=3 DATA=[01.01.00.01.00 (5)] INIT_STATE=5

[20:39:41][V][tuya:105]: Received Tuya: CMD=0x07 VERSION=3 DATA=[02.04.00.01.00 (5)] INIT_STATE=5

[20:39:41][V][tuya:105]: Received Tuya: CMD=0x07 VERSION=3 DATA=[03.04.00.01.09.00.00.00 (8)] INIT_STATE=5

[20:39:41][V][tuya:105]: Received Tuya: CMD=0x07 VERSION=3 DATA=[04.04.00.01.00 (5)] INIT_STATE=5

[20:39:41][V][tuya:105]: Received Tuya: CMD=0x07 VERSION=3 DATA=[05.04.00.01.00 (5)] INIT_STATE=5

[20:39:41][V][tuya:105]: Received Tuya: CMD=0x07 VERSION=3 DATA=[06.04.00.01.00.00.00.00 (8)] INIT_STATE=5
```

image
https://developer.tuya.com/en/docs/iot/tuya-cloud-universal-serial-port-access-protocol?id=K9hhi0xxtn9cb

### PR DESCRIPTION
**Pull request by nuttytree**
Break the Tuya set_datapoint_value method into separate methods per datapoint type

# What does this implement/fix? 

This PR breaks the Tuya set_datapoint_value method into multiple methods, one per datapoint type rather than having one method that attempts to determine the datapoint type and size from the last received datapoint.  This prevents issues with attempting to set a datapoint before the Tuya MCU has reported a value.  If the Tuya MCU has reported a value for the datapoint it does do validation that the datapoint type matches and will not send the data if it has not changed.

## Types of changes

- [X] Bugfix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] Other

**Related issue or feature (if applicable):** partially fixes esphome/issues#2149 (PR esphome/esphome#1982 provides the other half of the fix)

**Pull request in [esphome-docs](https://github.com/esphome/esphome-docs) with documentation (if applicable):** N/A

## Test Environment

- [ ] ESP32
- [X] ESP8266

```

## Checklist:
  - [X] The code change is tested and works locally.
  - [N/A] Tests have been added to verify that the new code works (under `tests/` folder).
  
If user exposed functionality or configuration variables are added/changed:
  - [N/A] Documentation added/updated in [esphome-docs](https://github.com/esphome/esphome-docs).

### CODE REVIEW

File: esphome/components/tuya/tuya.cpp [hunk 1]
```diff
@@ -398,42 +398,38 @@ void Tuya::send_local_time_() {
...
 #endif
 
-void Tuya::set_datapoint_value(uint8_t datapoint_id, uint32_t value) {
-  ESP_LOGD(TAG, "Setting datapoint %u to %u", datapoint_id, value);
+void Tuya::set_raw_datapoint_value(uint8_t datapoint_id, const std::vector<uint8_t> &value) {
+  ESP_LOGD(TAG, "Setting datapoint %u to %s", datapoint_id, hexencode(value).c_str());
   optional<TuyaDatapoint> datapoint = this->get_datapoint_(datapoint_id);
   if (!datapoint.has_value()) {
-    ESP_LOGE(TAG, "Attempt to set unknown datapoint %u", datapoint_id);
+    ESP_LOGW(TAG, "Attempt to set unknown datapoint %u", datapoint_id);
```
Comment (trvrnrth) [inline esphome/components/tuya/tuya.cpp]: These should probably read as follows now to make it clear that whilst the datapoint is unknown we are actually setting it.
```suggestion
    ESP_LOGW(TAG, "Setting unknown datapoint %u", datapoint_id);
```

File: esphome/components/tuya/tuya.cpp [hunk 2]
```diff
@@ -444,13 +440,52 @@ void Tuya::set_datapoint_value(uint8_t datapoint_id, const std::string &value) {
...
       return datapoint;
   return {};
 }
 
+void Tuya::set_numeric_datapoint_value_(uint8_t datapoint_id, TuyaDatapointType datapoint_type, const uint32_t value,
+                                        uint8_t length) {
+  ESP_LOGD(TAG, "Setting datapoint %u to %u", datapoint_id, value);
+  optional<TuyaDatapoint> datapoint = this->get_datapoint_(datapoint_id);
+  if (!datapoint.has_value()) {
+    ESP_LOGW(TAG, "Attempt to set unknown datapoint %u", datapoint_id);
```
Comment (trvrnrth) [inline esphome/components/tuya/tuya.cpp]:
```suggestion
    ESP_LOGW(TAG, "Setting unknown datapoint %u", datapoint_id);
```

File: esphome/components/tuya/tuya.cpp [hunk 3]
```diff
@@ -398,42 +398,38 @@ void Tuya::send_local_time_() {
...
 
-void Tuya::set_datapoint_value(uint8_t datapoint_id, const std::string &value) {
+void Tuya::set_string_datapoint_value(uint8_t datapoint_id, const std::string &value) {
   ESP_LOGD(TAG, "Setting datapoint %u to %s", datapoint_id, value.c_str());
   optional<TuyaDatapoint> datapoint = this->get_datapoint_(datapoint_id);
   if (!datapoint.has_value()) {
-    ESP_LOGE(TAG, "Attempt to set unknown datapoint %u", datapoint_id);
-  }
-  if (datapoint->value_string == value) {
+    ESP_LOGW(TAG, "Attempt to set unknown datapoint %u", datapoint_id);
```
Comment (trvrnrth) [inline esphome/components/tuya/tuya.cpp]:
```suggestion
    ESP_LOGW(TAG, "Setting unknown datapoint %u", datapoint_id);
```

**Review by trvrnrth — APPROVED** [review]
I'm away at the moment so can't try this on my thermostat device but this all looks sensible to me :)

**Comment by trvrnrth** [comment]
I've just taken this for a spin on my thermostat device and setting enum, boolean and integer datapoints all works fine on it.

**Review by OttoWinter — APPROVED** [review]
LGTM, thanks!

**Review by jesserockz — APPROVED** [review]
