### PR TITLE
Added Banking support to tca9555, fixed input bug

### LINKED ISSUE #6438: TCA9555 does not report input changes
### The problem

binary_sensors using GPIO pins from tca9555 do not change regardless of the signals applied.

The relevant yaml code, with outputs and lights left to check that the chip is working, is in the dedicated section below.

### Which version of ESPHome has the issue?

2024.10.3

### What type of installation are you using?

Home Assistant Add-on

### Which version of Home Assistant has the issue?

2024.11.2

### What platform are you using?

ESP8266

### Board

esp12e

### Component causing the issue

tca9555

### Example YAML snippet

```yaml
substitutions:
  device_name: test
  upper_devicename: Test

esp8266:
board: esp12e

i2c: # required for tca9555

tca9555:
  - id: exp0 # Consider only base IOs
    address: 0x20 # 20-27, 20 is the first expander, default would be 0x21
output:
  - id: pin_ledusr
    platform: gpio
    pin:
      tca9555: exp0
      number: 9
      mode: output
light:
  - id: ledconn
    platform: status_led
    pin:
      tca9555: exp0
      number: 8
      mode: output
      #inverted: true
  - id: ledusr
    platform: binary
    name: "${upper_devicename} Led Usr"
    output: pin_ledusr
binary_sensor:
  - id: in1
    name: "${upper_devicename} In 1"
    platform: gpio
    pin:
      tca9555: exp0
      number: 2
      mode: INPUT # already tried 'input'

esphome:
  name: $device_name

# Enable Home Assistant API
api:
  encryption:
    key: "##################"
  reboot_timeout: 0s
    

ota:
  - platform: esphome
    password: "###############"

web_server:
  port: 80
  version: 2


wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password
  fast_connect: true

  # Enable fallback hotspot (captive portal) in case wifi connection fails
  ap:
    ssid: "${upper_devicename}"
    password: !secret wifi_fallback_pass

captive_portal:

# Enable logging
logger:
  baud_rate: 0 # Do not log over serial port
```

### Anything in the logs that might be useful for us?

_No response_

### Additional information

The circuit is working  correctly with an older custom component (quite messy code that I wrote many years ago), so it's not a hardware issue. The board where the esp12e is mounted is my DomoNode 2.1 (https://github.com/NdK73/HomeAutomation/tree/master/domonode2).

### PR DESCRIPTION
**Pull request by mobrembski**
# What does this implement/fix?

## Types of changes

- [X] Bugfix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] Code quality improvements to existing code or addition of tests
- [ ] Other

**Related issue or feature (if applicable):**

- fixes [https://github.com/esphome/issues/issues/6438](https://github.com/esphome/issues/issues/6438)

## Test Environment

- [X] ESP32
- [ ] ESP32 IDF
- [ ] ESP8266
- [ ] RP2040
- [ ] BK72xx
- [ ] RTL87xx

## Checklist:
  - [X] The code change is tested and works locally.
  - [ ] Tests have been added to verify that the new code works (under `tests/` folder).

### CODE REVIEW

**Comment by mobrembski** [comment]
@jesserockz Can we merge this? This is an important bugfix for TCA9555 driver

**Comment by lk-ek** [comment]
Hey, new user of the TCA9555 here. I can confirm that this works for actually reading the state of the GPIOs - without this PR, I get no state changes.

Also, as I'm trying to read a bus signal from two GPIOs where the bits are encoded by the length of a the LOW signal (5 vs. 10ms), the timing is quite critical for me. I can't use the interrupt line (i2c is isolated and level-shifted via an ADuM1250), so I've hacked in an update()-method that simply invalidates the cache when I really need to get an updated value:

void TCA9555Component::update() { this->reset_pin_cache_(); }

This way, I can be sure that the next digital_read() will poll the TCA9555. Without this, I can't get accurate timings from the GPIOs. Would this be a feasable change for inclusion?

**Comment by NdK73** [comment]
Already at least 2 ESPHome releases and this quite trivial PR have not been merged. Is there hope?

**Comment by mobrembski** [comment]
I had the hope but i have no idea how to ping devs to merge IT :/

niedz., 6 kwi 2025, 21:44 użytkownik NdK ***@***.***> napisał:

**Comment by NdK73** [comment]
I'm quite ignorant, too, but looking at closed PRs it seems at least @kbx81 and @bdraco have the power to approve. Or (hopefully) they know who to tag. 🤞

**Comment by lk-ek** [comment]
fyi, I've created a repository so that this branch and fix can be easily used by others until it's finally merged:

https://github.com/lk-ek/esphome-tca9555

The only change in that repository is the addition of the update()-function that simply invalidates the cache and hence allows for timinig-critical gpio readings.

To use in your devices, simply add this external component:
```yaml
external_components:
  - source:
      type: git
      url: https://github.com/lk-ek/esphome-tca9555
      ref: main
    components: ["tca9555", "gpio_expander"]
```

**Comment by NdK73** [comment]
Maybe also tagging @jesserockz can help speeding up merge? Feeling more-than-a-bit ignored :(

**Review by jesserockz — DISMISSED** [review]

File: esphome/components/gpio_expander/cached_gpio.h [hunk 1]
```diff
@@ -3,35 +3,51 @@
...
   virtual bool digital_read_cache(T pin) = 0;
+  /// @brief Call component low level function to write GPIO state to device
   virtual void digital_write_hw(T pin, bool value) = 0;
+  const uint8_t cache_byte_size_ = N / (sizeof(T) * BITS_PER_BYTE);
 
+  /// @brief Invalidate cache. This function should be called in component loop().
   void reset_pin_cache_() {
-    for (T i = 0; i < N; i++) {
-      this->read_cache_invalidated_[i] = false;
+    for (T i = 0; i < cache_byte_size_; i++) {
```
Comment (jesserockz) [inline esphome/components/gpio_expander/cached_gpio.h]:
```suggestion
    for (T i = 0; i < this->cache_byte_size_; i++) {
```

File: esphome/components/gpio_expander/cached_gpio.h [hunk 2]
```diff
@@ -3,35 +3,51 @@
 #include <array>
 #include <cstdint>
 #include "esphome/core/hal.h"
+#include "esphome/core/log.h"
```
Comment (jesserockz) [inline esphome/components/gpio_expander/cached_gpio.h]:
```suggestion
```

**Review by jesserockz — APPROVED** [review]

**Comment by lk-ek** [comment]
Thanks a gazillion @jesserockz!
