### PR TITLE
Ignore already stopped dhcp for ethernet

### LINKED ISSUE #2783: Ethernet component cannot reconnect when manual_ip is configured
### The problem

When manual_ip is configured and ethernet cable is disconnected the ethernet component is marked as failed and won't reconnect when cable is plugged again.
The error is ESP_ERR_TCPIP_ADAPTER_DHCP_ALREADY_STOPPED.  Check the attached logs.
The same error happens when esphome starts with ethernet cable unplugged.

In dhcp mode (manual_ip not onfigured) esphome gracefully deals with both cases.

### Which version of ESPHome has the issue?

2021.11.4

### What type of installation are you using?

pip

### Which version of Home Assistant has the issue?

_No response_

### What platform are you using?

ESP32

### Board

WT32-ETH01

### Component causing the issue

ethernet

### Example YAML snippet

```yaml
esphome:
  name: wt32
  platform: ESP32
  board: nodemcu-32s

logger:

ethernet:
  type: LAN8720
  mdc_pin: GPIO23
  mdio_pin: GPIO18
  clk_mode: GPIO0_IN
  phy_addr: 1
  power_pin: GPIO16

  manual_ip:
    static_ip: 192.168.3.82
    subnet: 255.255.255.0
    gateway: 192.168.3.1
```

### Anything in the logs that might be useful for us?

```txt
[19:54:42][I][ethernet:096]: Connected via Ethernet!
[19:54:42][C][ethernet:228]:   IP Address: 192.168.3.82
[19:54:42][C][ethernet:229]:   Hostname: 'wt32'
[19:54:42][C][ethernet:230]:   Subnet: 255.255.255.0
[19:54:42][C][ethernet:231]:   Gateway: 192.168.3.1
[19:54:42][C][ethernet:242]:   DNS1: 0.0.0.0
[19:54:42][C][ethernet:243]:   DNS2: 0.0.0.0
[19:54:42][C][ethernet:246]:   MAC Address: A8:03:2A:A1:46:A3
[19:54:42][C][ethernet:247]:   Is Full Duplex: YES
[19:54:42][C][ethernet:248]:   Link Up: YES
[19:54:42][C][ethernet:249]:   Link Speed: 100
[19:54:42][I][app:060]: setup() finished successfully!
[19:54:42][I][app:099]: ESPHome version 2021.11.4 compiled on Dec  4 2021, 19:52:35
[19:54:42][C][logger:233]: Logger:
[19:54:42][C][logger:234]:   Level: DEBUG
[19:54:42][C][logger:235]:   Log Baud Rate: 115200
[19:54:42][C][logger:236]:   Hardware UART: UART0
[19:54:42][C][ethernet:119]: Ethernet:
[19:54:42][C][ethernet:228]:   IP Address: 192.168.3.82
[19:54:42][C][ethernet:229]:   Hostname: 'wt32'
[19:54:42][C][ethernet:230]:   Subnet: 255.255.255.0
[19:54:42][C][ethernet:231]:   Gateway: 192.168.3.1
[19:54:42][C][ethernet:242]:   DNS1: 0.0.0.0
[19:54:42][C][ethernet:243]:   DNS2: 0.0.0.0
[19:54:42][C][ethernet:246]:   MAC Address: A8:03:2A:A1:46:A3
[19:54:42][C][ethernet:247]:   Is Full Duplex: YES
[19:54:42][C][ethernet:248]:   Link Up: YES
[19:54:42][C][ethernet:249]:   Link Speed: 100
[19:54:43][C][ethernet:121]:   Power Pin: GPIO16
[19:54:43][C][ethernet:122]:   MDC Pin: 23
[19:54:43][C][ethernet:123]:   MDIO Pin: 18
[19:54:43][C][ethernet:124]:   Type: LAN8720
[19:54:43][C][mdns:084]: mDNS:
[19:54:43][C][mdns:085]:   Hostname: wt32

Here I unplug ethernet cable

[19:55:26][W][ethernet:111]: Connection via Ethernet lost! Re-connecting...
[19:55:26][E][ethernet:187]: DHCPC stop error: (20485) ESP_ERR_TCPIP_ADAPTER_DHCP_ALREADY_STOPPED
[19:55:26][E][component:103]: Component ethernet was marked as failed.
```

### Additional information

_No response_

### PR DESCRIPTION
**Pull request by madron**
# What does this implement/fix? 
This PR tries to fix https://github.com/esphome/issues/issues/2783

## Types of changes

- [x] Bugfix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] Other

**Related issue or feature (if applicable):** fixes https://github.com/esphome/issues/issues/2783

## Test Environment

- [x] ESP32
- [ ] ESP32 IDF
- [ ] ESP8266

## Example entry for `config.yaml`:

```yaml
esphome:
  name: wt32
  platform: ESP32
  board: nodemcu-32s

logger:

ethernet:
  type: LAN8720
  mdc_pin: GPIO23
  mdio_pin: GPIO18
  clk_mode: GPIO0_IN
  phy_addr: 1
  power_pin: GPIO16

  manual_ip:
    static_ip: 192.168.3.82
    subnet: 255.255.255.0
    gateway: 192.168.3.1
```

## Checklist:
  - [x] The code change is tested and works locally.
  - [ ] Tests have been added to verify that the new code works (under `tests/` folder).
  
If user exposed functionality or configuration variables are added/changed:
  - [ ] Documentation added/updated in [esphome-docs](https://github.com/esphome/esphome-docs).

### CODE REVIEW

File: esphome/components/ethernet/ethernet_component.cpp [hunk 1]
```diff
@@ -184,7 +184,9 @@ void EthernetComponent::start_connect_() {
   }
 
   err = tcpip_adapter_dhcpc_stop(TCPIP_ADAPTER_IF_ETH);
-  ESPHL_ERROR_CHECK(err, "DHCPC stop error");
+  if (! (this->manual_ip_.has_value() && err == ESP_ERR_TCPIP_ADAPTER_DHCP_ALREADY_STOPPED )) {
+    ESPHL_ERROR_CHECK(err, "DHCPC stop error");
+  }
```
Comment (oxan) [inline esphome/components/ethernet/ethernet_component.cpp]:
```suggestion
  if (err != ESP_ERR_TCPIP_ADAPTER_DHCP_ALREADY_STOPPED)) {
    ESPHL_ERROR_CHECK(err, "DHCPC stop error");
  }
```

File: esphome/components/ethernet/ethernet_component.cpp [hunk 2]
```diff
@@ -184,7 +184,9 @@ void EthernetComponent::start_connect_() {
   }
 
   err = tcpip_adapter_dhcpc_stop(TCPIP_ADAPTER_IF_ETH);
-  ESPHL_ERROR_CHECK(err, "DHCPC stop error");
+  if (err != ESP_ERR_TCPIP_ADAPTER_DHCP_ALREADY_STOPPED)) {
```
Comment (jesserockz) [inline esphome/components/ethernet/ethernet_component.cpp]:
```suggestion
  if (err != ESP_ERR_TCPIP_ADAPTER_DHCP_ALREADY_STOPPED) {
```

**Review by jesserockz — APPROVED** [review]
