### PR TITLE
Fix media_player.volume_set when media player is not started

### LINKED ISSUE #5877: When using `arduino` framework, the `volume` of a `media_player` can only be changed while playing
### The problem

The `volume` of an `arduino` `media_player` can only be changed during playback. Changes made when the `media_player` is `idle` will not be reflected.

By "changing" i mean both [`media_player.volume_set`](https://rc.home-assistant.io/integrations/media_player#service-media_playervolume_set) HA service calls and [`media_player.volume_set`](https://www.esphome.io/components/media_player/#media-player-volume-set-action) service calls in ESPHome.

### Which version of ESPHome has the issue?

20224.5.4

### What type of installation are you using?

Docker

### Which version of Home Assistant has the issue?

2024.5.x

### What platform are you using?

ESP32

### Board

Onju Voice

### Component causing the issue

i2s_audio

### Example YAML snippet

_No response_

### Anything in the logs that might be useful for us?

_No response_

### Additional information

_No response_

### PR DESCRIPTION
**Pull request by tetele**
# What does this implement/fix?

When the `media_player` was idle and the volume was changed, the change would not trigger all of the required logic inside the `media_player`.

Now the volume control code is placed before checking whether the `media_player` is playing.

Test in a config using

```yaml
external_components:
  - source: github://pr#6859
    components: i2s_audio
    refresh: 0s
```

## Types of changes

- [x] Bugfix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] Other

**Related issue or feature (if applicable):** fixes https://github.com/esphome/issues/issues/5877

**Pull request in [esphome-docs](https://github.com/esphome/esphome-docs) with documentation (if applicable):** esphome/esphome-docs#<esphome-docs PR number goes here>

## Test Environment

- [x] ESP32
- [ ] ESP32 IDF
- [ ] ESP8266
- [ ] RP2040
- [ ] BK72xx
- [ ] RTL87xx

## Example entry for `config.yaml`:

```yaml
# Example config.yaml

```

## Checklist:
  - [x] The code change is tested and works locally.
  - [ ] Tests have been added to verify that the new code works (under `tests/` folder).

If user exposed functionality or configuration variables are added/changed:
  - [ ] Documentation added/updated in [esphome-docs](https://github.com/esphome/esphome-docs).

### CODE REVIEW

File: esphome/components/i2s_audio/media_player/i2s_audio_media_player.cpp [hunk 1]
```diff
@@ -81,6 +57,32 @@ void I2SAudioMediaPlayer::control(const media_player::MediaPlayerCall &call) {
         break;
       }
```
Comment (jesserockz) [inline esphome/components/i2s_audio/media_player/i2s_audio_media_player.cpp:58]:
```suggestion
      }
      default:
        break;
```

File: esphome/components/i2s_audio/media_player/i2s_audio_media_player.cpp [hunk 2]
```diff
@@ -81,6 +57,32 @@ void I2SAudioMediaPlayer::control(const media_player::MediaPlayerCall &call) {
...
+        break;
+      case media_player::MEDIA_PLAYER_COMMAND_TOGGLE:
+        this->audio_->pauseResume();
+        if (this->audio_->isRunning()) {
+          this->state = media_player::MEDIA_PLAYER_STATE_PLAYING;
+        } else {
+          this->state = media_player::MEDIA_PLAYER_STATE_PAUSED;
+        }
+        break;
+    }
```
Comment (jesserockz) [inline esphome/components/i2s_audio/media_player/i2s_audio_media_player.cpp:89]:
```suggestion
      default:
        break;
    }
```

**Review by jesserockz — APPROVED** [review]
