### PR TITLE
[nrf52,pcf8563] fix build error

### LINKED ISSUE #11665: [nrf52] components/pcf8563/pcf8563.cpp:26:48: error: 'class esphome::pcf8563::PCF8563Component' has no member named 'timezone_'
### The problem

Hello,

I can't build the pcf8563 component for nrf52 platform:
```
/data/build/xiao-nrf52-i2c/src/esphome/components/pcf8563/pcf8563.cpp: In member function 'virtual void esphome::pcf8563::PCF8563Component::dump_config()':
/data/build/xiao-nrf52-i2c/src/esphome/components/pcf8563/pcf8563.cpp:26:48: error: 'class esphome::pcf8563::PCF8563Component' has no member named 'timezone_'
   26 |   ESP_LOGCONFIG(TAG, "  Timezone: '%s'", this->timezone_.c_str());
      |                                                ^~~~~~~~~
```
[pcf8563.cpp](https://github.com/esphome/esphome/blob/dev/esphome/components/pcf8563/pcf8563.cpp)

### Which version of ESPHome has the issue?

2025.11.0-dev

### What type of installation are you using?

Home Assistant Add-on

### What platform are you using?

nrf52

### Component causing the issue

[pcf8563](https://esphome.io/components/time/pcf8563/)

### YAML Config

```yaml
esphome:
  name: xiao-nrf52-i2c
  friendly_name: XIAO nRF52 I2C
  on_boot:
    then:
      # read the RTC time once when the system boots
      pcf8563.read_time:

nrf52:
  board: xiao_ble

logger:
  level: VERY_VERBOSE

external_components:
    # i2c
  - source: github://pr#8150
    components: [i2c]
    refresh: 1h

    # nrf52_display
  - source: github://lboue/esphome@nrf52_display
    components: [ display ]

time:
  - platform: pcf8563
    id: pcf8563_time
    # repeated synchronization is not necessary unless the external RTC
    # is much more accurate than the internal clock
    update_interval: never
    # timezone: "Europe/Paris"

i2c:
  - sda: P0.04
    scl: P0.05

font:
  # gfonts://family[@weight]
- file: "gfonts://Roboto"
  id: roboto_16
  size: 16

display:
  - platform: ssd1306_i2c
    model: "SSD1306 128x64"
    address: 0x3C
    lambda: |-
      it.print(0, 0, id(roboto_16), "ESPHome");
      it.print(0, 20, id(roboto_16), "nRF52");
      // Print time in HH:MM format
      it.strftime(0, 40, id(roboto_16), TextAlign::BASELINE_LEFT, "%H:%M", id(pcf8563_time).now());
```

### Anything in the logs that might be useful for us?

```txt
/data/build/xiao-nrf52-i2c/src/esphome/components/pcf8563/pcf8563.cpp: In member function 'virtual void esphome::pcf8563::PCF8563Component::dump_config()':
/data/build/xiao-nrf52-i2c/src/esphome/components/pcf8563/pcf8563.cpp:26:48: error: 'class esphome::pcf8563::PCF8563Component' has no member named 'timezone_'
   26 |   ESP_LOGCONFIG(TAG, "  Timezone: '%s'", this->timezone_.c_str());
      |                                                ^~~~~~~~~
```

### Additional information

[logs_xiao-nrf52-i2c_compile (4).txt](https://github.com/user-attachments/files/23286903/logs_xiao-nrf52-i2c_compile.4.txt)

### PR DESCRIPTION
**Pull request by tomaszduda23**
# What does this implement/fix?

zephyr do not support time zones. It has to be disabled.

## Types of changes

- [x] Bugfix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] Code quality improvements to existing code or addition of tests
- [ ] Other

**Related issue or feature (if applicable):**

- fixes https://github.com/esphome/esphome/issues/11665

**Pull request in [esphome-docs](https://github.com/esphome/esphome-docs) with documentation (if applicable):**

- esphome/esphome-docs#<esphome-docs PR number goes here>

## Test Environment

- [ ] ESP32
- [ ] ESP32 IDF
- [ ] ESP8266
- [ ] RP2040
- [ ] BK72xx
- [ ] RTL87xx
- [x] nRF52840

## Example entry for `config.yaml`:

```yaml
# Example config.yaml

```

## Checklist:
  - [ ] The code change is tested and works locally.
  - [x] Tests have been added to verify that the new code works (under `tests/` folder).

If user exposed functionality or configuration variables are added/changed:
  - [ ] Documentation added/updated in [esphome-docs](https://github.com/esphome/esphome-docs).

### CODE REVIEW

**Comment by lboue** [comment]
Thanks.

File: esphome/components/pcf8563/pcf8563.cpp [hunk 1]
```diff
@@ -23,7 +23,9 @@ void PCF8563Component::dump_config() {
   if (this->is_failed()) {
     ESP_LOGE(TAG, ESP_LOG_MSG_COMM_FAIL);
   }
+#ifndef USE_ZEPHYR
   ESP_LOGCONFIG(TAG, "  Timezone: '%s'", this->timezone_.c_str());
+#endif
```
Comment (bdraco) [inline esphome/components/pcf8563/pcf8563.cpp]: This is a bit messy to have to remember to do everywhere. Maybe we can come up with a better solution long term?

**Review by bdraco — DISMISSED** [review]

File: esphome/components/pcf8563/pcf8563.cpp (hunk 1 above)
Comment (tomaszduda23) [reply esphome/components/pcf8563/pcf8563.cpp]: Hmmm there is already USE_TIME_TIMEZONE

Comment (tomaszduda23) [reply esphome/components/pcf8563/pcf8563.cpp]: I moved it to base class.

**Comment by bdraco** [comment]
```
[11:20:44.860][C][homeassistant.time:010]: Home Assistant Time:
[11:20:44.863][C][time:029]:   Timezone: 'CST6CDT,M3.2.0,M11.1.0'
```

I guess thats ok. .. maybe we should take out the "  "

File: esphome/components/time/real_time_clock.cpp [hunk 2]
```diff
@@ -23,6 +23,13 @@ namespace time {
 static const char *const TAG = "time";
 
 RealTimeClock::RealTimeClock() = default;
+
+void RealTimeClock::dump_config() {
+#ifdef USE_TIME_TIMEZONE
+  ESP_LOGCONFIG(TAG, "  Timezone: '%s'", this->timezone_.c_str());
```
Comment (bdraco) [inline esphome/components/time/real_time_clock.cpp]:
```suggestion
  ESP_LOGCONFIG(TAG, "Timezone: '%s'", this->timezone_.c_str());
```

Since its a different tag

File: esphome/components/homeassistant/time/homeassistant_time.cpp [hunk 3]
```diff
@@ -7,10 +7,8 @@ namespace homeassistant {
 static const char *const TAG = "homeassistant.time";
 
 void HomeassistantTime::dump_config() {
-  ESP_LOGCONFIG(TAG,
-                "Home Assistant Time:\n"
-                "  Timezone: '%s'",
-                this->timezone_.c_str());
+  ESP_LOGCONFIG(TAG, "Home Assistant Time:");
```
Comment (bdraco) [inline esphome/components/homeassistant/time/homeassistant_time.cpp]:
```suggestion
  ESP_LOGCONFIG(TAG, "Home Assistant Time");
```

**Review by bdraco — APPROVED** [review]
