### PR TITLE
[pipsolar] cleanup / refactoring

### LINKED ISSUE #5193: pipsolar QPIGS not decoded correctly
### The problem

I am trying to decode the messages from an MPP Solar PIP6048MT inverter and currently the QPIGS messages fail the CRC while the QPIRI ones pass. I did not check the other commands yet.

I have modified the check_incoming_crc_ to always return 1, in order to see how the decoded values look like, but they are all zeroes.

```
[12:51:50][D][pipsolar:837]: Sending polling command : QPIRI with length 5
[12:51:50][D][uart_debug:114]: >>> 51:50:49:52:49:F8:54:0D
[12:51:50][D][pipsolar:773]: checking crc on incoming message
[12:51:50][D][pipsolar:776]: CRC OK
[12:51:50][D][pipsolar:430]: Decode QPIRI
[12:51:50][V][sensor:043]: 'inverter0_grid_rating_current': Received new state 26.000000
[12:51:50][D][sensor:093]: 'inverter0_grid_rating_current': Sending state 26.00000 A with 1 decimals of accuracy
[12:51:50][D][uart_debug:114]: <<< 28:32:33:30:2E:30:20:32:36:2E:30:20:32:33:30:2E:30:20:35:30:2E:30:20:32:36:2E:30:20:36:30:30:30:20:36:30:30:30:20:34:38:2E:30:20:34:36:2E:30:20:34:32:2E:30:20:35:36:2E:34:20:35:34:2E:30:20:32:20:30:30:32:20:31:32:30:20:31:20:32:20:31:20:31:20:30:31:20:30:20:30:20:35:34:2E:30:20:30:20:31:6D:51:0D
```

```
[12:51:50][D][pipsolar:837]: Sending polling command : QPIGS with length 5
[12:51:50][W][component:214]: Component esphome.coroutine took a long time for an operation (0.08 s).
[12:51:50][W][component:215]: Components should block for at most 20-30ms.
[12:51:50][D][uart_debug:114]: >>> 51:50:49:47:53:B7:A9:0D
[12:51:50][D][pipsolar:773]: checking crc on incoming message
[12:51:50][D][pipsolar:782]: CRC NOK expected: A4 3F but got: 29 10
[12:51:50][D][pipsolar:449]: Decode QPIGS
[12:51:50][V][sensor:043]: 'inverter0_grid_voltage': Received new state 0.000000
[12:51:50][D][sensor:093]: 'inverter0_grid_voltage': Sending state 0.00000 V with 1 decimals of accuracy
[12:51:50][V][sensor:043]: 'inverter0_ac_output_voltage': Received new state 0.000000
[12:51:50][D][sensor:093]: 'inverter0_ac_output_voltage': Sending state 0.00000 V with 1 decimals of accuracy
[12:51:50][V][sensor:043]: 'inverter0_output_load_percent': Received new state 0.000000
[12:51:50][D][sensor:093]: 'inverter0_output_load_percent': Sending state 0.00000 % with 1 decimals of accuracy
[12:51:50][V][sensor:043]: 'inverter0_battery_voltage': Received new state 0.000000
[12:51:50][D][sensor:093]: 'inverter0_battery_voltage': Sending state 0.00000 V with 1 decimals of accuracy
[12:51:50][D][uart_debug:114]: <<< 28:30:30:30:2E:30:20:30:30:2E:30:20:32:32:39:2E:39:20:35:30:2E:30:20:30:30:30:30:20:30:30:30:30:20:30:30:30:20:33:36:33:20:35:32:2E:34:30:20:30:30:30:20:31:30:30:20:30:30:33:36:20:30:30:2E:30:20:30:30:30:2E:30:20:30:30:2E:30:30:20:30:30:30:30:30:20:30:30:30:31:30:30:30:30:20:30:30:20:30:30:20:30:30:30:30:30:20:30:31:31:20:30:20:30:30:20:30:30:30:30:29:10:0D
```

Running into a HEX->ASCII converter the output from above yields: (000.0 00.0 229.9 50.0 0000 0000 000 363 52.40 000 100 0036 00.0 000.0 00.00 00000 00010000 00 00 00000 011 0 00 0000)

As you can see, the values are there, at least ac_output_voltage=229.9 and battery_voltage=52.40

I did not go deep into the code to see exacly why it fails. On the inverter I have main cpu firmware version 00060.06 and secondary cpu fw version 00025.08.

### Which version of ESPHome has the issue?

2023.11.6

### What type of installation are you using?

pip

### Which version of Home Assistant has the issue?

_No response_

### What platform are you using?

ESP8266

### Board

nodemcu

### Component causing the issue

pipsolar

### Example YAML snippet

_No response_

### Anything in the logs that might be useful for us?

_No response_

### Additional information

_No response_

### PR DESCRIPTION
**Pull request by patagonaa**
# What does this implement/fix?

This is based on #10289. That should be reviewed and merged first!
- rename / remove confusing methods
- move large chunks of code out of loop() into separate methods
- replace sscanf with separate read-calls to improve readability and make unknown states possible
- fix typo `warnung_low_pv_energy` -> `warning_low_pv_energy`
- fix potential buffer overrun 

## Types of changes

- [ ] Bugfix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [x] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [x] Code quality improvements to existing code or addition of tests
- [ ] Other

**Related issue or feature (if applicable):**

- fixes https://github.com/esphome/issues/issues/5193

**Pull request in [esphome-docs](https://github.com/esphome/esphome-docs) with documentation (if applicable):**

- esphome/esphome-docs#<esphome-docs PR number goes here>

## Test Environment

- [ ] ESP32
- [x] ESP32 IDF
- [ ] ESP8266
- [ ] RP2040
- [ ] BK72xx
- [ ] RTL87xx
- [ ] nRF52840

## Example entry for `config.yaml`:

```yaml
uart:
  - id: inverter_uart
    rx_pin: GPIO21
    tx_pin: GPIO22
    baud_rate: 2400
    data_bits: 8
    parity: NONE
    stop_bits: 1

pipsolar:
  - id: inverter0
    uart_id: inverter_uart
    update_interval: 1s

sensor:
  - platform: pipsolar
    pipsolar_id: inverter0
    ac_output_voltage:
      name: Inv AC Output Voltage
    ac_output_frequency:
      name: Inv AC Output Frequency
    ac_output_apparent_power:
      name: Inv AC Output Apparent Power
    ac_output_active_power:
      state_class: measurement
    output_load_percent:
      state_class: measurement
```

## Checklist:
  - [x] The code change is tested and works locally.
  - [ ] Tests have been added to verify that the new code works (under `tests/` folder).

If user exposed functionality or configuration variables are added/changed:
  - [ ] Documentation added/updated in [esphome-docs](https://github.com/esphome/esphome-docs).

### CODE REVIEW

**Comment by patagonaa** [comment]
I can't really split this up further, most of the lines of code are just from moving stuff out of the loop method (and even there, I've put moving the code and modifying it in seperate commits for easier review).

File: esphome/components/pipsolar/pipsolar.cpp [hunk 1]
```diff
@@ -815,94 +227,544 @@ bool Pipsolar::send_next_command_() {
...
+      case 29:
+        this->publish_binary_sensor_(enabled, this->warning_battery_too_low_to_charge_);
+        value_warnings_present |= enabled.value_or(false);
+        break;
+      case 30:
+        this->publish_binary_sensor_(enabled, this->fault_dc_dc_over_current_);
+        value_faults_present |= enabled.value_or(false);
+        break;
+      case 33:
+        this->publish_binary_sensor_(enabled, this->warnung_low_pv_energy_);
```
Comment (swoboda1337) [inline esphome/components/pipsolar/pipsolar.cpp]: Spelling: warnung

**Review by swoboda1337 — CHANGES_REQUESTED** [review]

File: esphome/components/pipsolar/pipsolar.cpp (hunk 1 above)
Comment (patagonaa) [reply esphome/components/pipsolar/pipsolar.cpp]: This is not a new typo, but I guess this is a fine PR to fix this as well. This is also already correct in docs so they don't need to be changed.

**Comment by swoboda1337** [comment]
I was doing a final review of this. I wanted to know how the buffer got null terminated as it affects your new parsing and found this:
```
    while (this->available()) {
      uint8_t byte;
      this->read_byte(&byte);

      if (this->read_pos_ == PIPSOLAR_READ_BUFFER_LENGTH) {
        this->read_pos_ = 0;
        this->empty_uart_buffer_();
      }
      this->read_buffer_[this->read_pos_] = byte;
      this->read_pos_++;

      // end of answer
      if (byte == 0x0D) {
        this->read_buffer_[this->read_pos_] = 0;
        this->empty_uart_buffer_();
        if (this->state_ == STATE_POLL) {
          this->state_ = STATE_POLL_COMPLETE;
        }
        if (this->state_ == STATE_COMMAND) {
          this->state_ = STATE_COMMAND_COMPLETE;
        }
      }
    }  // available
``` 
It seems that in appending the null terminator it might overrun the buffer as the check `this->read_pos_ == PIPSOLAR_READ_BUFFER_LENGTH` doesn't make sure there is room for two more bytes only one. 

Probably need to increase to 111?

Can you fix this potential memory overrun as well? Otherwise it looks good. Thanks

**Review by swoboda1337 — CHANGES_REQUESTED** [review]
Need to fix memory overrun in existing code.

**Comment by patagonaa** [comment]
@swoboda1337 Good catch! While looking at that code I already thought it was suspicious, but didn't find an overflow straight away.

I fixed the overflow, added a comment to explain the -1, and added a `break` as well because it doesn't make sense to put that one received byte into the buffer while discarding the rest of the receive buffer.

**Comment by swoboda1337** [comment]
Does the buffer size have to increase to 111? or is 110 still fine?

**Comment by patagonaa** [comment]
> Does the buffer size have to increase to 111? or is 110 still fine?

I thought there was never responses that long, but I just found https://github.com/esphome/issues/issues/5193, so I'll just increase this a bit more and also add a log message in case this becomes too small again in the future.

**Review by swoboda1337 — APPROVED** [review]
