### PR TITLE
[wifi] Fix watchdog timeout on P4 WiFi scan

### LINKED ISSUE #13519: [wifi] AP scanning breaks on P4 hosted WiFi
### The problem

A change in 2026.1.1 has resulted in the `wifi` component stalling the loop thread when scanning WiFi SSIDs on an ESP32-P4 with the C6 hosted wifi.

### Which version of ESPHome has the issue?

2026.1.1

### What type of installation are you using?

pip

### What platform are you using?

ESP32

### Component causing the issue

wifi

### YAML Config

```yaml

```

### Anything in the logs that might be useful for us?

```txt
[17:33:00.129][V][mdns:184]:   - _esphomelib, _tcp, 6053
[17:33:00.129][V][mdns:187]:     TXT: friendly_name = P4-ESP
[17:33:00.134][V][mdns:187]:     TXT: version = 2026.2.0-dev
[17:33:00.140][V][mdns:187]:     TXT: mac = 30eda0e1844c
[17:33:00.145][V][mdns:187]:     TXT: platform = ESP32
[17:33:00.151][V][mdns:187]:     TXT: board = esp32-p4-evboard
[17:33:00.152][V][mdns:187]:     TXT: network = wifi
[17:33:02.743][V][wifi_esp32:815]: Scan done: status=0 number=23 scan_id=128
[17:33:02.743][D][wifi_esp32:835]: Getting scan record 1/23
[17:33:07.743]E (21796) task_wdt: Task watchdog got triggered. The following tasks/users did not reset the watchdog in time:
[17:33:07.748]E (21796) task_wdt:  - loopTask (CPU 1)
[17:33:07.753]E (21796) task_wdt: Tasks currently running:
[17:33:07.753]E (21796) task_wdt: CPU 0: IDLE0
[17:33:07.759]E (21796) task_wdt: CPU 1: IDLE1
[17:33:07.759]E (21796) task_wdt: Aborting.
[17:33:07.761]E (21796) task_wdt: Print CPU 1 registers
```

### Additional information

_No response_

### PR DESCRIPTION
**Pull request by clydebarrow**
# What does this implement/fix?

Recent change to WiFi AP scanning causes watchdog timeout on P4

Workaround is to add `fast_connect: true` to WiFi config. Fix here reverts to old code for P4 only.

## Types of changes

- [x] Bugfix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] Developer breaking change (an API change that could break external components)
- [ ] Code quality improvements to existing code or addition of tests
- [ ] Other

**Related issue or feature (if applicable):**

- fixes #13519 https://github.com/esphome/esphome/issues/13500

**Pull request in [esphome-docs](https://github.com/esphome/esphome-docs) with documentation (if applicable):**

- esphome/esphome-docs#<esphome-docs PR number goes here>

## Test Environment

- [ ] ESP32
- [x] ESP32 IDF
- [ ] ESP8266
- [ ] RP2040
- [ ] BK72xx
- [ ] RTL87xx
- [ ] LN882x
- [ ] nRF52840

## Example entry for `config.yaml`:

```yaml
# Example config.yaml

```

## Checklist:
  - [x] The code change is tested and works locally.
  - [ ] Tests have been added to verify that the new code works (under `tests/` folder).

If user exposed functionality or configuration variables are added/changed:
  - [ ] Documentation added/updated in [esphome-docs](https://github.com/esphome/esphome-docs).

### CODE REVIEW

File: esphome/components/wifi/wifi_component_esp_idf.cpp [hunk 1]
```diff
@@ -828,16 +828,27 @@ void WiFiComponent::wifi_process_event_(IDFWiFiEvent *data) {
 
     uint16_t number = it.number;
     scan_result_.init(number);
-
+#ifdef USE_ESP32_VARIANT_ESP32P4
```
Comment (bdraco) [inline esphome/components/wifi/wifi_component_esp_idf.cpp]: should we add a `USE_ESP32_HOSTED` to `esp32_hosted` and use it here?

I'm assuming the problem is its too slow fetching the records over the bus when its not local

Comment (clydebarrow) [reply esphome/components/wifi/wifi_component_esp_idf.cpp]: I did consider a HOSTED define, though we don't really know where the bug lies - I would guess it's in the HOSTED comms. A define for that is a Good Idea anyway.

 It's not just slow fetching the records, it blocks completely, so it is an upstream bug,not just a quirk.

**Review by bdraco — APPROVED** [review]

**Review by swoboda1337 — APPROVED** [review]
