### PR TITLE
Fix Light Trigger

### LINKED ISSUE #1521: Monochromatic Light Triggers are delayed
**Operating environment/Installation (Hass.io/Docker/pip/etc.):**

Hass.io

**ESP (ESP32/ESP8266, Board/Sonoff):**

NodeMCU
**ESPHome version (latest production, beta, dev branch)**

1.15.2
**Affected component:**

Light using `platform: monochromatic` [Link](https://esphome.io/components/light/monochromatic.html)

**Description of problem:**

The triggers `on_turn_on` and `on_turn_off` do not get called at the right time.
The log shows that the ESP receives an update to change the brightness (and changing the output state to `ON`) but no trigger is called (a call is indicated through the log messages `on event` and `off event`). Then the ESP receives the next brightness update (with no output state change). Now the trigger is called, that should have been called after the first update.
The trigger are also delayed by one update when the On/Off switch in the Homeassistant-UI is used.

**Problem-relevant YAML-configuration entries:**
```yaml
PASTE YAML FILE HERE
esphome:
  name: room1_light
  platform: ESP8266
  board: nodemcuv2


wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password

  # Enable fallback hotspot (captive portal) in case wifi connection fails
  ap:
    ssid: "room1_light Fallback Hotspot"
    password: "UVrrnCpXO7PU"

captive_portal:

# Enable logging
logger:

# Enable Home Assistant API
api:
  password: !secret api_password

ota:
  password: !secret ota_password


output:
  - platform: esp8266_pwm
    pin: D5
    frequency: 500 Hz
    min_power: 0.15
    inverted: true
    id: brightness_desk

  
  - platform: esp8266_pwm
    pin: D7
    frequency: 500 Hz
    min_power: 0.15
    inverted: true
    id: brightness_middle
  
switch:
  - platform: gpio
    id: power_middle
    pin: D8
    inverted: true
    internal: true
        
  - platform: gpio
    id: power_desk
    pin: D6
    inverted: true
    internal: true

light:
  - platform: monochromatic
    output: brightness_middle
    name: "Brightness Middle"
    on_turn_on:
      then:
        - logger.log: "on event"
    on_turn_off:
      then:
        - logger.log: "off event"
  
  - platform: monochromatic
    output: brightness_desk
    name: "Brightness Desk"
    on_turn_on:
      then:
        - switch.turn_on: power_desk
    on_turn_off:
      then:
        - switch.turn_off: power_desk
```

**Logs (if applicable):**

```
PASTE DEBUG LOG HERE
[02:34:52][D][light:264]: 'Brightness Middle' Setting:
[02:34:52][D][light:273]:   State: ON
[02:34:52][D][light:277]:   Brightness: 38%
[02:34:52][D][light:303]:   Transition Length: 1.0s
[02:34:52][D][main:286]: off event
[02:34:54][D][light:264]: 'Brightness Middle' Setting:
[02:34:54][D][light:277]:   Brightness: 50%
[02:34:54][D][light:303]:   Transition Length: 1.0s
[02:34:54][D][main:276]: on event
[02:35:18][D][light:264]: 'Brightness Middle' Setting:
[02:35:18][D][light:277]:   Brightness: 75%
[02:35:18][D][light:303]:   Transition Length: 1.0s
[02:35:21][D][light:264]: 'Brightness Middle' Setting:
[02:35:21][D][light:277]:   Brightness: 33%
[02:35:21][D][light:303]:   Transition Length: 1.0s
[02:35:45][D][light:264]: 'Brightness Middle' Setting:
[02:35:45][D][light:273]:   State: OFF
[02:35:45][D][light:303]:   Transition Length: 1.0s
[02:35:52][D][light:264]: 'Brightness Middle' Setting:
[02:35:52][D][light:273]:   State: ON
[02:35:52][D][light:277]:   Brightness: 14%
[02:35:52][D][light:303]:   Transition Length: 1.0s
[02:35:52][D][main:286]: off event
[02:35:55][D][light:264]: 'Brightness Middle' Setting:
[02:35:55][D][light:277]:   Brightness: 53%
[02:35:55][D][light:303]:   Transition Length: 1.0s
[02:35:55][D][main:276]: on event
[02:37:05][D][light:264]: 'Brightness Middle' Setting:
[02:37:05][D][light:303]:   Transition Length: 1.0s
[02:37:07][D][light:264]: 'Brightness Middle' Setting:
[02:37:07][D][light:273]:   State: OFF
[02:37:07][D][light:303]:   Transition Length: 1.0s
[02:37:09][D][light:264]: 'Brightness Middle' Setting:
[02:37:09][D][light:273]:   State: ON
[02:37:09][D][light:303]:   Transition Length: 1.0s
[02:37:09][D][main:286]: off event
[02:37:10][D][light:264]: 'Brightness Middle' Setting:
[02:37:10][D][light:273]:   State: OFF
[02:37:10][D][light:303]:   Transition Length: 1.0s
[02:37:10][D][main:276]: on event

```

**Additional information and things you've tried:**

***YAML-Config expected behaviour using the Homeassistant Web-UI:***
When the brightness of "Brightness Desk" is changed or it is switched On, the switch `power_desk` should also be switched on.

An update to the ESP (see log) that contains `State: OFF` should be immediately followed by the message `off event`.
An update to the ESP (see log) that contains `State: ON` should be immediately followed by the message `on event`.

***Actual behavior:***
Seemingly random On/Off switching with brightness transitions that do not end in the light actually switching off.

### LINKED ISSUE #1526: light.on_turn_off / light .on_turn_on firing inappropriately or binary light not working correctly
**Operating environment/Installation (Hass.io/Docker/pip/etc.):**
Hass.io

**ESP (ESP32/ESP8266, Board/Sonoff):**
ESP12-F

**ESPHome version (latest production, beta, dev branch)**
dev

**Affected component:**
light

**Description of problem:**
If the light is on, calling turn_on with a brightness of 100% or 10% causes the locatorled to turn on

**Problem-relevant YAML-configuration entries:**
```yaml
        - light.turn_on:
            id: light1
            brightness: 100%

        - light.turn_on:
            id: light1
            brightness: 10%

light:
  - platform: binary
    name: "Locator LED"
    output: locatorledpin
    id: locatorled
    internal: true
  - platform: monochromatic
    id: light1
    output: dimmer1
    name: Dimmerized Light
    on_turn_on:
      - light.turn_off: locatorled
    on_turn_off:
      - light.turn_on: locatorled

```

**Logs (if applicable):**

```
PASTE DEBUG LOG HERE
[17:43:48][D][light:264]: 'Dimmerized Light' Setting:
[17:43:48][D][light:277]:   Brightness: 100%
[17:43:48][D][light:303]:   Transition Length: 1.0s
[17:43:48][D][light:264]: 'Locator LED' Setting:
[17:43:48][D][light:273]:   State: OFF
[17:43:55][D][light:264]: 'Dimmerized Light' Setting:
[17:43:55][D][light:277]:   Brightness: 10%
[17:43:55][D][light:303]:   Transition Length: 1.0s
[locatorled is turned on during the 17:43:55 logs]





**Additional information and things you've tried:**




<!-- LEAVE THIS LINE AS-IS AND DON'T DELETE IT, OTHERWISE THE ISSUE WILL BE CLOSED AUTOMATICALLY. -->

### LINKED ISSUE #1534: Light On_turn_on and On_turn_off get switched after reboot
**Operating environment/Installation (Hass.io/Docker/pip/etc.):**

Hassio supervised on Raspbian (I know, it's been running since before HassOS and I'm busy with a migration plan to move away from it)
**ESP (ESP32/ESP8266, Board/Sonoff):**

TYWE3L specifically a Calex a60 smart light bulb (it should be a ESP8266)
**ESPHome version (latest production, beta, dev branch)**

ESPHome version 1.15 and 1.16-dev
**Affected component:**

Light specifically automation that deal with it such as on_turn_on and on_boot

**Description of problem:**

Scripting seems to be very wonky, I want my lightbulbs to automatically turn on when they are powered. That way I have an emergency way of turning the light bulb on (just turn the power on and off)

After a hard reboot on_turn_on seems to switch meaning. my automation now runs on_turn_off. Something which is quite undesirable when trying to turn things off after turning them on

The general idea of this device is disconnecting it shortly activates the light on the toilet. Since it's a toilet light it can usually be deactivated after a few minutes of being turned on.

**Problem-relevant YAML-configuration entries:**
```yaml
PASTE YAML FILE HERE

substitutions:
  devicename: toilet_lamp
  upper_devicename: "Toilet Lamp" 

esphome:
  name: ${devicename}
  platform: ESP8266
  board: esp01_1m
  on_boot:
    priority: 600
    # ...
    then:
      - light.turn_on: ${devicename}
      
wifi:
  ssid: REDACTED
  password: REDACTED

  # Enable fallback hotspot (captive portal) in case wifi connection fails
  ap:
    ssid: "${upper_devicename} Fallback Hotspot"
    password: REDACTED
captive_portal:

# Enable logging
logger:

# Enable Home Assistant API
api:

ota:

web_server:
  port: 80
  
globals:
    - id: pi
      type: float
      restore_value: no
      initial_value: '3.14159'
    - id: light_activated_by_pir
      type: bool
      initial_value: "false"
      
sensor:
  - platform: wifi_signal
    name: "${upper_devicename} signal strength"
    update_interval: 10s
    id: ${devicename}_wifi_dB
    
binary_sensor:
  - platform: gpio
    pin: 15
    name: "${upper_devicename} PIR Sensor"
    id:   ${devicename}_pir
    device_class: motion
    filters:
    on_press:
              then:
              - light.turn_on: ${devicename}
              - lambda: 'id(light_activated_by_pir) = true;'
    on_release:
        then:
          - if:
              condition:
               - lambda: 'return id(light_activated_by_pir);'
              then:
                - light.turn_off: ${devicename}
                - lambda: 'id(light_activated_by_pir) = false;'
                

light:
  - platform: rgbww
    name: ${upper_devicename}
    id: ${devicename}
    red: output_red
    green: output_green
    blue: output_blue
    cold_white: output_white
    warm_white: output_warmwhite
    cold_white_color_temperature: 4000 K
    warm_white_color_temperature: 2200 K
    on_turn_on:
      then:
      - delay: 10s
      - logger.log: tick
      - delay: 10s
      - logger.log: tick
      - delay: 10s
      #- delay: 2min
      - light.turn_off: ${devicename}

output:
  - platform: esp8266_pwm
    id: output_red
    pin: 4
  - platform: esp8266_pwm
    id: output_green
    pin: 12
  - platform: esp8266_pwm
    id: output_blue
    pin: 14
  - platform: esp8266_pwm
    id: output_white
    pin: 5
  - platform: esp8266_pwm
    id: output_warmwhite
    pin: 13

**Logs (if applicable):**
<!--
Please copy the debug log here. If possible, also connect to the ESP over USB and copy those logs into the backticks.
-->
```
PASTE DEBUG LOG HERE

```
[17:24:55][C][logger:185]: Logger:
[17:24:55][C][logger:186]:   Level: DEBUG
[17:24:55][C][logger:187]:   Log Baud Rate: 115200
[17:24:55][C][logger:188]:   Hardware UART: UART0
[17:24:55][C][light:177]: Light 'Toilet Lamp'
[17:24:55][C][light:179]:   Default Transition Length: 1.0s
[17:24:55][C][light:180]:   Gamma Correct: 2.80
[17:24:55][C][light:183]:   Min Mireds: 250.0
[17:24:55][C][light:184]:   Max Mireds: 454.5
[17:24:55][C][captive_portal:169]: Captive Portal:
[17:24:55][C][web_server:132]: Web Server:
[17:24:55][C][web_server:133]:   Address: toilet_lamp.local:80
[17:24:55][C][ota:029]: Over-The-Air Updates:
[17:24:55][C][ota:030]:   Address: toilet_lamp.local:8266
[17:24:55][C][api:095]: API Server:
[17:24:55][C][api:096]:   Address: toilet_lamp.local:6053
[17:24:55][C][wifi_signal.sensor:009]: WiFi Signal 'Toilet Lamp signal strength'
[17:24:55][C][wifi_signal.sensor:009]:   Unit of Measurement: 'dB'
[17:24:55][C][wifi_signal.sensor:009]:   Accuracy Decimals: 0
[17:24:55][C][wifi_signal.sensor:009]:   Icon: 'mdi:wifi'
[17:24:57][D][sensor:092]: 'Toilet Lamp signal strength': Sending state -49.00000 dB with 0 decimals of accuracy
[17:25:02][D][main:377]: tick
[17:25:07][D][api.connection:604]: Client 'Home Assistant 0.115.3 (192.168.10.254)' connected successfully!
[17:25:07][D][sensor:092]: 'Toilet Lamp signal strength': Sending state -49.00000 dB with 0 decimals of accuracy
[17:25:12][D][main:383]: tick
[17:25:12][D][light:264]: 'Toilet Lamp' Setting:
[17:25:12][D][light:273]:   State: OFF
[17:25:12][D][light:303]:   Transition Length: 1.0s
WARNING Disconnected from API: Timeout while waiting for message response!
INFO Connecting to toilet_lamp.local:6053 (192.168.10.194)
WARNING Couldn't connect to API (Error connecting to 192.168.10.194: timed out). Trying to reconnect in 1 seconds
INFO Connecting to toilet_lamp.local:6053 (192.168.10.194)
INFO Successfully connected to toilet_lamp.local
[17:26:06][D][sensor:092]: 'Toilet Lamp signal strength': Sending state -49.00000 dB with 0 decimals of accuracy
[17:26:16][D][sensor:092]: 'Toilet Lamp signal strength': Sending state -49.00000 dB with 0 decimals of accuracy
[17:26:26][D][sensor:092]: 'Toilet Lamp signal strength': Sending state -50.00000 dB with 0 decimals of accuracy
[17:26:32][D][light:264]: 'Toilet Lamp' Setting:
[17:26:32][D][light:273]:   State: OFF
[17:26:32][D][light:303]:   Transition Length: 1.0s
[17:26:36][D][sensor:092]: 'Toilet Lamp signal strength': Sending state -49.00000 dB with 0 decimals of accuracy
[17:26:42][D][main:371]: tick
[17:26:46][D][sensor:092]: 'Toilet Lamp signal strength': Sending state -50.00000 dB with 0 decimals of accuracy
[17:26:52][D][main:377]: tick
[17:26:56][D][sensor:092]: 'Toilet Lamp signal strength': Sending state -50.00000 dB with 0 decimals of accuracy
[17:27:02][D][main:383]: tick
[17:27:02][D][light:264]: 'Toilet Lamp' Setting:
[17:27:02][D][light:303]:   Transition Length: 1.0s
[17:27:06][D][sensor:092]: 'Toilet Lamp signal strength': Sending state -50.00000 dB with 0 decimals of accuracy
[17:27:08][D][light:264]: 'Toilet Lamp' Setting:
[17:27:08][D][light:273]:   State: ON
[17:27:08][D][light:303]:   Transition Length: 1.0s
[17:27:16][D][sensor:092]: 'Toilet Lamp signal strength': Sending state -49.00000 dB with 0 decimals of accuracy
[17:27:26][D][sensor:092]: 'Toilet Lamp signal strength': Sending state -49.00000 dB with 0 decimals of accuracy
[17:27:36][D][sensor:092]: 'Toilet Lamp signal strength': Sending state -50.00000 dB with 0 decimals of accuracy
[17:27:46][D][sensor:092]: 'Toilet Lamp signal strength': Sending state -50.00000 dB with 0 decimals of accuracy
[17:27:48][I][ota:046]: Boot seems successful, resetting boot loop counter.
[17:27:49][D][light:264]: 'Toilet Lamp' Setting:
[17:27:49][D][light:273]:   State: OFF
[17:27:49][D][light:303]:   Transition Length: 1.0s
[17:27:56][D][sensor:092]: 'Toilet Lamp signal strength': Sending state -51.00000 dB with 0 decimals of accuracy
[17:27:59][D][main:371]: tick
[17:28:06][D][sensor:092]: 'Toilet Lamp signal strength': Sending state -50.00000 dB with 0 decimals of accuracy
[17:28:09][D][main:377]: tick
```
**Additional information and things you've tried:**

I've also tried moving to 1.16.0-dev since I saw there were some recent changes to light automation.

I've tried changing on_turn_on into on_turn_off which seems to work except for the first time the light is turned on at boot. resulting in below:
```
[17:49:07][D][api.connection:604]: Client 'Home Assistant 0.115.3 (192.168.10.254)' connected successfully!
[17:49:10][D][sensor:092]: 'Toilet Lamp signal strength': Sending state -51.00000 dB with 0 decimals of accuracy
[17:49:18][D][light:264]: 'Toilet Lamp' Setting:
[17:49:18][D][light:273]:   State: OFF
[17:49:18][D][light:303]:   Transition Length: 1.0s
[17:49:20][D][sensor:092]: 'Toilet Lamp signal strength': Sending state -51.00000 dB with 0 decimals of accuracy
[17:49:30][D][sensor:092]: 'Toilet Lamp signal strength': Sending state -51.00000 dB with 0 decimals of accuracy
[17:49:40][D][sensor:092]: 'Toilet Lamp signal strength': Sending state -51.00000 dB with 0 decimals of accuracy
[17:49:41][D][light:264]: 'Toilet Lamp' Setting:
[17:49:41][D][light:273]:   State: ON
[17:49:41][D][light:303]:   Transition Length: 1.0s
[17:49:41][D][main:362]: tick
[17:49:50][D][sensor:092]: 'Toilet Lamp signal strength': Sending state -51.00000 dB with 0 decimals of accuracy
[17:49:51][D][main:381]: tick
[17:50:00][D][sensor:092]: 'Toilet Lamp signal strength': Sending state -52.00000 dB with 0 decimals of accuracy
[17:50:01][D][main:387]: tick
[17:50:10][D][sensor:092]: 'Toilet Lamp signal strength': Sending state -51.00000 dB with 0 decimals of accuracy
[17:50:11][D][main:393]: tick
[17:50:11][D][light:264]: 'Toilet Lamp' Setting:
[17:50:11][D][light:273]:   State: OFF
[17:50:11][D][light:303]:   Transition Length: 1.0s
```

For now I'm going to write a script for delayed off and couple it with each and every on action manually. I'm afraid the miss ain't too happy with me experimenting on the bathroom light already so further testing might be difficult.

### PR DESCRIPTION
**Pull request by MartinWelsch**
## Description:

The trigger `on_turn_on` now triggers immediately when the light is turned on.
The trigger `on_turn_off` now triggers after the light is actually off.

**Related issue (if applicable):** fixes https://github.com/esphome/issues/issues/1521
fixes https://github.com/esphome/issues/issues/1526
fixes https://github.com/esphome/issues/issues/1534

**Pull request in [esphome-docs](https://github.com/esphome/esphome-docs) with documentation (if applicable):**

## Checklist:
  - [x] The code change is tested and works locally.
  - [ ] Tests have been added to verify that the new code works (under `tests/` folder).

If user exposed functionality or configuration variables are added/changed:
  - [ ] Documentation added/updated in [esphome-docs](https://github.com/esphome/esphome-docs).

### CODE REVIEW

File: esphome/components/light/light_transformer.h [hunk 1]
```diff
@@ -65,7 +65,7 @@ class LightTransitionTransformer : public LightTransformer {
     return LightColorValues::lerp(this->get_start_values_(), this->get_target_values_(), v);
   }
 
-  bool publish_at_end() override { return false; }
+  bool publish_at_end() override { return true; }
```
Comment (glmnet) [inline esphome/components/light/light_transformer.h:68]: This makes publish at end true in all (2) overriden cases

Comment (MartinWelsch) [reply esphome/components/light/light_transformer.h:68]: I can't find any classes deriving from this but i guess that this does not match with the documented behavior of `add_new_remote_values_callback`, so i added the callback `target_state_reached_callback_` which does not involve publishing.

**Comment by MaartenKleijwegt** [comment]
Just did some quick tests, but this also seems to fix https://github.com/esphome/issues/issues/1534. With the quick tests I've done I'm not seeing the erratic behavior anymore

might this also fix https://github.com/esphome/issues/issues/1526 ?

File: esphome/components/light/light_state.cpp [hunk 2]
```diff
@@ -145,6 +145,8 @@ void LightState::loop() {
   if (this->transformer_ != nullptr) {
     if (this->transformer_->is_finished()) {
       this->remote_values = this->current_values = this->transformer_->get_end_values();
+      ESP_LOGD(TAG, "Reached the target state of %.5f.", this->current_values.get_state());
```
Comment (glmnet) [inline esphome/components/light/light_state.cpp:148]: Will need to change to lower verbosity or remove before merge

File: esphome/components/light/automation.h [hunk 3]
```diff
@@ -122,18 +123,18 @@ class LightTurnOnTrigger : public Trigger<> {
...
       // Set new state immediately so that trigger() doesn't devolve
       // into infinite loop
-      last_on_ = is_on;
+      this->last_on_ = is_on;
       if (should_trigger) {
         this->trigger();
       }
     });
-    last_on_ = a_light->current_values.is_on();
+    this->last_on_ = a_light->current_values.is_on();
```
Comment (glmnet) [inline esphome/components/light/automation.h:137]: This should still happen on `new_remote_values_callback` otherwise this state is not updated if light is turned on -> turned off before it fully turns on and hence `should_trigger` does not set

**Review by glmnet — CHANGES_REQUESTED** [review]
On turn off is not working properly

File: esphome/components/light/automation.h (hunk 3 above)
Comment (MartinWelsch) [reply esphome/components/light/automation.h:137]: The problem with `new_remote_values_callback` in case of `LightTurnOffTrigger` is that it is called before `a_light->current_values` is updated (due to transitions), so `a_light->current_values.is_on()` returns `true` when the light is turned off. If the remote value is used, the trigger would get triggered too early (before the transition finishes).
Your statement regarding not triggering for rapid switching is correct, missed that while testing.

It turns out that because of `target_state_reached_callback` being only called when a transition finishes, keeping track of the last on/off-state is not needed because there is no transition to `off` that does not result in the light emitting no light.

Comment (glmnet) [reply esphome/components/light/automation.h]: Thanks, this clears up possible breaking changes and now it seems more streamlined.
Note that on_turn_on might re - trigger if you turn off then quickly back turn on again, however I don't think this is a problem.
