### PR TITLE
atm90e32: make the total_increasing class sensors actually be increasing totals.

### LINKED ISSUE #2523: atm90e32 driver "Foward Active Energy" doesn't work the way homeassistant expects
### The problem

The 'Foward Active Energy' counters (and presumably the reverse ones as well) report themselves to HA as having a state class of 'total_increasing', which I believe means that HA expects them to be a cumulative total, like a utility electricity meter. If the counter decreases then I think HA assumes the device as been replaced or reset, and takes the last number before the decrease as a baseline and then adds the new cumulative total to that for the HA internal cumulative total used in the long-term stats.

What these counters actually do with the current code is return the amount of energy consumed _since the last update_. This means that HA sees a very small total with frequent random resets (when consumption for an update period happens to be less than the last period), and produces nothing useful in the energy dashboard.

What I think needs to happen is for ESPHome to keep an internal cumulative total of these registers which it reports back to HA. An alternative might be to report an extra 0 reading for them after every actual reading, so that HA thinks the device is continually be resetting on every update. I think the internal sum is probably preferable, particularly as then it doesn't matter if HA misses some updates.

(I'm assuming this is a result of the change where last_reset was dropped).

### Which version of ESPHome has the issue?

2021.9.2

### What type of installation are you using?

pip

### Which version of Home Assistant has the issue?

2021.9.7

### What platform are you using?

ESP32

### Board

nodemcu-32s

### Component causing the issue

atm90e32

### Example YAML snippet

```yaml
// This is basically just the example for the CircuitSetup Split Single Phase Energy Meter from https://esphome.io/components/sensor/atm90e32.html just with my calibrations and the forward_active_energy and reverse_active_energy sensors activated

sensor:
  - platform: atm90e32
    cs_pin: 5
    phase_a:
      voltage:
        name: "EMON Line Voltage A"
      current:
        name: "EMON CT1 Current"
      power:
        name: "EMON Active Power CT1"
      reactive_power:
        name: "EMON Reactive Power CT1"
      power_factor:
        name: "EMON Power Factor CT1"
      forward_active_energy:
        name: "EMON Foward Active Energy CT1"
      reverse_active_energy:
        name: "EMON Reverse Active Energy CT1"
      gain_voltage: 8080
      gain_ct: 24270
    phase_c:
      voltage:
        name: "EMON Line Voltage B"
      current:
        name: "EMON CT2 Current"
      power:
        name: "EMON Active Power CT2"
      reactive_power:
        name: "EMON Reactive Power CT2"
      power_factor:
        name: "EMON Power Factor CT2"
      forward_active_energy:
        name: "EMON Foward Active Energy CT2"
      reverse_active_energy:
        name: "EMON Reverse Active Energy CT2"
      gain_voltage: 8080
      gain_ct: 24270
    frequency:
      name: "EMON Line Frequency"
    chip_temperature:
      name: "EMON Chip Temperature"
    line_frequency: 50Hz
    current_phases: 2
    gain_pga: 2X
    update_interval: 30s
```

### Anything in the logs that might be useful for us?

_No response_

### Additional information

_No response_

### PR DESCRIPTION
**Pull request by davidmonro**
# What does this implement/fix? 

Changes the atm90e32 forward/reverse active energy sensors to be cumulative totals as expected by home-assistant for a sensor with the TOTAL_INCREASING state class

## Types of changes

- [X] Bugfix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] Other

**Related issue or feature (if applicable):** fixes https://github.com/esphome/issues/issues/2523

**Pull request in [esphome-docs](https://github.com/esphome/esphome-docs) with documentation (if applicable):** esphome/esphome-docs#<esphome-docs PR number goes here>

## Test Environment

- [X] ESP32
- [ ] ESP8266

## Example entry for `config.yaml`:

```yaml
# Example config.yaml
sensor:
  - platform: atm90e32
    cs_pin: 5
    phase_a:
      voltage:
        name: "EMON Line Voltage A"
      current:
        name: "EMON CT1 Current"
      power:
        name: "EMON Active Power CT1"
      reactive_power:
        name: "EMON Reactive Power CT1"
      power_factor:
        name: "EMON Power Factor CT1"
      forward_active_energy:
        name: "EMON Foward Active Energy CT1"
      reverse_active_energy:
        name: "EMON Reverse Active Energy CT1"
      gain_voltage: 8080
      gain_ct: 24270
    phase_c:
      voltage:
        name: "EMON Line Voltage B"
      current:
        name: "EMON CT2 Current"
      power:
        name: "EMON Active Power CT2"
      reactive_power:
        name: "EMON Reactive Power CT2"
      power_factor:
        name: "EMON Power Factor CT2"
      forward_active_energy:
        name: "EMON Foward Active Energy CT2"
      reverse_active_energy:
        name: "EMON Reverse Active Energy CT2"
      gain_voltage: 8080
      gain_ct: 24270
    frequency:
      name: "EMON Line Frequency"
    chip_temperature:
      name: "EMON Chip Temperature"
    line_frequency: 50Hz
    current_phases: 2
    gain_pga: 2X
    update_interval: 30s

```

## Checklist:
  - [X] The code change is tested and works locally.
  - [ ] Tests have been added to verify that the new code works (under `tests/` folder).
  
If user exposed functionality or configuration variables are added/changed:
  - [ ] Documentation added/updated in [esphome-docs](https://github.com/esphome/esphome-docs).

### CODE REVIEW

File: esphome/components/atm90e32/atm90e32.cpp [hunk 1]
```diff
@@ -265,27 +265,57 @@ float ATM90E32Component::get_power_factor_c_() {
 }
 float ATM90E32Component::get_forward_active_energy_a_() {
   uint16_t val = this->read16_(ATM90E32_REGISTER_APENERGYA);
-  return (float) val * 10 / 3200;  // convert register value to WattHours
+  if ((UINT32_MAX - this->phase_[0].cumulative_forward_active_energy_) > val) {
```
Comment (OttoWinter) [inline esphome/components/atm90e32/atm90e32.cpp:268]: Could you explain this sentence a bit more:

> What these counters actually do with the current code is return the amount of energy consumed since the _last update_

(https://github.com/esphome/issues/issues/2523)

Does `the last update` here mean since the last time the register was read? Or does update happen at a fixed interval like 1min?

Comment (davidmonro) [reply esphome/components/atm90e32/atm90e32.cpp:268]: Yes, since the time it was read (which would have been the last time we sent an update to HA)

**Review by OttoWinter — APPROVED** [review]

**Comment by OttoWinter** [comment]
Thanks!
