### PR TITLE
Fixed rc_switch dump off by one bit

### LINKED ISSUE #482: RC Switch Raw Dump is one bit off
**Operating environment/Installation (Hass.io/Docker/pip/etc.):**

pip on Ubuntu 19.04

**ESP (ESP32/ESP8266, Board/Sonoff):**

ESP8266 12E

**Affected component:**

[Remote Receiver](https://esphome.io/components/remote_receiver.html)

**Description of problem:**
The dumped output of the rc_switch codes appears to be one bit off, shifted right one bit, losing the least significant bit and having an extra leading zero. Verified by trying to transmit a code from an ESP running the remote_transmitter and receiving it on another ESP right along side. Also confirmed by using a simple sketch directly in Arduino IDE.

**Problem-relevant YAML-configuration entries:**
This code being transmitted:
```yaml
  turn_on_action:
    - remote_transmitter.transmit_rc_switch_raw:
        code: "01001011110101011010011000100010"
        protocol: 1
        repeat:
          times: 6
          wait_time: 0.5s

```
Results in this being received:

**Logs (if applicable):**

```
[19:49:51][D][remote.rc_switch:249]: Received RCSwitch Raw: protocol=1 data='00100101111010101101001100010001'
[19:49:54][D][remote.rc_switch:249]: Received RCSwitch Raw: protocol=1 data='00100101111010101101001100010001'
[19:49:54][D][remote.rc_switch:249]: Received RCSwitch Raw: protocol=1 data='00100101111010101101001100010001'
[19:49:54][D][remote.rc_switch:249]: Received RCSwitch Raw: protocol=1 data='00100101111010101101001100010001'
[19:49:54][D][remote.rc_switch:249]: Received RCSwitch Raw: protocol=1 data='00100101111010101101001100010001'
[19:49:54][D][remote.rc_switch:249]: Received RCSwitch Raw: protocol=1 data='00100101111010101101001100010001'

```

**Additional information and things you've tried:**
I'm looking into the code now to figure this one out, will send a PR if I get it fixed.

### PR DESCRIPTION
**Pull request by mtl010957**
## Description:
Found that the rc_switch dump raw output is off by one bit, the logic just needed to be changed to push the next received bit first and then shift the result left.

**Related issue (if applicable):** fixes [RC Switch Raw Dump is one bit off #482 ](https://github.com/esphome/issues/issues/482)

**Pull request in [esphome-docs](https://github.com/esphome/esphome-docs) with documentation (if applicable):** esphome/esphome-docs#<esphome-docs PR number goes here>

## Checklist:
  - [X] The code change is tested and works locally.
  - [ ] Tests have been added to verify that the new code works (under `tests/` folder).

If user exposed functionality or configuration variables are added/changed:
  - [ ] Documentation added/updated in [esphome-docs](https://github.com/esphome/esphome-docs).

### CODE REVIEW

File: esphome/components/remote_base/rc_switch_protocol.cpp [hunk 1]
```diff
@@ -115,11 +115,11 @@ bool RCSwitchBase::decode(RemoteReceiveData &src, uint32_t *out_data, uint8_t *o
   *out_data = 0;
   for (*out_nbits = 1; *out_nbits < 32; *out_nbits += 1) {
     if (this->expect_zero(src)) {
-      *out_data <<= 1;
       *out_data |= 0;
-    } else if (this->expect_one(src)) {
       *out_data <<= 1;
+    } else if (this->expect_one(src)) {
       *out_data |= 1;
+      *out_data <<= 1;
```
Comment (OttoWinter) [inline esphome/components/remote_base/rc_switch_protocol.cpp]: Uhm, the current code looks ok to me.

If anything, the _updated_ code is wrong - for example the LSB will never be set with the new code.

Comment (glmnet) [reply esphome/components/remote_base/rc_switch_protocol.cpp]: Isn't that for loop iterating only 31 times? isn't the code 32 bits?

Comment (OttoWinter) [reply esphome/components/remote_base/rc_switch_protocol.cpp]: Correct! There's the issue!

Comment (mtl010957) [reply esphome/components/remote_base/rc_switch_protocol.cpp]: It seems the loop only iterates 31 times, but changing the end count to 33 causes buffer overruns and boot looping, and when I can get it to actually receive a value the result clearly shows it's getting 33 bits, I need to dig some more.

Comment (OttoWinter) [reply esphome/components/remote_base/rc_switch_protocol.cpp]: @mtl010957 The issue will be that `out_nbits` doesn't get decremented again in the exit branch.

Cleaner code might look like this:

```cpp
for (*out_nbits = 0; *out_nbits < 32; *out_nbits += 1) {
  if (this->expect_zero(src)) {
    *out_data <<= 1;
    *out_data |= 0;
  } else if (this->expect_one(src)) {
    *out_data <<= 1;
    *out_data |= 0;
  } else {
    return *out_nbits >= 8;
  }
}
return true;
```

Comment (mtl010957) [reply esphome/components/remote_base/rc_switch_protocol.cpp]: @OttoWinter  Yes, that's definitely the trick, thanks! I was not getting my head wrapped around the logic and totally missed that decrementing of out_nbits. My patch is updated to this now and it works as expected.

**Review by OttoWinter — APPROVED** [review]
