### PR TITLE
tuya_light: fix float->int conversion while setting color temperature

### LINKED ISSUE #4669: tuya_light: getting color temperature from another MCU makes the device uncontrollable
### The problem

If **color_temperature_invert** is set to true, when user sets color temperature using the IR remote, the ceiling light get stuck in a certain state: 
- the device does not respond to IR remote
- log is flooded by endlessly repeating messages (see Logs section)

 The only way to leave this state is switch off the light via REST API double times, because the first request to switch it off does not work. 

Without the option  **color_temperature_invert** the ceiling light works without any issues

### Which version of ESPHome has the issue?

2023.6.3

### What type of installation are you using?

pip

### Which version of Home Assistant has the issue?

_No response_

### What platform are you using?

ESP8266

### Board

nodemcuv2

### Component causing the issue

tuya_light

### Example YAML snippet

```yaml
esp8266:
  board: nodemcuv2

logger:
  baud_rate: 0

uart:
  rx_pin: GPIO3
  tx_pin: GPIO1
  baud_rate: 115200

# Register the Tuya MCU connection
tuya:

light:
  - platform: "tuya"
    name: "Remez Leda"
    switch_datapoint: 20
    dimmer_datapoint: 22
    max_value: 1000
    color_temperature_datapoint: 23
    color_temperature_max_value: 1000
    cold_white_color_temperature: 154 mireds
    warm_white_color_temperature: 333 mireds
    color_temperature_invert: true
```

### Anything in the logs that might be useful for us?

```txt
Endlessly repeating:
[14:10:03][V][tuya:127]: Received Tuya: CMD=0x07 VERSION=3 DATA=[17.02.00.04.00.00.00.14 (8)] INIT_STATE=5

########################## Attention to this message ###########################
[14:10:03][D][tuya:312]: Datapoint 23 update to 20  
################################################################################

[14:10:03][D][light:036]: 'Remez Leda' Setting:                                 
[14:10:03][D][light:066]:   Color temperature: 329.4 mireds                     
[14:10:03][VV][api.service:122]: send_light_state_response: LightStateResponse {
  key: 3248337769                                                               
  state: YES                                                                    
  brightness: 1                                                                 
  color_mode: COLOR_MODE_COLOR_TEMPERATURE                                      
  color_brightness: 1                                                           
  red: 1                                                                        
  green: 1                                                                      
  blue: 1                                                                       
  white: 1                                                                      
  color_temperature: 329.42                                                     
  cold_white: 1                                                                 
  warm_white: 1                                                                 
  effect: ''                                                                    
}                                                                               
[14:10:03][V][tuya:407]: Sending Tuya: CMD=0x06 VERSION=0 DATA=[17.02.00.04.00.00.00.15 (8)] INIT_STATE=5

########################## Attention to this message ###########################
[14:10:03][D][tuya:593]: Setting datapoint 23 to 21 
################################################################################

[14:10:03][D][tuya:593]: Setting datapoint 22 to 1000                           
[14:10:03][V][tuya:601]: Not sending unchanged value                            
[14:10:03][D][tuya:593]: Setting datapoint 20 to 1                              
[14:10:03][V][tuya:601]: Not sending unchanged value                            
[14:10:03][V][tuya:127]: Received Tuya: CMD=0x07 VERSION=3 DATA=[17.02.00.04.00.00.00.14 (8)] INIT_STATE=5
[14:10:03][D][tuya:312]: Datapoint 23 update to 20                              
[14:10:03][D][light:036]: 'Remez Leda' Setting:                                 
[14:10:03][D][light:066]:   Color temperature: 329.4 mireds
```

### Additional information

_No response_

### PR DESCRIPTION
**Pull request by kswt**
# What does this implement/fix?
This PR fixes the conversion of the color temperature (CT) value between the components **light** and **tuya_light**. **Light** uses **float** datatype, but **tuya_light** uses **int**.  In order to send to Tuya device exactly the same value that was read from it before, converted value must be rounded instead of simple int casting.

## Types of changes

- [x] Bugfix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] Other

**Related issue or feature (if applicable):** fixes https://github.com/esphome/issues/issues/4669

## Test Environment

- [ ] ESP32
- [ ] ESP32 IDF
- [x] ESP8266
- [ ] RP2040

## Example entry for `config.yaml`:

```yaml
esp8266:
  board: nodemcuv2

logger:
  baud_rate: 0

uart:
  rx_pin: GPIO3
  tx_pin: GPIO1
  baud_rate: 115200

# Register the Tuya MCU connection
tuya:

light:
  - platform: "tuya"
    name: "Remez Leda"
    switch_datapoint: 20
    dimmer_datapoint: 22
    max_value: 1000
    color_temperature_datapoint: 23
    color_temperature_max_value: 1000
    cold_white_color_temperature: 154 mireds
    warm_white_color_temperature: 333 mireds
    color_temperature_invert: true

```

## Checklist:
  - [x] The code change is tested and works locally.
  - [ ] Tests have been added to verify that the new code works (under `tests/` folder).

### CODE REVIEW

File: esphome/components/tuya/light/tuya_light.cpp [hunk 1]
```diff
@@ -168,7 +168,7 @@ void TuyaLight::write_state(light::LightState *state) {
 
   if (brightness > 0.0f || !color_interlock_) {
     if (this->color_temperature_id_.has_value()) {
-      uint32_t color_temp_int = static_cast<uint32_t>(color_temperature * this->color_temperature_max_value_);
+      uint32_t color_temp_int = static_cast<uint32_t>(round(color_temperature * this->color_temperature_max_value_));
```
Comment (jesserockz) [inline esphome/components/tuya/light/tuya_light.cpp]:
```suggestion
      uint32_t color_temp_int = static_cast<uint32_t>(roundf(color_temperature * this->color_temperature_max_value_));
```

**Review by jesserockz — APPROVED** [review]
