### PR TITLE
[http_request] Retry update check on startup until network is ready

### LINKED ISSUE #14227: Network not connected, skipping update check *before* Wi-Fi connects
### The problem

The update OTA http_request does not perform the requisite manifest JSON request, it gives up right before Wi-Fi is connected, and nothing happens.

It's weird because I can see in the code that the priority of setup is after Wi-Fi.

https://github.com/esphome/esphome/blob/fb6c7d81d5b3832c19eb1dd7b61c70a944742d8a/esphome/components/http_request/update/http_request_update.h#L30

### Which version of ESPHome has the issue?

2026.2.1

### What type of installation are you using?

pip

### What platform are you using?

ESP32

### Component causing the issue

ota/http_request

### YAML Config

```yaml
# Currently trying this with ESPHome dev.

substitutions:
  name: living-room-music-player
  friendly_name: Living room music player
  area: Living room
  sample_rate: 44100
  # There is still room to reduce the buffer duration.
  # Although at a quarter second, responsiveness is quite okay.
  speaker_buffer_duration: 250ms
  media_player_buffer_size: 44100 # 0.25 seconds of CD-quality stereo audio.
  speaker_timeout: 250ms
  task_stack_in_psram: false
  codec_support: false
  format: WAV

esphome:
  name: ${name}
  area: ${area}
  friendly_name: ${friendly_name}
  name_add_mac_suffix: false
  platformio_options:
    board_build.arduino.memory_type: qio_opi

esp32:
  # Ju Jiasheng ESP32-S3-N16R8 from AliExpress.
  board: esp32-s3-devkitc-1
  cpu_frequency: 240MHz
  framework:
    type: esp-idf

packages:
  - !include packages/manage.yaml
  - !include packages/observe.yaml
  - !include packages/devtemp.yaml
  - !include packages/log-debug.yaml


# https://github.com/esphome/esphome/pull/12284#issuecomment-3929269125
external_components:
  - source:
      # https://github.com/esphome/esphome/pull/12429
      type: git
      url: https://github.com/esphome/esphome
      ref: a6c403deb7603d316dce2820897902e01c3695cc
    refresh: 0s
    components: [file, http_request, media_source, speaker_source]
  - source:
      # https://github.com/esphome/esphome/pull/12284
      type: git
      url: https://github.com/esphome/esphome
      ref: 119a5c25a483c58b3d58a35c8cec95495c6491c2
    components: [sendspin]

  # The following sources are merged into the dev branch of ESPHome, but not yet in a release.
  # We've pinned them to their specific squash merge commit id for reproducable builds.
  # These should be available in ESPHome 2026.3.0
  - source:
      # Dev commit hash for squash merge from PR#10212
      type: git
      url: https://github.com/esphome/esphome
      ref: 903971de12c1b291ca8cd367ce5cdf9af8b304ae
    components: [runtime_image]
  - source:
      # Dev commit hash for squash merge from PR#12258
      type: git
      url: https://github.com/esphome/esphome
      ref: 264c8faedd0ab956b0437ec2ecc0bacae1708923
    components: [media_player]
  - source:
      # Dev commit hash for squash merge from PR#14013
      type: git
      url: https://github.com/esphome/esphome
      ref: ba7134ee3f870ce00d2990d84b142b734028330f
    components: [mdns]
  - source:
      # Dev commit hash for squash merge from PR#14108
      type: git
      url: https://github.com/esphome/esphome
      ref: d2026b4cd74bbeb9b86941bf1887f3d93d639387
    components: [audio]
  # For SPDIF (TOSLINK) support:
  - source: github://pr#8065
    components: [i2s_audio]
    refresh: 1h

# Enable Home Assistant API
api:
  encryption:
    key: "NL+q75gOzoTd3brFb0M4j+593AAMD0KqOoeKsdOty1M="
  # Mitigate impact of Wi-Fi loss.
  reboot_timeout: 5min

ota:
  - platform: esphome
    password: "ebc6da18a79782424330d7ee897f304e"

psram:
  ignore_not_found: false
  mode: octal

network:
  enable_high_performance: true

wifi:
  use_psram: true
  domain: .dragonfear
  networks:
  - ssid: !secret wifi_ssid_ent
    eap:
      identity: living-room-music-player.dragonfear
      certificate_authority: wi-fi/ca.pem
      certificate: wi-fi/certs/living-room-music-player/cert.pem
      key: wi-fi/certs/living-room-music-player/key.pem
    priority: 2
  - ssid: !secret wifi_recovery_ssid
    password: !secret wifi_recovery_password
    priority: 0
  fast_connect: true

light:
  - platform: esp32_rmt_led_strip
    rgb_order: GRB
    chipset: WS2812
    pin: GPIO48
    num_leds: 1
    name: "Light"

sensor:
  - platform: sendspin
    type: kalman_error
    name: Kalman error
  - platform: sendspin
    type: audible_syncs
    name: Audible syncs

i2s_audio:
  - id: i2s_bus

speaker:
  # Hardware speaker output
  - platform: i2s_audio
    id: i2s_audio_speaker
    sample_rate: ${sample_rate}
    i2s_dout_pin: GPIO47
    spdif_mode: true
    bits_per_sample: 16bit
    i2s_audio_id: i2s_bus
    dac_type: external
    channel: stereo
    timeout: ${speaker_timeout}
    buffer_duration: ${speaker_buffer_duration}
    use_apll: true

  # Virtual speakers to combine the announcement and media streams together into one output
  - platform: mixer
    id: mixing_speaker
    output_speaker: i2s_audio_speaker
    num_channels: 2
    task_stack_in_psram: ${task_stack_in_psram}
    source_speakers:
      - id: announcement_mixing_input
        timeout: ${speaker_timeout}
        buffer_duration: ${speaker_buffer_duration}
      - id: media_mixing_input
        timeout: ${speaker_timeout}
        buffer_duration: ${speaker_buffer_duration}

  # Virtual speakers to resample each pipeline's audio, if necessary, as the mixer speaker requires the same sample rate
  - platform: resampler
    id: announcement_resampling_speaker
    output_speaker: announcement_mixing_input
    sample_rate: ${sample_rate}
    buffer_duration: ${speaker_buffer_duration}
    task_stack_in_psram: ${task_stack_in_psram}
  - platform: resampler
    id: media_resampling_speaker
    output_speaker: media_mixing_input
    sample_rate: ${sample_rate}
    buffer_duration: ${speaker_buffer_duration}
    task_stack_in_psram: ${task_stack_in_psram}

http_request:

##### Sendspin Configuration
sendspin:
  id: sendspin_hub
  task_stack_in_psram: ${task_stack_in_psram}
  kalman_process_error: 0.01

media_source:
  - platform: sendspin
    id: sendspin_source
    buffer_size: 524288
  - platform: http_request
    id: http_source
    buffer_size: ${media_player_buffer_size}

media_player:
  - platform: speaker_source
    id: external_media_player
    task_stack_in_psram: ${task_stack_in_psram}
    name: None
    announcement_speaker: announcement_resampling_speaker
    media_speaker: media_resampling_speaker
    announcement_pipeline:
      format: ${format}
      num_channels: 1
      sample_rate: ${sample_rate}
    media_pipeline:
      format: ${format}
      num_channels: 2
      sample_rate: ${sample_rate}
    sources:
      - sendspin_source
      - http_source
    on_announcement:
      - mixer_speaker.apply_ducking:
          id: media_mixing_input
          decibel_reduction: 20
          duration: 0.0s
  - platform: sendspin
    id: sendspin_group_media_player
```

### Anything in the logs that might be useful for us?

```txt
[14:56:09][D][light:153]:   Effect: 'Scanning for Wi-Fi'
[14:56:09][D][sensor:118]: 'Device temperature' >> 40.4 °C
[14:56:10][D][wifi:1382]: Found networks:
[14:56:10][I][wifi:1353]: - 'DragonFear CIS WPA3-SAE' [redacted]▂▄▆█ Ch: 1 -63dB P:0
[14:56:10][D][wifi:1739]: Retry phase: INITIAL_CONNECT → SCAN_CONNECTING
[14:56:10][I][wifi:1064]: Connecting to [redacted] [redacted] (priority 0, attempt 1/2 in phase SCAN_CONNECTING)...
[14:56:10][D][http_request.update:045]: Network not connected, skipping update check
[14:56:11][D][esp32.preferences:153]: Writing 1 items: 1 cached, 0 written, 0 failed
[14:56:11][D][sensor:118]: 'Wi-Fi signal strength' >> -60 dBm
[14:56:14][I][wifi:1475]: Connected
[14:56:14][D][wifi:1492]: Disabling AP
[14:56:14][C][wifi:1202]:   IP Address: 10.250.1.45
[14:56:14][C][wifi:1213]:   SSID: [redacted]
[14:56:14]  BSSID: [redacted]
[14:56:14]  Hostname: 'digital-audio-bridge-da3470'
[14:56:14]  Signal strength: -61 dB ▂▄▆█
[14:56:14]  Channel: 1
[14:56:14]  Subnet: 255.255.255.0
[14:56:14]  Gateway: 10.250.1.1
[14:56:14]  DNS1: 10.250.7.2
[14:56:14]  DNS2: 0.0.0.0
```

### Additional information

_No response_

### PR DESCRIPTION
**Pull request by swoboda1337**
# What does this implement/fix?

When the first polling update fires before WiFi has connected, the check is skipped and wont retry for the full update interval (default 6h). This adds initial retry logic that checks every 10s for up to 60s until the network is connected, matching the pattern used by esp32_hosted update.

## Types of changes

- [x] Bugfix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] Developer breaking change (an API change that could break external components)
- [ ] Code quality improvements to existing code or addition of tests
- [ ] Other

**Related issue or feature (if applicable):**

- fixes https://github.com/esphome/esphome/issues/14227

**Pull request in [esphome-docs](https://github.com/esphome/esphome-docs) with documentation (if applicable):**

- N/A

## Test Environment

- [x] ESP32
- [x] ESP32 IDF
- [ ] ESP8266
- [ ] RP2040
- [ ] BK72xx
- [ ] RTL87xx
- [ ] LN882x
- [ ] nRF52840

## Example entry for `config.yaml`:

```yaml
# Example config.yaml
update:
  - platform: http_request
    name: Firmware Update
    source: http://example.com/firmware/manifest.json
```

## Checklist:
  - [x] The code change is tested and works locally.
  - [ ] Tests have been added to verify that the new code works (under `tests/` folder).

If user exposed functionality or configuration variables are added/changed:
  - [ ] Documentation added/updated in [esphome-docs](https://github.com/esphome/esphome-docs).

### CODE REVIEW

File: esphome/components/http_request/update/http_request_update.cpp [hunk 1]
```diff
@@ -45,6 +63,8 @@ void HttpRequestUpdate::update() {
     ESP_LOGD(TAG, "Network not connected, skipping update check");
     return;
   }
+  // Network is up, cancel any pending initial check to prevent duplicate update checks
```
Comment (swoboda1337) [inline esphome/components/http_request/update/http_request_update.cpp]:
```suggestion
```

File: esphome/components/http_request/update/http_request_update.cpp [hunk 2]
```diff
@@ -24,8 +24,26 @@ namespace http_request {
...
+static constexpr uint32_t INITIAL_CHECK_INTERVAL_ID = 0;
+
+void HttpRequestUpdate::setup() {
+  this->ota_parent_->add_state_listener(this);
+
+  // Check every 10s until network is ready (max 6 attempts)
+  // Only if update interval is > 1 minute to avoid redundant checks
+  if (this->get_update_interval() != SCHEDULER_DONT_RUN && this->get_update_interval() > 60000) {
+    this->initial_check_remaining_ = 6;
+    this->set_interval(INITIAL_CHECK_INTERVAL_ID, 10000, [this]() {
```
Comment (bdraco) [inline esphome/components/http_request/update/http_request_update.cpp]: nit: magic numbers should be constexpr

**Review by bdraco — DISMISSED** [review]

**Review by bdraco — APPROVED** [review]

**Comment by swoboda1337** [comment]
Thanks
