### PR TITLE
wpa2 enterprise fixes: also copy eap parameters, don't require psk password to be set

### LINKED ISSUE #1379: esp32 unable to connect to wpa2 enterprise network
**Operating environment/Installation (Hass.io/Docker/pip/etc.):**

Hass.io

**ESP (ESP32/ESP8266, Board/Sonoff):**

ESP32, Board TTGO-T-Beam

**ESPHome version (latest production, beta, dev branch)**

dev branch

**Affected component:**

https://next.esphome.io/components/wifi.html#enterprise-authentication

**Description of problem:**
I was playing around with the wpa2 enterprise feature on esphome.
esphome saw my wpa2 enterprise SSID's however did not want to connect.
A connection wasn't even tried. The wpa2 enterprise SSID's where not in selection of valid SSID's.
(I troubleshooted this adding extra logging to the code)

The problem is found to be the ssid matching code. It wants a password at the ssid level in the config file.
The dev code also misses a line to copy the EAP parameters to the esp32 specific code.

**Problem-relevant YAML-configuration entries:**
```yaml
wifi:
  networks:
  - ssid: wifi-enterprise
    priority: 5
    eap:
      username: ${devicename}
      password: <radius password>
#      certificate_authority: .ubnt-radius.pem

```

**Logs (if applicable):**

```
[18:17:45][D][WiFiGeneric.cpp:337] _eventCallback(): Event: 1 - SCAN_DONE
[18:17:45][V][wifi_esp32:357]: Event: WiFi Scan Done status=0 number=3 scan_id=128
[18:17:45][D][wifi:320]: Found networks:
[18:17:45][D][wifi:370]: - wifi-enterprise [AP_MAC1] ▂▄▆█
[18:17:45][D][wifi:370]: - wifi-enterprise [AP_MAC2] ▂▄▆█
[18:17:45][D][wifi:370]: - wifi-enterprise [AP_MAC3] ▂▄▆█
[18:17:45][W][wifi:375]: No matching network found!
```

**Additional information and things you've tried:**

PR to fix will follow.

### PR DESCRIPTION
**Pull request by dr-oblivium**
## Description:

**Related issue (if applicable):** fixes https://github.com/esphome/issues/issues/1379

**Pull request in [esphome-docs](https://github.com/esphome/esphome-docs) with documentation (if applicable):** NA

## Checklist:
  - [X] The code change is tested and works locally.
  - [NA] Tests have been added to verify that the new code works (under `tests/` folder).

If user exposed functionality or configuration variables are added/changed:
  - [NA] Documentation added/updated in [esphome-docs](https://github.com/esphome/esphome-docs).

### CODE REVIEW

**Comment by OttoWinter** [comment]
CC @tomtom5152 (https://github.com/esphome/esphome/pull/1080)

File: esphome/components/wifi/wifi_component.cpp [hunk 1]
```diff
@@ -201,7 +201,15 @@ void WiFiComponent::start_connecting(const WiFiAP &ap, bool two) {
   } else {
     ESP_LOGV(TAG, "  BSSID: Not Set");
   }
-  ESP_LOGV(TAG, "  Password: " LOG_SECRET("'%s'"), ap.get_password().c_str());
+  if (ap.get_eap().has_value()) {
```
Comment (OttoWinter) [inline esphome/components/wifi/wifi_component.cpp:204]: These errors are because the `get_eap()` method (and the fields) only exist when `ESPHOME_WIFI_WPA2_EAP` is defined, please surround all these with `#ifdef ESPHOME_WIFI_WPA2_EAP`

**Review by OttoWinter — COMMENTED** [review]
Hmm, you're right. ~~This can't have worked.~~ Edit: would work with fast_connect

Thanks for submitting this PR! I don't have a WPA2 enterprise network around I could test with unfortunately, so I can't validate the fix here. But LGTM to me.

File: esphome/components/wifi/wifi_component.cpp (hunk 1 above)
Comment (dr-oblivium) [reply esphome/components/wifi/wifi_component.cpp:204]: Thanks, will review.

**Comment by tomtom5152** [comment]
Nice spot, I hadn't encountered it in testing because I didn't have verbose logging turned on, thus the whole section was `#ifdef`'d out. I still can't get it to trigger at compile time and don't particularly want to go digging in walls for ESPs to test it at runtime this evening.

Might it be worth adding in the printing of `ca_cert`, `client_cert` and `LOG_SECRET(client_key)` to complete the verbosity of with EAP-TLS and EAP-TTLS (only `ca_cert`), potentially wrapped with an if to only print if set?

**Comment by OttoWinter** [comment]
No no the certificate/key shouldn't be printed (it won't fit in the log buffer anyway)

**Comment by tomtom5152** [comment]
Not fitting is fair enough, but I’d have thought the same logic would apply to password which are far more sensitive than a public key cert.

Just incase I’ve misunderstood something (I’m not really a C++ dev), `std::string` isn’t nullable is it, as in EAP-TLS it is optional. Just struck me as a potential null pointer.

**Comment by OttoWinter** [comment]
@tomtom5152 all these structs are wrapped in `optional<>`, which isn't really nullable, but can have no value. `std::string` is not nullable (default state is zero-length string). So the log commands should be alright.

File: esphome/components/wifi/wifi_component.cpp [hunk 2]
```diff
@@ -576,9 +600,20 @@ bool WiFiScanResult::matches(const WiFiAP &config) {
...
+  // BSSID requires auth but no PSK or EAP credentials given
+  if (this->with_auth_ && (config.get_password().empty() && !config.get_eap().has_value()))
+    return false;
+
+  // BSSID does not require auth, but PSK or EAP credentials given
+  if (!this->with_auth_ && (!config.get_password().empty() || config.get_eap().has_value()))
     return false;
+#else
+  // If PSK given, only match for networks with auth (and vice versa)
+  if (config.get_password().empty() == this->with_auth_)
```
Comment (OttoWinter) [inline esphome/components/wifi/wifi_component.cpp:614]: A `return false` is missing on the next line.

Comment (dr-oblivium) [reply esphome/components/wifi/wifi_component.cpp:614]: Thx, will update the pr.

**Comment by OttoWinter** [comment]
LGTM, ready to merge when you press "Ready for review" to convert the PR to a non-draft PR.
