### PR TITLE
fix uart settings check

### LINKED ISSUE #6316: cse7766 platform says it requires even parity to compile and throws an error about parity on startup in the log
### The problem

INFO ESPHome 2024.10.0b1
INFO Reading configuration /config/esphome/sonoff-1.yaml...
INFO Detected timezone 'America/New_York'
Failed config

uart: [source /config/esphome/sonoff-1.yaml:28]
  - rx_pin: 
      number: 3
      mode: 
        input: True
        output: False
        open_drain: False
        pullup: False
        pulldown: False
        analog: False
      inverted: False
    baud_rate: 4800
    
    Component cse7766 requires parity EVEN for the uart referenced by uart_id.
    parity: NONE
    rx_buffer_size: 256
    stop_bits: 1

and in the log this shows up

[04:21:07][E][uart:028]:   Invalid parity: Integration requested parity NONE but you have EVEN!

### Which version of ESPHome has the issue?

2024.10.0b1

### What type of installation are you using?

Home Assistant Add-on

### Which version of Home Assistant has the issue?

2024.10

### What platform are you using?

ESP8266

### Board

Sonoff S31 

### Component causing the issue

cse7766

### Example YAML snippet

```yaml
uart:
  rx_pin: RX
  baud_rate: 4800
  parity: EVEN

sensor:
  - platform: cse7766
    current:
      name: "Current"
      accuracy_decimals: 1
      filters:
        - throttle_average: 60s
    voltage:
      name: "Voltage"
      accuracy_decimals: 1
      filters:
        - throttle_average: 60s
    power:
      name: "Power"
      accuracy_decimals: 1
      id: my_power
      filters:
        - throttle_average: 60s
```

### Anything in the logs that might be useful for us?

```txt
[04:21:07][E][uart:028]:   Invalid parity: Integration requested parity NONE but you have EVEN!
```

### Additional information

Sadly i Have no way to properly verify the values being reorted

### PR DESCRIPTION
**Pull request by ssieb**
# What does this implement/fix?

The uart settings check in `dump_config` needs the parity setting.

## Types of changes

- [X] Bugfix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] Other

**Related issue or feature (if applicable):** fixes https://github.com/esphome/issues/issues/6316

**Pull request in [esphome-docs](https://github.com/esphome/esphome-docs) with documentation (if applicable):** esphome/esphome-docs#<esphome-docs PR number goes here>

## Test Environment

- [ ] ESP32
- [ ] ESP32 IDF
- [ ] ESP8266
- [ ] RP2040
- [ ] BK72xx
- [ ] RTL87xx

## Example entry for `config.yaml`:

```yaml
# Example config.yaml

```

## Checklist:
  - [ ] The code change is tested and works locally.
  - [ ] Tests have been added to verify that the new code works (under `tests/` folder).

If user exposed functionality or configuration variables are added/changed:
  - [ ] Documentation added/updated in [esphome-docs](https://github.com/esphome/esphome-docs).

### CODE REVIEW

File: esphome/components/cse7766/cse7766.cpp [hunk 1]
```diff
@@ -244,7 +244,7 @@ void CSE7766Component::dump_config() {
   LOG_SENSOR("  ", "Apparent Power", this->apparent_power_sensor_);
   LOG_SENSOR("  ", "Reactive Power", this->reactive_power_sensor_);
   LOG_SENSOR("  ", "Power Factor", this->power_factor_sensor_);
-  this->check_uart_settings(4800);
+  this->check_uart_settings(4800, 1, UART_CONFIG_PARITY_EVEN);
```
Comment (ssieb) [inline esphome/components/cse7766/cse7766.cpp]:
```suggestion
  this->check_uart_settings(4800, 1, uart::UART_CONFIG_PARITY_EVEN);
```

**Review by kbx81 — APPROVED** [review]
