### PR TITLE
Couple more updates for the Tuya component

### LINKED ISSUE #2265: TuyaMCU Sending incorrect heartbeat packet, causing it to not work with some tuya devices
### The problem

I'm attempting to use a ESP8285 + MOES 4-circuit wall-switch: https://www.amazon.com/gp/product/B08NC6VTWY/

This device uses a Tuya MCU, and comes with a WB2S Tuya module. I have replaced the module with a ESP8285.

Setting up the device with the TuyaMCU add-on, ESPHome never establishes communication with the TuyaMCU.

Semi-Off Topic:

`esphome --version` does not work.

`esphome version` throws a warning, and then tells me to use the exact same command:

```
WARNING Calling ESPHome with the configuration before the command is deprecated and will be removed in the future.
WARNING Please instead use:
WARNING    esphome version
Version: 1.19.4
```

### What is version of ESPHome has the issue?

Version: 1.19.4

### What platform are you using?

ESP8266

### Component causing the issue

TuyaMCU

### Example YAML snippet

```yaml
# Enable logging
logger:
  baud_rate: 0
  level: VERY_VERBOSE

# Enable Home Assistant API
api:

ota:


uart:
  rx_pin: GPIO3
  tx_pin: GPIO1
  baud_rate: 9600


# Register the Tuya MCU connection
tuya:


switch:
  - platform: "tuya"
    name: "Quad Switch Relay 1"
    switch_datapoint: 1
  - platform: "tuya"
    name: "Quad Switch Relay 2"
    switch_datapoint: 2
  - platform: "tuya"
    name: "Quad Switch Relay 3"
    switch_datapoint: 3
  - platform: "tuya"
    name: "Quad Switch Relay 4"
    switch_datapoint: 4

binary_sensor:
  - platform: "tuya"
    name: "Quad Switch Button 1"
    sensor_datapoint: 1
  - platform: "tuya"
    name: "Quad Switch Button 2"
    sensor_datapoint: 2
  - platform: "tuya"
    name: "Quad Switch Button 3"
    sensor_datapoint: 3
  - platform: "tuya"
    name: "Quad Switch Button 4"
    sensor_datapoint: 4
```

### Anything in the logs that might be useful for us?

```txt
The generated heartbeat is:


[05:56:27][VV][scheduler:152]: Running interval 'heartbeat' with interval=10000 last_execution=35396 (now=45396)
[05:56:27][V][tuya:321]: Sending Tuya: CMD=0x00 VERSION=0 DATA=[04 (1)] INIT_STATE=0
[05:56:27][VV][uart_esp8266:111]:     Wrote 0b01010101 (0x55)
[05:56:27][VV][uart_esp8266:111]:     Wrote 0b10101010 (0xAA)
[05:56:27][VV][uart_esp8266:111]:     Wrote 0b00000000 (0x00)
[05:56:27][VV][uart_esp8266:111]:     Wrote 0b00000000 (0x00)
[05:56:27][VV][uart_esp8266:111]:     Wrote 0b00000000 (0x00)
[05:56:27][VV][uart_esp8266:111]:     Wrote 0b00000001 (0x01)
[05:56:27][VV][uart_esp8266:111]:     Wrote 0b00000100 (0x04)
[05:56:27][VV][uart_esp8266:101]:     Wrote 0b00000100 (0x04)

```

Note that if I manually toggle the buttons on the tuya MCU, I see log output about switches changing.

However, if you look at the Tuya Docs ( https://images.tuyacn.com/smart/aircondition/Guide-to-Interworking-with-the-Tuya-MCU.pdf ) they specify a example heartbeat: 

> For example, the Wi-Fi module sends `55 aa 00 00 00 00 ff`, and the MCU returns `55 aa 03 00 00 01 00 03` for the first packet and `55 aa 03 00 00 01 01 04` for other packets.

The generated heartbeat is definitely wrong. 

Looking in [`tuya.cpp`](https://github.com/esphome/esphome/blob/dev/esphome/components/tuya/tuya.cpp#L347-L349), `send_empty_command()` is hard-coded to always insert `0x04` as the body into empty commands (wut?).
```


### Additional information

_No response_

### PR DESCRIPTION
**Pull request by nuttytree**
# What does this implement/fix? 

* Update the heartbeat interval from 10s to 15s per the [Tuya documentation](https://developer.tuya.com/en/docs/iot/tuya-cloud-universal-serial-port-access-protocol?id=K9hhi0xxtn9cb#title-4-Detecting%20heartbeat)
* Fixes send_empty_command_ to actually send an empty command
* Prevents sending new commands while waiting for a response from the previous command, this requirement is not particularly clear in the Tuya documentation and I could not find what the timeout period should be so I went with the value Tasmota is using.
 
## Types of changes

- [X] Bugfix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] Other

**Related issue or feature (if applicable):** fixes esphome/issues#2265

## Test Environment

- [ ] ESP32
- [X] ESP8266

## Checklist:
  - [X] The code change is tested and works locally.
  - [N/A] Tests have been added to verify that the new code works (under `tests/` folder).
  
If user exposed functionality or configuration variables are added/changed:
  - [N/A] Documentation added/updated in [esphome-docs](https://github.com/esphome/esphome-docs).

### CODE REVIEW

**Review by OttoWinter — APPROVED** [review]
LGTM, @jesserockz you're listed as codeowner for a couple tuya platforms. Can you check if this looks ok?

**Review by jesserockz — APPROVED** [review]
Interesting, I actually think this has fixed my tuya heater. :tada: 
For some reason it was not getting through the init steps, but now it does. I believe it was the "empty" heartbeat change that has now fixed it as I reverted that line and it stopped working again.

Thanks

**Comment by jkl1337** [comment]
One deadlock remains: there is no timeout on packet reception. It looks like if there is a "short read", with valid bytes hanging around in the rx buffer, send_raw_command will never make progress.

**Comment by nuttytree** [comment]
> One deadlock remains: there is no timeout on packet reception. It looks like if there is a "short read", with valid bytes hanging around in the rx buffer, send_raw_command will never make progress.

I have never seen this situation occur but it is definitely possible.  I can put up another PR to address that issue, might be a day or 2 I have been sick for several days so I am trying to play catch up right now.

File: esphome/components/tuya/tuya.cpp [hunk 1]
```diff
@@ -8,9 +8,10 @@ namespace tuya {
 
 static const char *const TAG = "tuya";
 static const int COMMAND_DELAY = 50;
+static const int RECEIVE_TIMEOUT = 300;
 
 void Tuya::setup() {
-  this->set_interval("heartbeat", 10000, [this] { this->send_empty_command_(TuyaCommandType::HEARTBEAT); });
+  this->set_interval("heartbeat", 15000, [this] { this->send_empty_command_(TuyaCommandType::HEARTBEAT); });
```
Comment (trvrnrth) [inline esphome/components/tuya/tuya.cpp:14]: Just for reference this was changed to 15 seconds from 10 seconds in the tuya documentation in version 1.0.8 (20170512).  I agree with changing it to match but I thought I'd stick a note just in case issues crop up with older devices and anyone ends up referencing this PR.
