### PR TITLE
RG15 data is float/double, not int

### LINKED ISSUE #3323: Hydreon Rain sensor RG-15 incorrect message decoding
### The problem

Parsing report message from RG-15 is not correct. Only 'TotalAcc' gets value and it's missing decimals.
```
[13:34:48][D][uart_debug:158]: <<< "Acc  0.01 mm, EventAcc  0.01 mm, TotalAcc  8.52 mm, RInt  0.15 mmph\r\n"
[13:34:48][D][sensor:125]: 'rain': Sending state 0.00000 mm with 2 decimals of accuracy
[13:34:48][D][hydreon_rgxx.sensor:200]: Received Acc: 0.000000
[13:34:48][D][sensor:125]: 'rain event': Sending state 0.00000 mm with 2 decimals of accuracy
[13:34:48][D][hydreon_rgxx.sensor:200]: Received EventAcc: 0.000000
[13:34:48][D][sensor:125]: 'rain total': Sending state 8.00000 mm with 2 decimals of accuracy
[13:34:48][D][hydreon_rgxx.sensor:200]: Received TotalAcc: 8.000000
[13:35:17][W][hydreon_rgxx.sensor:051]: Missing Rint
```

I attach also log file with hex formatted message to see exact incoming message

Edit: please look also https://github.com/home-assistant/core/issues/72643

### Which version of ESPHome has the issue?

2022.5.1

### What type of installation are you using?

Home Assistant Add-on

### Which version of Home Assistant has the issue?

2022.5.5

### What platform are you using?

ESP32

### Board

esp32dev

### Component causing the issue

hydreon_rgxx 

### Example YAML snippet

```yaml
captive_portal:
    
uart:
  rx_pin: GPIO16
  tx_pin: GPIO17
  baud_rate: 9600
  debug:
    direction: BOTH
    dummy_receiver: false
    after:
      delimiter: "\n"
    sequence:
      - lambda: UARTDebug::log_string(direction, bytes);

sensor:
  - platform: hydreon_rgxx
    model: "RG_15"
    update_interval: 600s
    acc:
      name: "rain"
    event_acc:
      name: "rain event"
    total_acc:
      name: "rain total"
    r_int:
      name: "rain intensity"
      
  - platform: wifi_signal
    name: "esp32-rg15_rssi"
    update_interval: 60s
    
switch:
   - platform: template
     name: "RG-15 req"
     turn_on_action:
      - uart.write: "R\n"
      - uart.write: "C\n"
```
```


### Anything in the logs that might be useful for us?

```txt
INFO Reading configuration /config/esphome/esp32-rg15.yaml...
INFO Starting log output from 192.168.1.44 using esphome API
INFO Successfully connected to 192.168.1.44
[12:42:58][I][app:102]: ESPHome version 2022.5.1 compiled on May 28 2022, 12:41:37
[12:42:58][C][wifi:491]: WiFi:
[12:42:58][C][wifi:353]:   Local MAC: 08:3A:F2:3E:84:8C
[12:42:58][C][wifi:354]:   SSID: 'Antsumaja1'[redacted]
[12:42:58][C][wifi:355]:   IP Address: 192.168.1.44
[12:42:58][C][wifi:357]:   BSSID: B0:A7:B9:16:89:A8[redacted]
[12:42:58][C][wifi:358]:   Hostname: 'esp32-rg15'
[12:42:58][C][wifi:360]:   Signal strength: -56 dB ▂▄▆█
[12:42:58][C][wifi:364]:   Channel: 6
[12:42:58][C][wifi:365]:   Subnet: 255.255.255.0
[12:42:58][C][wifi:366]:   Gateway: 192.168.1.1
[12:42:58][C][wifi:367]:   DNS1: 0.0.0.0
[12:42:58][C][wifi:368]:   DNS2: 0.0.0.0
[12:42:58][C][logger:274]: Logger:
[12:42:58][C][logger:275]:   Level: DEBUG
[12:42:58][C][logger:276]:   Log Baud Rate: 115200
[12:42:58][C][logger:277]:   Hardware UART: UART0
[12:42:58][C][uart.arduino_esp32:107]: UART Bus:
[12:42:58][C][uart.arduino_esp32:108]:   TX Pin: GPIO17
[12:42:58][C][uart.arduino_esp32:109]:   RX Pin: GPIO16
[12:42:58][C][uart.arduino_esp32:111]:   RX Buffer Size: 256
[12:42:58][C][uart.arduino_esp32:113]:   Baud Rate: 9600 baud
[12:42:58][C][uart.arduino_esp32:114]:   Data Bits: 8
[12:42:58][C][uart.arduino_esp32:115]:   Parity: NONE
[12:42:58][C][uart.arduino_esp32:116]:   Stop bits: 1
[12:42:58][C][template.switch:058]: Template Switch 'RG-15 req'
[12:42:58][C][template.switch:059]:   Restore State: NO
[12:42:58][C][template.switch:060]:   Optimistic: NO
[12:42:59][C][hydreon_rgxx.sensor:015]: hydreon_rgxx:
[12:42:59][C][hydreon_rgxx.sensor:019]:   Update Interval: 600.0s
[12:42:59][C][hydreon_rgxx.sensor:026]:   "Acc" 'rain'
[12:42:59][C][hydreon_rgxx.sensor:026]:     Device Class: 'humidity'
[12:42:59][C][hydreon_rgxx.sensor:026]:     State Class: 'measurement'
[12:42:59][C][hydreon_rgxx.sensor:026]:     Unit of Measurement: 'mm'
[12:42:59][C][hydreon_rgxx.sensor:026]:     Accuracy Decimals: 2
[12:42:59][C][hydreon_rgxx.sensor:026]:   "Rint" 'rain intensity'
[12:42:59][C][hydreon_rgxx.sensor:026]:     Device Class: 'humidity'
[12:42:59][C][hydreon_rgxx.sensor:026]:     State Class: 'measurement'
[12:42:59][C][hydreon_rgxx.sensor:026]:     Unit of Measurement: 'mm/h'
[12:42:59][C][hydreon_rgxx.sensor:026]:     Accuracy Decimals: 2
[12:42:59][C][hydreon_rgxx.sensor:026]:   "EventAcc" 'rain event'
[12:42:59][C][hydreon_rgxx.sensor:026]:     Device Class: 'humidity'
[12:42:59][C][hydreon_rgxx.sensor:026]:     State Class: 'measurement'
[12:42:59][C][hydreon_rgxx.sensor:026]:     Unit of Measurement: 'mm'
[12:42:59][C][hydreon_rgxx.sensor:026]:     Accuracy Decimals: 2
[12:42:59][C][hydreon_rgxx.sensor:026]:   "TotalAcc" 'rain total'
[12:42:59][C][hydreon_rgxx.sensor:026]:     Device Class: 'humidity'
[12:42:59][C][hydreon_rgxx.sensor:026]:     State Class: 'measurement'
[12:42:59][C][hydreon_rgxx.sensor:026]:     Unit of Measurement: 'mm'
[12:42:59][C][hydreon_rgxx.sensor:026]:     Accuracy Decimals: 2
[12:42:59][C][captive_portal:088]: Captive Portal:
[12:42:59][C][mdns:084]: mDNS:
[12:42:59][C][mdns:085]:   Hostname: esp32-rg15
[12:42:59][C][ota:085]: Over-The-Air Updates:
[12:42:59][C][ota:086]:   Address: 192.168.1.44:3232
[12:42:59][C][ota:089]:   Using Password.
[12:42:59][C][api:138]: API Server:
[12:42:59][C][api:139]:   Address: 192.168.1.44:6053
[12:42:59][C][api:143]:   Using noise encryption: NO
[12:42:59][C][wifi_signal.sensor:009]: WiFi Signal 'esp32-rg15_rssi'
[12:42:59][C][wifi_signal.sensor:009]:   Device Class: 'signal_strength'
[12:42:59][C][wifi_signal.sensor:009]:   State Class: 'measurement'
[12:42:59][C][wifi_signal.sensor:009]:   Unit of Measurement: 'dBm'
[12:42:59][C][wifi_signal.sensor:009]:   Accuracy Decimals: 0
[12:43:20][D][switch:013]: 'RG-15 req' Turning ON.
[12:43:20][D][uart_debug:114]: >>> 52:0A
[12:43:20][D][uart_debug:114]: >>> 43:0A
[12:43:20][D][uart_debug:114]: <<< 41:63:63:20:20:30:2E:30:30:20:6D:6D:2C:20:45:76:65:6E:74:41:63:63:20:20:30:2E:30:30:20:6D:6D:2C:20:54:6F:74:61:6C:41:63:63:20:20:34:2E:38:38:20:6D:6D:2C:20:52:49:6E:74:20:20:30:2E:30:30:20:6D:6D:70:68:0D:0A
[12:43:20][D][sensor:125]: 'rain': Sending state 0.00000 mm with 2 decimals of accuracy
[12:43:20][D][hydreon_rgxx.sensor:200]: Received Acc: 0.000000
[12:43:20][D][sensor:125]: 'rain event': Sending state 0.00000 mm with 2 decimals of accuracy
[12:43:20][D][hydreon_rgxx.sensor:200]: Received EventAcc: 0.000000
[12:43:20][D][sensor:125]: 'rain total': Sending state 4.00000 mm with 2 decimals of accuracy
[12:43:20][D][hydreon_rgxx.sensor:200]: Received TotalAcc: 4.000000
[12:43:20][D][uart_debug:114]: <<< 63:0D:0A
[12:43:20][I][hydreon_rgxx.sensor:204]: Got unknown line: c

[12:43:27][D][sensor:125]: 'esp32-rg15_rssi': Sending state -56.00000 dBm with 0 decimals of accuracy
[12:44:24][D][uart_debug:114]: <<< 0D:0A
[12:44:24][I][hydreon_rgxx.sensor:204]: Got unknown line: 

[12:44:24][D][uart_debug:114]: <<< 3B:2D:2D:2D:2D:2D:2D:2D:2D:2D:2D:2D:2D:2D:2D:2D:2D:2D:2D:2D:2D:2D:2D:2D:2D:2D:2D:2D:2D:2D:2D:2D:2D:2D:2D:2D:2D:2D:2D:2D:2D:0D:0A
[12:44:24][I][hydreon_rgxx.sensor:146]: Comment: ;----------------------------------------
[12:44:24][D][uart_debug:114]: <<< 45:76:65:6E:74:0D:0A
[12:44:24][I][hydreon_rgxx.sensor:204]: Got unknown line: Event

[12:44:24][D][uart_debug:114]: <<< 53:57:20:31:2E:30:30:30:20:32:30:32:30:2E:30:37:2E:30:36:0D:0A
[12:44:24][I][hydreon_rgxx.sensor:174]: detected sw version 1000
[12:44:24][D][uart_debug:114]: <<< 0D:0A
[12:44:24][I][hydreon_rgxx.sensor:204]: Got unknown line: 

[12:44:24][D][uart_debug:114]: <<< 41:63:63:20:20:30:2E:30:37:20:6D:6D:2C:20:45:76:65:6E:74:41:63:63:20:20:30:2E:30:37:20:6D:6D:2C:20:54:6F:74:61:6C:41:63:63:20:20:34:2E:39:35:20:6D:6D:2C:20:52:49:6E:74:20:31:30:2E:36:38:20:6D:6D:70:68:0D:0A
[12:44:24][D][sensor:125]: 'rain': Sending state 0.00000 mm with 2 decimals of accuracy
[12:44:24][D][hydreon_rgxx.sensor:200]: Received Acc: 0.000000
[12:44:24][D][sensor:125]: 'rain event': Sending state 0.00000 mm with 2 decimals of accuracy
[12:44:24][D][hydreon_rgxx.sensor:200]: Received EventAcc: 0.000000
[12:44:24][D][sensor:125]: 'rain total': Sending state 4.00000 mm with 2 decimals of accuracy
[12:44:24][D][hydreon_rgxx.sensor:200]: Received TotalAcc: 4.000000
[12:44:27][D][sensor:125]: 'esp32-rg15_rssi': Sending state -56.00000 dBm with 0 decimals of accuracy
[12:44:42][D][uart_debug:114]: <<< 41:63:63:20:20:30:2E:32:32:20:6D:6D:2C:20:45:76:65:6E:74:41:63:63:20:20:30:2E:32:39:20:6D:6D:2C:20:54:6F:74:61:6C:41:63:63:20:20:35:2E:31:37:20:6D:6D:2C:20:52:49:6E:74:20:34:30:2E:39:30:20:6D:6D:70:68:0D:0A
[12:44:42][D][sensor:125]: 'rain': Sending state 0.00000 mm with 2 decimals of accuracy
[12:44:42][D][hydreon_rgxx.sensor:200]: Received Acc: 0.000000
[12:44:42][D][sensor:125]: 'rain event': Sending state 0.00000 mm with 2 decimals of accuracy
[12:44:42][D][hydreon_rgxx.sensor:200]: Received EventAcc: 0.000000
[12:44:42][D][sensor:125]: 'rain total': Sending state 5.00000 mm with 2 decimals of accuracy
[12:44:42][D][hydreon_rgxx.sensor:200]: Received TotalAcc: 5.000000
[12:44:48][D][uart_debug:114]: <<< 41:63:63:20:20:30:2E:34:36:20:6D:6D:2C:20:45:76:65:6E:74:41:63:63:20:20:30:2E:37:35:20:6D:6D:2C:20:54:6F:74:61:6C:41:63:63:20:20:35:2E:36:33:20:6D:6D:2C:20:52:49:6E:74:20:38:38:2E:39:39:20:6D:6D:70:68:0D:0A
[12:44:48][D][sensor:125]: 'rain': Sending state 0.00000 mm with 2 decimals of accuracy
[12:44:48][D][hydreon_rgxx.sensor:200]: Received Acc: 0.000000
[12:44:48][D][sensor:125]: 'rain event': Sending state 0.00000 mm with 2 decimals of accuracy
[12:44:48][D][hydreon_rgxx.sensor:200]: Received EventAcc: 0.000000
[12:44:48][D][sensor:125]: 'rain total': Sending state 5.00000 mm with 2 decimals of accuracy
[12:44:48][D][hydreon_rgxx.sensor:200]: Received TotalAcc: 5.000000
[12:44:54][D][uart_debug:114]: <<< 41:63:63:20:20:30:2E:33:33:20:6D:6D:2C:20:45:76:65:6E:74:41:63:63:20:20:31:2E:30:38:20:6D:6D:2C:20:54:6F:74:61:6C:41:63:63:20:20:35:2E:39:36:20:6D:6D:2C:20:52:49:6E:74:20:39:39:2E:38:31:20:6D:6D:70:68:0D:0A
[12:44:54][D][sensor:125]: 'rain': Sending state 0.00000 mm with 2 decimals of accuracy
[12:44:54][D][hydreon_rgxx.sensor:200]: Received Acc: 0.000000
[12:44:54][D][sensor:125]: 'rain event': Sending state 1.00000 mm with 2 decimals of accuracy
[12:44:54][D][hydreon_rgxx.sensor:200]: Received EventAcc: 1.000000
[12:44:54][D][sensor:125]: 'rain total': Sending state 5.00000 mm with 2 decimals of accuracy
[12:44:54][D][hydreon_rgxx.sensor:200]: Received TotalAcc: 5.000000
[12:45:00][D][uart_debug:114]: <<< 41:63:63:20:20:30:2E:33:30:20:6D:6D:2C:20:45:76:65:6E:74:41:63:63:20:20:31:2E:33:38:20:6D:6D:2C:20:54:6F:74:61:6C:41:63:63:20:20:36:2E:32:36:20:6D:6D:2C:20:52:49:6E:74:20:39:39:2E:38:31:20:6D:6D:70:68:0D:0A
[12:45:00][D][sensor:125]: 'rain': Sending state 0.00000 mm with 2 decimals of accuracy
[12:45:00][D][hydreon_rgxx.sensor:200]: Received Acc: 0.000000
[12:45:00][D][sensor:125]: 'rain event': Sending state 1.00000 mm with 2 decimals of accuracy
[12:45:00][D][hydreon_rgxx.sensor:200]: Received EventAcc: 1.000000
[12:45:00][D][sensor:125]: 'rain total': Sending state 6.00000 mm with 2 decimals of accuracy
[12:45:00][D][hydreon_rgxx.sensor:200]: Received TotalAcc: 6.000000
[12:45:06][D][uart_debug:114]: <<< 41:63:63:20:20:30:2E:32:31:20:6D:6D:2C:20:45:76:65:6E:74:41:63:63:20:20:31:2E:35:39:20:6D:6D:2C:20:54:6F:74:61:6C:41:63:63:20:20:36:2E:34:37:20:6D:6D:2C:20:52:49:6E:74:20:39:39:2E:38:31:20:6D:6D:70:68:0D:0A
[12:45:06][D][sensor:125]: 'rain': Sending state 0.00000 mm with 2 decimals of accuracy
[12:45:06][D][hydreon_rgxx.sensor:200]: Received Acc: 0.000000
[12:45:06][D][sensor:125]: 'rain event': Sending state 1.00000 mm with 2 decimals of accuracy
[12:45:06][D][hydreon_rgxx.sensor:200]: Received EventAcc: 1.000000
[12:45:06][D][sensor:125]: 'rain total': Sending state 6.00000 mm with 2 decimals of accuracy
[12:45:06][D][hydreon_rgxx.sensor:200]: Received TotalAcc: 6.000000
[12:45:12][D][uart_debug:114]: <<< 41:63:63:20:20:30:2E:30:34:20:6D:6D:2C:20:45:76:65:6E:74:41:63:63:20:20:31:2E:36:33:20:6D:6D:2C:20:54:6F:74:61:6C:41:63:63:20:20:36:2E:35:31:20:6D:6D:2C:20:52:49:6E:74:20:39:39:2E:38:31:20:6D:6D:70:68:0D:0A
[12:45:12][D][sensor:125]: 'rain': Sending state 0.00000 mm with 2 decimals of accuracy
[12:45:12][D][hydreon_rgxx.sensor:200]: Received Acc: 0.000000
[12:45:12][D][sensor:125]: 'rain event': Sending state 1.00000 mm with 2 decimals of accuracy
[12:45:12][D][hydreon_rgxx.sensor:200]: Received EventAcc: 1.000000
[12:45:12][D][sensor:125]: 'rain total': Sending state 6.00000 mm with 2 decimals of accuracy
[12:45:12][D][hydreon_rgxx.sensor:200]: Received TotalAcc: 6.000000
[12:45:18][D][uart_debug:114]: <<< 41:63:63:20:20:30:2E:34:36:20:6D:6D:2C:20:45:76:65:6E:74:41:63:63:20:20:32:2E:30:39:20:6D:6D:2C:20:54:6F:74:61:6C:41:63:63:20:20:36:2E:39:37:20:6D:6D:2C:20:52:49:6E:74:20:39:39:2E:38:31:20:6D:6D:70:68:0D:0A
[12:45:18][D][sensor:125]: 'rain': Sending state 0.00000 mm with 2 decimals of accuracy
[12:45:18][D][hydreon_rgxx.sensor:200]: Received Acc: 0.000000
[12:45:18][D][sensor:125]: 'rain event': Sending state 2.00000 mm with 2 decimals of accuracy
[12:45:18][D][hydreon_rgxx.sensor:200]: Received EventAcc: 2.000000
[12:45:18][D][sensor:125]: 'rain total': Sending state 6.00000 mm with 2 decimals of accuracy
[12:45:18][D][hydreon_rgxx.sensor:200]: Received TotalAcc: 6.000000
[12:45:24][D][uart_debug:114]: <<< 41:63:63:20:20:30:2E:34:33:20:6D:6D:2C:20:45:76:65:6E:74:41:63:63:20:20:32:2E:35:32:20:6D:6D:2C:20:54:6F:74:61:6C:41:63:63:20:20:37:2E:34:30:20:6D:6D:2C:20:52:49:6E:74:20:39:39:2E:38:31:20:6D:6D:70:68:0D:0A
[12:45:24][D][sensor:125]: 'rain': Sending state 0.00000 mm with 2 decimals of accuracy
[12:45:24][D][hydreon_rgxx.sensor:200]: Received Acc: 0.000000
[12:45:24][D][sensor:125]: 'rain event': Sending state 2.00000 mm with 2 decimals of accuracy
[12:45:24][D][hydreon_rgxx.sensor:200]: Received EventAcc: 2.000000
[12:45:24][D][sensor:125]: 'rain total': Sending state 7.00000 mm with 2 decimals of accuracy
[12:45:24][D][hydreon_rgxx.sensor:200]: Received TotalAcc: 7.000000
[12:45:27][D][sensor:125]: 'esp32-rg15_rssi': Sending state -56.00000 dBm with 0 decimals of accuracy
[12:45:30][D][uart_debug:114]: <<< 41:63:63:20:20:30:2E:34:35:20:6D:6D:2C:20:45:76:65:6E:74:41:63:63:20:20:32:2E:39:37:20:6D:6D:2C:20:54:6F:74:61:6C:41:63:63:20:20:37:2E:38:35:20:6D:6D:2C:20:52:49:6E:74:20:39:39:2E:38:31:20:6D:6D:70:68:0D:0A
[12:45:30][D][sensor:125]: 'rain': Sending state 0.00000 mm with 2 decimals of accuracy
[12:45:30][D][hydreon_rgxx.sensor:200]: Received Acc: 0.000000
[12:45:30][D][sensor:125]: 'rain event': Sending state 2.00000 mm with 2 decimals of accuracy
[12:45:30][D][hydreon_rgxx.sensor:200]: Received EventAcc: 2.000000
[12:45:30][D][sensor:125]: 'rain total': Sending state 7.00000 mm with 2 decimals of accuracy
[12:45:30][D][hydreon_rgxx.sensor:200]: Received TotalAcc: 7.000000
[12:45:36][D][uart_debug:114]: <<< 41:63:63:20:20:30:2E:32:38:20:6D:6D:2C:20:45:76:65:6E:74:41:63:63:20:20:33:2E:32:35:20:6D:6D:2C:20:54:6F:74:61:6C:41:63:63:20:20:38:2E:31:33:20:6D:6D:2C:20:52:49:6E:74:20:39:39:2E:38:31:20:6D:6D:70:68:0D:0A
[12:45:36][D][sensor:125]: 'rain': Sending state 0.00000 mm with 2 decimals of accuracy
[12:45:36][D][hydreon_rgxx.sensor:200]: Received Acc: 0.000000
[12:45:36][D][sensor:125]: 'rain event': Sending state 3.00000 mm with 2 decimals of accuracy
[12:45:36][D][hydreon_rgxx.sensor:200]: Received EventAcc: 3.000000
[12:45:36][D][sensor:125]: 'rain total': Sending state 8.00000 mm with 2 decimals of accuracy
[12:45:36][D][hydreon_rgxx.sensor:200]: Received TotalAcc: 8.000000
[12:45:41][D][uart_debug:114]: <<< 41:63:63:20:20:30:2E:33:36:20:6D:6D:2C:20:45:76:65:6E:74:41:63:63:20:20:33:2E:36:31:20:6D:6D:2C:20:54:6F:74:61:6C:41:63:63:20:20:38:2E:34:39:20:6D:6D:2C:20:52:49:6E:74:20:39:39:2E:38:31:20:6D:6D:70:68:0D:0A
[12:45:42][D][sensor:125]: 'rain': Sending state 0.00000 mm with 2 decimals of accuracy
[12:45:42][D][hydreon_rgxx.sensor:200]: Received Acc: 0.000000
[12:45:42][D][sensor:125]: 'rain event': Sending state 3.00000 mm with 2 decimals of accuracy
[12:45:42][D][hydreon_rgxx.sensor:200]: Received EventAcc: 3.000000
[12:45:42][D][sensor:125]: 'rain total': Sending state 8.00000 mm with 2 decimals of accuracy
[12:45:42][D][hydreon_rgxx.sensor:200]: Received TotalAcc: 8.000000
[12:45:47][D][uart_debug:114]: <<< 41:63:63:20:20:30:2E:30:31:20:6D:6D:2C:20:45:76:65:6E:74:41:63:63:20:20:33:2E:36:32:20:6D:6D:2C:20:54:6F:74:61:6C:41:63:63:20:20:38:2E:35:30:20:6D:6D:2C:20:52:49:6E:74:20:39:39:2E:38:31:20:6D:6D:70:68:0D:0A
[12:45:48][D][sensor:125]: 'rain': Sending state 0.00000 mm with 2 decimals of accuracy
[12:45:48][D][hydreon_rgxx.sensor:200]: Received Acc: 0.000000
[12:45:48][D][sensor:125]: 'rain event': Sending state 3.00000 mm with 2 decimals of accuracy
[12:45:48][D][hydreon_rgxx.sensor:200]: Received EventAcc: 3.000000
[12:45:48][D][sensor:125]: 'rain total': Sending state 8.00000 mm with 2 decimals of accuracy
[12:45:48][D][hydreon_rgxx.sensor:200]: Received TotalAcc: 8.000000
[12:46:17][D][uart_debug:114]: <<< 41:63:63:20:20:30:2E:30:31:20:6D:6D:2C:20:45:76:65:6E:74:41:63:63:20:20:33:2E:36:33:20:6D:6D:2C:20:54:6F:74:61:6C:41:63:63:20:20:38:2E:35:31:20:6D:6D:2C:20:52:49:6E:74:20:39:39:2E:38:31:20:6D:6D:70:68:0D:0A
[12:46:17][D][sensor:125]: 'rain': Sending state 0.00000 mm with 2 decimals of accuracy
[12:46:17][D][hydreon_rgxx.sensor:200]: Received Acc: 0.000000
[12:46:17][D][sensor:125]: 'rain event': Sending state 3.00000 mm with 2 decimals of accuracy
[12:46:17][D][hydreon_rgxx.sensor:200]: Received EventAcc: 3.000000
[12:46:17][D][sensor:125]: 'rain total': Sending state 8.00000 mm with 2 decimals of accuracy
[12:46:17][D][hydreon_rgxx.sensor:200]: Received TotalAcc: 8.000000
[12:46:27][D][sensor:125]: 'esp32-rg15_rssi': Sending state -55.00000 dBm with 0 decimals of accuracy
```

### Additional information

[logs_esp32-rg15_upload (2).txt](https://github.com/esphome/issues/files/8792763/logs_esp32-rg15_upload.2.txt)

### PR DESCRIPTION
**Pull request by wtremmel**
# What does this implement/fix?

Hydreon RG15 delivers data (as string) floating point values, this fixes the parsing

## Types of changes

- [x] Bugfix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] Other

fixes https://github.com/esphome/issues/issues/3323

**Pull request in [esphome-docs](https://github.com/esphome/esphome-docs) with documentation (if applicable):** esphome/esphome-docs#<esphome-docs PR number goes here>

## Test Environment

- [ ] ESP32
- [ ] ESP32 IDF
- [x] ESP8266

## Example entry for `config.yaml`:

```yaml
sensor:
  - platform: hydreon_rgxx                                                                                model: "RG_15"
    update_interval: 120s
    acc:
      name: "Rain"
    event_acc:
      name: "Rain Event"
    total_acc:
      name: "Rain Total"
    r_int:
      name: "Rain Intensity"
```

## Checklist:
  - [x] The code change is tested and works locally.
  - [ ] Tests have been added to verify that the new code works (under `tests/` folder).

If user exposed functionality or configuration variables are added/changed:
  - [ ] Documentation added/updated in [esphome-docs](https://github.com/esphome/esphome-docs).

### CODE REVIEW

**Comment by functionpointer** [comment]
Tested and works on RG-9 as well :)

File: esphome/components/hydreon_rgxx/hydreon_rgxx.cpp [hunk 1]
```diff
@@ -195,7 +195,7 @@ void HydreonRGxxComponent::process_line_() {
       if (n == std::string::npos) {
         continue;
       }
-      int data = strtol(this->buffer_.substr(n + strlen(PROTOCOL_NAMES[i])).c_str(), nullptr, 10);
+      double data = strtof(this->buffer_.substr(n + strlen(PROTOCOL_NAMES[i])).c_str(), nullptr);
```
Comment (jesserockz) [inline esphome/components/hydreon_rgxx/hydreon_rgxx.cpp]: We have a helper in ESPHome for number parsing (which ultimately uses `strtof`), but this way should make it easier on others taking this code as an example
```suggestion
      float data = parse_number<float>(this->buffer_.substr(n + strlen(PROTOCOL_NAMES[i]))).value();
```

Comment (wtremmel) [reply esphome/components/hydreon_rgxx/hydreon_rgxx.cpp]: does not work, this is what I get:

```
[08:48:26][D][sensor:124]: 'Rain': Sending state 26038240.00000 mm with 4 decimals of accuracy
[08:48:26][D][hydreon_rgxx.sensor:200]: Received Acc: 26038240.000000
[08:48:26][D][sensor:124]: 'Rain Intensity': Sending state 26038240.00000 mm/h with 4 decimals of accuracy
[08:48:26][D][hydreon_rgxx.sensor:200]: Received RInt: 26038240.000000
[08:48:26][D][sensor:124]: 'Rain Event': Sending state 26038240.00000 mm with 4 decimals of accuracy
[08:48:26][D][hydreon_rgxx.sensor:200]: Received EventAcc: 26038240.000000
[08:48:26][D][sensor:124]: 'Rain Total': Sending state 26038240.00000 mm with 4 decimals of accuracy
[08:48:26][D][hydreon_rgxx.sensor:200]: Received TotalAcc: 26038240.000000
```

Unfortunately I am travelling at the moment and cannot debug.

Comment (juhanjuku) [reply esphome/components/hydreon_rgxx/hydreon_rgxx.cpp]: Strange that it does not work for you?
I loaded changes as [functionpointer](https://github.com/functionpointer) suggested in 
https://github.com/esphome/issues/issues/3248 and since then I get correct data from my RG-15

**Comment by jesserockz** [comment]
@wtremmel I have pushed a commit, can you test it please?

**Comment by juhanjuku** [comment]
> @wtremmel I have pushed a commit, can you test it please?

I can test it at Sunday

**Comment by wtremmel** [comment]
No, does not work. 
```
[17:18:37][W][hydreon_rgxx.sensor:043]: No data at all
[17:18:37][E][hydreon_rgxx.sensor:063]: data missing 1 times
```
I suspect that strtof() is more tolerant - but I cannot properly debug while travelling.

**Comment by wtremmel** [comment]
I was able to to a little bit more of debugging, I wanted to know the content of the string to be converted.

```
[18:22:07][D][hydreon_rgxx.sensor:198]: String:   0.00 mm, EventAcc  0.00 mm, TotalAcc 74.66 mm, RInt  0.00 mmph
[18:22:07][D][hydreon_rgxx.sensor:198]: String:   0.00 mmph
[18:22:07][D][hydreon_rgxx.sensor:198]: String:   0.00 mm, TotalAcc 74.66 mm, RInt  0.00 mmph
[18:22:07][D][hydreon_rgxx.sensor:198]: String:  74.66 mm, RInt  0.00 mmph
```

So the string does not just contain the next float to be converted, but also the rest. Seems _strtof()_ is tolerant enough to ignore this, _parse_number<float>_ not.

**Comment by jesserockz** [comment]
Hmm strange, `parse_number` uses `strtof`...

https://github.com/esphome/esphome/blob/da336247eb853c02a5d977bbcfb0914d8f87df68/esphome/core/helpers.h#L316-L328

**Comment by juhanjuku** [comment]
> @wtremmel I have pushed a commit, can you test it please?

I try to test your changes, but I'm stuck with git. I have very little experience with github, so last time I followed  [functionpointer](https://github.com/functionpointer) suggestions as he described in  https://github.com/esphome/issues/issues/3248 
I installed esphome on my windows PC andused git clone.
Now I did same:  C:\Users\user>git clone https://github.com/home-assistant/core/tree/dev/homeassistant/components/esphome.git  but I get error ..esphome.git not found
Can you someone point me instructions how can I test /dev/ repository on my PC?

**Comment by functionpointer** [comment]
```
git fetch
git checkout wtremmel-hydreon-rg15-data
```
The output should look like this:
```
$ git checkout wtremmel-hydreon-rg15-data
branch 'wtremmel-hydreon-rg15-data' set up to track 'origin/wtremmel-hydreon-rg15-data'.
Switched to a new branch 'wtremmel-hydreon-rg15-data'
```

For verification you can run `git log` and the top commit id should match the latest one in this PR (see the [commits tab](https://github.com/esphome/esphome/pull/3512/commits)). Currently the id of the latest commit starts with  `8dfc069` .

Once you are sure you have the latest commit you can run it:
```
esphome run <yourfile>
```

If more commits appear in the future you can run `git pull` to get them.

Edit: If you have deleted your old repository you can run `git clone https://github.com/wtremmel/esphome.git` to recreate it from scratch. You still need to do the `git checkout wtremmel-hydreon-rg15-data` then.

**Comment by juhanjuku** [comment]
@functionpointer  your instructions are for testing your repository. 
I like to test official dev where @jesserockz made changes
Excuse me, if I'm confusing some things, github is still foggy for me :)

**Comment by functionpointer** [comment]
Actually my instructions are for testing @wtremmel's repository.

This PR is based on the `wtremmel-hydreon-rg15-data` branch in @wtremmel's repository. All changes we are discussing here are on that branch. That includes @jesserockz's changes. He pushed them in into @wtremmel's repository.

The `dev` branch of the official repository only contains changes from already accepted PRs.
In general, development always happens in PRs. Only when something works and has been successfully reviewed is it merged into the official repository. The idea is to always have a fully working version on the `dev` branch.

**Comment by functionpointer** [comment]
I feel like this git talk is cluttering the PR a bit.

If you have futher git questions i suggest you join the [ESPHome Discord](https://discord.gg/KhAMKrd) and add me [functionpointer#1609](https://discordapp.com/users/1609/).

**Comment by wtremmel** [comment]
> Hmm strange, `parse_number` uses `strtof`...
> 
> https://github.com/esphome/esphome/blob/da336247eb853c02a5d977bbcfb0914d8f87df68/esphome/core/helpers.h#L316-L328

parse_number has one additional check:
```
  if (end == str || *end != '\0' || value == HUGE_VALF)
```

and since the string to parse contains multiple values and is not `\0` terminated it fails.
Let me check if I can fix this.

**Comment by juhanjuku** [comment]
This code is NOT working
```
      auto data = parse_number<float>(this->buffer_.substr(n + strlen(PROTOCOL_NAMES[i])));
      if (!data.has_value())
        continue;
      float d = data.value();
```
nok

This code IS working
```
      double data = strtof(this->buffer_.substr(n + strlen(PROTOCOL_NAMES[i])).c_str(), nullptr);
```
ok

**Comment by jesserockz** [comment]
Ah yes I understand why now. `parse_number` wants only the number in the string, and using `strtof` directly will parse up until the numbers stop in the string basically.
Happy for this to remain `strtof` for now then and Ill look at revisiting it at a later date.

**Comment by wtremmel** [comment]
Ok, pushed another commit. Works here. I changed `double` into `float`.

The "proper" change can be done by @functionpointer  - basically a \0 needs to be put after each floating number in the string. I am not good enough in C++ to know how to do that.

**Review by jesserockz — APPROVED** [review]
