### PR TITLE
[nextion] Add configurable HTTP parameters for TFT upload

### LINKED ISSUE #3223: `Bug` transport_base: esp_tls_conn_read error, errno=No more processes
### TFT Version

2026015 (https://raw.githubusercontent.com/Blackymas/NSPanel_HA_Blueprint/v2026015/hmi/nspanel_eu.tft)

### Firmware Version

2026015

### Blueprint Version

2026015

### Panel Model

EU

### What is the bug?

When I try to upload the newest firmware it doesn't work for one device. I get: 
`transport_base: esp_tls_conn_read error, errno=No more processes` and later
```
[22:00:20.213][D][nextion.upload.esp32:106]: Upload: 91.84% (620980 left, heap: 76612+1952216)
[22:00:35.235][D][esp-idf:000]: E (448076) transport_base: esp_tls_conn_read error, errno=No more processes
[22:01:50.286][E][nextion.upload.esp32:091]: Read failed: 3114/4096 bytes
[22:01:50.286][E][nextion.upload.esp32:335]: TFT upload error
[22:01:50.287][D][nextion.upload.esp32:336]: Close HTTP
[22:01:50.287][E][nextion.upload:020]: Upload failed
```
Could there be a way to resume the flash, e.g. open the https file again and start at the range that was not written to the panel, the same way it starts at the beginning not at "0%": 
```
[21:58:44.223][D][nextion.upload.esp32:028]: Range start: 0
[21:58:49.651][D][nextion.upload.esp32:106]: Upload: 0.05% (7608756 left, heap: 76620+1979132)
[21:58:49.651][D][nextion.upload.esp32:116]: Recv: [08:00:00:64:00]
[21:58:49.651][I][nextion.upload.esp32:124]: New range: 6553600
[21:58:49.831][D][nextion.upload.esp32:028]: Range start: 6553600
[21:58:50.302][D][nextion.upload.esp32:106]: Upload: 86.14% (1055156 left, heap: 76612+1970268)
```

So: 
1. don't reboot right away, instead: try to fix the upload by opening the file again. If this fails --> reboot
2. after a reboot, 5 minutes until it is possible to try again --> could this be shorter, if you press the upload tft button twice? (auto mode --> use the 5 minutes)

### Steps to Reproduce

_No response_

### Your Panel's YAML

```yaml
substitutions:
  # Settings - Editable values
  device_name: "panel_og_noah"
  friendly_name: "Panel OG Noah"
  wifi_ssid: !secret wifi_ssid
  wifi_password: !secret wifi_password
  mac_temp: "A4:C1:38:EA:1E:5A"
  cover_entity: "cover.rollo_og_noah_cover_s"
  boot_sound: false
  upload_tft_automatically: true
  upload_tft_baud_rate: 115200  # Default value, changing not recommended due to UART bugs

  ##### addon-configuration #####
  ## addon_climate ##
  heater_relay: "1"
  temp_min: "15"
  temp_max: "25"
  temp_step: "0.5"
  heat_deadband: "0.3"  # Temperature delta before engaging heat
  heat_overrun: "0.2"   # Temperature delta before disengaging heat
  min_off_time: "30"
  min_run_time: "60"
  min_idle_time: "5"

# Customization area
##### My customization - Start #####
api:
  encryption: 
    key: !secret encryption_key
  reboot_timeout: 15min

ota:
  password: !secret ota_password
  platform: esphome

script:
  - id: !extend button_left_press_short
    then:
      - homeassistant.service:
          action: script.cover_stop_open
          data:
            cover_entity: '$cover_entity'
            panel_entity: '$device_name'
  - id: !extend button_right_press_short
    then:
      - homeassistant.service:
          action: script.cover_stop_close
          data:
            cover_entity: '$cover_entity'
            panel_entity: '$device_name'
  - id: !extend button_left_press_long
    then:
      - homeassistant.service:
          action: script.cover_set_cover_position
          data:
            position: '10'
            entity_id: '$cover_entity'
            panel_entity: '$device_name'   
  - id: !extend button_right_press_long 
    then:
      - homeassistant.service:
          action: script.cover_set_cover_position
          data:
            position: '50'
            entity_id: '$cover_entity'
            panel_entity: '$device_name'   

time:
  - id: !extend time_provider
    on_time:
      - seconds: 00
        minutes: 00
        hours: 21
        then:
          - if:
              condition:
                lambda: 'return id(thermostat_embedded).preset != CLIMATE_PRESET_AWAY;'
              then:
                - climate.control:
                    id: thermostat_embedded
                    target_temperature: 20
      - seconds: 00
        minutes: 00
        hours: 12
        then:
          - if:
              condition:
                lambda: 'return id(thermostat_embedded).preset != CLIMATE_PRESET_AWAY;'
              then:
                - climate.control:
                    id: thermostat_embedded
                    target_temperature: 22

climate:
  - id: !extend thermostat_embedded
    sensor: combined_temperature
    humidity_sensor: ext_humidity
    preset:
      - name: "home"
        default_target_temperature_low: 22
      - name: "away"
        default_target_temperature_low: 17   
    default_preset: home

esp32_ble_tracker:
  id: ble_tracker
  scan_parameters:
    window: 60ms
    active: false

sensor:
  - id: combined_temperature
    platform: template
    internal: true
    lambda: |-
      if (wifi_component->is_connected() and api_server->is_connected()) {
        return ext_temperature->state;
      } else {
        return temp_nspanel->state;
      }
  - platform: pvvx_mithermometer
    mac_address: $mac_temp
    temperature:
      name: "Temperatur"
      id: ext_temperature
      device_class: temperature
      filters:
        - throttle_average: 120s
    humidity:
      name: "Luftfeuchtigkeit"
      id: ext_humidity
      device_class: humidity
      filters:
        - throttle_average: 120s
    battery_level:
      name: "Batterieladestand"
      id: ext_battery_level
      entity_category: diagnostic
      filters:
        - throttle_average: 3600s
##### My customization - End #####

# Core and optional configurations
packages:
  remote_package_files:
    url: https://github.com/Blackymas/NSPanel_HA_Blueprint
    ref: main
    refresh: 0s
    files:
      - nspanel_esphome.yaml # Basic package
      - esphome/nspanel_esphome_addon_climate_heat.yaml
      - esphome/nspanel_esphome_addon_display_light.yaml
```

### ESPHome Logs

```text
[21:58:11.975][D][esp32.preferences:155]: Writing 1 items: 1 cached, 0 written, 0 failed
[21:58:13.720][D][nspanel.addon.upload_tft:161]: Waiting after time sync: 296079 / 300000 ms elapsed (98.7%)
[21:58:24.791][D][wifi:2112]: Roam scan (-65 dBm, attempt 1/3)
[21:58:28.763][D][nspanel.addon.upload_tft:173]: Set Nextion unavailable for blueprint calls
[21:58:28.763][D][binary_sensor:047]: 'Nextion display' >> OFF
[21:58:28.763][D][nspanel.addon.upload_tft:176]: Preparing for upload
[21:58:28.763][D][nspanel.addon.upload_tft:124]: Nextion status:
[21:58:28.763][D][nspanel.addon.upload_tft:125]:   Is detected: YES
[21:58:28.764][D][nspanel.addon.upload_tft:126]:   Is setup:    YES
[21:58:28.764][D][nspanel.addon.upload_tft:127]:   Queue size:  0
[21:58:28.791][D][nspanel.addon.upload_tft:181]: Starting the upload script
[21:58:30.744][D][nspanel.addon.upload_tft:225]: Stopping other scripts
[21:58:30.747][D][nspanel.addon.upload_tft:243]: Restarting Nextion display
[21:58:30.755][D][switch:026]: 'Nextion display - Power' Turning OFF.
[21:58:30.755][D][switch:065]: 'Nextion display - Power' >> OFF
[21:58:32.761][D][switch:022]: 'Nextion display - Power' Turning ON.
[21:58:32.769][D][switch:065]: 'Nextion display - Power' >> ON
[21:58:34.597][D][sensor:129]: 'ntc_source' >> 1.50 V
[21:58:34.597][D][sensor:129]: 'resistance_sensor' >> 9278.8 Ω
[21:58:34.730][D][sensor:129]: 'Temperature' >> 26.7 °C
[21:58:37.775][D][nspanel.addon.upload_tft:124]: Nextion status:
[21:58:37.775][D][nspanel.addon.upload_tft:125]:   Is detected: YES
[21:58:37.791][D][nspanel.addon.upload_tft:126]:   Is setup:    YES
[21:58:37.791][D][nspanel.addon.upload_tft:127]:   Queue size:  0
[21:58:37.791][D][main:281]: Attempting to upload TFT
[21:58:37.804][D][nspanel.addon.upload_tft:282]: Attempt #1
[21:58:38.798][D][nspanel.addon.upload_tft:133]: Waiting for empty UART and Nextion queues
[21:58:39.751][D][pvvx_mithermometer:122]: Got PVVX MiThermometer (A4:C1:38:EA:1E:5A):
[21:58:39.821][D][pvvx_mithermometer:125]:   Temperature: 22.35 °C
[21:58:39.821][D][pvvx_mithermometer:128]:   Humidity: 35.30 %
[21:58:39.821][D][pvvx_mithermometer:131]:   Battery Level: 13 %
[21:58:39.971][D][pvvx_mithermometer:134]:   Battery Voltage: 2.296 V
[21:58:40.866][D][nspanel.addon.upload_tft:140]: Starting TFT upload
[21:58:40.867][D][nextion.upload.esp32:162]: TFT upload requested
[21:58:40.867]Exit reparse: NO
[21:58:40.867]URL: https://raw.githubusercontent.com/Blackymas/NSPanel_HA_Blueprint/v2026015/hmi/nspanel_eu.tft
[21:58:40.882][D][nextion.upload.esp32:193]: Baud rate: 115200
[21:58:43.318][D][nextion.upload.esp32:246]: TFT size: 7612852 bytes
[21:58:43.322][D][nextion.upload.esp32:259]: Uploading
[21:58:44.223][D][nextion.upload.esp32:297]: Upload resp: [05] 1 B
[21:58:44.223][D][nextion.upload.esp32:320]: Uploading TFT:
[21:58:44.223][D][nextion.upload.esp32:320]:   URL:  https://raw.githubusercontent.com/Blackymas/NSPanel_HA_Blueprint/v2026015/hmi/nspanel_eu.tft
[21:58:44.223][D][nextion.upload.esp32:320]:   Size: 7612852 bytes
[21:58:44.223][D][nextion.upload.esp32:320]:   Heap: 2014496
[21:58:44.223][D][nextion.upload.esp32:028]: Range start: 0
[21:58:49.651][D][nextion.upload.esp32:106]: Upload: 0.05% (7608756 left, heap: 76620+1979132)
[21:58:49.651][D][nextion.upload.esp32:116]: Recv: [08:00:00:64:00]
[21:58:49.651][I][nextion.upload.esp32:124]: New range: 6553600
[21:58:49.831][D][nextion.upload.esp32:028]: Range start: 6553600
[21:58:50.302][D][nextion.upload.esp32:106]: Upload: 86.14% (1055156 left, heap: 76612+1970268)
[21:58:50.703][D][nextion.upload.esp32:106]: Upload: 86.19% (1051060 left, heap: 76612+1969496)
[21:58:51.110][D][nextion.upload.esp32:106]: Upload: 86.25% (1046964 left, heap: 76612+1969496)
[21:58:51.721][D][nextion.upload.esp32:106]: Upload: 86.30% (1042868 left, heap: 76612+1954156)
[21:58:52.106][D][nextion.upload.esp32:106]: Upload: 86.36% (1038772 left, heap: 76612+1952656)
[21:58:52.549][D][nextion.upload.esp32:106]: Upload: 86.41% (1034676 left, heap: 76612+1950496)
[21:58:52.927][D][nextion.upload.esp32:106]: Upload: 86.46% (1030580 left, heap: 76612+1954156)
[21:58:53.435][D][nextion.upload.esp32:106]: Upload: 86.52% (1026484 left, heap: 76612+1954520)
[21:58:53.777][D][nextion.upload.esp32:106]: Upload: 86.57% (1022388 left, heap: 76612+1954520)
[21:58:54.166][D][nextion.upload.esp32:106]: Upload: 86.62% (1018292 left, heap: 76612+1954520)
[21:58:54.569][D][nextion.upload.esp32:106]: Upload: 86.68% (1014196 left, heap: 76612+1954520)
[21:58:55.124][D][nextion.upload.esp32:106]: Upload: 86.73% (1010100 left, heap: 76612+1954516)
[21:58:55.502][D][nextion.upload.esp32:106]: Upload: 86.79% (1006004 left, heap: 76612+1954516)
[21:58:55.896][D][nextion.upload.esp32:106]: Upload: 86.84% (1001908 left, heap: 76612+1954516)
[21:58:56.305][D][nextion.upload.esp32:106]: Upload: 86.89% (997812 left, heap: 76612+1954516)
[21:58:56.864][D][nextion.upload.esp32:106]: Upload: 86.95% (993716 left, heap: 76612+1954660)
[21:58:57.244][D][nextion.upload.esp32:106]: Upload: 87.00% (989620 left, heap: 76612+1954544)
[21:58:57.637][D][nextion.upload.esp32:106]: Upload: 87.05% (985524 left, heap: 76612+1954136)
[21:58:58.046][D][nextion.upload.esp32:106]: Upload: 87.11% (981428 left, heap: 76612+1954252)
[21:58:58.758][D][nextion.upload.esp32:106]: Upload: 87.16% (977332 left, heap: 76612+1954924)
[21:58:59.097][D][nextion.upload.esp32:106]: Upload: 87.22% (973236 left, heap: 76612+1954528)
[21:58:59.484][D][nextion.upload.esp32:106]: Upload: 87.27% (969140 left, heap: 76612+1954300)
[21:58:59.899][D][nextion.upload.esp32:106]: Upload: 87.32% (965044 left, heap: 76612+1954528)
[21:59:00.516][D][nextion.upload.esp32:106]: Upload: 87.38% (960948 left, heap: 76612+1954520)
[21:59:00.912][D][nextion.upload.esp32:106]: Upload: 87.43% (956852 left, heap: 76612+1954520)
[21:59:01.322][D][nextion.upload.esp32:106]: Upload: 87.48% (952756 left, heap: 76612+1954520)
[21:59:01.663][D][nextion.upload.esp32:106]: Upload: 87.54% (948660 left, heap: 76612+1954520)
[21:59:08.509][D][nextion.upload.esp32:106]: Upload: 87.59% (944564 left, heap: 76612+1954644)
[21:59:08.900][D][nextion.upload.esp32:106]: Upload: 87.65% (940468 left, heap: 76612+1954412)
[21:59:09.309][D][nextion.upload.esp32:106]: Upload: 87.70% (936372 left, heap: 76612+1954644)
[21:59:09.658][D][nextion.upload.esp32:106]: Upload: 87.75% (932276 left, heap: 76612+1954644)
[21:59:17.095][D][nextion.upload.esp32:106]: Upload: 87.81% (928180 left, heap: 76612+1955520)
[21:59:17.510][D][nextion.upload.esp32:106]: Upload: 87.86% (924084 left, heap: 76612+1954340)
[21:59:17.850][D][nextion.upload.esp32:106]: Upload: 87.92% (919988 left, heap: 76612+1954060)
[21:59:18.235][D][nextion.upload.esp32:106]: Upload: 87.97% (915892 left, heap: 76612+1954060)
[21:59:18.967][D][nextion.upload.esp32:106]: Upload: 88.02% (911796 left, heap: 76612+1954340)
[21:59:19.357][D][nextion.upload.esp32:106]: Upload: 88.08% (907700 left, heap: 76612+1953648)
[21:59:19.755][D][nextion.upload.esp32:106]: Upload: 88.13% (903604 left, heap: 76612+1953648)
[21:59:20.169][D][nextion.upload.esp32:106]: Upload: 88.18% (899508 left, heap: 76612+1953648)
[21:59:20.818][D][nextion.upload.esp32:106]: Upload: 88.24% (895412 left, heap: 76612+1953944)
[21:59:21.204][D][nextion.upload.esp32:106]: Upload: 88.29% (891316 left, heap: 76612+1953944)
[21:59:21.597][D][nextion.upload.esp32:106]: Upload: 88.35% (887220 left, heap: 76612+1953944)
[21:59:22.007][D][nextion.upload.esp32:106]: Upload: 88.40% (883124 left, heap: 76612+1953944)
[21:59:22.639][D][nextion.upload.esp32:106]: Upload: 88.45% (879028 left, heap: 76612+1953920)
[21:59:23.032][D][nextion.upload.esp32:106]: Upload: 88.51% (874932 left, heap: 76612+1953920)
[21:59:23.442][D][nextion.upload.esp32:106]: Upload: 88.56% (870836 left, heap: 76612+1953920)
[21:59:23.789][D][nextion.upload.esp32:106]: Upload: 88.61% (866740 left, heap: 76612+1953920)
[21:59:24.414][D][nextion.upload.esp32:106]: Upload: 88.67% (862644 left, heap: 76612+1953900)
[21:59:24.799][D][nextion.upload.esp32:106]: Upload: 88.72% (858548 left, heap: 76612+1953900)
[21:59:25.190][D][nextion.upload.esp32:106]: Upload: 88.78% (854452 left, heap: 76612+1953880)
[21:59:27.036][D][nextion.upload.esp32:106]: Upload: 88.83% (850356 left, heap: 76612+1953900)
[21:59:27.036][D][nextion.upload.esp32:106]: Upload: 88.88% (846260 left, heap: 76612+1952424)
[21:59:27.036][D][nextion.upload.esp32:106]: Upload: 88.94% (842164 left, heap: 76612+1950928)
[21:59:27.043][D][nextion.upload.esp32:106]: Upload: 88.99% (838068 left, heap: 76612+1950928)
[21:59:27.443][D][nextion.upload.esp32:106]: Upload: 89.05% (833972 left, heap: 76612+1953920)
[21:59:28.175][D][nextion.upload.esp32:106]: Upload: 89.10% (829876 left, heap: 76612+1953728)
[21:59:28.573][D][nextion.upload.esp32:106]: Upload: 89.15% (825780 left, heap: 76612+1953900)
[21:59:29.325][D][nextion.upload.esp32:106]: Upload: 89.21% (821684 left, heap: 76612+1952404)
[21:59:29.325][D][nextion.upload.esp32:106]: Upload: 89.26% (817588 left, heap: 76612+1950908)
[21:59:44.740][D][esp-idf:000]: E (397589) transport_base: esp_tls_conn_read error, errno=No more processes
[21:59:50.621][D][nextion.upload.esp32:106]: Upload: 89.31% (813492 left, heap: 76612+1954048)
[21:59:51.005][D][nextion.upload.esp32:106]: Upload: 89.37% (809396 left, heap: 76612+1953628)
[21:59:51.396][D][nextion.upload.esp32:106]: Upload: 89.42% (805300 left, heap: 76612+1953628)
[21:59:51.806][D][nextion.upload.esp32:106]: Upload: 89.48% (801204 left, heap: 76612+1953628)
[21:59:52.471][D][nextion.upload.esp32:106]: Upload: 89.53% (797108 left, heap: 76612+1953408)
[21:59:52.856][D][nextion.upload.esp32:106]: Upload: 89.58% (793012 left, heap: 76612+1953408)
[21:59:53.243][D][nextion.upload.esp32:106]: Upload: 89.64% (788916 left, heap: 76612+1953340)
[21:59:53.760][D][nextion.upload.esp32:106]: Upload: 89.69% (784820 left, heap: 76612+1953408)
[21:59:54.480][D][nextion.upload.esp32:106]: Upload: 89.74% (780724 left, heap: 76612+1954980)
[21:59:55.296][D][nextion.upload.esp32:106]: Upload: 89.80% (776628 left, heap: 76612+1953500)
[21:59:55.296][D][nextion.upload.esp32:106]: Upload: 89.85% (772532 left, heap: 76612+1952004)
[21:59:55.620][D][nextion.upload.esp32:106]: Upload: 89.91% (768436 left, heap: 76612+1953292)
[21:59:56.325][D][nextion.upload.esp32:106]: Upload: 89.96% (764340 left, heap: 76612+1954060)
[21:59:56.720][D][nextion.upload.esp32:106]: Upload: 90.01% (760244 left, heap: 76612+1953324)
[21:59:57.079][D][nextion.upload.esp32:106]: Upload: 90.07% (756148 left, heap: 76612+1953324)
[21:59:57.465][D][nextion.upload.esp32:106]: Upload: 90.12% (752052 left, heap: 76612+1953324)
[21:59:58.098][D][nextion.upload.esp32:106]: Upload: 90.18% (747956 left, heap: 76612+1953032)
[21:59:58.480][D][nextion.upload.esp32:106]: Upload: 90.23% (743860 left, heap: 76612+1952952)
[21:59:58.879][D][nextion.upload.esp32:106]: Upload: 90.28% (739764 left, heap: 76612+1953032)
[22:00:00.526][D][nextion.upload.esp32:106]: Upload: 90.34% (735668 left, heap: 76612+1953032)
[22:00:00.530][D][nextion.upload.esp32:106]: Upload: 90.39% (731572 left, heap: 76612+1951956)
[22:00:00.816][D][nextion.upload.esp32:106]: Upload: 90.44% (727476 left, heap: 76612+1953136)
[22:00:01.226][D][nextion.upload.esp32:106]: Upload: 90.50% (723380 left, heap: 76612+1952716)
[22:00:01.578][D][nextion.upload.esp32:106]: Upload: 90.55% (719284 left, heap: 76612+1952716)
[22:00:08.925][D][nextion.upload.esp32:106]: Upload: 90.61% (715188 left, heap: 76612+1952664)
[22:00:09.315][D][nextion.upload.esp32:106]: Upload: 90.66% (711092 left, heap: 76612+1952716)
[22:00:09.725][D][nextion.upload.esp32:106]: Upload: 90.71% (706996 left, heap: 76612+1952716)
[22:00:10.072][D][nextion.upload.esp32:106]: Upload: 90.77% (702900 left, heap: 76612+1952716)
[22:00:10.847][D][nextion.upload.esp32:106]: Upload: 90.82% (698804 left, heap: 76612+1952452)
[22:00:11.178][D][nextion.upload.esp32:106]: Upload: 90.87% (694708 left, heap: 76612+1952452)
[22:00:11.582][D][nextion.upload.esp32:106]: Upload: 90.93% (690612 left, heap: 76612+1952452)
[22:00:11.986][D][nextion.upload.esp32:106]: Upload: 90.98% (686516 left, heap: 76612+1952452)
[22:00:12.597][D][nextion.upload.esp32:106]: Upload: 91.04% (682420 left, heap: 76612+1953140)
[22:00:12.921][D][nextion.upload.esp32:106]: Upload: 91.09% (678324 left, heap: 76612+1952860)
[22:00:13.312][D][nextion.upload.esp32:106]: Upload: 91.14% (674228 left, heap: 76612+1952860)
[22:00:13.728][D][nextion.upload.esp32:106]: Upload: 91.20% (670132 left, heap: 76612+1952860)
[22:00:14.373][D][nextion.upload.esp32:106]: Upload: 91.25% (666036 left, heap: 76612+1952460)
[22:00:14.759][D][nextion.upload.esp32:106]: Upload: 91.30% (661940 left, heap: 76612+1952460)
[22:00:15.161][D][nextion.upload.esp32:106]: Upload: 91.36% (657844 left, heap: 76612+1952460)
[22:00:15.562][D][nextion.upload.esp32:106]: Upload: 91.41% (653748 left, heap: 76612+1952460)
[22:00:16.941][D][nextion.upload.esp32:106]: Upload: 91.47% (649652 left, heap: 76612+1951956)
[22:00:18.139][D][nextion.upload.esp32:106]: Upload: 91.52% (645556 left, heap: 76612+1950460)
[22:00:18.139][D][nextion.upload.esp32:106]: Upload: 91.57% (641460 left, heap: 76612+1948964)
[22:00:18.139][D][nextion.upload.esp32:106]: Upload: 91.63% (637364 left, heap: 76612+1948964)
[22:00:19.057][D][nextion.upload.esp32:106]: Upload: 91.68% (633268 left, heap: 76612+1952316)
[22:00:19.453][D][nextion.upload.esp32:106]: Upload: 91.74% (629172 left, heap: 76612+1952316)
[22:00:19.865][D][nextion.upload.esp32:106]: Upload: 91.79% (625076 left, heap: 76612+1952316)
[22:00:20.213][D][nextion.upload.esp32:106]: Upload: 91.84% (620980 left, heap: 76612+1952216)
[22:00:35.235][D][esp-idf:000]: E (448076) transport_base: esp_tls_conn_read error, errno=No more processes
[22:01:50.286][E][nextion.upload.esp32:091]: Read failed: 3114/4096 bytes
[22:01:50.286][E][nextion.upload.esp32:335]: TFT upload error
[22:01:50.287][D][nextion.upload.esp32:336]: Close HTTP
[22:01:50.287][E][nextion.upload:020]: Upload failed
[22:01:50.287][W][component:543]: script took a long time for an operation (189458 ms)
[22:01:50.287][W][component:546]: Components should block for at most 30 ms
[22:01:50.287][W][component:543]: api took a long time for an operation (189461 ms)
[22:01:50.298][W][component:546]: Components should block for at most 30 ms
[22:01:50.298][W][esp32_ble:519]: Dropped 19722 BLE events due to buffer overflow
[22:01:50.298][D][nspanel.addon.upload_tft:290]: Attempt #1 returned: FAILED
[22:01:50.305][I][addon_upload_tft.script.upload_tft_attempt:291]: Restarting ESPHome
[22:01:50.305][I][app:258]: Rebooting safely
INFO Processing expected disconnect from ESPHome API for panel_og_noah @ 192.168.175.49
WARNING Disconnected from API
INFO Successfully resolved panel_og_noah @ 192.168.175.49 in 7.015s
INFO Successfully connected to panel_og_noah @ 192.168.175.49 in 0.165s
INFO Successful handshake with panel_og_noah @ 192.168.175.49 in 0.333s
[22:02:02.995][D][nspanel.datetime:156]: System clock synchronized
[22:02:03.082][D][nspanel.datetime:157]: Timezone: CET-1CEST,M3.5.0,M10.5.0/3
[22:02:03.113][W][nextion:091]: Not connected
[22:02:03.631][W][nextion:091]: Not connected
[22:02:04.153][W][nextion:091]: Not connected
[22:02:04.726][W][nextion:091]: Not connected
[22:02:05.232][W][nextion:091]: Not connected
[22:02:05.746][W][nextion:091]: Not connected
[22:02:06.253][W][nextion:091]: Not connected
[22:02:06.770][W][nextion:091]: Not connected
[22:02:07.290][W][nextion:091]: Not connected
[22:02:07.801][W][nextion:091]: Not connected
[22:02:07.819][D][nspanel.hw.relays:376]: Fallback to page Home
[22:02:07.894][W][nspanel.base:110]: Waiting for the system to be ready before executing an action
[22:02:08.325][W][nextion:091]: Not connected
[22:02:08.850][W][nextion:091]: Not connected
[22:02:09.360][W][nextion:091]: Not connected
[22:02:09.885][W][nextion:091]: Not connected
[22:02:10.455][W][nextion:091]: Not connected
[22:02:10.964][W][nextion:091]: Not connected
[22:02:11.480][W][nextion:091]: Not connected
[22:02:12.003][W][nextion:091]: Not connected
[22:02:12.500][W][nextion:091]: Not connected
[22:02:12.916][W][nspanel.base:110]: Waiting for the system to be ready before executing an action
[22:02:12.925][C][nspanel.versioning:102]: Blueprint:
[22:02:12.925][W][nspanel.versioning:107]:   Progress: 0.0%
[22:02:12.925][W][nspanel.versioning:108]:   State: DISCONNECTED
[22:02:12.932][C][nspanel.versioning:113]: ESPHome:
[22:02:12.932][C][nspanel.versioning:114]:   Version: 2026015
[22:02:12.934][C][nspanel.versioning:115]:   Compiler: 2026.1.3
[22:02:12.943][C][nspanel.versioning:119]:   Framework: ESP-IDF
[22:02:12.943][C][nspanel.api:338]: API: Connected
[22:02:12.944][C][nspanel.hw.relays:155]: UART:
[22:02:12.952][C][nspanel.hw.relays:156]:   Baud rate: 115200 bps
[22:02:12.957][C][nspanel.hw.relays:157]:   Queue size: 0
[22:02:12.957][C][nspanel.hw.relays:161]: Nextion:
[22:02:12.962][C][nspanel.hw.relays:162]:   Queue size:  0
[22:02:12.962][W][nspanel.hw.relays:166]:   Is setup:    False
[22:02:13.020][W][nspanel.hw.relays:167]:   Is detected: NO
[22:02:13.020][W][nspanel.hw.relays:173]:   Init: False
[22:02:13.020][W][nspanel.hw.relays:177]:   TFT: UNKNOWN
[22:02:13.020][C][nspanel.hw.relays:181]: Wake-up page: home
[22:02:13.020][C][nspanel.core:056]:   Free heap:
[22:02:13.020][C][nspanel.core:059]:     Internal:    89276 bytes (29.6%)
[22:02:13.020][C][nspanel.core:069]:     PSRAM:     1989320 bytes (95.5%)
[22:02:13.020][E][nspanel.hw.wifi:053]: WiFi: DISCONNECTED
[22:02:13.020][C][nspanel.core:095]: Packages:
[22:02:13.020][C][nspanel.core:097]:   - Core
[22:02:13.050][C][nspanel.core:106]:   - Upload TFT
[22:02:13.050][C][nspanel.core:109]:   - Climate - Base
[22:02:13.050][C][nspanel.core:118]:   - Climate - Heat
[22:02:13.050][C][nspanel.hw.temperature:094]: Temperature unit: °C
[22:02:13.050][C][nspanel.addon.upload_tft:112]: Add-on Upload TFT:
[22:02:13.050][C][nspanel.addon.upload_tft:114]:   File model: NSPanel EU
[22:02:13.050][C][nspanel.addon.upload_tft:118]:   Valid TFT:  NO
[22:02:13.050][C][nspanel.addon.climate:157]: Add-on climate:
[22:02:13.050][C][nspanel.addon.climate:164]:   Heat:  Enabled
[22:02:13.056][C][nspanel.addon.climate:165]:   Relay: 1
[22:02:13.056][C][nspanel.addon.display_light:050]: Add-on 'Display as a light'
[22:02:13.056][W][component:543]: script took a long time for an operation (142 ms)
[22:02:13.122][W][component:546]: Components should block for at most 30 ms
[22:02:13.122][W][component:543]: api took a long time for an operation (151 ms)
[22:02:13.122][W][component:546]: Components should block for at most 30 ms
[22:02:13.134][W][nextion:091]: Not connected
[22:02:13.629][W][nextion:091]: Not connected
[22:02:14.141][W][nextion:091]: Not connected
[22:02:14.655][W][nextion:091]: Not connected
[22:02:15.165][W][nextion:091]: Not connected
[22:02:15.680][W][nextion:091]: Not connected
[22:02:16.205][W][nextion:091]: Not connected
[22:02:16.727][W][nextion:091]: Not connected
[22:02:17.248][W][nextion:091]: Not connected
[22:02:17.830][W][nextion:091]: Not connected
[22:02:17.927][W][nspanel.base:110]: Waiting for the system to be ready before executing an action
[22:02:18.289][W][nextion:091]: Not connected
[22:02:18.797][W][nextion:091]: Not connected
[22:02:19.162][D][pvvx_mithermometer:122]: Got PVVX MiThermometer (A4:C1:38:EA:1E:5A):
[22:02:19.162][D][pvvx_mithermometer:125]:   Temperature: 22.36 °C
[22:02:19.162][D][pvvx_mithermometer:128]:   Humidity: 35.42 %
[22:02:19.162][D][pvvx_mithermometer:131]:   Battery Level: 15 %
[22:02:19.162][D][pvvx_mithermometer:134]:   Battery Voltage: 2.306 V
[22:02:19.361][W][nextion:091]: Not connected
[22:02:19.875][W][nextion:091]: Not connected
[22:02:20.385][W][nextion:091]: Not connected
[22:02:20.900][W][nextion:091]: Not connected
[22:02:21.416][W][nextion:091]: Not connected
[22:02:21.940][W][nextion:091]: Not connected
[22:02:22.464][W][nextion:091]: Not connected
[22:02:22.953][W][nspanel.base:110]: Waiting for the system to be ready before executing an action
[22:02:22.985][W][nextion:091]: Not connected
[22:02:23.559][W][nextion:091]: Not connected
[22:02:24.074][W][nextion:091]: Not connected
[22:02:24.595][W][nextion:091]: Not connected
[22:02:25.098][W][nextion:091]: Not connected
[22:02:26.145][W][nextion:091]: Not connected
```

### Home Assistant Logs

```text

```

### LINKED ISSUE #12692: Nextion TFT upload uses baud rate 0 (Arduino & ESP-IDF)
### The problem

Nextion TFT upload via ESPHome always reports Baud rate: 0 and never actually starts the upload, even when a UART baud rate is explicitly configured.

This happens both on Arduino and ESP-IDF frameworks and makes nextion.upload unusable.

### Which version of ESPHome has the issue?

2024.x – 2025.x

### What type of installation are you using?

Docker

### What platform are you using?

ESP32

### Component causing the issue

_No response_

### YAML Config

```yaml
esphome:
  name: nextion-test
  platform: ESP32
  board: esp32dev
  framework:
    type: arduino   # same result with espidf

logger:
  level: DEBUG

uart:
  id: tf_uart
  tx_pin: GPIO16
  rx_pin: GPIO17
  baud_rate: 115200

display:
  - platform: nextion
    id: hmi
    uart_id: tf_uart
    tft_url: "http://host/hmi.tft"

button:
  - platform: template
    name: "Upload Nextion"
    on_press:
      - nextion.upload:
          url: "http://host/hmi.tft"
```

### Anything in the logs that might be useful for us?

```txt
[D][nextion.upload.arduino:151]: TFT upload requested
[D][nextion.upload.arduino:152]: Exit reparse: YES
[D][nextion.upload.arduino:153]: URL: http://host/hmi.tft
[D][nextion.upload.arduino:168]: Exit reparse mode
[D][nextion.upload.arduino:177]: Baud rate: 0
[D][nextion.upload.arduino:205]: Connected

Same behaviour with ESP-IDF.
```

### Additional information

Expected behavior

The Nextion uploader should:
Use the configured UART baud rate or
Expose a YAML option to configure the upload baud rate (as in older ESPHome versions)

Upload should start with a valid baud rate (e.g. 9600 / 115200).

Actual behavior
Baud rate is always 0
Upload never proceeds

No configuration option exists to override this

### PR DESCRIPTION
**Pull request by edwardtfn**
# What does this implement/fix?

Adds three user-configurable parameters for the Nextion TFT upload process, replacing hardcoded values and allowing users to tune the HTTP transfer behavior for their specific network conditions.

### Problem
The TFT upload HTTP timeout (15s), retry count (5), and watchdog behavior are all hardcoded. Users with slow connections, high-latency networks, or large TFT files have no way to adjust these without modifying the source.
Additionally, there is no mechanism to temporarily adjust the watchdog timeout during the upload, which can cause WDT resets on slower transfers.

### Solution
Three new optional configuration parameters under the `display` component:

- **`tft_upload_http_timeout`** *(Time, default: `4.5s`)*: HTTP request timeout. Applied to `esp_http_client_config_t.timeout_ms` on IDF and `HTTPClient::setTimeout()` on Arduino.
- **`tft_upload_http_retries`** *(int 1-255, default: `5`)*: Retry count for transient HTTP failures. Applied to the initial GET retry loop (Arduino) and chunk read retry loop (IDF).
- **`tft_upload_watchdog_timeout`** *(Time, optional)*: Temporarily adjusts the system WDT timeout for the duration of the TFT transfer using the existing `WatchdogManager` RAII pattern. Restored automatically on any exit path. Not set by default (no WDT adjustment = current behavior).

#### Names reasoning

I've decided for the prefix `tft_upload_*` to make clear those settings are related only to the upload process, and not to the regular communication with the Nextion display, and added `http_` for the same reason, as during the upload we also have the two interfaces being used. If used just `timeout` like in `http_request` it would be ambiguous.

It is `tft_upload` (and not `upload_tft`) to keep consistency with `tft_url`.

### Changed files
- **`base_component.py`**: New `CONF_*` constants
- **`display.py`**: Schema entries and `to_code()` generation
- **`nextion.h`**: Setters and member variables
- **`nextion.cpp`**: `dump_config()` output
- **`nextion_upload_esp32.cpp`**: Use configurable timeout, retries, and WDT
- **`nextion_upload_arduino.cpp`**: Use configurable timeout, and retries - (not WDT)

### Breaking changes
The default timeout was `15s` before, however this would drive to a watchdog's timeout before the http client timeout triggers, causing a crash without any log (likely the issue with #12692).
With this PR I've set the default to `4.5s` (just like in [`http_request` component](https://esphome.io/components/http_request/#configuration-variables)) to prevent this crash.
Most users won't notice anything, but as it changes the default behavior, I'm flagging this a breaking change.

### Memory impact
+9 bytes RAM per instance (only when `tft_url` is set). Negligible flash.

## Types of changes

- [ ] Bugfix (non-breaking change which fixes an issue)
- [X] New feature (non-breaking change which adds functionality)
- [X] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] Developer breaking change (an API change that could break external components)
- [ ] Code quality improvements to existing code or addition of tests
- [ ] Other

**Related issue or feature (if applicable):**

- fixes #12692
- fixes Blackymas/NSPanel_HA_Blueprint#3223

**Pull request in [esphome-docs](https://github.com/esphome/esphome-docs) with documentation (if applicable):**

- esphome/esphome-docs#6172

## Test Environment

- [ ] ESP32
- [X] ESP32 IDF
- [ ] ESP8266
- [ ] RP2040
- [ ] BK72xx
- [ ] RTL87xx
- [ ] LN882x
- [ ] nRF52840

## Example entry for `config.yaml`:

```yaml
# Example config.yaml
display:
  - platform: nextion
    uart_id: my_uart
    tft_url: "http://192.168.1.100:8080/display.tft"
    tft_upload_http_timeout: 20s
    tft_upload_watchdog_timeout: 30s
    tft_upload_http_retries: 10
```

## Checklist:
  - [X] The code change is tested and works locally.
  - [X] Tests have been added to verify that the new code works (under `tests/` folder).

If user exposed functionality or configuration variables are added/changed:
  - [X] Documentation added/updated in [esphome-docs](https://github.com/esphome/esphome-docs).

### CODE REVIEW

File: esphome/components/nextion/nextion_upload_esp32.cpp [hunk 1]
```diff
@@ -68,7 +69,7 @@ int Nextion::upload_by_chunks_(esp_http_client_handle_t http_client, uint32_t &r
     int partial_read_len = 0;
     uint8_t retries = 0;
     // Attempt to read the chunk with retries.
-    while (retries < 5 && read_len < buffer_size) {
+    while (retries < this->tft_upload_http_retries_ && read_len < buffer_size) {
```
[the remark this answers is not in the document]
Comment (edwardtfn) [reply esphome/components/nextion/nextion_upload_esp32.cpp:72]: https://github.com/edwardtfn/esphome/commit/6a77e14641ade9e9023b4be5104a63d4f66148c8

File: esphome/components/nextion/nextion_upload_esp32.cpp [hunk 2]
```diff
@@ -157,6 +158,9 @@ int Nextion::upload_by_chunks_(esp_http_client_handle_t http_client, uint32_t &r
 bool Nextion::upload_tft(uint32_t baud_rate, bool exit_reparse) {
   ESP_LOGD(TAG, "TFT upload requested, exit reparse: %s, URL: %s", YESNO(exit_reparse), this->tft_url_.c_str());
 
+  // Temporarily adjust watchdog timeout for the duration of the TFT upload
+  watchdog::WatchdogManager wdm(this->tft_upload_watchdog_timeout_);
+
   if (this->connection_state_.is_updating_) {
```
[the remark this answers is not in the document]
Comment (edwardtfn) [reply esphome/components/nextion/nextion_upload_esp32.cpp]: Good catch!
Fixed with 84f6ae96498aa551ea601525d16e05d4a5bcd9a4
Please review.

File: esphome/components/nextion/nextion_upload_esp32.cpp [hunk 3]
```diff
@@ -7,6 +7,7 @@
 #include <esp_http_client.h>
 #include <cinttypes>
 #include "esphome/components/network/util.h"
+#include "esphome/components/watchdog/watchdog.h"
```
[the remark this answers is not in the document]
Comment (edwardtfn) [reply esphome/components/nextion/nextion_upload_esp32.cpp:10]: Fixed the description.

File: esphome/components/nextion/display.py [hunk 4]
```diff
@@ -115,6 +118,15 @@
                 ),
             ),
             cv.Optional(CONF_START_UP_PAGE): cv.uint8_t,
+            cv.Optional(CONF_TFT_UPLOAD_HTTP_RETRIES, default=5): cv.int_range(
+                min=1, max=255
+            ),
+            cv.Optional(
```
Comment (bdraco) [inline esphome/components/nextion/display.py]: timeout likely needs a cap. I think its a uint16_t on esp8266 HTTPClient

File: esphome/components/nextion/nextion.cpp [hunk 5]
```diff
@@ -191,6 +191,14 @@ void Nextion::dump_config() {
 #ifdef USE_NEXTION_MAX_QUEUE_SIZE
   ESP_LOGCONFIG(TAG, "  Max queue size: %zu", this->max_queue_size_);
 #endif
+#ifdef USE_NEXTION_TFT_UPLOAD
+  ESP_LOGCONFIG(TAG, "  TFT URL: %s", this->tft_url_.c_str());
+  ESP_LOGCONFIG(TAG, "  TFT upload HTTP timeout: %" PRIu32 "ms", this->tft_upload_http_timeout_);
+  ESP_LOGCONFIG(TAG, "  TFT upload HTTP retries: %u", this->tft_upload_http_retries_);
```
Comment (bdraco) [inline esphome/components/nextion/nextion.cpp]: https://developers.esphome.io/architecture/logging/#configuration-logging-esp_logconfig

File: esphome/components/nextion/display.py (hunk 4 above)
Comment (edwardtfn) [reply esphome/components/nextion/display.py]: Done!
440c81117b4218ce7f5ff2c106476e6937ffc933

File: esphome/components/nextion/nextion.cpp (hunk 5 above)
Comment (edwardtfn) [reply esphome/components/nextion/nextion.cpp]: Done!
440c81117b4218ce7f5ff2c106476e6937ffc933

File: esphome/components/nextion/display.py (hunk 4 above)
Comment (edwardtfn) [reply esphome/components/nextion/display.py]: And I think you are right. ESP8266 limits to uint16_t.
Anyhow, that is a quite big limit already. Probably no one should try setting a higher value.
And it save a few bytes. 😉 

Thanks for highlighting this.

**Review by bdraco — DISMISSED** [review]
Thanks @edwardtfn

**Comment by edwardtfn** [comment]
@bdraco, the code you previously approved was changed in order to not fail silently on ESP8266, but fail at compile time if users try to select incompatible options.
I would be nice if you could take a look specially on `display.py` again. ;)

**Comment by edwardtfn** [comment]
Tested!
Everything looks to be working as intended.

File: esphome/components/nextion/display.py [hunk 6]
```diff
@@ -43,6 +46,9 @@
 DEPENDENCIES = ["uart"]
 AUTO_LOAD = ["binary_sensor", "switch", "sensor", "text_sensor"]
 
+if CORE.is_esp32:
+    AUTO_LOAD.append("watchdog")
```
[the remark this answers is not in the document]
Comment (edwardtfn) [reply esphome/components/nextion/display.py]: Fixed!
1854ef436657f47ff1d276bcdda3e4aa6210c163

**Review by bdraco — APPROVED** [review]

**Comment by bdraco** [comment]
Thanks @edwardtfn
