### PR TITLE
[fix] ESP32-C6 BLE compile error

### LINKED ISSUE #4909: ESP32-C6 bluetooth not working
### The problem

When I tried to enable `esp32_ble_tracker` in my esp32-c6-devkitc-1 board, I encountered some compile error, see the logs below.

### Which version of ESPHome has the issue?

2023.9.0b2

### What type of installation are you using?

Home Assistant Add-on

### Which version of Home Assistant has the issue?

_No response_

### What platform are you using?

ESP32-IDF

### Board

_No response_

### Component causing the issue

_No response_

### Example YAML snippet

```yaml
# snippet of the full config
esp32:
  board: esp32-c6-devkitc-1
  # board: esp32dev
  framework:
    type: esp-idf
    platform_version: 6.4.0
    version: 5.1.1
  variant: esp32c6

esp32_ble_tracker:
  scan_parameters:
    active: true
```

### Anything in the logs that might be useful for us?

```txt
INFO ESPHome 2023.9.0b2
INFO Reading configuration /config/esphome/esp32-c6.yaml...
WARNING The selected ESP-IDF framework version is not the recommended one. If there are connectivity or build issues please remove the manual version.
WARNING The selected ESP-IDF framework version is not the recommended one. If there are connectivity or build issues please remove the manual version.
INFO Generating C++ source...
INFO Updating https://github.com/espressif/esp-protocols.git@mdns-v1.2.0
INFO Compiling app...
Processing esp32-c6 (board: esp32-c6-devkitc-1; framework: espidf; platform: platformio/espressif32@6.4.0)
--------------------------------------------------------------------------------
HARDWARE: ESP32C6 160MHz, 512KB RAM, 8MB Flash
 - framework-espidf @ 3.50101.230828 (5.1.1) 
 - tool-cmake @ 3.16.4 
 - tool-ninja @ 1.7.1 
 - tool-riscv32-esp-elf-gdb @ 12.1.0+20221002 
 - tool-xtensa-esp-elf-gdb @ 12.1.0+20221002 
 - toolchain-esp32ulp @ 2.35.0-20220830 
 - toolchain-riscv32-esp @ 12.2.0+20230208
Reading CMake configuration...
Dependency Graph
|-- noise-c @ 0.1.4
Compiling .pioenvs/esp32-c6/src/esphome/components/api/api_connection.o
Compiling .pioenvs/esp32-c6/src/esphome/components/api/api_frame_helper.o
Compiling .pioenvs/esp32-c6/src/esphome/components/api/api_pb2.o
Compiling .pioenvs/esp32-c6/src/esphome/components/api/api_pb2_service.o
Compiling .pioenvs/esp32-c6/src/esphome/components/api/api_server.o
Compiling .pioenvs/esp32-c6/src/esphome/components/api/list_entities.o
Compiling .pioenvs/esp32-c6/src/esphome/components/api/proto.o
Compiling .pioenvs/esp32-c6/src/esphome/components/api/subscribe_state.o
Compiling .pioenvs/esp32-c6/src/esphome/components/api/user_services.o
Compiling .pioenvs/esp32-c6/src/esphome/components/binary_sensor/automation.o
Compiling .pioenvs/esp32-c6/src/esphome/components/binary_sensor/binary_sensor.o
Compiling .pioenvs/esp32-c6/src/esphome/components/binary_sensor/filter.o
Compiling .pioenvs/esp32-c6/src/esphome/components/bluetooth_proxy/bluetooth_connection.o
Compiling .pioenvs/esp32-c6/src/esphome/components/bluetooth_proxy/bluetooth_proxy.o
Compiling .pioenvs/esp32-c6/src/esphome/components/captive_portal/captive_portal.o
Compiling .pioenvs/esp32-c6/src/esphome/components/esp32/core.o
Compiling .pioenvs/esp32-c6/src/esphome/components/esp32/gpio.o
Compiling .pioenvs/esp32-c6/src/esphome/components/esp32/preferences.o
Compiling .pioenvs/esp32-c6/src/esphome/components/esp32_ble/ble.o
Compiling .pioenvs/esp32-c6/src/esphome/components/esp32_ble/ble_advertising.o
In file included from src/esphome/components/esp32_ble/ble.cpp:7:
src/esphome/components/esp32_ble/ble.cpp: In member function 'bool esphome::esp32_ble::ESP32BLE::ble_setup_()':
/data/cache/platformio/packages/framework-espidf/components/bt/include/esp32c6/include/esp_bt.h:263:1: warning: missing initializer for member 'esp_bt_controller_config_t::cca_drop_mode' [-Wmissing-field-initializers]
  263 | }
      | ^
src/esphome/components/esp32_ble/ble.cpp:62:40: note: in expansion of macro 'BT_CONTROLLER_INIT_CONFIG_DEFAULT'
   62 |       esp_bt_controller_config_t cfg = BT_CONTROLLER_INIT_CONFIG_DEFAULT();
      |                                        ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
/data/cache/platformio/packages/framework-espidf/components/bt/include/esp32c6/include/esp_bt.h:263:1: warning: missing initializer for member 'esp_bt_controller_config_t::cca_low_tx_pwr' [-Wmissing-field-initializers]
  263 | }
      | ^
src/esphome/components/esp32_ble/ble.cpp:62:40: note: in expansion of macro 'BT_CONTROLLER_INIT_CONFIG_DEFAULT'
   62 |       esp_bt_controller_config_t cfg = BT_CONTROLLER_INIT_CONFIG_DEFAULT();
      |                                        ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
/data/cache/platformio/packages/framework-espidf/components/bt/include/esp32c6/include/esp_bt.h:258:58: error: narrowing conversion of 'efuse_hal_chip_revision()' from 'uint32_t' {aka 'long unsigned int'} to 'uint8_t' {aka 'unsigned char'} [-Werror=narrowing]
  258 |     .version_num                = efuse_hal_chip_revision(),                            \
      |                                   ~~~~~~~~~~~~~~~~~~~~~~~^~
src/esphome/components/esp32_ble/ble.cpp:62:40: note: in expansion of macro 'BT_CONTROLLER_INIT_CONFIG_DEFAULT'
   62 |       esp_bt_controller_config_t cfg = BT_CONTROLLER_INIT_CONFIG_DEFAULT();
      |                                        ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
cc1plus: some warnings being treated as errors
*** [.pioenvs/esp32-c6/src/esphome/components/esp32_ble/ble.o] Error 1
========================= [FAILED] Took 54.26 seconds =========================
```

### Additional information

_No response_

### LINKED ISSUE #6248: Build esp32-c6 with esp32_ble_tracker and bluetooth_proxy
### The problem

Unable to build with errors
```
In file included from src/esphome/components/esp32_ble/ble.cpp:6:
src/esphome/components/esp32_ble/const_esp32c6.h:62:1: error: 'const esp_bt_controller_config_t' has no non-static data member named 'enable_uart_hci'
   62 | };
      | ^
Compiling .pioenvs/camerettasensor-5cf4ec/src/esphome/components/esp32_ble_client/ble_characteristic.cpp.o
*** [.pioenvs/camerettasensor-5cf4ec/src/esphome/components/esp32_ble/ble.cpp.o] Error 1
```

### Which version of ESPHome has the issue?

2024.8.3

### What type of installation are you using?

Home Assistant Add-on

### Which version of Home Assistant has the issue?

2024.9.1

### What platform are you using?

ESP32

### Board

Waveshare ESP32-C6 

### Component causing the issue

esp32_ble

### Example YAML snippet

```yaml
esphome:
  name: bletracker-1
  friendly_name: bletracker-1

esp32:
  board: esp32-c6-devkitm-1
  variant: esp32c6
  flash_size: 4MB
  framework:
    type: esp-idf
    version: 5.3.1
    platform_version: 6.8.1
    sdkconfig_options:
        CONFIG_OPENTHREAD_ENABLED: n
        CONFIG_ENABLE_WIFI_STATION: y
        CONFIG_USE_MINIMAL_MDNS: n
        CONFIG_ESPTOOLPY_FLASHSIZE_4MB: y

esp32_ble_tracker:
  scan_parameters:
    active: false

bluetooth_proxy:
  active: false
```

### Anything in the logs that might be useful for us?

```txt
In file included from src/esphome/components/esp32_ble/ble.cpp:6:
src/esphome/components/esp32_ble/const_esp32c6.h:62:1: error: 'const esp_bt_controller_config_t' has no non-static data member named 'enable_uart_hci'
   62 | };
      | ^
Compiling .pioenvs/camerettasensor-5cf4ec/src/esphome/components/esp32_ble_client/ble_characteristic.cpp.o
*** [.pioenvs/camerettasensor-5cf4ec/src/esphome/components/esp32_ble/ble.cpp.o] Error 1
```

### Additional information

I have commented these rows from esphome/components/esp32_ble/const_esp32c6.h in order to build and run correctly on this board.
```
pragma once

#ifdef USE_ESP32_VARIANT_ESP32C6

#include <esp_bt.h>

namespace esphome {
namespace esp32_ble {

static const esp_bt_controller_config_t BT_CONTROLLER_CONFIG = {
    ....
    .enable_qa_test = RUN_QA_TEST,
    .enable_bqb_test = RUN_BQB_TEST,
    // .enable_uart_hci = HCI_UART_EN,
    // .ble_hci_uart_port = DEFAULT_BT_LE_HCI_UART_PORT,
    // .ble_hci_uart_baud = DEFAULT_BT_LE_HCI_UART_BAUD,
    // .ble_hci_uart_data_bits = DEFAULT_BT_LE_HCI_UART_DATA_BITS,
    // .ble_hci_uart_stop_bits = DEFAULT_BT_LE_HCI_UART_STOP_BITS,
    // .ble_hci_uart_flow_ctrl = DEFAULT_BT_LE_HCI_UART_FLOW_CTRL,
    // .ble_hci_uart_uart_parity = DEFAULT_BT_LE_HCI_UART_PARITY,
    .enable_tx_cca = DEFAULT_BT_LE_TX_CCA_ENABLED,
    .cca_rssi_thresh = 256 - DEFAULT_BT_LE_CCA_RSSI_THRESH,
    ...
};

}  // namespace esp32_ble
}  // namespace esphome

#endif  // USE_ESP32_VARIANT_ESP32C6
```

### PR DESCRIPTION
**Pull request by rvalitov**
# What does this implement/fix?
Compilation error happens when trying to use `esp32_ble_tracker` or `bluetooth_proxy` with ESP32-C6.

Example if error message:
```
In file included from src/esphome/components/esp32_ble/ble.cpp:6:
src/esphome/components/esp32_ble/const_esp32c6.h:62:1: error: 'const esp_bt_controller_config_t' has no non-static data member named 'enable_uart_hci'
   62 | };
      | ^
Compiling .pioenvs/camerettasensor-5cf4ec/src/esphome/components/esp32_ble_client/ble_characteristic.cpp.o
*** [.pioenvs/camerettasensor-5cf4ec/src/esphome/components/esp32_ble/ble.cpp.o] Error 1
```

This happens because of some data members in file `const_esp32c6.h` that should not be there in component `esp32_ble`. This PR fixes this issue and removes all such members causing the compilation error. After that the ESP32-C6 works perfectly as a Bluetooth proxy.

## Types of changes

- [ ] Bugfix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] Other

**Related issue or feature (if applicable):** 
- fixes https://github.com/esphome/issues/issues/6248 
- fixes https://github.com/esphome/issues/issues/4909

**Pull request in [esphome-docs](https://github.com/esphome/esphome-docs) with documentation (if applicable):** esphome/esphome-docs#<esphome-docs PR number goes here>

## Test Environment

- [ ] ESP32
- [x] ESP32 IDF
- [ ] ESP8266
- [ ] RP2040
- [ ] BK72xx
- [ ] RTL87xx

## Example entry for `config.yaml`:

```yaml
# Example config.yaml
esphome:
  name: bt-proxy
  friendly_name: Bluetooth Proxy
  platformio_options:
    board_build.flash_mode: dio 

esp32:
  board: esp32-c6-devkitc-1
  variant: ESP32C6
  flash_size: 8MB
  framework:
    type: esp-idf
    version: 5.3.1
    platform_version: 6.9.0
    sdkconfig_options:
      CONFIG_ESPTOOLPY_FLASHSIZE_8MB: y
      CONFIG_BT_BLE_50_FEATURES_SUPPORTED: y
      CONFIG_BT_BLE_42_FEATURES_SUPPORTED: y
      CONFIG_OPENTHREAD_ENABLED: n
      CONFIG_ENABLE_WIFI_STATION: y
      CONFIG_USE_MINIMAL_MDNS: y

wifi:
  ssid: "secret"
  password: "secret"

esp32_ble_tracker:
  id: ble_tracker
  scan_parameters:
    interval: 1100ms
    window: 1100ms
    active: true
    continuous: false

bluetooth_proxy:
  active: true 
```

## Checklist:
  - [x] The code change is tested and works locally.
  - [ ] Tests have been added to verify that the new code works (under `tests/` folder).

If user exposed functionality or configuration variables are added/changed:
  - [ ] Documentation added/updated in [esphome-docs](https://github.com/esphome/esphome-docs).

### CODE REVIEW

**Review by jesserockz — CHANGES_REQUESTED** [review]
I have a test c6 that works with bluetooth_proxy just fine which is when I added this file and code. 
If those fields dont exist with your config, then its because they were removed in a newer esp-idf version, which will need to be handled correctly with preproccesing.

I am using:
```yaml
    version: 5.1.2
    platform_version: 6.5.0
```

**Comment by rvalitov** [comment]
Thank you for the review! I checked the ESP IDF code and found out that some fields have been removed and some have been added since version 5.3.1 with commit https://github.com/espressif/esp-idf/commit/e761c1de8f9c0777829d597b4d5a33bb070a30a8
I applied a check for the ESP IDF version. Is it OK?

File: esphome/components/esp32_ble/const_esp32c6.h [hunk 1]
```diff
@@ -58,6 +62,9 @@ static const esp_bt_controller_config_t BT_CONTROLLER_CONFIG = {
     .cpu_freq_mhz = CONFIG_ESP_DEFAULT_CPU_FREQ_MHZ,
     .ignore_wl_for_direct_adv = 0,
     .enable_pcl = DEFAULT_BT_LE_POWER_CONTROL_ENABLED,
+#if ESP_IDF_VERSION >= ESP_IDF_VERSION_VAL(5, 3, 1)
```
Comment (jesserockz) [inline esphome/components/esp32_ble/const_esp32c6.h]: This field was added in 5.1.3
```suggestion
#if ESP_IDF_VERSION >= ESP_IDF_VERSION_VAL(5, 1, 3)
```

**Review by jesserockz — CHANGES_REQUESTED** [review]

**Review by jesserockz — APPROVED** [review]
