### PR TITLE
[esp32] Fix OTA rollback

### LINKED ISSUE #11296: Reading CMake configuration... Just Hangs sits there 20 min
### The problem

how long is it supposed to hang its been more then 20 min  i cant update any of my devices...    they all stuck on 9.3

and took me like 30 min to download the idf_tools.py   so not sure whats all going on  

```
INFO ESPHome 2025.10.0
INFO Reading configuration /config/esphome/emergency-button-1.yaml...
INFO Detected timezone 'America/Toronto'
INFO Generating C++ source...
INFO Compiling app...
Processing emergency-button-1 (board: esp32dev; framework: arduino, espidf; platform: https://github.com/pioarduino/platform-espressif32/releases/download/54.03.21-2/platform-espressif32.zip)
--------------------------------------------------------------------------------
INFO Installing tools via idf_tools.py (this may take several minutes)...
Tool Manager: Installing file:///root/.platformio/tools/toolchain-xtensa-esp-elf
INFO Installing file:///root/.platformio/tools/toolchain-xtensa-esp-elf
Tool Manager: toolchain-xtensa-esp-elf@14.2.0+20241119 has been installed!
INFO toolchain-xtensa-esp-elf@14.2.0+20241119 has been installed!
INFO Tool toolchain-xtensa-esp-elf successfully installed
INFO Package configuration completed successfully
Tool Manager: Installing https://github.com/pioarduino/registry/releases/download/0.0.1/xtensa-esp-elf-14.2.0_20241119.zip
INFO Installing https://github.com/pioarduino/registry/releases/download/0.0.1/xtensa-esp-elf-14.2.0_20241119.zip
Unpacking  [####################################]  100%
Tool Manager: toolchain-xtensa-esp-elf@14.2.0+20241119 has been installed!
INFO toolchain-xtensa-esp-elf@14.2.0+20241119 has been installed!
Library Manager: Installing esphome/noise-c @ 0.1.10
INFO Installing esphome/noise-c @ 0.1.10
Unpacking  [####################################]  100%
Library Manager: noise-c@0.1.10 has been installed!
INFO noise-c@0.1.10 has been installed!
Library Manager: Resolving dependencies...
INFO Resolving dependencies...
Library Manager: Installing esphome/libsodium @ 1.10020.7
INFO Installing esphome/libsodium @ 1.10020.7
Unpacking  [####################################]  100%
Library Manager: libsodium@1.10020.7 has been installed!
INFO libsodium@1.10020.7 has been installed!
Library Manager: Installing bblanchon/ArduinoJson @ 7.4.2
INFO Installing bblanchon/ArduinoJson @ 7.4.2
Unpacking  [####################################]  100%
Library Manager: ArduinoJson@7.4.2 has been installed!
INFO ArduinoJson@7.4.2 has been installed!
INFO Installing tools via idf_tools.py (this may take several minutes)...
Tool Manager: Installing file:///root/.platformio/tools/toolchain-xtensa-esp-elf
INFO Installing file:///root/.platformio/tools/toolchain-xtensa-esp-elf
Tool Manager: toolchain-xtensa-esp-elf@14.2.0+20241119 has been installed!
INFO toolchain-xtensa-esp-elf@14.2.0+20241119 has been installed!
INFO Tool toolchain-xtensa-esp-elf successfully installed
INFO Package configuration completed successfully
HARDWARE: ESP32 240MHz, 320KB RAM, 4MB Flash
 - framework-arduinoespressif32 @ 3.2.1 
 - framework-arduinoespressif32-libs @ 5.4.0+sha.858a988d6e 
 - framework-espidf @ 3.50402.0 (5.4.2) 
 - tool-cmake @ 3.30.2 
 - tool-esp-rom-elfs @ 2024.10.11 
 - tool-esptoolpy @ 5.0.2 
 - tool-mklittlefs @ 3.2.0 
 - tool-ninja @ 1.13.1 
 - tool-scons @ 4.40801.0 (4.8.1) 
 - toolchain-xtensa-esp-elf @ 14.2.0+20241119
Installing Arduino Python dependencies
Creating a new virtual environment for IDF Python dependencies
Installing ESP-IDF's Python dependencies
Reading CMake configuration...
```

### Which version of ESPHome has the issue?

2025.10.0

### What type of installation are you using?

Home Assistant Add-on

### What platform are you using?

ESP32

### Component causing the issue

all of them

### YAML Config

```yaml
esphome:
  name: emergency-button-1
  friendly_name: "Emergency Button #1 (Office)"

esp32:
  board: esp32dev
  framework:
    type: arduino
```

### Anything in the logs that might be useful for us?

```txt
ive uninstalled esphome  rebooted..
reinstalled esphome in home assistant

then tried to update my devices  but at moment hangs at the cmake 

roughly 30 min  now as of writting this
```

### Additional information

_No response_

### PR DESCRIPTION
**Pull request by swoboda1337**
# What does this implement/fix?

If the bootloader was built with CONFIG_BOOTLOADER_APP_ROLLBACK_ENABLE, as Arduino used to be, ESPHome OTA updates could get rolled back after a reboot. The workaround was to OTA twice in a row so no partition had a valid flag (rollback couldn't happen). 

We can fix this automatically by checking the partition status and marking it valid if the state is pending verify. If rollback was not enabled in the bootloader the state is -1 and nothing is done. 

I believe this will happen to a lot of people after the switch to Arduino as a component as rollback is now disabled in the fw and Arduino will no longer mark the partition as valid https://github.com/espressif/arduino-esp32/blob/master/cores/esp32/esp32-hal-misc.c#L284

## Types of changes

- [x] Bugfix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] Code quality improvements to existing code or addition of tests
- [x] Other

**Related issue or feature (if applicable):**

- fixes https://github.com/esphome/esphome/issues/11296

**Pull request in [esphome-docs](https://github.com/esphome/esphome-docs) with documentation (if applicable):**

- esphome/esphome-docs#<esphome-docs PR number goes here>

## Test Environment

- [ ] ESP32
- [x] ESP32 IDF
- [ ] ESP8266
- [ ] RP2040
- [ ] BK72xx
- [ ] RTL87xx
- [ ] nRF52840

## Example entry for `config.yaml`:

```yaml
# Example config.yaml

```

## Checklist:
  - [x] The code change is tested and works locally.
  - [ ] Tests have been added to verify that the new code works (under `tests/` folder).

If user exposed functionality or configuration variables are added/changed:
  - [ ] Documentation added/updated in [esphome-docs](https://github.com/esphome/esphome-docs).

### CODE REVIEW

**Comment by swoboda1337** [comment]
I think it makes sense to keep the code in esp32/core.cpp. The OTA code doesnt have a great place to put this and it is a good catch all for both frameworks and all configurations. It can be moved later if we ever decide to use the rollback feature.

File: esphome/components/esp32/core.cpp [hunk 1]
```diff
@@ -52,6 +53,16 @@ void arch_init() {
   disableCore1WDT();
 #endif
 #endif
+
+  // If the bootloader was compiled with CONFIG_BOOTLOADER_APP_ROLLBACK_ENABLE the current
+  // partition will get rolled back unless it is marked as valid.
+  esp_ota_img_states_t state;
+  const esp_partition_t *running = esp_ota_get_running_partition();
```
Comment (bdraco) [inline esphome/components/esp32/core.cpp:60]: How will this work if there is no OTA partition?

Comment (swoboda1337) [reply esphome/components/esp32/core.cpp:60]: It only looks at the current partition which always has to be there. Shouldn't matter if there is no OTA partition I guess.

Comment (swoboda1337) [reply esphome/components/esp32/core.cpp:60]: https://github.com/espressif/esp-idf/blob/master/components/app_update/esp_ota_ops.c#L797

Comment (bdraco) [reply esphome/components/esp32/core.cpp:60]: looking at the implementation it is expected to always be successful or abort if the partition can't be found so should be fine

**Comment by bdraco** [comment]
I think this is fine but I'm out of time to test it

**Comment by swoboda1337** [comment]
I will test some specifically with OTA disabled.

**Comment by swoboda1337** [comment]
I tested with a single partition and it works fine and the state is ESP_OTA_IMG_VALID so nothing is done:
```
typedef enum {
    ESP_OTA_IMG_NEW             = 0x0U,         /*!< Monitor the first boot. In bootloader this state is changed to ESP_OTA_IMG_PENDING_VERIFY. */
    ESP_OTA_IMG_PENDING_VERIFY  = 0x1U,         /*!< First boot for this app was. If while the second boot this state is then it will be changed to ABORTED. */
    ESP_OTA_IMG_VALID           = 0x2U,         /*!< App was confirmed as workable. App can boot and work without limits. */
    ESP_OTA_IMG_INVALID         = 0x3U,         /*!< App was confirmed as non-workable. This app will not selected to boot at all. */
    ESP_OTA_IMG_ABORTED         = 0x4U,         /*!< App could not confirm the workable or non-workable. In bootloader IMG_PENDING_VERIFY state will be changed to IMG_ABORTED. This app will not selected to boot at all. */
    ESP_OTA_IMG_UNDEFINED       = 0xFFFFFFFFU,  /*!< Undefined. App can boot and work without limits. */
} esp_ota_img_states_t;
```

**Comment by swoboda1337** [comment]
Most of my boards with older bootloads just return ESP_OTA_IMG_UNDEFINED, so nothing is done.

**Comment by swoboda1337** [comment]
Tested with the newer bootloaders and they return ESP_OTA_IMG_VALID so nothing is done

**Comment by swoboda1337** [comment]
Also verified:
- enabling CONFIG_BOOTLOADER_APP_ROLLBACK_ENABLE then loading via serial and twice via OTA
- disabling CONFIG_BOOTLOADER_APP_ROLLBACK_ENABLE then loading via OTA the state is ESP_OTA_IMG_PENDING_VERIFY
- rebooting the device without the fix rolls back
- with the fix it marks it as valid and does not roll back

**Comment by swoboda1337** [comment]
Should be good to go

**Review by bdraco — APPROVED** [review]

**Comment by bdraco** [comment]
Giving this a test this morning

**Comment by bdraco** [comment]
Tested on a few devices. All good

**Review by bdraco — APPROVED** [review]

**Review by bdraco — APPROVED** [review]

**Comment by bdraco** [comment]
Working on fixing the commenter issue in https://github.com/esphome/esphome/pull/11380

For now this is fine to force merge
