### PR TITLE
[sx127x] Fix FIFO read corruption

### LINKED ISSUE #14872: Potential Bit-Masking Bug in Fine Offset Protocol / SX127x Component - 0x80 Bit Error
Hi everyone,

I'm reporting a consistent issue regarding the hexadecimal data output in a Fine Offset weather station setup using the sx127x-esphome component.

After comparing the output of a "Legacy" receiver (running a direct SX127x implementation by swoboda1337) against a "New" receiver running the latest ESPHome, I've identified a systematic discrepancy affecting 2,229 synchronized rows of data.

The Issue:
The "New" receiver consistently flips the 0x80 bit (the Most Significant Bit) of several bytes in the payload, while the rest of the bits remain identical to the known-good source.

Data Pattern Example:

    Legacy (Good): a9 50 3d 4c ...

    New (ESPHome): a9 d0 3d 4c ...

    XOR Difference: 00 80 00 00 ... (The 0x50 becomes 0xd0 because of the 0x80 bit).

This happens across the entire packet. Sometimes it's constant (like in Byte 2), and sometimes it seems data-dependent in the temperature/humidity bytes, suggesting a potential signed vs. unsigned casting error or a bit-masking issue within the Fine Offset decodification logic or the SPI buffer handling of the SX127x component.

Environment:

    Component: Fine Offset / SX127x

    Source: https://github.com/swoboda1337/sx127x-esphome

    Observation: The error persists even when both sensors receive the exact same RF signal at the same second. It looks like the firmware is applying an OR mask (| 0x80) or failing to clear a parity/status bit from the radio's FIFO.

Has anyone else noticed this MSB corruption in RF protocols? It significantly affects the final decoded values (e.g., triggering signs or adding 128 to raw values).

Attached is a sample of the synchronized logs showing the XOR patterns.

Any insights would be appreciated!

### Which version of ESPHome has the issue?

2026.2.4

### What type of installation are you using?

Docker

### What platform are you using?

ESP32

### Component causing the issue

Fine Offset / SX127x

### YAML Config

```yaml

```

### Anything in the logs that might be useful for us?

```txt

```

### Additional information

[verificacion_patron_0x80.csv](https://github.com/user-attachments/files/26038411/verificacion_patron_0x80.csv)

### PR DESCRIPTION
**Pull request by swoboda1337**
# What does this implement/fix?

Fixes data corruption when reading packets from the SX127x FIFO. Certain byte values in received packets had their MSB (0x80 bit) flipped, causing incorrect data to be passed to listeners.

The issue occurs when using multi-byte SPI transactions (both `read_array` with null TX and `transfer_array` with zeroed TX/RX buffer) to burst-read the SX127x FIFO. The corruption is deterministic and data-dependent — specific byte values always have their MSB flipped.

The fix replaces `read_array` and `write_array` with `transfer_byte` loops in the FIFO access functions. Using individual single-byte SPI transactions within the same CS assertion eliminates the corruption.

**Key findings from testing:**
- `read_array` (null TX, multi-byte): **corrupts** MSB on specific bytes
- `transfer_array` (zero-filled TX=RX buffer, multi-byte): **corrupts** same bytes
- `transfer_byte(0x00)` in loop (single-byte transactions): **works perfectly**
- CC1101 on same ESP32 with same `read_array`: **no corruption**

This points to an interaction between the ESP32 SPI peripheral's multi-byte transaction handling and the SX127x chip specifically. The exact mechanism is unclear, but single-byte transactions reliably avoid it.

**Testing**: Sent a known packet (`a9 50 3d 4c 00 00 01 02 02 e0`) between two ESP32 devices:
- **Before**: received `a9 d0 3d 4c 00 00 01 02 02 60` (bytes 1 and 9 MSB flipped)
- **After**: received `a9 50 3d 4c 00 00 01 02 02 e0` (correct)

Fixes https://github.com/esphome/esphome/issues/14872

## Types of changes

- [x] Bugfix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected) — [policy](https://developers.esphome.io/contributing/code/#what-constitutes-a-c-breaking-change)
- [ ] Developer breaking change (an API change that could break external components) — [policy](https://developers.esphome.io/contributing/code/#what-is-considered-public-c-api)
- [ ] Undocumented C++ API change (removal or change of undocumented public methods that lambda users may depend on) — [policy](https://developers.esphome.io/contributing/code/#c-user-expectations)
- [ ] Code quality improvements to existing code or addition of tests
- [ ] Other

**Related issue or feature (if applicable):**

- fixes https://github.com/esphome/esphome/issues/14872

**Pull request in [esphome-docs](https://github.com/esphome/esphome-docs) with documentation (if applicable):**

- N/A

## Test Environment

- [x] ESP32
- [x] ESP32 IDF
- [ ] ESP8266
- [ ] RP2040/RP2350
- [ ] BK72xx
- [ ] RTL87xx
- [ ] LN882x
- [ ] nRF52840

## Example entry for config.yaml:

No config changes required.

## Checklist:
  - [x] The code change is tested and works locally.
  - [x] Tests have been added to verify that the new code works (under tests/ folder).

### CODE REVIEW

File: esphome/components/sx127x/sx127x.cpp [hunk 1]
```diff
@@ -38,14 +38,18 @@ void SX127x::write_register_(uint8_t reg, uint8_t value) {
...
   this->disable();
 }
 
 void SX127x::write_fifo_(const std::vector<uint8_t> &packet) {
   this->enable();
   this->write_byte(REG_FIFO | 0x80);
-  this->write_array(packet.data(), packet.size());
+  for (const auto &byte : packet) {
+    this->transfer_byte(byte);
+  }
```
Comment (bdraco) [inline esphome/components/sx127x/sx127x.cpp:52]: read fix looks good.

Isn't there a buffer that will buffer either way? Is the write fix needed?

It doesn't really matter for performance though since its all tiny writes

Comment (swoboda1337) [reply esphome/components/sx127x/sx127x.cpp:52]: Its the same hw fifo. I dont know why rx needs separate spi transactions so I made the same change on the tx side.

**Review by bdraco — APPROVED** [review]

File: esphome/components/sx127x/sx127x.cpp (hunk 1 above)
Comment (bdraco) [reply esphome/components/sx127x/sx127x.cpp:52]: not worth trying to sort it out as the correctness risk out weighs the performance concerns here
