### PR TITLE
Fix I2C recovery on Arduino

### LINKED ISSUE #2486: I2C component: Found no i2c devices!
### The problem

All my ESP8266 boards using i2c and compiled with the latest dev-version stop working because the i2c devices are not found anymore.  Recompile with production version 2021.9.1 solves the problem. It looks like a regression is introduced with te latest changes in the i2c component.

Tested with: ssd1306, bh1750, bm680, lcd_pcf8574

### Which version of ESPHome has the issue?

2021.10.0-dev

### What type of installation are you using?

pip

### Which version of Home Assistant has the issue?

_No response_

### What platform are you using?

ESP8266

### Board

d1_mini

### Component causing the issue

i2c

### Example YAML snippet

```yaml
Generic i2c problem with d1_mini boards
```

### Anything in the logs that might be useful for us?

```txt
logs from 2021.10.0-dev

[10:47:25][I][app:099]: ESPHome version 2021.10.0-dev compiled on Sep 28 2021, 10:46:15
[10:47:25][C][i2c.arduino:031]: I2C Bus:
[10:47:25][C][i2c.arduino:032]:   SDA Pin: GPIO5
[10:47:25][C][i2c.arduino:033]:   SCL Pin: GPIO4
[10:47:25][C][i2c.arduino:034]:   Frequency: 50000 Hz
[10:47:25][I][i2c.arduino:036]: Scanning i2c bus for active devices...
[10:47:25][I][i2c.arduino:048]: Found no i2c devices!

when using 2021.9.1 for the same device:

[10:46:44][I][app:102]: ESPHome version 2021.9.1 compiled on Sep 28 2021, 09:07:12
[10:41:28][C][i2c:028]: I2C Bus:
[10:41:28][C][i2c:029]:   SDA Pin: GPIO5
[10:41:28][C][i2c:030]:   SCL Pin: GPIO4
[10:41:28][C][i2c:031]:   Frequency: 50000 Hz
[10:41:28][I][i2c:033]: Scanning i2c bus for active devices...
[10:41:28][I][i2c:040]: Found i2c device at address 0x23
[10:41:28][I][i2c:040]: Found i2c device at address 0x77
```

### Additional information

_No response_

### PR DESCRIPTION
**Pull request by mmakaay**
# What does this implement/fix? 

The new recovery process for the Arduino I2C bus implementation broke device discovery on at least ESP8266. Scanning failed and communicating to I2C peripherals failed as well.

I modified the way in which the SCL is brought to HIGH and LOW state. Not by driving the pin, using it as an output pin, but instead by switching the pin mode. The I2C bus is based on open collector methodology, so driving the pin might have been the culprit here.

## Types of changes

- [x] Bugfix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] Other

**Related issue or feature (if applicable):** fixes https://github.com/esphome/issues/issues/2486

**Pull request in [esphome-docs](https://github.com/esphome/esphome-docs) with documentation (if applicable):** esphome/esphome-docs#<esphome-docs PR number goes here>

## Test Environment

- [x] ESP32
- [x] ESP8266

## Example entry for `config.yaml`:

```yaml
# Example config.yaml

```

## Checklist:
  - [x] The code change is tested and works locally.
  - [ ] Tests have been added to verify that the new code works (under `tests/` folder).
  
If user exposed functionality or configuration variables are added/changed:
  - [ ] Documentation added/updated in [esphome-docs](https://github.com/esphome/esphome-docs).

### CODE REVIEW

**Comment by oxan** [comment]
I remember a discussion on Discord, where I pointed out that Arduino implements the recovery natively and was met with a "it can't hurt, right?" :laughing: Fix looks right to me, though I'd still prefer using the native implementation.

Also, do we need to fix the ESP-IDF implementation as well? I think that one drives the pins as well.

**Comment by OttoWinter** [comment]
> I remember a discussion on Discord, where I pointed out that Arduino implements the recovery natively and was met with a "it can't hurt, right?"

Haha true 😂 

If we need open collector mode we can also just set that with the open drain pinMode:

https://github.com/esp8266/Arduino/blob/64e87f1149a0badf9438b29306d924db75eebf82/cores/esp8266/Arduino.h#L52

https://github.com/espressif/arduino-esp32/blob/317be68cefe4678e49f712e263da8064b75c7d68/cores/esp32/esp32-hal-gpio.h#L51

**Comment by OttoWinter** [comment]
And for esp idf with GPIO_MODE_OUTPUT_OD https://docs.espressif.com/projects/esp-idf/en/latest/esp32/api-reference/peripherals/gpio.html#_CPPv411gpio_mode_t

**Comment by mmakaay** [comment]
The recovery could also be more considerate about the state of the system.
If SDA is HIGH, then there's no need for running recovery to start with.
Also, flipping SCL 9 times to LOW does work, but it's okay to stop once SDA goes from LOW -> HIGH, because then the stuck device is ready sending its data.
And possibly, there should be some consideration for peripherals that pull SCL low to do timer stretching or what's it called. I'm not enough into the whole matter to know that for sure, but a clean implementation might want to wait for SCL to actually go HIGH before doing another drop to LOW.

All in all, I figured that simply "flushing the toilet" without checking if there's an actual "something floating in there" would be okay too, since it's not like this is blocking the device for a long time. It takes around 100us to run the whole sequence. I'm patient enough to wait for that during setup.

**Comment by mmakaay** [comment]
I had to search a bit, but I ended up with pin mode switching because of this comment I found:

"Due to lack of documentation regarding pin circuits from Espressif it’s really hard to say whats going on inside the chip. However I did some tests and it looks like ESP8266 pins do have an open-drain output mode. In Arduino you can enable it by calling pinMode(pin, OUTPUT_OPEN_DRAIN); on the pin of your choice. This mode was used in the original version of our software I2C code.
However we had issues from people forgetting about external pull up resistors, so the code has changed a bit recently. Instead of changing pin output register when banging the bits, we now change pin mode register. The pin is switched between INPUT_PULLUP and OUTPUT modes, which makes it either a weak pull up or a strong pull down (output register has 0 written into it in advance)."
(https://www.esp8266.com/viewtopic.php?p=24474)

I'll check though, to see if `OUTPUT_OPEN_DRAIN` can be used here.
If the recover doesn't break my devices, I will commit that version as a replacement.

**Comment by mmakaay** [comment]
I tested some code, and a D1 Mini + bme680_bsec went back to errors when using the following code.
Does this seem right to you guys?

```c++
  // Start by setting scl high.
  pinMode(scl_pin_, OUTPUT_OPEN_DRAIN);  // NOLINT
  digitalWrite(scl_pin_, 1);             // NOLINT
  delayMicroseconds(half_period_usec);

  // Now generate in total 9 falling-rising edges.
  for (auto i = 0; i < 9; i++) {
    digitalWrite(scl_pin_, 0);  // NOLINT
    delayMicroseconds(half_period_usec);
    digitalWrite(scl_pin_, 1);  // NOLINT
    delayMicroseconds(half_period_usec);
  }
```

When switching back to the original patch and flashing the D1 Mini, things don't even restore automatically. I still have to power cycle the device to get the I2C traffic back for the bme680_bsec.

**Comment by mmakaay** [comment]
Did some analysis with an oscilloscope, and with the working code, the SCL signal for the recovery looks like expected. The signal using `OUTPUT_OPEN_DRAIN` looks about the same. The only difference is that at the start there is one extra LOW, generated when the pin is set to `OUTPUT_OPEN_DRAIN` mode. That shouldn't be an issue. There's simply 10 LOW signals here instead of 9.

What I do see, is that with the working code, the SCL will keep working, however with the failing code, the SCL stays HIGH all the time. So the clock signal is broken somehow. This makes me prefer the mode switching solution :-)

**Comment by mmakaay** [comment]
Looking at the Arduino esp8266 source code, `OUTPUT_OPEN_DRAIN` does exactly that. When using this pin mode `GPC(pin) |= (1 << GPCD)` is used for the open drain part, but `GPF(pin) |= (1 << GPFPU)` (to enable pullup) is not used within that code path.
So that makes `OUTPUT_OPEN_DRAIN` a bit flaky for the recovery IMO, since it would depend on having an external pull up resistor in place or having a peripheral that takes care of the pull up.

File: esphome/components/i2c/i2c_bus_arduino.cpp [hunk 1]
```diff
@@ -100,23 +100,22 @@ void ArduinoI2CBus::recover_() {
...
   // try to get about 100kHz toggle frequency
   const auto half_period_usec = 1000000 / 100000 / 2;
-  const auto recover_scl_periods = 9;
-
-  // configure scl as output
-  pinMode(scl_pin_, OUTPUT);  // NOLINT
 
   // set scl high
-  digitalWrite(scl_pin_, 1);  // NOLINT
+  pinMode(scl_pin_, INPUT);         // NOLINT
```
Comment (OttoWinter) [inline esphome/components/i2c/i2c_bus_arduino.cpp]: why is this line required? Does the line after not already pull the line high (or rather float but with pullups)?

File: esphome/components/i2c/i2c_bus_arduino.cpp [hunk 2]
```diff
@@ -100,23 +100,22 @@ void ArduinoI2CBus::recover_() {
...
+  pinMode(scl_pin_, INPUT_PULLUP);  // NOLINT
+  delayMicroseconds(half_period_usec);
 
   // in total generate 9 falling-rising edges
+  const auto recover_scl_periods = 9;
   for (auto i = 0; i < recover_scl_periods; i++) {
+    pinMode(scl_pin_, INPUT);   // NOLINT
+    pinMode(scl_pin_, OUTPUT);  // NOLINT
```
Comment (OttoWinter) [inline esphome/components/i2c/i2c_bus_arduino.cpp:151]: Does pinMode OUTPUT reset the out register as well (if at any point before, digitalWrite(, HIGH)) was called, would this break?)

might be safer to call digitalWrite(, LOW) before the loop

File: esphome/components/i2c/i2c_bus_arduino.cpp [hunk 3]
```diff
@@ -100,23 +100,22 @@ void ArduinoI2CBus::recover_() {
...
     delayMicroseconds(half_period_usec);
-    digitalWrite(scl_pin_, 0);  // NOLINT
+    pinMode(scl_pin_, INPUT);         // NOLINT
```
Comment (OttoWinter) [inline esphome/components/i2c/i2c_bus_arduino.cpp:155]: same here

**Comment by OttoWinter** [comment]
> Looking at the Arduino esp8266 source code, `OUTPUT_OPEN_DRAIN` does exactly that. When using this pin mode `GPC(pin) |= (1 << GPCD)` is used for the open drain part, but `GPF(pin) |= (1 << GPFPU)` (to enable pullup) is not used within that code path.
> So that makes `OUTPUT_OPEN_DRAIN` a bit flaky for the recovery IMO, since it would depend on having an external pull up resistor in place or having a peripheral that takes care of the pull up.

ah yes that makes sense. thanks for the deep dive, learned a bit today :)

File: esphome/components/i2c/i2c_bus_arduino.cpp (hunk 1 above)
Comment (mmakaay) [reply esphome/components/i2c/i2c_bus_arduino.cpp]: Yeah, it it's not required indeed!

I'm now implementing some other considerations that I had, for example supporting clock timer stretching. I removed the line from this code already.

File: esphome/components/i2c/i2c_bus_arduino.cpp (hunk 2 above)
Comment (mmakaay) [reply esphome/components/i2c/i2c_bus_arduino.cpp:151]: It does not reset the out register. No other component should have done a HIGH write, but I agree that explicitly calling LOW would be best to match the intent of "recovery".
I added these in the latest code.

**Comment by mmakaay** [comment]
I went over the NXP I2C specs to fill in some of my blanks. Together with the remarks that @OttoWinter made, I came up with a new version for the Arduino framework. The basic strategy now is:

* Check if SCL is pulled low. If it is, then the I2C bus cannot become master -> error out.
* Do 9 clock pulses to drain a possibly stuck output byte cycle of a device. This code now also takes clock stretching into account.
* Check if SDA is pulled low. If it is, then the SDA line is seriously stuck -> error out.
* Generate a START condition, which will reset the bus logic of the I2C device(s).
* Generate a STOP condition to finish up the recovery and bring the bus into a good starting state.

I added some logging to the process, and I keep track of the recovery result. The recovery result is now shown in the `dump_config()` output. Example:

```
[01:32:27][I][i2c.arduino:112]: Performing I2C bus recovery
[01:32:27][I][i2c.arduino:147]: Sending 9 clock pulses to make sure SDA is free
[01:32:27][I][i2c.arduino:195]: Generate START condition to reset bus logic of I2C devices
[01:32:27][I][i2c.arduino:206]: Generate STOP condition to finalize recovery

----8<---- 

[01:32:31][C][i2c.arduino:031]: I2C Bus:
[01:32:31][C][i2c.arduino:032]:   SDA Pin: GPIO21
[01:32:31][C][i2c.arduino:033]:   SCL Pin: GPIO22
[01:32:31][C][i2c.arduino:034]:   Frequency: 50000 Hz
[01:32:31][C][i2c.arduino:037]:   Recovery: bus successfully recovered
[01:32:31][I][i2c.arduino:047]: Scanning i2c bus for active devices...
[01:32:31][I][i2c.arduino:052]: Found i2c device at address 0x77
```

This way, it is visible what is going on and knowing that SCL or SDA is pulled low incorrectly, causing I2C recovery to fail, could point people at faulty hardware wiring.

**Test of error case: SCL hard-linked to GND**

```
[01:59:27][I][i2c.arduino:112]: Performing I2C bus recovery
[01:59:27][E][i2c.arduino:120]: Recovery failed: SCL is held LOW, I2C bus cannot become master

----8<---- 

[01:59:31][C][i2c.arduino:031]: I2C Bus:
[01:59:31][C][i2c.arduino:032]:   SDA Pin: GPIO21
[01:59:31][C][i2c.arduino:033]:   SCL Pin: GPIO22
[01:59:31][C][i2c.arduino:034]:   Frequency: 50000 Hz
[01:59:31][C][i2c.arduino:040]:   Recovery: failed, SCL is held low on the bus
```

**Test of error case SDA hard-linked to GND**

```
[02:02:28][I][i2c.arduino:112]: Performing I2C bus recovery
[02:02:28][I][i2c.arduino:147]: Sending 9 clock pulses to make sure SDA is free
[02:02:28][E][i2c.arduino:179]: Recovery failed: SDA is LOW after clock pulse cycle

----8<---- 

[02:02:32][C][i2c.arduino:031]: I2C Bus:
[02:02:32][C][i2c.arduino:032]:   SDA Pin: GPIO21
[02:02:32][C][i2c.arduino:033]:   SCL Pin: GPIO22
[02:02:32][C][i2c.arduino:034]:   Frequency: 50000 Hz
[02:02:32][C][i2c.arduino:043]:   Recovery: failed, SDA is held low on the bus
```

Oh yeah, and there' s quite a bit of comments in the code now, to document the why of things. I don't think that the code would be a fun read without this added information.

I'll do one quick code cleanup cycle, and then I'll push these updates.

File: esphome/components/i2c/i2c_bus.h [hunk 4]
```diff
@@ -15,6 +15,12 @@ enum ErrorCode {
   ERROR_UNKNOWN = 6,
 };
 
+enum RecoveryCode {
```
Comment (OttoWinter) [inline esphome/components/i2c/i2c_bus.h]: That should be in `i2c_bus_arduino.h` IMO; it doesn't concern the i2c abstract interface, and is done by each implementation itself.

Comment (mmakaay) [reply esphome/components/i2c/i2c_bus.h]: But if the Arduino version is acceptable like this, I also want to update the esp-idf version. And then the exact same result codes will be used. So therefore the enum felt like a shared one to me. If you want to first merge this commit (not a bad idea since it's broken now), it would definitely be cleaner to move it next to the code that now uses it. I'll do that right away.

When this one is merged, I will start on the esp-idf version. I might then move recovery into a separate set of classes anyway, to handle the high level recovery policy in only one place. But that will be a concern for that PR then.

Comment (OttoWinter) [reply esphome/components/i2c/i2c_bus.h]: `i2c_bus.h` exposes an abstract interface for i2c buses. The only thing it should contain is what's necessary to describe that interface.

i2c bus _recovery_ is an implementation detail (that each implementation of an `I2CBus` does itself). i2c devices (`I2CDevice`) shouldn't be concerned with recovery, unless there is a need to expose the recovery state in the abstract `I2CBus`

The main difference IMO is this: I think of `i2c_bus.h` as an interface description, as opposed to an implementation helper for the `I2CBus` _implementations_ (I know esphome in the past often uses the latter system for files, but I'm slowly trying to change that to clean things up :smile:  )

**Review by OttoWinter — APPROVED** [review]

File: esphome/components/i2c/i2c_bus.h (hunk 4 above)
Comment (mmakaay) [reply esphome/components/i2c/i2c_bus.h]: I'm a huge fan of interfaces and the SOLID principles, so I get the architectural choice for this.
It will lead to some code duplication when keeping all code strictly within the two implementation files, but we're talking about just two implementations here, and if they are working correctly, there's not much need for change anymore.
I'll create the esp-idf version with that in mind.
