### PR TITLE
Fix ir_climate on ESP32-C3

### LINKED ISSUE #2422: ir_climate component doesn't compile for ESP32-C3
### The problem

The ir_climate component doesn't compile for ESP32-C3.

### Which version of ESPHome has the issue?

v2021.8.2

### What type of installation are you using?

Docker

### Which version of Home Assistant has the issue?

_No response_

### What platform are you using?

ESP32

### Board

esp32-c3-devkitm-1

### Component causing the issue

ir_climate

### Example YAML snippet

_No response_

### Anything in the logs that might be useful for us?

```txt
src/esphome/components/remote_base/remote_base.cpp: In member function 'void esphome::remote_base::RemoteRMTChannel::config_rmt(rmt_config_t&)':
src/esphome/components/remote_base/remote_base.cpp:17:67: error: 'RMT_CHANNEL_7' was not declared in this scope
   if (rmt_channel_t(int(this->channel_) + this->mem_block_num_) > RMT_CHANNEL_7) {
                                                                   ^~~~~~~~~~~~~
src/esphome/components/remote_base/remote_base.cpp:17:67: note: suggested alternative: 'RMT_CHANNEL_3'
   if (rmt_channel_t(int(this->channel_) + this->mem_block_num_) > RMT_CHANNEL_7) {
                                                                   ^~~~~~~~~~~~~
                                                                   RMT_CHANNEL_3
*** [.pioenvs/esp32c3-ac-kitchen/src/esphome/components/remote_base/remote_base.cpp.o] Error 1
src/esphome/components/remote_transmitter/remote_transmitter_esp32.cpp: In member function 'virtual void esphome::remote_transmitter::RemoteTransmitterComponent::send_internal(uint32_t, uint32_t)':
src/esphome/components/remote_transmitter/remote_transmitter_esp32.cpp:95:41: error: no matching function for call to 'min(int32_t&, int)'
       int32_t item = std::min(val, 32767);
                                         ^
In file included from /root/.platformio/packages/toolchain-riscv32-esp/riscv32-esp-elf/include/c++/8.4.0/bits/char_traits.h:39,
                 from /root/.platformio/packages/toolchain-riscv32-esp/riscv32-esp-elf/include/c++/8.4.0/string:40,
                 from src/esphome/core/component.h:3,
                 from src/esphome/components/remote_transmitter/remote_transmitter.h:3,
                 from src/esphome/components/remote_transmitter/remote_transmitter_esp32.cpp:1:
/root/.platformio/packages/toolchain-riscv32-esp/riscv32-esp-elf/include/c++/8.4.0/bits/stl_algobase.h:195:5: note: candidate: 'template<class _Tp> const _Tp& std::min(const _Tp&, const _Tp&)'
     min(const _Tp& __a, const _Tp& __b)
     ^~~
/root/.platformio/packages/toolchain-riscv32-esp/riscv32-esp-elf/include/c++/8.4.0/bits/stl_algobase.h:195:5: note:   template argument deduction/substitution failed:
src/esphome/components/remote_transmitter/remote_transmitter_esp32.cpp:95:41: note:   deduced conflicting types for parameter 'const _Tp' ('long int' and 'int')
       int32_t item = std::min(val, 32767);
                                         ^
In file included from /root/.platformio/packages/toolchain-riscv32-esp/riscv32-esp-elf/include/c++/8.4.0/bits/char_traits.h:39,
                 from /root/.platformio/packages/toolchain-riscv32-esp/riscv32-esp-elf/include/c++/8.4.0/string:40,
                 from src/esphome/core/component.h:3,
                 from src/esphome/components/remote_transmitter/remote_transmitter.h:3,
                 from src/esphome/components/remote_transmitter/remote_transmitter_esp32.cpp:1:
/root/.platformio/packages/toolchain-riscv32-esp/riscv32-esp-elf/include/c++/8.4.0/bits/stl_algobase.h:243:5: note: candidate: 'template<class _Tp, class _Compare> const _Tp& std::min(const _Tp&, const _Tp&, _Compare)'
     min(const _Tp& __a, const _Tp& __b, _Compare __comp)
     ^~~
/root/.platformio/packages/toolchain-riscv32-esp/riscv32-esp-elf/include/c++/8.4.0/bits/stl_algobase.h:243:5: note:   template argument deduction/substitution failed:
src/esphome/components/remote_transmitter/remote_transmitter_esp32.cpp:95:41: note:   deduced conflicting types for parameter 'const _Tp' ('long int' and 'int')
       int32_t item = std::min(val, 32767);
                                         ^
In file included from /root/.platformio/packages/toolchain-riscv32-esp/riscv32-esp-elf/include/c++/8.4.0/algorithm:62,
                 from /root/.platformio/packages/framework-arduinoespressif32@src-537c58760dafe7fcc8a1d9bbcf00b6f6/cores/esp32/Arduino.h:155,
                 from src/esphome/core/component.h:5,
                 from src/esphome/components/remote_transmitter/remote_transmitter.h:3,
                 from src/esphome/components/remote_transmitter/remote_transmitter_esp32.cpp:1:
/root/.platformio/packages/toolchain-riscv32-esp/riscv32-esp-elf/include/c++/8.4.0/bits/stl_algo.h:3450:5: note: candidate: 'template<class _Tp> _Tp std::min(std::initializer_list<_Tp>)'
     min(initializer_list<_Tp> __l)
     ^~~
/root/.platformio/packages/toolchain-riscv32-esp/riscv32-esp-elf/include/c++/8.4.0/bits/stl_algo.h:3450:5: note:   template argument deduction/substitution failed:
src/esphome/components/remote_transmitter/remote_transmitter_esp32.cpp:95:41: note:   mismatched types 'std::initializer_list<_Tp>' and 'long int'
       int32_t item = std::min(val, 32767);
                                         ^
In file included from /root/.platformio/packages/toolchain-riscv32-esp/riscv32-esp-elf/include/c++/8.4.0/algorithm:62,
                 from /root/.platformio/packages/framework-arduinoespressif32@src-537c58760dafe7fcc8a1d9bbcf00b6f6/cores/esp32/Arduino.h:155,
                 from src/esphome/core/component.h:5,
                 from src/esphome/components/remote_transmitter/remote_transmitter.h:3,
                 from src/esphome/components/remote_transmitter/remote_transmitter_esp32.cpp:1:
/root/.platformio/packages/toolchain-riscv32-esp/riscv32-esp-elf/include/c++/8.4.0/bits/stl_algo.h:3456:5: note: candidate: 'template<class _Tp, class _Compare> _Tp std::min(std::initializer_list<_Tp>, _Compare)'
     min(initializer_list<_Tp> __l, _Compare __comp)
     ^~~
/root/.platformio/packages/toolchain-riscv32-esp/riscv32-esp-elf/include/c++/8.4.0/bits/stl_algo.h:3456:5: note:   template argument deduction/substitution failed:
src/esphome/components/remote_transmitter/remote_transmitter_esp32.cpp:95:41: note:   mismatched types 'std::initializer_list<_Tp>' and 'long int'
       int32_t item = std::min(val, 32767);
                                         ^
*** [.pioenvs/esp32c3-ac-kitchen/src/esphome/components/remote_transmitter/remote_transmitter_esp32.cpp.o] Error 1
```

### Additional information

_No response_

### PR DESCRIPTION
**Pull request by stintel**
# What does this implement/fix? 

Fixes remote_base and remote_transmitter on ESP32-C3, so that ir_climate component can be used.

## Types of changes

- [x] Bugfix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] Other

**Related issue or feature (if applicable):** fixes esphome/issues#2422

**Pull request in [esphome-docs](https://github.com/esphome/esphome-docs) with documentation (if applicable):** esphome/esphome-docs#<esphome-docs PR number goes here>

## Test Environment

- [x] ESP32
- [ ] ESP8266

## Example entry for `config.yaml`:
```yaml
remote_transmitter:
  pin: 3
  carrier_duty_percent: 50%

climate:
  - platform: coolix       # adjust to match your AC unit!
    name: "Living Room AC"
```

## Checklist:
  - [x] The code change is tested and works locally.
  - [ ] Tests have been added to verify that the new code works (under `tests/` folder).
  
If user exposed functionality or configuration variables are added/changed:
  - [ ] Documentation added/updated in [esphome-docs](https://github.com/esphome/esphome-docs).

### CODE REVIEW

File: esphome/components/remote_base/remote_base.cpp [hunk 1]
```diff
@@ -7,15 +7,20 @@ namespace remote_base {
 static const char *const TAG = "remote_base";
 
 #ifdef ARDUINO_ARCH_ESP32
+#if SOC_RMT_CHANNELS_PER_GROUP > 4
+#define RMT_CHANNEL_MAX RMT_CHANNEL_7
+#else
+#define RMT_CHANNEL_MAX RMT_CHANNEL_3
+#endif
```
Comment (oxan) [inline esphome/components/remote_base/remote_base.cpp]: The `SOC_RMT_CHANNELS_PER_GROUP` define is new with v2 of the Arduino platform. The order in which this is coded here would cause the limit to drop down to 4 on the Arduino v1, which is still the default.

Luckily it seems the `rmt_channel_t` type defines `RMT_CHANNEL_MAX` as its last member, so using that minus one should work.

**Review by oxan — CHANGES_REQUESTED** [review]

File: esphome/components/remote_base/remote_base.cpp (hunk 1 above)
Comment (stintel) [reply esphome/components/remote_base/remote_base.cpp]: Seems like @OttoWinter beat me to it.

**Review by OttoWinter — APPROVED** [review]
