### PR TITLE
[uart] Setup uart pins only if flags are set

### LINKED ISSUE #11823: ESPHome 2025.10.3 breaks UART on external component
### The problem

From 2025.10.3, like this change https://github.com/esphome/esphome/pull/9248 breaks the UART communication of this external component https://github.com/pedobry/esphome_toshiba_suzumi/tree/main/components/toshiba_suzumi. It is also reported here https://github.com/pedobry/esphome_toshiba_suzumi/issues/33.

I looked at it using an oscilloscope but I wasn't able to track down the issue. Maybe @asergunov has an idea.

### Which version of ESPHome has the issue?

2025.10.3

### What type of installation are you using?

Docker

### What platform are you using?

ESP32

### Component causing the issue

uart

### YAML Config

```yaml
esphome:
  name: "climate-living-room"

esp32:
  board: nodemcu-32s
  framework:
    type: arduino

external_components:
  - source: 
      type: git
      url: https://github.com/pedobry/esphome_toshiba_suzumi
    components: [toshiba_suzumi]

logger:
  level: info

uart:
  id: uart_bus
  tx_pin: 33
  rx_pin: 32
  parity: EVEN
  baud_rate: 9600

climate:
  - platform: toshiba_suzumi
    name: living-room
    id: living_room
    uart_id: uart_bus
    outdoor_temp:        # Optional. Outdoor temperature sensor
      name: Outdoor Temp
      filters:
        # Filter out value 127 as that's what unit sends when it can's measure the outside temp.
        - filter_out: 127 
    power_select:
      name: "Power level"
    #horizontal_swing: true # Optional. Uncomment if your HVAC supports also horizontal swing
    #supported_presets:          # Optional. Enable only the features your HVAC
      #- "Standard"
      #- "Hi POWER"
      #- "ECO"
      #- "Fireplace 1"
      #- "Fireplace 2"
      #- "8 degrees"             # When enabling this mode, the temp range is set to 5-30°C
      #- "Silent#1"
      #- "Silent#2"
      #- "Sleep"
      #- "Floor"
      #- "Comfort"
    #disable_wifi_led: true # Optional. Disable Wifi LED on internal unit.

# Enable button to scan for unknown values in AC unit. This is optional.
button:
  - platform: template
    name: "Scan for unknown sensors"
    icon: "mdi:reload"
    on_press:
      then:
         # id(living_room) is the id of the climate component above
        - lambda: |-
            auto* controller = static_cast<toshiba_suzumi::ToshibaClimateUart*>(id(living_room));
            controller->scan();

# Enable Home Assistant API
api:
  encryption:
    key: !secret ha_enc_key

ota:
  password: !secret ota_password

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password

  # Enable fallback hotspot (captive portal) in case wifi connection fails
  ap:
    ssid: "A Fallback Hotspot"
    password: "xxxxxxxxxxx"
```

### Anything in the logs that might be useful for us?

```txt
Unfortunately, even with debug turned on I can't see any uart related output that differs from 2025.10.2
```

### Additional information

_No response_

### PR DESCRIPTION
**Pull request by asergunov**
# What does this implement/fix?

Don't call pin setup code if there are no pull or open drain flags set

Fixes a regression introduced in PR #9248 where unconditionally calling `pin->setup()` on UART RX/TX pins broke UART communication for some external components.

**Root cause:** PR #9248 added `pin->setup()` calls to enable pullup/pulldown support, but calling `setup()` on pins without any special flags changes their configuration from the hardware default state. Some UART hardware (particularly external components using custom protocols) relies on the default pin state.

**Solution:** Only call `pin->setup()` when the pin has special flags set (`FLAG_PULLUP`, `FLAG_PULLDOWN`, or `FLAG_OPEN_DRAIN`). This preserves the pullup/pulldown functionality from #9248 while maintaining backward compatibility for pins without special configuration.

## Types of changes

- [x] Bugfix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] Code quality improvements to existing code or addition of tests
- [ ] Other

**Related issue or feature (if applicable):**

- fixes https://github.com/esphome/esphome/issues/11823

**Pull request in [esphome-docs](https://github.com/esphome/esphome-docs) with documentation (if applicable):**

- esphome/esphome-docs#<esphome-docs PR number goes here>

## Test Environment

- [x] ESP32
- [x] ESP32 IDF
- [ ] ESP8266
- [ ] RP2040
- [ ] BK72xx
- [ ] RTL87xx
- [ ] nRF52840

## Example entry for `config.yaml`:

```yaml
# Example config.yaml

```

## Checklist:
  - [ ] The code change is tested and works locally.
  - [ ] Tests have been added to verify that the new code works (under `tests/` folder).

If user exposed functionality or configuration variables are added/changed:
  - [ ] Documentation added/updated in [esphome-docs](https://github.com/esphome/esphome-docs).

### CODE REVIEW

File: esphome/components/uart/uart_component_rp2040.cpp [hunk 1]
```diff
@@ -52,11 +52,19 @@ uint16_t RP2040UartComponent::get_config() {
 }
 
 void RP2040UartComponent::setup() {
-  if (this->rx_pin_) {
-    this->rx_pin_->setup();
-  }
-  if (this->tx_pin_ && this->rx_pin_ != this->tx_pin_) {
-    this->tx_pin_->setup();
+  auto setup_component_if_needed = [](InternalGPIOPin *pin) {
```
Comment (bdraco) [inline esphome/components/uart/uart_component_rp2040.cpp]:
```suggestion
  auto setup_pin_if_needed = [](InternalGPIOPin *pin) {
```

File: esphome/components/uart/uart_component_rp2040.cpp [hunk 2]
```diff
@@ -52,11 +52,19 @@ uint16_t RP2040UartComponent::get_config() {
...
+    }
+    const auto mask = gpio::Flags::FLAG_OPEN_DRAIN | gpio::Flags::FLAG_PULLUP | gpio::Flags::FLAG_PULLDOWN;
+    if (pin->get_flags() & mask) {
+      pin->setup();
+    }
+  };
+
+  setup_component_if_needed(this->rx_pin_);
+  if (this->rx_pin_ != this->tx_pin_) {
+    setup_component_if_needed(this->tx_pin_);
```
Comment (bdraco) [inline esphome/components/uart/uart_component_rp2040.cpp]:
```suggestion
  setup_pin_if_needed(this->rx_pin_);
  if (this->rx_pin_ != this->tx_pin_) {
    setup_pin_if_needed(this->tx_pin_);
```

File: esphome/components/uart/uart_component_esp_idf.cpp [hunk 3]
```diff
@@ -123,11 +123,19 @@ void IDFUARTComponent::load_settings(bool dump_config) {
...
-    this->rx_pin_->setup();
-  }
-  if (this->tx_pin_ && this->rx_pin_ != this->tx_pin_) {
-    this->tx_pin_->setup();
+  auto setup_pin_if_needed = [](InternalGPIOPin *pin) {
+    if (!pin) {
+      return;
+    }
+    const auto mask = gpio::Flags::FLAG_OPEN_DRAIN | gpio::Flags::FLAG_PULLUP | gpio::Flags::FLAG_PULLDOWN;
+    if (pin->get_flags() & mask) {
```
Comment (bdraco) [inline esphome/components/uart/uart_component_esp_idf.cpp]:
```suggestion
    if ((pin->get_flags() & mask) != gpio::Flags::FLAG_NONE) {
```

libretiny version is a bit more explict and clearer about the intent

File: esphome/components/uart/uart_component_esp8266.cpp [hunk 4]
```diff
@@ -56,11 +56,19 @@ uint32_t ESP8266UartComponent::get_config() {
...
-    this->rx_pin_->setup();
-  }
-  if (this->tx_pin_ && this->rx_pin_ != this->tx_pin_) {
-    this->tx_pin_->setup();
+  auto setup_pin_if_needed = [](InternalGPIOPin *pin) {
+    if (!pin) {
+      return;
+    }
+    const auto mask = gpio::Flags::FLAG_OPEN_DRAIN | gpio::Flags::FLAG_PULLUP | gpio::Flags::FLAG_PULLDOWN;
+    if (pin->get_flags() & mask) {
```
Comment (bdraco) [inline esphome/components/uart/uart_component_esp8266.cpp]:
```suggestion
    if ((pin->get_flags() & mask) != gpio::Flags::FLAG_NONE) {
```

libretiny version is a bit more explict and clearer about the intent

File: esphome/components/uart/uart_component_rp2040.cpp [hunk 5]
```diff
@@ -52,11 +52,19 @@ uint16_t RP2040UartComponent::get_config() {
...
-    this->rx_pin_->setup();
-  }
-  if (this->tx_pin_ && this->rx_pin_ != this->tx_pin_) {
-    this->tx_pin_->setup();
+  auto setup_component_if_needed = [](InternalGPIOPin *pin) {
+    if (!pin) {
+      return;
+    }
+    const auto mask = gpio::Flags::FLAG_OPEN_DRAIN | gpio::Flags::FLAG_PULLUP | gpio::Flags::FLAG_PULLDOWN;
+    if (pin->get_flags() & mask) {
```
Comment (bdraco) [inline esphome/components/uart/uart_component_rp2040.cpp]:
```suggestion
    if ((pin->get_flags() & mask) != gpio::Flags::FLAG_NONE) {
```

libretiny version is a bit more explict and clearer about the intent

**Review by jesserockz — APPROVED** [review]
