### PR TITLE
[online_image] Fix some large PNGs causing watchdog timeout

### LINKED ISSUE #11897: online_image runs out of watchdog time on large images, or at least it seems.
### The problem

When using large images, that are uploaded to e-ink display (inkplate 10 in my case) will trigger a WDT timeout.
At the moment, I can display 800x400 images without any issues, however when image size increases then WDT triggers are happening more often. The limiting resolution (regardless of bit depth / format, ie png or bmp) for me is 1200x600 

Below is a log from trying to get an image that has 1200x825 (however at resolution of 1200x650 it's already impossible to escape this error)

### Which version of ESPHome has the issue?

commit 67524e14eec345fecf60daf7251e67be7ff9a364 (HEAD -> dev, origin/dev, origin/HEAD)

### What type of installation are you using?

pip

### What platform are you using?

ESP32

### Component causing the issue

online_image (OR display component) 

### YAML Config

```yaml
esphome:
  name: inkplate-10-1
  friendly_name: inkplate_10-1

esp32:
  board: esp-wrover-kit
  cpu_frequency: 240MHz
  framework:
    type: esp-idf

psram:
   mode: quad
   speed: 80MHz

# Enable logging
#logger:

# Enable logging
logger:
  level: VERBOSE

debug:
  update_interval: 5s

text_sensor:
  - platform: debug
    device:
      name: "Device Info"
    reset_reason:
      name: "Reset Reason"

# Enable Home Assistant API
api:
  encryption:
    key: REDACTED

ota:
  - platform: esphome
    password: REDACTED

wifi:
  ssid: REDACTED
  password: REDACTED
  fast_connect: true
  enable_btm: true
  enable_rrm: true
  use_psram: true
  on_connect:
    - component.update: dashboard_image

i2c:

pca6416a:
  - id: pca6416a_hub
    address: 0x20
    # Primary expander for display control and additional I/O
  - id: pca6416a_hub2
    address: 0x21
    # Secondary expander for additional I/O

http_request:
  id: fetch_image_request
  verify_ssl: false
  useragent: esphome/seeed-studio-display-1
  timeout: 120s
  watchdog_timeout: 4min

online_image:
  - id: dashboard_image
    format: BMP
    type: RGB
    buffer_size: 65536
    url: http://192.168.161.1:5000/2
    update_interval: 1min
    on_download_finished:
      - component.update: main_display

display:
  - platform: inkplate
    id: main_display
    greyscale: true
    partial_updating: true
    update_interval: never
    model: inkplate_10
    lambda: |-
      it.image(0, 0, id(dashboard_image));
    ckv_pin: 32
    sph_pin: 33
    gmod_pin:
      pca6416a: pca6416a_hub
      number: 1
    gpio0_enable_pin:
      pca6416a: pca6416a_hub
      number: 8
    oe_pin:
      pca6416a: pca6416a_hub
      number: 0
    spv_pin:
      pca6416a: pca6416a_hub
      number: 2
    powerup_pin:
      pca6416a: pca6416a_hub
      number: 4
    wakeup_pin:
      pca6416a: pca6416a_hub
      number: 3
    vcom_pin:
      pca6416a: pca6416a_hub
      number: 5
```

### Anything in the logs that might be useful for us?

```txt
[22:43:55.150][C][wifi:803]:   Local MAC: 94:E6:86:A7:0A:C8
[22:43:55.151][C][wifi:810]:   IP Address: 192.168.160.209
[22:43:55.152][C][wifi:814]:   SSID: 'hmmm'
[22:43:55.154][C][wifi:814]:   BSSID: D4:5D:64:EC:79:61
[22:43:55.157][C][wifi:814]:   Hostname: 'inkplate-10-1'
[22:43:55.163][C][wifi:814]:   Signal strength: -69 dB ▂▄▆█
[22:43:55.163][C][wifi:814]:   Channel: 12
[22:43:55.166][C][wifi:814]:   Subnet: 255.255.252.0
[22:43:55.168][C][wifi:814]:   Gateway: 192.168.163.254
[22:43:55.171][C][wifi:814]:   DNS1: 192.168.163.254
[22:43:55.171][C][wifi:814]:   DNS2: 0.0.0.0
[22:43:55.174][C][wifi:833]:   BTM: enabled
[22:43:55.177][C][wifi:833]:   RRM: enabled
[22:43:55.188][V][esp32.preferences:067]: nvs_get_blob('3487505085'): ESP_ERR_NVS_NOT_FOUND - the key might not be set yet
[22:43:55.193][D][wifi:1599]: Saved fast_connect settings
[22:43:55.199][I][online_image:109]: Updating image http://192.168.161.1:5000/2
[22:43:55.205][V][http_request.watchdog:039]: Adjusting WDT to 240000ms
[22:43:55.222][D][http_request.idf:043]: Received response header, name: last-modified, value: Thu, 13 Nov 2025 22:43:02 GMT
[22:43:55.228][V][http_request.watchdog:039]: Adjusting WDT to 5000ms
[22:43:55.234][D][online_image:175]: Starting download
[22:43:55.239][D][online_image:180]: Allocating BMP decoder
[22:43:55.245][I][online_image:212]: Downloading image (Size: 2970138)
[22:43:55.250][W][component:337]: wifi cleared Warning flag
[22:43:55.256][W][component:454]: wifi took a long time for an operation (57 ms)
[22:43:55.261][W][component:457]: Components should block for at most 30 ms
[22:43:55.269][V][http_request.watchdog:039]: Adjusting WDT to 240000ms
[22:43:55.380][V][http_request.watchdog:039]: Adjusting WDT to 5000ms
[22:43:55.387][D][online_image:089]: Allocating new buffer of 2970000 bytes
[22:43:55.390][V][online_image:100]: New size: (1200, 825)
[22:43:55.482][W][component:454]: online_image took a long time for an operation (230 ms)
[22:43:55.488][W][component:457]: Components should block for at most 30 ms
[22:43:55.496][V][http_request.watchdog:039]: Adjusting WDT to 240000ms
[22:43:55.670][V][http_request.watchdog:039]: Adjusting WDT to 5000ms
[22:43:55.775][W][component:454]: online_image took a long time for an operation (290 ms)
[22:43:55.781][W][component:457]: Components should block for at most 30 ms
[22:43:55.789][V][http_request.watchdog:039]: Adjusting WDT to 240000ms
[22:43:55.984][V][http_request.watchdog:039]: Adjusting WDT to 5000ms
[22:43:56.086][W][component:454]: online_image took a long time for an operation (307 ms)
[22:43:56.092][W][component:457]: Components should block for at most 30 ms
[22:43:56.099][V][http_request.watchdog:039]: Adjusting WDT to 240000ms
[22:43:56.279][V][http_request.watchdog:039]: Adjusting WDT to 5000ms
[22:43:56.383][V][http_request.watchdog:039]: Adjusting WDT to 240000ms
[22:43:56.538][V][http_request.watchdog:039]: Adjusting WDT to 5000ms
[22:43:56.643][V][http_request.watchdog:039]: Adjusting WDT to 240000ms
[22:43:56.761][V][http_request.watchdog:039]: Adjusting WDT to 5000ms
[22:43:56.867][V][http_request.watchdog:039]: Adjusting WDT to 240000ms
[22:43:56.984][V][http_request.watchdog:039]: Adjusting WDT to 5000ms
[22:43:57.087][V][http_request.watchdog:039]: Adjusting WDT to 240000ms
[22:43:57.209][V][http_request.watchdog:039]: Adjusting WDT to 5000ms
[22:43:57.313][V][http_request.watchdog:039]: Adjusting WDT to 240000ms
[22:43:57.430][V][http_request.watchdog:039]: Adjusting WDT to 5000ms
[22:43:57.533][V][http_request.watchdog:039]: Adjusting WDT to 240000ms
[22:43:57.650][V][http_request.watchdog:039]: Adjusting WDT to 5000ms
[22:43:57.756][V][http_request.watchdog:039]: Adjusting WDT to 240000ms
[22:43:57.871][V][http_request.watchdog:039]: Adjusting WDT to 5000ms
[22:43:57.975][V][http_request.watchdog:039]: Adjusting WDT to 240000ms
[22:43:58.107][V][http_request.watchdog:039]: Adjusting WDT to 5000ms
[22:43:58.213][V][http_request.watchdog:039]: Adjusting WDT to 240000ms
[22:43:58.328][V][http_request.watchdog:039]: Adjusting WDT to 5000ms
[22:43:58.432][V][http_request.watchdog:039]: Adjusting WDT to 240000ms
[22:43:58.561][V][http_request.watchdog:039]: Adjusting WDT to 5000ms
[22:43:58.665][V][http_request.watchdog:039]: Adjusting WDT to 240000ms
[22:43:58.798][V][http_request.watchdog:039]: Adjusting WDT to 5000ms
[22:43:58.899][V][http_request.watchdog:039]: Adjusting WDT to 240000ms
[22:43:59.048][V][http_request.watchdog:039]: Adjusting WDT to 5000ms
[22:43:59.154][V][http_request.watchdog:039]: Adjusting WDT to 240000ms
[22:43:59.271][V][http_request.watchdog:039]: Adjusting WDT to 5000ms
[22:43:59.378][V][http_request.watchdog:039]: Adjusting WDT to 240000ms
[22:43:59.509][V][http_request.watchdog:039]: Adjusting WDT to 5000ms
[22:43:59.614][V][http_request.watchdog:039]: Adjusting WDT to 240000ms
[22:43:59.741][V][http_request.watchdog:039]: Adjusting WDT to 5000ms
[22:43:59.845][V][http_request.watchdog:039]: Adjusting WDT to 240000ms
[22:43:59.963][V][http_request.watchdog:039]: Adjusting WDT to 5000ms
[22:44:00.067][V][http_request.watchdog:039]: Adjusting WDT to 240000ms
[22:44:00.186][V][http_request.watchdog:039]: Adjusting WDT to 5000ms
[22:44:00.291][V][http_request.watchdog:039]: Adjusting WDT to 240000ms
[22:44:00.403][V][http_request.watchdog:039]: Adjusting WDT to 5000ms
[22:44:00.509][V][http_request.watchdog:039]: Adjusting WDT to 240000ms
[22:44:00.654][V][http_request.watchdog:039]: Adjusting WDT to 5000ms
[22:44:00.759][V][http_request.watchdog:039]: Adjusting WDT to 240000ms
[22:44:00.880][V][http_request.watchdog:039]: Adjusting WDT to 5000ms
[22:44:00.986][V][http_request.watchdog:039]: Adjusting WDT to 240000ms
[22:44:01.148][V][http_request.watchdog:039]: Adjusting WDT to 5000ms
[22:44:01.251][V][http_request.watchdog:039]: Adjusting WDT to 240000ms
[22:44:01.371][V][http_request.watchdog:039]: Adjusting WDT to 5000ms
[22:44:01.474][V][http_request.watchdog:039]: Adjusting WDT to 240000ms
[22:44:01.609][V][http_request.watchdog:039]: Adjusting WDT to 5000ms
[22:44:01.713][V][http_request.watchdog:039]: Adjusting WDT to 240000ms
[22:44:01.823][V][http_request.watchdog:039]: Adjusting WDT to 5000ms
[22:44:01.926][V][http_request.watchdog:039]: Adjusting WDT to 240000ms
[22:44:02.119][V][http_request.watchdog:039]: Adjusting WDT to 5000ms
[22:44:02.224][V][http_request.watchdog:039]: Adjusting WDT to 240000ms
[22:44:02.341][V][http_request.watchdog:039]: Adjusting WDT to 5000ms
[22:44:02.446][V][http_request.watchdog:039]: Adjusting WDT to 240000ms
[22:44:02.568][V][http_request.watchdog:039]: Adjusting WDT to 5000ms
[22:44:02.675][V][http_request.watchdog:039]: Adjusting WDT to 240000ms
[22:44:02.798][V][http_request.watchdog:039]: Adjusting WDT to 5000ms
[22:44:02.904][V][http_request.watchdog:039]: Adjusting WDT to 240000ms
[22:44:03.036][V][http_request.watchdog:039]: Adjusting WDT to 5000ms
[22:44:03.139][V][http_request.watchdog:039]: Adjusting WDT to 240000ms
[22:44:03.338][V][http_request.watchdog:039]: Adjusting WDT to 5000ms
[22:44:03.440][V][http_request.watchdog:039]: Adjusting WDT to 240000ms
[22:44:03.582][V][http_request.watchdog:039]: Adjusting WDT to 5000ms
[22:44:03.689][V][http_request.watchdog:039]: Adjusting WDT to 240000ms
[22:44:03.797][V][http_request.watchdog:039]: Adjusting WDT to 5000ms
[22:44:03.903][V][http_request.watchdog:039]: Adjusting WDT to 240000ms
[22:44:04.042][V][http_request.watchdog:039]: Adjusting WDT to 5000ms
[22:44:04.144][V][http_request.watchdog:039]: Adjusting WDT to 240000ms
[22:44:04.299][V][http_request.watchdog:039]: Adjusting WDT to 5000ms
[22:44:04.405][V][http_request.watchdog:039]: Adjusting WDT to 240000ms
[22:44:04.529][V][http_request.watchdog:039]: Adjusting WDT to 5000ms
[22:44:04.631][V][http_request.watchdog:039]: Adjusting WDT to 240000ms
[22:44:04.789][V][http_request.watchdog:039]: Adjusting WDT to 5000ms
[22:44:04.893][V][http_request.watchdog:039]: Adjusting WDT to 240000ms
[22:44:05.001][V][http_request.watchdog:039]: Adjusting WDT to 5000ms
[22:44:05.106][V][http_request.watchdog:039]: Adjusting WDT to 240000ms
[22:44:05.219][V][http_request.watchdog:039]: Adjusting WDT to 5000ms
[22:44:05.324][V][http_request.watchdog:039]: Adjusting WDT to 240000ms
[22:44:05.436][V][http_request.watchdog:039]: Adjusting WDT to 5000ms
[22:44:05.543][V][http_request.watchdog:039]: Adjusting WDT to 240000ms
[22:44:05.656][V][http_request.watchdog:039]: Adjusting WDT to 5000ms
[22:44:05.761][V][http_request.watchdog:039]: Adjusting WDT to 240000ms
[22:44:05.962][V][http_request.watchdog:039]: Adjusting WDT to 5000ms
[22:44:06.068][V][http_request.watchdog:039]: Adjusting WDT to 240000ms
[22:44:06.100][V][http_request.watchdog:039]: Adjusting WDT to 5000ms
[22:44:06.137][D][online_image:226]: Image fully downloaded, read 2970138 bytes, width/height = 1200/825
[22:44:06.140][D][online_image:228]: Total time: 11s
[22:44:06.146][W][http_request:029]: No header with name etag found
[22:44:06.157][D][http_request:039]: Header with name last-modified found with value Thu, 13 Nov 2025 22:43:02 GMT
[22:44:06.160][V][inkplate:293]: Fill called
[22:44:06.210][V][inkplate:304]: Fill finished (69ms)
[22:44:11.214]E (40628) task_wdt: Task watchdog got triggered. The following tasks/users did not reset the watchdog in time:
[22:44:11.218]E (40628) task_wdt:  - IDLE1 (CPU 1)
[22:44:11.223]E (40628) task_wdt: Tasks currently running:
[22:44:11.225]E (40628) task_wdt: CPU 0: IDLE0
[22:44:11.228]E (40628) task_wdt: CPU 1: loopTask
[22:44:11.231]E (40628) task_wdt: Aborting.
[22:44:11.234]E (40628) task_wdt: Print CPU 1 backtrace




[22:44:11.284]Backtrace: 0x4000bfed:0x3ffc0430 0x4008ca4e:0x3ffc0440 0x400fc269:0x3ffc0460 0x40081362:0x3ffc04a0 0x40081380:0x3ffc04c0 0x400d73cd:0x3ffc04e0 0x400da1f9:0x3ffc0510 0x400de113:0x3ffc0560 0x400de13b:0x3ffc0580 0x40172bad:0x3ffc05a0 0x400d6f29:0x3ffc05c0 0x400e44b1:0x3ffc05f0 0x400d7306:0x3ffc0610 0x400d7359:0x3ffc0630 0x400db5d9:0x3ffc0650 0x400e44e9:0x3ffc0670 0x401738d3:0x3ffc0690 0x40173a21:0x3ffc06b0 0x400dd3ee:0x3ffc06e0 0x400dd7ed:0x3ffc0710 0x40173615:0x3ffc0780 0x400e255d:0x3ffc07a0 0x400e2075:0x3ffc07c0 0x400e45ae:0x3ffc07f0 0x400d740a:0x3ffc0810
WARNING Found stack trace! Trying to decode it
WARNING Decoded 0x4008ca4e: vPortClearInterruptMaskFromISR at /Users/tomk/.platformio/packages/framework-espidf/components/freertos/FreeRTOS-Kernel/portable/xtensa/include/freertos/portmacro.h:560
 (inlined by) vPortExitCritical at /Users/tomk/.platformio/packages/framework-espidf/components/freertos/FreeRTOS-Kernel/portable/xtensa/port.c:514
WARNING Decoded 0x400fc269: esp_task_wdt_reset at /Users/tomk/.platformio/packages/framework-espidf/components/esp_system/task_wdt/task_wdt.c:715
WARNING Decoded 0x40081362: esphome::arch_feed_wdt() at /Users/tomk/work_personal/esp_home/esphome/config/.esphome/build/inkplate-10-1/src/esphome/components/esp32/core.cpp:68
WARNING Decoded 0x40081380: esphome::Application::feed_wdt(unsigned long) at /Users/tomk/work_personal/esp_home/esphome/config/.esphome/build/inkplate-10-1/src/esphome/core/application.cpp:207
WARNING Decoded 0x400d73cd: esphome::display::DisplayBuffer::draw_pixel_at(int, int, esphome::Color) at /Users/tomk/work_personal/esp_home/esphome/config/.esphome/build/inkplate-10-1/src/esphome/components/display/display_buffer.cpp:68
WARNING Decoded 0x400da1f9: esphome::image::Image::draw(int, int, esphome::display::Display*, esphome::Color, esphome::Color) at /Users/tomk/work_personal/esp_home/esphome/config/.esphome/build/inkplate-10-1/src/esphome/components/image/image.cpp:82
WARNING Decoded 0x400de113: esphome::online_image::OnlineImage::draw(int, int, esphome::display::Display*, esphome::Color, esphome::Color) at /Users/tomk/work_personal/esp_home/esphome/config/.esphome/build/inkplate-10-1/src/esphome/components/online_image/online_image.cpp:52
WARNING Decoded 0x400de13b: non-virtual thunk to esphome::online_image::OnlineImage::draw(int, int, esphome::display::Display*, esphome::Color, esphome::Color) at /Users/tomk/work_personal/esp_home/esphome/config/.esphome/build/inkplate-10-1/src/esphome/components/online_image/online_image.h:55
WARNING Decoded 0x40172bad: esphome::display::Display::image(int, int, esphome::display::BaseImage*, esphome::display::ImageAlign, esphome::Color, esphome::Color) at /Users/tomk/work_personal/esp_home/esphome/config/.esphome/build/inkplate-10-1/src/esphome/components/display/display.cpp:528
WARNING Decoded 0x400d6f29: esphome::display::Display::image(int, int, esphome::display::BaseImage*, esphome::Color, esphome::Color) at /Users/tomk/work_personal/esp_home/esphome/config/.esphome/build/inkplate-10-1/src/esphome/components/display/display.cpp:497
WARNING Decoded 0x400e44b1: setup()::{lambda(esphome::display::Display&)#1}::_FUN(esphome::display::Display&) at /Users/tomk/work_personal/esp_home/esphome/config/.esphome/build/inkplate-10-1/config/inkplate-10-1.yaml:91 (discriminator 4)
 (inlined by) _FUN at /Users/tomk/work_personal/esp_home/esphome/config/.esphome/build/inkplate-10-1/config/inkplate-10-1.yaml:92 (discriminator 4)
WARNING Decoded 0x400d7306: esphome::display::DisplayWriter<esphome::display::Display>::call(esphome::display::Display&) const at /Users/tomk/work_personal/esp_home/esphome/config/.esphome/build/inkplate-10-1/src/esphome/components/display/display.h:257
 (inlined by) esphome::display::DisplayWriter<esphome::display::Display>::call(esphome::display::Display&) const at /Users/tomk/work_personal/esp_home/esphome/config/.esphome/build/inkplate-10-1/src/esphome/components/display/display.h:254
WARNING Decoded 0x400d7359: esphome::display::DisplayWriter<esphome::display::Display>::operator()(esphome::display::Display&) const at /Users/tomk/work_personal/esp_home/esphome/config/.esphome/build/inkplate-10-1/src/esphome/components/display/display.h:269
 (inlined by) esphome::display::Display::do_update_() at /Users/tomk/work_personal/esp_home/esphome/config/.esphome/build/inkplate-10-1/src/esphome/components/display/display.cpp:659
WARNING Decoded 0x400db5d9: esphome::inkplate::Inkplate::update() at /Users/tomk/work_personal/esp_home/esphome/config/.esphome/build/inkplate-10-1/src/esphome/components/inkplate/inkplate.cpp:140
WARNING Decoded 0x400e44e9: esphome::UpdateComponentAction<bool>::play(bool const&) at /Users/tomk/work_personal/esp_home/esphome/config/.esphome/build/inkplate-10-1/src/esphome/core/base_automation.h:500
 (inlined by) esphome::UpdateComponentAction<bool>::play(bool const&) at /Users/tomk/work_personal/esp_home/esphome/config/.esphome/build/inkplate-10-1/src/esphome/core/base_automation.h:497
WARNING Decoded 0x401738d3: esphome::Action<bool>::play_complex(bool const&) at /Users/tomk/work_personal/esp_home/esphome/config/.esphome/build/inkplate-10-1/src/esphome/core/automation.h:199
WARNING Decoded 0x40173a21: esphome::ActionList<bool>::play(bool const&) at /Users/tomk/work_personal/esp_home/esphome/config/.esphome/build/inkplate-10-1/src/esphome/core/automation.h:278
 (inlined by) esphome::Automation<bool>::trigger(bool const&) at /Users/tomk/work_personal/esp_home/esphome/config/.esphome/build/inkplate-10-1/src/esphome/core/automation.h:318
 (inlined by) esphome::Trigger<bool>::trigger(bool const&) at /Users/tomk/work_personal/esp_home/esphome/config/.esphome/build/inkplate-10-1/src/esphome/core/automation.h:172
 (inlined by) esphome::online_image::DownloadFinishedTrigger::DownloadFinishedTrigger(esphome::online_image::OnlineImage*)::{lambda(bool)#1}::operator()(bool) const at /Users/tomk/work_personal/esp_home/esphome/config/.esphome/build/inkplate-10-1/src/esphome/components/online_image/online_image.h:233
 (inlined by) void std::__invoke_impl<void, esphome::online_image::DownloadFinishedTrigger::DownloadFinishedTrigger(esphome::online_image::OnlineImage*)::{lambda(bool)#1}&, bool>(std::__invoke_other, esphome::online_image::DownloadFinishedTrigger::DownloadFinishedTrigger(esphome::online_image::OnlineImage*)::{lambda(bool)#1}&, bool&&) at /Users/tomk/.platformio/packages/toolchain-xtensa-esp-elf/xtensa-esp-elf/include/c++/14.2.0/bits/invoke.h:61
 (inlined by) std::enable_if<is_invocable_r_v<void, esphome::online_image::DownloadFinishedTrigger::DownloadFinishedTrigger(esphome::online_image::OnlineImage*)::{lambda(bool)#1}&, bool>, void>::type std::__invoke_r<void, esphome::online_image::DownloadFinishedTrigger::DownloadFinishedTrigger(esphome::online_image::OnlineImage*)::{lambda(bool)#1}&, bool>(esphome::online_image::DownloadFinishedTrigger::DownloadFinishedTrigger(esphome::online_image::OnlineImage*)::{lambda(bool)#1}&, bool&&) at /Users/tomk/.platformio/packages/toolchain-xtensa-esp-elf/xtensa-esp-elf/include/c++/14.2.0/bits/invoke.h:111
 (inlined by) std::_Function_handler<void (bool), esphome::online_image::DownloadFinishedTrigger::DownloadFinishedTrigger(esphome::online_image::OnlineImage*)::{lambda(bool)#1}>::_M_invoke(std::_Any_data const&, bool&&) at /Users/tomk/.platformio/packages/toolchain-xtensa-esp-elf/xtensa-esp-elf/include/c++/14.2.0/bits/std_function.h:290
WARNING Decoded 0x400dd3ee: std::function<void (bool)>::operator()(bool) const at /Users/tomk/.platformio/packages/toolchain-xtensa-esp-elf/xtensa-esp-elf/include/c++/14.2.0/bits/std_function.h:591
 (inlined by) esphome::CallbackManager<void (bool)>::call(bool) at /Users/tomk/work_personal/esp_home/esphome/config/.esphome/build/inkplate-10-1/src/esphome/core/helpers.h:861
WARNING Decoded 0x400dd7ed: esphome::online_image::OnlineImage::loop() at /Users/tomk/work_personal/esp_home/esphome/config/.esphome/build/inkplate-10-1/src/esphome/components/online_image/online_image.cpp:231
WARNING Decoded 0x40173615: esphome::Component::call_loop() at /Users/tomk/work_personal/esp_home/esphome/config/.esphome/build/inkplate-10-1/src/esphome/core/component.cpp:139
WARNING Decoded 0x400e255d: esphome::Component::call() at /Users/tomk/work_personal/esp_home/esphome/config/.esphome/build/inkplate-10-1/src/esphome/core/component.cpp:184
WARNING Decoded 0x400e2075: esphome::Application::loop() at /Users/tomk/work_personal/esp_home/esphome/config/.esphome/build/inkplate-10-1/src/esphome/core/application.cpp:150
WARNING Decoded 0x400e45ae: loop() at /Users/tomk/work_personal/esp_home/esphome/config/.esphome/build/inkplate-10-1/config/inkplate-10-1.yaml:223
WARNING Decoded 0x400d740a: esphome::loop_task(void*) at /Users/tomk/work_personal/esp_home/esphome/config/.esphome/build/inkplate-10-1/src/esphome/components/esp32/core.cpp:94 (discriminator 1)




[22:44:12.498]ELF file SHA256: 464b878e9

[22:44:12.498]Rebooting...
[22:44:12.498]ets Jul 29 2019 12:21:46
```

### Additional information

This problem has been haunting me for quite some time.

### PR DESCRIPTION
**Pull request by jesserockz**
# What does this implement/fix?

## Types of changes

- [ ] Bugfix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] Code quality improvements to existing code or addition of tests
- [ ] Other

**Related issue or feature (if applicable):**

- fixes https://github.com/esphome/esphome/issues/11897

**Pull request in [esphome-docs](https://github.com/esphome/esphome-docs) with documentation (if applicable):**

- esphome/esphome-docs#<esphome-docs PR number goes here>

## Test Environment

- [ ] ESP32
- [ ] ESP32 IDF
- [ ] ESP8266
- [ ] RP2040
- [ ] BK72xx
- [ ] RTL87xx
- [ ] nRF52840

## Example entry for `config.yaml`:

```yaml
# Example config.yaml

```

## Checklist:
  - [ ] The code change is tested and works locally.
  - [ ] Tests have been added to verify that the new code works (under `tests/` folder).

If user exposed functionality or configuration variables are added/changed:
  - [ ] Documentation added/updated in [esphome-docs](https://github.com/esphome/esphome-docs).

### CODE REVIEW

File: esphome/components/online_image/png_image.cpp [hunk 1]
```diff
@@ -38,6 +39,14 @@ static void draw_callback(pngle_t *pngle, uint32_t x, uint32_t y, uint32_t w, ui
   PngDecoder *decoder = (PngDecoder *) pngle_get_user_data(pngle);
   Color color(rgba[0], rgba[1], rgba[2], rgba[3]);
   decoder->draw(x, y, w, h, color);
+
+  // Feed watchdog periodically to avoid triggering during long decode operations.
+  // Feed every 1000 pixels to balance efficiency and responsiveness.
+  uint32_t pixels = w * h;
+  decoder->add_pixels(pixels);
+  if ((decoder->get_pixels_decoded() % 1000) < pixels) {
```
[the remark this answers is not in the document]
Comment (swoboda1337) [reply esphome/components/online_image/png_image.cpp]: Seems legit. Could also use 1024 to so mods and divides are cheaper.

File: esphome/components/online_image/png_image.h [hunk 2]
```diff
@@ -25,9 +25,13 @@ class PngDecoder : public ImageDecoder {
   int prepare(size_t download_size) override;
   int HOT decode(uint8_t *buffer, size_t size) override;
 
+  void add_pixels(uint32_t count) { this->pixels_decoded_ += count; }
```
Comment (guillempages) [inline esphome/components/online_image/png_image.h]: to me `decoded_pixels` sounds more idiomatic than `pixels_decoded`, but you are the native speaker :thinking:  
```suggestion
  void add_pixels(uint32_t count) { this->decoded_pixels_ += count; }
```

File: esphome/components/online_image/png_image.cpp (hunk 1 above)
[the remark this answers is not in the document]
Comment (guillempages) [reply esphome/components/online_image/png_image.cpp]: Hm. I'm not sure that copilot is right in this case... if `pixels_decoded_` is 998 and we decode a single extra pixel, the watchdog will not be fed, but it will feed it in the next iteration, so that shouldn't really be an issue.
It's really a corner case, and adding two ifs instead of a single one just to care for this specific case sounds overkill.. Especially since decoding is in the critical path, so we want to be as fast as possible.
I would ignore the suggerstion from Copilot

Comment (guillempages) [inline esphome/components/online_image/png_image.cpp]: The suggestion from @swoboda1337 to use 1024 instead sound good though!
```suggestion
  if ((decoder->get_pixels_decoded() % 1024) < pixels) {
```

[the remark this answers is not in the document]
Comment (guillempages) [reply esphome/components/online_image/png_image.cpp]: Also, 998 + 1 is still less than 1000, so which boundary does copilot think that we crossed? :thinking:

File: esphome/components/online_image/png_image.h (hunk 2 above)
Comment (guillempages) [reply esphome/components/online_image/png_image.h]: Also, maybe `add_decoded_pixels` as well? To make it clearer? Otherwise, when reading the code in one year, it's not fully clear that "add_pixels" has any relation with decoded pixels; might be understood as "add pixels to the image" or similar (i.e. not just counting, but doing something with the pixels)

**Review by guillempages — COMMENTED** [review]
In general I think this is OK... Might it be an option to put that in the generic decoder code that actually calls the specific format decoders? So that different formats can also benefit from the watchdog, instead of having to take care of it each time by themselves?
OTOH, not sure how feasible this would be, since e.g. JPEG needs to download the full image before starting the decoding :confused:

File: esphome/components/online_image/png_image.cpp (hunk 1 above)
[the remark this answers is not in the document]
Comment (jesserockz) [reply esphome/components/online_image/png_image.cpp]: 1000 was just a "random" number plucked out of the air :rofl: 
I don't mind what it is

File: esphome/components/online_image/png_image.h (hunk 2 above)
Comment (jesserockz) [reply esphome/components/online_image/png_image.h]: `get_pixels_decoded` - sounds like the number of pixels decoded
`get_decoded_pixels` sounds like the getting the actual pixels that have been decoded

File: esphome/components/online_image/png_image.cpp [hunk 3]
```diff
@@ -38,6 +39,14 @@ static void draw_callback(pngle_t *pngle, uint32_t x, uint32_t y, uint32_t w, ui
   PngDecoder *decoder = (PngDecoder *) pngle_get_user_data(pngle);
   Color color(rgba[0], rgba[1], rgba[2], rgba[3]);
   decoder->draw(x, y, w, h, color);
+
+  // Feed watchdog periodically to avoid triggering during long decode operations.
+  // Feed every 1000 pixels to balance efficiency and responsiveness.
```
Comment (jesserockz) [inline esphome/components/online_image/png_image.cpp]:
```suggestion
  // Feed every 1024 pixels to balance efficiency and responsiveness.
```

**Review by swoboda1337 — DISMISSED** [review]

File: esphome/components/online_image/png_image.h (hunk 2 above)
Comment (guillempages) [reply esphome/components/online_image/png_image.h]: ack on the `get_pixels_decoded`... 
Any opinion on the `add_pixels`? Maybe even just add the count without even the `add_pixels` method? Somehow add_pixels throws me off the scent when reading the code :thinking:

**Comment by guillempages** [comment]
@jesserockz You might want to reference #11897 in the description; looks like this would close that issue if I am not mistaken

File: esphome/components/online_image/png_image.h (hunk 2 above)
Comment (jesserockz) [reply esphome/components/online_image/png_image.h]: Yeah, we dont really need a public function for this. will remove

**Review by swoboda1337 — APPROVED** [review]

File: esphome/components/online_image/png_image.h [hunk 4]
```diff
@@ -25,7 +25,7 @@ class PngDecoder : public ImageDecoder {
   int prepare(size_t download_size) override;
   int HOT decode(uint8_t *buffer, size_t size) override;
 
-  void add_pixels(uint32_t count) { this->pixels_decoded_ += count; }
+  void increment_pixels_decoded(uint32_t count) { this->pixels_decoded_ += count; }
```
Comment (guillempages) [inline esphome/components/online_image/png_image.h:28]: Didn't you say you would remove the method?
I have no objection to having it, but you said yourself, that there is no need for a public method for that :thinking:

Comment (jesserockz) [reply esphome/components/online_image/png_image.h:28]: I was going to, then when i opened the code I realised it is needed. It is called from a static callback that doesnt have protected access

**Comment by tomtom13** [comment]
Can you please reopen:
https://github.com/esphome/esphome/issues/11897

As this have not fixed the ONLINE_IMAGE crashing due WDT, this only addresses some png decoder problems that are unrelated and #11897 is unaffected by png decoding problems.
