### PR TITLE
[http_request.ota] Percent-encode credentials in URL

### LINKED ISSUE #14253: ESPHome is crashing when performing OTA w/ special characters in the password
### The problem

ESPHome crashes when attempting an OTA w/ a password containing special characters. I'm not exactly sure which one(s) is/are causing the issue, but removing them all fixes the issue.

The password was correctly quoted in the YAML file, and was displayed correctly in the logs.

### Which version of ESPHome has the issue?

2026.2.1

### What type of installation are you using?

Home Assistant Add-on

### What platform are you using?

ESP32

### Component causing the issue

http_request.ota

### YAML Config

```yaml
esphome:
  name: esp23-car-tracker-beta-3
  friendly_name: esp23-car-tracker-beta-3

esp32:
  board: esp32-s3-devkitc-1
  framework:
    type: esp-idf

logger:
  level: VERBOSE
  initial_level: DEBUG
  logs:
    esp-idf: VERBOSE # To get `HTTP_CLIENT` logs

ota:
  - platform: http_request

button:
  - platform: template
    id: btn_do_ota
    name: Firmware OTA
    on_press: 
      then:
        - script.execute: do_ota

script:
  - id: do_ota
    then:
      - ota.http_request.flash:
          md5_url: https://myrepo.com/file.md5
          url: https://myrepo.com/file.bin
          username: myusername
          password: !secret ota_password
```

### Anything in the logs that might be useful for us?

```txt
[I][http_request.ota:243]: Connecting to: https://myrepo.com/file
[V][esp-idf:000]: E (159249) HTTP_CLIENT: Error parse url https://myusername:^#^*abcde@myrepo.com/file
[V][esp-idf:000]: E (159253) HTTP_CLIENT: Failed to set URL
Guru Meditation Error: Core  1 panic'ed (StoreProhibited). Exception was unhandled.

Core  1 register dump:
PC      : 0x4202d87e  PS      : 0x00060d30  A0      : 0x820049f4  A1      : 0x3fcedae0  
A2      : 0x00000000  A3      : 0x00000000  A4      : 0x00000000  A5      : 0x00000000  
A6      : 0x3fca4d84  A7      : 0x00000044  A8      : 0x8206786c  A9      : 0x3fcedad0  
A10     : 0x00000000  A11     : 0x3c0984a7  A12     : 0x3c098a16  A13     : 0x00013bfe  
A14     : 0x3c0984a7  A15     : 0x3fca6a1c  SAR     : 0x00000019  EXCCAUSE: 0x0000001d  
EXCVADDR: 0x00000044  LBEG    : 0x400570e8  LEND    : 0x400570f3  LCOUNT  : 0x00000000  


Backtrace: 0x4202d87b:0x3fcedae0 0x420049f1:0x3fcedb10 0x4200509e:0x3fcedc00 0x420051ff:0x3fcedc80 0x4200568a:0x3fcedd10 0x42005877:0x3fcedd60 0x42005b94:0x3fcedfb0 0x42016f69:0x3fcedfd0 0x40
```

```txt
    0x4202d87e: esp_http_client_open at /data/cache/platformio/packages/framework-espidf/components/esp_http_client/esp_http_client.c:1779
    0x4202d87b: esp_http_client_open at /data/cache/platformio/packages/framework-espidf/components/esp_http_client/esp_http_client.c:1778
    0x420049f1: esphome::http_request::HttpRequestIDF::perform(std::__cxx11::basic_string, std::allocator > const&, std::__cxx11::basic_string, std::allocator > const&, std::__cxx11::basic_string, std::allocator > const&, std::__cxx11::list > const&, std::set, std::allocator >, std::less, std::allocator > >, std::allocator, std::allocator > > > const&) at /data/build/esp23-car-tracker-beta-3/src/esphome/components/http_request/http_request_idf.cpp:129
    0x4200509e: esphome::http_request::HttpRequestComponent::start(std::__cxx11::basic_string, std::allocator > const&, std::__cxx11::basic_string, std::allocator > const&, std::__cxx11::basic_string, std::allocator > const&, std::__cxx11::list > const&, std::set, std::allocator >, std::less, std::allocator > >, std::allocator, std::allocator > > > const&) at /data/build/esp23-car-tracker-beta-3/src/esphome/components/http_request/ota/../http_request.h:364
    0x420051ff: esphome::http_request::HttpRequestComponent::start(std::__cxx11::basic_string, std::allocator > const&, std::__cxx11::basic_string, std::allocator > const&, std::__cxx11::basic_string, std::allocator > const&, std::__cxx11::list > const&) at /data/build/esp23-car-tracker-beta-3/src/esphome/components/http_request/ota/../http_request.h:354
    0x420051ff: esphome::http_request::HttpRequestComponent::get(std::__cxx11::basic_string, std::allocator > const&) at /data/build/esp23-car-tracker-beta-3/src/esphome/components/http_request/ota/../http_request.h:331
    0x4200568a: esphome::http_request::OtaHttpRequestComponent::http_get_md5_() at /data/build/esp23-car-tracker-beta-3/src/esphome/components/http_request/ota/ota_http_request.cpp:244
    0x4200568a: esphome::http_request::OtaHttpRequestComponent::http_get_md5_() at /data/build/esp23-car-tracker-beta-3/src/esphome/components/http_request/ota/ota_http_request.cpp:232
    0x42005877: esphome::http_request::OtaHttpRequestComponent::do_ota_() at /data/build/esp23-car-tracker-beta-3/src/esphome/components/http_request/ota/ota_http_request.cpp:87
    0x42005b94: esphome::http_request::OtaHttpRequestComponent::flash() at /data/build/esp23-car-tracker-beta-3/src/esphome/components/http_request/ota/ota_http_request.cpp:49
    0x42016f69: esphome::http_request::OtaHttpRequestComponentFlashAction<>::play() at /data/build/esp23-car-tracker-beta-3/src/esphome/components/http_request/ota/automation.h:33
```

### Additional information

_No response_

### PR DESCRIPTION
**Pull request by swoboda1337**
# What does this implement/fix?

Special characters in the OTA username or password (e.g. `^`, `#`, `*`) were being embedded directly into the URL as `username:password@host`, causing ESP-IDF's HTTP client URL parser to fail and crash with a null pointer dereference in `esp_http_client_open()`.

This adds a `url_encode()` helper that percent-encodes the username and password per RFC 3986 before embedding them in the URL.

## Types of changes

- [x] Bugfix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] Developer breaking change (an API change that could break external components)
- [ ] Code quality improvements to existing code or addition of tests
- [ ] Other

**Related issue or feature (if applicable):**

- fixes https://github.com/esphome/esphome/issues/14253

**Pull request in [esphome-docs](https://github.com/esphome/esphome-docs) with documentation (if applicable):**

- N/A

## Test Environment

- [ ] ESP32
- [x] ESP32 IDF
- [ ] ESP8266
- [ ] RP2040
- [ ] BK72xx
- [ ] RTL87xx
- [ ] LN882x
- [ ] nRF52840

## Example entry for `config.yaml`:

```yaml
ota:
  - platform: http_request

button:
  - platform: template
    name: Firmware OTA
    on_press:
      then:
        - ota.http_request.flash:
            md5_url: https://myrepo.com/file.md5
            url: https://myrepo.com/file.bin
            username: myusername
            password: "^#^*abcde"
```

## Checklist:
  - [x] The code change is tested and works locally.
  - [ ] Tests have been added to verify that the new code works (under `tests/` folder).

### CODE REVIEW

File: esphome/components/http_request/ota/ota_http_request.cpp [hunk 1]
```diff
@@ -209,6 +212,23 @@ uint8_t OtaHttpRequestComponent::do_ota_() {
   return ota::OTA_RESPONSE_OK;
 }
 
+// URL-encode characters that are not unreserved per RFC 3986 section 2.3.
+// This is needed for embedding userinfo (username/password) in URLs safely.
+static std::string url_encode(const std::string &str) {
```
Comment (bdraco) [inline esphome/components/http_request/ota/ota_http_request.cpp:216]: Note: this allocates heap.. but its in a cold path

File: esphome/components/http_request/ota/ota_http_request.cpp [hunk 2]
```diff
@@ -209,6 +212,23 @@ uint8_t OtaHttpRequestComponent::do_ota_() {
...
+  std::string result;
+  result.reserve(str.size());
+  for (char c : str) {
+    if (std::isalnum(static_cast<unsigned char>(c)) || c == '-' || c == '_' || c == '.' || c == '~') {
```
Comment (bdraco) [inline esphome/components/http_request/ota/ota_http_request.cpp:220]: RFC 3986: unreserved = ALPHA / DIGIT / "-" / "." / "_" / "~" 👍

File: esphome/components/http_request/ota/ota_http_request.cpp (hunk 1 above)
Comment (bdraco) [reply esphome/components/http_request/ota/ota_http_request.cpp:216]: Its matching with the existing API.  Could be optimized later, but its hard to do unless we have a max url size

**Review by bdraco — DISMISSED** [review]

File: esphome/components/http_request/ota/ota_http_request.cpp (hunk 1 above)
Comment (bdraco) [reply esphome/components/http_request/ota/ota_http_request.cpp:216]: Its is a lot of bloat for a simple fix though

File: esphome/components/http_request/ota/ota_http_request.cpp [hunk 3]
```diff
@@ -209,6 +212,23 @@ uint8_t OtaHttpRequestComponent::do_ota_() {
...
+      result += c;
+    } else {
+      char buf[4];
+      snprintf(buf, sizeof(buf), "%%%02X", static_cast<unsigned char>(c));
+      result += buf;
```
Comment (bdraco) [inline esphome/components/http_request/ota/ota_http_request.cpp]: could replace it with 
```
  result += '%';
  result += format_hex_pretty_char((static_cast<uint8_t>(c) >> 4) & 0x0F);
  result += format_hex_pretty_char(static_cast<uint8_t>(c) & 0x0F);
```
but might be worse with the additional appends but `char` append is cheaper than push_back with strlen like we have now.. would have to check

File: esphome/components/http_request/ota/ota_http_request.cpp (hunk 1 above)
Comment (swoboda1337) [reply esphome/components/http_request/ota/ota_http_request.cpp:216]: Now only called when the username and password are set.

**Comment by bdraco** [comment]
no ram increase now but not much we can do about the flash

**Review by bdraco — APPROVED** [review]

**Comment by swoboda1337** [comment]
Thanks
