### PR TITLE
Fix scheduler with too many cancelled timers

### LINKED ISSUE #1090: ESP8266 intermittently crashes on Scheduler overload
**Operating environment/Installation (Hass.io/Docker/pip/etc.):**

Docker , ESPHome Ver : 1.14.3
**ESP (ESP32/ESP8266, Board/Sonoff):**

Wemos D1 mini
**Affected component:**

[WiFi Component](https://esphome.io/components/wifi.html) (not sure)

**Description of problem:**
My ESP has been crashing for some time. It works for as long as I don't restart it. When it restarts it may or may not boot up well. It keeps on crashing while connecting to WiFi and then enters the safe mode. At times it works fine. I really don't have a way to tell when would it start crashing. 

**Problem-relevant YAML-configuration entries:**
```yaml
# Feature List DONE:
# 1. Turns OFF the motor if the ESP  loses connection to the HA API. An important point to note here is that ESPHome does not
#   know which API client is connected to it. So if a API client to see the log messages is connected to ESPHome
#   it will continue to assume it has a connection. I might want to enhance this in future where I would specifically look
#   for some timestamp or counter form HA to ensure I have a connection to HA or not
# 2. Turns OFF the motor if the motor has been running for more than X min (presently configured as 45)



substitutions:
  relay_gpio: GPIO14
  status_gpio: GPIO15
  st_sp_gpio: GPIO2
  mode_gpio: GPIO12
  sump_gpio: GPIO13
  static_ip: 192.168.1.63
  max_disconnect_time: '15' # max time of disconnection from the api , take action after this
  api_scan_interval: '5' #time in sec to scan for HA api connection

globals:
   - id: api_disconnect_time #time in sec for which ESPHome is disconnected from HA API
     type: int
     restore_value: no
     initial_value: '0'


esphome:
  name: tank_controller
  platform: ESP8266
  board: d1_mini

wifi:
  ssid: !secret secondary_ssid
  password: !secret secondary_ssid_pswd
  manual_ip:
    static_ip: $static_ip
    gateway: !secret default_gateway
    subnet: !secret subnet_mask
  fast_connect: true
#  output_power: 17db
  
# Enable logging
logger:
  level: VERBOSE

api:
  reboot_timeout: 10 min

ota:
  password: !secret ota_pswd

status_led:
  pin: $status_gpio
  
switch:
  - platform: gpio
    name: "Motor Relay"
    id: "motor_relay"
    pin:
      number: $relay_gpio
      mode: OUTPUT
      inverted: False

binary_sensor:
  - platform: gpio
    pin:
      number: $st_sp_gpio
      mode: INPUT_PULLUP
      inverted: False
    name: "Start/Stop"
    id: "start_stop_button"
    filters:
      - delayed_on: 100ms
    on_press:
      then:
        - switch.toggle: motor_relay
        - lambda: |-
            {
              ESP_LOGI("main", "Motor toggled manually"  );
            }

  - platform: gpio
    pin:
      number: $mode_gpio
      mode: INPUT_PULLUP
      inverted: False
    name: "Mode Button"
    id: "mode_button"
    filters:
      - delayed_on_off: 100ms
    on_state:
      then:
        - lambda: |-
            id(tank_full_indicator).publish_state(id(tank_full_indicator).state);

  - platform: gpio
    pin:
      number: $sump_gpio
      mode: INPUT_PULLUP
      inverted: False
    name: "Sump Level"
    id: "sump_level"
    filters:
      - delayed_on_off: 5s
    on_state:
      then:
        - lambda: |-
            if(!id(sump_level).state) //sump level is OFF (aka LOW)
            {
              if(id(mode_button).state && id(motor_relay).state)
              { //auto mode is set and motor is ON
                id(motor_relay).turn_off();
                ESP_LOGI("main", "Sump Level low, Motor turned OFF");
              }
              else //send a message about the sump level being LOW
              {
                ESP_LOGI("main", "Sump Level low, Please fill up");
              }
            }

sensor:
  - platform: homeassistant
    id: tank_level_percent
    entity_id: sensor.water_level
    internal: true
    # The below code triggers the motor to turn ON if the mode is Auto and the water level is below a threshold
    on_value_range:
      above: 0
      below: 50
      then:
        if:
          condition:
            and:
              - binary_sensor.is_on: mode_button #If we are in Auto mode
              - text_sensor.state:
                  id: tank_full_indicator
                  state: 'off' # to be safe check this too as sensor.water_level is not 100% reliable
              - switch.is_off: motor_relay #only turn motor ON if it is OFF
              - api.connected
          then:
            - switch.turn_on: motor_relay
            - lambda: |-
               ESP_LOGI("main", "Motor turned ON at tank level :  %f%", x);

  - platform: template
    name: "Free Memory"
    lambda: 'return {ESP.getFreeHeap()};'
    update_interval: 15s
    icon: mdi:memory

text_sensor:
  - platform: homeassistant
    id: tank_full_indicator
    entity_id: binary_sensor.overhead_tank_full
    internal: true
    on_value:
      then:
        - lambda: |-
            if(id(mode_button).state && id(tank_full_indicator).state == "on")
            {
                id(motor_relay).turn_off();
                ESP_LOGI("main", "Tank full, turned motor OFF");
            }
  - platform: template
    name: "MAC Address"
    lambda: 'return {WiFi.macAddress().c_str()};'
    icon: mdi:fingerprint
  - platform: template
    name: "IP Address"
    lambda: 'return {WiFi.localIP().toString().c_str()};'
    icon: mdi:plus-network
    update_interval: 1d
font:
  - file: "fonts/ComicSansMS3.ttf"
    id: ms_sans_giant
    size: 50
  - file: "fonts/ComicSansMS3.ttf"
    id: ms_sans_large
    size: 30
  - file: "fonts/ComicSansMS3.ttf"
    id: ms_sans
    size: 20
  - file: "fonts/ComicSansMS3.ttf"
    id: ms_sans_small
    size: 15

i2c:
  sda: SDA
  scl: SCL

display:
  - platform: ssd1306_i2c
    model: "SSD1306 128x64"
    id: disp_oled
    address: 0x3C
    pages:
      - id: page_level_percent
        lambda: |-
          if (id(tank_level_percent).has_state()) {
            it.printf(20, it.get_height() / 2, id(ms_sans_giant), "%0.f%%", id(tank_level_percent).state) ;}
          else{
            it.printf(0, 10, id(ms_sans_small), "Initializing");}
      - id: page_full_status
        lambda: |-
           if (id(tank_full_indicator).has_state()) {
             it.printf(0, 15, id(ms_sans_large), "Tank ");
             it.printf(0, 50, id(ms_sans_large), "%s", id(tank_full_indicator).state =="on" ? "Full" : "Partial");}
           else{
             it.printf(0, 10, id(ms_sans_small), "Initializing");}

# As a safety measure we will turn the motor OFF if we lose the connection to home assistant/mqtt server
# TO DO: This is of no use as in case of loss of connection , this code keeps turning OFF and the code which looks at the level of the tank
# keeps turning ON , so you have to detect that there is a loss of conneciton and not fire the auto code for some time - TBD
interval:
  - interval: ${api_scan_interval}s
    then:
      - if:
          condition:
            and:
              - binary_sensor.is_on: mode_button
              - switch.is_on: motor_relay
              - not:
                  api.connected:
          then:
            - lambda: |-
                    id(api_disconnect_time) += ${api_scan_interval}; 
                    if(id(api_disconnect_time) > $max_disconnect_time)
                    {
                      id(motor_relay).turn_off();
                      ESP_LOGI("main", "Connection to HA unavailable, turned motor OFF");
                    }
          else:
            - lambda: |-
                  id(api_disconnect_time) = 0; //reset the counter as we're connected to the api
#      - display.page.show: page_level_percent
  - interval: 3s
    then:
      - display.page.show_next: disp_oled
      - component.update: disp_oled


```

**Logs (if applicable):**

```
18:46:15.539 -> last failed alloc call: 4022B47A(52)
18:46:15.539 -> 
18:46:15.539 ->  ets Jan  8 2013,rst cause:2, boot mode:(3,7)
18:46:15.539 -> 
18:46:15.539 -> load 0x4010f000, len 1384, room 16 
18:46:15.539 -> tail 8
18:46:15.539 -> chksum 0x2d
18:46:15.539 -> csum 0x2d
18:46:15.539 -> v8b899c12
18:46:15.539 -> ~ld
18:46:15.643 -> 
18:46:15.643 -> SDK:2.2.1(cfd48f3)/Core:2.5.2=20502000/lwIP:STABLE-2_1_2_RELEASE/glue:1.1-7-g82abda3/BearSSL:a143020
18:46:15.643 -> [0;32m[I][logger:156]: Log initialized[0m
18:46:15.643 -> [0;35m[C][status_led:014]: Setting up Status LED...[0m
18:46:15.643 -> [0;35m[C][ota:364]: There have been 8 suspected unsuccessful boot attempts.[0m
18:46:15.712 -> [0;32m[I][app:028]: Running through setup()...[0m
18:46:15.712 -> [0;37m[V][app:029]: Sorting components by setup priority...[0m
18:46:15.712 -> [0;35m[C][switch.gpio:011]: Setting up GPIO Switch 'Motor Relay'...[0m
18:46:15.712 -> [0;36m[D][switch:025]: 'Motor Relay' Turning OFF.[0m
18:46:15.712 -> [0;36m[D][switch:045]: 'Motor Relay': Sending state OFF[0m
18:46:15.712 -> [0;36m[D][switch:025]: 'Motor Relay' Turning OFF.[0m
18:46:15.712 -> [0;35m[C][ssd1306_i2c:010]: Setting up I2C SSD1306...[0m
18:46:15.815 -> [0;35m[C][wifi:033]: Setting up WiFi...[0m
18:46:15.815 -> [0;37m[V][wifi_esp8266:043]: Disabling AP.[0m
18:46:15.815 -> bcn 0
18:46:15.815 -> del if1
18:46:15.815 -> usl
18:46:15.815 -> mode : null
18:46:15.815 -> [0;37m[V][wifi_esp8266:033]: Enabling STA.[0m
18:46:15.815 -> mode : sta(2c:f4:32:20:4f:9f)
18:46:15.815 -> add if0
18:46:15.815 -> [0;37m[V][wifi_esp8266:376]: Event: Changed Mode old=AP new=OFF[0m
18:46:15.815 -> wifi evt: 8
18:46:15.815 -> [0;37m[V][wifi_esp8266:376]: Event: Changed Mode old=OFF new=STA[0m
18:46:15.815 -> wifi evt: 8
18:46:15.815 -> sleep disable
18:46:15.815 -> [0;32m[I][wifi:193]: WiFi Connecting to 'EAGLE_GF'...[0m
18:46:15.815 -> [0;37m[V][wifi:195]: Connection Params:[0m
18:46:15.815 -> [0;37m[V][wifi:196]:   SSID: 'EAGLE_GF'[0m
18:46:15.815 -> [0;37m[V][wifi:201]:   BSSID: Not Set[0m
18:46:15.815 -> [0;37m[V][wifi:203]:   Password: [5m'<redacted>'[6m[0m
18:46:15.815 -> [0;37m[V][wifi:207]:   Channel: Not Set[0m
18:46:15.815 -> [0;37m[V][wifi:213]:   Manual IP: Static IP=192.168.1.63 Gateway=192.168.1.1 Subnet=255.255.255.0 DNS1=(IP unset) DNS2=(IP unset)[0m
18:46:15.815 -> [0;37m[V][wifi:217]:   Hidden: NO[0m
18:46:15.815 -> [0;36m[D][text_sensor:015]: 'IP Address': Sending state '192.168.1.63'[0m
18:46:15.815 -> [0;36m[D][text_sensor:015]: 'MAC Address': Sending state '2C:F4:32:20:4F:9F'[0m
18:46:15.815 -> [0;37m[V][sensor:013]: 'Free Memory': Received new state 26376.000000[0m
18:46:15.815 -> [0;36m[D][sensor:092]: 'Free Memory': Sending state 26376.00000  with 1 decimals of accuracy[0m
18:46:16.263 -> [0;36m[D][binary_sensor:034]: 'Start/Stop': Sending initial state ON[0m
18:46:16.263 -> [0;36m[D][binary_sensor:034]: 'Mode Button': Sending initial state ON[0m
18:46:17.912 -> [0;37m[V][wifi_esp8266:344]: Event: Changed AuthMode old=OPEN new=WPA2 PSK[0m
18:46:17.912 -> wifi evt: 2
18:46:22.340 -> 
18:46:22.340 -> Abort called
18:46:22.340 -> 
18:46:22.340 -> >>>stack>>>

I have also tried to decipher the stack trace but cant make sense of it:
0x4020f48b: std::unique_ptr   > esphome::make_unique () at ?? line ?
0x4020f831: esphome::Scheduler::set_timeout(esphome::Component*, std::string const&, unsigned int, std::function &&) at ?? line ?
0x40207650: esphome::i2c::I2CComponent::raw_end_transmission(unsigned char) at ?? line ?
0x4022b47a: operator new(unsigned int) at /workdir/arena/gcc/xtensa-lx106-elf/libstdc++-v3-nox/libsupc++/../../../../../dl/gcc-xtensa/libstdc++-v3/libsupc++/new_op.cc line 52
0x4020e738: esphome::Component::set_timeout(std::string const&, unsigned int, std::function &&) at ?? line ?
0x402063ea: esphome::binary_sensor::DelayedOnOffFilter::new_value(bool, bool) at ?? line ?
0x4020627c: std::_Function_base::_Base_manager ::_M_manager(std::_Any_data&, std::_Function_base::_Base_manager  const&, std::_Manager_operation) at filter.cpp line ?
0x40206538: std::_Function_handler ::_M_invoke(std::_Any_data const&) at filter.cpp line ?
0x4020f64a: void std::__push_heap__gnu_cxx::__normal_iterator    >*, std::vector    >, std::allocator    > > > >, int, std::unique_ptr   >, bool (*)(std::unique_ptr   > const&, std::unique_ptr   > const&)>(__gnu_cxx::__normal_iterator    >*, std::vector    >, std::allocator    > > > >, int, int, std::unique_ptr   >, bool (*)(std::unique_ptr   > const&, std::unique_ptr   > const&)) at ?? line ?
0x402064e3: esphome::binary_sensor::Filter::input(bool, bool) at ?? line ?
0x4020c894: esphome::wifi::WiFiComponent::wifi_sta_status_() at ?? line ?
0x4020603e: esphome::binary_sensor::BinarySensor::publish_state(bool) at ?? line ?
0x40206c1c: esphome::gpio::GPIOBinarySensor::loop() at ?? line ?
0x40206c7c: non-virtual thunk to esphome::gpio::GPIOBinarySensor::loop() at ?? line ?
0x40221c60: esphome::Component::call_loop() at ?? line ?
0x40221d04: esphome::Component::call() at ?? line ?
0x4020e4b0: esphome::Application::setup() at ?? line ?
0x4022078c: free at ?? line ?
0x4022b40a: operator delete(void*) at /workdir/arena/gcc/xtensa-lx106-elf/libstdc++-v3-nox/libsupc++/../../../../../dl/gcc-xtensa/libstdc++-v3/libsupc++/del_op.cc line 48
0x402150bf: setup at ?? line ?
0x4025ba9c: sleep_reset_analog_rtcreg_8266 at ?? line ?
0x4025baa8: sleep_reset_analog_rtcreg_8266 at ?? line ?
0x4025bab3: sleep_reset_analog_rtcreg_8266 at ?? line ?
0x4025bacb: sleep_reset_analog_rtcreg_8266 at ?? line ?
0x4025bada: sleep_reset_analog_rtcreg_8266 at ?? line ?
0x4025bae9: sleep_reset_analog_rtcreg_8266 at ?? line ?
0x4025baf0: sleep_reset_analog_rtcreg_8266 at ?? line ?
0x4025baf4: sleep_reset_analog_rtcreg_8266 at ?? line ?
0x4025baf8: sleep_reset_analog_rtcreg_8266 at ?? line ?
0x4025bafa: sleep_reset_analog_rtcreg_8266 at ?? line ?
0x4025bb10: sleep_reset_analog_rtcreg_8266 at ?? line ?
0x4025bb1b: sleep_reset_analog_rtcreg_8266 at ?? line ?
0x4025bb31: sleep_reset_analog_rtcreg_8266 at ?? line ?
0x4025bb47: sleep_reset_analog_rtcreg_8266 at ?? line ?
0x4025bb5d: sleep_reset_analog_rtcreg_8266 at ?? line ?
0x4025bb75: sleep_reset_analog_rtcreg_8266 at ?? line ?
0x4025bb8b: sleep_reset_analog_rtcreg_8266 at ?? line ?
0x4025bba3: sleep_reset_analog_rtcreg_8266 at ?? line ?
0x4025bbbb: sleep_reset_analog_rtcreg_8266 at ?? line ?
0x4025bbd3: sleep_reset_analog_rtcreg_8266 at ?? line ?
0x4025bbdb: sleep_reset_analog_rtcreg_8266 at ?? line ?
0x4025bbf1: sleep_reset_analog_rtcreg_8266 at ?? line ?
0x4025bc07: sleep_reset_analog_rtcreg_8266 at ?? line ?
0x4025bc1d: sleep_reset_analog_rtcreg_8266 at ?? line ?
0x4025bc33: sleep_reset_analog_rtcreg_8266 at ?? line ?
0x4025bc49: sleep_reset_analog_rtcreg_8266 at ?? line ?
0x4025bc5f: sleep_reset_analog_rtcreg_8266 at ?? line ?
0x4025bc75: sleep_reset_analog_rtcreg_8266 at ?? line ?
0x4025bc8b: sleep_reset_analog_rtcreg_8266 at ?? line ?
0x4025bc96: sleep_reset_analog_rtcreg_8266 at ?? line ?
0x4025bcac: sleep_reset_analog_rtcreg_8266 at ?? line ?
0x4025bcc2: sleep_reset_analog_rtcreg_8266 at ?? line ?
0x4025bccd: sleep_reset_analog_rtcreg_8266 at ?? line ?
0x4025bce3: sleep_reset_analog_rtcreg_8266 at ?? line ?
0x4025bcf9: sleep_reset_analog_rtcreg_8266 at ?? line ?
0x4025bd0f: sleep_reset_analog_rtcreg_8266 at ?? line ?
0x4025bd1a: sleep_reset_analog_rtcreg_8266 at ?? line ?
0x4025bd34: sleep_reset_analog_rtcreg_8266 at ?? line ?
0x4025bd4c: sleep_reset_analog_rtcreg_8266 at ?? line ?
0x4025bd62: sleep_reset_analog_rtcreg_8266 at ?? line ?
0x4025bd7a: sleep_reset_analog_rtcreg_8266 at ?? line ?
0x4025bd92: sleep_reset_analog_rtcreg_8266 at ?? line ?
0x4025bdaa: sleep_reset_analog_rtcreg_8266 at ?? line ?
0x4025bdc0: sleep_reset_analog_rtcreg_8266 at ?? line ?
0x4025bdd6: sleep_reset_analog_rtcreg_8266 at ?? line ?
0x4025bdec: sleep_reset_analog_rtcreg_8266 at ?? line ?
0x4025be02: sleep_reset_analog_rtcreg_8266 at ?? line ?
0x4025be08: sleep_reset_analog_rtcreg_8266 at ?? line ?
0x4025be10: sleep_reset_analog_rtcreg_8266 at ?? line ?
0x4025be28: sleep_reset_analog_rtcreg_8266 at ?? line ?
0x4025be30: sleep_reset_analog_rtcreg_8266 at ?? line ?
0x4025be48: sleep_reset_analog_rtcreg_8266 at ?? line ?
0x4025be50: sleep_reset_analog_rtcreg_8266 at ?? line ?
0x4025be5c: sleep_reset_analog_rtcreg_8266 at ?? line ?
0x4025be68: sleep_reset_analog_rtcreg_8266 at ?? line ?
0x4025be80: sleep_reset_analog_rtcreg_8266 at ?? line ?
0x4025be8b: sleep_reset_analog_rtcreg_8266 at ?? line ?
0x4025be9a: sleep_reset_analog_rtcreg_8266 at ?? line ?
0x4025bea7: sleep_reset_analog_rtcreg_8266 at ?? line ?
0x4025beb3: sleep_reset_analog_rtcreg_8266 at ?? line ?
0x4025bec3: sleep_reset_analog_rtcreg_8266 at ?? line ?
0x4025becb: sleep_reset_analog_rtcreg_8266 at ?? line ?
0x4025bed3: sleep_reset_analog_rtcreg_8266 at ?? line ?
0x4025bedf: sleep_reset_analog_rtcreg_8266 at ?? line ?
0x4025beec: sleep_reset_analog_rtcreg_8266 at ?? line ?
0x4025bef4: sleep_reset_analog_rtcreg_8266 at ?? line ?
0x4025befc: sleep_reset_analog_rtcreg_8266 at ?? line ?
0x4025bf06: sleep_reset_analog_rtcreg_8266 at ?? line ?
0x4025bf0e: sleep_reset_analog_rtcreg_8266 at ?? line ?
0x4025bf17: sleep_reset_analog_rtcreg_8266 at ?? line ?
0x4025bf29: sleep_reset_analog_rtcreg_8266 at ?? line ?
0x4025bf39: sleep_reset_analog_rtcreg_8266 at ?? line ?
0x4025bf51: sleep_reset_analog_rtcreg_8266 at ?? line ?
0x4025bf59: sleep_reset_analog_rtcreg_8266 at ?? line ?
0x40223870: int conststr::parseNthInteger6u>(char const (&) [6u], unsigned int) at ?? line ?
0x40223870: int conststr::parseNthInteger6u>(char const (&) [6u], unsigned int) at ?? line ?
0x40223870: int conststr::parseNthInteger6u>(char const (&) [6u], unsigned int) at ?? line ?
0x40223870: int conststr::parseNthInteger6u>(char const (&) [6u], unsigned int) at ?? line ?
0x40223870: int conststr::parseNthInteger6u>(char const (&) [6u], unsigned int) at ?? line ?
0x40223870: int conststr::parseNthInteger6u>(char const (&) [6u], unsigned int) at ?? line ?
0x40223870: int conststr::parseNthInteger6u>(char const (&) [6u], unsigned int) at ?? line ?
0x40223870: int conststr::parseNthInteger6u>(char const (&) [6u], unsigned int) at ?? line ?
0x4021e5a4: loop_wrapper() at core_esp8266_main.cpp line ?
0x40101399: cont_wrapper at ?? line ?

```

**Additional information and things you've tried:**
I have tried the following but nothing has solved the issue:
1. I tried specifying fast_connect = true
2. I was using both MQTT and API , I removed MQTT altogether , it didnt solve the issue. A point to be noted is that when MQTT was in use it used to fail while connecting to MQTT and not to connecting WiFi. So the point of failure has moved.
3. I have tried changing the Wemos board , it didnt make a difference
4. I have tried specifying the output_power manually, it didnt make a difference.

I am at a point where I am not able to debug it any longer. Given this issue is intermittent, I have to try a fix and then wait for a long time making finding the solution very slow. I have hit a dead end now, somebody please suggest how to proceed.

### PR DESCRIPTION
**Pull request by glmnet**
## Description:

Scheduler is using a min heap to store the pending interval or timeouts timer calls.
Since this structure only has access to the top item (which is due earliest) old items are stored in behind the head item.
If too many old items are stored in the memory which are due later than the top item, memory fills up, the program is not buggy as the items stored are marked for removal, but removal only happens after top item is due, so they are not happening soon enough and in some circumstances the ESP runs out of memory and crashes.

To consistently reproduce this issue I use the following code:

```yaml
esphome:
  name: test_esp8266
  platform: ESP8266
  board: nodemcuv2

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_pass

logger:
  level: DEBUG

api:

binary_sensor:
  - platform: gpio
    id: io14
    pin: GPIO14
    filters:
      - delayed_on_off: 10s

interval:
  interval: 2s
  then:
    - logger.log: "interval timer"
```

Now you have to trigger GPIO14 on, off quickly enough, I connected it to a 1Khz square wave function generator.

Delayed on_off will cancel the `"ON_OFF"` timer every time the GPIO14 ticks, but there is a timer for the interval which will be due before the `interval: 2s` and thus in 2s the memory will be filled and ESP will crash.

This PR adds a counter of how many pending to remove timers are in the heap, and if there are more than 10 it just recreates the heap without the removed items.

**Related issue (if applicable):** fixes https://github.com/esphome/issues/issues/1090

**Pull request in [esphome-docs](https://github.com/esphome/esphome-docs) with documentation (if applicable):** esphome/esphome-docs#<esphome-docs PR number goes here>

## Checklist:
  - [x] The code change is tested and works locally.
  - [ ] Tests have been added to verify that the new code works (under `tests/` folder).

If user exposed functionality or configuration variables are added/changed:
  - [ ] Documentation added/updated in [esphome-docs](https://github.com/esphome/esphome-docs).

### CODE REVIEW

File: esphome/core/scheduler.cpp [hunk 1]
```diff
@@ -107,6 +107,26 @@ void ICACHE_RAM_ATTR HOT Scheduler::call() {
...
+    std::vector<std::unique_ptr<SchedulerItem>> valid_items;
+    while (!this->empty_()) {
+      auto item = std::move(this->items_[0]);
+      this->pop_raw_();
+      valid_items.push_back(std::move(item));
+    }
+    this->items_ = std::move(valid_items);
+
+    // The following should not happen unless I'm missing something
+    if (to_remove_ != 0) {
```
Comment (motwok) [inline esphome/core/scheduler.cpp:123]: how can to_remove be zero here?
Did i miss something in the previours loop that modifies to_remove in any way?

File: esphome/core/scheduler.cpp [hunk 2]
```diff
@@ -107,6 +107,26 @@ void ICACHE_RAM_ATTR HOT Scheduler::call() {
   }
 #endif  // ESPHOME_DEBUG_SCHEDULER
 
+  auto to_remove_was = to_remove_;
+  auto items_was = items_.size();
+  // If we have too many items to remove
+  if (to_remove_ > 10) {
+    std::vector<std::unique_ptr<SchedulerItem>> valid_items;
+    while (!this->empty_()) {
```
Comment (motwok) [inline esphome/core/scheduler.cpp:115]: it looks like that this code is duplicate the code in the previous ESPHOME_DEBUG_SCHEDULER block... even this code is executed in other conditions.
My suggestion remove the code from  ESPHOME_DEBUG_SCHEDULER block

File: esphome/core/scheduler.cpp [hunk 3]
```diff
@@ -107,6 +107,26 @@ void ICACHE_RAM_ATTR HOT Scheduler::call() {
   }
 #endif  // ESPHOME_DEBUG_SCHEDULER
 
+  auto to_remove_was = to_remove_;
```
Comment (motwok) [inline esphome/core/scheduler.cpp:110]: unused variables!

File: esphome/core/scheduler.cpp [hunk 4]
```diff
@@ -107,6 +107,26 @@ void ICACHE_RAM_ATTR HOT Scheduler::call() {
...
+  auto items_was = items_.size();
+  // If we have too many items to remove
+  if (to_remove_ > 10) {
+    std::vector<std::unique_ptr<SchedulerItem>> valid_items;
+    while (!this->empty_()) {
+      auto item = std::move(this->items_[0]);
+      this->pop_raw_();
+      valid_items.push_back(std::move(item));
```
Comment (motwok) [inline esphome/core/scheduler.cpp:118]: If only the list should be recreated, to release memory from vector, this loop should be at the end of this method.
also capacity() - size() should be used as criteria instead of to_remove_.

**Review by motwok — COMMENTED** [review]
There is one big question after the my review:

When the method_cancel_interval runs, is it not to late?

The loop at the end of method_cancel_interval removes the items and does the same job a little different!

File: esphome/core/scheduler.cpp (hunk 1 above)
Comment (glmnet) [reply esphome/core/scheduler.cpp:123]: yes, the while condition calls is_empty which in turns call cleanup which does decrement the `to_remove_` var

File: esphome/core/scheduler.cpp (hunk 2 above)
Comment (glmnet) [reply esphome/core/scheduler.cpp:115]: `ESPHOME_DEBUG_SCHEDULER` is conditionally compiled and used only for debugging, this is not conditional, so unlesss you're debugging this is not duplicated

File: esphome/core/scheduler.cpp (hunk 3 above)
Comment (glmnet) [reply esphome/core/scheduler.cpp:110]: This variable is used in the log warning statement below. It should be removed if the warning is removed though, pretty sure the linter will warn about it

File: esphome/core/scheduler.cpp (hunk 4 above)
Comment (glmnet) [reply esphome/core/scheduler.cpp:118]: `capacity() - size() ` would not get too big before the ESP gets out of memory, most items are logically deleted and they need to be on top of the min heap to be freed from memory. The thing is this is not happening.

May be there are other ways to do this, but I could not find something easier without causing much hassle, and since this code shouldn't normally trigger I think it will be ok.

Comment (motwok) [reply esphome/core/scheduler.cpp:119]: if this code fixes the problem then you found a bug in stdlib, at least in the espressif implementation.

Comment (glmnet) [reply esphome/core/scheduler.cpp:119]: Actually the bug is there. It's just a bit ugly the the method `is_empty()` is actually removing items from the vector/heap

Comment (motwok) [reply esphome/core/scheduler.cpp:119]: A bit irritating... this way it hides your intension... this shold be made a bit more visible, more local, even when this creates a line of duplicate code.
Imagine you read this code in 20 years... it takes you a while to understand.

In my previous Job (review of c# code from 15 coders) a rule was "If the reviewer asks what you really doing in your code, then there is a problem with your structure and code locality"...

Comment (glmnet) [reply esphome/core/scheduler.cpp:119]: Yeah, agree, a bit surprising coming from Otto but gets the job done.
I'm already running this code on several of my nodes so will be merging it soon.
