### PR TITLE
[esp32_touch] Fix setup mode in v1 driver

### LINKED ISSUE #9690: ESP32 Touch Pad Values Sticking
### The problem

The touch values appear to stick on a past value. On boot, it (always?) seems to start at zero and stay there. Touch it with my finger and the values will jump around as expected (and in the range I’ve seen before with a touch). Stop touching and it will simply stay on the last value. Touch it to GND and it will go to zero, but remove it and it will stay at zero indefinitely. Changing boards, pins and framework had no effect. Flashing with YAML compiled on ESPHome 2025.6.3 and behavior is back to expected.

### Which version of ESPHome has the issue?

2025.7.1

### What type of installation are you using?

Home Assistant Add-on

### What platform are you using?

ESP32

### Component causing the issue

esp32_touch

### YAML Config

```yaml
esphome:
  name: test-esp32
  friendly_name: Test ESP32

esp32:
  board: esp32dev
  framework:
    type: arduino
#    type: esp-idf
    
# Enable logging
logger:

# Enable Home Assistant API
api:
  encryption:
    key: "xxxxxxxxxxxxxxxxxxxxxxxxxxxxx"

ota:
  - platform: esphome
    password: "xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx"

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password

  # Enable fallback hotspot (captive portal) in case wifi connection fails
  ap:
    ssid: "Test-Esp32 Fallback Hotspot"
    password: "xxxxxxxxxxxxx"

#captive_portal:

esp32_touch:
  setup_mode: true

binary_sensor:

  - platform: esp32_touch
    name: Touch Pad 1
    icon: mdi:gesture-tap
    pin: GPIO04
    threshold: 1000
```

### Anything in the logs that might be useful for us?

```txt

```

### Additional information

_No response_

### PR DESCRIPTION
**Pull request by swoboda1337**
# What does this implement/fix?

Fix setup mode in v1 driver. Set the threshold to the max and compare the value it in software. Will get an interrupt every period. Without this setup mode never shows any data unless touched. If setup_mode is false set the real threshold to avoid constant interrupts. 

Fix log message, always said the state was ON. 

## Types of changes

- [x] Bugfix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] Code quality improvements to existing code or addition of tests
- [ ] Other

**Related issue or feature (if applicable):**

- fixes https://github.com/esphome/esphome/issues/9690

**Pull request in [esphome-docs](https://github.com/esphome/esphome-docs) with documentation (if applicable):**

- esphome/esphome-docs#<esphome-docs PR number goes here>

## Test Environment

- [ ] ESP32
- [x] ESP32 IDF
- [ ] ESP8266
- [ ] RP2040
- [ ] BK72xx
- [ ] RTL87xx
- [ ] nRF52840

## Example entry for `config.yaml`:

```yaml
# Example config.yaml

```

## Checklist:
  - [x] The code change is tested and works locally.
  - [ ] Tests have been added to verify that the new code works (under `tests/` folder).

If user exposed functionality or configuration variables are added/changed:
  - [ ] Documentation added/updated in [esphome-docs](https://github.com/esphome/esphome-docs).

### CODE REVIEW

**Comment by bdraco** [comment]
Thanks. I can test late tomorrow or monday when I'll have access to a board

File: esphome/components/esp32_touch/esp32_touch_v1.cpp [hunk 1]
```diff
@@ -211,11 +212,16 @@ void IRAM_ATTR ESP32TouchComponent::touch_isr_handler(void *arg) {
     }
 
     // Skip pads that aren’t in the trigger mask
-    bool is_touched = (mask >> pad) & 1;
-    if (!is_touched) {
+    if (((mask >> pad) & 1) == 0) {
       continue;
     }
 
+    // IMPORTANT: ESP32 v1 touch detection logic - INVERTED compared to v2!
```
Comment (bdraco) [inline esphome/components/esp32_touch/esp32_touch_v1.cpp:219]: Makes sense. I was concerned about https://github.com/esphome/esphome/pull/9414/files#diff-88995b3d8d0c2bbc173f0a0d3e0b5799d700ad36002e57a3d6b154994c143bffL215 during review - replacing the value comparison with the mask check seemed problematic, but I second-guessed myself. In hindsight, I should have flagged that the `is_touched = (mask >> pad) & 1` line was fundamentally changing the touch detection logic from comparing actual sensor values to just checking interrupt status. Good catch on the fix!

**Review by bdraco — APPROVED** [review]

**Comment by bdraco** [comment]
This looks good.  I'm sure it will solve the issue. I will still test it to though when I get home to be extra safe.

**Comment by bdraco** [comment]
Thanks @swoboda1337

File: esphome/components/esp32_touch/esp32_touch_v1.cpp (hunk 1 above)
Comment (swoboda1337) [reply esphome/components/esp32_touch/esp32_touch_v1.cpp:219]: Well ``is_touched = (mask >> pad) & 1`` is ok if the interrupt threshold is the same as the threshold in the yaml. Now that the interrupt threshold can be different a check is required.

**Comment by bdraco** [comment]
Tested in setup mode and no setup mode. Everything looks correct
