### PR TITLE
Fix senseair component uart read timeout

### LINKED ISSUE #1965: Unable to read data from Senseair S8
**Operating environment/Installation (Hass.io/Docker/pip/etc.):**

ESPHome installed via pip, Python 3.8.2

**ESP (ESP32/ESP8266, Board/Sonoff):**

Esp8266,  [Lolin D1 Mini](https://www.wemos.cc/en/latest/d1/d1_mini.html)

**ESPHome version (latest production, beta, dev branch)**

ESPHome v1.16.2

**Affected component:**

[Senseair S8](https://esphome.io/components/sensor/senseair.html) (PWM variant, but functionally the same).

**Description of problem:**
I am unable to read anything coming from the sensor, it's exactly as if the sensor was not connected at all. This is a similar symptom with https://github.com/esphome/issues/issues/795 except I don't use any logic converter; power is provided directly by my Esp8266 board.

I have tested both the board and sensor in isolation and they seemed to work individually:
* Board: works fine with a BME280 and can send data to my home assistant instance.
* Sensor: I am able to read data from the S8 with the help a spare Arduino [with this code](https://www.co2meter.com/blogs/news/35432257-arduino-code-for-k-30-co2-sensor-works-for-s8-sensor-too) (buried a bit within the links)
* Board+Sensor:  I managed to get data out of the sensor using Espeasy, both from the dedicated serial pins and from a random set of GPIO 
image . Using the same pins with Esphome yield no result (I also tried with a switched Tx/Rx pin just in case).

My workaround for now would be to use Espeasy, but I'd rather use Esphome instead. Any help appreciated ! Is there any further debugging info I can provide ?

**Problem-relevant YAML-configuration entries:**
```yaml
esphome:
  name: office-multisensor
  platform: ESP8266
  board: d1_mini
wifi:
  ssid: "RocketJump Five G"
  password: "fourwordsalluppercase"

  # Enable fallback hotspot (captive portal) in case wifi connection fails
  ap:
    ssid: "office-multisensor"
    password: "rPCFD0DlPfSy"

logger:
  level: VERY_VERBOSE

api:
  password: "FIVEWORDALLLOWERCASE"
ota:
  password: "FIVEWORDALLLOWERCASE"
uart:
  rx_pin: D6
  tx_pin: D7
  baud_rate: 9600
sensor:
  - platform: senseair
    co2:
      name: "SenseAir CO2 Value"
    update_interval: 2s  

```
**Logs (if applicable):**

```
INFO Successfully uploaded program.
INFO Starting log output from COM5 with baud rate 115200
[00:47:23]{ll\x9c\x9f<\x84l\xe0|♥♦♀♀\x84♀l\xe4♦c|\x8e\x83♥\xecxdbs\x9b#\x8c♦c\x8c\xfbog\x9flgn\x9c\xe3\xe4♦c∟8\x84\x8fl{lsdp\xfbg\xe0↑♥♀♀\x83♀l♦Ĝ♦♦♀#♀g\xe3|♥\xecd\x87♀\x8fc\x8c\xf3og\xef$\x8c\xc7d`☻\x90↕♀l`♥♥n{\x87\x93\x9bo♀♦c☻d`♥s\x9b\x92'♦♀c♥l`♥\x9c#♀♦\x87∟♥\x93$r\x93`♥\xfc\x83g\xdc♥
[00:47:23]SDK:2.2.2-dev(38a443e)/Core:2.7.3-3-g2843a5ac=20703003/lwIP:STABLE-2_1_2_RELEASE/glue:1.2-30-g92add50/BearSSL:5c771be
[00:47:23][I][logger:166]: Log initialized
[00:47:23][VV][preferences:038]: LOAD 32: valid=YES, 0=0x00000000 1=0x0DEFE4E3 (Type=233825507, CRC=0x0DEFE4E3)
[00:47:23][C][ota:366]: There have been 0 suspected unsuccessful boot attempts.
[00:47:23][VV][preferences:051]: SAVE 32: 0=0x00000001 1=0x42F4583F (Type=233825507, CRC=0x42F4583F)
[00:47:23][I][app:029]: Running through setup()...
[00:47:23][V][app:030]: Sorting components by setup priority...
[00:47:23][C][uart_esp8266:046]: Setting up UART bus...
[00:47:23][VV][scheduler:057]: set_interval(name='update', interval=2000, offset=626)
[00:47:23][VV][preferences:038]: LOAD 0: valid=NO, 0=0xFFFFFFFF 1=0xFFFFFFFF (Type=3183385860, CRC=0x8D5ADE27)
[00:47:23][C][wifi:033]: Setting up WiFi...
[00:47:23][V][wifi_esp8266:054]: Disabling AP.
[00:47:23]bcn 0
[00:47:23]del if1
[00:47:23]usl
[00:47:23]mode : null
[00:47:23][V][wifi_esp8266:044]: Enabling STA.
[00:47:23]mod[V][wifi_esp8266:492]: Event: Changed Mode old=AP new=OFF
[00:47:23]wifi evt: 8
[00:47:23]e : sta(e8:db:84:9b:69:b6)
[00:47:23]add if0
[00:47:23][V][wifi_esp8266:492]: Event: Changed Mode old=OFF new=STA
[00:47:23]wifi evt: 8
[00:47:23]sleep disable
[00:47:23][D][wifi:324]: Starting scan...
[00:47:23][VV][scheduler:152]: Running interval 'update' with interval=2000 last_execution=4294964792 (now=178)
[00:47:23][VV][uart_esp8266:182]:     Flushing...
[00:47:23][VV][uart_esp8266:111]:     Wrote 0b11111110 (0xFE)
[00:47:23][VV][uart_esp8266:111]:     Wrote 0b00000100 (0x04)
[00:47:23][VV][uart_esp8266:111]:     Wrote 0b00000000 (0x00)
[00:47:23][VV][uart_esp8266:111]:     Wrote 0b00000000 (0x00)
[00:47:23][VV][uart_esp8266:111]:     Wrote 0b00000000 (0x00)
[00:47:23][VV][uart_esp8266:111]:     Wrote 0b00000100 (0x04)
[00:47:23][VV][uart_esp8266:111]:     Wrote 0b11100101 (0xE5)
[00:47:23][VV][uart_esp8266:111]:     Wrote 0b11000110 (0xC6)
[00:47:23][E][uart_esp8266:167]: Reading from UART timed out at byte 0!
[00:47:23][VV][uart_esp8266:182]:     Flushing...
[00:47:23][W][senseair:015]: Reading data from SenseAir failed!
[00:47:24][VV][scheduler:152]: Running interval 'update' with interval=2000 last_execution=4294966792 (now=1496)
[00:47:24][VV][uart_esp8266:182]:     Flushing...
[00:47:24][VV][uart_esp8266:111]:     Wrote 0b11111110 (0xFE)
[00:47:24][VV][uart_esp8266:111]:     Wrote 0b00000100 (0x04)
[00:47:24][VV][uart_esp8266:111]:     Wrote 0b00000000 (0x00)
[00:47:24][VV][uart_esp8266:111]:     Wrote 0b00000000 (0x00)
[00:47:24][VV][uart_esp8266:111]:     Wrote 0b00000000 (0x00)
[00:47:24][VV][uart_esp8266:111]:     Wrote 0b00000100 (0x04)
[00:47:24][VV][uart_esp8266:111]:     Wrote 0b11100101 (0xE5)
[00:47:24][VV][uart_esp8266:111]:     Wrote 0b11000110 (0xC6)
[00:47:24][E][uart_esp8266:167]: Reading from UART timed out at byte 0!
[00:47:24][VV][uart_esp8266:182]:     Flushing...
[00:47:24][W][senseair:015]: Reading data from SenseAir failed!
[00:47:26][VV][scheduler:152]: Running interval 'update' with interval=2000 last_execution=1496 (now=3496)
[00:47:26][VV][uart_esp8266:182]:     Flushing...
[00:47:26][VV][uart_esp8266:111]:     Wrote 0b11111110 (0xFE)
[00:47:26][VV][uart_esp8266:111]:     Wrote 0b00000100 (0x04)
[00:47:26][VV][uart_esp8266:111]:     Wrote 0b00000000 (0x00)
[00:47:26][VV][uart_esp8266:111]:     Wrote 0b00000000 (0x00)
[00:47:26][VV][uart_esp8266:111]:     Wrote 0b00000000 (0x00)
[00:47:26][VV][uart_esp8266:111]:     Wrote 0b00000100 (0x04)
[00:47:26][VV][uart_esp8266:111]:     Wrote 0b11100101 (0xE5)
[00:47:26][VV][uart_esp8266:111]:     Wrote 0b11000110 (0xC6)
[00:47:26][E][uart_esp8266:167]: Reading from UART timed out at byte 0!
[00:47:26][VV][uart_esp8266:182]:     Flushing...
[00:47:26][W][senseair:015]: Reading data from SenseAir failed!

```
**Additional information and things you've tried:**

See above.

### PR DESCRIPTION
**Pull request by rotarykite**
# What does this implement/fix? 

Quick description and explanation of changes

## Types of changes

- [x] Bugfix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] Other

**Related issue or feature (if applicable):** fixes <https://github.com/esphome/issues/issues/1965>

**Pull request in [esphome-docs](https://github.com/esphome/esphome-docs) with documentation (if applicable):** esphome/esphome-docs#<esphome-docs PR number goes here>

## Test Environment

- [ ] ESP32
- [ ] ESP32 IDF
- [x] ESP8266

## Example entry for `config.yaml`:

```yaml
uart:
  rx_pin: D6
  tx_pin: D5
  baud_rate: 9600
  
sensor:   
  - platform: senseair
    co2:
      name: "SenseAir CO2 Value"
    update_interval: 30s

```

## Checklist:
  - [x] The code change is tested and works locally.
  - [ ] Tests have been added to verify that the new code works (under `tests/` folder).
  
If user exposed functionality or configuration variables are added/changed:
  - [ ] Documentation added/updated in [esphome-docs](https://github.com/esphome/esphome-docs).

### CODE REVIEW

File: esphome/components/senseair/senseair.cpp [hunk 1]
```diff
@@ -141,8 +141,16 @@ void SenseAirComponent::abc_get_period() {
 }
 
 bool SenseAirComponent::senseair_write_command_(const uint8_t *command, uint8_t *response, uint8_t response_length) {
+  int retry = 0;
   this->flush();
-  this->write_array(command, SENSEAIR_REQUEST_LENGTH);
+
+  while (!this->available()) {
```
Comment (OttoWinter) [inline esphome/components/senseair/senseair.cpp]: If there's data available already this would never send the command. Is that expected/correct?

File: esphome/components/senseair/senseair.cpp [hunk 2]
```diff
@@ -141,8 +141,16 @@ void SenseAirComponent::abc_get_period() {
...
+    retry ++;
+    this->write_array(command, SENSEAIR_REQUEST_LENGTH);
```
Comment (OttoWinter) [inline esphome/components/senseair/senseair.cpp]: This may send the command multiple times, and may produce multiple responses if the timing is just right (if the response to the first command happens after 20ms). How is that case handled?

File: esphome/components/senseair/senseair.cpp (hunk 1 above)
Comment (rotarykite) [reply esphome/components/senseair/senseair.cpp]: There will be no data at this point of time as no write command had been send prior to this line

File: esphome/components/senseair/senseair.cpp (hunk 2 above)
Comment (rotarykite) [reply esphome/components/senseair/senseair.cpp]: I tested locally using 20ms running for 24 hour straight, no far no duplicate response happen. Duplicate response do happen if the delay is like 100ms and above.

Let me put in some context of the problem. With the original code, the uart log always report read timeout and no co2 reading can be obtain at all. Soon I found out the code was performing write then straight away read command where the sensor had not reply anything yet. (sensor not ready?)

Updating to write > delay x ms > read sometime able to obtain reading.

The sensor only able to reply to each request nicely by sending write > delay > write  > delay > read. I have no idea why it behave as such, but by referring to a working logic from airgradient.com, a while loop with retry is the product.

File: esphome/components/senseair/senseair.cpp (hunk 1 above)
Comment (DAVe3283) [reply esphome/components/senseair/senseair.cpp]: Couldn't this be refactored to a do/while loop instead? That would solve the problem @OttoWinter mentioned, even if it doesn't seem to come up in real-life testing.

**Comment by DAVe3283** [comment]
Strangely, I am using a SenseAir S8 without issue. Once you have the final code, I can test it on my S8 to make sure mine still works with these changes.

File: esphome/components/senseair/senseair.cpp (hunk 1 above)
Comment (rotarykite) [reply esphome/components/senseair/senseair.cpp]: Do you mean as such? If yes, I shall commit this.
```
do {
  this->write_array(command, SENSEAIR_REQUEST_LENGTH);
  delay(20); // NOLINT
  retry ++;
  if (retry > 10)
    break;
}
while (!this->available());
```

For your info, the SenseAir model I had is this.

**Comment by rotarykite** [comment]
Hi @DAVe3283, thank you very much for helping. I only have one sensor on hand so I can't be sure is it only this particular sensor or this model (S8-4B) having this problem.

Here are the logs and code used for testing. Sensor update frequency is 10s. 
Notice the "Retry log on line 155"
SenseAir code
[COM Serial Log - SenseAir.txt](https://github.com/esphome/esphome/files/7480771/COM.Serial.Log.-.SenseAir.txt)

**Comment by DAVe3283** [comment]
@rotarykite I have the standard SenseAir S8 004-0-0053. Yours appears to be an embedded version primarily designed as a safety switch, and the data sheet doesn't even officially list the serial pins. That could explain why it responds differently.

Looking at their [serial protocol documentation](https://rmtplusstoragesenseair.blob.core.windows.net/docs/Dev/publicerat/TDE2067.pdf), it seems the maximum response time is 180 ms. So even the regular SenseAir S8 could fail to read, theoretically, without a delay.

How about you implement a variable delay [like I did in the MAX31865 sensor](https://github.com/esphome/esphome/blob/d536509a63189490f314e5923471828ca28ba26d/esphome/components/max31865/max31865.cpp#L44), as that should allow both of our sensors to work as quickly as possible.

I ran this code on mine, and it works fine. Plus, it only waits as long as is actually necessary, rather than multiples of 20ms:

```cpp
bool SenseAirComponent::senseair_write_command_(const uint8_t *command, uint8_t *response, uint8_t response_length) {
  // Verify we have somewhere to store the response
  if (response == nullptr) {
    return false;
  }

  this->flush();
  this->write_array(command, SENSEAIR_REQUEST_LENGTH);
  const uint32_t start_time = micros();

  uint32_t read_time;
  do {
    read_time = micros() - start_time;
    if (read_time  >= 180000) {
      ESP_LOGW(TAG, "Response not available after %uμs (datasheet spec is 180000μs max)! Aborting read.", read_time);
      return false;
    }
  } while (!this->available());
  ESP_LOGV(TAG, "Response ready in %uμs.", read_time);

  bool ret = this->read_array(response, response_length);
  this->flush();
  return ret;
}
```

```
[09:16:46][V][s8:161]: Response ready in 15903μs.
[09:16:46][D][s8:058]: SenseAir Received CO₂=872ppm Status=0x00
[09:17:16][V][s8:161]: Response ready in 15936μs.
[09:17:16][D][s8:058]: SenseAir Received CO₂=869ppm Status=0x00
[09:17:46][V][s8:161]: Response ready in 15908μs.
[09:17:46][D][s8:058]: SenseAir Received CO₂=868ppm Status=0x00
```

Ideally we should be using a callback as to not block, but since the real-world appears to be ~20 ms, it is probably fine.

EDIT: I might not fully understand your sensor's exact issue. This code only adds a variable delay up to 180ms (vs the default 100ms delay allowed by [uart_component.cpp](https://esphome.io/api/uart__component_8cpp_source.html)). You were re-sending the command, implying your sensor might not even receive the initial command. In that case, this code won't fix it. Maybe try it out and post back what happens?

And for what it is worth, I hooked mine up to the exact same pins as you (D6, D5) and it worked with the software UART too. Strangely the response was almost 10ms faster than on the hardware serial, but that does tend to rule out a software serial specific issue.

**Comment by DAVe3283** [comment]
Here is a version that retries sending the command up to 5 times, with a 180ms timeout each time (per the datasheet). This can take over a second if it times out every time, which is really not ideal. But as a test, it should tell a lot about what is happening with your particular sensor.

```cpp
bool SenseAirComponent::senseair_write_command_(const uint8_t *command, uint8_t *response, uint8_t response_length) {
  // Verify we have somewhere to store the response
  if (response == nullptr) {
    return false;
  }

  // Retry for flaky sensors
  int retries = -1;
  bool timed_out;
  do {
    this->flush();
    this->write_array(command, SENSEAIR_REQUEST_LENGTH);
    const uint32_t start_time = micros();
    ESP_LOGV(TAG, "Sent command (%d retries).", ++retries);

    timed_out = false;
    uint32_t read_time;
    do {
      read_time = micros() - start_time;
      if (read_time  >= 180000) {
        ESP_LOGW(TAG, "Response not available after %uμs (datasheet spec is 180000μs max)!", read_time);
        timed_out = true;
        break;
      }
    } while (!this->available());
    if (!timed_out) {
      ESP_LOGV(TAG, "Response ready in %uμs.", read_time);
    }
  } while (timed_out && retries < 5);
  if (retries) {
    ESP_LOGW(TAG, "Command needed %d retries!", retries);
  }

  bool ret = this->read_array(response, response_length);
  this->flush();
  return ret;
}
```

**Comment by rotarykite** [comment]
Hi @DAVe3283, thanks for the code. Here is the result.

1st code 
> [11:21:06][W][senseair:157]: Response not available after 180000μs (datasheet spec is 180000μs max)! Aborting read.
[11:21:06][W][senseair:023]: Reading data from SenseAir failed!
[11:21:16][W][senseair:157]: Response not available after 180000μs (datasheet spec is 180000μs max)! Aborting read.
[11:21:16][W][senseair:023]: Reading data from SenseAir failed!
[11:21:26][W][senseair:157]: Response not available after 180000μs (datasheet spec is 180000μs max)! Aborting read.
[11:21:26][W][senseair:023]: Reading data from SenseAir failed!
[11:21:36][W][senseair:157]: Response not available after 180001μs (datasheet spec is 180000μs max)! Aborting read.
[11:21:36][W][senseair:023]: Reading data from SenseAir failed!
[11:21:46][W][senseair:157]: Response not available after 180001μs (datasheet spec is 180000μs max)! Aborting read.
[11:21:46][W][senseair:023]: Reading data from SenseAir failed!

2nd code (Total time taken: ~208ms)
Only the first write request can complete in 1 cycle during startup. No idea why.
> [11:31:23][D][senseair:156]: Sent command (0 retries).
[11:31:23][D][senseair:169]: Response ready in 6936μs.
[11:31:23][D][senseair:058]: SenseAir Received CO₂=395ppm Status=0x00
[11:31:23][D][sensor:113]: 'SenseAir CO2 Value': Sending state 395.00000 ppm with 0 decimals of accuracy

>[11:31:31][D][senseair:156]: Sent command (0 retries).
[11:31:31][W][senseair:163]: Response not available after 180001μs (datasheet spec is 180000μs max)!
[11:31:31][D][senseair:156]: Sent command (1 retries).
[11:31:31][D][senseair:169]: Response ready in 6945μs.
[11:31:31][W][senseair:173]: Command needed 1 retries!
[11:31:31][D][senseair:058]: SenseAir Received CO₂=395ppm Status=0x00
[11:31:31][D][sensor:113]: 'SenseAir CO2 Value': Sending state 395.00000 ppm with 0 decimals of accuracy

>[11:31:40][D][senseair:156]: Sent command (0 retries).
[11:31:40][W][senseair:163]: Response not available after 180001μs (datasheet spec is 180000μs max)!
[11:31:40][D][senseair:156]: Sent command (1 retries).
[11:31:40][D][senseair:169]: Response ready in 5955μs.
[11:31:40][W][senseair:173]: Command needed 1 retries!
[11:31:40][D][senseair:058]: SenseAir Received CO₂=395ppm Status=0x00
[11:31:40][D][sensor:113]: 'SenseAir CO2 Value': Sending state 395.00000 ppm with 0 decimals of accuracy

>[11:31:50][D][senseair:156]: Sent command (0 retries).
[11:31:50][W][senseair:163]: Response not available after 180001μs (datasheet spec is 180000μs max)!
[11:31:50][D][senseair:156]: Sent command (1 retries).
[11:31:50][D][senseair:169]: Response ready in 5976μs.
[11:31:50][W][senseair:173]: Command needed 1 retries!
[11:31:50][D][senseair:058]: SenseAir Received CO₂=405ppm Status=0x00
[11:31:50][D][sensor:113]: 'SenseAir CO2 Value': Sending state 405.00000 ppm with 0 decimals of accuracy

With that, here are more findings as I try to 'force' my way to see which combination work.

Not working or encounter error
- ```
  this->write_array(command, SENSEAIR_REQUEST_LENGTH);
  delay(any amount);

  bool ret = this->read_array(response, response_length);

  // Output
  [14:26:43][E][uart:015]: Reading from UART timed out at byte 0!
  [14:26:43][W][senseair:023]: Reading data from SenseAir failed!
  [14:26:53][E][uart:015]: Reading from UART timed out at byte 0!
  [14:26:53][W][senseair:023]: Reading data from SenseAir failed!
  [14:27:03][E][uart:015]: Reading from UART timed out at byte 0!
  [14:27:03][W][senseair:023]: Reading data from SenseAir failed!
- ```
  this->write_array(command, SENSEAIR_REQUEST_LENGTH);
  this->write_array(command, SENSEAIR_REQUEST_LENGTH);
  // any number of write_array

  bool ret = this->read_array(response, response_length);

  // Output
  [14:29:22][E][uart:015]: Reading from UART timed out at byte 0!
  [14:29:22][W][senseair:023]: Reading data from SenseAir failed!
  [14:29:32][E][uart:015]: Reading from UART timed out at byte 0!
  [14:29:32][W][senseair:023]: Reading data from SenseAir failed!
  [14:29:42][E][uart:015]: Reading from UART timed out at byte 0!
  [14:29:42][W][senseair:023]: Reading data from SenseAir failed!

Working with lowest delay before the read become garbage data. (Total time taken: ~37ms)
- ```  
  this->write_array(command, SENSEAIR_REQUEST_LENGTH);
  delay(20);
  this->write_array(command, SENSEAIR_REQUEST_LENGTH);
  
  bool ret = this->read_array(response, response_length);

  // Output
  [14:33:02][D][senseair:058]: SenseAir Received CO₂=377ppm Status=0x00
  [14:33:02][D][sensor:113]: 'SenseAir CO2 Value': Sending state 377.00000 ppm with 0 decimals of accuracy
  [14:33:12][D][senseair:058]: SenseAir Received CO₂=377ppm Status=0x00
  [14:33:12][D][sensor:113]: 'SenseAir CO2 Value': Sending state 377.00000 ppm with 0 decimals of accuracy
  [14:33:22][D][senseair:058]: SenseAir Received CO₂=351ppm Status=0x00
  [14:33:22][D][sensor:113]: 'SenseAir CO2 Value': Sending state 351.00000 ppm with 0 decimals of accuracy
  
Summary:
It seems this particular sensor behavior is as such. (not sure about the whole S8-4B 004-0-0024 lineup)
- It need at least 2 read command with a short delay between it.
- The sensor does not reply first write command within the modbus 180ms max response time. Even 1000ms does not help.
- The working logic is consistent with your 2nd code where 1 retry is needed in order for this sensor to return properly.


I agree with your approach on the variable delay as one should not cause additional delay for good behavior sensor such as the 0053.

**Comment by DAVe3283** [comment]
@rotarykite Have you tried reading this particular sensor with any other platforms? The issue you linked (started by someone else) said the S8 would work with other platforms but not ESPHome. I don't think that is what is happening here.

The fact that the first command works kind of implies something is getting put on the serial bus, making the S8 think a command has started. Then when this command is sent, it is seen as part of the existing (invalid) command, and is just ignored by the S8.

Do you have access to a scope or logic analyzer at all? Or a USB to serial converter? It would be really interesting to see if there is extra data being sent by the UART that is confusing the S8, or if the command is getting corrupted somehow. You could always try just putting an external pull-up resistor to 3.3V on the TX line (D5) and see if it starts working every time. But really we need to see _exactly_ what is being sent/received by the S8 to determine if the issue is physical/electrical, or something unique to the S8-4B variant.

If you don't have the equipment to really dig in to it, I could trade you a standard S8 for this one, then I could mess with it here where I do have that equipment. If you are interested shoot me an email (my username at gmail).

**Comment by rotarykite** [comment]
@DAVe3283 The issue I linked mentions the S8 was tested with an Arduino with code base from co2meter.com which basically its the same code from airgradient.com. I used their code on a Wemos D1 (clone) with Arduino IDE and was able to get the co2 reading successfully.

I also tried to modify the code using Arduino IDE and the conclusion is the same as ESPHome behavior. (write>delay>write>read). 

I will drop you an email for more discussion on this.

Logic from co2meter.com
```
void loop()
{
 sendRequest(readCO2);
 unsigned long valCO2 = getValue(response);
 Serial.print("Co2 ppm = ");
 Serial.println(valCO2);
 delay(2000);
}
void sendRequest(byte packet[])
{
 while(!K_30_Serial.available()) //keep sending request until we start to
get a response
 {
 K_30_Serial.write(readCO2,7);
 delay(50); 
7
 }
 int timeout=0; //set a timeout counter
 while(K_30_Serial.available() < 7 ) //Wait to get a 7 byte response
 {
 timeout++;
 if(timeout > 10) //if it takes too long there was probably an error
 {
 while(K_30_Serial.available()) //flush whatever we have
 K_30_Serial.read();
 break; //exit and try again
 }
 delay(50);
 } 
 for (int i=0; i < 7; i++)
 {
 response[i] = K_30_Serial.read();
 }
}
```

**Comment by DAVe3283** [comment]
If other projects are having to loop the send, then it is probably a common issue with the SenseAir S8. Yeah, we probably need to loop sending the command as well. Perhaps something like this, which limits the total delay to a more realistic 20ms (like you found works), instead of the 180ms theoretical max:

```cpp
// At top of senseair.cpp
static const uint32_t SENSEAIR_COMMAND_TIMEOUT = 20000;  // in μs; 20 ms real-world, 180 ms datasheet max

bool SenseAirComponent::senseair_write_command_(const uint8_t *command, uint8_t *response, uint8_t response_length) {
  // Verify we have somewhere to store the response
  if (response == nullptr) {
    return false;
  }

  // Retry for flaky sensors
  int retries = -1;
  bool timed_out;
  do {
    this->flush();
    this->write_array(command, SENSEAIR_REQUEST_LENGTH);
    const uint32_t start_time = micros();
    ESP_LOGV(TAG, "Sent command (%d retries).", ++retries);

    timed_out = false;
    do {
      const uint32_t read_time = micros() - start_time;
      if (read_time >= SENSEAIR_COMMAND_TIMEOUT) {
        ESP_LOGW(TAG, "Command timed out! Response not available after %uμs.", read_time);
        timed_out = true;
        break;
      }
    } while (!this->available());
    if (!timed_out) {
      ESP_LOGV(TAG, "Response ready in %uμs.", read_time);
    }
  } while (timed_out && retries < 5);

  bool ret = this->read_array(response, response_length);
  this->flush();
  return ret;
}
```

This seems to work fine on my S8:

```
[00:15:41][V][s8:155]: Sent command (0 retries).
[00:15:41][V][s8:168]: Response ready in 7572μs.
[00:15:41][D][s8:057]: SenseAir Received CO₂=1137ppm Status=0x00
```

File: esphome/components/senseair/senseair.cpp [hunk 3]
```diff
@@ -141,12 +141,17 @@ void SenseAirComponent::abc_get_period() {
...
 
 bool SenseAirComponent::senseair_write_command_(const uint8_t *command, uint8_t *response, uint8_t response_length) {
+  // Verify we have somewhere to store the response
+  if (response == nullptr) {
+    return false;
+  }
+  
   this->flush();
+  // Write wake up byte required by some S8 sensor model
+  this->write_byte(0);
```
Comment (DAVe3283) [inline esphome/components/senseair/senseair.cpp]: In theory, I think the `flush()` should come after the wake-up byte is sent, to ensure it actually gets sent before we `delay()`.

```suggestion
  // Write wake up byte required by some S8 sensor models
  this->write_byte(0);
  this->flush();
```

Otherwise, this looks good to me, and works (either way) on my SenseAir S8.

File: esphome/components/senseair/senseair.cpp [hunk 4]
```diff
@@ -141,12 +141,17 @@ void SenseAirComponent::abc_get_period() {
 }
 
 bool SenseAirComponent::senseair_write_command_(const uint8_t *command, uint8_t *response, uint8_t response_length) {
+  // Verify we have somewhere to store the response
+  if (response == nullptr) {
+    return false;
+  }
+
```
Comment (DAVe3283) [inline esphome/components/senseair/senseair.cpp]: Here, the linter wants trailing whitespace removed:

```suggestion

```

File: esphome/components/senseair/senseair.cpp [hunk 5]
```diff
@@ -141,12 +141,17 @@ void SenseAirComponent::abc_get_period() {
...
 bool SenseAirComponent::senseair_write_command_(const uint8_t *command, uint8_t *response, uint8_t response_length) {
+  // Verify we have somewhere to store the response
+  if (response == nullptr) {
+    return false;
+  }
+  
+  // Write wake up byte required by some S8 sensor models
+  this->write_byte(0);
   this->flush();
+  delay(5); // NOLINT
```
Comment (DAVe3283) [inline esphome/components/senseair/senseair.cpp]: Here, the linter wants an extra space before the comment:

```suggestion
  delay(5);  // NOLINT
```

**Review by DAVe3283 — COMMENTED** [review]
I think you need to fix the [2 linter errors](https://github.com/esphome/esphome/runs/4160550735?check_suite_focus=true) before this can be merged.

**Comment by rotarykite** [comment]
Thanks @DAVe3283. I was wondering what's with the error that did not show which line was causing the problem.

**Review by DAVe3283 — APPROVED** [review]
This looks good to me, and works fine on my "normal" SenseAir S8 sensor.

File: esphome/components/senseair/senseair.cpp [hunk 6]
```diff
@@ -141,12 +141,16 @@ void SenseAirComponent::abc_get_period() {
...
 
 bool SenseAirComponent::senseair_write_command_(const uint8_t *command, uint8_t *response, uint8_t response_length) {
+  // Verify we have somewhere to store the response
+  if (response == nullptr) {
+    return false;
+  }
+  // Write wake up byte required by some S8 sensor models
+  this->write_byte(0);
   this->flush();
+  delay(5);  // NOLINT
```
Comment (jesserockz) [inline esphome/components/senseair/senseair.cpp]: This delay should not need `// NOLINT`
```suggestion
  delay(5);
```

**Review by jesserockz — APPROVED** [review]
