### PR TITLE
Reserve less memory for json

### LINKED ISSUE #3112: empty {} topic config json in mqtt discovery
### The problem

send empty {} json in config topic, all work fine in 2022.2.5
this bug is replay all board esp32

### Which version of ESPHome has the issue?

2022.2.6

### What type of installation are you using?

Docker

### Which version of Home Assistant has the issue?

_No response_

### What platform are you using?

ESP32

### Board

_No response_

### Component causing the issue

_No response_

### Example YAML snippet

```yaml
substitutions:
  device_name: livingroom-ac

esphome:
  name: ${device_name}
  platform: ESP32
  board: esp32dev

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password
  fast_connect: true

  # Enable fallback hotspot (captive portal) in case wifi connection fails
  ap:
    ssid: "Living Room Ac Hotspot"
    password: !secret ap_password

captive_portal:

# Enable logging
logger:
  level: WARN
  # level: DEBUG
  baud_rate: 0

# Enable Home Assistant API
# api:

ota:
  password: !secret ota_password

web_server:

esp32_ble_tracker:
#  scan_parameters:
#    window: 120ms

mqtt:
  broker: !secret mqtt_host
  topic_prefix: esphome/${device_name}

text_sensor:
  - platform: version
    name: "Version"
  
  - platform: wifi_info
    ip_address:
      name: "Address"

  - platform: template
    id: uptime_human
    name: "Uptime"
```

### Anything in the logs that might be useful for us?

_No response_

### Additional information

_No response_

### PR DESCRIPTION
**Pull request by jesserockz**
# What does this implement/fix?

It seems that even though the response from `heap_caps_get_largest_free_block` can be around 30kb (in my local testing), `malloc` fails to allocate giving a nullptr buffer which means json can not be built or parsed.

If 10kb is not enough of a maximum, then we might be able to increase it via config variable?

## Types of changes

- [x] Bugfix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] Other

**Related issue or feature (if applicable):** fixes https://github.com/esphome/issues/issues/3112

**Pull request in [esphome-docs](https://github.com/esphome/esphome-docs) with documentation (if applicable):** esphome/esphome-docs#<esphome-docs PR number goes here>

## Test Environment

- [ ] ESP32
- [ ] ESP32 IDF
- [ ] ESP8266

## Example entry for `config.yaml`:

```yaml
# Example config.yaml

```

## Checklist:
  - [ ] The code change is tested and works locally.
  - [ ] Tests have been added to verify that the new code works (under `tests/` folder).

If user exposed functionality or configuration variables are added/changed:
  - [ ] Documentation added/updated in [esphome-docs](https://github.com/esphome/esphome-docs).

### CODE REVIEW

File: esphome/components/json/json_util.cpp [hunk 1]
```diff
@@ -36,16 +44,24 @@ std::string build_json(const json_build_t &f) {
...
 #elif defined(USE_ESP32)
-  const size_t free_heap = heap_caps_get_largest_free_block(MALLOC_CAP_INTERNAL) - 2048;
+  const size_t free_heap = heap_caps_get_largest_free_block(MALLOC_CAP_INTERNAL);
 #endif
 
-  DynamicJsonDocument json_document(free_heap);
+  const size_t request_size = std::min(free_heap - 2048, (size_t) 10240);
+
+  DynamicJsonDocument json_document(request_size);
+  if (json_document.memoryPool().buffer() == nullptr) {
```
Comment (OttoWinter) [inline esphome/components/json/json_util.cpp]: Hmm, now it's limited to 10kb of json data (which is probably ok), but maybe we can change it to start with something like 2k, and if that fails in the deserialization, up the limit to 8kb, then 32kb, etc.

Then we both allow large json payloads, but also might be easier on the malloc implementation. 
1. especially the realloc in `shrinkToFit` below could maybe result in some fragmentation depending on the malloc implementation, especially if the implementation reserves some sections for certain block sizes etc
2. The realloc could _theoretically_ need to alloc a new array and copy it over, in which case we only can use 1/2 the available space
3. On ESP32, if another task is running it can alloc too while we're parsing. So we shouldn't just use the max available and hope for the best.

We could even start the initial size with a reasonable guess, like `1.5 * data.size()` (good value should be checked)

Comment (jesserockz) [reply esphome/components/json/json_util.cpp]: The main issue this PR is trying to solve is actually the building of JSON rather than the parsing.

I did think about the 1.5 * size at the start but not sure why I didn't do it. I will use that plus an increasing amount until it hits free heap limit.

**Comment by Metus88** [comment]
Thanks! This pull request fix my problem!
