### PR TITLE
Fix bulk and single Bluetooth parser coexistence

### LINKED ISSUE #4641: Xiaomi LYWSDCGQ and CGDK2 no longer report Temerature and Humidty.
### The problem

I have 5 ESP32's and about 8 to 10 temperature sensors.  All of them being either LYWSDCGQ or CGDK2.

The last update broke them all.  They will only (might) report once after the ESP32 is restarted.  They never report a second time.

### Which version of ESPHome has the issue?

2023.6.3

### What type of installation are you using?

Home Assistant Add-on

### Which version of Home Assistant has the issue?

2023.7.0b2

### What platform are you using?

ESP32

### Board

mhetesp32devkit

### Component causing the issue

xiaomi_lywsdcgq, xiaomi_cgdk2

### Example YAML snippet

```yaml
e.g. CGDK2


sensor:
  - platform: xiaomi_cgdk2
    mac_address: "58:2D:34:12:BC:7C"
    bindkey: "f6d5a0db976d1c758a23b24807e0ff2b"
    temperature:
      name: Server Room Temperature
    humidity:
      name: Server Room Humidity
    battery_level:
      name: Server Room Battery Level
```

e.g.LYWSDCGQ 

```
sensor:
  - platform: xiaomi_lywsdcgq
    mac_address: !secret mijia_ble_temperature_3
    temperature:
      name: "Master Bathroom Temperature"
      device_class: "temperature"
      state_class: "measurement"
    humidity:
      name: "Master Bathroom Humidity"
      device_class: "humidity"
      state_class: "measurement"
    battery_level:
      name: "Master Bathroom Temperature Sensor Battery Level"
```
```


### Anything in the logs that might be useful for us?

```txt
here's the logs from one showing the issue, you'll see a single update from one of the 2 configured sensors, and nothing ever again.

INFO ESPHome 2023.6.3
INFO Reading configuration /config/esphome/master_closet_esp32.yaml...
WARNING 'master_closet_esp32': Using the '_' (underscore) character in the hostname is discouraged as it can cause problems with some DHCP and local name services. For more information, see https://esphome.io/guides/faq.html#why-shouldn-t-i-use-underscores-in-my-device-name
INFO Starting log output from master_closet_esp32.local using esphome API
INFO Successfully connected to master_closet_esp32.local
[06:11:47][I][app:102]: ESPHome version 2023.6.3 compiled on Jun 29 2023, 10:08:45
[06:11:47][C][wifi:543]: WiFi:
[06:11:47][C][wifi:379]:   Local MAC: 84:CC:A8:5D:13:60
[06:11:47][C][wifi:380]:   SSID: [redacted]
[06:11:47][C][wifi:381]:   IP Address: 192.168.20.14
[06:11:47][C][wifi:383]:   BSSID: [redacted]
[06:11:47][C][wifi:384]:   Hostname: 'master_closet_esp32'
[06:11:47][C][wifi:386]:   Signal strength: -69 dB ▂▄▆█
[06:11:47][C][wifi:390]:   Channel: 11
[06:11:47][C][wifi:391]:   Subnet: 255.255.255.0
[06:11:47][C][wifi:392]:   Gateway: 192.168.20.1
[06:11:47][C][wifi:393]:   DNS1: 192.168.20.1
[06:11:47][C][wifi:394]:   DNS2: 0.0.0.0
[06:11:47][C][logger:301]: Logger:
[06:11:47][C][logger:302]:   Level: DEBUG
[06:11:47][C][logger:303]:   Log Baud Rate: 115200
[06:11:47][C][logger:305]:   Hardware UART: UART0
[06:11:47][C][template.sensor:022]: Template Sensor 'Master Bathroom Temperature Sensor Number'
[06:11:47][C][template.sensor:022]:   State Class: ''
[06:11:47][C][template.sensor:022]:   Unit of Measurement: ''
[06:11:47][C][template.sensor:022]:   Accuracy Decimals: 1
[06:11:47][C][template.sensor:023]:   Update Interval: 86400.0s
[06:11:47][C][template.sensor:022]: Template Sensor 'Master Bedroom Temperature Sensor Number'
[06:11:47][C][template.sensor:022]:   State Class: ''
[06:11:47][C][template.sensor:022]:   Unit of Measurement: ''
[06:11:47][C][template.sensor:022]:   Accuracy Decimals: 1
[06:11:47][C][template.sensor:023]:   Update Interval: 86400.0s
[06:11:47][C][uptime.sensor:031]: Uptime Sensor 'Master Bedroom ESP32 Ethernet Uptime'
[06:11:47][C][uptime.sensor:031]:   Device Class: 'duration'
[06:11:47][C][uptime.sensor:031]:   State Class: 'total_increasing'
[06:11:47][C][uptime.sensor:031]:   Unit of Measurement: 's'
[06:11:47][C][uptime.sensor:031]:   Accuracy Decimals: 0
[06:11:47][C][uptime.sensor:031]:   Icon: 'mdi:timer-outline'
[06:11:47][C][template.sensor:022]: Template Sensor 'Master Bedroom ESP32 Free Memory'
[06:11:47][C][template.sensor:022]:   State Class: 'measurement'
[06:11:47][C][template.sensor:022]:   Unit of Measurement: 'B'
[06:11:47][C][template.sensor:022]:   Accuracy Decimals: 1
[06:11:47][C][template.sensor:023]:   Update Interval: 60.0s
[06:11:47][C][bluetooth_proxy:088]: Bluetooth Proxy:
[06:11:47][C][bluetooth_proxy:089]:   Active: YES
[06:11:47][C][restart:068]: Restart Switch 'Master Bedroom ESP32 Restart'
[06:11:47][C][restart:070]:   Icon: 'mdi:restart'
[06:11:47][C][restart:091]:   Restore Mode: always OFF
[06:11:47][C][xiaomi_lywsdcgq:012]: Xiaomi LYWSDCGQ
[06:11:47][C][xiaomi_lywsdcgq:013]:   Temperature 'Master Bathroom Temperature'
[06:11:47][C][xiaomi_lywsdcgq:013]:     Device Class: 'temperature'
[06:11:47][C][xiaomi_lywsdcgq:013]:     State Class: 'measurement'
[06:11:47][C][xiaomi_lywsdcgq:013]:     Unit of Measurement: '°C'
[06:11:47][C][xiaomi_lywsdcgq:013]:     Accuracy Decimals: 1
[06:11:47][C][xiaomi_lywsdcgq:014]:   Humidity 'Master Bathroom Humidity'
[06:11:47][C][xiaomi_lywsdcgq:014]:     Device Class: 'humidity'
[06:11:47][C][xiaomi_lywsdcgq:014]:     State Class: 'measurement'
[06:11:47][C][xiaomi_lywsdcgq:014]:     Unit of Measurement: '%'
[06:11:47][C][xiaomi_lywsdcgq:014]:     Accuracy Decimals: 1
[06:11:47][C][xiaomi_lywsdcgq:015]:   Battery Level 'Master Bathroom Temperature Sensor Battery Level'
[06:11:47][C][xiaomi_lywsdcgq:015]:     Device Class: 'battery'
[06:11:47][C][xiaomi_lywsdcgq:015]:     State Class: 'measurement'
[06:11:47][C][xiaomi_lywsdcgq:015]:     Unit of Measurement: '%'
[06:11:47][C][xiaomi_lywsdcgq:015]:     Accuracy Decimals: 0
[06:11:47][C][xiaomi_lywsdcgq:012]: Xiaomi LYWSDCGQ
[06:11:47][C][xiaomi_lywsdcgq:013]:   Temperature 'Master Bedroom Temperature'
[06:11:47][C][xiaomi_lywsdcgq:013]:     Device Class: 'temperature'
[06:11:47][C][xiaomi_lywsdcgq:013]:     State Class: 'measurement'
[06:11:47][C][xiaomi_lywsdcgq:013]:     Unit of Measurement: '°C'
[06:11:47][C][xiaomi_lywsdcgq:013]:     Accuracy Decimals: 1
[06:11:47][C][xiaomi_lywsdcgq:014]:   Humidity 'Master Bedroom Humidity'
[06:11:47][C][xiaomi_lywsdcgq:014]:     Device Class: 'humidity'
[06:11:47][C][xiaomi_lywsdcgq:014]:     State Class: 'measurement'
[06:11:47][C][xiaomi_lywsdcgq:014]:     Unit of Measurement: '%'
[06:11:47][C][xiaomi_lywsdcgq:014]:     Accuracy Decimals: 1
[06:11:47][C][xiaomi_lywsdcgq:015]:   Battery Level 'Master Bedroom Temperature Sensor Battery Level'
[06:11:47][C][xiaomi_lywsdcgq:015]:     Device Class: 'battery'
[06:11:47][C][xiaomi_lywsdcgq:015]:     State Class: 'measurement'
[06:11:47][C][xiaomi_lywsdcgq:015]:     Unit of Measurement: '%'
[06:11:47][C][xiaomi_lywsdcgq:015]:     Accuracy Decimals: 0
[06:11:47][C][esp32_ble:238]: ESP32 BLE:
[06:11:47][C][esp32_ble:240]:   MAC address: 84:CC:A8:5D:13:62
[06:11:47][C][esp32_ble:241]:   IO Capability: none
[06:11:47][C][esp32_ble_tracker:590]: BLE Tracker:
[06:11:47][C][esp32_ble_tracker:591]:   Scan Duration: 300 s
[06:11:47][C][esp32_ble_tracker:592]:   Scan Interval: 320.0 ms
[06:11:47][C][esp32_ble_tracker:593]:   Scan Window: 30.0 ms
[06:11:47][C][esp32_ble_tracker:594]:   Scan Type: ACTIVE
[06:11:47][C][esp32_ble_tracker:595]:   Continuous Scanning: True
[06:11:47][C][mdns:108]: mDNS:
[06:11:47][C][mdns:109]:   Hostname: master_closet_esp32
[06:11:47][C][ota:093]: Over-The-Air Updates:
[06:11:47][C][ota:094]:   Address: master_closet_esp32.local:3232
[06:11:47][C][api:138]: API Server:
[06:11:47][C][api:139]:   Address: master_closet_esp32.local:6053
[06:11:47][C][api:143]:   Using noise encryption: NO
[06:12:07][D][sensor:094]: 'Master Bedroom ESP32 Free Memory': Sending state 75108.00000 B with 1 decimals of accuracy
[06:12:08][D][sensor:094]: 'Master Bedroom ESP32 Ethernet Uptime': Sending state 72172.25000 s with 0 decimals of accuracy
[06:12:38][D][switch:012]: 'Master Bedroom ESP32 Restart' Turning ON.
[06:12:38][D][switch:055]: 'Master Bedroom ESP32 Restart': Sending state OFF
[06:12:38][I][restart:016]: Restarting device...
[06:12:38][I][app:134]: Rebooting safely...
INFO Processing expected disconnect from ESPHome API for master_closet_esp32.local
WARNING Disconnected from API
INFO Successfully connected to master_closet_esp32.local
[06:12:46][C][esp32_ble_tracker:590]: BLE Tracker:
[06:12:46][C][esp32_ble_tracker:591]:   Scan Duration: 300 s
[06:12:46][C][esp32_ble_tracker:592]:   Scan Interval: 320.0 ms
[06:12:46][C][esp32_ble_tracker:593]:   Scan Window: 30.0 ms
[06:12:46][C][esp32_ble_tracker:594]:   Scan Type: ACTIVE
[06:12:46][C][esp32_ble_tracker:595]:   Continuous Scanning: True
[06:12:46][C][mdns:108]: mDNS:
[06:12:46][C][mdns:109]:   Hostname: master_closet_esp32
[06:12:46][C][ota:093]: Over-The-Air Updates:
[06:12:46][C][ota:094]:   Address: master_closet_esp32.local:3232
[06:12:46][C][api:138]: API Server:
[06:12:46][C][api:139]:   Address: master_closet_esp32.local:6053
[06:12:46][C][api:143]:   Using noise encryption: NO
[06:12:47][D][xiaomi_ble:328]: Got Xiaomi LYWSDCGQ (58:2D:34:3A:C4:B9):
[06:12:47][D][xiaomi_ble:331]:   Temperature: 23.0°C
[06:12:47][D][xiaomi_ble:334]:   Humidity: 80.0%
[06:12:47][D][sensor:094]: 'Master Bathroom Temperature': Sending state 23.00000 °C with 1 decimals of accuracy
[06:12:47][D][sensor:094]: 'Master Bathroom Humidity': Sending state 80.00000 % with 1 decimals of accuracy
[06:12:49][D][api:102]: Accepted 192.168.1.134
[06:12:49][D][api.connection:1030]: Home Assistant 2023.7.0b2 (192.168.1.134): Connected successfully
[06:13:15][D][sensor:094]: 'Master Bedroom ESP32 Free Memory': Sending state 75484.00000 B with 1 decimals of accuracy
[06:13:36][D][sensor:094]: 'Master Bedroom ESP32 Ethernet Uptime': Sending state 55.94300 s with 0 decimals of accuracy
[06:14:15][D][sensor:094]: 'Master Bedroom ESP32 Free Memory': Sending state 75340.00000 B with 1 decimals of accuracy
[06:14:36][D][sensor:094]: 'Master Bedroom ESP32 Ethernet Uptime': Sending state 115.94000 s with 0 decimals of accuracy
[06:15:15][D][sensor:094]: 'Master Bedroom ESP32 Free Memory': Sending state 75500.00000 B with 1 decimals of accuracy
[06:15:36][D][sensor:094]: 'Master Bedroom ESP32 Ethernet Uptime': Sending state 175.94701 s with 0 decimals of accuracy
[06:16:15][D][sensor:094]: 'Master Bedroom ESP32 Free Memory': Sending state 75500.00000 B with 1 decimals of accuracy
[06:16:36][D][sensor:094]: 'Master Bedroom ESP32 Ethernet Uptime': Sending state 235.94701 s with 0 decimals of accuracy
[06:17:15][D][sensor:094]: 'Master Bedroom ESP32 Free Memory': Sending state 75368.00000 B with 1 decimals of accuracy
[06:17:36][D][sensor:094]: 'Master Bedroom ESP32 Ethernet Uptime': Sending state 295.94601 s with 0 decimals of accuracy
[06:17:40][I][ota:113]: Boot seems successful, resetting boot loop counter.
[06:17:40][D][esp32.preferences:114]: Saving 1 preferences to flash...
[06:17:40][D][esp32.preferences:143]: Saving 1 preferences to flash: 0 cached, 1 written, 0 failed
[06:17:40][D][esp32_ble_tracker:245]: Starting scan...
[06:18:15][D][sensor:094]: 'Master Bedroom ESP32 Free Memory': Sending state 75424.00000 B with 1 decimals of accuracy
[06:18:36][D][sensor:094]: 'Master Bedroom ESP32 Ethernet Uptime': Sending state 355.94000 s with 0 decimals of accuracy
[06:19:15][D][sensor:094]: 'Master Bedroom ESP32 Free Memory': Sending state 75424.00000 B with 1 decimals of accuracy
[06:19:36][D][sensor:094]: 'Master Bedroom ESP32 Ethernet Uptime': Sending state 415.94000 s with 0 decimals of accuracy
[06:20:15][D][sensor:094]: 'Master Bedroom ESP32 Free Memory': Sending state 75424.00000 B with 1 decimals of accuracy
[06:20:36][D][sensor:094]: 'Master Bedroom ESP32 Ethernet Uptime': Sending state 475.94000 s with 0 decimals of accuracy
[06:21:15][D][sensor:094]: 'Master Bedroom ESP32 Free Memory': Sending state 75424.00000 B with 1 decimals of accuracy
[06:21:36][D][sensor:094]: 'Master Bedroom ESP32 Ethernet Uptime': Sending state 535.94000 s with 0 decimals of accuracy
[06:22:15][D][sensor:094]: 'Master Bedroom ESP32 Free Memory': Sending state 75424.00000 B with 1 decimals of accuracy
[06:22:36][D][sensor:094]: 'Master Bedroom ESP32 Ethernet Uptime': Sending state 595.94299 s with 0 decimals of accuracy
[06:22:40][D][esp32_ble_tracker:245]: Starting scan...
[06:23:15][D][sensor:094]: 'Master Bedroom ESP32 Free Memory': Sending state 75424.00000 B with 1 decimals of accuracy
[06:23:36][D][sensor:094]: 'Master Bedroom ESP32 Ethernet Uptime': Sending state 655.94000 s with 0 decimals of accuracy
[06:24:15][D][sensor:094]: 'Master Bedroom ESP32 Free Memory': Sending state 75424.00000 B with 1 decimals of accuracy
[06:24:36][D][sensor:094]: 'Master Bedroom ESP32 Ethernet Uptime': Sending state 715.94397 s with 0 decimals of accuracy
[06:25:15][D][sensor:094]: 'Master Bedroom ESP32 Free Memory': Sending state 75424.00000 B with 1 decimals of accuracy
[06:25:36][D][sensor:094]: 'Master Bedroom ESP32 Ethernet Uptime': Sending state 775.94000 s with 0 decimals of accuracy
[06:26:15][D][sensor:094]: 'Master Bedroom ESP32 Free Memory': Sending state 75424.00000 B with 1 decimals of accuracy
[06:26:36][D][sensor:094]: 'Master Bedroom ESP32 Ethernet Uptime': Sending state 835.94202 s with 0 decimals of accuracy
[06:27:15][D][sensor:094]: 'Master Bedroom ESP32 Free Memory': Sending state 75424.00000 B with 1 decimals of accuracy
[06:27:36][D][sensor:094]: 'Master Bedroom ESP32 Ethernet Uptime': Sending state 895.94000 s with 0 decimals of accuracy
[06:27:40][D][esp32_ble_tracker:245]: Starting scan...
[06:28:15][D][sensor:094]: 'Master Bedroom ESP32 Free Memory': Sending state 75424.00000 B with 1 decimals of accuracy
[06:28:36][D][sensor:094]: 'Master Bedroom ESP32 Ethernet Uptime': Sending state 955.94000 s with 0 decimals of accuracy
```
```


### Additional information

_No response_

### LINKED ISSUE #4667: ble_rrsi sensor causing errors in HA
### The problem

I've set up `ble_rssi` platform sensor to monitor my Xiaomi Miscale which recently stopped working properly (mostly esphome is not able to read the measurements anymore). Now I'm receiving lots of errors in HA log.

### Which version of ESPHome has the issue?

2023.6.4

### What type of installation are you using?

Docker

### Which version of Home Assistant has the issue?

2023.7.0

### What platform are you using?

ESP32

### Board

ESP32 DEVKITV1

### Component causing the issue

ble_rssi

### Example YAML snippet

```yaml
sensor:
  - platform: ble_rssi
    mac_address: 0C:95:41:7E:E8:17
    name: "Xiaomi Scale RSSI"
esp32_ble_tracker:
  scan_parameters:
    interval: 60s
    window: 20s
```

### Anything in the logs that might be useful for us?

```txt
2023-07-06 09:10:50.385 ERROR (MainThread) [homeassistant.components.mqtt.models] Exception raised when updating state of sensor.xiaomi_scale_rssi, topic: 'bttracker2/sensor/xiaomi_scale_rssi/state' with payload: b'nan'
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/components/sensor/__init__.py", line 590, in state
    numerical_value = int(value)
                      ^^^^^^^^^^
ValueError: invalid literal for int() with base 10: 'nan'

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/components/mqtt/models.py", line 270, in process_write_state_requests
    entity.async_write_ha_state()
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 742, in async_write_ha_state
    self._async_write_ha_state()
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 809, in _async_write_ha_state
    state = self._stringify_state(available)
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 748, in _stringify_state
    if (state := self.state) is None:
                 ^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/components/sensor/__init__.py", line 594, in state
    raise ValueError(
ValueError: Sensor sensor.xiaomi_scale_rssi has device class 'signal_strength', state class 'measurement' unit 'dBm' and suggested precision 'None' thus indicating it has a numeric value; however, it has the non-numeric value: 'nan' (<class 'str'>)
```

### Additional information

I've changed the `scan_interval` parameters to 60s and 20s accordingly as with default parameters the esphome has not been receiving any data from the scale.
I'm using mqtt so that the last reading is visible in HA. With esphome native integration the last reading would not be visible in HA after e.g. restart of HA.

### LINKED ISSUE #4680: Automation of esp32_ble_tracker cannot be triggered after bluetooth_proxy is enabled
### The problem

After using bluetooth_proxy, the automation of esp32_ble_tracker can be triggered before the device is connected to HomeAssistant through the API, but when the device is connected to HomeAssistant through the API, esp32_ble_tracker automation will no longer trigger.

In version 2023.5.5, the automation works fine.

### Which version of ESPHome has the issue?

2023.6.1-2023.6.4

### What type of installation are you using?

Home Assistant Add-on

### Which version of Home Assistant has the issue?

2023.7.1

### What platform are you using?

ESP32

### Board

nodemcu

### Component causing the issue

bluetooth proxy

### Example YAML snippet

```yaml
esphome:
  name: test
  friendly_name: test
esp32:
  board: esp32dev
  framework:
    type: arduino

# Enable logging
logger:

# Enable Home Assistant API
api:

ota:
  password: ""

ethernet:
  type: LAN8720
  id: eth
  mdc_pin: GPIO23
  mdio_pin: GPIO18
  clk_mode: GPIO17_OUT
  phy_addr: 1

esp32_ble_tracker:
  scan_parameters:
    interval: 1100ms
    window: 1100ms
    active: true
  on_ble_advertise:
    - mac_address:
        - A4:C1:xx:xx:xx:xx
      then:
        - lambda: |-
            ESP_LOGD("ble_adv", "New BLE device");
            ESP_LOGD("ble_adv", "  address: %s", x.address_str().c_str());
            ESP_LOGD("ble_adv", "  name: %s", x.get_name().c_str());
            ESP_LOGD("ble_adv", "  Advertised service UUIDs:");
            for (auto uuid : x.get_service_uuids()) {
                ESP_LOGD("ble_adv", "    - %s", uuid.to_string().c_str());
            }
            ESP_LOGD("ble_adv", "  Advertised service data:");
            for (auto data : x.get_service_datas()) {
                ESP_LOGD("ble_adv", "    - %s: (length %i)", data.uuid.to_string().c_str(), data.data.size());
            }
            ESP_LOGD("ble_adv", "  Advertised manufacturer data:");
            for (auto data : x.get_manufacturer_datas()) {
                ESP_LOGD("ble_adv", "    - %s: (length %i)", data.uuid.to_string().c_str(), data.data.size());
            }

bluetooth_proxy:
  id: ble_proxy
  active: true
  # cache_services: true
```

### Anything in the logs that might be useful for us?

```txt
␛[0;36m[D][ble_adv:044]: New BLE device␛[0m
␛[0;36m[D][ble_adv:045]:   address: A4:C1:xx:xx:xx:xx␛[0m
␛[0;36m[D][ble_adv:046]:   name: xxxx␛[0m
␛[0;36m[D][ble_adv:047]:   Advertised service UUIDs:␛[0m
␛[0;36m[D][ble_adv:051]:   Advertised service data:␛[0m
␛[0;36m[D][ble_adv:053]:     - 0x0000: (length 10)␛[0m
␛[0;36m[D][ble_adv:055]:   Advertised manufacturer data:␛[0m
␛[0;36m[D][ble_adv:057]:     - 0x0000: (length 1)␛[0m
␛[0;33m[W][component:204]: Component esp32_ble_tracker took a long time for an operation (0.56 s).␛[0m
␛[0;33m[W][component:205]: Components should block for at most 20-30ms.␛[0m
␛[0;36m[D][api:102]: Accepted 192.168.xx.xx␛[0m
␛[0;36m[D][api.connection:1030]: Home Assistant 2023.7.1 (192.168.xx.xx): Connected successfully␛[0m
␛[0;32m[I][ota:113]: Boot seems successful, resetting boot loop counter.␛[0m
␛[0;36m[D][esp32.preferences:114]: Saving 1 preferences to flash...␛[0m
␛[0;36m[D][esp32.preferences:143]: Saving 1 preferences to flash: 0 cached, 1 written, 0 failed␛[0m
␛[0;36m[D][esp32_ble_tracker:245]: Starting scan...␛[0m
␛[0;36m[D][esp32_ble_tracker:245]: Starting scan...␛[0m
␛[0;36m[D][esp32_ble_tracker:245]: Starting scan...␛[0m
```

### Additional information

_No response_

### PR DESCRIPTION
**Pull request by bdraco**
# What does this implement/fix?

fixes https://github.com/esphome/issues/issues/4641 fixes https://github.com/esphome/issues/issues/4667 fixes https://github.com/esphome/issues/issues/4680

## Types of changes

- [x] Bugfix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] Other

**Related issue or feature (if applicable):** fixes <link to issue>

**Pull request in [esphome-docs](https://github.com/esphome/esphome-docs) with documentation (if applicable):** esphome/esphome-docs#<esphome-docs PR number goes here>

## Test Environment

- [ ] ESP32
- [ ] ESP32 IDF
- [ ] ESP8266
- [ ] RP2040

## Example entry for `config.yaml`:

```yaml
# Example config.yaml

```

## Checklist:
  - [ ] The code change is tested and works locally.
  - [ ] Tests have been added to verify that the new code works (under `tests/` folder).

If user exposed functionality or configuration variables are added/changed:
  - [ ] Documentation added/updated in [esphome-docs](https://github.com/esphome/esphome-docs).

### CODE REVIEW

**Comment by bdraco** [comment]
I don't have a way to test this with anything other than proxies as I have no devices that are configured locally on the esphome device

**Comment by antibill51** [comment]
> I don't have a way to test this

it seems to work for me.
I just added:

```
external_components:
  - source: github://pr#5073
    components: [ esp32_ble_tracker ]
```

File: esphome/components/esp32_ble_tracker/esp32_ble_tracker.cpp [hunk 1]
```diff
@@ -107,16 +107,16 @@ void ESP32BLETracker::loop() {
...
+      bool needs_single_parse = false;
 
       for (auto *listener : this->listeners_) {
-        bulk_parsed |= listener->parse_devices(this->scan_result_buffer_, this->scan_result_index_);
+        needs_single_parse |= !listener->parse_devices(this->scan_result_buffer_, this->scan_result_index_);
       }
       for (auto *client : this->clients_) {
-        bulk_parsed |= client->parse_devices(this->scan_result_buffer_, this->scan_result_index_);
+        needs_single_parse |= !client->parse_devices(this->scan_result_buffer_, this->scan_result_index_);
       }
```
Comment (bdraco) [inline esphome/components/esp32_ble_tracker/esp32_ble_tracker.cpp]: I think it would be cleaner to have a `this->needs_single_parse_` that gets recalculated every time a client and listener is added or removed.

**Comment by bdraco** [comment]
Unfortunately this introduces a regression and its parsing both bulk and single.

Need to think about a solution some more

File: esphome/components/esp32_ble_tracker/esp32_ble_tracker.cpp (hunk 1 above)
Comment (bdraco) [reply esphome/components/esp32_ble_tracker/esp32_ble_tracker.cpp]: Maybe have `bluetooth_proxy` return an enum of parser types

if (this->raw_advertisements_) {
  return BluetoothTrackerParser::MULTI_DEVICE;
} else {
  return BluetoothTrackerParser::SINGLE_DEVICE;
}

Than we can override it to return SINGLE_DEVICE by default

That would allow clients to return BluetoothTrackerParser::MULTI_DEVICE | BluetoothTrackerParser::SINGLE_DEVICE if they want both.

Then whenever a client or listener is registered we recalculate `BluetoothTrackerParser` and the code can change to be

`if (this->parsers & BluetoothTrackerParser::MULTI_DEVICE) {`

`if (this->parsers & BluetoothTrackerParser::SINGLE_DEVICE) {`

Comment (bdraco) [reply esphome/components/esp32_ble_tracker/esp32_ble_tracker.cpp]: It would perform better to have two flags and avoid the & op each loop

**Comment by bdraco** [comment]
I should be able to test the above design even without a local ble device and just the proxy with some old school print debugging

**Comment by bdraco** [comment]
Refactored it a bit to avoid the regression

```
external_components:
  - source: github://pr#5073
    components: [ esp32_ble_tracker, bluetooth_proxy  ]
```

@antibill51 Can you confirm it still works with the above?

**Review by jesserockz — APPROVED** [review]
LGTM, thanks for fixing =)

**Comment by bdraco** [comment]
Will undraft when new design is confirmed working above

**Comment by jesserockz** [comment]
Im just configuring one of my proxies to grab the data locally too

File: esphome/components/esp32_ble_tracker/esp32_ble_tracker.h [hunk 2]
```diff
@@ -231,6 +236,8 @@ class ESP32BLETracker : public Component, public GAPEventHandler, public GATTcEv
   bool scan_continuous_;
   bool scan_active_;
   bool scanner_idle_;
+  bool raw_advertisements_{false};
+  bool parse_advertisements_{false};
```
Comment (bdraco) [inline esphome/components/esp32_ble_tracker/esp32_ble_tracker.h:240]:
```suggestion
  bool parse_advertisements_{true};
```

Comment (bdraco) [reply esphome/components/esp32_ble_tracker/esp32_ble_tracker.h:240]: If we want it to still print if there are no listeners

Comment (bdraco) [reply esphome/components/esp32_ble_tracker/esp32_ble_tracker.h:240]: Maybe best leave as-is as its more stable if we don't parse it

**Comment by antibill51** [comment]
> Refactored it a bit to avoid the regression
> 
> ```
> external_components:
>   - source: github://pr#5073
>     components: [ esp32_ble_tracker, bluetooth_proxy  ]
> ```
> 
> @antibill51 Can you confirm it still works with the above?

It's fine for me, Thanks !

**Comment by bdraco** [comment]
Thanks for testing!

**Comment by regystro** [comment]
I can confirm that this also fixed this issue: https://github.com/home-assistant/core/issues/96102

Thank you :)

**Comment by myhomeiot** [comment]
@bdraco This fix introduce `register_listener` method which you plan to use in current version of `bluetooth_proxy` or it's for later improvements? I try to understand if I can improve [ble_gateway](https://github.com/myhomeiot/esphome-components#ble-gateway) to use raw advertisements or better to wait for next version.

**Comment by bdraco** [comment]
> @bdraco This fix introduce `register_listener` method which you plan to use in current version of `bluetooth_proxy` or it's for later improvements? I try to understand if I can improve [ble_gateway](https://github.com/myhomeiot/esphome-components#ble-gateway) to use raw advertisements or better to wait for next version.

That method has always been available.  It was just moved around

**Comment by myhomeiot** [comment]
> That method has always been available. It was just moved around

You are right, and it's was used only by esp32_ble_tracker itself.
