### PR TITLE
[gdk101] Retry reset on interval for slow-booting sensor MCU

### LINKED ISSUE #11375: GDK101 is unable to reset after powerup
### The problem

GDK101 sensor is marked failed right after power up due to sensor not been able to acknowledge reset in that case. After reboot of esp it working good. It is probably due to booting of sensor MCU (STM32) but by adding retries and delays I was not able to fix that.

### Which version of ESPHome has the issue?

2025.10.1

### What type of installation are you using?

Home Assistant Add-on

### What platform are you using?

ESP8266

### Component causing the issue

gdk101

### YAML Config

```yaml
esphome:
  name: gdk101
  friendly_name: gdk101

esp8266:
  board: d1_mini

# Enable logging
logger:

# Enable Home Assistant API
api:
  encryption:
    key: "XXX"

ota:
  - platform: esphome
    password: "XXX"

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password

  # Enable fallback hotspot (captive portal) in case wifi connection fails
  ap:
    ssid: "Fallback Hotspot"
    password: "XXX"

captive_portal:

status_led:
  pin:
    number: GPIO02

i2c:
  sda: GPIO04
  scl: GPIO05
#  scan: True
  id: bus_a

gdk101:    
  i2c_id: bus_a
  address: 0x18
  update_interval: 60s

sensor:
  - platform: gdk101
    radiation_dose_per_1m:
      name: "GDK101 average radiation dose per 1 min"
    radiation_dose_per_10m:
      name: "GDK101 average radiation dose per 10 min"
    status:
      name: "GDK101 status"
    version:
      name: "GDK101 fw version"
    measurement_duration:
      name: "GDK101 measurement time"

binary_sensor:
  - platform: status
    name: "Status"
  - platform: gdk101
    vibrations:
      name: "GDK101 vibration status"
```

### Anything in the logs that might be useful for us?

```txt
[19:33:24.893][I][i2c.arduino:099]: Results from bus scan:
[19:33:24.898][I][i2c.arduino:105]: Found device at address 0x18
[19:33:24.915][C][template.text_sensor:014]: Template Sensor 'GDK101 Status Description'
[19:33:24.927][C][gdk101:066]: GDK101:
[19:33:24.927][C][gdk101:067]:   Address: 0x18
[19:33:24.927][E][gdk101:069]: Communication failed
[19:33:24.955][C][gdk101:015]:   Average Radaition Dose per 1 minute 'GDK101 average radiation dose per 1 min'
[19:33:24.955][C][gdk101:015]:     State Class: 'measurement'
[19:33:24.955][C][gdk101:015]:     Unit of Measurement: 'µSv/h'
[19:33:24.955][C][gdk101:015]:     Accuracy Decimals: 2
[19:33:24.971][C][gdk101:029]:     Icon: 'mdi:radioactive'
[19:33:24.971][C][gdk101:015]:   Average Radaition Dose per 10 minutes 'GDK101 average radiation dose per 10 min'
[19:33:24.971][C][gdk101:015]:     State Class: 'measurement'
[19:33:24.971][C][gdk101:015]:     Unit of Measurement: 'µSv/h'
[19:33:24.971][C][gdk101:015]:     Accuracy Decimals: 2
[19:33:24.971][C][gdk101:029]:     Icon: 'mdi:radioactive'
[19:33:24.981][C][gdk101:015]:   Status 'GDK101 status'
[19:33:24.981][C][gdk101:015]:     State Class: ''
[19:33:24.981][C][gdk101:015]:     Unit of Measurement: ''
[19:33:24.981][C][gdk101:015]:     Accuracy Decimals: 0
[19:33:24.994][C][gdk101:015]:   Measurement Duration 'GDK101 measurement time'
[19:33:24.994][C][gdk101:015]:     State Class: 'total_increasing'
[19:33:24.994][C][gdk101:015]:     Unit of Measurement: 's'
[19:33:24.994][C][gdk101:015]:     Accuracy Decimals: 0
[19:33:25.006][C][gdk101:025]:     Device Class: 'duration'
[19:33:25.006][C][gdk101:029]:     Icon: 'mdi:timer-outline'
[19:33:25.027][C][gdk101:016]:   Vibration Status 'GDK101 vibration status'
[19:33:25.028][C][gdk101:019]:     Device Class: 'vibration'
[19:33:25.028][C][gdk101:014]:   Firmware Version 'GDK101 fw version'
[19:33:25.028][C][gdk101:021]:     Icon: 'mdi:chip'
[19:33:25.035][E][component:154]:   gdk101 is marked FAILED: Reset not acknowledged!
[19:33:25.043][C][status:016]: Status Binary Sensor 'Status'
[19:33:25.043][C][status:019]:   Device Class: 'connectivity'
[19:33:25.061][C][captive_portal:116]: Captive Portal:
[19:33:25.073][C][esphome.ota:093]: Over-The-Air updates:
[19:33:25.073][C][esphome.ota:093]:   Address: gdk101.local:8266
[19:33:25.073][C][esphome.ota:093]:   Version: 2
[19:33:25.078][C][esphome.ota:100]:   Password configured
[19:33:25.084][C][safe_mode:018]: Safe Mode:
[19:33:25.084][C][safe_mode:018]:   Successful after: 60s
[19:33:25.084][C][safe_mode:018]:   Invoke after: 10 attempts
[19:33:25.084][C][safe_mode:018]:   Duration: 300s
[19:33:25.093][C][web_server.ota:241]: Web Server OTA
[19:33:25.101][C][api:222]: Server:
[19:33:25.101][C][api:222]:   Address: gdk101.local:6053
[19:33:25.101][C][api:222]:   Listen backlog: 1
[19:33:25.101][C][api:222]:   Max connections: 4
[19:33:25.105][C][api:229]:   Noise encryption: YES
[19:33:25.108][C][mdns:179]: mDNS:
[19:33:25.108][C][mdns:179]:   Hostname: gdk101
```

### Additional information

I will work on that in the free time, but maybe someone have some idea how to fix it.

### PR DESCRIPTION
**Pull request by Szewcson**
# What does this implement/fix?

The GDK101 radiation sensor uses an STM32 MCU that boots slowly after a power cycle. The previous `setup()` implementation would fail immediately if the sensor didn't acknowledge the reset command, marking the component as failed with no recovery path.

This PR makes the reset non-blocking and retries on a 1-second interval (up to 10 attempts) so the sensor can finish booting without blocking other components from initializing. Once the sensor acknowledges the reset, normal polling resumes. If all retries are exhausted, the component is marked failed.

Changes:
- Extract reset logic into `try_reset_()` method
- Use `set_interval` with a 1-second retry loop instead of blocking in `setup()`
- `update()` skips sensor reads until reset completes
- Cancel the retry interval on success or hard failure

## Types of changes

- [x] Bugfix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected) — [policy](https://developers.esphome.io/contributing/code/#what-constitutes-a-c-breaking-change)
- [ ] Developer breaking change (an API change that could break external components) — [policy](https://developers.esphome.io/contributing/code/#what-is-considered-public-c-api)
- [ ] Undocumented C++ API change (removal or change of undocumented public methods that lambda users may depend on) — [policy](https://developers.esphome.io/contributing/code/#c-user-expectations)
- [ ] Code quality improvements to existing code or addition of tests
- [ ] Other

**Related issue or feature (if applicable):**

- fixes #11375

**Pull request in [esphome-docs](https://github.com/esphome/esphome-docs) with documentation (if applicable):**

- esphome/esphome-docs#

## Test Environment

- [ ] ESP32
- [ ] ESP32 IDF
- [x] ESP8266
- [ ] RP2040/RP2350
- [ ] BK72xx
- [ ] RTL87xx
- [ ] LN882x
- [ ] nRF52840

## Example entry for `config.yaml`:

```yaml
# Example config.yaml

```

## Checklist:
  - [x] The code change is tested and works locally.
  - [ ] Tests have been added to verify that the new code works (under `tests/` folder).

If user exposed functionality or configuration variables are added/changed:
  - [ ] Documentation added/updated in [esphome-docs](https://github.com/esphome/esphome-docs).

### CODE REVIEW

File: esphome/components/gdk101/gdk101.cpp [hunk 1]
```diff
@@ -33,18 +33,14 @@ void GDK101Component::update() {
...
-    this->mark_failed();
-    return;
-  }
-  // sensor should acknowledge success of the reset procedure
-  if (data[0] != 1) {
-    this->status_set_error(LOG_STR("Reset not acknowledged!"));
-    this->mark_failed();
-    return;
+  while (data[0] != 1) {
+    if (!this->reset_sensor_(data)) {
```
Comment (bdraco) [inline esphome/components/gdk101/gdk101.cpp]: This is an unbounded busy wait at setup that can block startup forever

**Review by bdraco — CHANGES_REQUESTED** [review]
This is an unbounded busy wait at setup that can block startup forever. If the sensor never acknowledges the reset, the device will never boot and you won't be able to OTA or connect to it at all.

The approach should be to try the reset once in setup(), and if it doesn't get acknowledged, track the state with a member variable and keep retrying in update() until the sensor finally responds or give up after a reasonable number of attempts and mark_failed(). That way the device can still boot, connect to wifi, and be reachable for OTA even if the sensor is being slow or unresponsive.

Also get_setup_priority() is defined in the cpp but theres no declaration for it in the header file which should be a compile error which is likely from the merge conflict.

**Comment by bdraco** [comment]
I did some cleanup. Please give it a try.

**Comment by Szewcson** [comment]
Seems to work.

**Review by bdraco — DISMISSED** [review]

**Review by bdraco — APPROVED** [review]

**Comment by bdraco** [comment]
@Szewcson I did some more cleanup.  Is it still working ok for you?

**Comment by Szewcson** [comment]
```
[19:31:00.719][C][template.text_sensor:016]: Template Sensor 'GDK101 Status'
[19:31:00.735][C][gdk101:084]: GDK101:
[19:31:00.736][C][gdk101:085]:   Address: 0x18
[19:31:00.747][E][gdk101:087]: Communication failed
[19:31:00.747][C][gdk101:017]:   Average Radaition Dose per 1 minute 'GDK101 1min µSv⁄h'
[19:31:00.747][C][gdk101:017]:     State Class: 'measurement'
[19:31:00.747][C][gdk101:017]:     Unit of Measurement: 'µSv/h'
[19:31:00.747][C][gdk101:017]:     Accuracy Decimals: 2
[19:31:00.748][C][gdk101:228]:     Icon: 'mdi:radioactive'
[19:31:00.759][C][gdk101:017]:   Average Radaition Dose per 10 minutes 'GDK101 10min µSv⁄h'
[19:31:00.759][C][gdk101:017]:     State Class: 'measurement'
[19:31:00.759][C][gdk101:017]:     Unit of Measurement: 'µSv/h'
[19:31:00.759][C][gdk101:017]:     Accuracy Decimals: 2
[19:31:00.771][C][gdk101:228]:     Icon: 'mdi:radioactive'
[19:31:00.771][C][gdk101:017]:   Status 'GDK101 status'
[19:31:00.771][C][gdk101:017]:     State Class: ''
[19:31:00.771][C][gdk101:017]:     Unit of Measurement: ''
[19:31:00.771][C][gdk101:017]:     Accuracy Decimals: 0
[19:31:00.782][C][gdk101:017]:   Measurement Duration 'GDK101 meas time (s)'
[19:31:00.782][C][gdk101:017]:     State Class: 'total_increasing'
[19:31:00.782][C][gdk101:017]:     Unit of Measurement: 's'
[19:31:00.782][C][gdk101:017]:     Accuracy Decimals: 0
[19:31:00.803][C][gdk101:237]:     Device Class: 'duration'
[19:31:00.803][C][gdk101:228]:     Icon: 'mdi:timer-outline'
[19:31:00.815][C][gdk101:016]:   Vibration Status 'GDK101 Vibration'
[19:31:00.815][C][gdk101:237]:     Device Class: 'vibration'
[19:31:00.827][C][gdk101:016]:   Firmware Version 'GDK101 FW'
[19:31:00.828][C][gdk101:228]:     Icon: 'mdi:chip'
[19:31:00.828][E][component:230]:   gdk101 is marked FAILED: Reset failed after retries
```

**Comment by bdraco** [comment]
ok maybe its really that slow.. increased it in https://github.com/esphome/esphome/pull/15584
