### PR TITLE
[TCS34725] remove duplicated endian conversion

### LINKED ISSUE #2930: TCS34725 broke with recent changes, endian is wrong
### The problem

Previously working code to determine color of LED (red or green) now fails, and return values for RGB and clear are very small.

Loading a copy of 2021.10.3 or older as a custom component (change name throughout) fixes the issue. Expected percentages are in the range of 10-40%, but with new version they are well under 0.1%. Using older version of TCS34725 as custom component restores proper operation.

Pull request https://github.com/esphome/esphome/pull/2445 indicates that endian was swapped because documentation showed little endian in ESP but big endian in I2C. this was implemented on lines 185-190 in TCS34725.cpp. However, this calls read_byte_16 in i2c.cpp, which in turn calls read_bytes_16, which has the endian swap already.

Please remove lines 185-190 in the newest TCS34725.cpp to fix this issue.

Thanks

### Which version of ESPHome has the issue?

2021.11.0 and later

### What type of installation are you using?

Home Assistant Add-on

### Which version of Home Assistant has the issue?

2021.12.7

### What platform are you using?

ESP32

### Board

d1 mini and TCS34725

### Component causing the issue

TCS34725

### Example YAML snippet

```yaml
- platform: tcs34725old
    red_channel:
      name: "TCS34725 Red"
      internal: true
      id: red_bright

    green_channel:
      name: "TCS34725 Green"
      internal: true
      id: green_bright

    clear_channel:
      name: "TCS34725 Clear"
      internal: true
      id: clear_bright

    blue_channel:
      name: "TCS34725 Blue"
      internal: true
      id: blue_bright
      on_value:
        then:
          - script.execute: read_colors

    gain: 60x
#    integration_time: 2.4ms
    integration_time: 101ms
    address: 0x29
    update_interval: 200ms
```

### Anything in the logs that might be useful for us?

```txt
No error message, just wrong values for RGB and Clear
```

### Additional information

_No response_

### PR DESCRIPTION
**Pull request by martgras**
# What does this implement/fix? 

The existing code uses i2c::read_byte_16 which calls i2c::i2ctohs. Since TCS34725 uses little endian the  i2c::i2ctohs has to be called again to revert the previous incorrect (for this sensor)  i2c::i2ctohs call. 
This fix uses i2c::write_register instead.
For consistency all remaining i2c calls are changed to use i2c::write/read_register only. 

To address the issue from 2930 the scaling algorithm for C,R,G and B is changed to report R,B,G as percentage of C. 
C is scaled in relation to the max value based on intergration time instead of hardcoding the max to 65535 

## Types of changes
 
- [x] Bugfix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] Other

**Related issue or feature (if applicable):** fixes https://github.com/esphome/issues/issues/2930

**Pull request in [esphome-docs](https://github.com/esphome/esphome-docs) with documentation (if applicable):** esphome/esphome-docs#<esphome-docs PR number goes here>

## Test Environment

- [x] ESP32
- [ ] ESP32 IDF
- [ ] ESP8266

## Checklist:
  - [ ] The code change is tested and works locally.
  - [ ] Tests have been added to verify that the new code works (under `tests/` folder).
  
If user exposed functionality or configuration variables are added/changed:
  - [ ] Documentation added/updated in [esphome-docs](https://github.com/esphome/esphome-docs).

### CODE REVIEW

**Comment by oxan** [comment]
I wonder why @razorback16 needed to add these in #2445, nothing relevant in the I2C code has changed since then as far as I can see. Do different devices have different endianness?

**Comment by ceandraka** [comment]
I posted the issue here: https://github.com/esphome/issues/issues/2930. The change in 2445 definitely broke a working system, and appears to be a duplication of swapping endian. This new revision restores proper operation. I am using a d1 Mini and a TCS34725.

It does appear that i2c was updated at some point. I had not recompiled my ESPHome devices in at least a few months, but recompile with update of ESPHome this week caused this failure. Restoration to 2021.10.3 or earlier restored operation (restoration of just TCS34725 code). Removal of the endian swap in 2021.12.3 also resolved the issue.

I cannot answer if different devices have different endiness, but this solution repairs the code for the d1 mini. My understanding is that all ESP's have the same endiness.

**Comment by razorback16** [comment]
@ceandraka at that time, it was swapping the endianness and I was getting the wrong result.

**Comment by ceandraka** [comment]
I have not reviewed the i2c updates, but that also changed from my original compile. Perhaps that changed (added endian swap) after your update. Or, as oxan suggested, different devices have different endian?

**Comment by razorback16** [comment]
I used an ESP32 at that time

**Comment by ceandraka** [comment]
razorback16, can you test the PR version on your hardware?

**Comment by ceandraka** [comment]
It appears that the endian change in i2c changed in the 2021.10.0 version. This was a substantial change to the entire layout of the i2c routines. Since it was a substantial change, I have not picked through it enough to determine if indeed an endian change occurred, but that is when the i2ctohs conversion was placed in the read_bytes_16 routine. As I said, the changes there were substantial, so perhaps adding the conversion replaced something else that was converting prior.

**Comment by ceandraka** [comment]
I compiled and tested on my limited application, and it appears to be working.

It should be noted that the new RGB output differs from documentation. It is now consistent with Adafruit version. Clear channel is also changed, and appears more appropriate. However, these changes need to be in the documentation, and may result in this being a "breaking" change.

RGB values are now a percentage of clear value, rather than a percentage of saturation. This allows one to see the "color" even at low light levels. The clear is now a percentage of the possible saturation based on integration time, rather than a percentage of ultimate saturation of 65535. Adafruit only reports RGB channels as a percentage of clear, and does not attempt to report the clear channel at all. 

I think the approach presented in this PR is favorable, as RGB is consistent with Adafruit, and allows reporting values even at low light. The clear channel is an enhancement, and maintains some level of compatibility with prior releases, where the clear channel may have been used by some members.

Thanks for your work on this.

File: esphome/components/tcs34725/tcs34725.cpp [hunk 1]
```diff
@@ -134,9 +134,9 @@ void TCS34725Component::calculate_temperature_and_lux_(uint16_t r, uint16_t g, u
     /* Adjust sat to 75% to avoid analog saturation if atime < 153.6ms */
     sat -= sat / 4.f;
   }
-
   /* Check for saturation and mark the sample as invalid if true */
   if (c >= sat) {
+    ESP_LOGW(TAG, "Saturation too high discarding sample = sat=.1%f clear = %d", sat, c);
```
Comment (oxan) [inline esphome/components/tcs34725/tcs34725.cpp]:
```suggestion
    ESP_LOGW(TAG, "Saturation too high, discarding sample with saturation %.1f and clear %d", sat, c);
```

**Review by oxan — APPROVED** [review]
LGTM.

**Comment by oxan** [comment]
An extension of the documentation would be nice, but I don't think anything there is factually incorrect with this change. We'll mention that changed behaviour in the changelog.

**Comment by martgras** [comment]
docs updated

**Review by jesserockz — APPROVED** [review]
