### PR TITLE
[http_request] Fix OTA failures on ESP8266/Arduino by making read semantics consistent

### LINKED ISSUE #13255: HTTP OTA update fails with Arduino framework since 2025.12.0
### The problem

Since ESPHome 2025.12.0, HTTP OTA updates using the arduino framework on ESP32-C3 consistently fail. The firmware download terminates prematurely (e.g., at ~13% progress), which subsequently leads to an MD5 mismatch error.

###  Key Observations:
1. Regression: This worked perfectly fine in ESPHome 2025.11.5 using the arduino framework.
2. Framework Specific: In 2025.12.x, the issue only occurs with `arduino`. Switching the framework to esp-idf on
  the same device and same ESPHome version (2025.12.6) allows the OTA update to complete successfully.
3. Behavior: The logs show the download starting, reaching a small percentage, and then suddenly finishing as if
  the stream reached EOF unexpectedly.

### Which version of ESPHome has the issue?

2025.12.0, 2025.12.6

### What type of installation are you using?

pip

### What platform are you using?

ESP32

### Component causing the issue

http_request

### YAML Config

```yaml
substitutions:
  device_name: weather-display-waveshare
  friendly_name: weather display
  version: "2.5.0"
  timezone: Asia/Taipei
  ota_update_source: https://dl.brandonch.com/weather-display-waveshare/manifest.json

esphome:
  project:
    name: Brandon.$device_name
    version: $version

  name: $device_name
  friendly_name: $friendly_name

esp32:
  board: esp32-c3-devkitm-1
  framework:
    type: arduino

logger:
  level: DEBUG

wifi:
  id: wifi_id

  ap:
    ssid: "$friendly_name"
    password: "12345678"

api:
  reboot_timeout: 0s

time:
  - platform: sntp
    id: esp_time
    timezone: $timezone
    servers:
      - time1.google.com
      - time2.google.com
      - time3.google.com

button:
  - platform: template
    name: "Check"
    on_press:
      - logger.log:
          level: INFO
          format: "Check Button Pressed"
      - component.update: update_manager

  - platform: template
    name: "Perform Update"
    on_press:
      - logger.log:
          level: INFO
          format: "Perform Update Button Pressed"
      - update.perform: update_manager

http_request:
  verify_ssl: false
  timeout: 15s
  watchdog_timeout: 15s

update:
  - platform: http_request
    id: update_manager
    name: Firmware
    source: $ota_update_source

ota:
  - platform: esphome
  - platform: http_request
```

### Anything in the logs that might be useful for us?

```txt
INFO ESPHome 2025.12.6
INFO Reading configuration weather-display-waveshare-ota-debug.yaml...
INFO Generating C++ source...
INFO Compiling app... Build path: /home/brandon/workspaces/github/weather-display-waveshare/.esphome/build/weather-display-waveshare
Processing weather-display-waveshare (board: esp32-c3-devkitm-1; framework: arduino, espidf; platform: https://github.com/pioarduino/platform-espressif32/releases/download/55.03.31-2/platform-espressif32.zip)
--------------------------------------------------------------------------------
HARDWARE: ESP32C3 160MHz, 320KB RAM, 4MB Flash
 - contrib-piohome @ 3.4.4 
 - framework-arduinoespressif32 @ 3.3.2 
 - framework-arduinoespressif32-libs @ 5.5.0+sha.129cd0d247 
 - framework-espidf @ 3.50501.0 (5.5.1) 
 - tool-cmake @ 4.0.3 
 - tool-esp-rom-elfs @ 2024.10.11 
 - tool-esptoolpy @ 5.1.0 
 - tool-mklittlefs @ 3.2.0 
 - tool-ninja @ 1.13.1 
 - tool-scons @ 4.40801.0 (4.8.1) 
 - toolchain-riscv32-esp @ 14.2.0+20241119
Reading CMake configuration...
Dependency Graph
|-- Networking @ 3.3.2
|-- ESPmDNS @ 3.3.2
|-- ArduinoJson @ 7.4.2
|-- NetworkClientSecure @ 3.3.2
|-- HTTPClient @ 3.3.2
RAM:   [=         ]  10.5% (used 34564 bytes from 327680 bytes)
Flash: [======    ]  56.8% (used 1042750 bytes from 1835008 bytes)
========================= [SUCCESS] Took 7.14 seconds =========================
INFO Successfully compiled program.
INFO Connecting to 192.168.10.184 port 3232...
INFO Connected to 192.168.10.184
INFO Uploading /home/brandon/workspaces/github/weather-display-waveshare/.esphome/build/weather-display-waveshare/.pioenvs/weather-display-waveshare/firmware.bin (1043152 bytes)

Uploading: [                                                            ] 0% 
Uploading: [=                                                           ] 1% 
Uploading: [=                                                           ] 2% 
Uploading: [==                                                          ] 3% 
Uploading: [===                                                         ] 4% 
Uploading: [===                                                         ] 5% 
Uploading: [====                                                        ] 6% 
Uploading: [====                                                        ] 7% 
Uploading: [=====                                                       ] 8% 
Uploading: [======                                                      ] 9% 
Uploading: [======                                                      ] 10% 
Uploading: [=======                                                     ] 11% 
Uploading: [========                                                    ] 12% 
Uploading: [========                                                    ] 13% 
Uploading: [========                                                    ] 14% 
Uploading: [=========                                                   ] 15% 
Uploading: [==========                                                  ] 16% 
Uploading: [==========                                                  ] 17% 
Uploading: [===========                                                 ] 18% 
Uploading: [============                                                ] 19% 
Uploading: [============                                                ] 20% 
Uploading: [=============                                               ] 21% 
Uploading: [==============                                              ] 22% 
Uploading: [==============                                              ] 23% 
Uploading: [===============                                             ] 24% 
Uploading: [===============                                             ] 25% 
Uploading: [================                                            ] 26% 
Uploading: [================                                            ] 27% 
Uploading: [=================                                           ] 28% 
Uploading: [=================                                           ] 29% 
Uploading: [==================                                          ] 30% 
Uploading: [===================                                         ] 31% 
Uploading: [===================                                         ] 32% 
Uploading: [====================                                        ] 33% 
Uploading: [=====================                                       ] 34% 
Uploading: [=====================                                       ] 35% 
Uploading: [======================                                      ] 36% 
Uploading: [=======================                                     ] 37% 
Uploading: [=======================                                     ] 38% 
Uploading: [========================                                    ] 39% 
Uploading: [========================                                    ] 40% 
Uploading: [=========================                                   ] 41% 
Uploading: [=========================                                   ] 42% 
Uploading: [==========================                                  ] 43% 
Uploading: [===========================                                 ] 44% 
Uploading: [===========================                                 ] 45% 
Uploading: [============================                                ] 46% 
Uploading: [============================                                ] 47% 
Uploading: [=============================                               ] 48% 
Uploading: [==============================                              ] 49% 
Uploading: [==============================                              ] 50% 
Uploading: [===============================                             ] 51% 
Uploading: [================================                            ] 52% 
Uploading: [================================                            ] 53% 
Uploading: [=================================                           ] 54% 
Uploading: [=================================                           ] 55% 
Uploading: [==================================                          ] 56% 
Uploading: [==================================                          ] 57% 
Uploading: [===================================                         ] 58% 
Uploading: [====================================                        ] 59% 
Uploading: [====================================                        ] 60% 
Uploading: [=====================================                       ] 61% 
Uploading: [=====================================                       ] 62% 
Uploading: [======================================                      ] 63% 
Uploading: [=======================================                     ] 64% 
Uploading: [=======================================                     ] 65% 
Uploading: [========================================                    ] 66% 
Uploading: [=========================================                   ] 67% 
Uploading: [=========================================                   ] 68% 
Uploading: [=========================================                   ] 69% 
Uploading: [==========================================                  ] 70% 
Uploading: [===========================================                 ] 71% 
Uploading: [===========================================                 ] 72% 
Uploading: [============================================                ] 73% 
Uploading: [=============================================               ] 74% 
Uploading: [=============================================               ] 75% 
Uploading: [==============================================              ] 76% 
Uploading: [===============================================             ] 77% 
Uploading: [===============================================             ] 78% 
Uploading: [================================================            ] 79% 
Uploading: [================================================            ] 80% 
Uploading: [=================================================           ] 81% 
Uploading: [=================================================           ] 82% 
Uploading: [==================================================          ] 83% 
Uploading: [==================================================          ] 84% 
Uploading: [===================================================         ] 85% 
Uploading: [====================================================        ] 86% 
Uploading: [====================================================        ] 87% 
Uploading: [=====================================================       ] 88% 
Uploading: [======================================================      ] 89% 
Uploading: [======================================================      ] 90% 
Uploading: [=======================================================     ] 91% 
Uploading: [========================================================    ] 92% 
Uploading: [========================================================    ] 93% 
Uploading: [=========================================================   ] 94% 
Uploading: [=========================================================   ] 95% 
Uploading: [==========================================================  ] 96% 
Uploading: [==========================================================  ] 97% 
Uploading: [=========================================================== ] 98% 
Uploading: [============================================================] 99% 
Uploading: [============================================================] 100% Done...

INFO Upload took 4.97 seconds, waiting for result...
INFO OTA successful
INFO Successfully uploaded program.
INFO Starting log output from 192.168.10.184 using esphome API
INFO Successfully resolved weather-display-waveshare @ 192.168.10.184 in 0.000s
INFO Successfully connected to weather-display-waveshare @ 192.168.10.184 in 5.278s
INFO Successful handshake with weather-display-waveshare @ 192.168.10.184 in 0.006s
[08:47:43.494][I][app:194]: ESPHome version 2025.12.6 compiled on Jan 16 2026, 08:36:28
[08:47:43.507][I][app:196]: Project Brandon.weather-display-waveshare version 2.5.0
[08:47:43.507][C][logger:261]: Logger:
[08:47:43.507][C][logger:261]:   Max Level: DEBUG
[08:47:43.507][C][logger:261]:   Initial Level: DEBUG
[08:47:43.507][C][logger:267]:   Log Baud Rate: 115200
[08:47:43.507][C][logger:267]:   Hardware UART: USB_SERIAL_JTAG
[08:47:43.507][C][logger:274]:   Task Log Buffer Size: 768
[08:47:43.520][C][wifi:1132]: WiFi:
[08:47:43.520][C][wifi:1132]:   Connected: YES
[08:47:43.520][C][wifi:897]:   Local MAC: EC:DA:3B:39:97:40
[08:47:43.520][C][wifi:904]:   IP Address: 192.168.10.184
[08:47:43.522][C][wifi:908]:   SSID: 'Brandon'
[08:47:43.522][C][wifi:908]:   BSSID: 50:88:11:AC:A6:0B
[08:47:43.522][C][wifi:908]:   Hostname: 'weather-display-waveshare'
[08:47:43.522][C][wifi:908]:   Signal strength: -37 dB ▂▄▆█
[08:47:43.522][C][wifi:908]:   Channel: 3
[08:47:43.522][C][wifi:908]:   Subnet: 255.255.255.0
[08:47:43.522][C][wifi:908]:   Gateway: 192.168.10.1
[08:47:43.522][C][wifi:908]:   DNS1: 8.8.8.8
[08:47:43.522][C][wifi:908]:   DNS2: 8.8.4.4
[08:47:43.525][C][sntp:059]: SNTP Time:
[08:47:43.529][C][sntp:062]:   Server 0: 'time1.google.com'
[08:47:43.529][C][sntp:062]:   Server 1: 'time2.google.com'
[08:47:43.530][C][sntp:062]:   Server 2: 'time3.google.com'
[08:47:43.531][C][time:029]: Timezone: 'CST-8'
[08:47:43.541][C][esphome.ota:092]: Over-The-Air updates:
[08:47:43.541][C][esphome.ota:092]:   Address: weather-display-waveshare.local:3232
[08:47:43.541][C][esphome.ota:092]:   Version: 2
[08:47:43.551][C][safe_mode:018]: Safe Mode:
[08:47:43.551][C][safe_mode:018]:   Successful after: 60s
[08:47:43.551][C][safe_mode:018]:   Invoke after: 10 attempts
[08:47:43.551][C][safe_mode:018]:   Duration: 300s
[08:47:43.559][C][http_request.ota:025]: Over-The-Air updates via HTTP request
[08:47:43.571][C][api:211]: Server:
[08:47:43.571][C][api:211]:   Address: weather-display-waveshare.local:6053
[08:47:43.571][C][api:211]:   Listen backlog: 4
[08:47:43.571][C][api:211]:   Max connections: 8
[08:47:43.571][C][api:223]:   Noise encryption: NO
[08:47:43.581][C][http_request:013]: HTTP Request:
[08:47:43.581][C][http_request:013]:   Timeout: 15000ms
[08:47:43.581][C][http_request:013]:   User-Agent: ESPHome/2025.12.6 (https://esphome.io)
[08:47:43.581][C][http_request:013]:   Follow redirects: YES
[08:47:43.581][C][http_request:013]:   Redirect limit: 3
[08:47:43.582][C][http_request:021]:   Watchdog Timeout: 15000ms
[08:47:43.599][C][mdns:177]: mDNS:
[08:47:43.599][C][mdns:177]:   Hostname: weather-display-waveshare
[08:48:15.441][D][button:022]: 'Check' Pressed.
[08:48:15.445][I][main:248]: Check Button Pressed
[08:48:18.996][D][update:012]: 'Firmware' - Publishing:
[08:48:18.998][D][update:013]:   Current Version: 2.5.0
[08:48:18.999][D][update:016]:   Latest Version: 2.5.2
[08:48:19.001][D][update:019]:   Firmware URL: https://dl-brandonch-com.pages.dev/weather-display-waveshare/releases/2.5.2/firmware.ota.bin
[08:48:19.014][D][update:022]:   Title: Weather Display (Waveshare)
[08:48:19.014][D][http_request.arduino:141][update_task]: Content-Length: 457
[08:48:25.680][D][button:022]: 'Perform Update' Pressed.
[08:48:25.682][I][main:276]: Perform Update Button Pressed
[08:48:25.684][D][update:012]: 'Firmware' - Publishing:
[08:48:25.691][D][update:013]:   Current Version: 2.5.0
[08:48:25.691][D][update:016]:   Latest Version: 2.5.2
[08:48:25.691][D][update:019]:   Firmware URL: https://dl-brandonch-com.pages.dev/weather-display-waveshare/releases/2.5.2/firmware.ota.bin
[08:48:25.691][D][update:022]:   Title: Weather Display (Waveshare)
[08:48:25.696][I][http_request.ota:050]: Starting update
[08:48:25.697][D][http_request.ota:097]: MD5 expected: 5742ef9be25c4d118726a1a8ba7996c4
[08:48:25.701][I][http_request.ota:104]: Connecting to: https://dl-brandonch-com.pages.dev/weather-display-waveshare/releases/2.5.2/firmware.ota.bin
[08:48:26.478][D][http_request.arduino:141]: Content-Length: 1484384
[08:48:31.719][D][http_request.ota:167]: Progress: 0.0%
[08:48:31.719][D][update:012]: 'Firmware' - Publishing:
[08:48:31.719][D][update:013]:   Current Version: 2.5.0
[08:48:31.719][D][update:016]:   Latest Version: 2.5.2
[08:48:31.719][D][update:019]:   Firmware URL: https://dl-brandonch-com.pages.dev/weather-display-waveshare/releases/2.5.2/firmware.ota.bin
[08:48:31.719][D][update:022]:   Title: Weather Display (Waveshare)
[08:48:31.727][D][update:031]:   Progress: 0%
[08:48:32.664][D][http_request.ota:167]: Progress: 13.1%
[08:48:32.664][D][update:012]: 'Firmware' - Publishing:
[08:48:32.664][D][update:013]:   Current Version: 2.5.0
[08:48:32.666][D][update:016]:   Latest Version: 2.5.2
[08:48:32.668][D][update:019]:   Firmware URL: https://dl-brandonch-com.pages.dev/weather-display-waveshare/releases/2.5.2/firmware.ota.bin
[08:48:32.673][D][update:022]:   Title: Weather Display (Waveshare)
[08:48:32.674][D][update:031]:   Progress: 13%
[08:48:32.809][I][http_request.ota:174]: Done in 8 seconds
[08:48:32.812][E][http_request.ota:181]: MD5 computed: 510d5be4194f4f301e330c06ca02ef02$\x91\xc9?\xc8\xc5\xca?T\x80\xcb?` - Aborting due to MD5 mismatch
[08:48:32.820][E][component:362]: http_request.update set Error flag: Failed to install firmware
[08:48:32.820][D][update:012]: 'Firmware' - Publishing:
[08:48:32.822][D][update:013]:   Current Version: 2.5.0
[08:48:32.826][D][update:016]:   Latest Version: 2.5.2
[08:48:32.826][D][update:019]:   Firmware URL: https://dl-brandonch-com.pages.dev/weather-display-waveshare/releases/2.5.2/firmware.ota.bin
[08:48:32.831][D][update:022]:   Title: Weather Display (Waveshare)
[08:48:32.833][D][update:031]:   Progress: 13%
[08:48:32.833][W][component:490]: http_request.update took a long time for an operation (7546 ms)
[08:48:32.835][W][component:493]: Components should block for at most 30 ms
[08:48:32.838][W][component:490]: api took a long time for an operation (7552 ms)
[08:48:32.840][W][component:493]: Components should block for at most 30 ms
[08:48:35.921][I][safe_mode:042]: Boot seems successful; resetting boot loop counter
[08:48:35.926][D][esp32.preferences:149]: Writing 1 items: 0 cached, 1 written, 0 failed
[08:48:53.400][D][button:022]: 'Perform Update' Pressed.
[08:48:53.406][I][main:276]: Perform Update Button Pressed
[08:48:53.406][D][update:012]: 'Firmware' - Publishing:
[08:48:53.406][D][update:013]:   Current Version: 2.5.0
[08:48:53.406][D][update:016]:   Latest Version: 2.5.2
[08:48:53.407][D][update:019]:   Firmware URL: https://dl-brandonch-com.pages.dev/weather-display-waveshare/releases/2.5.2/firmware.ota.bin
[08:48:53.412][D][update:022]:   Title: Weather Display (Waveshare)
[08:48:53.412][D][update:031]:   Progress: 13%
[08:48:53.418][I][http_request.ota:050]: Starting update
[08:48:53.418][D][http_request.ota:097]: MD5 expected: 5742ef9be25c4d118726a1a8ba7996c4
[08:48:53.418][I][http_request.ota:104]: Connecting to: https://dl-brandonch-com.pages.dev/weather-display-waveshare/releases/2.5.2/firmware.ota.bin
[08:48:53.934][D][http_request.arduino:141]: Content-Length: 1484384
[08:48:59.270][D][http_request.ota:167]: Progress: 0.0%
[08:48:59.270][D][update:012]: 'Firmware' - Publishing:
[08:48:59.270][D][update:013]:   Current Version: 2.5.0
[08:48:59.270][D][update:016]:   Latest Version: 2.5.2
[08:48:59.270][D][update:019]:   Firmware URL: https://dl-brandonch-com.pages.dev/weather-display-waveshare/releases/2.5.2/firmware.ota.bin
[08:48:59.270][D][update:022]:   Title: Weather Display (Waveshare)
[08:48:59.270][D][update:031]:   Progress: 0%
[08:48:59.790][I][http_request.ota:174]: Done in 7 seconds
[08:48:59.790][E][http_request.ota:181]: MD5 computed: 1e64d8015a46a8711118a3d37504b103l\xff\xcb? - Aborting due to MD5 mismatch
[08:48:59.795][D][update:012]: 'Firmware' - Publishing:
[08:48:59.795][D][update:013]:   Current Version: 2.5.0
[08:48:59.797][D][update:016]:   Latest Version: 2.5.2
[08:48:59.798][D][update:019]:   Firmware URL: https://dl-brandonch-com.pages.dev/weather-display-waveshare/releases/2.5.2/firmware.ota.bin
[08:48:59.800][D][update:022]:   Title: Weather Display (Waveshare)
[08:48:59.803][D][update:031]:   Progress: 0%
```

### Additional information

_No response_

### LINKED ISSUE #13424: With esp8266 HTTP OTA update fails with Arduino framework since 2025.12.0
### The problem

Same issue as #13255 but with esp8266 and it is still an issue with 2026.1.0.

It starts to download the binary file and fails after some random % are downloaded with a MD5 mismatch error. This only happens with my esp8266 devices.

### Which version of ESPHome has the issue?

any > 2025.12.0

### What type of installation are you using?

pip

### What platform are you using?

ESP8266

### Component causing the issue

_No response_

### YAML Config

```yaml
substitutions:
  <<: !include ../../project_version.yaml

esphome:
  project:
    name: "home.${device_id}"
    version: "${project_version}"

http_request:
  verify_ssl: false
  timeout: 10s

ota:
  - platform: http_request
    id: http_ota

update:
  - platform: http_request
    name: Firmware Update
    source: http://XXXX.YYYY/${device_id}-manifest.json
```

### Anything in the logs that might be useful for us?

```txt
[17:10:20.637][D][update:029]:   Release URL: http://XXXX.YYYY
[17:10:20.637][D][update:033]:   Progress: 7%
[17:10:20.638][I][http_request.ota:167]: Done in 2 seconds
[17:10:20.638][E][http_request.ota:174]: MD5 computed: 5932ced1cc2d41eaafd573da3bb7eb53 - Aborting due to MD5 mismatch
[17:10:20.638][D][update:012]: 'Firmware Update' >>
[17:10:20.638][D][update:012]:   Current Version: 2026.1.0/2026-01-21T17:06:49+00:00/dirty
[17:10:20.638][D][update:018]:   Latest Version: 2026.1.0/2026-01-21T16:09:28+00:00/b9d7bea
```

### Additional information

_No response_

### PR DESCRIPTION
**Pull request by bdraco**
# What does this implement/fix?

Fixes HTTP OTA updates failing with MD5 mismatch on ESP8266 and ESP32 Arduino since 2025.12.0.

## Root Cause

PR #12480 changed the OTA code to exit when `read() == 0`, but the `read()` semantics were inconsistent between platforms:
- Arduino's non-blocking `read()` returned 0 for both "no data yet" and "connection closed"
- ESP-IDF's blocking `read()` returned 0 only when connection closed

This caused the download to terminate prematurely on Arduino, resulting in incomplete firmware and MD5 mismatches.

## Solution

Unified the `read()` semantics across all platforms:

```
WARNING: These semantics differ from standard BSD sockets!

BSD socket read() returns:
  > 0: bytes read
  == 0: connection closed (EOF)
  < 0: error (check errno)

HttpContainer::read() returns:
  > 0: bytes read successfully
  == 0: no data available yet OR all content read
       (caller should check bytes_read vs content_length to distinguish)
  < 0: error or connection closed (caller should EXIT)
       HTTP_ERROR_CONNECTION_CLOSED (-1) = connection closed prematurely
       other negative values = platform-specific errors
```

### Platform-specific implementation:

**ESP-IDF (blocking mode):**
- Uses blocking `esp_http_client_read()` calls
- Returns 0 only when all content has been read (via early check)
- Maps `esp_http_client_read() == 0` (EOF before content_length) → `HTTP_ERROR_CONNECTION_CLOSED`
- Added guard against double-cleanup in `end()` to fix crash on OTA failure

**Arduino (non-blocking mode):**
- Use `stream->connected()` to distinguish "no data yet" from "connection closed"
- When `available() == 0 && !connected()` → `HTTP_ERROR_CONNECTION_CLOSED`
- When `available() == 0 && connected()` → `0` (no data yet)

### Helper functions added:

- `HTTP_ERROR_CONNECTION_CLOSED` constant (-1) for connection closed error
- `HttpReadLoopResult` enum and `http_read_loop_result()` for manual loops with per-chunk processing
- `HttpReadResult` struct and `http_read_fully()` for simple buffer reads

### Documentation added:

All code is heavily documented to warn developers about the non-BSD socket semantics:
- Block comment at top of `http_request.h` explaining the difference
- Method documentation for `HttpContainer::read()` with WARNING
- Comments in both implementation files explaining the mapping
- Reminder comments at all call sites pointing to documentation

## Changes

- `http_request.h`:
  - Added block comment documenting non-BSD socket semantics
  - Added `HTTP_ERROR_CONNECTION_CLOSED` constant with documentation
  - Added helper enums/structs/functions (`HttpReadStatus`, `HttpReadResult`, `HttpReadLoopResult`, `http_read_loop_result()`, `http_read_fully()`)
  - Added `get_timeout()` getter
  - Fixed `HttpRequestSendAction` to use helper with documentation
- `http_request_idf.cpp`:
  - Uses blocking mode (no async)
  - Normalize return values with full documentation
  - Added guard against double-cleanup in `end()` to fix crash on OTA failure
- `http_request_arduino.cpp`: Use `connected()` to detect premature close with full documentation
- `ota_http_request.cpp`: Use helpers with reminder comment about semantics
- `http_request_update.cpp`:
  - Use `http_read_fully()` helper
  - Fixed UPDATE_RETURN macro for clang-tidy (added `__builtin_unreachable()`)
- `esp32_hosted_update.cpp`: Use `http_read_loop_result()` helper with reminder comments

## Testing

Tested on real hardware:

**ESP8266 Arduino:**
- ✅ Normal OTA - 12 seconds, MD5 verified, successful
- ✅ Slow OTA (1KB/s) - 542 seconds, successful
- ✅ Disconnect detection - Error detected and reported properly

**ESP32-S3 IDF:**
- ✅ Disconnect detection - Immediate error detection with `-1` return
- ✅ Manifest parsing working

## Types of changes

- [x] Bugfix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] Developer breaking change (an API change that could break external components)
- [ ] Code quality improvements to existing code or addition of tests
- [ ] Other

**Related issue or feature (if applicable):**

- fixes https://github.com/esphome/esphome/issues/13424
- fixes https://github.com/esphome/esphome/issues/13255

**Pull request in [esphome-docs](https://github.com/esphome/esphome-docs) with documentation (if applicable):**

- N/A (no user-facing changes)

## Test Environment

- [ ] ESP32
- [x] ESP32 IDF
- [x] ESP8266
- [ ] RP2040
- [ ] BK72xx
- [ ] RTL87xx
- [ ] LN882x
- [ ] nRF52840

## Example entry for `config.yaml`:

```yaml
# Existing configs will work - no changes needed
http_request:
  timeout: 10s

ota:
  - platform: http_request
```

## Checklist:
  - [x] The code change is tested and works locally.
  - [ ] Tests have been added to verify that the new code works (under `tests/` folder).

If user exposed functionality or configuration variables are added/changed:
  - [ ] Documentation added/updated in [esphome-docs](https://github.com/esphome/esphome-docs).

### CODE REVIEW

File: esphome/components/http_request/update/http_request_update.cpp [hunk 1]
```diff
@@ -70,19 +70,21 @@ void HttpRequestUpdate::update_task(void *params) {
...
+                                     this_update->request_parent_->get_timeout());
+  if (read_result.status != HttpReadStatus::OK) {
+    if (read_result.status == HttpReadStatus::TIMEOUT) {
+      ESP_LOGE(TAG, "Timeout reading manifest");
+    } else {
+      ESP_LOGE(TAG, "Error reading manifest: %d", read_result.error_code);
     }
-
-    read_index += read_bytes;
+    // Defer to main loop to avoid race condition on component_state_ read-modify-write
```
[the remark this answers is not in the document]
Comment (bdraco) [reply esphome/components/http_request/update/http_request_update.cpp:86]: was already fixed in 81df19dd4b8df5b058ea5127ecba794f1c6f766c but your review started before it was pushed

**Comment by bdraco** [comment]
[firmware_test_server.zip](https://github.com/user-attachments/files/24782186/firmware_test_server.zip)

aiohttp server + test config -- change the ip to your local ip

**Comment by bdraco** [comment]
fixed some bugs in the test server
[firmare_test_server_v2.zip](https://github.com/user-attachments/files/24782272/firmare_test_server_v2.zip)

**Comment by bdraco** [comment]
testing matrix

- [x] esp8266 check for updates
- [x] esp8266 disconnect in middle of ota  - Error detected and reported properly       
- [x] esp8266 very slow update 1024 bytes at a time   - 542 seconds, successful     
- [x] esp8266 normal http server - 12 seconds, successful  
- [x] esp32 check for updates
- [x] esp32 disconnect in middle of ota [13:25:06.279][V][esp-idf:000]: W (74661) HTTP_CLIENT: esp_transport_read returned:-1 and errno:128 
- [x] esp32 very slow update 1024 bytes at a time
- [x] esp32 normal http server - 15 sec, success

**Comment by bdraco** [comment]
Screenshot 2026-01-21 at 1 28 35 PM

**Comment by bdraco** [comment]
test with s3

[firmware_server_esp8266_esp32s3.zip](https://github.com/user-attachments/files/24782474/firmware_server_esp8266_esp32s3.zip)

**Comment by bdraco** [comment]
to test with s3

```
 python test_http_ota_server.py .esphome/build/test-http-ota-s3/.pioenvs/test-http-ota-s3/firmware.ota.bin 
```

**Comment by bdraco** [comment]
This is much larger than I would normally like to put in a patch release, but with the mismatched semantics it was never going to be a small targeted fix.

File: esphome/components/http_request/http_request_idf.cpp [hunk 2]
```diff
@@ -209,26 +210,68 @@ std::shared_ptr<HttpContainer> HttpRequestIDF::perform(const std::string &url, c
...
+//   > 0: bytes read
+//   0: no data yet, retry            <-- NOTE: 0 means retry, NOT EOF!
+//   < 0: error/connection closed     <-- connection closed returns -1, not 0
 int HttpContainerIDF::read(uint8_t *buf, size_t max_len) {
   const uint32_t start = millis();
   watchdog::WatchdogManager wdm(this->parent_->get_watchdog_timeout());
 
+  // Check if we've already read all expected content
+  if (this->bytes_read_ >= this->content_length) {
+    this->duration_ms += (millis() - start);
```
Comment (swoboda1337) [inline esphome/components/http_request/http_request_idf.cpp]:
```suggestion
```

nit: we are returning right away, no reason to update duration_ms

Comment (bdraco) [reply esphome/components/http_request/http_request_idf.cpp]: 133cf0be1eb2c8e8ef65bbce32a5a5fed8bd2398

**Comment by bdraco** [comment]
bool is_async[](https://docs.espressif.com/projects/esp-idf/en/stable/esp32/api-reference/protocols/esp_http_client.html#_CPPv4N24esp_http_client_config_t8is_asyncE)
Set asynchronous mode, only supported with HTTPS for now

**Review by swoboda1337 — APPROVED** [review]

**Comment by bdraco** [comment]
retest is good
[16:14:32.169][D][update:018]:   Latest Version: 2099.1.0
[16:14:32.170][D][update:021]:   Firmware URL: http://192.168.106.109:8000/firmware.bin
[16:14:32.172][D][update:024]:   Title: Test HTTP OTA
[16:14:32.174][D][update:026]:   Summary: Test OTA update
[16:14:32.174][D][update:033]:   Progress: 100%
[16:14:32.177][I][http_request.ota:175]: Done in 963 seconds
[16:14:32.623][I][http_request.ota:203]: Update complete
[16:14:32.624][D][main:260]: OTA update complete!
[16:14:32.635][I][app:258]: Rebooting safely
[16:14:32.691][V][esp32.preferences:126]: Saving 1 items...
[16:14:32.699][V][esp32.preferences:140]: sync: key: 233825507, len: 4
[16:14:32.701][D][esp32.preferences:155]: Writing 1 items: 0 cached, 1 written, 0 failed
[16:14:32.772][V][api:192]: Remove connection Home Assistant 2026.2.0.dev0
[16:14:32.773][W][component:389]: api set Warning flag: unspecified
[16:14:32.878]ESP-ROM:esp32s3-20210327
[16:14:32.879]Build:Mar 27 2021

**Comment by bdraco** [comment]
retest on esp8266 is good

**Comment by bdraco** [comment]
thanks
