### PR TITLE
[interval] Fix startup behaviour

### LINKED ISSUE #9521: interval will not be executed at startup anymore
### The problem

Since 58fe8b39b20c8fe9767107a6136ca30873b82056 `platform: interval` scripts will not be executed at startup anymore.

The first execution will occur after a random delay between 0 and halve of the interval and therefore the issue is only noticeable with configurations using a high interval. `startup_delay` will be added additionally onto the random offset.

I can workaround this issue, by moving the interval into a script and calling this script with `script.execute` in the interval and in on_boot. But this is an update in behavior to previous versions and in #5327 it was explicitly said, that the first execution of an interval should be executed pretty soon after startup.

### Which version of ESPHome has the issue?

2025.4.0

### What type of installation are you using?

pip

### What platform are you using?

ESP8266

### Component causing the issue

interval

### YAML Config

```yaml
interval:
  - interval: 10min
    startup_delay: 10s
    then:
      - logger.log: "Interval"
```

### PR DESCRIPTION
**Pull request by clydebarrow**
# What does this implement/fix?

A previous change to the scheduler changed the behaviour of `interval:` triggers.

Earlier, the first execution of the trigger happened more-or-less immediately, then
the next execution happened at a time somewhere between 0 and half the update interval, then
subsequent executions happened after every `update_interval`.

After the previous PR this changed so that the first execution did not happen until after a random delay up to half the update interval - see #9521.

New behaviour with this PR is to run the first execution after a randomised short delay, being the lesser of half the update interval and 5s. Then each subsequent execution will be as close as possible to the update interval after the previous one.

This prevents a rush of executions at startup, but comes close to the expectation that the trigger will be called immediately then every update interval.

## Types of changes

- [x] Bugfix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] Code quality improvements to existing code or addition of tests
- [ ] Other

**Related issue or feature (if applicable):**

- fixes #9521 

**Pull request in [esphome-docs](https://github.com/esphome/esphome-docs) with documentation (if applicable):**

- esphome/esphome-docs#<esphome-docs PR number goes here>

## Test Environment

- [ ] ESP32
- [ ] ESP32 IDF
- [ ] ESP8266
- [ ] RP2040
- [ ] BK72xx
- [ ] RTL87xx
- [ ] nRF52840
- [x] host

## Example entry for `config.yaml`:

```yaml
# Example config.yaml

```

## Checklist:
  - [x] The code change is tested and works locally.
  - [ ] Tests have been added to verify that the new code works (under `tests/` folder).

If user exposed functionality or configuration variables are added/changed:
  - [ ] Documentation added/updated in [esphome-docs](https://github.com/esphome/esphome-docs).

### CODE REVIEW

File: esphome/core/scheduler.cpp [hunk 1]
```diff
@@ -100,9 +100,11 @@ void HOT Scheduler::set_timer_common_(Component *component, SchedulerItem::Type
   // Type-specific setup
   if (type == SchedulerItem::INTERVAL) {
     item->interval = delay;
-    // Calculate random offset (0 to interval/2)
-    uint32_t offset = (delay != 0) ? (random_uint32() % delay) / 2 : 0;
+    // first execution happens immediately after a random smallish offset
+    // Calculate random offset (0 to min(interval/2, 5s))
+    uint32_t offset = std::min(delay / 2, 5000u) * random_float();
```
Comment (clydebarrow) [inline esphome/core/scheduler.cpp:105]:
```suggestion
    uint32_t offset = std::min(delay / 2, 5000ul) * random_float();
```

**Comment by bdraco** [comment]
I haven't figured out the root cause of the scheduler test failure, but if you re-run it, it will likely pass.  I'm hit a wall investigating it in https://github.com/esphome/esphome/pull/9788 but I'll keep trying

File: esphome/core/component.cpp [hunk 2]
```diff
@@ -373,11 +373,10 @@ bool Component::has_overridden_loop() const {
 PollingComponent::PollingComponent(uint32_t update_interval) : update_interval_(update_interval) {}
 
 void PollingComponent::call_setup() {
+  // init the poller before calling setup, allowing setup to cancel it if desired
+  this->start_poller();
   // Let the polling component subclass setup their HW.
   this->setup();
-
-  // init the poller
-  this->start_poller();
```
Comment (bdraco) [inline esphome/core/component.cpp:380]: While this change seems fine, I'd be worried about putting it in a patch release as there could be side effects we can't predict. I'd rather it go through beta (at least the audience size is a bit bigger even if beta doesn't catch much right now).

**Comment by bdraco** [comment]
+1 on the implementation, but I don't think its a critical enough bug (and there are workarounds available) to take the back-port risk on the timing change.

✅ from me if the milestone is dropped

File: esphome/core/component.cpp (hunk 2 above)
Comment (clydebarrow) [reply esphome/core/component.cpp:380]: Given that this and all the component callbacks happen on the single loop thread the `update()` call can't happen until the function returns, so the only possible difference it could make is a slight timing change for the first update call relative to setup.

But I'm fine with leaving it until the next beta.

**Review by bdraco — APPROVED** [review]
