### PR TITLE
Fix bluetooth race when disconnect called while still connecting

### LINKED ISSUE #6701: BLE client "DISCONNECTING" state is terminal and leaks btproxy connections
### The problem

It looks like `disconnect()` may mark a Bluetooth connection as `DISCONNECTING` if some conditions are not satisfied, which is a terminal state in this FSM and makes connection unusable.

Relevant code:

https://github.com/esphome/esphome/blob/b454f63b3604d766abb038fe3c0f79dc20ab5cad/esphome/components/esp32_ble_client/ble_client_base.cpp#L125-L142

As a result, connection becomes unusable.  Repeat this twice, and esp32 is out of connection slots and Bluetooth is dead on that one.

### Which version of ESPHome has the issue?

2024.12.2

### What type of installation are you using?

pip

### Which version of Home Assistant has the issue?

2025.1.3

### What platform are you using?

ESP32-IDF

### Board

Olimex PoE

### Component causing the issue

bluetooth_proxy

### YAML Config

```yaml
esp32:
  board: esp32-poe
  framework:
    type: esp-idf

esp32_ble_tracker:
  scan_parameters:
    interval: 1100ms
    window: 1100ms
    active: true

bluetooth_proxy:
  id: btproxy
  active: true

# The following is likely irrelevant but included for posterity:

api:
  encryption:
    key: !secret api_encryption_key

status_led:
  pin: GPIO2

ethernet:
  type: LAN8720
  mdc_pin: GPIO23
  mdio_pin: GPIO18
  clk_mode: GPIO17_OUT
  phy_addr: 0
  power_pin: GPIO12
  domain: ""

text_sensor:
- platform: ethernet_info
  ip_address:
    name: "Device IP (Ethernet)"
  mac_address:
    name: "Device MAC (Ethernet)"

logger:

sensor:
- platform: uptime
  name: "Uptime"

button:
- platform: restart
  name: "ESP chip restart"
  entity_category: diagnostic

ota:
  - platform: esphome
    password: !secret ota_password
```

### Anything in the logs that might be useful for us?

```txt
2025-01-21T11:56:22.749711+00:00 btproxy-c257a8 btproxy-c257a8[esp32_ble_client] [D][esp32_ble_client:171]: [0] [04:EE:03:BC:C5:2F] ESP_GATTC_DISCONNECT_EVT, reason 256
2025-01-21T11:56:22.766376+00:00 btproxy-c257a8 btproxy-c257a8[esp32_ble_tracker] [D][esp32_ble_tracker:273]: Starting scan...
2025-01-21T11:56:22.910660+00:00 btproxy-c257a8 btproxy-c257a8[esp-idf] [D][esp-idf:000]#033[1;31m[BTU_TASK]#033[0;36m: #033[0;33mW (68318623) BT_L2CAP: L2CAP - LE - cannot start new connection at conn st: 1#033[0m
2025-01-21T11:56:23.337690+00:00 btproxy-c257a8 btproxy-c257a8[esp-idf] [D][esp-idf:000]#033[1;31m[BTU_TASK]#033[0;36m: #033[0;31mE (68319049) BT_L2CAP: L2CAP got BLE scanner conn_comp in bad state: 0#033[0m
2025-01-21T11:56:23.424043+00:00 btproxy-c257a8 btproxy-c257a8[esp-idf] [D][esp-idf:000]#033[1;31m[BTU_TASK]#033[0;36m: #033[0;33mW (68319135) BT_HCI: hcif disc complete: hdl 0x0, rsn 0x3e#033[0m
2025-01-21T11:56:42.875170+00:00 btproxy-c257a8 btproxy-c257a8[esp32_ble_client] [I][esp32_ble_client:084]: [0] [80:6F:B0:A9:EC:25] Disconnecting.
2025-01-21T11:56:42.887162+00:00 btproxy-c257a8 btproxy-c257a8[esp-idf] [D][esp-idf:000]#033[1;31m[BTU_TASK]#033[0;36m: #033[0;33mW (68338599) BT_L2CAP: L2CAP - LE - cannot start new connection at conn st: 1#033[0m
2025-01-21T11:57:03.123322+00:00 btproxy-c257a8 btproxy-c257a8[bluetooth_proxy] [W][bluetooth_proxy:272]: [0] [80:6F:B0:A9:EC:25] Connection request ignored, device is disconnecting
2025-01-21T11:57:43.377583+00:00 btproxy-c257a8 btproxy-c257a8[bluetooth_proxy] [W][bluetooth_proxy:272]: [0] [80:6F:B0:A9:EC:25] Connection request ignored, device is disconnecting

...
```

### Additional information

The problem was discovered following my post:

https://community.home-assistant.io/t/bt-proxy-btproxy-suddenly-stops-discovering-debugging/832665

Looks like related problems have been seen before:

https://community.home-assistant.io/t/esphome-bluetooth-ble-proxy-stops-working/649181/14

### PR DESCRIPTION
**Pull request by bdraco**
# What does this implement/fix?

There is a race where we would try to disconnect before the connection callback which meant the `conn_id_` would be `0xFFFF` so we would try to disconnect the "unset" connection id value of 0xFFFF and proceed to set the state to disconnecting.

Later the callback to set `conn_id_` would get delivered and set the `conn_id_` to the correct value, however this meant the client would be stuck in the disconnecting state forever and the connection left open.

To fix this, when disconnect is requested and we are still in the process of connecting, we set `this->want_disconnect_` to `true`.  When the client gets a `ESP_GATTC_OPEN_EVT` and `this->want_disconnect_` is true, we now call `esp_ble_gattc_close` via `unconditional_disconnect` to disconnect the connection and set the client state to idle. 

Fix can be tested with 
```yaml
external_components:
  - source: github://pr#8297
    components: [ esp32_ble_client, esp32_ble_tracker ]
    refresh: 0s
```

```
[18:40:21][D][sensor:093]: 'Ethernet Uptime': Sending state 105.10000 s with 0 decimals of accuracy
[18:40:22][W][esp32_ble_client:129]: [1] [10:76:36:14:93:76] Disconnecting before connected
[18:40:22][D][esp32_ble_tracker:115]: connecting: 0, discovered: 0, searching: 0, disconnecting: 1
[18:40:24][D][esp32_ble_client:169]: [0] [BC:14:EF:7B:22:2A] ESP_GATTC_NOTIFY_EVT
[18:40:24][D][esp32_ble_client:169]: [0] [BC:14:EF:7B:22:2A] ESP_GATTC_WRITE_CHAR_EVT
```

## Types of changes

- [x] Bugfix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] Code quality improvements to existing code or addition of tests
- [ ] Other

**Related issue or feature (if applicable):**

- fixes https://github.com/esphome/issues/issues/6701

**Pull request in [esphome-docs](https://github.com/esphome/esphome-docs) with documentation (if applicable):**

- esphome/esphome-docs#<esphome-docs PR number goes here>

## Test Environment

- [ ] ESP32
- [x] ESP32 IDF
- [ ] ESP8266
- [ ] RP2040
- [ ] BK72xx
- [ ] RTL87xx

## Example entry for `config.yaml`:

```yaml
# Example config.yaml

```

## Checklist:
  - [x] The code change is tested and works locally.
  - [ ] Tests have been added to verify that the new code works (under `tests/` folder).

If user exposed functionality or configuration variables are added/changed:
  - [ ] Documentation added/updated in [esphome-docs](https://github.com/esphome/esphome-docs).

### CODE REVIEW

File: esphome/components/esp32_ble_client/ble_client_base.cpp [hunk 1]
```diff
@@ -125,6 +125,10 @@ esp_err_t BLEClientBase::pair() { return esp_ble_set_encryption(this->remote_bda
 void BLEClientBase::disconnect() {
   if (this->state_ == espbt::ClientState::IDLE || this->state_ == espbt::ClientState::DISCONNECTING)
     return;
+  if (this->conn_id_ == UNSET_CONN_ID) {
+    ESP_LOGW(TAG, "[%d] [%s] Disconnecting before connected", this->connection_index_, this->address_str_.c_str());
+    return;
+  }
```
Comment (bdraco) [inline esphome/components/esp32_ble_client/ble_client_base.cpp]: This doesn't really fix the issue, instead we need to call disconnect as soon as the connection callback comes in ....

File: esphome/components/esp32_ble_client/ble_client_base.cpp [hunk 2]
```diff
@@ -209,6 +232,13 @@ bool BLEClientBase::gattc_event_handler(esp_gattc_cb_event_t event, esp_gatt_if_
       if (!this->check_addr(param->connect.remote_bda))
         return false;
       this->log_event_("ESP_GATTC_CONNECT_EVT");
+      if (this->state_ == espbt::ClientState::DISCONNECTING) {
+        // Disconnect was requested before after connecting started,
```
Comment (bdraco) [inline esphome/components/esp32_ble_client/ble_client_base.cpp]:
```suggestion
        // Disconnect was requested after connecting started,
```

File: esphome/components/esp32_ble_client/ble_client_base.cpp [hunk 3]
```diff
@@ -190,6 +205,14 @@ bool BLEClientBase::gattc_event_handler(esp_gattc_cb_event_t event, esp_gatt_if_
         this->set_state(espbt::ClientState::IDLE);
         break;
       }
+      if (this->state_ == espbt::ClientState::DISCONNECTING) {
+        // Disconnect was requested before after connecting started,
```
Comment (bdraco) [inline esphome/components/esp32_ble_client/ble_client_base.cpp]:
```suggestion
        // Disconnect was requested after connecting started,
```

File: esphome/components/esp32_ble_client/ble_client_base.cpp [hunk 4]
```diff
@@ -125,15 +125,30 @@ esp_err_t BLEClientBase::pair() { return esp_ble_set_encryption(this->remote_bda
...
+  // Disconnect without checking the state.
   ESP_LOGI(TAG, "[%d] [%s] Disconnecting.", this->connection_index_, this->address_str_.c_str());
+  if (this->conn_id_ == UNSET_CONN_ID) {
+    ESP_LOGE(TAG, "[%d] [%s] No connection ID set, cannot disconnect.", this->connection_index_,
+             this->address_str_.c_str());
+    return;
+  }
   auto err = esp_ble_gattc_close(this->gattc_if_, this->conn_id_);
   if (err != ESP_OK) {
     ESP_LOGW(TAG, "[%d] [%s] esp_ble_gattc_close error, err=%d", this->connection_index_, this->address_str_.c_str(),
```
Comment (bdraco) [inline esphome/components/esp32_ble_client/ble_client_base.cpp]: We should upgrade to error logging as this is fatal as it means we are likely in a bad state already and should probably reboot here.... but too much to change in a patch/fix release

**Comment by bdraco** [comment]
latest push was logging and comment changes only to make future issue reports easily to track down. no need to update again

**Review by jesserockz — APPROVED** [review]

**Comment by tomaszduda23** [comment]
@bdraco I just used this for 90 min. After that this happened:
```
[00:03:55][I][app:100]: ESPHome version 2025.2.0 compiled on Feb 25 2025, 22:35:34
[00:03:55][C][bluetooth_proxy:091]: Bluetooth Proxy:
[00:03:55][C][bluetooth_proxy:092]:   Active: NO
[00:03:55][C][bluetooth_proxy:093]:   Connections: 0
[00:03:55][C][bluetooth_proxy:094]:   Raw advertisements: YES
[00:03:55][C][display.pvvx_mithermometer:011]: PVVX MiThermometer display:
[00:03:55][C][display.pvvx_mithermometer:012]:   MAC address           : 
[00:03:55][C][display.pvvx_mithermometer:013]:   Service UUID          : 00001F10-0000-1000-8000-00805F9B34FB
[00:03:55][C][display.pvvx_mithermometer:014]:   Characteristic UUID   : 00001F1F-0000-1000-8000-00805F9B34FB
[00:03:55][C][display.pvvx_mithermometer:015]:   Auto clear            : YES
[00:03:55][C][display.pvvx_mithermometer:017]:   Set time on connection: YES
[00:03:55][C][display.pvvx_mithermometer:019]:   Disconnect delay      : 30000ms
[00:03:55][C][display.pvvx_mithermometer:020]:   Update Interval: 86400.0s
[00:03:55][C][homeassistant.time:010]: Home Assistant Time:nges
[00:03:55][C][esp32_ble:418]: ESP32 BLE:
[00:03:55][C][esp32_ble:420]:   MAC address: 
[00:03:55][C][esp32_ble:421]:   IO Capability: keyboard_only
[00:03:55][C][esp32_ble_tracker:677]: BLE Tracker:
[00:03:55][C][esp32_ble_tracker:678]:   Scan Duration: 300 s
[00:03:55][C][esp32_ble_tracker:679]:   Scan Interval: 1100.0 ms
[00:03:55][C][esp32_ble_tracker:680]:   Scan Window: 1100.0 ms
[00:03:55][C][esp32_ble_tracker:681]:   Scan Type: ACTIVE
[00:03:55][C][esp32_ble_tracker:682]:   Continuous Scanning: YES
[00:03:55][C][esp32_ble_tracker:683]:   Scanner Idle: NO
[00:03:55][C][esp32_ble_tracker:684]:   Scan End: NO
[00:03:55][C][esp32_ble_tracker:686]:   Connecting: 0, discovered: 0, searching: 0, disconnecting: 0
[00:03:55][C][ble_client:027]: BLE Client:
[00:03:55][C][esp32_ble_client:048]:   Address: 
[00:03:55][C][esp32_ble_client:049]:   Auto-Connect: TRUE
[00:03:55][C][esp32_ble_client:083]:   State: IDLE
[00:04:25][V][sensor:043]: 'esp-livingroom-sensors_uptime': Received new state 5259.028809
[00:04:25][D][sensor:094]: 'esp-livingroom-sensors_uptime': Sending state 5259.02881 s with 0 decimals of accuracy
[00:05:25][V][sensor:043]: 'esp-livingroom-sensors_uptime': Received new state 5319.025879
[00:05:25][D][sensor:094]: 'esp-livingroom-sensors_uptime': Sending state 5319.02588 s with 0 decimals of accuracy
[00:05:34][D][time:051]: Synchronized time: 2025-02-26 00:05:34
[00:05:34][D][time:051]: Synchronized time: 2025-02-26 00:05:34
[00:06:25][V][sensor:043]: 'esp-livingroom-sensors_uptime': Received new state 5379.025879
[00:06:25][D][sensor:094]: 'esp-livingroom-sensors_uptime': Sending state 5379.02588 s with 0 decimals of accuracy
[00:07:12][E][esp32_ble_tracker:296]: ESP-IDF BLE scan never terminated, rebooting to restore BLE stack...
[00:07:12][I][app:125]: Forcing a reboot...
```

**Comment by bdraco** [comment]
@tomaszduda23 Would you please turn on debug logging for `esp32_ble_tracker`, `esp32_ble_client`, and open an issue report?  There aren't any changes to the scanning code here so I can't see how this fix would cause the scanner to never terminate, hopefully the logs will give a clue.

**Comment by tomaszduda23** [comment]
> @tomaszduda23 Would you please turn on debug logging for `esp32_ble_tracker`, `esp32_ble_client`, and open an issue report? There aren't any changes to the scanning code here so I can't see how this fix would cause the scanner to never terminate, hopefully the logs will give a clue.

I'm running debug logs already. There was no events at all. It might be still that problem https://github.com/esphome/issues/issues/5119

**Comment by bdraco** [comment]
> > @tomaszduda23 Would you please turn on debug logging for `esp32_ble_tracker`, `esp32_ble_client`, and open an issue report? There aren't any changes to the scanning code here so I can't see how this fix would cause the scanner to never terminate, hopefully the logs will give a clue.
> 
> I'm running debug logs already. There was no events at all. It might be still that problem [esphome/issues#5119](https://github.com/esphome/issues/issues/5119)

I agree that its likely https://github.com/esphome/issues/issues/5119

I think that problem might be solved by https://github.com/esphome/esphome/pull/8328
