### PR TITLE
Fix LEDC resolution calculation on ESP32-C3/S2/S3

### LINKED ISSUE #2751: ledc_output resolution calculation not compatible with low frequencies
### The problem

The `ledc_bit_depth_for_frequency()` method calculates a resolution that is incompatible with low frequencies such as 100Mhz on devices that don't support high-speed mode (esp32-c3, etc). I added some debug code to show the values being calculated and the ESPIDF error that is generated when the channel is being configured.  In this example, I'm using a frequency of 100Hz for controlling a 24V 2-pin fan via a L293D half-H driver IC:

```
[07:26:44][I][ledc.output:036]: LEDC max_div_number is 4095.996094
[07:26:44][I][ledc.output:043]: LEDC min_frequency calculated as 0.018626
[07:26:44][I][ledc.output:045]: LEDC max_frequency calculated as 76.293945
[07:26:44][I][ledc.output:036]: LEDC max_div_number is 4095.996094
[07:26:44][I][ledc.output:043]: LEDC min_frequency calculated as 0.037253
[07:26:44][I][ledc.output:045]: LEDC max_frequency calculated as 152.587891
[07:26:44][I][ledc.output:047]: LEDC bit depth calculated as 19
[07:26:44][D][esp-idf:000]: E (810) ledc: freq_hz=100 duty_resolution=19
```

Some general comments regarding resolution and channel limits specifically with respect to the ESP32-C3 according to [their docs](https://docs.espressif.com/projects/esp-idf/en/latest/esp32c3/api-reference/peripherals/ledc.html#ledc-api-supported-range-frequency-duty-resolution):

* max resolution is 14 bit -- not 20 as currently being used in the `ledc_bit_depth_for_frequency()` function
* max channels is 6  and not 8

Looking at other chips, here are some additional comments:

* esp32-s2: also limited to 14 bit resolution, but supports the full 8 channels
* esp32-s3: similar to the esp32-s3 where it's limited to 14 bits, but supports the full 8 channels

In all situations, `components/hal/include/hal/ledc_types.h` provides a LEDC_TIMER_BIT_MAX and LEDC_CHANNEL_MAX a references that we can use instead of hard coding it to 20. 

### Which version of ESPHome has the issue?

2021.12.0-dev

### What type of installation are you using?

pip

### Which version of Home Assistant has the issue?

_No response_

### What platform are you using?

ESP32-IDF

### Board

esp32-c3

### Component causing the issue

ledc_output

### Example YAML snippet

_No response_

### Anything in the logs that might be useful for us?

_No response_

### Additional information

_No response_

### PR DESCRIPTION
**Pull request by rsumner**
# What does this implement/fix? 

Fixes improper use of a 20-bit duty resolution, which is incompatible with C3, S2, and S3 chips.  In addition, frequencies below 100Mhz would not function properly, so a conditional was added to use a different divisor for those lower frequencies. Lastly, better error checking in setup() was added to properly detect, log, and set the proper warning flags when a resolution couldn't be automatically determined.

## Types of changes

* [X] Bugfix (non-breaking change which fixes an issue)
* [ ] New feature (non-breaking change which adds functionality)
* [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
* [ ] Other

**Related issue or feature (if applicable):** fixes [esphome/issues#2751](https://github.com/esphome/issues/issues/2751)

Includes fixes from pending pull request [esphome/pull##2791 ](https://github.com/esphome/esphome/pull/2791)

## Test Environment

* [X] ESP32
* [X] ESP32 IDF
* [ ] ESP8266

## Example entry for `config.yaml`:

```yaml
...
power_supply:
  - id: l293d_enable
    pin: 4

output:
  - platform: ledc
    power_supply: l293d_enable
    pin: 5
    id: fan1
    frequency: 10
    channel: 0

fan:
  - platform: speed
    output: fan1
    name: "Data Closet Fan 1"
```

## Checklist:

* [X] The code change is tested and works locally.
* [ ] Tests have been added to verify that the new code works (under tests/ folder).

### CODE REVIEW

File: esphome/components/ledc/ledc_output.cpp [hunk 1]
```diff
@@ -16,6 +16,7 @@ namespace ledc {
 static const char *const TAG = "ledc.output";
 
 #ifdef USE_ESP_IDF
+static const int MAX_RES_BITS = (LEDC_TIMER_BIT_MAX - 1);
```
Comment (oxan) [inline esphome/components/ledc/ledc_output.cpp]: Parentheses are superfluous:
```suggestion
static const int MAX_RES_BITS = LEDC_TIMER_BIT_MAX - 1;
```

**Review by oxan — APPROVED** [review]

**Comment by oxan** [comment]
Thanks for your contribution!
