### PR TITLE
Fix ethernet component hostname handling

### LINKED ISSUE #2184: Hostname always "espressif" when using Ethernet on ESP32
**Operating environment/Installation (Hass.io/Docker/pip/etc.):**

Hass.io

**ESP (ESP32/ESP8266, Board/Sonoff):**

ESP32 (WT32-ETH01)

**ESPHome version (latest production, beta, dev branch)**

ESPHome version v1.19.2

**Affected component:**

https://esphome.io/components/ethernet.html#ethernet-component

**Description of problem:**

When using ethernet, the hostname is not set correctly and is always "espressif" (instead of "esp32-test-ethernet" as defined in the example below). Therefore, communication between HA and the board does not work correctly. Accessing the board works only with "espressif" as hostname or directly via its IP. In the logs, it shows the correct hostname and no indication that it has failed to set it. When using wifi instead of ethernet everything works fine and the hostname is set correctly.

Here the DHCP Lease:
192.168.1.47	a8:03:2a:21:f3:dc		espressif		2021/06/23 09:29:02	2021/06/23 11:29:02	online	active

**Problem-relevant YAML-configuration entries:**
```yaml
substitutions:
  devicename: esp32-test-ethernet
  devicename_underscore: esp32_test_ethernet
  devicename_pretty: ESP32 Test Ethernet

esphome:
  name: $devicename
  platform: ESP32
  board: nodemcu-32s

# wifi:
#   ssid: !secret wifi_ssid
#   password: !secret wifi_password
#   domain: !secret mydomain
#   ap:
#     ssid: $devicename
#     password: !secret ap_password
    
ethernet:
  type: LAN8720
  mdc_pin: GPIO23
  mdio_pin: GPIO18
  clk_mode: GPIO0_IN
  phy_addr: 1
  power_pin: GPIO16
  domain: !secret mydomain

web_server:
  port: !secret web_server_port

logger:
  level: VERY_VERBOSE

api:
  password: !secret api_password

ota:
  password: !secret ota_password

sensor:
- platform: uptime
  name: $devicename_pretty Uptime
  update_interval: 60s

```

**Logs (if applicable):**

```

rst:0xc (SW_CPU_RESET),boot:0x13 (SPI_FAST_FLASH_BOOT)
configsip: 0, SPIWP:0xee
clk_drv:0x00,q_drv:0x00,d_drv:0x00,cs0_drv:0x00,hd_drv:0x00,wp_drv:0x00
mode:DIO, clock div:2
load:0x3fff0018,len:4
load:0x3fff001c,len:1044
load:0x40078000,len:8896
load:0x40080400,len:5828
entry 0x400806ac
[I][logger:170]: Log initialized
[VV][preferences:038]: LOAD 0: valid=YES, 0=0x00000000 1=0x0DEFE4E3 (Type=233825507, CRC=0x0DEFE4E3)
[C][ota:366]: There have been 0 suspected unsuccessful boot attempts.
[VV][preferences:051]: SAVE 0: 0=0x00000001 1=0x42F4583F (Type=233825507, CRC=0x42F4583F)
[I][app:029]: Running through setup()...
[V][app:030]: Sorting components by setup priority...
[VV][scheduler:057]: set_interval(name='update', interval=60000, offset=29679)
[C][ethernet:025]: Setting up Ethernet...
[VV][scheduler:152]: Running interval 'update' with interval=60000 last_execution=4294877678 (now=89)
[V][sensor:023]: 'ESP32 Test Ethernet Uptime': Received new state 0.089000
[D][sensor:117]: 'ESP32 Test Ethernet Uptime': Sending state 0.08900 s with 0 decimals of accuracy
[W][ethernet:043]: Connecting via ethernet failed! Re-connecting...
[D][WiFiGeneric.cpp:374] _eventCallback(): Event: 21 - ETH_START
[V][ethernet:109]: [Ethernet event] ETH started (num=21)
[D][WiFiGeneric.cpp:374] _eventCallback(): Event: 23 - ETH_CONNECTED
[V][ethernet:109]: [Ethernet event] ETH connected (num=23)
[D][WiFiGeneric.cpp:374] _eventCallback(): Event: 25 - ETH_GOT_IP
[D][WiFiGeneric.cpp:455] _eventCallback(): ETH IP: 192.168.1.47, MASK: 255.255.255.0, GW: 192.168.1.1
[V][ethernet:109]: [Ethernet event] ETH Got IP (num=25)
[I][ethernet:054]: Connected via Ethernet!
[C][ethernet:222]:   IP Address: 192.168.1.47
[C][ethernet:223]:   Hostname: 'esp32-test-ethernet'
[C][ethernet:224]:   Subnet: 255.255.255.0
[C][ethernet:225]:   Gateway: 192.168.1.1
[C][ethernet:236]:   DNS1: 192.168.1.1
[C][ethernet:237]:   DNS2: 0.0.0.0
[C][ethernet:240]:   MAC Address: A8:03:2A:21:F3:DC
[C][ethernet:241]:   Is Full Duplex: YES
[C][ethernet:242]:   Link Up: YES
[C][ethernet:243]:   Link Speed: 100
[C][web_server:073]: Setting up web server...
[VV][scheduler:057]: set_interval(name='', interval=10000, offset=2906)
[C][ota:029]: Over-The-Air Updates:
[C][ota:030]:   Address: 192.168.1.47:3232
[C][ota:032]:   Using Password.
[C][api:022]: Setting up Home Assistant API server...
[I][app:059]: setup() finished successfully!
[VV][scheduler:152]: Running interval '' with interval=10000 last_execution=9285 (now=22221)
[I][app:105]: ESPHome version 1.19.2 compiled on Jun 23 2021, 11:25:25
[C][uptime.sensor:030]: Uptime Sensor 'ESP32 Test Ethernet Uptime'
[C][uptime.sensor:030]:   State Class: ''
[C][uptime.sensor:030]:   Unit of Measurement: 's'
[C][uptime.sensor:030]:   Accuracy Decimals: 0
[C][uptime.sensor:030]:   Icon: 'mdi:timer-outline'
[V][uptime.sensor:030]:   Unique ID: 'a8032a21f3dc-uptime'
[C][logger:189]: Logger:
[C][logger:190]:   Level: VERY_VERBOSE
[C][logger:191]:   Log Baud Rate: 115200
[C][logger:192]:   Hardware UART: UART0
[C][ethernet:068]: Ethernet:
[C][ethernet:222]:   IP Address: 192.168.1.47
[C][ethernet:223]:   Hostname: 'esp32-test-ethernet'
[C][ethernet:224]:   Subnet: 255.255.255.0
[C][ethernet:225]:   Gateway: 192.168.1.1
[C][ethernet:236]:   DNS1: 192.168.1.1
[C][ethernet:237]:   DNS2: 0.0.0.0
[C][ethernet:240]:   MAC Address: A8:03:2A:21:F3:DC
[C][ethernet:241]:   Is Full Duplex: YES
[C][ethernet:242]:   Link Up: YES
[C][ethernet:243]:   Link Speed: 100
[C][ethernet:070]:   Power Pin: GPIO16 (Mode: OUTPUT)
[C][ethernet:071]:   MDC Pin: 23
[C][ethernet:072]:   MDIO Pin: 18
[C][ethernet:073]:   Type: LAN8720
[C][web_server:136]: Web Server:
[C][web_server:137]:   Address: 192.168.1.47:80
[C][ota:029]: Over-The-Air Updates:
[C][ota:030]:   Address: 192.168.1.47:3232
[C][ota:032]:   Using Password.
[C][api:095]: API Server:
[C][api:096]:   Address: 192.168.1.47:6053
[VV][api.service:192]: on_hello_request: HelloRequest {
  client_info: 'ESPHome v1.19.2'
}
[V][api.connection:628]: Hello from client: 'ESPHome v1.19.2 (192.168.1.220)'
[VV][api.service:012]: send_hello_response: HelloResponse {
  api_version_major: 1
  api_version_minor: 4
  server_info: 'esp32-test-ethernet (esphome v1.19.2)'
}
[VV][api.service:199]: on_connect_request: ConnectRequest {
  password: 'mPwdvvTOFRnDF'
}
[D][api.connection:644]: Client 'ESPHome v1.19.2 (192.168.1.220)' connected successfully!
[VV][api.service:016]: send_connect_response: ConnectResponse {
  invalid_password: NO
}
[VV][api.service:255]: on_subscribe_logs_request: SubscribeLogsRequest {
  level: UNKNOWN
  dump_config: YES
}
[I][app:105]: ESPHome version 1.19.2 compiled on Jun 23 2021, 11:25:25
[C][uptime.sensor:030]: Uptime Sensor 'ESP32 Test Ethernet Uptime'
[C][uptime.sensor:030]:   State Class: ''
[C][uptime.sensor:030]:   Unit of Measurement: 's'
[C][uptime.sensor:030]:   Accuracy Decimals: 0
[C][uptime.sensor:030]:   Icon: 'mdi:timer-outline'
[V][uptime.sensor:030]:   Unique ID: 'a8032a21f3dc-uptime'
[C][logger:189]: Logger:
[C][logger:190]:   Level: VERY_VERBOSE
[C][logger:191]:   Log Baud Rate: 115200
[C][logger:192]:   Hardware UART: UART0
[C][ethernet:068]: Ethernet:
[C][ethernet:222]:   IP Address: 192.168.1.47
[C][ethernet:223]:   Hostname: 'esp32-test-ethernet'
[C][ethernet:224]:   Subnet: 255.255.255.0
[C][ethernet:225]:   Gateway: 192.168.1.1
[C][ethernet:236]:   DNS1: 192.168.1.1
[C][ethernet:237]:   DNS2: 0.0.0.0
[C][ethernet:240]:   MAC Address: A8:03:2A:21:F3:DC
[C][ethernet:241]:   Is Full Duplex: YES
[C][ethernet:242]:   Link Up: YES
[C][ethernet:243]:   Link Speed: 100
[C][ethernet:070]:   Power Pin: GPIO16 (Mode: OUTPUT)
[C][ethernet:071]:   MDC Pin: 23
[C][ethernet:072]:   MDIO Pin: 18
[C][ethernet:073]:   Type: LAN8720
[C][web_server:136]: Web Server:
[C][web_server:137]:   Address: 192.168.1.47:80
[C][ota:029]: Over-The-Air Updates:
[C][ota:030]:   Address: 192.168.1.47:3232
[C][ota:032]:   Using Password.
[C][api:095]: API Server:
[C][api:096]:   Address: 192.168.1.47:6053
[VV][api.service:220]: on_ping_request: PingRequest {}
[VV][api.service:032]: send_ping_response: PingResponse {}
[VV][scheduler:152]: Running interval '' with interval=10000 last_execution=19285 (now=29285)
[VV][scheduler:152]: Running interval 'update' with interval=60000 last_execution=4294937678 (now=30385)
[V][sensor:023]: 'ESP32 Test Ethernet Uptime': Received new state 30.386999
[D][sensor:117]: 'ESP32 Test Ethernet Uptime': Sending state 30.38700 s with 0 decimals of accuracy
[VV][api.service:220]: on_ping_request: PingRequest {}
[VV][api.service:032]: send_ping_response: PingResponse {}
[VV][api.service:220]: on_ping_request: PingRequest {}
[VV][api.service:032]: send_ping_response: PingResponse {}
[VV][scheduler:152]: Running interval '' with interval=10000 last_execution=29285 (now=39285)
[VV][api.service:220]: on_ping_request: PingRequest {}
[VV][api.service:032]: send_ping_response: PingResponse {}
[VV][api.service:220]: on_ping_request: PingRequest {}
[VV][api.service:032]: send_ping_response: PingResponse {}
[VV][scheduler:152]: Running interval '' with interval=10000 last_execution=39285 (now=49285)
[VV][api.service:220]: on_ping_request: PingRequest {}
[VV][api.service:032]: send_ping_response: PingResponse {}
[VV][api.service:220]: on_ping_request: PingRequest {}
[VV][api.service:032]: send_ping_response: PingResponse {}
[VV][scheduler:152]: Running interval '' with interval=10000 last_execution=49285 (now=59285)
[VV][api.service:220]: on_ping_request: PingRequest {}
[VV][api.service:032]: send_ping_response: PingResponse {}

```

**Additional information and things you've tried:**

### PR DESCRIPTION
**Pull request by flacjacket**
# What does this implement/fix? 

Previously, the ethernet component would try to setup and connect before
`esp_eth_enable` is called, which can be called right after
`esp_eth_init` is called.  The rest of the logic in `start_connect_`,
for example setting up the hostname and dhcp information, should wait
until after the ETH_START event is received.  This would result in the
first connection attempt always failing (as `esp_eth_enable` would only
be called on the second run through `start_connect_`) and once
connected, would fail to set the hostname correctly.

This PR correctly runs `esp_eth_enable` and `esp_eth_init` in the
`setup` for the component.  This allows the ethernet component to
connect on the first attempt, saving 15 sec (the connection timeout) on
component startup.

This PR adds some additional state tracking to the ethernet component to
be able to know when the start event has been received and start the
connection once the eth_start event is received, and also track the
connection status through this state machine.  This makes the state more
explicit, rather than using `last_connected_` and `connected_` to track
state.

With this PR, because of the now correct setup, the hostname is
correctly set.  This could have been seen earlier by error checking the
return from `tcpip_adapter_set_hostname`, as this would fail on the
first call, before the esp_eth_enable.  Error checking is added to the
call to set the hostname, to catch further problems with this.

## Types of changes

- [X] Bugfix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] Other

**Related issue or feature (if applicable):**

Fixes esphome/issues#2184

**Pull request in [esphome-docs](https://github.com/esphome/esphome-docs) with documentation (if applicable):** N/A

## Test Environment

- [X] ESP32
- [ ] ESP8266

## Example entry for `config.yaml`:
```yaml
esphome:
  name: testdevice
  platform: ESP32
  board: wesp32

ethernet:
  type: LAN8720
  mdc_pin: GPIO16
  mdio_pin: GPIO17
  clk_mode: GPIO0_IN
  domain: !secret my_domain

logger:

api:

ota:
  password: !secret ota_password
```

## Checklist:
  - [X] The code change is tested and works locally.
  - [ ] Tests have been added to verify that the new code works (under `tests/` folder).

Ran test yaml on wesp32 device, saw that device would connect correctly
on the first attempt without requiring a re-try on the ethernet
connection, and once connected, had the correct hostname. Disconnected
and re-connected the ethernet cable to observe the state correctly
transition between connecting and connected.
  
If user exposed functionality or configuration variables are added/changed:
  - [ ] Documentation added/updated in [esphome-docs](https://github.com/esphome/esphome-docs).

### CODE REVIEW

File: esphome/components/ethernet/ethernet_component.h [hunk 1]
```diff
@@ -26,6 +26,12 @@ struct ManualIP {
   IPAddress dns2;  ///< The second DNS server. 0.0.0.0 for default.
 };
 
+enum class EthernetComponentState {
+  Stopped,
+  Connecting,
+  Connected,
```
Comment (OttoWinter) [inline esphome/components/ethernet/ethernet_component.h]:
```suggestion
  STOPPED,
  CONNECTING,
  CONNECTED,
```

In ESPHome we use UPPER_SNAKE_CASE for enum constants (I think `clang-tidy` didn't detect it automatically here because it skips all ESP32-only files)

Comment (flacjacket) [reply esphome/components/ethernet/ethernet_component.h]: Got it, thanks for the fix here.

File: esphome/components/ethernet/ethernet_component.cpp [hunk 2]
```diff
@@ -36,38 +43,83 @@ void EthernetComponent::setup() {
...
+        this->state_ = EthernetComponentState::STOPPED;
+      } else if (this->connected_) {
+        // connection established
+        ESP_LOGI(TAG, "Connected via Ethernet!");
+        this->state_ = EthernetComponentState::CONNECTED;
+
+        this->dump_connect_params_();
+        this->status_clear_warning();
+
+        network_tick_mdns();
```
Comment (jesserockz) [inline esphome/components/ethernet/ethernet_component.cpp:106]: I think you missed adding the `network_tick_mdns` while it is `CONNECTED`?
This will only call once when first connected

Comment (flacjacket) [reply esphome/components/ethernet/ethernet_component.cpp:106]: Thanks for taking a look at this.

I think this maintains the current behavior for that, so maybe you can help me understand what is the correct time to call `network_tick_mdns`?

Previously, this function was only called as a connection is made or as a connection is dropped, and would do nothing while a connection remained connected or unconnected, because of the `if (this->connected_ == this->last_connected_) return;` block. I tried to maintain the previous behavior (though it looks like this no longer ticks when a connection is dropped). I can add the tick while the connection remains connected, but just want to check on what is the right thing to do there. Looking at the wifi component, it looks like that ticks on every loop, regardless of the state of the connection, is that the correct behavior?

Comment (jesserockz) [reply esphome/components/ethernet/ethernet_component.cpp:106]: Hmm I see...
I had not looked at the ethernet componenet before...
I just know that the wifi_component calls it every loop.

Leave as is then as it is not changing how it was working before.

**Review by jesserockz — APPROVED** [review]

File: esphome/components/ethernet/ethernet_component.cpp (hunk 2 above)
Comment (flacjacket) [reply esphome/components/ethernet/ethernet_component.cpp:106]: Got it, thanks. Digging back a bit through git blame on esphome-core, it looks like the change in esphome/esphome-core#481 just added the tick at the end of the loop, and may not have looked in particular to see how the exit happened. That said, it looks like the tick at least currently only does anything for ESP8266's, which wouldn't be applicable for ethernet, since it is esp32-only.

Comment (jesserockz) [reply esphome/components/ethernet/ethernet_component.cpp:106]: Huh yeah there is not even any point in having the tick in the ethernet file...
