### PR TITLE
[binary_sensor] Fix reporting of 'unknown'

### LINKED ISSUE #12252: Binary sensors no longer Unknown
### The problem

I've been using binary_sensor.invalidate_state to set binary sensors to Unknown. However, I've noticed today (and I'd noticed something wasn't right but I hadn't had time to look into the detail until today) that it no longer seems to work. Has there been a change to this action?

### Which version of ESPHome has the issue?

2025.11.2

### What type of installation are you using?

Home Assistant Add-on

### What platform are you using?

ESP32

### Component causing the issue

_No response_

### YAML Config

```yaml

```

### Anything in the logs that might be useful for us?

```txt

```

### Additional information

This is the C++ code that uses the action:
```
            void setInfotainmentSensors (bool state) // state is an anachronism
            {
                if (!state)
                {
                    ChargeStateSensor->publish_state (NAN);
                    OdometerStateSensor->publish_state (NAN);
                    ChargeCurrentStateSensor->publish_state (NAN);
                    ChargeVoltageStateSensor->publish_state (NAN);
                    ChargePowerStateSensor->publish_state (NAN);
                    MaxSocStateSensor->publish_state (NAN);
                    MaxAmpsStateSensor->publish_state (NAN);
                    MinsToLimitStateSensor->publish_state (NAN);
                    ShiftStateSensor->publish_state ("Unknown");
                    DefrostStateSensor->publish_state ("Unknown");
                    ChargingStateSensor->publish_state ("Unknown");
                    BatteryRangeStateSensor->publish_state (NAN);
                    isClimateOnSensor->invalidate_state ();
                    insideTempStateSensor->publish_state (NAN);
                    outsideTempStateSensor->publish_state (NAN);
                    ChargeEnergyAddedSensor->publish_state (NAN);
                    ChargeDistanceAddedSensor->publish_state (NAN);
                    isBootOpenSensor->invalidate_state ();
                    isFrunkOpenSensor->invalidate_state ();
                    windowsStateSensor->invalidate_state ();
                }
```

### PR DESCRIPTION
**Pull request by clydebarrow**
# What does this implement/fix?

Recent changes to the interface between sensor and API resulted in `unknown` state of a binary sensor not being sent to HA. The cause was that the call to notify the API Controller was not in the base class method that is called directly when the state becomes invalid.

The fix required overriding `set_state_()` and notifying the Controller in that method to ensure that both valid and invalid states are notified to the API.

## Types of changes

- [x] Bugfix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] Developer breaking change (an API change that could break external components)
- [ ] Code quality improvements to existing code or addition of tests
- [ ] Other

**Related issue or feature (if applicable):**

- fixes https://github.com/esphome/esphome/issues/12252

**Pull request in [esphome-docs](https://github.com/esphome/esphome-docs) with documentation (if applicable):**

- esphome/esphome-docs#<esphome-docs PR number goes here>

## Test Environment

- [ ] ESP32
- [ ] ESP32 IDF
- [ ] ESP8266
- [ ] RP2040
- [ ] BK72xx
- [ ] RTL87xx
- [ ] nRF52840
- [x] host

## Example entry for `config.yaml`:

```yaml
# Example config.yaml
      then:
        - binary_sensor.template.publish:
            id: bs
            state: true
        - delay: 3s
        - binary_sensor.template.publish:
            id: bs
            state: false
        - delay: 3s
        - binary_sensor.invalidate_state:
            id: bs
```

## Checklist:
  - [x] The code change is tested and works locally.
  - [ ] Tests have been added to verify that the new code works (under `tests/` folder).

If user exposed functionality or configuration variables are added/changed:
  - [ ] Documentation added/updated in [esphome-docs](https://github.com/esphome/esphome-docs).

### CODE REVIEW

**Comment by bdraco** [comment]
Need to check into the CI failure, and we should probably add some integration test for this so we don't break it again.

I have calls most of the afternoon and then I can take a look

**Comment by bdraco** [comment]
- BinarySensorInvalidateAction dropped from 124 → 28 bytes (-77%)
- TimeoutFilter::input lambda dropped from 125 → 31 bytes (-75%)
- send_state_internal dropped from 88 → 35 bytes (-60%)

**Comment by bdraco** [comment]
It all still looks correct. I think its just the compiler doing a better job

File: esphome/components/binary_sensor/binary_sensor.cpp [hunk 1]
```diff
@@ -34,13 +34,20 @@ void BinarySensor::publish_initial_state(bool new_state) {
...
   // copy the new state to the visible property for backwards compatibility, before any callbacks
   this->state = new_state;
-  // Note that set_state_ de-dups and will only trigger callbacks if the state has actually changed
-  if (this->set_state_(new_state)) {
-    ESP_LOGD(TAG, "'%s': New state is %s", this->get_name().c_str(), ONOFF(new_state));
+  // Note that set_new_state_ de-dups and will only trigger callbacks if the state has actually changed
+  this->set_new_state(new_state);
+}
+
+bool BinarySensor::set_new_state(const optional<bool> &new_state) {
```
Comment (bdraco) [inline esphome/components/binary_sensor/binary_sensor.cpp:41]: Did we need to make this public, can we keep it protected so users don't use it in lambdas?

Comment (clydebarrow) [reply esphome/components/binary_sensor/binary_sensor.cpp:41]: I don't think it should be made public (it is and was protected.) `publish_state()` and `invalidate_state()` are what users should be using.

The name had to change because clang-tidy doesn't like virtual methods ending in _ even when protected. And `set_state()` clashed with some other classes' methods.

Comment (bdraco) [reply esphome/components/binary_sensor/binary_sensor.cpp:41]: I read it as it was public because it didn't have the `_`, and missed its in `protected:` .. had to look higher up in the diff

**Review by bdraco — APPROVED** [review]

**Comment by bdraco** [comment]
Thanks @clydebarrow
