### PR TITLE
[modbus] Fix timing bugs and better adhere to spec

### LINKED ISSUE #6633: Modbus has multiple timing issues
### The problem

I've been working through a number of modbus timing issues which occur when trying to poll multiple devices in quick succession (in this case 2x sdm_meter devices). I tested these devices both using the sdm_meter component, and using a modbus_controller. There are problems with each.

The symptoms that appear include:
- CRC error when beginning of response is cut off. 
- Timeout when end of response is cut off (almost always at 120 bytes)
- Various errors that stem from that (retries can cascade the issue)

The issues:

- Frame delay timeout (3.5 characters from spec) is not honoured, incorrectly merging unrelated bytes
- Turnaround delay (application specific) is not present, allowing tx too soon after rx or tx
- UART buffer (120 bytes by default) causes timeouts for long responses which get broken into pieces
- TX is synchronous (with flush) causing long component loop execution times
- Waiting for response didn't care if response was from correct address
- Waiting for response is used for server mode which cannot receive responses
- waiting_for_response() only blocks when waiting, doesn't block for frame delay or turnaround delay
- Multiple components inherit from ModbusDevice but don't block for waiting_for_response() : sdm_meter, havells_solar, kuntze, pzemac, pzemdc, selec_meter

I have built a patch which solves each of them (some elegantly, some less so). 

### Which version of ESPHome has the issue?

2024.12.2

### What type of installation are you using?

Home Assistant Add-on

### Which version of Home Assistant has the issue?

_No response_

### What platform are you using?

ESP32

### Board

_No response_

### Component causing the issue

modbus

### YAML Config

```yaml
esphome:
  name: power-system
  friendly_name: Power System

esp32:
  board: esp32dev
  framework:
    type: arduino

# Enable logging
logger:
  baud_rate: 0
  level: VERBOSE
  logs:
    modbus: VERBOSE
    modbus_controller: VERBOSE
    sensor: DEBUG

# Enable Home Assistant API
api:
  encryption:
    key: !secret api_key 

ota:
  - platform: esphome
    password: !secret ota_password

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password

external_components:
  - source: components

i2c:
  sda: 16
  scl: 17
  frequency: 800kHz



uart:
  tx_pin: 1
  rx_pin: 3
  baud_rate: 9600
  debug:


modbus:
  flow_control_pin: 4
  send_wait_time: 200ms
  turnaround_time: 200ms #This is from the patched version


# modbus_controller:
#  - address: 2
#    id: well_power_meter
#    update_interval: 2s 
#    #command_throttle: 200ms
#    max_cmd_retries: 0
#  - address: 3
#    id: pressure_power_meter
#    update_interval: 2s 
#    #command_throttle: 200ms
#    max_cmd_retries: 0
  

sensor:

  - platform: sdm_meter
    address: 2
    update_interval: 1s
    phase_a:
      current:
        name: "Well Pump Current"
      voltage:
        name: "Well Pump Voltage"
  - platform: sdm_meter
    address: 3
    update_interval: 1s
    phase_a:
      current:
        name: "Pressure Pump Current"
      voltage:
        name: "Pressure Pump Voltage"
  # - platform: modbus_controller
  #   modbus_controller_id: well_power_meter
  #   name: "Well Pump Voltage"
  #   address: 0x0000
  #   register_count: 2
  #   unit_of_measurement: "V"
  #   register_type: read
  #   value_type: FP32
  #   accuracy_decimals: 3
  #   device_class: voltage
  # - platform: modbus_controller
  #   modbus_controller_id: well_power_meter
  #   name: "Well Pump Current"
  #   address: 0x0006
  #   register_count: 100
  #   unit_of_measurement: "A"
  #   register_type: read
  #   value_type: FP32
  #   accuracy_decimals: 3
  #   device_class: current
  # - platform: modbus_controller
  #   modbus_controller_id: pressure_power_meter
  #   name: "Pressure Pump Voltage"
  #   address: 0x0000
  #   register_count: 2
  #   unit_of_measurement: "V"
  #   register_type: read
  #   value_type: FP32
  #   accuracy_decimals: 3
  #   device_class: voltage
  # - platform: modbus_controller
  #   modbus_controller_id: pressure_power_meter
  #   name: "Pressure Pump Current"
  #   address: 0x0006
  #   register_count: 2
  #   unit_of_measurement: "A"
  #   register_type: read
  #   value_type: FP32
  #   accuracy_decimals: 3
  #   device_class: current
  # - platform: modbus_controller
  #   modbus_controller_id: pressure_power_meter
  #   name: "Pressure Pump Active Power"
  #   address: 0x000C
  #   register_count: 2
  #   unit_of_measurement: "W"
  #   register_type: read
  #   value_type: FP32
  #   accuracy_decimals: 3
  #   device_class: power
  # - platform: modbus_controller
  #   modbus_controller_id: pressure_power_meter
  #   name: "Pressure Pump Aparent Power"
  #   address: 0x0012
  #   register_count: 2
  #   unit_of_measurement: "W"
  #   register_type: read
  #   value_type: FP32
  #   accuracy_decimals: 3
  #   device_class: power
```

### Anything in the logs that might be useful for us?

_No response_

### Additional information

_No response_

### PR DESCRIPTION
**Pull request by exciton**
This PR is part of a series of fixes for modbus and related components:
1. #8032 
2. #14172 (merge after 1)
3. #11969 (merge after 2)
4. #11781 (merge after 3)
5. #11987 (merge after 3)
6.  #12376 (merge after 3)
7.  #12421 (merge after 4 & 6)
8. #12612 (merge after 7)
9.  #12614 (merge after 8)

# The issues (see https://github.com/esphome/issues/issues/6633)
- Frame delay timeout (3.5 characters from spec) is not honoured, incorrectly merging unrelated bytes
- Turnaround delay (application specific) is not present, allowing tx too soon after rx or tx
- UART buffer (120 bytes by default) causes timeouts for long responses which get broken into pieces
- TX is synchronous (with flush) causing long component loop execution times
- Waiting for response didn't care if response was from correct address
- Waiting for response is used for server mode which cannot receive responses
- waiting_for_response() only blocks when waiting, doesn't block for frame delay or turnaround delay
- Multiple components inherit from ModbusDevice but don't block for waiting_for_response() -- sdm_meter, havells_solar, kuntze, pzemac, pzemdc, selec_meter

# The fixes:
- Adds a standard 3.5 character timeout for receiving frames (per spec)
- Adds a configurable turnaround delay to prevent sending too quickly after a previous message
- Adds an additional receive timeout delay when long messages are received, to workarond UART buffering
- <strike>Forces RxFIFOFull to 1 for Arduino and uart_set_rx_full_threshold to 1 for ESP-IDF.</strike> This change is taken care of in #8103 with new defaults. 
- Makes TX asynchronous (with set_timeout) to avoid long loops
- Makes on_modbus_data and other callbacks asynchronous to avoid long loops
- Adds a TX buffer queue for ModbusDevices which don't pay attention to waiting_for_response().
- Modifies !waiting_for_response (and renames to ready_for_immediate_send) to ensure send can be immediate (ModbusController will behave the same, TX buffer will never fill up)

To test this PR add the following to your configuration.

```yaml
external_components:
  - source: github://pr#8032
    components: [modbus, modbus_controller, growatt_solar]
    refresh: 1h
```

## Types of changes

- [X] Bugfix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] Code quality improvements to existing code or addition of tests
- [ ] Other

**Related issue or feature (if applicable):**

- fixes [Issue 6633](https://github.com/esphome/issues/issues/6633)

**Pull request in [esphome-docs](https://github.com/esphome/esphome-docs) with documentation (if applicable):**

- esphome/esphome-docs#5359

## Test Environment

- [X] ESP32
- [x] ESP32 IDF
- [ ] ESP8266
- [ ] RP2040
- [ ] BK72xx
- [ ] RTL87xx

## Example entry for `config.yaml`:

```yaml
esphome:
  name: power-system
  friendly_name: Power System

esp32:
  board: esp32dev
  framework:
    type: arduino

external_components:
  - source: github://pr#8103
    components: [uart]
    refresh: 1h
  - source: github://pr#8032
    components: [modbus, modbus_controller, growatt_solar]
    refresh: 1h

# Enable logging
logger:
  baud_rate: 0
  level: VERBOSE
  logs:
    modbus: VERBOSE
    modbus_controller: VERBOSE
    sensor: DEBUG

# Enable Home Assistant API
api:
  encryption:
    key: !secret api_key 

ota:
  - platform: esphome
    password: !secret ota_password

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password

i2c:
  sda: 16
  scl: 17
  frequency: 800kHz

uart:
  tx_pin: 1
  rx_pin: 3
  baud_rate: 9600
  debug:


modbus:
  flow_control_pin: 4
  send_wait_time: 200ms
  turnaround_time: 200ms #This is from the patched version


# modbus_controller:
#  - address: 2
#    id: well_power_meter
#    update_interval: 2s 
#    #command_throttle: 200ms
#    max_cmd_retries: 0
#  - address: 3
#    id: pressure_power_meter
#    update_interval: 2s 
#    #command_throttle: 200ms
#    max_cmd_retries: 0
  

sensor:

  - platform: sdm_meter
    address: 2
    update_interval: 1s
    phase_a:
      current:
        name: "Well Pump Current"
      voltage:
        name: "Well Pump Voltage"
  - platform: sdm_meter
    address: 3
    update_interval: 1s
    phase_a:
      current:
        name: "Pressure Pump Current"
      voltage:
        name: "Pressure Pump Voltage"
  # - platform: modbus_controller
  #   modbus_controller_id: well_power_meter
  #   name: "Well Pump Voltage"
  #   address: 0x0000
  #   register_count: 2
  #   unit_of_measurement: "V"
  #   register_type: read
  #   value_type: FP32
  #   accuracy_decimals: 3
  #   device_class: voltage
  # - platform: modbus_controller
  #   modbus_controller_id: well_power_meter
  #   name: "Well Pump Current"
  #   address: 0x0006
  #   register_count: 100
  #   unit_of_measurement: "A"
  #   register_type: read
  #   value_type: FP32
  #   accuracy_decimals: 3
  #   device_class: current
  # - platform: modbus_controller
  #   modbus_controller_id: pressure_power_meter
  #   name: "Pressure Pump Voltage"
  #   address: 0x0000
  #   register_count: 2
  #   unit_of_measurement: "V"
  #   register_type: read
  #   value_type: FP32
  #   accuracy_decimals: 3
  #   device_class: voltage
  # - platform: modbus_controller
  #   modbus_controller_id: pressure_power_meter
  #   name: "Pressure Pump Current"
  #   address: 0x0006
  #   register_count: 2
  #   unit_of_measurement: "A"
  #   register_type: read
  #   value_type: FP32
  #   accuracy_decimals: 3
  #   device_class: current
  # - platform: modbus_controller
  #   modbus_controller_id: pressure_power_meter
  #   name: "Pressure Pump Active Power"
  #   address: 0x000C
  #   register_count: 2
  #   unit_of_measurement: "W"
  #   register_type: read
  #   value_type: FP32
  #   accuracy_decimals: 3
  #   device_class: power
  # - platform: modbus_controller
  #   modbus_controller_id: pressure_power_meter
  #   name: "Pressure Pump Aparent Power"
  #   address: 0x0012
  #   register_count: 2
  #   unit_of_measurement: "W"
  #   register_type: read
  #   value_type: FP32
  #   accuracy_decimals: 3
  #   device_class: power

```

## Checklist:
  - [X] The code change is tested and works locally.
  - [X] Tests have been added to verify that the new code works (under `tests/` folder).

If user exposed functionality or configuration variables are added/changed:
  - [x] Documentation added/updated in [esphome-docs](https://github.com/esphome/esphome-docs).

### CODE REVIEW

File: esphome/components/modbus/modbus.cpp [hunk 1]
```diff
@@ -11,46 +11,76 @@ void Modbus::setup() {
   if (this->flow_control_pin_ != nullptr) {
     this->flow_control_pin_->setup();
   }
+  //3.5 characters * 11 bits per character * 1000ms/sec / (bits/sec) (Standard modbus frame delay)
+  this->frame_delay_ms_ = (3.5 * 11 * 1000 / this->parent_->get_baud_rate()) + 1;
+  //120 characters (default RxFIFOBuffer in HardwareSerial)
+  this->long_rx_buffer_delay_ms_ = (120 * 11 * 1000 / this->parent_->get_baud_rate()) + 1;
```
Comment (exciton) [inline esphome/components/modbus/modbus.cpp]: This is a workaround for the HardwareSerial buffer which sends over chunks of 120 characters at a time, by default.
If we were able to set RxFIFOFull to 1 (there's no API in UART component to do this), then this additional buffer would not be necessary. I tested doing this manually (by editing uart_component_esp32_arduino.cpp) and it works.

Alternately we could provide a getRxFIFO API to UART component so we can read this out directly, rather than assuming it's 120 characters.

File: esphome/components/modbus/modbus.h [hunk 2]
```diff
@@ -65,7 +79,7 @@ class ModbusDevice {
   }
   void send_raw(const std::vector<uint8_t> &payload) { this->parent_->send_raw(payload); }
   // If more than one device is connected block sending a new command before a response is received
-  bool waiting_for_response() { return parent_->waiting_for_response != 0; }
+  bool waiting_for_response() { return !parent_->tx_buffer_empty() || parent_->tx_blocked(); }
```
Comment (exciton) [inline esphome/components/modbus/modbus.h]: Here we ensure that we're ready to send immediately (i.e. there's nothing in the buffer, and we've reached clear air past the various timers). This function should probably be renamed to waiting_for_send_window or something, since it waits for more things than the response.
With this implementation the two components which actually check (ModbusController and GrowattSolar) will be able to send immediately, so no change is needed.

File: esphome/components/modbus/modbus.h [hunk 3]
```diff
@@ -4,10 +4,13 @@
 #include "esphome/components/uart/uart.h"
 
 #include <vector>
+#include <deque>
 
 namespace esphome {
 namespace modbus {
 
+static const uint16_t MODBUS_TX_BUFFER_SIZE = 10;
```
Comment (exciton) [inline esphome/components/modbus/modbus.h]: This is arbitrary. Only components that don't check waiting_for_response (such as sdm_meter) will ever put more than 1 item in the buffer. It seems safe to keep this, but we could also just delete the limit all together.

File: esphome/components/modbus/modbus.cpp [hunk 4]
```diff
@@ -229,20 +283,33 @@ void Modbus::send_raw(const std::vector<uint8_t> &payload) {
...
-  this->flush();
-  if (this->flow_control_pin_ != nullptr)
-    this->flow_control_pin_->digital_write(false);
-  waiting_for_response = payload[0];
-  ESP_LOGV(TAG, "Modbus write raw: %s", format_hex_pretty(payload).c_str());
-  last_send_ = millis();
+  for (auto &item : tx_buffer_) {
+      if (item == data) {
+        ESP_LOGW(TAG, "Duplicate queued command dropped: %s", format_hex_pretty(data).c_str());
+        return;
```
Comment (exciton) [inline esphome/components/modbus/modbus.cpp]: This should be super rare. Components like ModbusController will not fill more than one item in the buffer anyway, so will never hit this. Components like sdm_meter might if we try to poll too frequently. This avoids building up a long list of identical commands that will never execute.

File: esphome/components/modbus/modbus.cpp [hunk 5]
```diff
@@ -134,7 +164,7 @@ bool Modbus::parse_modbus_byte_(uint8_t byte) {
       // Is it an error response?
       if ((function_code & 0x80) == 0x80) {
         ESP_LOGD(TAG, "Modbus error function code: 0x%X exception: %d", function_code, raw[2]);
-        if (waiting_for_response != 0) {
+        if (waiting_for_response == address) {
```
Comment (exciton) [inline esphome/components/modbus/modbus.cpp]: Check that it's the correct address before sending.

File: esphome/components/modbus/modbus.cpp [hunk 6]
```diff
@@ -11,46 +11,76 @@ void Modbus::setup() {
...
+
+bool Modbus::tx_blocked() {
   const uint32_t now = millis();
 
+  return available() ||
+        (rx_buffer_.size() > 0) ||
+        (waiting_for_response != 0) ||
+        (now - last_send_ < frame_delay_ms_ + (role == ModbusRole::CLIENT ? turnaround_delay_ms_ : 0)) ||
+        (now - last_modbus_byte_ < frame_delay_ms_ + (role == ModbusRole::CLIENT ? turnaround_delay_ms_ : 0));
+}
```
Comment (exciton) [inline esphome/components/modbus/modbus.cpp:76]: We block transmission in any of these cases
- There are bytes in the UART Rx buffer
- There are bytes in our Rx buffer
- We're waiting for a response
- The last sent byte isn't more than frame_delay ms ago (i.e. wait to tell receivers that our previous Tx is done)
- The last received byte isn't more than frame_delay ms ago (i.e. wait to be sure there isn't more Rx coming)
- If we're a client - then also wait for the turnaround delay, to give the servers time to process the previous message

File: esphome/components/modbus/__init__.py [hunk 7]
```diff
@@ -40,6 +41,9 @@
             cv.Optional(
                 CONF_SEND_WAIT_TIME, default="250ms"
             ): cv.positive_time_period_milliseconds,
+            cv.Optional(
+                CONF_TURNAROUND_TIME, default="0ms"
```
Comment (exciton) [inline esphome/components/modbus/__init__.py]: The turnaround delay is much more effective at preventing clashes between multiple devices on the network than command_throttle in ModbusController. The reason for this, is that ModbusController can only throttle commands for it's one addressed device. If there are multiple ModbusControllers they can't throttle between each other, so device #1 can be processing (and ignoring) a message from device #2 and then miss a command from the client/master if it's sent too quickly.

I found it very effective to set turnaround_time to 200ms and command_throttle to 0ms when using ModbusController to pull multiple registers from a pair of sdm meters. Swapping these creates frequent collisions.

**Review by exciton — COMMENTED** [review]
Added some comments to explain what's going on

**Comment by karllinder** [comment]
Hi!

Still have issues with CRC, did try this fix aswell, did not work, do you have any input what i should try?
With  2.0.6 there is no issue:

```
framework: 
    type: arduino
    version: 2.0.6
```

But if i go for default arduino the CRC check error starts.


Config:

```
external_components:
  - source: github://pr#8032
    components: [ modbus ]

uart:
  rx_pin: 16
  tx_pin: 17
  baud_rate: 38400
  parity: even
  stop_bits: 1
  debug:

modbus:
  flow_control_pin: 5
  #send_wait_time: 200ms
  #turnaround_time: 200ms #This is from the patched version

Sensors and more
sensor:
  - platform: dallas_temp
    address: 0xa73c01f09514a628
    one_wire_id: dallasbus1
    name: "Temp"
    
  - platform: sdm_meter
    phase_a:
      current:
        name: "SDM630 Phase A Current"
      voltage:
        name: "SDM630 Phase A Voltage"
```
Log file:
```
`[19:05:56][D][uart_debug:114]: >>> 01:04:00:00:00:50:F0:36
[19:05:56][W][modbus:155]: Modbus CRC Check failed! C071!=C200 00.00.00.00.C2 (5) at 18153
[19:05:56][W][modbus:155]: Modbus CRC Check failed! B3BF!=7F3F CF.A9.2E.3F.7F (5) at 18157
[19:05:56][W][modbus:155]: Modbus CRC Check failed! C421!=00 EB.7F.00.00.00 (5) at 18171
[19:05:56][W][modbus:155]: Modbus CRC Check failed! 9621!=5E51 00.C1.08.51.5E (5) at 18173
[19:05:56][W][modbus:155]: Modbus CRC Check failed! C071!=4200 00.00.00.00.42 (5) at 18187
[19:05:56][W][modbus:155]: Modbus CRC Check failed! FCCE!=D446 47.EB.23.46.D4 (5) at 18189
[19:05:56][W][component:237]: Component modbus took a long time for an operation (66 ms).
[19:05:56][W][component:238]: Components should block for at most 30 ms.
[19:05:56][W][modbus:155]: Modbus CRC Check failed! 4652!=4303 00.01.04.A0.43.65.3B.03.43 (9) at 18287
[19:05:56][W][modbus:155]: Modbus CRC Check failed! 3861!=6743 64.C3.34.43.67 (5) at 18292
[19:05:56][D][uart_debug:114]: <<< 00:00:00:00:C2:CF:A9:2E:3F:7F:EB:7F:00:00:00:00:C1:08:51:5E:00:00:00:00:42:47:EB:23:46:D4:9D:7E:3A:83:12:6F:44:CA:2E:14:45:45:D6:19:1C:39:00:00:01:04:A0:43:65:3B:03:43:64:C3:34:43:67:6A:6E:40:60:72:C9:40:A4:90:63:40:A1:9F:86:44:3F:80:D3:44:92:E4:52:44:91:99:71:44:3F:80:DB:44:92:ED:48:44:91:F1:4A:00:00:00:00:C1:CD:3D:AB:C2:A0:08:78:3F:80:00:00:3F:7F:F0:6F:3F:7F:66:20:3E:D9:03:DD:BF:9F:DC:45:C0:7B:59:C4:43:65:CD:8D:00:00:00:00:40:91:E9:FD:41:5A:DE
[19:05:56][W][component:237]: Component modbus took a long time for an operation (80 ms).
[19:05:56][W][component:238]: Components should block for at most 30 ms.
[19:05:56][D][uart_debug:114]: <<< FB:00:00:00:00:45:42:12:17:00:00:00:00:45:42:42:02
[19:06:06][D][uart_debug:114]: >>> 01:04:00:00:00:50:F0:36
[19:06:06][W][modbus:155]: Modbus CRC Check failed! C071!=C200 00.00.00.00.C2 (5) at 28165
[19:06:06][W][modbus:155]: Modbus CRC Check failed! FF36!=7F3F D0.F5.C8.3F.7F (5) at 28169
[19:06:06][W][modbus:155]: Modbus CRC Check failed! 6A1F!=00 DE.15.00.00.00 (5) at 28182
[19:06:06][W][modbus:155]: Modbus CRC Check failed! B681!=C249 00.BF.F6.49.C2 (5) at 28185
[19:06:06][W][modbus:155]: Modbus CRC Check failed! C071!=4200 00.00.00.00.42 (5) at 28198
[19:06:06][W][modbus:155]: Modbus CRC Check failed! 5287!=D446 47.F5.34.46.D4 (5) at 28201
[19:06:06][W][modbus:155]: Modbus CRC Check failed! D01!=1283 9D.83.3A.83.12 (5) at 28215
[19:06:06][W][component:237]: Component modbus took a long time for an operation (67 ms).
[19:06:06][W][component:238]: Components should block for at most 30 ms.
[19:06:06][W][modbus:155]: Modbus CRC Check failed! 7A52!=43D6 00.01.04.A0.43.65.6B.D6.43 (9) at 28297
[19:06:06][W][modbus:155]: Modbus CRC Check failed! BAAF!=6743 64.D6.0D.43.67 (5) at 28300
[19:06:06][W][modbus:155]: Modbus CRC Check failed! 2B4F!=E4A1 B6.5A.40.60.5E.A4.40.A4.9D.C6.40.A1.BE.82.44.3F.F3.A3.44.92.F1.CD.44.91.E6.20.44.3F.F3.AD.44.92.FB.01.44.92.3D.75.00.00.00.00.C1.D0.10.A8.C2.9F.BA.87.3F.80.00.00.3F.7F.F0.09.3F.7F.67.62.3E.34.10.0F.BF.A1.E4 (69) at 28317
[19:06:06][W][modbus:155]: Modbus CRC Check failed! 18D0!=EE51 DB.C0.7A.51.EE (5) at 28341
[19:06:06][D][uart_debug:114]: <<< 00:00:00:00:C2:D0:F5:C8:3F:7F:DE:15:00:00:00:00:BF:F6:49:C2:00:00:00:00:42:47:F5:34:46:D4:9D:83:3A:83:12:6F:44:CA:2E:14:45:45:D6:1D:68:54:00:00:01:04:A0:43:65:6B:D6:43:64:D6:0D:43:67:B6:5A:40:60:5E:A4:40:A4:9D:C6:40:A1:BE:82:44:3F:F3:A3:44:92:F1:CD:44:91:E6:20:44:3F:F3:AD:44:92:FB:01:44:92:3D:75:00:00:00:00:C1:D0:10:A8:C2:9F:BA:87:3F:80:00:00:3F:7F:F0:09:3F:7F:67:62:3E:34:10:0F:BF:A1:E4:DB:C0:7A:51:EE:43:65:FD:6B:00:00:00:00:40:91:F5:70:41:5A:F0
[19:06:06][W][component:237]: Component modbus took a long time for an operation (104 ms).
[19:06:06][W][component:238]: Components should block for at most 30 ms.
[19:06:06][D][uart_debug:114]: <<< 28:00:00:00:00:45:42:68:DF:00:00:00:00:45:42:99:27
[19:06:16][D][uart_debug:114]: >>> 01:04:00:00:00:50:F0:36
[19:06:16][W][modbus:155]: Modbus CRC Check failed! C071!=C200 00.00.00.00.C2 (5) at 38166
[19:06:16][W][modbus:155]: Modbus CRC Check failed! ED31!=7F3F D3.BE.B1.3F.7F (5) at 38170
[19:06:16][W][modbus:155]: Modbus CRC Check failed! 9B4B!=00 DB.E6.00.00.00 (5) at 38184
[19:06:16][W][modbus:155]: Modbus CRC Check failed! B2C1!=2FD0 00.BF.F9.D0.2F (5) at 38186
[19:06:16][W][modbus:155]: Modbus CRC Check failed! C071!=4200 00.00.00.00.42 (5) at 38200
[19:06:16][W][modbus:155]: Modbus CRC Check failed! 5306!=D446 47.F7.B6.46.D4 (5) at 38202
[19:06:16][W][modbus:155]: Modbus CRC Check failed! CD03!=1283 9D.87.3A.83.12 (5) at 38216
[19:06:16][W][component:237]: Component modbus took a long time for an operation (68 ms).
[19:06:16][W][component:238]: Components should block for at most 30 ms.
[19:06:16][W][modbus:155]: Modbus CRC Check failed! EA93!=436A 00.01.04.A0.43.65.AA.6A.43 (9) at 38300
[19:06:16][W][modbus:155]: Modbus CRC Check failed! 95D8!=6643 64.9C.E6.43.66 (5) at 38305
[19:06:16][W][modbus:155]: Modbus CRC Check failed! A546!=CB60 EE.CA.40.60.CB (5) at 38319
[19:06:16][D][uart_debug:114]: <<< 00:00:00:00:C2:D3:BE:B1:3F:7F:DB:E6:00:00:00:00:BF:F9:D0:2F:00:00:00:00:42:47:F7:B6:46:D4:9D:87:3A:83:12:6F:44:CA:2E:14:45:45:D6:21:4D:81:00:00:01:04:A0:43:65:AA:6A:43:64:9C:E6:43:66:EE:CA:40:60:CB:75:40:A4:82:D0:40:A1:4B:C4:44:40:4B:FF:44:92:A2:0D:44:91:13:A5:44:40:4C:0F:44:92:A9:99:44:91:6B:53:00:00:00:00:C1:BC:33:8B:C2:9F:98:42:3F:80:00:00:3F:7F:F1:95:3F:7F:64:58:3E:B8:49:AA:BF:99:D9:4B:C0:7C:CC:EE:43:65:BC:B4:00:00:00:00:40:91:D8:3B:41:5A:C4
[19:06:16][W][component:237]: Component modbus took a long time for an operation (82 ms).
[19:06:16][W][component:238]: Components should block for at most 30 ms.
[19:06:16][D][uart_debug:114]: <<< 59:00:00:00:00:45:41:B9:E1:00:00:00:00:45:41:EA:51
[19:06:17][D][dallas.temp.sensor:054]: 'Temp': Got Temperature=27.1°C
[19:06:17][D][sensor:094]: 'Temp': Sending state 27.12500 °C with 1 decimals of accuracy
[19:06:26][D][uart_debug:114]: >>> 01:04:00:00:00:50:F0:36
[19:06:26][W][modbus:155]: Modbus CRC Check failed! C071!=C200 00.00.00.00.C2 (5) at 48159
[19:06:26][W][modbus:155]: Modbus CRC Check failed! 5217!=7F3F D1.B4.9B.3F.7F (5) at 48163
[19:06:26][W][modbus:155]: Modbus CRC Check failed! 5AA6!=00 DD.F6.00.00.00 (5) at 48177
[19:06:26][W][modbus:155]: Modbus CRC Check failed! 7200!=9B51 00.BF.F8.51.9B (5) at 48179
[19:06:26][W][modbus:155]: Modbus CRC Check failed! C071!=4200 00.00.00.00.42 (5) at 48192
[19:06:26][W][component:237]: Component modbus took a long time for an operation (53 ms).
[19:06:26][W][component:238]: Components should block for at most 30 ms.
[19:06:26][W][modbus:155]: Modbus CRC Check failed! B2D3!=4367 00.01.04.A0.43.64.B5.67.43 (9) at 48291
[19:06:26][W][modbus:155]: Modbus CRC Check failed! B5DF!=6743 65.A9.59.43.67 (5) at 48296
[19:06:26][W][modbus:155]: Modbus CRC Check failed! 790D!=A540 84.05.40.61.25.9E.40.A5 (8) at 48310
[19:06:26][D][uart_debug:114]: <<< 00:00:00:00:C2:D1:B4:9B:3F:7F:DD:F6:00:00:00:00:BF:F8:51:9B:00:00:00:00:42:48:02:78:46:D4:9D:8B:3A:83:12:6F:44:CA:2E:14:45:45:D6:21:13:2D:00:00:01:04:A0:43:64:B5:67:43:65:A9:59:43:67:84:05:40:61:25:9E:40:A5:09:45:40:A1:C8:07:44:3F:27:B6:44:93:DE:92:44:91:DA:5E:44:3F:27:B5:44:93:E6:14:44:92:31:CC:00:00:00:00:C1:BC:7C:1D:C2:9F:CA:A7:3F:80:00:00:3F:7F:F3:0D:3F:7F:66:F9:3E:84:D8:54:BF:91:CC:C7:C0:7A:A8:39:43:65:F6:41:00:00:00:00:40:92:3D:69:41:5B:5C
[19:06:26][W][component:237]: Component modbus took a long time for an operation (82 ms).
[19:06:26][W][component:238]: Components should block for at most 30 ms.
[19:06:26][D][uart_debug:114]: <<< 1D:00:00:00:00:45:42:A6:65:00:00:00:00:45:42:D5:DE
[19:06:27][D][sensor:094]: 'WiFi Signal': Sending state -67.00000 dBm with 0 decimals of accuracy
```


With 2.0.6:
```
19:13:24][D][uart_debug:114]: >>> 01:04:00:00:00:50:F0:36
[19:13:24][D][uart_debug:114]: <<< 00
[19:13:25][D][uart_debug:114]: <<< 01:04:A0:43:5D:EA:DE:43:66:2B:2C:43:69:5C:59:40:65:25:4B:40:A4:C0:C8:40:9C:FB:21:44:3C:B0:45:44:93:F0:56:44:8E:B4:B0:44:3C:B3:0F:44:93:F8:2D:44:8E:FC:02:C1:01:63:1A:C1:C0:A7:20:C2:8E:BD:2C:3F:7F:FC:4A:3F:7F:F2:81:3F:7F:80:86:BF:1C:1B:24:BF:94:D9:02:C0:64:C4:D1:43:64:7B:77:00:00:00:00:40:91:35:35:41:59:CF:D0:00:00:00:00:45:40:7E:94:00:00:00:00:45:40:A6:DC:00:00:00:00:C2:CF:13:57:3F:7F:DA:F0:00:00:00:00:BF:F6:AD:BF:00:00:00:00:42:48:15:F3:46:D4:9E
[19:13:25][D][sdm_meter:043]: SDMMeter Phase A: V=221.917 V, I=3.580 A, Active P=754.754 W, Apparent P=754.798 VA, Reactive P=-8.087 var, PF=1.000, PA=-0.610 °
[19:13:25][D][sensor:094]: 'SDM630 Phase A Voltage': Sending state 221.91745 V with 2 decimals of accuracy
[19:13:25][D][sensor:094]: 'SDM630 Phase A Current': Sending state 3.58040 A with 3 decimals of accuracy
[19:13:25][D][sensor:094]: 'SDM630 Phase A Power': Sending state 754.75421 W with 2 decimals of accuracy
[19:13:25][D][sensor:094]: 'SDM630 Phase A Apparent Power': Sending state 754.79779 VA with 2 decimals of accuracy
[19:13:25][D][sensor:094]: 'SDM630 Phase A Reactive Power': Sending state -8.08669 var with 2 decimals of accuracy
[19:13:25][D][sensor:094]: 'SDM630 Phase A Power Factor': Sending state 0.99994  with 3 decimals of accuracy
[19:13:25][D][sensor:094]: 'SDM630 Phase A Phase Angle': Sending state -0.60979 ° with 3 decimals of accuracy
[19:13:25][D][sdm_meter:043]: SDMMeter Phase B: V=230.169 V, I=5.149 A, Active P=1183.510 W, Apparent P=1183.755 VA, Reactive P=-24.082 var, PF=1.000, PA=-1.163 °
[19:13:25][D][sensor:094]: 'SDM630 Phase B Voltage': Sending state 230.16864 V with 2 decimals of accuracy
[19:13:25][D][sensor:094]: 'SDM630 Phase B Current': Sending state 5.14853 A with 3 decimals of accuracy
[19:13:25][D][sensor:094]: 'SDM630 Phase B Power': Sending state 1183.51050 W with 2 decimals of accuracy
[19:13:25][D][sensor:094]: 'SDM630 Phase B Apparent Power': Sending state 1183.75549 VA with 2 decimals of accuracy
[19:13:25][D][sensor:094]: 'SDM630 Phase B Reactive Power': Sending state -24.08160 var with 2 decimals of accuracy
[19:13:25][D][sensor:094]: 'SDM630 Phase B Power Factor': Sending state 0.99979  with 3 decimals of accuracy
[19:13:25][D][sensor:094]: 'SDM630 Phase B Phase Angle': Sending state -1.16287 ° with 3 decimals of accuracy
[19:13:25][D][sdm_meter:043]: SDMMeter Phase C: V=233.361 V, I=4.906 A, Active P=1141.646 W, Apparent P=1143.875 VA, Reactive P=-71.369 var, PF=0.998, PA=-3.575 °
[19:13:25][D][sensor:094]: 'SDM630 Phase C Voltage': Sending state 233.36073 V with 2 decimals of accuracy
[19:13:25][D][sensor:094]: 'SDM630 Phase C Current': Sending state 4.90566 A with 3 decimals of accuracy
[19:13:25][D][sensor:094]: 'SDM630 Phase C Power': Sending state 1141.64648 W with 2 decimals of accuracy
[19:13:25][D][sensor:094]: 'SDM630 Phase C Apparent Power': Sending state 1143.87524 VA with 2 decimals of accuracy
[19:13:25][D][sensor:094]: 'SDM630 Phase C Reactive Power': Sending state -71.36948 var with 2 decimals of accuracy
[19:13:25][D][sensor:094]: 'SDM630 Phase C Power Factor': Sending state 0.99805  with 3 decimals of accuracy
[19:13:25][D][sensor:094]: 'SDM630 Phase C Phase Angle': Sending state -3.57451 ° with 3 decimals of accuracy
[19:13:25][D][sdm_meter:069]: SDMMeter: F=50.021 Hz, Im.A.E=27215.156 Wh, Ex.A.E=0.001 Wh, Im.R.E=1617.445 VARh, Ex.R.E=3165.400 VARh, T.P=3079.911 W
[19:13:25][D][sensor:094]: 'SDM630 Total Power': Sending state 3079.91113 W with 2 decimals of accuracy
[19:13:25][D][sensor:094]: 'SDM630 Frequency': Sending state 50.02143 Hz with 3 decimals of accuracy
[19:13:25][D][sensor:094]: 'SDM630 Import Active Energy': Sending state 27215.15625 kWh with 2 decimals of accuracy
[19:13:25][D][sensor:094]: 'SDM630 Export Active Energy': Sending state 0.00100 kWh with 2 decimals of accuracy
[19:13:25][D][sensor:094]: 'SDM630 Import Reactive Energy': Sending state 1617.44495 kVARh with 2 decimals of accuracy
[19:13:25][D][sensor:094]: 'SDM630 Export Reactive Energy': Sending state 3165.39990 kVARh with 2 decimals of accuracy
[19:13:25][W][component:237]: Component modbus took a long time for an operation (398 ms).
[19:13:25][W][component:238]: Components should block for at most 30 ms.
[19:13:25][D][uart_debug:114]: <<< 50:3A:83:12:6F:44:CA:2E:3D:45:45:D6:66:44:34:00
[19:13:29][I][safe_mode:041]: Boot seems successful; resetting boot loop counter
[19:13:29][D][esp32.preferences:114]: Saving 1 preferences to flash...
[19:13:29][D][esp32.preferences:143]: Saving 1 preferences to flash: 0 cached, 1 written, 0 failed
[19:13:34][D][uart_debug:114]: >>> 01:04:00:00:00:50:F0:36
[19:13:34][D][uart_debug:114]: <<< 00:01:04:A0:43:5D:ED:52:43:66:2E:C8:43:69:A1:2F:40:63:FC:10:40:A4:D7:20:40:9D:21:F3:44:3C:4C:BE:44:93:FB:20:44:8E:EA:06:44:3C:4F:6D:44:94:04:54:44:8F:31:04:C0:FD:FC:9D:C1:D0:BF:5B:C2:8E:84:0F:3F:7F:FC:6F:3F:7F:F0:28:3F:7F:81:32:BF:19:09:27:BF:A1:47:55:C0:64:29:EE:43:64:94:6D:00:00:00:00:40:91:18:5A:41:59:A4:87:00:00:00:00:45:40:85:62:00:00:00:00:45:40:AD:F5:00:00:00:00:C2:CE:27:7F:3F:7F:DB:6D:00:00:00:00:BF:F5:0C:1D:00:00:00:00:42:48:0D:2B:46:D4
[19:13:35][D][sdm_meter:043]: SDMMeter Phase A: V=221.927 V, I=3.562 A, Active P=753.199 W, Apparent P=753.241 VA, Reactive P=-7.937 var, PF=1.000, PA=-0.598 °
[19:13:35][D][sensor:094]: 'SDM630 Phase A Voltage': Sending state 221.92703 V with 2 decimals of accuracy
[19:13:35][D][sensor:094]: 'SDM630 Phase A Current': Sending state 3.56226 A with 3 decimals of accuracy
[19:13:35][D][sensor:094]: 'SDM630 Phase A Power': Sending state 753.19910 W with 2 decimals of accuracy
[19:13:35][D][sensor:094]: 'SDM630 Phase A Apparent Power': Sending state 753.24103 VA with 2 decimals of accuracy
[19:13:35][D][sensor:094]: 'SDM630 Phase A Reactive Power': Sending state -7.93709 var with 2 decimals of accuracy
[19:13:35][D][sensor:094]: 'SDM630 Phase A Power Factor': Sending state 0.99995  with 3 decimals of accuracy
[19:13:35][D][sensor:094]: 'SDM630 Phase A Phase Angle': Sending state -0.59780 ° with 3 decimals of accuracy
[19:13:35][D][sdm_meter:043]: SDMMeter Phase B: V=230.183 V, I=5.151 A, Active P=1183.848 W, Apparent P=1184.135 VA, Reactive P=-26.093 var, PF=1.000, PA=-1.260 °
[19:13:35][D][sensor:094]: 'SDM630 Phase B Voltage': Sending state 230.18274 V with 2 decimals of accuracy
[19:13:35][D][sensor:094]: 'SDM630 Phase B Current': Sending state 5.15126 A with 3 decimals of accuracy
[19:13:35][D][sensor:094]: 'SDM630 Phase B Power': Sending state 1183.84766 W with 2 decimals of accuracy
[19:13:35][D][sensor:094]: 'SDM630 Phase B Apparent Power': Sending state 1184.13525 VA with 2 decimals of accuracy
[19:13:35][D][sensor:094]: 'SDM630 Phase B Reactive Power': Sending state -26.09344 var with 2 decimals of accuracy
[19:13:35][D][sensor:094]: 'SDM630 Phase B Power Factor': Sending state 0.99976  with 3 decimals of accuracy
[19:13:35][D][sensor:094]: 'SDM630 Phase B Phase Angle': Sending state -1.25999 ° with 3 decimals of accuracy
[19:13:35][D][sdm_meter:043]: SDMMeter Phase C: V=233.630 V, I=4.910 A, Active P=1143.313 W, Apparent P=1145.532 VA, Reactive P=-71.258 var, PF=0.998, PA=-3.565 °
[19:13:35][D][sensor:094]: 'SDM630 Phase C Voltage': Sending state 233.62962 V with 2 decimals of accuracy
[19:13:35][D][sensor:094]: 'SDM630 Phase C Current': Sending state 4.91039 A with 3 decimals of accuracy
[19:13:35][D][sensor:094]: 'SDM630 Phase C Power': Sending state 1143.31323 W with 2 decimals of accuracy
[19:13:35][D][sensor:094]: 'SDM630 Phase C Apparent Power': Sending state 1145.53174 VA with 2 decimals of accuracy
[19:13:35][D][sensor:094]: 'SDM630 Phase C Reactive Power': Sending state -71.25793 var with 2 decimals of accuracy
[19:13:35][D][sensor:094]: 'SDM630 Phase C Power Factor': Sending state 0.99807  with 3 decimals of accuracy
[19:13:35][D][sensor:094]: 'SDM630 Phase C Phase Angle': Sending state -3.56506 ° with 3 decimals of accuracy
[19:13:35][D][sdm_meter:069]: SDMMeter: F=50.013 Hz, Im.A.E=27215.164 Wh, Ex.A.E=0.001 Wh, Im.R.E=1617.445 VARh, Ex.R.E=3165.400 VARh, T.P=3080.336 W
[19:13:35][D][sensor:094]: 'SDM630 Total Power': Sending state 3080.33643 W with 2 decimals of accuracy
[19:13:35][D][sensor:094]: 'SDM630 Frequency': Sending state 50.01286 Hz with 3 decimals of accuracy
[19:13:35][D][sensor:094]: 'SDM630 Import Active Energy': Sending state 27215.16406 kWh with 2 decimals of accuracy
[19:13:35][D][sensor:094]: 'SDM630 Export Active Energy': Sending state 0.00100 kWh with 2 decimals of accuracy
[19:13:35][D][sensor:094]: 'SDM630 Import Reactive Energy': Sending state 1617.44495 kVARh with 2 decimals of accuracy
[19:13:35][D][sensor:094]: 'SDM630 Export Reactive Energy': Sending state 3165.39990 kVARh with 2 decimals of accuracy
[19:13:35][W][component:237]: Component modbus took a long time for an operation (380 ms).
[19:13:35][W][component:238]: Components should block for at most 30 ms.
[19:13:35][D][uart_debug:114]: <<< 9E:54:3A:83:12:6F:44:CA:2E:3D:45:45:D6:66:30:68:00
[19:13:44][D][uart_debug:114]: >>> 01:04:00:00:00:50:F0:36
[19:13:44][D][uart_debug:114]: <<< 00
[19:13:45][D][uart_debug:114]: <<< 01:04:A0:43:5F:1F:5B:43:65:F8:3C:43:68:8F:B0:40:63:EE:20:40:A4:AE:45:40:9C:72:2F:44:3D:2D:2A:44:93:B2:FB:44:8D:C2:60:44:3D:2D:2A:44:93:BC:6D:44:8E:09:FA:00:00:00:00:C1:D3:4C:77:C2:8E:8C:CB:3F:80:00:00:3F:7F:EF:AE:3F:7F:7F:20:BE:AD:FA:40:BF:A3:AF:D8:C0:66:05:03:43:64:8D:18:00:00:00:00:40:90:CD:D7:41:59:34:C2:00:00:00:00:45:40:05:1C:00:00:00:00:45:40:61:04:00:00:00:00:C2:D1:51:D6:3F:7F:DA:17:00:00:00:00:BF:F9:7A:A2:00:00:00:00:42:48:0D:35:46:D4:9E
[19:13:45][D][sdm_meter:043]: SDMMeter Phase A: V=223.122 V, I=3.561 A, Active P=756.706 W, Apparent P=756.706 VA, Reactive P=0.000 var, PF=1.000, PA=-0.340 °
[19:13:45][D][sensor:094]: 'SDM630 Phase A Voltage': Sending state 223.12248 V with 2 decimals of accuracy
[19:13:45][D][sensor:094]: 'SDM630 Phase A Current': Sending state 3.56141 A with 3 decimals of accuracy
[19:13:45][D][sensor:094]: 'SDM630 Phase A Power': Sending state 756.70569 W with 2 decimals of accuracy
[19:13:45][D][sensor:094]: 'SDM630 Phase A Apparent Power': Sending state 756.70569 VA with 2 decimals of accuracy
[19:13:45][D][sensor:094]: 'SDM630 Phase A Reactive Power': Sending state 0.00000 var with 2 decimals of accuracy
[19:13:45][D][sensor:094]: 'SDM630 Phase A Power Factor': Sending state 1.00000  with 3 decimals of accuracy
[19:13:45][D][sensor:094]: 'SDM630 Phase A Phase Angle': Sending state -0.33980 ° with 3 decimals of accuracy
[19:13:45][D][sdm_meter:043]: SDMMeter Phase B: V=229.970 V, I=5.146 A, Active P=1181.593 W, Apparent P=1181.888 VA, Reactive P=-26.412 var, PF=1.000, PA=-1.279 °
[19:13:45][D][sensor:094]: 'SDM630 Phase B Voltage': Sending state 229.96967 V with 2 decimals of accuracy
[19:13:45][D][sensor:094]: 'SDM630 Phase B Current': Sending state 5.14627 A with 3 decimals of accuracy
[19:13:45][D][sensor:094]: 'SDM630 Phase B Power': Sending state 1181.59314 W with 2 decimals of accuracy
[19:13:45][D][sensor:094]: 'SDM630 Phase B Apparent Power': Sending state 1181.88831 VA with 2 decimals of accuracy
[19:13:45][D][sensor:094]: 'SDM630 Phase B Reactive Power': Sending state -26.41234 var with 2 decimals of accuracy
[19:13:45][D][sensor:094]: 'SDM630 Phase B Power Factor': Sending state 0.99975  with 3 decimals of accuracy
[19:13:45][D][sensor:094]: 'SDM630 Phase B Phase Angle': Sending state -1.27880 ° with 3 decimals of accuracy
[19:13:45][D][sdm_meter:043]: SDMMeter Phase C: V=232.561 V, I=4.889 A, Active P=1134.074 W, Apparent P=1136.312 VA, Reactive P=-71.275 var, PF=0.998, PA=-3.594 °
[19:13:45][D][sensor:094]: 'SDM630 Phase C Voltage': Sending state 232.56128 V with 2 decimals of accuracy
[19:13:45][D][sensor:094]: 'SDM630 Phase C Current': Sending state 4.88894 A with 3 decimals of accuracy
[19:13:45][D][sensor:094]: 'SDM630 Phase C Power': Sending state 1134.07422 W with 2 decimals of accuracy
[19:13:45][D][sensor:094]: 'SDM630 Phase C Apparent Power': Sending state 1136.31177 VA with 2 decimals of accuracy
[19:13:45][D][sensor:094]: 'SDM630 Phase C Reactive Power': Sending state -71.27499 var with 2 decimals of accuracy
[19:13:45][D][sensor:094]: 'SDM630 Phase C Power Factor': Sending state 0.99803  with 3 decimals of accuracy
[19:13:45][D][sensor:094]: 'SDM630 Phase C Phase Angle': Sending state -3.59406 ° with 3 decimals of accuracy
[19:13:45][D][sdm_meter:069]: SDMMeter: F=50.013 Hz, Im.A.E=27215.172 Wh, Ex.A.E=0.001 Wh, Im.R.E=1617.445 VARh, Ex.R.E=3165.400 VARh, T.P=3072.319 W
[19:13:45][D][sensor:094]: 'SDM630 Total Power': Sending state 3072.31934 W with 2 decimals of accuracy
[19:13:45][D][sensor:094]: 'SDM630 Frequency': Sending state 50.01290 Hz with 3 decimals of accuracy
[19:13:45][D][sensor:094]: 'SDM630 Import Active Energy': Sending state 27215.17188 kWh with 2 decimals of accuracy
[19:13:45][D][sensor:094]: 'SDM630 Export Active Energy': Sending state 0.00100 kWh with 2 decimals of accuracy
[19:13:45][D][sensor:094]: 'SDM630 Import Reactive Energy': Sending state 1617.44495 kVARh with 2 decimals of accuracy
[19:13:45][D][sensor:094]: 'SDM630 Export Reactive Energy': Sending state 3165.39990 kVARh with 2 decimals of accuracy
[19:13:45][W][component:237]: Component modbus took a long time for an operation (391 ms).
[19:13:45][W][component:238]: Components should block for at most 30 ms.
```

**Comment by exciton** [comment]
Could you turn on verbose logging for modbus and send the full log please?

Also try setting turnaround_time to 200ms.

**Comment by karllinder** [comment]
Thanks for taking the time!

This log have also CRC check to false, logging to Verbose and Debug on UART

```
[20:39:42][V][modbus:221]: Modbus write: 01.04.00.00.00.50.F0.36 (8) at 29993
[20:39:42][D][uart_debug:114]: >>> 01:04:00:00:00:50:F0:36
[20:39:42][V][modbus:067]: Modbus received first Byte  0 (0X0) at 20232
[20:39:42][D][modbus:153]: Modbus CRC Check failed, but ignored! C071!=C200  00.00.00.00.C2 (5)
[20:39:42][W][modbus:184]: Got Modbus frame from unknown address 0x00! 
[20:39:42][V][modbus:310]: Clearing buffer of 5 bytes - parse succeeded at 30032
[20:39:42][V][modbus:067]: Modbus received first Byte  253 (0Xfd) at 30045
[20:39:42][D][modbus:153]: Modbus CRC Check failed, but ignored! CEC2!=7F3F  FD.84.57.3F.7F (5)
[20:39:42][W][modbus:184]: Got Modbus frame from unknown address 0xFD! 
[20:39:42][V][modbus:310]: Clearing buffer of 5 bytes - parse succeeded at 30062
[20:39:42][V][modbus:067]: Modbus received first Byte  208 (0Xd0) at 30076
[20:39:42][D][modbus:153]: Modbus CRC Check failed, but ignored! 3975!=00  D0.0C.00.00.00 (5)
[20:39:42][W][modbus:184]: Got Modbus frame from unknown address 0xD0! 
[20:39:42][V][modbus:310]: Clearing buffer of 5 bytes - parse succeeded at 30094
[20:39:42][V][modbus:067]: Modbus received first Byte  0 (0X0) at 30107
[20:39:42][D][modbus:153]: Modbus CRC Check failed, but ignored! C521!=B54B  00.C0.0C.4B.B5 (5)
[20:39:42][W][modbus:184]: Got Modbus frame from unknown address 0x00! 
[20:39:42][V][modbus:310]: Clearing buffer of 5 bytes - parse succeeded at 30125
[20:39:42][V][modbus:067]: Modbus received first Byte  0 (0X0) at 30139
[20:39:42][D][modbus:153]: Modbus CRC Check failed, but ignored! C071!=4200  00.00.00.00.42 (5)
[20:39:42][W][modbus:184]: Got Modbus frame from unknown address 0x00! 
[20:39:42][V][modbus:310]: Clearing buffer of 5 bytes - parse succeeded at 30156
[20:39:42][V][modbus:067]: Modbus received first Byte  72 (0X48) at 30169
[20:39:42][D][modbus:153]: Modbus CRC Check failed, but ignored! 286B!=3FC2  48.2E.52.46.D4.A7.5B.3A.83.12.6F.44.CA.2F.02.45.45.D9.BA.5E.D8.00.00.01.04.A0.43.65.15.74.43.68.5C.DF.43.6C.52.4E.40.85.2A.E5.40.A7.74.38.40.9E.0C.C4.44.63.E1.96.44.97.CB.4E.44.91.94.A7.44.63.FD.45.44.97.D2.A0.44.91.DF.54.C1.E0.74.24.C1.BC.94.4D.C2.93.86.C2.3F (87)
[20:39:42][W][modbus:184]: Got Modbus frame from unknown address 0x48! 
[20:39:42][V][modbus:310]: Clearing buffer of 87 bytes - parse succeeded at 30214
[20:39:42][V][modbus:067]: Modbus received first Byte  127 (0X7f) at 30216
[20:39:42][D][modbus:153]: Modbus CRC Check failed, but ignored! 59C8!=7F3F  7F.E0.FD.3F.7F (5)
[20:39:42][W][modbus:184]: Got Modbus frame from unknown address 0x7F! 
[20:39:42][V][modbus:310]: Clearing buffer of 5 bytes - parse succeeded at 30245
[20:39:42][V][modbus:067]: Modbus received first Byte  243 (0Xf3) at 30247
[20:39:42][D][modbus:153]: Modbus CRC Check failed, but ignored! 13B6!=7D7F  F3.B7.3F.7F.7D (5)
[20:39:42][W][modbus:184]: Got Modbus frame from unknown address 0xF3! 
[20:39:42][V][modbus:310]: Clearing buffer of 5 bytes - parse succeeded at 30277
[20:39:42][V][modbus:067]: Modbus received first Byte  3 (0X3) at 30279
[20:39:42][D][modbus:153]: Modbus CRC Check failed, but ignored! B831!=E0A3  03.BF.E1.A3.E0 (5)
[20:39:42][W][modbus:184]: Got Modbus frame from unknown address 0x03! 
[20:39:42][V][modbus:310]: Clearing buffer of 5 bytes - parse succeeded at 30308
[20:39:42][V][modbus:067]: Modbus received first Byte  191 (0Xbf) at 30311
[20:39:42][D][modbus:153]: Modbus CRC Check failed, but ignored! 45A4!=C0DE  BF.8E.02.DE.C0 (5)
[20:39:42][W][modbus:184]: Got Modbus frame from unknown address 0xBF! 
[20:39:42][V][modbus:310]: Clearing buffer of 5 bytes - parse succeeded at 30340
[20:39:42][V][modbus:067]: Modbus received first Byte  103 (0X67) at 30342
[20:39:42][D][modbus:153]: Modbus CRC Check failed, but ignored! 734A!=6843  67.E6.11.43.68 (5)
[20:39:42][W][modbus:184]: Got Modbus frame from unknown address 0x67! 
[20:39:42][V][modbus:310]: Clearing buffer of 5 bytes - parse succeeded at 30362
[20:39:42][V][modbus:067]: Modbus received first Byte  150 (0X96) at 30376
[20:39:42][D][modbus:153]: Modbus CRC Check failed, but ignored! BCD9!=00  96.E1.00.00.00 (5)
[20:39:42][W][modbus:184]: Got Modbus frame from unknown address 0x96! 
[20:39:42][V][modbus:310]: Clearing buffer of 5 bytes - parse succeeded at 30394
[20:39:42][V][modbus:067]: Modbus received first Byte  0 (0X0) at 30407
[20:39:42][D][uart_debug:114]: <<< 00:00:00:00:C2:FD:84:57:3F:7F:D0:0C:00:00:00:00:C0:0C:4B:B5:00:00:00:00:42:48:2E:52:46:D4:A7:5B:3A:83:12:6F:44:CA:2F:02:45:45:D9:BA:5E:D8:00:00:01:04:A0:43:65:15:74:43:68:5C:DF:43:6C:52:4E:40:85:2A:E5:40:A7:74:38:40:9E:0C:C4:44:63:E1:96:44:97:CB:4E:44:91:94:A7:44:63:FD:45:44:97:D2:A0:44:91:DF:54:C1:E0:74:24:C1:BC:94:4D:C2:93:86:C2:3F:7F:E0:FD:3F:7F:F3:B7:3F:7F:7D:03:BF:E1:A3:E0:BF:8E:02:DE:C0:67:E6:11:43:68:96:E1:00:00:00:00:40:98:A0:2F:41:64:F0
[20:39:42][W][component:237]: Component modbus took a long time for an operation (468 ms).
[20:39:42][W][component:238]: Components should block for at most 30 ms.
[20:39:42][V][modbus:310]: Clearing buffer of 25 bytes - timeout at 30484
[20:39:42][V][modbus:036]: Stop waiting for response from 1
[20:39:42][D][uart_debug:114]: <<< 47:00:00:00:00:45:4D:A8:60:00:00:00:00:45:4D:D8:4B

[20:39:49][V][sensor:043]: 'Uptime': Received new state 37.179001
[20:39:49][D][sensor:094]: 'Uptime': Sending state 0.00000 h with 0 decimals of accuracy

[20:39:52][V][modbus:221]: Modbus write: 01.04.00.00.00.50.F0.36 (8) at 39996
[20:39:52][D][uart_debug:114]: >>> 01:04:00:00:00:50:F0:36
[20:39:52][V][modbus:067]: Modbus received first Byte  0 (0X0) at 30467
[20:39:52][D][modbus:153]: Modbus CRC Check failed, but ignored! C071!=C200  00.00.00.00.C2 (5)
[20:39:52][W][modbus:184]: Got Modbus frame from unknown address 0x00! 
[20:39:52][V][modbus:310]: Clearing buffer of 5 bytes - parse succeeded at 40036
[20:39:52][V][modbus:067]: Modbus received first Byte  250 (0Xfa) at 40038
[20:39:52][D][modbus:153]: Modbus CRC Check failed, but ignored! 6986!=7F3F  FA.C8.DE.3F.7F (5)
[20:39:52][W][modbus:184]: Got Modbus frame from unknown address 0xFA! 
[20:39:52][V][modbus:310]: Clearing buffer of 5 bytes - parse succeeded at 40067
[20:39:52][V][modbus:067]: Modbus received first Byte  206 (0Xce) at 40070
[20:39:52][D][modbus:153]: Modbus CRC Check failed, but ignored! 6F43!=00  CE.C5.00.00.00 (5)
[20:39:52][W][modbus:184]: Got Modbus frame from unknown address 0xCE! 
[20:39:52][V][modbus:310]: Clearing buffer of 5 bytes - parse succeeded at 40100
[20:39:52][V][modbus:067]: Modbus received first Byte  0 (0X0) at 40102
[20:39:52][D][modbus:153]: Modbus CRC Check failed, but ignored! 4A0!=5227  00.C0.0E.27.52 (5)
[20:39:52][W][modbus:184]: Got Modbus frame from unknown address 0x00! 
[20:39:52][V][modbus:310]: Clearing buffer of 5 bytes - parse succeeded at 40131
[20:39:52][V][modbus:067]: Modbus received first Byte  0 (0X0) at 40134
[20:39:52][D][modbus:153]: Modbus CRC Check failed, but ignored! C071!=4200  00.00.00.00.42 (5)
[20:39:52][W][modbus:184]: Got Modbus frame from unknown address 0x00! 
[20:39:52][V][modbus:310]: Clearing buffer of 5 bytes - parse succeeded at 40152
[20:39:52][V][modbus:067]: Modbus received first Byte  72 (0X48) at 40165
[20:39:52][D][modbus:153]: Modbus CRC Check failed, but ignored! 5765!=A63E  48.24.29.46.D4.A7.60.3A.83.12.6F.44.CA.2F.02.45.45.D9.BA.92.40.00.00.01.04.A0.43.65.7F.28.43.67.FE.D9.43.6B.AE.11.40.87.28.02.40.A7.3E.A6 (46)
[20:39:52][W][modbus:184]: Got Modbus frame from unknown address 0x48! 
[20:39:52][V][modbus:310]: Clearing buffer of 46 bytes - parse succeeded at 40197
[20:39:52][V][modbus:067]: Modbus received first Byte  64 (0X40) at 40210
[20:39:52][D][modbus:153]: Modbus CRC Check failed, but ignored! 6459!=4401  40.9D.7F.01.44 (5)
[20:39:52][W][modbus:184]: Got Modbus frame from unknown address 0x40! 
[20:39:52][V][modbus:310]: Clearing buffer of 5 bytes - parse succeeded at 40229
[20:39:52][V][modbus:067]: Modbus received first Byte  102 (0X66) at 40231
[20:39:52][D][uart_debug:114]: <<< 00:00:00:00:C2:FA:C8:DE:3F:7F:CE:C5:00:00:00:00:C0:0E:27:52:00:00:00:00:42:48:24:29:46:D4:A7:60:3A:83:12:6F:44:CA:2F:02:45:45:D9:BA:92:40:00:00:01:04:A0:43:65:7F:28:43:67:FE:D9:43:6B:AE:11:40:87:28:02:40:A7:3E:A6:40:9D:7F:01:44:66:01:98:44:97:52:1B:44:90:B2:01:44:66:21:58:44:97:5A:F5:44:90:FC:70:C1:F1:A6:94:C1:CF:06:93:C2:92:D6:B7:3F:7F:DC:CC:3F:7F:F1:0B:3F:7F:7C:9E:BF:F0:68:49:BF:9C:B3:04:C0:68:3F:9C:43:68:64:07:00:00:00:00:40:99:07:C4:41:65:8B
[20:39:52][W][component:237]: Component modbus took a long time for an operation (305 ms).
[20:39:52][W][component:238]: Components should block for at most 30 ms.
[20:39:52][V][modbus:310]: Clearing buffer of 91 bytes - timeout at 40324
[20:39:52][D][uart_debug:114]: <<< A6:00:00:00:00:45:4D:82:74:00:00:00:00:45:4D:B4:09
[20:39:52][V][modbus:036]: Stop waiting for response from 1

[20:40:02][D][dallas.temp.sensor:054]: 'Temp': Got Temperature=27.0°C
[20:40:02][V][sensor:043]: 'Temp': Received new state 27.000000
[20:40:02][D][sensor:094]: 'Temp': Sending state 27.00000 °C with 1 decimals of accuracy

[20:40:02][V][modbus:221]: Modbus write: 01.04.00.00.00.50.F0.36 (8) at 49985
[20:40:02][D][uart_debug:114]: >>> 01:04:00:00:00:50:F0:36
[20:40:02][V][modbus:067]: Modbus received first Byte  0 (0X0) at 40307
[20:40:02][D][modbus:153]: Modbus CRC Check failed, but ignored! C071!=C300  00.00.00.00.C3 (5)
[20:40:02][W][modbus:184]: Got Modbus frame from unknown address 0x00! 
[20:40:02][V][modbus:310]: Clearing buffer of 5 bytes - parse succeeded at 50026
[20:40:02][V][modbus:067]: Modbus received first Byte  1 (0X1) at 50029
[20:40:02][D][modbus:153]: Modbus CRC Check failed, but ignored! 5040!=7F3F  01.81.00.3F.7F (5)
[20:40:02][D][modbus:166]: Modbus error function code: 0x81 exception: 0
[20:40:02][V][modbus:310]: Clearing buffer of 5 bytes - parse succeeded at 50047
[20:40:02][V][modbus:067]: Modbus received first Byte  205 (0Xcd) at 50060
[20:40:02][D][modbus:153]: Modbus CRC Check failed, but ignored! CFCD!=00  CD.6F.00.00.00 (5)
[20:40:02][W][modbus:184]: Got Modbus frame from unknown address 0xCD! 
[20:40:02][V][modbus:310]: Clearing buffer of 5 bytes - parse succeeded at 50077
[20:40:02][V][modbus:067]: Modbus received first Byte  0 (0X0) at 50091
[20:40:02][D][modbus:153]: Modbus CRC Check failed, but ignored! C20!=7D11  00.C0.10.11.7D (5)
[20:40:02][W][modbus:184]: Got Modbus frame from unknown address 0x00! 
[20:40:02][V][modbus:310]: Clearing buffer of 5 bytes - parse succeeded at 50112
[20:40:02][V][modbus:067]: Modbus received first Byte  0 (0X0) at 50113
[20:40:02][D][modbus:153]: Modbus CRC Check failed, but ignored! C071!=4200  00.00.00.00.42 (5)
[20:40:02][W][modbus:184]: Got Modbus frame from unknown address 0x00! 
[20:40:02][V][modbus:310]: Clearing buffer of 5 bytes - parse succeeded at 50143
[20:40:02][V][modbus:067]: Modbus received first Byte  72 (0X48) at 50145
[20:40:02][D][modbus:153]: Modbus CRC Check failed, but ignored! ED7!=CA44  48.30.08.46.D4.A7.64.3A.83.12.6F.44.CA (13)
[20:40:02][W][modbus:184]: Got Modbus frame from unknown address 0x48! 
[20:40:02][V][modbus:310]: Clearing buffer of 13 bytes - parse succeeded at 50175
[20:40:02][V][modbus:067]: Modbus received first Byte  47 (0X2f) at 50178
[20:40:02][D][modbus:153]: Modbus CRC Check failed, but ignored! 4082!=3F8F  2F.02.45.45.D9.BA.5F.AC.00.00.01.04.A0.43.65.BE.EB.43.68.6A.D3.43.6B.F8.B5.40.87.53.25.40.A7.7D.C5.40.9D.C2.69.44.68.A1.EF.44.97.D0.18.44.91.0C.8C.44.68.C0.30.44.97.D8.AC.44.91.56.B8.C1.ED.4D.E0.C1.CC.23.75.C2.92.C2.8F.3F (74)
[20:40:02][W][modbus:184]: Got Modbus frame from unknown address 0x2F! 
[20:40:02][V][modbus:310]: Clearing buffer of 74 bytes - parse succeeded at 50222
[20:40:02][V][modbus:067]: Modbus received first Byte  127 (0X7f) at 50234
[20:40:02][D][modbus:153]: Modbus CRC Check failed, but ignored! 918!=7F3F  7F.DE.BC.3F.7F (5)
[20:40:02][W][modbus:184]: Got Modbus frame from unknown address 0x7F! 
[20:40:02][V][modbus:310]: Clearing buffer of 5 bytes - parse succeeded at 50252
[20:40:02][V][modbus:067]: Modbus received first Byte  241 (0Xf1) at 50266
[20:40:02][D][modbus:153]: Modbus CRC Check failed, but ignored! B308!=7D7F  F1.9D.3F.7F.7D (5)
[20:40:02][W][modbus:184]: Got Modbus frame from unknown address 0xF1! 
[20:40:02][V][modbus:310]: Clearing buffer of 5 bytes - parse succeeded at 50284
[20:40:02][V][modbus:067]: Modbus received first Byte  138 (0X8a) at 50297
[20:40:02][D][modbus:153]: Modbus CRC Check failed, but ignored! 94E1!=5EB3  8A.BF.E9.B3.5E (5)
[20:40:02][W][modbus:184]: Got Modbus frame from unknown address 0x8A! 
[20:40:02][V][modbus:310]: Clearing buffer of 5 bytes - parse succeeded at 50317
[20:40:02][V][modbus:067]: Modbus received first Byte  191 (0Xbf) at 50330
[20:40:02][D][modbus:153]: Modbus CRC Check failed, but ignored! C8AB!=C094  BF.99.AE.94.C0 (5)
[20:40:02][W][modbus:184]: Got Modbus frame from unknown address 0xBF! 
[20:40:02][V][modbus:310]: Clearing buffer of 5 bytes - parse succeeded at 50347
[20:40:02][V][modbus:067]: Modbus received first Byte  103 (0X67) at 50360
[20:40:02][D][uart_debug:114]: <<< 00:00:00:00:C3:01:81:00:3F:7F:CD:6F:00:00:00:00:C0:10:11:7D:00:00:00:00:42:48:30:08:46:D4:A7:64:3A:83:12:6F:44:CA:2F:02:45:45:D9:BA:5F:AC:00:00:01:04:A0:43:65:BE:EB:43:68:6A:D3:43:6B:F8:B5:40:87:53:25:40:A7:7D:C5:40:9D:C2:69:44:68:A1:EF:44:97:D0:18:44:91:0C:8C:44:68:C0:30:44:97:D8:AC:44:91:56:B8:C1:ED:4D:E0:C1:CC:23:75:C2:92:C2:8F:3F:7F:DE:BC:3F:7F:F1:9D:3F:7F:7D:8A:BF:E9:B3:5E:BF:99:AE:94:C0:67:6E:9B:43:68:B6:27:00:00:00:00:40:99:41:92:41:65:E2
[20:40:02][W][component:237]: Component modbus took a long time for an operation (429 ms).
[20:40:02][W][component:238]: Components should block for at most 30 ms.
[20:40:02][V][modbus:310]: Clearing buffer of 35 bytes - timeout at 50426
[20:40:02][D][uart_debug:114]: <<< 5B:00:00:00:00:45:4E:9B:C2:00:00:00:00:45:4E:CD:0A

[20:40:03][V][sensor:043]: 'WiFi Signal': Received new state -71.000000
[20:40:03][D][sensor:094]: 'WiFi Signal': Sending state -71.00000 dBm with 0 decimals of accuracy

[20:40:12][V][modbus:221]: Modbus write: 01.04.00.00.00.50.F0.36 (8) at 59998
[20:40:12][D][uart_debug:114]: >>> 01:04:00:00:00:50:F0:36
[20:40:12][V][modbus:067]: Modbus received first Byte  0 (0X0) at 50420
[20:40:12][D][modbus:153]: Modbus CRC Check failed, but ignored! C071!=C300  00.00.00.00.C3 (5)
[20:40:12][W][modbus:184]: Got Modbus frame from unknown address 0x00! 
[20:40:12][V][modbus:310]: Clearing buffer of 5 bytes - parse succeeded at 60037
[20:40:12][V][modbus:067]: Modbus received first Byte  0 (0X0) at 60039
[20:40:12][D][modbus:153]: Modbus CRC Check failed, but ignored! D7C2!=7F3F  00.BB.75.3F.7F (5)
[20:40:12][W][modbus:184]: Got Modbus frame from unknown address 0x00! 
[20:40:12][V][modbus:310]: Clearing buffer of 5 bytes - parse succeeded at 60068
[20:40:12][V][modbus:067]: Modbus received first Byte  206 (0Xce) at 60070
[20:40:12][D][modbus:153]: Modbus CRC Check failed, but ignored! FF71!=00  CE.80.00.00.00 (5)
[20:40:12][W][modbus:184]: Got Modbus frame from unknown address 0xCE! 
[20:40:12][V][modbus:310]: Clearing buffer of 5 bytes - parse succeeded at 60099
[20:40:12][V][modbus:067]: Modbus received first Byte  0 (0X0) at 60101
[20:40:12][D][modbus:153]: Modbus CRC Check failed, but ignored! 4A0!=2B8A  00.C0.0E.8A.2B (5)
[20:40:12][W][modbus:184]: Got Modbus frame from unknown address 0x00! 
[20:40:12][V][modbus:310]: Clearing buffer of 5 bytes - parse succeeded at 60130
[20:40:12][V][modbus:067]: Modbus received first Byte  0 (0X0) at 60132
[20:40:12][D][modbus:153]: Modbus CRC Check failed, but ignored! C071!=4200  00.00.00.00.42 (5)
[20:40:12][W][modbus:184]: Got Modbus frame from unknown address 0x00! 
[20:40:12][V][modbus:310]: Clearing buffer of 5 bytes - parse succeeded at 60161
[20:40:12][V][modbus:067]: Modbus received first Byte  72 (0X48) at 60163
[20:40:12][D][uart_debug:114]: <<< 00:00:00:00:C3:00:BB:75:3F:7F:CE:80:00:00:00:00:C0:0E:8A:2B:00:00:00:00:42:48:30:EC:46:D4:A7:69:3A:83:12:6F:44:CA:2F:02:45:45:D9:BE:2D:67:00:00:01:04:A0:43:65:8C:28:43:68:37:04:43:6B:D1:2E:40:85:78:1D:40:A7:5F:4E:40:9D:A9:E9:44:64:5F:E9:44:97:97:7C:44:90:DE:50:44:64:7E:9A:44:97:9E:EE:44:91:28:D4:C1:EC:9F:2C:C1:BE:07:34:C2:93:02:64:3F:7F:DD:AF:3F:7F:F3:81:3F:7F:7C:9F:BF:ED:5B:BD:BF:8F:39:BB:C0:68:3E:BB:43:68:86:C9:00:00:00:00:40:98:91:D9:41:64:DA
[20:40:12][W][component:237]: Component modbus took a long time for an operation (237 ms).
[20:40:12][W][component:238]: Components should block for at most 30 ms.
[20:40:12][I][safe_mode:041]: Boot seems successful; resetting boot loop counter
[20:40:12][D][esp32.preferences:114]: Saving 1 preferences to flash...
[20:40:12][V][esp32.preferences:126]: sync: key: 233825507, len: 4
[20:40:12][D][esp32.preferences:143]: Saving 1 preferences to flash: 0 cached, 1 written, 0 failed
[20:40:12][V][modbus:310]: Clearing buffer of 142 bytes - timeout at 60297
[20:40:12][D][uart_debug:114]: <<< C5:00:00:00:00:45:4D:52:E0:00:00:00:00:45:4D:83:88
[20:40:12][V][modbus:036]: Stop waiting for response from 1

[20:40:22][V][modbus:221]: Modbus write: 01.04.00.00.00.50.F0.36 (8) at 69991
[20:40:22][D][uart_debug:114]: >>> 01:04:00:00:00:50:F0:36
[20:40:22][V][modbus:067]: Modbus received first Byte  0 (0X0) at 60240
[20:40:22][D][modbus:153]: Modbus CRC Check failed, but ignored! C071!=C200  00.00.00.00.C2 (5)
[20:40:22][W][modbus:184]: Got Modbus frame from unknown address 0x00! 
[20:40:22][V][modbus:310]: Clearing buffer of 5 bytes - parse succeeded at 70027
[20:40:22][V][modbus:067]: Modbus received first Byte  253 (0Xfd) at 70040
[20:40:22][D][modbus:153]: Modbus CRC Check failed, but ignored! 419F!=7F3F  FD.AB.FC.3F.7F (5)
[20:40:22][W][modbus:184]: Got Modbus frame from unknown address 0xFD! 
[20:40:22][V][modbus:310]: Clearing buffer of 5 bytes - parse succeeded at 70059
[20:40:22][V][modbus:067]: Modbus received first Byte  208 (0Xd0) at 70072
[20:40:22][D][modbus:153]: Modbus CRC Check failed, but ignored! A92E!=00  D0.D5.00.00.00 (5)
[20:40:22][W][modbus:184]: Got Modbus frame from unknown address 0xD0! 
[20:40:22][V][modbus:310]: Clearing buffer of 5 bytes - parse succeeded at 70090
[20:40:22][V][modbus:067]: Modbus received first Byte  0 (0X0) at 70103
[20:40:22][D][modbus:153]: Modbus CRC Check failed, but ignored! 760!=3524  00.C0.0B.24.35 (5)
[20:40:22][W][modbus:184]: Got Modbus frame from unknown address 0x00! 
[20:40:22][V][modbus:310]: Clearing buffer of 5 bytes - parse succeeded at 70121
[20:40:22][V][modbus:067]: Modbus received first Byte  0 (0X0) at 70134
[20:40:22][D][modbus:153]: Modbus CRC Check failed, but ignored! C071!=4200  00.00.00.00.42 (5)
[20:40:22][W][modbus:184]: Got Modbus frame from unknown address 0x00! 
[20:40:22][V][modbus:310]: Clearing buffer of 5 bytes - parse succeeded at 70152
[20:40:22][V][modbus:067]: Modbus received first Byte  72 (0X48) at 70167
[20:40:22][D][modbus:153]: Modbus CRC Check failed, but ignored! E47!=5A7C  48.17.5D.46.D4.A7.6F.3A.83.12.6F.44.CA.2F.02.45.45.D9.BE.FB.CC.00.00.01.04.A0.43.65.20.F7.43.68.63.27.43.6C.0F.B9.40.84.D5.3A.40.A7.72.6A.40.9D.CB.04.44.64.4E.05.44.97.D9.F6.44.91.35.53.44.64.6B.B5.44.97.E1.6B.44.91.80.3D.C1.E3.9D.23.C1.CB.1C.11.C2.93.96.36.3F.7F.E0.3F.3F.7F.F1.B6.3F.7F.7C.5A (98)
[20:40:22][W][modbus:184]: Got Modbus frame from unknown address 0x48! 
[20:40:22][V][modbus:310]: Clearing buffer of 98 bytes - parse succeeded at 70212
[20:40:22][V][modbus:067]: Modbus received first Byte  191 (0Xbf) at 70225
[20:40:22][D][modbus:153]: Modbus CRC Check failed, but ignored! 194B!=BF66  BF.E4.53.66.BF (5)
[20:40:22][W][modbus:184]: Got Modbus frame from unknown address 0xBF! 
[20:40:22][V][modbus:310]: Clearing buffer of 5 bytes - parse succeeded at 70242
[20:40:22][V][modbus:067]: Modbus received first Byte  153 (0X99) at 70255
[20:40:22][D][uart_debug:114]: <<< 00:00:00:00:C2:FD:AB:FC:3F:7F:D0:D5:00:00:00:00:C0:0B:24:35:00:00:00:00:42:48:17:5D:46:D4:A7:6F:3A:83:12:6F:44:CA:2F:02:45:45:D9:BE:FB:CC:00:00:01:04:A0:43:65:20:F7:43:68:63:27:43:6C:0F:B9:40:84:D5:3A:40:A7:72:6A:40:9D:CB:04:44:64:4E:05:44:97:D9:F6:44:91:35:53:44:64:6B:B5:44:97:E1:6B:44:91:80:3D:C1:E3:9D:23:C1:CB:1C:11:C2:93:96:36:3F:7F:E0:3F:3F:7F:F1:B6:3F:7F:7C:5A:BF:E4:53:66:BF:99:28:C9:C0:68:7B:61:43:68:86:9D:00:00:00:00:40:98:6D:48:41:64:A3
[20:40:22][W][component:237]: Component modbus took a long time for an operation (320 ms).
[20:40:22][W][component:238]: Components should block for at most 30 ms.
[20:40:22][V][modbus:310]: Clearing buffer of 39 bytes - timeout at 70333
[20:40:22][D][uart_debug:114]: <<< EC:00:00:00:00:45:4D:7E:AD:00:00:00:00:45:4D:AF:7F
[20:40:22][V][modbus:036]: Stop waiting for response from 1

[20:40:32][V][modbus:221]: Modbus write: 01.04.00.00.00.50.F0.36 (8) at 79993
[20:40:32][D][uart_debug:114]: >>> 01:04:00:00:00:50:F0:36
[20:40:32][V][modbus:067]: Modbus received first Byte  0 (0X0) at 70316
[20:40:32][D][modbus:153]: Modbus CRC Check failed, but ignored! C071!=C200  00.00.00.00.C2 (5)
[20:40:32][W][modbus:184]: Got Modbus frame from unknown address 0x00! 
[20:40:32][V][modbus:310]: Clearing buffer of 5 bytes - parse succeeded at 80030
[20:40:32][V][modbus:067]: Modbus received first Byte  255 (0Xff) at 80043
[20:40:32][V][modbus:310]: Clearing buffer of 42 bytes - timeout at 80064
[20:40:32][V][modbus:067]: Modbus received first Byte  0 (0X0) at 80048
[20:40:32][D][modbus:153]: Modbus CRC Check failed, but ignored! 3452!=43A9  00.01.04.A0.43.65.83.A9.43 (9)
[20:40:32][W][modbus:184]: Got Modbus frame from unknown address 0x00! 
[20:40:32][V][modbus:310]: Clearing buffer of 9 bytes - parse succeeded at 80158
[20:40:32][V][modbus:067]: Modbus received first Byte  103 (0X67) at 80160
[20:40:32][D][modbus:153]: Modbus CRC Check failed, but ignored! C307!=6B43  67.F7.6E.43.6B (5)
[20:40:32][W][modbus:184]: Got Modbus frame from unknown address 0x67! 
[20:40:32][V][modbus:310]: Clearing buffer of 5 bytes - parse succeeded at 80190
[20:40:32][V][modbus:067]: Modbus received first Byte  216 (0Xd8) at 80192
[20:40:32][D][modbus:153]: Modbus CRC Check failed, but ignored! CB80!=5C85  D8.BC.40.85.5C (5)
[20:40:32][W][modbus:184]: Got Modbus frame from unknown address 0xD8! 
[20:40:32][V][modbus:310]: Clearing buffer of 5 bytes - parse succeeded at 80221
[20:40:32][V][modbus:067]: Modbus received first Byte  44 (0X2c) at 80223
[20:40:32][D][uart_debug:114]: <<< 00:00:00:00:C2:FF:44:83:3F:7F:CE:BE:00:00:00:00:C0:0E:31:6F:00:00:00:00:42:48:12:C4:46:D4:A7:73:3A:83:12:6F:44:CA:2F:02:45:45:D9:C3:C6:5D:00:00:01:04:A0:43:65:83:A9:43:67:F7:6E:43:6B:D8:BC:40:85:5C:2C:40:A7:37:6E:40:9D:BF:8A:44:64:98:44:44:97:4E:1E:44:90:F1:96:44:64:B4:07:44:97:56:A3:44:91:3C:2E:C1:E1:20:27:C1:CB:16:B1:C2:93:1F:F4:3F:7F:E0:FD:3F:7F:F1:9D:3F:7F:7C:C1:BF:E1:A3:E0:BF:99:AE:94:C0:68:20:99:43:68:71:47:00:00:00:00:40:98:82:82:41:64:C3
[20:40:32][W][component:237]: Component modbus took a long time for an operation (160 ms).
[20:40:32][W][component:238]: Components should block for at most 30 ms.
[20:40:32][V][modbus:310]: Clearing buffer of 101 bytes - timeout at 80347
[20:40:32][D][uart_debug:114]: <<< C3:00:00:00:00:45:4D:59:A3:00:00:00:00:45:4D:88:C9
[20:40:32][V][modbus:036]: Stop waiting for response from 1

[20:40:42][V][modbus:221]: Modbus write: 01.04.00.00.00.50.F0.36 (8) at 89994
[20:40:42][D][uart_debug:114]: >>> 01:04:00:00:00:50:F0:36
[20:40:42][V][modbus:067]: Modbus received first Byte  0 (0X0) at 80297
[20:40:42][D][modbus:153]: Modbus CRC Check failed, but ignored! C071!=C200  00.00.00.00.C2 (5)
[20:40:42][W][modbus:184]: Got Modbus frame from unknown address 0x00! 
[20:40:42][V][modbus:310]: Clearing buffer of 5 bytes - parse succeeded at 90032
[20:40:42][V][modbus:067]: Modbus received first Byte  248 (0Xf8) at 90045
[20:40:42][D][modbus:153]: Modbus CRC Check failed, but ignored! 5299!=7F3F  F8.9C.84.3F.7F (5)
[20:40:42][W][modbus:184]: Got Modbus frame from unknown address 0xF8! 
[20:40:42][V][modbus:310]: Clearing buffer of 5 bytes - parse succeeded at 90063
[20:40:42][V][modbus:067]: Modbus received first Byte  209 (0Xd1) at 90076
[20:40:42][D][modbus:153]: Modbus CRC Check failed, but ignored! 9931!=00  D1.3E.00.00.00 (5)
[20:40:42][W][modbus:184]: Got Modbus frame from unknown address 0xD1! 
[20:40:42][V][modbus:310]: Clearing buffer of 5 bytes - parse succeeded at 90093
[20:40:42][V][modbus:067]: Modbus received first Byte  0 (0X0) at 90106
[20:40:42][D][modbus:153]: Modbus CRC Check failed, but ignored! C7A1!=DE88  00.C0.0A.88.DE (5)
[20:40:42][W][modbus:184]: Got Modbus frame from unknown address 0x00! 
[20:40:42][V][modbus:310]: Clearing buffer of 5 bytes - parse succeeded at 90125
[20:40:42][V][modbus:067]: Modbus received first Byte  0 (0X0) at 90139
[20:40:42][D][modbus:153]: Modbus CRC Check failed, but ignored! C071!=4200  00.00.00.00.42 (5)
[20:40:42][W][modbus:184]: Got Modbus frame from unknown address 0x00! 
[20:40:42][V][modbus:310]: Clearing buffer of 5 bytes - parse succeeded at 90157
[20:40:42][V][modbus:067]: Modbus received first Byte  72 (0X48) at 90170
[20:40:42][D][uart_debug:114]: <<< 00:00:00:00:C2:F8:9C:84:3F:7F:D1:3E:00:00:00:00:C0:0A:88:DE:00:00:00:00:42:48:19:9C:46:D4:A7:77:3A:83:12:6F:44:CA:2F:02:45:45:D9:C3:9B:38:00:00:01:04:A0:43:65:48:94:43:67:E9:D5:43:6C:38:16:40:83:CA:90:40:A7:25:32:40:9D:D6:4E:44:64:52:0D:44:97:5B:38:44:91:6F:B3:44:64:6C:8B:44:97:63:0F:44:91:B9:08:C1:DB:C2:BE:C1:C2:DB:8A:C2:92:1F:48:3F:7F:E2:63:3F:7F:F2:BE:3F:7F:7F:6B:BF:DC:7F:93:BF:93:87:08:C0:65:C1:E2:43:68:78:D5:00:00:00:00:40:97:FE:F2:41:63:FE
[20:40:42][W][component:237]: Component modbus took a long time for an operation (237 ms).
[20:40:42][W][component:238]: Components should block for at most 30 ms.
[20:40:42][V][modbus:310]: Clearing buffer of 142 bytes - timeout at 90287
[20:40:42][D][uart_debug:114]: <<< 6B:00:00:00:00:45:4D:79:F9:00:00:00:00:45:4D:A9:2E
[20:40:42][V][modbus:036]: Stop waiting for response from 1

[20:40:49][V][sensor:043]: 'Uptime': Received new state 97.183998
[20:40:49][D][sensor:094]: 'Uptime': Sending state 0.00000 h with 0 decimals of accuracy
[20:40:52][V][modbus:221]: Modbus write: 01.04.00.00.00.50.F0.36 (8) at 99998
[20:40:52][D][uart_debug:114]: >>> 01:04:00:00:00:50:F0:36
[20:40:52][V][modbus:067]: Modbus received first Byte  0 (0X0) at 90237
[20:40:52][D][modbus:153]: Modbus CRC Check failed, but ignored! C071!=C200  00.00.00.00.C2 (5)
[20:40:52][W][modbus:184]: Got Modbus frame from unknown address 0x00! 
[20:40:52][V][modbus:310]: Clearing buffer of 5 bytes - parse succeeded at 100037
[20:40:52][V][modbus:067]: Modbus received first Byte  249 (0Xf9) at 100050
[20:40:52][D][modbus:153]: Modbus CRC Check failed, but ignored! CA73!=7F3F  F9.C6.DA.3F.7F (5)
[20:40:52][W][modbus:184]: Got Modbus frame from unknown address 0xF9! 
[20:40:52][V][modbus:310]: Clearing buffer of 5 bytes - parse succeeded at 100068
[20:40:52][V][modbus:067]: Modbus received first Byte  208 (0Xd0) at 100081
[20:40:52][D][modbus:153]: Modbus CRC Check failed, but ignored! 927!=00  D0.CB.00.00.00 (5)
[20:40:52][W][modbus:184]: Got Modbus frame from unknown address 0xD0! 
[20:40:52][V][modbus:310]: Clearing buffer of 5 bytes - parse succeeded at 100098
[20:40:52][V][modbus:067]: Modbus received first Byte  0 (0X0) at 100111
[20:40:52][D][modbus:153]: Modbus CRC Check failed, but ignored! 760!=F832  00.C0.0B.32.F8 (5)
[20:40:52][W][modbus:184]: Got Modbus frame from unknown address 0x00! 
[20:40:52][V][modbus:310]: Clearing buffer of 5 bytes - parse succeeded at 100129
[20:40:52][V][modbus:067]: Modbus received first Byte  0 (0X0) at 100142
[20:40:52][D][modbus:153]: Modbus CRC Check failed, but ignored! C071!=4200  00.00.00.00.42 (5)
[20:40:52][W][modbus:184]: Got Modbus frame from unknown address 0x00! 
[20:40:52][V][modbus:310]: Clearing buffer of 5 bytes - parse succeeded at 100160
[20:40:52][V][modbus:067]: Modbus received first Byte  72 (0X48) at 100174
[20:40:52][D][uart_debug:114]: <<< 00:00:00:00:C2:F9:C6:DA:3F:7F:D0:CB:00:00:00:00:C0:0B:32:F8:00:00:00:00:42:48:20:81:46:D4:A7:7C:3A:83:12:6F:44:CA:2F:02:45:45:D9:C3:CB:A9:00:00:01:04:A0:43:65:71:63:43:67:8E:CA:43:6C:05:F0:40:85:2A:6F:40:A6:FA:EA:40:9D:BB:54:44:66:91:CE:44:96:DD:47:44:91:0C:61:44:66:AE:93:44:96:E4:E3:44:91:56:16:C1:E6:3A:5F:C1:BF:AA:7B:C2:92:4C:4C:3F:7F:DF:FF:3F:7F:F2:30:3F:7F:7E:D3:BF:E5:39:2A:BF:96:95:37:C0:66:49:D8:43:68:57:60:00:00:00:00:40:98:5C:73:41:64:8A
[20:40:52][D][modbus:153]: Modbus CRC Check failed, but ignored! D6EB!=383C  48.20.81.46.D4.A7.7C.3A.83.12.6F.44.CA.2F.02.45.45.D9.C3.CB.A9.00.00.01.04.A0.43.65.71.63.43.67.8E.CA.43.6C.05.F0.40.85.2A.6F.40.A6.FA.EA.40.9D.BB.54.44.66.91.CE.44.96.DD.47.44.91.0C.61.44.66.AE.93.44.96.E4.E3.44.91.56.16.C1.E6.3A.5F.C1.BF.AA.7B.C2.92.4C.4C.3F.7F.DF.FF.3F.7F.F2.30.3F.7F.7E.D3.BF.E5.39.2A.BF.96.95.37.C0.66.49.D8.43.68.57.60.00.00.00.00.40.98.5C.73.41.64.8A.AD.00.00.00.00.45.4D.3C.38 (134)
[20:40:52][W][modbus:184]: Got Modbus frame from unknown address 0x48! 
[20:40:52][V][modbus:310]: Clearing buffer of 134 bytes - parse succeeded at 100287
[20:40:52][V][modbus:067]: Modbus received first Byte  0 (0X0) at 100300
[20:40:52][D][modbus:153]: Modbus CRC Check failed, but ignored! C071!=4500  00.00.00.00.45 (5)
[20:40:52][W][modbus:184]: Got Modbus frame from unknown address 0x00! 
[20:40:52][V][modbus:310]: Clearing buffer of 5 bytes - parse succeeded at 100317
[20:40:52][V][modbus:067]: Modbus received first Byte  77 (0X4d) at 100330
[20:40:52][W][component:237]: Component modbus took a long time for an operation (329 ms).
[20:40:52][W][component:238]: Components should block for at most 30 ms.
[20:40:52][V][modbus:310]: Clearing buffer of 3 bytes - timeout at 100349
[20:40:52][D][uart_debug:114]: <<< AD:00:00:00:00:45:4D:3C:38:00:00:00:00:45:4D:6C:49
[20:40:52][V][modbus:036]: Stop waiting for response from 1

```

**Comment by exciton** [comment]
Could you turn CRC checks back on please, and include the log from the very beginning so I can see the configuration section? 

What I can see is that the start of the response is cut off (should start with 0x01 - the address of the device) and not 0x00.

**Comment by karllinder** [comment]
Thanks again, here is the log from the start.

```

NFO OTA successful
INFO Successfully uploaded program.
INFO Starting log output from 192.168.1.12 using esphome API
INFO Successfully connected to utilhouse @ 192.168.1.12 in 7.214s
INFO Successful handshake with utilhouse @ 192.168.1.12 in 0.381s
[21:40:53][I][app:100]: ESPHome version 2024.12.2 compiled on Jan  5 2025, 21:38:45
[21:40:53][C][status_led:019]: Status LED:
[21:40:53][C][status_led:020]:   Pin: GPIO25
[21:40:53][C][wifi:600]: WiFi:
[21:40:53][C][wifi:428]:   Local MAC: 7C:9E:BD:F3:1A:34
[21:40:53][C][wifi:433]:   SSID: [redacted]
[21:40:53][C][wifi:436]:   IP Address: 192.168.1.12
[21:40:53][C][wifi:440]:   BSSID: [redacted]
[21:40:53][C][wifi:441]:   Hostname: 'utilhouse'
[21:40:53][C][wifi:443]:   Signal strength: -64 dB ▂▄▆█
[21:40:53][V][wifi:445]:   Priority: 0.0
[21:40:53][C][wifi:447]:   Channel: 6
[21:40:53][C][wifi:448]:   Subnet: 255.255.255.0
[21:40:53][C][wifi:449]:   Gateway: 192.168.1.1
[21:40:53][C][wifi:450]:   DNS1: 8.8.8.8
[21:40:53][C][wifi:451]:   DNS2: 1.1.1.1
[21:40:53][C][logger:185]: Logger:
[21:40:53][C][logger:186]:   Level: VERBOSE
[21:40:53][C][logger:188]:   Log Baud Rate: 115200
[21:40:53][C][logger:189]:   Hardware UART: UART0
[21:40:53][C][gpio.one_wire:020]: GPIO 1-wire bus:
[21:40:53][C][gpio.one_wire:021]:   Pin: GPIO32
[21:40:53][C][gpio.one_wire:080]:   Found devices:
[21:40:53][C][gpio.one_wire:082]:     0xa73c01f09514a628 (DS18B20)
[21:40:53][C][uart.arduino_esp32:151]: UART Bus 1:
[21:40:54][C][uart.arduino_esp32:152]:   TX Pin: GPIO17
[21:40:54][C][uart.arduino_esp32:153]:   RX Pin: GPIO16
[21:40:54][C][uart.arduino_esp32:155]:   RX Buffer Size: 256
[21:40:54][C][uart.arduino_esp32:157]:   Baud Rate: 38400 baud
[21:40:54][C][uart.arduino_esp32:158]:   Data Bits: 8
[21:40:54][C][uart.arduino_esp32:159]:   Parity: EVEN
[21:40:54][C][uart.arduino_esp32:160]:   Stop bits: 1
[21:40:54][C][modbus:230]: Modbus:
[21:40:54][C][modbus:231]:   Flow Control Pin: GPIO5
[21:40:54][C][modbus:232]:   Send Wait Time: 500 ms
[21:40:54][C][modbus:233]:   Turnaround Time: 800 ms
[21:40:54][C][modbus:234]:   Frame Delay: 2 ms
[21:40:54][C][modbus:235]:   Long Rx Buffer Delay: 35 ms
[21:40:54][C][modbus:236]:   CRC Disabled: NO
[21:40:54][C][uptime.sensor:033]: Uptime Sensor 'Uptime'
[21:40:54][C][uptime.sensor:033]:   Device Class: 'duration'
[21:40:54][C][uptime.sensor:033]:   State Class: 'total_increasing'
[21:40:54][C][uptime.sensor:033]:   Unit of Measurement: 'h'
[21:40:54][C][uptime.sensor:033]:   Accuracy Decimals: 0
[21:40:54][C][uptime.sensor:033]:   Icon: 'mdi:timer-outline'
[21:40:54][V][uptime.sensor:033]:   Unique ID: '7c9ebdf31a34-uptime'
[21:40:54][C][uptime.sensor:034]:   Type: Seconds
[21:40:54][C][dallas.temp.sensor:029]: Dallas Temperature Sensor:
[21:40:54][C][dallas.temp.sensor:034]:   Address: 0xa73c01f09514a628 (DS18B20)
[21:40:54][C][dallas.temp.sensor:035]:   Resolution: 12 bits
[21:40:54][C][dallas.temp.sensor:036]:   Update Interval: 60.0s
[21:40:54][C][sdm_meter:087]: SDM Meter:
[21:40:54][C][sdm_meter:088]:   Address: 0x01
[21:40:54][C][sdm_meter:093]:   Phase A
[21:40:54][C][sdm_meter:094]:     Voltage 'SDM630 Phase A Voltage'
[21:40:54][C][sdm_meter:094]:       Device Class: 'voltage'
[21:40:54][C][sdm_meter:094]:       State Class: 'measurement'
[21:40:54][C][sdm_meter:094]:       Unit of Measurement: 'V'
[21:40:54][C][sdm_meter:094]:       Accuracy Decimals: 2
[21:40:54][C][sdm_meter:095]:     Current 'SDM630 Phase A Current'
[21:40:54][C][sdm_meter:095]:       Device Class: 'current'
[21:40:54][C][sdm_meter:095]:       State Class: 'measurement'
[21:40:54][C][sdm_meter:095]:       Unit of Measurement: 'A'
[21:40:54][C][sdm_meter:095]:       Accuracy Decimals: 3
[21:40:54][C][sdm_meter:096]:     Active Power 'SDM630 Phase A Power'
[21:40:54][C][sdm_meter:096]:       Device Class: 'power'
[21:40:54][C][sdm_meter:096]:       State Class: 'measurement'
[21:40:54][C][sdm_meter:096]:       Unit of Measurement: 'W'
[21:40:54][C][sdm_meter:096]:       Accuracy Decimals: 2
[21:40:54][C][sdm_meter:097]:     Apparent Power 'SDM630 Phase A Apparent Power'
[21:40:54][C][sdm_meter:097]:       State Class: 'measurement'
[21:40:54][C][sdm_meter:097]:       Unit of Measurement: 'VA'
[21:40:54][C][sdm_meter:097]:       Accuracy Decimals: 2
[21:40:54][C][sdm_meter:098]:     Reactive Power 'SDM630 Phase A Reactive Power'
[21:40:54][C][sdm_meter:098]:       State Class: 'measurement'
[21:40:54][C][sdm_meter:098]:       Unit of Measurement: 'var'
[21:40:54][C][sdm_meter:098]:       Accuracy Decimals: 2
[21:40:54][C][sdm_meter:099]:     Power Factor 'SDM630 Phase A Power Factor'
[21:40:54][C][sdm_meter:099]:       Device Class: 'power_factor'
[21:40:54][C][sdm_meter:099]:       State Class: 'measurement'
[21:40:54][C][sdm_meter:099]:       Unit of Measurement: ''
[21:40:54][C][sdm_meter:099]:       Accuracy Decimals: 3
[21:40:54][C][sdm_meter:100]:     Phase Angle 'SDM630 Phase A Phase Angle'
[21:40:54][C][sdm_meter:100]:       State Class: ''
[21:40:54][C][sdm_meter:100]:       Unit of Measurement: '°'
[21:40:54][C][sdm_meter:100]:       Accuracy Decimals: 3
[21:40:54][C][sdm_meter:100]:       Icon: 'mdi:flash'
[21:40:54][C][sdm_meter:093]:   Phase B
[21:40:54][C][sdm_meter:094]:     Voltage 'SDM630 Phase B Voltage'
[21:40:54][C][sdm_meter:094]:       Device Class: 'voltage'
[21:40:54][C][sdm_meter:094]:       State Class: 'measurement'
[21:40:54][C][sdm_meter:094]:       Unit of Measurement: 'V'
[21:40:54][C][sdm_meter:094]:       Accuracy Decimals: 2
[21:40:54][C][sdm_meter:095]:     Current 'SDM630 Phase B Current'
[21:40:54][C][sdm_meter:095]:       Device Class: 'current'
[21:40:54][C][sdm_meter:095]:       State Class: 'measurement'
[21:40:54][C][sdm_meter:095]:       Unit of Measurement: 'A'
[21:40:54][C][sdm_meter:095]:       Accuracy Decimals: 3
[21:40:54][C][sdm_meter:096]:     Active Power 'SDM630 Phase B Power'
[21:40:54][C][sdm_meter:096]:       Device Class: 'power'
[21:40:54][C][sdm_meter:096]:       State Class: 'measurement'
[21:40:54][C][sdm_meter:096]:       Unit of Measurement: 'W'
[21:40:54][C][sdm_meter:096]:       Accuracy Decimals: 2
[21:40:54][C][sdm_meter:097]:     Apparent Power 'SDM630 Phase B Apparent Power'
[21:40:54][C][sdm_meter:097]:       State Class: 'measurement'
[21:40:54][C][sdm_meter:097]:       Unit of Measurement: 'VA'
[21:40:54][C][sdm_meter:097]:       Accuracy Decimals: 2
[21:40:54][C][sdm_meter:098]:     Reactive Power 'SDM630 Phase B Reactive Power'
[21:40:54][C][sdm_meter:098]:       State Class: 'measurement'
[21:40:54][C][sdm_meter:098]:       Unit of Measurement: 'var'
[21:40:54][C][sdm_meter:098]:       Accuracy Decimals: 2
[21:40:54][C][sdm_meter:099]:     Power Factor 'SDM630 Phase B Power Factor'
[21:40:54][C][sdm_meter:099]:       Device Class: 'power_factor'
[21:40:54][C][sdm_meter:099]:       State Class: 'measurement'
[21:40:54][C][sdm_meter:099]:       Unit of Measurement: ''
[21:40:54][C][sdm_meter:099]:       Accuracy Decimals: 3
[21:40:54][C][sdm_meter:100]:     Phase Angle 'SDM630 Phase B Phase Angle'
[21:40:54][C][sdm_meter:100]:       State Class: ''
[21:40:54][C][sdm_meter:100]:       Unit of Measurement: '°'
[21:40:54][C][sdm_meter:100]:       Accuracy Decimals: 3
[21:40:54][C][sdm_meter:100]:       Icon: 'mdi:flash'
[21:40:54][C][sdm_meter:093]:   Phase C
[21:40:54][C][sdm_meter:094]:     Voltage 'SDM630 Phase C Voltage'
[21:40:54][C][sdm_meter:094]:       Device Class: 'voltage'
[21:40:54][C][sdm_meter:094]:       State Class: 'measurement'
[21:40:54][C][sdm_meter:094]:       Unit of Measurement: 'V'
[21:40:54][C][sdm_meter:094]:       Accuracy Decimals: 2
[21:40:54][C][sdm_meter:095]:     Current 'SDM630 Phase C Current'
[21:40:54][C][sdm_meter:095]:       Device Class: 'current'
[21:40:54][C][sdm_meter:095]:       State Class: 'measurement'
[21:40:54][C][sdm_meter:095]:       Unit of Measurement: 'A'
[21:40:54][C][sdm_meter:095]:       Accuracy Decimals: 3
[21:40:54][C][sdm_meter:096]:     Active Power 'SDM630 Phase C Power'
[21:40:54][C][sdm_meter:096]:       Device Class: 'power'
[21:40:54][C][sdm_meter:096]:       State Class: 'measurement'
[21:40:54][C][sdm_meter:096]:       Unit of Measurement: 'W'
[21:40:54][C][sdm_meter:096]:       Accuracy Decimals: 2
[21:40:54][C][sdm_meter:097]:     Apparent Power 'SDM630 Phase C Apparent Power'
[21:40:54][C][sdm_meter:097]:       State Class: 'measurement'
[21:40:54][C][sdm_meter:097]:       Unit of Measurement: 'VA'
[21:40:54][C][sdm_meter:097]:       Accuracy Decimals: 2
[21:40:54][C][sdm_meter:098]:     Reactive Power 'SDM630 Phase C Reactive Power'
[21:40:54][C][sdm_meter:098]:       State Class: 'measurement'
[21:40:54][C][sdm_meter:098]:       Unit of Measurement: 'var'
[21:40:54][C][sdm_meter:098]:       Accuracy Decimals: 2
[21:40:54][C][sdm_meter:099]:     Power Factor 'SDM630 Phase C Power Factor'
[21:40:54][C][sdm_meter:099]:       Device Class: 'power_factor'
[21:40:54][C][sdm_meter:099]:       State Class: 'measurement'
[21:40:54][C][sdm_meter:099]:       Unit of Measurement: ''
[21:40:54][C][sdm_meter:099]:       Accuracy Decimals: 3
[21:40:54][C][sdm_meter:100]:     Phase Angle 'SDM630 Phase C Phase Angle'
[21:40:54][C][sdm_meter:100]:       State Class: ''
[21:40:54][C][sdm_meter:100]:       Unit of Measurement: '°'
[21:40:54][C][sdm_meter:100]:       Accuracy Decimals: 3
[21:40:54][C][sdm_meter:100]:       Icon: 'mdi:flash'
[21:40:54][C][sdm_meter:102]:   Total Power 'SDM630 Total Power'
[21:40:54][C][sdm_meter:102]:     Device Class: 'power'
[21:40:54][C][sdm_meter:102]:     State Class: 'measurement'
[21:40:54][C][sdm_meter:102]:     Unit of Measurement: 'W'
[21:40:54][C][sdm_meter:102]:     Accuracy Decimals: 2
[21:40:54][C][sdm_meter:103]:   Frequency 'SDM630 Frequency'
[21:40:54][C][sdm_meter:103]:     State Class: 'measurement'
[21:40:54][C][sdm_meter:103]:     Unit of Measurement: 'Hz'
[21:40:54][C][sdm_meter:103]:     Accuracy Decimals: 3
[21:40:54][C][sdm_meter:103]:     Icon: 'mdi:current-ac'
[21:40:54][C][sdm_meter:104]:   Import Active Energy 'SDM630 Import Active Energy'
[21:40:54][C][sdm_meter:104]:     Device Class: 'energy'
[21:40:54][C][sdm_meter:104]:     State Class: 'total_increasing'
[21:40:54][C][sdm_meter:104]:     Unit of Measurement: 'kWh'
[21:40:54][C][sdm_meter:104]:     Accuracy Decimals: 2
[21:40:54][C][sdm_meter:105]:   Export Active Energy 'SDM630 Export Active Energy'
[21:40:54][C][sdm_meter:105]:     Device Class: 'energy'
[21:40:54][C][sdm_meter:105]:     State Class: 'total_increasing'
[21:40:54][C][sdm_meter:105]:     Unit of Measurement: 'kWh'
[21:40:54][C][sdm_meter:105]:     Accuracy Decimals: 2
[21:40:54][C][sdm_meter:106]:   Import Reactive Energy 'SDM630 Import Reactive Energy'
[21:40:54][C][sdm_meter:106]:     State Class: 'total_increasing'
[21:40:54][C][sdm_meter:106]:     Unit of Measurement: 'kVARh'
[21:40:54][C][sdm_meter:106]:     Accuracy Decimals: 2
[21:40:54][C][sdm_meter:107]:   Export Reactive Energy 'SDM630 Export Reactive Energy'
[21:40:54][C][sdm_meter:107]:     State Class: 'total_increasing'
[21:40:54][C][sdm_meter:107]:     Unit of Measurement: 'kVARh'
[21:40:54][C][sdm_meter:107]:     Accuracy Decimals: 2
[21:40:54][C][status:034]: Status Binary Sensor 'Status'
[21:40:54][C][status:034]:   Device Class: 'connectivity'
[21:40:54][C][restart.button:017]: Restart Button 'Reboot'
[21:40:54][C][restart.button:017]:   Icon: 'mdi:restart'
[21:40:54][C][captive_portal:089]: Captive Portal:
[21:40:54][C][sntp:042]: SNTP Time:
[21:40:54][C][sntp:045]:   Server 0: '0.pool.ntp.org'
[21:40:54][C][sntp:045]:   Server 1: '1.pool.ntp.org'
[21:40:54][C][sntp:045]:   Server 2: '2.pool.ntp.org'
[21:40:54][C][mdns:116]: mDNS:
[21:40:54][C][mdns:117]:   Hostname: utilhouse
[21:40:54][V][mdns:118]:   Services:
[21:40:54][V][mdns:120]:   - _esphomelib, _tcp, 6053
[21:40:55][V][mdns:122]:     TXT: friendly_name = Utilitymeter House
[21:40:55][V][mdns:122]:     TXT: version = 2024.12.2
[21:40:55][V][mdns:122]:     TXT: mac = 7c9ebdf31a34
[21:40:55][V][mdns:122]:     TXT: platform = ESP32
[21:40:55][V][mdns:122]:     TXT: board = esp32dev
[21:40:55][V][mdns:122]:     TXT: network = wifi
[21:40:55][V][mdns:122]:     TXT: api_encryption = Noise_NNpsk0_25519_ChaChaPoly_SHA256
[21:40:55][C][esphome.ota:073]: Over-The-Air updates:
[21:40:55][C][esphome.ota:074]:   Address: 192.168.1.12:3232
[21:40:55][C][esphome.ota:075]:   Version: 2
[21:40:55][C][esphome.ota:078]:   Password configured
[21:40:55][C][safe_mode:018]: Safe Mode:
[21:40:55][C][safe_mode:020]:   Boot considered successful after 60 seconds
[21:40:55][C][safe_mode:021]:   Invoke after 10 boot attempts
[21:40:55][C][safe_mode:023]:   Remain in safe mode for 300 seconds
[21:40:55][C][api:140]: API Server:
[21:40:55][C][api:141]:   Address: 192.168.1.12:6053
[21:40:55][C][api:143]:   Using noise encryption: YES
[21:40:55][C][wifi_signal.sensor:010]: WiFi Signal 'WiFi Signal'
[21:40:55][C][wifi_signal.sensor:010]:   Device Class: 'signal_strength'
[21:40:55][C][wifi_signal.sensor:010]:   State Class: 'measurement'
[21:40:55][C][wifi_signal.sensor:010]:   Unit of Measurement: 'dBm'
[21:40:55][C][wifi_signal.sensor:010]:   Accuracy Decimals: 0
[21:40:55][V][wifi_signal.sensor:010]:   Unique ID: '7c9ebdf31a34-wifisignal'
[21:41:01][V][modbus:221]: Modbus write: 01.04.00.00.00.50.F0.36 (8) at 16406
[21:41:01][D][uart_debug:114]: >>> 01:04:00:00:00:50:F0:36
[21:41:01][V][modbus:067]: Modbus received first Byte  0 (0X0) at 6754
[21:41:01][W][modbus:155]: Modbus CRC Check failed! C071!=C300 00.00.00.00.C3 (5) at 16428
[21:41:01][V][modbus:310]: Clearing buffer of 5 bytes - parse failed at 16430
[21:41:01][V][modbus:067]: Modbus received first Byte  20 (0X14) at 16443
[21:41:01][V][modbus:310]: Clearing buffer of 42 bytes - timeout at 16464
[21:41:02][D][uart_debug:114]: <<< 00:00:00:00:C3:14:4A:A0:3F:7C:87:7F:00:00:00:00:C1:12:55:12:00:00:00:00:42:48:12:FF:46:D4:AC:F9:3A:83:12:6F:44:CA:2F:6D:45:45:DC:4E:99:5B:00
[21:41:02][V][modbus:067]: Modbus received first Byte  0 (0X0) at 16448
[21:41:02][W][modbus:155]: Modbus CRC Check failed! 69D2!=4361 00.01.04.A0.43.65.51.61.43 (9) at 16581
[21:41:02][V][modbus:310]: Clearing buffer of 9 bytes - parse failed at 16595
[21:41:02][V][modbus:067]: Modbus received first Byte  104 (0X68) at 16597
[21:41:02][W][modbus:155]: Modbus CRC Check failed! 6E7A!=6943 68.E6.39.43.69 (5) at 16611
[21:41:02][V][modbus:310]: Clearing buffer of 5 bytes - parse failed at 16613
[21:41:02][V][modbus:067]: Modbus received first Byte  168 (0Xa8) at 16626
[21:41:02][W][modbus:155]: Modbus CRC Check failed! 6669!=1D07 A8.6F.40.45.A8.96.3F.15.9F.BE.3F.19.64.51.44.2C.96.1C.42.E2.2E.44.42.EF.D7.9F.44.2C.96.24.43.07.F9.D2.43.0C.2D.7F.00.00.00.00.C2.97.31.6F.C2.91.08.6F.3F.80.00.00.3F.54.CA.4D.3F.5B.15.0B.BE.EE.33.EE.C2.07.1D (69) at 16633
[21:41:02][V][modbus:310]: Clearing buffer of 69 bytes - parse failed at 16656
[21:41:02][V][modbus:067]: Modbus received first Byte  194 (0Xc2) at 16659
[21:41:02][W][modbus:155]: Modbus CRC Check failed! EE41!=D43D C2.C1.F9.3D.D4 (5) at 16673
[21:41:02][V][modbus:310]: Clearing buffer of 5 bytes - parse failed at 16675
[21:41:02][V][modbus:067]: Modbus received first Byte  67 (0X43) at 16688
[21:41:02][W][component:237]: Component modbus took a long time for an operation (115 ms).
[21:41:02][W][component:238]: Components should block for at most 30 ms.
[21:41:02][V][modbus:310]: Clearing buffer of 32 bytes - timeout at 16708
[21:41:02][D][uart_debug:114]: <<< 00:01:04:A0:43:65:51:61:43:68:E6:39:43:69:A8:6F:40:45:A8:96:3F:15:9F:BE:3F:19:64:51:44:2C:96:1C:42:E2:2E:44:42:EF:D7:9F:44:2C:96:24:43:07:F9:D2:43:0C:2D:7F:00:00:00:00:C2:97:31:6F:C2:91:08:6F:3F:80:00:00:3F:54:CA:4D:3F:5B:15:0B:BE:EE:33:EE:C2:07:1D:C2:C1:F9:3D:D4:43:67:F0:14:00:00:00:00:3F:B9:93:5B:40:8B:2E:84:00:00:00:00:44:66:B6:EE:00:00:00:00:44:71:81:8F
[21:41:02][V][modbus:036]: Stop waiting for response from 1
[21:41:11][V][modbus:221]: Modbus write: 01.04.00.00.00.50.F0.36 (8) at 26404
[21:41:11][D][uart_debug:114]: >>> 01:04:00:00:00:50:F0:36
[21:41:11][V][modbus:067]: Modbus received first Byte  0 (0X0) at 16692
[21:41:11][W][modbus:155]: Modbus CRC Check failed! C071!=C300 00.00.00.00.C3 (5) at 26427
[21:41:11][V][modbus:310]: Clearing buffer of 5 bytes - parse failed at 26429
[21:41:11][V][modbus:067]: Modbus received first Byte  20 (0X14) at 26442
[21:41:11][V][modbus:310]: Clearing buffer of 42 bytes - timeout at 26463
[21:41:12][D][uart_debug:114]: <<< 00:00:00:00:C3:14:1C:EF:3F:7C:7E:8D:00:00:00:00:C1:12:82:BC:00:00:00:00:42:48:23:2A:46:D4:AC:FA:3A:83:12:6F:44:CA:2F:6D:45:45:DC:4E:92:94:00
[21:41:12][V][modbus:067]: Modbus received first Byte  0 (0X0) at 26447
[21:41:12][W][modbus:155]: Modbus CRC Check failed! 8A93!=4366 00.01.04.A0.43.64.EA.66.43 (9) at 26578
[21:41:12][V][modbus:310]: Clearing buffer of 9 bytes - parse failed at 26580
[21:41:12][V][modbus:067]: Modbus received first Byte  105 (0X69) at 26594
[21:41:12][V][modbus:310]: Clearing buffer of 111 bytes - timeout at 26654
[21:41:12][D][uart_debug:114]: <<< 00:01:04:A0:43:64:EA:66:43:69:00:84:43:69:23:31:40:45:2F:46:3F:15:53:B5:3F:19:4A:45:44:2C:61:07:42:E1:CC:2A:42:EE:BD:6A:44:2C:61:14:43:07:E9:7D:43:0B:99:AC:00:00:00:00:C2:97:57:10:C2:90:C3:39:3F:80:00:00:3F:54:A7:20:3F:5A:E6:D5:BE:C1:41:97:C2:07:56:5D:C1:F9:DD:9C:43:67:AF:5F:00:00:00:00:3F:B9:20:2D:40:8A:D8:22:00:00:00:00:44:66:56:AD:00:00:00:00:44:71:24:F7
[21:41:12][V][modbus:036]: Stop waiting for response from 1
[21:41:21][V][modbus:221]: Modbus write: 01.04.00.00.00.50.F0.36 (8) at 36413
[21:41:21][D][uart_debug:114]: >>> 01:04:00:00:00:50:F0:36
[21:41:21][V][modbus:067]: Modbus received first Byte  0 (0X0) at 26603
[21:41:21][W][modbus:155]: Modbus CRC Check failed! C071!=C300 00.00.00.00.C3 (5) at 36437
[21:41:21][V][modbus:310]: Clearing buffer of 5 bytes - parse failed at 36439
[21:41:21][V][modbus:067]: Modbus received first Byte  26 (0X1a) at 36452
[21:41:21][W][modbus:155]: Modbus CRC Check failed! 475D!=7C3F 1A.ED.3F.3F.7C (5) at 36455
[21:41:21][V][modbus:310]: Clearing buffer of 5 bytes - parse failed at 36468
[21:41:21][V][modbus:067]: Modbus received first Byte  109 (0X6d) at 36470
[21:41:21][W][modbus:155]: Modbus CRC Check failed! BDF8!=00 6D.22.00.00.00 (5) at 36483
[21:41:22][V][modbus:310]: Clearing buffer of 5 bytes - parse failed at 36485
[21:41:22][V][modbus:067]: Modbus received first Byte  0 (0X0) at 36498
[21:41:22][W][modbus:155]: Modbus CRC Check failed! 9AE1!=445E 00.C1.19.5E.44 (5) at 36501
[21:41:22][V][modbus:310]: Clearing buffer of 5 bytes - parse failed at 36515
[21:41:22][V][modbus:067]: Modbus received first Byte  0 (0X0) at 36519
[21:41:22][W][modbus:155]: Modbus CRC Check failed! C071!=4200 00.00.00.00.42 (5) at 36521
[21:41:22][V][modbus:310]: Clearing buffer of 5 bytes - parse failed at 36535
[21:41:22][V][modbus:067]: Modbus received first Byte  72 (0X48) at 36537
[21:41:22][W][component:237]: Component modbus took a long time for an operation (132 ms).
[21:41:22][W][component:238]: Components should block for at most 30 ms.
[21:41:22][D][uart_debug:114]: <<< 00:00:00:00:C3:1A:ED:3F:3F:7C:6D:22:00:00:00:00:C1:19:5E:44:00:00:00:00:42:48:3B:B0:46:D4:AC:FB:3A:83:12:6F:44:CA:2F:6D:45:45:DC:52:C4:93:00:00:01:04:A0:43:65:36:39:43:68:33:10:43:69:A1:A8:40:45:99:20:3F:15:AD:6E:3F:1A:36:57:44:2C:C5:90:42:E1:B3:FA:42:F1:3F:1A:44:2C:C5:A1:43:07:C3:07:43:0C:BC:D6:00:00:00:00:C2:96:F0:EE:C2:91:03:0E:3F:80:00:00:3F:54:CC:90:3F:5B:69:76:BE:B4:10:47:C2:07:1A:1E:C1:F8:19:09:43:67:AE:51:00:00:00:00:3F:B9:B6:4B:40:8B:48
[21:41:22][W][component:237]: Component modbus took a long time for an operation (65 ms).
[21:41:22][W][component:238]: Components should block for at most 30 ms.
[21:41:22][V][modbus:310]: Clearing buffer of 142 bytes - timeout at 36683
[21:41:22][D][uart_debug:114]: <<< B8:00:00:00:00:44:67:23:F2:00:00:00:00:44:71:E5:99
[21:41:22][V][modbus:036]: Stop waiting for response from 1
[21:41:25][V][sensor:043]: 'Uptime': Received new state 40.223000
[21:41:25][D][sensor:094]: 'Uptime': Sending state 0.00000 h with 0 decimals of accuracy
[21:41:31][V][modbus:221]: Modbus write: 01.04.00.00.00.50.F0.36 (8) at 46402
[21:41:31][D][uart_debug:114]: >>> 01:04:00:00:00:50:F0:36
[21:41:31][V][modbus:067]: Modbus received first Byte  0 (0X0) at 36633
[21:41:31][W][modbus:155]: Modbus CRC Check failed! C071!=C300 00.00.00.00.C3 (5) at 46425
[21:41:31][V][modbus:310]: Clearing buffer of 5 bytes - parse failed at 46427
[21:41:31][V][modbus:067]: Modbus received first Byte  19 (0X13) at 46440
[21:41:31][W][modbus:155]: Modbus CRC Check failed! D543!=7C3F 13.F9.FE.3F.7C (5) at 46445
[21:41:31][V][modbus:310]: Clearing buffer of 5 bytes - parse failed at 46458
[21:41:31][V][modbus:067]: Modbus received first Byte  145 (0X91) at 46460
[21:41:31][W][modbus:155]: Modbus CRC Check failed! 7D62!=00 91.F9.00.00.00 (5) at 46474
[21:41:32][V][modbus:310]: Clearing buffer of 5 bytes - parse failed at 46476
[21:41:32][V][modbus:067]: Modbus received first Byte  0 (0X0) at 46489
[21:41:32][W][modbus:155]: Modbus CRC Check failed! 5DA0!=C415 00.C1.12.15.C4 (5) at 46492
[21:41:32][V][modbus:310]: Clearing buffer of 5 bytes - parse failed at 46505
[21:41:32][V][modbus:067]: Modbus received first Byte  0 (0X0) at 46507
[21:41:32][W][modbus:155]: Modbus CRC Check failed! C071!=4200 00.00.00.00.42 (5) at 46510
[21:41:32][V][modbus:310]: Clearing buffer of 5 bytes - parse failed at 46524
[21:41:32][V][modbus:067]: Modbus received first Byte  72 (0X48) at 46526
[21:41:32][W][component:237]: Component modbus took a long time for an operation (133 ms).
[21:41:32][W][component:238]: Components should block for at most 30 ms.
[21:41:32][D][uart_debug:114]: <<< 00:00:00:00:C3:13:F9:FE:3F:7C:91:F9:00:00:00:00:C1:12:15:C4:00:00:00:00:42:48:24:92:46:D4:AC:FD:3A:83:12:6F:44:CA:2F:6D:45:45:DC:52:4F:F4:00:00:01:04:A0:43:65:A8:40:43:68:BC:F6:43:69:A8:48:40:45:01:66:3F:15:39:B9:3F:19:23:16:44:2C:4F:B9:42:E1:4E:84:42:EF:53:41:44:2C:4F:C3:43:07:AA:74:43:0B:C5:9A:00:00:00:00:C2:97:30:17:C2:90:75:48:3F:80:00:00:3F:54:93:C3:3F:5B:21:4D:BE:8C:5B:37:C2:07:53:61:C1:F9:13:65:43:68:04:80:00:00:00:00:3F:B9:15:F9:40:8A:D0
[21:41:32][W][component:237]: Component modbus took a long time for an operation (63 ms).
[21:41:32][W][component:238]: Components should block for at most 30 ms.
[21:41:32][V][modbus:310]: Clearing buffer of 142 bytes - timeout at 46668
[21:41:32][D][uart_debug:114]: <<< 7B:00:00:00:00:44:66:3B:F7:00:00:00:00:44:71:02:4C
[21:41:32][V][modbus:036]: Stop waiting for response from 1
[21:41:36][D][dallas.temp.sensor:054]: 'Temp': Got Temperature=26.6°C
[21:41:36][V][sensor:043]: 'Temp': Received new state 26.562500
[21:41:36][D][sensor:094]: 'Temp': Sending state 26.56250 °C with 1 decimals of accuracy
[21:41:41][V][modbus:221]: Modbus write: 01.04.00.00.00.50.F0.36 (8) at 56401
[21:41:41][D][uart_debug:114]: >>> 01:04:00:00:00:50:F0:36
[21:41:41][V][modbus:067]: Modbus received first Byte  0 (0X0) at 46620
[21:41:41][W][modbus:155]: Modbus CRC Check failed! C071!=C300 00.00.00.00.C3 (5) at 56424
[21:41:41][V][modbus:310]: Clearing buffer of 5 bytes - parse failed at 56426
[21:41:41][V][modbus:067]: Modbus received first Byte  19 (0X13) at 56439
[21:41:41][W][modbus:155]: Modbus CRC Check failed! FC17!=7C3F 13.C9.9D.3F.7C (5) at 56442
[21:41:41][V][modbus:310]: Clearing buffer of 5 bytes - parse failed at 56455
[21:41:41][V][modbus:067]: Modbus received first Byte  152 (0X98) at 56457
[21:41:41][W][modbus:155]: Modbus CRC Check failed! 2F96!=00 98.88.00.00.00 (5) at 56473
[21:41:41][V][modbus:310]: Clearing buffer of 5 bytes - parse failed at 56476
[21:41:42][V][modbus:067]: Modbus received first Byte  0 (0X0) at 56489
[21:41:42][W][modbus:155]: Modbus CRC Check failed! 5DA0!=AD7C 00.C1.12.7C.AD (5) at 56492
[21:41:42][V][modbus:310]: Clearing buffer of 5 bytes - parse failed at 56505
[21:41:42][V][modbus:067]: Modbus received first Byte  0 (0X0) at 56507
[21:41:42][W][modbus:155]: Modbus CRC Check failed! C071!=4200 00.00.00.00.42 (5) at 56509
[21:41:42][V][modbus:310]: Clearing buffer of 5 bytes - parse failed at 56523
[21:41:42][V][modbus:067]: Modbus received first Byte  72 (0X48) at 56525
[21:41:42][W][component:237]: Component modbus took a long time for an operation (132 ms).
[21:41:42][W][component:238]: Components should block for at most 30 ms.
[21:41:42][D][uart_debug:114]: <<< 00:00:00:00:C3:13:C9:9D:3F:7C:98:88:00:00:00:00:C1:12:7C:AD:00:00:00:00:42:48:3A:CF:46:D4:AC:FE:3A:83:12:6F:44:CA:2F:6D:45:45:DC:52:CA:A9:00:00:01:04:A0:43:66:0D:8D:43:67:CF:C7:43:68:C9:94:40:45:21:05:3F:15:2F:85:3F:19:3D:F9:44:2C:D2:14:42:E0:7C:E0:42:EE:DB:A7:44:2C:D2:22:43:07:16:F7:43:0B:58:D3:00:00:00:00:C2:96:57:0F:C2:8F:96:34:3F:80:00:00:3F:54:B5:83:3F:5B:68:F9:BE:EE:A2:1A:C2:07:3F:38:C1:F8:1A:BA:43:67:8C:F8:00:00:00:00:3F:B9:22:B0:40:8A:DA
[21:41:42][W][component:237]: Component modbus took a long time for an operation (64 ms).
[21:41:42][W][component:238]: Components should block for at most 30 ms.
[21:41:42][V][modbus:310]: Clearing buffer of 142 bytes - timeout at 56670
[21:41:42][D][uart_debug:114]: <<< 04:00:00:00:00:44:66:BD:25:00:00:00:00:44:71:6E:15
[21:41:42][V][modbus:036]: Stop waiting for response from 1
[21:41:45][I][safe_mode:041]: Boot seems successful; resetting boot loop counter
[21:41:45][D][esp32.preferences:114]: Saving 1 preferences to flash...
[21:41:45][V][esp32.preferences:126]: sync: key: 233825507, len: 4
[21:41:45][D][esp32.preferences:143]: Saving 1 preferences to flash: 0 cached, 1 written, 0 failed
[21:41:51][V][sensor:043]: 'WiFi Signal': Received new state -66.000000
[21:41:51][D][sensor:094]: 'WiFi Signal': Sending state -66.00000 dBm with 0 decimals of accuracy
[21:41:51][V][modbus:221]: Modbus write: 01.04.00.00.00.50.F0.36 (8) at 66399
[21:41:51][D][uart_debug:114]: >>> 01:04:00:00:00:50:F0:36
[21:41:51][V][modbus:067]: Modbus received first Byte  0 (0X0) at 56619
[21:41:51][W][modbus:155]: Modbus CRC Check failed! C071!=C300 00.00.00.00.C3 (5) at 66422
[21:41:51][V][modbus:310]: Clearing buffer of 5 bytes - parse failed at 66424
[21:41:51][V][modbus:067]: Modbus received first Byte  18 (0X12) at 66437
[21:41:51][W][modbus:155]: Modbus CRC Check failed! DC17!=7C3F 12.F6.A2.3F.7C (5) at 66440
[21:41:51][V][modbus:310]: Clearing buffer of 5 bytes - parse failed at 66453
[21:41:51][V][modbus:067]: Modbus received first Byte  153 (0X99) at 66455
[21:41:51][W][modbus:155]: Modbus CRC Check failed! BFD0!=00 99.BD.00.00.00 (5) at 66469
[21:41:51][V][modbus:310]: Clearing buffer of 5 bytes - parse failed at 66471
[21:41:51][V][modbus:067]: Modbus received first Byte  0 (0X0) at 66484
[21:41:52][W][modbus:155]: Modbus CRC Check failed! 5CE0!=9A7E 00.C1.11.7E.9A (5) at 66487
[21:41:52][V][modbus:310]: Clearing buffer of 5 bytes - parse failed at 66502
[21:41:52][V][modbus:067]: Modbus received first Byte  0 (0X0) at 66504
[21:41:52][W][modbus:155]: Modbus CRC Check failed! C071!=4200 00.00.00.00.42 (5) at 66507
[21:41:52][V][modbus:310]: Clearing buffer of 5 bytes - parse failed at 66520
[21:41:52][V][modbus:067]: Modbus received first Byte  72 (0X48) at 66522
[21:41:52][W][component:237]: Component modbus took a long time for an operation (132 ms).
[21:41:52][W][component:238]: Components should block for at most 30 ms.
[21:41:52][W][modbus:155]: Modbus CRC Check failed! 6BBD!=3F0B 48.39.61.46.D4.AC.FF.3A.83.12.6F.44.CA.2F.6D.45.45.DC.56.00.A2.00.00.01.04.A0.43.65.C6.92.43.68.3A.67.43.68.B2.97.40.45.D3.D7.3F.15.8F.D5.3F.19.19.BE.44.2D.28.96.42.E1.57.40.42.EE.A4.8E.44.2D.28.A8.43.07.8D.BC.43.0B.28.A5.00.00.00.00.C2.96.BB.D9.C2.8F.36.CA.3F.80.00.00.3F.54.C8.90.3F.5B.81.62.BE.BE.0B.3F (102) at 66559
[21:41:52][V][modbus:310]: Clearing buffer of 102 bytes - parse failed at 66593
[21:41:52][V][modbus:067]: Modbus received first Byte  194 (0Xc2) at 66595
[21:41:52][D][uart_debug:114]: <<< 00:00:00:00:C3:12:F6:A2:3F:7C:99:BD:00:00:00:00:C1:11:7E:9A:00:00:00:00:42:48:39:61:46:D4:AC:FF:3A:83:12:6F:44:CA:2F:6D:45:45:DC:56:00:A2:00:00:01:04:A0:43:65:C6:92:43:68:3A:67:43:68:B2:97:40:45:D3:D7:3F:15:8F:D5:3F:19:19:BE:44:2D:28:96:42:E1:57:40:42:EE:A4:8E:44:2D:28:A8:43:07:8D:BC:43:0B:28:A5:00:00:00:00:C2:96:BB:D9:C2:8F:36:CA:3F:80:00:00:3F:54:C8:90:3F:5B:81:62:BE:BE:0B:3F:C2:07:20:8E:C1:F7:C5:D7:43:67:8A:7C:00:00:00:00:3F:B9:ED:B7:40:8B:72
[21:41:52][W][modbus:155]: Modbus CRC Check failed! E65B!=4400 C2.07.20.8E.C1.F7.C5.D7.43.67.8A.7C.00.00.00.00.3F.B9.ED.B7.40.8B.72.49.00.00.00.00.44.67.28.10.00.00.00.00.44 (37) at 66666
[21:41:52][V][modbus:310]: Clearing buffer of 37 bytes - parse failed at 66680
[21:41:52][V][modbus:067]: Modbus received first Byte  113 (0X71) at 66682
[21:41:52][W][component:237]: Component modbus took a long time for an operation (142 ms).
[21:41:52][W][component:238]: Components should block for at most 30 ms.
[21:41:52][V][modbus:310]: Clearing buffer of 3 bytes - timeout at 66712
[21:41:52][D][uart_debug:114]: <<< 49:00:00:00:00:44:67:28:10:00:00:00:00:44:71:D6:40
[21:41:52][V][modbus:036]: Stop waiting for response from 1
[21:42:01][V][modbus:221]: Modbus write: 01.04.00.00.00.50.F0.36 (8) at 76413
[21:42:01][D][uart_debug:114]: >>> 01:04:00:00:00:50:F0:36
[21:42:01][V][modbus:067]: Modbus received first Byte  0 (0X0) at 66695
[21:42:01][W][modbus:155]: Modbus CRC Check failed! C071!=C300 00.00.00.00.C3 (5) at 76436
[21:42:01][V][modbus:310]: Clearing buffer of 5 bytes - parse failed at 76438
[21:42:01][V][modbus:067]: Modbus received first Byte  18 (0X12) at 76451
[21:42:01][W][modbus:155]: Modbus CRC Check failed! 6812!=7C3F 12.F9.52.3F.7C (5) at 76454
[21:42:01][V][modbus:310]: Clearing buffer of 5 bytes - parse failed at 76467
[21:42:01][V][modbus:067]: Modbus received first Byte  154 (0X9a) at 76469
[21:42:01][W][modbus:155]: Modbus CRC Check failed! 2F2E!=00 9A.A8.00.00.00 (5) at 76483
[21:42:02][V][modbus:310]: Clearing buffer of 5 bytes - parse failed at 76485
[21:42:02][V][modbus:067]: Modbus received first Byte  0 (0X0) at 76498
[21:42:02][W][modbus:155]: Modbus CRC Check failed! 5CE0!=DD17 00.C1.11.17.DD (5) at 76501
[21:42:02][V][modbus:310]: Clearing buffer of 5 bytes - parse failed at 76514
[21:42:02][V][modbus:067]: Modbus received first Byte  0 (0X0) at 76516
[21:42:02][W][modbus:155]: Modbus CRC Check failed! C071!=4200 00.00.00.00.42 (5) at 76519
[21:42:02][V][modbus:310]: Clearing buffer of 5 bytes - parse failed at 76533
[21:42:02][V][modbus:067]: Modbus received first Byte  72 (0X48) at 76535
[21:42:02][W][component:237]: Component modbus took a long time for an operation (130 ms).
[21:42:02][W][component:238]: Components should block for at most 30 ms.
[21:42:02][W][modbus:155]: Modbus CRC Check failed! ACA4!=C848 48.3A.75.46.D4.AD.01.3A.83.12.6F.44.CA.2F.6D.45.45.DC.5A.D0.8B.00.00.01.04.A0.43.65.C1.68.43.67.5B.55.43.69.03.52.40.45.3B.0B.3F.15.2A.1B.3F.19.22.F7.44.2C.FE.D8.42.DF.FB.32.42.EE.A1.32.44.2C.FE.EA.43.06.CE.36.43.0B.62.D0.00.00.00.00.C2.96.13.32.C2.90.1D.EE.3F.80.00.00.3F.54.AD.15.3F.5B.33.BE.BE.65.33.59.C2.07.32.05.C1.F8.D3.7D.43.67.60.05.00.00.00.00.3F.B9.48.C8 (122) at 76572
[21:42:02][V][modbus:310]: Clearing buffer of 122 bytes - parse failed at 76606
[21:42:02][V][modbus:067]: Modbus received first Byte  64 (0X40) at 76619
[21:42:02][D][uart_debug:114]: <<< 00:00:00:00:C3:12:F9:52:3F:7C:9A:A8:00:00:00:00:C1:11:17:DD:00:00:00:00:42:48:3A:75:46:D4:AD:01:3A:83:12:6F:44:CA:2F:6D:45:45:DC:5A:D0:8B:00:00:01:04:A0:43:65:C1:68:43:67:5B:55:43:69:03:52:40:45:3B:0B:3F:15:2A:1B:3F:19:22:F7:44:2C:FE:D8:42:DF:FB:32:42:EE:A1:32:44:2C:FE:EA:43:06:CE:36:43:0B:62:D0:00:00:00:00:C2:96:13:32:C2:90:1D:EE:3F:80:00:00:3F:54:AD:15:3F:5B:33:BE:BE:65:33:59:C2:07:32:05:C1:F8:D3:7D:43:67:60:05:00:00:00:00:3F:B9:48:C8:40:8A:F6
[21:42:02][W][modbus:155]: Modbus CRC Check failed! 3297!=96 40.8A.F6.96.00 (5) at 76677
[21:42:02][V][modbus:310]: Clearing buffer of 5 bytes - parse failed at 76680
[21:42:02][V][modbus:067]: Modbus received first Byte  0 (0X0) at 76693
[21:42:02][W][modbus:155]: Modbus CRC Check failed! C071!=6644 00.00.00.44.66 (5) at 76696
[21:42:02][V][modbus:310]: Clearing buffer of 5 bytes - parse failed at 76709
[21:42:02][V][modbus:067]: Modbus received first Byte  140 (0X8c) at 76711
[21:42:02][W][modbus:155]: Modbus CRC Check failed! BBEB!=00 8C.D9.00.00.00 (5) at 76725
[21:42:02][V][modbus:310]: Clearing buffer of 5 bytes - parse failed at 76728
[21:42:02][V][modbus:067]: Modbus received first Byte  0 (0X0) at 76741
[21:42:02][W][component:237]: Component modbus took a long time for an operation (180 ms).
[21:42:02][W][component:238]: Components should block for at most 30 ms.
[21:42:02][V][modbus:310]: Clearing buffer of 5 bytes - timeout at 76761
[21:42:02][D][uart_debug:114]: <<< 96:00:00:00:00:44:66:8C:D9:00:00:00:00:44:71:43:DA
[21:42:02][V][modbus:036]: Stop waiting for response from 1
```

**Comment by exciton** [comment]
Ok - it's weird because the start of the response is incorrect (doesn't start with address) but the length is the same.

Can you check a couple of things - try at lower baud (like 9600), run with latest and 2.0.6 again but with modbus verbose this time, and make sure to clean build files between each run?

I updated the debugging to be a bit more useful.

**Comment by exciton** [comment]
Would you mind also testing with framework: esp-idf?

**Comment by karllinder** [comment]
New try, but no luck, hope that the debug gives some info. Can it be hardware related? Using the standard 485 converters from AliExpress.

### 2.0.6 with clean build, 9600baud
```
INFO Upload took 10.05 seconds, waiting for result...
INFO OTA successful
INFO Successfully uploaded program.
INFO Starting log output from 192.168.1.12 using esphome API
INFO Successfully connected to utilhouse @ 192.168.1.12 in 7.304s
INFO Successful handshake with utilhouse @ 192.168.1.12 in 0.273s
[12:00:25][I][app:100]: ESPHome version 2024.12.2 compiled on Jan  6 2025, 11:58:19
[12:00:25][C][status_led:019]: Status LED:
[12:00:25][C][status_led:020]:   Pin: GPIO25
[12:00:25][C][wifi:600]: WiFi:
[12:00:25][C][wifi:428]:   Local MAC: 7C:9E:BD:F3:1A:34
[12:00:25][C][wifi:433]:   SSID: [redacted]
[12:00:25][C][wifi:436]:   IP Address: 192.168.1.12
[12:00:25][C][wifi:440]:   BSSID: [redacted]
[12:00:25][C][wifi:441]:   Hostname: 'utilhouse'
[12:00:25][C][wifi:443]:   Signal strength: -73 dB ▂▄▆█
[12:00:25][V][wifi:445]:   Priority: 0.0
[12:00:25][C][wifi:447]:   Channel: 6
[12:00:25][C][wifi:448]:   Subnet: 255.255.255.0
[12:00:25][C][wifi:449]:   Gateway: 192.168.1.1
[12:00:25][C][wifi:450]:   DNS1: 8.8.8.8
[12:00:25][C][wifi:451]:   DNS2: 1.1.1.1
[12:00:25][C][logger:185]: Logger:
[12:00:25][C][logger:186]:   Level: VERBOSE
[12:00:25][C][logger:188]:   Log Baud Rate: 115200
[12:00:25][C][logger:189]:   Hardware UART: UART0
[12:00:25][C][gpio.one_wire:020]: GPIO 1-wire bus:
[12:00:25][C][gpio.one_wire:021]:   Pin: GPIO32
[12:00:25][C][gpio.one_wire:080]:   Found devices:
[12:00:25][C][gpio.one_wire:082]:     0xa73c01f09514a628 (DS18B20)
[12:00:25][C][uart.arduino_esp32:151]: UART Bus 1:
[12:00:25][C][uart.arduino_esp32:152]:   TX Pin: GPIO17
[12:00:25][C][uart.arduino_esp32:153]:   RX Pin: GPIO16
[12:00:25][C][uart.arduino_esp32:155]:   RX Buffer Size: 256
[12:00:25][C][uart.arduino_esp32:157]:   Baud Rate: 9600 baud
[12:00:25][C][uart.arduino_esp32:158]:   Data Bits: 8
[12:00:25][C][uart.arduino_esp32:159]:   Parity: NONE
[12:00:25][C][uart.arduino_esp32:160]:   Stop bits: 1
[12:00:25][C][modbus:230]: Modbus:
[12:00:25][C][modbus:231]:   Flow Control Pin: GPIO5
[12:00:25][C][modbus:232]:   Send Wait Time: 200 ms
[12:00:25][C][modbus:233]:   Turnaround Time: 200 ms
[12:00:25][C][modbus:234]:   Frame Delay: 5 ms
[12:00:25][C][modbus:235]:   Long Rx Buffer Delay: 138 ms
[12:00:25][C][modbus:236]:   CRC Disabled: NO
[12:00:25][C][uptime.sensor:033]: Uptime Sensor 'Uptime'
[12:00:25][C][uptime.sensor:033]:   Device Class: 'duration'
[12:00:25][C][uptime.sensor:033]:   State Class: 'total_increasing'
[12:00:25][C][uptime.sensor:033]:   Unit of Measurement: 'h'
[12:00:25][C][uptime.sensor:033]:   Accuracy Decimals: 0
[12:00:25][C][uptime.sensor:033]:   Icon: 'mdi:timer-outline'
[12:00:25][V][uptime.sensor:033]:   Unique ID: '7c9ebdf31a34-uptime'
[12:00:25][C][uptime.sensor:034]:   Type: Seconds
[12:00:25][C][dallas.temp.sensor:029]: Dallas Temperature Sensor:
[12:00:25][C][dallas.temp.sensor:034]:   Address: 0xa73c01f09514a628 (DS18B20)
[12:00:25][C][dallas.temp.sensor:035]:   Resolution: 12 bits
[12:00:25][C][dallas.temp.sensor:036]:   Update Interval: 60.0s
[12:00:25][C][sdm_meter:087]: SDM Meter:
[12:00:25][C][sdm_meter:088]:   Address: 0x01
[12:00:25][C][sdm_meter:093]:   Phase A
[12:00:25][C][sdm_meter:094]:     Voltage 'SDM630 Phase A Voltage'
[12:00:25][C][sdm_meter:094]:       Device Class: 'voltage'
[12:00:25][C][sdm_meter:094]:       State Class: 'measurement'
[12:00:25][C][sdm_meter:094]:       Unit of Measurement: 'V'
[12:00:25][C][sdm_meter:094]:       Accuracy Decimals: 2
[12:00:25][C][sdm_meter:095]:     Current 'SDM630 Phase A Current'
[12:00:25][C][sdm_meter:095]:       Device Class: 'current'
[12:00:25][C][sdm_meter:095]:       State Class: 'measurement'
[12:00:25][C][sdm_meter:095]:       Unit of Measurement: 'A'
[12:00:25][C][sdm_meter:095]:       Accuracy Decimals: 3
[12:00:25][C][sdm_meter:096]:     Active Power 'SDM630 Phase A Power'
[12:00:25][C][sdm_meter:096]:       Device Class: 'power'
[12:00:25][C][sdm_meter:096]:       State Class: 'measurement'
[12:00:25][C][sdm_meter:096]:       Unit of Measurement: 'W'
[12:00:25][C][sdm_meter:096]:       Accuracy Decimals: 2
[12:00:25][C][sdm_meter:097]:     Apparent Power 'SDM630 Phase A Apparent Power'
[12:00:25][C][sdm_meter:097]:       State Class: 'measurement'
[12:00:25][C][sdm_meter:097]:       Unit of Measurement: 'VA'
[12:00:25][C][sdm_meter:097]:       Accuracy Decimals: 2
[12:00:25][C][sdm_meter:098]:     Reactive Power 'SDM630 Phase A Reactive Power'
[12:00:25][C][sdm_meter:098]:       State Class: 'measurement'
[12:00:25][C][sdm_meter:098]:       Unit of Measurement: 'var'
[12:00:25][C][sdm_meter:098]:       Accuracy Decimals: 2
[12:00:25][C][sdm_meter:099]:     Power Factor 'SDM630 Phase A Power Factor'
[12:00:25][C][sdm_meter:099]:       Device Class: 'power_factor'
[12:00:25][C][sdm_meter:099]:       State Class: 'measurement'
[12:00:25][C][sdm_meter:099]:       Unit of Measurement: ''
[12:00:25][C][sdm_meter:099]:       Accuracy Decimals: 3
[12:00:25][C][sdm_meter:100]:     Phase Angle 'SDM630 Phase A Phase Angle'
[12:00:25][C][sdm_meter:100]:       State Class: ''
[12:00:25][C][sdm_meter:100]:       Unit of Measurement: '°'
[12:00:25][C][sdm_meter:100]:       Accuracy Decimals: 3
[12:00:25][C][sdm_meter:100]:       Icon: 'mdi:flash'
[12:00:25][C][sdm_meter:093]:   Phase B
[12:00:25][C][sdm_meter:094]:     Voltage 'SDM630 Phase B Voltage'
[12:00:25][C][sdm_meter:094]:       Device Class: 'voltage'
[12:00:25][C][sdm_meter:094]:       State Class: 'measurement'
[12:00:25][C][sdm_meter:094]:       Unit of Measurement: 'V'
[12:00:25][C][sdm_meter:094]:       Accuracy Decimals: 2
[12:00:25][C][sdm_meter:095]:     Current 'SDM630 Phase B Current'
[12:00:25][C][sdm_meter:095]:       Device Class: 'current'
[12:00:25][C][sdm_meter:095]:       State Class: 'measurement'
[12:00:25][C][sdm_meter:095]:       Unit of Measurement: 'A'
[12:00:25][C][sdm_meter:095]:       Accuracy Decimals: 3
[12:00:25][C][sdm_meter:096]:     Active Power 'SDM630 Phase B Power'
[12:00:25][C][sdm_meter:096]:       Device Class: 'power'
[12:00:25][C][sdm_meter:096]:       State Class: 'measurement'
[12:00:25][C][sdm_meter:096]:       Unit of Measurement: 'W'
[12:00:25][C][sdm_meter:096]:       Accuracy Decimals: 2
[12:00:25][C][sdm_meter:097]:     Apparent Power 'SDM630 Phase B Apparent Power'
[12:00:25][C][sdm_meter:097]:       State Class: 'measurement'
[12:00:25][C][sdm_meter:097]:       Unit of Measurement: 'VA'
[12:00:25][C][sdm_meter:097]:       Accuracy Decimals: 2
[12:00:25][C][sdm_meter:098]:     Reactive Power 'SDM630 Phase B Reactive Power'
[12:00:25][C][sdm_meter:098]:       State Class: 'measurement'
[12:00:25][C][sdm_meter:098]:       Unit of Measurement: 'var'
[12:00:25][C][sdm_meter:098]:       Accuracy Decimals: 2
[12:00:25][C][sdm_meter:099]:     Power Factor 'SDM630 Phase B Power Factor'
[12:00:25][C][sdm_meter:099]:       Device Class: 'power_factor'
[12:00:25][C][sdm_meter:099]:       State Class: 'measurement'
[12:00:25][C][sdm_meter:099]:       Unit of Measurement: ''
[12:00:25][C][sdm_meter:099]:       Accuracy Decimals: 3
[12:00:25][C][sdm_meter:100]:     Phase Angle 'SDM630 Phase B Phase Angle'
[12:00:25][C][sdm_meter:100]:       State Class: ''
[12:00:25][C][sdm_meter:100]:       Unit of Measurement: '°'
[12:00:25][C][sdm_meter:100]:       Accuracy Decimals: 3
[12:00:25][C][sdm_meter:100]:       Icon: 'mdi:flash'
[12:00:25][C][sdm_meter:093]:   Phase C
[12:00:25][C][sdm_meter:094]:     Voltage 'SDM630 Phase C Voltage'
[12:00:25][C][sdm_meter:094]:       Device Class: 'voltage'
[12:00:25][C][sdm_meter:094]:       State Class: 'measurement'
[12:00:25][C][sdm_meter:094]:       Unit of Measurement: 'V'
[12:00:25][C][sdm_meter:094]:       Accuracy Decimals: 2
[12:00:25][C][sdm_meter:095]:     Current 'SDM630 Phase C Current'
[12:00:25][C][sdm_meter:095]:       Device Class: 'current'
[12:00:25][C][sdm_meter:095]:       State Class: 'measurement'
[12:00:25][C][sdm_meter:095]:       Unit of Measurement: 'A'
[12:00:25][C][sdm_meter:095]:       Accuracy Decimals: 3
[12:00:25][C][sdm_meter:096]:     Active Power 'SDM630 Phase C Power'
[12:00:25][C][sdm_meter:096]:       Device Class: 'power'
[12:00:25][C][sdm_meter:096]:       State Class: 'measurement'
[12:00:26][C][sdm_meter:096]:       Unit of Measurement: 'W'
[12:00:26][C][sdm_meter:096]:       Accuracy Decimals: 2
[12:00:26][C][sdm_meter:097]:     Apparent Power 'SDM630 Phase C Apparent Power'
[12:00:26][C][sdm_meter:097]:       State Class: 'measurement'
[12:00:26][C][sdm_meter:097]:       Unit of Measurement: 'VA'
[12:00:26][C][sdm_meter:097]:       Accuracy Decimals: 2
[12:00:26][C][sdm_meter:098]:     Reactive Power 'SDM630 Phase C Reactive Power'
[12:00:26][C][sdm_meter:098]:       State Class: 'measurement'
[12:00:26][C][sdm_meter:098]:       Unit of Measurement: 'var'
[12:00:26][C][sdm_meter:098]:       Accuracy Decimals: 2
[12:00:26][C][sdm_meter:099]:     Power Factor 'SDM630 Phase C Power Factor'
[12:00:26][C][sdm_meter:099]:       Device Class: 'power_factor'
[12:00:26][C][sdm_meter:099]:       State Class: 'measurement'
[12:00:26][C][sdm_meter:099]:       Unit of Measurement: ''
[12:00:26][C][sdm_meter:099]:       Accuracy Decimals: 3
[12:00:26][C][sdm_meter:100]:     Phase Angle 'SDM630 Phase C Phase Angle'
[12:00:26][C][sdm_meter:100]:       State Class: ''
[12:00:26][C][sdm_meter:100]:       Unit of Measurement: '°'
[12:00:26][C][sdm_meter:100]:       Accuracy Decimals: 3
[12:00:26][C][sdm_meter:100]:       Icon: 'mdi:flash'
[12:00:26][C][sdm_meter:102]:   Total Power 'SDM630 Total Power'
[12:00:26][C][sdm_meter:102]:     Device Class: 'power'
[12:00:26][C][sdm_meter:102]:     State Class: 'measurement'
[12:00:26][C][sdm_meter:102]:     Unit of Measurement: 'W'
[12:00:26][C][sdm_meter:102]:     Accuracy Decimals: 2
[12:00:26][C][sdm_meter:103]:   Frequency 'SDM630 Frequency'
[12:00:26][C][sdm_meter:103]:     State Class: 'measurement'
[12:00:26][C][sdm_meter:103]:     Unit of Measurement: 'Hz'
[12:00:26][C][sdm_meter:103]:     Accuracy Decimals: 3
[12:00:26][C][sdm_meter:103]:     Icon: 'mdi:current-ac'
[12:00:26][C][sdm_meter:104]:   Import Active Energy 'SDM630 Import Active Energy'
[12:00:26][C][sdm_meter:104]:     Device Class: 'energy'
[12:00:26][C][sdm_meter:104]:     State Class: 'total_increasing'
[12:00:26][C][sdm_meter:104]:     Unit of Measurement: 'kWh'
[12:00:26][C][sdm_meter:104]:     Accuracy Decimals: 2
[12:00:26][C][sdm_meter:105]:   Export Active Energy 'SDM630 Export Active Energy'
[12:00:26][C][sdm_meter:105]:     Device Class: 'energy'
[12:00:26][C][sdm_meter:105]:     State Class: 'total_increasing'
[12:00:26][C][sdm_meter:105]:     Unit of Measurement: 'kWh'
[12:00:26][C][sdm_meter:105]:     Accuracy Decimals: 2
[12:00:26][C][sdm_meter:106]:   Import Reactive Energy 'SDM630 Import Reactive Energy'
[12:00:26][C][sdm_meter:106]:     State Class: 'total_increasing'
[12:00:26][C][sdm_meter:106]:     Unit of Measurement: 'kVARh'
[12:00:26][C][sdm_meter:106]:     Accuracy Decimals: 2
[12:00:26][C][sdm_meter:107]:   Export Reactive Energy 'SDM630 Export Reactive Energy'
[12:00:26][C][sdm_meter:107]:     State Class: 'total_increasing'
[12:00:26][C][sdm_meter:107]:     Unit of Measurement: 'kVARh'
[12:00:26][C][sdm_meter:107]:     Accuracy Decimals: 2
[12:00:26][C][status:034]: Status Binary Sensor 'Status'
[12:00:26][C][status:034]:   Device Class: 'connectivity'
[12:00:26][C][restart.button:017]: Restart Button 'Reboot'
[12:00:26][C][restart.button:017]:   Icon: 'mdi:restart'
[12:00:26][C][captive_portal:089]: Captive Portal:
[12:00:26][C][sntp:042]: SNTP Time:
[12:00:26][C][sntp:045]:   Server 0: '0.pool.ntp.org'
[12:00:26][C][sntp:045]:   Server 1: '1.pool.ntp.org'
[12:00:26][C][sntp:045]:   Server 2: '2.pool.ntp.org'
[12:00:26][C][mdns:116]: mDNS:
[12:00:26][C][mdns:117]:   Hostname: utilhouse
[12:00:26][V][mdns:118]:   Services:
[12:00:26][V][mdns:120]:   - _esphomelib, _tcp, 6053
[12:00:26][V][mdns:122]:     TXT: friendly_name = Utilitymeter House
[12:00:26][V][mdns:122]:     TXT: version = 2024.12.2
[12:00:26][V][mdns:122]:     TXT: mac = 7c9ebdf31a34
[12:00:26][V][mdns:122]:     TXT: platform = ESP32
[12:00:26][V][mdns:122]:     TXT: board = esp32dev
[12:00:26][V][mdns:122]:     TXT: network = wifi
[12:00:26][V][mdns:122]:     TXT: api_encryption = Noise_NNpsk0_25519_ChaChaPoly_SHA256
[12:00:26][C][esphome.ota:073]: Over-The-Air updates:
[12:00:26][C][esphome.ota:074]:   Address: 192.168.1.12:3232
[12:00:26][C][esphome.ota:075]:   Version: 2
[12:00:26][C][esphome.ota:078]:   Password configured
[12:00:26][C][safe_mode:018]: Safe Mode:
[12:00:26][C][safe_mode:020]:   Boot considered successful after 60 seconds
[12:00:26][C][safe_mode:021]:   Invoke after 10 boot attempts
[12:00:26][C][safe_mode:023]:   Remain in safe mode for 300 seconds
[12:00:26][C][api:140]: API Server:
[12:00:26][C][api:141]:   Address: 192.168.1.12:6053
[12:00:26][C][api:143]:   Using noise encryption: YES
[12:00:26][C][wifi_signal.sensor:010]: WiFi Signal 'WiFi Signal'
[12:00:26][C][wifi_signal.sensor:010]:   Device Class: 'signal_strength'
[12:00:26][C][wifi_signal.sensor:010]:   State Class: 'measurement'
[12:00:26][C][wifi_signal.sensor:010]:   Unit of Measurement: 'dBm'
[12:00:26][C][wifi_signal.sensor:010]:   Accuracy Decimals: 0
[12:00:26][V][wifi_signal.sensor:010]:   Unique ID: '7c9ebdf31a34-wifisignal'
[12:00:33][V][modbus:221]: Modbus write: 01.04.00.00.00.50.F0.36 (8) at 16846
[12:00:33][D][uart_debug:114]: >>> 01:04:00:00:00:50:F0:36
[12:00:33][V][modbus:067]: Modbus received first Byte  0 (0X0) at 7164
[12:00:33][V][modbus:310]: Clearing buffer of 1 bytes - timeout at 16885
[12:00:33][V][modbus:067]: Modbus received first Byte  1 (0X1) at 16869
[12:00:33][D][uart_debug:114]: <<< 00:01:04:A0:43:60:5E:A0:43:64:BD:28:43:69:37:12:41:6D:8A:55:40:73:F9:7A:3F:9B:DB:21:45:4E:BA:AB:44:40:E9:D0:43:6E:AF:FA:45:4F:64:2A:44:59:A0:BC:43:90:25:D1:C3:84:76:EE:43:C9:75:42:C3:21:AF:C8:3F:7F:2F:3A:3F:62:ED:6A:3F:53:F2:FB:C0:92:65:B7:41:DC:96:48:C2:08:76:FF:43:64:C6:49:00:00:00:00:40:D3:9C:C0:41:9E:B5:90:00:00:00:00:45:86:F0:0F:00:00:00:00:45:8B:E8:8A:00:00:00:00:C1:BD:99:02:3F:7F:FF:28:00:00:00:00:C1:2E:71:C6:00:00:00:00:42:48:09:DE:46:D4
[12:00:33][D][sdm_meter:043]: SDMMeter Phase A: V=224.370 V, I=14.846 A, Active P=3307.667 W, Apparent P=3318.260 VA, Reactive P=-264.929 var, PF=0.997, PA=-4.575 °
[12:00:33][V][sensor:043]: 'SDM630 Phase A Voltage': Received new state 224.369629
[12:00:33][D][sensor:094]: 'SDM630 Phase A Voltage': Sending state 224.36963 V with 2 decimals of accuracy
[12:00:33][V][sensor:043]: 'SDM630 Phase A Current': Received new state 14.846272
[12:00:34][D][sensor:094]: 'SDM630 Phase A Current': Sending state 14.84627 A with 3 decimals of accuracy
[12:00:34][V][sensor:043]: 'SDM630 Phase A Power': Received new state 3307.666748
[12:00:34][D][sensor:094]: 'SDM630 Phase A Power': Sending state 3307.66675 W with 2 decimals of accuracy
[12:00:34][V][sensor:043]: 'SDM630 Phase A Apparent Power': Received new state 3318.260254
[12:00:34][D][sensor:094]: 'SDM630 Phase A Apparent Power': Sending state 3318.26025 VA with 2 decimals of accuracy
[12:00:34][V][sensor:043]: 'SDM630 Phase A Reactive Power': Received new state -264.929138
[12:00:34][D][sensor:094]: 'SDM630 Phase A Reactive Power': Sending state -264.92914 var with 2 decimals of accuracy
[12:00:34][V][sensor:043]: 'SDM630 Phase A Power Factor': Received new state 0.996814
[12:00:34][D][sensor:094]: 'SDM630 Phase A Power Factor': Sending state 0.99681  with 3 decimals of accuracy
[12:00:34][V][sensor:043]: 'SDM630 Phase A Phase Angle': Received new state -4.574916
[12:00:34][D][sensor:094]: 'SDM630 Phase A Phase Angle': Sending state -4.57492 ° with 3 decimals of accuracy
[12:00:34][D][sdm_meter:043]: SDMMeter Phase B: V=228.739 V, I=3.812 A, Active P=771.653 W, Apparent P=870.511 VA, Reactive P=402.916 var, PF=0.886, PA=27.573 °
[12:00:34][V][sensor:043]: 'SDM630 Phase B Voltage': Received new state 228.738892
[12:00:34][D][sensor:094]: 'SDM630 Phase B Voltage': Sending state 228.73889 V with 2 decimals of accuracy
[12:00:34][V][sensor:043]: 'SDM630 Phase B Current': Received new state 3.812102
[12:00:34][D][sensor:094]: 'SDM630 Phase B Current': Sending state 3.81210 A with 3 decimals of accuracy
[12:00:34][V][sensor:043]: 'SDM630 Phase B Power': Received new state 771.653320
[12:00:34][D][sensor:094]: 'SDM630 Phase B Power': Sending state 771.65332 W with 2 decimals of accuracy
[12:00:34][V][sensor:043]: 'SDM630 Phase B Apparent Power': Received new state 870.511475
[12:00:34][D][sensor:094]: 'SDM630 Phase B Apparent Power': Sending state 870.51147 VA with 2 decimals of accuracy
[12:00:34][V][sensor:043]: 'SDM630 Phase B Reactive Power': Received new state 402.916077
[12:00:34][D][sensor:094]: 'SDM630 Phase B Reactive Power': Sending state 402.91608 var with 2 decimals of accuracy
[12:00:34][V][sensor:043]: 'SDM630 Phase B Power Factor': Received new state 0.886435
[12:00:34][D][sensor:094]: 'SDM630 Phase B Power Factor': Sending state 0.88644  with 3 decimals of accuracy
[12:00:34][V][sensor:043]: 'SDM630 Phase B Phase Angle': Received new state 27.573380
[12:00:34][D][sensor:094]: 'SDM630 Phase B Phase Angle': Sending state 27.57338 ° with 3 decimals of accuracy
[12:00:34][D][sdm_meter:043]: SDMMeter Phase C: V=233.215 V, I=1.218 A, Active P=238.687 W, Apparent P=288.295 VA, Reactive P=-161.687 var, PF=0.828, PA=-34.116 °
[12:00:34][V][sensor:043]: 'SDM630 Phase C Voltage': Received new state 233.215118
[12:00:34][D][sensor:094]: 'SDM630 Phase C Voltage': Sending state 233.21512 V with 2 decimals of accuracy
[12:00:34][V][sensor:043]: 'SDM630 Phase C Current': Received new state 1.217625
[12:00:34][D][sensor:094]: 'SDM630 Phase C Current': Sending state 1.21762 A with 3 decimals of accuracy
[12:00:34][V][sensor:043]: 'SDM630 Phase C Power': Received new state 238.687408
[12:00:34][D][sensor:094]: 'SDM630 Phase C Power': Sending state 238.68741 W with 2 decimals of accuracy
[12:00:34][V][sensor:043]: 'SDM630 Phase C Apparent Power': Received new state 288.295441
[12:00:34][D][sensor:094]: 'SDM630 Phase C Apparent Power': Sending state 288.29544 VA with 2 decimals of accuracy
[12:00:34][V][sensor:043]: 'SDM630 Phase C Reactive Power': Received new state -161.686646
[12:00:34][D][sensor:094]: 'SDM630 Phase C Reactive Power': Sending state -161.68665 var with 2 decimals of accuracy
[12:00:34][V][sensor:043]: 'SDM630 Phase C Power Factor': Received new state 0.827926
[12:00:34][D][sensor:094]: 'SDM630 Phase C Power Factor': Sending state 0.82793  with 3 decimals of accuracy
[12:00:34][V][sensor:043]: 'SDM630 Phase C Phase Angle': Received new state -34.116207
[12:00:34][D][sensor:094]: 'SDM630 Phase C Phase Angle': Sending state -34.11621 ° with 3 decimals of accuracy
[12:00:34][D][sdm_meter:069]: SDMMeter: F=50.010 Hz, Im.A.E=27253.033 Wh, Ex.A.E=0.001 Wh, Im.R.E=1618.222 VARh, Ex.R.E=3167.584 VARh, T.P=4318.007 W
[12:00:34][V][sensor:043]: 'SDM630 Total Power': Received new state 4318.007324
[12:00:34][D][sensor:094]: 'SDM630 Total Power': Sending state 4318.00732 W with 2 decimals of accuracy
[12:00:34][V][sensor:043]: 'SDM630 Frequency': Received new state 50.009636
[12:00:34][D][sensor:094]: 'SDM630 Frequency': Sending state 50.00964 Hz with 3 decimals of accuracy
[12:00:34][V][sensor:043]: 'SDM630 Import Active Energy': Received new state 27253.033203
[12:00:34][D][sensor:094]: 'SDM630 Import Active Energy': Sending state 27253.03320 kWh with 2 decimals of accuracy
[12:00:34][V][sensor:043]: 'SDM630 Export Active Energy': Received new state 0.001000
[12:00:34][D][sensor:094]: 'SDM630 Export Active Energy': Sending state 0.00100 kWh with 2 decimals of accuracy
[12:00:34][V][sensor:043]: 'SDM630 Import Reactive Energy': Received new state 1618.222046
[12:00:34][D][sensor:094]: 'SDM630 Import Reactive Energy': Sending state 1618.22205 kVARh with 2 decimals of accuracy
[12:00:34][V][sensor:043]: 'SDM630 Export Reactive Energy': Received new state 3167.583984
[12:00:34][D][sensor:094]: 'SDM630 Export Reactive Energy': Sending state 3167.58398 kVARh with 2 decimals of accuracy
[12:00:34][V][modbus:310]: Clearing buffer of 165 bytes - parse succeeded at 17705
[12:00:34][V][modbus:067]: Modbus received first Byte  0 (0X0) at 17718
[12:00:34][W][component:237]: Component modbus took a long time for an operation (608 ms).
[12:00:34][W][component:238]: Components should block for at most 30 ms.
[12:00:34][V][modbus:310]: Clearing buffer of 1 bytes - timeout at 17735
[12:00:34][D][uart_debug:114]: <<< EA:11:3A:83:12:6F:44:CA:47:1B:45:45:F9:58:E8:12:00
[12:00:43][V][modbus:221]: Modbus write: 01.04.00.00.00.50.F0.36 (8) at 26853
[12:00:43][D][uart_debug:114]: >>> 01:04:00:00:00:50:F0:36
[12:00:43][V][modbus:067]: Modbus received first Byte  0 (0X0) at 17720
[12:00:43][V][modbus:310]: Clearing buffer of 1 bytes - timeout at 26891
[12:00:43][V][modbus:067]: Modbus received first Byte  1 (0X1) at 26874
[12:00:43][D][uart_debug:114]: <<< 00:01:04:A0:43:64:A2:43:43:63:D2:5F:43:68:15:A4:40:B5:6D:AB:40:72:51:6B:3F:8F:77:80:44:9B:FB:66:44:3D:57:29:43:55:E5:55:44:9F:78:B3:44:57:54:7F:43:82:10:6D:C3:84:B5:C1:43:CD:1B:66:C3:14:09:C9:3F:7A:66:26:3F:61:19:D5:3F:52:7F:C2:C1:40:21:75:41:E3:8D:54:C2:0B:39:09:43:65:83:6D:00:00:00:00:40:61:D0:BB:41:29:5C:8C:00:00:00:00:45:0A:A2:33:00:00:00:00:45:15:D2:0D:00:00:00:00:00:00:00:00:3F:7F:FF:EB:00:00:00:00:C1:A3:BE:11:00:00:00:00:42:47:F9:93:46:D4
[12:00:43][D][sdm_meter:043]: SDMMeter Phase A: V=228.634 V, I=5.670 A, Active P=1247.856 W, Apparent P=1275.772 VA, Reactive P=-265.420 var, PF=0.978, PA=-12.008 °
[12:00:43][V][sensor:043]: 'SDM630 Phase A Voltage': Received new state 228.633835
[12:00:44][D][sensor:094]: 'SDM630 Phase A Voltage': Sending state 228.63383 V with 2 decimals of accuracy
[12:00:44][V][sensor:043]: 'SDM630 Phase A Current': Received new state 5.669637
[12:00:44][D][sensor:094]: 'SDM630 Phase A Current': Sending state 5.66964 A with 3 decimals of accuracy
[12:00:44][V][sensor:043]: 'SDM630 Phase A Power': Received new state 1247.856201
[12:00:44][D][sensor:094]: 'SDM630 Phase A Power': Sending state 1247.85620 W with 2 decimals of accuracy
[12:00:44][V][sensor:043]: 'SDM630 Phase A Apparent Power': Received new state 1275.771851
[12:00:44][D][sensor:094]: 'SDM630 Phase A Apparent Power': Sending state 1275.77185 VA with 2 decimals of accuracy
[12:00:44][V][sensor:043]: 'SDM630 Phase A Reactive Power': Received new state -265.419952
[12:00:44][D][sensor:094]: 'SDM630 Phase A Reactive Power': Sending state -265.41995 var with 2 decimals of accuracy
[12:00:44][V][sensor:043]: 'SDM630 Phase A Power Factor': Received new state 0.978121
[12:00:44][D][sensor:094]: 'SDM630 Phase A Power Factor': Sending state 0.97812  with 3 decimals of accuracy
[12:00:44][V][sensor:043]: 'SDM630 Phase A Phase Angle': Received new state -12.008168
[12:00:44][D][sensor:094]: 'SDM630 Phase A Phase Angle': Sending state -12.00817 ° with 3 decimals of accuracy
[12:00:44][D][sdm_meter:043]: SDMMeter Phase B: V=227.822 V, I=3.786 A, Active P=757.362 W, Apparent P=861.320 VA, Reactive P=410.214 var, PF=0.879, PA=28.444 °
[12:00:44][V][sensor:043]: 'SDM630 Phase B Voltage': Received new state 227.821762
[12:00:44][D][sensor:094]: 'SDM630 Phase B Voltage': Sending state 227.82176 V with 2 decimals of accuracy
[12:00:44][V][sensor:043]: 'SDM630 Phase B Current': Received new state 3.786219
[12:00:44][D][sensor:094]: 'SDM630 Phase B Current': Sending state 3.78622 A with 3 decimals of accuracy
[12:00:44][V][sensor:043]: 'SDM630 Phase B Power': Received new state 757.361877
[12:00:44][D][sensor:094]: 'SDM630 Phase B Power': Sending state 757.36188 W with 2 decimals of accuracy
[12:00:44][V][sensor:043]: 'SDM630 Phase B Apparent Power': Received new state 861.320251
[12:00:44][D][sensor:094]: 'SDM630 Phase B Apparent Power': Sending state 861.32025 VA with 2 decimals of accuracy
[12:00:44][V][sensor:043]: 'SDM630 Phase B Reactive Power': Received new state 410.214050
[12:00:44][D][sensor:094]: 'SDM630 Phase B Reactive Power': Sending state 410.21405 var with 2 decimals of accuracy
[12:00:44][V][sensor:043]: 'SDM630 Phase B Power Factor': Received new state 0.879300
[12:00:44][D][sensor:094]: 'SDM630 Phase B Power Factor': Sending state 0.87930  with 3 decimals of accuracy
[12:00:44][V][sensor:043]: 'SDM630 Phase B Phase Angle': Received new state 28.444008
[12:00:44][D][sensor:094]: 'SDM630 Phase B Phase Angle': Sending state 28.44401 ° with 3 decimals of accuracy
[12:00:44][D][sdm_meter:043]: SDMMeter Phase C: V=232.085 V, I=1.121 A, Active P=213.896 W, Apparent P=260.128 VA, Reactive P=-148.038 var, PF=0.822, PA=-34.806 °
[12:00:44][V][sensor:043]: 'SDM630 Phase C Voltage': Received new state 232.084534
[12:00:44][D][sensor:094]: 'SDM630 Phase C Voltage': Sending state 232.08453 V with 2 decimals of accuracy
[12:00:44][V][sensor:043]: 'SDM630 Phase C Current': Received new state 1.120834
[12:00:44][D][sensor:094]: 'SDM630 Phase C Current': Sending state 1.12083 A with 3 decimals of accuracy
[12:00:44][V][sensor:043]: 'SDM630 Phase C Power': Received new state 213.895828
[12:00:44][D][sensor:094]: 'SDM630 Phase C Power': Sending state 213.89583 W with 2 decimals of accuracy
[12:00:44][V][sensor:043]: 'SDM630 Phase C Apparent Power': Received new state 260.128326
[12:00:44][D][sensor:094]: 'SDM630 Phase C Apparent Power': Sending state 260.12833 VA with 2 decimals of accuracy
[12:00:44][V][sensor:043]: 'SDM630 Phase C Reactive Power': Received new state -148.038223
[12:00:44][D][sensor:094]: 'SDM630 Phase C Reactive Power': Sending state -148.03822 var with 2 decimals of accuracy
[12:00:44][V][sensor:043]: 'SDM630 Phase C Power Factor': Received new state 0.822262
[12:00:44][D][sensor:094]: 'SDM630 Phase C Power Factor': Sending state 0.82226  with 3 decimals of accuracy
[12:00:44][V][sensor:043]: 'SDM630 Phase C Phase Angle': Received new state -34.805698
[12:00:44][D][sensor:094]: 'SDM630 Phase C Phase Angle': Sending state -34.80570 ° with 3 decimals of accuracy
[12:00:44][D][sdm_meter:069]: SDMMeter: F=49.994 Hz, Im.A.E=27253.039 Wh, Ex.A.E=0.001 Wh, Im.R.E=1618.223 VARh, Ex.R.E=3167.584 VARh, T.P=2218.137 W
[12:00:44][V][sensor:043]: 'SDM630 Total Power': Received new state 2218.137451
[12:00:44][D][sensor:094]: 'SDM630 Total Power': Sending state 2218.13745 W with 2 decimals of accuracy
[12:00:44][V][sensor:043]: 'SDM630 Frequency': Received new state 49.993725
[12:00:44][D][sensor:094]: 'SDM630 Frequency': Sending state 49.99372 Hz with 3 decimals of accuracy
[12:00:44][V][sensor:043]: 'SDM630 Import Active Energy': Received new state 27253.039062
[12:00:44][D][sensor:094]: 'SDM630 Import Active Energy': Sending state 27253.03906 kWh with 2 decimals of accuracy
[12:00:44][V][sensor:043]: 'SDM630 Export Active Energy': Received new state 0.001000
[12:00:44][D][sensor:094]: 'SDM630 Export Active Energy': Sending state 0.00100 kWh with 2 decimals of accuracy
[12:00:44][V][sensor:043]: 'SDM630 Import Reactive Energy': Received new state 1618.223022
[12:00:44][D][sensor:094]: 'SDM630 Import Reactive Energy': Sending state 1618.22302 kVARh with 2 decimals of accuracy
[12:00:44][V][sensor:043]: 'SDM630 Export Reactive Energy': Received new state 3167.583984
[12:00:44][D][sensor:094]: 'SDM630 Export Reactive Energy': Sending state 3167.58398 kVARh with 2 decimals of accuracy
[12:00:44][V][modbus:310]: Clearing buffer of 165 bytes - parse succeeded at 27711
[12:00:44][V][modbus:067]: Modbus received first Byte  0 (0X0) at 27723
[12:00:44][W][component:237]: Component modbus took a long time for an operation (606 ms).
[12:00:44][W][component:238]: Components should block for at most 30 ms.
[12:00:44][V][modbus:310]: Clearing buffer of 1 bytes - timeout at 27741
[12:00:44][D][uart_debug:114]: <<< EA:14:3A:83:12:6F:44:CA:47:23:45:45:F9:58:02:14:00
[12:00:53][V][modbus:221]: Modbus write: 01.04.00.00.00.50.F0.36 (8) at 36842
[12:00:53][D][uart_debug:114]: >>> 01:04:00:00:00:50:F0:36
[12:00:53][V][modbus:067]: Modbus received first Byte  0 (0X0) at 27725
[12:00:53][V][modbus:310]: Clearing buffer of 1 bytes - timeout at 36881
[12:00:53][V][modbus:067]: Modbus received first Byte  1 (0X1) at 36864
[12:00:53][D][uart_debug:114]: <<< 00:01:04:A0:43:66:A6:5D:43:64:D9:0B:43:68:C3:66:40:5A:52:C5:3F:AB:88:E5:3F:8F:66:5C:44:3C:5B:1B:43:89:25:FA:43:56:17:BA:44:3C:66:0A:43:99:57:5A:43:82:62:37:41:80:50:F5:43:09:2B:5A:C3:14:E0:20:3F:7F:F1:48:3F:64:F8:48:3F:52:2D:F1:3F:9B:72:1C:41:D4:8C:D4:C2:0B:43:C6:43:66:C0:F0:00:00:00:00:3F:FB:E5:65:40:BC:EC:0C:00:00:00:00:44:9B:3A:03:00:00:00:00:44:A5:21:6A:00:00:00:00:00:00:00:00:3F:7F:FF:9F:00:00:00:00:41:5B:73:0C:00:00:00:00:42:47:FA:C6:46:D4
[12:00:53][D][sdm_meter:043]: SDMMeter Phase A: V=230.650 V, I=3.411 A, Active P=753.424 W, Apparent P=753.594 VA, Reactive P=16.040 var, PF=1.000, PA=1.214 °
[12:00:53][V][sensor:043]: 'SDM630 Phase A Voltage': Received new state 230.649857
[12:00:53][D][sensor:094]: 'SDM630 Phase A Voltage': Sending state 230.64986 V with 2 decimals of accuracy
[12:00:53][V][sensor:043]: 'SDM630 Phase A Current': Received new state 3.411302
[12:00:54][D][sensor:094]: 'SDM630 Phase A Current': Sending state 3.41130 A with 3 decimals of accuracy
[12:00:54][V][sensor:043]: 'SDM630 Phase A Power': Received new state 753.423523
[12:00:54][D][sensor:094]: 'SDM630 Phase A Power': Sending state 753.42352 W with 2 decimals of accuracy
[12:00:54][V][sensor:043]: 'SDM630 Phase A Apparent Power': Received new state 753.594360
[12:00:54][D][sensor:094]: 'SDM630 Phase A Apparent Power': Sending state 753.59436 VA with 2 decimals of accuracy
[12:00:54][V][sensor:043]: 'SDM630 Phase A Reactive Power': Received new state 16.039530
[12:00:54][D][sensor:094]: 'SDM630 Phase A Reactive Power': Sending state 16.03953 var with 2 decimals of accuracy
[12:00:54][V][sensor:043]: 'SDM630 Phase A Power Factor': Received new state 0.999775
[12:00:54][D][sensor:094]: 'SDM630 Phase A Power Factor': Sending state 0.99978  with 3 decimals of accuracy
[12:00:54][V][sensor:043]: 'SDM630 Phase A Phase Angle': Received new state 1.214420
[12:00:54][D][sensor:094]: 'SDM630 Phase A Phase Angle': Sending state 1.21442 ° with 3 decimals of accuracy
[12:00:54][D][sdm_meter:043]: SDMMeter Phase B: V=228.848 V, I=1.340 A, Active P=274.297 W, Apparent P=306.682 VA, Reactive P=137.169 var, PF=0.894, PA=26.569 °
[12:00:54][V][sensor:043]: 'SDM630 Phase B Voltage': Received new state 228.847824
[12:00:54][D][sensor:094]: 'SDM630 Phase B Voltage': Sending state 228.84782 V with 2 decimals of accuracy
[12:00:54][V][sensor:043]: 'SDM630 Phase B Current': Received new state 1.340115
[12:00:54][D][sensor:094]: 'SDM630 Phase B Current': Sending state 1.34012 A with 3 decimals of accuracy
[12:00:54][V][sensor:043]: 'SDM630 Phase B Power': Received new state 274.296692
[12:00:54][D][sensor:094]: 'SDM630 Phase B Power': Sending state 274.29669 W with 2 decimals of accuracy
[12:00:54][V][sensor:043]: 'SDM630 Phase B Apparent Power': Received new state 306.682434
[12:00:54][D][sensor:094]: 'SDM630 Phase B Apparent Power': Sending state 306.68243 VA with 2 decimals of accuracy
[12:00:54][V][sensor:043]: 'SDM630 Phase B Reactive Power': Received new state 137.169342
[12:00:54][D][sensor:094]: 'SDM630 Phase B Reactive Power': Sending state 137.16934 var with 2 decimals of accuracy
[12:00:54][V][sensor:043]: 'SDM630 Phase B Power Factor': Received new state 0.894413
[12:00:54][D][sensor:094]: 'SDM630 Phase B Power Factor': Sending state 0.89441  with 3 decimals of accuracy
[12:00:54][V][sensor:043]: 'SDM630 Phase B Phase Angle': Received new state 26.568764
[12:00:54][D][sensor:094]: 'SDM630 Phase B Phase Angle': Sending state 26.56876 ° with 3 decimals of accuracy
[12:00:54][D][sdm_meter:043]: SDMMeter Phase C: V=232.763 V, I=1.120 A, Active P=214.093 W, Apparent P=260.767 VA, Reactive P=-148.875 var, PF=0.821, PA=-34.816 °
[12:00:54][V][sensor:043]: 'SDM630 Phase C Voltage': Received new state 232.763275
[12:00:54][D][sensor:094]: 'SDM630 Phase C Voltage': Sending state 232.76328 V with 2 decimals of accuracy
[12:00:54][V][sensor:043]: 'SDM630 Phase C Current': Received new state 1.120311
[12:00:54][D][sensor:094]: 'SDM630 Phase C Current': Sending state 1.12031 A with 3 decimals of accuracy
[12:00:54][V][sensor:043]: 'SDM630 Phase C Power': Received new state 214.092682
[12:00:54][D][sensor:094]: 'SDM630 Phase C Power': Sending state 214.09268 W with 2 decimals of accuracy
[12:00:54][V][sensor:043]: 'SDM630 Phase C Apparent Power': Received new state 260.767303
[12:00:54][D][sensor:094]: 'SDM630 Phase C Apparent Power': Sending state 260.76730 VA with 2 decimals of accuracy
[12:00:54][V][sensor:043]: 'SDM630 Phase C Reactive Power': Received new state -148.875488
[12:00:54][D][sensor:094]: 'SDM630 Phase C Reactive Power': Sending state -148.87549 var with 2 decimals of accuracy
[12:00:54][V][sensor:043]: 'SDM630 Phase C Power Factor': Received new state 0.821014
[12:00:54][D][sensor:094]: 'SDM630 Phase C Power Factor': Sending state 0.82101  with 3 decimals of accuracy
[12:00:54][V][sensor:043]: 'SDM630 Phase C Phase Angle': Received new state -34.816185
[12:00:54][D][sensor:094]: 'SDM630 Phase C Phase Angle': Sending state -34.81618 ° with 3 decimals of accuracy
[12:00:54][D][sdm_meter:069]: SDMMeter: F=49.995 Hz, Im.A.E=27253.047 Wh, Ex.A.E=0.001 Wh, Im.R.E=1618.224 VARh, Ex.R.E=3167.586 VARh, T.P=1241.813 W
[12:00:54][V][sensor:043]: 'SDM630 Total Power': Received new state 1241.812866
[12:00:54][D][sensor:094]: 'SDM630 Total Power': Sending state 1241.81287 W with 2 decimals of accuracy
[12:00:54][V][sensor:043]: 'SDM630 Frequency': Received new state 49.994896
[12:00:54][D][sensor:094]: 'SDM630 Frequency': Sending state 49.99490 Hz with 3 decimals of accuracy
[12:00:54][V][sensor:043]: 'SDM630 Import Active Energy': Received new state 27253.046875
[12:00:54][D][sensor:094]: 'SDM630 Import Active Energy': Sending state 27253.04688 kWh with 2 decimals of accuracy
[12:00:54][V][sensor:043]: 'SDM630 Export Active Energy': Received new state 0.001000
[12:00:54][D][sensor:094]: 'SDM630 Export Active Energy': Sending state 0.00100 kWh with 2 decimals of accuracy
[12:00:54][V][sensor:043]: 'SDM630 Import Reactive Energy': Received new state 1618.223999
[12:00:54][D][sensor:094]: 'SDM630 Import Reactive Energy': Sending state 1618.22400 kVARh with 2 decimals of accuracy
[12:00:54][V][sensor:043]: 'SDM630 Export Reactive Energy': Received new state 3167.585938
[12:00:54][D][sensor:094]: 'SDM630 Export Reactive Energy': Sending state 3167.58594 kVARh with 2 decimals of accuracy
[12:00:54][V][modbus:310]: Clearing buffer of 165 bytes - parse succeeded at 37700
[12:00:54][V][modbus:067]: Modbus received first Byte  0 (0X0) at 37713
[12:00:54][W][component:237]: Component modbus took a long time for an operation (605 ms).
[12:00:54][W][component:238]: Components should block for at most 30 ms.
[12:00:54][V][modbus:310]: Clearing buffer of 1 bytes - timeout at 37733
[12:00:54][D][uart_debug:114]: <<< EA:18:3A:83:12:6F:44:CA:47:2B:45:45:F9:60:26:8E:00 
```

### Standard version Arduino, same settings as 2.0.6
```
INFO Successful handshake with utilhouse @ 192.168.1.12 in 0.137s
[12:11:34][I][app:100]: ESPHome version 2024.12.2 compiled on Jan  6 2025, 12:09:05
[12:11:34][C][status_led:019]: Status LED:
[12:11:34][C][status_led:020]:   Pin: GPIO25
[12:11:34][C][wifi:600]: WiFi:
[12:11:34][C][wifi:428]:   Local MAC: 7C:9E:BD:F3:1A:34
[12:11:34][C][wifi:433]:   SSID: [redacted]
[12:11:34][C][wifi:436]:   IP Address: 192.168.1.12
[12:11:34][C][wifi:440]:   BSSID: [redacted]
[12:11:34][C][wifi:441]:   Hostname: 'utilhouse'
[12:11:34][C][wifi:443]:   Signal strength: -74 dB ▂▄▆█
[12:11:34][V][wifi:445]:   Priority: 0.0
[12:11:34][C][wifi:447]:   Channel: 6
[12:11:34][C][wifi:448]:   Subnet: 255.255.255.0
[12:11:34][C][wifi:449]:   Gateway: 192.168.1.1
[12:11:34][C][wifi:450]:   DNS1: 8.8.8.8
[12:11:34][C][wifi:451]:   DNS2: 1.1.1.1
[12:11:34][C][logger:185]: Logger:
[12:11:34][C][logger:186]:   Level: VERBOSE
[12:11:34][C][logger:188]:   Log Baud Rate: 115200
[12:11:34][C][logger:189]:   Hardware UART: UART0
[12:11:34][C][gpio.one_wire:020]: GPIO 1-wire bus:
[12:11:34][C][gpio.one_wire:021]:   Pin: GPIO32
[12:11:34][C][gpio.one_wire:080]:   Found devices:
[12:11:34][C][gpio.one_wire:082]:     0xa73c01f09514a628 (DS18B20)
[12:11:34][C][uart.arduino_esp32:151]: UART Bus 1:
[12:11:34][C][uart.arduino_esp32:152]:   TX Pin: GPIO17
[12:11:34][C][uart.arduino_esp32:153]:   RX Pin: GPIO16
[12:11:34][C][uart.arduino_esp32:155]:   RX Buffer Size: 256
[12:11:34][C][uart.arduino_esp32:157]:   Baud Rate: 9600 baud
[12:11:34][C][uart.arduino_esp32:158]:   Data Bits: 8
[12:11:34][C][uart.arduino_esp32:159]:   Parity: NONE
[12:11:34][C][uart.arduino_esp32:160]:   Stop bits: 1
[12:11:34][C][modbus:230]: Modbus:
[12:11:34][C][modbus:231]:   Flow Control Pin: GPIO5
[12:11:34][C][modbus:232]:   Send Wait Time: 200 ms
[12:11:34][C][modbus:233]:   Turnaround Time: 200 ms
[12:11:34][C][modbus:234]:   Frame Delay: 5 ms
[12:11:34][C][modbus:235]:   Long Rx Buffer Delay: 138 ms
[12:11:34][C][modbus:236]:   CRC Disabled: NO
[12:11:34][C][uptime.sensor:033]: Uptime Sensor 'Uptime'
[12:11:34][C][uptime.sensor:033]:   Device Class: 'duration'
[12:11:34][C][uptime.sensor:033]:   State Class: 'total_increasing'
[12:11:34][C][uptime.sensor:033]:   Unit of Measurement: 'h'
[12:11:34][C][uptime.sensor:033]:   Accuracy Decimals: 0
[12:11:34][C][uptime.sensor:033]:   Icon: 'mdi:timer-outline'
[12:11:34][V][uptime.sensor:033]:   Unique ID: '7c9ebdf31a34-uptime'
[12:11:34][C][uptime.sensor:034]:   Type: Seconds
[12:11:34][C][dallas.temp.sensor:029]: Dallas Temperature Sensor:
[12:11:34][C][dallas.temp.sensor:034]:   Address: 0xa73c01f09514a628 (DS18B20)
[12:11:34][C][dallas.temp.sensor:035]:   Resolution: 12 bits
[12:11:34][C][dallas.temp.sensor:036]:   Update Interval: 60.0s
[12:11:34][C][sdm_meter:087]: SDM Meter:
[12:11:34][C][sdm_meter:088]:   Address: 0x01
[12:11:34][C][sdm_meter:093]:   Phase A
[12:11:34][C][sdm_meter:094]:     Voltage 'SDM630 Phase A Voltage'
[12:11:34][C][sdm_meter:094]:       Device Class: 'voltage'
[12:11:34][C][sdm_meter:094]:       State Class: 'measurement'
[12:11:34][C][sdm_meter:094]:       Unit of Measurement: 'V'
[12:11:34][C][sdm_meter:094]:       Accuracy Decimals: 2
[12:11:34][C][sdm_meter:095]:     Current 'SDM630 Phase A Current'
[12:11:34][C][sdm_meter:095]:       Device Class: 'current'
[12:11:34][C][sdm_meter:095]:       State Class: 'measurement'
[12:11:34][C][sdm_meter:095]:       Unit of Measurement: 'A'
[12:11:34][C][sdm_meter:095]:       Accuracy Decimals: 3
[12:11:34][C][sdm_meter:096]:     Active Power 'SDM630 Phase A Power'
[12:11:34][C][sdm_meter:096]:       Device Class: 'power'
[12:11:34][C][sdm_meter:096]:       State Class: 'measurement'
[12:11:34][C][sdm_meter:096]:       Unit of Measurement: 'W'
[12:11:34][C][sdm_meter:096]:       Accuracy Decimals: 2
[12:11:34][C][sdm_meter:097]:     Apparent Power 'SDM630 Phase A Apparent Power'
[12:11:34][C][sdm_meter:097]:       State Class: 'measurement'
[12:11:34][C][sdm_meter:097]:       Unit of Measurement: 'VA'
[12:11:34][C][sdm_meter:097]:       Accuracy Decimals: 2
[12:11:34][C][sdm_meter:098]:     Reactive Power 'SDM630 Phase A Reactive Power'
[12:11:34][C][sdm_meter:098]:       State Class: 'measurement'
[12:11:34][C][sdm_meter:098]:       Unit of Measurement: 'var'
[12:11:34][C][sdm_meter:098]:       Accuracy Decimals: 2
[12:11:34][C][sdm_meter:099]:     Power Factor 'SDM630 Phase A Power Factor'
[12:11:34][C][sdm_meter:099]:       Device Class: 'power_factor'
[12:11:34][C][sdm_meter:099]:       State Class: 'measurement'
[12:11:34][C][sdm_meter:099]:       Unit of Measurement: ''
[12:11:34][C][sdm_meter:099]:       Accuracy Decimals: 3
[12:11:34][C][sdm_meter:100]:     Phase Angle 'SDM630 Phase A Phase Angle'
[12:11:34][C][sdm_meter:100]:       State Class: ''
[12:11:34][C][sdm_meter:100]:       Unit of Measurement: '°'
[12:11:34][C][sdm_meter:100]:       Accuracy Decimals: 3
[12:11:34][C][sdm_meter:100]:       Icon: 'mdi:flash'
[12:11:34][C][sdm_meter:093]:   Phase B
[12:11:34][C][sdm_meter:094]:     Voltage 'SDM630 Phase B Voltage'
[12:11:34][C][sdm_meter:094]:       Device Class: 'voltage'
[12:11:34][C][sdm_meter:094]:       State Class: 'measurement'
[12:11:34][C][sdm_meter:094]:       Unit of Measurement: 'V'
[12:11:34][C][sdm_meter:094]:       Accuracy Decimals: 2
[12:11:34][C][sdm_meter:095]:     Current 'SDM630 Phase B Current'
[12:11:34][C][sdm_meter:095]:       Device Class: 'current'
[12:11:34][C][sdm_meter:095]:       State Class: 'measurement'
[12:11:34][C][sdm_meter:095]:       Unit of Measurement: 'A'
[12:11:34][C][sdm_meter:095]:       Accuracy Decimals: 3
[12:11:34][C][sdm_meter:096]:     Active Power 'SDM630 Phase B Power'
[12:11:34][C][sdm_meter:096]:       Device Class: 'power'
[12:11:34][C][sdm_meter:096]:       State Class: 'measurement'
[12:11:34][C][sdm_meter:096]:       Unit of Measurement: 'W'
[12:11:34][C][sdm_meter:096]:       Accuracy Decimals: 2
[12:11:34][C][sdm_meter:097]:     Apparent Power 'SDM630 Phase B Apparent Power'
[12:11:34][C][sdm_meter:097]:       State Class: 'measurement'
[12:11:34][C][sdm_meter:097]:       Unit of Measurement: 'VA'
[12:11:34][C][sdm_meter:097]:       Accuracy Decimals: 2
[12:11:35][C][sdm_meter:098]:     Reactive Power 'SDM630 Phase B Reactive Power'
[12:11:35][C][sdm_meter:098]:       State Class: 'measurement'
[12:11:35][C][sdm_meter:098]:       Unit of Measurement: 'var'
[12:11:35][C][sdm_meter:098]:       Accuracy Decimals: 2
[12:11:35][C][sdm_meter:099]:     Power Factor 'SDM630 Phase B Power Factor'
[12:11:35][C][sdm_meter:099]:       Device Class: 'power_factor'
[12:11:35][C][sdm_meter:099]:       State Class: 'measurement'
[12:11:35][C][sdm_meter:099]:       Unit of Measurement: ''
[12:11:35][C][sdm_meter:099]:       Accuracy Decimals: 3
[12:11:35][C][sdm_meter:100]:     Phase Angle 'SDM630 Phase B Phase Angle'
[12:11:35][C][sdm_meter:100]:       State Class: ''
[12:11:35][C][sdm_meter:100]:       Unit of Measurement: '°'
[12:11:35][C][sdm_meter:100]:       Accuracy Decimals: 3
[12:11:35][C][sdm_meter:100]:       Icon: 'mdi:flash'
[12:11:35][C][sdm_meter:093]:   Phase C
[12:11:35][C][sdm_meter:094]:     Voltage 'SDM630 Phase C Voltage'
[12:11:35][C][sdm_meter:094]:       Device Class: 'voltage'
[12:11:35][C][sdm_meter:094]:       State Class: 'measurement'
[12:11:35][C][sdm_meter:094]:       Unit of Measurement: 'V'
[12:11:35][C][sdm_meter:094]:       Accuracy Decimals: 2
[12:11:35][C][sdm_meter:095]:     Current 'SDM630 Phase C Current'
[12:11:35][C][sdm_meter:095]:       Device Class: 'current'
[12:11:35][C][sdm_meter:095]:       State Class: 'measurement'
[12:11:35][C][sdm_meter:095]:       Unit of Measurement: 'A'
[12:11:35][C][sdm_meter:095]:       Accuracy Decimals: 3
[12:11:35][C][sdm_meter:096]:     Active Power 'SDM630 Phase C Power'
[12:11:35][C][sdm_meter:096]:       Device Class: 'power'
[12:11:35][C][sdm_meter:096]:       State Class: 'measurement'
[12:11:35][C][sdm_meter:096]:       Unit of Measurement: 'W'
[12:11:35][C][sdm_meter:096]:       Accuracy Decimals: 2
[12:11:35][C][sdm_meter:097]:     Apparent Power 'SDM630 Phase C Apparent Power'
[12:11:35][C][sdm_meter:097]:       State Class: 'measurement'
[12:11:35][C][sdm_meter:097]:       Unit of Measurement: 'VA'
[12:11:35][C][sdm_meter:097]:       Accuracy Decimals: 2
[12:11:35][C][sdm_meter:098]:     Reactive Power 'SDM630 Phase C Reactive Power'
[12:11:35][C][sdm_meter:098]:       State Class: 'measurement'
[12:11:35][C][sdm_meter:098]:       Unit of Measurement: 'var'
[12:11:35][C][sdm_meter:098]:       Accuracy Decimals: 2
[12:11:35][C][sdm_meter:099]:     Power Factor 'SDM630 Phase C Power Factor'
[12:11:35][C][sdm_meter:099]:       Device Class: 'power_factor'
[12:11:35][C][sdm_meter:099]:       State Class: 'measurement'
[12:11:35][C][sdm_meter:099]:       Unit of Measurement: ''
[12:11:35][C][sdm_meter:099]:       Accuracy Decimals: 3
[12:11:35][C][sdm_meter:100]:     Phase Angle 'SDM630 Phase C Phase Angle'
[12:11:35][C][sdm_meter:100]:       State Class: ''
[12:11:35][C][sdm_meter:100]:       Unit of Measurement: '°'
[12:11:35][C][sdm_meter:100]:       Accuracy Decimals: 3
[12:11:35][C][sdm_meter:100]:       Icon: 'mdi:flash'
[12:11:35][C][sdm_meter:102]:   Total Power 'SDM630 Total Power'
[12:11:35][C][sdm_meter:102]:     Device Class: 'power'
[12:11:35][C][sdm_meter:102]:     State Class: 'measurement'
[12:11:35][C][sdm_meter:102]:     Unit of Measurement: 'W'
[12:11:35][C][sdm_meter:102]:     Accuracy Decimals: 2
[12:11:35][C][sdm_meter:103]:   Frequency 'SDM630 Frequency'
[12:11:35][C][sdm_meter:103]:     State Class: 'measurement'
[12:11:35][C][sdm_meter:103]:     Unit of Measurement: 'Hz'
[12:11:35][C][sdm_meter:103]:     Accuracy Decimals: 3
[12:11:35][C][sdm_meter:103]:     Icon: 'mdi:current-ac'
[12:11:35][C][sdm_meter:104]:   Import Active Energy 'SDM630 Import Active Energy'
[12:11:35][C][sdm_meter:104]:     Device Class: 'energy'
[12:11:35][C][sdm_meter:104]:     State Class: 'total_increasing'
[12:11:35][C][sdm_meter:104]:     Unit of Measurement: 'kWh'
[12:11:35][C][sdm_meter:104]:     Accuracy Decimals: 2
[12:11:35][C][sdm_meter:105]:   Export Active Energy 'SDM630 Export Active Energy'
[12:11:35][C][sdm_meter:105]:     Device Class: 'energy'
[12:11:35][C][sdm_meter:105]:     State Class: 'total_increasing'
[12:11:35][C][sdm_meter:105]:     Unit of Measurement: 'kWh'
[12:11:35][C][sdm_meter:105]:     Accuracy Decimals: 2
[12:11:35][C][sdm_meter:106]:   Import Reactive Energy 'SDM630 Import Reactive Energy'
[12:11:35][C][sdm_meter:106]:     State Class: 'total_increasing'
[12:11:35][C][sdm_meter:106]:     Unit of Measurement: 'kVARh'
[12:11:35][C][sdm_meter:106]:     Accuracy Decimals: 2
[12:11:35][C][sdm_meter:107]:   Export Reactive Energy 'SDM630 Export Reactive Energy'
[12:11:35][C][sdm_meter:107]:     State Class: 'total_increasing'
[12:11:35][C][sdm_meter:107]:     Unit of Measurement: 'kVARh'
[12:11:35][C][sdm_meter:107]:     Accuracy Decimals: 2
[12:11:35][C][status:034]: Status Binary Sensor 'Status'
[12:11:35][C][status:034]:   Device Class: 'connectivity'
[12:11:35][C][restart.button:017]: Restart Button 'Reboot'
[12:11:35][C][restart.button:017]:   Icon: 'mdi:restart'
[12:11:35][C][captive_portal:089]: Captive Portal:
[12:11:35][C][sntp:042]: SNTP Time:
[12:11:35][C][sntp:045]:   Server 0: '0.pool.ntp.org'
[12:11:35][C][sntp:045]:   Server 1: '1.pool.ntp.org'
[12:11:35][C][sntp:045]:   Server 2: '2.pool.ntp.org'
[12:11:35][C][mdns:116]: mDNS:
[12:11:35][C][mdns:117]:   Hostname: utilhouse
[12:11:35][V][mdns:118]:   Services:
[12:11:35][V][mdns:120]:   - _esphomelib, _tcp, 6053
[12:11:35][V][mdns:122]:     TXT: friendly_name = Utilitymeter House
[12:11:35][V][mdns:122]:     TXT: version = 2024.12.2
[12:11:35][V][mdns:122]:     TXT: mac = 7c9ebdf31a34
[12:11:35][V][mdns:122]:     TXT: platform = ESP32
[12:11:35][V][mdns:122]:     TXT: board = esp32dev
[12:11:35][V][mdns:122]:     TXT: network = wifi
[12:11:35][V][mdns:122]:     TXT: api_encryption = Noise_NNpsk0_25519_ChaChaPoly_SHA256
[12:11:35][C][esphome.ota:073]: Over-The-Air updates:
[12:11:35][C][esphome.ota:074]:   Address: 192.168.1.12:3232
[12:11:35][C][esphome.ota:075]:   Version: 2
[12:11:35][C][esphome.ota:078]:   Password configured
[12:11:35][C][safe_mode:018]: Safe Mode:
[12:11:35][C][safe_mode:020]:   Boot considered successful after 60 seconds
[12:11:35][C][safe_mode:021]:   Invoke after 10 boot attempts
[12:11:35][C][safe_mode:023]:   Remain in safe mode for 300 seconds
[12:11:35][C][api:140]: API Server:
[12:11:35][C][api:141]:   Address: 192.168.1.12:6053
[12:11:35][C][api:143]:   Using noise encryption: YES
[12:11:35][C][wifi_signal.sensor:010]: WiFi Signal 'WiFi Signal'
[12:11:35][C][wifi_signal.sensor:010]:   Device Class: 'signal_strength'
[12:11:35][C][wifi_signal.sensor:010]:   State Class: 'measurement'
[12:11:35][C][wifi_signal.sensor:010]:   Unit of Measurement: 'dBm'
[12:11:35][C][wifi_signal.sensor:010]:   Accuracy Decimals: 0
[12:11:35][V][wifi_signal.sensor:010]:   Unique ID: '7c9ebdf31a34-wifisignal'
[12:11:42][V][modbus:221]: Modbus write: 01.04.00.00.00.50.F0.36 (8) at 16665
[12:11:42][D][uart_debug:114]: >>> 01:04:00:00:00:50:F0:36
[12:11:42][V][modbus:067]: Modbus received first Byte  0 (0X0) at 6913
[12:11:42][W][modbus:155]: Modbus CRC Check failed! C071!=C200 00.00.00.00.C2 (5) at 16689
[12:11:42][V][modbus:310]: Clearing buffer of 5 bytes - parse failed at 16691
[12:11:42][V][modbus:067]: Modbus received first Byte  107 (0X6b) at 16704
[12:11:42][V][modbus:310]: Clearing buffer of 42 bytes - timeout at 16726
[12:11:42][D][uart_debug:114]: <<< 00:00:00:00:C2:6B:7F:97:3F:7F:F4:86:00:00:00:00:C0:90:71:52:00:00:00:00:42:48:0D:D1:46:D4:EB:63:3A:83:12:6F:44:CA:48:31:45:45:F9:EC:03:99:00
[12:11:42][V][modbus:036]: Stop waiting for response from 1
[12:11:42][V][modbus:067]: Modbus received first Byte  0 (0X0) at 16709
[12:11:42][W][modbus:155]: Modbus CRC Check failed! 2C90!=4383 00.01.04.A0.43.63.22.83.43 (9) at 16909
[12:11:42][V][modbus:310]: Clearing buffer of 9 bytes - parse failed at 16911
[12:11:42][V][modbus:067]: Modbus received first Byte  98 (0X62) at 16924
[12:11:43][D][uart_debug:114]: <<< 00:01:04:A0:43:63:22:83:43:62:29:CC:43:67:D7:EB:40:5C:32:95:40:A3:2A:7D:40:AB:C2:B2:44:3B:AD:69:44:8F:9B:5E:44:98:DD:E9:44:3B:B0:5C:44:8F:FF:1A:44:9A:06:23:41:03:77:43:42:A9:5C:7C:C3:16:C1:8F:3F:7F:FC:18:3F:7F:4E:C3:3F:7E:14:1E:3F:20:29:5B:40:86:E1:EC:C0:E0:CA:FA:43:64:61:69:00:00:00:00:40:94:1F:75:41:5E:2F:30:00:00:00:00:45:43:27:FE:00:00:00:00:45:43:EE:B6
[12:11:43][V][modbus:310]: Clearing buffer of 111 bytes - timeout at 17094
[12:11:52][V][modbus:221]: Modbus write: 01.04.00.00.00.50.F0.36 (8) at 26664
[12:11:52][D][uart_debug:114]: >>> 01:04:00:00:00:50:F0:36
[12:11:52][V][modbus:067]: Modbus received first Byte  0 (0X0) at 16933
[12:11:52][W][modbus:155]: Modbus CRC Check failed! C071!=C200 00.00.00.00.C2 (5) at 26686
[12:11:52][V][modbus:310]: Clearing buffer of 5 bytes - parse failed at 26689
[12:11:52][V][modbus:067]: Modbus received first Byte  103 (0X67) at 26702
[12:11:52][V][modbus:310]: Clearing buffer of 42 bytes - timeout at 26724
[12:11:52][D][uart_debug:114]: <<< 00:00:00:00:C2:67:6F:74:3F:7F:F5:89:00:00:00:00:C0:8F:9B:9D:00:00:00:00:42:47:F8:84:46:D4:EB:67:3A:83:12:6F:44:CA:48:39:45:45:F9:EC:8D:08:00
[12:11:52][V][modbus:036]: Stop waiting for response from 1
[12:11:52][V][modbus:067]: Modbus received first Byte  0 (0X0) at 26707
[12:11:52][W][modbus:155]: Modbus CRC Check failed! 2050!=43D6 00.01.04.A0.43.63.33.D6.43 (9) at 26908
[12:11:52][V][modbus:310]: Clearing buffer of 9 bytes - parse failed at 26922
[12:11:52][V][modbus:067]: Modbus received first Byte  99 (0X63) at 26924
[12:11:53][D][uart_debug:114]: <<< 00:01:04:A0:43:63:33:D6:43:63:58:EB:43:68:A2:3E:40:5C:A9:C1:40:A3:D5:FD:40:AD:A1:C6:44:3C:5A:59:44:90:E8:18:44:9C:4B:3B:44:3C:5E:4A:44:91:4E:ED:44:9D:7D:D6:41:1A:04:6C:42:AC:BF:EF:C3:1B:16:3B:3F:7F:FA:BD:3F:7F:4A:F9:3F:7E:0D:D3:3F:39:E2:A3:40:88:51:4B:C0:E2:3A:6D:43:65:0C:8D:00:00:00:00:40:95:0C:10:41:5F:92:18:00:00:00:00:45:45:B0:40:00:00:00:00:45:46:7D:F4
[12:11:53][V][modbus:310]: Clearing buffer of 111 bytes - timeout at 27105
[12:12:02][V][modbus:221]: Modbus write: 01.04.00.00.00.50.F0.36 (8) at 36658
[12:12:02][D][uart_debug:114]: >>> 01:04:00:00:00:50:F0:36
[12:12:02][V][modbus:067]: Modbus received first Byte  0 (0X0) at 26944
[12:12:02][W][modbus:155]: Modbus CRC Check failed! C071!=C200 00.00.00.00.C2 (5) at 36681
[12:12:02][V][modbus:310]: Clearing buffer of 5 bytes - parse failed at 36683
[12:12:02][V][modbus:067]: Modbus received first Byte  108 (0X6c) at 36696
[12:12:02][V][modbus:310]: Clearing buffer of 42 bytes - timeout at 36718
[12:12:02][D][uart_debug:114]: <<< 00:00:00:00:C2:6C:57:F3:3F:7F:F4:84:00:00:00:00:C0:91:64:4A:00:00:00:00:42:48:06:FB:46:D4:EB:6C:3A:83:12:6F:44:CA:48:39:45:45:F9:EC:E7:1E:00
[12:12:02][V][modbus:036]: Stop waiting for response from 1
[12:12:02][V][modbus:067]: Modbus received first Byte  0 (0X0) at 36701
[12:12:02][W][modbus:155]: Modbus CRC Check failed! 87D1!=432B 00.01.04.A0.43.63.B9.2B.43 (9) at 36935
[12:12:02][V][modbus:310]: Clearing buffer of 9 bytes - parse failed at 36938
[12:12:02][V][modbus:067]: Modbus received first Byte  99 (0X63) at 36951
[12:12:03][D][uart_debug:114]: <<< 00:01:04:A0:43:63:B9:2B:43:63:17:DC:43:68:74:E9:40:5D:13:6C:40:A3:C1:59:40:B1:0C:C7:44:3D:88:0A:44:90:AD:8E:44:9C:E0:71:44:3D:8B:5A:44:91:17:1A:44:9E:75:BF:41:33:82:23:42:AB:F9:B8:C3:1B:60:25:3F:7F:F8:E7:3F:7F:4C:2D:3F:7E:12:57:3F:57:E5:26:40:87:DD:23:C0:E1:32:F7:43:65:17:50:00:00:00:00:40:96:3A:5B:41:61:57:88:00:00:00:00:45:46:5B:26:00:00:00:00:45:47:28:71
[12:12:03][V][modbus:310]: Clearing buffer of 111 bytes - timeout at 37111
[12:12:12][V][modbus:221]: Modbus write: 01.04.00.00.00.50.F0.36 (8) at 46661
[12:12:12][D][uart_debug:114]: >>> 01:04:00:00:00:50:F0:36
[12:12:12][V][modbus:067]: Modbus received first Byte  0 (0X0) at 36961
[12:12:12][W][modbus:155]: Modbus CRC Check failed! C071!=C200 00.00.00.00.C2 (5) at 46684
[12:12:12][V][modbus:310]: Clearing buffer of 5 bytes - parse failed at 46686
[12:12:12][V][modbus:067]: Modbus received first Byte  104 (0X68) at 46699
[12:12:12][W][modbus:155]: Modbus CRC Check failed! 770D!=7F3F 68.AC.9A.3F.7F (5) at 46702
[12:12:12][V][modbus:310]: Clearing buffer of 5 bytes - parse failed at 46715
[12:12:12][V][modbus:067]: Modbus received first Byte  244 (0Xf4) at 46717
[12:12:12][W][modbus:155]: Modbus CRC Check failed! 3271!=00 F4.FC.00.00.00 (5) at 46731
[12:12:12][V][modbus:310]: Clearing buffer of 5 bytes - parse failed at 46733
[12:12:12][V][modbus:067]: Modbus received first Byte  0 (0X0) at 46746
[12:12:12][W][modbus:155]: Modbus CRC Check failed! 6CE0!=54AC 00.C0.91.AC.54 (5) at 46749
[12:12:12][V][modbus:310]: Clearing buffer of 5 bytes - parse failed at 46762
[12:12:12][V][modbus:067]: Modbus received first Byte  0 (0X0) at 46764
[12:12:12][W][modbus:155]: Modbus CRC Check failed! C071!=4200 00.00.00.00.42 (5) at 46766
[12:12:12][V][modbus:310]: Clearing buffer of 5 bytes - parse failed at 46780
[12:12:12][V][modbus:067]: Modbus received first Byte  72 (0X48) at 46782
[12:12:12][W][component:237]: Component modbus took a long time for an operation (130 ms).
[12:12:12][W][component:238]: Components should block for at most 30 ms.
[12:12:12][V][modbus:310]: Clearing buffer of 22 bytes - timeout at 46814
[12:12:12][V][modbus:036]: Stop waiting for response from 1
[12:12:12][V][modbus:067]: Modbus received first Byte  0 (0X0) at 46797
[12:12:12][W][modbus:155]: Modbus CRC Check failed! 8B11!=4338 00.01.04.A0.43.63.A8.38.43 (9) at 46903
[12:12:12][V][modbus:310]: Clearing buffer of 9 bytes - parse failed at 46905
[12:12:12][V][modbus:067]: Modbus received first Byte  97 (0X61) at 46918
[12:12:12][W][modbus:155]: Modbus CRC Check failed! E6C2!=6843 61.84.5E.43.68 (5) at 46921
[12:12:12][V][modbus:310]: Clearing buffer of 5 bytes - parse failed at 46935
[12:12:12][V][modbus:067]: Modbus received first Byte  221 (0Xdd) at 46937
[12:12:13][D][uart_debug:114]: <<< 00:00:00:00:C2:68:AC:9A:3F:7F:F4:FC:00:00:00:00:C0:91:AC:54:00:00:00:00:42:48:07:3C:46:D4:EB:71:3A:83:12:6F:44:CA:48:39:45:45:F9:F0:E3:42:00:00:01:04:A0:43:63:A8:38:43:61:84:5E:43:68:DD:45:40:5C:C0:74:40:A2:B8:60:40:AE:BA:AE:44:3C:DA:59:44:8E:DF:FC:44:9D:72:E1:44:3C:DF:0C:44:8F:3F:62:44:9E:A6:58:41:28:2B:6E:42:A5:36:D8:C3:1B:E0:25:3F:7F:F9:B2:3F:7F:55:AE:3F:7E:10:47:3F:4B:7A:1D:40:84:39:25:C0:E1:AB:6B:43:64:AD:F4:00:00:00:00:40:95:0E:41:41:5F:95
[12:12:13][W][component:237]: Component modbus took a long time for an operation (115 ms).
[12:12:13][W][component:238]: Components should block for at most 30 ms.
[12:12:13][D][uart_debug:114]: <<< 61:00:00:00:00:45:45:60:05:00:00:00:00:45:46:2A:A0
[12:12:13][V][modbus:310]: Clearing buffer of 106 bytes - timeout at 47161
[12:12:15][D][dallas.temp.sensor:054]: 'Temp': Got Temperature=26.7°C
[12:12:15][V][sensor:043]: 'Temp': Received new state 26.687500
[12:12:15][D][sensor:094]: 'Temp': Sending state 26.68750 °C with 1 decimals of accuracy
[12:12:16][V][sensor:043]: 'Uptime': Received new state 50.599998
[12:12:16][D][sensor:094]: 'Uptime': Sending state 0.00000 h with 0 decimals of accuracy
[12:12:22][V][modbus:221]: Modbus write: 01.04.00.00.00.50.F0.36 (8) at 56667
[12:12:22][D][uart_debug:114]: >>> 01:04:00:00:00:50:F0:36
[12:12:22][V][modbus:067]: Modbus received first Byte  0 (0X0) at 47013
[12:12:22][W][modbus:155]: Modbus CRC Check failed! C071!=C200 00.00.00.00.C2 (5) at 56690
[12:12:22][V][modbus:310]: Clearing buffer of 5 bytes - parse failed at 56692
[12:12:22][V][modbus:067]: Modbus received first Byte  123 (0X7b) at 56705
[12:12:22][W][modbus:155]: Modbus CRC Check failed! BC73!=90C0 7B.08.08.3F.7F.F3.23.00.00.00.00.C0.90 (13) at 56709
[12:12:22][V][modbus:310]: Clearing buffer of 13 bytes - parse failed at 56722
[12:12:22][V][modbus:067]: Modbus received first Byte  67 (0X43) at 56724
[12:12:22][W][modbus:155]: Modbus CRC Check failed! E4F8!=00 43.A3.00.00.00 (5) at 56738
[12:12:22][V][modbus:310]: Clearing buffer of 5 bytes - parse failed at 56740
[12:12:22][V][modbus:067]: Modbus received first Byte  0 (0X0) at 56753
[12:12:22][W][component:237]: Component modbus took a long time for an operation (84 ms).
[12:12:22][W][component:238]: Components should block for at most 30 ms.
[12:12:22][V][modbus:310]: Clearing buffer of 24 bytes - timeout at 56773
[12:12:22][V][modbus:036]: Stop waiting for response from 1
[12:12:22][D][uart_debug:114]: <<< 00:00:00:00:C2:7B:08:08:3F:7F:F3:23:00:00:00:00:C0:90:43:A3:00:00:00:00:42:48:03:BC:46:D4:EB:77:3A:83:12:6F:44:CA:48:39:45:45:F9:F0:02:3F:00
[12:12:22][V][modbus:067]: Modbus received first Byte  0 (0X0) at 56757
[12:12:22][W][modbus:155]: Modbus CRC Check failed! DD13!=4302 00.01.04.A0.43.64.20.02.43 (9) at 56919
[12:12:22][V][modbus:310]: Clearing buffer of 9 bytes - parse failed at 56922
[12:12:22][V][modbus:067]: Modbus received first Byte  97 (0X61) at 56935
[12:12:23][W][modbus:155]: Modbus CRC Check failed! EEB7!=1882 61.3D.69.43.67.59.CF.40.B5.4C.A7.40.EB.80.AB.40.AD.6F.AD.44.9B.4B.91.44.CA.EA.02.44.9A.85.39.44.9E.CB.DD.44.CF.C3.3A.44.9A.04.72.C3.84.54.7E.43.B2.9D.84.C3.16.A1.FB.3F.7A.5E.74.3F.7A.04.7C.3F.7E.14.98.C1.40.A5.C5.41.46.97.54.C0.E0.AF.14.43.64.3D.14.00.00.00.00.40.C4.62.BB.41.93.4A.0C.00.00.00.00.45.7F.70.20.00.00.00.00.45.82.18 (110) at 56944
[12:12:23][V][modbus:310]: Clearing buffer of 110 bytes - parse failed at 56978
[12:12:23][V][modbus:067]: Modbus received first Byte  10 (0Xa) at 56980
[12:12:23][W][component:237]: Component modbus took a long time for an operation (80 ms).
[12:12:23][W][component:238]: Components should block for at most 30 ms.
[12:12:23][V][modbus:310]: Clearing buffer of 1 bytes - timeout at 57008
[12:12:23][D][uart_debug:114]: <<< 00:01:04:A0:43:64:20:02:43:61:3D:69:43:67:59:CF:40:B5:4C:A7:40:EB:80:AB:40:AD:6F:AD:44:9B:4B:91:44:CA:EA:02:44:9A:85:39:44:9E:CB:DD:44:CF:C3:3A:44:9A:04:72:C3:84:54:7E:43:B2:9D:84:C3:16:A1:FB:3F:7A:5E:74:3F:7A:04:7C:3F:7E:14:98:C1:40:A5:C5:41:46:97:54:C0:E0:AF:14:43:64:3D:14:00:00:00:00:40:C4:62:BB:41:93:4A:0C:00:00:00:00:45:7F:70:20:00:00:00:00:45:82:18:0A
[12:12:26][I][safe_mode:041]: Boot seems successful; resetting boot loop counter
[12:12:26][D][esp32.preferences:114]: Saving 1 preferences to flash...
[12:12:26][V][esp32.preferences:126]: sync: key: 233825507, len: 4
[12:12:26][D][esp32.preferences:143]: Saving 1 preferences to flash: 0 cached, 1 written, 0 failed
[12:12:28][V][sensor:043]: 'WiFi Signal': Received new state -75.000000
[12:12:28][D][sensor:094]: 'WiFi Signal': Sending state -75.00000 dBm with 0 decimals of accuracy
[12:12:32][V][modbus:221]: Modbus write: 01.04.00.00.00.50.F0.36 (8) at 66667
[12:12:32][D][uart_debug:114]: >>> 01:04:00:00:00:50:F0:36
[12:12:32][V][modbus:067]: Modbus received first Byte  0 (0X0) at 56993
[12:12:32][W][modbus:155]: Modbus CRC Check failed! C071!=C200 00.00.00.00.C2 (5) at 66691
[12:12:32][V][modbus:310]: Clearing buffer of 5 bytes - parse failed at 66693
[12:12:32][V][modbus:067]: Modbus received first Byte  104 (0X68) at 66706
[12:12:32][V][modbus:310]: Clearing buffer of 42 bytes - timeout at 66727
[12:12:32][D][uart_debug:114]: <<< 00:00:00:00:C2:68:3F:C0:3F:7F:F9:BB:00:00:00:00:C1:2B:2E:28:00:00:00:00:42:48:10:6F:46:D4:EB:7D:3A:83:12:6F:44:CA:48:42:45:45:F9:F8:67:30:00
[12:12:32][V][modbus:036]: Stop waiting for response from 1
[12:12:32][V][modbus:067]: Modbus received first Byte  0 (0X0) at 66711
[12:12:32][W][modbus:155]: Modbus CRC Check failed! 7A92!=43C6 00.01.04.A0.43.64.AA.C6.43 (9) at 66909
[12:12:32][V][modbus:310]: Clearing buffer of 9 bytes - parse failed at 66922
[12:12:32][V][modbus:067]: Modbus received first Byte  98 (0X62) at 66924
[12:12:32][W][modbus:155]: Modbus CRC Check failed! 1794!=6843 62.F1.DC.43.68 (5) at 66939
[12:12:32][V][modbus:310]: Clearing buffer of 5 bytes - parse failed at 66941
[12:12:32][V][modbus:067]: Modbus received first Byte  132 (0X84) at 66954
[12:12:32][W][modbus:155]: Modbus CRC Check failed! 795D!=D5D 84.92.40.5D.0D (5) at 66957
[12:12:32][V][modbus:310]: Clearing buffer of 5 bytes - parse failed at 66970
[12:12:32][V][modbus:067]: Modbus received first Byte  87 (0X57) at 66972
[12:12:32][W][component:237]: Component modbus took a long time for an operation (87 ms).
[12:12:33][W][component:238]: Components should block for at most 30 ms.
[12:12:33][D][uart_debug:114]: <<< 00:01:04:A0:43:64:AA:C6:43:62:F1:DC:43:68:84:92:40:5D:0D:57:40:A3:A0:E6:40:AA:91:A0:44:3D:6D:14:44:90:94:B1:44:99:AC:3C:44:3D:72:FA:44:90:FB:16:44:9A:D6:99:41:3C:38:EB:42:AC:30:D1:C3:17:B2:72:3F:7F:F8:21:3F:7F:4B:36:3F:7E:12:C4:3F:63:5A:E3:40:88:3A:3E:C0:E1:1A:1C:43:65:60:67:00:00:00:00:40:94:05:7B:41:5E:08:38:00:00:00:00:45:44:27:38:00:00:00:00:45:44:F0:69
[12:12:33][V][modbus:310]: Clearing buffer of 101 bytes - timeout at 67151
[12:12:42][V][modbus:221]: Modbus write: 01.04.00.00.00.50.F0.36 (8) at 76658
[12:12:42][D][uart_debug:114]: >>> 01:04:00:00:00:50:F0:36
[12:12:42][V][modbus:067]: Modbus received first Byte  0 (0X0) at 66992
[12:12:42][W][modbus:155]: Modbus CRC Check failed! C071!=C200 00.00.00.00.C2 (5) at 76684
[12:12:42][V][modbus:310]: Clearing buffer of 5 bytes - parse failed at 76686
[12:12:42][V][modbus:067]: Modbus received first Byte  79 (0X4f) at 76699
[12:12:42][W][modbus:155]: Modbus CRC Check failed! 6611!=446F 4F.20.1B.3F.7F.F7.11.00.00.00.00.C0.91.F0.B3.00.00.00.00.42.48.0F.C0.46.D4.EB.81.3A.83.12.6F.44 (32) at 76703
[12:12:42][V][modbus:310]: Clearing buffer of 32 bytes - parse failed at 76717
[12:12:42][V][modbus:067]: Modbus received first Byte  202 (0Xca) at 76729
[12:12:42][W][component:237]: Component modbus took a long time for an operation (69 ms).
[12:12:42][W][component:238]: Components should block for at most 30 ms.
[12:12:42][V][modbus:310]: Clearing buffer of 10 bytes - timeout at 76748
[12:12:42][D][uart_debug:114]: <<< 00:00:00:00:C2:4F:20:1B:3F:7F:F7:11:00:00:00:00:C0:91:F0:B3:00:00:00:00:42:48:0F:C0:46:D4:EB:81:3A:83:12:6F:44:CA:48:4A:45:45:F9:F8:39:E3:00
[12:12:42][V][modbus:036]: Stop waiting for response from 1
[12:12:42][V][modbus:067]: Modbus received first Byte  0 (0X0) at 76732
[12:12:42][W][modbus:155]: Modbus CRC Check failed! B113!=4348 00.01.04.A0.43.64.B0.48.43 (9) at 76896
[12:12:42][V][modbus:310]: Clearing buffer of 9 bytes - parse failed at 76909
[12:12:42][V][modbus:067]: Modbus received first Byte  99 (0X63) at 76911
[12:12:43][D][uart_debug:114]: <<< 00:01:04:A0:43:64:B0:48:43:63:68:D5:43:68:70:F1:40:5C:60:10:40:A3:F8:9D:40:AC:15:EB:44:3D:20:25:44:91:1B:EB:44:9A:C9:8C:44:3D:27:0A:44:91:81:77:44:9B:F7:FD:41:4C:18:B5:42:AB:C9:57:C3:19:48:F5:3F:7F:F6:CD:3F:7F:4D:8F:3F:7E:0F:94:3F:75:CA:6A:40:87:57:1A:C0:E1:D4:2B:43:65:83:5B:00:00:00:00:40:94:87:71:41:5E:CB:2A:00:00:00:00:45:45:3A:C5:00:00:00:00:45:46:06:7D
[12:12:43][V][modbus:310]: Clearing buffer of 111 bytes - timeout at 77082
[12:12:52][V][modbus:221]: Modbus write: 01.04.00.00.00.50.F0.36 (8) at 86668
[12:12:52][D][uart_debug:114]: >>> 01:04:00:00:00:50:F0:36
[12:12:52][V][modbus:067]: Modbus received first Byte  0 (0X0) at 76932
[12:12:52][W][modbus:155]: Modbus CRC Check failed! C071!=C200 00.00.00.00.C2 (5) at 86690
[12:12:52][V][modbus:310]: Clearing buffer of 5 bytes - parse failed at 86692
[12:12:52][V][modbus:067]: Modbus received first Byte  90 (0X5a) at 86706
[12:12:52][W][modbus:155]: Modbus CRC Check failed! 3137!=7F3F 5A.8A.F8.3F.7F (5) at 86709
[12:12:52][V][modbus:310]: Clearing buffer of 5 bytes - parse failed at 86722
[12:12:52][V][modbus:067]: Modbus received first Byte  246 (0Xf6) at 86724
[12:12:52][W][modbus:155]: Modbus CRC Check failed! A283!=00 F6.39.00.00.00 (5) at 86738
[12:12:52][V][modbus:310]: Clearing buffer of 5 bytes - parse failed at 86740
[12:12:52][V][modbus:067]: Modbus received first Byte  0 (0X0) at 86753
[12:12:52][W][modbus:155]: Modbus CRC Check failed! 6DA0!=181F 00.C0.92.1F.18 (5) at 86756
[12:12:52][V][modbus:310]: Clearing buffer of 5 bytes - parse failed at 86769
[12:12:52][V][modbus:067]: Modbus received first Byte  0 (0X0) at 86771
[12:12:52][W][modbus:155]: Modbus CRC Check failed! C071!=4200 00.00.00.00.42 (5) at 86774
[12:12:52][V][modbus:310]: Clearing buffer of 5 bytes - parse failed at 86787
[12:12:52][V][modbus:067]: Modbus received first Byte  72 (0X48) at 86789
[12:12:52][W][modbus:155]: Modbus CRC Check failed! 94A!=3A87 48.06.F0.46.D4.EB.87.3A (8) at 86803
[12:12:52][V][modbus:310]: Clearing buffer of 8 bytes - parse failed at 86806
[12:12:52][V][modbus:067]: Modbus received first Byte  131 (0X83) at 86819
[12:12:52][W][component:237]: Component modbus took a long time for an operation (148 ms).
[12:12:52][W][component:238]: Components should block for at most 30 ms.
[12:12:52][V][modbus:310]: Clearing buffer of 14 bytes - timeout at 86838
[12:12:52][V][modbus:036]: Stop waiting for response from 1
[12:12:52][V][modbus:067]: Modbus received first Byte  0 (0X0) at 86822
[12:12:52][W][modbus:155]: Modbus CRC Check failed! 2212!=433A 00.01.04.A0.43.64.74.3A.43 (9) at 86912
[12:12:52][V][modbus:310]: Clearing buffer of 9 bytes - parse failed at 86914
[12:12:52][V][modbus:067]: Modbus received first Byte  99 (0X63) at 86927
[12:12:52][W][modbus:155]: Modbus CRC Check failed! B669!=6843 63.9E.1E.43.68 (5) at 86930
[12:12:52][V][modbus:310]: Clearing buffer of 5 bytes - parse failed at 86943
[12:12:52][V][modbus:067]: Modbus received first Byte  153 (0X99) at 86945
[12:12:53][D][uart_debug:114]: <<< 00:00:00:00:C2:5A:8A:F8:3F:7F:F6:39:00:00:00:00:C0:92:1F:18:00:00:00:00:42:48:06:F0:46:D4:EB:87:3A:83:12:6F:44:CA:48:4A:45:45:FA:00:BB:A5:00:00:01:04:A0:43:64:74:3A:43:63:9E:1E:43:68:99:66:40:5B:CA:29:40:A4:1F:FD:40:AC:C6:5E:44:3C:D8:80:44:91:5E:70:44:9A:21:F2:44:3C:DF:55:44:91:C6:50:44:9B:4D:7C:41:4B:26:D1:42:AD:E7:95:C3:18:39:2A:3F:7F:F6:C6:3F:7F:4B:D8:3F:7E:10:13:3F:4F:49:67:40:87:FD:26:C0:E1:B7:3F:43:65:8E:95:00:00:00:00:40:94:B6:8D:41:5F:11
[12:12:53][W][component:237]: Component modbus took a long time for an operation (114 ms).
[12:12:53][W][component:238]: Components should block for at most 30 ms.
[12:12:53][D][uart_debug:114]: <<< D3:00:00:00:00:45:46:14:53:00:00:00:00:45:46:E1:D9
[12:12:53][V][modbus:310]: Clearing buffer of 106 bytes - timeout at 87166
[12:13:02][V][modbus:221]: Modbus write: 01.04.00.00.00.50.F0.36 (8) at 96662
[12:13:02][D][uart_debug:114]: >>> 01:04:00:00:00:50:F0:36
[12:13:02][V][modbus:067]: Modbus received first Byte  0 (0X0) at 87021
[12:13:02][W][modbus:155]: Modbus CRC Check failed! C071!=C200 00.00.00.00.C2 (5) at 96685
[12:13:02][V][modbus:310]: Clearing buffer of 5 bytes - parse failed at 96687
[12:13:02][V][modbus:067]: Modbus received first Byte  103 (0X67) at 96700
[12:13:02][W][modbus:155]: Modbus CRC Check failed! 9E6C!=7F3F 67.93.BD.3F.7F (5) at 96703
[12:13:02][V][modbus:310]: Clearing buffer of 5 bytes - parse failed at 96716
[12:13:02][V][modbus:067]: Modbus received first Byte  245 (0Xf5) at 96718
[12:13:02][W][modbus:155]: Modbus CRC Check failed! F26E!=00 F5.14.00.00.00 (5) at 96732
[12:13:02][V][modbus:310]: Clearing buffer of 5 bytes - parse failed at 96735
[12:13:02][V][modbus:067]: Modbus received first Byte  0 (0X0) at 96748
[12:13:02][W][modbus:155]: Modbus CRC Check failed! 6CE0!=19AE 00.C0.91.AE.19 (5) at 96751
[12:13:02][V][modbus:310]: Clearing buffer of 5 bytes - parse failed at 96764
[12:13:02][V][modbus:067]: Modbus received first Byte  0 (0X0) at 96766
[12:13:02][W][modbus:155]: Modbus CRC Check failed! C071!=4200 00.00.00.00.42 (5) at 96769
[12:13:02][V][modbus:310]: Clearing buffer of 5 bytes - parse failed at 96782
[12:13:02][V][modbus:067]: Modbus received first Byte  72 (0X48) at 96784
[12:13:02][W][modbus:155]: Modbus CRC Check failed! BD5E!=3A8B 48.06.B7.46.D4.EB.8B.3A (8) at 96798
[12:13:02][V][modbus:310]: Clearing buffer of 8 bytes - parse failed at 96800
[12:13:02][V][modbus:067]: Modbus received first Byte  131 (0X83) at 96813
[12:13:02][W][component:237]: Component modbus took a long time for an operation (148 ms).
[12:13:02][W][component:238]: Components should block for at most 30 ms.
[12:13:02][V][modbus:310]: Clearing buffer of 14 bytes - timeout at 96832
[12:13:02][V][modbus:036]: Stop waiting for response from 1
[12:13:02][V][modbus:067]: Modbus received first Byte  0 (0X0) at 96816
[12:13:02][W][modbus:155]: Modbus CRC Check failed! 5B91!=4347 00.01.04.A0.43.60.D6.47.43 (9) at 96904
[12:13:02][V][modbus:310]: Clearing buffer of 9 bytes - parse failed at 96918
[12:13:02][V][modbus:067]: Modbus received first Byte  100 (0X64) at 96920
[12:13:02][W][modbus:155]: Modbus CRC Check failed! 81DB!=6843 64.99.16.43.68 (5) at 96934
[12:13:02][V][modbus:310]: Clearing buffer of 5 bytes - parse failed at 96937
[12:13:02][V][modbus:067]: Modbus received first Byte  196 (0Xc4) at 96950
[12:13:02][W][modbus:155]: Modbus CRC Check failed! 2E0E!=BDB3 C4.22.41.49.D6.8C.40.A5.EC.5C.40.A9.F4.06.45.30.C5.EE.44.93.95.C0.44.99.5B.24.45.30.C6.37.44.93.F4.8E.44.9A.A0.BF.41.1F.6F.46.42.A7.63.32.C3.1E.56.12.3F.7F.FF.9A.3F.7F.5C.1C.3F.7D.E5.07.3E.4C.9A.32.40.81.B3.BD (70) at 96957
[12:13:02][V][modbus:310]: Clearing buffer of 70 bytes - parse failed at 96981
[12:13:03][V][modbus:067]: Modbus received first Byte  192 (0Xc0) at 96983
[12:13:03][W][modbus:155]: Modbus CRC Check failed! F1BE!=4333 C0.EB.52.33.43 (5) at 96996
[12:13:03][V][modbus:310]: Clearing buffer of 5 bytes - parse failed at 96999
[12:13:03][V][modbus:067]: Modbus received first Byte  100 (0X64) at 97012
[12:13:03][W][modbus:155]: Modbus CRC Check failed! 7083!=00 64.BB.D5.00.00 (5) at 97015
[12:13:03][V][modbus:310]: Clearing buffer of 5 bytes - parse failed at 97027
[12:13:03][V][modbus:067]: Modbus received first Byte  0 (0X0) at 97029
[12:13:03][D][uart_debug:114]: <<< 00:00:00:00:C2:67:93:BD:3F:7F:F5:14:00:00:00:00:C0:91:AE:19:00:00:00:00:42:48:06:B7:46:D4:EB:8B:3A:83:12:6F:44:CA:48:4A:45:45:FA:00:21:8E:00:00:01:04:A0:43:60:D6:47:43:64:99:16:43:68:C4:22:41:49:D6:8C:40:A5:EC:5C:40:A9:F4:06:45:30:C5:EE:44:93:95:C0:44:99:5B:24:45:30:C6:37:44:93:F4:8E:44:9A:A0:BF:41:1F:6F:46:42:A7:63:32:C3:1E:56:12:3F:7F:FF:9A:3F:7F:5C:1C:3F:7D:E5:07:3E:4C:9A:32:40:81:B3:BD:C0:EB:52:33:43:64:BB:D5:00:00:00:00:40:F5:B7:0B:41:B8:49
[12:13:03][W][component:237]: Component modbus took a long time for an operation (200 ms).
[12:13:03][W][component:238]: Components should block for at most 30 ms.
[12:13:03][V][modbus:310]: Clearing buffer of 26 bytes - timeout at 97117
[12:13:03][D][uart_debug:114]: <<< 48:00:00:00:00:45:A3:9F:30:00:00:00:00:45:A4:08:6F
[12:13:12][V][modbus:221]: Modbus write: 01.04.00.00.00.50.F0.36 (8) at 106657
[12:13:12][D][uart_debug:114]: >>> 01:04:00:00:00:50:F0:36
[12:13:12][V][modbus:067]: Modbus received first Byte  0 (0X0) at 97100
[12:13:12][W][modbus:155]: Modbus CRC Check failed! C071!=C200 00.00.00.00.C2 (5) at 106680
[12:13:12][V][modbus:310]: Clearing buffer of 5 bytes - parse failed at 106682
[12:13:12][V][modbus:067]: Modbus received first Byte  129 (0X81) at 106695
[12:13:12][W][modbus:155]: Modbus CRC Check failed! B004!=EB50 81.5B.0A.3F.7F.FB.65.00.00.00.00.C0.31.50.EB (15) at 106698
[12:13:12][V][modbus:310]: Clearing buffer of 15 bytes - parse failed at 106712
[12:13:12][V][modbus:067]: Modbus received first Byte  0 (0X0) at 106714
[12:13:12][W][modbus:155]: Modbus CRC Check failed! C071!=4200 00.00.00.00.42 (5) at 106728
[12:13:12][V][modbus:310]: Clearing buffer of 5 bytes - parse failed at 106730
[12:13:12][V][modbus:067]: Modbus received first Byte  72 (0X48) at 106743
[12:13:12][W][component:237]: Component modbus took a long time for an operation (85 ms).
[12:13:12][W][component:238]: Components should block for at most 30 ms.
[12:13:12][V][modbus:310]: Clearing buffer of 22 bytes - timeout at 106764
[12:13:12][V][modbus:036]: Stop waiting for response from 1
[12:13:12][D][uart_debug:114]: <<< 00:00:00:00:C2:81:5B:0A:3F:7F:FB:65:00:00:00:00:C0:31:50:EB:00:00:00:00:42:48:02:F1:46:D4:EB:91:3A:83:12:6F:44:CA:48:52:45:45:FA:00:43:3A:00
[12:13:12][V][modbus:067]: Modbus received first Byte  0 (0X0) at 106748
[12:13:12][W][modbus:155]: Modbus CRC Check failed! 5152!=435D 00.01.04.A0.43.64.CF.5D.43 (9) at 106893
[12:13:12][V][modbus:310]: Clearing buffer of 9 bytes - parse failed at 106906
[12:13:12][V][modbus:067]: Modbus received first Byte  99 (0X63) at 106908
[12:13:12][W][modbus:155]: Modbus CRC Check failed! 16D!=6743 63.93.6A.43.67 (5) at 106922
[12:13:12][V][modbus:310]: Clearing buffer of 5 bytes - parse failed at 106924
[12:13:12][V][modbus:067]: Modbus received first Byte  255 (0Xff) at 106938
[12:13:12][W][modbus:155]: Modbus CRC Check failed! F026!=3659 FF.8B.40.59.36 (5) at 106941
[12:13:12][V][modbus:310]: Clearing buffer of 5 bytes - parse failed at 106954
[12:13:12][V][modbus:067]: Modbus received first Byte  217 (0Xd9) at 106956
[12:13:12][W][component:237]: Component modbus took a long time for an operation (87 ms).
[12:13:12][W][component:238]: Components should block for at most 30 ms.
[12:13:13][D][uart_debug:114]: <<< 00:01:04:A0:43:64:CF:5D:43:63:93:6A:43:67:FF:8B:40:59:36:D9:40:A4:18:D0:40:AE:AB:4D:44:3C:F0:9B:44:91:3F:11:44:9A:53:80:44:3C:F6:C5:44:91:A7:5C:44:9B:7D:AA:41:40:0B:3D:42:AE:2D:76:C3:17:F7:A7:3F:7F:F7:BE:3F:7F:48:FF:3F:7E:15:42:3F:68:DF:A8:40:89:0F:58:C0:E0:88:17:43:65:76:1C:00:00:00:00:40:94:E8:92:41:5F:5C:DB:00:00:00:00:45:45:05:6F:00:00:00:00:45:45:D0:35
[12:13:13][V][modbus:310]: Clearing buffer of 101 bytes - timeout at 107125
[12:13:15][D][dallas.temp.sensor:054]: 'Temp': Got Temperature=26.7°C
[12:13:15][V][sensor:043]: 'Temp': Received new state 26.687500
[12:13:15][D][sensor:094]: 'Temp': Sending state 26.68750 °C with 1 decimals of accuracy
[12:13:16][V][sensor:043]: 'Uptime': Received new state 110.599998
[12:13:16][D][sensor:094]: 'Uptime': Sending state 0.00000 h with 0 decimals of accuracy
[12:13:22][V][modbus:221]: Modbus write: 01.04.00.00.00.50.F0.36 (8) at 116668
[12:13:22][D][uart_debug:114]: >>> 01:04:00:00:00:50:F0:36
[12:13:22][V][modbus:067]: Modbus received first Byte  0 (0X0) at 106976
[12:13:22][W][modbus:155]: Modbus CRC Check failed! C071!=C200 00.00.00.00.C2 (5) at 116691
[12:13:22][V][modbus:310]: Clearing buffer of 5 bytes - parse failed at 116693
[12:13:22][V][modbus:067]: Modbus received first Byte  83 (0X53) at 116706
[12:13:22][W][modbus:155]: Modbus CRC Check failed! 99E1!=7F3F 53.80.E0.3F.7F (5) at 116709
[12:13:22][V][modbus:310]: Clearing buffer of 5 bytes - parse failed at 116722
[12:13:22][V][modbus:067]: Modbus received first Byte  246 (0Xf6) at 116725
[12:13:22][W][modbus:155]: Modbus CRC Check failed! 62C5!=00 F6.CD.00.00.00 (5) at 116739
[12:13:22][V][modbus:310]: Clearing buffer of 5 bytes - parse failed at 116741
[12:13:22][V][modbus:067]: Modbus received first Byte  0 (0X0) at 116754
[12:13:22][W][modbus:155]: Modbus CRC Check failed! 6CE0!=EEE2 00.C0.91.E2.EE (5) at 116757
[12:13:22][V][modbus:310]: Clearing buffer of 5 bytes - parse failed at 116770
[12:13:22][V][modbus:067]: Modbus received first Byte  0 (0X0) at 116772
[12:13:22][W][modbus:155]: Modbus CRC Check failed! C071!=4200 00.00.00.00.42 (5) at 116787
[12:13:22][V][modbus:310]: Clearing buffer of 5 bytes - parse failed at 116789
[12:13:22][V][modbus:067]: Modbus received first Byte  71 (0X47) at 116802
[12:13:22][W][modbus:155]: Modbus CRC Check failed! A00!=D446 47.FF.6A.46.D4 (5) at 116805
[12:13:22][V][modbus:310]: Clearing buffer of 5 bytes - parse failed at 116818
[12:13:22][V][modbus:067]: Modbus received first Byte  235 (0Xeb) at 116820
[12:13:22][W][modbus:155]: Modbus CRC Check failed! D7EF!=1283 EB.97.3A.83.12 (5) at 116834
[12:13:22][V][modbus:310]: Clearing buffer of 5 bytes - parse failed at 116836
[12:13:22][V][modbus:067]: Modbus received first Byte  111 (0X6f) at 116849
[12:13:22][W][component:237]: Component modbus took a long time for an operation (179 ms).
[12:13:22][W][component:238]: Components should block for at most 30 ms.
[12:13:22][V][modbus:310]: Clearing buffer of 12 bytes - timeout at 116868
[12:13:22][V][modbus:036]: Stop waiting for response from 1
[12:13:22][V][modbus:067]: Modbus received first Byte  0 (0X0) at 116852
[12:13:22][W][modbus:155]: Modbus CRC Check failed! 3912!=437B 00.01.04.A0.43.64.50.7B.43 (9) at 116905
[12:13:22][V][modbus:310]: Clearing buffer of 9 bytes - parse failed at 116918
[12:13:22][V][modbus:067]: Modbus received first Byte  100 (0X64) at 116920
[12:13:22][D][uart_debug:114]: <<< 00:00:00:00:C2:53:80:E0:3F:7F:F6:CD:00:00:00:00:C0:91:E2:EE:00:00:00:00:42:47:FF:6A:46:D4:EB:97:3A:83:12:6F:44:CA:48:52:45:45:FA:04:49:E3:00:00:01:04:A0:43:64:50:7B:43:64:2F:F3:43:68:C6:39:40:5B:EF:67:40:A4:78:E8:40:AC:34:14:44:3D:39:AE:44:91:FC:82:44:9B:1B:B1:44:3D:3F:4A:44:92:66:07:44:9C:49:2C:41:36:F3:B3:42:AF:A5:BD:C3:19:32:C9:3F:7F:F8:8E:3F:7F:47:B6:3F:7E:12:1B:3F:5D:1E:A8:40:89:8C:FB:C0:E1:B8:DB:43:65:C2:38:00:00:00:00:40:94:A9:98:41:5E:FE
[12:13:22][W][component:237]: Component modbus took a long time for an operation (85 ms).
[12:13:22][W][component:238]: Components should block for at most 30 ms.
```

### IDF version

```
INFO Upload took 9.87 seconds, waiting for result...
INFO OTA successful
INFO Successfully uploaded program.
INFO Starting log output from 192.168.1.12 using esphome API
INFO Successfully connected to utilhouse @ 192.168.1.12 in 4.239s
INFO Successful handshake with utilhouse @ 192.168.1.12 in 0.225s
[12:30:55][I][app:100]: ESPHome version 2024.12.2 compiled on Jan  6 2025, 12:25:02
[12:30:55][C][status_led:019]: Status LED:
[12:30:55][C][status_led:020]:   Pin: GPIO25
[12:30:55][C][wifi:600]: WiFi:
[12:30:55][C][wifi:428]:   Local MAC: 7C:9E:BD:F3:1A:34
[12:30:55][C][wifi:433]:   SSID: [redacted]
[12:30:55][C][wifi:436]:   IP Address: 192.168.1.12
[12:30:55][C][wifi:439]:   BSSID: [redacted]
[12:30:55][C][wifi:441]:   Hostname: 'utilhouse'
[12:30:55][C][wifi:443]:   Signal strength: -71 dB ▂▄▆█
[12:30:55][V][wifi:445]:   Priority: 0.0
[12:30:55][C][wifi:447]:   Channel: 6
[12:30:55][C][wifi:448]:   Subnet: 255.255.255.0
[12:30:55][C][wifi:449]:   Gateway: 192.168.1.1
[12:30:55][C][wifi:450]:   DNS1: 8.8.8.8
[12:30:55][C][wifi:451]:   DNS2: 1.1.1.1
[12:30:55][C][logger:185]: Logger:
[12:30:55][C][logger:186]:   Level: VERBOSE
[12:30:55][C][logger:188]:   Log Baud Rate: 115200
[12:30:55][C][logger:189]:   Hardware UART: UART0
[12:30:55][C][gpio.one_wire:020]: GPIO 1-wire bus:
[12:30:55][C][gpio.one_wire:021]:   Pin: GPIO32
[12:30:55][C][gpio.one_wire:080]:   Found devices:
[12:30:55][C][gpio.one_wire:082]:     0xa73c01f09514a628 (DS18B20)
[12:30:55][C][uart.idf:159]: UART Bus 1:
[12:30:55][C][uart.idf:160]:   TX Pin: GPIO17
[12:30:55][C][uart.idf:161]:   RX Pin: GPIO16
[12:30:55][C][uart.idf:163]:   RX Buffer Size: 256
[12:30:55][C][uart.idf:165]:   Baud Rate: 9600 baud
[12:30:55][C][uart.idf:166]:   Data Bits: 8
[12:30:55][C][uart.idf:167]:   Parity: NONE
[12:30:55][C][uart.idf:168]:   Stop bits: 1
[12:30:55][C][modbus:230]: Modbus:
[12:30:55][C][modbus:231]:   Flow Control Pin: GPIO5
[12:30:55][C][modbus:232]:   Send Wait Time: 200 ms
[12:30:55][C][modbus:233]:   Turnaround Time: 200 ms
[12:30:55][C][modbus:234]:   Frame Delay: 5 ms
[12:30:55][C][modbus:235]:   Long Rx Buffer Delay: 138 ms
[12:30:55][C][modbus:236]:   CRC Disabled: NO
[12:30:55][C][uptime.sensor:033]: Uptime Sensor 'Uptime'
[12:30:55][C][uptime.sensor:033]:   Device Class: 'duration'
[12:30:55][C][uptime.sensor:033]:   State Class: 'total_increasing'
[12:30:55][C][uptime.sensor:033]:   Unit of Measurement: 'h'
[12:30:55][C][uptime.sensor:033]:   Accuracy Decimals: 0
[12:30:55][C][uptime.sensor:033]:   Icon: 'mdi:timer-outline'
[12:30:55][V][uptime.sensor:033]:   Unique ID: '7c9ebdf31a34-uptime'
[12:30:55][C][uptime.sensor:034]:   Type: Seconds
[12:30:56][C][dallas.temp.sensor:029]: Dallas Temperature Sensor:
[12:30:56][C][dallas.temp.sensor:034]:   Address: 0xa73c01f09514a628 (DS18B20)
[12:30:56][C][dallas.temp.sensor:035]:   Resolution: 12 bits
[12:30:56][C][dallas.temp.sensor:036]:   Update Interval: 60.0s
[12:30:56][C][sdm_meter:087]: SDM Meter:
[12:30:56][C][sdm_meter:088]:   Address: 0x01
[12:30:56][C][sdm_meter:093]:   Phase A
[12:30:56][C][sdm_meter:094]:     Voltage 'SDM630 Phase A Voltage'
[12:30:56][C][sdm_meter:094]:       Device Class: 'voltage'
[12:30:56][C][sdm_meter:094]:       State Class: 'measurement'
[12:30:56][C][sdm_meter:094]:       Unit of Measurement: 'V'
[12:30:56][C][sdm_meter:094]:       Accuracy Decimals: 2
[12:30:56][C][sdm_meter:095]:     Current 'SDM630 Phase A Current'
[12:30:56][C][sdm_meter:095]:       Device Class: 'current'
[12:30:56][C][sdm_meter:095]:       State Class: 'measurement'
[12:30:56][C][sdm_meter:095]:       Unit of Measurement: 'A'
[12:30:56][C][sdm_meter:095]:       Accuracy Decimals: 3
[12:30:56][C][sdm_meter:096]:     Active Power 'SDM630 Phase A Power'
[12:30:56][C][sdm_meter:096]:       Device Class: 'power'
[12:30:56][C][sdm_meter:096]:       State Class: 'measurement'
[12:30:56][C][sdm_meter:096]:       Unit of Measurement: 'W'
[12:30:56][C][sdm_meter:096]:       Accuracy Decimals: 2
[12:30:56][C][sdm_meter:097]:     Apparent Power 'SDM630 Phase A Apparent Power'
[12:30:56][C][sdm_meter:097]:       State Class: 'measurement'
[12:30:56][C][sdm_meter:097]:       Unit of Measurement: 'VA'
[12:30:56][C][sdm_meter:097]:       Accuracy Decimals: 2
[12:30:56][C][sdm_meter:098]:     Reactive Power 'SDM630 Phase A Reactive Power'
[12:30:56][C][sdm_meter:098]:       State Class: 'measurement'
[12:30:56][C][sdm_meter:098]:       Unit of Measurement: 'var'
[12:30:56][C][sdm_meter:098]:       Accuracy Decimals: 2
[12:30:56][C][sdm_meter:099]:     Power Factor 'SDM630 Phase A Power Factor'
[12:30:56][C][sdm_meter:099]:       Device Class: 'power_factor'
[12:30:56][C][sdm_meter:099]:       State Class: 'measurement'
[12:30:56][C][sdm_meter:099]:       Unit of Measurement: ''
[12:30:56][C][sdm_meter:099]:       Accuracy Decimals: 3
[12:30:56][C][sdm_meter:100]:     Phase Angle 'SDM630 Phase A Phase Angle'
[12:30:56][C][sdm_meter:100]:       State Class: ''
[12:30:56][C][sdm_meter:100]:       Unit of Measurement: '°'
[12:30:56][C][sdm_meter:100]:       Accuracy Decimals: 3
[12:30:56][C][sdm_meter:100]:       Icon: 'mdi:flash'
[12:30:56][C][sdm_meter:093]:   Phase B
[12:30:56][C][sdm_meter:094]:     Voltage 'SDM630 Phase B Voltage'
[12:30:56][C][sdm_meter:094]:       Device Class: 'voltage'
[12:30:56][C][sdm_meter:094]:       State Class: 'measurement'
[12:30:56][C][sdm_meter:094]:       Unit of Measurement: 'V'
[12:30:56][C][sdm_meter:094]:       Accuracy Decimals: 2
[12:30:56][C][sdm_meter:095]:     Current 'SDM630 Phase B Current'
[12:30:56][C][sdm_meter:095]:       Device Class: 'current'
[12:30:56][C][sdm_meter:095]:       State Class: 'measurement'
[12:30:56][C][sdm_meter:095]:       Unit of Measurement: 'A'
[12:30:56][C][sdm_meter:095]:       Accuracy Decimals: 3
[12:30:56][C][sdm_meter:096]:     Active Power 'SDM630 Phase B Power'
[12:30:56][C][sdm_meter:096]:       Device Class: 'power'
[12:30:56][C][sdm_meter:096]:       State Class: 'measurement'
[12:30:56][C][sdm_meter:096]:       Unit of Measurement: 'W'
[12:30:56][C][sdm_meter:096]:       Accuracy Decimals: 2
[12:30:56][C][sdm_meter:097]:     Apparent Power 'SDM630 Phase B Apparent Power'
[12:30:56][C][sdm_meter:097]:       State Class: 'measurement'
[12:30:56][C][sdm_meter:097]:       Unit of Measurement: 'VA'
[12:30:56][C][sdm_meter:097]:       Accuracy Decimals: 2
[12:30:56][C][sdm_meter:098]:     Reactive Power 'SDM630 Phase B Reactive Power'
[12:30:56][C][sdm_meter:098]:       State Class: 'measurement'
[12:30:56][C][sdm_meter:098]:       Unit of Measurement: 'var'
[12:30:56][C][sdm_meter:098]:       Accuracy Decimals: 2
[12:30:56][C][sdm_meter:099]:     Power Factor 'SDM630 Phase B Power Factor'
[12:30:56][C][sdm_meter:099]:       Device Class: 'power_factor'
[12:30:56][C][sdm_meter:099]:       State Class: 'measurement'
[12:30:56][C][sdm_meter:099]:       Unit of Measurement: ''
[12:30:56][C][sdm_meter:099]:       Accuracy Decimals: 3
[12:30:56][C][sdm_meter:100]:     Phase Angle 'SDM630 Phase B Phase Angle'
[12:30:56][C][sdm_meter:100]:       State Class: ''
[12:30:56][C][sdm_meter:100]:       Unit of Measurement: '°'
[12:30:56][C][sdm_meter:100]:       Accuracy Decimals: 3
[12:30:56][C][sdm_meter:100]:       Icon: 'mdi:flash'
[12:30:56][C][sdm_meter:093]:   Phase C
[12:30:56][C][sdm_meter:094]:     Voltage 'SDM630 Phase C Voltage'
[12:30:56][C][sdm_meter:094]:       Device Class: 'voltage'
[12:30:56][C][sdm_meter:094]:       State Class: 'measurement'
[12:30:56][C][sdm_meter:094]:       Unit of Measurement: 'V'
[12:30:56][C][sdm_meter:094]:       Accuracy Decimals: 2
[12:30:56][C][sdm_meter:095]:     Current 'SDM630 Phase C Current'
[12:30:56][C][sdm_meter:095]:       Device Class: 'current'
[12:30:56][C][sdm_meter:095]:       State Class: 'measurement'
[12:30:56][C][sdm_meter:095]:       Unit of Measurement: 'A'
[12:30:56][C][sdm_meter:095]:       Accuracy Decimals: 3
[12:30:56][C][sdm_meter:096]:     Active Power 'SDM630 Phase C Power'
[12:30:56][C][sdm_meter:096]:       Device Class: 'power'
[12:30:56][C][sdm_meter:096]:       State Class: 'measurement'
[12:30:56][C][sdm_meter:096]:       Unit of Measurement: 'W'
[12:30:56][C][sdm_meter:096]:       Accuracy Decimals: 2
[12:30:56][C][sdm_meter:097]:     Apparent Power 'SDM630 Phase C Apparent Power'
[12:30:56][C][sdm_meter:097]:       State Class: 'measurement'
[12:30:56][C][sdm_meter:097]:       Unit of Measurement: 'VA'
[12:30:56][C][sdm_meter:097]:       Accuracy Decimals: 2
[12:30:56][C][sdm_meter:098]:     Reactive Power 'SDM630 Phase C Reactive Power'
[12:30:56][C][sdm_meter:098]:       State Class: 'measurement'
[12:30:56][C][sdm_meter:098]:       Unit of Measurement: 'var'
[12:30:56][C][sdm_meter:098]:       Accuracy Decimals: 2
[12:30:56][C][sdm_meter:099]:     Power Factor 'SDM630 Phase C Power Factor'
[12:30:56][C][sdm_meter:099]:       Device Class: 'power_factor'
[12:30:56][C][sdm_meter:099]:       State Class: 'measurement'
[12:30:56][C][sdm_meter:099]:       Unit of Measurement: ''
[12:30:56][C][sdm_meter:099]:       Accuracy Decimals: 3
[12:30:56][C][sdm_meter:100]:     Phase Angle 'SDM630 Phase C Phase Angle'
[12:30:56][C][sdm_meter:100]:       State Class: ''
[12:30:56][C][sdm_meter:100]:       Unit of Measurement: '°'
[12:30:56][C][sdm_meter:100]:       Accuracy Decimals: 3
[12:30:56][C][sdm_meter:100]:       Icon: 'mdi:flash'
[12:30:56][C][sdm_meter:102]:   Total Power 'SDM630 Total Power'
[12:30:56][C][sdm_meter:102]:     Device Class: 'power'
[12:30:56][C][sdm_meter:102]:     State Class: 'measurement'
[12:30:56][C][sdm_meter:102]:     Unit of Measurement: 'W'
[12:30:56][C][sdm_meter:102]:     Accuracy Decimals: 2
[12:30:56][C][sdm_meter:103]:   Frequency 'SDM630 Frequency'
[12:30:56][C][sdm_meter:103]:     State Class: 'measurement'
[12:30:56][C][sdm_meter:103]:     Unit of Measurement: 'Hz'
[12:30:56][C][sdm_meter:103]:     Accuracy Decimals: 3
[12:30:56][C][sdm_meter:103]:     Icon: 'mdi:current-ac'
[12:30:56][C][sdm_meter:104]:   Import Active Energy 'SDM630 Import Active Energy'
[12:30:56][C][sdm_meter:104]:     Device Class: 'energy'
[12:30:56][C][sdm_meter:104]:     State Class: 'total_increasing'
[12:30:56][C][sdm_meter:104]:     Unit of Measurement: 'kWh'
[12:30:56][C][sdm_meter:104]:     Accuracy Decimals: 2
[12:30:56][C][sdm_meter:105]:   Export Active Energy 'SDM630 Export Active Energy'
[12:30:56][C][sdm_meter:105]:     Device Class: 'energy'
[12:30:56][C][sdm_meter:105]:     State Class: 'total_increasing'
[12:30:56][C][sdm_meter:105]:     Unit of Measurement: 'kWh'
[12:30:56][C][sdm_meter:105]:     Accuracy Decimals: 2
[12:30:56][C][sdm_meter:106]:   Import Reactive Energy 'SDM630 Import Reactive Energy'
[12:30:56][C][sdm_meter:106]:     State Class: 'total_increasing'
[12:30:56][C][sdm_meter:106]:     Unit of Measurement: 'kVARh'
[12:30:56][C][sdm_meter:106]:     Accuracy Decimals: 2
[12:30:56][C][sdm_meter:107]:   Export Reactive Energy 'SDM630 Export Reactive Energy'
[12:30:56][C][sdm_meter:107]:     State Class: 'total_increasing'
[12:30:56][C][sdm_meter:107]:     Unit of Measurement: 'kVARh'
[12:30:56][C][sdm_meter:107]:     Accuracy Decimals: 2
[12:30:56][C][status:034]: Status Binary Sensor 'Status'
[12:30:56][C][status:034]:   Device Class: 'connectivity'
[12:30:56][C][restart.button:017]: Restart Button 'Reboot'
[12:30:56][C][restart.button:017]:   Icon: 'mdi:restart'
[12:30:56][C][captive_portal:089]: Captive Portal:
[12:30:56][C][sntp:042]: SNTP Time:
[12:30:56][C][sntp:045]:   Server 0: '0.pool.ntp.org'
[12:30:56][C][sntp:045]:   Server 1: '1.pool.ntp.org'
[12:30:56][C][sntp:045]:   Server 2: '2.pool.ntp.org'
[12:30:56][C][mdns:116]: mDNS:
[12:30:56][C][mdns:117]:   Hostname: utilhouse
[12:30:56][V][mdns:118]:   Services:
[12:30:56][V][mdns:120]:   - _esphomelib, _tcp, 6053
[12:30:56][V][mdns:122]:     TXT: friendly_name = Utilitymeter House
[12:30:56][V][mdns:122]:     TXT: version = 2024.12.2
[12:30:56][V][mdns:122]:     TXT: mac = 7c9ebdf31a34
[12:30:56][V][mdns:122]:     TXT: platform = ESP32
[12:30:56][V][mdns:122]:     TXT: board = esp32dev
[12:30:56][V][mdns:122]:     TXT: network = wifi
[12:30:56][V][mdns:122]:     TXT: api_encryption = Noise_NNpsk0_25519_ChaChaPoly_SHA256
[12:30:56][C][esphome.ota:073]: Over-The-Air updates:
[12:30:56][C][esphome.ota:078]:   Password configured
[12:30:56][C][safe_mode:018]: Safe Mode:
[12:30:56][C][safe_mode:019]:   Boot considered successful after 60 seconds
[12:30:56][C][safe_mode:021]:   Invoke after 10 boot attempts
[12:30:56][C][safe_mode:022]:   Remain in safe mode for 300 seconds
[12:30:56][C][api:140]: API Server:
[12:30:56][C][api:141]:   Address: 192.168.1.12:6053
[12:30:56][C][api:143]:   Using noise encryption: YES
[12:30:56][C][wifi_signal.sensor:010]: WiFi Signal 'WiFi Signal'
[12:30:56][C][wifi_signal.sensor:010]:   Device Class: 'signal_strength'
[12:30:56][C][wifi_signal.sensor:010]:   State Class: 'measurement'
[12:30:56][C][wifi_signal.sensor:010]:   Unit of Measurement: 'dBm'
[12:30:56][C][wifi_signal.sensor:010]:   Accuracy Decimals: 0
[12:30:56][V][wifi_signal.sensor:010]:   Unique ID: '7c9ebdf31a34-wifisignal'
[12:30:58][V][modbus:221]: Modbus write: 01.04.00.00.00.50.F0.36 (8) at 8072
[12:30:58][D][uart_debug:114]: >>> 01:04:00:00:00:50:F0:36
[12:30:58][V][modbus:067]: Modbus received first Byte  0 (0X0) at 999
[12:30:58][W][modbus:155]: Modbus CRC Check failed! C071!=4200 00.00.00.00.42 (5) at 8278
[12:30:58][V][modbus:310]: Clearing buffer of 5 bytes - parse failed at 8281
[12:30:58][V][modbus:067]: Modbus received first Byte  153 (0X99) at 8283
[12:30:58][W][modbus:155]: Modbus CRC Check failed! 59D!=7F3F 99.AC.67.3F.7F (5) at 8286
[12:30:58][V][modbus:310]: Clearing buffer of 5 bytes - parse failed at 8289
[12:30:58][V][modbus:067]: Modbus received first Byte  150 (0X96) at 8291
[12:30:58][V][modbus:036]: Stop waiting for response from 1
[12:30:58][D][uart_debug:114]: <<< 00:00:00:00:42:99:AC:67:3F:7F:96:6D:00:00:00:00:41:7D:FA:40:00:00:00:00:42:48:1B:04:46:D4:ED:B6:3A:83:12:6F:44:CA:49:60:45:45:FA:BC:F2:B8:00:00:01:04:A0:43:62:F7:92:43:66:B9:05:43:6A:9A:C1:40:5C:4C:1A:3F:C8:68:1A:3F:D2:EA:1B:44:3B:8A:FA:43:8D:C2:8B:43:B0:72:01:44:3B:8C:F3:43:B4:9E:5E:43:C1:49:7C:40:D7:F0:6C:43:5F:D9:99:C3:1D:D2:60:3F:7F:FD:68:3F:48:ED:1B:3F
[12:30:59][V][modbus:310]: Clearing buffer of 110 bytes - timeout at 8457
[12:31:08][V][modbus:221]: Modbus write: 01.04.00.00.00.50.F0.36 (8) at 18073
[12:31:08][D][uart_debug:114]: >>> 01:04:00:00:00:50:F0:36
[12:31:08][V][modbus:067]: Modbus received first Byte  105 (0X69) at 8308
[12:31:08][W][modbus:155]: Modbus CRC Check failed! FD15!=23F 69.B1.BD.3F.02 (5) at 18226
[12:31:08][V][modbus:310]: Clearing buffer of 5 bytes - parse failed at 18229
[12:31:08][V][modbus:067]: Modbus received first Byte  130 (0X82) at 18231
[12:31:08][W][modbus:155]: Modbus CRC Check failed! 649D!=463A 82.39.42.19.2D.6B.C1.C0.C6.A0.43.66.C3.C8.00.00.00.00.40.12.F3.C7.40.DC.6D.AB.00.00.00.00.44.AD.52.A0.00.00.00.00.44.BB.40.70.00.00.00.00.42.91.8D.79.3F.7F.A5.6F.00.00.00.00.41.7B.26.E5.00.00.00.00.42.48.27.3A.46 (71) at 18240
[12:31:08][V][modbus:310]: Clearing buffer of 71 bytes - parse failed at 18247
[12:31:08][V][modbus:067]: Modbus received first Byte  212 (0Xd4) at 18257
[12:31:08][W][modbus:155]: Modbus CRC Check failed! DA7C!=833A D4.ED.B8.3A.83 (5) at 18260
[12:31:08][V][modbus:310]: Clearing buffer of 5 bytes - parse failed at 18268
[12:31:08][V][modbus:067]: Modbus received first Byte  18 (0X12) at 18278
[12:31:08][V][modbus:036]: Stop waiting for response from 1
[12:31:08][W][component:237]: Component modbus took a long time for an operation (72 ms).
[12:31:08][W][component:238]: Components should block for at most 30 ms.
[12:31:08][V][modbus:310]: Clearing buffer of 39 bytes - timeout at 18310
[12:31:08][V][modbus:067]: Modbus received first Byte  112 (0X70) at 18290
[12:31:08][W][modbus:155]: Modbus CRC Check failed! D807!=DD3B 70.B7.44.3B.DD (5) at 18345
[12:31:08][V][modbus:310]: Clearing buffer of 5 bytes - parse failed at 18347
[12:31:08][V][modbus:067]: Modbus received first Byte  73 (0X49) at 18349
[12:31:08][D][uart_debug:114]: <<< 69:B1:BD:3F:02:82:39:42:19:2D:6B:C1:C0:C6:A0:43:66:C3:C8:00:00:00:00:40:12:F3:C7:40:DC:6D:AB:00:00:00:00:44:AD:52:A0:00:00:00:00:44:BB:40:70:00:00:00:00:42:91:8D:79:3F:7F:A5:6F:00:00:00:00:41:7B:26:E5:00:00:00:00:42:48:27:3A:46:D4:ED:B8:3A:83:12:6F:44:CA:49:60:45:45:FA:BC:7B:77:00:00:01:04:A0:43:62:E9:58:43:66:C3:EA:43:6A:60:73:40:5C:C9:50:3F:C8:B2:C2:3F:C4:70:B7:44:3B:DD:49:43:8E:0D:CD:43:A2:77:AE:44:3B:DD:4D:43:B4:EA:33:43:B3:D9:0A:00:00:00:00
[12:31:08][W][component:237]: Component modbus took a long time for an operation (52 ms).
[12:31:08][W][component:238]: Components should block for at most 30 ms.
[12:31:09][D][uart_debug:114]: <<< 43:60:0F:B0:C3:1A:44:41:3F:7F:FC:7F:3F:49:21:96:3F:66:6A:37:3F:17:B0:57:42:18:E1:88:C1:CE:B0:80:43:66:AF:3C:00:00:00:00:40:0F:7D:61:40:D7:3C:11:00:00:00:00:44:A8:D8:48:00:00:00:00:44:B6:E7:6C:00:00:00:00:42:9D:F8:57:3F:7F:8F:D2:00:00:00:00:41:7E:97:F7:00:00:00:00:42:48
[12:31:09][V][modbus:310]: Clearing buffer of 115 bytes - timeout at 18547
[12:31:18][V][modbus:221]: Modbus write: 01.04.00.00.00.50.F0.36 (8) at 28067
[12:31:18][D][uart_debug:114]: >>> 01:04:00:00:00:50:F0:36
[12:31:18][V][modbus:036]: Stop waiting for response from 1
[12:31:18][V][modbus:067]: Modbus received first Byte  32 (0X20) at 18392
[12:31:18][W][modbus:155]: Modbus CRC Check failed! 5880!=EDD4 20.BE.46.D4.ED (5) at 28290
[12:31:18][V][modbus:310]: Clearing buffer of 5 bytes - parse failed at 28293
[12:31:18][V][modbus:067]: Modbus received first Byte  186 (0Xba) at 28295
[12:31:18][D][uart_debug:114]: <<< 20:BE:46:D4:ED:BA:3A:83:12:6F:44:CA:49:68:45:45:FA:C1:F8:91:00:00:01:04:A0:43:62:B3:1B:43:67:4D:0C:43:6A:22:A9:40:61:C7:A8:3F:C8:E9:17:3F:BD:D6:52:44:41:9D:78:43:8E:7D:01:43:9C:6A:0E:44:41:9F:E0:43:B5:86:CC:43:AD:9F:9A:C0:F1:22:E1:43:60:EF:70:C3:16:BA:2B:3F:7F:FC:E8:3F:48:F1:AB:3F:66:A0:78:BF:0E:88:C2:42:19:26:D4:C1:CD:D1:21:43:66:B6:45:00:00:00:00:40:11:75
[12:31:19][V][modbus:310]: Clearing buffer of 115 bytes - timeout at 28451
[12:31:21][V][sensor:043]: 'Uptime': Received new state 30.591999
[12:31:21][D][sensor:093]: 'Uptime': Sending state 0.00000 h with 0 decimals of accuracy
[12:31:28][V][modbus:221]: Modbus write: 01.04.00.00.00.50.F0.36 (8) at 38073
[12:31:28][D][uart_debug:114]: >>> 01:04:00:00:00:50:F0:36
[12:31:28][V][modbus:067]: Modbus received first Byte  90 (0X5a) at 28305
[12:31:28][V][modbus:036]: Stop waiting for response from 1
[12:31:28][D][uart_debug:114]: <<< 5A:40:DA:30:07:00:00:00:00:44:AB:88:80:00:00:00:00:44:B9:99:8A:00:00:00:00:42:93:25:54:3F:7F:AA:CA:00:00:00:00:41:76:32:01:00:00:00:00:42:48:01:5D:46:D4:ED:BC:3A:83:12:6F:44:CA:49:68:45:45:FA:C1:E2:67:00:00:01:04:A0:43:5F:80:42:43:64:AB:E9:43:6B:BC:69:41:49:EA:EF:41:11:4B:D2:3F:CD:A1:F7:45:2F:8B:EF:45:00:E3:90:43:AA:0B:B0:45:2F:8B:EF:45:01:A4:6F:43:BD:5B:04
[12:31:28][V][modbus:310]: Clearing buffer of 120 bytes - timeout at 38411
[12:31:34][V][sensor:043]: 'WiFi Signal': Received new state -73.000000
[12:31:34][D][sensor:093]: 'WiFi Signal': Sending state -73.00000 dBm with 0 decimals of accuracy
[12:31:36][D][dallas.temp.sensor:054]: 'Temp': Got Temperature=26.6°C
[12:31:36][V][sensor:043]: 'Temp': Received new state 26.625000
[12:31:36][D][sensor:093]: 'Temp': Sending state 26.62500 °C with 1 decimals of accuracy
[12:31:38][V][modbus:221]: Modbus write: 01.04.00.00.00.50.F0.36 (8) at 48073
[12:31:38][D][uart_debug:114]: >>> 01:04:00:00:00:50:F0:36
[12:31:38][V][modbus:067]: Modbus received first Byte  0 (0X0) at 38262
[12:31:38][W][modbus:155]: Modbus CRC Check failed! C071!=4300 00.00.00.00.43 (5) at 48195
[12:31:38][V][modbus:310]: Clearing buffer of 5 bytes - parse failed at 48197
[12:31:38][V][modbus:067]: Modbus received first Byte  95 (0X5f) at 48199
[12:31:38][V][modbus:036]: Stop waiting for response from 1
[12:31:38][W][modbus:155]: Modbus CRC Check failed! 4C9D!=C93F 5F.4C.7F.C3.26.9C.FB.3F.80.00.00.3F.7E.83.53.3F.65.E5.9F.3C.E5.33.33.40.C5.BA.53.C1.D0.CE.C3.43.65.4D.87.00.00.00.00.40.FA.47.A4.41.BB.B5.BB.00.00.00.00.45.A2.D8.7A.00.00.00.00.45.A4.6D.DF.00.00.00.00.42.62.BE.0F.3F.7F.FB.E6.00.00.00.00.40.89.50.17.00.00.00.00.42.48.0F.06.46.D4.ED.C1.3A.83.12.6F.44.CA.49.71.45.45.FA.C5.16.CF.00.00.01.04.A0.43.62.E7.47.43.67.7B.09.43.69.E0.C7.40.5B.DB.65.3F.C9 (132) at 48317
[12:31:38][V][modbus:310]: Clearing buffer of 132 bytes - parse failed at 48342
[12:31:38][V][modbus:067]: Modbus received first Byte  73 (0X49) at 48350
[12:31:38][W][modbus:155]: Modbus CRC Check failed! 6687!=4CC6 49.8A.3F.C6.4C (5) at 48353
[12:31:38][V][modbus:310]: Clearing buffer of 5 bytes - parse failed at 48356
[12:31:38][V][modbus:067]: Modbus received first Byte  147 (0X93) at 48360
[12:31:38][D][uart_debug:114]: <<< 00:00:00:00:43:5F:4C:7F:C3:26:9C:FB:3F:80:00:00:3F:7E:83:53:3F:65:E5:9F:3C:E5:33:33:40:C5:BA:53:C1:D0:CE:C3:43:65:4D:87:00:00:00:00:40:FA:47:A4:41:BB:B5:BB:00:00:00:00:45:A2:D8:7A:00:00:00:00:45:A4:6D:DF:00:00:00:00:42:62:BE:0F:3F:7F:FB:E6:00:00:00:00:40:89:50:17:00:00:00:00:42:48:0F:06:46:D4:ED:C1:3A:83:12:6F:44:CA:49:71:45:45:FA:C5:16:CF:00:00:01:04:A0:43:62:E7:47:43:67:7B:09:43:69:E0:C7:40:5B:DB:65:3F:C9:49:8A:3F:C6:4C:93:44:3B:66:1B:43:8E:C5
[12:31:38][W][component:237]: Component modbus took a long time for an operation (103 ms).
[12:31:38][W][component:238]: Components should block for at most 30 ms.
[12:31:39][V][modbus:310]: Clearing buffer of 98 bytes - timeout at 48425
[12:31:39][D][uart_debug:114]: <<< 11:43:A4:10:35:44:3B:66:29:43:B6:02:17:43:B5:29:D0:00:00:00:00:43:61:C6:CA:C3:19:AA:B9:3F:80:00:00:3F:48:CF:4A:3F:67:D5:EB:3E:FB:D0:48:42:19:5C:21:C1:CA:83:84:43:66:C1:08:00:00:00:00:40:11:7F:8D:40:DA:3F:54:00:00:00:00:44:A9:63:14:00:00:00:00:44:B7:75:E5:00:00:00:00:42
[12:31:48][V][modbus:221]: Modbus write: 01.04.00.00.00.50.F0.36 (8) at 58073
[12:31:48][D][uart_debug:114]: >>> 01:04:00:00:00:50:F0:36
[12:31:48][V][modbus:067]: Modbus received first Byte  147 (0X93) at 48418
[12:31:48][W][modbus:155]: Modbus CRC Check failed! 8CB0!=7F3F 93.BC.83.3F.7F (5) at 58277
[12:31:48][V][modbus:310]: Clearing buffer of 5 bytes - parse failed at 58280
[12:31:48][V][modbus:067]: Modbus received first Byte  140 (0X8c) at 58283
[12:31:48][W][modbus:155]: Modbus CRC Check failed! EB90!=00 8C.7C.00.00.00 (5) at 58286
[12:31:48][V][modbus:310]: Clearing buffer of 5 bytes - parse failed at 58288
[12:31:48][V][modbus:067]: Modbus received first Byte  0 (0X0) at 58290
[12:31:48][V][modbus:036]: Stop waiting for response from 1
[12:31:48][D][uart_debug:114]: <<< 93:BC:83:3F:7F:8C:7C:00:00:00:00:41:79:F4:BD:00:00:00:00:42:48:16:22:46:D4:ED:C4:3A:83:12:6F:44:CA:49:71:45:45:FA:C5:A1:C8:00:00:01:04:A0:43:63:55:77:43:66:CF:E7:43:69:A0:B5:40:5A:BA:C6:3F:C7:F6:9B:3F:CC:83:B6:44:3A:8C:3C:43:8D:D1:D5:43:A9:C1:F2:44:3A:8E:67:43:B4:49:F4:43:BA:A4:43:40:E2:4F:DD:43:5E:A1:D3:C3:1B:25:04:3F:7F:FD:1A:3F:49:61:57:3F:68:D8:42:3F:09
[12:31:49][V][modbus:310]: Clearing buffer of 110 bytes - timeout at 58456
[12:31:50][I][safe_mode:041]: Boot seems successful; resetting boot loop counter
[12:31:50][D][esp32.preferences:114]: Saving 1 preferences to flash...
[12:31:50][V][esp32.preferences:126]: sync: key: 233825507, len: 4
[12:31:50][D][esp32.preferences:142]: Saving 1 preferences to flash: 0 cached, 1 written, 0 failed
[12:31:58][V][modbus:221]: Modbus write: 01.04.00.00.00.50.F0.36 (8) at 68073
[12:31:58][D][uart_debug:114]: >>> 01:04:00:00:00:50:F0:36
[12:31:58][V][modbus:067]: Modbus received first Byte  246 (0Xf6) at 58305
[12:31:58][W][modbus:155]: Modbus CRC Check failed! D937!=46CD F6.27.42.18.85.2C.C1.C4.78.00.43.66.97.5C.00.00.00.00.40.13.10.42.40.DC.98.63.00.00.00.00.44.AB.2B.0F.00.00.00.00.44.B9.02.C2.00.00.00.00.42.95.1E.9E.3F.7F.9E.37.00.00.00.00.41.77.71.97.00.00.00.00.42.48.16.CD.46 (71) at 68229
[12:31:58][V][modbus:310]: Clearing buffer of 71 bytes - parse failed at 68232
[12:31:58][V][modbus:067]: Modbus received first Byte  212 (0Xd4) at 68234
[12:31:58][W][modbus:155]: Modbus CRC Check failed! FAFC!=833A D4.ED.C6.3A.83 (5) at 68237
[12:31:58][V][modbus:310]: Clearing buffer of 5 bytes - parse failed at 68252
[12:31:58][V][modbus:067]: Modbus received first Byte  18 (0X12) at 68262
[12:31:58][V][modbus:310]: Clearing buffer of 44 bytes - timeout at 68286
[12:31:58][V][modbus:036]: Stop waiting for response from 1
[12:31:58][V][modbus:067]: Modbus received first Byte  183 (0Xb7) at 68270
[12:31:58][D][uart_debug:114]: <<< F6:27:42:18:85:2C:C1:C4:78:00:43:66:97:5C:00:00:00:00:40:13:10:42:40:DC:98:63:00:00:00:00:44:AB:2B:0F:00:00:00:00:44:B9:02:C2:00:00:00:00:42:95:1E:9E:3F:7F:9E:37:00:00:00:00:41:77:71:97:00:00:00:00:42:48:16:CD:46:D4:ED:C6:3A:83:12:6F:44:CA:49:79:45:45:FA:C9:FA:F6:00:00:01:04:A0:43:63:50:1A:43:63:0B:95:43:6A:1E:50:40:5C:54:F9:41:10:8A:7B:3F:CF:8E:5B:44:3B:A9:B7:44:FE:96:92:43:A9:F4:81:44:3B:AB:FF:45:00:02:06:43:BB:8E:6E:40:E7:BA:B6:43:57:FE:33:C3
[12:31:59][D][uart_debug:114]: <<< 1E:A7:0A:3F:7F:FC:FF:3F:7E:92:B9:3F:67:FA:C7:3F:0C:73:02:40:C1:AF:0A:C1:C8:29:EF:43:65:7E:00:00:00:00:00:40:9A:22:8B:41:67:33:D1:00:00:00:00:45:43:74:47:00:00:00:00:45:46:5E:D4:00:00:00:00:42:81:29:FD:3F:7F:F2:05:00:00:00:00:40:DE:FD:BD:00:00:00:00:42:48:17:A9:46:D4:ED
[12:31:59][V][modbus:310]: Clearing buffer of 120 bytes - timeout at 68513
[12:32:08][V][modbus:221]: Modbus write: 01.04.00.00.00.50.F0.36 (8) at 78072
[12:32:08][D][uart_debug:114]: >>> 01:04:00:00:00:50:F0:36
[12:32:08][V][modbus:036]: Stop waiting for response from 1
[12:32:08][V][modbus:067]: Modbus received first Byte  201 (0Xc9) at 68366
[12:32:08][D][uart_debug:114]: <<< C9:3A:83:12:6F:44:CA:49:81:45:45:FA:C9:4D:74:00:00:01:04:A0:43:62:A3:38:43:66:58:7E:43:68:D9:FC:40:5E:FA:76:3F:C7:32:80:3F:C4:38:68:44:3D:1E:CD:43:8D:37:A0:43:A1:99:C7:44:3D:21:4A:43:B3:3C:3A:43:B2:7A:32:40:F5:60:B5:43:5C:C0:BB:C3:17:84:6B:3F:7F:FC:B1:3F:49:B2:4C:3F:67:CC:27:3F:13:66:81:42:18:0F:A0:C1:C8:EE:FD:43:65:F1:E7:00:00:00:00:40:11:A8:59:40:DA:7C:86
[12:32:09][V][modbus:310]: Clearing buffer of 120 bytes - timeout at 78451
[12:32:18][V][modbus:221]: Modbus write: 01.04.00.00.00.50.F0.36 (8) at 88073
[12:32:18][D][uart_debug:114]: >>> 01:04:00:00:00:50:F0:36
[12:32:18][V][modbus:067]: Modbus received first Byte  0 (0X0) at 78301
[12:32:18][W][modbus:155]: Modbus CRC Check failed! C071!=4400 00.00.00.00.44 (5) at 88259
[12:32:18][V][modbus:310]: Clearing buffer of 5 bytes - parse failed at 88262
[12:32:18][V][modbus:067]: Modbus received first Byte  168 (0Xa8) at 88264
[12:32:18][W][modbus:155]: Modbus CRC Check failed! C2AE!=00 A8.D5.B8.00.00 (5) at 88268
[12:32:18][V][modbus:310]: Clearing buffer of 5 bytes - parse failed at 88270
[12:32:18][V][modbus:067]: Modbus received first Byte  0 (0X0) at 88272
[12:32:18][W][modbus:155]: Modbus CRC Check failed! 74D5!=208 00.00.44.B6.90.0F.00.00.00.00.42.99.D5.63.3F.7F.95.78.00.00.00.00.41.7A.C7.BA.00.00.00.00.42.48.14.F0.46.D4.ED.CC.3A.83.12.6F.44.CA.49.81.45.45.FA.C9.51.5D.00.00.01.04.A0.43.5F.8E.6D.43.68.22.B5.43.6A.69.22.41.4B.08.02 (73) at 88284
[12:32:18][V][modbus:310]: Clearing buffer of 73 bytes - parse failed at 88301
[12:32:18][V][modbus:067]: Modbus received first Byte  63 (0X3f) at 88311
[12:32:18][W][modbus:155]: Modbus CRC Check failed! D056!=3F8E 3F.CB.6F.8E.3F (5) at 88314
[12:32:18][V][modbus:310]: Clearing buffer of 5 bytes - parse failed at 88321
[12:32:18][V][modbus:067]: Modbus received first Byte  196 (0Xc4) at 88332
[12:32:18][W][modbus:155]: Modbus CRC Check failed! 407C!=3045 C4.EE.2C.45.30 (5) at 88342
[12:32:18][V][modbus:310]: Clearing buffer of 5 bytes - parse failed at 88345
[12:32:18][V][modbus:067]: Modbus received first Byte  100 (0X64) at 88352
[12:32:18][W][modbus:155]: Modbus CRC Check failed! 8E07!=C293 64.B6.43.93.C2 (5) at 88363
[12:32:18][V][modbus:310]: Clearing buffer of 5 bytes - parse failed at 88372
[12:32:18][V][modbus:067]: Modbus received first Byte  229 (0Xe5) at 88374
[12:32:18][V][modbus:036]: Stop waiting for response from 1
[12:32:18][W][component:237]: Component modbus took a long time for an operation (140 ms).
[12:32:18][W][component:238]: Components should block for at most 30 ms.
[12:32:18][V][modbus:310]: Clearing buffer of 22 bytes - timeout at 88404
[12:32:19][D][uart_debug:114]: <<< 00:00:00:00:44:A8:D5:B8:00:00:00:00:44:B6:90:0F:00:00:00:00:42:99:D5:63:3F:7F:95:78:00:00:00:00:41:7A:C7:BA:00:00:00:00:42:48:14:F0:46:D4:ED:CC:3A:83:12:6F:44:CA:49:81:45:45:FA:C9:51:5D:00:00:01:04:A0:43:5F:8E:6D:43:68:22:B5:43:6A:69:22:41:4B:08:02:3F:CB:6F:8E:3F:C4:EE:2C:45:30:64:B6:43:93:C2:E5:43:A1:71:F7:45:30:64:E9:43:B8:78:AD:43:B4:52:93:41:02:44:DE:43
[12:32:21][V][sensor:043]: 'Uptime': Received new state 90.594002
[12:32:21][D][sensor:093]: 'Uptime': Sending state 0.00000 h with 0 decimals of accuracy
[12:32:28][V][modbus:221]: Modbus write: 01.04.00.00.00.50.F0.36 (8) at 98073
[12:32:28][D][uart_debug:114]: >>> 01:04:00:00:00:50:F0:36
[12:32:28][V][modbus:067]: Modbus received first Byte  92 (0X5c) at 88384
[12:32:28][W][modbus:155]: Modbus CRC Check failed! 9BA9!=20C3 5C.DF.A3.C3.20 (5) at 98209
[12:32:28][V][modbus:310]: Clearing buffer of 5 bytes - parse failed at 98212
[12:32:28][V][modbus:067]: Modbus received first Byte  165 (0Xa5) at 98214
[12:32:28][W][modbus:155]: Modbus CRC Check failed! 4660!=7F3F A5.07.3F.7F.FF.BB.3F.4D.0E.13.3F.65.33.D3.3E.28.47.E8.42.13.1C.0C.C1.D3.9D.F4.43.66.08.C1.00.00.00.00.40.AA.F3.79.41.80.36.9B.00.00.00.00.45.57.0B.52.00.00.00.00.45.5D.FE.51.00.00.00.00.42.88.BD.D4.3F.7F (68) at 98221
[12:32:28][V][modbus:310]: Clearing buffer of 68 bytes - parse failed at 98232
[12:32:28][V][modbus:067]: Modbus received first Byte  243 (0Xf3) at 98235
[12:32:28][W][modbus:155]: Modbus CRC Check failed! 6380!=00 F3.01.00.00.00 (5) at 98243
[12:32:28][V][modbus:310]: Clearing buffer of 5 bytes - parse failed at 98253
[12:32:28][V][modbus:067]: Modbus received first Byte  0 (0X0) at 98263
[12:32:28][V][modbus:036]: Stop waiting for response from 1
[12:32:28][W][component:237]: Component modbus took a long time for an operation (74 ms).
[12:32:28][W][component:238]: Components should block for at most 30 ms.
[12:32:28][V][modbus:310]: Clearing buffer of 42 bytes - timeout at 98295
[12:32:28][V][modbus:067]: Modbus received first Byte  17 (0X11) at 98276
[12:32:28][D][uart_debug:114]: <<< 5C:DF:A3:C3:20:A5:07:3F:7F:FF:BB:3F:4D:0E:13:3F:65:33:D3:3E:28:47:E8:42:13:1C:0C:C1:D3:9D:F4:43:66:08:C1:00:00:00:00:40:AA:F3:79:41:80:36:9B:00:00:00:00:45:57:0B:52:00:00:00:00:45:5D:FE:51:00:00:00:00:42:88:BD:D4:3F:7F:F3:01:00:00:00:00:40:CF:A3:A3:00:00:00:00:42:48:33:38:46:D4:ED:CF:3A:83:12:6F:44:CA:49:89:45:45:FA:CD:58:7D:00:00:01:04:A0:43:63:B6:5E:43:66:11:37:43:69:A2:81:40:5B:90:DF:3F:C6:9D:72:3F:CA:F5:05:44:3B:2F:58:43:8C:C3:62:43:A8:91:3A
[12:32:28][W][modbus:155]: Modbus CRC Check failed! 8407!=1742 11.37.43.69.A2.81.40.5B.90.DF.3F.C6.9D.72.3F.CA.F5.05.44.3B.2F.58.43.8C.C3.62.43.A8.91.3A.44.3B.32.83.43.B2.7E.D0.43.B9.39.D5.41.08.5B.BA.43.5B.82.E9.C3.19.8A.78.3F.80.00.00.3F.49.E6.91.3F.68.C0.80.3E.FB.D0.48.42.17 (72) at 98368
[12:32:28][V][modbus:310]: Clearing buffer of 72 bytes - parse failed at 98376
[12:32:28][V][modbus:067]: Modbus received first Byte  195 (0Xc3) at 98378
[12:32:28][W][modbus:155]: Modbus CRC Check failed! C2D!=DEC4 C3.92.C1.C4.DE (5) at 98386
[12:32:28][V][modbus:310]: Clearing buffer of 5 bytes - parse failed at 98396
[12:32:28][V][modbus:067]: Modbus received first Byte  67 (0X43) at 98406
[12:32:28][W][component:237]: Component modbus took a long time for an operation (87 ms).
[12:32:29][W][component:238]: Components should block for at most 30 ms.
[12:32:29][V][modbus:310]: Clearing buffer of 43 bytes - timeout at 98428
[12:32:29][D][uart_debug:114]: <<< 44:3B:32:83:43:B2:7E:D0:43:B9:39:D5:41:08:5B:BA:43:5B:82:E9:C3:19:8A:78:3F:80:00:00:3F:49:E6:91:3F:68:C0:80:3E:FB:D0:48:42:17:C3:92:C1:C4:DE:43:43:66:78:B3:00:00:00:00:40:11:EE:CE:40:DA:E6:35:00:00:00:00:44:AA:97:52:00:00:00:00:44:B8:33:F0:00:00:00:00:42:85:13:27:3F:7F
[12:32:34][V][sensor:043]: 'WiFi Signal': Received new state -71.000000
[12:32:34][D][sensor:093]: 'WiFi Signal': Sending state -71.00000 dBm with 0 decimals of accuracy
[12:32:36][D][dallas.temp.sensor:054]: 'Temp': Got Temperature=26.6°C
[12:32:36][V][sensor:043]: 'Temp': Received new state 26.625000
[12:32:36][D][sensor:093]: 'Temp': Sending state 26.62500 °C with 1 decimals of accuracy
[12:32:38][V][modbus:221]: Modbus write: 01.04.00.00.00.50.F0.36 (8) at 108073
[12:32:38][D][uart_debug:114]: >>> 01:04:00:00:00:50:F0:36
[12:32:38][V][modbus:067]: Modbus received first Byte  162 (0Xa2) at 98412
[12:32:38][W][modbus:155]: Modbus CRC Check failed! 12DD!=00 A2.13.00.00.00 (5) at 108279
[12:32:38][V][modbus:310]: Clearing buffer of 5 bytes - parse failed at 108282
[12:32:38][V][modbus:067]: Modbus received first Byte  0 (0X0) at 108284
[12:32:38][V][modbus:036]: Stop waiting for response from 1
[12:32:38][D][uart_debug:114]: <<< A2:13:00:00:00:00:41:75:37:3C:00:00:00:00:42:48:2B:E3:46:D4:ED:D2:3A:83:12:6F:44:CA:49:89:45:45:FA:CD:1D:B0:00:00:01:04:A0:43:64:20:40:43:63:DB:42:43:6B:67:4E:40:5B:23:22:41:0F:D2:AD:3F:CF:2F:8C:44:3C:3A:EF:44:FE:6B:10:43:AC:B3:81:44:3C:3F:42:44:FF:DF:71:43:BE:84:40:41:20:10:88:43:59:F4:CC:C3:20:E2:2C:3F:7F:FA:41:3F:7E:8B:71:3F:68:0F:42:3F:42:40:E0:40:C3:9B
[12:32:39][V][modbus:310]: Clearing buffer of 115 bytes - timeout at 108446
[12:32:48][V][modbus:221]: Modbus write: 01.04.00.00.00.50.F0.36 (8) at 118073
[12:32:48][D][uart_debug:114]: >>> 01:04:00:00:00:50:F0:36
[12:32:48][V][modbus:067]: Modbus received first Byte  61 (0X3d) at 108296
[12:32:48][W][modbus:155]: Modbus CRC Check failed! EF0!=25D3 3D.C1.C7.D3.25 (5) at 118259
[12:32:48][V][modbus:310]: Clearing buffer of 5 bytes - parse failed at 118262
[12:32:48][V][modbus:067]: Modbus received first Byte  67 (0X43) at 118265
[12:32:48][V][modbus:036]: Stop waiting for response from 1
[12:32:48][D][uart_debug:114]: <<< 3D:C1:C7:D3:25:43:66:76:45:00:00:00:00:40:98:75:97:41:64:B0:63:00:00:00:00:45:43:5C:67:00:00:00:00:45:46:53:66:00:00:00:00:42:88:40:2E:3F:7F:F0:83:00:00:00:00:40:E2:38:5D:00:00:00:00:42:48:14:F3:46:D4:ED:D6:3A:83:12:6F:44:CA:49:91:45:45:FA:D1:E7:A1:00:00:01:04:A0:43:63:6B:BC:43:66:BF:2A:43:6A:43:E6:40:5C:A8:1A:3F:C7:3A:45:3F:CA:CE:E1:44:3B:93:A0:43:8D:81:89:43:A8:CA:AD:44:3B:96:4C:43:B3:93:1D:43:B9:96:E3:40:F9:28:47:43:5D:1D:CA:C3:1A:4F:02:3F:7F
[12:32:49][D][uart_debug:114]: <<< FC:7C:3F:49:BB:62:3F:68:D5:68:3F:17:F1:3A:42:18:02:6A:C1:C4:84:4A:43:66:CF:99:00:00:00:00:40:10:7C:37:40:D8:BA:52:00:00:00:00:44:AB:5C:DE:00:00:00:00:44:B9:15:A6:00:00:00:00:42:95:30:16:3F:7F:93:86:00:00:00:00:41:7C:0F:70:00:00:00:00:42:48:18:20:46:D4:ED:D8:3A:83:12:6F
[12:32:49][V][modbus:310]: Clearing buffer of 235 bytes - timeout at 118573
[12:32:58][V][modbus:221]: Modbus write: 01.04.00.00.00.50.F0.36 (8) at 128073
[12:32:58][D][uart_debug:114]: >>> 01:04:00:00:00:50:F0:36
[12:32:58][V][modbus:036]: Stop waiting for response from 1
[12:32:58][V][modbus:067]: Modbus received first Byte  68 (0X44) at 118425
[12:32:58][W][modbus:155]: Modbus CRC Check failed! 83A6!=459A 44.CA.49.9A.45 (5) at 128311
[12:32:58][V][modbus:310]: Clearing buffer of 5 bytes - parse failed at 128313
[12:32:58][V][modbus:067]: Modbus received first Byte  69 (0X45) at 128316
[12:32:58][W][modbus:155]: Modbus CRC Check failed! E9E2!=127B 45.FA.D1.7B.12 (5) at 128319
[12:32:58][V][modbus:310]: Clearing buffer of 5 bytes - parse failed at 128321
[12:32:58][V][modbus:067]: Modbus received first Byte  0 (0X0) at 128323
[12:32:58][W][modbus:155]: Modbus CRC Check failed! 7700!=43A0 00.00.01.04.A0.43 (6) at 128335
[12:32:58][V][modbus:310]: Clearing buffer of 6 bytes - parse failed at 128344
[12:32:58][V][modbus:067]: Modbus received first Byte  99 (0X63) at 128347
[12:32:58][W][modbus:155]: Modbus CRC Check failed! D974!=6743 63.B2.8A.43.67 (5) at 128355
[12:32:58][V][modbus:310]: Clearing buffer of 5 bytes - parse failed at 128364
[12:32:58][V][modbus:067]: Modbus received first Byte  115 (0X73) at 128367
[12:32:58][W][modbus:155]: Modbus CRC Check failed! 1A8F!=CF69 73.EB.43.69.CF (5) at 128375
[12:32:58][V][modbus:310]: Clearing buffer of 5 bytes - parse failed at 128385
[12:32:58][V][modbus:067]: Modbus received first Byte  149 (0X95) at 128395
[12:32:58][W][component:237]: Component modbus took a long time for an operation (98 ms).
[12:32:58][W][component:238]: Components should block for at most 30 ms.
[12:32:58][V][modbus:310]: Clearing buffer of 94 bytes - timeout at 128416
[12:32:59][D][uart_debug:114]: <<< 44:CA:49:9A:45:45:FA:D1:7B:12:00:00:01:04:A0:43:63:B2:8A:43:67:73:EB:43:69:CF:95:40:5E:E8:EF:3F:C8:56:68:3F:CD:D8:2C:44:3F:FB:5D:43:8E:75:1C:43:AB:69:C2:44:3F:FB:5E:43:B5:20:B0:43:BC:00:A9:00:00:00:00:43:5F:B9:59:C3:1A:6F:42:3F:80:00:00:3F:49:58:49:3F:69:D1:F8:BE:90:52:2B:42:18:7F:55:C1:C0:39:10:43:66:FC:AF:00:00:00:00:40:13:B0:A3:40:DD:88:F4:00:00:00:00:44
```

**Comment by exciton** [comment]
Ok, the one hardware thing I notice, both in the 2.0.6 log and the 9600 Arduino and 9600 esp-idf log is and extra 0x00 byte at the start and end of the response that shouldn't be there.

Response should start with 0x01 0x04 , but there's an extra 0x01 in front. 

In the 2.0.6 code this extra byte gets timed out and discarded, but in the others it doesn't and is included in the response, messing it up.

I suspect this is due to low level buffering in the uart code. I think in 2.0.6 it's giving us the first byte with a gap (so modbus code can separate them properly) and in the failing examples it's mashing then together so modbus code doesn't see the gap. 

The high speed code you shared earlier is even more messed up. There I think the buffer is getting overrun or something.

So - one hardware issue - the weird 0x00 byte. Could be an echo from not having a termination resistor? 

And one software issue - suspected uart buffer timing. I tested myself adding setRxFIFOFull to 1 in the esphome uart code (right after the call to begin()) and this could solve the timing issue. Will make a patch later to demonstrate this.

**Comment by karllinder** [comment]
You where correct, a 120ohm resistor was missing, did add that now, but still the same issue with the extra 0x00

this log with standard Arduino.

I am starting to think there is a hardware error on the 485 interface, using the HW-97. 
I will try to rebuild a new one and see if it get any better, will take some days.

```
INFO Upload took 8.84 seconds, waiting for result...
INFO OTA successful
INFO Successfully uploaded program.
INFO Starting log output from 192.168.1.12 using esphome API
INFO Successfully connected to utilhouse @ 192.168.1.12 in 7.261s
INFO Successful handshake with utilhouse @ 192.168.1.12 in 0.363s
[16:21:36][I][app:100]: ESPHome version 2024.12.2 compiled on Jan  6 2025, 16:19:26
[16:21:36][C][status_led:019]: Status LED:
[16:21:36][C][status_led:020]:   Pin: GPIO25
[16:21:36][C][wifi:600]: WiFi:
[16:21:36][C][wifi:428]:   Local MAC: 7C:9E:BD:F3:1A:34
[16:21:36][C][wifi:433]:   SSID: [redacted]
[16:21:36][C][wifi:436]:   IP Address: 192.168.1.12
[16:21:36][C][wifi:440]:   BSSID: [redacted]
[16:21:36][C][wifi:441]:   Hostname: 'utilhouse'
[16:21:36][C][wifi:443]:   Signal strength: -65 dB ▂▄▆█
[16:21:36][V][wifi:445]:   Priority: 0.0
[16:21:36][C][wifi:447]:   Channel: 6
[16:21:36][C][wifi:448]:   Subnet: 255.255.255.0
[16:21:36][C][wifi:449]:   Gateway: 192.168.1.1
[16:21:36][C][wifi:450]:   DNS1: 8.8.8.8
[16:21:36][C][wifi:451]:   DNS2: 1.1.1.1
[16:21:36][C][logger:185]: Logger:
[16:21:36][C][logger:186]:   Level: VERBOSE
[16:21:36][C][logger:188]:   Log Baud Rate: 115200
[16:21:36][C][logger:189]:   Hardware UART: UART0
[16:21:36][C][gpio.one_wire:020]: GPIO 1-wire bus:
[16:21:36][C][gpio.one_wire:021]:   Pin: GPIO32
[16:21:36][C][gpio.one_wire:080]:   Found devices:
[16:21:36][C][gpio.one_wire:082]:     0xa73c01f09514a628 (DS18B20)
[16:21:36][C][uart.arduino_esp32:151]: UART Bus 1:
[16:21:36][C][uart.arduino_esp32:152]:   TX Pin: GPIO17
[16:21:36][C][uart.arduino_esp32:153]:   RX Pin: GPIO16
[16:21:36][C][uart.arduino_esp32:155]:   RX Buffer Size: 256
[16:21:36][C][uart.arduino_esp32:157]:   Baud Rate: 9600 baud
[16:21:36][C][uart.arduino_esp32:158]:   Data Bits: 8
[16:21:36][C][uart.arduino_esp32:159]:   Parity: NONE
[16:21:36][C][uart.arduino_esp32:160]:   Stop bits: 1
[16:21:36][C][modbus:230]: Modbus:
[16:21:36][C][modbus:231]:   Flow Control Pin: GPIO5
[16:21:36][C][modbus:232]:   Send Wait Time: 200 ms
[16:21:36][C][modbus:233]:   Turnaround Time: 200 ms
[16:21:36][C][modbus:234]:   Frame Delay: 5 ms
[16:21:36][C][modbus:235]:   Long Rx Buffer Delay: 138 ms
[16:21:36][C][modbus:236]:   CRC Disabled: NO
[16:21:36][C][uptime.sensor:033]: Uptime Sensor 'Uptime'
[16:21:36][C][uptime.sensor:033]:   Device Class: 'duration'
[16:21:36][C][uptime.sensor:033]:   State Class: 'total_increasing'
[16:21:36][C][uptime.sensor:033]:   Unit of Measurement: 'h'
[16:21:36][C][uptime.sensor:033]:   Accuracy Decimals: 0
[16:21:36][C][uptime.sensor:033]:   Icon: 'mdi:timer-outline'
[16:21:36][V][uptime.sensor:033]:   Unique ID: '7c9ebdf31a34-uptime'
[16:21:36][C][uptime.sensor:034]:   Type: Seconds
[16:21:36][C][dallas.temp.sensor:029]: Dallas Temperature Sensor:
[16:21:36][C][dallas.temp.sensor:034]:   Address: 0xa73c01f09514a628 (DS18B20)
[16:21:36][C][dallas.temp.sensor:035]:   Resolution: 12 bits
[16:21:36][C][dallas.temp.sensor:036]:   Update Interval: 60.0s
[16:21:36][C][sdm_meter:087]: SDM Meter:
[16:21:36][C][sdm_meter:088]:   Address: 0x01
[16:21:36][C][sdm_meter:093]:   Phase A
[16:21:36][C][sdm_meter:094]:     Voltage 'SDM630 Phase A Voltage'
[16:21:36][C][sdm_meter:094]:       Device Class: 'voltage'
[16:21:36][C][sdm_meter:094]:       State Class: 'measurement'
[16:21:36][C][sdm_meter:094]:       Unit of Measurement: 'V'
[16:21:36][C][sdm_meter:094]:       Accuracy Decimals: 2
[16:21:36][C][sdm_meter:095]:     Current 'SDM630 Phase A Current'
[16:21:36][C][sdm_meter:095]:       Device Class: 'current'
[16:21:36][C][sdm_meter:095]:       State Class: 'measurement'
[16:21:36][C][sdm_meter:095]:       Unit of Measurement: 'A'
[16:21:36][C][sdm_meter:095]:       Accuracy Decimals: 3
[16:21:36][C][sdm_meter:096]:     Active Power 'SDM630 Phase A Power'
[16:21:36][C][sdm_meter:096]:       Device Class: 'power'
[16:21:36][C][sdm_meter:096]:       State Class: 'measurement'
[16:21:36][C][sdm_meter:096]:       Unit of Measurement: 'W'
[16:21:36][C][sdm_meter:096]:       Accuracy Decimals: 2
[16:21:36][C][sdm_meter:097]:     Apparent Power 'SDM630 Phase A Apparent Power'
[16:21:36][C][sdm_meter:097]:       State Class: 'measurement'
[16:21:36][C][sdm_meter:097]:       Unit of Measurement: 'VA'
[16:21:36][C][sdm_meter:097]:       Accuracy Decimals: 2
[16:21:36][C][sdm_meter:098]:     Reactive Power 'SDM630 Phase A Reactive Power'
[16:21:36][C][sdm_meter:098]:       State Class: 'measurement'
[16:21:36][C][sdm_meter:098]:       Unit of Measurement: 'var'
[16:21:36][C][sdm_meter:098]:       Accuracy Decimals: 2
[16:21:36][C][sdm_meter:099]:     Power Factor 'SDM630 Phase A Power Factor'
[16:21:36][C][sdm_meter:099]:       Device Class: 'power_factor'
[16:21:36][C][sdm_meter:099]:       State Class: 'measurement'
[16:21:36][C][sdm_meter:099]:       Unit of Measurement: ''
[16:21:36][C][sdm_meter:099]:       Accuracy Decimals: 3
[16:21:36][C][sdm_meter:100]:     Phase Angle 'SDM630 Phase A Phase Angle'
[16:21:36][C][sdm_meter:100]:       State Class: ''
[16:21:36][C][sdm_meter:100]:       Unit of Measurement: '°'
[16:21:36][C][sdm_meter:100]:       Accuracy Decimals: 3
[16:21:36][C][sdm_meter:100]:       Icon: 'mdi:flash'
[16:21:36][C][sdm_meter:093]:   Phase B
[16:21:36][C][sdm_meter:094]:     Voltage 'SDM630 Phase B Voltage'
[16:21:36][C][sdm_meter:094]:       Device Class: 'voltage'
[16:21:36][C][sdm_meter:094]:       State Class: 'measurement'
[16:21:36][C][sdm_meter:094]:       Unit of Measurement: 'V'
[16:21:36][C][sdm_meter:094]:       Accuracy Decimals: 2
[16:21:36][C][sdm_meter:095]:     Current 'SDM630 Phase B Current'
[16:21:36][C][sdm_meter:095]:       Device Class: 'current'
[16:21:36][C][sdm_meter:095]:       State Class: 'measurement'
[16:21:36][C][sdm_meter:095]:       Unit of Measurement: 'A'
[16:21:36][C][sdm_meter:095]:       Accuracy Decimals: 3
[16:21:36][C][sdm_meter:096]:     Active Power 'SDM630 Phase B Power'
[16:21:36][C][sdm_meter:096]:       Device Class: 'power'
[16:21:36][C][sdm_meter:096]:       State Class: 'measurement'
[16:21:36][C][sdm_meter:096]:       Unit of Measurement: 'W'
[16:21:36][C][sdm_meter:096]:       Accuracy Decimals: 2
[16:21:37][C][sdm_meter:097]:     Apparent Power 'SDM630 Phase B Apparent Power'
[16:21:37][C][sdm_meter:097]:       State Class: 'measurement'
[16:21:37][C][sdm_meter:097]:       Unit of Measurement: 'VA'
[16:21:37][C][sdm_meter:097]:       Accuracy Decimals: 2
[16:21:37][C][sdm_meter:098]:     Reactive Power 'SDM630 Phase B Reactive Power'
[16:21:37][C][sdm_meter:098]:       State Class: 'measurement'
[16:21:37][C][sdm_meter:098]:       Unit of Measurement: 'var'
[16:21:37][C][sdm_meter:098]:       Accuracy Decimals: 2
[16:21:37][C][sdm_meter:099]:     Power Factor 'SDM630 Phase B Power Factor'
[16:21:37][C][sdm_meter:099]:       Device Class: 'power_factor'
[16:21:37][C][sdm_meter:099]:       State Class: 'measurement'
[16:21:37][C][sdm_meter:099]:       Unit of Measurement: ''
[16:21:37][C][sdm_meter:099]:       Accuracy Decimals: 3
[16:21:37][C][sdm_meter:100]:     Phase Angle 'SDM630 Phase B Phase Angle'
[16:21:37][C][sdm_meter:100]:       State Class: ''
[16:21:37][C][sdm_meter:100]:       Unit of Measurement: '°'
[16:21:37][C][sdm_meter:100]:       Accuracy Decimals: 3
[16:21:37][C][sdm_meter:100]:       Icon: 'mdi:flash'
[16:21:37][C][sdm_meter:093]:   Phase C
[16:21:37][C][sdm_meter:094]:     Voltage 'SDM630 Phase C Voltage'
[16:21:37][C][sdm_meter:094]:       Device Class: 'voltage'
[16:21:37][C][sdm_meter:094]:       State Class: 'measurement'
[16:21:37][C][sdm_meter:094]:       Unit of Measurement: 'V'
[16:21:37][C][sdm_meter:094]:       Accuracy Decimals: 2
[16:21:37][C][sdm_meter:095]:     Current 'SDM630 Phase C Current'
[16:21:37][C][sdm_meter:095]:       Device Class: 'current'
[16:21:37][C][sdm_meter:095]:       State Class: 'measurement'
[16:21:37][C][sdm_meter:095]:       Unit of Measurement: 'A'
[16:21:37][C][sdm_meter:095]:       Accuracy Decimals: 3
[16:21:37][C][sdm_meter:096]:     Active Power 'SDM630 Phase C Power'
[16:21:37][C][sdm_meter:096]:       Device Class: 'power'
[16:21:37][C][sdm_meter:096]:       State Class: 'measurement'
[16:21:37][C][sdm_meter:096]:       Unit of Measurement: 'W'
[16:21:37][C][sdm_meter:096]:       Accuracy Decimals: 2
[16:21:37][C][sdm_meter:097]:     Apparent Power 'SDM630 Phase C Apparent Power'
[16:21:37][C][sdm_meter:097]:       State Class: 'measurement'
[16:21:37][C][sdm_meter:097]:       Unit of Measurement: 'VA'
[16:21:37][C][sdm_meter:097]:       Accuracy Decimals: 2
[16:21:37][C][sdm_meter:098]:     Reactive Power 'SDM630 Phase C Reactive Power'
[16:21:37][C][sdm_meter:098]:       State Class: 'measurement'
[16:21:37][C][sdm_meter:098]:       Unit of Measurement: 'var'
[16:21:37][C][sdm_meter:098]:       Accuracy Decimals: 2
[16:21:37][C][sdm_meter:099]:     Power Factor 'SDM630 Phase C Power Factor'
[16:21:37][C][sdm_meter:099]:       Device Class: 'power_factor'
[16:21:37][C][sdm_meter:099]:       State Class: 'measurement'
[16:21:37][C][sdm_meter:099]:       Unit of Measurement: ''
[16:21:37][C][sdm_meter:099]:       Accuracy Decimals: 3
[16:21:37][C][sdm_meter:100]:     Phase Angle 'SDM630 Phase C Phase Angle'
[16:21:37][C][sdm_meter:100]:       State Class: ''
[16:21:37][C][sdm_meter:100]:       Unit of Measurement: '°'
[16:21:37][C][sdm_meter:100]:       Accuracy Decimals: 3
[16:21:37][C][sdm_meter:100]:       Icon: 'mdi:flash'
[16:21:37][C][sdm_meter:102]:   Total Power 'SDM630 Total Power'
[16:21:37][C][sdm_meter:102]:     Device Class: 'power'
[16:21:37][C][sdm_meter:102]:     State Class: 'measurement'
[16:21:37][C][sdm_meter:102]:     Unit of Measurement: 'W'
[16:21:37][C][sdm_meter:102]:     Accuracy Decimals: 2
[16:21:37][C][sdm_meter:103]:   Frequency 'SDM630 Frequency'
[16:21:37][C][sdm_meter:103]:     State Class: 'measurement'
[16:21:37][C][sdm_meter:103]:     Unit of Measurement: 'Hz'
[16:21:37][C][sdm_meter:103]:     Accuracy Decimals: 3
[16:21:37][C][sdm_meter:103]:     Icon: 'mdi:current-ac'
[16:21:37][C][sdm_meter:104]:   Import Active Energy 'SDM630 Import Active Energy'
[16:21:37][C][sdm_meter:104]:     Device Class: 'energy'
[16:21:37][C][sdm_meter:104]:     State Class: 'total_increasing'
[16:21:37][C][sdm_meter:104]:     Unit of Measurement: 'kWh'
[16:21:37][C][sdm_meter:104]:     Accuracy Decimals: 2
[16:21:37][C][sdm_meter:105]:   Export Active Energy 'SDM630 Export Active Energy'
[16:21:37][C][sdm_meter:105]:     Device Class: 'energy'
[16:21:37][C][sdm_meter:105]:     State Class: 'total_increasing'
[16:21:37][C][sdm_meter:105]:     Unit of Measurement: 'kWh'
[16:21:37][C][sdm_meter:105]:     Accuracy Decimals: 2
[16:21:37][C][sdm_meter:106]:   Import Reactive Energy 'SDM630 Import Reactive Energy'
[16:21:37][C][sdm_meter:106]:     State Class: 'total_increasing'
[16:21:37][C][sdm_meter:106]:     Unit of Measurement: 'kVARh'
[16:21:37][C][sdm_meter:106]:     Accuracy Decimals: 2
[16:21:37][C][sdm_meter:107]:   Export Reactive Energy 'SDM630 Export Reactive Energy'
[16:21:37][C][sdm_meter:107]:     State Class: 'total_increasing'
[16:21:37][C][sdm_meter:107]:     Unit of Measurement: 'kVARh'
[16:21:37][C][sdm_meter:107]:     Accuracy Decimals: 2
[16:21:37][C][status:034]: Status Binary Sensor 'Status'
[16:21:37][C][status:034]:   Device Class: 'connectivity'
[16:21:37][C][restart.button:017]: Restart Button 'Reboot'
[16:21:37][C][restart.button:017]:   Icon: 'mdi:restart'
[16:21:37][C][captive_portal:089]: Captive Portal:
[16:21:37][C][sntp:042]: SNTP Time:
[16:21:37][C][sntp:045]:   Server 0: '0.pool.ntp.org'
[16:21:37][C][sntp:045]:   Server 1: '1.pool.ntp.org'
[16:21:37][C][sntp:045]:   Server 2: '2.pool.ntp.org'
[16:21:37][C][mdns:116]: mDNS:
[16:21:37][C][mdns:117]:   Hostname: utilhouse
[16:21:37][V][mdns:118]:   Services:
[16:21:37][V][mdns:120]:   - _esphomelib, _tcp, 6053
[16:21:37][V][mdns:122]:     TXT: friendly_name = Utilitymeter House
[16:21:37][V][mdns:122]:     TXT: version = 2024.12.2
[16:21:37][V][mdns:122]:     TXT: mac = 7c9ebdf31a34
[16:21:37][V][mdns:122]:     TXT: platform = ESP32
[16:21:37][V][mdns:122]:     TXT: board = esp32dev
[16:21:37][V][mdns:122]:     TXT: network = wifi
[16:21:37][V][mdns:122]:     TXT: api_encryption = Noise_NNpsk0_25519_ChaChaPoly_SHA256
[16:21:37][C][esphome.ota:073]: Over-The-Air updates:
[16:21:37][C][esphome.ota:074]:   Address: 192.168.1.12:3232
[16:21:37][C][esphome.ota:075]:   Version: 2
[16:21:37][C][esphome.ota:078]:   Password configured
[16:21:37][C][safe_mode:018]: Safe Mode:
[16:21:37][C][safe_mode:020]:   Boot considered successful after 60 seconds
[16:21:37][C][safe_mode:021]:   Invoke after 10 boot attempts
[16:21:37][C][safe_mode:023]:   Remain in safe mode for 300 seconds
[16:21:37][C][api:140]: API Server:
[16:21:37][C][api:141]:   Address: 192.168.1.12:6053
[16:21:37][C][api:143]:   Using noise encryption: YES
[16:21:37][C][wifi_signal.sensor:010]: WiFi Signal 'WiFi Signal'
[16:21:37][C][wifi_signal.sensor:010]:   Device Class: 'signal_strength'
[16:21:37][C][wifi_signal.sensor:010]:   State Class: 'measurement'
[16:21:37][C][wifi_signal.sensor:010]:   Unit of Measurement: 'dBm'
[16:21:37][C][wifi_signal.sensor:010]:   Accuracy Decimals: 0
[16:21:37][V][wifi_signal.sensor:010]:   Unique ID: '7c9ebdf31a34-wifisignal'
[16:21:44][V][modbus:221]: Modbus write: 01.04.00.00.00.50.F0.36 (8) at 16068
[16:21:44][D][uart_debug:114]: >>> 01:04:00:00:00:50:F0:36
[16:21:44][V][modbus:067]: Modbus received first Byte  0 (0X0) at 6478
[16:21:44][W][modbus:155]: Modbus CRC Check failed! C071!=C200 00.00.00.00.C2 (5) at 16092
[16:21:44][V][modbus:310]: Clearing buffer of 5 bytes - parse failed at 16094
[16:21:44][V][modbus:067]: Modbus received first Byte  60 (0X3c) at 16107
[16:21:44][W][modbus:155]: Modbus CRC Check failed! 2410!=00 3C.74.0C.3F.7F.F9.3E.00.00.00.00.C0.89.77.71.00.00 (17) at 16111
[16:21:44][V][modbus:310]: Clearing buffer of 17 bytes - parse failed at 16124
[16:21:44][V][modbus:067]: Modbus received first Byte  0 (0X0) at 16126
[16:21:44][W][component:237]: Component modbus took a long time for an operation (67 ms).
[16:21:44][W][component:238]: Components should block for at most 30 ms.
[16:21:44][V][modbus:310]: Clearing buffer of 25 bytes - timeout at 16157
[16:21:44][D][uart_debug:114]: <<< 00:00:00:00:C2:3C:74:0C:3F:7F:F9:3E:00:00:00:00:C0:89:77:71:00:00:00:00:42:47:F3:AD:46:D5:09:09:3A:83:12:6F:44:CA:5D:50:45:46:05:5C:C3:A5:00
[16:21:44][V][modbus:036]: Stop waiting for response from 1
[16:21:44][V][modbus:067]: Modbus received first Byte  0 (0X0) at 16141
[16:21:44][W][modbus:155]: Modbus CRC Check failed! 6911!=43C1 00.01.04.A0.43.61.50.C1.43 (9) at 16304
[16:21:44][V][modbus:310]: Clearing buffer of 9 bytes - parse failed at 16306
[16:21:44][V][modbus:067]: Modbus received first Byte  100 (0X64) at 16319
[16:21:44][W][modbus:155]: Modbus CRC Check failed! D05D!=6743 64.91.D4.43.67 (5) at 16322
[16:21:44][V][modbus:310]: Clearing buffer of 5 bytes - parse failed at 16335
[16:21:44][V][modbus:067]: Modbus received first Byte  85 (0X55) at 16337
[16:21:44][W][component:237]: Component modbus took a long time for an operation (60 ms).
[16:21:44][W][component:238]: Components should block for at most 30 ms.
[16:21:44][D][uart_debug:114]: <<< 00:01:04:A0:43:61:50:C1:43:64:91:D4:43:67:55:68:40:57:1E:6D:40:A3:E8:C7:40:BE:FD:CA:44:37:D2:5B:44:91:DD:8F:44:AA:EB:50:44:37:DB:9E:44:92:66:29:44:AB:BA:16:C1:68:A7:3A:42:C7:CF:75:C3:05:16:83:3F:7F:F3:35:3F:7F:10:78:3F:7E:CD:FD:BF:A2:72:9F:40:9C:D1:2A:C0:B1:43:45:43:64:68:00:00:00:00:00:40:99:F0:85:41:66:E8:C7:00:00:00:00:45:4C:5C:11:00:00:00:00:45:4D:0A:3E
[16:21:44][V][modbus:310]: Clearing buffer of 106 bytes - timeout at 16519
[16:21:54][V][modbus:221]: Modbus write: 01.04.00.00.00.50.F0.36 (8) at 26071
[16:21:54][D][uart_debug:114]: >>> 01:04:00:00:00:50:F0:36
[16:21:54][V][modbus:067]: Modbus received first Byte  0 (0X0) at 16359
[16:21:54][W][modbus:155]: Modbus CRC Check failed! C071!=C200 00.00.00.00.C2 (5) at 26095
[16:21:54][V][modbus:310]: Clearing buffer of 5 bytes - parse failed at 26097
[16:21:54][V][modbus:067]: Modbus received first Byte  67 (0X43) at 26110
[16:21:54][W][modbus:155]: Modbus CRC Check failed! A526!=7F3F 43.8A.3D.3F.7F (5) at 26113
[16:21:54][V][modbus:310]: Clearing buffer of 5 bytes - parse failed at 26126
[16:21:54][V][modbus:067]: Modbus received first Byte  248 (0Xf8) at 26128
[16:21:54][W][modbus:155]: Modbus CRC Check failed! 3187!=00 F8.B4.00.00.00 (5) at 26142
[16:21:54][V][modbus:310]: Clearing buffer of 5 bytes - parse failed at 26145
[16:21:54][V][modbus:067]: Modbus received first Byte  0 (0X0) at 26158
[16:21:54][W][modbus:155]: Modbus CRC Check failed! A761!=4187 00.C0.8B.87.41 (5) at 26160
[16:21:54][V][modbus:310]: Clearing buffer of 5 bytes - parse failed at 26174
[16:21:54][V][modbus:067]: Modbus received first Byte  0 (0X0) at 26176
[16:21:54][W][modbus:155]: Modbus CRC Check failed! C071!=4200 00.00.00.00.42 (5) at 26178
[16:21:54][V][modbus:310]: Clearing buffer of 5 bytes - parse failed at 26192
[16:21:54][V][modbus:067]: Modbus received first Byte  71 (0X47) at 26194
[16:21:54][W][modbus:155]: Modbus CRC Check failed! 2381!=D546 47.FD.88.46.D5 (5) at 26208
[16:21:54][V][modbus:310]: Clearing buffer of 5 bytes - parse failed at 26210
[16:21:54][V][modbus:067]: Modbus received first Byte  9 (0X9) at 26223
[16:21:54][W][component:237]: Component modbus took a long time for an operation (151 ms).
[16:21:54][W][component:238]: Components should block for at most 30 ms.
[16:21:54][V][modbus:310]: Clearing buffer of 17 bytes - timeout at 26242
[16:21:54][V][modbus:036]: Stop waiting for response from 1
[16:21:54][V][modbus:067]: Modbus received first Byte  0 (0X0) at 26227
[16:21:54][W][modbus:155]: Modbus CRC Check failed! E51!=43CA 00.01.04.A0.43.61.DB.CA.43 (9) at 26316
[16:21:54][V][modbus:310]: Clearing buffer of 9 bytes - parse failed at 26318
[16:21:54][V][modbus:067]: Modbus received first Byte  101 (0X65) at 26331
[16:21:54][W][modbus:155]: Modbus CRC Check failed! F610!=9DAB 65.54.25.43.67.4C.6A.40.55.C4.8F.40.A4.5C.74.40.C3.25.32.44.38.7C.86.44.92.93.DC.44.AA.CF.4D.44.38.83.CA.44.93.1F.B2.44.AB.9D (42) at 26337
[16:21:54][V][modbus:310]: Clearing buffer of 42 bytes - parse failed at 26350
[16:21:54][V][modbus:067]: Modbus received first Byte  2 (0X2) at 26363
[16:21:54][W][modbus:155]: Modbus CRC Check failed! A401!=9F37 02.C1.4E.37.9F (5) at 26366
[16:21:54][V][modbus:310]: Clearing buffer of 5 bytes - parse failed at 26379
[16:21:54][V][modbus:067]: Modbus received first Byte  66 (0X42) at 26381
[16:21:54][W][modbus:155]: Modbus CRC Check failed! CEC6!=C3D3 42.CA.A7.D3.C3 (5) at 26395
[16:21:54][V][modbus:310]: Clearing buffer of 5 bytes - parse failed at 26398
[16:21:54][V][modbus:067]: Modbus received first Byte  4 (0X4) at 26411
[16:21:54][W][modbus:155]: Modbus CRC Check failed! DB04!=7F3F 04.B3.67.3F.7F (5) at 26413
[16:21:54][V][modbus:310]: Clearing buffer of 5 bytes - parse failed at 26427
[16:21:54][V][modbus:067]: Modbus received first Byte  246 (0Xf6) at 26429
[16:21:54][D][uart_debug:114]: <<< 00:00:00:00:C2:43:8A:3D:3F:7F:F8:B4:00:00:00:00:C0:8B:87:41:00:00:00:00:42:47:FD:88:46:D5:09:0D:3A:83:12:6F:44:CA:5D:50:45:46:05:60:70:24:00:00:01:04:A0:43:61:DB:CA:43:65:54:25:43:67:4C:6A:40:55:C4:8F:40:A4:5C:74:40:C3:25:32:44:38:7C:86:44:92:93:DC:44:AA:CF:4D:44:38:83:CA:44:93:1F:B2:44:AB:9D:02:C1:4E:37:9F:42:CA:A7:D3:C3:04:B3:67:3F:7F:F6:12:3F:7F:0C:D8:3F:7E:CD:7E:BF:7F:5D:23:40:9D:FF:F5:C0:B1:68:17:43:64:D4:1F:00:00:00:00:40:9B:40:3F:41:68:E0
[16:21:54][W][component:237]: Component modbus took a long time for an operation (191 ms).
[16:21:54][W][component:238]: Components should block for at most 30 ms.
[16:21:54][V][modbus:310]: Clearing buffer of 54 bytes - timeout at 26519
[16:21:54][D][uart_debug:114]: <<< 5E:00:00:00:00:45:4C:D0:B6:00:00:00:00:45:4D:AB:AC
```

**Comment by exciton** [comment]
To help narrow it down, could you also test Arduino 2.0.7 with the same config as you tested 2.0.6, and esp-idf v4.4.3?

There's a bunch of uart changes between those versions that could be of interest.

**Comment by exciton** [comment]
Ok, I did some extensive testing to figure out what's going on, and it all comes down to low level buffering between the hardware UART and the RxBuffer in the UART driver (both for Arduino and ESP-IDF stacks).

When the RxBuffer is large (set to 120 by default) two things happen:
- The first byte arrives late (either after a timeout from the end of a short message or after a full 120 bytes arrive)
- The bytes after 120 arrive after a delay (since they are buffered by the hardware serial and not delivered to the drive - so it seems like a gap

The way to fix this is to force the hardware UART to deliver every byte into the RxBuffer when it arrives.

For arduino library it goes in uart_component_esp32_arduino.cpp inside load_settings() after begin():
this->hw_serial_->setRxFIFOFull(1); 

For esp-idf it goes in uart_component_esp_idf.cpp inside setup() after uart_driver_install():
uart_set_rx_full_threshold(this->uart_num_, 1);

This eliminates the need for the long_rx_buffer_delay which I added, and ensures we can capture short gaps between frames to pick up spurious characters (like the extra 0x00 from above) I hope.

Here are is the summary results of the tests I ran:
With the long_rx_buffer_delay disabled I tested the time between modbus write and first byte picked up by the modbus library
Arduino library 2.0.5 (i.e. recommended) shows the long delay (140-180ms) and 120byte timeout issue ❌
Adruino library 2.0.6+ shows short delay (30-50ms) and no timeout issue ✅ (tested 2.0.7, 2.0.11, 2.0.17)
Arduino library 2.0.5 with setRxFIFOFull(1) shows short delay (30-50ms) and no timeout issue ✅ 
ESP-IDF library 5.1.5 (recommended) and 5.3.0 shows the long delay (140-180ms) and 120byte timeout issue ❌
ESP-IDF library 5.1.5 with uart_set_rx_full_threshold(x,1) shows short delay (30-50ms) and no timeout issue ✅ 

I will write a patch to remove the long_rx_buffer_delay and instead add an option to reduce the RxFIFOFull threshold in UART. Since this is the default behaviour in Arduino library 2.0.6+ I don't see any reason not to use it. 

In the meantime, I don't see a reason not to use Arduino 2.0.6 in conjunction with my current patch to get the desired behaviour.

**Comment by karllinder** [comment]
Very good work, to find this!
Just a note, have been running 2.0.7 for last 24h with out any issues.
IDF I did not manage to load the correct version, give error message, probably me not know how to set the parameters correct.

Let me know if you need more testing from me?
I let is run on 2.0.7 and see how it´s going over time.

Below output logs:

```
INFO ESPHome 2024.12.2
INFO Reading configuration /config/esphome/utility meter House.yaml...
WARNING The selected Arduino framework version is not the recommended one. If there are connectivity or build issues please remove the manual version.
INFO Detected timezone 'Europe/Stockholm'
WARNING GPIO5 is a strapping PIN and should only be used for I/O with care.
Attaching external pullup/down resistors to strapping pins can cause unexpected failures.
See https://esphome.io/guides/faq.html#why-am-i-getting-a-warning-about-strapping-pins
WARNING The selected Arduino framework version is not the recommended one. If there are connectivity or build issues please remove the manual version.
INFO Starting log output from 192.168.1.12 using esphome API
INFO Successfully connected to utilhouse @ 192.168.1.12 in 0.087s
INFO Successful handshake with utilhouse @ 192.168.1.12 in 0.107s
[21:49:36][I][app:100]: ESPHome version 2024.12.2 compiled on Jan  6 2025, 19:32:08
[21:49:36][C][status_led:019]: Status LED:
[21:49:36][C][status_led:020]:   Pin: GPIO25
[21:49:36][C][wifi:600]: WiFi:
[21:49:36][C][wifi:428]:   Local MAC: 7C:9E:BD:F3:1A:34
[21:49:36][C][wifi:433]:   SSID: [redacted]
[21:49:36][C][wifi:436]:   IP Address: 192.168.1.12
[21:49:36][C][wifi:440]:   BSSID: [redacted]
[21:49:36][C][wifi:441]:   Hostname: 'utilhouse'
[21:49:36][C][wifi:443]:   Signal strength: -69 dB ▂▄▆█
[21:49:36][V][wifi:445]:   Priority: 0.0
[21:49:36][C][wifi:447]:   Channel: 6
[21:49:36][C][wifi:448]:   Subnet: 255.255.255.0
[21:49:36][C][wifi:449]:   Gateway: 192.168.1.1
[21:49:36][C][wifi:450]:   DNS1: 8.8.8.8
[21:49:36][C][wifi:451]:   DNS2: 1.1.1.1
[21:49:36][C][logger:185]: Logger:
[21:49:36][C][logger:186]:   Level: VERBOSE
[21:49:36][C][logger:188]:   Log Baud Rate: 115200
[21:49:36][C][logger:189]:   Hardware UART: UART0
[21:49:36][C][gpio.one_wire:020]: GPIO 1-wire bus:
[21:49:36][C][gpio.one_wire:021]:   Pin: GPIO32
[21:49:36][C][gpio.one_wire:080]:   Found devices:
[21:49:36][C][gpio.one_wire:082]:     0xa73c01f09514a628 (DS18B20)
[21:49:36][C][uart.arduino_esp32:151]: UART Bus 1:
[21:49:36][C][uart.arduino_esp32:152]:   TX Pin: GPIO17
[21:49:36][C][uart.arduino_esp32:153]:   RX Pin: GPIO16
[21:49:36][C][uart.arduino_esp32:155]:   RX Buffer Size: 256
[21:49:36][C][uart.arduino_esp32:157]:   Baud Rate: 9600 baud
[21:49:36][C][uart.arduino_esp32:158]:   Data Bits: 8
[21:49:36][C][uart.arduino_esp32:159]:   Parity: NONE
[21:49:36][C][uart.arduino_esp32:160]:   Stop bits: 1
[21:49:36][C][modbus:226]: Modbus:
[21:49:36][C][modbus:227]:   Flow Control Pin: GPIO5
[21:49:36][C][modbus:228]:   Send Wait Time: 200 ms
[21:49:36][C][modbus:229]:   Turnaround Time: 200 ms
[21:49:36][C][modbus:230]:   Frame Delay: 5 ms
[21:49:36][C][modbus:231]:   Long Rx Buffer Delay: 138 ms
[21:49:36][C][modbus:232]:   CRC Disabled: NO
[21:49:36][C][uptime.sensor:033]: Uptime Sensor 'Uptime'
[21:49:36][C][uptime.sensor:033]:   Device Class: 'duration'
[21:49:36][C][uptime.sensor:033]:   State Class: 'total_increasing'
[21:49:36][C][uptime.sensor:033]:   Unit of Measurement: 'h'
[21:49:36][C][uptime.sensor:033]:   Accuracy Decimals: 0
[21:49:36][C][uptime.sensor:033]:   Icon: 'mdi:timer-outline'
[21:49:36][V][uptime.sensor:033]:   Unique ID: '7c9ebdf31a34-uptime'
[21:49:36][C][uptime.sensor:034]:   Type: Seconds
[21:49:36][C][dallas.temp.sensor:029]: Dallas Temperature Sensor:
[21:49:36][C][dallas.temp.sensor:034]:   Address: 0xa73c01f09514a628 (DS18B20)
[21:49:36][C][dallas.temp.sensor:035]:   Resolution: 12 bits
[21:49:36][C][dallas.temp.sensor:036]:   Update Interval: 60.0s
[21:49:36][C][sdm_meter:087]: SDM Meter:
[21:49:36][C][sdm_meter:088]:   Address: 0x01
[21:49:36][C][sdm_meter:093]:   Phase A
[21:49:36][C][sdm_meter:094]:     Voltage 'SDM630 Phase A Voltage'
[21:49:36][C][sdm_meter:094]:       Device Class: 'voltage'
[21:49:36][C][sdm_meter:094]:       State Class: 'measurement'
[21:49:36][C][sdm_meter:094]:       Unit of Measurement: 'V'
[21:49:36][C][sdm_meter:094]:       Accuracy Decimals: 2
[21:49:36][C][sdm_meter:095]:     Current 'SDM630 Phase A Current'
[21:49:36][C][sdm_meter:095]:       Device Class: 'current'
[21:49:36][C][sdm_meter:095]:       State Class: 'measurement'
[21:49:36][C][sdm_meter:095]:       Unit of Measurement: 'A'
[21:49:36][C][sdm_meter:095]:       Accuracy Decimals: 3
[21:49:36][C][sdm_meter:096]:     Active Power 'SDM630 Phase A Power'
[21:49:36][C][sdm_meter:096]:       Device Class: 'power'
[21:49:36][C][sdm_meter:096]:       State Class: 'measurement'
[21:49:36][C][sdm_meter:096]:       Unit of Measurement: 'W'
[21:49:36][C][sdm_meter:096]:       Accuracy Decimals: 2
[21:49:36][C][sdm_meter:097]:     Apparent Power 'SDM630 Phase A Apparent Power'
[21:49:36][C][sdm_meter:097]:       State Class: 'measurement'
[21:49:36][C][sdm_meter:097]:       Unit of Measurement: 'VA'
[21:49:36][C][sdm_meter:097]:       Accuracy Decimals: 2
[21:49:36][C][sdm_meter:098]:     Reactive Power 'SDM630 Phase A Reactive Power'
[21:49:36][C][sdm_meter:098]:       State Class: 'measurement'
[21:49:36][C][sdm_meter:098]:       Unit of Measurement: 'var'
[21:49:36][C][sdm_meter:098]:       Accuracy Decimals: 2
[21:49:36][C][sdm_meter:099]:     Power Factor 'SDM630 Phase A Power Factor'
[21:49:36][C][sdm_meter:099]:       Device Class: 'power_factor'
[21:49:36][C][sdm_meter:099]:       State Class: 'measurement'
[21:49:36][C][sdm_meter:099]:       Unit of Measurement: ''
[21:49:36][C][sdm_meter:099]:       Accuracy Decimals: 3
[21:49:36][C][sdm_meter:100]:     Phase Angle 'SDM630 Phase A Phase Angle'
[21:49:36][C][sdm_meter:100]:       State Class: ''
[21:49:36][C][sdm_meter:100]:       Unit of Measurement: '°'
[21:49:36][C][sdm_meter:100]:       Accuracy Decimals: 3
[21:49:36][C][sdm_meter:100]:       Icon: 'mdi:flash'
[21:49:36][C][sdm_meter:093]:   Phase B
[21:49:36][C][sdm_meter:094]:     Voltage 'SDM630 Phase B Voltage'
[21:49:36][C][sdm_meter:094]:       Device Class: 'voltage'
[21:49:36][C][sdm_meter:094]:       State Class: 'measurement'
[21:49:36][C][sdm_meter:094]:       Unit of Measurement: 'V'
[21:49:36][C][sdm_meter:094]:       Accuracy Decimals: 2
[21:49:36][C][sdm_meter:095]:     Current 'SDM630 Phase B Current'
[21:49:36][C][sdm_meter:095]:       Device Class: 'current'
[21:49:36][C][sdm_meter:095]:       State Class: 'measurement'
[21:49:36][C][sdm_meter:095]:       Unit of Measurement: 'A'
[21:49:36][C][sdm_meter:095]:       Accuracy Decimals: 3
[21:49:36][C][sdm_meter:096]:     Active Power 'SDM630 Phase B Power'
[21:49:36][C][sdm_meter:096]:       Device Class: 'power'
[21:49:36][C][sdm_meter:096]:       State Class: 'measurement'
[21:49:36][C][sdm_meter:096]:       Unit of Measurement: 'W'
[21:49:36][C][sdm_meter:096]:       Accuracy Decimals: 2
[21:49:36][C][sdm_meter:097]:     Apparent Power 'SDM630 Phase B Apparent Power'
[21:49:36][C][sdm_meter:097]:       State Class: 'measurement'
[21:49:36][C][sdm_meter:097]:       Unit of Measurement: 'VA'
[21:49:36][C][sdm_meter:097]:       Accuracy Decimals: 2
[21:49:37][C][sdm_meter:098]:     Reactive Power 'SDM630 Phase B Reactive Power'
[21:49:37][C][sdm_meter:098]:       State Class: 'measurement'
[21:49:37][C][sdm_meter:098]:       Unit of Measurement: 'var'
[21:49:37][C][sdm_meter:098]:       Accuracy Decimals: 2
[21:49:37][C][sdm_meter:099]:     Power Factor 'SDM630 Phase B Power Factor'
[21:49:37][C][sdm_meter:099]:       Device Class: 'power_factor'
[21:49:37][C][sdm_meter:099]:       State Class: 'measurement'
[21:49:37][C][sdm_meter:099]:       Unit of Measurement: ''
[21:49:37][C][sdm_meter:099]:       Accuracy Decimals: 3
[21:49:37][C][sdm_meter:100]:     Phase Angle 'SDM630 Phase B Phase Angle'
[21:49:37][C][sdm_meter:100]:       State Class: ''
[21:49:37][C][sdm_meter:100]:       Unit of Measurement: '°'
[21:49:37][C][sdm_meter:100]:       Accuracy Decimals: 3
[21:49:37][C][sdm_meter:100]:       Icon: 'mdi:flash'
[21:49:37][C][sdm_meter:093]:   Phase C
[21:49:37][C][sdm_meter:094]:     Voltage 'SDM630 Phase C Voltage'
[21:49:37][C][sdm_meter:094]:       Device Class: 'voltage'
[21:49:37][C][sdm_meter:094]:       State Class: 'measurement'
[21:49:37][C][sdm_meter:094]:       Unit of Measurement: 'V'
[21:49:37][C][sdm_meter:094]:       Accuracy Decimals: 2
[21:49:37][C][sdm_meter:095]:       Device Class: 'current'
[21:49:37][C][sdm_meter:095]:       Unit of Measurement: 'A'
[21:49:37][C][sdm_meter:095]:       Accuracy Decimals: 3
[21:49:37][C][sdm_meter:096]:     Active Power 'SDM630 Phase C Power'
[21:49:37][C][sdm_meter:096]:       Device Class: 'power'
[21:49:37][C][sdm_meter:096]:       State Class: 'measurement'
[21:49:37][C][sdm_meter:096]:       Unit of Measurement: 'W'
[21:49:37][C][sdm_meter:096]:       Accuracy Decimals: 2
[21:49:37][C][sdm_meter:097]:     Apparent Power 'SDM630 Phase C Apparent Power'
[21:49:37][C][sdm_meter:097]:       State Class: 'measurement'
[21:49:37][C][sdm_meter:097]:       Unit of Measurement: 'VA'
[21:49:37][C][sdm_meter:097]:       Accuracy Decimals: 2
[21:49:37][C][sdm_meter:098]:     Reactive Power 'SDM630 Phase C Reactive Power'
[21:49:37][C][sdm_meter:098]:       State Class: 'measurement'
[21:49:37][C][sdm_meter:098]:       Unit of Measurement: 'var'
[21:49:37][C][sdm_meter:098]:       Accuracy Decimals: 2
[21:49:37][C][sdm_meter:099]:     Power Factor 'SDM630 Phase C Power Factor'
[21:49:37][C][sdm_meter:099]:       Device Class: 'power_factor'
[21:49:37][C][sdm_meter:099]:       State Class: 'measurement'
[21:49:37][C][sdm_meter:099]:       Unit of Measurement: ''
[21:49:37][C][sdm_meter:099]:       Accuracy Decimals: 3
[21:49:37][C][sdm_meter:100]:     Phase Angle 'SDM630 Phase C Phase Angle'
[21:49:37][C][sdm_meter:100]:       State Class: ''
[21:49:37][C][sdm_meter:100]:       Unit of Measurement: '°'
[21:49:37][C][sdm_meter:100]:       Accuracy Decimals: 3
[21:49:37][C][sdm_meter:100]:       Icon: 'mdi:flash'
[21:49:37][C][sdm_meter:102]:   Total Power 'SDM630 Total Power'
[21:49:37][C][sdm_meter:102]:     Device Class: 'power'
[21:49:37][C][sdm_meter:102]:     State Class: 'measurement'
[21:49:37][C][sdm_meter:102]:     Unit of Measurement: 'W'
[21:49:37][C][sdm_meter:102]:     Accuracy Decimals: 2
[21:49:37][C][sdm_meter:103]:   Frequency 'SDM630 Frequency'
[21:49:37][C][sdm_meter:103]:     State Class: 'measurement'
[21:49:37][C][sdm_meter:103]:     Unit of Measurement: 'Hz'
[21:49:37][C][sdm_meter:103]:     Accuracy Decimals: 3
[21:49:37][C][sdm_meter:103]:     Icon: 'mdi:current-ac'
[21:49:37][C][sdm_meter:104]:   Import Active Energy 'SDM630 Import Active Energy'
[21:49:37][C][sdm_meter:104]:     Device Class: 'energy'
[21:49:37][C][sdm_meter:104]:     State Class: 'total_increasing'
[21:49:37][C][sdm_meter:104]:     Unit of Measurement: 'kWh'
[21:49:37][C][sdm_meter:104]:     Accuracy Decimals: 2
[21:49:37][C][sdm_meter:105]:   Export Active Energy 'SDM630 Export Active Energy'
[21:49:37][C][sdm_meter:105]:     Device Class: 'energy'
[21:49:37][C][sdm_meter:105]:     State Class: 'total_increasing'
[21:49:37][C][sdm_meter:105]:     Unit of Measurement: 'kWh'
[21:49:37][C][sdm_meter:105]:     Accuracy Decimals: 2
[21:49:37][C][sdm_meter:106]:   Import Reactive Energy 'SDM630 Import Reactive Energy'
[21:49:37][C][sdm_meter:106]:     State Class: 'total_increasing'
[21:49:37][C][sdm_meter:106]:     Unit of Measurement: 'kVARh'
[21:49:37][C][sdm_meter:106]:     Accuracy Decimals: 2
[21:49:37][C][sdm_meter:107]:   Export Reactive Energy 'SDM630 Export Reactive Energy'
[21:49:37][C][sdm_meter:107]:     State Class: 'total_increasing'
[21:49:37][C][sdm_meter:107]:     Unit of Measurement: 'kVARh'
[21:49:37][C][sdm_meter:107]:     Accuracy Decimals: 2
[21:49:37][C][status:034]: Status Binary Sensor 'Status'
[21:49:37][C][status:034]:   Device Class: 'connectivity'
[21:49:37][C][restart.button:017]: Restart Button 'Reboot'
[21:49:37][C][restart.button:017]:   Icon: 'mdi:restart'
[21:49:37][C][captive_portal:089]: Captive Portal:
[21:49:37][C][sntp:042]: SNTP Time:
[21:49:37][C][sntp:045]:   Server 0: '0.pool.ntp.org'
[21:49:37][C][sntp:045]:   Server 1: '1.pool.ntp.org'
[21:49:37][C][sntp:045]:   Server 2: '2.pool.ntp.org'
[21:49:37][C][mdns:116]: mDNS:
[21:49:37][C][mdns:117]:   Hostname: utilhouse
[21:49:37][V][mdns:118]:   Services:
[21:49:37][V][mdns:120]:   - _esphomelib, _tcp, 6053
[21:49:37][V][mdns:122]:     TXT: friendly_name = Utilitymeter House
[21:49:37][V][mdns:122]:     TXT: version = 2024.12.2
[21:49:37][V][mdns:122]:     TXT: mac = 7c9ebdf31a34
[21:49:37][V][mdns:122]:     TXT: platform = ESP32
[21:49:37][V][mdns:122]:     TXT: board = esp32dev
[21:49:37][V][mdns:122]:     TXT: network = wifi
[21:49:37][V][mdns:122]:     TXT: api_encryption = Noise_NNpsk0_25519_ChaChaPoly_SHA256
[21:49:37][C][esphome.ota:073]: Over-The-Air updates:
[21:49:37][C][esphome.ota:074]:   Address: 192.168.1.12:3232
[21:49:37][C][esphome.ota:075]:   Version: 2
[21:49:37][C][esphome.ota:078]:   Password configured
[21:49:37][C][safe_mode:018]: Safe Mode:
[21:49:37][C][safe_mode:020]:   Boot considered successful after 60 seconds
[21:49:37][C][safe_mode:021]:   Invoke after 10 boot attempts
[21:49:37][C][safe_mode:023]:   Remain in safe mode for 300 seconds
[21:49:37][C][api:140]: API Server:
[21:49:37][C][api:141]:   Address: 192.168.1.12:6053
[21:49:37][C][api:143]:   Using noise encryption: YES
[21:49:37][C][wifi_signal.sensor:010]: WiFi Signal 'WiFi Signal'
[21:49:37][C][wifi_signal.sensor:010]:   Device Class: 'signal_strength'
[21:49:37][C][wifi_signal.sensor:010]:   State Class: 'measurement'
[21:49:37][C][wifi_signal.sensor:010]:   Unit of Measurement: 'dBm'
[21:49:37][C][wifi_signal.sensor:010]:   Accuracy Decimals: 0
[21:49:37][V][wifi_signal.sensor:010]:   Unique ID: '7c9ebdf31a34-wifisignal'
[21:49:42][D][dallas.temp.sensor:054]: 'Temp': Got Temperature=27.4°C
[21:49:42][V][sensor:043]: 'Temp': Received new state 27.437500
[21:49:42][D][sensor:094]: 'Temp': Sending state 27.43750 °C with 1 decimals of accuracy
[21:49:44][V][modbus:218]: Modbus write: 01.04.00.00.00.50.F0.36 (8) at 94536169
[21:49:44][D][uart_debug:114]: >>> 01:04:00:00:00:50:F0:36
[21:49:44][V][modbus:062]: Modbus received first Byte 0 (0X0) 19ms after last send
[21:49:44][V][modbus:305]: Clearing buffer of 1 bytes - timeout 39ms after last send
[21:49:44][V][modbus:062]: Modbus received first Byte 1 (0X1) 111ms after last send
[21:49:45][D][uart_debug:114]: <<< 00:01:04:A0:43:63:D0:C9:43:67:36:4A:43:6A:74:F4:40:44:C3:F4:40:9E:DA:B0:40:94:22:EC:44:29:FA:F9:44:8F:4A:26:44:87:38:9E:44:29:FA:FA:44:8F:4A:D9:44:87:93:90:00:00:00:00:C0:E1:F9:DB:C2:9C:EE:EE:3F:80:00:00:3F:7F:FE:C2:3F:7F:54:57:3D:C6:7E:3D:BE:B4:A1:EE:C0:84:BE:0A:43:67:29:58:00:00:00:00:40:86:ED:CB:41:4A:64:B0:00:00:00:00:45:35:C0:20:00:00:00:00:45:35:ED:F3:00:00:00:00:C2:AB:0E:8C:3F:7F:E4:62:00:00:00:00:BF:D7:7A:D0:00:00:00:00:42:48:1D:DB:46:D5
[21:49:45][D][sdm_meter:043]: SDMMeter Phase A: V=227.816 V, I=3.074 A, Active P=679.921 W, Apparent P=679.922 VA, Reactive P=0.000 var, PF=1.000, PA=0.097 °
[21:49:45][V][sensor:043]: 'SDM630 Phase A Voltage': Received new state 227.815567
[21:49:45][D][sensor:094]: 'SDM630 Phase A Voltage': Sending state 227.81557 V with 2 decimals of accuracy
[21:49:45][V][sensor:043]: 'SDM630 Phase A Current': Received new state 3.074460
[21:49:45][D][sensor:094]: 'SDM630 Phase A Current': Sending state 3.07446 A with 3 decimals of accuracy
[21:49:45][V][sensor:043]: 'SDM630 Phase A Power': Received new state 679.921448
[21:49:45][D][sensor:094]: 'SDM630 Phase A Power': Sending state 679.92145 W with 2 decimals of accuracy
[21:49:45][V][sensor:043]: 'SDM630 Phase A Apparent Power': Received new state 679.921509
[21:49:45][D][sensor:094]: 'SDM630 Phase A Apparent Power': Sending state 679.92151 VA with 2 decimals of accuracy
[21:49:45][V][sensor:043]: 'SDM630 Phase A Reactive Power': Received new state 0.000000
[21:49:45][D][sensor:094]: 'SDM630 Phase A Reactive Power': Sending state 0.00000 var with 2 decimals of accuracy
[21:49:45][V][sensor:043]: 'SDM630 Phase A Power Factor': Received new state 1.000000
[21:49:45][D][sensor:094]: 'SDM630 Phase A Power Factor': Sending state 1.00000  with 3 decimals of accuracy
[21:49:45][V][sensor:043]: 'SDM630 Phase A Phase Angle': Received new state 0.096920
[21:49:45][D][sensor:094]: 'SDM630 Phase A Phase Angle': Sending state 0.09692 ° with 3 decimals of accuracy
[21:49:45][D][sdm_meter:043]: SDMMeter Phase B: V=231.212 V, I=4.964 A, Active P=1146.317 W, Apparent P=1146.339 VA, Reactive P=-7.062 var, PF=1.000, PA=-0.353 °
[21:49:45][V][sensor:043]: 'SDM630 Phase B Voltage': Received new state 231.212067
[21:49:45][D][sensor:094]: 'SDM630 Phase B Voltage': Sending state 231.21207 V with 2 decimals of accuracy
[21:49:45][V][sensor:043]: 'SDM630 Phase B Current': Received new state 4.964195
[21:49:45][D][sensor:094]: 'SDM630 Phase B Current': Sending state 4.96420 A with 3 decimals of accuracy
[21:49:45][V][sensor:043]: 'SDM630 Phase B Power': Received new state 1146.317139
[21:49:45][D][sensor:094]: 'SDM630 Phase B Power': Sending state 1146.31714 W with 2 decimals of accuracy
[21:49:45][V][sensor:043]: 'SDM630 Phase B Apparent Power': Received new state 1146.338989
[21:49:45][D][sensor:094]: 'SDM630 Phase B Apparent Power': Sending state 1146.33899 VA with 2 decimals of accuracy
[21:49:45][V][sensor:043]: 'SDM630 Phase B Reactive Power': Received new state -7.061750
[21:49:45][D][sensor:094]: 'SDM630 Phase B Reactive Power': Sending state -7.06175 var with 2 decimals of accuracy
[21:49:45][V][sensor:043]: 'SDM630 Phase B Power Factor': Received new state 0.999981
[21:49:45][D][sensor:094]: 'SDM630 Phase B Power Factor': Sending state 0.99998  with 3 decimals of accuracy
[21:49:45][V][sensor:043]: 'SDM630 Phase B Phase Angle': Received new state -0.352798
[21:49:45][D][sensor:094]: 'SDM630 Phase B Phase Angle': Sending state -0.35280 ° with 3 decimals of accuracy
[21:49:45][D][sdm_meter:043]: SDMMeter Phase C: V=234.457 V, I=4.629 A, Active P=1081.769 W, Apparent P=1084.611 VA, Reactive P=-78.467 var, PF=0.997, PA=-4.148 °
[21:49:45][V][sensor:043]: 'SDM630 Phase C Voltage': Received new state 234.456848
[21:49:45][D][sensor:094]: 'SDM630 Phase C Voltage': Sending state 234.45685 V with 2 decimals of accuracy
[21:49:45][V][sensor:043]: 'SDM630 Phase C Current': Received new state 4.629263
[21:49:45][D][sensor:094]: 'SDM630 Phase C Current': Sending state 4.62926 A with 3 decimals of accuracy
[21:49:45][V][sensor:043]: 'SDM630 Phase C Power': Received new state 1081.769287
[21:49:45][D][sensor:094]: 'SDM630 Phase C Power': Sending state 1081.76929 W with 2 decimals of accuracy
[21:49:45][V][sensor:043]: 'SDM630 Phase C Apparent Power': Received new state 1084.611328
[21:49:45][D][sensor:094]: 'SDM630 Phase C Apparent Power': Sending state 1084.61133 VA with 2 decimals of accuracy
[21:49:45][V][sensor:043]: 'SDM630 Phase C Reactive Power': Received new state -78.466660
[21:49:45][D][sensor:094]: 'SDM630 Phase C Reactive Power': Sending state -78.46666 var with 2 decimals of accuracy
[21:49:45][V][sensor:043]: 'SDM630 Phase C Power Factor': Received new state 0.997381
[21:49:45][D][sensor:094]: 'SDM630 Phase C Power Factor': Sending state 0.99738  with 3 decimals of accuracy
[21:49:45][V][sensor:043]: 'SDM630 Phase C Phase Angle': Received new state -4.148198
[21:49:45][D][sensor:094]: 'SDM630 Phase C Phase Angle': Sending state -4.14820 ° with 3 decimals of accuracy
[21:49:45][D][sdm_meter:069]: SDMMeter: F=50.029 Hz, Im.A.E=27330.387 Wh, Ex.A.E=0.001 Wh, Im.R.E=1621.785 VARh, Ex.R.E=3173.860 VARh, T.P=2908.008 W
[21:49:45][V][sensor:043]: 'SDM630 Total Power': Received new state 2908.007812
[21:49:45][D][sensor:094]: 'SDM630 Total Power': Sending state 2908.00781 W with 2 decimals of accuracy
[21:49:45][V][sensor:043]: 'SDM630 Frequency': Received new state 50.029156
[21:49:45][D][sensor:094]: 'SDM630 Frequency': Sending state 50.02916 Hz with 3 decimals of accuracy
[21:49:45][V][sensor:043]: 'SDM630 Import Active Energy': Received new state 27330.386719
[21:49:45][D][sensor:094]: 'SDM630 Import Active Energy': Sending state 27330.38672 kWh with 2 decimals of accuracy
[21:49:45][V][sensor:043]: 'SDM630 Export Active Energy': Received new state 0.001000
[21:49:45][D][sensor:094]: 'SDM630 Export Active Energy': Sending state 0.00100 kWh with 2 decimals of accuracy
[21:49:45][V][sensor:043]: 'SDM630 Import Reactive Energy': Received new state 1621.785034
[21:49:45][D][sensor:094]: 'SDM630 Import Reactive Energy': Sending state 1621.78503 kVARh with 2 decimals of accuracy
[21:49:45][V][sensor:043]: 'SDM630 Export Reactive Energy': Received new state 3173.860107
[21:49:45][D][sensor:094]: 'SDM630 Export Reactive Energy': Sending state 3173.86011 kVARh with 2 decimals of accuracy
[21:49:45][V][modbus:305]: Clearing buffer of 165 bytes - parse succeeded 858ms after last send
[21:49:45][V][modbus:062]: Modbus received first Byte 0 (0X0) 871ms after last send
[21:49:45][W][component:237]: Component modbus took a long time for an operation (605 ms).
[21:49:45][W][component:238]: Components should block for at most 30 ms.
[21:49:45][V][modbus:305]: Clearing buffer of 1 bytes - timeout 890ms after last send
[21:49:45][D][uart_debug:114]: <<< 84:C6:3A:83:12:6F:44:CA:B9:1F:45:46:5D:C3:9B:66:00
[21:49:46][V][sensor:043]: 'WiFi Signal': Received new state -68.000000
[21:49:46][D][sensor:094]: 'WiFi Signal': Sending state -68.00000 dBm with 0 decimals of accuracy
[21:49:54][V][modbus:218]: Modbus write: 01.04.00.00.00.50.F0.36 (8) at 94546172
[21:49:54][D][uart_debug:114]: >>> 01:04:00:00:00:50:F0:36
[21:49:54][V][modbus:062]: Modbus received first Byte 0 (0X0) 20ms after last send
[21:49:54][V][modbus:305]: Clearing buffer of 1 bytes - timeout 40ms after last send
[21:49:54][V][modbus:062]: Modbus received first Byte 1 (0X1) 111ms after last send
[21:49:55][D][uart_debug:114]: <<< 00:01:04:A0:43:63:67:DD:43:67:2B:6F:43:6A:BB:C2:40:46:15:44:40:9E:D0:9E:40:94:3A:24:44:29:48:28:44:8F:6A:BD:44:87:7F:0B:44:29:48:30:44:8F:6B:5E:44:87:D9:F2:00:00:00:00:C0:D6:AD:E6:C2:9D:0D:D6:3F:80:00:00:3F:7F:FE:48:3F:7F:55:A7:3D:D6:65:A7:BE:D4:79:D8:C0:84:3B:DF:43:67:1A:5B:00:00:00:00:40:87:2A:0F:41:4A:BF:16:00:00:00:00:45:35:C8:86:00:00:00:00:45:35:F6:45:00:00:00:00:C2:AD:57:CA:3F:7F:E3:BB:00:00:00:00:BF:D9:FB:3C:00:00:00:00:42:48:1A:5A:46:D5
[21:49:55][D][sdm_meter:043]: SDMMeter Phase A: V=227.406 V, I=3.095 A, Active P=677.127 W, Apparent P=677.128 VA, Reactive P=0.000 var, PF=1.000, PA=0.105 °
[21:49:55][V][sensor:043]: 'SDM630 Phase A Voltage': Received new state 227.405716
[21:49:55][D][sensor:094]: 'SDM630 Phase A Voltage': Sending state 227.40572 V with 2 decimals of accuracy
[21:49:55][V][sensor:043]: 'SDM630 Phase A Current': Received new state 3.095048
[21:49:55][D][sensor:094]: 'SDM630 Phase A Current': Sending state 3.09505 A with 3 decimals of accuracy
[21:49:55][V][sensor:043]: 'SDM630 Phase A Power': Received new state 677.127441
[21:49:55][D][sensor:094]: 'SDM630 Phase A Power': Sending state 677.12744 W with 2 decimals of accuracy
[21:49:55][V][sensor:043]: 'SDM630 Phase A Apparent Power': Received new state 677.127930
[21:49:55][D][sensor:094]: 'SDM630 Phase A Apparent Power': Sending state 677.12793 VA with 2 decimals of accuracy
[21:49:55][V][sensor:043]: 'SDM630 Phase A Reactive Power': Received new state 0.000000
[21:49:55][D][sensor:094]: 'SDM630 Phase A Reactive Power': Sending state 0.00000 var with 2 decimals of accuracy
[21:49:55][V][sensor:043]: 'SDM630 Phase A Power Factor': Received new state 1.000000
[21:49:55][D][sensor:094]: 'SDM630 Phase A Power Factor': Sending state 1.00000  with 3 decimals of accuracy
[21:49:55][V][sensor:043]: 'SDM630 Phase A Phase Angle': Received new state 0.104686
[21:49:55][D][sensor:094]: 'SDM630 Phase A Phase Angle': Sending state 0.10469 ° with 3 decimals of accuracy
[21:49:55][D][sdm_meter:043]: SDMMeter Phase B: V=231.170 V, I=4.963 A, Active P=1147.336 W, Apparent P=1147.355 VA, Reactive P=-6.709 var, PF=1.000, PA=-0.415 °
[21:49:55][V][sensor:043]: 'SDM630 Phase B Voltage': Received new state 231.169662
[21:49:55][D][sensor:094]: 'SDM630 Phase B Voltage': Sending state 231.16966 V with 2 decimals of accuracy
[21:49:55][V][sensor:043]: 'SDM630 Phase B Current': Received new state 4.962966
[21:49:55][D][sensor:094]: 'SDM630 Phase B Current': Sending state 4.96297 A with 3 decimals of accuracy
[21:49:55][V][sensor:043]: 'SDM630 Phase B Power': Received new state 1147.335571
[21:49:55][D][sensor:094]: 'SDM630 Phase B Power': Sending state 1147.33557 W with 2 decimals of accuracy
[21:49:55][V][sensor:043]: 'SDM630 Phase B Apparent Power': Received new state 1147.355225
[21:49:55][D][sensor:094]: 'SDM630 Phase B Apparent Power': Sending state 1147.35522 VA with 2 decimals of accuracy
[21:49:55][V][sensor:043]: 'SDM630 Phase B Reactive Power': Received new state -6.708728
[21:49:55][D][sensor:094]: 'SDM630 Phase B Reactive Power': Sending state -6.70873 var with 2 decimals of accuracy
[21:49:55][V][sensor:043]: 'SDM630 Phase B Power Factor': Received new state 0.999974
[21:49:55][D][sensor:094]: 'SDM630 Phase B Power Factor': Sending state 0.99997  with 3 decimals of accuracy
[21:49:55][V][sensor:043]: 'SDM630 Phase B Phase Angle': Received new state -0.414992
[21:49:55][D][sensor:094]: 'SDM630 Phase B Phase Angle': Sending state -0.41499 ° with 3 decimals of accuracy
[21:49:55][D][sdm_meter:043]: SDMMeter Phase C: V=234.733 V, I=4.632 A, Active P=1083.970 W, Apparent P=1086.811 VA, Reactive P=-78.527 var, PF=0.997, PA=-4.132 °
[21:49:55][V][sensor:043]: 'SDM630 Phase C Voltage': Received new state 234.733429
[21:49:55][D][sensor:094]: 'SDM630 Phase C Voltage': Sending state 234.73343 V with 2 decimals of accuracy
[21:49:55][V][sensor:043]: 'SDM630 Phase C Current': Received new state 4.632097
[21:49:55][D][sensor:094]: 'SDM630 Phase C Current': Sending state 4.63210 A with 3 decimals of accuracy
[21:49:55][V][sensor:043]: 'SDM630 Phase C Power': Received new state 1083.970093
[21:49:55][D][sensor:094]: 'SDM630 Phase C Power': Sending state 1083.97009 W with 2 decimals of accuracy
[21:49:55][V][sensor:043]: 'SDM630 Phase C Apparent Power': Received new state 1086.810791
[21:49:55][D][sensor:094]: 'SDM630 Phase C Apparent Power': Sending state 1086.81079 VA with 2 decimals of accuracy
[21:49:55][V][sensor:043]: 'SDM630 Phase C Reactive Power': Received new state -78.527023
[21:49:55][D][sensor:094]: 'SDM630 Phase C Reactive Power': Sending state -78.52702 var with 2 decimals of accuracy
[21:49:55][V][sensor:043]: 'SDM630 Phase C Power Factor': Received new state 0.997401
[21:49:55][D][sensor:094]: 'SDM630 Phase C Power Factor': Sending state 0.99740  with 3 decimals of accuracy
[21:49:55][V][sensor:043]: 'SDM630 Phase C Phase Angle': Received new state -4.132308
[21:49:55][D][sensor:094]: 'SDM630 Phase C Phase Angle': Sending state -4.13231 ° with 3 decimals of accuracy
[21:49:55][D][sdm_meter:069]: SDMMeter: F=50.026 Hz, Im.A.E=27330.395 Wh, Ex.A.E=0.001 Wh, Im.R.E=1621.785 VARh, Ex.R.E=3173.860 VARh, T.P=2908.533 W
[21:49:55][V][sensor:043]: 'SDM630 Total Power': Received new state 2908.532715
[21:49:55][D][sensor:094]: 'SDM630 Total Power': Sending state 2908.53271 W with 2 decimals of accuracy
[21:49:55][V][sensor:043]: 'SDM630 Frequency': Received new state 50.025734
[21:49:55][D][sensor:094]: 'SDM630 Frequency': Sending state 50.02573 Hz with 3 decimals of accuracy
[21:49:55][V][sensor:043]: 'SDM630 Import Active Energy': Received new state 27330.394531
[21:49:55][D][sensor:094]: 'SDM630 Import Active Energy': Sending state 27330.39453 kWh with 2 decimals of accuracy
[21:49:55][V][sensor:043]: 'SDM630 Export Active Energy': Received new state 0.001000
[21:49:55][D][sensor:094]: 'SDM630 Export Active Energy': Sending state 0.00100 kWh with 2 decimals of accuracy
[21:49:55][V][sensor:043]: 'SDM630 Import Reactive Energy': Received new state 1621.785034
[21:49:55][D][sensor:094]: 'SDM630 Import Reactive Energy': Sending state 1621.78503 kVARh with 2 decimals of accuracy
[21:49:55][V][sensor:043]: 'SDM630 Export Reactive Energy': Received new state 3173.860107
[21:49:55][D][sensor:094]: 'SDM630 Export Reactive Energy': Sending state 3173.86011 kVARh with 2 decimals of accuracy
[21:49:55][V][modbus:305]: Clearing buffer of 165 bytes - parse succeeded 862ms after last send
[21:49:55][V][modbus:062]: Modbus received first Byte 0 (0X0) 876ms after last send
[21:49:55][W][component:237]: Component modbus took a long time for an operation (610 ms).
[21:49:55][W][component:238]: Components should block for at most 30 ms.
[21:49:55][V][modbus:305]: Clearing buffer of 1 bytes - timeout 894ms after last send
[21:49:55][D][uart_debug:114]: <<< 84:CA:3A:83:12:6F:44:CA:B9:1F:45:46:5D:C3:BF:D0:00
[21:50:04][V][modbus:218]: Modbus write: 01.04.00.00.00.50.F0.36 (8) at 94556166
[21:50:04][D][uart_debug:114]: >>> 01:04:00:00:00:50:F0:36
[21:50:04][V][modbus:062]: Modbus received first Byte 0 (0X0) 20ms after last send
[21:50:04][V][modbus:305]: Clearing buffer of 1 bytes - timeout 40ms after last send
[21:50:04][V][modbus:062]: Modbus received first Byte 1 (0X1) 112ms after last send
[21:50:05][D][uart_debug:114]: <<< 00:01:04:A0:43:64:02:4B:43:66:B8:36:43:6A:DE:3B:40:46:28:62:40:9E:91:77:40:94:52:5E:44:2A:61:DC:44:8E:C4:DB:44:87:9B:4E:44:2A:61:E4:44:8E:C5:AB:44:87:F5:C2:00:00:00:00:C0:F3:11:6A:C2:9C:BA:85:3F:80:00:00:3F:7F:FE:91:3F:7F:55:AE:3E:03:4A:79:BE:C2:0D:0D:C0:84:39:25:43:67:32:E9:00:00:00:00:40:87:20:40:41:4A:B0:60:00:00:00:00:45:35:C8:8C:00:00:00:00:45:35:F6:30:00:00:00:00:C2:AF:82:20:3F:7F:E4:9C:00:00:00:00:BF:DD:66:0C:00:00:00:00:42:48:06:FC:46:D5
[21:50:05][D][sdm_meter:043]: SDMMeter Phase A: V=228.009 V, I=3.096 A, Active P=681.529 W, Apparent P=681.530 VA, Reactive P=0.000 var, PF=1.000, PA=0.128 °
[21:50:05][V][sensor:043]: 'SDM630 Phase A Voltage': Received new state 228.008957
[21:50:05][D][sensor:094]: 'SDM630 Phase A Voltage': Sending state 228.00896 V with 2 decimals of accuracy
[21:50:05][V][sensor:043]: 'SDM630 Phase A Current': Received new state 3.096215
[21:50:05][D][sensor:094]: 'SDM630 Phase A Current': Sending state 3.09621 A with 3 decimals of accuracy
[21:50:05][V][sensor:043]: 'SDM630 Phase A Power': Received new state 681.529053
[21:50:05][D][sensor:094]: 'SDM630 Phase A Power': Sending state 681.52905 W with 2 decimals of accuracy
[21:50:05][V][sensor:043]: 'SDM630 Phase A Apparent Power': Received new state 681.529541
[21:50:05][D][sensor:094]: 'SDM630 Phase A Apparent Power': Sending state 681.52954 VA with 2 decimals of accuracy
[21:50:05][V][sensor:043]: 'SDM630 Phase A Reactive Power': Received new state 0.000000
[21:50:05][D][sensor:094]: 'SDM630 Phase A Reactive Power': Sending state 0.00000 var with 2 decimals of accuracy
[21:50:05][V][sensor:043]: 'SDM630 Phase A Power Factor': Received new state 1.000000
[21:50:05][D][sensor:094]: 'SDM630 Phase A Power Factor': Sending state 1.00000  with 3 decimals of accuracy
[21:50:05][V][sensor:043]: 'SDM630 Phase A Phase Angle': Received new state 0.128214
[21:50:05][D][sensor:094]: 'SDM630 Phase A Phase Angle': Sending state 0.12821 ° with 3 decimals of accuracy
[21:50:05][D][sdm_meter:043]: SDMMeter Phase B: V=230.720 V, I=4.955 A, Active P=1142.152 W, Apparent P=1142.177 VA, Reactive P=-7.596 var, PF=1.000, PA=-0.379 °
[21:50:05][V][sensor:043]: 'SDM630 Phase B Voltage': Received new state 230.719574
[21:50:05][D][sensor:094]: 'SDM630 Phase B Voltage': Sending state 230.71957 V with 2 decimals of accuracy
[21:50:05][V][sensor:043]: 'SDM630 Phase B Current': Received new state 4.955257
[21:50:05][D][sensor:094]: 'SDM630 Phase B Current': Sending state 4.95526 A with 3 decimals of accuracy
[21:50:05][V][sensor:043]: 'SDM630 Phase B Power': Received new state 1142.151733
[21:50:05][D][sensor:094]: 'SDM630 Phase B Power': Sending state 1142.15173 W with 2 decimals of accuracy
[21:50:05][V][sensor:043]: 'SDM630 Phase B Apparent Power': Received new state 1142.177124
[21:50:05][D][sensor:094]: 'SDM630 Phase B Apparent Power': Sending state 1142.17712 VA with 2 decimals of accuracy
[21:50:05][V][sensor:043]: 'SDM630 Phase B Reactive Power': Received new state -7.595876
[21:50:05][D][sensor:094]: 'SDM630 Phase B Reactive Power': Sending state -7.59588 var with 2 decimals of accuracy
[21:50:05][V][sensor:043]: 'SDM630 Phase B Power Factor': Received new state 0.999978
[21:50:05][D][sensor:094]: 'SDM630 Phase B Power Factor': Sending state 0.99998  with 3 decimals of accuracy
[21:50:05][V][sensor:043]: 'SDM630 Phase B Phase Angle': Received new state -0.379006
[21:50:05][D][sensor:094]: 'SDM630 Phase B Phase Angle': Sending state -0.37901 ° with 3 decimals of accuracy
[21:50:05][D][sdm_meter:043]: SDMMeter Phase C: V=234.868 V, I=4.635 A, Active P=1084.853 W, Apparent P=1087.680 VA, Reactive P=-78.364 var, PF=0.997, PA=-4.132 °
[21:50:05][V][sensor:043]: 'SDM630 Phase C Voltage': Received new state 234.868088
[21:50:05][D][sensor:094]: 'SDM630 Phase C Voltage': Sending state 234.86809 V with 2 decimals of accuracy
[21:50:05][V][sensor:043]: 'SDM630 Phase C Current': Received new state 4.635055
[21:50:05][D][sensor:094]: 'SDM630 Phase C Current': Sending state 4.63505 A with 3 decimals of accuracy
[21:50:05][V][sensor:043]: 'SDM630 Phase C Power': Received new state 1084.853271
[21:50:05][D][sensor:094]: 'SDM630 Phase C Power': Sending state 1084.85327 W with 2 decimals of accuracy
[21:50:05][V][sensor:043]: 'SDM630 Phase C Apparent Power': Received new state 1087.679932
[21:50:05][D][sensor:094]: 'SDM630 Phase C Apparent Power': Sending state 1087.67993 VA with 2 decimals of accuracy
[21:50:05][V][sensor:043]: 'SDM630 Phase C Reactive Power': Received new state -78.364296
[21:50:05][D][sensor:094]: 'SDM630 Phase C Reactive Power': Sending state -78.36430 var with 2 decimals of accuracy
[21:50:05][V][sensor:043]: 'SDM630 Phase C Power Factor': Received new state 0.997401
[21:50:05][D][sensor:094]: 'SDM630 Phase C Power Factor': Sending state 0.99740  with 3 decimals of accuracy
[21:50:05][V][sensor:043]: 'SDM630 Phase C Phase Angle': Received new state -4.131976
[21:50:05][D][sensor:094]: 'SDM630 Phase C Phase Angle': Sending state -4.13198 ° with 3 decimals of accuracy
[21:50:05][D][sdm_meter:069]: SDMMeter: F=50.007 Hz, Im.A.E=27330.402 Wh, Ex.A.E=0.001 Wh, Im.R.E=1621.785 VARh, Ex.R.E=3173.860 VARh, T.P=2908.534 W
[21:50:05][V][sensor:043]: 'SDM630 Total Power': Received new state 2908.534180
[21:50:05][D][sensor:094]: 'SDM630 Total Power': Sending state 2908.53418 W with 2 decimals of accuracy
[21:50:05][V][sensor:043]: 'SDM630 Frequency': Received new state 50.006821
[21:50:05][D][sensor:094]: 'SDM630 Frequency': Sending state 50.00682 Hz with 3 decimals of accuracy
[21:50:05][V][sensor:043]: 'SDM630 Import Active Energy': Received new state 27330.402344
[21:50:05][D][sensor:094]: 'SDM630 Import Active Energy': Sending state 27330.40234 kWh with 2 decimals of accuracy
[21:50:05][V][sensor:043]: 'SDM630 Export Active Energy': Received new state 0.001000
[21:50:05][D][sensor:094]: 'SDM630 Export Active Energy': Sending state 0.00100 kWh with 2 decimals of accuracy
[21:50:05][V][sensor:043]: 'SDM630 Import Reactive Energy': Received new state 1621.785034
[21:50:05][D][sensor:094]: 'SDM630 Import Reactive Energy': Sending state 1621.78503 kVARh with 2 decimals of accuracy
[21:50:05][V][sensor:043]: 'SDM630 Export Reactive Energy': Received new state 3173.860107
[21:50:05][D][sensor:094]: 'SDM630 Export Reactive Energy': Sending state 3173.86011 kVARh with 2 decimals of accuracy
[21:50:05][V][modbus:305]: Clearing buffer of 165 bytes - parse succeeded 859ms after last send
[21:50:05][V][modbus:062]: Modbus received first Byte 0 (0X0) 861ms after last send
[21:50:05][W][component:237]: Component modbus took a long time for an operation (606 ms).
[21:50:05][W][component:238]: Components should block for at most 30 ms.
[21:50:05][V][modbus:305]: Clearing buffer of 1 bytes - timeout 891ms after last send
[21:50:05][V][sensor:043]: 'Uptime': Received new state 94557.078125
[21:50:05][D][sensor:094]: 'Uptime': Sending state 26.00000 h with 0 decimals of accuracy
[21:50:05][D][uart_debug:114]: <<< 84:CE:3A:83:12:6F:44:CA:B9:1F:45:46:5D:C3:F5:01:00
[21:50:14][V][modbus:218]: Modbus write: 01.04.00.00.00.50.F0.36 (8) at 94566175
[21:50:14][D][uart_debug:114]: >>> 01:04:00:00:00:50:F0:36
[21:50:14][V][modbus:062]: Modbus received first Byte 0 (0X0) 20ms after last send
[21:50:14][V][modbus:305]: Clearing buffer of 1 bytes - timeout 39ms after last send
[21:50:14][V][modbus:062]: Modbus received first Byte 1 (0X1) 110ms after last send
[21:50:15][D][uart_debug:114]: <<< 00:01:04:A0:43:64:28:FA:43:67:1F:76:43:6A:B7:91:40:46:49:0D:40:9E:C4:13:40:94:5D:26:44:2B:36:1B:44:8F:3F:BC:44:87:94:A1:44:2B:36:24:44:8F:40:CB:44:87:F0:1D:00:00:00:00:C1:0B:31:67:C2:9D:9A:F1:3F:80:00:00:3F:7F:FE:22:3F:7F:53:C7:3E:53:81:AD:BE:DD:76:13:C0:84:F5:A7:43:67:55:55:00:00:00:00:40:87:3A:20:41:4A:D7:30:00:00:00:00:45:36:37:B5:00:00:00:00:45:36:65:FD:00:00:00:00:C2:AF:01:1E:3F:7F:E4:14:00:00:00:00:BF:DC:08:42:00:00:00:00:42:48:07:13:46:D5
[21:50:15][D][sdm_meter:043]: SDMMeter Phase A: V=228.160 V, I=3.098 A, Active P=684.845 W, Apparent P=684.846 VA, Reactive P=0.000 var, PF=1.000, PA=0.207 °
[21:50:15][V][sensor:043]: 'SDM630 Phase A Voltage': Received new state 228.160065
[21:50:15][D][sensor:094]: 'SDM630 Phase A Voltage': Sending state 228.16006 V with 2 decimals of accuracy
[21:50:15][V][sensor:043]: 'SDM630 Phase A Current': Received new state 3.098209
[21:50:15][D][sensor:094]: 'SDM630 Phase A Current': Sending state 3.09821 A with 3 decimals of accuracy
[21:50:15][V][sensor:043]: 'SDM630 Phase A Power': Received new state 684.845398
[21:50:15][D][sensor:094]: 'SDM630 Phase A Power': Sending state 684.84540 W with 2 decimals of accuracy
[21:50:15][V][sensor:043]: 'SDM630 Phase A Apparent Power': Received new state 684.845947
[21:50:15][D][sensor:094]: 'SDM630 Phase A Apparent Power': Sending state 684.84595 VA with 2 decimals of accuracy
```

**Comment by exciton** [comment]
Most recent commits do the following:
- Remove the long timeout delay in favour of setting RxFIFOFull (or uart_set_rx_full_threshold) to 1. To properly segregate modbus frames and also receive long responses this is the only way. Only alternate is to have the modbus code run as a low-level driver rather than a component.
- Remove duplicate handling on send - user can deal with this (modbus_controller already does)
- Rename !waiting_for_response to ready_for_immediate_send to reflect the fact that it's waiting until the TX buffer is empty and the line is clear (which is what modbus_controller wants)
- Make response async also (like send). If the response triggers a long list of sensor publishes, this will avoid holding up the main loop

This code works well (for me) for the default versions of Arduino and ESP-IDF using multiple modbus components running at the limit of their response rate.

**Comment by exciton** [comment]
@karllinder - could you test with the latest (with default arduino library) please? I'm interested to see if the long component errors go away.

File: esphome/components/modbus/modbus.cpp [hunk 8]
```diff
@@ -11,46 +13,77 @@ void Modbus::setup() {
...
+    this->frame_delay_ms_ = 2;  // 1750us minimium per spec - rounded up to 2ms.
+
+#ifdef USE_ESP32_FRAMEWORK_ARDUINO
+  static_cast<uart::ESP32ArduinoUARTComponent *>(this->parent_)->get_hw_serial()->setRxFIFOFull(1);
+#endif  // USE_ESP32_FRAMEWORK_ARDUINO
+
+#ifdef USE_ESP_IDF
+  uint8_t serial = static_cast<uart::IDFUARTComponent *>(this->parent_)->get_hw_serial_number();
+  uart_set_rx_full_threshold(serial, 1);
+#endif  // USE_ESP_IDF
```
Comment (exciton) [inline esphome/components/modbus/modbus.cpp]: This can be done in many ways. We could add an option to the uart component to set the FIFOFull threshold, but that would also require the user to set it.
This change profoundly improves the ability for the modbus component to function. It is not able to use timing calculations at all if the UART holds on to 120 bytes at a time (especially for long responses), so putting this code here could make sense.

**Comment by karllinder** [comment]
Hi
Sorry, did not work with default arduino library.

Karl
```

INFO Upload took 10.68 seconds, waiting for result...
INFO OTA successful
INFO Successfully uploaded program.
INFO Starting log output from 192.168.1.12 using esphome API
INFO Successfully connected to utilhouse @ 192.168.1.12 in 7.195s
INFO Successful handshake with utilhouse @ 192.168.1.12 in 1.100s
[19:16:16][I][app:100]: ESPHome version 2024.12.2 compiled on Jan  8 2025, 19:14:03
[19:16:16][C][status_led:019]: Status LED:
[19:16:16][C][status_led:020]:   Pin: GPIO25
[19:16:16][C][wifi:600]: WiFi:
[19:16:16][C][wifi:428]:   Local MAC: 7C:9E:BD:F3:1A:34
[19:16:16][C][wifi:433]:   SSID: '[redacted]
[19:16:16][C][wifi:436]:   IP Address: 192.168.1.12
[19:16:16][C][wifi:440]:   BSSID: (redacted]
[19:16:16][C][wifi:441]:   Hostname: 'utilhouse'
[19:16:16][C][wifi:443]:   Signal strength: -71 dB ââââ
[19:16:16][V][wifi:445]:   Priority: 0.0
[19:16:16][C][wifi:447]:   Channel: 6
[19:16:16][C][wifi:448]:   Subnet: 255.255.255.0
[19:16:16][C][wifi:449]:   Gateway: 192.168.1.1
[19:16:16][C][wifi:450]:   DNS1: 8.8.8.8
[19:16:16][C][wifi:451]:   DNS2: 1.1.1.1
[19:16:16][C][logger:185]: Logger:
[19:16:16][C][sdm_meter:094]:     Voltage 'SDM630 Phase A Voltage'
[19:16:16][C][sdm_meter:094]:       Device Class: 'voltage'
[19:16:16][C][sdm_meter:094]:       State Class: 'measurement'
[19:16:16][C][sdm_meter:094]:       Unit of Measurement: 'V'
[19:16:16][C][sdm_meter:094]:       Accuracy Decimals: 2
[19:16:16][C][sdm_meter:095]:     Current 'SDM630 Phase A Current'
[19:16:16][C][sdm_meter:095]:       Device Class: 'current'
[19:16:16][C][sdm_meter:095]:       State Class: 'measurement'
[19:16:16][C][sdm_meter:095]:       Unit of Measurement: 'A'
[19:16:16][C][sdm_meter:095]:       Accuracy Decimals: 3
[19:16:16][C][sdm_meter:096]:     Active Power 'SDM630 Phase A Power'
[19:16:16][C][sdm_meter:096]:       Device Class: 'power'
[19:16:16][C][sdm_meter:096]:       State Class: 'measurement'
[19:16:16][C][sdm_meter:096]:       Unit of Measurement: 'W'
[19:16:16][C][sdm_meter:096]:       Accuracy Decimals: 2
[19:16:16][C][sdm_meter:097]:     Apparent Power 'SDM630 Phase A Apparent Power'
[19:16:16][C][sdm_meter:097]:       State Class: 'measurement'
[19:16:16][C][sdm_meter:097]:       Unit of Measurement: 'VA'
[19:16:16][C][sdm_meter:097]:       Accuracy Decimals: 2
[19:16:16][C][sdm_meter:098]:     Reactive Power 'SDM630 Phase A Reactive Power'
[19:16:16][C][sdm_meter:098]:       State Class: 'measurement'
[19:16:16][C][sdm_meter:098]:       Unit of Measurement: 'var'
[19:16:16][C][sdm_meter:098]:       Accuracy Decimals: 2
[19:16:16][C][sdm_meter:099]:     Power Factor 'SDM630 Phase A Power Factor'
[19:16:16][C][sdm_meter:099]:       Device Class: 'power_factor'
[19:16:16][C][sdm_meter:099]:       State Class: 'measurement'
[19:16:16][C][sdm_meter:099]:       Unit of Measurement: ''
[19:16:16][C][sdm_meter:099]:       Accuracy Decimals: 3
[19:16:16][C][sdm_meter:100]:     Phase Angle 'SDM630 Phase A Phase Angle'
[19:16:16][C][sdm_meter:100]:       State Class: ''
[19:16:16][C][sdm_meter:100]:       Unit of Measurement: 'Â°'
[19:16:16][C][sdm_meter:100]:       Accuracy Decimals: 3
[19:16:16][C][sdm_meter:100]:       Icon: 'mdi:flash'
[19:16:16][C][sdm_meter:093]:   Phase B
[19:16:16][C][sdm_meter:094]:     Voltage 'SDM630 Phase B Voltage'
[19:16:16][C][sdm_meter:094]:       Device Class: 'voltage'
[19:16:16][C][sdm_meter:094]:       State Class: 'measurement'
[19:16:16][C][sdm_meter:094]:       Unit of Measurement: 'V'
[19:16:16][C][sdm_meter:094]:       Accuracy Decimals: 2
[19:16:16][C][sdm_meter:095]:     Current 'SDM630 Phase B Current'
[19:16:16][C][sdm_meter:095]:       Device Class: 'current'
[19:16:16][C][sdm_meter:095]:       State Class: 'measurement'
[19:16:16][C][sdm_meter:095]:       Unit of Measurement: 'A'
[19:16:16][C][sdm_meter:095]:       Accuracy Decimals: 3
[19:16:16][C][sdm_meter:096]:     Active Power 'SDM630 Phase B Power'
[19:16:16][C][sdm_meter:096]:       Device Class: 'power'
[19:16:16][C][sdm_meter:096]:       State Class: 'measurement'
[19:16:16][C][sdm_meter:096]:       Unit of Measurement: 'W'
[19:16:16][C][sdm_meter:096]:       Accuracy Decimals: 2
[19:16:16][C][sdm_meter:097]:     Apparent Power 'SDM630 Phase B Apparent Power'
[19:16:16][C][sdm_meter:097]:       State Class: 'measurement'
[19:16:16][C][sdm_meter:097]:       Unit of Measurement: 'VA'
[19:16:16][C][sdm_meter:097]:       Accuracy Decimals: 2
[19:16:16][C][sdm_meter:098]:     Reactive Power 'SDM630 Phase B Reactive Power'
[19:16:16][C][sdm_meter:098]:       State Class: 'measurement'
[19:16:16][C][sdm_meter:098]:       Unit of Measurement: 'var'
[19:16:16][C][sdm_meter:098]:       Accuracy Decimals: 2
[19:16:16][C][sdm_meter:099]:     Power Factor 'SDM630 Phase B Power Factor'
[19:16:16][C][sdm_meter:099]:       Device Class: 'power_factor'
[19:16:16][C][sdm_meter:099]:       State Class: 'measurement'
[19:16:16][C][sdm_meter:099]:       Unit of Measurement: ''
[19:16:16][C][sdm_meter:099]:       Accuracy Decimals: 3
[19:16:16][C][sdm_meter:100]:     Phase Angle 'SDM630 Phase B Phase Angle'
[19:16:16][C][sdm_meter:100]:       State Class: ''
[19:16:16][C][sdm_meter:100]:       Unit of Measurement: 'Â°'
[19:16:16][C][sdm_meter:100]:       Accuracy Decimals: 3
[19:16:16][C][sdm_meter:100]:       Icon: 'mdi:flash'
[19:16:16][C][sdm_meter:093]:   Phase C
[19:16:16][C][sdm_meter:094]:     Voltage 'SDM630 Phase C Voltage'
[19:16:16][C][sdm_meter:094]:       Device Class: 'voltage'
[19:16:16][C][sdm_meter:094]:       State Class: 'measurement'
[19:16:16][C][sdm_meter:094]:       Unit of Measurement: 'V'
[19:16:16][C][sdm_meter:094]:       Accuracy Decimals: 2
[19:16:16][C][sdm_meter:095]:     Current 'SDM630 Phase C Current'
[19:16:16][C][sdm_meter:095]:       Device Class: 'current'
[19:16:16][C][sdm_meter:095]:       State Class: 'measurement'
[19:16:16][C][sdm_meter:095]:       Unit of Measurement: 'A'
[19:16:16][C][sdm_meter:095]:       Accuracy Decimals: 3
[19:16:16][C][sdm_meter:096]:     Active Power 'SDM630 Phase C Power'
[19:16:16][C][sdm_meter:096]:       Device Class: 'power'
[19:16:16][C][sdm_meter:096]:       State Class: 'measurement'
[19:16:16][C][sdm_meter:096]:       Unit of Measurement: 'W'
[19:16:16][C][sdm_meter:096]:       Accuracy Decimals: 2
[19:16:16][C][sdm_meter:097]:     Apparent Power 'SDM630 Phase C Apparent Power'
[19:16:16][C][sdm_meter:097]:       State Class: 'measurement'
[19:16:16][C][sdm_meter:097]:       Unit of Measurement: 'VA'
[19:16:16][C][sdm_meter:097]:       Accuracy Decimals: 2
[19:16:16][C][sdm_meter:098]:     Reactive Power 'SDM630 Phase C Reactive Power'
[19:16:16][C][sdm_meter:098]:       State Class: 'measurement'
[19:16:16][C][sdm_meter:098]:       Unit of Measurement: 'var'
[19:16:16][C][sdm_meter:098]:       Accuracy Decimals: 2
[19:16:16][C][sdm_meter:099]:     Power Factor 'SDM630 Phase C Power Factor'
[19:16:16][C][sdm_meter:099]:       Device Class: 'power_factor'
[19:16:16][C][sdm_meter:099]:       State Class: 'measurement'
[19:16:16][C][sdm_meter:099]:       Unit of Measurement: ''
[19:16:16][C][sdm_meter:099]:       Accuracy Decimals: 3
[19:16:16][C][sdm_meter:100]:     Phase Angle 'SDM630 Phase C Phase Angle'
[19:16:17][C][sdm_meter:100]:       State Class: ''
[19:16:17][C][sdm_meter:100]:       Unit of Measurement: 'Â°'
[19:16:17][C][sdm_meter:100]:       Accuracy Decimals: 3
[19:16:17][C][sdm_meter:100]:       Icon: 'mdi:flash'
[19:16:17][C][sdm_meter:102]:   Total Power 'SDM630 Total Power'
[19:16:17][C][sdm_meter:102]:     Device Class: 'power'
[19:16:17][C][sdm_meter:102]:     State Class: 'measurement'
[19:16:17][C][sdm_meter:102]:     Unit of Measurement: 'W'
[19:16:17][C][sdm_meter:102]:     Accuracy Decimals: 2
[19:16:17][C][sdm_meter:103]:   Frequency 'SDM630 Frequency'
[19:16:17][C][sdm_meter:103]:     State Class: 'measurement'
[19:16:17][C][sdm_meter:103]:     Unit of Measurement: 'Hz'
[19:16:17][C][sdm_meter:103]:     Accuracy Decimals: 3
[19:16:17][C][sdm_meter:103]:     Icon: 'mdi:current-ac'
[19:16:17][C][sdm_meter:104]:   Import Active Energy 'SDM630 Import Active Energy'
[19:16:17][C][sdm_meter:104]:     Device Class: 'energy'
[19:16:17][C][sdm_meter:104]:     State Class: 'total_increasing'
[19:16:17][C][sdm_meter:104]:     Unit of Measurement: 'kWh'
[19:16:17][C][sdm_meter:104]:     Accuracy Decimals: 2
[19:16:17][C][sdm_meter:105]:   Export Active Energy 'SDM630 Export Active Energy'
[19:16:17][C][sdm_meter:105]:     Device Class: 'energy'
[19:16:17][C][sdm_meter:105]:     State Class: 'total_increasing'
[19:16:17][C][sdm_meter:105]:     Unit of Measurement: 'kWh'
[19:16:17][C][sdm_meter:105]:     Accuracy Decimals: 2
[19:16:17][C][sdm_meter:106]:   Import Reactive Energy 'SDM630 Import Reactive Energy'
[19:16:17][C][sdm_meter:106]:     State Class: 'total_increasing'
[19:16:17][C][sdm_meter:106]:     Unit of Measurement: 'kVARh'
[19:16:17][C][sdm_meter:106]:     Accuracy Decimals: 2
[19:16:17][C][sdm_meter:107]:   Export Reactive Energy 'SDM630 Export Reactive Energy'
[19:16:17][C][sdm_meter:107]:     State Class: 'total_increasing'
[19:16:17][C][sdm_meter:107]:     Unit of Measurement: 'kVARh'
[19:16:17][C][sdm_meter:107]:     Accuracy Decimals: 2
[19:16:17][C][status:034]: Status Binary Sensor 'Status'
[19:16:17][C][status:034]:   Device Class: 'connectivity'
[19:16:17][C][restart.button:017]: Restart Button 'Reboot'
[19:16:17][C][restart.button:017]:   Icon: 'mdi:restart'
[19:16:17][C][captive_portal:089]: Captive Portal:
[19:16:17][C][sntp:042]: SNTP Time:
[19:16:17][C][sntp:045]:   Server 0: '0.pool.ntp.org'
[19:16:17][C][sntp:045]:   Server 1: '1.pool.ntp.org'
[19:16:17][C][sntp:045]:   Server 2: '2.pool.ntp.org'
[19:16:17][C][mdns:116]: mDNS:
[19:16:17][C][mdns:117]:   Hostname: utilhouse
[19:16:17][V][mdns:118]:   Services:
[19:16:17][V][mdns:120]:   - _esphomelib, _tcp, 6053
[19:16:17][V][mdns:122]:     TXT: friendly_name = Utilitymeter House
[19:16:17][V][mdns:122]:     TXT: version = 2024.12.2
[19:16:17][V][mdns:122]:     TXT: mac = 7c9ebdf31a34
[19:16:17][V][mdns:122]:     TXT: platform = ESP32
[19:16:17][V][mdns:122]:     TXT: board = esp32dev
[19:16:17][V][mdns:122]:     TXT: network = wifi
[19:16:17][V][mdns:122]:     TXT: api_encryption = Noise_NNpsk0_25519_ChaChaPoly_SHA256
[19:16:17][C][esphome.ota:073]: Over-The-Air updates:
[19:16:17][C][esphome.ota:074]:   Address: 192.168.1.12:3232
[19:16:17][C][esphome.ota:075]:   Version: 2
[19:16:17][C][esphome.ota:078]:   Password configured
[19:16:17][C][safe_mode:018]: Safe Mode:
[19:16:17][C][safe_mode:020]:   Boot considered successful after 60 seconds
[19:16:17][C][safe_mode:021]:   Invoke after 10 boot attempts
[19:16:17][C][safe_mode:023]:   Remain in safe mode for 300 seconds
[19:16:17][C][api:140]: API Server:
[19:16:17][C][api:141]:   Address: 192.168.1.12:6053
[19:16:17][C][api:143]:   Using noise encryption: YES
[19:16:17][C][wifi_signal.sensor:010]: WiFi Signal 'WiFi Signal'
[19:16:17][C][wifi_signal.sensor:010]:   Device Class: 'signal_strength'
[19:16:17][C][wifi_signal.sensor:010]:   State Class: 'measurement'
[19:16:17][C][wifi_signal.sensor:010]:   Unit of Measurement: 'dBm'
[19:16:17][C][wifi_signal.sensor:010]:   Accuracy Decimals: 0
[19:16:17][V][wifi_signal.sensor:010]:   Unique ID: '7c9ebdf31a34-wifisignal'
[19:16:24][V][modbus:218]: Modbus write: 01.04.00.00.00.50.F0.36 (8) at 17238
[19:16:24][D][uart_debug:114]: >>> 01:04:00:00:00:50:F0:36
[19:16:24][V][modbus:062]: Modbus received first Byte 0 (0X0) 21ms after last send
[19:16:24][W][modbus:153]: Modbus CRC Check failed! C071!=C200 00.00.00.00.C2 (5) 25ms after last send
[19:16:24][V][modbus:305]: Clearing buffer of 5 bytes - parse failed 38ms after last send
[19:16:24][V][modbus:062]: Modbus received first Byte 219 (0Xdb) 41ms after last send
[19:16:24][W][modbus:153]: Modbus CRC Check failed! 7660!=4645 DB.49.20.3F.7E.EA.67.00.00.00.00.C0.D6.3A.CC.00.00.00.00.42.48.28.A0.46.D5.E2.AD.3A.83.12.6F.44.CB.2C.21.45.46 (37) 56ms after last send
[19:16:24][V][modbus:305]: Clearing buffer of 37 bytes - parse failed 70ms after last send
[19:16:24][V][modbus:062]: Modbus received first Byte 161 (0Xa1) 83ms after last send
[19:16:24][W][component:237]: Component modbus took a long time for an operation (81 ms).
[19:16:24][W][component:238]: Components should block for at most 30 ms.
[19:16:24][V][modbus:305]: Clearing buffer of 5 bytes - timeout 101ms after last send
[19:16:24][D][uart_debug:114]: <<< 00:00:00:00:C2:DB:49:20:3F:7E:EA:67:00:00:00:00:C0:D6:3A:CC:00:00:00:00:42:48:28:A0:46:D5:E2:AD:3A:83:12:6F:44:CB:2C:21:45:46:A1:64:1A:D9:00
[19:16:24][V][modbus:037]: Stop waiting for response from 1 213ms after last send
[19:16:24][V][modbus:062]: Modbus received first Byte 0 (0X0) 235ms after last send
[19:16:24][W][modbus:153]: Modbus CRC Check failed! 9600!=43DB 00.01.04.A0.43.5E.44.DB.43 (9) 240ms after last send
[19:16:24][V][modbus:305]: Clearing buffer of 9 bytes - parse failed 253ms after last send
[19:16:24][V][modbus:062]: Modbus received first Byte 104 (0X68) 256ms after last send
[19:16:24][W][modbus:153]: Modbus CRC Check failed! F9E2!=6A43 68.C5.B3.43.6A (5) 270ms after last send
[19:16:24][V][modbus:305]: Clearing buffer of 5 bytes - parse failed 272ms after last send
[19:16:24][V][modbus:062]: Modbus received first Byte 31 (0X1f) 286ms after last send
[19:16:24][W][modbus:153]: Modbus CRC Check failed! 5612!=2378 1F.C6.40.78.23 (5) 288ms after last send
[19:16:24][V][modbus:305]: Clearing buffer of 5 bytes - parse failed 302ms after last send
[19:16:24][V][modbus:062]: Modbus received first Byte 104 (0X68) 304ms after last send
[19:16:24][W][modbus:153]: Modbus CRC Check failed! E035!=1C2 68.3F.3E.48.0C.3F.7C.05.38.44.50.0F.3A.43.2C.FD.C1.43.42.77.16.44.50.18.D1.43.2C.FD.C1.43.66.7C.0A.41.7C.59.56.00.00.00.00.C2.F7.70.2B.3F.7F.F4.52.3F.80.00.00.3F.57.FD.E2.3F.8A.77.6E.BF.79.43.4D.C2.01 (67) 324ms after last send
[19:16:24][V][modbus:305]: Clearing buffer of 67 bytes - parse failed 347ms after last send
[19:16:24][V][modbus:062]: Modbus received first Byte 222 (0Xde) 350ms after last send
[19:16:24][W][modbus:153]: Modbus CRC Check failed! FB05!=B865 DE.CF.43.65.B8 (5) 363ms after last send
[19:16:24][V][modbus:305]: Clearing buffer of 5 bytes - parse failed 365ms after last send
[19:16:24][V][modbus:062]: Modbus received first Byte 199 (0Xc7) 379ms after last send
[19:16:24][W][modbus:153]: Modbus CRC Check failed! 3DC0!=00 C7.00.00.00.00 (5) 381ms after last send
[19:16:24][V][modbus:305]: Clearing buffer of 5 bytes - parse failed 395ms after last send
[19:16:24][V][modbus:062]: Modbus received first Byte 63 (0X3f) 408ms after last send
[19:16:24][W][modbus:153]: Modbus CRC Check failed! 5C5!=4047 3F.F2.9D.47.40 (5) 411ms after last send
[19:16:24][V][modbus:305]: Clearing buffer of 5 bytes - parse failed 425ms after last send
[19:16:24][V][modbus:062]: Modbus received first Byte 181 (0Xb5) 427ms after last send
[19:16:24][W][modbus:153]: Modbus CRC Check failed! 31E7!=00 B5.F5.F5.00.00 (5) 441ms after last send
[19:16:24][V][modbus:305]: Clearing buffer of 5 bytes - parse failed 443ms after last send
[19:16:24][V][modbus:062]: Modbus received first Byte 0 (0X0) 457ms after last send
[19:16:24][W][component:237]: Component modbus took a long time for an operation (225 ms).
[19:16:24][W][component:238]: Components should block for at most 30 ms.
[19:16:24][V][modbus:305]: Clearing buffer of 14 bytes - timeout 476ms after last send
[19:16:24][D][uart_debug:114]: <<< 00:01:04:A0:43:5E:44:DB:43:68:C5:B3:43:6A:1F:C6:40:78:23:68:3F:3E:48:0C:3F:7C:05:38:44:50:0F:3A:43:2C:FD:C1:43:42:77:16:44:50:18:D1:43:2C:FD:C1:43:66:7C:0A:41:7C:59:56:00:00:00:00:C2:F7:70:2B:3F:7F:F4:52:3F:80:00:00:3F:57:FD:E2:3F:8A:77:6E:BF:79:43:4D:C2:01:DE:CF:43:65:B8:C7:00:00:00:00:3F:F2:9D:47:40:B5:F5:F5:00:00:00:00:44:95:F6:38:00:00:00:00:44:9A:7B:A2
[19:16:34][V][modbus:218]: Modbus write: 01.04.00.00.00.50.F0.36 (8) at 27238
[19:16:34][D][uart_debug:114]: >>> 01:04:00:00:00:50:F0:36
[19:16:34][V][modbus:062]: Modbus received first Byte 0 (0X0) 20ms after last send
[19:16:34][W][modbus:153]: Modbus CRC Check failed! C071!=C200 00.00.00.00.C2 (5) 23ms after last send
[19:16:34][V][modbus:305]: Clearing buffer of 5 bytes - parse failed 36ms after last send
[19:16:34][V][modbus:062]: Modbus received first Byte 215 (0Xd7) 40ms after last send
[19:16:34][W][modbus:153]: Modbus CRC Check failed! 688B!=7E3F D7.E5.00.3F.7E (5) 53ms after last send
[19:16:34][V][modbus:305]: Clearing buffer of 5 bytes - parse failed 55ms after last send
[19:16:34][V][modbus:062]: Modbus received first Byte 230 (0Xe6) 68ms after last send
[19:16:34][W][modbus:153]: Modbus CRC Check failed! 7D9!=00 E6.E3.00.00.00 (5) 70ms after last send
[19:16:34][V][modbus:305]: Clearing buffer of 5 bytes - parse failed 83ms after last send
[19:16:34][V][modbus:062]: Modbus received first Byte 0 (0X0) 96ms after last send
[19:16:34][W][modbus:153]: Modbus CRC Check failed! 5D60!=978D 00.C0.D3.8D.97 (5) 98ms after last send
[19:16:34][V][modbus:305]: Clearing buffer of 5 bytes - parse failed 111ms after last send
[19:16:34][V][modbus:062]: Modbus received first Byte 0 (0X0) 113ms after last send
[19:16:34][W][modbus:153]: Modbus CRC Check failed! C071!=4200 00.00.00.00.42 (5) 126ms after last send
[19:16:34][V][modbus:305]: Clearing buffer of 5 bytes - parse failed 128ms after last send
[19:16:34][W][modbus:153]: Modbus CRC Check failed! 5C0C!=40F1 3F.EF.80.F1.40 (5) 418ms after last send
[19:16:34][V][modbus:305]: Clearing buffer of 5 bytes - parse failed 433ms after last send
[19:16:34][V][modbus:062]: Modbus received first Byte 179 (0Xb3) 435ms after last send
[19:16:34][D][uart_debug:114]: <<< 00:00:00:00:C2:D7:E5:00:3F:7E:E6:E3:00:00:00:00:C0:D3:8D:97:00:00:00:00:42:47:F9:84:46:D5:E2:AE:3A:83:12:6F:44:CB:2C:21:45:46:A1:64:FA:50:00:00:01:04:A0:43:5E:DA:4C:43:68:E3:EF:43:69:47:AB:40:73:28:09:3F:3E:8C:B6:3F:7D:8A:F3:44:4C:DB:3B:43:2C:AE:21:43:43:62:EF:44:4C:E6:00:43:2C:AE:21:43:67:0A:70:41:84:D4:AA:00:00:00:00:C2:F6:9B:D7:3F:7F:F2:9F:3F:80:00:00:3F:58:7E:FA:3F:94:33:2B:BE:B2:A2:22:C2:01:06:DD:43:65:AC:A3:00:00:00:00:3F:EF:80:F1:40:B3:A0
[19:16:34][W][modbus:153]: Modbus CRC Check failed! 9039!=00 B3.A0.B5.00.00 (5) 507ms after last send
[19:16:34][V][modbus:305]: Clearing buffer of 5 bytes - parse failed 509ms after last send
[19:16:34][V][modbus:062]: Modbus received first Byte 0 (0X0) 521ms after last send
[19:16:34][W][component:237]: Component modbus took a long time for an operation (277 ms).
[19:16:34][W][component:238]: Components should block for at most 30 ms.
[19:16:34][V][modbus:305]: Clearing buffer of 14 bytes - timeout 540ms after last send
[19:16:34][D][uart_debug:114]: <<< B5:00:00:00:00:44:94:6F:BF:00:00:00:00:44:98:EA:12
[19:16:44][V][modbus:218]: Modbus write: 01.04.00.00.00.50.F0.36 (8) at 37233
[19:16:44][D][uart_debug:114]: >>> 01:04:00:00:00:50:F0:36
[19:16:44][V][modbus:062]: Modbus received first Byte 0 (0X0) 20ms after last send
[19:16:44][W][modbus:153]: Modbus CRC Check failed! C071!=C200 00.00.00.00.C2 (5) 24ms after last send
[19:16:44][V][modbus:305]: Clearing buffer of 5 bytes - parse failed 38ms after last send
[19:16:44][V][modbus:062]: Modbus received first Byte 213 (0Xd5) 40ms after last send
[19:16:44][V][modbus:305]: Clearing buffer of 42 bytes - timeout 74ms after last send
[19:16:44][D][uart_debug:114]: <<< 00:00:00:00:C2:D5:66:AC:3F:7E:F1:2F:00:00:00:00:C0:D7:B2:A5:00:00:00:00:42:47:FB:5F:46:D5:E2:B0:3A:83:12:6F:44:CB:2C:29:45:46:A1:68:A3:5C:00
[19:16:44][V][modbus:037]: Stop waiting for response from 1 204ms after last send
[19:16:44][V][modbus:062]: Modbus received first Byte 0 (0X0) 241ms after last send
[19:16:44][W][modbus:153]: Modbus CRC Check failed! C000!=435C 00.01.04.A0.43.5F.4C.5C.43 (9) 246ms after last send
[19:16:44][V][modbus:305]: Clearing buffer of 9 bytes - parse failed 259ms after last send
[19:16:44][V][modbus:062]: Modbus received first Byte 105 (0X69) 261ms after last send
[19:16:44][W][modbus:153]: Modbus CRC Check failed! 373F!=6943 69.D5.A5.43.69 (5) 277ms after last send
[19:16:44][V][modbus:305]: Clearing buffer of 5 bytes - parse failed 280ms after last send
[19:16:44][V][modbus:062]: Modbus received first Byte 241 (0Xf1) 293ms after last send
[19:16:44][W][modbus:153]: Modbus CRC Check failed! 934B!=4172 F1.99.40.72.41 (5) 296ms after last send
[19:16:44][V][modbus:305]: Clearing buffer of 5 bytes - parse failed 310ms after last send
[19:16:44][V][modbus:062]: Modbus received first Byte 117 (0X75) 312ms after last send
[19:16:44][W][modbus:153]: Modbus CRC Check failed! 6860!=C23D 75.3F.3D.F1.B3.3F.7D.B6.65.44.4C.BD.3F.43.2D.7F.6F.43.44.42.59.44.4C.CA.CF.43.2D.7F.6F.43.67.DA.72.41.94.99.93.00.00.00.00.C2.F6.E3.10.3F.7F.EF.45.3F.80.00.00.3F.58.B4.27.3F.A5.BB.4A.BD.C6.7E.3D.C2 (66) 330ms after last send
[19:16:44][V][modbus:305]: Clearing buffer of 66 bytes - parse failed 353ms after last send
[19:16:44][V][modbus:062]: Modbus received first Byte 0 (0X0) 356ms after last send
[19:16:44][W][modbus:153]: Modbus CRC Check failed! F50C!=6643 00.AD.8C.43.66 (5) 370ms after last send
[19:16:44][V][modbus:305]: Clearing buffer of 5 bytes - parse failed 372ms after last send
[19:16:44][V][modbus:062]: Modbus received first Byte 91 (0X5b) 386ms after last send
[19:16:44][W][modbus:153]: Modbus CRC Check failed! 2358!=00 5B.DF.00.00.00 (5) 388ms after last send
[19:16:44][V][modbus:305]: Clearing buffer of 5 bytes - parse failed 402ms after last send
[19:16:44][V][modbus:062]: Modbus received first Byte 0 (0X0) 404ms after last send
[19:16:44][W][component:237]: Component modbus took a long time for an operation (178 ms).
[19:16:44][W][component:238]: Components should block for at most 30 ms.
[19:16:44][V][modbus:305]: Clearing buffer of 25 bytes - timeout 435ms after last send
[19:16:44][D][uart_debug:114]: <<< 00:01:04:A0:43:5F:4C:5C:43:69:D5:A5:43:69:F1:99:40:72:41:75:3F:3D:F1:B3:3F:7D:B6:65:44:4C:BD:3F:43:2D:7F:6F:43:44:42:59:44:4C:CA:CF:43:2D:7F:6F:43:67:DA:72:41:94:99:93:00:00:00:00:C2:F6:E3:10:3F:7F:EF:45:3F:80:00:00:3F:58:B4:27:3F:A5:BB:4A:BD:C6:7E:3D:C2:00:AD:8C:43:66:5B:DF:00:00:00:00:3F:EF:1C:04:40:B3:55:03:00:00:00:00:44:94:A7:FB:00:00:00:00:44:99:1A:59
[19:16:49][V][sensor:043]: 'WiFi Signal': Received new state -70.000000
[19:16:49][D][sensor:094]: 'WiFi Signal': Sending state -70.00000 dBm with 0 decimals of accuracy
[19:16:54][V][modbus:218]: Modbus write: 01.04.00.00.00.50.F0.36 (8) at 47230
[19:16:54][D][uart_debug:114]: >>> 01:04:00:00:00:50:F0:36
[19:16:54][V][modbus:062]: Modbus received first Byte 0 (0X0) 21ms after last send
[19:16:54][W][modbus:153]: Modbus CRC Check failed! C071!=C200 00.00.00.00.C2 (5) 25ms after last send
[19:16:54][V][modbus:305]: Clearing buffer of 5 bytes - parse failed 38ms after last send
[19:16:54][V][modbus:062]: Modbus received first Byte 216 (0Xd8) 41ms after last send
[19:16:54][W][component:237]: Component modbus took a long time for an operation (51 ms).
[19:16:54][W][component:238]: Components should block for at most 30 ms.
[19:16:54][V][modbus:305]: Clearing buffer of 42 bytes - timeout 72ms after last send
[19:16:54][D][uart_debug:114]: <<< 00:00:00:00:C2:D8:53:DE:3F:7E:E9:8F:00:00:00:00:C0:D6:BD:05:00:00:00:00:42:48:04:2F:46:D5:E2:B1:3A:83:12:6F:44:CB:2C:29:45:46:A1:68:93:95:00
[19:16:54][V][modbus:037]: Stop waiting for response from 1 202ms after last send
[19:16:54][V][modbus:062]: Modbus received first Byte 0 (0X0) 233ms after last send
[19:16:54][W][modbus:153]: Modbus CRC Check failed! 4801!=43A4 00.01.04.A0.43.5F.AC.A4.43 (9) 238ms after last send
[19:16:54][V][modbus:305]: Clearing buffer of 9 bytes - parse failed 250ms after last send
[19:16:54][V][modbus:062]: Modbus received first Byte 103 (0X67) 252ms after last send
[19:16:54][W][modbus:153]: Modbus CRC Check failed! F77B!=6943 67.A6.E1.43.69 (5) 265ms after last send
[19:16:54][V][modbus:305]: Clearing buffer of 5 bytes - parse failed 268ms after last send
[19:16:54][D][uart_debug:114]: <<< 00:01:04:A0:43:5F:AC:A4:43:67:A6:E1:43:69:76:E3:40:C0:83:17:40:EA:33:46:40:A7:95:BC:44:A2:92:23:44:D0:D7:2B:44:97:71:3A:44:A5:C4:A0:44:D3:B4:3D:44:98:35:D5:C3:81:99:06:43:8A:CF:23:C2:F4:55:F4:3F:7B:10:79:3F:7C:89:A9:3F:7E:B5:8B:C1:34:51:C1:41:16:F3:D8:C0:B8:36:6B:43:65:98:CD:00:00:00:00:40:C5:B7:64:41:94:49:8B:00:00:00:00:45:82:B6:A2:00:00:00:00:45:84:6B:AD
[19:16:54][V][modbus:305]: Clearing buffer of 101 bytes - timeout 480ms after last send
[19:16:59][D][dallas.temp.sensor:054]: 'Temp': Got Temperature=27.6Â°C
[19:16:59][V][sensor:043]: 'Temp': Received new state 27.562500
[19:16:59][D][sensor:094]: 'Temp': Sending state 27.56250 Â°C with 1 decimals of accuracy
[19:17:04][V][modbus:218]: Modbus write: 01.04.00.00.00.50.F0.36 (8) at 57232
[19:17:04][D][uart_debug:114]: >>> 01:04:00:00:00:50:F0:36
[19:17:04][V][modbus:062]: Modbus received first Byte 0 (0X0) 19ms after last send
[19:17:04][W][modbus:153]: Modbus CRC Check failed! C071!=C200 00.00.00.00.C2 (5) 22ms after last send
[19:17:04][V][modbus:305]: Clearing buffer of 5 bytes - parse failed 35ms after last send
[19:17:04][V][modbus:062]: Modbus received first Byte 207 (0Xcf) 37ms after last send
[19:17:04][V][modbus:305]: Clearing buffer of 42 bytes - timeout 68ms after last send
[19:17:04][V][sensor:043]: 'Uptime': Received new state 57.355999
[19:17:04][D][sensor:094]: 'Uptime': Sending state 0.00000 h with 0 decimals of accuracy
[19:17:04][D][uart_debug:114]: <<< 00:00:00:00:C2:CF:7D:81:3F:7F:EC:66:00:00:00:00:C1:0F:21:1D:00:00:00:00:42:48:06:A9:46:D5:E2:B6:3A:83:12:6F:44:CB:2C:29:45:46:A1:68:73:26:00
[19:17:04][V][modbus:037]: Stop waiting for response from 1 215ms after last send
[19:17:04][V][modbus:062]: Modbus received first Byte 0 (0X0) 236ms after last send
[19:17:04][W][modbus:153]: Modbus CRC Check failed! 3151!=4337 00.01.04.A0.43.60.4F.37.43 (9) 241ms after last send
[19:17:04][V][modbus:305]: Clearing buffer of 9 bytes - parse failed 254ms after last send
[19:17:04][V][modbus:062]: Modbus received first Byte 102 (0X66) 256ms after last send
[19:17:04][W][modbus:153]: Modbus CRC Check failed! 9BF3!=6943 66.87.B0.43.69 (5) 269ms after last send
[19:17:04][V][modbus:305]: Clearing buffer of 5 bytes - parse failed 271ms after last send
[19:17:04][V][modbus:062]: Modbus received first Byte 76 (0X4c) 284ms after last send
[19:17:04][W][modbus:153]: Modbus CRC Check failed! 2510!=D716 4C.11.40.BF.13.F9.40.E9.51.D5.40.A7.D2.90.44.A2.29.10.44.CF.32.75.44.97.B4.35.44.A5.4B.CB.44.D2.0F.DF.44.98.7B.45.C3.80.2C.00.43.8A.4C.72.C2.F6.12.C4.3F.7B.25.70.3F.7C.82.47.3F.7E.B3.26.C1.31.5B.CB.41.16.D7 (69) 301ms after last send
[19:17:04][V][modbus:305]: Clearing buffer of 69 bytes - parse failed 324ms after last send
[19:17:04][V][modbus:062]: Modbus received first Byte 217 (0Xd9) 326ms after last send
[19:17:04][W][modbus:153]: Modbus CRC Check failed! 49F0!=23E1 D9.C0.B8.E1.23 (5) 340ms after last send
[19:17:04][V][modbus:305]: Clearing buffer of 5 bytes - parse failed 352ms after last send
[19:17:04][V][modbus:062]: Modbus received first Byte 67 (0X43) 354ms after last send
[19:17:04][W][component:237]: Component modbus took a long time for an operation (133 ms).
[19:17:04][W][component:238]: Components should block for at most 30 ms.
[19:17:04][V][modbus:305]: Clearing buffer of 32 bytes - timeout 384ms after last send
[19:17:07][I][safe_mode:041]: Boot seems successful; resetting boot loop counter
[19:17:07][D][esp32.preferences:114]: Saving 1 preferences to flash...
[19:17:07][V][esp32.preferences:126]: sync: key: 233825507, len: 4
[19:17:07][D][esp32.preferences:143]: Saving 1 preferences to flash: 0 cached, 1 written, 0 failed
[19:17:14][V][modbus:218]: Modbus write: 01.04.00.00.00.50.F0.36 (8) at 67234
[19:17:14][D][uart_debug:114]: >>> 01:04:00:00:00:50:F0:36
[19:17:14][V][modbus:062]: Modbus received first Byte 0 (0X0) 19ms after last send
[19:17:14][W][modbus:153]: Modbus CRC Check failed! C071!=C200 00.00.00.00.C2 (5) 23ms after last send
[19:17:14][V][modbus:305]: Clearing buffer of 5 bytes - parse failed 37ms after last send
[19:17:14][V][modbus:062]: Modbus received first Byte 204 (0Xcc) 39ms after last send
[19:17:14][W][component:237]: Component modbus took a long time for an operation (51 ms).
[19:17:14][W][component:238]: Components should block for at most 30 ms.
[19:17:14][V][modbus:305]: Clearing buffer of 42 bytes - timeout 72ms after last send
[19:17:14][D][uart_debug:114]: <<< 00:00:00:00:C2:CC:2C:32:3F:7F:EC:E7:00:00:00:00:C1:0E:41:B8:00:00:00:00:42:47:E8:F5:46:D5:E2:BC:3A:83:12:6F:44:CB:2C:31:45:46:A1:71:1B:DD:00
[19:17:14][V][modbus:037]: Stop waiting for response from 1 201ms after last send
[19:17:14][V][modbus:062]: Modbus received first Byte 0 (0X0) 233ms after last send
[19:17:14][W][modbus:153]: Modbus CRC Check failed! 11D1!=4322 00.01.04.A0.43.60.31.22.43 (9) 238ms after last send
[19:17:14][V][modbus:305]: Clearing buffer of 9 bytes - parse failed 251ms after last send
[19:17:14][V][modbus:062]: Modbus received first Byte 104 (0X68) 254ms after last send
[19:17:14][W][modbus:153]: Modbus CRC Check failed! 3FF2!=3F00 68.17.3B.43.69.E2.C5.40.73.99.80.40.A2.F2.67.40.A7.A9.E7.44.4E.D2.14.44.93.8C.D9.44.97.F6.4F.44.4E.E4.59.44.93.8C.D9.44.98.BE.E8.41.AD.8E.37.00.00.00.00.C2.F7.3B.16.3F.7F.E9.9B.3F.80.00.00.3F (64) 272ms after last send
[19:17:14][V][modbus:305]: Clearing buffer of 64 bytes - parse failed 295ms after last send
[19:17:14][V][modbus:062]: Modbus received first Byte 126 (0X7e) 297ms after last send
[19:17:14][W][modbus:153]: Modbus CRC Check failed! C3A5!=BF3F 7E.B0.25.3F.BF (5) 311ms after last send
[19:17:14][V][modbus:305]: Clearing buffer of 5 bytes - parse failed 313ms after last send
[19:17:14][V][modbus:062]: Modbus received first Byte 190 (0Xbe) 327ms after last send
[19:17:14][W][modbus:153]: Modbus CRC Check failed! 35B3!=9CB0 BE.84.3D.B0.9C (5) 330ms after last send
[19:17:14][V][modbus:305]: Clearing buffer of 5 bytes - parse failed 343ms after last send
[19:17:14][V][modbus:062]: Modbus received first Byte 75 (0X4b) 345ms after last send
[19:17:14][W][modbus:153]: Modbus CRC Check failed! 6490!=63B6 4B.C0.B9.B6.63 (5) 359ms after last send
[19:17:14][V][modbus:305]: Clearing buffer of 5 bytes - parse failed 373ms after last send
[19:17:14][V][modbus:062]: Modbus received first Byte 67 (0X43) 375ms after last send
[19:17:14][W][component:237]: Component modbus took a long time for an operation (157 ms).
[19:17:14][W][component:238]: Components should block for at most 30 ms.
[19:17:14][V][modbus:305]: Clearing buffer of 32 bytes - timeout 406ms after last send
[19:17:14][D][uart_debug:114]: <<< 00:01:04:A0:43:60:31:22:43:68:17:3B:43:69:E2:C5:40:73:99:80:40:A2:F2:67:40:A7:A9:E7:44:4E:D2:14:44:93:8C:D9:44:97:F6:4F:44:4E:E4:59:44:93:8C:D9:44:98:BE:E8:41:AD:8E:37:00:00:00:00:C2:F7:3B:16:3F:7F:E9:9B:3F:80:00:00:3F:7E:B0:25:3F:BF:BE:84:3D:B0:9C:4B:C0:B9:B6:63:43:66:0E:61:00:00:00:00:40:96:8F:B2:41:61:D7:8B:00:00:00:00:45:49:76:19:00:00:00:00:45:49:DE:F7

```

**Comment by exciton** [comment]
That extra 0x00 byte at the beginning is really annoying. If it's within 3.5 characters of the actual response address then there's no way to filter it. Can you turn on very verbose logging? It may show how far apart those bytes are.

Also testing again with default ESP-IDF will help.

**Comment by exciton** [comment]
It's also clear that the response message sometimes gets garbled in the default Arduino library. There are some bug fixes in subsequent versions that probably explain this.

**Comment by exciton** [comment]
@karllinder - I looked back to summarise your tests, and I think the telling thing is in the UART data:

1. ❌ Arduino 2.0.5 38400 baud, default send_wait (250), default turnaround (0). Nonsense UART repsonse: 00:00:00:00:C2:D0:F5:C8... 
2. ✅ Arduino **2.0.6** 38400 baud, default send_wait (250), default turnaround (0). 0x00 then correct response:  01:04:A0:43:5F:1F:5B:43...
3. ❌ Arduino 2.0.5 38400 baud, **send_wait 500ms,** **turnaround 800ms**. Nonsense UART repsonse: 00:00:00:00:C3:01:81:00:3F... 
4. ✅ Arduino **2.0.6** 9600 baud, send_wait 200ms, turnaround 200ms. 0x00 then correct response:  00:01:04:A0:43:60:5E:A0...
5. ❌ Arduino **2.0.5** 9600 baud, send_wait 200ms, turnaround 200ms. Nonsense UART response: 00:00:00:00:C2:6B:7F:97:3F...
6. ❌ ESP-IDF 5.1.5? 9600 baud, send_wait 200ms, turnaround 200ms. Nonsense UART response: 00:00:00:00:42:99:AC:67:3F...
7. ✅ Arduino **2.0.7** 9600 baud, send_wait 200ms, turnaround 200ms. 0x00 then correct response:  00:01:04:A0:43:63:D0:C9:43...
8. ❌ Arduino **2.0.5** 9600 baud, send_wait 200ms, turnaround 200ms. Nonsense UART response: 00:00:00:00:C2:6B:7F:97:3F...
9. ❌ Arduino **2.0.5** 9600 baud with setFIFOFull(1), send_wait 200ms, turnaround 200ms.  Nonsense UART response: 00:00:00:00:C2:D8:53...

In all cases with Arduino version 2.0.5 the UART response is nonsense (does not reflect what the hardware would return), which indicates there's a bug in the UART driver. I believe it's fixed in 2.0.6 onward.

So for your case you need the later Arduino library version.

However the modbus patch in this pull request is still beneficial in both cases

**Comment by exciton** [comment]
To summarise the test I ran on my system:

Here is the base configuration for the tests:

```yaml
esphome:
  name: water-system
  friendly_name: Water System

esp32:
  board: esp32dev
  framework:
    type: arduino

# Enable logging
logger:
  baud_rate: 0
  level: VERBOSE
  logs:
    modbus: VERBOSE
    modbus_controller: VERBOSE


external_components:
  - source: esphome/components
    components:
      - modbus

uart:
  tx_pin: 1
  rx_pin: 3
  baud_rate: 9600
  debug:


modbus:
  flow_control_pin: 4
  send_wait_time: 200ms
  turnaround_time: 100ms


# modbus_controller:
#  - address: 2
#    id: well_power_meter
#    update_interval: 1s 
#    #command_throttle: 200ms
#    max_cmd_retries: 0
#  - address: 3
#    id: pressure_power_meter
#    update_interval: 1s 
#    #command_throttle: 200ms
#    max_cmd_retries: 0
  



sensor:

  - platform: sdm_meter
    address: 2
    update_interval: 1s
    phase_a:
      current:
        name: "Well Pump Current"
      voltage:
        name: "Well Pump Voltage"
      power_factor: 
        name: "Well Pump Power Factor"
    frequency: 
      name: "Well Pump Frequency"
    total_power: 
      name: "Well Pump Total Power"
    import_active_energy: 
      name: "Well Pump Energy"
  - platform: sdm_meter
    address: 3
    update_interval: 1s
    phase_a:
      current:
        name: "Pressure Pump Current"
      voltage:
        name: "Pressure Pump Voltage"
      power_factor: 
        name: "Pressure Pump Power Factor"
    frequency: 
      name: "Pressure Pump Frequency"
    total_power: 
      name: "Pressure Pump Total Power"
    import_active_energy: 
      name: "Pressure Pump Energy"

  # - platform: modbus_controller
  #   modbus_controller_id: well_power_meter
  #   name: "Well Pump Voltage"
  #   address: 0x0000
  #   register_count: 2
  #   unit_of_measurement: "V"
  #   register_type: read
  #   value_type: FP32
  #   accuracy_decimals: 3
  #   device_class: voltage
  # - platform: modbus_controller
  #   modbus_controller_id: well_power_meter
  #   name: "Well Pump Current"
  #   address: 0x0006
  #   register_count: 100
  #   unit_of_measurement: "A"
  #   register_type: read
  #   value_type: FP32
  #   accuracy_decimals: 3
  #   device_class: current
  # - platform: modbus_controller
  #   modbus_controller_id: pressure_power_meter
  #   name: "Pressure Pump Voltage"
  #   address: 0x0000
  #   register_count: 2
  #   unit_of_measurement: "V"
  #   register_type: read
  #   value_type: FP32
  #   accuracy_decimals: 3
  #   device_class: voltage
  # - platform: modbus_controller
  #   modbus_controller_id: pressure_power_meter
  #   name: "Pressure Pump Current"
  #   address: 0x0006
  #   register_count: 2
  #   unit_of_measurement: "A"
  #   register_type: read
  #   value_type: FP32
  #   accuracy_decimals: 3
  #   device_class: current
  # - platform: modbus_controller
  #   modbus_controller_id: pressure_power_meter
  #   name: "Pressure Pump Active Power"
  #   address: 0x000C
  #   register_count: 2
  #   unit_of_measurement: "W"
  #   register_type: read
  #   value_type: FP32
  #   accuracy_decimals: 3
  #   device_class: power
  # - platform: modbus_controller
  #   modbus_controller_id: pressure_power_meter
  #   name: "Pressure Pump Aparent Power"
  #   address: 0x0012
  #   register_count: 2
  #   unit_of_measurement: "W"
  #   register_type: read
  #   value_type: FP32
  #   accuracy_decimals: 3
  #   device_class: power

 ```
The following changes were tested in different combinations:

- With pull request vs without pull request (standard)
- Arduino vs ESP-IDF
- sdm_meter x2 each polling at 1s intervals OR modbus_controller x2 polling a total of 5 registers at 1s intervals

All tests used:
- ESPHome 2024.12.2
- 9600 baud 8N1
- 200ms Send Wait Time
- 100ms Turnaround Time (when using pull request)
- 100ms Command Throttle in modbus_controller (when NOT using pull request)




Framework | Modbus | SDM Driver | Result
--- | --- | --- | ---
Arduino 2.0.5 | pull request | sdm_meter | ✅
Arduino 2.0.5 | standard | sdm_meter | ❌ Occasional modbus CRC errors (when both devices try to poll close together), modbus blocking (80ms)
Arduino 2.0.5 | pull request | modbus_controller | ✅
Arduino 2.0.5 | standard | modbus_controller | ❌ Frequent CRC errors, Device offline intermittently
Arduino 2.0.6 | pull request | sdm_meter | 🟠 Modbus blocking (59ms)
Arduino 2.0.6 | standard | sdm_meter | ❌ Frequent modbus CRC errors, modbus blocking (80ms)
Arduino 2.0.6 | pull request | modbus_controller | ✅
Arduino 2.0.6 | standard | modbus_controller | ❌ Frequent CRC errors, Device offline intermittently
ESP-IDF 5.1.5 | pull request | sdm_meter | ✅
ESP-IDF 5.1.5 | standard | sdm_meter | ❌ Frequent modbus CRC errors, modbus blocking (70ms)
ESP-IDF 5.1.5 | pull request | modbus_controller | ✅
ESP-IDF 5.1.5 | standard | modbus_controller | ❌ Frequent CRC errors, Device offline intermittently

Full logs of these tests are here:
[Arduino 2.0.5 pull request modbus_controller.txt](https://github.com/user-attachments/files/18371347/Arduino.2.0.5.pull.request.modbus_controller.txt)
[Arduino 2.0.5 pull request sdm_meter.txt](https://github.com/user-attachments/files/18371349/Arduino.2.0.5.pull.request.sdm_meter.txt)
[Arduino 2.0.5 standard modbus_controller.txt](https://github.com/user-attachments/files/18371350/Arduino.2.0.5.standard.modbus_controller.txt)
[Arduino 2.0.5 upstream sdm_meter.txt](https://github.com/user-attachments/files/18371351/Arduino.2.0.5.upstream.sdm_meter.txt)
[Arduino 2.0.6 pull request modbus_controller.txt](https://github.com/user-attachments/files/18371352/Arduino.2.0.6.pull.request.modbus_controller.txt)
[Arduino 2.0.6 pull request sdm_meter.txt](https://github.com/user-attachments/files/18371353/Arduino.2.0.6.pull.request.sdm_meter.txt)
[Arduino 2.0.6 standard modbus_controller.txt](https://github.com/user-attachments/files/18371354/Arduino.2.0.6.standard.modbus_controller.txt)
[Arduino 2.0.6 standard sdm_meter.txt](https://github.com/user-attachments/files/18371355/Arduino.2.0.6.standard.sdm_meter.txt)
[ESP-IDF 5.1.5 pull request modbus_controller.txt](https://github.com/user-attachments/files/18371356/ESP-IDF.5.1.5.pull.request.modbus_controller.txt)
[ESP-IDF 5.1.5 pull request sdm_meter.txt](https://github.com/user-attachments/files/18371357/ESP-IDF.5.1.5.pull.request.sdm_meter.txt)
[ESP-IDF 5.1.5 standard modbus_controller.txt](https://github.com/user-attachments/files/18371358/ESP-IDF.5.1.5.standard.modbus_controller.txt)
[ESP-IDF 5.1.5 standard sdm_meter.txt](https://github.com/user-attachments/files/18371359/ESP-IDF.5.1.5.standard.sdm_meter.txt)

Summary: This pull request significantly improves functionality both of well-behaved modbus components (like modbus_controller_) and misbehaving modbus components (like sdm_meter which doesn't even check to see if the line is free before sending), especially when there is contention for the line (multiple devices) and when there is a high data rate (requests scheduled faster than the bus can handle). Works for both Arduino (regardless of version) and ESP-IDF.

**Comment by exciton** [comment]
@jesserockz - Maybe you want to take a look at this?

**Comment by karllinder** [comment]
Hi
I have very good news:

With IDF recommended version I now se no error! 

Can confirm that 2.0.6 and IDF is working with this fix!

Very good work!

```
INFO ESPHome 2024.12.2
INFO Reading configuration /config/esphome/utility meter House.yaml...
INFO Detected timezone 'Europe/Stockholm'
WARNING GPIO5 is a strapping PIN and should only be used for I/O with care.
Attaching external pullup/down resistors to strapping pins can cause unexpected failures.
See https://esphome.io/guides/faq.html#why-am-i-getting-a-warning-about-strapping-pins
INFO Starting log output from 192.168.1.12 using esphome API
INFO Successfully connected to utilhouse @ 192.168.1.12 in 0.013s
INFO Successful handshake with utilhouse @ 192.168.1.12 in 0.243s
[08:05:46][I][app:100]: ESPHome version 2024.12.2 compiled on Jan  9 2025, 14:08:54
[08:05:46][C][status_led:019]: Status LED:
[08:05:46][C][status_led:020]:   Pin: GPIO25
[08:05:46][C][wifi:600]: WiFi:
[08:05:46][C][wifi:428]:   Local MAC: 7C:9E:BD:F3:1A:34
[08:05:46][C][wifi:433]:   SSID: [redacted]
[08:05:46][C][wifi:436]:   IP Address: 192.168.1.12
[08:05:46][C][wifi:439]:   BSSID: [redacted]
[08:05:46][C][wifi:441]:   Hostname: 'utilhouse'
[08:05:46][C][wifi:443]:   Signal strength: -72 dB ▂▄▆█
[08:05:46][C][wifi:447]:   Channel: 6
[08:05:46][C][wifi:448]:   Subnet: 255.255.255.0
[08:05:46][C][wifi:449]:   Gateway: 192.168.1.1
[08:05:46][C][wifi:450]:   DNS1: 8.8.8.8
[08:05:47][C][wifi:451]:   DNS2: 1.1.1.1
[08:05:47][C][logger:185]: Logger:
[08:05:47][C][logger:186]:   Level: DEBUG
[08:05:47][C][logger:188]:   Log Baud Rate: 115200
[08:05:47][C][logger:189]:   Hardware UART: UART0
[08:05:47][C][gpio.one_wire:020]: GPIO 1-wire bus:
[08:05:47][C][gpio.one_wire:021]:   Pin: GPIO32
[08:05:47][C][gpio.one_wire:080]:   Found devices:
[08:05:47][C][gpio.one_wire:082]:     0xa73c01f09514a628 (DS18B20)
[08:05:47][C][uart.idf:159]: UART Bus 1:
[08:05:47][C][uart.idf:160]:   TX Pin: GPIO17
[08:05:47][C][uart.idf:161]:   RX Pin: GPIO16
[08:05:47][C][uart.idf:163]:   RX Buffer Size: 256
[08:05:47][C][uart.idf:165]:   Baud Rate: 9600 baud
[08:05:47][C][uart.idf:166]:   Data Bits: 8
[08:05:47][C][uart.idf:167]:   Parity: NONE
[08:05:47][C][uart.idf:168]:   Stop bits: 1
[08:05:47][C][modbus:238]: Modbus:
[08:05:47][C][modbus:239]:   Flow Control Pin: GPIO5
[08:05:47][C][modbus:240]:   Send Wait Time: 200 ms
[08:05:47][C][modbus:241]:   Turnaround Time: 200 ms
[08:05:47][C][modbus:242]:   Frame Delay: 5 ms
[08:05:47][C][modbus:243]:   CRC Disabled: NO
[08:05:47][C][uptime.sensor:033]: Uptime Sensor 'Uptime'
[08:05:47][C][uptime.sensor:033]:   Device Class: 'duration'
[08:05:47][C][uptime.sensor:033]:   State Class: 'total_increasing'
[08:05:47][C][uptime.sensor:033]:   Unit of Measurement: 'h'
[08:05:47][C][uptime.sensor:033]:   Accuracy Decimals: 0
[08:05:47][C][uptime.sensor:033]:   Icon: 'mdi:timer-outline'
[08:05:47][C][uptime.sensor:034]:   Type: Seconds
[08:05:47][C][dallas.temp.sensor:029]: Dallas Temperature Sensor:
[08:05:47][C][dallas.temp.sensor:034]:   Address: 0xa73c01f09514a628 (DS18B20)
[08:05:47][C][dallas.temp.sensor:035]:   Resolution: 12 bits
[08:05:47][C][dallas.temp.sensor:036]:   Update Interval: 60.0s
[08:05:47][C][sdm_meter:087]: SDM Meter:
[08:05:47][C][sdm_meter:088]:   Address: 0x01
[08:05:47][C][sdm_meter:093]:   Phase A
[08:05:47][C][sdm_meter:094]:     Voltage 'SDM630 Phase A Voltage'
[08:05:47][C][sdm_meter:094]:       Device Class: 'voltage'
[08:05:47][C][sdm_meter:094]:       State Class: 'measurement'
[08:05:47][C][sdm_meter:094]:       Unit of Measurement: 'V'
[08:05:47][C][sdm_meter:094]:       Accuracy Decimals: 2
[08:05:47][C][sdm_meter:095]:     Current 'SDM630 Phase A Current'
[08:05:47][C][sdm_meter:095]:       Device Class: 'current'
[08:05:47][C][sdm_meter:095]:       State Class: 'measurement'
[08:05:47][C][sdm_meter:095]:       Unit of Measurement: 'A'
[08:05:47][C][sdm_meter:095]:       Accuracy Decimals: 3
[08:05:47][C][sdm_meter:096]:     Active Power 'SDM630 Phase A Power'
[08:05:47][C][sdm_meter:096]:       Device Class: 'power'
[08:05:47][C][sdm_meter:096]:       State Class: 'measurement'
[08:05:47][C][sdm_meter:096]:       Unit of Measurement: 'W'
[08:05:47][C][sdm_meter:096]:       Accuracy Decimals: 2
[08:05:47][C][sdm_meter:097]:     Apparent Power 'SDM630 Phase A Apparent Power'
[08:05:47][C][sdm_meter:097]:       State Class: 'measurement'
[08:05:47][C][sdm_meter:097]:       Unit of Measurement: 'VA'
[08:05:47][C][sdm_meter:097]:       Accuracy Decimals: 2
[08:05:47][C][sdm_meter:098]:     Reactive Power 'SDM630 Phase A Reactive Power'
[08:05:47][C][sdm_meter:098]:       State Class: 'measurement'
[08:05:47][C][sdm_meter:098]:       Unit of Measurement: 'var'
[08:05:47][C][sdm_meter:098]:       Accuracy Decimals: 2
[08:05:47][C][sdm_meter:099]:     Power Factor 'SDM630 Phase A Power Factor'
[08:05:47][C][sdm_meter:099]:       Device Class: 'power_factor'
[08:05:47][C][sdm_meter:099]:       State Class: 'measurement'
[08:05:47][C][sdm_meter:099]:       Unit of Measurement: ''
[08:05:47][C][sdm_meter:099]:       Accuracy Decimals: 3
[08:05:47][C][sdm_meter:100]:     Phase Angle 'SDM630 Phase A Phase Angle'
[08:05:47][C][sdm_meter:100]:       State Class: ''
[08:05:47][C][sdm_meter:100]:       Unit of Measurement: '°'
[08:05:47][C][sdm_meter:100]:       Accuracy Decimals: 3
[08:05:47][C][sdm_meter:100]:       Icon: 'mdi:flash'
[08:05:47][C][sdm_meter:093]:   Phase B
[08:05:47][C][sdm_meter:094]:     Voltage 'SDM630 Phase B Voltage'
[08:05:47][C][sdm_meter:094]:       Device Class: 'voltage'
[08:05:47][C][sdm_meter:094]:       State Class: 'measurement'
[08:05:47][C][sdm_meter:094]:       Unit of Measurement: 'V'
[08:05:47][C][sdm_meter:094]:       Accuracy Decimals: 2
[08:05:47][C][sdm_meter:095]:     Current 'SDM630 Phase B Current'
[08:05:47][C][sdm_meter:095]:       Device Class: 'current'
[08:05:47][C][sdm_meter:095]:       State Class: 'measurement'
[08:05:47][C][sdm_meter:095]:       Unit of Measurement: 'A'
[08:05:47][C][sdm_meter:095]:       Accuracy Decimals: 3
[08:05:47][C][sdm_meter:096]:     Active Power 'SDM630 Phase B Power'
[08:05:47][C][sdm_meter:096]:       Device Class: 'power'
[08:05:47][C][sdm_meter:096]:       State Class: 'measurement'
[08:05:47][C][sdm_meter:096]:       Unit of Measurement: 'W'
[08:05:47][C][sdm_meter:096]:       Accuracy Decimals: 2
[08:05:47][C][sdm_meter:097]:     Apparent Power 'SDM630 Phase B Apparent Power'
[08:05:47][C][sdm_meter:097]:       State Class: 'measurement'
[08:05:47][C][sdm_meter:097]:       Unit of Measurement: 'VA'
[08:05:47][C][sdm_meter:097]:       Accuracy Decimals: 2
[08:05:47][C][sdm_meter:098]:     Reactive Power 'SDM630 Phase B Reactive Power'
[08:05:47][C][sdm_meter:098]:       State Class: 'measurement'
[08:05:47][C][sdm_meter:098]:       Unit of Measurement: 'var'
[08:05:47][C][sdm_meter:098]:       Accuracy Decimals: 2
[08:05:47][C][sdm_meter:099]:     Power Factor 'SDM630 Phase B Power Factor'
[08:05:47][C][sdm_meter:099]:       Device Class: 'power_factor'
[08:05:47][C][sdm_meter:099]:       State Class: 'measurement'
[08:05:47][C][sdm_meter:099]:       Unit of Measurement: ''
[08:05:47][C][sdm_meter:099]:       Accuracy Decimals: 3
[08:05:47][C][sdm_meter:100]:     Phase Angle 'SDM630 Phase B Phase Angle'
[08:05:47][C][sdm_meter:100]:       State Class: ''
[08:05:47][C][sdm_meter:100]:       Unit of Measurement: '°'
[08:05:47][C][sdm_meter:100]:       Accuracy Decimals: 3
[08:05:47][C][sdm_meter:100]:       Icon: 'mdi:flash'
[08:05:47][C][sdm_meter:093]:   Phase C
[08:05:47][C][sdm_meter:094]:     Voltage 'SDM630 Phase C Voltage'
[08:05:47][C][sdm_meter:094]:       Device Class: 'voltage'
[08:05:47][C][sdm_meter:094]:       State Class: 'measurement'
[08:05:47][C][sdm_meter:094]:       Unit of Measurement: 'V'
[08:05:47][C][sdm_meter:094]:       Accuracy Decimals: 2
[08:05:47][C][sdm_meter:095]:     Current 'SDM630 Phase C Current'
[08:05:47][C][sdm_meter:095]:       Device Class: 'current'
[08:05:47][C][sdm_meter:095]:       State Class: 'measurement'
[08:05:47][C][sdm_meter:095]:       Unit of Measurement: 'A'
[08:05:47][C][sdm_meter:095]:       Accuracy Decimals: 3
[08:05:47][C][sdm_meter:096]:     Active Power 'SDM630 Phase C Power'
[08:05:47][C][sdm_meter:096]:       Device Class: 'power'
[08:05:47][C][sdm_meter:096]:       State Class: 'measurement'
[08:05:47][C][sdm_meter:096]:       Unit of Measurement: 'W'
[08:05:47][C][sdm_meter:096]:       Accuracy Decimals: 2
[08:05:47][C][sdm_meter:097]:     Apparent Power 'SDM630 Phase C Apparent Power'
[08:05:47][C][sdm_meter:097]:       State Class: 'measurement'
[08:05:47][C][sdm_meter:097]:       Unit of Measurement: 'VA'
[08:05:47][C][sdm_meter:097]:       Accuracy Decimals: 2
[08:05:47][C][sdm_meter:098]:     Reactive Power 'SDM630 Phase C Reactive Power'
[08:05:47][C][sdm_meter:098]:       State Class: 'measurement'
[08:05:47][C][sdm_meter:098]:       Unit of Measurement: 'var'
[08:05:47][C][sdm_meter:098]:       Accuracy Decimals: 2
[08:05:47][C][sdm_meter:099]:     Power Factor 'SDM630 Phase C Power Factor'
[08:05:47][C][sdm_meter:099]:       Device Class: 'power_factor'
[08:05:47][C][sdm_meter:099]:       State Class: 'measurement'
[08:05:47][C][sdm_meter:099]:       Unit of Measurement: ''
[08:05:47][C][sdm_meter:099]:       Accuracy Decimals: 3
[08:05:47][C][sdm_meter:100]:     Phase Angle 'SDM630 Phase C Phase Angle'
[08:05:47][C][sdm_meter:100]:       State Class: ''
[08:05:47][C][sdm_meter:100]:       Unit of Measurement: '°'
[08:05:47][C][sdm_meter:100]:       Accuracy Decimals: 3
[08:05:47][C][sdm_meter:100]:       Icon: 'mdi:flash'
[08:05:47][C][sdm_meter:102]:   Total Power 'SDM630 Total Power'
[08:05:47][C][sdm_meter:102]:     Device Class: 'power'
[08:05:47][C][sdm_meter:102]:     State Class: 'measurement'
[08:05:47][C][sdm_meter:102]:     Unit of Measurement: 'W'
[08:05:47][C][sdm_meter:102]:     Accuracy Decimals: 2
[08:05:47][C][sdm_meter:103]:   Frequency 'SDM630 Frequency'
[08:05:47][C][sdm_meter:103]:     State Class: 'measurement'
[08:05:47][C][sdm_meter:103]:     Unit of Measurement: 'Hz'
[08:05:47][C][sdm_meter:103]:     Accuracy Decimals: 3
[08:05:47][C][sdm_meter:103]:     Icon: 'mdi:current-ac'
[08:05:47][C][sdm_meter:104]:   Import Active Energy 'SDM630 Import Active Energy'
[08:05:47][C][sdm_meter:104]:     Device Class: 'energy'
[08:05:47][C][sdm_meter:104]:     State Class: 'total_increasing'
[08:05:47][C][sdm_meter:104]:     Unit of Measurement: 'kWh'
[08:05:47][C][sdm_meter:104]:     Accuracy Decimals: 2
[08:05:47][C][sdm_meter:105]:   Export Active Energy 'SDM630 Export Active Energy'
[08:05:47][C][sdm_meter:105]:     Device Class: 'energy'
[08:05:47][C][sdm_meter:105]:     State Class: 'total_increasing'
[08:05:47][C][sdm_meter:105]:     Unit of Measurement: 'kWh'
[08:05:47][C][sdm_meter:105]:     Accuracy Decimals: 2
[08:05:47][C][sdm_meter:106]:   Import Reactive Energy 'SDM630 Import Reactive Energy'
[08:05:47][C][sdm_meter:106]:     State Class: 'total_increasing'
[08:05:47][C][sdm_meter:106]:     Unit of Measurement: 'kVARh'
[08:05:47][C][sdm_meter:106]:     Accuracy Decimals: 2
[08:05:47][C][sdm_meter:107]:   Export Reactive Energy 'SDM630 Export Reactive Energy'
[08:05:47][C][sdm_meter:107]:     State Class: 'total_increasing'
[08:05:47][C][sdm_meter:107]:     Unit of Measurement: 'kVARh'
[08:05:47][C][sdm_meter:107]:     Accuracy Decimals: 2
[08:05:47][C][status:034]: Status Binary Sensor 'Status'
[08:05:47][C][status:034]:   Device Class: 'connectivity'
[08:05:47][C][restart.button:017]: Restart Button 'Reboot'
[08:05:47][C][restart.button:017]:   Icon: 'mdi:restart'
[08:05:47][C][captive_portal:089]: Captive Portal:
[08:05:47][C][sntp:042]: SNTP Time:
[08:05:47][C][sntp:045]:   Server 0: '0.pool.ntp.org'
[08:05:47][C][sntp:045]:   Server 1: '1.pool.ntp.org'
[08:05:47][C][sntp:045]:   Server 2: '2.pool.ntp.org'
[08:05:47][C][mdns:116]: mDNS:
[08:05:47][C][mdns:117]:   Hostname: utilhouse
[08:05:47][C][esphome.ota:073]: Over-The-Air updates:
[08:05:47][C][esphome.ota:074]:   Address: 192.168.1.12:3232
[08:05:47][C][esphome.ota:075]:   Version: 2
[08:05:47][C][esphome.ota:078]:   Password configured
[08:05:47][C][safe_mode:018]: Safe Mode:
[08:05:47][C][safe_mode:019]:   Boot considered successful after 60 seconds
[08:05:47][C][safe_mode:021]:   Invoke after 10 boot attempts
[08:05:47][C][safe_mode:022]:   Remain in safe mode for 300 seconds
[08:05:47][C][api:140]: API Server:
[08:05:47][C][api:141]:   Address: 192.168.1.12:6053
[08:05:47][C][api:143]:   Using noise encryption: YES
[08:05:47][C][wifi_signal.sensor:010]: WiFi Signal 'WiFi Signal'
[08:05:47][C][wifi_signal.sensor:010]:   Device Class: 'signal_strength'
[08:05:48][C][wifi_signal.sensor:010]:   State Class: 'measurement'
[08:05:48][C][wifi_signal.sensor:010]:   Unit of Measurement: 'dBm'
[08:05:48][C][wifi_signal.sensor:010]:   Accuracy Decimals: 0
[08:05:56][D][uart_debug:114]: >>> 01:04:00:00:00:50:F0:36
[08:05:56][D][uart_debug:114]: <<< 00:01:04:A0:43:65:D2:4A:43:60:54:FA:43:62:D6:3B:40:39:57:F0:40:A0:E6:98:40:8F:0B:7F:44:21:9E:E6:44:8C:77:F5:44:7D:29:4B:44:21:9E:E8:44:8C:E2:9B:44:7D:55:A8:00:00:00:00:42:AD:38:E2:C2:15:E5:81:3F:80:00:00:3F:7F:3D:70:3F:7F:D3:AB:3D:0C:5B:14:40:8D:52:FD:C0:06:E4:A5:43:62:FF:2B:00:00:00:00:40:84:05:85:41:46:08:48:00:00:00:00:45:2D:DD:45:00:00:00:00:45:2E:1D:E5:00:00:00:00:42:46:67:FB:3F:7F:F5:7F:00:00:00:00:40:23:8E:F9:00:00:00:00:42:48:46:48:46:D6
[08:05:56][D][sdm_meter:039]: SDMMeter Phase A: V=229.821 V, I=2.896 A, Active P=646.483 W, Apparent P=646.483 VA, Reactive P=0.000 var, PF=1.000, PA=0.034 °
[08:05:56][D][sensor:093]: 'SDM630 Phase A Voltage': Sending state 229.82144 V with 2 decimals of accuracy
[08:05:56][D][sensor:093]: 'SDM630 Phase A Current': Sending state 2.89599 A with 3 decimals of accuracy
[08:05:56][D][sensor:093]: 'SDM630 Phase A Power': Sending state 646.48279 W with 2 decimals of accuracy
[08:05:56][D][sensor:093]: 'SDM630 Phase A Apparent Power': Sending state 646.48291 VA with 2 decimals of accuracy
[08:05:56][D][sensor:093]: 'SDM630 Phase A Reactive Power': Sending state 0.00000 var with 2 decimals of accuracy
[08:05:56][D][sensor:093]: 'SDM630 Phase A Power Factor': Sending state 1.00000  with 3 decimals of accuracy
[08:05:56][D][sensor:093]: 'SDM630 Phase A Phase Angle': Sending state 0.03427 ° with 3 decimals of accuracy
[08:05:56][D][sdm_meter:039]: SDMMeter Phase B: V=224.332 V, I=5.028 A, Active P=1123.749 W, Apparent P=1127.081 VA, Reactive P=86.611 var, PF=0.997, PA=4.416 °
[08:05:56][D][sensor:093]: 'SDM630 Phase B Voltage': Sending state 224.33194 V with 2 decimals of accuracy
[08:05:56][D][sensor:093]: 'SDM630 Phase B Current': Sending state 5.02815 A with 3 decimals of accuracy
[08:05:56][D][sensor:093]: 'SDM630 Phase B Power': Sending state 1123.74866 W with 2 decimals of accuracy
[08:05:56][D][sensor:093]: 'SDM630 Phase B Apparent Power': Sending state 1127.08142 VA with 2 decimals of accuracy
[08:05:56][D][sensor:093]: 'SDM630 Phase B Reactive Power': Sending state 86.61110 var with 2 decimals of accuracy
[08:05:56][D][sensor:093]: 'SDM630 Phase B Power Factor': Sending state 0.99703  with 3 decimals of accuracy
[08:05:56][D][sensor:093]: 'SDM630 Phase B Phase Angle': Sending state 4.41638 ° with 3 decimals of accuracy
[08:05:56][D][sdm_meter:039]: SDMMeter Phase C: V=226.837 V, I=4.470 A, Active P=1012.645 W, Apparent P=1013.338 VA, Reactive P=-37.474 var, PF=0.999, PA=-2.108 °
[08:05:56][D][sensor:093]: 'SDM630 Phase C Voltage': Sending state 226.83684 V with 2 decimals of accuracy
[08:05:56][D][sensor:093]: 'SDM630 Phase C Current': Sending state 4.47015 A with 3 decimals of accuracy
[08:05:56][D][sensor:093]: 'SDM630 Phase C Power': Sending state 1012.64520 W with 2 decimals of accuracy
[08:05:56][D][sensor:093]: 'SDM630 Phase C Apparent Power': Sending state 1013.33838 VA with 2 decimals of accuracy
[08:05:56][D][sensor:093]: 'SDM630 Phase C Reactive Power': Sending state -37.47412 var with 2 decimals of accuracy
[08:05:56][D][sensor:093]: 'SDM630 Phase C Power Factor': Sending state 0.99932  with 3 decimals of accuracy
[08:05:56][D][sensor:093]: 'SDM630 Phase C Phase Angle': Sending state -2.10771 ° with 3 decimals of accuracy
[08:05:56][D][sdm_meter:067]: SDMMeter: F=50.069 Hz, Im.A.E=27457.645 Wh, Ex.A.E=0.001 Wh, Im.R.E=1629.578 VARh, Ex.R.E=3183.053 VARh, T.P=2781.829 W
[08:05:56][D][sensor:093]: 'SDM630 Total Power': Sending state 2781.82935 W with 2 decimals of accuracy
[08:05:56][D][sensor:093]: 'SDM630 Frequency': Sending state 50.06863 Hz with 3 decimals of accuracy
[08:05:56][D][sensor:093]: 'SDM630 Import Active Energy': Sending state 27457.64453 kWh with 2 decimals of accuracy
[08:05:56][D][sensor:093]: 'SDM630 Export Active Energy': Sending state 0.00100 kWh with 2 decimals of accuracy
[08:05:56][D][sensor:093]: 'SDM630 Import Reactive Energy': Sending state 1629.57800 kVARh with 2 decimals of accuracy
[08:05:56][D][sensor:093]: 'SDM630 Export Reactive Energy': Sending state 3183.05298 kVARh with 2 decimals of accuracy
[08:05:56][W][component:237]: Component modbus took a long time for an operation (308 ms).
[08:05:56][W][component:238]: Components should block for at most 30 ms.
[08:05:56][D][uart_debug:114]: <<< 83:4A:3A:83:12:6F:44:CB:B2:7F:45:46:F0:D9:11:74:00
[08:06:06][D][uart_debug:114]: >>> 01:04:00:00:00:50:F0:36
[08:06:06][D][uart_debug:114]: <<< 00:01:04:A0:43:66:32:23:43:61:5D:C7:43:63:89:E1:40:38:B5:7C:40:A1:81:12:40:8F:6F:2B:44:22:05:1E:44:8D:85:86:44:7E:A3:56:44:22:05:25:44:8D:F4:C2:44:7E:D0:77:00:00:00:00:42:B1:92:42:C2:17:9F:A1:3F:80:00:00:3F:7F:37:6B:3F:7F:D2:BB:3E:5A:31:41:40:8F:7E:B9:C0:08:50:29:43:63:B3:44:00:00:00:00:40:84:3F:53:41:46:5E:FC:00:00:00:00:45:2E:EC:E0:00:00:00:00:45:2F:16:58:00:00:00:00:42:4A:E3:A0:3F:7F:F3:1A:00:00:00:00:40:25:BC:D5:00:00:00:00:42:48:30:97:46:D6
[08:06:06][D][sdm_meter:039]: SDMMeter Phase A: V=230.196 V, I=2.886 A, Active P=648.080 W, Apparent P=648.080 VA, Reactive P=0.000 var, PF=1.000, PA=0.213 °
[08:06:06][D][sensor:093]: 'SDM630 Phase A Voltage': Sending state 230.19585 V with 2 decimals of accuracy
[08:06:06][D][sensor:093]: 'SDM630 Phase A Current': Sending state 2.88608 A with 3 decimals of accuracy
[08:06:06][D][sensor:093]: 'SDM630 Phase A Power': Sending state 648.07996 W with 2 decimals of accuracy
[08:06:06][D][sensor:093]: 'SDM630 Phase A Apparent Power': Sending state 648.08038 VA with 2 decimals of accuracy
[08:06:06][D][sensor:093]: 'SDM630 Phase A Reactive Power': Sending state 0.00000 var with 2 decimals of accuracy
[08:06:06][D][sensor:093]: 'SDM630 Phase A Power Factor': Sending state 1.00000  with 3 decimals of accuracy
[08:06:06][D][sensor:093]: 'SDM630 Phase A Phase Angle': Sending state 0.21308 ° with 3 decimals of accuracy
[08:06:06][D][sdm_meter:039]: SDMMeter Phase B: V=225.366 V, I=5.047 A, Active P=1132.173 W, Apparent P=1135.649 VA, Reactive P=88.786 var, PF=0.997, PA=4.484 °
[08:06:06][D][sensor:093]: 'SDM630 Phase B Voltage': Sending state 225.36632 V with 2 decimals of accuracy
[08:06:06][D][sensor:093]: 'SDM630 Phase B Current': Sending state 5.04701 A with 3 decimals of accuracy
[08:06:06][D][sensor:093]: 'SDM630 Phase B Power': Sending state 1132.17261 W with 2 decimals of accuracy
[08:06:06][D][sensor:093]: 'SDM630 Phase B Apparent Power': Sending state 1135.64868 VA with 2 decimals of accuracy
[08:06:06][D][sensor:093]: 'SDM630 Phase B Reactive Power': Sending state 88.78566 var with 2 decimals of accuracy
[08:06:06][D][sensor:093]: 'SDM630 Phase B Power Factor': Sending state 0.99694  with 3 decimals of accuracy
[08:06:06][D][sensor:093]: 'SDM630 Phase B Phase Angle': Sending state 4.48422 ° with 3 decimals of accuracy
[08:06:06][D][sdm_meter:039]: SDMMeter Phase C: V=227.539 V, I=4.482 A, Active P=1018.552 W, Apparent P=1019.257 VA, Reactive P=-37.906 var, PF=0.999, PA=-2.130 °
[08:06:06][D][sensor:093]: 'SDM630 Phase C Voltage': Sending state 227.53859 V with 2 decimals of accuracy
[08:06:06][D][sensor:093]: 'SDM630 Phase C Current': Sending state 4.48232 A with 3 decimals of accuracy
[08:06:06][D][sensor:093]: 'SDM630 Phase C Power': Sending state 1018.55212 W with 2 decimals of accuracy
[08:06:06][D][sensor:093]: 'SDM630 Phase C Apparent Power': Sending state 1019.25726 VA with 2 decimals of accuracy
[08:06:06][D][sensor:093]: 'SDM630 Phase C Reactive Power': Sending state -37.90589 var with 2 decimals of accuracy
[08:06:06][D][sensor:093]: 'SDM630 Phase C Power Factor': Sending state 0.99931  with 3 decimals of accuracy
[08:06:06][D][sensor:093]: 'SDM630 Phase C Phase Angle': Sending state -2.12989 ° with 3 decimals of accuracy
[08:06:06][D][sdm_meter:067]: SDMMeter: F=50.047 Hz, Im.A.E=27457.654 Wh, Ex.A.E=0.001 Wh, Im.R.E=1629.579 VARh, Ex.R.E=3183.053 VARh, T.P=2798.805 W
[08:06:06][D][sensor:093]: 'SDM630 Total Power': Sending state 2798.80469 W with 2 decimals of accuracy
[08:06:06][D][sensor:093]: 'SDM630 Frequency': Sending state 50.04745 Hz with 3 decimals of accuracy
[08:06:06][D][sensor:093]: 'SDM630 Import Active Energy': Sending state 27457.65430 kWh with 2 decimals of accuracy
[08:06:06][D][sensor:093]: 'SDM630 Export Active Energy': Sending state 0.00100 kWh with 2 decimals of accuracy
[08:06:06][D][sensor:093]: 'SDM630 Import Reactive Energy': Sending state 1629.57898 kVARh with 2 decimals of accuracy
[08:06:06][D][sensor:093]: 'SDM630 Export Reactive Energy': Sending state 3183.05298 kVARh with 2 decimals of accuracy
[08:06:06][W][component:237]: Component modbus took a long time for an operation (294 ms).
[08:06:06][W][component:238]: Components should block for at most 30 ms.
[08:06:06][D][uart_debug:114]: <<< 83:4F:3A:83:12:6F:44:CB:B2:87:45:46:F0:D9:DC:CD:00
```

**Comment by Sleeper85** [comment]
@exciton 

Congratulations for all this hard work.

I will test all this soon with my YamBMS project in multi-node modbus and in particular the behavior when a node no longer responds.

**Comment by SeByDocKy** [comment]
Can be tested also with IDF 4.4.8  ?

File: esphome/components/modbus/modbus.cpp (hunk 8 above)
Comment (jesserockz) [reply esphome/components/modbus/modbus.cpp]: Something like this would be better as a config option on uart. 
modbus could even require it to be set using `FINAL_VALIDATE_SCHEMA` to make sure the uart config includes the right setting.

File: esphome/components/modbus/modbus.cpp (hunk 6 above)
Comment (jesserockz) [reply esphome/components/modbus/modbus.cpp:76]: Want to add this as an actual inline comment for future reference and so the next person to come along doesn't have to decipher the condition?

File: esphome/components/modbus/modbus.cpp [hunk 9]
```diff
@@ -133,38 +168,78 @@ bool Modbus::parse_modbus_byte_(uint8_t byte) {
     if (device->address_ == address) {
       // Is it an error response?
       if ((function_code & 0x80) == 0x80) {
-        ESP_LOGD(TAG, "Modbus error function code: 0x%X exception: %d", function_code, raw[2]);
-        if (waiting_for_response != 0) {
-          device->on_modbus_error(function_code & 0x7F, raw[2]);
+        uint8_t exception = raw[2];
+        ESP_LOGD(TAG, "Modbus error function code: 0x%X exception: %d", function_code, exception);
+        if (waiting_for_response_ == address) {
+          set_timeout("on_modbus_error", 0, [device, function_code, exception]() {
```
Comment (jesserockz) [inline esphome/components/modbus/modbus.cpp]: > All uses of class members and member functions should be prefixed with `this->` to distinguish them from global functions/variables.

https://esphome.io/guides/contributing#codebase-standards
```suggestion
          this->set_timeout("on_modbus_error", 0, [device, function_code, exception]() {
```

We actually have another function for simply performing in the next loop:
```suggestion
          this->defer("on_modbus_error", [device, function_code, exception]() {
```
Internally its just set_timeout with a 0, but better for component code to use it instead.

**Review by jesserockz — DISMISSED** [review]

File: esphome/components/modbus/modbus.cpp [hunk 10]
```diff
@@ -133,38 +168,78 @@ bool Modbus::parse_modbus_byte_(uint8_t byte) {
...
+
+  if (this->role == ModbusRole::CLIENT) {
+    waiting_for_response_ = data[0];
+  }
+
+  if (this->flow_control_pin_ != nullptr)
+    this->flow_control_pin_->digital_write(true);
+
+  this->write_array(data);
+  this->flush();
```
Comment (brambo123) [inline esphome/components/modbus/modbus.cpp]: If flow_control_pin_ is not in use then flush() is only called to set last_send_ to the correct time?
Especially at lower baudrates I think that is not desirable.
A basic modbus request is 8 bytes long, which causes about 9ms blocking delay at 9600 bps.
Maybe last_send_ can just be calculated?

Please also take a look at #8103 which adds hardware flow control to the uart component, reducing the need for blocking software flow control.

**Comment by brambo123** [comment]
I looked closely at the FIFO full threshold.
Simply setting this to 1 is not a solution.
Data is copied during an interrupt, which can be done by the RX FIFO full interrupt, but also by the RX timeout interrupt.
In the Arduino framework the RX timeout is 2 (byte-times), on IDF its 10.
This 10 is a bit high, but most of the delay is just how often loop() is called.
The correct values ​​for FIFO full threshold depend largely on the baud rate.
At low baudrates (like <= 9600) it make sens to set the FIFO full threshold to 1.
At higher speeds it is better to rely on RX timeout.
A value of 2 is perfectly suitable for this.
Again, most of the delay is simply how often loop() is called.


There are much bigger problems in server mode.
The module simply cannot handle multiple devices on the same bus.
It does not know whether something is a request or a response, calculates CRC incorrectly and therefore throws away half packets.
Only when the bus is idle long enough is buffer is properly cleared and can it process a packet again.
It even gives "Got Modbus frame from unknown address" warnings, while modbus is simply multi point.


@karllinder
I find all those 00 values ​​you receive very strange.
Can you confirm that your RS485 bus termination and biasing is correct?

File: esphome/components/modbus/modbus.cpp (hunk 10 above)
Comment (exciton) [reply esphome/components/modbus/modbus.cpp]: This is technically correct, however it only makes a difference when a TX buffer is used in UART, which is not the default, and ESPHome provides no way to set it higher than 0. 

I agree moving the hardware flow control to the UART component makes sense.

**Comment by exciton** [comment]
> I looked closely at the FIFO full threshold. Simply setting this to 1 is not a solution. Data is copied during an interrupt, which can be done by the RX FIFO full interrupt, but also by the RX timeout interrupt. In the Arduino framework the RX timeout is 2 (byte-times), on IDF its 10. This 10 is a bit high, but most of the delay is just how often loop() is called. The correct values ​​for FIFO full threshold depend largely on the baud rate. At low baudrates (like <= 9600) it make sens to set the FIFO full threshold to 1. At higher speeds it is better to rely on RX timeout. A value of 2 is perfectly suitable for this. Again, most of the delay is simply how often loop() is called.

It's true that the RX timeout also triggers a data copy, but when the RX response is longer than the buffer then you get a partial response copied in the middle, followed by a long delay for the second half. The RX timeout only triggers after the response is complete and there's silence on the line. 
Agreed setting RX timeout to 2 makes sense in the case that RX FIFO Full is set higher than 1 (this is what the esp-modbus library does: https://github.com/espressif/esp-modbus).
Getting the timing right to segregate frames properly in a loop() component at high baud rates is basically impossible - if we want a high performance component we should use a library which does all the timing calculations using interrupts. 
I had an earlier implementation which adds a delay inside the component to wait for the buffer to fill - maybe this is the right option for high baud rates?

> 
> There are much bigger problems in server mode. The module simply cannot handle multiple devices on the same bus. It does not know whether something is a request or a response, calculates CRC incorrectly and therefore throws away half packets. Only when the bus is idle long enough is buffer is properly cleared and can it process a packet again. It even gives "Got Modbus frame from unknown address" warnings, while modbus is simply multi point.

Are you seeing CRC errors in server mode using this pull request? Do the same issues exist with upstream code? 

Agreed the "unknown address" errors make no sense in server mode. I'll adjust that.

> 
> @exciton I find all those 00 values ​​you receive very strange. Can you confirm that your RS485 bus termination and biasing is correct?

I don't see the 00 values on my hardware - this data is from @karllinder.

File: esphome/components/modbus/modbus.cpp (hunk 10 above)
Comment (brambo123) [reply esphome/components/modbus/modbus.cpp]: > This is technically correct, however it only makes a difference when a TX buffer is used in UART, which is not the default, and ESPHome provides no way to set it higher than 0.

Despite the fact that there is 0 in the code, there is a TX buffer active.
Maybe it's a software buffer that uses interrupts, I don't know exactly, but there really is a TX buffer.

I did the following test (with new hardware flow control from #8103):
```
uart:
  id: my_uart
  tx_pin: GPIO1
  rx_pin: GPIO3
  flow_control_pin: GPIO22
  parity: EVEN
  baud_rate: 9600

output:
  - platform: gpio
    pin: GPIO2
    id: led_1
    
interval:
  - interval: 5s
    then:
      - output.turn_on: led_1
      - uart.write: "test\r\n"
      - output.turn_off: led_1
```
This results in a very neat waveform:
image

Comment (exciton) [reply esphome/components/modbus/modbus.cpp]: I see. Perhaps we revisit this once the flow control in UART is merged?

**Comment by brambo123** [comment]
> It's true that the RX timeout also triggers a data copy, but when the RX response is longer than the buffer then you get a partial response copied in the middle, followed by a long delay for the second half. The RX timeout only triggers after the response is complete and there's silence on the line. Agreed setting RX timeout to 2 makes sense in the case that RX FIFO Full is set higher than 1 (this is what the esp-modbus library does: https://github.com/espressif/esp-modbus). 

The system should always use both trigger.
The FIFO full threshold is currently set to 120 I think. So with a long answer you should get data after 120 bytes.
If 20 more bytes come after that, they would be delivered by the RX timeout.
Only by setting RX timeout way too high can you get a half second delay.

> Getting the timing right to segregate frames properly in a loop() component at high baud rates is basically impossible - if we want a high performance component we should use a library which does all the timing calculations using interrupts. I had an earlier implementation which adds a delay inside the component to wait for the buffer to fill - maybe this is the right option for high baud rates?

Correct, that is actually impossible without a direct interrupt.
Using delay doesn't seem wise to me.
The most important thing seems to me the minimum time between packets.
If you really need modbus with such extreme performance that a little extra delay is a problem, then ESPhome is simply not the solution.

> Are you seeing CRC errors in server mode using this pull request? Do the same issues exist with upstream code?

Yes, and there is also a logical reason why these errors occur.
The code assumes that everything is a request.
For example, if you use function_code 3, the code always assumes that the data_len is 4.
But a response from another device can easily be much longer, but CRC is still calculated over data_len 4.
The CRC is then wrong, some data is thrown away, but then you are somewhere halfway through a data packet.
On a fast bus, and without interrupt control, it is almost impossible to determine the correct starting point of a packet again.

Edit:
If you request 1 register, the response is even 1 byte smaller than the request.
In that case, the first byte of the next request is added to the response.

> I don't see the 00 values on my hardware - this data is from @karllinder.

Sorry, I changed it.

File: esphome/components/modbus/modbus.cpp (hunk 10 above)
Comment (brambo123) [reply esphome/components/modbus/modbus.cpp]: > I see. Perhaps we revisit this once the flow control in UART is merged?

Hardware flow control is only available on ESP32, so software flow control must remain anyway.
Now that we are already improving the code, I think it would be smart to do this properly.

File: esphome/components/modbus/modbus.cpp [hunk 11]
```diff
@@ -133,38 +168,78 @@ bool Modbus::parse_modbus_byte_(uint8_t byte) {
...
+
+  if (this->flow_control_pin_ != nullptr)
+    this->flow_control_pin_->digital_write(false);
+
+  this->tx_buffer_.pop_front();
+
+  last_send_ = millis();
```
Comment (brambo123) [inline esphome/components/modbus/modbus.cpp]: I think this is enough to prevent unnecessary blocking:
```suggestion
  if (this->flow_control_pin_ != nullptr) {
    this->flush();
    this->flow_control_pin_->digital_write(false);
    last_send_ = millis();
  }
  else {
    last_send_ = millis() + (((10 * data.size() * 11 * 1000 / this->parent_->get_baud_rate()) + 5) / 10);
  }
  
  this->tx_buffer_.pop_front();
  
```
The ((10 * x) + 5) / 10) ensures rounding up ;)

File: esphome/components/modbus/modbus.cpp [hunk 12]
```diff
@@ -11,46 +13,77 @@ void Modbus::setup() {
   if (this->flow_control_pin_ != nullptr) {
     this->flow_control_pin_->setup();
   }
+  // 3.5 characters * 11 bits per character * 1000ms/sec / (bits/sec) (Standard modbus frame delay)
+  this->frame_delay_ms_ = (3.5 * 11 * 1000 / this->parent_->get_baud_rate()) + 1;
```
Comment (brambo123) [inline esphome/components/modbus/modbus.cpp]: Round up instead of adding 1 ms.
```suggestion
  this->frame_delay_ms_ = ((35 * 11 * 1000 / this->parent_->get_baud_rate()) + 5 ) / 10;
```

**Comment by exciton** [comment]
> > Are you seeing CRC errors in server mode using this pull request? Do the same issues exist with upstream code?
> 
> Yes, and there is also a logical reason why these errors occur. The code assumes that everything is a request. For example, if you use function_code 3, the code always assumes that the data_len is 4. But a response from another device can easily be much longer, but CRC is still calculated over data_len 4. The CRC is then wrong, some data is thrown away, but then you are somewhere halfway through a data packet. On a fast bus, and without interrupt control, it is almost impossible to determine the correct starting point of a packet again.

If there is an error in the CRC code we should definitely fix it. Perhaps open a fresh pull request just for that - it's largely independent of this issue, since it's not timing related.

File: esphome/components/modbus/modbus.cpp (hunk 8 above)
Comment (exciton) [reply esphome/components/modbus/modbus.cpp]: Agreed. Will need some help getting that done though. UART component is pretty central, and I can only test on a few platforms. 
Was thinking to pull in rx_full_threshold and rx_timeout at the same time, since they are both relevant here.

File: esphome/components/modbus/modbus.cpp (hunk 10 above)
Comment (exciton) [reply esphome/components/modbus/modbus.cpp]: Open to suggestions on this. When using software flow control flush is required, and even without it we need to know when TX is complete to be able to avoid sending again too soon.

File: esphome/components/modbus/modbus.cpp (hunk 8 above)
Comment (exciton) [reply esphome/components/modbus/modbus.cpp]: Also need to consider whether we want a global default for these values in UART or not (probably not). The default/automatic value for non-modbus situations probably shouldn't change. What's the conventional way to provide an option with no default value, and not set anything when the option isn't used?

Comment (exciton) [reply esphome/components/modbus/modbus.cpp]: Ok, this is implemented in the latest branch.

- Only implemented in ESP32 Arduino and ESP-IDF. Either need to implement in other platforms, provide a warning that it doesn't do anything, or remove the requirement for those platforms.

Comment (brambo123) [reply esphome/components/modbus/modbus.cpp]: You really shouldn't force rx_full_threshold (or even do anything with it).
You're trying to solve something that isn't a problem.
There is not half a second of delay anywhere.

At a baudrate of 115200, a rx_timeout of 2 is 190μs (or 0.19ms).
The loop() should run with 16ms intervals.
And we use timers with 1ms precision.
If you lower the rx_full_threshold to 1, every single byte becomes an interrupt.
The main code must be paused, the interrupt must be executed, the main code resumed.
So that will actually make it slower.
If you ar running at lower speeds, like 9600, it can help to lower rx_full_threshold (or rx_timeout) to 1.
Then you are talking about 1 to 2 ms differences, which still does not make a big difference considering the loop interval.
You really should leave it up to the user.
If you have a very low speed bus, like 2400 baud, then you can adjust rx_full_threshold and/or rx_timeout to impove performance.

Current hard coded default:
[Arduino rx_timeout: 2](https://github.com/espressif/arduino-esp32/blob/2.0.5/cores/esp32/HardwareSerial.cpp#L143)
[Arduino rx_full_threshold: 112](https://github.com/espressif/arduino-esp32/blob/2.0.5/cores/esp32/HardwareSerial.h#L109)
[ESP-IDF rx_timeout: 10](https://github.com/espressif/esp-idf/blob/v5.1.5/components/driver/uart/uart.c#L56)
[ESP-IDF rx_full_threshold: 120](https://github.com/espressif/esp-idf/blob/v5.1.5/components/driver/uart/uart.c#L55)

A option to change the rx_full_threshold and rx_timeout are inside #8103

Comment (jesserockz) [reply esphome/components/modbus/modbus.cpp]: Specific config options can be restricted to certain platforms: `cv.only_on_esp32` for example

File: esphome/components/uart/__init__.py [hunk 13]
```diff
@@ -301,7 +305,10 @@ async def to_code(config):
     cg.add(var.set_rx_buffer_size(config[CONF_RX_BUFFER_SIZE]))
     cg.add(var.set_stop_bits(config[CONF_STOP_BITS]))
     cg.add(var.set_data_bits(config[CONF_DATA_BITS]))
-    cg.add(var.set_parity(config[CONF_PARITY]))
```
Comment (brambo123) [inline esphome/components/uart/__init__.py:341]: I I really don't think it's a good idea to remove set_parity.

File: esphome/components/modbus/modbus.cpp (hunk 11 above)
Comment (exciton) [reply esphome/components/modbus/modbus.cpp]: Something like this could be used to avoid blocking, but the millis() + offset method won't work. 
If we later compare this value to millis() and less than offset ms have elapsed we'll get a negative number (which will wrap to a large positive number) and falsely tell us that we're past millis() + offset when we're not.

I'll propose an alternative that achieves the non-blocking behaviour.

File: esphome/components/modbus/modbus.cpp (hunk 8 above)
Comment (exciton) [reply esphome/components/modbus/modbus.cpp]: @brambo123 I agree there is more benefit of the rx_full_threshold change at lower baud rates, but your description isn't quite capturing the problem. 
In a situation where we have a long response (say 240 bytes) and we're at 9600 baud (roughly 1ms per baud) the following happens when we have rx_full_threshold set to 120:
1. available() is false for 120ms (while first 120 bytes are received into buffer)
2. suddenly 120 bytes are transferred, and available() is true while we copy them out
3. available() is false again for 120ms (while next 120 bytes are received into buffer)
4. suddenly 120 bytes are transferred and available is true again while we copy them

In order to know if the response frame has timed out we'd have to set a timeout that's at least 120ms long (when the spec calls a timeout after 3.5ms) otherwise we break the response in the middle (step 3) because it appears to have stopped. We also need to set our initial response timeout to be greater than 120ms to wait for the buffer to fill the first time.

I made an implementation that does this originally (see reversion of this here: https://github.com/esphome/esphome/pull/8032/commits/df776bd0bfa695dbb198ce9f179425f2d0187fa6), however it has issues:
* We need to guess how big the rx buffer is - and I don't see a way to extract this
* Setting a long timeout like this will miss real timeouts that occur

What we could do is provide a method to set rx_full_threshold (not require it), set it to the same defaults that currently exist in the libraries, and then read that value in to calculate an extended timeout. 
My current implementation of setting rx_full_threshold is not to set a default and allow the library to set its own default, which means we can't really know what value is in there.

For reference I think Arduino 2.0.5 is actually set to 120 as well (not 112), in a different part of the code. Later versions set it to 1 when baud is <= 9600.

Comment (exciton) [reply esphome/components/modbus/modbus.cpp]: Ok - code just pushed does exactly this. It will account for the rx_full_threshold that is set and increase the timeout accordingly.

Comment (brambo123) [reply esphome/components/modbus/modbus.cpp]: I was working on #8103 where the parameters are already included.
Maybe it's a good idea to not have the default for rx_full_threshold be a fixed value, but calculated to max 10ms for example.
I really don't assume that there is any component that depends on high values.
And maybe a verification option for components, also with ms.

**Comment by exciton** [comment]
@jesserockz - if you want to pull #8103 first, I can merge that in here to simplify (since it overlaps some).

**Comment by ximex** [comment]
the assigned milestone is wrong.

**Comment by patagonaa** [comment]
Please merge this and ideally set a good default for the `rx_full_threshold` (lower than common timeouts).

I just spent hours of my life staring at my logic analyzer and the modbus component code, wondering why it would send requests before the last response is received.

Turns out, of course, the receive timeout elapses because no bytes "arrive" (which would prevent the timeout from elapsing), allowing the next request to be sent.

**Comment by bigretromike** [comment]
Will this fix this issue: https://github.com/esphome/esphome/issues/10338 ?

**Comment by exciton** [comment]
Yes, I believe so.

**Comment by bigretromike** [comment]
@martgras @jesserockz @ximex is it good now ?

@kbx81 thanks for updating info

**Comment by kbx81** [comment]
> is it good now ?

We cannot merge until all conflicts are resolved (looks pretty out-of-date). Please merge in `dev`, fix conflicts & we'll revisit.

**Comment by patagonaa** [comment]
As #8103 (as far as I can tell) already does all the changes in the UART component done here (and more), as @exciton suggested it might make sense to merge that first and do the Modbus-specific changes of this PR on top of that.

**Comment by bigretromike** [comment]
@exciton you can do your magic, "magicman"

**Comment by exciton** [comment]
Yeah I can either merge in dev as-is (which duplicates changes in #8103), or wait til #8103 is merged and then rebuild this on top (will then not contain direct changes to UART component). 

@kbx81 - any preference?

**Comment by patagonaa** [comment]
TBH, as there hasn't been happening much with #8103 lately (and I'm kinda happier with your solution / defaults even), I'm fine with just merging this instead for now (but would still prefer if 8103 was merged first).
Only thing missing from this is HW-controlled flow control pins (which could be done as a separate PR) and unit tests.

I think some yaml unit tests with the added properties would be nice, but even without them I think this could / should be merged.

EDIT:
Docs should be updated for the new properties as well of course, maybe https://github.com/esphome/esphome-docs/pull/4592 could be used / adapted.

**Comment by kbx81** [comment]
> Yeah I can either merge in dev as-is (which duplicates changes in #8103), or wait til #8103 is merged and then rebuild this on top (will then not contain direct changes to UART component).
> 
> @kbx81 - any preference?

As a general practice it's best to break changes for each component out into separate PRs; it keeps the PRs smaller and it's easier to revert changes if something goes horribly off the rails. 🙂

**Comment by exciton** [comment]
Ok, merged in dev, compiles and all checks pass.

**Comment by exciton** [comment]
> > Yeah I can either merge in dev as-is (which duplicates changes in #8103), or wait til #8103 is merged and then rebuild this on top (will then not contain direct changes to UART component).
> > 
> > @kbx81 - any preference?
> 
> As a general practice it's best to break changes for each component out into separate PRs; it keeps the PRs smaller and it's easier to revert changes if something goes horribly off the rails. 🙂

I updated to merge cleanly into the latest dev branch. I consider this good to go. 

If #8103 is merged into dev first then I can remove the UART changes from this PR. However, I can't take those changes out now, since it won't work without them, and will break for people (like me) using the PR directly.

I don't mind either way.

File: esphome/components/modbus/modbus.cpp [hunk 14]
```diff
@@ -12,46 +12,88 @@ void Modbus::setup() {
...
+  if (this->frame_delay_ms_ < 2)
+    this->frame_delay_ms_ = 2;  // 1750us minimium per spec - rounded up to 2ms.
```
Comment (brambo123) [inline esphome/components/modbus/modbus.cpp]:
```suggestion
  this->frame_delay_ms_ = std::max(
      2, // 1750us minimium per spec - rounded up to 2ms.
      (3.5 * 11 * 1000 / this->parent_->get_baud_rate()) + 1));
```

**Comment by exciton** [comment]
Ok, I have reverted changes to the uart component in favour of those in #8103. Tests on this PR will fail until #8103 is merged, at which point a branch update will get everything working again, ready to merge.

**Comment by exciton** [comment]
@kbx81 - looks like we're good to go on this one now 😉

File: esphome/components/modbus/modbus.h [hunk 15]
```diff
@@ -28,28 +31,39 @@ class Modbus : public uart::UARTDevice, public Component {
...
+  uint16_t turnaround_delay_ms_{100};
   bool disable_crc_;
   std::vector<uint8_t> rx_buffer_;
+  void clear_rx_buffer_(const std::string &reason);
   uint32_t last_modbus_byte_{0};
   uint32_t last_send_{0};
+  uint32_t last_send_tx_offset_{0};
   std::vector<ModbusDevice *> devices_;
+  std::deque<std::vector<uint8_t>> tx_buffer_;
+  void send_next_frame_();
```
Comment (kbx81) [inline esphome/components/modbus/modbus.h]: Please sort types by widest to narrowest and place pointers and other types last; this approach minimizes padding, reducing wasted bytes in RAM. I think this will work & should show a small reduction in memory use:
```suggestion
  bool parse_modbus_byte_(uint8_t byte);
  void receive_and_parse_modbus_bytes_();
  void clear_rx_buffer_(const std::string &reason);
  void send_next_frame_();

  uint32_t last_modbus_byte_{0};
  uint32_t last_send_{0};
  uint32_t last_send_tx_offset_{0};
  uint16_t frame_delay_ms_{5};
  uint16_t long_rx_buffer_delay_ms_{0};
  uint16_t send_wait_time_{250};
  uint16_t turnaround_delay_ms_{100};
  uint8_t waiting_for_response_{0};
  bool disable_crc_;

  GPIOPin *flow_control_pin_{nullptr};

  std::vector<uint8_t> rx_buffer_;
  std::vector<ModbusDevice *> devices_;
  std::deque<std::vector<uint8_t>> tx_buffer_;
```

**Review by kbx81 — DISMISSED** [review]

File: esphome/components/modbus/modbus.cpp [hunk 16]
```diff
@@ -12,46 +12,89 @@ void Modbus::setup() {
...
+      std::max(2,  // 1750us minimium per spec - rounded up to 2ms.
+                   // 3.5 characters * 11 bits per character * 1000ms/sec / (bits/sec) (Standard modbus frame delay)
+               (uint16_t) (3.5 * 11 * 1000 / this->parent_->get_baud_rate()) + 1);
+
+  this->long_rx_buffer_delay_ms_ =
+      (this->parent_->get_rx_full_threshold() * 11 * 1000 / this->parent_->get_baud_rate()) + 1;
 }
+
 void Modbus::loop() {
-  const uint32_t now = App.get_loop_component_start_time();
```
Comment (kbx81) [inline esphome/components/modbus/modbus.cpp:20]: This is a performance optimization; could we retain it and use it below instead of adding multiple new calls to `millis()`? I think it would work fine since you're just using it to determine if a timeout has elapsed. Calling `millis()` is slower than reading this stored value.

File: esphome/components/modbus/modbus.cpp [hunk 17]
```diff
@@ -12,46 +12,89 @@ void Modbus::setup() {
...
+  }
+
+  // If there's no response pending and there's commands in the buffer
+  if (!this->tx_blocked() && !this->tx_buffer_.empty()) {
+    this->defer("send_next_frame", [this]() { this->send_next_frame_(); });
+  }
+}
+
+bool Modbus::tx_blocked() {
+  const uint32_t now = millis();
```
Comment (kbx81) [inline esphome/components/modbus/modbus.cpp:62]: As above

File: esphome/components/modbus/modbus.cpp (hunk 16 above)
Comment (exciton) [reply esphome/components/modbus/modbus.cpp:20]: Yes, it's low risk for timeouts. If the cached value is stale (cached some ms in the past) it will just cause us to wait a little longer to timeout or send the next frame. 

This is not true for setting the timestamps after sending a frame, though. Those need to be fresh to ensure we wait sufficient time after transmission.

File: esphome/components/modbus/modbus.cpp [hunk 18]
```diff
@@ -168,25 +222,64 @@ bool Modbus::parse_modbus_byte_(uint8_t byte) {
...
+    this->last_send_tx_offset_ = 0;
+  } else {
+    this->write_array(data);
+    this->last_send_tx_offset_ = data.size() * 11 * 1000 / this->parent_->get_baud_rate() + 1;
+  }
+
+  this->tx_buffer_.pop_front();
+
+  ESP_LOGV(TAG, "Modbus write: %s %dms after last send", format_hex_pretty(data).c_str(), millis() - this->last_send_);
+  this->last_send_ = millis();
```
Comment (exciton) [inline esphome/components/modbus/modbus.cpp:301]: This line must call millis() since there's a blocking call to flush() above. Any subsequent comparisons to this value need to be at least as fresh (i.e not cached before this call)

File: esphome/components/modbus/modbus.cpp [hunk 19]
```diff
@@ -12,46 +12,89 @@ void Modbus::setup() {
...
-    if (now - this->last_send_ > send_wait_time_) {
-      if (waiting_for_response > 0) {
-        ESP_LOGV(TAG, "Stop waiting for response from %d", waiting_for_response);
-      }
-      waiting_for_response = 0;
+    // If the bytes in the rx buffer do not parse, clear out the buffer
+    if (!this->parse_modbus_byte_(byte)) {
+      this->clear_rx_buffer_("parse failed");
     }
+    this->last_modbus_byte_ = millis();
```
Comment (exciton) [inline esphome/components/modbus/modbus.cpp]: This call to millis() needs to be fresh since there may be bytes arriving while parsing, so it's not guaranteed that all available bytes are already in the buffer at the start of the loop. If we use a stale value here it could cause a premature timeout.

File: esphome/components/modbus/modbus.cpp [hunk 20]
```diff
@@ -12,46 +12,89 @@ void Modbus::setup() {
...
+  this->receive_and_parse_modbus_bytes_();
+
+  // If the response frame is finished (including interframe delay) - we timeout.
+  // The long_rx_buffer_delay accounts for long responses (larger than the UART rx_full_threshold) to avoid timeouts
+  // when the buffer is filling the back half of the response
+  const uint16_t timeout = std::max(
+      (uint16_t) this->frame_delay_ms_,
+      (uint16_t) (this->rx_buffer_.size() > this->parent_->get_rx_full_threshold() - 1 ? this->long_rx_buffer_delay_ms_
+                                                                                       : 0));
+  if (millis() - this->last_modbus_byte_ > timeout) {
```
Comment (exciton) [inline esphome/components/modbus/modbus.cpp:44]: If we use a stale value in place of millis() (i.e.  App.get_loop_component_start_time()), and we have just updated last_modbus_byte within the receive_and_parse_modbus_bytes function with a fresh value of millis() then it's possible for this subtraction calc to yield a small negative number, which will wrap to a large positive number (uint) which will immediately cause a timeout. 

This comparison only works properly if it's impossible for the left operand (millis) to come before the right operand (last_modbus_byte) in time.

File: esphome/components/modbus/modbus.cpp (hunk 16 above)
Comment (exciton) [reply esphome/components/modbus/modbus.cpp:20]: Actually, on deeper analysis, it could be problematic. I added comments below to explain.

File: esphome/components/modbus/modbus.cpp [hunk 21]
```diff
@@ -12,46 +12,89 @@ void Modbus::setup() {
...
+  // 1. There are bytes in the UART Rx buffer
+  // 2. There are bytes in our Rx buffer
+  // 3. We're waiting for a response
+  // 4. The last sent byte isn't more than frame_delay ms ago (i.e. wait to tell receivers that our previous Tx is done)
+  // 5. The last received byte isn't more than frame_delay ms ago (i.e. wait to be sure there isn't more Rx coming)
+  // 6. If we're a client - also wait for the turnaround delay, to give the servers time to process the previous message
+  return this->available() || !this->rx_buffer_.empty() || (this->waiting_for_response_ != 0) ||
+         (now - this->last_send_ < this->last_send_tx_offset_ + this->frame_delay_ms_ +
+                                       (this->role == ModbusRole::CLIENT ? this->turnaround_delay_ms_ : 0)) ||
+         (now - this->last_modbus_byte_ <
```
Comment (exciton) [inline esphome/components/modbus/modbus.cpp:74]: This comparison requires the now value to definitely be after the last_modbus_byte value in time to work properly. Since we update last_modbus_byte inside the loop then we can't use a stale value of now from the start of the loop in this comparison.

File: esphome/components/modbus/modbus.cpp (hunk 16 above)
Comment (exciton) [reply esphome/components/modbus/modbus.cpp:20]: I can cache a now value in a few spots to save a few calls to millis(), but I don't think the App cached value works at all for this component. 

The debugging complexity of solving future race conditions between stale timestamps and UART rx/tx buffering may not be worth the imperceptible benefit of saving a few calls to get a fresh timestamp. Especially in this component where timing is critical.

Comment (kbx81) [reply esphome/components/modbus/modbus.cpp:20]: Ah, makes sense. Thanks for explaining. 🍻

Comment (kbx81) [reply esphome/components/modbus/modbus.cpp:20]: BTW, for posterity, you may want to add a comment where relevant to explain this. 😉

**Review by exciton — COMMENTED** [review]
Added some comments explaining the use of millis() for correct timestamp comparison.

**Comment by kbx81** [comment]
> Added some comments explaining the use of millis() for correct timestamp comparison.

@exciton sorry if I wasn't clear 🙈 -- I meant comments in the code, not the PR. 🙂

File: esphome/components/modbus/modbus.cpp [hunk 22]
```diff
@@ -12,46 +12,94 @@ void Modbus::setup() {
...
+bool Modbus::tx_buffer_empty() { return this->tx_buffer_.empty(); }
 
+void Modbus::receive_and_parse_modbus_bytes_() {
   while (this->available()) {
     uint8_t byte;
     this->read_byte(&byte);
-    if (this->parse_modbus_byte_(byte)) {
-      this->last_modbus_byte_ = now;
+    if (this->rx_buffer_.empty()) {
+      ESP_LOGV(TAG, "Modbus received first Byte %d (0X%x) %dms after last send", byte, byte,
```
Comment (kbx81) [inline esphome/components/modbus/modbus.cpp]: For consistency with our [logging best practices](https://developers.esphome.io/architecture/logging/#minimizing-impact)
```suggestion
      ESP_LOGV(TAG, "Received first byte %d (0X%x) %dms after last send", byte, byte,
```

File: esphome/components/modbus/modbus.cpp [hunk 23]
```diff
@@ -12,46 +12,94 @@ void Modbus::setup() {
...
+               millis() - this->last_send_);
     } else {
-      size_t at = this->rx_buffer_.size();
-      if (at > 0) {
-        ESP_LOGV(TAG, "Clearing buffer of %d bytes - parse failed", at);
-        this->rx_buffer_.clear();
-      }
+      ESP_LOGVV(TAG, "Modbus received Byte %d (0X%x) %dms after last send", byte, byte, millis() - this->last_send_);
```
Comment (kbx81) [inline esphome/components/modbus/modbus.cpp]:
```suggestion
      ESP_LOGVV(TAG, "Received byte %d (0X%x) %dms after last send", byte, byte, millis() - this->last_send_);
```

File: esphome/components/modbus/modbus.cpp [hunk 24]
```diff
@@ -130,9 +178,11 @@ bool Modbus::parse_modbus_byte_(uint8_t byte) {
     uint16_t remote_crc = uint16_t(raw[data_offset + data_len]) | (uint16_t(raw[data_offset + data_len + 1]) << 8);
     if (computed_crc != remote_crc) {
       if (this->disable_crc_) {
-        ESP_LOGD(TAG, "Modbus CRC Check failed, but ignored! %02X!=%02X", computed_crc, remote_crc);
+        ESP_LOGD(TAG, "Modbus CRC Check failed, but ignored! %02X!=%02X  %s %dms after last send", computed_crc,
+                 remote_crc, format_hex_pretty(this->rx_buffer_).c_str(), millis() - this->last_send_);
```
Comment (kbx81) [inline esphome/components/modbus/modbus.cpp]: Split this up; leave dumping packet contents for (very_)verbose mode.
```suggestion
        ESP_LOGW(TAG, "CRC check failed; ignoring");
        ESP_LOGVV(TAG, "  (%02X != %02X)  %s %dms after last send", computed_crc,
                 remote_crc, format_hex_pretty(this->rx_buffer_).c_str(), millis() - this->last_send_);
```

File: esphome/components/modbus/modbus.cpp [hunk 25]
```diff
@@ -130,9 +178,11 @@ bool Modbus::parse_modbus_byte_(uint8_t byte) {
...
       } else {
-        ESP_LOGW(TAG, "Modbus CRC Check failed! %02X!=%02X", computed_crc, remote_crc);
+        ESP_LOGW(TAG, "Modbus CRC Check failed! %02X!=%02X %s %dms after last send", computed_crc, remote_crc,
+                 format_hex_pretty(this->rx_buffer_).c_str(), millis() - this->last_send_);
```
Comment (kbx81) [inline esphome/components/modbus/modbus.cpp]: As above:
```suggestion
        ESP_LOGW(TAG, "CRC check failed");
        ESP_LOGVV(TAG, "  (%02X != %02X) %s %dms after last send", computed_crc, remote_crc,
                 format_hex_pretty(this->rx_buffer_).c_str(), millis() - this->last_send_);
```

File: esphome/components/modbus/modbus.cpp [hunk 26]
```diff
@@ -144,49 +194,89 @@ bool Modbus::parse_modbus_byte_(uint8_t byte) {
       found = true;
       // Is it an error response?
       if ((function_code & 0x80) == 0x80) {
-        ESP_LOGD(TAG, "Modbus error function code: 0x%X exception: %d", function_code, raw[2]);
-        if (waiting_for_response != 0) {
-          device->on_modbus_error(function_code & 0x7F, raw[2]);
-        } else {
+        uint8_t exception = raw[2];
+        ESP_LOGD(TAG, "Modbus error function code: 0x%X exception: %d", function_code, exception);
```
Comment (kbx81) [inline esphome/components/modbus/modbus.cpp]:
```suggestion
        ESP_LOGD(TAG, "Error function code: 0x%X exception: %d", function_code, exception);
```

File: esphome/components/modbus/modbus.cpp [hunk 27]
```diff
@@ -144,49 +194,89 @@ bool Modbus::parse_modbus_byte_(uint8_t byte) {
...
+    this->last_send_tx_offset_ = data.size() * 11 * 1000 / this->parent_->get_baud_rate() + 1;
+  }
+
+  this->tx_buffer_.pop_front();
+
+  ESP_LOGV(TAG, "Modbus write: %s %dms after last send", format_hex_pretty(data).c_str(), millis() - this->last_send_);
+  this->last_send_ = millis();
+
+  if (!this->tx_buffer_.empty()) {
+    ESP_LOGV(TAG, "Modbus write queue contains %d items.", this->tx_buffer_.size());
```
Comment (kbx81) [inline esphome/components/modbus/modbus.cpp]:
```suggestion
    ESP_LOGV(TAG, "Write queue contains %d items.", this->tx_buffer_.size());
```

File: esphome/components/modbus/modbus.cpp [hunk 28]
```diff
@@ -250,20 +326,26 @@ void Modbus::send_raw(const std::vector<uint8_t> &payload) {
...
-  this->flush();
-  if (this->flow_control_pin_ != nullptr)
-    this->flow_control_pin_->digital_write(false);
-  waiting_for_response = payload[0];
-  ESP_LOGV(TAG, "Modbus write raw: %s", format_hex_pretty(payload).c_str());
-  last_send_ = millis();
+  if (this->tx_buffer_.size() < MODBUS_TX_BUFFER_SIZE) {
+    this->tx_buffer_.push_back(data);
+  } else {
+    ESP_LOGW(TAG, "Modbus write buffer full, dropped: %s", format_hex_pretty(data).c_str());
```
Comment (kbx81) [inline esphome/components/modbus/modbus.cpp]:
```suggestion
    ESP_LOGW(TAG, "Write buffer full, dropped: %s", format_hex_pretty(data).c_str());
```

File: esphome/components/modbus/modbus.cpp [hunk 29]
```diff
@@ -144,49 +194,89 @@ bool Modbus::parse_modbus_byte_(uint8_t byte) {
...
+    this->flow_control_pin_->digital_write(false);
+    this->last_send_tx_offset_ = 0;
+  } else {
+    this->write_array(data);
+    this->last_send_tx_offset_ = data.size() * 11 * 1000 / this->parent_->get_baud_rate() + 1;
+  }
+
+  this->tx_buffer_.pop_front();
+
+  ESP_LOGV(TAG, "Modbus write: %s %dms after last send", format_hex_pretty(data).c_str(), millis() - this->last_send_);
```
Comment (kbx81) [inline esphome/components/modbus/modbus.cpp]:
```suggestion
  ESP_LOGV(TAG, "Write: %s %dms after last send", format_hex_pretty(data).c_str(), millis() - this->last_send_);
```

File: esphome/components/modbus/modbus.cpp [hunk 30]
```diff
@@ -144,49 +194,89 @@ bool Modbus::parse_modbus_byte_(uint8_t byte) {
...
+        this->defer("on_modbus_data", [device, data]() { device->on_modbus_data(data); });
       }
-      // fallthrough for other function codes
-      device->on_modbus_data(data);
     }
   }
-  waiting_for_response = 0;
 
-  if (!found) {
+  if (!found && this->role == ModbusRole::CLIENT) {
```
Comment (kbx81) [inline esphome/components/modbus/modbus.cpp:259]: `ESP_LOGW` on the line below this one should have the component name removed from the message

File: esphome/components/modbus/modbus.cpp [hunk 31]
```diff
@@ -144,49 +194,89 @@ bool Modbus::parse_modbus_byte_(uint8_t byte) {
...
-        if (waiting_for_response != 0) {
-          device->on_modbus_error(function_code & 0x7F, raw[2]);
-        } else {
+        uint8_t exception = raw[2];
+        ESP_LOGD(TAG, "Modbus error function code: 0x%X exception: %d", function_code, exception);
+        if (waiting_for_response_ == address) {
+          this->defer("on_modbus_error", [device, function_code, exception]() {
+            device->on_modbus_error(function_code & 0x7F, exception);
+          });
+        } else if (this->role == ModbusRole::CLIENT) {
```
Comment (kbx81) [inline esphome/components/modbus/modbus.cpp]: ESP_LOGD on the line below this one should have the component name removed from the message

**Review by kbx81 — COMMENTED** [review]
Cleaning up some logging 🙂

**Comment by exciton** [comment]
@kbx81 - think this is polished now. Take a look.

**Comment by ngehrsitz** [comment]
@kbx81 @jesserockz Are there any remaining blockers?

**Comment by kbx81** [comment]
Conflicts need fixing before we can approve & merge

**Comment by exciton** [comment]
Ok, conflicts fixed.

File: esphome/components/modbus/modbus.h [hunk 32]
```diff
@@ -30,28 +33,41 @@ class Modbus : public uart::UARTDevice, public Component {
...
+  uint8_t waiting_for_response_{0};
   bool disable_crc_;
+
+  GPIOPin *flow_control_pin_{nullptr};
+
   std::vector<uint8_t> rx_buffer_;
-  uint32_t last_modbus_byte_{0};
-  uint32_t last_send_{0};
   std::vector<ModbusDevice *> devices_;
+  std::deque<std::vector<uint8_t>> tx_buffer_;
```
Comment (bdraco) [inline esphome/components/modbus/modbus.h]: Its the deque driving the large jump in component size.

deque also allocates a min of 512 bytes and it allocates in chunks

File: esphome/components/modbus/modbus.cpp [hunk 33]
```diff
@@ -12,46 +12,93 @@ void Modbus::setup() {
...
+      (uint16_t) this->frame_delay_ms_,
+      (uint16_t) (this->rx_buffer_.size() > this->parent_->get_rx_full_threshold() - 1 ? this->long_rx_buffer_delay_ms_
+                                                                                       : 0));
+  // We use millis() here and elsewhere instead of App.get_loop_component_start_time() to avoid stale timestamps
+  // It's critical in all timestamp comparisons that the left timestamp comes before the right one in time
+  // If we use a cached value in place of millis() and last_modbus_byte_ is updated inside our loop
+  // then the comparison is backwards (small negative which wraps to large positive) and will cause a false timeout
+  // So in this component we don't use any cached timestamp values to avoid these annoying bugs
+  if (millis() - this->last_modbus_byte_ > timeout) {
+    clear_rx_buffer_("timeout after partial response", true);
```
Comment (kbx81) [inline esphome/components/modbus/modbus.cpp]:
```suggestion
    this->clear_rx_buffer_("timeout after partial response", true);
```

File: esphome/components/modbus/modbus.cpp [hunk 34]
```diff
@@ -152,53 +201,97 @@ bool Modbus::parse_modbus_byte_(uint8_t byte) {
...
           device->on_modbus_write_registers(function_code, data);
-          continue;
+        }
+      } else {  // We're a client
+        // Is it an error response?
+        if ((function_code & FUNCTION_CODE_EXCEPTION_MASK) == FUNCTION_CODE_EXCEPTION_MASK) {
+          uint8_t exception = raw[2];
+          ESP_LOGW(TAG, "Error function code: 0x%X exception: %d, address: %d, %dms after last send", function_code,
+                   exception, address, millis() - this->last_send_);
+          if (waiting_for_response_ == address) {
```
Comment (kbx81) [inline esphome/components/modbus/modbus.cpp]:
```suggestion
          if (this->waiting_for_response_ == address) {
```

File: esphome/components/modbus/modbus.cpp [hunk 35]
```diff
@@ -152,53 +201,97 @@ bool Modbus::parse_modbus_byte_(uint8_t byte) {
...
+            device->on_modbus_error(function_code & FUNCTION_CODE_MASK, exception);
+          } else {
+            // Ignore modbus exception not related to a pending command
+            ESP_LOGD(TAG, "Ignoring error - not expecting a response from %d", address);
+          }
+        } else {  // Not an error response
+          if (waiting_for_response_ == address) {
```
Comment (kbx81) [inline esphome/components/modbus/modbus.cpp]:
```suggestion
          if (this->waiting_for_response_ == address) {
```

File: esphome/components/modbus_controller/modbus_controller.cpp [hunk 36]
```diff
@@ -18,7 +18,7 @@ void ModbusController::setup() { this->create_register_ranges_(); }
 bool ModbusController::send_next_command_() {
   uint32_t last_send = millis() - this->last_command_timestamp_;
 
-  if ((last_send > this->command_throttle_) && !waiting_for_response() && !this->command_queue_.empty()) {
+  if ((last_send > this->command_throttle_) && ready_for_immediate_send() && !this->command_queue_.empty()) {
```
Comment (kbx81) [inline esphome/components/modbus_controller/modbus_controller.cpp]:
```suggestion
  if ((last_send > this->command_throttle_) && this->ready_for_immediate_send() && !this->command_queue_.empty()) {
```

**Comment by henrykuijpers** [comment]
Thank you for your excellent work @exciton ! Hopefully this can be merged in very soon, so that we can all benefit from your immense effort to stabilize modbus in esphome! ❤️ 

(Suffering myself to set up modbus measuring of quite a few SDM630 & SDM120 in my home network and encountering various problems that, when googling, all lead to your work. :D )

**Comment by exciton** [comment]
> Thank you for your excellent work @exciton ! Hopefully this can be merged in very soon, so that we can all benefit from your immense effort to stabilize modbus in esphome! ❤️
> 
> (Suffering myself to set up modbus measuring of quite a few SDM630 & SDM120 in my home network and encountering various problems that, when googling, all lead to your work. :D )

Thanks @henrykuijpers! If you have tested any of these PRs and found that it helps (or doesn't!) please drop a comment or log file describing it. It helps reviewers to know that it's working for folks.

**Comment by exciton** [comment]
@kbx81 code style fixes done per your suggestions.

**Comment by henrykuijpers** [comment]
Will this PR also fix the issues on start-up where sometimes several devices can't be reached and will never be reached? 

The esp32 starts up and tries to send requests and fails. The next time (after 30 seconds for example) it still fails. And it will never show the values.
A restart sometimes fixes it, sometimes not. Sometimes another device will suddenly be available and the one that was available, goes missing.

It becomes a challenge when you have more than 2 devices, of course. As the chance gets smaller and smaller that you'll have a boot with all devices available.

**Comment by exciton** [comment]
> Will this PR also fix the issues on start-up where sometimes several devices can't be reached and will never be reached? 
> ...

It sounds like the kind of problem that this PR fixes, so I expect it will help. You can test the PR directly to find out, or post a log file if you want others to take a look at your situation.

**Comment by henrykuijpers** [comment]
@exciton Would it be possible to reference all 8 PRs in the yaml file?
```
external_components:
  - source: github://pr#8032
    components: [modbus, modbus_controller, growatt_solar]
    refresh: 1h
```
is useful, but it doesn't allow testing all the nice fixes at once?

**Comment by exciton** [comment]
@henrykuijpers yes - just use the last one 12614 as it includes all changes

**Comment by henrykuijpers** [comment]
@exciton thanks for that! Will try that soon with my esp modbus reader. 

Is that last PR constantly kept up to date with all the changes in all the branches? 

Appreciate your work man, insane effort!

**Comment by exciton** [comment]
Generally yes, important bug fixes are cherry picked into each branch, but major changes become a new PR.

**Comment by exciton** [comment]
Merged in latest dev. This one should be good to go.

File: esphome/components/modbus/modbus.h [hunk 37]
```diff
@@ -30,28 +33,44 @@ class Modbus : public uart::UARTDevice, public Component {
...
+  GPIOPin *flow_control_pin_{nullptr};
+
   std::vector<uint8_t> rx_buffer_;
-  uint32_t last_modbus_byte_{0};
-  uint32_t last_send_{0};
   std::vector<ModbusDevice *> devices_;
+  // std::queue is appropriate here since we need a FIFO buffer, and we can't know ahead of time how many
+  // requests will be queued. Each modbus component may queue multiple requests, and the sequence of scheduling
+  // may change at run time.
+  std::queue<std::vector<uint8_t>> tx_buffer_;
```
Comment (bdraco) [inline esphome/components/modbus/modbus.h]: `std::vector` brings reallocation machinery that's never used. It looks like frames are built once, and consumed once.

File: esphome/components/modbus/modbus.cpp [hunk 38]
```diff
@@ -155,52 +204,100 @@ bool Modbus::parse_modbus_byte_(uint8_t byte) {
...
 }
 
+void Modbus::send_next_frame_() {
+  if (this->tx_buffer_.empty())
+    return;
+
+  if (this->tx_blocked())
+    return;
+
+  std::vector<uint8_t> data = this->tx_buffer_.front();
```
Comment (bdraco) [inline esphome/components/modbus/modbus.cpp]: This is making a copy on the heap

Comment (bdraco) [inline esphome/components/modbus/modbus.cpp]:
```suggestion
  std::vector<uint8_t> data = std::move(this->tx_buffer_.front()); 
```

Comment (bdraco) [reply esphome/components/modbus/modbus.cpp]: But you still need to manage the lifetime after moving as well

File: esphome/components/modbus/modbus.h (hunk 37 above)
Comment (bdraco) [reply esphome/components/modbus/modbus.h]: If I'm reading this right we know the size ahead of time so std::vector is not the right container since its going to make reallocation machinery that is never used.

Can we try to send sync first, and only queue if it can't be sent right away?

something like

```diff
diff --git a/esphome/components/modbus/modbus.cpp b/esphome/components/modbus/modbus.cpp
index 8a65eb4ad4..6ea91c63f3 100644
--- a/esphome/components/modbus/modbus.cpp
+++ b/esphome/components/modbus/modbus.cpp
@@ -2,6 +2,7 @@
 #include "esphome/core/application.h"
 #include "esphome/core/helpers.h"
 #include "esphome/core/log.h"
+#include <cstring>
 
 namespace esphome {
 namespace modbus {
@@ -257,35 +258,39 @@ void Modbus::send_next_frame_() {
   if (this->tx_blocked())
     return;
 
-  std::vector<uint8_t> data = this->tx_buffer_.front();
+  TxFrame &frame = this->tx_buffer_.front();
 
+  this->transmit_frame_(frame.data.get(), frame.size);
+
+  this->tx_buffer_.pop();
+
+  if (!this->tx_buffer_.empty()) {
+    ESP_LOGV(TAG, "Write queue contains %d items.", this->tx_buffer_.size());
+  }
+}
+
+void Modbus::transmit_frame_(const uint8_t *data, uint16_t size) {
   if (this->role == ModbusRole::CLIENT) {
     this->waiting_for_response_ = data[0];
   }
 
   if (this->flow_control_pin_ != nullptr) {
     this->flow_control_pin_->digital_write(true);
-    this->write_array(data);
+    this->write_array(data, size);
     this->flush();
     this->flow_control_pin_->digital_write(false);
     this->last_send_tx_offset_ = 0;
   } else {
-    this->write_array(data);
-    this->last_send_tx_offset_ = data.size() * 11 * 1000 / this->parent_->get_baud_rate() + 1;
+    this->write_array(data, size);
+    this->last_send_tx_offset_ = size * 11 * 1000 / this->parent_->get_baud_rate() + 1;
   }
 
-  this->tx_buffer_.pop();
-
 #if ESPHOME_LOG_LEVEL >= ESPHOME_LOG_LEVEL_VERBOSE
   char hex_buf[format_hex_pretty_size(MODBUS_MAX_LOG_BYTES)];
 #endif
-  ESP_LOGV(TAG, "Write: %s %dms after last send", format_hex_pretty_to(hex_buf, data.data(), data.size()),
+  ESP_LOGV(TAG, "Write: %s %dms after last send", format_hex_pretty_to(hex_buf, data, size),
            millis() - this->last_send_);
   this->last_send_ = millis();
-
-  if (!this->tx_buffer_.empty()) {
-    ESP_LOGV(TAG, "Write queue contains %d items.", this->tx_buffer_.size());
-  }
 }
 
 void Modbus::dump_config() {
@@ -316,32 +321,69 @@ void Modbus::send(uint8_t address, uint8_t function_code, uint16_t start_address
     return;
   }
 
-  std::vector<uint8_t> data;
-  data.push_back(address);
-  data.push_back(function_code);
+  // Calculate frame size upfront to avoid vector reallocation
+  // Frame: address(1) + function(1) + [start_addr(2) + num_entities(2)] + [byte_count(1)] + payload + CRC(2)
+  uint16_t frame_size = 2;  // address + function_code
   if (this->role == ModbusRole::CLIENT) {
-    data.push_back(start_address >> 8);
-    data.push_back(start_address >> 0);
+    frame_size += 2;  // start_address
     if (function_code != ModbusFunctionCode::WRITE_SINGLE_COIL &&
         function_code != ModbusFunctionCode::WRITE_SINGLE_REGISTER) {
-      data.push_back(number_of_entities >> 8);
-      data.push_back(number_of_entities >> 0);
+      frame_size += 2;  // number_of_entities
     }
   }
-
+  uint8_t actual_payload_len = 0;
   if (payload != nullptr) {
     if (this->role == ModbusRole::SERVER || function_code == ModbusFunctionCode::WRITE_MULTIPLE_COILS ||
-        function_code == ModbusFunctionCode::WRITE_MULTIPLE_REGISTERS) {  // Write multiple
-      data.push_back(payload_len);                                        // Byte count is required for write
+        function_code == ModbusFunctionCode::WRITE_MULTIPLE_REGISTERS) {
+      frame_size += 1;  // byte_count
+      actual_payload_len = payload_len;
     } else {
-      payload_len = 2;  // Write single register or coil
+      actual_payload_len = 2;  // Write single register or coil
+    }
+    frame_size += actual_payload_len;
+  }
+  frame_size += 2;  // CRC
+
+  // Use stack buffer - Modbus frames are small and bounded
+  uint8_t data[MODBUS_MAX_FRAME_SIZE];
+  uint16_t pos = 0;
+
+  data[pos++] = address;
+  data[pos++] = function_code;
+  if (this->role == ModbusRole::CLIENT) {
+    data[pos++] = start_address >> 8;
+    data[pos++] = start_address & 0xFF;
+    if (function_code != ModbusFunctionCode::WRITE_SINGLE_COIL &&
+        function_code != ModbusFunctionCode::WRITE_SINGLE_REGISTER) {
+      data[pos++] = number_of_entities >> 8;
+      data[pos++] = number_of_entities & 0xFF;
     }
-    for (int i = 0; i < payload_len; i++) {
-      data.push_back(payload[i]);
+  }
+
+  if (payload != nullptr) {
+    if (this->role == ModbusRole::SERVER || function_code == ModbusFunctionCode::WRITE_MULTIPLE_COILS ||
+        function_code == ModbusFunctionCode::WRITE_MULTIPLE_REGISTERS) {
+      data[pos++] = actual_payload_len;  // Byte count
     }
+    std::memcpy(data + pos, payload, actual_payload_len);
+    pos += actual_payload_len;
   }
 
-  send_raw(data);
+  auto crc = crc16(data, pos);
+  data[pos++] = crc & 0xFF;
+  data[pos++] = crc >> 8;
+
+  // Try to send synchronously if possible, otherwise queue
+  if (!this->tx_blocked() && this->tx_buffer_.empty()) {
+    this->transmit_frame_(data, pos);
+  } else if (this->tx_buffer_.size() < MODBUS_TX_BUFFER_SIZE) {
+    this->tx_buffer_.emplace(data, pos);
+  } else {
+#if ESPHOME_LOG_LEVEL >= ESPHOME_LOG_LEVEL_ERROR
+    char hex_buf[format_hex_pretty_size(MODBUS_MAX_LOG_BYTES)];
+#endif
+    ESP_LOGE(TAG, "Write buffer full, dropped: %s", format_hex_pretty_to(hex_buf, data, pos));
+  }
 }
 
 // Helper function for lambdas
@@ -350,19 +392,28 @@ void Modbus::send_raw(const std::vector<uint8_t> &payload) {
   if (payload.empty()) {
     return;
   }
-  std::vector<uint8_t> data = payload;
 
-  auto crc = crc16(data.data(), data.size());
-  data.push_back(crc >> 0);
-  data.push_back(crc >> 8);
+  // Frame size: payload + CRC(2)
+  size_t frame_size = payload.size() + 2;
+
+  // Use stack buffer - Modbus frames are small and bounded
+  uint8_t data[MODBUS_MAX_FRAME_SIZE];
+
+  std::memcpy(data, payload.data(), payload.size());
+  auto crc = crc16(data, payload.size());
+  data[payload.size()] = crc & 0xFF;
+  data[payload.size() + 1] = crc >> 8;
 
-  if (this->tx_buffer_.size() < MODBUS_TX_BUFFER_SIZE) {
-    this->tx_buffer_.push(data);
+  // Try to send synchronously if possible, otherwise queue
+  if (!this->tx_blocked() && this->tx_buffer_.empty()) {
+    this->transmit_frame_(data, frame_size);
+  } else if (this->tx_buffer_.size() < MODBUS_TX_BUFFER_SIZE) {
+    this->tx_buffer_.emplace(data, frame_size);
   } else {
 #if ESPHOME_LOG_LEVEL >= ESPHOME_LOG_LEVEL_ERROR
     char hex_buf[format_hex_pretty_size(MODBUS_MAX_LOG_BYTES)];
 #endif
-    ESP_LOGE(TAG, "Write buffer full, dropped: %s", format_hex_pretty_to(hex_buf, data.data(), data.size()));
+    ESP_LOGE(TAG, "Write buffer full, dropped: %s", format_hex_pretty_to(hex_buf, data, frame_size));
   }
 }
 
diff --git a/esphome/components/modbus/modbus.h b/esphome/components/modbus/modbus.h
index 60a2e13996..ba63113c23 100644
--- a/esphome/components/modbus/modbus.h
+++ b/esphome/components/modbus/modbus.h
@@ -5,13 +5,27 @@
 
 #include "esphome/components/modbus/modbus_definitions.h"
 
-#include <vector>
+#include <cstring>
+#include <memory>
 #include <queue>
+#include <vector>
 
 namespace esphome {
 namespace modbus {
 
-static const uint16_t MODBUS_TX_BUFFER_SIZE = 100;
+static constexpr uint16_t MODBUS_TX_BUFFER_SIZE = 100;
+// Maximum Modbus RTU frame size (for stack allocation)
+static constexpr size_t MODBUS_MAX_FRAME_SIZE = 256;
+
+// Tx frame with exact-size allocation to avoid std::vector overhead
+struct TxFrame {
+  std::unique_ptr<uint8_t[]> data;
+  uint16_t size;  // Modbus RTU max is 256 bytes
+
+  TxFrame(const uint8_t *src, uint16_t len) : data(std::make_unique<uint8_t[]>(len)), size(len) {
+    std::memcpy(this->data.get(), src, len);
+  }
+};
 
 enum ModbusRole {
   CLIENT,
@@ -52,6 +66,7 @@ class Modbus : public uart::UARTDevice, public Component {
   void receive_and_parse_modbus_bytes_();
   void clear_rx_buffer_(const std::string &reason, bool warn = false);
   void send_next_frame_();
+  void transmit_frame_(const uint8_t *data, uint16_t size);
 
   uint32_t last_modbus_byte_{0};
   uint32_t last_send_{0};
@@ -70,7 +85,7 @@ class Modbus : public uart::UARTDevice, public Component {
   // std::queue is appropriate here since we need a FIFO buffer, and we can't know ahead of time how many
   // requests will be queued. Each modbus component may queue multiple requests, and the sequence of scheduling
   // may change at run time.
-  std::queue<std::vector<uint8_t>> tx_buffer_;
+  std::queue<TxFrame> tx_buffer_;
 };
 
 class ModbusDevice {
```

Comment (bdraco) [reply esphome/components/modbus/modbus.h]: Also if there is a reasonable chance we will drain the write queue every time, than `std::vector<TxFrame> tx_buffer_` is likely a better container since we would only have to do `O(n)` `.erase()` for rare cases.

Comment (bdraco) [reply esphome/components/modbus/modbus.h]: oh right modbus requires a delay. So we could use vector compaction instead

Comment (bdraco) [reply esphome/components/modbus/modbus.h]: Here is a version that tracks the vectors and clears it once the queue is cleared so it only expands when its behind and than clears quickly once it empties the queue

```diff
diff --git a/esphome/components/modbus/modbus.cpp b/esphome/components/modbus/modbus.cpp
index 8a65eb4ad4..4fefa5f7d7 100644
--- a/esphome/components/modbus/modbus.cpp
+++ b/esphome/components/modbus/modbus.cpp
@@ -2,6 +2,7 @@
 #include "esphome/core/application.h"
 #include "esphome/core/helpers.h"
 #include "esphome/core/log.h"
+#include <cstring>
 
 namespace esphome {
 namespace modbus {
@@ -55,7 +56,7 @@ void Modbus::loop() {
   }
 
   // If there's no response pending and there's commands in the buffer
-  if (!this->tx_blocked() && !this->tx_buffer_.empty()) {
+  if (!this->tx_blocked() && this->tx_buffer_front_ < this->tx_buffer_.size()) {
     this->defer("send_next_frame", [this]() { this->send_next_frame_(); });
   }
 }
@@ -77,7 +78,7 @@ bool Modbus::tx_blocked() {
           this->frame_delay_ms_ + (this->role == ModbusRole::CLIENT ? this->turnaround_delay_ms_ : 0));
 }
 
-bool Modbus::tx_buffer_empty() { return this->tx_buffer_.empty(); }
+bool Modbus::tx_buffer_empty() { return this->tx_buffer_front_ >= this->tx_buffer_.size(); }
 
 void Modbus::receive_and_parse_modbus_bytes_() {
   while (this->available()) {
@@ -251,41 +252,49 @@ bool Modbus::parse_modbus_byte_(uint8_t byte) {
 }
 
 void Modbus::send_next_frame_() {
-  if (this->tx_buffer_.empty())
+  if (this->tx_buffer_front_ >= this->tx_buffer_.size())
     return;
 
   if (this->tx_blocked())
     return;
 
-  std::vector<uint8_t> data = this->tx_buffer_.front();
+  TxFrame &frame = this->tx_buffer_[this->tx_buffer_front_];
 
+  this->transmit_frame_(frame.data.get(), frame.size);
+
+  this->tx_buffer_front_++;
+
+  // Compact when all frames consumed
+  if (this->tx_buffer_front_ >= this->tx_buffer_.size()) {
+    this->tx_buffer_.clear();
+    this->tx_buffer_front_ = 0;
+  } else {
+    ESP_LOGV(TAG, "Write queue contains %d items.", this->tx_buffer_.size() - this->tx_buffer_front_);
+  }
+}
+
+void Modbus::transmit_frame_(const uint8_t *data, uint16_t size) {
   if (this->role == ModbusRole::CLIENT) {
     this->waiting_for_response_ = data[0];
   }
 
   if (this->flow_control_pin_ != nullptr) {
     this->flow_control_pin_->digital_write(true);
-    this->write_array(data);
+    this->write_array(data, size);
     this->flush();
     this->flow_control_pin_->digital_write(false);
     this->last_send_tx_offset_ = 0;
   } else {
-    this->write_array(data);
-    this->last_send_tx_offset_ = data.size() * 11 * 1000 / this->parent_->get_baud_rate() + 1;
+    this->write_array(data, size);
+    this->last_send_tx_offset_ = size * 11 * 1000 / this->parent_->get_baud_rate() + 1;
   }
 
-  this->tx_buffer_.pop();
-
 #if ESPHOME_LOG_LEVEL >= ESPHOME_LOG_LEVEL_VERBOSE
   char hex_buf[format_hex_pretty_size(MODBUS_MAX_LOG_BYTES)];
 #endif
-  ESP_LOGV(TAG, "Write: %s %dms after last send", format_hex_pretty_to(hex_buf, data.data(), data.size()),
+  ESP_LOGV(TAG, "Write: %s %dms after last send", format_hex_pretty_to(hex_buf, data, size),
            millis() - this->last_send_);
   this->last_send_ = millis();
-
-  if (!this->tx_buffer_.empty()) {
-    ESP_LOGV(TAG, "Write queue contains %d items.", this->tx_buffer_.size());
-  }
 }
 
 void Modbus::dump_config() {
@@ -316,32 +325,69 @@ void Modbus::send(uint8_t address, uint8_t function_code, uint16_t start_address
     return;
   }
 
-  std::vector<uint8_t> data;
-  data.push_back(address);
-  data.push_back(function_code);
+  // Calculate frame size upfront to avoid vector reallocation
+  // Frame: address(1) + function(1) + [start_addr(2) + num_entities(2)] + [byte_count(1)] + payload + CRC(2)
+  uint16_t frame_size = 2;  // address + function_code
   if (this->role == ModbusRole::CLIENT) {
-    data.push_back(start_address >> 8);
-    data.push_back(start_address >> 0);
+    frame_size += 2;  // start_address
     if (function_code != ModbusFunctionCode::WRITE_SINGLE_COIL &&
         function_code != ModbusFunctionCode::WRITE_SINGLE_REGISTER) {
-      data.push_back(number_of_entities >> 8);
-      data.push_back(number_of_entities >> 0);
+      frame_size += 2;  // number_of_entities
     }
   }
-
+  uint8_t actual_payload_len = 0;
   if (payload != nullptr) {
     if (this->role == ModbusRole::SERVER || function_code == ModbusFunctionCode::WRITE_MULTIPLE_COILS ||
-        function_code == ModbusFunctionCode::WRITE_MULTIPLE_REGISTERS) {  // Write multiple
-      data.push_back(payload_len);                                        // Byte count is required for write
+        function_code == ModbusFunctionCode::WRITE_MULTIPLE_REGISTERS) {
+      frame_size += 1;  // byte_count
+      actual_payload_len = payload_len;
     } else {
-      payload_len = 2;  // Write single register or coil
+      actual_payload_len = 2;  // Write single register or coil
     }
-    for (int i = 0; i < payload_len; i++) {
-      data.push_back(payload[i]);
+    frame_size += actual_payload_len;
+  }
+  frame_size += 2;  // CRC
+
+  // Use stack buffer - Modbus frames are small and bounded
+  uint8_t data[MODBUS_MAX_FRAME_SIZE];
+  uint16_t pos = 0;
+
+  data[pos++] = address;
+  data[pos++] = function_code;
+  if (this->role == ModbusRole::CLIENT) {
+    data[pos++] = start_address >> 8;
+    data[pos++] = start_address & 0xFF;
+    if (function_code != ModbusFunctionCode::WRITE_SINGLE_COIL &&
+        function_code != ModbusFunctionCode::WRITE_SINGLE_REGISTER) {
+      data[pos++] = number_of_entities >> 8;
+      data[pos++] = number_of_entities & 0xFF;
     }
   }
 
-  send_raw(data);
+  if (payload != nullptr) {
+    if (this->role == ModbusRole::SERVER || function_code == ModbusFunctionCode::WRITE_MULTIPLE_COILS ||
+        function_code == ModbusFunctionCode::WRITE_MULTIPLE_REGISTERS) {
+      data[pos++] = actual_payload_len;  // Byte count
+    }
+    std::memcpy(data + pos, payload, actual_payload_len);
+    pos += actual_payload_len;
+  }
+
+  auto crc = crc16(data, pos);
+  data[pos++] = crc & 0xFF;
+  data[pos++] = crc >> 8;
+
+  // Try to send synchronously if possible, otherwise queue
+  if (!this->tx_blocked() && this->tx_buffer_empty()) {
+    this->transmit_frame_(data, pos);
+  } else if (this->tx_buffer_.size() < MODBUS_TX_BUFFER_SIZE) {
+    this->tx_buffer_.emplace_back(data, pos);
+  } else {
+#if ESPHOME_LOG_LEVEL >= ESPHOME_LOG_LEVEL_ERROR
+    char hex_buf[format_hex_pretty_size(MODBUS_MAX_LOG_BYTES)];
+#endif
+    ESP_LOGE(TAG, "Write buffer full, dropped: %s", format_hex_pretty_to(hex_buf, data, pos));
+  }
 }
 
 // Helper function for lambdas
@@ -350,19 +396,28 @@ void Modbus::send_raw(const std::vector<uint8_t> &payload) {
   if (payload.empty()) {
     return;
   }
-  std::vector<uint8_t> data = payload;
 
-  auto crc = crc16(data.data(), data.size());
-  data.push_back(crc >> 0);
-  data.push_back(crc >> 8);
+  // Frame size: payload + CRC(2)
+  size_t frame_size = payload.size() + 2;
+
+  // Use stack buffer - Modbus frames are small and bounded
+  uint8_t data[MODBUS_MAX_FRAME_SIZE];
+
+  std::memcpy(data, payload.data(), payload.size());
+  auto crc = crc16(data, payload.size());
+  data[payload.size()] = crc & 0xFF;
+  data[payload.size() + 1] = crc >> 8;
 
-  if (this->tx_buffer_.size() < MODBUS_TX_BUFFER_SIZE) {
-    this->tx_buffer_.push(data);
+  // Try to send synchronously if possible, otherwise queue
+  if (!this->tx_blocked() && this->tx_buffer_empty()) {
+    this->transmit_frame_(data, frame_size);
+  } else if (this->tx_buffer_.size() < MODBUS_TX_BUFFER_SIZE) {
+    this->tx_buffer_.emplace_back(data, frame_size);
   } else {
 #if ESPHOME_LOG_LEVEL >= ESPHOME_LOG_LEVEL_ERROR
     char hex_buf[format_hex_pretty_size(MODBUS_MAX_LOG_BYTES)];
 #endif
-    ESP_LOGE(TAG, "Write buffer full, dropped: %s", format_hex_pretty_to(hex_buf, data.data(), data.size()));
+    ESP_LOGE(TAG, "Write buffer full, dropped: %s", format_hex_pretty_to(hex_buf, data, frame_size));
   }
 }
 
diff --git a/esphome/components/modbus/modbus.h b/esphome/components/modbus/modbus.h
index 60a2e13996..367d62fcde 100644
--- a/esphome/components/modbus/modbus.h
+++ b/esphome/components/modbus/modbus.h
@@ -5,13 +5,26 @@
 
 #include "esphome/components/modbus/modbus_definitions.h"
 
+#include <cstring>
+#include <memory>
 #include <vector>
-#include <queue>
 
 namespace esphome {
 namespace modbus {
 
-static const uint16_t MODBUS_TX_BUFFER_SIZE = 100;
+static constexpr uint16_t MODBUS_TX_BUFFER_SIZE = 100;
+// Maximum Modbus RTU frame size (for stack allocation)
+static constexpr size_t MODBUS_MAX_FRAME_SIZE = 256;
+
+// Tx frame with exact-size allocation to avoid std::vector overhead
+struct TxFrame {
+  std::unique_ptr<uint8_t[]> data;
+  uint16_t size;  // Modbus RTU max is 256 bytes
+
+  TxFrame(const uint8_t *src, uint16_t len) : data(std::make_unique<uint8_t[]>(len)), size(len) {
+    std::memcpy(this->data.get(), src, len);
+  }
+};
 
 enum ModbusRole {
   CLIENT,
@@ -52,6 +65,7 @@ class Modbus : public uart::UARTDevice, public Component {
   void receive_and_parse_modbus_bytes_();
   void clear_rx_buffer_(const std::string &reason, bool warn = false);
   void send_next_frame_();
+  void transmit_frame_(const uint8_t *data, uint16_t size);
 
   uint32_t last_modbus_byte_{0};
   uint32_t last_send_{0};
@@ -67,10 +81,11 @@ class Modbus : public uart::UARTDevice, public Component {
 
   std::vector<uint8_t> rx_buffer_;
   std::vector<ModbusDevice *> devices_;
-  // std::queue is appropriate here since we need a FIFO buffer, and we can't know ahead of time how many
-  // requests will be queued. Each modbus component may queue multiple requests, and the sequence of scheduling
-  // may change at run time.
-  std::queue<std::vector<uint8_t>> tx_buffer_;
+  // Vector for FIFO buffer - with sync-first sending, this is usually empty.
+  // Using vector instead of deque-backed queue to avoid deque's 512-byte minimum allocation.
+  // Index-based front tracking avoids O(n) erase on each pop.
+  std::vector<TxFrame> tx_buffer_;
+  size_t tx_buffer_front_{0};
 };
 
 class ModbusDevice {
```

Comment (bdraco) [reply esphome/components/modbus/modbus.h]: even with 15 messages backed up there is a good chance it uses less memory than the deque

Comment (bdraco) [reply esphome/components/modbus/modbus.h]: and if we are worried about frames backing up, we could force compact the vector when it hits 15 pending in the tx buffer with something like
```diff
diff --git a/esphome/components/modbus/modbus.cpp b/esphome/components/modbus/modbus.cpp
index 8a65eb4ad4..55d99faab2 100644
--- a/esphome/components/modbus/modbus.cpp
+++ b/esphome/components/modbus/modbus.cpp
@@ -2,6 +2,7 @@
 #include "esphome/core/application.h"
 #include "esphome/core/helpers.h"
 #include "esphome/core/log.h"
+#include <cstring>
 
 namespace esphome {
 namespace modbus {
@@ -55,7 +56,7 @@ void Modbus::loop() {
   }
 
   // If there's no response pending and there's commands in the buffer
-  if (!this->tx_blocked() && !this->tx_buffer_.empty()) {
+  if (!this->tx_blocked() && this->tx_buffer_front_ < this->tx_buffer_.size()) {
     this->defer("send_next_frame", [this]() { this->send_next_frame_(); });
   }
 }
@@ -77,7 +78,7 @@ bool Modbus::tx_blocked() {
           this->frame_delay_ms_ + (this->role == ModbusRole::CLIENT ? this->turnaround_delay_ms_ : 0));
 }
 
-bool Modbus::tx_buffer_empty() { return this->tx_buffer_.empty(); }
+bool Modbus::tx_buffer_empty() { return this->tx_buffer_front_ >= this->tx_buffer_.size(); }
 
 void Modbus::receive_and_parse_modbus_bytes_() {
   while (this->available()) {
@@ -251,41 +252,53 @@ bool Modbus::parse_modbus_byte_(uint8_t byte) {
 }
 
 void Modbus::send_next_frame_() {
-  if (this->tx_buffer_.empty())
+  if (this->tx_buffer_front_ >= this->tx_buffer_.size())
     return;
 
   if (this->tx_blocked())
     return;
 
-  std::vector<uint8_t> data = this->tx_buffer_.front();
+  TxFrame &frame = this->tx_buffer_[this->tx_buffer_front_];
 
+  this->transmit_frame_(frame.data.get(), frame.size);
+
+  this->tx_buffer_front_++;
+
+  // Compact when all frames consumed or when we've consumed 15+ frames
+  if (this->tx_buffer_front_ >= this->tx_buffer_.size()) {
+    this->tx_buffer_.clear();
+    this->tx_buffer_front_ = 0;
+  } else if (this->tx_buffer_front_ >= MODBUS_TX_BUFFER_COMPACTION_THRESHOLD) {
+    this->tx_buffer_.erase(this->tx_buffer_.begin(), this->tx_buffer_.begin() + this->tx_buffer_front_);
+    this->tx_buffer_front_ = 0;
+    ESP_LOGV(TAG, "Write queue contains %d items.", this->tx_buffer_.size());
+  } else {
+    ESP_LOGV(TAG, "Write queue contains %d items.", this->tx_buffer_.size() - this->tx_buffer_front_);
+  }
+}
+
+void Modbus::transmit_frame_(const uint8_t *data, uint16_t size) {
   if (this->role == ModbusRole::CLIENT) {
     this->waiting_for_response_ = data[0];
   }
 
   if (this->flow_control_pin_ != nullptr) {
     this->flow_control_pin_->digital_write(true);
-    this->write_array(data);
+    this->write_array(data, size);
     this->flush();
     this->flow_control_pin_->digital_write(false);
     this->last_send_tx_offset_ = 0;
   } else {
-    this->write_array(data);
-    this->last_send_tx_offset_ = data.size() * 11 * 1000 / this->parent_->get_baud_rate() + 1;
+    this->write_array(data, size);
+    this->last_send_tx_offset_ = size * 11 * 1000 / this->parent_->get_baud_rate() + 1;
   }
 
-  this->tx_buffer_.pop();
-
 #if ESPHOME_LOG_LEVEL >= ESPHOME_LOG_LEVEL_VERBOSE
   char hex_buf[format_hex_pretty_size(MODBUS_MAX_LOG_BYTES)];
 #endif
-  ESP_LOGV(TAG, "Write: %s %dms after last send", format_hex_pretty_to(hex_buf, data.data(), data.size()),
+  ESP_LOGV(TAG, "Write: %s %dms after last send", format_hex_pretty_to(hex_buf, data, size),
            millis() - this->last_send_);
   this->last_send_ = millis();
-
-  if (!this->tx_buffer_.empty()) {
-    ESP_LOGV(TAG, "Write queue contains %d items.", this->tx_buffer_.size());
-  }
 }
 
 void Modbus::dump_config() {
@@ -316,32 +329,69 @@ void Modbus::send(uint8_t address, uint8_t function_code, uint16_t start_address
     return;
   }
 
-  std::vector<uint8_t> data;
-  data.push_back(address);
-  data.push_back(function_code);
+  // Calculate frame size upfront to avoid vector reallocation
+  // Frame: address(1) + function(1) + [start_addr(2) + num_entities(2)] + [byte_count(1)] + payload + CRC(2)
+  uint16_t frame_size = 2;  // address + function_code
   if (this->role == ModbusRole::CLIENT) {
-    data.push_back(start_address >> 8);
-    data.push_back(start_address >> 0);
+    frame_size += 2;  // start_address
     if (function_code != ModbusFunctionCode::WRITE_SINGLE_COIL &&
         function_code != ModbusFunctionCode::WRITE_SINGLE_REGISTER) {
-      data.push_back(number_of_entities >> 8);
-      data.push_back(number_of_entities >> 0);
+      frame_size += 2;  // number_of_entities
     }
   }
-
+  uint8_t actual_payload_len = 0;
   if (payload != nullptr) {
     if (this->role == ModbusRole::SERVER || function_code == ModbusFunctionCode::WRITE_MULTIPLE_COILS ||
-        function_code == ModbusFunctionCode::WRITE_MULTIPLE_REGISTERS) {  // Write multiple
-      data.push_back(payload_len);                                        // Byte count is required for write
+        function_code == ModbusFunctionCode::WRITE_MULTIPLE_REGISTERS) {
+      frame_size += 1;  // byte_count
+      actual_payload_len = payload_len;
     } else {
-      payload_len = 2;  // Write single register or coil
+      actual_payload_len = 2;  // Write single register or coil
     }
-    for (int i = 0; i < payload_len; i++) {
-      data.push_back(payload[i]);
+    frame_size += actual_payload_len;
+  }
+  frame_size += 2;  // CRC
+
+  // Use stack buffer - Modbus frames are small and bounded
+  uint8_t data[MODBUS_MAX_FRAME_SIZE];
+  uint16_t pos = 0;
+
+  data[pos++] = address;
+  data[pos++] = function_code;
+  if (this->role == ModbusRole::CLIENT) {
+    data[pos++] = start_address >> 8;
+    data[pos++] = start_address & 0xFF;
+    if (function_code != ModbusFunctionCode::WRITE_SINGLE_COIL &&
+        function_code != ModbusFunctionCode::WRITE_SINGLE_REGISTER) {
+      data[pos++] = number_of_entities >> 8;
+      data[pos++] = number_of_entities & 0xFF;
+    }
+  }
+
+  if (payload != nullptr) {
+    if (this->role == ModbusRole::SERVER || function_code == ModbusFunctionCode::WRITE_MULTIPLE_COILS ||
+        function_code == ModbusFunctionCode::WRITE_MULTIPLE_REGISTERS) {
+      data[pos++] = actual_payload_len;  // Byte count
     }
+    std::memcpy(data + pos, payload, actual_payload_len);
+    pos += actual_payload_len;
   }
 
-  send_raw(data);
+  auto crc = crc16(data, pos);
+  data[pos++] = crc & 0xFF;
+  data[pos++] = crc >> 8;
+
+  // Try to send synchronously if possible, otherwise queue
+  if (!this->tx_blocked() && this->tx_buffer_empty()) {
+    this->transmit_frame_(data, pos);
+  } else if (this->tx_buffer_.size() < MODBUS_TX_BUFFER_SIZE) {
+    this->tx_buffer_.emplace_back(data, pos);
+  } else {
+#if ESPHOME_LOG_LEVEL >= ESPHOME_LOG_LEVEL_ERROR
+    char hex_buf[format_hex_pretty_size(MODBUS_MAX_LOG_BYTES)];
+#endif
+    ESP_LOGE(TAG, "Write buffer full, dropped: %s", format_hex_pretty_to(hex_buf, data, pos));
+  }
 }
 
 // Helper function for lambdas
@@ -350,19 +400,28 @@ void Modbus::send_raw(const std::vector<uint8_t> &payload) {
   if (payload.empty()) {
     return;
   }
-  std::vector<uint8_t> data = payload;
 
-  auto crc = crc16(data.data(), data.size());
-  data.push_back(crc >> 0);
-  data.push_back(crc >> 8);
+  // Frame size: payload + CRC(2)
+  size_t frame_size = payload.size() + 2;
+
+  // Use stack buffer - Modbus frames are small and bounded
+  uint8_t data[MODBUS_MAX_FRAME_SIZE];
+
+  std::memcpy(data, payload.data(), payload.size());
+  auto crc = crc16(data, payload.size());
+  data[payload.size()] = crc & 0xFF;
+  data[payload.size() + 1] = crc >> 8;
 
-  if (this->tx_buffer_.size() < MODBUS_TX_BUFFER_SIZE) {
-    this->tx_buffer_.push(data);
+  // Try to send synchronously if possible, otherwise queue
+  if (!this->tx_blocked() && this->tx_buffer_empty()) {
+    this->transmit_frame_(data, frame_size);
+  } else if (this->tx_buffer_.size() < MODBUS_TX_BUFFER_SIZE) {
+    this->tx_buffer_.emplace_back(data, frame_size);
   } else {
 #if ESPHOME_LOG_LEVEL >= ESPHOME_LOG_LEVEL_ERROR
     char hex_buf[format_hex_pretty_size(MODBUS_MAX_LOG_BYTES)];
 #endif
-    ESP_LOGE(TAG, "Write buffer full, dropped: %s", format_hex_pretty_to(hex_buf, data.data(), data.size()));
+    ESP_LOGE(TAG, "Write buffer full, dropped: %s", format_hex_pretty_to(hex_buf, data, frame_size));
   }
 }
 
diff --git a/esphome/components/modbus/modbus.h b/esphome/components/modbus/modbus.h
index 60a2e13996..a5c3cfea40 100644
--- a/esphome/components/modbus/modbus.h
+++ b/esphome/components/modbus/modbus.h
@@ -5,13 +5,28 @@
 
 #include "esphome/components/modbus/modbus_definitions.h"
 
+#include <cstring>
+#include <memory>
 #include <vector>
-#include <queue>
 
 namespace esphome {
 namespace modbus {
 
-static const uint16_t MODBUS_TX_BUFFER_SIZE = 100;
+static constexpr uint16_t MODBUS_TX_BUFFER_SIZE = 100;
+// Maximum Modbus RTU frame size (for stack allocation)
+static constexpr size_t MODBUS_MAX_FRAME_SIZE = 256;
+// Compact tx_buffer_ when this many frames have been consumed
+static constexpr size_t MODBUS_TX_BUFFER_COMPACTION_THRESHOLD = 15;
+
+// Tx frame with exact-size allocation to avoid std::vector overhead
+struct TxFrame {
+  std::unique_ptr<uint8_t[]> data;
+  uint16_t size;  // Modbus RTU max is 256 bytes
+
+  TxFrame(const uint8_t *src, uint16_t len) : data(std::make_unique<uint8_t[]>(len)), size(len) {
+    std::memcpy(this->data.get(), src, len);
+  }
+};
 
 enum ModbusRole {
   CLIENT,
@@ -52,6 +67,7 @@ class Modbus : public uart::UARTDevice, public Component {
   void receive_and_parse_modbus_bytes_();
   void clear_rx_buffer_(const std::string &reason, bool warn = false);
   void send_next_frame_();
+  void transmit_frame_(const uint8_t *data, uint16_t size);
 
   uint32_t last_modbus_byte_{0};
   uint32_t last_send_{0};
@@ -67,10 +83,10 @@ class Modbus : public uart::UARTDevice, public Component {
 
   std::vector<uint8_t> rx_buffer_;
   std::vector<ModbusDevice *> devices_;
-  // std::queue is appropriate here since we need a FIFO buffer, and we can't know ahead of time how many
-  // requests will be queued. Each modbus component may queue multiple requests, and the sequence of scheduling
-  // may change at run time.
-  std::queue<std::vector<uint8_t>> tx_buffer_;
+  // Vector for FIFO buffer - with sync-first sending, this is usually empty.
+  // Uses less memory than deque-backed queue even with 15+ messages queued.
+  std::vector<TxFrame> tx_buffer_;
+  size_t tx_buffer_front_{0};  // Index-based front for O(1) pop
 };
 
 class ModbusDevice {
```

But if need that it likely means we would crash anyways because the buffer is never shrinking .. so this version might be overkill (it will certainly use a lot flash than not having the compaction)

Comment (exciton) [reply esphome/components/modbus/modbus.h]: A scenario I have developed in a subsequent PR is one where we continuously poll devices by essentially placing commands back on the queue immediately - in this case the queue never empties, but also doesn't grow infinitely. It can still grow and shrink occasionally if there are one-time commands (like writes) that come through. 

For that purpose dequeue is a good choice.

File: esphome/components/modbus/modbus.cpp (hunk 38 above)
Comment (exciton) [reply esphome/components/modbus/modbus.cpp]: Good catch

Comment (exciton) [reply esphome/components/modbus/modbus.cpp]: Good catch

File: esphome/components/modbus/modbus.h (hunk 37 above)
Comment (exciton) [reply esphome/components/modbus/modbus.h]: Ok - did some testing on a few different variants of the tx_buffer based on the suggestions above, with the following results:

| Code Version | Base | NoVector | NoQueue |
| --- | --- | --- | --- |
| Storage | std::deque<std::vector<uint8_t>> | std::deque\<TxFrame> | std::vector\<TxFrame> |
| Image size | 838675 bytes | 838747 (+72) | 838591 (-84) |
| LOC | 0 | +22 | +37 |
| Mean Heap free | 259711 bytes | 259510 (-201) | 260266 (+756) |
| Min heap free | 252380 bytes | 243100 (-9280) | 251656 (-724) |
| Fragmentation | 16.4% | 16.4%  | 16.6% (+0.2) |

Min heap free is very stochastic - it changes rapidly in the first few minutes then settles out, and lands on a different value each time the device is reset. I wouldn't say the differences here are meaningful.

Mean Heap free is more stable - I took averages after the startup settling time. However it also settles on a slightly different value each restart, so the differences above should be taken with a grain of sale.

Fragmentation is extremely stable, it jumps around by only ~0.1% for all examples.

If you're interested to see what was tested the code is:
Base (this PR): https://github.com/exciton/esphome/commit/661e26d1209a5c89d6dda84a218157aa6eebb7d1
NoVector: https://github.com/exciton/esphome/commit/cf1158c41143e6e0cdb8d83f1ce7966a3191d89b
NoQueue: https://github.com/exciton/esphome/commit/d6b7dbf44de9fc9d73792cd0d8270a0fa7a8741c

A couple of ideas in the above code weren't incorporated (but can be later):
- Transmitting without queuing. This is a small optimisation in most cases where multiple registers are requested at once. After we split server and client mode (which completely eliminates the queue for server mode) and simplify the API - then it makes sense to make this optimisation.
- Avoid std::vector in ::send(). This function is being refactored completely in subsequent PRs. Better optimise after deleting the unnecessary stuff in there.

I incorporated the heap allocation suggestions already.

I would recommend we either stick with the Base implementation, or use the NoVector option. It's a fairly straightforward change, and easy to understand what's happening. The vector-as-queue option with occasional compaction is a quite error prone (e.g. it's easy to accidentally use front() and not get the front), and adds a bunch of code to maintain. This approach would be better off as a tested, reusable template that re-implements a proper front() and hides the implementation details, if we want something like that.

@bdraco - open to further feedback.

**Comment by exciton** [comment]
Merged dev again. Good to go now.

File: esphome/components/modbus/modbus.cpp [hunk 39]
```diff
@@ -15,55 +15,93 @@ void Modbus::setup() {
...
+  // when the buffer is filling the back half of the response
+  const uint16_t timeout = std::max(
+      (uint16_t) this->frame_delay_ms_,
+      (uint16_t) (this->rx_buffer_.size() > this->parent_->get_rx_full_threshold() - 1 ? this->long_rx_buffer_delay_ms_
+                                                                                       : 0));
+  // We use millis() here and elsewhere instead of App.get_loop_component_start_time() to avoid stale timestamps
+  // It's critical in all timestamp comparisons that the left timestamp comes before the right one in time
+  // If we use a cached value in place of millis() and last_modbus_byte_ is updated inside our loop
+  // then the comparison is backwards (small negative which wraps to large positive) and will cause a false timeout
+  // So in this component we don't use any cached timestamp values to avoid these annoying bugs
```
Comment (bdraco) [inline esphome/components/modbus/modbus.cpp:43]: Ideally we don't call `millis()` in loop and use `App.get_loop_component_start_time()` everywhere

As long as we use the same time source constantly, it should be fine to use `App.get_loop_component_start_time()` unless there is time being set outside the loop or something blocks the loop for a long time in this component which is another issue.

The problem arises when we mix

File: esphome/components/modbus/modbus.cpp [hunk 40]
```diff
@@ -290,23 +356,34 @@ void Modbus::send_raw(const std::vector<uint8_t> &payload) {
...
+#if ESPHOME_LOG_LEVEL >= ESPHOME_LOG_LEVEL_ERROR
+    char hex_buf[format_hex_pretty_size(MODBUS_MAX_LOG_BYTES)];
 #endif
-  ESP_LOGV(TAG, "Modbus write raw: %s", format_hex_pretty_to(hex_buf, payload.data(), payload.size()));
-  last_send_ = millis();
+    ESP_LOGE(TAG, "Write buffer full, dropped: %s", format_hex_pretty_to(hex_buf, data.data(), data.size()));
+  }
+}
+
+void Modbus::clear_rx_buffer_(const std::string &reason, bool warn) {
```
Comment (bdraco) [inline esphome/components/modbus/modbus.cpp]:
```suggestion
void Modbus::clear_rx_buffer_(const char *reason, bool warn) {
```

Right now this allocates a string on the heap every time

File: esphome/components/modbus/modbus.cpp [hunk 41]
```diff
@@ -15,55 +15,93 @@ void Modbus::setup() {
...
   }
 
-  if (now - this->last_modbus_byte_ > 50) {
-    size_t at = this->rx_buffer_.size();
-    if (at > 0) {
-      ESP_LOGV(TAG, "Clearing buffer of %d bytes - timeout", at);
-      this->rx_buffer_.clear();
+  // If there's no response pending and there's commands in the buffer
+  if (!this->tx_blocked() && !this->tx_buffer_.empty()) {
+    this->defer("send_next_frame", [this]() { this->send_next_frame_(); });
```
Comment (bdraco) [inline esphome/components/modbus/modbus.cpp]: This should be managed in the loop's lifecycle to defer to the next loop, we should not use defer here as it churns the scheduler

File: esphome/components/modbus/modbus.h [hunk 42]
```diff
@@ -30,28 +33,44 @@ class Modbus : public uart::UARTDevice, public Component {
...
+
+  uint32_t last_modbus_byte_{0};
+  uint32_t last_send_{0};
+  uint32_t last_send_tx_offset_{0};
+  uint16_t frame_delay_ms_{5};
+  uint16_t long_rx_buffer_delay_ms_{0};
   uint16_t send_wait_time_{250};
+  uint16_t turnaround_delay_ms_{100};
+  uint8_t waiting_for_response_{0};
   bool disable_crc_;
```
Comment (bdraco) [inline esphome/components/modbus/modbus.h]:
```suggestion
  bool disable_crc_{false};
```

nit

File: esphome/components/modbus/modbus.h [hunk 43]
```diff
@@ -30,28 +33,44 @@ class Modbus : public uart::UARTDevice, public Component {
...
+  bool tx_buffer_empty();
+  bool tx_blocked();
 
   void send(uint8_t address, uint8_t function_code, uint16_t start_address, uint16_t number_of_entities,
             uint8_t payload_len = 0, const uint8_t *payload = nullptr);
   void send_raw(const std::vector<uint8_t> &payload);
   void set_role(ModbusRole role) { this->role = role; }
   void set_flow_control_pin(GPIOPin *flow_control_pin) { this->flow_control_pin_ = flow_control_pin; }
-  uint8_t waiting_for_response{0};
   void set_send_wait_time(uint16_t time_in_ms) { send_wait_time_ = time_in_ms; }
```
Comment (bdraco) [inline esphome/components/modbus/modbus.h]:
```suggestion
  void set_send_wait_time(uint16_t time_in_ms) { this->send_wait_time_ = time_in_ms; }
```

File: esphome/components/modbus/modbus.h [hunk 44]
```diff
@@ -30,28 +33,44 @@ class Modbus : public uart::UARTDevice, public Component {
...
+  void set_turnaround_time(uint16_t time_in_ms) { turnaround_delay_ms_ = time_in_ms; }
```
Comment (bdraco) [inline esphome/components/modbus/modbus.h]:
```suggestion
  void set_turnaround_time(uint16_t time_in_ms) { this->turnaround_delay_ms_ = time_in_ms; }
```

File: esphome/components/modbus/modbus.h [hunk 45]
```diff
@@ -30,28 +33,44 @@ class Modbus : public uart::UARTDevice, public Component {
...
   void set_disable_crc(bool disable_crc) { disable_crc_ = disable_crc; }
```
Comment (bdraco) [inline esphome/components/modbus/modbus.h]:
```suggestion
  void set_disable_crc(bool disable_crc) { this->disable_crc_ = disable_crc; }
```

existing but its in the view

File: esphome/components/modbus/modbus.cpp [hunk 46]
```diff
@@ -228,60 +322,32 @@ void Modbus::send(uint8_t address, uint8_t function_code, uint16_t start_address
...
-
-  if (this->flow_control_pin_ != nullptr)
-    this->flow_control_pin_->digital_write(false);
-  waiting_for_response = address;
-  last_send_ = millis();
-#if ESPHOME_LOG_LEVEL >= ESPHOME_LOG_LEVEL_VERBOSE
-  char hex_buf[format_hex_pretty_size(MODBUS_MAX_LOG_BYTES)];
-#endif
-  ESP_LOGV(TAG, "Modbus write: %s", format_hex_pretty_to(hex_buf, data, pos));
+  send_raw(data);
```
Comment (bdraco) [inline esphome/components/modbus/modbus.cpp]:
```suggestion
  this->send_raw(data);
```

File: esphome/components/modbus/modbus.cpp [hunk 47]
```diff
@@ -15,55 +15,93 @@ void Modbus::setup() {
...
-    avail -= to_read;
+  // First process all available incoming data.
+  this->receive_and_parse_modbus_bytes_();
+
+  // If the response frame is finished (including interframe delay) - we timeout.
+  // The long_rx_buffer_delay accounts for long responses (larger than the UART rx_full_threshold) to avoid timeouts
+  // when the buffer is filling the back half of the response
+  const uint16_t timeout = std::max(
+      (uint16_t) this->frame_delay_ms_,
+      (uint16_t) (this->rx_buffer_.size() > this->parent_->get_rx_full_threshold() - 1 ? this->long_rx_buffer_delay_ms_
```
Comment (bdraco) [inline esphome/components/modbus/modbus.cpp]:
```suggestion
      (uint16_t) (this->rx_buffer_.size() >= this->parent_->get_rx_full_threshold() ? this->long_rx_buffer_delay_ms_
```

looks like this can underflow ?

File: esphome/components/modbus/modbus.cpp [hunk 48]
```diff
@@ -15,55 +15,93 @@ void Modbus::setup() {
   if (this->flow_control_pin_ != nullptr) {
     this->flow_control_pin_->setup();
   }
+
+  this->frame_delay_ms_ =
+      std::max(2,  // 1750us minimium per spec - rounded up to 2ms.
```
Comment (bdraco) [inline esphome/components/modbus/modbus.cpp]:
```suggestion
      std::max(2,  // 1750us minimum per spec - rounded up to 2ms.
```

File: esphome/components/modbus/modbus.h [hunk 49]
```diff
@@ -6,10 +6,13 @@
 #include "esphome/components/modbus/modbus_definitions.h"
 
 #include <vector>
+#include <queue>
 
 namespace esphome {
 namespace modbus {
 
+static const uint16_t MODBUS_TX_BUFFER_SIZE = 100;
```
Comment (bdraco) [inline esphome/components/modbus/modbus.h]:
```suggestion
static constexpr uint16_t MODBUS_TX_BUFFER_SIZE = 100;
```

File: esphome/components/modbus/modbus.cpp [hunk 50]
```diff
@@ -290,23 +356,34 @@ void Modbus::send_raw(const std::vector<uint8_t> &payload) {
   if (payload.empty()) {
     return;
   }
+  std::vector<uint8_t> data = payload;
```
Comment (bdraco) [inline esphome/components/modbus/modbus.cpp]: please avoid allocating vector on the stack

File: esphome/components/modbus/modbus.cpp [hunk 51]
```diff
@@ -15,55 +15,93 @@ void Modbus::setup() {
...
+         (now - this->last_modbus_byte_ <
+          this->frame_delay_ms_ + (this->role == ModbusRole::CLIENT ? this->turnaround_delay_ms_ : 0));
+}
+
+bool Modbus::tx_buffer_empty() { return this->tx_buffer_.empty(); }
+
+void Modbus::receive_and_parse_modbus_bytes_() {
+  while (this->available()) {
+    uint8_t byte;
+    this->read_byte(&byte);
```
Comment (bdraco) [inline esphome/components/modbus/modbus.cpp]: The old version read up to 64 bytes at a time. This is a regression to the single byte reads

File: esphome/components/modbus/modbus.cpp (hunk 40 above)
Comment (bdraco) [reply esphome/components/modbus/modbus.cpp]: Actually should use LogString

File: esphome/components/modbus_controller/__init__.py [hunk 52]
```diff
@@ -56,8 +57,8 @@
 ServerCourtesyResponse = modbus_controller_ns.struct("ServerCourtesyResponse")
 ServerRegister = modbus_controller_ns.struct("ServerRegister")
 
-ModbusFunctionCode_ns = modbus_controller_ns.namespace("ModbusFunctionCode")
-ModbusFunctionCode = ModbusFunctionCode_ns.enum("ModbusFunctionCode")
+ModbusFunctionCode_ns = modbus_ns.namespace("FunctionCode")
+ModbusFunctionCode = ModbusFunctionCode_ns.enum("FunctionCode")
```
Comment (bdraco) [inline esphome/components/modbus_controller/__init__.py]: This doesn't match the cpp code `modbus_controller::ModbusFunctionCode::ModbusFunctionCode`

File: esphome/components/modbus/modbus.h (hunk 37 above)
Comment (bdraco) [reply esphome/components/modbus/modbus.h]: Ring buffer would be the way to go here but since we don't know the bounds I think we are stuck with the queue for now. We can optimize it later

File: esphome/components/modbus/modbus.cpp (hunk 39 above)
Comment (exciton) [reply esphome/components/modbus/modbus.cpp:43]: Understood on the intent here - there are calls in modbus that originate outside its loop (e.g. when another component sends), and there can be significant time delays internally (e.g. a write to UART with flush).

This version is well tested, so I'd prefer not to mess with it in this PR.

The calls to millis() are significantly reduced in a future PR #11969 - the next one in the series. See commit here: https://github.com/exciton/esphome/commit/ce5d1b9e2113db995d105a35e420a14e77058d82

File: esphome/components/modbus/modbus.cpp (hunk 41 above)
Comment (exciton) [reply esphome/components/modbus/modbus.cpp]: Without defer this component will give the infamous "component took a long time for an operation" for  writes at typical RS485 baud rates when software flow control is used. At 9600 baud 30 bytes = 30 ms. 

Can remove if preferred - it's not a functionality concern.

File: esphome/components/modbus/modbus.cpp (hunk 47 above)
Comment (exciton) [reply esphome/components/modbus/modbus.cpp]: Should be 1 or greater - but fair point.

File: esphome/components/modbus/modbus.cpp (hunk 51 above)
Comment (exciton) [reply esphome/components/modbus/modbus.cpp]: A subsequent PR #12421 changes this to read all at once - see here: https://github.com/exciton/esphome/commit/b1ada156fb1f9008851c60e5944bf28420855d89 

The issue is that the current implementation parses bytes one at a time (which is also inefficient), so reading chunks of bytes from UART means double-handling them while feeding them to the parser. 

I can backport the UART read-once method from PR #12421 into PR #11969 (which parses whole frames at once) to get what we want after the next PR is merged. 

I could also reenable the 64-byte double handling method for now, but not sure it buys us much. Reading one byte at a time has been there for years and noone complained ;)

File: esphome/components/modbus_controller/__init__.py (hunk 52 above)
Comment (exciton) [reply esphome/components/modbus_controller/__init__.py]: Good catch. Seems this isn't actually used for anything anyway.

File: esphome/components/modbus/modbus.cpp (hunk 50 above)
Comment (exciton) [reply esphome/components/modbus/modbus.cpp]: Switched to a fixed-length array for frame storage.

File: esphome/components/modbus/modbus.cpp [hunk 53]
```diff
@@ -228,60 +322,32 @@ void Modbus::send(uint8_t address, uint8_t function_code, uint16_t start_address
...
-  static constexpr size_t MAX_PAYLOAD_SIZE = std::numeric_limits<uint8_t>::max();
-  static constexpr size_t CRC_SIZE = 2;
-  static constexpr size_t MAX_FRAME_SIZE =
-      ADDR_SIZE + FC_SIZE + START_ADDR_SIZE + NUM_ENTITIES_SIZE + BYTE_COUNT_SIZE + MAX_PAYLOAD_SIZE + CRC_SIZE;
-  uint8_t data[MAX_FRAME_SIZE];
-  size_t pos = 0;
-
-  data[pos++] = address;
-  data[pos++] = function_code;
+  std::vector<uint8_t> data;
```
Comment (bdraco) [inline esphome/components/modbus/modbus.cpp]: We have another vector on the stack here which means `send` has regressed to heap allocating in the hot path

File: esphome/components/modbus/modbus.cpp [hunk 54]
```diff
@@ -290,23 +356,42 @@ void Modbus::send_raw(const std::vector<uint8_t> &payload) {
...
+
+void Modbus::clear_rx_buffer_(const LogString *reason, bool warn) {
+  size_t at = this->rx_buffer_.size();
+  if (at > 0) {
+    if (warn) {
+      ESP_LOGW(TAG, "Clearing buffer of %d bytes - %s %dms after last send", at, LOG_STR_ARG(reason),
+               millis() - this->last_send_);
+    } else {
+      ESP_LOGV(TAG, "Clearing buffer of %d bytes - %s %dms after last send", at, LOG_STR_ARG(reason),
+               millis() - this->last_send_);
```
Comment (bdraco) [inline esphome/components/modbus/modbus.cpp]: millis() is uint32_t

Please use PRIu32

File: esphome/components/modbus/modbus.h [hunk 55]
```diff
@@ -76,7 +107,7 @@ class ModbusDevice {
     this->send_raw(error_response);
   }
   // If more than one device is connected block sending a new command before a response is received
-  bool waiting_for_response() { return parent_->waiting_for_response != 0; }
```
Comment (bdraco) [inline esphome/components/modbus/modbus.h:79]: Removing this is a breaking change

File: esphome/components/modbus/modbus.h [hunk 56]
```diff
@@ -76,7 +107,7 @@ class ModbusDevice {
...
+  bool ready_for_immediate_send() { return parent_->tx_buffer_empty() && !parent_->tx_blocked(); }
```
Comment (bdraco) [inline esphome/components/modbus/modbus.h:116]:
```suggestion
  ESPDEPRECATED("Use ready_for_immediate_send() instead. Removed in 2026.9.0", "2026.3.0")
  bool waiting_for_response() { return !ready_for_immediate_send(); }
  bool ready_for_immediate_send() { return parent_->tx_buffer_empty() && !parent_->tx_blocked(); }
```

File: esphome/components/modbus/modbus.h [hunk 57]
```diff
@@ -30,28 +45,44 @@ class Modbus : public uart::UARTDevice, public Component {
...
+  uint16_t send_wait_time_{250};
+  uint16_t turnaround_delay_ms_{100};
+  uint8_t waiting_for_response_{0};
+  bool disable_crc_{false};
+
+  GPIOPin *flow_control_pin_{nullptr};
+
+  std::vector<uint8_t> rx_buffer_;
   std::vector<ModbusDevice *> devices_;
+  // std::dequeue is appropriate here since we need a FIFO buffer, and we can't know ahead of time how many
```
Comment (bdraco) [inline esphome/components/modbus/modbus.h]:
```suggestion
  // std::deque is appropriate here since we need a FIFO buffer, and we can't know ahead of time how many
```

File: esphome/components/modbus/modbus.cpp [hunk 58]
```diff
@@ -15,55 +15,93 @@ void Modbus::setup() {
...
 
-  if (now - this->last_modbus_byte_ > 50) {
-    size_t at = this->rx_buffer_.size();
-    if (at > 0) {
-      ESP_LOGV(TAG, "Clearing buffer of %d bytes - timeout", at);
-      this->rx_buffer_.clear();
+  // If there's no response pending and there's commands in the buffer
+  if (!this->tx_blocked() && !this->tx_buffer_.empty()) {
+    this->send_next_frame_();
+  }
```
Comment (bdraco) [inline esphome/components/modbus/modbus.cpp]: there is a double tx_blocked check here.  send_next_frame_ checks it and we check it here. Both do another millis() call

File: esphome/components/modbus/modbus.h [hunk 59]
```diff
@@ -5,18 +5,33 @@
...
 
+#include <cstring>
+#include <memory>
 #include <vector>
+#include <queue>
 
 namespace esphome {
 namespace modbus {
 
+static constexpr uint16_t MODBUS_TX_BUFFER_SIZE = 100;
```
Comment (bdraco) [inline esphome/components/modbus/modbus.h]: 100 seems large here since each is doing a heap allocation. This likely won't prevent the OOM scenerio its designed to protect against on constrained devices.

File: tests/integration/test_uart_mock_modbus.py [hunk 60]
```diff
@@ -74,20 +99,52 @@ def on_state(state: EntityState) -> None:
...
+            )
+        except TimeoutError:
+            pass  # Expected timeout since we never inject a response for late_response
+
+        try:
+            await asyncio.wait_for(no_response_changed, timeout=5.0)
+            pytest.fail(
+                f"no_response change should not have been triggered, but was. Received sensor states:\n"
+                f"  no_response: {sensor_states['no_response']}\n"
+            )
```
Comment (bdraco) [inline tests/integration/test_uart_mock_modbus.py:129]: 5s timeout is likely a bit overkill with a 200ms send wait time. It should fail long before this. 

I'd go with 1s or 1.5s

File: esphome/components/modbus/modbus.h (hunk 59 above)
Comment (exciton) [reply esphome/components/modbus/modbus.h]: What's the best way to calculate a good number here? Most requests would be 7-10 bytes of frame data plus overhead.

File: esphome/components/modbus/modbus.cpp (hunk 51 above)
Comment (exciton) [reply esphome/components/modbus/modbus.cpp]: Reenabled the 64-byte mode for now. Subsequent PRs will just pull the whole buffer in one hit.

File: esphome/components/modbus/modbus.cpp (hunk 53 above)
Comment (exciton) [reply esphome/components/modbus/modbus.cpp]: Fixed

File: esphome/components/modbus/modbus.h (hunk 59 above)
Comment (bdraco) [reply esphome/components/modbus/modbus.h]: - deque overhead: minimum 512 bytes per block (deque allocates in 512-byte chunks regardless of element size)
  - 100 entries × 8 bytes = 800 bytes of struct storage (2 deque blocks)
  - 100 heap allocations for frame data: up to 100 × ~258 bytes = ~25 KB worst case, though typical Modbus frames are ~10 bytes so more like 100 × ~12 bytes = ~1.2 KB. Pretty much guaranteed OOM on 8266 if frames are large

Since only components that don't check waiting_for_response would ever queue multiple, and it looks like ModbusController only queues 1 at a time, I'd go with 10-15 max, but even than something has gone very wrong.

Comment (exciton) [reply esphome/components/modbus/modbus.h]: Ok. The plan is to remove the queue from Modbus controller (PR is already written) and remove it's check to waiting_for_response, so I can set this to 15 for now, and increase it then we remove the ModbusController queue.

**Review by bdraco — APPROVED** [review]

**Comment by bdraco** [comment]
Thanks @exciton

**Comment by exciton** [comment]
Very welcome!
