### PR TITLE
DHT platform now supports modules with inbuilt external resistor

### LINKED ISSUE #4615: pi pico w doesn't read DHT22
### The problem

My pi pico w isn't getting data from a DHT22.  If I put micropython on the pi pico w, it reads the sensor as expected.

This is on ESPHome 2023.6.2

### Which version of ESPHome has the issue?

2023.6.2

### What type of installation are you using?

Home Assistant Add-on

### Which version of Home Assistant has the issue?

2023.6.3

### What platform are you using?

RP2040

### Board

pi pico w

### Component causing the issue

dht sensor

### Example YAML snippet

```yaml
sensor:
  - platform: dht
    pin: 5
    temperature:
      name: "DEV - Living Room Temperature"
    humidity:
      name: "DEV - Living Room Humidity"
    model: DHT22
    update_interval: 10s
```

### Anything in the logs that might be useful for us?

```txt
INFO ESPHome 2023.6.2
INFO Reading configuration /config/esphome/pico-dev.yaml...
INFO Generating C++ source...
INFO Compiling app...
Processing pico-dev (board: rpipicow; framework: arduino; platform: https://github.com/maxgerhardt/platform-raspberrypi.git)
--------------------------------------------------------------------------------
HARDWARE: RP2040 133MHz, 264KB RAM, 2MB Flash
 - framework-arduinopico @ 1.20604.0 (2.6.4) 
 - tool-rp2040tools @ 1.0.2 
Flash size: 2.00MB
Sketch size: 1.00MB
Filesystem size: 1.00MB
Maximium Sketch size: 1044480 EEPROM start: 0x101ff000 Filesystem start: 0x100ff000 Filesystem end: 0x101ff000
Dependency Graph
|-- WiFi @ 1.0.0
|-- LEAmDNS @ 1.2
|-- Updater @ 1.0
|-- noise-c @ 0.1.4
|-- MD5Builder @ 1.0.0
Compiling /data/pico-dev/.pioenvs/pico-dev/src/esphome/components/api/api_connection.cpp.o
Compiling /data/pico-dev/.pioenvs/pico-dev/src/esphome/components/api/api_frame_helper.cpp.o
Compiling /data/pico-dev/.pioenvs/pico-dev/src/esphome/components/api/api_pb2.cpp.o
Compiling /data/pico-dev/.pioenvs/pico-dev/src/esphome/components/api/api_pb2_service.cpp.o
Compiling /data/pico-dev/.pioenvs/pico-dev/src/esphome/components/api/api_server.cpp.o
Compiling /data/pico-dev/.pioenvs/pico-dev/src/esphome/components/api/list_entities.cpp.o
In file included from /data/cache/platformio/packages/toolchain-rp2040-earlephilhower/arm-none-eabi/include/c++/10.3.0/vector:72,
                 from /data/cache/platformio/packages/toolchain-rp2040-earlephilhower/arm-none-eabi/include/c++/10.3.0/functional:62,
                 from src/esphome/core/component.h:4,
                 from src/esphome/components/api/proto.h:3,
                 from src/esphome/components/api/api_pb2.h:5,
                 from src/esphome/components/api/api_pb2.cpp:3:
/data/cache/platformio/packages/toolchain-rp2040-earlephilhower/arm-none-eabi/include/c++/10.3.0/bits/vector.tcc: In member function 'void std::vector<_Tp, _Alloc>::_M_realloc_insert(std::vector<_Tp, _Alloc>::iterator, _Args&& ...) [with _Args = {esphome::api::BluetoothLERawAdvertisement}; _Tp = esphome::api::BluetoothLERawAdvertisement; _Alloc = std::allocator<esphome::api::BluetoothLERawAdvertisement>]':
/data/cache/platformio/packages/toolchain-rp2040-earlephilhower/arm-none-eabi/include/c++/10.3.0/bits/vector.tcc:426:7: note: parameter passing for argument of type 'std::vector<esphome::api::BluetoothLERawAdvertisement>::iterator' changed in GCC 7.1
  426 |       vector<_Tp, _Alloc>::
      |       ^~~~~~~~~~~~~~~~~~~
/data/cache/platformio/packages/toolchain-rp2040-earlephilhower/arm-none-eabi/include/c++/10.3.0/bits/vector.tcc: In member function 'virtual bool esphome::api::BluetoothLERawAdvertisementsResponse::decode_length(uint32_t, esphome::api::ProtoLengthDelimited)':
/data/cache/platformio/packages/toolchain-rp2040-earlephilhower/arm-none-eabi/include/c++/10.3.0/bits/vector.tcc:121:21: note: parameter passing for argument of type '__gnu_cxx::__normal_iterator<esphome::api::BluetoothLERawAdvertisement*, std::vector<esphome::api::BluetoothLERawAdvertisement> >' changed in GCC 7.1
  121 |    _M_realloc_insert(end(), std::forward<_Args>(__args)...);
      |    ~~~~~~~~~~~~~~~~~^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
/data/cache/platformio/packages/toolchain-rp2040-earlephilhower/arm-none-eabi/include/c++/10.3.0/bits/vector.tcc: In member function 'void std::vector<_Tp, _Alloc>::_M_realloc_insert(std::vector<_Tp, _Alloc>::iterator, _Args&& ...) [with _Args = {long long unsigned int}; _Tp = long long unsigned int; _Alloc = std::allocator<long long unsigned int>]':
/data/cache/platformio/packages/toolchain-rp2040-earlephilhower/arm-none-eabi/include/c++/10.3.0/bits/vector.tcc:426:7: note: parameter passing for argument of type 'std::vector<long long unsigned int>::iterator' changed in GCC 7.1
  426 |       vector<_Tp, _Alloc>::
      |       ^~~~~~~~~~~~~~~~~~~
/data/cache/platformio/packages/toolchain-rp2040-earlephilhower/arm-none-eabi/include/c++/10.3.0/bits/vector.tcc: In member function 'std::vector<_Tp, _Alloc>::reference std::vector<_Tp, _Alloc>::emplace_back(_Args&& ...) [with _Args = {long long unsigned int}; _Tp = long long unsigned int; _Alloc = std::allocator<long long unsigned int>]':
/data/cache/platformio/packages/toolchain-rp2040-earlephilhower/arm-none-eabi/include/c++/10.3.0/bits/vector.tcc:121:21: note: parameter passing for argument of type '__gnu_cxx::__normal_iterator<long long unsigned int*, std::vector<long long unsigned int> >' changed in GCC 7.1
  121 |    _M_realloc_insert(end(), std::forward<_Args>(__args)...);
      |    ~~~~~~~~~~~~~~~~~^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
Compiling /data/pico-dev/.pioenvs/pico-dev/src/esphome/components/api/proto.cpp.o
Compiling /data/pico-dev/.pioenvs/pico-dev/src/esphome/components/api/subscribe_state.cpp.o
Compiling /data/pico-dev/.pioenvs/pico-dev/src/esphome/components/api/user_services.cpp.o
Compiling /data/pico-dev/.pioenvs/pico-dev/src/esphome/components/dht/dht.cpp.o
Compiling /data/pico-dev/.pioenvs/pico-dev/src/esphome/components/logger/logger.cpp.o
Compiling /data/pico-dev/.pioenvs/pico-dev/src/esphome/components/md5/md5.cpp.o
Compiling /data/pico-dev/.pioenvs/pico-dev/src/esphome/components/mdns/mdns_component.cpp.o
Compiling /data/pico-dev/.pioenvs/pico-dev/src/esphome/components/mdns/mdns_esp32.cpp.o
Compiling /data/pico-dev/.pioenvs/pico-dev/src/esphome/components/mdns/mdns_esp8266.cpp.o
Compiling /data/pico-dev/.pioenvs/pico-dev/src/esphome/components/mdns/mdns_host.cpp.o
Compiling /data/pico-dev/.pioenvs/pico-dev/src/esphome/components/mdns/mdns_rp2040.cpp.o
Compiling /data/pico-dev/.pioenvs/pico-dev/src/esphome/components/network/util.cpp.o
Compiling /data/pico-dev/.pioenvs/pico-dev/src/esphome/components/ota/ota_backend_arduino_esp32.cpp.o
Compiling /data/pico-dev/.pioenvs/pico-dev/src/esphome/components/ota/ota_backend_arduino_esp8266.cpp.o
Compiling /data/pico-dev/.pioenvs/pico-dev/src/esphome/components/ota/ota_backend_arduino_rp2040.cpp.o
Compiling /data/pico-dev/.pioenvs/pico-dev/src/esphome/components/ota/ota_backend_esp_idf.cpp.o
Compiling /data/pico-dev/.pioenvs/pico-dev/src/esphome/components/ota/ota_component.cpp.o
Compiling /data/pico-dev/.pioenvs/pico-dev/src/esphome/components/rp2040/gpio.cpp.o
Compiling /data/pico-dev/.pioenvs/pico-dev/src/esphome/components/rp2040/preferences.cpp.o
Compiling /data/pico-dev/.pioenvs/pico-dev/src/esphome/components/sensor/automation.cpp.o
Compiling /data/pico-dev/.pioenvs/pico-dev/src/esphome/components/sensor/filter.cpp.o
Compiling /data/pico-dev/.pioenvs/pico-dev/src/esphome/components/sensor/sensor.cpp.o
Compiling /data/pico-dev/.pioenvs/pico-dev/src/esphome/components/socket/bsd_sockets_impl.cpp.o
Compiling /data/pico-dev/.pioenvs/pico-dev/src/esphome/components/socket/lwip_raw_tcp_impl.cpp.o
Compiling /data/pico-dev/.pioenvs/pico-dev/src/esphome/components/socket/socket.cpp.o
Compiling /data/pico-dev/.pioenvs/pico-dev/src/esphome/components/wifi/wifi_component.cpp.o
Compiling /data/pico-dev/.pioenvs/pico-dev/src/esphome/components/wifi/wifi_component_esp32_arduino.cpp.o
Compiling /data/pico-dev/.pioenvs/pico-dev/src/esphome/components/wifi/wifi_component_esp8266.cpp.o
Compiling /data/pico-dev/.pioenvs/pico-dev/src/esphome/components/wifi/wifi_component_esp_idf.cpp.o
Compiling /data/pico-dev/.pioenvs/pico-dev/src/esphome/components/wifi/wifi_component_pico_w.cpp.o
Compiling /data/pico-dev/.pioenvs/pico-dev/src/esphome/core/application.cpp.o
Compiling /data/pico-dev/.pioenvs/pico-dev/src/esphome/core/component.cpp.o
Compiling /data/pico-dev/.pioenvs/pico-dev/src/esphome/core/component_iterator.cpp.o
Compiling /data/pico-dev/.pioenvs/pico-dev/src/esphome/core/controller.cpp.o
Compiling /data/pico-dev/.pioenvs/pico-dev/src/esphome/core/entity_base.cpp.o
Compiling /data/pico-dev/.pioenvs/pico-dev/src/esphome/core/helpers.cpp.o
Compiling /data/pico-dev/.pioenvs/pico-dev/src/esphome/core/log.cpp.o
Compiling /data/pico-dev/.pioenvs/pico-dev/src/esphome/core/scheduler.cpp.o
Compiling /data/pico-dev/.pioenvs/pico-dev/src/esphome/core/string_ref.cpp.o
Compiling /data/pico-dev/.pioenvs/pico-dev/src/esphome/core/util.cpp.o
Compiling /data/pico-dev/.pioenvs/pico-dev/src/main.cpp.o
Linking /data/pico-dev/.pioenvs/pico-dev/firmware.elf
Generating UF2 image
elf2uf2 "/data/pico-dev/.pioenvs/pico-dev/firmware.elf" "/data/pico-dev/.pioenvs/pico-dev/firmware.uf2"
Flash size: 2.00MB
Sketch size: 1.00MB
Filesystem size: 1.00MB
Maximium Sketch size: 1044480 EEPROM start: 0x101ff000 Filesystem start: 0x100ff000 Filesystem end: 0x101ff000
RAM:   [===       ]  26.4% (used 69252 bytes from 262144 bytes)
Flash: [=====     ]  48.5% (used 506544 bytes from 1044480 bytes)
Building /data/pico-dev/.pioenvs/pico-dev/firmware.bin
Building /data/pico-dev/.pioenvs/pico-dev/firmware.bin.signed
========================= [SUCCESS] Took 38.47 seconds =========================
INFO Successfully compiled program.
INFO Resolving IP address of pico-dev.local
INFO  -> 192.168.1.9
INFO Uploading /data/pico-dev/.pioenvs/pico-dev/firmware.bin (518576 bytes)
Uploading: [============================================================] 100% Done...

INFO Waiting for result...
INFO OTA successful
INFO Successfully uploaded program.
INFO Starting log output from pico-dev.local using esphome API
WARNING Can't connect to ESPHome API for pico-dev.local: Error resolving IP address: [Errno -5] No address associated with hostname
INFO Trying to connect to pico-dev.local in the background
INFO Successfully connected to pico-dev.local
[16:10:41][I][app:102]: ESPHome version 2023.6.2 compiled on Jun 24 2023, 16:10:15
[16:10:41][C][wifi:543]: WiFi:
[16:10:41][C][wifi:379]:   Local MAC: XXXXX
[16:10:41][C][wifi:380]:   SSID: 'XXXXX'[redacted]
[16:10:41][C][wifi:381]:   IP Address: 192.168.1.9
[16:10:41][C][wifi:382]:   BSSID: XXXXXX[redacted]
[16:10:41][C][wifi:384]:   Hostname: 'pico-dev'
[16:10:41][C][wifi:386]:   Signal strength: -47 dB ▂▄▆█
[16:10:41][C][wifi:390]:   Channel: 6
[16:10:41][C][wifi:391]:   Subnet: 255.255.255.0
[16:10:41][C][wifi:392]:   Gateway: 192.168.1.1
[16:10:41][C][wifi:393]:   DNS1: 208.67.222.222
[16:10:41][C][wifi:394]:   DNS2: 208.67.220.220
[16:10:41][C][logger:301]: Logger:
[16:10:41][C][logger:302]:   Level: DEBUG
[16:10:41][C][logger:303]:   Log Baud Rate: 115200
[16:10:41][C][logger:305]:   Hardware UART: USB_CDC
[16:10:41][C][dht:017]: DHT:
[16:10:41][C][dht:018]:   Pin: GPIO5
[16:10:41][C][dht:024]:   Model: DHT22 (or equivalent)
[16:10:41][C][dht:027]:   Update Interval: 10.0s
[16:10:41][C][dht:029]:   Temperature 'DEV - Living Room Temperature'
[16:10:41][C][dht:029]:     Device Class: 'temperature'
[16:10:41][C][dht:029]:     State Class: 'measurement'
[16:10:41][C][dht:029]:     Unit of Measurement: '°C'
[16:10:41][C][dht:029]:     Accuracy Decimals: 1
[16:10:41][C][dht:030]:   Humidity 'DEV - Living Room Humidity'
[16:10:41][C][dht:030]:     Device Class: 'humidity'
[16:10:41][C][dht:030]:     State Class: 'measurement'
[16:10:41][C][dht:030]:     Unit of Measurement: '%'
[16:10:41][C][dht:030]:     Accuracy Decimals: 0
[16:10:41][C][mdns:108]: mDNS:
[16:10:41][C][mdns:109]:   Hostname: pico-dev
[16:10:41][C][ota:093]: Over-The-Air Updates:
[16:10:41][C][ota:094]:   Address: pico-dev.local:2040
[16:10:41][C][ota:097]:   Using Password.
[16:10:41][C][api:138]: API Server:
[16:10:41][C][api:139]:   Address: pico-dev.local:6053
[16:10:41][C][api:141]:   Using noise encryption: YES
[16:10:50][W][dht:169]: Requesting data from DHT failed!
[16:10:50][W][dht:060]: Invalid readings! Please check your wiring (pull-up resistor, pin number).
[16:10:50][D][sensor:093]: 'DEV - Living Room Temperature': Sending state inf °C with 1 decimals of accuracy
[16:10:50][D][sensor:093]: 'DEV - Living Room Humidity': Sending state inf % with 0 decimals of accuracy
[16:11:00][W][dht:169]: Requesting data from DHT failed!
[16:11:00][W][dht:060]: Invalid readings! Please check your wiring (pull-up resistor, pin number).
[16:11:00][D][sensor:093]: 'DEV - Living Room Temperature': Sending state inf °C with 1 decimals of accuracy
[16:11:00][D][sensor:093]: 'DEV - Living Room Humidity': Sending state inf % with 0 decimals of accuracy
```

### Additional information

here's the micropython code I used to check the functionality of the setup

from machine import Pin
from time import sleep
import dht

sensor = dht.DHT22(Pin(5))

while True:
    try:
        sleep(1)
        sensor.measure()
        # Retrieves measurements from the sensor
        print(f"Temperature : {sensor.temperature():.1f}")
        print(f"Humidity    : {sensor.humidity():.1f}")
        # Transmits the temperature to the terminal
    except OSError as e:
        print('Failed reception')
        # If the pico does not receive the measurements from the sensor

### PR DESCRIPTION
**Pull request by deCodeIt**
# What does this implement/fix?
The DHT11 and DHT22 modules that already have an external resistor were not returning any readings with the Raspberry Pi pico w ( RP2040 ) board. The root cause was the configuration of the internal pull-up resistor, which once disabled, the module worked properly and returned proper values.

The following DHT modules were used. They contain SMD 103 on-board resistor - 10K-Ohm.
DHT22 - https://quartzcomponents.com/products/dht22-temprature-and-humidity-sensor-module
DHT11 - https://quartzcomponents.com/products/dht11-temperature-humidity-sensor-module

## Types of changes

- [x] Bugfix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] Code quality improvements to existing code or addition of tests
- [ ] Other

**Related issue or feature (if applicable):**

- fixes https://github.com/esphome/issues/issues/4615 

**Pull request in [esphome-docs](https://github.com/esphome/esphome-docs) with documentation (if applicable):**

- esphome/esphome-docs#4673

## Test Environment

- [ ] ESP32
- [ ] ESP32 IDF
- [ ] ESP8266
- [x] RP2040
- [ ] BK72xx
- [ ] RTL87xx

## Example entry for `config.yaml`:

```yaml
  - platform: dht
    model: DHT22
    pin:
      number: GPIO19
      mode:
        input: true
        pullup: false
    temperature:
      name: "Room Temperature"
    humidity:
      name: "Room Humidity"
    update_interval: 5s

```

## Checklist:
  - [x] The code change is tested and works locally.
  - [ ] Tests have been added to verify that the new code works (under `tests/` folder).

If user exposed functionality or configuration variables are added/changed:
  - [ ] Documentation added/updated in [esphome-docs](https://github.com/esphome/esphome-docs).

### CODE REVIEW

**Comment by deCodeIt** [comment]
This patch does sound like a breaking change given that pullup: true needs to be configured in all existing configurations.

I'm thinking to use pulldown in the code changes so it becomes a non-breaking change as follows

```cpp
  if (this->pin_->get_flags() & gpio::FLAG_PULLDOWN) {
    flags = flags | gpio::FLAG_PULLDOWN;
  } else {
    flags = flags | gpio::FLAG_PULLUP;
  }
```

Let me know your thoughts on this.

Tagging @DjordjeMandic @jesserockz from a similar outdated PR https://github.com/esphome/esphome/pull/7752

**Comment by deCodeIt** [comment]
> This patch does sound like a breaking change given that pullup: true needs to be configured in all existing configurations.
> 
> I'm thinking to use pulldown in the code changes so it becomes a non-breaking change as follows
> 
> ```c++
>   if (this->pin_->get_flags() & gpio::FLAG_PULLDOWN) {
>     flags = flags | gpio::FLAG_PULLDOWN;
>   } else {
>     flags = flags | gpio::FLAG_PULLUP;
>   }
> ```
> 
> Let me know your thoughts on this.
> 
> Tagging @DjordjeMandic @jesserockz from a similar outdated PR #7752

Went ahead with the non-breaking change approach.

**Comment by DjordjeMandic** [comment]
Revert and use this in config schema https://github.com/esphome/esphome/blob/dev/esphome%2Fpins.py#L250-L256

File: esphome/components/dht/dht.cpp [hunk 1]
```diff
@@ -101,7 +101,14 @@ bool HOT IRAM_ATTR DHT::read_sensor_(float *temperature, float *humidity, bool r
   } else {
     delayMicroseconds(800);
   }
-  this->pin_->pin_mode(gpio::FLAG_INPUT | gpio::FLAG_PULLUP);
+
+  gpio::Flags flags = gpio::FLAG_INPUT;
+  if (this->pin_->get_flags() & gpio::FLAG_PULLDOWN) {
```
Comment (DjordjeMandic) [inline esphome/components/dht/dht.cpp]: Check if flag pullup is set and enable it only if so. If pullup flag is not set, set it to classic high impedance input.

**Review by DjordjeMandic — CHANGES_REQUESTED** [review]
https://github.com/esphome/esphome/blob/dev/esphome%2Fpins.py#L250-L256

Use this schema for CONF_PIN in config schema (sensor.py)

Edit: https://github.com/esphome/esphome/pull/7752#issuecomment-2619944645

File: esphome/components/dht/dht.cpp (hunk 1 above)
Comment (deCodeIt) [reply esphome/components/dht/dht.cpp]: Thank you for the inputs, looking into it.

**Comment by DjordjeMandic** [comment]
My phone won't refresh history of this PR. Anyways, please test if it compiles and if it works as intended. It would be nice if you could create small pr in docs (to next branch) about this.

**Comment by deCodeIt** [comment]
> My phone won't refresh history of this PR. Anyways, please test if it compiles and if it works as intended. It would be nice if you could create small pr in docs (to next branch) about this.

Sure,
I just tested the suggested changes on my DHT modules and they worked flawlessly. With default configuration I didn't get any values
```yaml
    pin:
      number: GPIO19
```
As soon as I set pullup to false, I was getting values. So the patch is working as expected.
```yaml
    pin:
      number: GPIO19
      mode:
        input: true
        pullup: false
```

Let me try updating the docs

**Comment by DjordjeMandic** [comment]
Logconfig internal pullup could stay. Use macro ONOFF(this->pin_->get_flags() & gpio::FLAG_PULLUP).

**Comment by deCodeIt** [comment]
> this->pin_->get_flags() & gpio::FLAG_PULLUP

Configured and was able to see it in logs as follows

```
[10:49:56][C][dht:017]: DHT:
[10:49:56][C][dht:018]:   Pin: GPIO19
[10:49:56][C][dht:024]:   Model: DHT22 (or equivalent)
[10:49:56][C][dht:026]:   Internal Pull-up: OFF
[10:49:56][C][dht:028]:   Update Interval: 5.0s
[10:49:56][C][dht:030]:   Temperature 'Room Temperature'
[10:49:56][C][dht:030]:     Device Class: 'temperature'
[10:49:56][C][dht:030]:     State Class: 'measurement'
[10:49:56][C][dht:030]:     Unit of Measurement: '°C'
[10:49:56][C][dht:030]:     Accuracy Decimals: 1
[10:49:56][C][dht:031]:   Humidity 'Room Humidity'
[10:49:56][C][dht:031]:     Device Class: 'humidity'
[10:49:56][C][dht:031]:     State Class: 'measurement'
[10:49:56][C][dht:031]:     Unit of Measurement: '%'
[10:49:56][C][dht:031]:     Accuracy Decimals: 0
```

**Comment by DjordjeMandic** [comment]
> ```yaml
>     pin:
>       number: GPIO19
> ```
> As soon as I set pullup to false, I was getting values. So the patch is working as expected.
> ```yaml
>     pin:
>       number: GPIO19
>       mode:
>         input: true
>         pullup: false
> ```
> 

So if nothing is supplied except the number it works fine with pullup enabled (non-breaking) and with just pullup false or both input true and pullup false(breaking change) it also works?

**Comment by deCodeIt** [comment]
> > ```yaml
> >     pin:
> >       number: GPIO19
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > As soon as I set pullup to false, I was getting values. So the patch is working as expected.
> > ```yaml
> >     pin:
> >       number: GPIO19
> >       mode:
> >         input: true
> >         pullup: false
> > ```
> 
> So if nothing is supplied except the number it works fine with pullup enabled (non-breaking) and with just pullup false or both input true and pullup false(breaking change) it also works?

No, Maybe my words were confusing. Let me try rephrasing them.

All existing DHT modules which were working/not-working as of today will continue to retain their behaviour with their existing configuration i.e. they will continue to work/not-work respectively as before with no config changes.

Now for those modules which were not-working with existing configuration i.e. the ones having external resistor. They will need the `pullup: false` config change to have them working.

**Comment by DjordjeMandic** [comment]
> No, Maybe my words were confusing. Let me try rephrasing them.
> 
> All existing DHT modules which were working/not-working as of today will continue to retain their behaviour with their existing configuration i.e. they will continue to work/not-work respectively as before with no config changes.
> 
> Now for those modules which were not-working with existing configuration i.e. the ones having external resistor. They will need the `pullup: false` config change to have them working.

Sorry, it was 5 am when I wrote that. What I meant to say:
Do old yaml configurations compile fine? Do old working yaml configurations still compile fine without pullup true supplied?

Edit: tests pass, my question is answered :)

**Review by DjordjeMandic — APPROVED** [review]

**Comment by deCodeIt** [comment]
> > No, Maybe my words were confusing. Let me try rephrasing them.
> > All existing DHT modules which were working/not-working as of today will continue to retain their behaviour with their existing configuration i.e. they will continue to work/not-work respectively as before with no config changes.
> > Now for those modules which were not-working with existing configuration i.e. the ones having external resistor. They will need the `pullup: false` config change to have them working.
> 
> Sorry, it was 5 am when I wrote that. What I meant to say: Do old yaml configurations compile fine? Do old working yaml configurations still compile fine without pullup true supplied?
> 
> Edit: tests pass, my question is answered :)

Ah my bad.
Yes, the old yaml configurations will still compile fine without `pullup: true`

**Review by DjordjeMandic — APPROVED** [review]
Closed #7752 in favour of this

**Review by jesserockz — APPROVED** [review]
