### PR TITLE
[wifi] Fix positive RSSI values on 8266

### LINKED ISSUE #11813: WiFi RSSI sensor reports positive value
### The problem

Have following button to restart WiFi component in case of bad reception etc.

Today I used it. After restart device RSSI sensor sent positive value to HA:

Image

### Which version of ESPHome has the issue?

2025.9.3

### What type of installation are you using?

Home Assistant Add-on

### What platform are you using?

ESP8266

### Component causing the issue

WiFi

### YAML Config

```yaml
button:
  - platform: template
    name: "${device_name}Restart WiFi"
    id: button_wifi_restart
    icon: "mdi:wifi-refresh"
    entity_category: diagnostic
    on_press:
      - wifi.disable:
      - wifi.enable:

sensor:  
  - platform: wifi_signal
    name: "${device_name}RSSI"
    id: sensor_rssi
    update_interval: ${interval_rssi}
    entity_category: "diagnostic"
```

### Anything in the logs that might be useful for us?

```txt

```

### Additional information

_No response_

### PR DESCRIPTION
**Pull request by swoboda1337**
# What does this implement/fix?

Fix positive RSSI values on 8266, datasheet says 31 is an error: https://www.espressif.com/sites/default/files/2c-esp8266_non_os_sdk_api_guide_en_v1.5.4.pdf

## Types of changes

- [x] Bugfix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] Code quality improvements to existing code or addition of tests
- [ ] Other

**Related issue or feature (if applicable):**

- fixes https://github.com/esphome/esphome/issues/11813

**Pull request in [esphome-docs](https://github.com/esphome/esphome-docs) with documentation (if applicable):**

- esphome/esphome-docs#<esphome-docs PR number goes here>

## Test Environment

- [ ] ESP32
- [ ] ESP32 IDF
- [x] ESP8266
- [ ] RP2040
- [ ] BK72xx
- [ ] RTL87xx
- [ ] nRF52840

## Example entry for `config.yaml`:

```yaml
# Example config.yaml

```

## Checklist:
  - [ ] The code change is tested and works locally.
  - [ ] Tests have been added to verify that the new code works (under `tests/` folder).

If user exposed functionality or configuration variables are added/changed:
  - [ ] Documentation added/updated in [esphome-docs](https://github.com/esphome/esphome-docs).

### CODE REVIEW

File: esphome/components/wifi/wifi_component_esp8266.cpp [hunk 1]
```diff
@@ -872,7 +872,13 @@ bssid_t WiFiComponent::wifi_bssid() {
   return bssid;
 }
 std::string WiFiComponent::wifi_ssid() { return WiFi.SSID().c_str(); }
-int8_t WiFiComponent::wifi_rssi() { return WiFi.status() == WL_CONNECTED ? WiFi.RSSI() : WIFI_RSSI_DISCONNECTED; }
+int8_t WiFiComponent::wifi_rssi() {
+  if (WiFi.status() != WL_CONNECTED)
+    return WIFI_RSSI_DISCONNECTED;
+  int8_t rssi = WiFi.RSSI();
+  // Values >= 31 are error codes per NONOS SDK API, not valid RSSI readings
+  return rssi >= 31 ? WIFI_RSSI_DISCONNECTED : rssi;
```
Comment (bdraco) [inline esphome/components/wifi/wifi_component_esp8266.cpp:880]: nit: could be constexpr WIFI_ERROR_CODE_START or something similar, but its only used in one place and clearly documented so 🤷

**Review by bdraco — APPROVED** [review]

**Comment by swoboda1337** [comment]
Thanks
