### PR TITLE
[uart] fix: missing uart_config_t struct initialisation

### LINKED ISSUE #9: Error with ESPHome 2026.6.1
After update to latest ESPHome version, uart component fails:

```
[23:38:14][W][uart.idf:149]: uart_param_config failed: ESP_ERR_NOT_SUPPORTED
[23:38:14][E][component:138]: Component uart was marked as failed.
[23:38:14][D][esp-idf:000]: E (6433) uart: uart_param_config(846): register back up is not supported
```

### LINKED ISSUE #7163: LD2410 sensor data 'Unknown' on ESP8266 & ESP32-C3 after recent update (UART issue)
### The problem

An LD2410 presence sensor that was working perfectly for weeks on an ESP8266 stopped providing data after a recent ESPHome update. The ESPHome device connects to Wi-Fi and Home Assistant, and all entities for the ld2410 component are created, but their state remains "Unknown".

To rule out hardware failure, I built a brand new ESPHome device from scratch using an ESP32-C3 board and a brand new LD2410 sensor module. The exact same failure occurs.

I can connect to the LD2410 sensor directly via Bluetooth, and I can see all the presence and distance data perfectly. 

### Which version of ESPHome has the issue?

2025.6.1

### What type of installation are you using?

Home Assistant Add-on

### Which version of Home Assistant has the issue?

2025.6.3

### What platform are you using?

ESP32

### Board

ESP32 C3 Zero (Also on ESP8266 originally - see above)

### Component causing the issue

ld2410

### YAML Config

```yaml
esphome:
  name: office-sensors
  friendly_name: Office Sensors

esp32:
  board: esp32-c3-devkitm-1
  framework:
    type: esp-idf

ld2410:

uart:
  tx_pin: 21
  rx_pin: 20
  baud_rate: 256000

i2c:
  sda: 8
  scl: 9
  scan: true
  id: bus_a

# Enable logging
logger:
  baud_rate: 0

# Enable Home Assistant API
api:
  encryption:
    key: "***"

ota:
  - platform: esphome
    password: "***"

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password

  ap:
    ssid: "Office-Sensors Fallback Hotspot"
    password: "***"

captive_portal:

switch:
  - platform: ld2410
    engineering_mode:
      name: "engineering mode"
    bluetooth:
      name: "control bluetooth"


sensor:

  - platform: scd4x
    co2:
      name: "Office CO2"
    temperature:
      id: "office_temperature"
      name: "Office Temperature"
    humidity:
      id: "office_humidity"
      name: "Office Humidity"

  - platform: sgp30
    eco2:
      name: "Office eCO2"
      accuracy_decimals: 1
      filters:
        - exponential_moving_average:
            alpha: 0.1
            send_every: 15
    tvoc:
      name: "Office TVOC"
      accuracy_decimals: 1
      filters:
        - exponential_moving_average:
            alpha: 0.1
            send_every: 15
    store_baseline: yes
    address: 0x58
    update_interval: 1s
    compensation:
      temperature_source: "office_temperature"
      humidity_source: "office_humidity"

  - platform: wifi_signal
    name: "WiFi Signal"
    update_interval: 60s

  #mmWave Presence
  - platform: ld2410
    light:
      name: "Light"
    moving_distance:
      name : "Moving Distance"
    still_distance:
      name: "Still Distance"
    moving_energy:
      name: "Move Energy"
    still_energy:
      name: "Still Energy"
    detection_distance:
      name: "Detection Distance"
    g1:
      move_energy:
        name: g1 move energy
      still_energy:
        name: g1 still energy
    g2:
      move_energy:
        name: g2 move energy
      still_energy:
        name: g2 still energy
    g3:
      move_energy:
        name: g3 move energy
      still_energy:
        name: g3 still energy
    g4:
      move_energy:
        name: g4 move energy
      still_energy:
        name: g4 still energy
    g5:
      move_energy:
        name: g5 move energy
      still_energy:
        name: g5 still energy
    g6:
      move_energy:
        name: g6 move energy
      still_energy:
        name: g6 still energy
    g7:
      move_energy:
        name: g7 move energy
      still_energy:
        name: g7 still energy
    g8:
      move_energy:
        name: g8 move energy
      still_energy:
        name: g8 still energy

binary_sensor:
  - platform: ld2410
    has_target:
      name: Presence
    has_moving_target:
      name: Moving Target
    has_still_target:
      name: Still Target

number:
  - platform: ld2410
    timeout:
      name: timeout
    light_threshold:
      name: light threshold
    max_move_distance_gate:
      name: max move distance gate
    max_still_distance_gate:
      name: max still distance gate
    g0:
      move_threshold:
        name: g0 move threshold
      still_threshold:
        name: g0 still threshold
    g1:
      move_threshold:
        name: g1 move threshold
      still_threshold:
        name: g1 still threshold
    g2:
      move_threshold:
        name: g2 move threshold
      still_threshold:
        name: g2 still threshold
    g3:
      move_threshold:
        name: g3 move threshold
      still_threshold:
        name: g3 still threshold
    g4:
      move_threshold:
        name: g4 move threshold
      still_threshold:
        name: g4 still threshold
    g5:
      move_threshold:
        name: g5 move threshold
      still_threshold:
        name: g5 still threshold
    g6:
      move_threshold:
        name: g6 move threshold
      still_threshold:
        name: g6 still threshold
    g7:
      move_threshold:
        name: g7 move threshold
      still_threshold:
        name: g7 still threshold
    g8:
      move_threshold:
        name: g8 move threshold
      still_threshold:
        name: g8 still threshold

button:
  - platform: ld2410
    factory_reset:
      name: "Factory Reset"
    restart:
      name: "Restart"
    query_params:
      name: query params

text_sensor:
  - platform: ld2410
    version:
      name: "Firmware Version"
    mac_address:
      name: "MAC Address"

select:
  - platform: ld2410
    distance_resolution:
      name: "Distance Resolution"
    baud_rate:
      name: "Baud Rate"
    light_function:
      name: light function
    out_pin_level:
      name: out pin level
```

### Anything in the logs that might be useful for us?

```txt

```

### Additional information

_No response_

### LINKED ISSUE #7167: ESPHome 2025.6 breaks uart
### The problem

After upgrading to 2025.6.0 or 2025.6.1 following Log message appears:
```
[23:38:14][W][uart.idf:149]: uart_param_config failed: ESP_ERR_NOT_SUPPORTED
[23:38:14][E][component:138]: Component uart was marked as failed.
[23:38:14][D][esp-idf:000]: E (6433) uart: uart_param_config(846): register back up is not supported
```

### Which version of ESPHome has the issue?

2025.6.1

### What type of installation are you using?

Home Assistant Add-on

### Which version of Home Assistant has the issue?

2025.6.3

### What platform are you using?

ESP32

### Board

_No response_

### Component causing the issue

_No response_

### YAML Config

```yaml
esphome:
  name: "hcp01"
  friendly_name: "HCP01"
  platformio_options:
    monitor_filters: esp32_exception_decoder

external_components:
    - source: github://14yannick/hoermann_door
      refresh: 0s

esp32:
  board: adafruit_feather_esp32s3
  framework:
    type: esp-idf

logger:
  logs:
    uapbridge_esp: NONE

ota:
  - platform: esphome
    password: "xgUChqY38CLu5kpd6RhfZRMo2pjsYBVo"

uart:
  id: uart_bus
  baud_rate: 19200
  rx_pin: 18
  tx_pin: 17

one_wire:
  - platform: gpio
    pin: 4

uapbridge_esp:
  id: garage_door_comp
  uart_id: uart_bus
  auto_correction: true

cover:
  - platform: uapbridge
    id: cover01
    name: cover01
    device_class: garage

binary_sensor:
  - platform: uapbridge
    error_state:
      name: error_state
      entity_category: "diagnostic"
    got_valid_broadcast:
      name: connection_state
      entity_category: "diagnostic"

button:
  - platform: uapbridge
    impulse_button:
      id: button_impulse
      name: impulse
  - platform: restart
    name: restart

sensor:
  - platform: dallas_temp
    address: 0xb900000b55de6028
    name: temperature01
    update_interval: 120s
  - platform: dallas_temp
    address: 0xcc00000a4cdf3928
    name: temperature02
    update_interval: 120s
  - platform: wifi_signal
    name: signal
    filters:
      - lambda: return min(max(2 * (x + 100.0), 0.0), 100.0);
    unit_of_measurement: "%"
    state_class: measurement
    update_interval: 60s
    entity_category: "diagnostic"
  - platform: uptime
    name: uptime
    unit_of_measurement: "s"
    state_class: measurement
    device_class: duration
    update_interval: 60s
    entity_category: "diagnostic"

api:
  encryption:
    key: "xxx"

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password

improv_serial:
```

### Anything in the logs that might be useful for us?

```txt

```

### Additional information

_No response_

### PR DESCRIPTION
**Pull request by Rezoran**
# What does this implement/fix?

[esp-idf](https://github.com/espressif/esp-idf/blob/v5.3.2/components/esp_driver_uart/src/uart.c#L846) added a check in its `uart_param_config` function to check if `uart_config->flags.backup_before_sleep == 0` when `SOC_UART_SUPPORT_SLEEP_RETENTION` is not supported and implemented a new [flags](https://github.com/espressif/esp-idf/blob/v5.3.2/components/esp_driver_uart/include/driver/uart.h#L49) property of the `uart_config_t` struct

this [struct](https://github.com/espressif/esp-idf/blob/v5.3.2/components/esp_driver_uart/include/driver/uart.h#L54) is not correctly initialized with 0 in esphomes [IDFUARTComponent::get_config_](https://github.com/esphome/esphome/blob/dev/esphome/components/uart/uart_component_esp_idf.cpp#L45) function.

This leads to flaky behavior, because it holds random uninitialized memory as value.

## Types of changes

- [X] Bugfix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] Code quality improvements to existing code or addition of tests
- [ ] Other

**Related issue or feature (if applicable):**

- fixes https://github.com/14yannick/hoermann_door/issues/9  
- fixes https://github.com/esphome/issues/issues/7167
- fixes https://github.com/esphome/issues/issues/7163

**Pull request in [esphome-docs](https://github.com/esphome/esphome-docs) with documentation (if applicable):**

- esphome/esphome-docs#<esphome-docs PR number goes here>

## Test Environment

- [ ] ESP32
- [X] ESP32 IDF
- [ ] ESP8266
- [ ] RP2040
- [ ] BK72xx
- [ ] RTL87xx

## Example entry for `config.yaml`:

```yaml
esphome:
  name: "hcp01"
  friendly_name: "HCP01"

external_components:
    - source: github://14yannick/hoermann_door
      refresh: 0s

esp32:
  board: esp32dev
  framework:
    type: esp-idf

logger:
  level: DEBUG
  baud_rate: 0 # Disable Serial logging to avoid conflict with uart bus on UART0

ota:
  - platform: esphome

uart:
  id: uart_bus
  baud_rate: 19200
  rx_pin: 18
  tx_pin: 17

uapbridge_esp:
  id: garage_door_comp
  uart_id: uart_bus
  auto_correction: true

cover:
  - platform: uapbridge
    id: cover01
    name: cover01
    device_class: garage

api:

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password

```

## Checklist:
  - [X] The code change is tested and works locally.
  - [ ] Tests have been added to verify that the new code works (under `tests/` folder).

If user exposed functionality or configuration variables are added/changed:
  - [ ] Documentation added/updated in [esphome-docs](https://github.com/esphome/esphome-docs).

### CODE REVIEW

File: esphome/components/uart/uart_component_esp_idf.cpp [hunk 1]
```diff
@@ -42,7 +42,7 @@ uart_config_t IDFUARTComponent::get_config_() {
       break;
   }
 
-  uart_config_t uart_config;
+  uart_config_t uart_config = {0};
```
Comment (clydebarrow) [inline esphome/components/uart/uart_component_esp_idf.cpp]:
```suggestion
  uart_config_t uart_config{};
```

**Review by clydebarrow — APPROVED** [review]

**Review by bdraco — APPROVED** [review]
