### PR TITLE
SPS30 : fix i2c read size

### LINKED ISSUE #2782: [SPS30] "pm_size" not working?
### The problem

Looking at the [code](https://github.com/esphome/esphome/blob/dev/esphome/components/sps30/sensor.py#L94), it seems that `pm_size` should be supported. However, it does not seem to be taken into account in the config:

> [15:54:22][C][sps30:067]: sps30:
[15:54:22][C][sps30:068]:   Address: 0x69
[15:54:22][W][sps30:084]: Unable to request sensor firmware version
[15:54:22][C][sps30:094]:   Update Interval: 60.0s
[15:54:22][C][sps30:095]:   Serial Number: ''
[15:54:22][C][sps30:096]:   PM1.0 'PM <1µm Weight concentration'
[15:54:22][C][sps30:096]:     Device Class: 'pm1'
[15:54:22][C][sps30:096]:     State Class: 'measurement'
[15:54:22][C][sps30:096]:     Unit of Measurement: 'µg/m³'
[15:54:22][C][sps30:096]:     Accuracy Decimals: 2
[15:54:22][C][sps30:096]:     Icon: 'mdi:chemical-weapon'
[15:54:22][C][sps30:097]:   PM2.5 'PM <2.5µm Weight concentration'
[15:54:22][C][sps30:097]:     Device Class: 'pm25'
[15:54:22][C][sps30:097]:     State Class: 'measurement'
[15:54:22][C][sps30:097]:     Unit of Measurement: 'µg/m³'
[15:54:22][C][sps30:097]:     Accuracy Decimals: 2
[15:54:22][C][sps30:097]:     Icon: 'mdi:chemical-weapon'
[15:54:22][C][sps30:098]:   PM4 'PM <4µm Weight concentration'
[15:54:22][C][sps30:098]:     State Class: 'measurement'
[15:54:22][C][sps30:098]:     Unit of Measurement: 'µg/m³'
[15:54:22][C][sps30:098]:     Accuracy Decimals: 2
[15:54:22][C][sps30:098]:     Icon: 'mdi:chemical-weapon'
[15:54:22][C][sps30:099]:   PM10 'PM <10µm Weight concentration'
[15:54:22][C][sps30:099]:     Device Class: 'pm10'
[15:54:22][C][sps30:099]:     State Class: 'measurement'
[15:54:22][C][sps30:099]:     Unit of Measurement: 'µg/m³'
[15:54:22][C][sps30:099]:     Accuracy Decimals: 2
[15:54:22][C][sps30:099]:     Icon: 'mdi:chemical-weapon'

It is also not present in the [documentation](https://esphome.io/components/sensor/sps30.html).

### Which version of ESPHome has the issue?

2021.11.4

### What type of installation are you using?

Docker

### Which version of Home Assistant has the issue?

_No response_

### What platform are you using?

ESP32

### Board

wemos_d1_mini32

### Component causing the issue

sps30

### Example YAML snippet

```yaml
sensor:
  - platform: scd30
    co2:
      name: "CO2"
      on_value:
        then:
          - http_request.send:
              method: PUT
              url: "${openhab_rest_url}/AirQuality_CO2/state"
              headers:
                Content-Type: text/plain
                Accept: application/json
              body: !lambda "return esphome::to_string(x);"
    temperature:
      name: "Temperature"
    humidity:
      name: "Humidity"
    automatic_self_calibration: false
    altitude_compensation: 750m
    address: 0x61
    update_interval: 60s
  - platform: sps30
    pm_1_0:
      name: "PM <1µm Weight concentration"
      id: "PM_1_0"
    pm_2_5:
      name: "PM <2.5µm Weight concentration"
      id: "PM_2_5"
    pm_4_0:
      name: "PM <4µm Weight concentration"
      id: "PM_4_0"
    pm_10_0:
      name: "PM <10µm Weight concentration"
      id: "PM_10_0"
    pmc_0_5:
      name: "PM <0.5µm Number concentration"
      id: "PMC_0_5"
    pmc_1_0:
      name: "PM <1µm Number concentration"
      id: "PMC_1_0"
    pmc_2_5:
      name: "PM <2.5µm Number concentration"
      id: "PMC_2_5"
    pmc_4_0:
      name: "PM <4µm Number concentration"
      id: "PMC_4_0"
    pmc_10_0:
      name: "PM <10µm Number concentration"
      id: "PMC_10_0"
    pm_size:
      name: "PM average size"
      id: "PM_SIZE"
    address: 0x69
    update_interval: 60s
```

### Anything in the logs that might be useful for us?

```txt
[15:54:22][C][sps30:067]: sps30:
[15:54:22][C][sps30:068]:   Address: 0x69
[15:54:22][W][sps30:084]: Unable to request sensor firmware version
[15:54:22][C][sps30:094]:   Update Interval: 60.0s
[15:54:22][C][sps30:095]:   Serial Number: ''
[15:54:22][C][sps30:096]:   PM1.0 'PM <1µm Weight concentration'
[15:54:22][C][sps30:096]:     Device Class: 'pm1'
[15:54:22][C][sps30:096]:     State Class: 'measurement'
[15:54:22][C][sps30:096]:     Unit of Measurement: 'µg/m³'
[15:54:22][C][sps30:096]:     Accuracy Decimals: 2
[15:54:22][C][sps30:096]:     Icon: 'mdi:chemical-weapon'
[15:54:22][C][sps30:097]:   PM2.5 'PM <2.5µm Weight concentration'
[15:54:22][C][sps30:097]:     Device Class: 'pm25'
[15:54:22][C][sps30:097]:     State Class: 'measurement'
[15:54:22][C][sps30:097]:     Unit of Measurement: 'µg/m³'
[15:54:22][C][sps30:097]:     Accuracy Decimals: 2
[15:54:22][C][sps30:097]:     Icon: 'mdi:chemical-weapon'
[15:54:22][C][sps30:098]:   PM4 'PM <4µm Weight concentration'
[15:54:22][C][sps30:098]:     State Class: 'measurement'
[15:54:22][C][sps30:098]:     Unit of Measurement: 'µg/m³'
[15:54:22][C][sps30:098]:     Accuracy Decimals: 2
[15:54:22][C][sps30:098]:     Icon: 'mdi:chemical-weapon'
[15:54:22][C][sps30:099]:   PM10 'PM <10µm Weight concentration'
[15:54:22][C][sps30:099]:     Device Class: 'pm10'
[15:54:22][C][sps30:099]:     State Class: 'measurement'
[15:54:22][C][sps30:099]:     Unit of Measurement: 'µg/m³'
[15:54:22][C][sps30:099]:     Accuracy Decimals: 2
[15:54:22][C][sps30:099]:     Icon: 'mdi:chemical-weapon'
```

### Additional information

I don't have the sensor yet, I'm just preparing my setup. Also, I discovered ESPHome today. Amazing project. Planned on implementing things myself but this project is just perfect for my needs.

### PR DESCRIPTION
**Pull request by martgras**
# What does this implement/fix? 

Too many bytes requested when reading firmware version.
Removing leading 0 from fw subversion
Read firmware version in setup and show in dump_config.
Add missing sensors to dump_config

## Types of changes

- [x] Bugfix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] Other

**Related issue or feature (if applicable):** fixes https://github.com/esphome/issues/issues/2782

**Pull request in [esphome-docs](https://github.com/esphome/esphome-docs) with documentation (if applicable):** esphome/esphome-docs#1699

## Test Environment

- [x] ESP32
- [x] ESP32 IDF
- [ ] ESP8266

## Example entry for `config.yaml`:

```yaml
# Example config.yaml

```

## Checklist:
  - [x] The code change is tested and works locally.
  - [ ] Tests have been added to verify that the new code works (under `tests/` folder).
  
If user exposed functionality or configuration variables are added/changed:
  - [ ] Documentation added/updated in [esphome-docs](https://github.com/esphome/esphome-docs).

### CODE REVIEW

File: esphome/components/sps30/sps30.cpp [hunk 1]
```diff
@@ -32,14 +32,11 @@ void SPS30Component::setup() {
       return;
     }
 
-    uint16_t raw_firmware_version[4];
-    if (!this->read_data_(raw_firmware_version, 4)) {
+    if (!this->read_data_(&raw_firmware_version_, 1)) {
```
Comment (oxan) [inline esphome/components/sps30/sps30.cpp:35]: This reads just one byte of `raw_firmware_version_`...

File: esphome/components/sps30/sps30.cpp [hunk 2]
```diff
@@ -93,10 +92,17 @@ void SPS30Component::dump_config() {
   }
   LOG_UPDATE_INTERVAL(this);
   ESP_LOGCONFIG(TAG, "  Serial Number: '%s'", this->serial_number_);
-  LOG_SENSOR("  ", "PM1.0", this->pm_1_0_sensor_);
-  LOG_SENSOR("  ", "PM2.5", this->pm_2_5_sensor_);
-  LOG_SENSOR("  ", "PM4", this->pm_4_0_sensor_);
-  LOG_SENSOR("  ", "PM10", this->pm_10_0_sensor_);
+  ESP_LOGCONFIG(TAG, "  Firmware version v%0d.%0d", (raw_firmware_version_ >> 8),
+                uint16_t(raw_firmware_version_ & 0xFF));
```
Comment (oxan) [inline esphome/components/sps30/sps30.cpp:96]: ...while this uses two.

Comment (oxan) [reply esphome/components/sps30/sps30.cpp:96]: Judging from the datasheet it gives a 3-byte response, firmware major, firmware minor, and a checksum.

**Review by oxan — CHANGES_REQUESTED** [review]

File: esphome/components/sps30/sps30.cpp (hunk 1 above)
Comment (martgras) [reply esphome/components/sps30/sps30.cpp:35]: this confused me as well when starting to look at the code.

Actually this reads 3 bytes and handles the crc as well
https://github.com/esphome/esphome/blob/06da540ab03f9b25df876d004b02116fd0fb2674/esphome/components/sps30/sps30.cpp#L243

Comment (martgras) [reply esphome/components/sps30/sps30.cpp:35]: see previous comment
in my test FW is correctly retried with this change
```
[14:30:35][C][sps30:066]: sps30:
[14:30:35][C][sps30:067]:   Address: 0x69
[14:30:35][C][sps30:093]:   Update Interval: 30.0s
[14:30:35][C][sps30:094]:   Serial Number: '320EFB29FC301E66'
[14:30:35][C][sps30:095]:   Firmware version v2.2
[14:30:35][C][sps30:096]:   PM1.0 Weight Concentration ' PM <1µm Weight concentration'
[14:30:35][C][sps30:096]:     Device Class: 'pm1'
[14:30:35][C][sps30:096]:     State Class: 'measurement'
[14:30:35][C][sps30:096]:     Unit of Measurement: 'µg/m³'
[14:30:35][C][sps30:096]:     Accuracy Decimals: 2
[14:30:35][C][sps30:096]:     Icon: 'mdi:chemical-weapon'
```

File: esphome/components/sps30/sps30.cpp (hunk 2 above)
Comment (martgras) [reply esphome/components/sps30/sps30.cpp:96]: see previous comment
in my test FW is correctly retrieved with this change
```
[14:30:35][C][sps30:066]: sps30:
[14:30:35][C][sps30:067]:   Address: 0x69
[14:30:35][C][sps30:093]:   Update Interval: 30.0s
[14:30:35][C][sps30:094]:   Serial Number: '320EFB29FC301E66'
[14:30:35][C][sps30:095]:   Firmware version v2.2
[14:30:35][C][sps30:096]:   PM1.0 Weight Concentration ' PM <1µm Weight concentration'
[14:30:35][C][sps30:096]:     Device Class: 'pm1'
[14:30:35][C][sps30:096]:     State Class: 'measurement'
[14:30:35][C][sps30:096]:     Unit of Measurement: 'µg/m³'
[14:30:35][C][sps30:096]:     Accuracy Decimals: 2
[14:30:35][C][sps30:096]:     Icon: 'mdi:chemical-weapon'
```

File: esphome/components/sps30/sps30.cpp (hunk 1 above)
Comment (oxan) [reply esphome/components/sps30/sps30.cpp:35]: Ah bugger, you're right.

**Review by oxan — APPROVED** [review]
