### PR TITLE
Expose WHITE/CWWW/RGBCT color modes over MQTT

### LINKED ISSUE #2358: MQTT light on HA - Error: Invalid supported_color_modes []
### The problem

Light bulb configured with cwww component does not appear on Home Assistant when upgraded to 2021.8.1. Also tried on 2021.8.2 and same problem persists.
HA throws the following exception:
Aug 25 10:50:45 abc hass[27314]:     raise vol.Error(f"Invalid supported_color_modes {sorted(color_modes)}")
Aug 25 10:50:45 abc hass[27314]: voluptuous.error.Error: Invalid supported_color_modes []

The mqtt homeassistant/light message contains the following:
"color_mode":true,"supported_color_modes":[],"brightness":true

Downgrading esphome to 1.20.4 got the light appearing on HA again.

### Which version of ESPHome has the issue?

2021.8.1 and 2021.8.2

### What type of installation are you using?

pip

### Which version of Home Assistant has the issue?

2021.7.4

### What platform are you using?

ESP8266

### Board

_No response_

### Component causing the issue

light

### Example YAML snippet

```yaml
output:
  - platform: esp8266_pwm
    id: output_warm_white
    pin: GPIO12
  - platform: esp8266_pwm
    id: output_daylight
    pin: GPIO14

light:
  - platform: cwww
    name: ${name}
    id: light1
    cold_white: output_daylight
    warm_white: output_warm_white
    cold_white_color_temperature: 6500 K
    warm_white_color_temperature: 2700 K
```

### Anything in the logs that might be useful for us?

```txt
HA logs:
Aug 25 10:50:45 abc hass[27314]:     raise vol.Error(f"Invalid supported_color_modes {sorted(color_modes)}")
Aug 25 10:50:45 abc hass[27314]: voluptuous.error.Error: Invalid supported_color_modes []

The mqtt homeassistant/light message contains the following:
"color_mode":true,"supported_color_modes":[],"brightness":true
```

### Additional information

_No response_

### PR DESCRIPTION
**Pull request by oxan**
# What does this implement/fix? 

The White, CWWW and RGBCT color modes weren't exposed over MQTT. RGBCT is somewhat problematic as HA only offers a RGBWW mode, and we don't have CWWW -> CT emulation in ESPHome at the moment (and I don't have time/interest to add that in the short term). Just expose RGBCT as RGBW for now, it's better than nothing. 

I haven't tested this beyond compilation as I don't have an MQTT setup.

## Types of changes

- [x] Bugfix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] Other

**Related issue or feature (if applicable):** fixes esphome/issues#2358

**Pull request in [esphome-docs](https://github.com/esphome/esphome-docs) with documentation (if applicable):** esphome/esphome-docs#<esphome-docs PR number goes here>

## Test Environment

- [ ] ESP32
- [ ] ESP8266

## Example entry for `config.yaml`:

```yaml
# Example config.yaml

```

## Checklist:
  - [ ] The code change is tested and works locally.
  - [ ] Tests have been added to verify that the new code works (under `tests/` folder).
  
If user exposed functionality or configuration variables are added/changed:
  - [ ] Documentation added/updated in [esphome-docs](https://github.com/esphome/esphome-docs).

### CODE REVIEW

File: esphome/components/mqtt/mqtt_light.cpp [hunk 1]
```diff
@@ -38,18 +38,23 @@ void MQTTJSONLightComponent::send_discovery(JsonObject &root, mqtt::SendDiscover
 
   root["color_mode"] = true;
   JsonArray &color_modes = root.createNestedArray("supported_color_modes");
-  if (traits.supports_color_mode(ColorMode::COLOR_TEMPERATURE))
+  if (traits.supports_color_mode(ColorMode::ON_OFF))
+    color_modes.add("onoff");
+  if (traits.supports_color_mode(ColorMode::BRIGHTNESS))
+    color_modes.add("brightness");
+  if (traits.supports_color_mode(ColorMode::WHITE))
+    color_modes.add("white");
```
Comment (jesserockz) [inline esphome/components/mqtt/mqtt_light.cpp:46]: I realise you are only moving these lines up, but there are rules for HA color modes for these 3

- ON_OFF should only exist for binary lights
- BRIGHTNESS should only exist for monochromatic lights
- WHITE cannot be the only color_mode supported

https://developers.home-assistant.io/docs/core/entity/light/#color-modes

Comment (oxan) [reply esphome/components/mqtt/mqtt_light.cpp:46]: Those constraints hold for all lights in ESPHome now. We could add validation here for when external components break that but :shrug:

Comment (jesserockz) [reply esphome/components/mqtt/mqtt_light.cpp:46]: Yeah fair point =)

**Review by jesserockz — APPROVED** [review]
