### PR TITLE
BH1750: Fix a too high default H-res2 mode value

### LINKED ISSUE #2357: ESPHome node for BH1750: problem at the default H-resolution mode2
### The problem

The BH1750FVI sensor has three different resolution modes, but it would be expected that in all three modes the given lux value would be roughly the same with the same light circumstances.
The current default ESPHome node for the BH1750FVI sensor appears to give a too high value in the High resolution 2 mode (which is the default setting for this node), compared to the two other resolution modes High resolution and Low resolution. Changing the MTres or "measurement_duration" value does not have an effect on this.
A test in a controlled environment with two fixed light levels shows this result for the possible combinations:
[Testresults](https://community-assets.home-assistant.io/original/3X/a/d/ad5c109752f84cb8acc392aeff89f095adefb38d.jpeg)
This clearly shows that the values in the H-res2 mode are always approximately twice as high as for the other two modes.
So the H-res2 value should be divided by two to get more realistic values, which is also in stated in the BH1750FVI datasheet.
See [this Home Assistant community discussion](https://community.home-assistant.io/t/esphome-node-for-bh1750-problem-at-the-default-h-resolution-mode2/332385) for more details.
It is clear that modifying this could create a breaking change for many of the current implementations because the lux values for the default setting would become twice as low. But at least it would be good to make this issue clear on the ESPHome [BH1750 web page](https://esphome.io/components/sensor/bh1750.html) so that new implementations can take this into account.

### Which version of ESPHome has the issue?

version 2021.8.1

### What type of installation are you using?

Home Assistant Add-on

### Which version of Home Assistant has the issue?

2021.8.8

### What platform are you using?

ESP8266

### Board

Wemos D1 mini Pro v2

### Component causing the issue

_No response_

### Example YAML snippet

_No response_

### Anything in the logs that might be useful for us?

_No response_

### Additional information

_No response_

### PR DESCRIPTION
**Pull request by kixtarter**
The BH1750 integration gives double the realistic lx value for the default H-res2 mode (resolution 0.5).
The BH1750 datasheet specifies that the lx value has to be divided by 2 to get a realistic value in the H-res2 mode, which is not yet done in the ESPHome code.
See this GitHub report and this community post for more background info.
https://github.com/esphome/issues/issues/2357
https://community.home-assistant.io/t/esphome-node-for-bh1750-problem-at-the-default-h-resolution-mode2/332385/3

This correction might be a breaking change when the H-res2 resolution mode value is used as trigger in an automation.
Therefore I added a warning log entry to indicate this.

Note: Since this is my first ever pull-request, any comments or corrections are welcome.

# What does this implement/fix? 

This fix corrects the currently unrealistically high H-res2 mode value, so resolves esphome/issues#2357.

## Types of changes

- [x] Bugfix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [x] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] Other

**Related issue or feature (if applicable):** fixes <link to issue>

**Pull request in [esphome-docs](https://github.com/esphome/esphome-docs) with documentation (if applicable):** esphome/esphome-docs#<esphome-docs PR number goes here>

## Test Environment

- [ ] ESP32
- [ ] ESP32 IDF
- [x] ESP8266

## Example entry for `config.yaml`:

```yaml
# Example config.yaml

```

## Checklist:
  - [x] The code change is tested and works locally.
  - [ ] Tests have been added to verify that the new code works (under `tests/` folder).
  
If user exposed functionality or configuration variables are added/changed:
  - [ ] Documentation added/updated in [esphome-docs](https://github.com/esphome/esphome-docs).

### CODE REVIEW

File: esphome/components/bh1750/bh1750.cpp [hunk 1]
```diff
@@ -79,6 +79,10 @@ void BH1750Sensor::read_data_() {
 
   float lx = float(raw_value) / 1.2f;
   lx *= 69.0f / this->measurement_duration_;
+  if (this->resolution_ == BH1750_RESOLUTION_0P5_LX) {
+    lx /= 2.0f;
+    ESP_LOGW(TAG, "Potentially breaking change: H-res2 value corrected. Check related automations!");
```
Comment (OttoWinter) [inline esphome/components/bh1750/bh1750.cpp]: Since this is a bugfix I'd say we don't need to log here.

We can tag it as a breaking change so it shows up in the logs, just this warning message is not understandable/actionable by the average user (what does H-res2 value corrected mean for example)

Comment (kixtarter) [reply esphome/components/bh1750/bh1750.cpp]: Thanks Otto, I fully agree.
Can and should I modify the code myself?
And if so, since this is my very first pull-request, how should I do this?

Comment (oxan) [reply esphome/components/bh1750/bh1750.cpp]: Yes, you can change the code yourself. See the [GitHub docs](https://docs.github.com/en/github/collaborating-with-pull-requests) for how to do that.

**Review by oxan — APPROVED** [review]

File: esphome/components/bh1750/bh1750.cpp (hunk 1 above)
Comment (kixtarter) [reply esphome/components/bh1750/bh1750.cpp]: Thanks Oxan, I incorporated the change in my fork of the code and did a recommit.
Hope this is correct.
