### PR TITLE
fix integration sensor

### LINKED ISSUE #533: Integration Sensor: function "process_sensor_value_" is not integrating correctly
**Operating environment/Installation (Hass.io/Docker/pip/etc.):**

hassbian

**ESP (ESP32/ESP8266, Board/Sonoff):**

ESP8266

**Affected component:**

Integration sensor

**Description of problem:**
The integration sensor is not integrating correctly. The problem is not visible at first with a rather constant sensor value. However by e.g. integration of varying power values, one can see that the reported value even decreases some-times.

The main issue is this line of the function process_sensor_value__
`this->publish_and_save_(this->last_value_ + area);`

which is not adding the new value to the result accumulator but to the last value.
In addition the last_value and and time is never updated.
And because the old time is never updated, the sensor data appears to be integrating, since the calculated time difference to the last value gets larger and larger and thus also the calculated area increases, while in fact its only multplying the current sensor reading with the time lasted since the last reset.

**Problem-relevant YAML-configuration entries:**
```yaml
PASTE YAML FILE HERE

```

**Logs (if applicable):**

```
PASTE DEBUG LOG HERE

```

**Additional information and things you've tried:**
The issue can fixed with following changes at the end of function process_sensor_value_ inside integration_sensor.cpp
`this->last_value_ =  new_value;`
`this->last_update_ = now;`
`this->publish_and_save_(this->result_ + area);`

### PR DESCRIPTION
**Pull request by glmnet**
## Description:

Issue reported in #533 also I believe it is storing the value on rtc mem even when restore is not set.

**Related issue (if applicable):** fixes https://github.com/esphome/issues/issues/533

**Pull request in [esphome-docs](https://github.com/esphome/esphome-docs) with documentation (if applicable):** N/A

## Checklist:
  - [ ] The code change is tested and works locally.
  - [ ] Tests have been added to verify that the new code works (under `tests/` folder).

If user exposed functionality or configuration variables are added/changed:
  - [ ] Documentation added/updated in [esphome-docs](https://github.com/esphome/esphome-docs).

### CODE REVIEW

File: esphome/components/integration/integration_sensor.h [hunk 1]
```diff
@@ -54,7 +54,9 @@ class IntegrationSensor : public sensor::Sensor, public Component {
   void publish_and_save_(float result) {
     this->result_ = result;
     this->publish_state(result);
-    this->rtc_.save(&result);
```
Comment (OttoWinter) [inline esphome/components/integration/integration_sensor.h]: This is unnecessary - if the RTC object is never created, save will be a no-op. Granted, it is a bit hacky but lots of code depends on that behavior already.
