### PR TITLE
Sprinkler fixes

### LINKED ISSUE #4502: Sprinkler Controller is Marking Valve Complete before it's actually complete (because of valve open delay)
### The problem

It looks like Sprinkler Controller is marking a valve completed too early if valve open delay is set. 

In the attached log file it is visible that both "Marking valve 0 complete" and "Marking valve 1 complete" are kicking in 10s earlier (10s is the valve open delay what has been set) than the actual end time of the zone ('Relay 1' Turning OFF. and 'Relay 2' Turning OFF. respectively).

@kbx81 Is this something you could have a look?

### Which version of ESPHome has the issue?

2023.4.4

### What type of installation are you using?

Docker

### Which version of Home Assistant has the issue?

2023.05

### What platform are you using?

ESP8266

### Board

sonoff 4ch pro

### Component causing the issue

Sprinkler

### Example YAML snippet

_No response_

### Anything in the logs that might be useful for us?

```txt
INFO Reading configuration /config/irrigation.yaml...
WARNING 'sonoff4chpro_sprinkler': Using the '_' (underscore) character in the hostname is discouraged as it can cause problems with some DHCP and local name services. For more information, see https://esphome.io/guides/faq.html#why-shouldn-t-i-use-underscores-in-my-device-name
WARNING ESP8266: Pin 9 (9-10) might already be used by the flash interface in QUAD IO flash mode.
WARNING ESP8266: Pin 10 (9-10) might already be used by the flash interface in QUAD IO flash mode.
INFO Starting log output from sonoff4chpro_sprinkler.localdomain using esphome API
INFO Successfully connected to sonoff4chpro_sprinkler.localdomain
[13:45:19][I][app:102]: ESPHome version 2023.4.4 compiled on May  8 2023, 13:36:26
[13:45:19][C][wifi:505]: WiFi:
[13:45:19][C][wifi:363]:   Local MAC: 4C:EB:D6:CA:82:52
[13:45:19][C][wifi:364]:   SSID: 'OlympIoTwoI'[redacted]
[13:45:19][C][wifi:365]:   IP Address: 192.168.33.118
[13:45:19][C][wifi:366]:   BSSID: B6:8B:A9:1D:E3:02[redacted]
[13:45:19][C][wifi:368]:   Hostname: 'sonoff4chpro_sprinkler'
[13:45:19][C][wifi:370]:   Signal strength: -69 dB ▂▄▆█
[13:45:19][C][wifi:374]:   Channel: 1
[13:45:19][C][wifi:375]:   Subnet: 255.255.255.0
[13:45:19][C][wifi:376]:   Gateway: 192.168.33.254
[13:45:19][C][wifi:377]:   DNS1: 8.8.8.8
[13:45:19][C][wifi:378]:   DNS2: 0.0.0.0
[13:45:19][C][logger:294]: Logger:
[13:45:19][C][logger:295]:   Level: DEBUG
[13:45:19][C][logger:296]:   Log Baud Rate: 115200
[13:45:19][C][logger:297]:   Hardware UART: UART0
[13:45:19][C][esp8266_pwm:022]: ESP8266 PWM:
[13:45:19][C][esp8266_pwm:023]:   Pin: GPIO13
[13:45:19][C][esp8266_pwm:024]:   Frequency: 1000.0 Hz
[13:45:19][C][esp8266_pwm:025]:   Inverted: YES
[13:45:19][C][uptime.sensor:031]: Uptime Sensor 'Uptime'
[13:45:19][C][uptime.sensor:031]:   Device Class: 'duration'
[13:45:19][C][uptime.sensor:031]:   State Class: 'total_increasing'
[13:45:19][C][uptime.sensor:031]:   Unit of Measurement: 's'
[13:45:19][C][uptime.sensor:031]:   Accuracy Decimals: 0
[13:45:19][C][uptime.sensor:031]:   Icon: 'mdi:timer-outline'
[13:45:19][C][template.sensor:023]: Template Sensor 'Sprinkler Zone 1 Progress Percentage'
[13:45:19][C][template.sensor:023]:   State Class: ''
[13:45:19][C][template.sensor:023]:   Unit of Measurement: ''
[13:45:19][C][template.sensor:023]:   Accuracy Decimals: 1
[13:45:19][C][template.sensor:024]:   Update Interval: 1.0s
[13:45:19][C][template.sensor:023]: Template Sensor 'Sprinkler Zone 2 Progress Percentage'
[13:45:20][C][template.sensor:023]:   State Class: ''
[13:45:20][C][template.sensor:023]:   Unit of Measurement: ''
[13:45:20][C][template.sensor:023]:   Accuracy Decimals: 1
[13:45:20][C][template.sensor:024]:   Update Interval: 1.0s
[13:45:20][C][template.sensor:023]: Template Sensor 'Drip Zone Progress Percentage'
[13:45:20][C][template.sensor:023]:   State Class: ''
[13:45:20][C][template.sensor:023]:   Unit of Measurement: ''
[13:45:20][C][template.sensor:023]:   Accuracy Decimals: 1
[13:45:20][C][template.sensor:024]:   Update Interval: 1.0s
[13:45:20][C][template.sensor:023]: Template Sensor 'Sprinkler Controller Overall Progress Percentage'
[13:45:20][C][template.sensor:023]:   State Class: ''
[13:45:20][C][template.sensor:023]:   Unit of Measurement: ''
[13:45:20][C][template.sensor:023]:   Accuracy Decimals: 1
[13:45:20][C][template.sensor:024]:   Update Interval: 1.0s
[13:45:20][C][template.sensor:023]: Template Sensor 'Sprinkler Controller Status Internal'
[13:45:20][C][template.sensor:023]:   State Class: ''
[13:45:20][C][template.sensor:023]:   Unit of Measurement: ''
[13:45:20][C][template.sensor:023]:   Accuracy Decimals: 1
[13:45:20][C][template.sensor:023]:   Icon: 'mdi:information-variant'
[13:45:20][C][template.sensor:024]:   Update Interval: 1.0s
[13:45:20][C][template.sensor:023]: Template Sensor 'Drip Controller Status Internal'
[13:45:20][C][template.sensor:023]:   State Class: ''
[13:45:20][C][template.sensor:023]:   Unit of Measurement: ''
[13:45:20][C][template.sensor:023]:   Accuracy Decimals: 1
[13:45:20][C][template.sensor:023]:   Icon: 'mdi:information-variant'
[13:45:20][C][template.sensor:024]:   Update Interval: 1.0s
[13:45:20][C][template.text_sensor:021]: Template Sensor 'Sprinkler Controller Status'
[13:45:20][C][template.text_sensor:021]:   Icon: 'mdi:information-variant'
[13:45:20][C][template.text_sensor:021]: Template Sensor 'Drip Controller Status'
[13:45:20][C][template.text_sensor:021]:   Icon: 'mdi:information-variant'
[13:45:20][C][template.text_sensor:021]: Template Sensor 'Sprinkler Zone 1 Status'
[13:45:20][C][template.text_sensor:021]:   Icon: 'mdi:information-variant'
[13:45:20][C][template.text_sensor:021]: Template Sensor 'Sprinkler Zone 2 Status'
[13:45:20][C][template.text_sensor:021]:   Icon: 'mdi:information-variant'
[13:45:20][C][template.text_sensor:021]: Template Sensor 'Drip Zone Status'
[13:45:20][C][template.text_sensor:021]:   Icon: 'mdi:information-variant'
[13:45:20][C][template.text_sensor:021]: Template Sensor 'Sprinkler Zone 1 Time Remaining'
[13:45:20][C][template.text_sensor:021]:   Icon: 'mdi:progress-clock'
[13:45:20][C][template.text_sensor:021]: Template Sensor 'Sprinkler Zone 2 Time Remaining'
[13:45:20][C][template.text_sensor:021]:   Icon: 'mdi:progress-clock'
[13:45:20][C][template.text_sensor:021]: Template Sensor 'Drip Zone Time Remaining'
[13:45:20][C][template.text_sensor:021]:   Icon: 'mdi:progress-clock'
[13:45:20][C][template.text_sensor:021]: Template Sensor 'Sprinkler Controller Overall Time Remaining'
[13:45:20][C][template.text_sensor:021]:   Icon: 'mdi:progress-clock'
[13:45:20][C][template.text_sensor:021]: Template Sensor 'Drip Controller Overall Time Remaining'
[13:45:20][C][template.text_sensor:021]:   Icon: 'mdi:progress-clock'
[13:45:20][C][sprinkler:075]: Sprinkler Switch 'Sprinkler Start/Resume/Stop'
[13:45:20][C][sprinkler:097]:   Restore Mode: always OFF
[13:45:20][C][sprinkler:075]: Sprinkler Switch 'Sprinkler Auto-Advance'
[13:45:20][C][sprinkler:097]:   Restore Mode: restore defaults to OFF
[13:45:20][C][sprinkler:075]: Sprinkler Switch 'Sprinkler Zone 1'
[13:45:20][C][sprinkler:097]:   Restore Mode: always OFF
[13:45:20][C][sprinkler:075]: Sprinkler Switch 'Enable Sprinkler Zone 1'
[13:45:20][C][sprinkler:097]:   Restore Mode: restore defaults to OFF
[13:45:20][C][sprinkler:075]: Sprinkler Switch 'Sprinkler Zone 2'
[13:45:20][C][sprinkler:097]:   Restore Mode: always OFF
[13:45:20][C][sprinkler:075]: Sprinkler Switch 'Enable Sprinkler Zone2'
[13:45:20][C][sprinkler:097]:   Restore Mode: restore defaults to OFF
[13:45:20][C][sprinkler:075]: Sprinkler Switch 'Drip Start/Resume/Stop'
[13:45:20][C][sprinkler:097]:   Restore Mode: always OFF
[13:45:20][C][sprinkler:075]: Sprinkler Switch 'Drip Auto-Advance'
[13:45:20][C][sprinkler:097]:   Restore Mode: restore defaults to OFF
[13:45:20][C][sprinkler:075]: Sprinkler Switch 'Drip Zone'
[13:45:20][C][sprinkler:097]:   Restore Mode: always OFF
[13:45:20][C][sprinkler:075]: Sprinkler Switch 'Unused Switch'
[13:45:20][C][sprinkler:097]:   Restore Mode: always OFF
[13:45:20][C][switch.gpio:075]: GPIO Switch 'Relay 1'
[13:45:20][C][switch.gpio:097]:   Restore Mode: restore defaults to OFF
[13:45:20][C][switch.gpio:031]:   Pin: GPIO12
[13:45:20][C][switch.gpio:033]:   Interlocks:
[13:45:20][C][switch.gpio:037]:     Relay 2
[13:45:20][C][switch.gpio:037]:     Relay 3
[13:45:20][C][switch.gpio:075]: GPIO Switch 'Relay 2'
[13:45:20][C][switch.gpio:097]:   Restore Mode: restore defaults to OFF
[13:45:20][C][switch.gpio:031]:   Pin: GPIO5
[13:45:20][C][switch.gpio:033]:   Interlocks:
[13:45:20][C][switch.gpio:037]:     Relay 1
[13:45:20][C][switch.gpio:037]:     Relay 3
[13:45:20][C][switch.gpio:075]: GPIO Switch 'Relay 3'
[13:45:20][C][switch.gpio:097]:   Restore Mode: restore defaults to OFF
[13:45:20][C][switch.gpio:031]:   Pin: GPIO4
[13:45:20][C][switch.gpio:033]:   Interlocks:
[13:45:20][C][switch.gpio:037]:     Relay 1
[13:45:20][C][switch.gpio:037]:     Relay 2
[13:45:20][C][switch.gpio:075]: GPIO Switch 'Relay 4'
[13:45:20][C][switch.gpio:097]:   Restore Mode: restore defaults to OFF
[13:45:20][C][switch.gpio:031]:   Pin: GPIO15
[13:45:20][C][switch.gpio:033]:   Interlocks:
[13:45:20][C][switch.gpio:037]:     Relay 1
[13:45:20][C][switch.gpio:037]:     Relay 2
[13:45:20][C][switch.gpio:037]:     Relay 3
[13:45:20][C][gpio.binary_sensor:015]: GPIO Binary Sensor 'key1'
[13:45:20][C][gpio.binary_sensor:016]:   Pin: GPIO0
[13:45:20][C][gpio.binary_sensor:015]: GPIO Binary Sensor 'key2'
[13:45:20][C][gpio.binary_sensor:016]:   Pin: GPIO9
[13:45:20][C][gpio.binary_sensor:015]: GPIO Binary Sensor 'key3'
[13:45:20][C][gpio.binary_sensor:016]:   Pin: GPIO10
[13:45:20][C][light:103]: Light 'status_led'
[13:45:20][C][light:105]:   Default Transition Length: 1.0s
[13:45:20][C][light:106]:   Gamma Correct: 2.80
[13:45:20][C][homeassistant.time:010]: Home Assistant Time:
[13:45:20][C][homeassistant.time:011]:   Timezone: 'CET-1CEST,M3.5.0,M10.5.0/3'
[13:45:20][C][version.text_sensor:021]: Version Text Sensor 'ESPHome Version'
[13:45:20][C][version.text_sensor:021]:   Icon: 'mdi:new-box'
[13:45:20][C][sprinkler:1626]: Sprinkler Controller -- Sprinkler Start/Resume/Stop
[13:45:20][C][sprinkler:1651]:   Valve Open Delay: 10 seconds
[13:45:20][C][sprinkler:1652]:   Pump Switch Off During Valve Open Delay: NO
[13:45:20][C][sprinkler:1657]:   Valve 0:
[13:45:20][C][sprinkler:1658]:     Name: Sprinkler Zone 1
[13:45:20][C][sprinkler:1659]:     Run Duration: 60 seconds
[13:45:20][C][sprinkler:1657]:   Valve 1:
[13:45:20][C][sprinkler:1658]:     Name: Sprinkler Zone 2
[13:45:20][C][sprinkler:1659]:     Run Duration: 60 seconds
[13:45:20][C][sprinkler:1669]:   Total number of valves: 2
[13:45:20][C][sprinkler:1626]: Sprinkler Controller -- Drip Start/Resume/Stop
[13:45:20][C][sprinkler:1657]:   Valve 0:
[13:45:20][C][sprinkler:1658]:     Name: Drip Zone
[13:45:20][C][sprinkler:1659]:     Run Duration: 1800 seconds
[13:45:20][C][sprinkler:1657]:   Valve 1:
[13:45:20][C][sprinkler:1658]:     Name: Unused Switch
[13:45:20][C][sprinkler:1659]:     Run Duration: 1800 seconds
[13:45:20][C][sprinkler:1669]:   Total number of valves: 2
[13:45:20][C][restart.button:017]: Restart Button 'Sprinkler Controller Reboot'
[13:45:20][C][sprinkler:104]: Sprinkler Controller Number 'Sprinkler Multiplier'
[13:45:20][C][sprinkler:104]:   Icon: 'mdi:timer-cog-outline'
[13:45:21][C][sprinkler:104]: Sprinkler Controller Number 'Drip Multiplier'
[13:45:21][C][sprinkler:104]:   Icon: 'mdi:timer-cog-outline'
[13:45:21][C][sprinkler:104]: Sprinkler Controller Number 'Sprinkler Zone 1 Duration'
[13:45:21][C][sprinkler:104]:   Icon: 'mdi:timer-outline'
[13:45:21][C][sprinkler:104]:   Unit of Measurement: 'min'
[13:45:21][C][sprinkler:104]: Sprinkler Controller Number 'Sprinkler Zone 2 Duration'
[13:45:21][C][sprinkler:104]:   Icon: 'mdi:timer-outline'
[13:45:21][C][sprinkler:104]:   Unit of Measurement: 'min'
[13:45:21][C][sprinkler:104]: Sprinkler Controller Number 'Drip Zone 1 Duration'
[13:45:21][C][sprinkler:104]:   Icon: 'mdi:timer-outline'
[13:45:21][C][sprinkler:104]:   Unit of Measurement: 'min'
[13:45:21][C][sprinkler:104]: Sprinkler Controller Number 'Drip Zone 2 Duration'
[13:45:21][C][sprinkler:104]:   Icon: 'mdi:timer-outline'
[13:45:21][C][sprinkler:104]:   Unit of Measurement: 'min'
[13:45:21][C][captive_portal:088]: Captive Portal:
[13:45:21][C][web_server:151]: Web Server:
[13:45:21][C][web_server:152]:   Address: sonoff4chpro_sprinkler.localdomain:80
[13:45:21][C][mdns:108]: mDNS:
[13:45:21][C][mdns:109]:   Hostname: sonoff4chpro_sprinkler
[13:45:21][C][ota:093]: Over-The-Air Updates:
[13:45:21][C][ota:094]:   Address: sonoff4chpro_sprinkler.localdomain:8266
[13:45:21][C][api:138]: API Server:
[13:45:21][C][api:139]:   Address: sonoff4chpro_sprinkler.localdomain:6053
[13:45:21][C][api:143]:   Using noise encryption: NO
[13:45:21][C][wifi_signal.sensor:009]: WiFi Signal 'WiFi Signal'
[13:45:21][C][wifi_signal.sensor:009]:   Device Class: 'signal_strength'
[13:45:21][C][wifi_signal.sensor:009]:   State Class: 'measurement'
[13:45:21][C][wifi_signal.sensor:009]:   Unit of Measurement: 'dBm'
[13:45:21][C][wifi_signal.sensor:009]:   Accuracy Decimals: 0
[13:45:34][D][switch:012]: 'Sprinkler Start/Resume/Stop' Turning ON.
[13:45:34][D][sprinkler:1364]: CYCLE is starting valve 0 for 30 seconds, cycle 1 of 1
[13:45:34][D][switch:012]: 'Relay 1' Turning ON.
[13:45:34][D][switch:055]: 'Relay 1': Sending state ON
[13:45:34][D][switch:055]: 'Sprinkler Start/Resume/Stop': Sending state ON
[13:45:34][D][switch:055]: 'Sprinkler Zone 1': Sending state ON
[13:45:34][D][text_sensor:064]: 'Sprinkler Controller Status': Sending state 'Zone 1 Active'
[13:45:34][D][text_sensor:064]: 'Sprinkler Zone 1 Status': Sending state 'Running'
[13:45:35][D][sensor:109]: 'Sprinkler Controller Status Internal': Sending state 2.00000  with 1 decimals of accuracy
[13:45:35][D][text_sensor:064]: 'Sprinkler Controller Overall Time Remaining': Sending state '59s'
[13:45:35][D][sensor:109]: 'Sprinkler Controller Overall Progress Percentage': Sending state 1.00000  with 1 decimals of accuracy
[13:45:35][D][text_sensor:064]: 'Sprinkler Zone 1 Time Remaining': Sending state '29s'
[13:45:35][D][sensor:109]: 'Sprinkler Zone 1 Progress Percentage': Sending state 3.00000  with 1 decimals of accuracy
[13:45:36][D][text_sensor:064]: 'Sprinkler Controller Overall Time Remaining': Sending state '58s'
[13:45:36][D][sensor:109]: 'Sprinkler Controller Overall Progress Percentage': Sending state 3.00000  with 1 decimals of accuracy
[13:45:36][D][text_sensor:064]: 'Sprinkler Zone 1 Time Remaining': Sending state '28s'
[13:45:36][D][sensor:109]: 'Sprinkler Zone 1 Progress Percentage': Sending state 6.00000  with 1 decimals of accuracy
[13:45:37][D][text_sensor:064]: 'Sprinkler Controller Overall Time Remaining': Sending state '57s'
[13:45:37][D][sensor:109]: 'Sprinkler Controller Overall Progress Percentage': Sending state 5.00000  with 1 decimals of accuracy
[13:45:37][D][text_sensor:064]: 'Sprinkler Zone 1 Time Remaining': Sending state '27s'
[13:45:37][D][sensor:109]: 'Sprinkler Zone 1 Progress Percentage': Sending state 10.00000  with 1 decimals of accuracy
[13:45:38][D][text_sensor:064]: 'Sprinkler Controller Overall Time Remaining': Sending state '56s'
[13:45:38][D][sensor:109]: 'Sprinkler Controller Overall Progress Percentage': Sending state 6.00000  with 1 decimals of accuracy
[13:45:38][D][text_sensor:064]: 'Sprinkler Zone 1 Time Remaining': Sending state '26s'
[13:45:38][D][sensor:109]: 'Sprinkler Zone 1 Progress Percentage': Sending state 13.00000  with 1 decimals of accuracy
[13:45:39][D][text_sensor:064]: 'Sprinkler Controller Overall Time Remaining': Sending state '55s'
[13:45:39][D][sensor:109]: 'Sprinkler Controller Overall Progress Percentage': Sending state 8.00000  with 1 decimals of accuracy
[13:45:39][D][text_sensor:064]: 'Sprinkler Zone 1 Time Remaining': Sending state '25s'
[13:45:39][D][sensor:109]: 'Sprinkler Zone 1 Progress Percentage': Sending state 16.00000  with 1 decimals of accuracy
[13:45:40][D][text_sensor:064]: 'Sprinkler Controller Overall Time Remaining': Sending state '54s'
[13:45:40][D][sensor:109]: 'Sprinkler Controller Overall Progress Percentage': Sending state 10.00000  with 1 decimals of accuracy
[13:45:40][D][text_sensor:064]: 'Sprinkler Zone 1 Time Remaining': Sending state '24s'
[13:45:40][D][sensor:109]: 'Sprinkler Zone 1 Progress Percentage': Sending state 20.00000  with 1 decimals of accuracy
[13:45:41][D][text_sensor:064]: 'Sprinkler Controller Overall Time Remaining': Sending state '53s'
[13:45:41][D][sensor:109]: 'Sprinkler Controller Overall Progress Percentage': Sending state 11.00000  with 1 decimals of accuracy
[13:45:41][D][text_sensor:064]: 'Sprinkler Zone 1 Time Remaining': Sending state '23s'
[13:45:41][D][sensor:109]: 'Sprinkler Zone 1 Progress Percentage': Sending state 23.00000  with 1 decimals of accuracy
[13:45:42][D][text_sensor:064]: 'Sprinkler Controller Overall Time Remaining': Sending state '52s'
[13:45:42][D][sensor:109]: 'Sprinkler Controller Overall Progress Percentage': Sending state 13.00000  with 1 decimals of accuracy
[13:45:42][D][text_sensor:064]: 'Sprinkler Zone 1 Time Remaining': Sending state '22s'
[13:45:42][D][sensor:109]: 'Sprinkler Zone 1 Progress Percentage': Sending state 26.00000  with 1 decimals of accuracy
[13:45:43][D][text_sensor:064]: 'Sprinkler Controller Overall Time Remaining': Sending state '51s'
[13:45:43][D][sensor:109]: 'Sprinkler Controller Overall Progress Percentage': Sending state 15.00000  with 1 decimals of accuracy
[13:45:43][D][text_sensor:064]: 'Sprinkler Zone 1 Time Remaining': Sending state '21s'
[13:45:43][D][sensor:109]: 'Sprinkler Zone 1 Progress Percentage': Sending state 30.00000  with 1 decimals of accuracy
[13:45:44][D][text_sensor:064]: 'Sprinkler Controller Overall Time Remaining': Sending state '50s'
[13:45:44][D][sensor:109]: 'Sprinkler Controller Overall Progress Percentage': Sending state 16.00000  with 1 decimals of accuracy
[13:45:44][D][text_sensor:064]: 'Sprinkler Zone 1 Time Remaining': Sending state '20s'
[13:45:44][D][sensor:109]: 'Sprinkler Zone 1 Progress Percentage': Sending state 33.00000  with 1 decimals of accuracy
[13:45:45][D][text_sensor:064]: 'Sprinkler Controller Overall Time Remaining': Sending state '49s'
[13:45:45][D][sensor:109]: 'Sprinkler Controller Overall Progress Percentage': Sending state 18.00000  with 1 decimals of accuracy
[13:45:45][D][text_sensor:064]: 'Sprinkler Zone 1 Time Remaining': Sending state '19s'
[13:45:45][D][sensor:109]: 'Sprinkler Zone 1 Progress Percentage': Sending state 36.00000  with 1 decimals of accuracy
[13:45:46][D][text_sensor:064]: 'Sprinkler Controller Overall Time Remaining': Sending state '48s'
[13:45:46][D][sensor:109]: 'Sprinkler Controller Overall Progress Percentage': Sending state 20.00000  with 1 decimals of accuracy
[13:45:46][D][text_sensor:064]: 'Sprinkler Zone 1 Time Remaining': Sending state '18s'
[13:45:46][D][sensor:109]: 'Sprinkler Zone 1 Progress Percentage': Sending state 40.00000  with 1 decimals of accuracy
[13:45:47][D][text_sensor:064]: 'Sprinkler Controller Overall Time Remaining': Sending state '47s'
[13:45:47][D][sensor:109]: 'Sprinkler Controller Overall Progress Percentage': Sending state 21.00000  with 1 decimals of accuracy
[13:45:47][D][text_sensor:064]: 'Sprinkler Zone 1 Time Remaining': Sending state '17s'
[13:45:47][D][sensor:109]: 'Sprinkler Zone 1 Progress Percentage': Sending state 43.00000  with 1 decimals of accuracy
[13:45:48][D][text_sensor:064]: 'Sprinkler Controller Overall Time Remaining': Sending state '46s'
[13:45:48][D][sensor:109]: 'Sprinkler Controller Overall Progress Percentage': Sending state 23.00000  with 1 decimals of accuracy
[13:45:48][D][text_sensor:064]: 'Sprinkler Zone 1 Time Remaining': Sending state '16s'
[13:45:48][D][sensor:109]: 'Sprinkler Zone 1 Progress Percentage': Sending state 46.00000  with 1 decimals of accuracy
[13:45:49][D][text_sensor:064]: 'Sprinkler Controller Overall Time Remaining': Sending state '45s'
[13:45:49][D][sensor:109]: 'Sprinkler Controller Overall Progress Percentage': Sending state 25.00000  with 1 decimals of accuracy
[13:45:49][D][text_sensor:064]: 'Sprinkler Zone 1 Time Remaining': Sending state '15s'
[13:45:49][D][sensor:109]: 'Sprinkler Zone 1 Progress Percentage': Sending state 50.00000  with 1 decimals of accuracy
[13:45:50][D][text_sensor:064]: 'Sprinkler Controller Overall Time Remaining': Sending state '44s'
[13:45:50][D][sensor:109]: 'Sprinkler Controller Overall Progress Percentage': Sending state 26.00000  with 1 decimals of accuracy
[13:45:50][D][text_sensor:064]: 'Sprinkler Zone 1 Time Remaining': Sending state '14s'
[13:45:50][D][sensor:109]: 'Sprinkler Zone 1 Progress Percentage': Sending state 53.00000  with 1 decimals of accuracy
[13:45:51][D][text_sensor:064]: 'Sprinkler Controller Overall Time Remaining': Sending state '43s'
[13:45:51][D][sensor:109]: 'Sprinkler Controller Overall Progress Percentage': Sending state 28.00000  with 1 decimals of accuracy
[13:45:51][D][text_sensor:064]: 'Sprinkler Zone 1 Time Remaining': Sending state '13s'
[13:45:51][D][sensor:109]: 'Sprinkler Zone 1 Progress Percentage': Sending state 56.00000  with 1 decimals of accuracy
[13:45:52][D][text_sensor:064]: 'Sprinkler Controller Overall Time Remaining': Sending state '42s'
[13:45:52][D][sensor:109]: 'Sprinkler Controller Overall Progress Percentage': Sending state 30.00000  with 1 decimals of accuracy
[13:45:52][D][text_sensor:064]: 'Sprinkler Zone 1 Time Remaining': Sending state '12s'
[13:45:52][D][sensor:109]: 'Sprinkler Zone 1 Progress Percentage': Sending state 60.00000  with 1 decimals of accuracy
[13:45:53][D][text_sensor:064]: 'Sprinkler Controller Overall Time Remaining': Sending state '41s'
[13:45:53][D][sensor:109]: 'Sprinkler Controller Overall Progress Percentage': Sending state 31.00000  with 1 decimals of accuracy
[13:45:53][D][text_sensor:064]: 'Sprinkler Zone 1 Time Remaining': Sending state '11s'
[13:45:53][D][sensor:109]: 'Sprinkler Zone 1 Progress Percentage': Sending state 63.00000  with 1 decimals of accuracy
[13:45:54][D][text_sensor:064]: 'Sprinkler Controller Overall Time Remaining': Sending state '40s'
[13:45:54][D][sensor:109]: 'Sprinkler Controller Overall Progress Percentage': Sending state 33.00000  with 1 decimals of accuracy
[13:45:54][D][text_sensor:064]: 'Sprinkler Zone 1 Time Remaining': Sending state '10s'
[13:45:54][D][sensor:109]: 'Sprinkler Zone 1 Progress Percentage': Sending state 66.00000  with 1 decimals of accuracy
[13:45:54][D][sprinkler:1242]: Marking valve 0 complete
[13:45:55][D][sensor:109]: 'Sprinkler Controller Status Internal': Sending state 1.00000  with 1 decimals of accuracy
[13:45:55][D][text_sensor:064]: 'Sprinkler Zone 2 Time Remaining': Sending state '9s'
[13:45:55][D][sensor:109]: 'Sprinkler Zone 2 Progress Percentage': Sending state 70.00000  with 1 decimals of accuracy
[13:45:55][D][text_sensor:064]: 'Sprinkler Controller Overall Time Remaining': Sending state '9s'
[13:45:55][D][sensor:109]: 'Sprinkler Controller Overall Progress Percentage': Sending state 85.00000  with 1 decimals of accuracy
[13:45:55][D][sensor:109]: 'Sprinkler Zone 1 Progress Percentage': Sending state 100.00000  with 1 decimals of accuracy
[13:45:56][D][text_sensor:064]: 'Sprinkler Zone 2 Time Remaining': Sending state '8s'
[13:45:56][D][sensor:109]: 'Sprinkler Zone 2 Progress Percentage': Sending state 73.00000  with 1 decimals of accuracy
[13:45:56][D][text_sensor:064]: 'Sprinkler Controller Overall Time Remaining': Sending state '8s'
[13:45:56][D][sensor:109]: 'Sprinkler Controller Overall Progress Percentage': Sending state 86.00000  with 1 decimals of accuracy
[13:45:57][D][text_sensor:064]: 'Sprinkler Zone 2 Time Remaining': Sending state '7s'
[13:45:57][D][sensor:109]: 'Sprinkler Zone 2 Progress Percentage': Sending state 76.00000  with 1 decimals of accuracy
[13:45:57][D][text_sensor:064]: 'Sprinkler Controller Overall Time Remaining': Sending state '7s'
[13:45:57][D][sensor:109]: 'Sprinkler Controller Overall Progress Percentage': Sending state 88.00000  with 1 decimals of accuracy
[13:45:58][D][text_sensor:064]: 'Sprinkler Zone 2 Time Remaining': Sending state '6s'
[13:45:58][D][sensor:109]: 'Sprinkler Zone 2 Progress Percentage': Sending state 80.00000  with 1 decimals of accuracy
[13:45:58][D][text_sensor:064]: 'Sprinkler Controller Overall Time Remaining': Sending state '6s'
[13:45:58][D][sensor:109]: 'Sprinkler Controller Overall Progress Percentage': Sending state 90.00000  with 1 decimals of accuracy
[13:45:59][D][text_sensor:064]: 'Sprinkler Zone 2 Time Remaining': Sending state '5s'
[13:45:59][D][sensor:109]: 'Sprinkler Zone 2 Progress Percentage': Sending state 83.00000  with 1 decimals of accuracy
[13:45:59][D][text_sensor:064]: 'Sprinkler Controller Overall Time Remaining': Sending state '5s'
[13:45:59][D][sensor:109]: 'Sprinkler Controller Overall Progress Percentage': Sending state 91.00000  with 1 decimals of accuracy
[13:46:00][D][text_sensor:064]: 'Sprinkler Zone 2 Time Remaining': Sending state '4s'
[13:46:00][D][sensor:109]: 'Sprinkler Zone 2 Progress Percentage': Sending state 86.00000  with 1 decimals of accuracy
[13:46:00][D][text_sensor:064]: 'Sprinkler Controller Overall Time Remaining': Sending state '4s'
[13:46:00][D][sensor:109]: 'Sprinkler Controller Overall Progress Percentage': Sending state 93.00000  with 1 decimals of accuracy
[13:46:01][D][text_sensor:064]: 'Sprinkler Zone 2 Time Remaining': Sending state '3s'
[13:46:01][D][sensor:109]: 'Sprinkler Zone 2 Progress Percentage': Sending state 90.00000  with 1 decimals of accuracy
[13:46:01][D][text_sensor:064]: 'Sprinkler Controller Overall Time Remaining': Sending state '3s'
[13:46:01][D][sensor:109]: 'Sprinkler Controller Overall Progress Percentage': Sending state 95.00000  with 1 decimals of accuracy
[13:46:02][D][text_sensor:064]: 'Sprinkler Zone 2 Time Remaining': Sending state '2s'
[13:46:02][D][sensor:109]: 'Sprinkler Zone 2 Progress Percentage': Sending state 93.00000  with 1 decimals of accuracy
[13:46:02][D][text_sensor:064]: 'Sprinkler Controller Overall Time Remaining': Sending state '2s'
[13:46:02][D][sensor:109]: 'Sprinkler Controller Overall Progress Percentage': Sending state 96.00000  with 1 decimals of accuracy
[13:46:03][D][text_sensor:064]: 'Sprinkler Zone 2 Time Remaining': Sending state '1s'
[13:46:03][D][sensor:109]: 'Sprinkler Zone 2 Progress Percentage': Sending state 96.00000  with 1 decimals of accuracy
[13:46:03][D][text_sensor:064]: 'Sprinkler Controller Overall Time Remaining': Sending state '1s'
[13:46:03][D][sensor:109]: 'Sprinkler Controller Overall Progress Percentage': Sending state 98.00000  with 1 decimals of accuracy
[13:46:04][D][text_sensor:064]: 'Sprinkler Zone 2 Time Remaining': Sending state '0s'
[13:46:04][D][sensor:109]: 'Sprinkler Zone 2 Progress Percentage': Sending state 100.00000  with 1 decimals of accuracy
[13:46:04][D][text_sensor:064]: 'Sprinkler Controller Overall Time Remaining': Sending state '0s'
[13:46:04][D][sensor:109]: 'Sprinkler Controller Overall Progress Percentage': Sending state 100.00000  with 1 decimals of accuracy
[13:46:04][D][switch:016]: 'Relay 1' Turning OFF.
[13:46:04][D][switch:055]: 'Relay 1': Sending state OFF
[13:46:04][D][switch:055]: 'Sprinkler Zone 1': Sending state OFF
[13:46:04][D][text_sensor:064]: 'Sprinkler Controller Status': Sending state 'Idle'
[13:46:04][D][text_sensor:064]: 'Sprinkler Zone 1 Status': Sending state 'Idle'
[13:46:04][D][text_sensor:064]: 'Sprinkler Zone 1 Time Remaining': Sending state '--'
[13:46:05][D][text_sensor:064]: 'Sprinkler Zone 2 Time Remaining': Sending state '1s'
[13:46:05][D][sensor:109]: 'Sprinkler Zone 2 Progress Percentage': Sending state 96.00000  with 1 decimals of accuracy
[13:46:05][D][text_sensor:064]: 'Sprinkler Controller Overall Time Remaining': Sending state '0s'
[13:46:06][D][sensor:109]: 'WiFi Signal': Sending state -66.00000 dBm with 0 decimals of accuracy
[13:46:06][D][text_sensor:064]: 'Sprinkler Zone 2 Time Remaining': Sending state '1s'
[13:46:06][D][text_sensor:064]: 'Sprinkler Controller Overall Time Remaining': Sending state '0s'
[13:46:06][D][sensor:109]: 'Uptime': Sending state 560.40503 s with 0 decimals of accuracy
[13:46:07][D][text_sensor:064]: 'Sprinkler Zone 2 Time Remaining': Sending state '1s'
[13:46:07][D][text_sensor:064]: 'Sprinkler Controller Overall Time Remaining': Sending state '0s'
[13:46:08][D][text_sensor:064]: 'Sprinkler Zone 2 Time Remaining': Sending state '1s'
[13:46:08][D][text_sensor:064]: 'Sprinkler Controller Overall Time Remaining': Sending state '0s'
[13:46:09][D][text_sensor:064]: 'Sprinkler Zone 2 Time Remaining': Sending state '1s'
[13:46:09][D][text_sensor:064]: 'Sprinkler Controller Overall Time Remaining': Sending state '0s'
[13:46:10][D][text_sensor:064]: 'Sprinkler Zone 2 Time Remaining': Sending state '1s'
[13:46:10][D][text_sensor:064]: 'Sprinkler Controller Overall Time Remaining': Sending state '0s'
[13:46:11][D][text_sensor:064]: 'Sprinkler Zone 2 Time Remaining': Sending state '1s'
[13:46:11][D][text_sensor:064]: 'Sprinkler Controller Overall Time Remaining': Sending state '0s'
[13:46:12][D][text_sensor:064]: 'Sprinkler Zone 2 Time Remaining': Sending state '1s'
[13:46:12][D][text_sensor:064]: 'Sprinkler Controller Overall Time Remaining': Sending state '0s'
[13:46:13][D][text_sensor:064]: 'Sprinkler Zone 2 Time Remaining': Sending state '1s'
[13:46:13][D][text_sensor:064]: 'Sprinkler Controller Overall Time Remaining': Sending state '0s'
[13:46:14][D][text_sensor:064]: 'Sprinkler Zone 2 Time Remaining': Sending state '1s'
[13:46:14][D][text_sensor:064]: 'Sprinkler Controller Overall Time Remaining': Sending state '0s'
[13:46:14][D][sprinkler:1364]: CYCLE is starting valve 1 for 30 seconds, cycle 1 of 1
[13:46:14][D][switch:012]: 'Relay 2' Turning ON.
[13:46:14][D][switch:055]: 'Relay 2': Sending state ON
[13:46:14][D][switch:055]: 'Sprinkler Zone 2': Sending state ON
[13:46:14][D][text_sensor:064]: 'Sprinkler Controller Status': Sending state 'Zone 2 Active'
[13:46:14][D][text_sensor:064]: 'Sprinkler Zone 2 Status': Sending state 'Running'
[13:46:15][D][sensor:109]: 'Sprinkler Controller Status Internal': Sending state 2.00000  with 1 decimals of accuracy
[13:46:15][D][text_sensor:064]: 'Sprinkler Zone 2 Time Remaining': Sending state '29s'
[13:46:15][D][sensor:109]: 'Sprinkler Zone 2 Progress Percentage': Sending state 3.00000  with 1 decimals of accuracy
[13:46:15][D][text_sensor:064]: 'Sprinkler Controller Overall Time Remaining': Sending state '29s'
[13:46:15][D][sensor:109]: 'Sprinkler Controller Overall Progress Percentage': Sending state 51.00000  with 1 decimals of accuracy
[13:46:16][D][text_sensor:064]: 'Sprinkler Zone 2 Time Remaining': Sending state '28s'
[13:46:16][D][sensor:109]: 'Sprinkler Zone 2 Progress Percentage': Sending state 6.00000  with 1 decimals of accuracy
[13:46:16][D][text_sensor:064]: 'Sprinkler Controller Overall Time Remaining': Sending state '28s'
[13:46:16][D][sensor:109]: 'Sprinkler Controller Overall Progress Percentage': Sending state 53.00000  with 1 decimals of accuracy
[13:46:17][D][text_sensor:064]: 'Sprinkler Zone 2 Time Remaining': Sending state '27s'
[13:46:17][D][sensor:109]: 'Sprinkler Zone 2 Progress Percentage': Sending state 10.00000  with 1 decimals of accuracy
[13:46:17][D][text_sensor:064]: 'Sprinkler Controller Overall Time Remaining': Sending state '27s'
[13:46:17][D][sensor:109]: 'Sprinkler Controller Overall Progress Percentage': Sending state 55.00000  with 1 decimals of accuracy
[13:46:18][D][text_sensor:064]: 'Sprinkler Zone 2 Time Remaining': Sending state '26s'
[13:46:18][D][sensor:109]: 'Sprinkler Zone 2 Progress Percentage': Sending state 13.00000  with 1 decimals of accuracy
[13:46:18][D][text_sensor:064]: 'Sprinkler Controller Overall Time Remaining': Sending state '26s'
[13:46:18][D][sensor:109]: 'Sprinkler Controller Overall Progress Percentage': Sending state 56.00000  with 1 decimals of accuracy
[13:46:19][D][text_sensor:064]: 'Sprinkler Zone 2 Time Remaining': Sending state '25s'
[13:46:19][D][sensor:109]: 'Sprinkler Zone 2 Progress Percentage': Sending state 16.00000  with 1 decimals of accuracy
[13:46:19][D][text_sensor:064]: 'Sprinkler Controller Overall Time Remaining': Sending state '25s'
[13:46:19][D][sensor:109]: 'Sprinkler Controller Overall Progress Percentage': Sending state 58.00000  with 1 decimals of accuracy
[13:46:20][D][text_sensor:064]: 'Sprinkler Zone 2 Time Remaining': Sending state '24s'
[13:46:20][D][sensor:109]: 'Sprinkler Zone 2 Progress Percentage': Sending state 20.00000  with 1 decimals of accuracy
[13:46:20][D][text_sensor:064]: 'Sprinkler Controller Overall Time Remaining': Sending state '24s'
[13:46:20][D][sensor:109]: 'Sprinkler Controller Overall Progress Percentage': Sending state 60.00000  with 1 decimals of accuracy
[13:46:21][D][text_sensor:064]: 'Sprinkler Zone 2 Time Remaining': Sending state '23s'
[13:46:21][D][sensor:109]: 'Sprinkler Zone 2 Progress Percentage': Sending state 23.00000  with 1 decimals of accuracy
[13:46:21][D][text_sensor:064]: 'Sprinkler Controller Overall Time Remaining': Sending state '23s'
[13:46:21][D][sensor:109]: 'Sprinkler Controller Overall Progress Percentage': Sending state 61.00000  with 1 decimals of accuracy
[13:46:22][D][text_sensor:064]: 'Sprinkler Zone 2 Time Remaining': Sending state '22s'
[13:46:22][D][sensor:109]: 'Sprinkler Zone 2 Progress Percentage': Sending state 26.00000  with 1 decimals of accuracy
[13:46:22][D][text_sensor:064]: 'Sprinkler Controller Overall Time Remaining': Sending state '22s'
[13:46:22][D][sensor:109]: 'Sprinkler Controller Overall Progress Percentage': Sending state 63.00000  with 1 decimals of accuracy
[13:46:23][D][text_sensor:064]: 'Sprinkler Zone 2 Time Remaining': Sending state '21s'
[13:46:23][D][sensor:109]: 'Sprinkler Zone 2 Progress Percentage': Sending state 30.00000  with 1 decimals of accuracy
[13:46:23][D][text_sensor:064]: 'Sprinkler Controller Overall Time Remaining': Sending state '21s'
[13:46:23][D][sensor:109]: 'Sprinkler Controller Overall Progress Percentage': Sending state 65.00000  with 1 decimals of accuracy
[13:46:24][D][text_sensor:064]: 'Sprinkler Zone 2 Time Remaining': Sending state '20s'
[13:46:24][D][sensor:109]: 'Sprinkler Zone 2 Progress Percentage': Sending state 33.00000  with 1 decimals of accuracy
[13:46:24][D][text_sensor:064]: 'Sprinkler Controller Overall Time Remaining': Sending state '20s'
[13:46:24][D][sensor:109]: 'Sprinkler Controller Overall Progress Percentage': Sending state 66.00000  with 1 decimals of accuracy
[13:46:25][D][text_sensor:064]: 'Sprinkler Zone 2 Time Remaining': Sending state '19s'
[13:46:25][D][sensor:109]: 'Sprinkler Zone 2 Progress Percentage': Sending state 36.00000  with 1 decimals of accuracy
[13:46:25][D][text_sensor:064]: 'Sprinkler Controller Overall Time Remaining': Sending state '19s'
[13:46:25][D][sensor:109]: 'Sprinkler Controller Overall Progress Percentage': Sending state 68.00000  with 1 decimals of accuracy
[13:46:26][D][text_sensor:064]: 'Sprinkler Zone 2 Time Remaining': Sending state '18s'
[13:46:26][D][sensor:109]: 'Sprinkler Zone 2 Progress Percentage': Sending state 40.00000  with 1 decimals of accuracy
[13:46:26][D][text_sensor:064]: 'Sprinkler Controller Overall Time Remaining': Sending state '18s'
[13:46:26][D][sensor:109]: 'Sprinkler Controller Overall Progress Percentage': Sending state 70.00000  with 1 decimals of accuracy
[13:46:27][D][text_sensor:064]: 'Sprinkler Zone 2 Time Remaining': Sending state '17s'
[13:46:27][D][sensor:109]: 'Sprinkler Zone 2 Progress Percentage': Sending state 43.00000  with 1 decimals of accuracy
[13:46:27][D][text_sensor:064]: 'Sprinkler Controller Overall Time Remaining': Sending state '17s'
[13:46:27][D][sensor:109]: 'Sprinkler Controller Overall Progress Percentage': Sending state 71.00000  with 1 decimals of accuracy
[13:46:28][D][text_sensor:064]: 'Sprinkler Zone 2 Time Remaining': Sending state '16s'
[13:46:28][D][sensor:109]: 'Sprinkler Zone 2 Progress Percentage': Sending state 46.00000  with 1 decimals of accuracy
[13:46:28][D][text_sensor:064]: 'Sprinkler Controller Overall Time Remaining': Sending state '16s'
[13:46:28][D][sensor:109]: 'Sprinkler Controller Overall Progress Percentage': Sending state 73.00000  with 1 decimals of accuracy
[13:46:29][D][text_sensor:064]: 'Sprinkler Zone 2 Time Remaining': Sending state '15s'
[13:46:29][D][sensor:109]: 'Sprinkler Zone 2 Progress Percentage': Sending state 50.00000  with 1 decimals of accuracy
[13:46:29][D][text_sensor:064]: 'Sprinkler Controller Overall Time Remaining': Sending state '15s'
[13:46:29][D][sensor:109]: 'Sprinkler Controller Overall Progress Percentage': Sending state 75.00000  with 1 decimals of accuracy
[13:46:30][D][text_sensor:064]: 'Sprinkler Zone 2 Time Remaining': Sending state '14s'
[13:46:30][D][sensor:109]: 'Sprinkler Zone 2 Progress Percentage': Sending state 53.00000  with 1 decimals of accuracy
[13:46:30][D][text_sensor:064]: 'Sprinkler Controller Overall Time Remaining': Sending state '14s'
[13:46:30][D][sensor:109]: 'Sprinkler Controller Overall Progress Percentage': Sending state 76.00000  with 1 decimals of accuracy
[13:46:31][D][text_sensor:064]: 'Sprinkler Zone 2 Time Remaining': Sending state '13s'
[13:46:31][D][sensor:109]: 'Sprinkler Zone 2 Progress Percentage': Sending state 56.00000  with 1 decimals of accuracy
[13:46:31][D][text_sensor:064]: 'Sprinkler Controller Overall Time Remaining': Sending state '13s'
[13:46:31][D][sensor:109]: 'Sprinkler Controller Overall Progress Percentage': Sending state 78.00000  with 1 decimals of accuracy
[13:46:32][D][text_sensor:064]: 'Sprinkler Zone 2 Time Remaining': Sending state '12s'
[13:46:32][D][sensor:109]: 'Sprinkler Zone 2 Progress Percentage': Sending state 60.00000  with 1 decimals of accuracy
[13:46:32][D][text_sensor:064]: 'Sprinkler Controller Overall Time Remaining': Sending state '12s'
[13:46:32][D][sensor:109]: 'Sprinkler Controller Overall Progress Percentage': Sending state 80.00000  with 1 decimals of accuracy
[13:46:33][D][text_sensor:064]: 'Sprinkler Zone 2 Time Remaining': Sending state '11s'
[13:46:33][D][sensor:109]: 'Sprinkler Zone 2 Progress Percentage': Sending state 63.00000  with 1 decimals of accuracy
[13:46:33][D][text_sensor:064]: 'Sprinkler Controller Overall Time Remaining': Sending state '11s'
[13:46:33][D][sensor:109]: 'Sprinkler Controller Overall Progress Percentage': Sending state 81.00000  with 1 decimals of accuracy
[13:46:34][D][text_sensor:064]: 'Sprinkler Zone 2 Time Remaining': Sending state '10s'
[13:46:34][D][sensor:109]: 'Sprinkler Zone 2 Progress Percentage': Sending state 66.00000  with 1 decimals of accuracy
[13:46:34][D][text_sensor:064]: 'Sprinkler Controller Overall Time Remaining': Sending state '10s'
[13:46:34][D][sensor:109]: 'Sprinkler Controller Overall Progress Percentage': Sending state 83.00000  with 1 decimals of accuracy
[13:46:34][D][sprinkler:1242]: Marking valve 1 complete
[13:46:35][D][sensor:109]: 'Sprinkler Controller Status Internal': Sending state 3.00000  with 1 decimals of accuracy
[13:46:35][D][text_sensor:064]: 'Sprinkler Zone 2 Time Remaining': Sending state '9s'
[13:46:35][D][sensor:109]: 'Sprinkler Zone 2 Progress Percentage': Sending state 70.00000  with 1 decimals of accuracy
[13:46:35][D][text_sensor:064]: 'Sprinkler Controller Overall Time Remaining': Sending state '-1m -1s'
[13:46:35][D][sensor:109]: 'Sprinkler Controller Overall Progress Percentage': Sending state 201.00000  with 1 decimals of accuracy
[13:46:36][D][text_sensor:064]: 'Sprinkler Zone 2 Time Remaining': Sending state '8s'
[13:46:36][D][sensor:109]: 'Sprinkler Zone 2 Progress Percentage': Sending state 73.00000  with 1 decimals of accuracy
[13:46:36][D][text_sensor:064]: 'Sprinkler Controller Overall Time Remaining': Sending state '-1m -2s'
[13:46:36][D][sensor:109]: 'Sprinkler Controller Overall Progress Percentage': Sending state 203.00000  with 1 decimals of accuracy
[13:46:37][D][text_sensor:064]: 'Sprinkler Zone 2 Time Remaining': Sending state '7s'
[13:46:37][D][sensor:109]: 'Sprinkler Zone 2 Progress Percentage': Sending state 76.00000  with 1 decimals of accuracy
[13:46:37][D][text_sensor:064]: 'Sprinkler Controller Overall Time Remaining': Sending state '-1m -3s'
[13:46:37][D][sensor:109]: 'Sprinkler Controller Overall Progress Percentage': Sending state 205.00000  with 1 decimals of accuracy
[13:46:38][D][text_sensor:064]: 'Sprinkler Zone 2 Time Remaining': Sending state '6s'
[13:46:38][D][sensor:109]: 'Sprinkler Zone 2 Progress Percentage': Sending state 80.00000  with 1 decimals of accuracy
[13:46:38][D][text_sensor:064]: 'Sprinkler Controller Overall Time Remaining': Sending state '-1m -4s'
[13:46:38][D][sensor:109]: 'Sprinkler Controller Overall Progress Percentage': Sending state 206.00000  with 1 decimals of accuracy
[13:46:39][D][text_sensor:064]: 'Sprinkler Zone 2 Time Remaining': Sending state '5s'
[13:46:39][D][sensor:109]: 'Sprinkler Zone 2 Progress Percentage': Sending state 83.00000  with 1 decimals of accuracy
[13:46:39][D][text_sensor:064]: 'Sprinkler Controller Overall Time Remaining': Sending state '-1m -5s'
[13:46:39][D][sensor:109]: 'Sprinkler Controller Overall Progress Percentage': Sending state 208.00000  with 1 decimals of accuracy
[13:46:40][D][text_sensor:064]: 'Sprinkler Zone 2 Time Remaining': Sending state '4s'
[13:46:40][D][sensor:109]: 'Sprinkler Zone 2 Progress Percentage': Sending state 86.00000  with 1 decimals of accuracy
[13:46:40][D][text_sensor:064]: 'Sprinkler Controller Overall Time Remaining': Sending state '-1m -6s'
[13:46:40][D][sensor:109]: 'Sprinkler Controller Overall Progress Percentage': Sending state 210.00000  with 1 decimals of accuracy
[13:46:41][D][text_sensor:064]: 'Sprinkler Zone 2 Time Remaining': Sending state '3s'
[13:46:41][D][sensor:109]: 'Sprinkler Zone 2 Progress Percentage': Sending state 90.00000  with 1 decimals of accuracy
[13:46:41][D][text_sensor:064]: 'Sprinkler Controller Overall Time Remaining': Sending state '-1m -7s'
[13:46:41][D][sensor:109]: 'Sprinkler Controller Overall Progress Percentage': Sending state 211.00000  with 1 decimals of accuracy
[13:46:42][D][text_sensor:064]: 'Sprinkler Zone 2 Time Remaining': Sending state '2s'
[13:46:42][D][sensor:109]: 'Sprinkler Zone 2 Progress Percentage': Sending state 93.00000  with 1 decimals of accuracy
[13:46:42][D][text_sensor:064]: 'Sprinkler Controller Overall Time Remaining': Sending state '-1m -8s'
[13:46:42][D][sensor:109]: 'Sprinkler Controller Overall Progress Percentage': Sending state 213.00000  with 1 decimals of accuracy
[13:46:43][D][text_sensor:064]: 'Sprinkler Zone 2 Time Remaining': Sending state '1s'
[13:46:43][D][sensor:109]: 'Sprinkler Zone 2 Progress Percentage': Sending state 96.00000  with 1 decimals of accuracy
[13:46:43][D][text_sensor:064]: 'Sprinkler Controller Overall Time Remaining': Sending state '-1m -9s'
[13:46:43][D][sensor:109]: 'Sprinkler Controller Overall Progress Percentage': Sending state 215.00000  with 1 decimals of accuracy
[13:46:44][D][text_sensor:064]: 'Sprinkler Zone 2 Time Remaining': Sending state '0s'
[13:46:44][D][sensor:109]: 'Sprinkler Zone 2 Progress Percentage': Sending state 100.00000  with 1 decimals of accuracy
[13:46:44][D][text_sensor:064]: 'Sprinkler Controller Overall Time Remaining': Sending state '-1m -10s'
[13:46:44][D][sensor:109]: 'Sprinkler Controller Overall Progress Percentage': Sending state 216.00000  with 1 decimals of accuracy
[13:46:44][D][switch:016]: 'Relay 2' Turning OFF.
[13:46:44][D][switch:055]: 'Relay 2': Sending state OFF
[13:46:44][D][switch:055]: 'Sprinkler Zone 2': Sending state OFF
[13:46:44][D][text_sensor:064]: 'Sprinkler Controller Status': Sending state 'Idle'
[13:46:44][D][text_sensor:064]: 'Sprinkler Zone 2 Status': Sending state 'Idle'
[13:46:44][D][text_sensor:064]: 'Sprinkler Zone 2 Time Remaining': Sending state '--'
[13:46:45][D][text_sensor:064]: 'Sprinkler Zone 2 Time Remaining': Sending state '0s'
[13:46:45][D][text_sensor:064]: 'Sprinkler Controller Overall Time Remaining': Sending state '-1m -10s'
[13:46:45][D][sprinkler:1388]: All valves stopped, including pumps
[13:46:45][D][switch:055]: 'Sprinkler Start/Resume/Stop': Sending state OFF
[13:46:45][D][text_sensor:064]: 'Sprinkler Controller Overall Time Remaining': Sending state '--'
[13:46:46][D][sensor:109]: 'Sprinkler Controller Status Internal': Sending state 0.00000  with 1 decimals of accuracy
[13:46:46][D][sensor:109]: 'Sprinkler Zone 2 Progress Percentage': Sending state 0.00000  with 1 decimals of accuracy
[13:46:46][D][sensor:109]: 'Sprinkler Controller Overall Progress Percentage': Sending state 0.00000  with 1 decimals of accuracy
[13:46:46][D][sensor:109]: 'Sprinkler Zone 1 Progress Percentage': Sending state 0.00000  with 1 decimals of accuracy
[13:47:06][D][sensor:109]: 'WiFi Signal': Sending state -66.00000 dBm with 0 decimals of accuracy
[13:47:06][D][sensor:109]: 'Uptime': Sending state 620.40503 s with 0 decimals of accuracy
```

### Additional information

_No response_

### PR DESCRIPTION
**Pull request by kbx81**
# What does this implement/fix?

Fixes issues discussed in https://github.com/esphome/issues/issues/4502

## Types of changes

- [x] Bugfix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] Other

**Related issue or feature (if applicable):** fixes https://github.com/esphome/issues/issues/4502

**Pull request in [esphome-docs](https://github.com/esphome/esphome-docs) with documentation (if applicable):** esphome/esphome-docs#<esphome-docs PR number goes here>

## Test Environment

- [x] ESP32
- [ ] ESP32 IDF
- [ ] ESP8266
- [ ] RP2040

## Test this PR by adding this to your device's `config.yaml`:
```yaml
external_components:
  - source: github://pr#4816
    components: [ sprinkler ]
```

## Checklist:
  - [x] The code change is tested and works locally.
  - [ ] Tests have been added to verify that the new code works (under `tests/` folder).

If user exposed functionality or configuration variables are added/changed:
  - [ ] Documentation added/updated in [esphome-docs](https://github.com/esphome/esphome-docs).

### CODE REVIEW

File: esphome/components/sprinkler/sprinkler.cpp [hunk 1]
```diff
@@ -238,19 +240,33 @@ void SprinklerValveOperator::stop() {
...
     }
-    this->pinned_millis_ = millis();  // save the time the stop request was made
   } else {
     this->kill_();  // there is no stop_delay_, so just stop the pump and valve
   }
+  this->stop_millis_ = millis();  // save the time the stop request was made
 }
 
-uint32_t SprinklerValveOperator::run_duration() { return this->run_duration_; }
+uint32_t SprinklerValveOperator::run_duration() { return this->run_duration_ / 1000; }
```
Comment (jesserockz) [inline esphome/components/sprinkler/sprinkler.cpp:249]: Is this not confusing having `run_duration` on different classes take and give millis or seconds? They really should be all the same (millis)

Comment (kbx81) [reply esphome/components/sprinkler/sprinkler.cpp:249]: "Under the hood" everything is handled in milliseconds (because `millis()`). Outside of the classes, everything is in seconds, hence the `/ 1000` added here (this should've been here all along, I caught it as I was debugging. haha).

Comment (jesserockz) [reply esphome/components/sprinkler/sprinkler.cpp:249]: Would it not be better to always return millis everywhere and convert only when required for visual purposes?

Comment (jesserockz) [reply esphome/components/sprinkler/sprinkler.cpp:249]: Or at least switch everything to store also in seconds, but if you are using the values to compare against `millis()` then it makes more sensor to always have them as millis.

Its very easy to get lost in knowing which unit a time is in and best to keep everything consistent

Comment (kbx81) [reply esphome/components/sprinkler/sprinkler.cpp:249]: Good point -- let me take a look at that. 😄

Comment (kbx81) [reply esphome/components/sprinkler/sprinkler.cpp:249]: Alright, after reviewing this...

There are a couple functions that are public that are widely used by users -- `valve_run_duration()` and 
`valve_run_duration_adjusted()`. These are expected to return time in seconds. That said, they are also used extensively internally to get these values. Might sound crazy, but it seems it would introduce more complexity to change it than to leave it as-is. haha

The conversion is really only done by the `SprinklerValveOperator` class -- with the exception of where `set_timeout()` is used, everything else is using time in seconds. ⏲️

Comment (kbx81) [reply esphome/components/sprinkler/sprinkler.cpp:249]: ...so yes, it appears my earlier statement was wrong. That's what I get for trying to recite from memory and not actually checking. 😆

**Comment by olympia** [comment]
I was reporting [those issues](https://github.com/esphome/issues/issues/4502) what this PR is addressing and - following careful testing - I confirm that this PR is fixing those.

Many thanks @kbx81!

**Review by jesserockz — APPROVED** [review]
