### PR TITLE
Move i2c scan to setup

### LINKED ISSUE #2735: SPS30 not initializing
### The problem

I have a Lolin D1 mini board connected to a Sensirion SPS30 sensor via I2C. When I run connect ESPhome to this the sensor is not recognized. The log message is:

```
[11:50:40][C][sps30:068]:   Address: 0x69
[11:50:40][W][sps30:084]: Unable to request sensor firmware version
[11:50:40][C][sps30:094]:   Update Interval: 10.0s
[11:50:40][C][sps30:095]:   Serial Number: ''
```

When i start up Arduino and use an example sketch myself using this lib (https://github.com/paulvha/sps30) it works like a charm and the readings come in. So from a hardware perspective it looks good.

```
16:05:05.054 -> Trying to connect
16:05:05.054 -> Detected SPS30.
16:05:07.072 -> 	Serial number : 6B19E22CD975E11A
16:05:07.072 -> 	Product name  : 00080000
16:05:07.072 -> Firmware level: 1.0
16:05:07.072 -> Library level : 1.4
16:05:07.072 -> Detected SCD30
16:05:07.072 -> 	Serial number : 215165⸮
16:05:08.106 -> Measurement started
16:05:08.106 -> 
16:05:08.106 -> Hit <enter> to continue reading
16:05:10.114 -> Hit <enter> to continue reading
16:05:12.095 -> Hit <enter> to continue reading
16:05:14.101 -> ==================================== SPS30 ===================================== ========= SCD30 ==========
16:05:14.134 -> -------------Mass -----------    ------------- Number --------------   -Average- CO2   Humidity Temperature
16:05:14.134 ->      Concentration [μg/m3]             Concentration [#/cm3]             [μm]    [ppm]    [%]      [*C]
16:05:14.134 -> P1.0	P2.5	P4.0	P10	P0.5	P1.0	P2.5	P4.0	P10	PrtSize
16:05:14.134 -> 
16:05:14.134 -> 7.78	11.73	14.17	15.29	43.44	55.81	59.20	59.63	59.71	0.69	  1507	 45.6	  25.99
```
My knowledge about the libs / integration in ESP is limited, but the initialization looks a bit different init or checking for the S/N, etc. Because when I flash it manually it works, and when I flash it afterwards with ESPhome I get a different result:

During init I now get: 

```
[12:48:49][C][sps30:067]: sps30:
[12:48:49][C][sps30:068]:   Address: 0x69
[12:48:49][C][sps30:094]:   Update Interval: 10.0s
[12:48:49][C][sps30:095]:   Serial Number: '6B19E22CD975E11A'
```

During probing I nog get 

```
[12:46:45][D][sps30:105]: Trying to reconnect the sensor...
[12:46:45][D][sps30:116]: Sensor soft-reset failed. Is the sensor offline?
```

### Which version of ESPHome has the issue?

2021.11.1

### What type of installation are you using?

Home Assistant Add-on

### Which version of Home Assistant has the issue?

core-2021.11.4

### What platform are you using?

ESP8266

### Board

Lolin D1 Mini

### Component causing the issue

SPS30 sensor over I2C

### Example YAML snippet

```yaml
#----
# AirQual Meter sensor thingy

substitutions:
  device_name_friendly: 'AQ! Ceiling Overloop D1'
  device_name: 'aqi-overloop'
  wifi_fb_password: 'xxx'
  scd30_temp_offset: '5.7'
#No changes after here required.

esphome:
  name: ${device_name}
  platform: ESP8266
  board: d1_mini

wifi:
  ssid: !secret wifi_ssid_iot
  password: !secret wifi_password_iot
  fast_connect: true

  # Enable fallback hotspot (captive portal) in case wifi connection fails
  ap:
    ssid: '${device_name_friendly} Fallback'
    password: ${wifi_fb_password}

# captive_portal:

# Example configuration entry
debug:

# Logger must be at least debug (default)
logger:
  level: debug

#web_server:
#  port: 80

# Enable Home Assistant API
api:
  password: !secret esphome_local
  reboot_timeout: 300s
  encryption: 
    key: !secret esphome_api_key
  id: device_name

ota:
  password: !secret esphome_local

i2c:
  sda: D2
  scl: D1
  scan: True
  id: bus_a
  frequency: 100kHz

time:
  - platform: homeassistant
    id: homeassistant_time

sensor:
  - platform: scd30
    i2c_id: bus_a
    address: 0x61
    co2:
      name: '${device_name_friendly} CO2'
      accuracy_decimals: 1
    temperature:
      name: '${device_name_friendly} Temperature'
      id: scd30_temperature
      accuracy_decimals: 1
    humidity:
      name: '${device_name_friendly} Humidity'
      id: scd30_humidity
      accuracy_decimals: 1
    temperature_offset: ${scd30_temp_offset}
    update_interval: 10s
    altitude_compensation: 7m

  - platform: sgp30
    i2c_id: bus_a
    address: 0x58
    eco2:
      name: '${device_name_friendly} eCO2'
      accuracy_decimals: 1
    tvoc:
      name: '${device_name_friendly} TVOC'
      accuracy_decimals: 1
    update_interval: 10s
    compensation:
      temperature_source: scd30_temperature
      humidity_source: scd30_humidity

  - platform: sps30
    i2c_id: bus_a
    address: 0x69
    pm_1_0:
      name: '${device_name_friendly} <1µm Weight concentration'
    pm_2_5:
      name: '${device_name_friendly} <2.5µm Weight concentration'
    pm_4_0:
      name: '${device_name_friendly} <4µm Weight concentration'
    pm_10_0:
      name: '${device_name_friendly} <10µm Weight concentration'
    pmc_0_5:
      name: '${device_name_friendly} <0.5µm Number concentration'
    pmc_1_0:
      name: '${device_name_friendly} <1µm Number concentration'
    pmc_2_5:
      name: '${device_name_friendly} <2.5µm Number concentration'
    pmc_4_0:
      name: '${device_name_friendly} <4µm Number concentration'
    pmc_10_0:
      name: '${device_name_friendly} <10µm Number concentration'
    update_interval: 10s
```

### Anything in the logs that might be useful for us?

```txt
[11:50:40][C][sps30:068]:   Address: 0x69
[11:50:40][W][sps30:084]: Unable to request sensor firmware version
[11:50:40][C][sps30:094]:   Update Interval: 10.0s
[11:50:40][C][sps30:095]:   Serial Number: ''
```
```


### Additional information

_No response_

### PR DESCRIPTION
**Pull request by martgras**
# What does this implement/fix? 

move i2c scan from dump_config to setup.

Intermittently SPS30 fails to initialize.
In https://github.com/esphome/issues/issues/2735#issuecomment-979188757   the log shows that the i2c scan happens in between two ic2 operations of SPS 30 causing setup of the component to fail. 
IMHO the i2c scan should be completed before  running setup for i2c components

## Types of changes

- [ ] Bugfix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] Other

**Related issue or feature (if applicable):** fixes https://github.com/esphome/issues/issues/2735

**Pull request in [esphome-docs](https://github.com/esphome/esphome-docs) with documentation (if applicable):** esphome/esphome-docs#<esphome-docs PR number goes here>

## Test Environment

- [x] ESP32
- [x] ESP32 IDF
- [ ] ESP8266

## Example entry for `config.yaml`:

```yaml
# Example config.yaml

```

## Checklist:
  - [x] The code change is tested and works locally.
  - [ ] Tests have been added to verify that the new code works (under `tests/` folder).
  
If user exposed functionality or configuration variables are added/changed:
  - [ ] Documentation added/updated in [esphome-docs](https://github.com/esphome/esphome-docs).

### CODE REVIEW

File: esphome/components/i2c/i2c_bus_esp_idf.cpp [hunk 1]
```diff
@@ -55,21 +73,13 @@ void IDFI2CBus::dump_config() {
...
-    }
-    if (found == 0) {
+    ESP_LOGI(TAG, "i2c bus scan results...");
+    for (const auto &s : scan_results_)
+      ESP_LOGI(TAG, "%s", s.c_str());
+    if (scan_results_.empty())
       ESP_LOGI(TAG, "Found no i2c devices!");
-    }
+    // release memory
+    scan_results_ = std::vector<std::string>();
```
Comment (jesserockz) [inline esphome/components/i2c/i2c_bus_esp_idf.cpp]: I don't mind releasing the memory, but it means when you attach to the logs for a second, or subsequent times, it will say `Found no i2c devices`

Comment (martgras) [reply esphome/components/i2c/i2c_bus_esp_idf.cpp]: oh - didn't know that. 
changed it.

File: esphome/components/i2c/i2c_bus_arduino.cpp [hunk 2]
```diff
@@ -27,6 +28,23 @@ void ArduinoI2CBus::setup() {
...
+        ESP_LOGV(TAG, "Found i2c device at address 0x%02X", address);
+        scan_results_.push_back(str_sprintf("Found i2c device at address 0x%02X", address));
+        found++;
+      } else if (err == ERROR_UNKNOWN) {
+        ESP_LOGV(TAG, "Unknown error at address 0x%02X", address);
+        scan_results_.push_back(str_sprintf("Unknown error at address 0x%02X", address));
+      }
+    }
+    if (found == 0)
+      ESP_LOGI(TAG, "Found no i2c devices!");
```
Comment (oxan) [inline esphome/components/i2c/i2c_bus_arduino.cpp]: Why is this one at a higher verbosity than the other messages?

File: esphome/components/i2c/i2c_bus_arduino.h [hunk 3]
```diff
@@ -39,6 +39,7 @@ class ArduinoI2CBus : public I2CBus, public Component {
   uint8_t scl_pin_;
   uint32_t frequency_;
   bool initialized_ = false;
+  std::vector<std::string> scan_results_;
```
Comment (oxan) [inline esphome/components/i2c/i2c_bus_arduino.h]: Can we store just an (address, status) tuple, instead of the fully formatted string?

File: esphome/components/i2c/i2c_bus_esp_idf.cpp [hunk 4]
```diff
@@ -36,6 +37,23 @@ void IDFI2CBus::setup() {
...
+        scan_results_.push_back(str_sprintf("Found i2c device at address 0x%02X", address));
+        found++;
+      } else if (err == ERROR_UNKNOWN) {
+        scan_results_.push_back(str_sprintf("Unknown error at address 0x%02X", address));
+        ESP_LOGV(TAG, "Unknown error at address 0x%02X", address);
+      }
+    }
+    if (found == 0)
+      ESP_LOGD(TAG, "Found no i2c devices!");
+  }
```
Comment (oxan) [inline esphome/components/i2c/i2c_bus_esp_idf.cpp:44]: This logic seems to be identical between Arduino and ESP-IDF (except for differing log levels..), can we move it to the `I2CBus` parent class?

File: esphome/components/i2c/i2c_bus_arduino.cpp (hunk 2 above)
Comment (martgras) [reply esphome/components/i2c/i2c_bus_arduino.cpp]: fixed

File: esphome/components/i2c/i2c_bus_arduino.h (hunk 3 above)
Comment (martgras) [reply esphome/components/i2c/i2c_bus_arduino.h]: done

File: esphome/components/i2c/i2c_bus_esp_idf.cpp (hunk 4 above)
Comment (martgras) [reply esphome/components/i2c/i2c_bus_esp_idf.cpp:44]: good idea - done

File: esphome/components/i2c/i2c_bus.h [hunk 5]
```diff
@@ -40,6 +42,20 @@ class I2CBus {
...
+    for (uint8_t address = 8; address < 120; address++) {
+      auto err = writev(address, nullptr, 0);
+      if (err == ERROR_OK) {
+        scan_results_.emplace_back(true, address);
+      } else if (err == ERROR_UNKNOWN) {
+        scan_results_.emplace_back(false, address);
+      }
+    }
+  }
+  std::vector<std::pair<bool, int>> scan_results_;
```
Comment (oxan) [inline esphome/components/i2c/i2c_bus.h]: The address can (should) be a `uint8_t`, and swapping the address/status makes more sense, imo.

File: esphome/components/i2c/i2c_bus_arduino.cpp [hunk 6]
```diff
@@ -45,22 +50,20 @@ void ArduinoI2CBus::dump_config() {
...
-      auto err = writev(address, nullptr, 0);
-      if (err == ERROR_OK) {
-        ESP_LOGI(TAG, "Found i2c device at address 0x%02X", address);
-        found++;
-      } else if (err == ERROR_UNKNOWN) {
-        ESP_LOGI(TAG, "Unknown error at address 0x%02X", address);
-      }
-    }
-    if (found == 0) {
+    ESP_LOGI(TAG, "i2c bus scan results...");
```
Comment (oxan) [inline esphome/components/i2c/i2c_bus_arduino.cpp]: It's a bit awkward to start without a capital, and the `...` implies some action is being executed.
```suggestion
    ESP_LOGI(TAG, "Results from i2c bus scan:");
```

File: esphome/components/i2c/i2c_bus_arduino.h [hunk 7]
```diff
@@ -1,7 +1,6 @@
 #pragma once
 
 #ifdef USE_ARDUINO
-
```
Comment (oxan) [inline esphome/components/i2c/i2c_bus_arduino.h]: This blank line here helps readability, imo.

File: esphome/components/i2c/i2c_bus_esp_idf.cpp [hunk 8]
```diff
@@ -55,23 +60,20 @@ void IDFI2CBus::dump_config() {
...
-
-      if (err == ERROR_OK) {
-        ESP_LOGI(TAG, "Found i2c device at address 0x%02X", address);
-        found++;
-      } else if (err == ERROR_UNKNOWN) {
-        ESP_LOGI(TAG, "Unknown error at address 0x%02X", address);
-      }
-    }
-    if (found == 0) {
+    ESP_LOGI(TAG, "i2c bus scan results...");
```
Comment (oxan) [inline esphome/components/i2c/i2c_bus_esp_idf.cpp]:
```suggestion
    ESP_LOGI(TAG, "Results from i2c bus scan:");
```

File: esphome/components/i2c/i2c_bus_arduino.h (hunk 7 above)
Comment (martgras) [reply esphome/components/i2c/i2c_bus_arduino.h]: done

File: esphome/components/i2c/i2c_bus.h (hunk 5 above)
Comment (martgras) [reply esphome/components/i2c/i2c_bus.h]: done

**Review by oxan — APPROVED** [review]

**Review by jesserockz — APPROVED** [review]
